### ISSUE TITLE
Minicart redirects customer to homepage on firefox

### ISSUE THREAD

**Issue by CMoorhouse** [magento/magento2#9959] opened 2017-06-15 13:41 UTC
### Preconditions
1. Magento 2.1.5
2. php 7.0.17
3. Domain www.priceofbath.com
2. Browser not working correctly is firefox

Hi 

The details are:

### Steps to reproduce
1. Visit - https://www.priceofbath.com/squash/testing.html
2. Add a product to the basket/cart
3. The number of items now show in the minicart icon in the header
4. Selecting the minicart icon/number in a firefox browser redirects the customer to the homepage and not to checkout/cart

### Expected result
1. Selecting the minicart icon/number in the header should show the contents of the minicart in the minicart view and allow the customer to then go to checkout

### Actual result
1. Selecting the minicart icon/number in a firefox browser does not show the contents in the minicart view it instead redirects the customer to the homepage and not to checkout/cart
2. It works correctly in IE and chrome

I have tried swapping the theme back the default luma theme but the bug remains.
thank you.

**Comment by Andrii-Deineha** [comment] 2017-07-06 12:28
@CMoorhouse Hi, unfortunally, I can't reproduce the issue as you described it. May you please confirm if this problem is relevant on latest release version of Magento 2?

**Comment by CMoorhouse** [comment] 2017-07-06 13:10
I am using magneto 2.1.5

 

From www.priceofbath.com <http://www.priceofbath.com>  if you add product to the cart and then select the cart icon it redirects you to the homepage.

 

Caroline Moorhouse                 Director

 

Zealous Kite

taking your business to new heights

T: 01225 742913 | M: 07971 553134 | E:  <mailto:caroline@zealouskite.co.uk> caroline@zealouskite.co.uk

**Comment by Andrii-Deineha** [comment] 2017-07-07 07:58
@CMoorhouse If you need fix in version 2.1.5, please refer to the [Community Forums](https://community.magento.com/).  Can you  confirm if this problem is relevant on version 2.1.7? Thank

**Comment by korostii** [comment] 2017-07-10 08:29
Hi @CMoorhouse,

I guess what @Andrii-Deineha was trying to say is that 2.1.7 doesn't seem to have this issue, which means on of the following:
a) the issue is caused by a 3rd-party module or a misconfiguration, or there are some more (subtle, yet important) steps to it.
b) the issue was present on 2.1.5 but got fixed in the next revisions.

Could you please upgrade to 2.1.7 (preferably in a staging environment first) and double-check whether the issue issue will disappear? 
It might fix your issue altogether and it'll help to rule out whether it's a 2.1.5-only bug.

@Andrii-Deineha, could you please explain why do you expect the community forums to help with the issue? You got me completely puzzled by that part.

**Closed as completed** 2017-09-13 21:16 UTC
Labels: bug report, Progress: needs update, Fixed in 2.1.x, Issue: Format is valid
