### ISSUE TITLE
Send tracking INformatoin error on shipment mail

### ISSUE THREAD

**Issue by moazzama** [magento/magento2#30942] opened 2020-11-17 07:22 UTC
i have faced the issue when we click on (SEND TRACKING INFORMATION) THEN page is like a (on magento 2.3.5 p1 and magento 2.4.1)

1. Both in Production and Development Environment
2. go to order>shipment>click on SEND TRACKING INFORMATION
3.That is actual result

![Screenshot (57)](https://user-images.githubusercontent.com/68050583/99358574-8c2c8000-28cf-11eb-94c5-a9aca646fdbf.png)

**Comment by engcom-Alfa** [comment] 2020-11-27 19:53
Hi @moazzama .
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Actual Result:** :heavy_check_mark: On Developer and Production mode 

![Peek 2020-11-27 21-43](https://user-images.githubusercontent.com/51679138/100480764-e06b0780-30fa-11eb-8b3c-a8150399bbed.gif)

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-27 19:53 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5-p1

**Comment by moazzama** [comment] 2020-11-27 20:40
I appreciate you that you are working on this issue
When i install new Magento 2.3.5 or 2.4.1 then you have to test the action
then error occurs so you should be test on newly install magento
Thanks
Moazzam Ali S

**Comment by code4** [comment] 2021-01-28 18:03
Hi,
I have a fresh installation of 2.4.1 and i am facing the same issue as described here.
