### ISSUE TITLE
Can not add option to simple product using REST 

### ISSUE THREAD

**Issue by zexperto** [magento/magento2#6209] opened 2016-08-17 18:58 UTC
### Preconditions

1.  Add Option to simple product in REST
### Steps to reproduce

1. Create Simple Product using REST or any another way.
2. If i want to add new option to the product using (REST) with POST method  i have this message [Unable to save product]. the same if i want to update the product using PUT method with new options
3. I tried to make some debug , then i have this error [Call to a member function getId() on a non-object] in this file [vendor/magento/module-catalog-inventory/Model/Plugin/AroundProductRepositorySave.php' on line 58"].
4. For example : i have two simple product (sku = simple1, sku = simple2).
5. I want to add option to product (sku = simple1), with this json using PUT method in REST
   {
   "option": {
     "product_sku": "simple1",
     "title": "Option Title",
     "type": "drop_down",
     "sort_order": 0,
     "is_require": true,
     "values": [
       {
         "title": "Value Title",
         "sort_order": 0,
         "price": null,
         "price_type": null,
         "sku": "simple2",
         "option_type_id": 2
       }
     ]
   }
   }
6. End point [/V1/products/options] , method = POST
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

**Comment by palamar** [comment] 2016-08-18 17:13
Thanks for the reporting.
Please provide a version of Magento (e.g.,. 2.0.0, 2.1.0) that has a problem.

**Comment by zexperto** [comment] 2016-08-18 18:09
Hi,
I am working on 2.0.9

**Comment by sevos1984** [comment] 2016-09-05 12:08
I have tried your payload and had an error that price and price_type can't be null. With correct values it works. Here is my payload  

> {
> "option" :
>        {
>            "product_sku": "simple",
>            "title": "option",
>            "type": "drop_down",
>            "sort_order": 0,
>            "is_require": true,
>            "price": 10,
>            "price_type": "fixed",
>            "sku": "sku",
>            "max_characters": 152,
>            "values":
>            [
>                {
>                 "title": "Title",
>                 "sort_order": 0,
>                 "price": 0,
>                 "price_type": "fixed",
>                 "sku": "simple2",
>                 "option_type_id": 2
>                 }
>            ]
>        }
>     }

**Comment by sevos1984** [comment] 2016-09-26 12:12
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:12 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi
