### ISSUE TITLE
Default Magento Attribute is not saving

### ISSUE THREAD

**Issue by nilesh2jcommerce** [magento/magento2#9153] opened 2017-04-06 12:01 UTC
### Preconditions

1. Magento CE 2.1.4, PHP Version 7.0.14, MYSQL Version 5.6.31-77.0

### Steps to reproduce

1. In Admin Store >> Attributes >> Products use any default attribute of magento (e.g: status) and without doing anything simply click on save button.That time only Ajax screen loader will show and screen get lock. 

### Expected result

1. It should save that attribute on which clicked for save.

### Actual result

1. After click on save button screen get locked please check attached screenshot.
http://my.jetscreenshot.com/demo/20170406-8ovy-90kb

I also tried this patch :https://github.com/magento/magento2/commit/45ad72f562316e576438d1dcf45f64690510eab7

But after made changes run deploy clean cache.Then check it again while saving it re-direct to dashboard page.
So this patch also not working for me.

**Comment by nilesh2jcommerce** [comment] 2017-04-22 12:36
Please check this as i tired solution from here https://github.com/magento/magento2/commit/45ad72f562316e576438d1dcf45f64690510eab7

After using this patch it re-direct me on Dashboard page.

**Comment by Stas94** [comment] 2017-06-27 08:31
@nilesh2jcommerce We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by korostii** [comment] 2017-06-27 11:37
@nilesh2jcommerce I'd also check browser console (hit F12 to open it up) for errors on both the `Console` and `Network` tabs.
Please post a copy of trace or a screenshot of those (if any), as well.

**Comment by nilesh2jcommerce** [comment] 2017-06-27 12:20
@Stas94 

I am using Magento CE 2.1.4, PHP Version 7.0.14, MYSQL Version 5.6.31-77.0

Steps to reproduce

    In Admin Store >> Attributes >> Products use any Default Attribute of magento **(e.g: status)** and without doing anything simply click on save button.That time only Ajax screen loader will show and screen get locked please check attached screenshot.
![2017-06-27_17-37](https://user-images.githubusercontent.com/18118658/27587181-f317c148-5b60-11e7-8382-96328f288ba9.jpg)
![2017-06-27_17-48 2](https://user-images.githubusercontent.com/18118658/27587179-f3040c02-5b60-11e7-9693-f6d588fdf80e.jpg)
![2017-06-27_17-48](https://user-images.githubusercontent.com/18118658/27587180-f310aa8e-5b60-11e7-89b7-8d9bda477d07.jpg)


Please check all screenshot that will help you to getting issue in admin please let me know if you get fixes.

**Comment by veloraven** [comment] 2017-06-29 06:12
@nilesh2jcommerce thank you for your report.
We were able to reproduce this issue and we have internal ticket MAGETWO-69716 for it.

**Comment by magento-engcom-team** [comment] 2017-10-06 11:30
@nilesh2jcommerce, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-06 11:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Format is valid

**Comment by korostii** [comment] 2017-10-24 23:58
Hi @magento-engcom-team, 
If the description is correct, this seems to be a quite critical bug.

I assume it's still present on 2.1 branch - is that correct?
If so, please consider adding this bug as a known issue to the release notes of 2.1 branch and\or providing a timeline (or a milestone) for its planned resolution in 2.1 branch.
