### ISSUE TITLE
Duplicate bundle product's child products issue.

### ISSUE THREAD

**Issue by kunj1988** [magento/magento2#14112] opened 2018-03-15 08:19 UTC
When we create duplicate bundle product from Ex. Sprite Yoga Companion Kit  > Sprite Yoga Companion Kit 1 and after duplication while we delete duplicate product(Ex. Sprite Yoga Companion Kit 1) from grid main product "(Ex. Sprite Yoga Companion Kit)" options also removed.  

### Preconditions

1. Magento version 2.2.1
2. Magento version 2.2.2
3. Magento version 2.2.3

### Steps to reproduce

1. First create new bundle product.
2. edit last created bundle product and click on save and duplicate.
3. Now go on product grid page and delete last duplicated product.
4. Open first main product, magento deleting main product's selected child.  

### Expected result

1. While creating duplicate product of bundle product magento should create new child options. 

### Actual result

1. ![sprite yoga companion kit products main product we will create duplicate product from this](https://user-images.githubusercontent.com/13017040/37510654-e92484c0-2921-11e8-8454-107bdc04e8fd.png)

2. ![sprite yoga companion kit before duplicate it](https://user-images.githubusercontent.com/13017040/37510659-e9cc6136-2921-11e8-850d-8fdad9bc379d.png)

3. ![sprite yoga companion kit product duplicate product](https://user-images.githubusercontent.com/13017040/37510658-e9a0c346-2921-11e8-9658-94955037b3dc.png)

4. ![sprite yoga companion kit duplicate products bundle item](https://user-images.githubusercontent.com/13017040/37510656-e976a2dc-2921-11e8-9e87-aa0e79e21025.png)

5. ![products inventory catalog delete duplicate product from grid](https://user-images.githubusercontent.com/13017040/37510655-e94ee210-2921-11e8-9a94-c8512cacfba3.png)

6. ![products inventory catalog deleted duplicate product](https://user-images.githubusercontent.com/13017040/37510653-e8fcd8c6-2921-11e8-8128-216240f41bbb.png)

7. ![sprite yoga companion kit products bundle item delete after delete duplicate product](https://user-images.githubusercontent.com/13017040/37510650-e8cfdbf0-2921-11e8-9484-50b2905206d7.png)

**Comment by paragpadsumbiya** [comment] 2018-03-15 09:59
@kunj1988  thank you for your report.
Please use the issue reporting guidelines to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:

Preconditions: Magento version
Steps to reproduce
Expected result
Actual result

Can you please provide detialed information so we can check this .

**Comment by magento-engcom-team** [comment] 2018-03-16 06:59
@kunj1988, thank you for your report. We've acknowledged the issue and added to our backlog.
[Please watch the video about how to reproduce this issue.](https://github.com/magento/magento2/files/1818187/Sprite.Yoga.Companion.Kit.webm.zip)

**Comment by KalaiarasanSeetharaman** [comment] 2018-05-19 10:09
I am working on it #dmcdindia

**Comment by kunj1988** [comment] 2018-05-23 05:45
Please review my commit, I have tried to resolve this issue.

**Resolved #14112 : Duplicate bundle product's child products issue.**

**Comment by magento-engcom-team** [comment] 2018-05-26 10:57
Hi @kunj1988 
Could you please submit a Pull Request to this repository with your fix? Thank you

**Comment by riccardougolini** [comment] 2018-06-09 09:33
#perugia

**Comment by magento-engcom-team** [comment] 2018-06-09 09:33
@riccardougolini thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by kunj1988** [comment] 2018-12-04 13:07
@magento-engcom-team Is this merged on Magento 2.2 and 2.3?

**Comment by magento-engcom-team** [comment] 2019-03-08 09:19
Hi @riccardougolini. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by riccardougolini** [comment] 2019-03-08 09:30
not reproducible for Magento 2.3 @magento-engcom-team

**Comment by GalichMolodothon** [comment] 2019-03-16 09:57
#kharkivcd19

**Comment by magento-engcom-team** [comment] 2019-03-16 09:57
@GalichMolodothon thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by GalichMolodothon** [comment] 2019-03-16 11:20
not reproducible for Magento 2.2 @magento-engcom-team

**Comment by magento-engcom-team** [comment] 2019-09-27 23:35
Hi @kunj1988. Thank you for your report. 
The issue has been fixed in magento/magento2#24703 by @hostep in 2.3-develop branch
Related commit(s):
 - [f1a187eba85b2eaeca4c619c1482ca8916fdb284](https://github.com/magento/magento2/commit/f1a187eba85b2eaeca4c619c1482ca8916fdb284)
 - [bf36defe362496ecb6f6b7693600a9054fbd801b](https://github.com/magento/magento2/commit/bf36defe362496ecb6f6b7693600a9054fbd801b)
 - [629fcdfc22c35ce0cc2f3732b54b9885e8b2b362](https://github.com/magento/magento2/commit/629fcdfc22c35ce0cc2f3732b54b9885e8b2b362)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-09-27 23:35 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Event: kharkivcd19

**Comment by YiffyToys** [comment] 2024-06-21 13:30
We can reproduce this issue again in 2.4.7-p1. There seems to be a refression.
However there is no need for deletion to reproduce it.
After duplication and doing any edits on the duplicated product, all bundled options of the original product are empty.

**Comment by hostep** [comment] 2024-06-27 14:03
@YiffyToys: this is a really old issue, it's probably a better idea to open a new one and if you think this one is relevant, link to it from the new one.
