### ISSUE TITLE
Adding 2 million coupons to a cart discount rule breaks the Admin UI

### ISSUE THREAD

**Issue by justinwatkins** [magento/magento2#28712] opened 2020-06-12 17:27 UTC
### Preconditions (*)

1. 2.3.4

### Steps to reproduce (*)

1. Create a cart price rule, set any condition, it's not relevant.  Setup to use dynamic coupon codes
2. Generate 2 million coupon codes using the Admin UI
3. Wait approximately 2 hours for the background process to complete

### Expected result (*)

1. The UI loads fine and you can page through the 2 million discount coupons

### Actual result (*)

1. The entire page is not functional.  Not just the discount coupons at the bottom, you can not see or edit any properties of the cart discount rule.  The screen is broken.
2. Warning: DOMDocumentFragment::appendXML(): Entity: line 1: parser error : internal error: Huge input lookup in /var/www/html/magento/vendor/magento/framework/View/TemplateEngine/Xhtml/Template.php on line 60

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by justinwatkins** [comment] 2020-06-12 17:28
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-12 17:28
Hi @justinwatkins. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-12 17:30
Hi @justinwatkins, here is your [Magento instance](https://i-28712-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28712-2-4-develop.instances.magento-community.engineering/admin_60de](https://i-28712-2-4-develop.instances.magento-community.engineering/admin_60de)
Login: `6aafee74` Password: `a50f482b9df9`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Lima** [comment] 2020-07-04 01:05
Hello @justinwatkins 
I am not able to reproduce this issue on the latest 2.4-develop branch by provided steps.
**Testing scenario:**

**Steps to reproduce:**

1. Create a cart price rule, set any condition, it's not relevant. 
2. Save the rule
3. Open for editing this price rule
4. Setup to use dynamic coupon codes
5. Generate 2 million coupon codes using the Admin UI
6. Wait approximately 6 hours for the background process to complete

Result:
The UI loads fine and you can page through the 2 million discount coupons
![Peek 2020-07-04 03-58](https://user-images.githubusercontent.com/60198022/86502396-5c129380-bdab-11ea-9580-875767acb847.gif)

So I close it.
Thanks for your report!

**Closed as completed by engcom-Lima** 2020-07-04 01:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.4
