### ISSUE TITLE
Magento 2.1.3 Store View Configuration Issue.

### ISSUE THREAD

**Issue by magekey** [magento/magento2#8439] opened 2017-02-06 20:51 UTC
### Preconditions

1.  Install Magento 2.1.3 from archive release.

### Steps to reproduce

1. Go to Admin.
2. Stores -> Configuration > [Any Tab]  
3. Example with General > Store Email Addresses > General Contact section.
**Sender Name** field
Store View:  **Default**. Update to "Owner1"
Select Store View: **Main Website**. Update to "Owner2"
Select Store View: **Default Store View**: value is "Owner1"

Magento 2.1.2 works correct

### Expected result

In  **Default Store View** Sender Name value should be "Owner2" from website scope

**Comment by hostep** [comment] 2017-02-06 22:01
This is a new bug introduced in 2.1.3 and has been reported multiple times, see: https://github.com/magento/magento2/issues/7943

**Comment by naydav** [comment] 2017-02-07 09:17
Hi
Internal ticket MAGETWO-62648, which tracks this GitHub issue, is in our issue backlog.
I’m closing this issue because it is a duplicate of #7943. Please reopen this issue as needed.
Thanks

**Closed as completed** 2017-02-07 09:17 UTC
