### ISSUE TITLE
URL Rewriting Issues in Magento 2.1.1

### ISSUE THREAD

**Issue by jtw372** [magento/magento2#6685] opened 2016-09-21 06:29 UTC
the .html suffix is being added to product urls twice, domain.com/widget-a.html.html.  In addition to this , when changing the product key for a product, a URL is not being rewritten.  

Category URLs show the system URLs for categories and product pages.  However, if I simply edit the parent category page and save it, all the URLs in that category page works follows the format I want (rewritten URL)
### Preconditions
1.  Magento 2.1.1
2.  Ubuntu 16.04.1 x64 - Nginx in front of Apache. PHP-FPM 7.0 and MySQL
3.  Orson Theme, custom modules loaded with theme
4.  Product were successfully loaded into the site using the product called "Store Manager", using their "PHP MySQL bridge connection.
5.  SEO Settings Configured:Search Engine Optimization
6. Configuration - Web - URL settings: Use Web Server Rewrites
7. Configuration - Catalog - Search Engine Optimization:
   --Product URL Suffix: "use system values" .html
   --Category URL suffix: I have this field blank
   6.. I flush the cache and manually reindex
### Steps to reproduce
1.  Products and categories are loaded into the store using the Store Manager.  Category pages show the none rewritten, system generated url, even through the correct url key shows in the seo settings for the product.
2.  Click to edit a category and save it, URL with correct key works after a flush and reindex
3.  Click a product and the URL shows the double suffix.  Remove product url suffix in "Search Engine Optimization" and now when the url loads, it only has a single suffix
### Expected result
1.  Product URL should look like this
   domain.com/product-url.htm
2. Category URL should look like this
   domain.com/category/sub-category

**Comment by sevos1984** [comment] 2016-10-03 12:19
This looks like Store Manager issue as you can't set suffix for product explicitly on product page.

**Comment by jtw372** [comment] 2016-10-03 12:32
I would have thought that as well, however, after a brand new, fresh install w/o using Store Manager, I have the same problem.  I imported using a csv file on the newest import.

**Comment by sevos1984** [comment] 2016-10-04 09:45
Can you describe exact steps to reproduce issue on clean magento using csv import/export?

**Comment by sevos1984** [comment] 2016-10-19 09:26
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-19 09:26 UTC
Labels: bug report, Progress: needs update, Component: CatalogUrlRewrite
