### ISSUE TITLE
when upgrade magento version 2.3.4-p1 to 2.4.6-p1 then its give error

### ISSUE THREAD

**Issue by nishthaparmar26** [magento/magento2#37819] opened 2023-08-01 06:33 UTC
### Preconditions and environment

Magento Version 2.4.6-p1

![update_error1](https://github.com/magento/magento2/assets/137600994/b41876d8-9ade-47e5-b522-125711af4512)

### Steps to reproduce

updating magento version 

### Expected result

its give me error

### Actual result

![update_error1](https://github.com/magento/magento2/assets/137600994/15caf8f6-c0db-4838-b976-3d184fa8c1c3)

### Additional information

please help me to solve this issue

### Release note

this error appearing after updating magento version

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-08-01 08:48
This has been reported a couple of times before:
- https://github.com/magento/magento2/issues/35474
- https://github.com/magento/magento2/issues/35419
- https://github.com/magento/magento2/issues/36547

To me it doesn't sound like a bug in Magento, but as a missing php extension `sodium` that's not installed on your machine (maybe only for php-cli?).

**Comment by nishthaparmar26** [comment] 2023-08-01 10:18
thank you for your replay 
but i have enable sodium extension in wamp server and this extension show in phpinfo file
but still gating this error

**Comment by engcom-Dash** [comment] 2023-08-01 10:55
Hi @nishthaparmar26 ,

Thanks @hostep for given inputs.
Seems like the [Error](https://user-images.githubusercontent.com/137600994/257425624-15caf8f6-c0db-4838-b976-3d184fa8c1c3.png) occurs due to Sodium PHP extension Missing in your system,Kindly recheck with following mentioned comments .
Kindly go through with this [37454](https://github.com/magento/magento2/issues/35474#issuecomment-1206388931) and If you any clarifications,Kindly Let us know.

Regards!

**Comment by nishthaparmar26** [comment] 2023-08-01 11:46
Thank you sir 
but still geting error please help me

**Comment by hostep** [comment] 2023-08-01 12:04
Make sure sodium is also enabled for php on the command line, usually the command line uses separate `php.ini` file(s).

**Comment by nishthaparmar26** [comment] 2023-08-01 12:50
yes sir in my system sodium extension is enable

**Comment by hostep** [comment] 2023-08-01 12:54
Then I'm afraid you'll need to try to figure it out yourself, this is an environmental problem, not a bug in Magento, sorry! So this issue can be closed in my opinion.

**Comment by nishthaparmar26** [comment] 2023-08-01 13:29
okay thank you

**Comment by engcom-Dash** [comment] 2023-08-02 09:08
Hi @nishthaparmar26 ,

Seams like issue is not from core magento and its environmental issue,Hence we are closing this issue.Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!

**Closed as completed by engcom-Dash** 2023-08-02 09:08 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
