### ISSUE TITLE
Magento using regular price instead of the special price when calculation tier price type discount

### ISSUE THREAD

**Issue by mohammedTBB** [magento/magento2#39167] opened 2024-09-13 10:57 UTC
### Preconditions and environment

- Magento version 2.4.6-p4
- Php: 8.1

### Steps to reproduce

1- Create a simple producto
2- add a special price lower than the regular price
3- add a tier price Discount
4- check the product in the frontend

Example:
product: 24-MB01
regular price: 255.36
special price: 202.84
**Customer group price (tier price)** Quantity: 2 , Price: Discount 25%

### Expected result

Special price should be used to calculate the tier price and the final price.

Example: 
Sepcial price - tier price discount =  final price
202.84 - 25% = 152,13$

### Actual result

Regular price is ued to calculate the tier price and the final price.

Example:
Regular price - tier price discount =  final price
255.36 - 25% = 191,52$

![image](https://github.com/user-attachments/assets/a5cbe02b-24e8-4a54-92bc-299522cf4e3e)

### Additional information

I think the tier price should be calculated based on the minimum price which in this case the special price. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-17 07:16
Hi @mohammedTBB,

Thanks for your reporting and collaboration.

As Per the Magento devdocs it looks like and expected behaviour of magento 

Final Price will calculated as below.Regular price = Base price which we have created for a product.

<img width="1437" alt="Screenshot 2024-09-17 at 11 54 35" src="https://github.com/user-attachments/assets/322d5149-75a3-4721-a390-1b221ec3e5d7">



Kindly let us know if we are missing anything.

Thanks.

**Comment by mohammedTBB** [comment] 2024-09-17 10:15
Hi @engcom-Bravo Based on the NOTE mentioned in the devdocs
`The final product price is calculated as the minimum relevant price`

Should not the tier price be calculated based on the special price and not the original price because it is the minimum price in this case?

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-18 09:33
Hi @mohammedTBB,

Thanks for your update.

As per the mentioned document final price will calculate based on the regular price(which we have created for the product) not on the special price and it is an expected behaviour of magento.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-30 05:48
Hi @mohammedTBB,


We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-09-30 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.6-p4
