### ISSUE TITLE
Display zero tax configuration does not work in case of multiple shipping methods on Cart page

### ISSUE THREAD

**Issue by pranayhbwsl** [magento/magento2#35561] opened 2022-06-01 05:40 UTC
### Preconditions and environment

- Magento version 2.4.2

### Steps to reproduce

1. Enable multiple delivery methods by navigating to Stores -> Configuration -> Sales -> Delivery Methods.
2. Set 'Display Zero Tax Subtotal' to 'No' by navigating to Stores -> Configuration -> Sales -> Tax -> Shopping Cart Display Settings.
3. Visit storefront without signing in, add a product to cart and check shopping cart. Zero tax  field is visible untill we chose a shipping method.

### Expected result

Tax field with value 0.00 should not be visible in cart totals before selecting shipping methods.

![Screenshot from 2022-06-01 10-53-33](https://user-images.githubusercontent.com/77313820/171335255-2d488c75-73db-4dfd-b160-98373517cc6b.png)

### Actual result

Tax field with value 0.00 is visible even before selecting shipping method.
![Screenshot from 2022-06-01 10-51-42](https://user-images.githubusercontent.com/77313820/171335135-07e9b238-babc-4a25-a028-047e53b94111.png)

### Additional information

This issue happens because of strict equals operator in ->  vendor/magento/module-tax/view/frontend/web/js/view/checkout/cart/totals/tax.js on line 24.

If we change it '==' the value '0.00' will also satisfy this condition and hide the tax field.

Same operator i.e., '==' is used in vendor/magento/module-tax/view/frontend/web/js/view/checkout/summary/tax.js for tax field zero value display check.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-01 12:45
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
tax:0 is displayed in shopping cart page if shipping method is not selected. After shipping method is selected in checkout page and navigated back to shopping cart page, tax:0 is not displayed.
![image](https://user-images.githubusercontent.com/60198231/171407474-25e94b59-b966-4297-8722-393668bfa32b.png)
![image](https://user-images.githubusercontent.com/60198231/171407509-c2aa4e29-2bad-4778-8856-ee3129fd46fd.png)

**Comment by mmezhensky** [comment] 2022-06-13 13:18
@magento I am working on this

**Comment by engcom-Lima** [comment] 2022-08-10 13:45
@magento give me 2.4-develop instance

**Comment by isxam** [comment] 2022-09-08 08:10
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-09-14 11:16
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3201 by the internal team
Related commits: https://github.com/search?q=AC-3201&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-09-14 11:16 UTC
Labels: Component: Tax, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.2, Area: Cart & Checkout, Area: Tax
