### ISSUE TITLE
Configuring Login as Customer Settings > Enable Extension > No, causes console error on customer register.

### ISSUE THREAD

**Issue by victortodoran** [magento/magento2#31088] opened 2020-11-28 17:45 UTC
### Preconditions (*)

1. Magento 2.4.1 and 2.4-develop

### Steps to reproduce (*)

1. Ensure following configuration Stores > Configuration > Customers > Login as Customer Settings > Enable Extension is set to No
2. Go to customer/account/create
3. Without entering any values in the form, submit it.

### Expected result (*)

1. Validation kicks in. Form is not submitted. Request does not go through. No console error.

### Actual result (*)

1. Console error present.

### Additional info from Engcom
The issue is reproducible on Magento 2.4.1 composer and 2.4-develop versions
![consoele_errorpng](https://user-images.githubusercontent.com/51680745/100628367-d03c6d80-3330-11eb-82db-bd9a3949afb1.png)

The console error is not reproducible when the extension is Enabled
![enable_yes](https://user-images.githubusercontent.com/51680745/100628510-f4984a00-3330-11eb-81f4-ff20a5d9cf03.png)

**Comment by victortodoran** [comment] 2020-11-28 17:46
@magento give me 2.4-develop instance

**Comment by victortodoran** [comment] 2020-11-28 19:29
For reasons I don't have time to check upon on Commerce this is causing the request to go through.

**Comment by ajijshekh123** [comment] 2020-11-30 04:46
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-11-30 05:15
Hi @victortodoran,
I have verified this issue on the latest Magento 2.4 Instance with the above steps of reproduce, actual result and expected result. 
I have found errors in the console section and Only a single error displayed in the Create an account section.
See attached the screenshot:

![CreateCustomer](https://user-images.githubusercontent.com/24711761/100571444-268dba00-32f9-11eb-860e-923106e16056.jpg)

![CreateCustomer](https://user-images.githubusercontent.com/24711761/100571448-28f01400-32f9-11eb-9097-be95f1ce2db4.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-11-30 05:19
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39479` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by victortodoran** [comment] 2020-11-30 08:27
@ajijshekh123 So the message "The password bla bla" shows that the request went through and the backend validation kicked in.
The request MUST NOT go through if the form is empty, FE validation MUST prevent the request from going through.

**Comment by engcom-Bravo** [comment] 2020-11-30 15:26
Hello @vicobohdan 

Thank you for your report

We confirm that the issue is reproducible on 2.4.1 and on the latest 2.4-develop.
We also Confirm that the Console error is **not reproducible when the Extension is Enabled**

Additional info from Engcom is added to the description

**Comment by magento-engcom-team** [comment] 2020-11-30 15:27
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39479` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by basvanpoppel** [comment] 2021-01-29 13:25
As far as i see (and tested) this was fixed here: https://github.com/magento/magento2/commit/69c26af51b38754144eedf1ad73b44e479f4f29a

**Comment by victortodoran** [comment] 2021-01-30 20:03
The fix looks legit.

**Comment by engcom-Bravo** [comment] 2024-07-02 05:53
Hi @victortodoran,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1430" alt="Screenshot 2024-07-02 at 11 21 40" src="https://github.com/magento/magento2/assets/51680745/0aac879e-4778-46e2-b5c8-4d648459a204">



There is no console error.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-02 05:53 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Component: Admin, Component: Console, Reproduced on 2.4.x, Priority: P3, Severity: S3, Component: LoginAsCustomer, Progress: done, Issue: ready for confirmation, Reported on 2.4.1
