### ISSUE TITLE
JS error on product page Cannot read property 'oldPrice' of undefined

### ISSUE THREAD

**Issue by katesuykovskaya** [magento/magento2#7959] opened 2016-12-26 08:46 UTC
### Preconditions

1. M 2.1.3

### Steps to reproduce

1. Create conf. product on 2 swatch attributes (for ex. color and size) with assigned simple products
2. upload gallery to first simple product (will be needed to test gallery reload)
3. go to product page, click on 1st swatch

### Expected result

1. gallery of first simple product should be loaded

### Actual result

1. JS error
Trace:
swatch-renderer.js:694 Uncaught TypeError: Cannot read property 'oldPrice' of undefined
    at $.(anonymous function).(anonymous function)._UpdatePrice (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:694:23)
    at $.(anonymous function).(anonymous function)._UpdatePrice (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/jquery/jquery-ui.js:402:25)
    at $.(anonymous function).(anonymous function)._OnClick (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:532:25)
    at $.(anonymous function).(anonymous function)._OnClick (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/jquery/jquery-ui.js:402:25)
    at HTMLDivElement.<anonymous> (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/Magento_Swatches/js/swatch-renderer.js:482:32)
    at HTMLDivElement.dispatch (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/jquery.js:4624:9)
    at HTMLDivElement.elemData.handle (http://magento213.loc/pub/static/version1482569607/frontend/Magento/luma/en_US/jquery.js:4292:28)
![image](https://cloud.githubusercontent.com/assets/10142848/21478695/7cbda606-cb56-11e6-8eb2-dac3aecfb070.png)
2. Notes:
2.1. if I click on next swatch (color), error is not occurred (in other words when all options/swatches are chosen)
2.2. there was no such error on 2.1.2

**Comment by ashsmith** [comment] 2017-01-11 13:09
I'm also getting this after upgrading a client from 2.1.2 to 2.1.3.

From playing around a light bit of debugging, I've found the following lines were introduced in 2.1.3, and is where the error comes from. `result` is undefined when these lines are executed.

    if (result.oldPrice.amount !== result.finalPrice.amount) {
        $(this.options.slyOldPriceSelector).show();
    } else {
        $(this.options.slyOldPriceSelector).hide();
    }

Taking a look a what `result` is:

    result = $widget.options.jsonConfig.optionPrices[_.findKey($widget.options.jsonConfig.index, options)];

Now, the reason why this returns `undefined` is because none of the `options` match `$widget.options.jsonConfig.index`. This is because (in my case) there was one option not yet selected. `options` looks like this: `{187: undefined, 191: "1443"}`. Whereas, it is expected for both items to have values.

My (current) solution, to get around this, is to override in the theme, and abort before code mentioned above is executed. Which looks like this:

    if (!result) {
        return;
    }
    
    if (result.oldPrice.amount !== result.finalPrice.amount) {
        $(this.options.slyOldPriceSelector).show();
    } else {
        $(this.options.slyOldPriceSelector).hide();
    }

Of course, this means the state of `this.options.slyOldPriceSelector` is never changed, which in my use case, as it stands is fine.

This is specific commit, which includes links to the github tickets it was resolving: https://github.com/magento/magento2/commit/eb2ec29a03e2d7cb6adde7c0c01efa06d9b53d47

**Comment by ghost** [comment] 2017-01-15 01:00
@ashsmith workaround did the job for me.

**Comment by petterkj** [comment] 2017-02-08 15:33
Confirmed. 2.1.4. 

2 user selectable attributes. 

In my case, Color (swatch) size (dropdown). 

If you only select swatch, JS error (and product image does not change)...

BUT if you select dropdown AND then swatch, no JS error.. And it changes product image..

Tested in environment: production.

**Comment by mcspronko** [comment] 2017-03-02 17:09
Can't reproduce on current magento:develop branch.

**Comment by mpont91** [comment] 2017-03-04 00:27
Installed a fresh magento 2.1.5 via bitnami VM magento stack, with sample data:

![capture](https://cloud.githubusercontent.com/assets/8566701/23573886/a3e99d4a-0079-11e7-9079-f04a2d0c004a.PNG)

**Comment by martynshanks** [comment] 2017-03-14 09:45
Same issue Magento 2.1.5 download from Github

![screen shot 2017-03-14 at 09 45 16](https://cloud.githubusercontent.com/assets/19185251/23894689/ff324e4e-089a-11e7-9cf8-1a47028f671c.png)

adding the code snippet about worked for me too
/vendor/magento/module-swatches/view/frontend/web/js (line 714)

`            if (!result) {
                return;
            }

            if (result.oldPrice.amount !== result.finalPrice.amount) {
                $(this.options.slyOldPriceSelector).show();
            } else {
                $(this.options.slyOldPriceSelector).hide();
            }`

**Comment by thdoan** [comment] 2017-04-03 03:36
We just upgraded to v2.1.5 and can still reproduce this issue.

**Comment by refaelgold** [comment] 2017-04-03 09:41
Same here 👎

**Comment by blizam** [comment] 2017-04-10 22:37
same issue... just posting so I can watch this issue

Also, this is ALWAYS an issue in Configurable products where no attribute can be defaulted thus all options have no values on page load

**Comment by thdoan** [comment] 2017-04-17 11:13
Another quick fix:

            if (result && result.oldPrice.amount !== result.finalPrice.amount) {
                $(this.options.slyOldPriceSelector).show();
            } else {
                $(this.options.slyOldPriceSelector).hide();
            }

**Comment by blizam** [comment] 2017-04-18 01:49
I tested https://github.com/crantron/magento2/commit/a84852b057577a802067411ec5a4c967cfe24125 and the price is not updating as options are selected/even after all options are selected... I have both swatches and normal dropdown attributes on my configurable product

EDIT: it was a by-product of me moving the product.info.price element to a different area of the page... would by nice if the JS worked for changing the price regardless of where the price is rendered... though it does occur to me that form elements might not work so well outside the form :)

**Comment by LCIJJ** [comment] 2017-04-28 20:11
Confirming this issue still occurs on 2.1.6, environment: default.

Clicking color swatch doesn't update product image. It's not until after clicking the size, associated product image updates. Using Chrome developer console, JS error (Uncaught TypeError: Cannot read property 'oldPrice' of undefined) triggers each time a swatch is clicked. See screenshot for full error>>> https://www.screencast.com/t/fXpFIEo4

Posting to follow.

**Comment by vkranjith** [comment] 2017-05-03 10:28
Hi Magento Team,
I would like to work on it.

**Comment by dreamworkers** [comment] 2017-05-29 08:49
Hi, @OZZlE and I will work on it.

**Comment by dreamworkers** [comment] 2017-05-29 09:31
Fixed with: https://github.com/magento/magento2/commit/269c2154db82e2c3a19f8ba9a36e9b249a745998

**Comment by okorshenko** [comment] 2017-05-29 10:09
@dreamworkers thank you for research. Could you please apply the fix 269c215 (which was done for `develop` branch) for `2.1-develop` branch, verify it and create Pull Request to `2.1-develop` branch

Thank you

**Comment by ihor-sviziev** [comment] 2017-06-08 06:15
Looks like this issue was already fixed in develop & 2.1-develop branches. I think we need to close it.

**Comment by okorshenko** [comment] 2017-06-09 21:40
@ihor-sviziev thank you for your comment

**Closed as completed by okorshenko** 2017-06-09 21:40 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog

**Comment by magento-team** [comment] 2017-08-01 01:09
Internal ticket to track issue progress: MAGETWO-69541
