### ISSUE TITLE
Long time request execution

### ISSUE THREAD

**Issue by wassuupp** [magento/magento2#36276] opened 2022-10-12 08:34 UTC
### Preconditions and environment

- 2.4.5
- Make a request to bulk API with a lot of products in request. For instance 5k. <website_url>rest/async/bulk/V1/products.

### Steps to reproduce

- open client to work with Magento API
- fetch the token
- fill request body with huge amount of product. For instance > 5k
- create API request to the <website_url>rest/async/bulk/V1/products
- wait until request finishes

### Expected result

Have a quick response

### Actual result

Request duration is too long

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nuzil** [comment] 2022-10-12 09:19
Some performance metrics
<img width="1288" alt="Screenshot 2022-10-12 at 11 18 00" src="https://user-images.githubusercontent.com/1667889/195303648-68164766-c6c2-4e81-887b-0318c6da85e7.png">

**Comment by engcom-Bravo** [comment] 2022-12-21 14:00
Hi @wassuupp,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We have Instance with nearly 500K products.


<img width="1490" alt="Screenshot 2022-12-21 at 5 14 11 PM" src="https://user-images.githubusercontent.com/51680745/208922258-7be94146-1de0-48d9-97ae-5058e6e209d9.png">



We have created API request with 1000 products.we got response in `5.42 seconds`.



<img width="780" alt="Screenshot 2022-12-21 at 5 15 23 PM" src="https://user-images.githubusercontent.com/51680745/208922656-69444fdb-3c40-445a-bd64-5ef3b5591319.png">



<img width="810" alt="Screenshot 2022-12-21 at 5 15 16 PM" src="https://user-images.githubusercontent.com/51680745/208922678-cb9c2ad8-6004-4d3b-8900-5f50612e51bf.png">



<img width="912" alt="Screenshot 2022-12-21 at 5 14 44 PM" src="https://user-images.githubusercontent.com/51680745/208922708-6d36e74d-2311-446b-8652-aaf592bd18b9.png">




Kindly let us know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-02 06:10
Hi @wassuupp,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-02 06:10 UTC
Labels: Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.4.5
