### ISSUE TITLE
Refreshing statistic for Coupon report fails: Table 'm231_main.salesrule_coupon_aggregated' doesn't exist

### ISSUE THREAD

**Issue by pavdan** [magento/magento2#23362] opened 2019-06-21 15:26 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. In admin panel open `Reports > Refresh Statistic`
2. Click checkbox near **Coupons** row
3. Click `Refresh Statistics for the Last Day` and `Submit`

### Expected result (*)

1. Report is updated

### Actual result (*)

1. Error message: `We can't refresh recent statistics.`

Problem is caused by SQL exception: `Base table or view not found: 1146 Table 'm231_main.salesrule_coupon_aggregated' doesn't exist`. Because models try to use wrong connection (`default` or strange `salesrule` instead of `sales`). I attach patch that fixes problem
[fix_statistic_reports_coupon_aggregation.patch.txt](https://github.com/magento/magento2/files/3315087/fix_statistic_reports_coupon_aggregation.patch.txt)

**Comment by engcom-Bravo** [comment] 2019-06-21 15:44
Hello @pavdan. We've been not able to reproduce Your issue on the latest 2.3-develop version instance. Could You please try to reproduce it Yourself asking a bot for an instance as You are advised above:
![Advised](https://user-images.githubusercontent.com/51680745/59934609-9a653b00-9454-11e9-9958-f3e2263bb210.png)
Thank You.

**Comment by pavdan** [comment] 2019-06-24 07:27
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-24 07:27
Hi @pavdan. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-24 07:28
Hi @pavdan, here is your [Magento instance](https://i-23362-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23362-2-3-develop.instances.magento-community.engineering/admin](https://i-23362-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pavdan** [comment] 2019-06-24 08:25
I couldn't reproduce, but I'm sure it's caused by
vendor/magento/module-reports/Model/ResourceModel/Report/AbstractReport.php:182
`$this->getConnection()->delete($table, $deleteCondition);`

**Comment by engcom-Bravo** [comment] 2019-06-24 11:41
Thanks for Your reply, @pavdan. If You are not able to reproduce the issue on a vanilla instance it means that most likely Your issue has alresdy been fixed or has been caused by some not native code. We are suuposed to close an issue in such cases. You can see it in details to point 4 of our [workflow](https://github.com/magento/magento2/issues/23362#issuecomment-504471989)
So we are closing the issue. If You find a way to reproduce it on a clear instance of the latest develop version please feel free to reopen it.

**Closed as completed by engcom-Bravo** 2019-06-24 11:41 UTC
Labels: Progress: needs update, Issue: Format is valid
