### ISSUE TITLE
Magento unable to recover automatically after DB transaction failure

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#29916] opened 2020-09-04 20:45 UTC
### Preconditions (*)
- Magento 2.4
- Production setup

### Steps to reproduce (*)
1. Register Customer
2. Add default Shipping Address and Default Billing Address for Customer
3. Delete the `customer_address_entity` entries for above addresses
4. Try to place an order.

### Expected result (*)
1. The client should choose the Default Shipping  / Billing Address again

### Actual result (*)
1. An error does not let Client proceed.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2020-09-08 09:19
Hi @lbajsarowicz , I couldn't reproduce this issue on the latest 2.4-develop branch of Magento. I followed steps you described in the ticket:

Precondition:  
1. Clean install Magento 2.4-develop
2. Set Magento into production mode
Steps:
1. Register Customer
2. Add default Shipping Address and Default Billing Address for Customer
3. Delete the `customer_address_entity` entries for above addresses from DB
4. Try to place an order.
Actual result:
 I placed order without any errors, during checkout i was prompted to fill-in new Shipping  / Billing Address. 

Therefore i'm closing this ticket, if you have any additional details how to reproduce it, fill free to reopen it

**Closed as completed by engcom-Oscar** 2020-09-08 09:19 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.4.0
