### ISSUE TITLE
Whitespace issues for related, cross and upsell grids

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#21541] opened 2019-03-01 12:21 UTC
Related to issue #20140. I believe only the category product grids were fixed in commit e1abd4a0274e241e7ef50fa0e5b43dd5530bafab

Problem is visible on related, cross sell and upsell product grids. The grid is wrapping prematurely and leaving huge whitespace on the right side of screen.

Problem on both desktop and mobile screen size.

Example product page:

![wrapbug1](https://user-images.githubusercontent.com/1741593/53637508-9f8f4780-3c23-11e9-8610-91bdc10f365a.PNG)

![wrapbug2](https://user-images.githubusercontent.com/1741593/53637518-a61dbf00-3c23-11e9-8c3b-dca3a27b48d5.PNG)

Desktop view:

![wrapbug3](https://user-images.githubusercontent.com/1741593/53637524-a9b14600-3c23-11e9-91e7-b9370aa10afd.PNG)

On shopping cart page:

![wrapbug4](https://user-images.githubusercontent.com/1741593/53637529-acac3680-3c23-11e9-87c5-c52ba382ef16.PNG)

### Preconditions (*)

1. Magento 2.3.0 CE
2. PHP 7.1
3. Nginx
4. Luma theme
5. Sample products

### Steps to reproduce (*)

1. Install Magento 2.3.0 via composer
2. Go into a product and add more related, cross sell and upsell products so the grid will wrap
3. Clear cache, go on frontend and check
4. Add product to cart, go view cart and check

### Expected result (*)

Product grid should fill the entire container and not wrap prematurely.

### Actual result (*)

Products wrapping too early.

**Comment by magento-engcom-team** [comment] 2019-03-01 12:21
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-01 12:58
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-03-01 13:01
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 13:02
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 13:02
Hi @krishprakash, here is your [Magento instance](https://i-21541-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21541-2-3-develop.instances.magento-community.engineering/admin](https://i-21541-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-03 12:57
Hi @Leandry. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Leandry** [comment] 2019-03-03 13:07
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-03 13:07
Hi @Leandry. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-03 13:07
Hi @Leandry, here is your [Magento instance](https://i-21541-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21541-2-2-develop.instances.magento-community.engineering/admin](https://i-21541-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leandry** [comment] 2019-03-03 13:59
The issue was not reproduced on the mobile device and on Magento 2.2. 
But on the desktop Magento 2.3, there was whitespace on the right side of the screen.
![2019-03-03_15-21-14](https://user-images.githubusercontent.com/9416636/53695938-5c230d80-3dca-11e9-83df-7d7b65bf9cbb.png)
![2019-03-03_15-22-44](https://user-images.githubusercontent.com/9416636/53696689-5f21fc00-3dd2-11e9-8374-09c3ac512e33.png)

Thank you!

**Comment by magento-engcom-team** [comment] 2019-03-03 14:02
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98523` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-16 13:28
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#21582 by @amol2jcommerce in 2.3-develop branch
Related commit(s):
 - [9ab463fda7bab8d58c791dd4ba07fe4ec8407943](https://github.com/magento/magento2/commit/9ab463fda7bab8d58c791dd4ba07fe4ec8407943)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-16 13:28 UTC
Labels: Issue: Ready for Work, Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Ui, Area: Design/Frontend
