### ISSUE TITLE
Product's photos doesn't load anymore after magento update 2.2.3 to 2.2.4

### ISSUE THREAD

**Issue by damien-lechopier** [magento/magento2#14993] opened 2018-05-04 10:46 UTC
### Preconditions
1. Magento v2.2.4 (after update from 2.2.3)
2. PHP 7.1
3 Theme Moza (CleverSoft)

### Steps to reproduce
1. Go on frontend on a product page with photo
2. Image doesn't load on the page
3. 

### Expected result
1. Photo must load

### Actual result
I check my firebug console and I see a javascript error on that file 
=> /www/lib/web/mage/apply/scripts.js

Error is => SyntaxError: JSON.parse: unexpected character at line 14 column 36 of the JSON data

Problem looks like to come from JS function getNodeData on the return JSON.parse(data);
If some values of the JSON object are null, the console return a JSON Syntax error.

Thanks for your help

**Comment by lingwooc** [comment] 2018-05-04 11:03
Have a look in the dev tools of your browser to see if you can find a failed json load. I suspect it's a 404 or a php error message or something. The trick is to find the json its trying to parse and see what it looks like. You might need to use the javascript debugger to find it.

This isn't a problem with images as such. It's a problem with the javascript execution chain being broken because it is ludicrously brittle. Ideally it would fail at whatever if twas trying to do but press on with everything that it can do.

For what it's worth I don't see this issue.

**Comment by lingwooc** [comment] 2018-05-04 11:09
duplicate of  #14977

**Comment by Krapulat** [comment] 2018-05-04 11:52
I have the same problem.

**Comment by magento-engcom-team** [comment] 2018-05-04 14:27
@damien-lechopier @lingwooc @Krapulat Please continue tracking under https://github.com/magento/magento2/issues/14977 reference. Closing this ticket as duplicate.

**Closed as completed by magento-engcom-team** 2018-05-04 14:27 UTC
Labels: Issue: Format is valid
