### ISSUE TITLE
Error while installing Magento from scratch if Locale Resolver is injected in cli command

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#21752] opened 2019-03-14 16:25 UTC
### Summary (*)
Tested on 2.3, but exactly same code exists in this file on 2.2-develop branch.
Method `getDefaultLocale` of `Magento\Framework\Locale\Resolver` checks configuration in `core_config_data`. The reason of it is that if this class or some other that have it injected in some parent (for example `Magento\Sales\Model\Order\Address\Validator`) is injected in constructor in Cli Command in some custom module, installation of Magento fails.

### Examples (*)

1. Add custom module with Cli Command in which `Magento\Sales\Model\Order\Address\Validator` is injected
2. Try to install Magento from scratch using Cli.
3. See following error: `Base table or view not found: 1146 Table 'database.store_website' doesn't exist, query was: SELECT `store_website`.* FROM `store_website`"`

### Proposed solution
This is fixed under #21693

**Comment by magento-engcom-team** [comment] 2019-03-14 16:25
Hi @Bartlomiejsz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Bartlomiejsz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Al3ks73** [comment] 2019-03-15 08:05
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-15 08:05
Hi @Al3ks73. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-15 08:05
Hi @Al3ks73, here is your [Magento instance](https://i-21752-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21752-2-3-develop.instances.magento-community.engineering/admin](https://i-21752-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-15 08:53
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-18 08:25
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98753`, `MAGETWO-98754` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-25 13:53
Hi @Bartlomiejsz. Thank you for your report. 
The issue has been fixed in magento/magento2#21693 by @Bartlomiejsz in 2.3-develop branch
Related commit(s):
 - [28b047ec570fce2752960668e5b4e6eda21593b4](https://github.com/magento/magento2/commit/28b047ec570fce2752960668e5b4e6eda21593b4)
 - [b92ffa24299d32b62d2a211aa7756d866ad13154](https://github.com/magento/magento2/commit/b92ffa24299d32b62d2a211aa7756d866ad13154)
 - [fda4377384169d385a04057e7edf2f1ac32bc5ec](https://github.com/magento/magento2/commit/fda4377384169d385a04057e7edf2f1ac32bc5ec)
 - [b2004c3f74f7cdd2654986f056f6ba8d8beaa5ee](https://github.com/magento/magento2/commit/b2004c3f74f7cdd2654986f056f6ba8d8beaa5ee)
 - [b86f981ad04f63c7ca8d2c3ca5f3b4abe999ca4d](https://github.com/magento/magento2/commit/b86f981ad04f63c7ca8d2c3ca5f3b4abe999ca4d)
 - [73d88aaeaa7da30c68608d7f048b7b88557e936d](https://github.com/magento/magento2/commit/73d88aaeaa7da30c68608d7f048b7b88557e936d)
 - [9c7fbfdc24380fc3174d313bcf5c12ca381e9313](https://github.com/magento/magento2/commit/9c7fbfdc24380fc3174d313bcf5c12ca381e9313)
 - [e09429f7cca09d91245c0999cb043e7845d4fa74](https://github.com/magento/magento2/commit/e09429f7cca09d91245c0999cb043e7845d4fa74)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-25 13:53 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
