### ISSUE TITLE
Allowed memory size error on deleting products (2.1.3)

### ISSUE THREAD

**Issue by am2008** [magento/magento2#7938] opened 2016-12-22 16:41 UTC
### Preconditions

1. Magento CE 2.1.3 is installed.
2. 9k products in catalog (118k records)

### Steps to reproduce

1. In Admin Panel navigate Products->Catalog
2. Select one product
3. Select "Delete" in Actions
4. Confirm action

### Expected result

A total of 1 record(s) have been deleted.

### Actual result

**@memory_limit 768M:**
After 10+ seconds:
HTTP ERROR 500
_PHP Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes..._

**@memory_limit 1G:**
After 10+ seconds:
HTTP ERROR 500
_PHP Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes..._

**@memory_limit 2G**
After 40+ seconds:
A total of 1 record(s) have been deleted.

---------
**Server:**
Intel® Core™ i7-4770 Quad-Core Haswell
32 GB RAM

**PHP Version:**
7.0.9

**Comment by kandy** [comment] 2016-12-27 14:09
We have internal issue for this MAGETWO-58876  (already fixed for 2.1.x) and will be delivered in one of next release

**Comment by ghost** [comment] 2017-01-05 15:29
I can also confirm this happens, no matter what the limit is up to 4GB in our case. Selecting one product to delete shouldn't require 4GB of memory.

**Comment by ghost** [comment] 2017-01-05 15:44
Just an FYI it appears to select every product???

[pid  2686] sendto(6, "\223\307\n\0\3SELECT `t_d`.`attribute_id`, `e`.`entity_id`, `t_d`.`value` AS `default_value`, `t_s`.`value` AS `store_value`, IF(t_s.value_id IS NULL, t_d.value, t_s.value) AS `value` FROM `catalog_product_entity_varchar` AS `t_d`\n INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = t_d.entity_id\n LEFT JOIN `catalog_product_entity_varchar` AS `t_s` ON t_s.attribute_id = t_d.attribute_id AND t_s.entity_id = t_d.entity_id AND t_s.store_id = 1 WHERE (e.entity_id IN (35733, 35734, 35735, 35736, 35737, 35738, 35739, 35740, 35741, 35742, 35743, 35744, 35745, 35746, 35747, 35748, 35749, 35750, 35751, 35752, 35753, 35754, 35755, 35756, 35757, 35758, 35759, 35760, 35761, 35762, 35763, 35764, 35765, 35766, 35767, 35768, 35769, 35770, 35771, 35772, 35773, 35774, 35775, 35776, 35777, 35778, 35779, 35780, 35781, 35782, 35783, 35784, 35785, 35786, 35787, 35788, 35789, 35790, 35791, 35792, 35793,

The ids above go on forever until it hits memory limit.

**Comment by kandy** [comment] 2017-01-08 14:47
FYI, This issue is already resolved in mainline. See MAGETWO-59555(bd9e1c8c99bb575fa689128c198e9604c80ec76d) for reference

**Comment by magento-engcom-team** [comment] 2017-10-03 10:30
@am2008, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-03 10:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue:  Cannot Reproduce, Issue: Format is valid
