### ISSUE TITLE
Shipping tax rounding error - off by 1 cent 

### ISSUE THREAD

**Issue by willtran** [magento/magento2#26599] opened 2020-01-31 05:27 UTC
### Preconditions (*)
1. Magento 2.4-develop
2. PHP 7.3

### Steps to reproduce (*)
1. Create a fixed price shipping - cost is unimportant, but the problem is found when shipping cost is $5 fixed
2. Create product that can be added to cart. Again price is not important but problem can be replicated if product price can be divided by $5
3. Create tax for product and shipping. When problem is found tax rate is set at 10% applied to both product and shipping

### Expected result (*)
1. Shipping is calculated correctly. Total shipping  = shipping price + shipping tax
2. For example: $5 shipping with 10% tax = 4.54 shipping price, 0.46 shipping tax
3. Refund shipping should go through successfully

### Actual result (*)
1. **Some** orders will have wrong shipping tax
2. Refund shipping will not be possible because the shipping price is recalculated. Magento will throw error, example: "Maximum shipping amount allowed to refund is: $4.99" (this is the result of shipping price $4.54 + 0.45) 
3. This issue only affect some orders, not all. Investigation show that the number of items / price of items in cart affect the shipping tax calculation

### Notes
Issue is with how Delta is calculated. Relevant discussion: https://magento.stackexchange.com/questions/15846/why-does-magento-store-a-rounding-delta-when-calculating-taxes
The problem is that the delta for products price is being used to calculate shipping tax. See module-tax/Model/Calculation/AbstractAggregateCalculator.php

**Comment by LiamKarlMitchell** [comment] 2020-05-12 05:43
Also experiencing this in 2.3.0

Flat Rate shipping set to 8.695652173913043 with a GST Tax of 1.15 expecting to see a final shipping cost of $10.00 but I see $10.1

8.695652173913043 * 1.15 should be $10.0.

On the Shipping Methods screen before the Review & Payments step of checkout the cost shows as 8.7
![image](https://user-images.githubusercontent.com/1968109/81642647-fa533e80-9477-11ea-94f6-5ba1536b7c41.png)

What it looks like on checkout.

![image](https://user-images.githubusercontent.com/1968109/81642630-ef98a980-9477-11ea-8b06-545ad6c0eac7.png)

This should also show including GST as well.

**Comment by engcom-Alfa** [comment] 2020-05-21 12:56
Hi @willtran .

Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.

**Preconditions:**
1. Simple product with the price -> 5$ for ex.;
2. Fixed shipping price -> 5 $ for ex.;

**Manual testing scenario:**
1. Go to **Admin -> Stores -> Configuration -> Sales -> Tax** and set like this:

![Screenshot from 2020-05-21 15-31-18](https://user-images.githubusercontent.com/51679138/82559372-34a79480-9b78-11ea-830f-a9f168705a86.png)
![Screenshot from 2020-05-21 15-31-42](https://user-images.githubusercontent.com/51679138/82559381-3709ee80-9b78-11ea-9bc5-5dc923d11f53.png)

2. Create tax for product and shipping ( Go to **Admin -> Stores -> Tax Rules** )
In my case I set **10%** tax

![Screenshot from 2020-05-21 15-34-46](https://user-images.githubusercontent.com/51679138/82559683-b992ae00-9b78-11ea-81e2-9ff188d734b2.png)
![Screenshot from 2020-05-21 15-34-55](https://user-images.githubusercontent.com/51679138/82559695-bdbecb80-9b78-11ea-87f9-ccb1e26cfaef.png)

3.  Go to **Admin -> Sales -> Orders -> Create New Order**
4. Add created before the product to Shopping Cart
![Screenshot from 2020-05-21 15-39-14](https://user-images.githubusercontent.com/51679138/82560023-489fc600-9b79-11ea-88c2-6b2f4e3ba516.png)
5. Select shipping method ( **5$**);
![Screenshot from 2020-05-21 15-40-03](https://user-images.githubusercontent.com/51679138/82560166-93b9d900-9b79-11ea-8fab-ba85478f3d98.png)

![Screenshot from 2020-05-21 15-40-35](https://user-images.githubusercontent.com/51679138/82560144-87ce1700-9b79-11ea-8256-ac7b068ec7b9.png)

:heavy_check_mark: For 5% shipping calculation looks like: $5 shipping with 10% tax = 4.54 shipping price, 0.46 shipping tax
![Screenshot from 2020-05-21 15-47-34](https://user-images.githubusercontent.com/51679138/82560696-9bc64880-9b7a-11ea-97ad-15a3acd75118.png)

6. Create Order;
7. Create Invoice;
8. Create Credit Memo (Refund)
![Screenshot from 2020-05-21 15-52-25](https://user-images.githubusercontent.com/51679138/82560950-168f6380-9b7b-11ea-8eb6-1c5541fef120.png)
9. Click on **Refund Offline**

**Actual Result:** :heavy_check_mark: Credit memo was successfully created

![Screenshot from 2020-05-21 15-54-00](https://user-images.githubusercontent.com/51679138/82561122-7c7beb00-9b7b-11ea-973a-9125ce8dad46.png)

@willtran Could you take a look?

Thanks!

**Comment by willtran** [comment] 2020-05-22 04:44
@engcom-Alfa  thanks for checking. I haven't test on 2.4. Have you play around with the number of qty and product prices?
This issue only happens to some small percentages of order because the delta calculated for product rounding were used for rounding shipping and only **sometimes** it is not correct (the delta becomes too small). I'm not that good at maths to reverse engineer the combination of qty / price and tax rate that would 100% result in the error.
However on principle does it make more senses for product tax calculation to have its own delta, and shipping to have its own? similar to the pull request https://github.com/magento/magento2/pull/26600 
I will try to replicate on 2.4 and let you know.

**Comment by LiamKarlMitchell** [comment] 2020-08-12 07:50
Ah sorry, my issue stems from somewhere else, currency round is used in the setPrice method and other places throughout the collection of rates which removes extra precision intended to be used.

<details>
  <summary>Spoiler warning</summary>
  
  The item->unit_price is 8.7 when I entered a decimal number with longer precision 8.695652173913043, I need at least 3 decimal places, even calling a setPrice(8.695) then getPrice() shows the wrong value of 8.7.

Magento\Quote\Model\Quote\Address\RateResult::setPrice calls a priceCurrency->round which is rounding to 2dp reducing the precision.

```php
$rate->setData('price', $this->priceCurrency->round($price));
```
  
</details>

**Comment by LiamKarlMitchell** [comment] 2020-11-19 04:55
I noticed the label was added recently Reported on 2.4.0,  is there any update on a fix for this when the cause is loss of precision in the setPrice method due to it rounding the value.

I don't think setting the value should round it, only round when displaying the values.

**Comment by LiamKarlMitchell** [comment] 2021-02-03 06:11
Bump.

**Comment by marvinhinz** [comment] 2021-04-20 14:11
Happens on 2.4.2

**Comment by engcom-Oscar** [comment] 2021-04-21 09:29
Hi @willtran !
I can confirm that tax calculation is not correct. Here my example with order with some different products with the same price, but taxes are different there. But I was not able to reproduce error for credit memo creation. Had you chance to check the issue if it reproducing for you on the Magento 2.4.2?
![Screenshot from 2021-04-21 12-28-49](https://user-images.githubusercontent.com/60198413/115531202-2f2d5f80-a29d-11eb-9885-2e4ef81b7cb9.png)

**Comment by amcguireweb** [comment] 2021-04-28 16:05
We are also experiencing this problem.

**Comment by stu11262020** [comment] 2021-05-31 23:14
For anyone getting this issue just create a patch from this PR https://github.com/magento/magento2/pull/26600

**Comment by willtran** [comment] 2021-05-31 23:16
For anyone getting this issue the fix in this PR has been working for us https://github.com/magento/magento2/pull/26600/files so it worth creating a patch file manually.

**Comment by engcom-Echo** [comment] 2021-06-01 06:43
Hi willtran ,

We are not able to re-produce the issue on 2.4-develop branch.
Requesting you,  kindly elaborate the steps to reproduce with screen shots.

Thanks

**Comment by engcom-Lima** [comment] 2021-06-22 13:33
Hi @willtran,
 
Hoping, your issue is resolved and also we did not get any response from you more than 14 days. Hence closing this ticket.

Please feel free to raise the new ticket or reopen the existing ticket. if you have any issue.

**Closed as completed by engcom-Lima** 2021-06-22 13:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.0

**Comment by homecoded** [comment] 2022-05-11 15:01
Hi there
I'm using Magento ver. 2.4.2-p1 and I believe there is something fundamentally wrong with the way tax is rounded in `Magento\Tax\Model\Calculation\AbstractCalculator`. The deltas used for the tax calculation change each time the method is called making it essentially a statefull method. The deltas may become so big that is creates serious rounding errors. 

I made some sample code demonstrating the problem using the `AbstractCalculator` class:

```
class TestCalculator extends \Magento\Tax\Model\Calculation\AbstractCalculator
{
    public function __construct(
        \Magento\Tax\Api\TaxClassManagementInterface         $taxClassService,
        \Magento\Tax\Api\Data\TaxDetailsItemInterfaceFactory $taxDetailsItemDataObjectFactory,
        \Magento\Tax\Api\Data\AppliedTaxInterfaceFactory     $appliedTaxDataObjectFactory,
        \Magento\Tax\Api\Data\AppliedTaxRateInterfaceFactory $appliedTaxRateDataObjectFactory,
        \Magento\Tax\Model\Calculation                       $calculationTool,
        \Magento\Tax\Model\Config                            $config,
                                                             $storeId = 1,
        \Magento\Framework\DataObject                        $addressRateRequest = null
    ) {
        parent::__construct(
            $taxClassService,
            $taxDetailsItemDataObjectFactory,
            $appliedTaxDataObjectFactory,
            $appliedTaxRateDataObjectFactory,
            $calculationTool,
            $config,
            $storeId,
            $addressRateRequest
        );
    }

    public function calculateWithTaxNotInPrice(\Magento\Tax\Api\Data\QuoteDetailsItemInterface $item, $quantity, $round = true) {}
    public function calculateWithTaxInPrice(\Magento\Tax\Api\Data\QuoteDetailsItemInterface $item, $quantity, $round = true) {}

    public function deltaRoundProxy($price, $rate, $direction, $type = self::KEY_REGULAR_DELTA_ROUNDING, $round = true)
    {
        return $this->deltaRound($price, $rate, $direction, $type, $round);
    }
}

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$rowBaseCalculator = $objectManager->get(TestCalculator::class);
$priceWithoutTax = 2.95 - (2.95 / 1.19); // 0.47100840336134
echo "<pre>";
for ($i = 0; $i < 15; $i++) {
    echo $i . ':' . $priceWithoutTax . " => " . $rowBaseCalculator->deltaRoundProxy($priceWithoutTax, "19", true) . PHP_EOL;
}
echo "</pre>";
```
(!) Please note that you may have to change the $storeId in the constructor.
(!) You can copy&paste this code at the end of your `pub/index.php` and check the output in the browser.

The output will be:

```
0:0.47100840336134 => 0.47
1:0.47100840336134 => 0.47
2:0.47100840336134 => 0.47
3:0.47100840336134 => 0.47
4:0.47100840336134 => 0.48
5:0.47100840336134 => 0.47
6:0.47100840336134 => 0.47
7:0.47100840336134 => 0.47
8:0.47100840336134 => 0.47
9:0.47100840336134 => 0.47
10:0.47100840336134 => 0.47
11:0.47100840336134 => 0.47
12:0.47100840336134 => 0.47
13:0.47100840336134 => 0.47
14:0.47100840336134 => 0.48
```
As you can see, the calculated tax amount alternates between 0.47 and 0.48. This means the method `deltaRound` returns different results depending on how often you call it. This cannot be right!

I am fairly sure that is is the root for most of the off-by-one errors we're seeing.

**Comment by Nuranto** [comment] 2023-10-16 11:54
I just got the error on 2.4.6-p2.
We have a lot of orders, and this is the first time it happens, so it must be a very rare case. However, I can confirm it's there :/

**Comment by apedicdev** [comment] 2024-10-07 15:06
@magento-engcom-team give me 2.4-develop instance

**Comment by apedicdev** [comment] 2024-10-17 13:54
This seems to be the expected way when Tax calculation based on Total is set. Setting it based on Row Total, will not use the increase `deltaRound` till the latest row trying to spread the loss over shipment
