### ISSUE TITLE
Shipping radios become disabled on initial page load

### ISSUE THREAD

**Issue by vovayatsyuk** [magento/magento2#5700] opened 2016-07-19 14:22 UTC
## Steps to reproduce
1. Install Magento CE 2.1.0
2. Add any product the the cart and proceed to checkout
3. Fill the Shipping address form with test values
4. Select Shipping method radio and click Next
5. Now return to the Shipping Information step and **refresh** the page in browser
## Expected result

One ajax request to `/estimate-shipping-methods` action and shipping radio should stay active.
## Actual result

There will be a two concurrent ajax requests to `/estimate-shipping-methods` action and shipping radios become disabled after second request.
## 

This happens each time you refresh the page, after the following fields where saved in quote:
- country
- zipcode
- region

**Comment by alena-marchenko** [comment] 2016-09-02 15:56
Hi @vovayatsyuk 

I was unable to reproduce this issue on the latest CE 2.1 version.
Please verify if the issue still persists.

**Comment by vovayatsyuk** [comment] 2016-09-06 11:11
Hi @alena-marchenko 

I'm not able to reproduce this bug too. Not sure what caused this behavior in past.

I think you can close the ticket.

**Comment by alena-marchenko** [comment] 2016-09-07 13:50
Hi @vovayatsyuk 
I am closing the issue.

**Closed as completed by alena-marchenko** 2016-09-07 13:50 UTC
Labels: bug report, Progress: needs update
