### ISSUE TITLE
Magento2 admin custom module throwing the error

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#8943] opened 2017-03-20 08:40 UTC
I created a custom module in magento2 for admin panel. Grid form is version fine. But When I tried to add/edit a record then its throwing the error like "Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving."

Magento version is 2.1.1.

I am unable to find any clue in logs. Please help! How can I resolve this issue?

**Comment by korostii** [comment] 2017-03-20 10:48
Seriously, there is an [answered question on stackexchange](http://magento.stackexchange.com/questions/95532/add-order-data-to-custom-template-on-admin-magento-2) very similar to yours. Please consider using search first. If your situation turns out to be different, posting your code along also speeds the help up.

In general, if you are looking for an advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for reporting the bugs inside Magento2 itself only.
The issues which cannot be consistently reproduced on a clean installation of Magento CE aren't likely to get resolved in here.

**Comment by baltechies** [comment] 2017-03-20 11:12
@korostii  Thank you for respond. I have requested the help in [Magento Stack Exchange](http://magento.stackexchange.com/).  and Link of my request is [http://magento.stackexchange.com/questions/165135/magento2-admin-custom-module-throwing-the-error](http://magento.stackexchange.com/questions/165135/magento2-admin-custom-module-throwing-the-error).

Main point is that magento2 not throwing the relevant error message to debug the issue.

**Comment by veloraven** [comment] 2017-06-27 11:14
@baltechies thank you for your feedback but I'm closing this issue.
If you want to report an issue p;ease create new GitHub issue and format it according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
When you are looking for help please refer to the forums specified above as GitHub issue tracker is intended for technical issues only.

**Closed as completed by veloraven** 2017-06-27 11:14 UTC
