### ISSUE TITLE
[2.3.3]The coupon applies to all products in the shopping cart, not the sku I specified.

### ISSUE THREAD

**Issue by akgitcom** [magento/magento2#28246] opened 2020-05-16 07:36 UTC
Hi all!

**Preconditions**
Magento 2.3.3

**Steps to reproduce**
Go to Marketing -> Cart Price Rules
Create a coupon code. The main issue to set 'SKU'  in the Conditions tab.
Add some products to the cart and go to cart page.
Try to apply coupon code.
Log in to my account.
Go to cart page and try to apply coupon code again.
The coupon applies to all products in the shopping cart, not the sku I specified

**Expected result**
Coupon applied to my designated SKU.

**Actual result**
When there are more than one item in the cart, the coupon is applied to all items.

Thanks,
ak

**Comment by akgitcom** [comment] 2020-05-16 09:19
2.3.5 can be reproduced
![001](https://user-images.githubusercontent.com/1925899/82116005-06514000-9799-11ea-8e71-5656821e8033.png)
![002](https://user-images.githubusercontent.com/1925899/82116008-081b0380-9799-11ea-9a09-5ee892062ae3.png)

**Comment by ajijshekh123** [comment] 2020-05-18 05:05
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-18 05:05
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-18 05:06
Hi @ajijshekh123, here is your [Magento instance](https://i-28246-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28246-2-4-develop.instances.magento-community.engineering/admin_ed67](https://i-28246-2-4-develop.instances.magento-community.engineering/admin_ed67)
Login: `8897247f` Password: `9b527b4aa7ab`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-05-18 06:30
Hello @akgitcom,
As per follow the Steps, Expected result and Actual result. I have reproduced this issue in the Default Magento 2.4 instance.
If I am creating the Cart rule to the specific SKU and Add different products on the cart and applied the coupon code, This coupon code discount is applied to all the products instead of specific SKU product. 

See attached the Screenshot:
![WithAppliedCoupoCode](https://user-images.githubusercontent.com/24711761/82180946-28fd6900-98ff-11ea-94c2-2f7c4f3b3053.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-05-18 06:32
@ajijshekh123 Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-05-18 07:33
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34369` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-18 21:04
Hello @akgitcom 
fyi: @ajijshekh123 

The issue seems as expected behavior or configuration issue

In general "Condition" section defines, like if the condition is TRUE = apply the rule for all cart items. 
But in the bottom of the "Actions" section, there is setting for condition  **Apply the rule only to cart items matching the following conditions (leave blank for all items).**
Use it to apply the rule only for a specific SKU.

Please see screen for more details
![issue_28246](https://user-images.githubusercontent.com/3409584/82259431-2ca1e780-9921-11ea-8652-e2adfbd05d08.png)


Please confirm that we can close the issue or provide additional details/preconditions/etc

**Comment by ajijshekh123** [comment] 2020-05-19 05:26
Okay @sdzhepa, I Will review it again this issue and update the comment.

**Comment by sdzhepa** [comment] 2020-07-14 21:59
It seems the issue is not actual anymore and was a reason of miss configuration.

**Closed as completed by sdzhepa** 2020-07-14 21:59 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, non-issue, Issue: Format is valid, Component: Rule, Reproduced on 2.4.x, Reported on 2.3.3
