### ISSUE TITLE
Product Images loosing inheritance scoping in multisite after storeview rest API PUT

### ISSUE THREAD

**Issue by eraq** [magento/magento2#35512] opened 2022-05-20 20:41 UTC
### Preconditions and environment

Magento 2.4.4, multisite with more than one store view. Occurs in cloud docker, as well as staging and product cloud environments.

### Steps to reproduce

1. have or create a product with a product image (image, thumbnail, small_image) assigned to default scope value
2. use the storeview scoped products PUT rest api to update a single attribute such as 'name' on that sub storeview (e.g {{domain}}/rest/{{store_view_code}}/V1/products/{{sku}}).

### Expected result

name attribute is updated creating a single row with store_id=1 in `catalog_product_entity_varchar`. No other rows with store_id != 0 are created in `catalog_product_entity_varchar`, and no rows are created in `catalog_product_entity_media_gallery_value`

### Actual result

attribute row of store_id=1 for `name` attribute is created successfully, but several rows of store_id=1 are created for attributes 'image', 'thumbnail', and 'small_image' which then breaks inheritance of the image from default level. Also a store_id=1 row is created in `catalog_product_entity_media_gallery_value`.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-26 09:08
@magento give me 2.4-develop instance

**Comment by girija-kudupudi** [comment] 2022-05-26 13:22
Hi @eraq ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
**Steps performed:**
1. Magento multi store setup
2. Created a product without image and assigned product to both websites
3. Change scope to default store view scope and added image with options "Small" and ""Thumbnail - Save
Verified DB tables: 
catalog_product_entity_varchar and - 13 records got created
catalog_product_entity_media_gallery_value - 2 records created for store id's 0 and 1
4. Send PUT request using below payload for default store view scope: http://mg24ce.local/rest/default/V1/products/simple234
_{
"product": {
"sku": "simple234",
"name": "efefefefe"
}
}_
![image](https://user-images.githubusercontent.com/92021070/170495844-e5a34132-1199-4a70-9eb1-bad2cdc75710.png)

No new row/records created in _catalog_product_entity_media_gallery_value_ table and only one new row created with store id 1 in _catalog_product_entity_varchar_ for product name
![image](https://user-images.githubusercontent.com/92021070/170495776-1547e5f9-c962-4861-9ad1-7a1f9dbe4a1a.png)
Kindly recheck the issue again on magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-05-26 13:30
Hi @eraq ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
**Steps performed:**
1. Magento multi store setup
2. Created a product without image and assigned product to both websites
3. Change scope to default store view scope and added image with options "Small" and ""Thumbnail - Save
4. Verified DB tables:
    catalog_product_entity_varchar and - 13 records got created
    catalog_product_entity_media_gallery_value - 2 records created for store id's 0 and 1
5. Send PUT request using below payload for default store view scope: http://mg24ce.local/rest/default/V1/products/simple234
    _{
    "product": {
    "sku": "simple234",
    "name": "efefefefe"
    }
    }_
![image](https://user-images.githubusercontent.com/60198231/170497411-adfd1944-7381-477c-9bb5-a7f9a70cefed.png)
No new row/records created in catalog_product_entity_media_gallery_value table and only one new row created with store id 1 in catalog_product_entity_varchar for product name
image
![image](https://user-images.githubusercontent.com/60198231/170497465-9dba93f7-90b8-480c-a5af-07efa15efbf0.png)
Kindly recheck the issue again on magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-06-10 05:53
Hi @eraq ,
We are closing this issue as there has been no latest update on the same. Kindly reopen/ create new issue if you are still facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-10 05:53 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
