### ISSUE TITLE
bundle summary should be sticky on product view page but it's not working..

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#24697] opened 2019-09-23 12:44 UTC
### Preconditions (*)

1. Magento 2.3.2
2.

### Steps to reproduce (*)

create a bundle product with around 4-5 options
then navigate to frontent
open created product page
 https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/widgets/widget_sticky.html
 https://github.com/magento/magento2/blob/2.3/app/code/Magento/Bundle/view/frontend/templates/catalog/product/view/summary.phtml

### Expected result (*)

1. 
![sticky](https://user-images.githubusercontent.com/44425160/65426377-c3b7ad80-de2d-11e9-81a1-7fbc30debdd0.png)

### Actual result (*)

![not-sticky](https://user-images.githubusercontent.com/44425160/65426390-c914f800-de2d-11e9-9e2e-a2c08d38cd8a.png)

**Comment by magento-engcom-team** [comment] 2019-09-23 14:40
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20331` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-10-20 18:11
Hello @rani-webkul 

We are not able to reproduce this issue on the latest `2.4-develop`
Probably it was fixed in some other pr. 
Or some information is missed in steps to reproduce.

If you still have this issue om 2.4-develop please create a new issue report with actual steps to reproduce

**Closed as completed by sdzhepa** 2020-10-20 18:11 UTC
Labels: Reproduced on 2.3.x, Component: Bundle, Progress: ready for dev
