### ISSUE TITLE
Magento 2.3.3 introduced backward incompatible changes to /Framework/Mail

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#25679] opened 2019-11-21 09:30 UTC
### Preconditions
1. Magento 2.3.3

### Steps to reproduce
1. Check commit https://github.com/magento/magento2/commit/3a90a0f61e953c8b943b8242525e77477cee8455#diff-fe7166a7e0c547acb18a774c9ddc9fe1 
2. MessageEnvelope class and MessageEnvelopeInterface are renamed to EmailMessage class and EmailMessageInterface.
3. This introduces backwards incompatible changes while the version number of the composer package only goes from 102.0.2 to 102.0.3 and should only introduce bugfixes. 

### Expected result
1. Semantic versioning bugfix releases should only have non breaking changes. 
2. Module should have been updated to version 103.0.0 instead

### Actual result 
1. This introduces backwards incompatible changes while the version number of the composer package only goes from 102.0.2 to 102.0.3 and should only introduce bugfixes.

**Comment by magento-engcom-team** [comment] 2019-12-05 15:13
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29446` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment] 2020-02-06 06:46
Hi @magento-engcom-team, how does one proceed on this since 2.3.4 is already released? 
Related: 
- https://github.com/magento/magento2/commit/3a90a0f61e953c8b943b8242525e77477cee8455#diff-fe7166a7e0c547acb18a774c9ddc9fe1
- https://github.com/magento/magento2/commit/e14296f8fc3fbf22d4de6af35e3c72f8678c5841
- https://github.com/magento/magento2/commit/e14296f8fc3fbf22d4de6af35e3c72f8678c5841#r37106887

CC/ @ihor-sviziev

**Comment by ihor-sviziev** [comment] 2020-02-10 12:28
@buskamuza I saw your commits in 2.3.4 that probably wanted to improve backward compatibility.
Could you add some info?

**Comment by gabrieldagama** [comment] 2020-10-15 16:11
Hi @dverkade, we are sorry that this happened, we try our best to keep backward compatibility on our patch releases. While we are still trying to minimize BIC, changes can still be applied to internal classes/interfaces that are not marked as @api.

I will be closing this issue for now since there is no work to be done.

Thanks.

**Closed as completed** 2020-10-15 16:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Email, Triage: Dev.Experience, Progress: done

**Comment by dverkade** [comment] 2020-10-15 17:10
@gabrieldagama, there's definitely work to be done. The changes need to be reverted and made backwards compatible. You just can't add backwards incompatible changes.

**Comment by ihor-sviziev** [comment] 2020-10-15 19:03
@dverkade i believe it’s not possible anymore as multiple releases already including these changes - so reverting them will break backward compatibility and some extensions will be broken 😞
