### ISSUE TITLE
Category Price filter does not work for configurables with out of stock childs, when ShowOutOfStock Option is enabled

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#27341] opened 2020-03-18 17:12 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create an configurable product with two child products with a price of 100$ resp. 200$ and add the configurable to a category
![Screenshot from 2020-08-06 19-27-11](https://user-images.githubusercontent.com/51679138/89559365-3b13e700-d81e-11ea-9d2d-5feec399518e.png)

2. Set the cheaper child product in the advanced inventory to manage stock -> true, but to be not in stock and save the product

![2020-08-06_19-53](https://user-images.githubusercontent.com/51679138/89559579-85956380-d81e-11ea-9248-64ec3a911d29.png)

3. Go to Admin->Stores->Configuration->Catalog->Inventory and Set Display Out of Stock Products to YES
4. Set the cheaper child product in the advanced inventory to manage_stock -> false (this does not change the value of is_in_stock in the database. This remains 0)

![Screenshot from 2020-08-06 19-59-15](https://user-images.githubusercontent.com/51679138/89560249-63e8ac00-d81f-11ea-9d1f-d48ae3349e6f.png)
5. Go to the category and see, that the price for your configurable is displayed as starting from 100 $, as out of stock products shall be displayed according to your settings.
6. Try to filter for a range which includes 100$

### Expected result (*)

1. I would assume to see the configurable in the product collection

### Actual result (*)

1. I do not see the configurable in the product collection

![Peek 2020-08-06 19-49](https://user-images.githubusercontent.com/51679138/89560266-69de8d00-d81f-11ea-817b-c42d9a1d4543.gif)

**Comment by shikhamis11** [comment] 2020-03-19 03:13
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-19 03:13
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by shikhamis11** [comment] 2020-03-22 16:59
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-22 16:59
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-22 16:59
Hi @shikhamis11, here is your [Magento instance](https://i-27341-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27341-2-4-develop.instances.magento-community.engineering/admin_fb87](https://i-27341-2-4-develop.instances.magento-community.engineering/admin_fb87)
Login: `d3811792` Password: `752a85865d4e`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-03-22 17:19
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32636` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento2dev** [comment] 2021-01-29 07:25
The issue stills exist on Magento 2.4

**Comment by sprankhub** [comment] 2021-04-15 18:49
This is still relevant.

**Comment by sprankhub** [comment] 2021-09-15 18:36
This is still relevant.

**Comment by pmonosolo** [comment] 2023-01-26 00:45
This is not only broken on the Configurable products. Simple products also have this issue. 

As soon as "Display Out of Stock Products" is enabled, the issue shows up:

![image](https://user-images.githubusercontent.com/66754347/214728843-d8a8c7d1-af20-4494-9d76-71841514e4b0.png)

My vanilla Magento 2 install showing incorrect products that are out of price range:

![image](https://user-images.githubusercontent.com/66754347/214728727-62ae7000-f166-4eda-884b-7cfcc9cc8f19.png)

**Comment by pmonosolo** [comment] 2023-01-26 00:49
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment] 2023-01-26 01:04
Looks like this was fixed somewhere in the new release:
![image](https://user-images.githubusercontent.com/66754347/214731859-f11db86a-fa83-467b-95a7-ed83b7005190.png)

https://ff3a03238b6f6097df6d825e42625e90.instances.magento-community.engineering/gear/bags.html?price=0-40

WITHOUT Display Out Of Stock Products

![image](https://user-images.githubusercontent.com/66754347/214731015-4bfe340f-94a0-4b76-8529-de5505682fd3.png)

Making the switch to "Yes":

![image](https://user-images.githubusercontent.com/66754347/214731131-47367d2f-ab6b-490f-8d64-ab84676b0923.png)

Reindexed:
![image](https://user-images.githubusercontent.com/66754347/214731670-1134853e-d89b-43b8-8a9d-3c927ce43ab2.png)

Reloading the page:
https://ff3a03238b6f6097df6d825e42625e90.instances.magento-community.engineering/gear/bags.html?price=0-40
![image](https://user-images.githubusercontent.com/66754347/214731784-30786489-e6eb-47dd-adb0-5c745c3a426f.png)

**Comment by pmonosolo** [comment] 2023-01-27 21:40
Hmmmm, I stripped the whole site down to the bolts and it didnt help. Applied patches or fixes that are in upcoming 2.4.6 upgrade and it also didnt help.

Then I tried to reduce the number of attributes that are used in Layered Navigation. We had 259 attributes spread around the catalog and after removing 50 attributes it all of a sudden started to work.

Could it be some kind of conflict or just too many attributes in the list? hmmmm.

Still investigating.

**Comment by engcom-Bravo** [comment] 2024-07-30 07:20
Hi @norgeindian,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="884" alt="Screenshot 2024-07-30 at 12 48 15" src="https://github.com/user-attachments/assets/f6d6e57c-df3f-41f5-9b1c-556e79ffba7b">



We are able to see the products after applying the filters.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-30 07:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S3, Triage: Ready for Triage, Progress: done, Reported on 2.3.4
