### ISSUE TITLE
Inconsistent static test rulesets for PHPMD in Magento repository

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#19062] opened 2018-11-04 20:16 UTC
### Summary (*)
Each contribution to Magento is tested against the Code Style rules provided in Magento repository:

https://github.com/magento/magento2/blob/a119df4e9ab5ffe3f3097255cc6a02cfe2e23376/dev/tests/static/phpunit.xml.dist#L21-L23

The class contains ruleset hardcoded:

https://github.com/magento/magento2/blob/9db2bd05dbf0a1a7a5b4986bdb9091f4f2d2c1f8/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php#L285

However in the repository, there is also other ruleset available:

https://github.com/magento/magento2/blob/42ad5383200fb60cc4fa543094d805c9dc94b546/dev/tests/static/framework/Magento/ruleset.xml

Which is not being used across the project.

### Proposed solution
Remove unused and misleading ruleset from the repository.

**Comment by magento-engcom-team** [comment] 2018-11-04 20:16
Hi @lbajsarowicz. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lbajsarowicz do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-04 23:02
Hi @orlangur. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Closed as completed** 2018-11-04 23:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid
