### ISSUE TITLE
HTML Minification leads to "syntax error, unexpected end of file" in .phtml files (M2.2.10)

### ISSUE THREAD

**Issue by FerihumF** [magento/magento2#25551] opened 2019-11-11 09:49 UTC
### Preconditions (*)

1. Magento 2.2.10
2. PHP 7.1.22

### Steps to reproduce (*)

1. Enable HTML minification and switch to production mode
2. Load any frontend page

### Expected result (*)

1. Page loads normally

### Actual result (*)

1. PHP Parse error:  syntax error, unexpected end of file in /path/to/magento/var/view_preprocessed/pub/static/vendor/magento/module-newsletter/view/frontend/templates/js/components.phtml on line 1

The file itself looks like this:
`<?php /** * Copyright © Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ ?> <?= $block->getChildHtml() ?> <?php`

Problem here: the newline after the last open tag was removed, which results in the syntax error.

Tried it on Magento 2.3.2, seems resolved there, but still a major issue for M2.2.10

**Comment by danielpfarmer** [comment] 2019-11-15 13:29
I can also replicate this. 

As a quick fix, I have added an end of line to the minify function in:

Magento\Framework\View\Template\Html\Minifier

`public function minify($file)
    {
        $dir = dirname($file);
        $fileName = basename($file);
        $content = preg_replace(
            '#(?<!]]>)\s+</#',
            '</',
            preg_replace(
                '#((?:<\?php\s+(?!echo|print|if|elseif|else)[^\?]*)\?>)\s+#',
                '$1 ',
                preg_replace(
                    '#(?<!' . implode('|', $this->inlineHtmlTags) . ')\> \<#',
                    '><',
                    preg_replace(
                        '#(?ix)(?>[^\S ]\s*|\s{2,})(?=(?:(?:[^<]++|<(?!/?(?:textarea|pre|script)\b))*+)'
                        . '(?:<(?>textarea|pre|script)\b|\z))#',
                        ' ',
                        preg_replace(
                            '#(?<!:|\\\\|\'|")//(?!\s*\<\!\[)(?!\s*]]\>)[^\n\r]*#',
                            '',
                            preg_replace(
                                '#(?<!:|\'|")//[^\n\r]*(\?\>)#',
                                ' $1',
                                preg_replace(
                                    '#(?<!:)//[^\n\r]*(\<\?php)[^\n\r]*(\s\?\>)[^\n\r]*#',
                                    '',
                                    $this->readFactory->create($dir)->readFile($fileName)
                                )
                            )
                        )
                    )
                )
            )
        ) . **PHP_EOL**;

        if (!$this->htmlDirectory->isExist()) {
            $this->htmlDirectory->create();
        }
        
        $this->htmlDirectory->writeFile($this->getRelativeGeneratedPath($file), rtrim($content));
    }`

**Comment by 0x15f** [comment] 2019-11-19 14:39
Can confirm this bug.

**Comment by 0x15f** [comment] 2019-11-19 19:54
Attached a patch that I tested on a Magento Cloud environment.

https://kayser-roth-public.s3.amazonaws.com/25551.patch

**Comment by engcom-Echo** [comment] 2019-12-09 13:13
Hello All


Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Enable HTML minification and switch to production mode
2. Load any frontend page

**Result**
Page loads normally

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-09 13:13 UTC
Labels: Issue: Format is valid

**Comment by LiamTrioTech** [comment] 2020-08-07 03:13
Still a problem, e.g. WeltPixel and custom phtml template when Minified and switching to production mode there is errors.
Magento 2.3.2 if we upgrade to 2.4 is it fixed?

Parse error: syntax error, unexpected 'else' (T_ELSE), expecting end of file in /var/www/html/var/view_preprocessed/pub/static/app/code/FT/DueDate/view/frontend/templates/stocklabel.phtml on line 1 

```php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php /* @var //$customBlock \Furnituretree\DueDate\Block\StockLabel */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>

        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span> In Stock </span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span>Available on Order</span>
        </div>
    <?php endif; ?>
<?php endif; ?>

```

On Product pages.

Cheers.
