### ISSUE TITLE
Advanced/Tier Pricing thousand separators corrupt quantities on save (e.g. qty of 1,000 on save becomes 1)

### ISSUE THREAD

**Issue by Part-A** [magento/magento2#6002] opened 2016-08-05 07:09 UTC
Bug is apparent in version 2.1, I have not checked earlier versions.

System set to a language that uses , (comma) as a thousands separator.

When creating a product with a advanced/tiered pricing structure, naturally, quantities of 1000 or above may be required. However, if a product is revisited and saved the quantities of 1000 and above are truncated at the displayed thousands separator: 1,000 becomes 1, 2,000 becomes 2, etc.

Steps to reproduce are:
1. Create or open a product
2. Open Advanced pricing and create tiered pricing entries with 'Quantity' set to 1000 or above.
3. Save and close the product
4. Re-open the product, save and close the product (there is no need to open the 'Advanced Pricing' Panel)
5. Re-open the product, open the 'Advanced Pricing' panel. All quantities of 1000 and above will have been truncated.

**Comment by Part-A** [comment] 2016-08-08 17:11
Additionally, the same bug affects the 'weight' field

**Comment by paales** [comment] 2016-08-09 13:39
Duplicate of https://github.com/magento/magento2/issues/5745

**Comment by Part-A** [comment] 2016-08-22 13:10
This issue can be corrected temporarily (until an official bug release) by amending lines 107 and 108 of General.php

This file can be found in the generally (composer or downloaded from webste) installed version,  at:
`vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/General.php`

or in the version on GitHub at:
`app/code/Magento/Catalog/Ui/DataProvider/Product/Form/Modifier/General.php`

Change:
`$value[ProductAttributeInterface::CODE_TIER_PRICE_FIELD_PRICE_QTY] =
                    $this->formatNumber((int)$value[ProductAttributeInterface::CODE_TIER_PRICE_FIELD_PRICE_QTY]);
`
to 

`$value[ProductAttributeInterface::CODE_TIER_PRICE_FIELD_PRICE_QTY] =
                    (int)$value[ProductAttributeInterface::CODE_TIER_PRICE_FIELD_PRICE_QTY];
`
This is for Magento 2.1. I have not as yet looked into the weight field. 

Do not simply comment out the line as the casting to an int is required.

**Comment by paales** [comment] 2016-08-24 09:05
@Part-A Technically the QTY field doesn't have to be an int, it can be a float as well. To convert to a number, do `$value * 1`.

**Comment by senthilengg** [comment] 2016-09-02 07:05
To add to it, if you upload advanced pricing using csv ( bulk upload ) then go a head and  view the same product in the catalog --> product section --> Advanced Pricing . It shows with thousands separator now try to save.

**Expected Result**
  Product should be saved.
**Actual Result**
  We found a duplicate website, tier price, customer group and quantity.

**Comment by miakusha** [comment] 2016-09-27 12:06
Closed as duplicate #5745
Issue has been fixed

**Closed as completed by miakusha** 2016-09-27 12:06 UTC
Labels: bug report
