### ISSUE TITLE
Configurable product - getUsedProducts doesn't include required attributes when called second time

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#35450] opened 2022-05-10 09:44 UTC
### Preconditions 
1. Magento 2.4.4

### Steps to reproduce 
Note: it's possible to reproduce it only by customization
1. Create some custom product attribute like `color2`
2. Create a configurable product with one child
3. Fill the child product's `color2` with some test value like 'RED'
4. Use the following code snippet somewhere in you customizations
Use instead `{CONFIGURABLE_SKU}` your configurable's product SKU
instead `{COLOR2_ID}` - your `color2` attribute id

```
$productRepository = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
$configurableType = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\ConfigurableProduct\Model\Product\Type\Configurable::class);

$configurableProduct = $productRepository->get('{CONFIGURABLE_SKU}');

$usedProducts1 = $configurableType->getUsedProducts($configurableProduct);
$usedProducts2 = $configurableType->getUsedProducts($configurableProduct, ['{COLOR2_ID}']);

$child1 = array_pop($usedProducts1);
echo $child1->getData('color2');

$child2 = array_pop($usedProducts2);
echo $child2->getData('color2');
```
What is going on here:
We just want to get Configurable's children using \Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts two times
At the first time we want to get children with the default set of attributes
At the second time we want to get children with the default set of attributes **and with our custom `color2` value**

### Expected result
1. `$child1->getData('color2');` returns null
2. `$child2->getData('color2');` returns 'RED'

### Actual result
1. `$child1->getData('color2');` returns null
2. `$child2->getData('color2');` returns null

### Why it happens
It happens because when \Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts loads products list first time - it caches them inside product using key `$this->_usedProducts`
When we want to get used products second time, but with some `$requiredAttributeIds`, it ignores `$requiredAttributeIds` and just returns previously cached value

### Possible solution
See how \Magento\ConfigurableProduct\Model\Plugin\Frontend\UsedProductsCache::aroundGetUsedProducts generate cache key includes `$requiredAttributeIds`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-07-21 12:11
Hi @Dren7755 ,

Thank you for raising the issue.

Can you please provide some use cases for this customisation ? 

Since this issue is not reproducible without your customised code, that’s why asking use cases which will help me with my analysis and how it is relevant for Magento core.

Thanks

**Comment by engcom-Lima** [comment] 2022-08-04 10:35
Hi @Dren7755 ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-04 10:35 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4

**Comment by Dren7755** [comment] 2022-08-04 13:48
Hi @engcom-Lima,

About problem use case:

Let's assume I have 2 different modules, that displays configurable's children on PDP twice

- The first module displays children with their default attribute values (using `$configurableType->getUsedProducts($configurableProduct)`)
- The second module creates custom product attribute `custom_attribute_1` and displays children with their 'custom_attribute_1' attribute values (using `$configurableType->getUsedProducts($configurableProduct, ['custom_attribute_1']);`)

So in case, the first module's template is rendered first - the result will be cached and then the second module will receive cached result **without** `custom_attribute_1` values in children.


Please reopen this issue, because it's still issue

**Comment by Lez-2** [comment] 2024-01-19 13:35
I came accross this issue in my current M2.4.6 project.
My use case is that I'm trying to add additional variation attributes to `jsonConfig` when the configurable product has swatch attributes.
On the product view page, the `getUsedProducts` function is called first by the `afterGetOptionsMediaGalleryDataJson` function from `Magento\ConfigurableProduct\Block\Plugin\Product\Media\Gallery`
This populates the `$this->_usedProducts` property with configurable variations that have only basic attributes and prevents adding additional attributes to these variations when calling `getUsedProducts` again with `$requiredAttributeIds`.

My current "quick fix" is creating an after plugin for `Magento\ConfigurableProduct\Model\Product\Type\Configurable::getUsedProducts()`

```
namespace Cmcs\ConfigurableProduct\Plugin\Model\Product\Type;

use Magento\Catalog\Model\Config;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Catalog\Api\ProductAttributeRepositoryInterface;

class Configurable
{
    private $catalogConfig;
    private $searchCriteriaBuilder;
    private $productAttributeRepository;

    public function __construct(
        SearchCriteriaBuilder $searchCriteriaBuilder = null,
        ProductAttributeRepositoryInterface $productAttributeRepository = null,
    ) {
        $this->searchCriteriaBuilder = $searchCriteriaBuilder ?:
            ObjectManager::getInstance()->get(SearchCriteriaBuilder::class);
        $this->productAttributeRepository = $productAttributeRepository ?:
            ObjectManager::getInstance()->get(ProductAttributeRepositoryInterface::class);
    }
    
    public function afterGetUsedProducts(\Magento\ConfigurableProduct\Model\Product\Type\Configurable $subject, $result, $product, $requiredAttributeIds = null)
    {
        if ($requiredAttributeIds) {
            $collection = $this->getConfiguredUsedProductCollection($subject, $product, false, $requiredAttributeIds);
            $usedProducts = array_values($collection->getItems());
            return $usedProducts;
        }

        return $result;
    }

    private function getConfiguredUsedProductCollection(
        $subject,
        \Magento\Catalog\Model\Product $product,
        $skipStockFilter = true,
        $requiredAttributeIds = null
    ) {
        $collection = $subject->getUsedProductCollection($product);

        if ($skipStockFilter) {
            $collection->setFlag('has_stock_status_filter', true);
        }

        $attributesForSelect = $this->getAttributesForCollection($subject, $product);
        if ($requiredAttributeIds) {
            $this->searchCriteriaBuilder->addFilter('attribute_id', $requiredAttributeIds, 'in');
            $requiredAttributes = $this->productAttributeRepository
                ->getList($this->searchCriteriaBuilder->create())->getItems();
            $requiredAttributeCodes = [];
            foreach ($requiredAttributes as $requiredAttribute) {
                $requiredAttributeCodes[] = $requiredAttribute->getAttributeCode();
            }
            
            $attributesForSelect = array_unique(array_merge($attributesForSelect, $requiredAttributeCodes));
        }
        $collection
            ->addAttributeToSelect($attributesForSelect)
            ->addFilterByRequiredOptions()
            ->setStoreId($product->getStoreId());

        $collection->addMediaGalleryData();
        $collection->addTierPriceData();

        return $collection;
    }

    private function getAttributesForCollection($subject, \Magento\Catalog\Model\Product $product)
    {
        $productAttributes = $this->getCatalogConfig($subject)->getProductAttributes();

        $requiredAttributes = [
            'name',
            'price',
            'weight',
            'image',
            'thumbnail',
            'status',
            'visibility',
            'media_gallery'
        ];

        $usedAttributes = array_map(
            function($attr) {
                return $attr->getAttributeCode();
            },
            $subject->getUsedProductAttributes($product)
        );

        return array_unique(array_merge($productAttributes, $requiredAttributes, $usedAttributes));
    }

    private function getCatalogConfig($subject)
    {
        if (!$this->catalogConfig) {
            $this->catalogConfig = ObjectManager::getInstance()->get(Config::class);
        }
        return $this->catalogConfig;
    }
}
```

Not an ideal solution, but it works...
Had to recreate many of the private functions and properties used by `getUsedProducts()`.
A solution with cache keys based on required attributes would be a better and more permanent solution.
