### ISSUE TITLE
Wrong validation of bundle product on save if simple product assigned to multiple sources

### ISSUE THREAD

**Issue by Garde85** [magento/magento2#33659] opened 2021-08-02 13:27 UTC
### Preconditions (*)
1. Magento 2.4.2-p1
2. Multi source inventory active

### Steps to reproduce (*)
1. Magento installation has at least 2 website: WEBSITE-A and WEBSITE-B
2. Multisource inventory has at least 2 sources: INVENTORY-A and INVENTORY-B
3. WEBSITE-A assigned to INVENTORY-A and WEBSITE-B assigned to INVENTORY-B
4. 1 simple product: PROD-SIMPLE assigned to WEBSITE-A and WEBSITE-B
5. PROD-SIMPLE is in stock on INVENTORY-A and INVENTORY-B
5. 1 bundle product: PROD-BUNDLE assigned to WEBSITE-A and contains PROD-SIMPLE in bundle configuration, with "Ship bundle items" setted on "Together"

### Expected result (*)
1. On admin, if I try to edit PROD-BUNDLE, and I click on save, product have to saved with no errors.

### Actual result (*)

1. On admin, if I try to save after edit PROD-BUNDLE this error are send me back:

`Product "PROD-SIMPLE" cannot be added to bundle product as bundle product has "Ship Bundle Items Together" and "PROD-SIMPLE" product assigned to multiple sources or has different source then rest of bundle items`

In my opinion this is not right, beacuse my product bundle PROD-BUNDLE is available on WEBSITE-A, because PROD-SIMPLE is available on INVENTORY-A, it doesn't matter if PROD-SIMPLE is assigned to INVENTORY-B, too.

I think that validation rules introduced in these class have to be reviewed:
```
\Magento\InventoryBundleProduct\Plugin\Bundle\Model\LinkManagement\ValidateSourceItemsBeforeSaveBundleSelectionPlugin
\Magento\InventoryBundleProduct\Plugin\Bundle\Model\LinkManagement\ValidateSourceItemsBeforeAddBundleSelectionPlugin
\Magento\InventoryBundleProduct\Model\SourceItem\Validator\ShipmentTypeValidator
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ *] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rogyar** [comment] 2021-08-04 07:19
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-08-05 07:29
Verified the issue on Magento 2.4-develop branch and is reproducible but as per the official Magento [User docs](https://docs.magento.com/user-guide/catalog/product-create-bundle.html?itm_source=merchdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=%22Ship%20Bundle%20Items%20Together), if "Ship Bundle Items" is set to Together, all bundle items must be assigned the same Source. Since the Bundle product (have default source by default) containing simple Product which is assigned multiple sources, error message is thrown.
We are able to save the product if Ship Bundle Items is set to "Separately"
I believe this is not an issue. 
FYI 
@sdzhepa can you please confirm the expected behavior.
Thank you!

**Comment by Garde85** [comment] 2021-08-05 07:46
> ... **We are able to save the product if Ship Bundle Items is set to "Separately"
> I believe this is not an issue.**
> FYI
> @sdzhepa can you please confirm the expected behavior.
> T.....

I think that is not right. 
I say that because I don't want that users can decide to ship bunlde items separately. My bundle is shipped always togher fot customer of WEBSITE-A. At the same time, in all may magento installation, product PROD-SIMPLE is unique and this SKU identify a specific product. Than, if user in WEBSITE-A purchase PROD-BUNDLE, magento has to update stock info of PROD-SIMPLE on  INVENTORY-A.

**Comment by engcom-Hotel** [comment] 2022-02-16 14:32
Hello @Garde85,
```
We have received the reply from the PO, actually, that is expected behavior and a current limitation of MSI. There were other requests like https://jira.corp.magento.com/browse/MC-42816
 
Having into consideration that Bundles does not have a heavy adoption and we are not having assigned Core engineering teams to MSI I will leave them clear that we have no plans to fix that behavior.
```
Hence closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-02-16 14:32 UTC
Labels: Component: Bundle, Component: Inventory, Reproduced on 2.4.x, Triage: Need PO Confirmation, Issue: On Hold, Issue: needs update
