### ISSUE TITLE
It takes up to 1 minute to get the confirmation message after creating an account

### ISSUE THREAD

**Issue by jibrandlr** [magento/magento2#6330] opened 2016-08-24 19:32 UTC
### Preconditions

1. Magento 2.1.0, PHP 7.0.8, Ubuntu 16.04
### Steps to reproduce
1. Fill the form in the create an account page
2. Click "create an account" button.
### Expected result
1. The user should see the confirmation of the registration process after a few seconds (reasonable time).
### Actual result
1. It takes up to 1 minute to see the confirmation message.

![time-create-account](https://cloud.githubusercontent.com/assets/8398744/17944983/8126a662-6a07-11e6-9459-404227960bd4.jpg)

**Comment by heldchen** [comment] 2016-08-24 20:30
not seeing that here:
![image](https://cloud.githubusercontent.com/assets/299636/17946862/5af9439e-6a4a-11e6-9055-79a92bc9ec40.png)

looks very much like a 60s timeout of something... is your sendmail configured properly?

**Comment by jibrandlr** [comment] 2016-08-24 23:37
@heldchen I don't think sendmail is configured properly. It's a local installation used only for theme development (no need for sendmail). I'll look at the sendmail configuration

**Comment by antboiko** [comment] 2016-08-30 10:41
Hi @lgarridoj , did you have a chance to check the sendmail configuration? Please give us an update on this.

Thanks,
Anton.

**Comment by jibrandlr** [comment] 2016-08-30 22:04
@antboiko The problem was indeed sendmail not configured properly, thanks.

**Comment by veloraven** [comment] 2016-08-31 07:48
@lgarridoj thank you for update.
I'm closing this issue as not a bug.

**Closed as completed by veloraven** 2016-08-31 07:48 UTC
Labels: Progress: needs update
