### ISSUE TITLE
Can not enable products from the configurable

### ISSUE THREAD

**Issue by lyusya-nnn** [magento/magento2#10846] opened 2017-09-12 06:24 UTC
### Preconditions
Magento 2.1.8
### Steps to reproduce
1. In admin panel go to Products > Catalog
2. Click on Add configurable product, enter product name, sku and price for the new product, click on Create configuration button and add child products to the configurable, put status Disable for the assigned products:
![new product products inventory products verpakkingsmaterialen hodi b v magento admin](https://user-images.githubusercontent.com/8502721/30310863-4cf49ddc-979b-11e7-9352-77f6b6420e7d.png)
3. Save the product
4.On Configurations section select Enable product from the Action list:
![test configurable 1 products inventory products verpakkingsmaterialen hodi b v magento admin](https://user-images.githubusercontent.com/8502721/30310930-a7e7bf30-979b-11e7-8f71-e95c641f61ab.png)
5. Save the product

### Expected result: 
Assigned products are enabled
### Actual result: 
Assigned products are shown as disable
![test configurable 1 products inventory products verpakkingsmaterialen hodi b v magento admin](https://user-images.githubusercontent.com/8502721/30310983-ebcd6b78-979b-11e7-8003-d9fcdbdb7aec.png)

**Comment by yusere** [comment] 2017-09-16 15:16
The story

Before saving the informations about configurable product, there are initialised the informations about simple products belonging to it. This is happening in module-configurable-product/Controller/Adminhtml/Product/Initialization/Helper/Plugin/UpdateConfigurations.php file, following function:

private function getConfigurationsFromProduct(\Magento\Catalog\Model\Product $configurableProduct)
    {
        $result = [];

        $configurableMatrix = $configurableProduct->hasData('configurable-matrix') ?
            $configurableProduct->getData('configurable-matrix') : [];
        foreach ($configurableMatrix as $item) {
            if (empty($item['was_changed'])) {
                continue;
            } else {
                unset($item['was_changed']);
            }

            if (!$item['newProduct']) {
                $result[$item['id']] = $this->mapData($item);

                if (isset($item['qty'])) {
                    $result[$item['id']]['quantity_and_stock_status']['qty'] = $item['qty'];
                }
            }
        }

        return $result;
    }
Here, the simple products are iterated and if a product contains was_changed, in the array informations, it is added in the $result array to be saved in the database.

The problem: Even if I change the status for a simple product, the was_changed attribute is not set for it, in the informations which will be received by the "save" controller. So, when the simple items are iterated in getConfigurationsFromProduct function, the continue statement will be hit every time, $result array being null.

The solution:

I've found a way to set was_changed attribute, in the toggleStatusProduct function from module-configurable-product/view/adminhtml/web/js/components/dynamic-rows-configurable.js, which is dispatched every time the simple product status is changed. The cleanest way is to rewrite that file and replace the function with:

toggleStatusProduct: function (rowIndex) {
            var tmpArray = this.getUnionInsertData(),
                status = parseInt(tmpArray[rowIndex].status, 10);

            if (status === 1) {
                tmpArray[rowIndex].status = 2;
            } else {
                tmpArray[rowIndex].status = 1;
            }
            tmpArray[rowIndex]['was_changed'] = true;
            this.unionInsertData(tmpArray);
        }
Clear the cache, run a deploy and it should work.

Good luck !

**Comment by magento-engcom-team** [comment] 2017-09-21 19:06
@lyusya-nnn, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-21 19:06 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
