### ISSUE TITLE
CSS Minify Option Breaks inline SVG XML

### ISSUE THREAD

**Issue by jvreeken** [magento/magento2#6822] opened 2016-09-30 17:13 UTC
### Preconditions
1. Magento 2.1.1 
### Steps to reproduce
1. In your css, use an svg as an background image
2. Example:
   `background:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" viewBox="0 0 38 40"><style>.st0{fill:none;stroke:%23ffffff;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}</style><circle cx="14.7" cy="14.7" r="13.7" class="st0"/><path d="M23.9 24.7L37 39" class="st0"/></svg>') no-repeat left center;`
   (Note that Colors with hex values need # to be url encoded to %23 to not break firefox and safari)
3. Turn on css minify in the backend
4. deploy static content
### Expected result
1.  The svg xml should not be minified / should be minified and url encoded hash symbols for colors to work in all browsers
   `background:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" viewBox="0 0 38 40"><style>.st0{fill:none;stroke:%23ffffff;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}</style><circle cx="14.7" cy="14.7" r="13.7" class="st0"/><path d="M23.9 24.7L37 39" class="st0"/></svg>') no-repeat left center;`
### Actual result
1. The svg xml is not properly parsed and breaks the image and does not display:
   Spaces are removed that should not be removed (marked in bold below)...

`background:url('data:image/svg+xml;utf8,<svgxmlns="http://www.w3.org/2000/svg"id="Layer_1"viewBox="**003840**"><style>.st0{fill:none;stroke:%23ffffff;stroke-width:2;stroke-linecap:round;stroke-miterlimit:10;}</style><circlecx="14.7"cy="14.7"r="13.7"class="st0"/><pathd="**M23.924.7L3739**"class="st0"/></svg>') no-repeat left center;`

There is a similar example here with other css minify libraries:
https://github.com/yui/yuicompressor/issues/141

I'd like to be able to use inline svgs as background images to reduce http requests.
For now I've just changed them to use svg files in the meantime...

**Comment by magento-team** [comment] 2017-07-31 23:02
Internal ticket to track issue progress: MAGETWO-67487

**Comment by magento-engcom-team** [comment] 2017-09-20 22:36
@jvreeken, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:36 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Fixed in 2.2.x, Issue: Format is valid
