### ISSUE TITLE
Page Layout/Margins not consistent across all pages when viewed on wide enough screen

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#30705] opened 2020-10-29 11:59 UTC
### Preconditions (*)

1. 2.4.1 and 2.4-develop
2. The same behavior on Blank and Luma Themes

### Steps to reproduce (*)

1. Deploy a blank vanilla site
2. Expand browser window so there are left and right margins on screen with site centered
3. Create a test product in a test category
4. Browse the following pages, noticing if the position of the logo/navbar/content changes on each page from left/right by a small amount

- Home Page
- Category Page
- Product Page
- Popular Search Terms
- Orders and Returns
- Contact Us
- Advanced Search

### Expected result (*)

1. Page Layouts should be consistent

### Actual result (*)

1. They are not
2. Sometimes the content shifts right and then back again very quickly, other times it stays offset.

![8fZgdqCovk](https://user-images.githubusercontent.com/30697781/97565347-fdb69400-19dd-11eb-811d-3402bd536aef.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gwharton** [comment] 2020-10-29 12:07
Scroll bar visibility being the issue, but can anything be done to improve it.

**Comment by engcom-Bravo** [comment] 2020-10-29 16:26
The same behavior on the latest 2.4-develop.
Rechecked with Blank and Luma Themes

**Comment by magento-engcom-team** [comment] 2020-10-29 16:28
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38805` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment] 2020-10-29 16:29
As someone pointed out to me, it is because of scrollbar visibility. Loading a page with content below the fold results in a scroll bar, which shifts the content left slightly when the scrollbar becomes visible. The only way I see round it, is to either a) not have a theme that is page centered...... not gonna happen, or b) use overflow-y to keep scrollbar visible all the time.

**Comment by mrtuvn** [comment] 2020-10-29 16:51
maybe some section shift content while rendering that cause problem. That's  call Cumulative Layout Shift

**Comment by Leland** [comment] 2020-12-08 23:46
This is a non-issue IMO.

Long pages have scrollbars. Short pages do not. That's just how browsers work.

The Luma homepage in the issue description's GIF doesn't have a scrollbar because it's, well, an empty homepage. Once content is added, this issue will be "fixed."

**Comment by ihor-sviziev** [comment] 2020-12-09 10:31
Hi @Leland,
TBH I do agree with @Leland that it's not an issue, but just a default behavior of the browsers which is expected.

What do you think about that?

**Comment by gwharton** [comment] 2020-12-09 10:40
As the original reporter of the issue, I was going to close it as soon as i realised it was a scroll bar issue, however after a bit of thought, I couldnt decide whether it was valid or not.

I understand exactly why it is happening, but..... I dunno, it just feels like the luma theme, in its out of the box format, should present a nice example of a UI which doesn't suffer from the shifting when browsing between pages with and without scroll bars.

Once a site is filled with content, I would expect the vast majority of pages would include below the fold content so would not be an issue, but there will occasionally be a short page somewhere, where a jump is seen.

I'm not gonna die in a ditch about it. I now understand why it is happening. I have implemented always visible scrollbars on my site, because that is my preference, and it only actually affects a very small proportion of my pages, so I am happy, and understand that its probably not right to enforce this policy on everyone who uses Luma as a starting point who may not share my views.

Thanks for the work you put in on the PR @mrtuvn, and apologies if it is deemed no longer required.

**Closed as completed** 2020-12-09 11:19 UTC
Labels: Area: Frontend, Issue: Confirmed, Component: Ui, Severity: S3, Priority: P4, Progress: done, Issue: needs update, Reported on 2.4.1

**Comment by magento-engcom-team** [comment] 2020-12-09 11:21
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
