### ISSUE TITLE
Swatch names and values can disappear with an uncorrectable error after "Saving" from another config tab

### ISSUE THREAD

**Issue by Sanfam** [magento/magento2#5549] opened 2016-07-08 20:17 UTC
When an admin attempts to create a new visual swatch, they need to ensure that the "Admin" column has all of the necessary values entered.  If the necessary data is absent, the user will be prompted to correct this discrepancy.  If, however, they leave one or more admin fields absent while clicking "Save Attribute" from within another tab (for example, the "Storefront Properties" option set), they receive an error reading `Admin is a required field in the each row` and on navigating back to the "Properties" tab are shown a blank set of swatches with no ability to add, edit, or remove them.  Any work put in up to this point is lost.
## Steps to reproduce
1. Begin creating a new Visual Swatch attribute.  Add several options, being sure to leave both Name fields on the top row blank.
2. ![magento_attribute_bad_configuration](https://cloud.githubusercontent.com/assets/3504427/16700267/2aa30e16-4527-11e6-802f-0f4b5b6857f1.PNG)
3. Navigate to the "Storefront Properties" tab and make any changes
4. From the "Storefront Properties" tab, click the orange "Save Attribute" button.
## Expected result
1. A (mostly) grammatically correct Error Message appears below the swatch list, `Admin is a required field in the each row`
2. ![magento_attribute_correct_error](https://cloud.githubusercontent.com/assets/3504427/16700114/3b9a4910-4526-11e6-9d91-7585aed2e7c5.PNG)
3. The user is able to make their correction and add the missing required data
## Actual result
1. User receives error, `Admin is a required field in the each row` at the top of the "Storefront Properties" page
2. ![magento_attribute_failure_state](https://cloud.githubusercontent.com/assets/3504427/16700257/156ed232-4527-11e6-8293-0ca997f28387.PNG)
3. The swatch list is completely absent with no way to add, edit, or remove data.  This swatch needs to be recreated.

**Comment by dthampy** [comment] 2016-07-08 22:49
Thank you for your detailed bug report and screenshots. An Internal jira ticket(MAGETWO-55231) has been created for this issue.

**Comment by nishantbkw** [comment] 2016-11-22 12:30
Did you solve it? 
I am having same issue i added all colors and now trying to add all colors by choosing visual swatch from drop down i have filled all colors in the admin field but still getting error "Admin is a required field in the each row" when i save it after choosing 
colors from swatch

**Comment by nishantbkw** [comment] 2016-11-22 12:42
![color product attributes attributes stores magento admin](https://cloud.githubusercontent.com/assets/11628633/20524164/21995004-b0df-11e6-8eae-7dd44968d55e.png)

Atatched is screenshot the blank showing fields are screenshot error

**Comment by dthampy** [comment] 2016-11-28 15:07
@nishantbkw , Please note that a ticket has been created internally, but will need to be prioritized by the Product owners before it can be worked on. 
Thanks.

**Comment by renatocason** [comment] 2017-01-04 11:05
On a further note - if you get this error but all the labels are set, watch out for zeros. The check uses the PHP _empty_ function which considers "0" to be empty (line 433 of _vendor/magento/module-swatches/Model/Plugin/EavAttribute.php_). Probably another bug.

**Comment by rafaelstz** [comment] 2017-01-09 22:01
I hope that this report help to fix.
The POST params with all attributes are right, but when Magento process the attributes, it breaks in the attribute **number 199** (I tested in many attributes with this error), like the image below.
![image](https://cloud.githubusercontent.com/assets/610598/21785293/1af3d05c-d6a6-11e6-9b06-e68f6035602a.png)

**Comment by thaddeusmt** [comment] 2017-08-16 03:10
I think I just ran in to this with Enterprise 2.1.7 - any progress on this bug?

**Comment by benmarks** [comment] 2017-08-23 14:20
@thaddeusmt Please file a ticket with Enterprise support team - they will be able to update regarding status. Thanks!

**Comment by magento-engcom-team** [comment] 2017-10-05 06:30
@Sanfam, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 06:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
