### ISSUE TITLE
Product Media gallery deletes and inserts existing unchanged images on product save.

### ISSUE THREAD

**Issue by ericclaeren** [magento/magento2#31121] opened 2020-12-02 10:08 UTC
### Preconditions (*)
1. Tested in 2.3.5-p1,
2. Reproducible on 2.4-develop

But the code which causes this issue can be found in 2.4.1

### Steps to reproduce (*)
1. Go to a product which contains media, I have tested this with a configurable product, but any type should do.
2. Change any non related image / gallery field (e.g. product status On -> Off)
3. Save product

### Expected result (*)
1. Product saved, only the changed field values should be saved.

### Actual result (*)
1. The create handler inserts/deletes every image in the catalog_product_entity_media_gallery_value table.
2. This dispatches the mysql trigger: trg_catalog_product_entity_media_gallery_value_after_delete for every image.
3. This dispatches the mysql trigger: trg_catalog_product_entity_media_gallery_value_after_insert for every image.
4. This triggers mview subscription tables to add a record for the product entity, which leads to massive amount of changelog records for the same product.

A product with 10 images, generates 20 changelogs for e.g. catalog_product_flat. And has a negative performance impact on the database when inserting the values and fetching them when mview needs to re-index those values. The values are de-duplicated, but other 3rd party index tables might not do that. It also slows the index process because of the limit and has a memory cost for all fetched duplicate entity_id's

https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Catalog/Model/Product/Gallery/CreateHandler.php#L266

There's a 'removed' check, which is always true, this function should have been split in 2 separate functions, one to for inserting, second for updating images when values actually have changed. Also the parent already has split images for new and existing and logic could be based on that.

There's also an empty \Magento\Catalog\Model\Product\Gallery\CreateHandler::processDeletedImages which does absolutely nothing and should be removed.

### Additional info from Engcom
Reproducible on the latest 2.4-develop

1. Create a product containing an image
![image](https://user-images.githubusercontent.com/51680745/100881062-28e94300-34b6-11eb-8365-99a1552b7418.png)
2. Open `catalog_product_entity_media_gallery_value` table from database
3. Observe the value in the `record_id` column
4. Disable the previously created product
![disable](https://user-images.githubusercontent.com/51680745/100881501-aad96c00-34b6-11eb-8bca-371b9b62dcf0.png)
5. Observe the value in the `record_id` column

**Actual Result**
The `record_id` value has been changed
![conf_record11](https://user-images.githubusercontent.com/51680745/100882046-5edaf700-34b7-11eb-9a32-c9914c10e478.png)

**Comment by engcom-Bravo** [comment] 2020-12-02 14:00
Hello @ericclaeren 

Thank you for your report

We confirm that the issue is reproducible on the latest 2.4-develop version. Additional info from Engcom is added to the description.

**Comment by magento-engcom-team** [comment] 2020-12-02 14:03
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39546` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Lunaetic** [comment] 2020-12-03 23:33
@magento I am working on this

**Comment by Lunaetic** [comment] 2020-12-08 18:18
Alright, working on this waylaid by the fact that one of the use cases relies on a static call to File/Uploader::getNewFileName (which I'm guessing is why there aren't currently unit tests for this code :( ) Halting work on this and seeing if that can be addressed.

**Comment by engcom-Bravo** [comment] 2024-07-03 06:25
Hi @ericclaeren,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="782" alt="Screenshot 2024-07-03 at 11 50 26" src="https://github.com/magento/magento2/assets/51680745/cdc53334-26aa-41d0-bdf8-b292583f5565">


The record_id value has not changed.

Hence we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2024-07-03 06:25 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.4.x, Component: MediaContent, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Reported on 2.3.5-p1

**Comment by veppywaqar** [comment] 2024-08-16 12:07
any update on this issue?

**Comment by onlinebizsoft** [comment] 2024-11-30 07:25
@engcom-Bravo can you refer the commit or pull request corresponding with this? Do we know which Magento release would fix this ?

**Comment by onlinebizsoft** [comment] 2025-02-22 11:02
@magento-engcom-team can you refer the commit or pull request corresponding with this? Do we know which Magento release would fix this ?
