### ISSUE TITLE
Can't add Simple Products to Grouped Product

### ISSUE THREAD

**Issue by densen45** [magento/magento2#25555] opened 2019-11-11 13:49 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Chromium: 78.0.3904.70 (Official Build), 64-Bit
3. Firefox: 70.0.1 (64-Bit)

### Steps to reproduce (*)

1. Create several Simple Products (I don't know how many are necessary or whether the amount of products has to do with this problem. We have ~2300 Simple Products.)
2. Go to Catalog > Products > Add Product > Grouped Product
3. Scroll down and click on "Add Products to Group"

### Expected result (*)

1. Usually the "Add Products to Group" window opens and the table with all available Simple Products is loaded.

### Actual result (*)

1. The "Add Products to Group" window opens, but the table is not fully loaded (the menu bar and the header of the table are rendered, but the products are not)
2. The page becomes unresponsive
3. A little later the question form the browser, if you want to continue or stop the script execution, will open
4. The browser's task manager shows 100 percent CPU and up to 9GB memory usage (Chromium)

**Comment by densen45** [comment] 2019-11-11 13:51
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-11 13:51
Hi @densen45. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-11 13:52
Hi @densen45, here is your [Magento instance](https://i-25555-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25555-2-3-develop.instances.magento-community.engineering/admin](https://i-25555-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2019-11-11 14:03
@densen45 I am not able to reproduced in Magento 2.3-develop instance. So I am closing this,

**Closed as completed by sudheers-kensium** 2019-11-11 14:03 UTC
Labels: Issue: Format is valid

**Comment by densen45** [comment] 2019-11-11 14:08
@sudheers-kensium how many Simple Products did you have created before you tested to add some to a Grouped Product?

I'm also not able to reproduce this issue with six Simple Products (test instance) but maybe the amount of Simple Products (how many rows have to be rendered) has to do with this problem.

**Comment by sudheers-kensium** [comment] 2019-11-11 14:14
@densen45 I have verified with more than 1000 products.

**Comment by densen45** [comment] 2019-11-11 14:44
@sudheers-kensium ok. 

Maybe it has something to do with our custom attributes then. Or the combination of many products and many custom attributes. We have ~140 custom attributes. The scrollbar at the bottom of the table indicates that the table has a lot of columns, i.e. it tries to load many custom attributes.

**Comment by densen45** [comment] 2019-11-12 08:57
We have found the cause for our issue. 
See my comment here: https://github.com/magento/magento2/issues/25038#issuecomment-552796629
