### ISSUE TITLE
Dashboard New Customers Tab in admin - currency issue

### ISSUE THREAD

**Issue by farior** [magento/magento2#5661] opened 2016-07-15 08:17 UTC
## Steps to reproduce
1. Make several websites each with one group and store view
2. Make products with different prices for each website
3. Make several customers and some orders in different websites
4. Go to admin area
## Expected result
1. New Customers tab should display correct currency for values ordered
## Actual result
1. New Customers tab amount values have default currency
2. ![newc](https://cloud.githubusercontent.com/assets/10270387/16867964/94bfbd98-4a7d-11e6-82c7-4e25663a5746.jpg)
## 

This should use order currency, or convert values to config currency

**Comment by sevos1984** [comment] 2016-09-01 15:20
How magento can count one customer account on two websites in different currency if customer is shared for two websites? Admin panel always shows account in default currency.

**Comment by farior** [comment] 2016-09-02 10:34
I have 4 different websites each with one store group and one store view. Each website with differect currency
Dashboard currency is set to SEK. Customers is shared between websites.
If customer makes order in Website with SEK currency > Dashboard shows values and currency as expected (in SEK)
If customer makes order in Website with USD currency > Dashboard shows USD values, but with SEK label

This is confusing and I think currency should be correct, otherwise values should be converted to dashboard currency using rates stored in sales_order table

**Comment by ronnybremer** [comment] 2016-09-08 06:10
I can confirm this behaviour in CE 2.1.1 and maybe add a few thoughts.

Our setup is similar, we have US-$ as the default currency at system level, so our dashboard needs to show all prices in US-$ (we need this to calculate commission, compare forecasts etc).
For each region we have a different website (one store within each and 2-3 views for language reasons) and each website has a different set of currencies. For EU we accept GBP, €, CZK. For Switzerland we accept CHF and €. For the rest of the world: US-$.
We import our conversion rates automatically through the yahoo service.

We expect the dashboard to show all values converted to US-$, (of course, the view on the dashboard is set to "all Store Views". This is the way it worked in Magento 1.9.
The actual behaviour is similar to what sevos1984 is describing, but even more weird, cause the currency symbol for the mayor figures on the dash board is CHF! For a totally unknown reason. If you click on Most Viewed Products it changes to US-$.

This is for us a show stopper to roll out CE 2.1.

**Comment by sevos1984** [comment] 2016-09-29 09:32
@farior I can't recreate that, have you set your currency rates correctly?

**Comment by sevos1984** [comment] 2016-09-29 09:47
@ronnybremer Can you please create new issue with detailed steps to reproduce?

**Comment by ronnybremer** [comment] 2016-09-29 10:58
will do

**Comment by farior** [comment] 2016-09-29 12:05
@sevos1984 Yes, currencies are ![OK](http://dl2.joxi.net/drive/2016/09/29/0008/0597/553557/57/fd3ebc5f04.jpg)

**Comment by sevos1984** [comment] 2016-10-04 09:18
@farior I can't reproduce that, can you give more detailed steps please?

**Comment by sevos1984** [comment] 2016-10-19 08:19
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-19 08:19 UTC
Labels: bug report, Progress: needs update, Component: Customer
