### ISSUE TITLE
MessageQueue MessageController returns incomplete lock object, failed messages are not requeued

### ISSUE THREAD

**Issue by PTuijtelaars-ISAAC** [magento/magento2#34754] opened 2021-12-03 09:27 UTC
### Preconditions (*)

1. Magento 2.3.7-p2
2. Magento Framework Message Queue

### Steps to reproduce (*)

1. Add a message to the queue
2. Start the consumer
3. Let the message handling fail and make sure the message is requeued
4. Message status is now incorrect and message is not handled again by the consumer

### Expected result (*)

1. Message lock is removed
2. Message is requeued and has correct status ( QueueManagement::MESSAGE_STATUS_RETRY_REQUIRED )

### Actual result (*)

1. Message lock is not removed, therefor the message is not processed again but is handled by the acknowledge method
2.

The Magento\Framework\MessageQueue\MessageController  is used to create the lock and return the LockInterface Object. The object does not contain all the information neccessary to handle the cleaning of the queue_lock table as is defined in Magento\Framework\MessageQueue\Consumer getTransactionCallback. 

The getTransactionCallback expects that there is an id added to the lock object, but the id returned is null, therefor no locks are cleaned and affected messages end up with a status QueueManagement::MESSAGE_STATUS_COMPLETE as it is set in aknowledge method of the driver. 

This can be fixed by patching the MessageController
`diff --git a/MessageController.php b/MessageController.php
index ae5fe65..05bd64d 100644
--- a/MessageController.php
+++ b/MessageController.php
@@ -66,6 +66,7 @@ public function lock(EnvelopeInterface $envelope, $consumerName)
             throw new MessageLockException(new Phrase('The "%1" message code was already processed.', [$code]));
         }
         $this->writer->saveLock($lock);
+        $this->reader->read($lock, $code);
         return $lock;
     }
 }`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2022-07-20 11:38
Hi @PTuijtelaars-ISAAC ,

Thanks for reporting the issue

Tried reproducing the issue with latest 2.4-develop instance however the issue is not reproducible.

Steps tried to reproduce the issue

1. Install latest 2.4-develop instance
2. Configure rabbitmq [devdocs](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/install-rabbitmq.html)
3. Create a custom queue [devdocs](https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/)
4. Fail the queue (Check entry in **queue_message_status** table) the status should be **5 i.e MESSAGE_STATUS_RETRY_REQUIRED**

**Output:**
After running the consumer again the queue is re run and successfully executed. The status is updated to **4 i.e MESSAGE_STATUS_COMPLETE**

Pasting here different status for reference:
 ```
 MESSAGE_STATUS_NEW = 2;
  MESSAGE_STATUS_IN_PROGRESS = 3;
  MESSAGE_STATUS_COMPLETE= 4;
  MESSAGE_STATUS_RETRY_REQUIRED = 5;
  MESSAGE_STATUS_ERROR = 6;
  MESSAGE_STATUS_TO_BE_DELETED = 7;
```

If the issue is still reproducible for you on latest 2.4-develop instance do let us know the exact steps so I can retry the same.

Thanks

**Comment by engcom-Lima** [comment] 2022-08-03 06:25
Hi @PTuijtelaars-ISAAC ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-03 06:25 UTC
Labels: Triage: Dev.Experience, Issue: needs update
