### ISSUE TITLE
Sales order email not sent

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#36453] opened 2022-11-10 09:59 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Setup a new customer account with a lastname including the following characters: 

Foo-<Bar

Because the lastname is not sanitised, the emails fails:

msmtp: recipient address Foo?=_<foo_bar@mail.net not accepted by the server msmtp: server message: 501 Syntax error in parameters msmtp: could not send mail (account default from /etc/msmtp/msmtprc) Nov 08 12:05:14 host=anonymized tls=on auth=on user=apikey from=anonymized@anonymized.anonymized recipients=Foo?=_<foo_bar@mail.net,anonymized@anonymized.anonymized smtpstatus=501 smtpmsg='501 Syntax error in parameters' errormsg='recipient address Foo?=_<foo_bar@mail.net not accepted by the server'

I have replaced sensitive data by anonymized

### Expected result

Email is sent.

### Actual result

Email is not sent.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-11 14:04
Hi @thomas-kl1,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and we are not able to reproduce the issue.Kindly refer the screeenshots.

We are not able to setup the customer account for the lastname you have provided.


<img width="900" alt="Screenshot 2022-11-11 at 7 30 45 PM" src="https://user-images.githubusercontent.com/51680745/201356088-37197658-13fb-4c26-ac7b-c9f0410fd6b3.png">



Kindly Provide exact steps to reproduce the issue.

Thanks.

**Comment by thomas-kl1** [comment] 2022-11-11 20:13
Hello @engcom-Bravo 
It is possible on Magento 2.3. but you are right, it seems not possible on 2.4. However, even if you upgrade, the already created accounts are not sanitized regarding this new rule which should prevent invalid characters

**Comment by engcom-Bravo** [comment] 2022-11-14 10:01
Hi @thomas-kl1,

Thanks for your Update.

As it is not possible on 2.4 can u please confirm can we close this issue.

Please let us know if you are still facing any issue.

Thanks.

**Comment by thomas-kl1** [comment] 2022-11-14 10:23
You misunderstood the problem. My bad the description is not clear. Shortly, You have a website with Magento < 2.4. You create a user with an a lastname which would be invalid with Magento 2.4.
Then you upgrade your website to 2.4. So your user still have the lastname, with now invalid characters. So unless I edit the customer, the invalid characters remains. However I won't spend my time to look for invalid user name. So there is an issue with Magento 2.4, because there is no data patch to fix and replace invalid characters, or at least warns about it.

**Comment by engcom-Bravo** [comment] 2022-11-18 06:31
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-18 10:14
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-18 11:56
HI @thomas-kl1,

Thanks for your Update.

we tired to reproduce the issue but we are not able to reproduce the issue.In 2.3.X we are not able to create the customer account with a last name **Foo-<Bar**.


Installed Magento version 2.3.7 with php 7.4.



<img width="856" alt="Screenshot 2022-11-18 at 3 05 06 PM" src="https://user-images.githubusercontent.com/51680745/202699671-42fd410f-ea6d-4c0d-b476-4b5b66c89c6d.png">



Kindly provide more steps to reproduce the issue.

Thanks.

**Comment by thomas-kl1** [comment] 2022-11-18 13:29
Was possible with 2.3.0 for sure

**Comment by engcom-Bravo** [comment] 2022-11-21 07:48
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-22 05:59
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-11-23 10:50
Hello @thomas-kl1,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue via upgrading Magento from 2.3.5 to 2.4.5-p1. But for is the issue is not reproducible. We have followed the below steps:
1. Install Magento 2.3.5
2. Create a user with mentioned last name in the main description:
![AccountWithUnsanitizedName](https://user-images.githubusercontent.com/51681618/203527480-e8bffe70-4e0c-4fd9-b5af-71fe4bd9b619.png)
3. Create an order with that user and then from the admin panel `Sales -> Orders - > Send Mail`, to send the email about the order. We are able to get the email:
![235_able-to-get-email](https://user-images.githubusercontent.com/51681618/203527875-24c1ea8a-3b95-47a8-8fa5-1fead4802751.png)
4. Upgrade the Magento instance with 2.4.5-p1
![AfterUpgradeDashboard](https://user-images.githubusercontent.com/51681618/203527931-c0b56333-c307-4a29-b9bb-3be52b59ac0c.png)
5. Try to send the email from the order section again and this time also be able to get the email:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/51681618/203528407-23086f16-1ed7-42b7-951d-c62e8fa693a7.png">

Please let us know if you are talking about the specific email.

Thanks

**Comment by slavvka** [comment] 2022-11-28 20:11
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-12-05 08:56
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-12-05 08:57
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-12-07 07:38
Dear @thomas-kl1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-12-07 07:38 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.x
