### ISSUE TITLE
Form Validation are not translated

### ISSUE THREAD

**Issue by AlessandroStaffolani** [magento/magento2#9644] opened 2017-05-16 10:03 UTC
I'm trying to translate magento 2, but I can't translate the validation messages added on the form.

### Preconditions

1. I'm using Magento 2.1.5 

### Steps to reproduce

1. Add `<magento_root>/app/i18n/<vendor>/it_IT` with these files: 
       - `composer.json`
       - `it_IT.csv` the file contains 4 columns: "en_text","it_text",module,module_name
       - `language.xml`
       - `registration.php`
2. I followed official documentation to create a language pack: http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-i18n.html#config-cli-subcommands-xlate-example2
3. I copied on the root the csv file. Then I executed this command: `magento i18n:pack /var/www/html/<magento_root>/it_IT.csv -d it_IT`
4. I've executed also `magento setup:static-content:deploy it_IT` and `magento cache:flush`
5. Now all modules on vendor as the it_IT.csv file on their i18n folder with my translation

### Expected result

1. All translation are translated

### Actual result

1. The most of all translation strings are translated, but the translation about form validation `<magento_root>/vendor/module-ui/view/base/web/js/lib/validation/rule.js` are not, even if 
I checked that the it_IT.csv file on module-ui contains the right translation and they match the strings on rule.js file

**Comment by dmitriyprime** [comment] 2017-06-26 11:40
Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2?

**Comment by stephansteiner** [comment] 2017-08-24 12:13
This is STILL an issue in 2.1.8. The form validations in lib/web/mage/validation.js contain error messages that should be
- one liners and not concatenated with "+" (like validator.passwordErrorMessage)
- enclosed by $.mage.__('Some error message') instead of 'Some error message'

Same goes for 
- vendor/magento/magento2-base/lib/web/mage/validation.js
- vendor/magento/module-ui/view/base/web/js/lib/validation/rules.js (please fix the validate-customer-password: "Minimum of different classes of characters in password is %1....")
Without this, you most probably won't get a fully translated frontend for the customer.

**Comment by magento-engcom-team** [comment] 2017-09-19 15:27
@ale8193 , thank you for your report.
The fix for this issue is already available on Magento 2.2.0 branch.

**Closed as completed by magento-engcom-team** 2017-09-19 15:27 UTC
Labels: bug report, Component: Translation, Issue: Clear Description, Fixed in 2.2.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2017-10-30 18:33
@magento-engcom-team Please backport to 2.1 or mark as up for grabs.
