### ISSUE TITLE
Minicart and Currency dropdown format incorrectly on a tablet

### ISSUE THREAD

**Issue by wibbel** [magento/magento2#9529] opened 2017-05-05 13:36 UTC
### Preconditions
1.  Magento 2.16
2.  Tablet ie iPad Air2 or Mobile
3.  luma or blank theme

### Steps to reproduce
1.  from a tablet, click the minicart icon in the header 
2. Same problem on an iphone

### Expected result
1.  Minicart dropdown displays with "No Items message"
2.  Minicart icon and quantity counter (if visible) should remain in the same position

### Actual result
1. Minicart icon and quantity counter (*if visible) shift to the left by about a third of the screen

The same problem occurs with other dropdowns such as the currency selector on a multple currency installation. In this case, the currency block all shifts to the left by the width of the dropdown.

Everything works fine on desktop browsers at all screensizes, including mobile sizes. The problem only appears on an ipad using desktop layout (I don't have any other tablets to test on!) and also with iPhone which uses mobile layout . 

Problem is experienced with default installation on luma and blank themes, and even using extension deveopers demo sites!

**Comment by ArthurTransoftgroup** [comment] 2017-07-24 08:19
@wibbel We've created internal ticket MAGETWO-70951 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-09-29 12:30
@wibbel, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-29 12:30 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Format is valid
