### ISSUE TITLE
Applied discount is incorrect after selecting shipping method 

### ISSUE THREAD

**Issue by evs-xsarus** [magento/magento2#36904] opened 2023-02-22 10:16 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1 Open Source

### Steps to reproduce

- create a € 40,- discount on the whole cart incl. shipping with a coupon code
- add 2 configurables to the cart
- apply the rule and confirm a € 40,- discount
- go to the checkout
- Select shipping
- now go back to the cart and change the qty for 1 item to 2

### Expected result

The discount should be € 40,-

### Actual result

The discount is now lower then € 40,- .

### Additional information

This is due to the cartBaseTotals being calculated incorrectly. Not only the configurable prices are summed, but also the previously calculated discount prices set on the simples are added. Thus giving a too high total which leade to incorrect new discount prices.

This will fix it:

```diff
--- a/vendor/magento/module-sales-rule/Model/Validator.php
+++ b/vendor/magento/module-sales-rule/Model/Validator.php
@@ -463,6 +463,7 @@
                 if (!$this->isValidItemForRule($item, $rule)
                     || ($item->getChildren() && $item->isChildrenCalculated())
                     || $item->getNoDiscount()
+                    || ($item->getProductType() === 'simple' && !empty($item->getParentItemId()))
                 ) {
                     continue;
                 }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-22 11:01
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-22 12:55
Hi @evs-xsarus,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- create a € 40,- discount on the whole cart incl. shipping with a coupon code
- add 2 configurables to the cart
- apply the rule and confirm a € 40,- discount
- go to the checkout
- Select shipping
- now go back to the cart and change the qty for 1 item to 2


<img width="1387" alt="Screenshot 2023-02-22 at 4 54 12 PM" src="https://user-images.githubusercontent.com/51680745/220608062-bafe0edd-5bc8-4298-9c16-8add873ffc8e.png">




<img width="1420" alt="Screenshot 2023-02-22 at 5 02 17 PM" src="https://user-images.githubusercontent.com/51680745/220608303-5c66c6e8-3990-43c5-a80e-09c65505c84a.png">




There is no change in the discount after selecting shipping method and updating quantity of the product.Discount is 40$.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-06 04:45
Hi @evs-xsarus,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-06 04:45 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
