### ISSUE TITLE
Price Filter not showing when using elastic search 6+

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#25258] opened 2019-10-24 05:52 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Elasticsearch 6+

### Steps to reproduce (*)

1. Enable Elasticsearch 6+
2. See Category page layered navigation

### Expected result (*)

1. Price filter must show

### Actual result (*)

1. Price filter is missing

**Comment by engcom-Charlie** [comment] 2019-10-25 13:37
Hello @vijay-prevaj 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

**Manual testing scenario:**
1. Enable Elasticsearch 6+
![image](https://user-images.githubusercontent.com/51680850/67575250-cc5d1580-f744-11e9-8386-62a8ae70ba8a.png)
2. Create some products with different prices and assign it to one category
3. Go to the frontend at category page
4. Check for price filter

**Actual result:**
Price filter exist.
![image](https://user-images.githubusercontent.com/51680850/67575199-b6e7eb80-f744-11e9-9ac4-8f1b9bef2d04.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-25 13:37 UTC
Labels: Issue: Format is valid

**Comment by vijay-prevaj** [comment] 2019-10-29 05:44
Sorry for the inconvenience, @engcom-Charlie the issue occur when "Price Navigation Step Calculation" is set to "Automatic (equalize product counts)" please see the screenshot below :

![Configuration   Settings   Stores   Magento Admin   World of Watches](https://user-images.githubusercontent.com/34272427/67740743-e3e61800-fa3c-11e9-8103-477073d00d00.jpg)


![Configuration   Settings   Stores   Magento Admin   World of Watches (1)](https://user-images.githubusercontent.com/34272427/67740820-2c053a80-fa3d-11e9-9559-45456e3a3845.jpg)

**Comment by vijay-prevaj** [comment] 2019-10-29 05:56
@engcom-Charlie Please also change the status ones it reproduce in magento instance.

Thank You.

**Comment by engcom-Charlie** [comment] 2019-10-29 12:05
Hello @vijay-prevaj 
I am still can't reproduce this issue with this configuration:
![image](https://user-images.githubusercontent.com/51680850/67753879-1ba18f80-fa3e-11e9-80f2-919470074ea1.png)
**Result:**
![image](https://user-images.githubusercontent.com/51680850/67753904-265c2480-fa3e-11e9-9468-451e6eb36ffd.png)

You can try to change value of `Interval Division Limit`(if you have less than 9 products at category).
