### ISSUE TITLE
Shipping settings use default

### ISSUE THREAD

**Issue by Corefix** [magento/magento2#6045] opened 2016-08-08 10:10 UTC
### Preconditions

1. Magento 2.1 
2. Chrome 51.x 
3. Mac OS X 10.11
### Steps to reproduce

1. Go to Magento admin System > Configuration
2. Got to a website (fx example main website if nothing else is configured)
3. Go to Shipping Methods
4. Select Flat rate
5. Select Ship to Applicable Countries and choose specific countries
6. Choose a country from the list that is now useable
7. Save
### Expected result

1. The use default on Ship to specific countries should be unchecked since it allows me to select a specific one
### Actual result

1. The countries are "greyed out" and the use default checkbox is still checked

This is a minor issue noticed it while setting up shipping rates I attached a screenshot so you can see the result I'm getting right after selecting specific countries.

The use default checkbox is checked but I can still edit the list, leaving me to belive that this will be saved.

![screen shot 2016-08-08 at 12 09 56](https://cloud.githubusercontent.com/assets/16081779/17476608/2041c992-5d61-11e6-8789-0430aef21e28.png)

**Comment by SerhiyShkolyarenko** [comment] 2016-09-06 08:38
Thank you for the report. Our internal issue is MAGETWO-58067

**Comment by magento-engcom-team** [comment] 2017-09-20 22:30
@Corefix, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:30 UTC
Labels: Issue: Ready for Work, bug report, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
