### ISSUE TITLE
Advance reporting  issue in magento 2.3.3

### ISSUE THREAD

**Issue by deepakpant91** [magento/magento2#28600] opened 2020-06-07 18:17 UTC
### Preconditions (*)

1.version 2.3.3
2.

### Steps to reproduce (*)

1. I have added Magento Analytics and advance reproting is also enabled.
2.

### Expected result (*)

1. Advance reporting will work.
2.

### Actual result (*)

1. There is 401 error.And i am unable to see advance reporting.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sambath1293** [comment] 2020-06-08 06:22
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-06-08 06:22
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-06-08 06:24
Hi @sambath1293, here is your [Magento instance](https://i-28600-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-28600-2-3-3.instances.magento-community.engineering/admin_e1b6](https://i-28600-2-3-3.instances.magento-community.engineering/admin_e1b6)
Login: `bc00acbb` Password: `a3ad0545cab0`
Instance will be terminated in up to 3 hours.

**Comment by sambath1293** [comment] 2020-06-08 06:36
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-08 06:36
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-08 06:38
Hi @sambath1293, here is your [Magento instance](https://i-28600-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28600-2-4-develop.instances.magento-community.engineering/admin_2dc2](https://i-28600-2-4-develop.instances.magento-community.engineering/admin_2dc2)
Login: `a48e8638` Password: `9e1c012be23d`
Instance will be terminated in up to 3 hours.

**Comment by MobiphoneNL** [comment] 2020-06-08 13:10
Hi, Im having issues with advanced reporting as well and I thought to share some stuff I found out which might be useful to you. 
First of all, the call to rjmetrics server uses a OneTimePass(OTP) so if you first get a 404 and then refresh the page you will get 401. So it might be due to you refreshing the page after a 404. If that it not the case then I would advise you to check the the Integrations settings. There should be a "Magento Analytics user" with Analytics>API resources allowed. 

You can test whether it works by calling the Magento 2 API ```/V1/analytics/link``` endpoint with the Magento Analytics Users acces token in the header. The response should be an initialization vector and the data.tgz file. If it does not work, try to reauthorize and try the API call again. 

If you can verify that it works, or does not work, you might get closer to the actual solution. I hope this helps a little bit, if you have any questions feel free to ask.

**Comment by sambath1293** [comment] 2020-06-10 11:03
@deepakpant91  -This issue is a duplicate of #24180
moving this ticket to closed.

**Closed as completed by sambath1293** 2020-06-10 11:03 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.3
