### ISSUE TITLE
GraphQl. Retrieve customer's shopping cart without an authorization token

### ISSUE THREAD

**Issue by atwixfirster** [magento/magento2#28040] opened 2020-04-29 11:29 UTC
### Preconditions (*)

1. Sample data
2. Login as `Veronica Costello`
3. Add any product(s) into a shopping cart

### Steps to reproduce (*)

1. Copy `PHPSESSID` value from a browser window

<img width="1384" alt="27373-01" src="https://user-images.githubusercontent.com/13585327/80591103-c44c9e00-8a25-11ea-96f4-116b3b76826a.png">

2. Set `PHPSESSID` in a header 

<img width="1211" alt="27373-02" src="https://user-images.githubusercontent.com/13585327/80591123-cd3d6f80-8a25-11ea-9211-84aa97fa6c70.png">

3. Run the next GraphQL query to retrieve a customer's cart
```
{
  cart(cart_id: "kSjlU0dTeaH9CUuaRGFSUTOejwTN9ZLn") {
    id
    items {
      id
      quantity
      product {
        sku
      }
    }
  }
}
```

### Expected result (*)

1. GraphQl should use an Authorization token (`Bearer`) ONLY to retrieve a customer's cart.

<img width="1057" alt="27373-04" src="https://user-images.githubusercontent.com/13585327/80591686-c531ff80-8a26-11ea-9c94-0e43f6ed3d26.png">

### Actual result (*)

1. Guest sees products which customer has been added into shopping cart. 

<img width="1062" alt="27373-03" src="https://user-images.githubusercontent.com/13585327/80591140-d595aa80-8a25-11ea-954e-db5a419b1789.png">

**Comment by atwixfirster** [comment] 2020-04-29 11:30
Fix provided in https://github.com/magento/magento2/pull/27373

**Comment by lenaorobei** [comment] 2020-04-30 15:51
Confirmed with PO that is was a requirement to support both - token and session.
Sorry, but I need to close this issue.

**Comment by slavvka** [comment] 2020-06-05 15:40
Hi @atwixfirster. Thank you for your report. 
The issue has been fixed in magento/magento2#27373 by @atwixfirster in 2.4-develop branch
Related commit(s):
 - [b96c8e9c647dbb5182c64d7b25abc1a5299388a1](https://github.com/magento/magento2/commit/b96c8e9c647dbb5182c64d7b25abc1a5299388a1)
 - [41f6a6ef9392e8bc969fb0b8c359db627f170d0b](https://github.com/magento/magento2/commit/41f6a6ef9392e8bc969fb0b8c359db627f170d0b)

The fix will be available with the upcoming 2.4.1 release.

**Comment by jesse-deboer** [comment] 2022-01-21 13:10
Hi @slavvka, why is this fixed as a bug while @lenaorobei confirmed this was a requirement?

Now it's not possible to combine GraphQL calls that need a `bearer` token with `basic-auth` for a staging environment, right?

**Comment by atwixfirster** [comment] 2022-01-21 13:46
> Now it's not possible to combine GraphQL calls that need a `bearer` token with `basic-auth` for a staging environment, right?

Hi, @jesse-deboer !

We used `Bearer` with enable `Basic Auth` without any issues.

And yes, @lenaorobei  has provided the expected result here, so I believe your PR is correct one.

Thanks

**Comment by cpartica** [comment] 2022-02-08 15:52
The way GQL works now is that we support both Session and Token - any would count for accessing authenticated content.
It is the product intention to phase out "session" support, but there are two problems with this:
- one is that since it's supported, there are clients that depend on it
- removing sessions (and we have tried) caused misbehavior of some capabilities that gathered their data from the actual session like "Tax".

**Comment by engcom-Lima** [comment] 2022-09-15 09:38
@magento give me 2.4-develop instance

**Closed as completed** 2022-09-29 07:51 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Component: CustomerGraphQl, Priority: P1, Severity: S0, Triage: Done, Progress: done, Area: APIs
