### ISSUE TITLE
magento 2.1.9 not showing correct paging for configurable products in list

### ISSUE THREAD

**Issue by whereowareadmin** [magento/magento2#12553] opened 2017-12-05 15:22 UTC
### Preconditions

1.  I am using centos 7.4, php 7.0.2, mysql 5.6
2. 

### Steps to reproduce

1.  create configurable products based on swatches, make sure your associated products to configurable products visibility: Search only. not Not Visible or Catalog, Search
2.  create a category page from the menu.

### Expected result

1. the listing should show the correct number of pages. that means to count the pages considering the configurable product as 1 product only. you can only see the associated product while going in the product page as I made associated product visibility: search only. and these associated products should not be counted while creating paging.

### Actual result

1. [Screenshot, logs]
1. it does count the associated products while creating paging, while it is visibility: Search.

http://ellis.cnfei.com/category/decor.html

check on this page "6" Mini Canvas Art" is my configurable product.

**Comment by magento-engcom-team** [comment] 2017-12-05 16:52
@whereowareadmin, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-05 16:52 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by whereowareadmin** [comment] 2017-12-05 17:35
Hi, you will not fix it with Magento 2.1.9 then? it looks like on my ongoing development I will have to upgrade Magento? please let me know what are the possible changes I copy from 2.2.1 and fix it on 2.1.9?
