### ISSUE TITLE
Magento v 2.4.2: Console errors occur when data attribute column is clicked in All Customers grid

### ISSUE THREAD

**Issue by vitaliiyz** [magento/magento2#33091] opened 2021-05-27 13:40 UTC
Preconditions:
1. User with birthday date is created

Steps to reproduce:
1. Go to admin > Customers > All Customers
2. Open browser console
3. Open Columns settings
4. Click Date of Birth column

Expected result: There are no errors in browser console

Actual result: Errors appear in browser console (![image](https://user-images.githubusercontent.com/70089162/119835967-00dd1880-bf0a-11eb-9e6d-f270186c20eb.png))

**Comment by krishprakash** [comment] 2021-05-28 04:30
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-05-28 04:50
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42487` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vlmed** [comment] 2021-06-29 12:59
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-06-12 04:49
Hi @vitaliiyz,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1378" alt="Screenshot 2024-06-12 at 10 18 26" src="https://github.com/magento/magento2/assets/51680745/ebea01f3-be99-4180-a37b-6e83fb65792d">


There are no errors in browser console

Hence we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2024-06-12 04:49 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done
