### ISSUE TITLE
PayPal express checkout issue in Magento 2.3.6

### ISSUE THREAD

**Issue by brianrootways** [magento/magento2#31105] opened 2020-12-01 07:07 UTC
### Preconditions (*)

1.  Magento 2.3.6

### Steps to reproduce (*)

1. While doing checkout with PayPal express for some seconds I am getting an error something went wrong with your request. Please try again later. and redirect to PayPal after some seconds.

Earlier we are using Magento version 2.3.5-p2 but we are getting same issue we have upgrade Magento version to 2.3.6 but face same issue.

### Expected result (*)

1. Customer should be redirected to PayPal without any error.

### Actual result (*)

 ![paypal-error](https://user-images.githubusercontent.com/68637204/100707845-55775f00-33d1-11eb-984f-8b5631d064d1.jpg)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2020-12-01 09:19
PayPal has deprecated the express checkout support, setting this issue to one side it might be better to switch across to one of the other implementations in the long term anyway.

[https://docs.magento.com/user-guide/payment/paypal-express-checkout.html](url)

**Comment by kestraly** [comment] 2020-12-01 20:13
Hosted solution is awful. Forever going wrong and both Payments Standard and Hosted created Pending Payment orders. What a nightmare those payment methods are.

**Comment by devchris79** [comment] 2020-12-02 09:53
@kestraly You need to set the payment action to sale (it should be the default in my opinion). If you have it set to authorization it will be problematic as you describe.

**Comment by brianrootways** [comment] 2020-12-02 12:37
Is there any patch for this issue?

**Comment by brianrootways** [comment] 2020-12-02 12:39
I think issue because of customer-data.js error. Please check attached screenshot. 
![image](https://user-images.githubusercontent.com/68637204/100873621-73c08600-34c9-11eb-8368-d44012c6bce1.png)

**Comment by aloupfor** [comment] 2020-12-07 14:45
I am facing the same issue on Magento ver. 2.3.5-p2.
Issue seems to already have been reported: https://github.com/magento/magento2/issues/28092 but no information about a fix has been provided.

---

I am able to produce the issue on Firefox 78.5.0esr.

After click on `Continue to PayPal` button, following message is displayed in Magento checkout before reaching paypal page:

```
Something went wrong with your request. Please try again later.
```

Console:
```
Uncaught Error: [object Object]
    getFromServer .../Magento_Customer/js/customer-data.min.js:1
    fire .../_cache/merged/3edb8bcff9d69f5781448484e25fa3b1.min.js line 166 > Function:214
    fireWith .../_cache/merged/3edb8bcff9d69f5781448484e25fa3b1.min.js line 166 > Function:220
    done .../_cache/merged/3edb8bcff9d69f5781448484e25fa3b1.min.js line 166 > Function:630
    callback .../_cache/merged/3edb8bcff9d69f5781448484e25fa3b1.min.js line 166 > Function:657
customer-data.min.js:1:1598
```

Stack trace:
```
getFromServer (.../Magento_Customer/js/customer-data.min.js:formatted#58)
reload (.../Magento_Customer/js/customer-data.min.js:formatted#186)
<anonymous> (.../Magento_Customer/js/customer-data.min.js:formatted#231)
handlers (source-server0.conn1.child2/source2753#340)
add (source-server0.conn1.child2/source2753#313)
trigger (source-server0.conn1.child2/source2753#334)
trigger (source-server0.conn1.child2/source2818#56)
done (source-server0.conn1.child2/source2753#632)
createActiveXHR (source-server0.conn1.child2/source2753#657)
```

I am seeing two requests without a status:
- `/V1/guest-carts/token/totals`
- `/customer/section/load/`

I am also seeing that call to `reload` is made by:
```
  $(document).on('ajaxComplete', function (event, xhr, settings) {
    var sections,
    redirects;
    if (settings.type.match(/post|put|delete/i)) {
      sections = sectionConfig.getAffectedSections(settings.url);
      if (sections) {
        customerData.invalidate(sections);
        redirects = [
          'redirect',
          'backUrl'
        ];
        if (_.isObject(xhr.responseJSON) && !_.isEmpty(_.pick(xhr.responseJSON, redirects))) {
          return;
        }
        customerData.reload(sections, true);
      }
    }
  });
```
where `settings.url` equals:
```
.../V1/guest-carts/*******/set-payment-information
```


---

I am unable to produce issue on Chrome 85.0.4183.102.

Requests:
- `/V1/guest-carts/*******/totals`
- `/customer/section/load/`

have a status 200.

**Comment by brianrootways** [comment] 2020-12-10 12:15
@aloupfor  Let me know if you find any solution for this error.

**Comment by cengizcoskun** [comment] 2020-12-30 20:49
I have same problem.

**Comment by engcom-Delta** [comment] 2021-01-25 08:55
Hi @brianrootways thank you for your report, I'm not able to reproduce issue by steps you described on clean 2.4-develop
**Manual testing scenario:**

- Configure PayPal Express Checkout with Sandbox Mode = Yes
- Create customer
- Add product to cart 
- Go to checkout page
- Select  PayPal Express Checkout
- Click on PayPal button

**Result:**
:heavy_check_mark: Modal window for login into paypal is shown
![Peek 2021-01-25 10-44](https://user-images.githubusercontent.com/51681379/105682610-57eec480-5efb-11eb-9510-b36270d7f0a0.gif)
:heavy_check_mark: Order is placed successfully
![image](https://user-images.githubusercontent.com/51681379/105682126-b6677300-5efa-11eb-9f0f-bf50e80f283a.png)

If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2021-01-25 08:55 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.6

**Comment by cengizcoskun** [comment] 2021-02-06 15:37
I use "PayPal All-in-One Payment Solutions" and still same problem..

**Comment by pixiemediaweb** [comment] 2021-02-27 11:54
I've just had this issue with 2.3.6 - turned out CURL needed an update on the server.   You can test by logging into the server as root and running;

curl -v -s https://api-3t.sandbox.paypal.com/nvp

If this fails, update curl

yum update curl  (if you're in a centos environment)

Hope this helps someone.

**Comment by hewgim** [comment] 2021-03-04 09:36
Hi there, we are having the same issue, and are also getting the message "Something went wring with your request. Please try again later." However, I think the original creator of the ticket may be using Paypal standard rather than Paypal Express as we are. The original screenshot shows a terms and conditions link just above the Continue to Paypal button. I dont think you see this on Paypal express. On paypal express you get redirected back to a review page on the magento website where you accept the terms and coniditions

@engcom-Delta I don't you were testing the same scenario. Your screenshot shows a big yellow paypal express button which suggests you were testing Paypal express with in-context experience turned on. That's different to the screenshot uploaded by the original creator. To test, try turning on paypal standard instead. Use firefox and go through the magento checkout process. When you click on the "Continue to Paypal" button you hopefully will see the error.

**Comment by brianrootways** [comment] 2021-03-04 09:41
@hewgim  Yes, exactly we are facing issue only in Firefox. Need to checkout with PayPal express. Let us know if you fix this issue.

**Comment by Daisy1302** [comment] 2021-03-29 08:27
Hi team, 

I'm working with Magento 2 ver 2.3.5-p2 and still facing this issue on Firefox.

**Comment by chequille** [comment] 2021-04-26 07:27
It is a shame, that nobody is aible to fix this, as it is still within 2.4.x
Sorry guys, there must be somebody who can fix this!!! Or not?

**Comment by gianisimone** [comment] 2021-05-12 14:13
Still getting the error with 2.3.7. Unbelievable!!!!! My store is useless as I cannot receive payments.
It is simply ridiculous!!

**Comment by Ckaneriya** [comment] 2021-07-09 04:45
@engcom-Delta  Most of the people facing this issue then why it is closed. we have noticed this issue in several of our Magento 2.3.6 stores. one of our stores is in default luma theme with only 2 demo products. no customization has been done still we are facing a similar issue.

**Comment by baseplayer** [comment] 2022-12-01 14:46
I have 2.3.7 and still have this problem, sometimes it works and other times money comes in and the order is not to be found in magneto?

I do not understand why magento 2 always has bugs that are never solved|? this cost thousands of euros

**Comment by ziofonta** [comment] 2024-01-18 14:26
still the same problem randomly. we have Magento 2.4.6-p1. At least twice a day a customer calls our customer service because he cannot complete the payment with his credit card.... It is becoming embarassing for us...

**Comment by ziofonta** [comment] 2024-01-18 14:29
also, why these error are not logged anywhere? I checked payment.log, system.log, exception.log... nothing there.
