### ISSUE TITLE
magento/composer is locked to 1.6.0

### ISSUE THREAD

**Issue by drpayyne** [magento/magento2#34029] opened 2021-09-08 18:20 UTC
### Preconditions (*)
1. Install Magento 2.4.3 EE using composer

### Steps to reproduce (*)
1. Run `composer why magento/composer`

### Expected result (*)
1. `magento/composer` should not be locked to `1.6.0`, but rather be constraint to `^1.7`, for example.

### Actual result (*)
1. `magento/composer` is locked to `1.6.0`, which is locking `composer/composer` to `1` instead of `2` available in `magento/composer:1.7.0`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by drpayyne** [comment] 2021-09-08 18:23
This issue prevents `1.7.0` of https://github.com/magento/composer from being installed in Magento 2.4.3 EE. @fascinosum, could you please look into this? I see that you're the one who upgraded `composer/composer` to `2` in this commit - https://github.com/magento/composer/commit/3bd4b3115f8f39671af10e7ec30b335b9742645d

**Comment by fascinosum** [comment] 2021-09-08 18:36
hi @drpayyne,
thank you for you report, I think this is a duplicate of https://github.com/magento/magento2/issues/33681

**Comment by ihor-sviziev** [comment] 2021-09-09 05:47
This is duplicated of https://github.com/magento/magento2/issues/33681.
The issue was already fixed in 2.4-develop, but unfortunately, it wasn't added to the 2.4.3 release.
Here you can find all details + link to workaround that you can use in the meanwhile https://github.com/magento/magento2/issues/33681#issuecomment-892819485.

**Closed as completed by ihor-sviziev** 2021-09-09 05:47 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.3
