### ISSUE TITLE
Subtotal in mini cart does not match with subtotal in shopping cart

### ISSUE THREAD

**Issue by Veorirac** [magento/magento2#33617] opened 2021-07-28 13:13 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Account with two or more added addresses
3. Multishipping Enable

### Steps to reproduce (*)

1. As the customer add two different products to the cart
2. Open Shopping Cart page
3. Click on Check Out with Multiple Addresses Link
4. Select different addresses for products
5. Click Update Qty & Addresses button
6. Click Back to Shopping Cart button
7. Change qty for one of product from 1 to 2
8. Click Update Shopping Cart button
9. Open mini cart

### Expected result (*)

1. The cart subtotal in the mini cart should be calculated by price and quantity of items

### Actual result (*)

1. The cart subtotal in the mini cart calculated by price and quantity of items multiplied by two
![chrome_fTJLGybVe1](https://user-images.githubusercontent.com/68002645/127326697-f0e644fb-5076-47ad-b06b-a47c5bcf79d9.png)
![chrome_oUcQi2uumd](https://user-images.githubusercontent.com/68002645/127326729-6fbaa974-6442-42a2-9559-ad6769e964dd.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Veorirac** [comment] 2021-07-28 14:20
@magento I am working on this

**Comment by krishprakash** [comment] 2021-07-29 05:12
@magento give me 2.4-develop instance

**Comment by jmcharadva** [comment] 2021-08-02 09:32
@magento add to contributors team

**Comment by engcom-Bravo** [comment] 2021-08-19 04:33
Hi @Veorirac 

we tried to reproduced this issue on 2.4.develop but were unable to do so

Below are the steps we followed
  1.As the customer add two different products to the cart
  2.Open Shopping Cart page
  3.Click on Check Out with Multiple Addresses Link
  4.Select different addresses for products
  5.Click Update Qty & Addresses button
  6.Click Back to Shopping Cart button
  7.Change qty for one of product from 1 to 2
  8.Click Update Shopping Cart button
  9.Open mini cart

<img width="1319" alt="addedProducts" src="https://user-images.githubusercontent.com/51680745/130008009-52a63b7b-daf1-473d-b947-d097207c4728.png">
<img width="1318" alt="mutltiaddress" src="https://user-images.githubusercontent.com/51680745/130008026-704f135f-f608-4df0-9bbf-2f337a20e888.png">
<img width="1314" alt="update quantity" src="https://user-images.githubusercontent.com/51680745/130008052-e58928ff-6bbd-4e53-88d2-fb7080073cb2.png">
<img width="1317" alt="minicart" src="https://user-images.githubusercontent.com/51680745/130008061-c001f864-f63b-482e-8b9e-f9c3894bfebd.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

**Comment by engcom-November** [comment] 2021-09-09 09:49
Hi @Veorirac ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-09 09:49 UTC
Labels: Issue: needs update
