### ISSUE TITLE
Magento 2 checkout issue 

### ISSUE THREAD

**Issue by wclansar** [magento/magento2#4187] opened 2016-04-18 09:52 UTC
Hello , 

When i go in checkout page i am getting one error notice.

Recoverable Error: Object of class Magento\Customer\Model\Data\Region could not be converted to string in /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2903

Can you please help to resolve that issue.

Thanks

**Comment by wclansar** [comment] 2016-04-18 10:48
Here you go for screen shot .
![checkout error](https://cloud.githubusercontent.com/assets/10025094/14601690/33a37702-0581-11e6-9d12-29857e23082b.jpeg)

**Comment by ishakhsuvarov** [comment] 2016-04-18 11:44
@wclansar Hi, thank you for reporting. Do you have any customizations on your Magento installation? Please provide more detailed preconditions and steps to reproduce.

**Comment by piotrekkaminski** [comment] 2016-05-24 05:20
Closing due to lack of updates. @wclansar if you still experience this issue please create a new report.

**Closed as completed by piotrekkaminski** 2016-05-24 05:20 UTC
Labels: Progress: needs update, Issue: Format is not valid

**Comment by phronesis** [comment] 2016-06-20 18:19
I have experienced same:
Recoverable Error: Object of class Magento\Customer\Model\Data\Region could not be converted to string in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2903 in /var/www/releases/d-GOG2F8Y2G/vendor/magento/framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/releases/d-GOG2F8Y2G/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/releases/d-GOG2F8Y2G/vendor/magento/module-webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/releases/d-GOG2F8Y2G/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/releases/d-GOG2F8Y2G/vendor/magento/framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/releases/d-GOG2F8Y2G/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/releases/d-GOG2F8Y2G/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))

**Comment by ankitce** [comment] 2016-10-20 10:39
We are experiencing the same error when region field is not mandatory.

In order to reproduce the error, 
1. Set a country as an allowed country which expects no 'region' information in the address structure.
2. Create a customer who belongs to the country specified in step 1.
3. Add some products in cart and go to checkout page.
4. The error!!!  `Recoverable Error: Object of class Magento\Customer\Model\Data\Region could not be converted to string in /vendor/magento/framework/DB/Adapter/Pdo/Mysql.php`

**Comment by somat211** [comment] 2016-10-20 13:47
We are facing the same error when the customer address has not region. We have also checked on Magento 2 live Demo at http://magento2-demo.nexcess.net/ We have created a customer address without the region. We have tried to place orders and it shows the only Order Summary on checkout page.
You can check with below Customer Address:
First Name *: Test
Last Name  *: Test
Street Address *: Test Address
Company : 
Company *: Dubai
State/Province : 
Phone Number \* : 
Fax : 
Country \* : United Arab Emirates

**Comment by birchestx** [comment] 2016-11-09 09:24
This needs re-opening and resolving. At the moment you only support countries with regions. Its pretty clear bug and affecting all UK magento 2 installs.

**Comment by johnhughes1984** [comment] 2016-11-09 09:44
We've come across this issue too (we're UK based) and needs addressing as @wsakaren has said

**Comment by pboisvert** [comment] 2016-11-09 22:42
Hey All. Apologies if this issue in ongoing for some of you. This issue was CLOSED back in May when the original reporter failed to respond to requests for more information. We try to reproduce issues as reported and when we cannot we ask for more information. If anyone is STILL having this issue, the proper action to take is to open a new issue and you can reference back to the closed issue if it contains any useful information. In this was we have an active issue and someone to contact for more details if we cannot reproduce the issue. thanks

**Comment by friimaind** [comment] 2017-11-24 17:19
Reopened https://github.com/magento/magento2/issues/12436
