### ISSUE TITLE
Headless/API/GraphQL operations are not locked (order can be placed twice)

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#36417] opened 2022-11-03 16:32 UTC
### Preconditions and environment

- any Magento 2 version
- headless installation (when front app works with backend API)

### Steps to reproduce

1. open https://venia.magento.com/ or use any other headless installation
2. add any product
3. proceed to checkout
4. fill data
5. use chekmo or any other offline payment
6. proceed to review order step without placing the order
7. extract cart-id from local-storage or network log
8. extract store_code from network log
9. Adjust the script below with your values 
10. Execute script in browser console

```
var myHeaders = new Headers();
myHeaders.append("store", "default");
myHeaders.append("Content-Type", "application/json");

var graphql = JSON.stringify({
    query: "  mutation placeOrder($cartId: String!) {\n   placeOrder(\n     input: {\n       cart_id: $cartId\n     }\n   ) {\n         order {\n             order_id\n         }\n   }\n }\n ",
    variables: {"cartId":"11K35ZN5VR7cTEcqFsR6eGfJtbZA80Ed"}
})
var requestOptions = {
    method: 'POST',
    headers: myHeaders,
    body: graphql,
    redirect: 'follow'
};

fetch("https://venia.magento.com/graphql", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));

fetch("https://venia.magento.com/graphql", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));
//you can add more ;)
```

### Expected result

1. Order is placed once
2. Additional requests are rejected by backend

### Actual result

1. Order is placed twice
![Selection_156](https://user-images.githubusercontent.com/3192770/199776522-f898d9ef-c8df-4b87-8924-eff7bc474282.png)
2. got 2 emails
![Selection_157](https://user-images.githubusercontent.com/3192770/199776629-c8fc58f9-66f9-4edd-bd19-114f1c7dee3f.png)
3. Both orders assigned to same cart_id

### Additional information

You can try this trick with any other mutation.
e.g. add asynchronously same product to cart or change qty or anything else
API does not lock any operations. So if frontend sends a few requests simultaneously it leads to unexpected results.
API mutations must be locked.

### Release note

Now API mutations locked and prevent unexpected behavior when a few requests received simultaneously in headless installation.
  

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rodrigowebjump** [comment] 2022-11-03 20:18
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-11-04 07:55
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-11-04 11:22
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch and also on venia website.

**Description:** Headless/API/GraphQL operations are not locked (order can be placed twice)

**Pre-requisite:**
- Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**
1. Open https://venia.magento.com/ or use any other headless installation
2. Add any product
3. Proceed to checkout
4. Fill data
5. use chekmo or any other offline payment
6. proceed to review order step without placing the order
7. extract cart-id from local-storage or network log
8. extract store_code from network log
9. Adjust the script below with your values
10. Execute script in browser console
```
var myHeaders = new Headers();
myHeaders.append("store", "default");
myHeaders.append("Content-Type", "application/json");

var graphql = JSON.stringify({
    query: "  mutation placeOrder($cartId: String!) {\n   placeOrder(\n     input: {\n       cart_id: $cartId\n     }\n   ) {\n         order {\n             order_id\n         }\n   }\n }\n ",
    variables: {"cartId":"11K35ZN5VR7cTEcqFsR6eGfJtbZA80Ed"}
})
var requestOptions = {
    method: 'POST',
    headers: myHeaders,
    body: graphql,
    redirect: 'follow'
};

fetch("https://venia.magento.com/graphql", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));

fetch("https://venia.magento.com/graphql", requestOptions)
    .then(response => response.text())
    .then(result => console.log(result))
    .catch(error => console.log('error', error));
//you can add more ;)
```
**Expected result:** 
1. Order is placed once
2. Additional requests are rejected by backend

**Actual result:** Order placed twice with same cart id
**Screenshots:**
<img width="1488" alt="Screenshot 2022-11-04 at 1 17 54 PM" src="https://user-images.githubusercontent.com/60198022/199960796-29ec2269-c4f1-4e5d-a298-6503aca7c957.png">

<img width="1493" alt="Screenshot 2022-11-04 at 1 18 28 PM" src="https://user-images.githubusercontent.com/60198022/199960827-f3b4a039-8b42-4f7b-9f81-626236fc3232.png">

<img width="1489" alt="Screenshot 2022-11-04 at 4 10 44 PM" src="https://user-images.githubusercontent.com/60198022/199960865-e51b9b46-3f06-4471-af0c-df571aa5ab93.png">

**Comment by ilnytskyi** [comment] 2022-12-06 09:36
Maybe for orders partial fix would be here https://github.com/magento/magento2/pull/29854 but any other API operations are not locked

**Comment by Den4ik** [comment] 2023-02-07 22:22
Looks like issue closed by mistake. I reopen it

**Comment by engcom-Alfa** [comment] 2023-03-07 06:25
Hey @ilnytskyi,

as per discussion with the internal team, we retested the ticket on the latest package 2.4.6 beta11 of Magento along with the latest PWA bundle, we are not able to reproduce the issue.

![image](https://user-images.githubusercontent.com/51679138/223338134-9299941b-3ebe-4ddc-95d5-a67bf17b7db9.png)

hence request to try running the test on the latest environment of Magento and PWA.

Thanks

**Comment by ilnytskyi** [comment] 2023-03-31 08:33
@engcom-Alfa

Looks like it's fixed for order placement

mutex in graphql:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Resolver/PlaceOrder.php#L83

direct lock usage in API:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/QuoteManagement.php#L623

However: 

The GQ lock name https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Cart/PlaceOrderMutex.php#L19

differs form API lock name:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/QuoteManagement.php#L55

Looks like with proper timing still possible to place order via API and GraphQL.

The issue also mentions that no API or GraphQL mutations are locked. So the problem might still be applicable to cases like.

- adding products to cart in concurrent requests
- adding coupon to cart in concurrent requests
- setting payment method to cart in concurrent requests (will create two records of payment id DB)
- merging two carts in concurrent requests
- setting email and billing address  in concurrent requests
- more other cases and combinations possible

might also be related to https://github.com/magento/magento2/pull/29854

**Comment by engcom-November** [comment] 2023-04-13 09:43
Hi @ilnytskyi ,
As the older issue reported with steps mentioned in the description is no more reproducible on 2.4-develop instance, we are closing this issue. Kindly create new issue with updated / new steps to reproduce if the issue is still reproducible.
Thank you.

**Closed as completed by engcom-November** 2023-04-13 09:43 UTC
Labels: Component: Catalog, Priority: P1, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Cart & Checkout
