### ISSUE TITLE
Updating price of configurables does not update price in quote tables -> results in 503 error when customer tries to login

### ISSUE THREAD

**Issue by Muhamann** [magento/magento2#34217] opened 2021-10-01 08:18 UTC
Hello,

i refer back to this issues:
https://github.com/magento/magento2/issues/6144
https://github.com/magento/magento2/issues/33921

They are closed, but now i could reproduce it.

**ISSUE:**
Changing a price of a configurable does NOT update the quote tables.
Prices in table "quote_item" are not updated AND quote grand total etc. is not updated in table "quote".
This results in an error 503, when a customer wants to login.
Only current solution is to delete the specific quote-table entry.

**REPRODUCTION:**
Change a price of a CONFIGURABLE (so a product which has a parent), like this:

First add parent Produkt P and make it a configurable with child product C.
Then login as a customer and add this product C to cart. Logout.

Then change price of product C with this code line:
`$productC->setPrice(100);`

After that, try to login again with this customer. It will fail and result in a 503 error.
Then compare the quote table data of "quote_item" and "quote" with the new price. The new price has not updated in quote tables.

Thank you,
Muhamann

**Comment by Muhamann** [comment] 2021-10-06 14:20
@m2-community-project

@m2-assistant

@magento I am working on this


 @engcom-Echo can you check this again like in the closed issue?

**Comment by engcom-Lima** [comment] 2021-10-11 11:02
Hi @Muhamann,

Thank you for reporting the issue.

However, I am not able to reproduce it on Magento 2.4-develop instance. Here is what I did to reproduce it:
1. I created a configurable product with multiple simple products.
2. Logged in as customer and added one of the simple product to cart. Logged out.
3. Changed price of the same simple product from Admin Panel
4. On frontend, logged in again.
5. Checked the cart and the price got updated to the latest one.

Now, what I could not understand from your description is where did you add code`$productC->setPrice(100);` or changed price if not from Admin Panel ? 
Please let me know if you are able to reproduce this Magento 2.4-develop and if you did anything differently than above provided steps ?

**Comment by Muhamann** [comment] 2021-10-12 09:54
> Hi @Muhamann,
> 
> Thank you for reporting the issue.
> 
> However, I am not able to reproduce it on Magento 2.4-develop instance. Here is what I did to reproduce it:
> 
> 1. I created a configurable product with multiple simple products.
> 2. Logged in as customer and added one of the simple product to cart. Logged out.
> 3. Changed price of the same simple product from Admin Panel
> 4. On frontend, logged in again.
> 5. Checked the cart and the price got updated to the latest one.
> 
> Now, what I could not understand from your description is where did you add code`$productC->setPrice(100);` or changed price if not from Admin Panel ? Please let me know if you are able to reproduce this Magento 2.4-develop and if you did anything differently than above provided steps ?

Hello @engcom-Lima ,

thanks for working oin this issue.
But your step 3:

> Changed price of the same simple product from Admin Panel

is wrong.
As i wrote in my reproduction-steps, you have to use:

`$product->setPrice($this->convertPriceValue($artikel['ART_VK1']));`

in a any file. In our case we use this in an import/update cronjob, but this is random. You can just set the price by using the setPrice function in any other php file... 
This does not activate the price-changing process in the quote-tables like it is by changing the price using the admin-panel as in your step 3.

Kind regards,
Roman

**Comment by engcom-Hotel** [comment] 2021-12-24 08:55
Dear @Muhamann,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-24 08:55 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
