### ISSUE TITLE
Unable add category to cart price rule by clicking on checkbox 

### ISSUE THREAD

**Issue by bruvinsky** [magento/magento2#26724] opened 2020-02-06 08:49 UTC
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.2.22

### Steps to reproduce (*)

1. Marketing > Cart Price Rules > Add New Rule
2. Add conditions to Actions: choose "category", click on the ellipsis, see the input field, click "Open chooser", see the category tree
3. Try to add category by clicking checkbox

### Expected result (*)

1. Category ID will appear in the input

### Actual result (*)

```
Uncaught TypeError: Cannot read property 'updateElement' of undefined
    at Ext.tree.TreePanel.Enhanced.<anonymous> (category-checkbox-tree.js:249)
    at Ext.util.Event.fire (ext-tree.js:29)
    at Ext.tree.TreePanel.Enhanced.fireEvent (ext-tree.js:29)
    at Ext.tree.CheckboxNodeUI.check (ext-tree-checkbox.js:193)
    at ext-tree.js:9
    at Ext.tree.TreeNode.expand (ext-tree.js:201)
    at Ext.tree.CheckboxNodeUI.check (ext-tree-checkbox.js:162)
    at El.Flyweight.<anonymous> (ext-tree.js:9)
    at HTMLInputElement.h (ext-tree.js:33)
    at HTMLInputElement.M (legacy-build.min.js:8)
```
![20200206_001](https://user-images.githubusercontent.com/11726895/73920554-4b2e2680-48ce-11ea-9fbd-a9ac34e8d92b.png)

**Comment by bruvinsky** [comment] 2020-02-06 08:54
Looks like a bug long known
https://github.com/magento/magento2/issues/23582

**Comment by krishprakash** [comment] 2020-02-06 09:05
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-06 09:05
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-06 09:06
Hi @krishprakash, here is your [Magento instance](https://i-26724-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26724-2-4-develop.instances.magento-community.engineering/admin_a8a3](https://i-26724-2-4-develop.instances.magento-community.engineering/admin_a8a3)
Login: `74108f4d` Password: `a7edde8c05e8`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-06 09:12
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31172` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hws47a** [comment] 2020-02-06 14:38
Can confirm the issue on multiple projects on 2.3.4

**Comment by sdzhepa** [comment] 2020-04-30 17:30
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-30 17:30
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-30 17:31
Hi @sdzhepa, here is your [Magento instance](https://i-26724-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26724-2-4-develop.instances.magento-community.engineering/admin_ffe4](https://i-26724-2-4-develop.instances.magento-community.engineering/admin_ffe4)
Login: `d97ac09d` Password: `b51e94b2c459`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-04-30 17:43
Hello @hws47a  @krishprakash

I am not able to reproduce the issue on the lates `2.4-develop` branch
Probably it was already fixed and we can close the issue
or I missed some steps 

Here is how I tried: https://www.screencast.com/t/fEqQPbOEXC

**Comment by krishprakash** [comment] 2020-05-01 04:35
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-01 04:35
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-01 04:37
Hi @krishprakash, here is your [Magento instance](https://i-26724-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26724-2-4-develop.instances.magento-community.engineering/admin_aa02](https://i-26724-2-4-develop.instances.magento-community.engineering/admin_aa02)
Login: `a3a93b11` Password: `ff44094860dc`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-05-01 04:46
@hws47a @sdzhepa closing this issue as not able to reproduce on latest latest 2.4-develop branch

**Closed as completed by krishprakash** 2020-05-01 04:46 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: SalesRule, Component: Admin, Reported on 2.3.4

**Comment by johncarlson21** [comment] 2020-05-19 20:32
I'm also having this same issue, but it only happens when the site is in production mode

**Comment by johncarlson21** [comment] 2020-05-19 20:41
So my site is in production and I go to work with a Cart Price Rule, I choose the action of "Category" is not, then I click on the tree button, which pulls up the tree.

Once that is loaded as soon as I click a category I get this error:
`TypeError: options.jsFormObject is undefined category-checkbox-tree.js:249:17
    <anonymous> http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/Magento_Catalog/js/category-checkbox-tree.js:249
    fire http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:29
    fireEvent http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:29
    check http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree-checkbox.js:193
    createDelegate http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:9
    expand http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:201
    check http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree-checkbox.js:162
    createDelegate http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:9
    h http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/extjs/ext-tree.js:33
    M http://m2.du-ha.com/static/adminhtml/Magento/backend/en_US/legacy-build.min.js:8
`

**Comment by bruvinsky** [comment] 2020-05-19 22:00
> I'm also having this same issue, but it only happens when the site is in production mode
@johncarlson21 ,
maybe this fix can be useful as a temporary solution
https://github.com/magento/magento2/pull/26791/commits/9e8a5966b5cc731422a090c5e9d431bee17a8147
or Magento has already fixed in 2.4-develop branch

**Comment by johncarlson21** [comment] 2020-05-20 13:26
@bruvinsky yep.. that fixed it.. thanks.. I must not have seen that above.

**Comment by stupachenko** [comment] 2020-12-22 18:53
Fix from Magento Team https://github.com/magento/magento2/commit/e699d3feb9514ee73c8c0afc3fdb8b5c03ed18d5
