### ISSUE TITLE
Checkout/view/frontend/web/template/billing-address/details.html  tries to join street address fields on undefined value

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#33826] opened 2021-08-17 14:19 UTC
### Preconditions (*)

1. 2.4.3

### Steps to reproduce (*)

1. reach checkout payment step with billing address missing street fields or street field is not a array 

### Expected result (*)

1. no errors displayed , checkout working

### Actual result (*)

1. error logged, all script execution broken 

`Uncaught TypeError: Unable to process binding "text: function(){return currentBillingAddress().street.join(', ') }"`

2. this is caused in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html 

created with a commit by @rostyslav-hymon on following https://github.com/magento/magento2/commit/53b85cce1e95a5cfb60db6dc029e551d053e1f14#diff-e4dcdf0e20375ec650339c4cc63147ff8156a5eb9d2e82e2927d744599d157b5 

3. was working before on 2.4.2 (p1 and p2 included) so probably a mixup of template edited as the change is completely lost on git history for this specific line : https://github.com/magento/magento2/blob/2.4.2/app/code/Magento/Checkout/view/frontend/web/template/billing-address/details.html 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ * ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-08-18 03:45
Is there any solutions for such case ? Highly interesting this issue

**Comment by mrtuvn** [comment] 2021-08-18 03:58
Seem in magento requirejs default use async mode for request scripts

**Comment by ihor-sviziev** [comment] 2021-08-18 06:19
@sivaschenko @sidolov @gabrieldagama, this issue should have p1 prio

**Comment by speedupmate** [comment] 2021-08-18 06:34
> Is there any solutions for such case ? Highly interesting this issue

yes, rewrite/revert in theme scope

**Comment by engcom-Bravo** [comment] 2021-10-21 12:44
@speedupmate Can you please help us from where billing address with missing street fields is added.
As street field is required field.
<img width="780" alt="Screenshot 2021-10-21 at 6 11 21 PM" src="https://user-images.githubusercontent.com/51680745/138279785-526da0e9-a6bb-492b-8c36-ff9c700d13fe.png">

**Comment by engcom-Hotel** [comment] 2021-12-16 07:40
Hi @speedupmate,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop, we didn’t find any error in the checkout and the adding/updating billing address.

Steps followed to reproduce issue:
1. Added product to the cart, started the checkout process.
2. Added new billing address, also tried the existing address. 
3. Able to checkout successfully.
4. Tried to update billing address using the admin panel but the empty address is not allowed(See below-attached screenshot).
<img width="1425" alt="Screenshot 2021-12-13 at 9 18 26 PM" src="https://user-images.githubusercontent.com/51681618/146328584-70d3345b-b1d7-4530-882b-667e83604e0b.png">

<img width="1425" alt="Screenshot 2021-12-13 at 9 27 22 PM" src="https://user-images.githubusercontent.com/51681618/146328592-4c5778be-ba28-495b-976a-76ad93fcb006.png">

<img width="1425" alt="Screenshot 2021-12-13 at 9 27 52 PM" src="https://user-images.githubusercontent.com/51681618/146328594-96853591-80fa-42b3-8159-d9e36491ca10.png">

As we are not able to reproduce this issue, hence closing this issue.

Thanks

**Comment by speedupmate** [comment] 2021-12-16 13:02
@engcom-Hotel 

this is so simple programming ABC I can't even argue here: 

1. if you request a property or method from the object and the object does not exist it will fail so `currentBillingAddress().street` will fail if `currentBillingAddress()` is "null, undefined, false , or does not have the street property". 
2. it was working before and you were spoon fed with the exact line and before and after and pointed to a commit that changes this to be broken

If you can't replicate this then make a condition where you can. Take dev-tools , add a breakpoint , remove the street variable from the object before you hit that line and you are there. This can happen when checkout templates are customised , network has issues as the checkout is not async, it tries to be but the asset loading is still a waterfall and quote object or any object related to it can be undefined, null, object, object with random parameters, object with full parameters, object without methods or full and proper object  dependant on page loading and object init sequence . 

simplest customisation trough layout file is that you reveal the payment methods on first step , just move the xml to first step and you have it 

@ihor-sviziev maybe you can enlighten the team here

**Comment by ihor-sviziev** [comment] 2021-12-16 13:47
Maybe @sdzhepa ?

**Comment by sdzhepa** [comment] 2021-12-17 18:21
@engcom-Hotel 

Could you please review this issue one more time?
also, i noticed that this issue was fixed in the scope https://jira.corp.magento.com/browse/AC-691. PR is created but not merged yet. I assume it means that Issue is reproducible 

So, could you pls investigate the situation and bring more clarity to it?


cc: @ihor-sviziev , speedupmate

**Comment by engcom-Hotel** [comment] 2021-12-20 10:49
Hello @sdzhepa @speedupmate @ihor-sviziev 

We will look into it and get back to you soon.

Thanks

**Closed as completed** 2022-01-17 04:53 UTC
Labels: Component: Checkout, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.3, Area: Cart & Checkout

**Comment by hostep** [comment] 2022-02-01 19:25
Since this issue got closed without info, I searched the commits a bit for a reference that mentions "AC-691" and found this one: https://github.com/magento/magento2/commit/e2e82b0036a2e42f9e5fd2750230e0f09b2e4ec4, hope it helps for people searching for a solution.

**Comment by leonhelmus** [comment] 2022-10-19 14:26
@hostep  was this resolved in 2.4.5?

**Comment by speedupmate** [comment] 2022-10-20 08:03
@leonhelmus yes this is resolved in 2.4.5
