### ISSUE TITLE
Problem with customer account confirmation when changing customer group on registration

### ISSUE THREAD

**Issue by Umfi** [magento/magento2#6273] opened 2016-08-22 12:32 UTC
### Preconditions
1. Magento 2.08 CE
2. Account E-Mail Confirmation activated
3. Write observer on event: customer_register_success

`
$groupId = 2;
objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $customerWithCorrectGroup = $objectManager->create('Magento\Customer\Model\Customer')->load($customer->getId());
        $customerWithCorrectGroup->setGroupId($groupId);
        $customerWithCorrectGroup->save();
`
### This happens:
1. you register an account and the observer sets the group
2. get confirmation email
3. click confirmation-link and see message: "There was an error confirming the account."

**Comment by sevos1984** [comment] 2016-08-26 10:23
Cannot reproduce your issue. I've added customer register observer with following code:
`$groupId = 2;
        $customer = $observer->getEvent()->getData('customer');
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $customerWithCorrectGroup = $objectManager->create(\Magento\Customer\Model\Customer::class)->load($customer->getId());
        $customerWithCorrectGroup->setGroupId($groupId);
        $customerWithCorrectGroup->save();`
Then registered customer and confirmed email. Confirmation was successful and customer assigned to group 2. Could you try update your code to latest release version 2.0.9 and see if it helps? Thanks

**Comment by Umfi** [comment] 2016-08-29 07:00
Hey, i tested in on 2.0.9.. same error...

here the full code:

`
<?php
namespace Company\Module\Observer;

use Magento\Framework\Event\ObserverInterface;

class AfterCustomerSave implements ObserverInterface {

```
protected $_logger;
protected $_customerExtensionFactory;
protected $_customerRepository;
protected $storeManager;
protected $_helper;

public function __construct(
    \Psr\Log\LoggerInterface $logger,
    \Magento\Customer\Api\CustomerRepositoryInterface $customerRepository,
    \Magento\Customer\Api\Data\CustomerExtensionFactory $customerExtensionFactory,
    \Magento\Store\Model\StoreManagerInterface $storeManager,
    \WellLinked\Registration\Helper\Data $helper
) {

    $this->_logger = $logger;

    $this->_logger->addDebug('AfterCustomerSaveObserver_Constructor_Begin');

    $this->_customerRepository = $customerRepository;
    $this->_customerExtensionFactory = $customerExtensionFactory;
    $this->_storeManager = $storeManager;
    $this->_helper = $helper;

    $this->_logger->addDebug('AfterCustomerSaveObserver_Constructor_End');
}

private function getCustomerGroupByCode($code) {
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $groupOptions = $objectManager->get('\Magento\Customer\Model\ResourceModel\Group\Collection')->toOptionArray();

    foreach ($groupOptions as $key => $field) {
        if (strpos($field["label"], $code) !== false) {
            return $groupOptions[$key]['value'];
        }
    }

    //return default group if not found
    return 1;
}

public function execute(\Magento\Framework\Event\Observer $observer) {

    $this->_logger->addDebug('AfterCustomerSaveObserver_Execute_Begin');

    $event = $observer->getEvent();
    $customer = $event->getCustomer();

    $firstName = $customer->getFirstname();
    $lastName = $customer->getLastname();
    $email = $customer->getEmail();
    $title = $customer->getCustomAttribute("bla")->getValue();
    $grad = $customer->getCustomAttribute("blu")->getValue();


    // set to default
    $groupId = 1;

    if(strcmp($this->_storeManager->getStore()->getCode(),"egg") == 0) {
        $groupId = $this->getCustomerGroupByCode("Privatkunde-EGG");
    } else {
        $groupId = $this->getCustomerGroupByCode("Privatkunde-SGG");
    }


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerWithCorrectGroup = $objectManager->create('Magento\Customer\Model\Customer')->load($customer->getId());
    $customerWithCorrectGroup->setGroupId($groupId);
    $customerWithCorrectGroup->save();


    // build an object... not full code here
    $register = new Register($person);


    //Initiate cURL.
    $ch = curl_init("http://" . $_SERVER['HTTP_HOST'] . ":9990/user/register");
    $jsonDataEncoded = json_encode($register);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
    $result = curl_exec($ch);

    $this->_logger->addDebug('AfterCustomerSaveObserver_Execute_End');
}
```

}

`

But on confimation of email: 
![image](https://cloud.githubusercontent.com/assets/13978552/18043258/fcdf8e78-6dc6-11e6-93a1-8dd81a9f8a45.png)

EDIT: I have added a custom event to the execute function in 
https://github.com/magento/magento2/blob/2.0.9/app/code/Magento/Customer/Controller/Account/Confirm.php

but this shouldn't be a problem
`
 $this->_eventManager->dispatch(
                'customer_confirmation_success',
                ['account_controller' => $this, 'customer' => $customer]);
`

**Comment by sevos1984** [comment] 2016-10-31 11:18
Have you tried upgrading to latest release version?

**Comment by Umfi** [comment] 2016-10-31 11:22
i used an workaround to fix this problem.
using plugin: aroundExecute() of \Magento\Customer\Controller\Account\Confirm

**Comment by sevos1984** [comment] 2016-11-01 09:51
Could you create a pull request for this?

**Comment by sevos1984** [comment] 2016-11-28 14:21
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-28 14:21 UTC
Labels: bug report, Component: Customer
