### ISSUE TITLE
Compilation error when processing anonymous functions.

### ISSUE THREAD

**Issue by konstanchuk** [magento/magento2#9415] opened 2017-04-26 21:49 UTC
### Preconditions

Using Magento 2.1.3 with sample data and PHP 7.0.15

### Steps to reproduce

Create a simple php file in the root folder of the module. For example app/code/VendorName/ModuleName/custom_script.php
Put the following code in the file:
```
<?php
$function = function () {
    echo 'Hello Magento!';
};
```
Run the command: php bin/magento setup:di:compile

### Actual result
![2017-04-27 00-47-08](https://cloud.githubusercontent.com/assets/9463474/25458615/3f4c0622-2ae3-11e7-95e3-f41fbf6af672.png)

### Expected result
Compilation finishes without errors

**Comment by magento-engcom-team** [comment] 2017-10-11 19:03
@konstanchuk, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 19:03 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
