### ISSUE TITLE
REST API broken if SKU contains /

### ISSUE THREAD

**Issue by robgt** [magento/magento2#10434] opened 2017-08-04 09:44 UTC
### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Using Zynk to synchronise Sage 200 MMS to Magento 2.1.6. A new error occurs that we have never encountered while using Magento 1.x (currently 1.9.3).

### Expected result

1. Zynk should be able to use the REST API to update data in Magento 2.1.6

### Actual result

1. Any product SKU containing a "/" throws an error and that record is not processed.

This thread on stackexchange from late last year highlights the same issue, but it seems the fix (the plugin) also doesn't work now?
https://magento.stackexchange.com/questions/142056/how-to-get-magento2-product-with-rest-if-sku-has-slash

Is this something that could easily be resolved somehow?

**Comment by misha-kotov** [comment] 2017-08-04 16:18
Thanks for reporting this issue. It's a duplicate of #8615 which cites the internal issue for this is MAGETWO-60899.

**Closed as completed by misha-kotov** 2017-08-04 16:18 UTC
