### ISSUE TITLE
Cannot set attribute value to empty/null on configurable products

### ISSUE THREAD

**Issue by mktudock** [magento/magento2#5830] opened 2016-07-27 09:32 UTC
### Preconditions
1. Have Magento 2.1 with a configurable product and an attribute set with some optional attributes
### Steps to reproduce
1. Edit the product and set the values of the optional attributes to empty/null
### Expected result
1. The values are empty or null after save
### Actual result
1. The values get set to some kind of default

I tested this on Magento 2.1 "vanilla" with sample data.

**Comment by oserediuk** [comment] 2016-07-27 12:09
Thanks for the report! This issue is duplicate of https://github.com/magento/magento2/issues/4910. I'm closed this one. Feel free to reopen if you have any additional questions about theme selection.

**Closed as completed by oserediuk** 2016-07-27 12:09 UTC
