### ISSUE TITLE
Reorder not working from admin environment

### ISSUE THREAD

**Issue by zaheerbadi** [magento/magento2#11285] opened 2017-10-07 07:58 UTC
When i tried to reorder from specific customer it redirect to page where css was not loaded and give php error like `Argument 1 passed to Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor::getItemPrice() must be an instance of Magento\Catalog\Model\Product, instance of Magento\Wishlist\Model\Item given, called in C:\wamp64\www\mage220\vendor\magento\module-sales\view\adminhtml\templates\order\create\sidebar\items.phtml on line 73 and defined in C:\wamp64\www\mage220\generated\code\Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor.php on line 280` and one more ` TypeError: Argument 1 passed to Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor::getItemPrice() must be an instance of Magento\Catalog\Model\Product, instance of Magento\Wishlist\Model\Item given, called in C:\wamp64\www\mage220\vendor\magento\module-sales\view\adminhtml\templates\order\create\sidebar\items.phtml on line 73 in C:\wamp64\www\mage220\generated\code\Magento\Sales\Block\Adminhtml\Order\Create\Sidebar\Wishlist\Interceptor.php on line 280`

### Preconditions

1. Magento 2.2.0 with windows 10 environment
2. php 7.0.10
3. apache 2.4.23
4. My Sql 5.7.14

### Steps to reproduce

1. On admin go to customer order tab and reorder it.

### Expected result

1.  it should be recreate order and give order place screen

### Actual result

1. [[Errpr screen shot]](https://www.screencast.com/t/QUXgvc9zy)

**Comment by magento-engcom-team** [comment] 2017-10-09 08:30
@zaheerbadi, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-09 08:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
