### ISSUE TITLE
Outdated PHP memory limit in .htaccess

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/magento2#24157] opened 2019-08-16 20:59 UTC
### Summary (*)
I'd like to open a PR to avoid this issue, and curious if it will be accepted before writing.

The files `.htaccess` and `.htaccess.sample` both set `php_value memory_limit 756M`.

This is below what Magento's install guide suggests (2048M):
- https://devdocs.magento.com/guides/v2.3/comp-mgr/trouble/cman/out-of-memory.html

As I understand it, Composer does some magic to raise or ignore the memory limit so its operations can complete installing modules.
- https://mage2.pro/t/topic/1045

This does not apply when Magento is serving requests, and keeping 756M fails on a simple user flow:

1. Load the home page (works)
2. Click "create account" (works)
3. Submit the form (fails, out of memory)

I have limited system admin experience, and don't know the implications this change creates. This is a bad developer experience though, and it seems obvious that the recommended default memory limit should actually be used in default config files.

### Proposed solution
Change the memory limit in these files to 2048M:

- .htaccess
- .htaccess.sample

This will reflect the documentation, and avoid a bad first experience as a developer.

**Comment by hostep** [comment] 2019-08-17 11:12
Hi @brendanfalkowski 

I can't reproduce your 3rd step on a vanilla installation, even when only running with a memory_limit of `256M`.
Are you sure there is no custom code involved which maybe has some memory issues?

The documentation you refer to is some troubleshooting guide for running `composer update` on the server I believe, this can indeed take a lot of memory and needs swap space available, but in my opinion you shouldn't run `composer update` on the server where Magento is hosted.

After some discussion on the [devdocs repo](https://github.com/magento/devdocs/issues/739) a while ago, I think the conclusion was that every shop is different and every shop needs to determine its own `memory_limit` value for what is needed.
You'll notice that there is no recommendation for just running Magento [in the docs](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html).

The current `756M` is still too high in my opinion, but some shops probably need it somehow...
From own experience: most of the shops we host have the `memory_limit` set to `256M` and this doesn't cause any issues.

Other opinions are welcome, this is just speaking from my own experience :)

**Comment by brendanfalkowski** [comment] 2019-08-19 17:51
@hostep — Thanks, there is custom code in the repo I'm working on. I just wasn't expecting it could render but not process a form with the default `memory_limit`. I have too explore what's causing the higher memory usage.

It seemed like the docs suggested that 2048 MB was recommended:
- https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html

But I see the PHP requirements are specifically different (756 MB):
- https://devdocs.magento.com/guides/v2.3/install-gde/prereq/php-settings.html

Which matches `.htaccess.sample`.

**Comment by hostep** [comment] 2019-08-19 18:09
The `756M` refers to compiling code and deploying static assets. You tend to do using the php command line (which usually uses a different `php.ini` file and usually has an unlimited `memory_limit` set).

Currently there is no recommendation for the `memory_limit` value for serving a Magento shop using a webserver. It depends on how big your shop is, and if it uses specific features which need much memory or not.

In my opinion if you need 2GB of memory simply for creating a single customer account, then there is something fishy in the code. And I hope you can find this problem!

I'm going to close this issue for now if you don't mind 🙂

**Closed as completed by hostep** 2019-08-19 18:09 UTC
Labels: Issue: Format is not valid
