### ISSUE TITLE
Problems creating a queue | could not find an implementation type for type "sync" and connection "db".

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#38236] opened 2023-11-30 08:04 UTC
### Summary

I'm trying to create a queue based on the docs using db as connection. However when using `PublisherInterface`  to publish a message I'm greeted with this exception in Magento 2.4.1

`Could not find an implementation type for type "sync" and connection "db".`

I couldn't find relevant info about it or how to solve it. 

I followed many guides online including the docs to try different alternatives but still bumping into this error when publishing a message. 

The queue is created in the database tables as far as I can see. 

When adding `is_synchronous="false"` in communication.xml the error is gone but I don't see my message published.

### Examples

I'm attaching here the configuration for the queue 

[queue.tar.gz](https://github.com/magento/magento2/files/13510134/queue.tar.gz)

I forgot to mention that the bulk of the code was created using the official PHPSTORM plugin for code scaffolding

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-12-05 07:14
Hello @ioweb-gr,

Thank you for the report!

It appears these errors are caused by miss configuration of the queue.
For the error `Could not find an implementation type for type "sync" and connection "db"`, you might need to remove `response="string"` from communication.xml as this is only required when defining a synchronous topic.
As for the message not being published please check your consumerInterface and handler, make sure it is configured properly.
Please follow this official documentation to configure the handler.  https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/#handler-element-1 

Let us know if this fixed your issue.

Thank you.

**Comment by ioweb-gr** [comment] 2023-12-11 06:28
Hi @engcom-November I've already checked the link you mentioned and in the official docs 

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Communication/etc/communication.xsd">
  <topic name="synchronous.rpc.test" request="string" response="string">
    <handler name="processRpcRequest" type="Magento\TestModuleSynchronousAmqp\Model\RpcRequestHandler" method="process"/>
  </topic>
  <topic name="magento.testModuleSynchronousAmqp.api.serviceInterface.execute" schema="Magento\TestModuleSynchronousAmqp\Api\ServiceInterface::execute">
    <handler name="processRemoteRequest" type="Magento\TestModuleSynchronousAmqp\Model\RpcRequestHandler" method="process"/>
  </topic>
</config>

```

You will notice that for a synchronous topic it still defines `response="string"`

https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/#communicationxml

Therefore either the doc is wrong or it's not what's at fault here.

**Comment by engcom-November** [comment] 2023-12-12 08:46
Hello @ioweb-gr,

Thank you for the quick reply!

Yes the `response="string"` is only required in case of a synchronous topic. I believe you are defining a asynchronous topic, in this case you cas skip the `response` attribute, or you can specify `is_synchronous="false"`. (It is preferred to use asynhronous topic)

In the above example `response="string"` is present because they are definig a synchronous topic.
Please go throgh with this documentation
https://developer.adobe.com/commerce/php/development/components/message-queues/configuration/#topic-element.

I have created a asynchronous message queue which is working fine in my case, please check this with your configuration and let us know if you face any issue.
[MqVendor.zip](https://github.com/magento/magento2/files/13645772/MqVendor.zip)

Thank you.

**Comment by engcom-November** [comment] 2024-01-02 12:26
Hello @ioweb-gr,

We have noticed that this issue has not been updated for a long time. We believe your query has been resolved, hence closing this issue.
Feel free to reopen this issue or raise a fresh one if you need more assistance.

Thank you.

**Closed as completed by engcom-November** 2024-01-02 12:26 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.1
