### ISSUE TITLE
Magento 2.0.4

### ISSUE THREAD

**Issue by leonbrag** [magento/magento2#4056] opened 2016-04-07 20:50 UTC
I have exact issue as this: https://github.com/magento/magento2/issues/3783  on  Ubuntu 14.04.4 

Is this still an open issue?
Is there a workaround?

thanks

**Comment by mazhalai** [comment] 2016-04-07 20:56
How did you deploy 2.0.4? via git, composer or zip from magento.com?
This fix is in the develop branch, so if you deployed via git, it should work.

**Comment by leonbrag** [comment] 2016-04-08 00:15
I have re-installed from GIT. Now I got this error: 
Magento supports PHP 5.5.22 or later. However I am running it on 
PHP Version 5.5.9-1ubuntu4.14

Is not my 5.5.9 higher then needed 5.5.22?

**Comment by alankent** [comment] 2016-04-08 00:42
5.5.9 (note the "9") is lower than 5.5.22 (note the "22"). Yes, it's 22, not 2.2, so 5.5.9 is older than 5.5.22.  (And if you are serious about development, I would jump to 7.0.4.)

**Comment by mazhalai** [comment] 2016-04-11 13:48
@leonbrag please update your PHP version. Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-04-11 13:48 UTC
Labels: Progress: needs update

**Comment by scholtz** [comment] 2016-04-22 14:32
Hi guys, if you officially support Ubuntu, you should accept the latest stable PHP build that is 

PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)

What is in PHP 5.5.22 so important that you force administrators to use other PHP distribution sources?
