### ISSUE TITLE
The bundle customizable option "FILE" returns empty array

### ISSUE THREAD

**Issue by WilliejanB** [magento/magento2#33263] opened 2021-06-16 17:34 UTC
The bundle customizable option "FILE" returns an empty array after adding a product into the cart. As a result, cart is empty and we get a redirect issue to this product page.

### Preconditions (*)

1. Magento ver. 2.4.2
2. PHP 7.4
3. MySQL ver. 10.2.35-MariaDB
4. 

### Steps to reproduce (*)
1. Go to this link: https://www.mirrorengraving.com/laser-engraved-mirrors
2. Click the "Customize and Add to Cart" button.
3. Select all required fields to customize the product.
- Mirror size: 8"x12"
- Quantity: 1
- Text: (skip this field)
- Font style: Basic Formal
- Upload: Add any .jpg, png or tiff file
- Upload: (skip this upload)
- Upload: (skip this upload)
- Optimize images(s): Yes - Optimize 1 image
- Mounting: E04 for mirrors up to 16"
- Instructions: (skip this field).
 
4. Click the "Add to Cart" button 

### Expected result (*)
Magento should now proceed to the final checkout page.

### Actual result (*)
Magento refreshes the page and, clears all entered options 
![BUNDLE__FILE_OPTION](https://user-images.githubusercontent.com/67437750/122259214-3904c500-ced2-11eb-8bc3-6e3ae0b3cfe8.png)
1. [Screenshots, logs or description]

**Comment by WilliejanB** [comment] 2021-07-05 17:32
Any news or progress for this issue?

**Comment by engcom-Hotel** [comment] 2021-07-06 07:02
Hello @WilliejanB,

We have tried to reproduce this issue on Magento 2.4-develop. And it seems that issue is reproducible. We have followed below steps in order to reproduce the issue:
1. Created a customisable product as per the Issue description (Referred the customer’s product link):

![image](https://user-images.githubusercontent.com/51681618/124556481-f3467700-de55-11eb-915f-91f6e808f474.png)

2. Which looks on the product details page like this:

![image](https://user-images.githubusercontent.com/51681618/124556552-078a7400-de56-11eb-802c-53fae02714e0.png)

3. After customising the product as per the description, and then clicking on “Add to Cart” is not adding the product in cart and page get reloaded.

I am confirming the issue.

**Comment by WilliejanB** [comment] 2021-07-06 07:10
@engcom-Hotel, Thank you so much for the confirmation and your effort to help. I hope a fix can be found as soon as possible.
Best regards,
Williejan

**Comment by WilliejanB** [comment] 2021-07-14 18:06
Fixed locally by changing Magento code at this core file - vendor/magento/module-catalog/Model/Product/Type/AbstractType.php

"Error: Call to undefined method Magento\Catalog\Model\Product\Option\Type\File\ValidatorFile::setIsValid() in /home/lasersp2/public_html/vendor/magento/module-catalog/Model/Product/Type/AbstractType.php:521

Please fix in next update.

**Comment by magento-engcom-team** [comment] 2021-07-18 04:33
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42875` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2021-07-18 04:33
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42875` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mmezhensky** [comment] 2021-07-21 11:39
@magento I am working on this

**Comment by mmezhensky** [comment] 2021-12-23 12:36
Hi @WilliejanB, @engcom-Hotel  
Right now, I can't reproduce this issue in the 2.4-develop branch. Could you provide a more detailed description of the steps to reproduce?

**Comment by engcom-Alfa** [comment] 2022-03-11 10:29
Hi @WilliejanB Thanks for your contribution
Tried to reproduce the issue once again in the latest _Magento 2.4-develop_ instance, not able to reproduce at all.
1. Created a product with custom options as shown in the [above screenshot](https://github.com/magento/magento2/issues/33263#issuecomment-874512664).
2. In the front end, added the same product to cart selecting multiple custom options.
The product got added successfully. Also proceeded to checkout!

The issue might have fixed along with any other code PR updates. So, I am closing this issue as off now considering above @mmezhensky 's comment as well.
Kindly re-test again your end in the latest _Magento 2.4-develop_ instance. If the issue is still reproducible, you can re-open the same ticket with all detailed information about the issue like _steps by steps to reproduce_, _what is the actual issue_, _what is expected_ and _relevant screenshots/ docs/ screen records_ as such! Or you may report a fresh issue as well.
Thanks

@mmezhensky, thanks for your collaboration regarding this issue!

**Closed as completed by engcom-Alfa** 2022-03-11 10:29 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.2, Area: Catalog
