### ISSUE TITLE
ShippingCartAddress available_shipping_methods wrong amount (shopping cart rules do not applied)

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#31489] opened 2020-12-29 22:08 UTC
### Precondition:

- Magento 2.4.1.
- Sample data.
- Cart Price Rule "Spend $50 or more - shipping is free!" is active.
- Shipping method "Table Rate" is enabled
(vanilla Magento with sample data is configured as well)

### Steps to reproduce
1. mutation createEmptyCart

2. mutation addSimpleProductsToCart
```
  addSimpleProductsToCart(
    input: {
      cart_id: <CART_ID>
      cart_items: [
        {
          data: {
            quantity: 2
            sku: "24-MB04"
          }
        }
      ]
    }
  ) {...}

```
3. mutation setShippingAddressesOnCart
```
  setShippingAddressesOnCart(
    input: {
      cart_id: <CART_ID>
      shipping_addresses: [
        {
          address: {
            firstname: "Bob"
            lastname: "Roll"
            company: "Magento"
            street: ["Magento Pkwy", "Main Street"]
            city: "Austin"
            region: "TX"
            postcode: "78758"
            country_code: "US"
            telephone: "8675309"
            save_in_address_book: false
          }
        }
      ]
    }
  ) {...}
}
```

4. Get available shipping methods list 
```
  query cart(cart_id: <CART_ID>) {
    shipping_addresses {
      available_shipping_methods {
        available
        carrier_code
        carrier_title
        error_message
        method_code
        method_title
        amount {
          currency
          value
        }
        price_excl_tax {
          value
          currency
        }
        price_incl_tax {
          value
          currency
        }
      }
    }
  }
```

### Expected result
The shipping amount for "Table Rate" method should be $0 as on Luma theme
![Shopping-Cart](https://user-images.githubusercontent.com/3465267/103316700-f4739300-4a31-11eb-9230-31f5eef27830.png)

### Actual result
"Table Rate" method amount is $15
![Desktop-screenshot](https://user-images.githubusercontent.com/3465267/103316744-1ff67d80-4a32-11eb-83ed-750c0a50dedd.png)

### Possible fix
It works well for me when I add row:
```
$address = $cart->getShippingAddress();
```
before line https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Resolver/ShippingAddress/AvailableShippingMethods.php#L74

**Comment by KrishnaK-Z** [comment] 2021-01-04 12:55
@magento I am working on this

**Comment by cpartica** [comment] 2021-04-20 19:54
@KrishnaK-Z  @OleksiyOleksiyovych I tried to reproduce this on 2.4.1 and on 2.4-develop and I couldn't.
What version did you used when reporting this?
Can you see if it's still reproducible?

**Comment by rahulbarot** [comment] 2022-05-30 12:22
@magento give me 2.4.3-p2 instance

**Comment by engcom-Bravo** [comment] 2022-08-30 08:21
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-30 12:35
Hi @OleksiyOleksiyovych,


Thank you for reporting and collaboration. 

Verified the issue on Magento 2.4-develop branch we are able to reproduce the issue.

Kindly refer the screenshots.

Cart Price Rule "Spend $50 or more - shipping is free!" is activated.

<img width="896" alt="dk" src="https://user-images.githubusercontent.com/51680745/187433017-77f216d4-8795-4803-8cbf-f6a1da1ff231.png">


1.mutation addSimpleProductsToCart




<img width="928" alt="dk1" src="https://user-images.githubusercontent.com/51680745/187433259-d0e69560-9654-48bf-b6b3-73701f8fcbc0.png">



2.mutation setShippingAddressesOnCart



<img width="924" alt="dk 2" src="https://user-images.githubusercontent.com/51680745/187433460-d510829f-c645-46d0-bfc5-e7c355f9c7cd.png">



3.Get available shipping methods list




<img width="885" alt="dk 4" src="https://user-images.githubusercontent.com/51680745/187433564-a9719cb1-2d75-4e67-ab23-dc168f2f7678.png">



<img width="929" alt="dk 5" src="https://user-images.githubusercontent.com/51680745/187433662-946a4092-2abc-46f9-8348-125b13380cc0.png">


We are getting "Table Rate" method amount is $15.


Hence confirming the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-01 08:48
Hi @OleksiyOleksiyovych,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.

Kindly refer the screenshots.


1.Cart Price Rule "Spend $50 or more - shipping is free!" is active.


<img width="926" alt="venkat 5" src="https://user-images.githubusercontent.com/51680745/187871609-cb2a8544-6e14-4262-958b-d1c455a02ae4.png">



2.Shipping Methods(Free shipping and Table Rate) are Enabled.


<img width="927" alt="venkat" src="https://user-images.githubusercontent.com/51680745/187871872-fd8a36eb-5cc7-4ab4-83f2-984fc691ed18.png">



<img width="936" alt="venkat 2" src="https://user-images.githubusercontent.com/51680745/187871910-ae7e7c56-14fb-4f05-91eb-2a096d45fcc8.png">




3.Added the Product above $50 



<img width="929" alt="venkat 3" src="https://user-images.githubusercontent.com/51680745/187872254-8778d1f9-f470-46ca-a3a8-a1cb4ecd45b0.png">



Please apply Discount coupon for free shipping. Kindly refer screenshots




<img width="930" alt="venkat 4" src="https://user-images.githubusercontent.com/51680745/187872299-4787c594-01f3-4df8-bcd9-0c55cba3ad36.png">



Let us Know we have miss anything.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-09-19 05:06
Hi @OleksiyOleksiyovych,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-19 05:06 UTC
Labels: Priority: P1, Project: GraphQL, Progress: done, Issue: needs update
