### ISSUE TITLE
Cron gets wrong base media URL

### ISSUE THREAD

**Issue by MrDaar** [magento/magento2#9111] opened 2017-04-03 12:15 UTC
### Preconditions
1. Magento: 2.1.5
2. PHP: 7

### Steps to reproduce
1. Set up Magento with pub folder as webroot
2. Set email logo in `Content > Design > Configuration > Edit > Transactional Emails > Logo Image`
3. Have a cron (custom) send an email

### Expected result
1. Email is received with all images showing.

### Actual result
1. No images show.
2. Path to images contain: "/pub/"

The image above is set in config, but the issue will also happen for product image urls generated by:
```
return $this->_imageHelper->init($product, $type, $attributes)
            ->setImageFile($imageFile)->resize(208, 260)->save()->getUrl();
```
or images included with directives:
```
<img src="{{media url="wysiwyg/emails/mailer-footer.png"}}" alt="{{trans "Thank you, %store_name" store_name=$store.getFrontendName()}}!" />
```

You can force the media url in config:
`Stores > Configuration > Web`
But that shouldn't be necessary.

`Magento\Store\Model\Store->getBaseUrl(...)` returns wrong value.

**Comment by scottsb** [comment] 2017-04-05 18:42
We're experiencing the same issue with the built-in product stock alert module, which generates its emails via cron.

**Comment by scottsb** [comment] 2017-04-05 20:12
Just noted that this is a duplicate of #8868.

**Comment by scottsb** [comment] 2017-04-05 21:23
Finally found workaround:
http://magento.stackexchange.com/a/167869/567

**Comment by MrDaar** [comment] 2017-04-05 21:29
@scottsb 

> You can force the media url in config:
`Stores > Configuration > Web`

So if you set the config value in control centre it'll also be fine.

**Comment by MrDaar** [comment] 2017-04-05 21:31
**Base URL for User Media Files** `{{unsecure_base_url}}media/`
**Secure Base URL for User Media Files** `{{secure_base_url}}media/`

_(edited)_

**Comment by scottsb** [comment] 2017-04-05 22:37
I attempted that, but it didn't seem to resolve the issue for me. Either I did something wrong, forgot to clear my cache or it's another issue with single-store mode (_maybe_ related to #8137).

**Comment by hostep** [comment] 2017-04-06 10:46
We experienced the same problem, where the media paths in the generated sitemap.xml file were incorrect when the sitemap.xml was generated by the cronjob, if you generate it manually, the paths were correct.

Solution from @MrDaar fixed it for us, but it shouldn't contain the forward slash in the middle, it should be:
- `{{unsecure_base_url}}media/`
- `{{secure_base_url}}media/`

**Comment by magento-engcom-team** [comment] 2017-10-25 18:30
@MrDaar, thank you for your report.
We've created internal ticket(s) MAGETWO-82739 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-03-06 13:43
Hi @MrDaar 
We are now closing this as a duplicate of https://github.com/magento/magento2/issues/8868

Thank you for participation

**Closed as completed by magento-engcom-team** 2018-03-06 13:43 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid

**Comment by Axel29** [comment] 2018-06-15 08:56
Hi,

Thank you for your solutions, I've been debugging this problem for a moment now!
The only thing is that I also had to change the `web/(un)secure/base_static_url` paths to `{{(un)secure_base_url}}static/` to make it work.

**Comment by jajajaime** [comment] 2018-09-27 18:11
I can corroborate that setting the `base_static_url` path to `{{(un)secure_base_url}}static/` solves the issue for me. The config that needs to be set probably depends if your images are in media or static folder.

**Comment by nahuelsanchez** [comment] 2018-09-30 18:51
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-09-30 18:51
Hi @nahuelsanchez. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-09-30 18:52
Hi @nahuelsanchez, here is your [Magento instance](https://i-9111-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-9111-2-3-develop.engcom.dev.magento.com/admin](https://i-9111-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by scottsb** [comment] 2018-10-01 21:02
WHAT IS THIS MAGIC?

**Comment by Naeemakhter1999** [comment] 2020-07-22 11:48
In have to add cron process in extension ,which can shown in a  cron_schedule tabel.
how can i add? in Magento1 Googleshopping Extension.

**Comment by hareshpatel** [comment] 2021-02-11 06:30
Hello same issue can you plz help me 
what is step resolve this issue
