### ISSUE TITLE
ESI controller generates an issue

### ISSUE THREAD

**Issue by YahorDubrouski** [magento/magento2#38349] opened 2024-01-11 15:36 UTC
### Preconditions and environment

- Magento version - 2.4.5-p4
- Varnish is used for caching
- There is a block with set up "ttl" parameter in layout of "review_product_list.xml" page. For example main menu.
- Developer mode is set up

### Steps to reproduce

1. Clean varnish cache
2. Open the review product list page

### Expected result

No exceptions, the menu's block html is returned

### Actual result

See an exception in developer mode because the product does not exist

### Additional information

**Technical notes**
The issue appears, as:

1. The controller `Magento\PageCache\Controller\Block\Esi` is called with 'review_product_list.xml' layout handler as a parameter
2. Magento generates the layout
3. While the layout generation `Magento\Review\Block\Product\View\ListView::_prepareLayout->getReviewsCollection()->getProduct()` is called
4. The issue appears because the product is not set

**Suggestion**
Move the logic from _prepareLayout to another method

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by 0MazaHacka0** [comment] 2024-01-12 13:07
@magento give me 2.4.4 instance

**Comment by engcom-Dash** [comment] 2024-01-12 15:49
Hi @EgorDubrovskiy 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance, after clearing varnish cache we are not seeing exceptions in exceptions.log

Can you please provide the detailed steps to reproduce and the actual errors you are getting.

Thanks.

**Comment by 0MazaHacka0** [comment] 2024-01-15 09:18
@magento give me 2.4.4 instance

**Comment by engcom-Dash** [comment] 2024-01-31 06:05
Hi @EgorDubrovskiy 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-31 06:05 UTC
Labels: Issue: needs update
