### ISSUE TITLE
When reordering an order placed from admin with a custom price, the cart shows the wrong price of the product.

### ISSUE THREAD

**Issue by iovistainc** [magento/magento2#38357] opened 2024-01-17 13:07 UTC
### Preconditions and environment

**Preconditions**
- Magento 2.4.6

### Steps to reproduce

1. Place an order from the admin side and add a custom price.
2. Log in as a customer after placing the order.
3. Check the last order placed from the admin side.
4. Click on the reorder button, which will redirect to the cart page.
5. Observe that the price of the product displayed on the cart page is showing the custom price.

https://github.com/magento/magento2/assets/16300151/c202e26f-9ecf-4c17-ba07-e8d837a906f4

### Expected result

The original product price should be displayed on the cart page when a customer attempts to reorder an order that was placed from the admin side with a custom price.

### Actual result

It's considering a custom price instead of the original price.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-01-18 05:46
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-18 09:51
Hi @iovistainc,

Thanks for your report and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**


- Place an order from the admin side and add a custom price.
- Log in as a customer after placing the order.
- Check the last order placed from the admin side.
- Click on the reorder button, which will redirect to the cart page.
- Observe that the price of the product displayed on the cart page is showing the custom price.


[Screencast from 18-01-24 11:58:21 AM IST.webm](https://github.com/magento/magento2/assets/51680745/f13248bb-7b18-497a-ad29-ac1919abf1cd)


original product price should be displaying on the cart page when a customer attempts to reorder an order that was placed from the admin side with a custom price.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by sagarbliss** [comment] 2024-01-18 13:42
@magento-admin give me 2.4-develop instance

**Comment by sagarbliss** [comment] 2024-01-18 13:57
@engcom-Bravo Place an order with a configurable product and it can be reproducible. I will reproduce an issue once the instance is ready.

**Comment by iovistainc** [comment] 2024-01-18 14:07
@magento give me 2.4-develop instance

**Comment by gabrieldagama** [comment] 2024-01-18 22:29
@magento give me 2.4.6-p3 instance

**Comment by sagarbliss** [comment] 2024-01-19 04:41
@magento give me 2.4.6-p3 instance

**Comment by engcom-Bravo** [comment] 2024-01-19 05:43
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-01-19 06:20
Hi @sagarmagento @iovistainc,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Place an order from the admin side and add a custom price.
- Log in as a customer after placing the order.
- Check the last order placed from the admin side.
- Click on the reorder button, which will redirect to the cart page.
- Observe that the price of the product displayed on the cart page is showing the custom price.

![Screenshot from 2024-01-19 11-34-12](https://github.com/magento/magento2/assets/51680745/12b4e25a-453b-429c-8e10-9cf84e5c3542)



![Screenshot from 2024-01-19 11-34-24](https://github.com/magento/magento2/assets/51680745/88628e76-e6ec-4532-9e63-477e7eded7fe)

original product price should be displaying on the cart page when a customer attempts to reorder an order that was placed from the admin side with a custom price for a configurable product also.



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by iovistainc** [comment] 2024-01-19 11:24
@engcom-Bravo I have checked version 2.4.7-beta2 and confirmed that the issue has been fixed, as mentioned in the release notes.
![image](https://github.com/magento/magento2/assets/16300151/76883026-e850-48e4-8f40-04bbcfcfc311)
https://experienceleague.adobe.com/docs/commerce-operations/release/notes/magento-open-source/2-4-7.html?lang=en

https://github.com/magento/magento2/commit/68f18e445517d045344ce91c3cc38321f0274274

Let me know if an official patch is available to fix this issue.

**Comment by engcom-Bravo** [comment] 2024-01-23 07:09
Hi @iovistainc,

Thanks for your update.

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1514 by the internal team
Related commits : https://github.com/search?q=repo%3Amagento%2Fmagento2+ACP2E-1514&type=commits


Since the issue is not reproducible in Magento 2.4-develop instance We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-23 07:09 UTC
Labels: Issue: needs update, Reported on 2.4.6
