### ISSUE TITLE
msrp module error breaks the swatches on product configuration page

### ISSUE THREAD

**Issue by drabikowy** [magento/magento2#23832] opened 2019-07-23 08:35 UTC
### Preconditions (*)
1. Magento 2.3.1 Theme Luma
2. Msrp module is disabled

### Steps to reproduce (*)
1. Add a configurable product
2. Create a configurations for product:
 - add two new attributes: color swatch + text swatch
 - add separate pictures eg. for color variants
 - apply same price to all skus
 - apply same quantity to all skus
3. Go to created product's pdp, select color swatch + text swatch and add it to cart
3. Open minicart and click "edit" button to go to product configuration page

### Expected result (*)

1. Previously selected configuration should be saved and swatches should be selected
2. Click on the swatch should change the product image (if configured)

### Actual result (*)

In console there is an msrp module error which breaks the swatches functionallity:
- preselection of previously selected configuration does not work
- if you configured swatches to change product gallery - this stops working, too

Here is the error that appears:

https://d2aztkdj0ezvrk.cloudfront.net/items/2X3y2T3r163y0i232k16/Image%202019-07-23%20at%2010.00.31%20AM.png 

And form my investigation, error is triggered in `swatches-renderer.js` OnClick method, where below logic triggers the "updateMsrpPriceBlock" event:
```
$(document).trigger('updateMsrpPriceBlock',
    [
        parseInt($this.attr('index'), 10) + 1,
        $widget.options.jsonConfig.optionPrices
]);
```

On regular PDP, msrp module does not listen to this event, while on product configuration page it does - even if msrp is disabled. Either msrt should not listen here, too or wrong data is passed to this event and it breaks.

**Comment by drabikowy** [comment] 2019-07-23 08:47
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-07-23 08:47
Hi @drabikowy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-23 08:48
Hi @drabikowy, here is your [Magento instance](https://i-23832-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23832-2-3-develop.instances.magento-community.engineering/admin](https://i-23832-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drabikowy** [comment] 2019-07-23 09:21
I confirm - issue is reproducible on provided Magento instance.

**Comment by engcom-Charlie** [comment] 2019-07-23 11:09
Hi, @drabikowy ! 
How did you disable the Msrp module? Because when i turned it off my magento stopped working:
![wowowo](https://user-images.githubusercontent.com/51680850/61707469-3aafc780-ad53-11e9-82b2-b5e6d3aeef16.png)
Frontent doesn't work either.

**Comment by drabikowy** [comment] 2019-07-23 11:29
Hello!

Actually it was disabled by default on provided instance.

I mean in stores->configuration->sales->minimum advertised price - I didn’t
touch this settings


W dniu wt., 23.07.2019 o 13:10 Robert Turchyn <notifications@github.com>
napisał(a):

**Comment by magento-engcom-team** [comment] 2019-07-23 11:45
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18471` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drabikowy** [comment] 2019-08-09 06:55
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-09 06:55
Hi @drabikowy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-09 06:56
Hi @drabikowy, here is your [Magento instance](https://i-23832-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23832-2-3-develop.instances.magento-community.engineering/admin](https://i-23832-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by drabikowy** [comment] 2019-09-03 09:45
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-03 09:46
Hi @drabikowy. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-03 09:46
Hi @drabikowy, here is your [Magento instance](https://i-23832-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23832-2-3-develop.instances.magento-community.engineering/admin](https://i-23832-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment] 2019-12-13 19:26
This issue is no longer reproducible on `2.4-develop` branch:
![ezgif-4-5fa63dc84a00](https://user-images.githubusercontent.com/829189/70826311-dadfb900-1de6-11ea-8351-5ec5926f6e65.gif)

**Closed as completed by krzksz** 2019-12-13 19:26 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Store

**Comment by FerihumF** [comment] 2020-01-20 13:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @FerihumF. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:59
Hi @FerihumF, here is your [Magento instance](https://i-23832-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-23832-2-4-develop.instances.magento-community.engineering/admin_83b0](https://i-23832-2-4-develop.instances.magento-community.engineering/admin_83b0)
Login: `c825cc97` Password: `63566afed2ed`
Instance will be terminated in up to 3 hours.
