### ISSUE TITLE
Update to 2.4.2-p1 not possible when running PHP 7.4.3

### ISSUE THREAD

**Issue by chequille** [magento/magento2#33109] opened 2021-05-31 22:39 UTC
### Preconditions (*)

1. Actual version Magento 2.4.2
2. PHP Version 7.4.3

### Steps to reproduce (*)

1. In command line: composer require magento/product-community-edition 2.4.2-p1 --no-update

### Expected result (*)

1. Getting no error to be able to update

### Actual result (*)

1. Error: Could not find a Magento project package matching "magento/product-community-edition 2.4.2-p1" for PHP version 7.4.3

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by chequille** [comment] 2021-05-31 22:40
How to fix this?
Any ideas?

**Comment by chequille** [comment] 2021-05-31 22:59
Just found, that "composer require magento/product-community-edition 2.4.2 --no-update" is as well not working.
Can it be, that it has something to do with github access changes? I got an email from them to change my access token.
But where is it defined. I do not see any part in the composer.json file of my magento installation.

Or am I now completly stupid, as the commands above to update to a new relase did work before.

Any ideas guys?
Best regards
Chequille

**Comment by robolmos** [comment] 2021-06-01 18:41
> ### Steps to reproduce (*)
> 1. In command line: composer require magento/product-community-edition 2.4.2-p1 --no-update

Try including the equal sign like this: `magento/product-community-edition=2.4.2-p1`

> But where is it defined. I do not see any part in the composer.json file of my magento installation.

Look in ~/.config/composer or ~/.composer for an auth.json file.
This command might work too: `composer config -g --unset github.oauth.github.com`

**Comment by hostep** [comment] 2021-06-01 19:19
@chequille: over here your command works perfectly fine. Also if you provide the `--no-update` flag, I think that composer doesn't do any dependency resolving, so it's very weird that you get that error.

Maybe try including the `-vvv` flag in your command, maybe it gives some extra info that can show you were the problem is.
If that still doesn't work or gives not enough info, try manually changing your `composer.json` file and changing `2.4.2` to `2.4.2-p1` and running `composer update magento/product-community-edition --with-dependencies` and see if that works or gives you some more info why it doesn't want to work.

The new github access token format probably has little to do with this, since Magento modules aren't hosted on github (but be aware that if you do change it to the latest format, that your composer is at least version 1.10.21 or 2.0.12, composer only supports the new github access token format since those versions)

Good luck! 🙂

**Comment by hostep** [comment] 2021-06-01 19:23
Ah wait, it might have something to do with the `magento/composer-root-update-plugin` composer plugin, since that error message is thrown over there:
https://github.com/magento/composer-root-update-plugin/blob/1.1.2/src/Magento/ComposerRootUpdatePlugin/Updater/RootPackageRetriever.php#L284

Maybe first try to update that package to the latest version and after that try to update Magento to the latest version?

(I didn't test with that module enabled earlier, because I really don't like that module and always remove it from my Magento installations, I know perfectly fine how to manually update Magento and don't need that module to automatically update my `composer.json` files)

**Comment by chequille** [comment] 2021-06-01 20:21
Hi guys,
thanks for your replies :-)

I found the problem. For some reason (do not know why), in my composer file the section for repositories was not there.
I added these like:
```
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com"
        },
        "ulmod_freepacks": {
            "type": "composer",
            "url": "https://freepacks.ulmod.com/"
        }
    },
```
and changed under sectio require magento version to 2.4.2-p1

After this change I run composer update and it works. It then asked as well for the new github access token which is afterwards stored in the auth.json file.

So, everything fine.
Regards,
Chequille

**Comment by hostep** [comment] 2021-06-01 21:54
Ah this makes sense if you have no repositories besides the default one from packagist.

Be aware, in the snippet you posted, you now have 2 times the same repo `repo.magento.com`, it's probably best to remove one of both (the one with the `/` at the end looks like the most correct one).

And about storing the github access token in your `auth.json` file, if this is the `auth.json` file in your project, I would remove it from there and add it to the global `auth.json` file. If you already have it in your global `auth.json` file, then ignore this comment.
To me it feels like this github token is yours personally and has nothing to do with a project, hence why I prefer it in my global `auth.json` file (which is `~/.composer/auth.json` on macOS and `~/.config/composer/auth.json` on Linux I think like @robolmos already explained before).

**Comment by engcom-Echo** [comment] 2021-06-03 05:59
Hi @chequille ,

Based on your recent comments, it looks it was an issue due to mis-configuration and everything is working fine now.
Thus we are closing this issue . 

Thanks

**Closed as completed by engcom-Echo** 2021-06-03 05:59 UTC
Labels: Issue: ready for confirmation
