### ISSUE TITLE
Out of stock products is displaying in product listing. 

### ISSUE THREAD

**Issue by AleksLi** [magento/magento2#13099] opened 2018-01-10 14:49 UTC
### Preconditions

1. Magento 2.2.0
2. mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. PHP 7.0.22

### Steps to reproduce

1. Check your [catalog inventory configuration](http://joxi.ru/EA4Q6vbSwEV7Lr)
2. You should have multiple attributes visible in catalog listing. [Like that.](http://joxi.ru/Grq1ygBiQ5Zajr)
3. Go to some product on Admin Panel (configurable product) and set qty to 0 for some simple product attached to this configurable. This simple product should be **out of Stock** after save. 
4. Go to frontend.

### Expected result

1. This Simple product (out of stock) should be hidden on frontend when you are clicking on option.
2. For example if we disabled [M size Black Color](http://joxi.ru/Y2L6k0DS95B0or) and we clicked on Black color - M size should be disabled

### Actual result

1. This product is still available on frontend.

**Comment by orlangur** [comment] 2018-01-10 22:23
Hi @AleksLi, did you assure stock index was updated? Is this caching-related?

**Comment by AleksLi** [comment] 2018-01-11 06:34
hi @orlangur , Magento cache is disabled and I've tried to do reindex manually `$ php bin/magento indexer:reindex`. Nothing helpes

**Comment by hitarthpattani** [comment] 2018-01-11 06:52
Hello @AleksLi , I think I am working on similar kind of issue which is an issue with "out of stock" swatches displays at frontend. Can you please check and confirm https://github.com/magento/magento2/issues/12317?

**Comment by AleksLi** [comment] 2018-01-11 08:59
Hi @hitarthpattani, Yes #12317 is similar to this one. I couldn't find any issue like that, so that's why I created this one. 
**This 2 issues are similar**

**Comment by magento-engcom-team** [comment] 2018-01-11 09:46
Duplicate of #12317

**Closed as completed by magento-engcom-team** 2018-01-11 09:46 UTC
Labels: Issue: Clear Description, Issue: Format is valid
