### ISSUE TITLE
Discount Rule does not show Default Rule Label

### ISSUE THREAD

**Issue by pmoreno1980** [magento/magento2#11497] opened 2017-10-16 17:59 UTC
### Preconditions

Magento 2.1.7
PHP 7.0
Mysql 5.7

### Steps to reproduce

1. i added products to the cart
2. https://mage2.pro/uploads/default/original/1X/87f29efbead4b3c3f222562e3345078ea9c380c7.png

### Expected result

1. rule label= "May Promo 3% discount -$58.35"

### Actual result

1. i see "discount -$58.35" instead of rule label

**Comment by magento-engcom-team** [comment] 2017-10-17 13:30
@pmoreno1980, thank you for your report.
We've created internal ticket(s) MAGETWO-82095 to track progress on the issue.

**Comment by mrodespin** [comment] 2017-10-18 06:58
@pmoreno1980  @magento-engcom-team there is one issue resolved pending of magento validation with the same error that this one mentioned.

The issue is this one #11438

**Comment by pmoreno1980** [comment] 2017-10-19 18:41
Thanks for your help but i don't see any solution for this #11438 or #11428.

@okobchenko  added the non-issue label to this issue,he thinks it is normal behavior but it is not. In magento 1 it works perfectly.

**Comment by pmoreno1980** [comment] 2017-10-20 13:42
yes, that solution doesn't work.

we have 2 situations for this issue (Cart Price Rule Label is not working):

Shopping Cart Rules with Coupon Code and this is the solution for that https://github.com/magento/magento2/issues/6244

Shopping Cart Rules without Coupon Code, i mean automatic discount, we don't have solution for this yet, this #11438 doesn't work.

this is a very important problem that is not solved in Magento 2. we didn't have this issue on Magento 1

thanks for you help

**Comment by pmoreno1980** [comment] 2017-10-26 20:24
any update here? i didn;t have answers here or #11438

**Comment by allanwebjump** [comment] 2017-10-30 18:38
https://github.com/magento/magento2/pull/11883

This issue can be solved with this PR

**Comment by pmoreno1980** [comment] 2017-11-01 15:50
@allanwebjump  wroks!! Thanks a lot !!!!

**Comment by magento-team** [comment] 2018-01-17 17:10
Hi @pmoreno1980. Thank you for your report. 
The issue has been fixed in magento/magento2#13141 by @ihor-sviziev in 2.2-develop branch
Related commit(s):
 - 976182b27212fb22bdb12c0a2da3e6a3e7231368
 - 3fc1f40d84b319e254284054c8a4dfe4aacf1a18
 - 0f36e0eac721070312fede445aa13d3b838e35d4

The fix will be available with the upcoming patch release.

**Closed as completed by magento-team** 2018-01-17 17:10 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2018-01-18 20:10
Hi @pmoreno1980. Thank you for your report. 
The issue has been fixed in magento/magento2#13223 by @ihor-sviziev in 2.3-develop branch
Related commit(s):
 - 1721ff185412d7aa04f45bb68717b2083b5b7769
 - 90d508bc112b341d0eeeed6db0ab18ee8b9b64d0
 - 968d7af6a4b5c3845c136c85d58fe80d5a1cd601

The fix will be available with the upcoming patch release.
