### ISSUE TITLE
Custom sorting on category pages not working if out of stock products are shown

### ISSUE THREAD

**Issue by codebase-md** [magento/magento2#36113] opened 2022-09-08 07:07 UTC
### Preconditions and environment

- M 2.4.5
- Show out of stock Products(`cataloginventory/options/show_out_of_stock`) is enabled
- You are on a category page

### Steps to reproduce

1. Enable `cataloginventory/options/show_out_of_stock`(Show out of stock products)
2. Introduce a custom sort order
3. Navigate to a category page and apply custom sorting

### Expected result

Custom sort order is applied.

### Actual result

Custom sort order is not applied. Only sorting by name, price(asc/desc) and position are working.

### Additional information

I investigated this issue and traced it down to the function `\Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::categoryProductByCustomSortOrder` which has been introduced with M2.4.5. It creates a new select statement due to which former table joins are lost. But these joins are necessary for the loop which applies sort orders(line 234 and following). Additionally it applies a hardcoded sort order for salability which moves out of stock products to the end of a product listing no matter what. This behavior might not be wanted in every case. We created two patches which fix this issue:

First one does not remove sorting by `is_salable` so out of stock products will be displayed at the end of a listing:
```
Index: vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	(date 1662547508268)
@@ -213,17 +213,12 @@
         $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
 
         $connection = $this->collection->getConnection();
-        $query = clone $connection->select()
+        $query = clone $this->collection->getSelect()
             ->reset(\Magento\Framework\DB\Select::ORDER)
             ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
-            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
-            ->reset(\Magento\Framework\DB\Select::COLUMNS);
-        $query->from(
-            ['e' => $this->collection->getTable('catalog_product_entity')],
-            ['e.entity_id']
-        );
+            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
+
         $this->stockStatusApplier->setSearchResultApplier(true);
-        $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
         $query->join(
             ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
             'cat_index.product_id = e.entity_id'

```
Second patch removes sorting by salability as well:
```
Index: vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php
--- a/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	
+++ b/vendor/magento/module-elasticsearch/Model/ResourceModel/Fulltext/Collection/SearchResultApplier.php	(date 1662619604901)
@@ -210,20 +210,14 @@
         $storeId = $this->collection->getStoreId();
         $searchCriteria = $this->searchResult->getSearchCriteria();
         $sortOrders = $searchCriteria->getSortOrders() ?? [];
-        $sortOrders = array_merge(['is_salable' => \Magento\Framework\DB\Select::SQL_DESC], $sortOrders);
 
         $connection = $this->collection->getConnection();
-        $query = clone $connection->select()
+        $query = clone $this->collection->getSelect()
             ->reset(\Magento\Framework\DB\Select::ORDER)
             ->reset(\Magento\Framework\DB\Select::LIMIT_COUNT)
-            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET)
-            ->reset(\Magento\Framework\DB\Select::COLUMNS);
-        $query->from(
-            ['e' => $this->collection->getTable('catalog_product_entity')],
-            ['e.entity_id']
-        );
+            ->reset(\Magento\Framework\DB\Select::LIMIT_OFFSET);
+
         $this->stockStatusApplier->setSearchResultApplier(true);
-        $query = $this->stockStatusFilter->execute($query, 'e', 'stockItem');
         $query->join(
             ['cat_index' => $this->collection->getTable('catalog_category_product_index_store' . $storeId)],
             'cat_index.product_id = e.entity_id'
```
I can't promise that it is the best or even correct solution but it fixes this issue for now. Feedback welcome.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rogerdz** [comment] 2022-09-08 07:55
i think new select on magento 2.4.5 is not necessary, move out stock product to bottom of list should be done via elasticsearch. Can you try https://github.com/magento/magento2/pull/36102 and confirm it's working properly?

**Comment by gwharton** [comment] 2022-09-11 16:34
Related to https://github.com/magento/magento2/issues/35920

**Comment by khnaim** [comment] 2022-10-03 10:33
Hello,

I have de same problem (Adobe Commerce ver. 2.4.5).

Do you have a solution to fix this problem?

TIA

**Comment by engcom-Bravo** [comment] 2022-10-03 12:30
Hi @codebase-md,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and the issue is reproducible with above steps to reproduce. however, similar issue has been confirmed here [35920](https://github.com/magento/magento2/issues/35920).


Hence we are closing this as duplicate.


Thanks.

**Closed as completed by engcom-Bravo** 2022-10-03 12:30 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.5

**Comment by idlea** [comment] 2022-11-26 10:36
thank you just disabling show out of stock products worked, strange though I have 3 magento sites and only one had this problem

**Comment by idlea** [comment] 2022-12-05 09:21
thanks for now I have disabled show out of stock products
