### ISSUE TITLE
Inconsistent behaviour of getStockItem() and getStockData()

### ISSUE THREAD

**Issue by GamesmenJordan** [magento/magento2#37937] opened 2023-08-30 02:15 UTC
### Preconditions and environment

Magento version 2.4.5 (tested)

Create simple observer for event `catalog_product_save_before` with the following `execute` method:

```php
public function execute(\Magento\Framework\Event\Observer $observer) {
        $product = $observer->getProduct();
        $stockItem = $product->getStockItem();
        $stockData = $product->getStockData();
        return; //set breakpoint here
}
```

### Steps to reproduce

1. Save a product in the Admin portal
2. Observe that `$stockData` will be populated with the stock item object, but `$stockItem` will be null
3. Save a product via the REST API
4. Observe that `$stockItem` will be populated with the stock item object, but now `$stockData` will be null

### Expected result

Both `getStockData()` or `getStockItem()` should behave consistently regardless of how the product is saved, likely both returning the data or one function becoming an alias for the other.

### Actual result

1. `getStockData()` only returns the stock item object if the product was saved via the admin portal UI, otherwise returning null.
2. `getStockItem()` only returns the stock item object if the product was saved via the REST API, otherwise returning null.

Both functions return the same stock item object in their respective scenarios.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Usik2203** [comment] 2023-08-30 08:56
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2023-09-01 08:52
Hello @GamesmenJordan,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but it seems the issue is not reproducible for us. We have made an Observer in order to reproduce the issue.

Please find below the same as a reference:

[Magz.zip](https://github.com/magento/magento2/files/12496164/Magz.zip)

We request you to please review the steps to reproduce and let us know if anything is missed.

Thanks

**Comment by engcom-Hotel** [comment] 2023-09-21 08:19
Dear @GamesmenJordan,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-09-21 08:19 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5

**Comment by aario** [comment] 2025-01-23 14:01
Same issue here. v2.4.4
