### ISSUE TITLE
Store -> Attribute -> Product Attribute -> Manage Options (Values of Your Attribute) Can Not Accept More Than 110 Values

### ISSUE THREAD

**Issue by malikhokhar** [magento/magento2#8549] opened 2017-02-14 15:30 UTC
### Preconditions

1. Magento ver. 2.1.3
2. PHP 7

### Steps to reproduce

1. Store -> Attribute -> Product Attribute
2. Manage Options (Values of Your Attribute) 
3. If we add values more than 110 it will just vanish it. It will say it is saved. But when you reopen all gone above 110. 

### Expected result

1. There should not be any limit and it should allow as many as required.

### Actual result

1. https://snag.gy/d9U473.jpg

**Comment by thlassche** [comment] 2017-02-14 15:33
@malikhokhar Are you sure you are not hitting the `max_input_vars` PHP limit? (see your php.ini)

**Comment by malikhokhar** [comment] 2017-02-14 15:41
@thlassche Thank you. I tried searching but did not find any solution for this. Yes that was the problem.

I had to remove ; from there and default value was enough to handle it i.e. max_input_vars = 10000 

Thanks Once Again.

**Comment by choukalos** [comment] 2017-02-15 17:19
Closing not a bug; configuration.

**Closed as completed by choukalos** 2017-02-15 17:19 UTC
