### ISSUE TITLE
Products Import Not Display.

### ISSUE THREAD

**Issue by shuaiZend** [magento/magento2#3131] opened 2016-01-26 03:45 UTC
ENV:
Magento2 V:2.0.1

```
[root@localhost M2db]# php -v
PHP 5.6.16 (cli) (built: Jan 10 2016 02:31:28) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies
```
## Webserver:nginx version: nginx/1.8.0

so， first check csv，is pass

and I import notice:Import successfully done

But,in catalog and  categories ,no any products..
no any Error information...

any help?

[Uploading myimportcsv.zip…]()
[Uploading myimportcsv.zip…]()

**Comment by shuaiZend** [comment] 2016-01-26 03:50
sorry,file cant upload.pls save to csv:
sku,store_view_code,attribute_set_code,product_type,categories,product_websites,name,description,short_description,weight,product_online,tax_class_name,visibility,price,url_key,meta_title,meta_keywords,meta_description,base_image,small_image,thumbnail_image,display_product_options_in,map_price,msrp_price,msrp_display_actual_price_type,country_of_manufacture,additional_attributes,qty,out_of_stock_qty,use_config_min_qty,is_qty_decimal,allow_backorders,use_config_backorders,min_cart_qty,use_config_min_sale_qty,max_cart_qty,use_config_max_sale_qty,is_in_stock,notify_on_stock_below,use_config_notify_stock_qty,manage_stock,use_config_manage_stock,use_config_qty_increments,qty_increments,use_config_enable_qty_inc,enable_qty_increments,is_decimal_divided,website_id,deferred_stock_update,use_config_deferred_stock_update,related_skus,crosssell_skus,upsell_skus,additional_images,additional_image_labels,hide_from_product_page,custom_options,bundle_price_type,bundle_sku_type,bundle_price_view,bundle_weight_type,bundle_values,associated_skus
H-LVMOADM40988SD-N,,Bag,simple,"Home,Home/Louis Vuitton,Home/Louis Vuitton/Louis Vuitton Monogram",base,Louis Vuitton Monogram Speedy 20 Bag M40988,"<p>Louis Vuitton Monogram Speedy 20 Bag M40988 Brown <br />The Speedy is an iconic Louis Vuitton design. Its simple lines and chic Monogram canvas immediately appeal to women with an eye for fashion. The perfect bag for the city.<br />Bronze color metallic pieces.Ultra-grade bronze metal handle, Speedy handbag iconic Louis Vuitton design. It is the perfect choice for city handbags.<br />Elegant hand carry<br />Zip closure and padlock<br />High-density copper metal plating, suture delicate, extremely light, retro, any gift to fashion and dress are female flavor.</p>",,1,1,Taxable Goods,"Catalog, Search",548,Louis Vuitton Monogram Speedy 20 Bag M40988 Brown  H-LVMOADM40988SD-N,Louis Vuitton Monogram Speedy 20 Bag M40988 Brown  H-LVMOADM40988SD-N,,,H-LVMOADM40988SD-N.jpg,H-LVMOADM40988SD-N.jpg,H-LVMOADM40988SD-N.jpg,Block after Info Column,,,Use config,,"brand=Louis Vuitton,gender=Women,size=W22XH18XD14(cm),type=Shoulder Bags|CrossBody Bags,color=Brown",100,0,1,0,0,1,1,0,0,1,1,,1,0,1,1,0,1,0,0,1,0,1,"24-WG087,24-WG086","24-WG087,24-WG086","24-WG087,24-WG086","H-LVMOADM40988SD-N_1.jpg,H-LVMOADM40988SD-N_2.jpg,H-LVMOADM40988SD-N_3.jpg,H-LVMOADM40988SD-N_4jpg,H-LVMOADM40988SD-N_5jpg,H-LVMOADM40988SD-N_6jpg,H-LVMOADM40988SD-N_7jpg,H-LVMOADM40988SD-N_8jpg,H-LVMOADM40988SD-N_9jpg","Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 01,Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 02，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 03，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 04，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 05，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 06，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 07，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 08，Louis Vuitton Monogram Speedy 20 Bag M40988 Brown 09  ",,"name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=,option_title=Gold|name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=,option_title=Silver|name=Custom Yoga Option,type=drop_down,required=0,price=10.0000,price_type=fixed,sku=yoga3sku,option_title=Platinum",,,,,,
H-LVMOADM40989MD-N,,Bag,simple,"Home,Home/Louis Vuitton,Home/Louis Vuitton/Louis Vuitton Monogram",base,Louis Vuitton Monogram Speedy 25 Bag M40989,"<p>Louis Vuitton Monogram Speedy 25 Bag M40989 Brown<br />The Speedy is an iconic Louis Vuitton design. Its simple lines and chic Monogram canvas immediately appeal to women with an eye for fashion. The perfect bag for the city.<br />Bronze color metallic pieces.Ultra-grade bronze metal handle, Speedy handbag iconic Louis Vuitton design. It is the perfect choice for city handbags.<br />Elegant hand carry<br />Zip closure and padlock<br />High-density copper metal plating, suture delicate, extremely light, retro, any gift to fashion and dress are female flavor.</p>",,1,1,Taxable Goods,"Catalog, Search",568,Louis Vuitton Monogram Speedy 25 Bag M40989 Brown  H-LVMOADM40989MD-N,Louis Vuitton Monogram Speedy 25 Bag M40989 Brown  H-LVMOADM40989MD-N,,,H-LVMOADM40989MD-N_1.jpg,H-LVMOADM40989MD-N_1.jpg,H-LVMOADM40989MD-N_1.jpg,Block after Info Column,,,Use config,,"brand=Louis Vuitton,gender=Women,size=W25XH19XD15(cm),type=Shoulder Bags|CrossBody Bags,color=Brown",100,0,1,0,0,1,1,0,0,1,1,,1,0,1,1,0,1,0,0,1,0,1,24-WG087,24-WG087,24-WG087,"H-LVMOADM40989MD-N_1.jpg,H-LVMOADM40989MD-N_2.jpg,H-LVMOADM40989MD-N_3.jpg,H-LVMOADM40989MD-N_4jpg,H-LVMOADM40989MD-N_5jpg,H-LVMOADM40989MD-N_6jpg,H-LVMOADM40989MD-N_7jpg,H-LVMOADM40989MD-N_8jpg,H-LVMOADM40989MD-N_9jpg","Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 01,Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 02，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 03，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 04，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 05，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 06，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 07，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 08，Louis Vuitton Monogram Speedy 25 Bag M40989 Brown 09  ",,,,,,,,
H-LVMOADM40990LD-N,,Bag,simple,"Home,Home/Louis Vuitton,Home/Louis Vuitton/Louis Vuitton Monogram",base,Louis Vuitton Monogram Speedy 30 Bag M40990,"<p>Louis Vuitton Monogram Speedy 30 Bag M40990 Brown<br />The Speedy is an iconic Louis Vuitton design. Its simple lines and chic Monogram canvas immediately appeal to women with an eye for fashion. The perfect bag for the city.<br />Bronze color metallic pieces.Ultra-grade bronze metal handle, Speedy handbag iconic Louis Vuitton design. It is the perfect choice for city handbags.<br />Elegant hand carry<br />Zip closure and padlock<br />High-density copper metal plating, suture delicate, extremely light, retro, any gift to fashion and dress are female flavor.</p>",,1,1,Taxable Goods,"Catalog, Search",579,Louis Vuitton Monogram Speedy 30 Bag M40990 Brown H-LVMOADM40990LD-N,Louis Vuitton Monogram Speedy 30 Bag M40990 Brown H-LVMOADM40990LD-N,,,H-LVMOADM40990LD-N_1.jpg,H-LVMOADM40990LD-N_1.jpg,H-LVMOADM40990LD-N_1.jpg,Block after Info Column,,,Use config,,"brand=Louis Vuitton,gender=Women,size=W30XH21XD17(cm),type=Shoulder Bags|CrossBody Bags,color=Brown",100,0,1,0,0,1,1,0,0,1,1,,1,0,1,1,0,1,0,0,1,0,1,24-WG086,24-WG086,24-WG086,"H-LVMOADM40990LD-N_1.jpg,H-LVMOADM40990LD-N_2.jpg,H-LVMOADM40990LD-N_3.jpg,H-LVMOADM40990LD-N_4jpg,H-LVMOADM40990LD-N_5jpg,H-LVMOADM40990LD-N_6jpg,H-LVMOADM40990LD-N_7jpg,H-LVMOADM40990LD-N_8jpg","Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 01,Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 02，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 03，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 04，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 05，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 06，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 07，Louis Vuitton Monogram Speedy 30 Bag M40990 Brown 08",,,,,,,,
H-LVMOADM41693MD-N,,Bag,simple,"Home,Home/Louis Vuitton,Home/Louis Vuitton/Louis Vuitton Monogram",base,Louis Vuitton Monogram Sac Triangle PM Bag M41693,"<p>Louis Vuitton Monogram Sac Triangle PM Bag M41693<br />The new Sac Triangle in iconic Monogram is one of the stars of the F/W 15 show. Arranged around a lock inspired by a custom Vuitton design from the 1930s, the Triangle&rsquo;s structured shape and sliding leather strap makes it a versatile piece, one that will complement a wide range of looks, from day into evening.<br />\- Monogram Canvas<br />\- Trunk lock closure<br />\- Cowhide trim<br />\- Microfiber lining<br />\- Sliding leather strap<br />\- D-ring for charm<br />\- 2 inside flat pocket</p>",,1,1,Taxable Goods,"Catalog, Search",438,Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown H-LVMOADM41693MD-N,Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown H-LVMOADM41693MD-N,,,H-LVMOADM41693MD-N.jpg,H-LVMOADM41693MD-N.jpg,H-LVMOADM41693MD-N.jpg,Block after Info Column,,,Use config,,"brand=Louis Vuitton,gender=Women,size=W31XH16XD10(cm),type=Shoulder Bags|Clutches,color=Brown",100,0,1,0,0,1,1,0,0,1,1,,1,1,1,1,0,1,0,0,1,0,1,"24-WG087,24-WG086","24-WG087,24-WG086","24-WG087,24-WG086","H-LVMOADM41693MD-N_1.jpg,H-LVMOADM41693MD-N_2.jpg,H-LVMOADM41693MD-N_3.jpg,H-LVMOADM41693MD-N_4jpg,H-LVMOADM41693MD-N_5jpg,H-LVMOADM41693MD-N_6jpg,H-LVMOADM41693MD-N_7jpg","Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 01,Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 02，Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 03，Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 04，Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 05，Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 06，Louis Vuitton Monogram Sac Triangle PM Bag M41693 Brown 07  ",,,,,,,,"24-WG085=5.0000,24-WG086=5.0000"

**Comment by mazhalai** [comment] 2016-01-26 16:52
@shuaiZend is this using the data import tool? can you please provide steps to reproduce?

**Comment by davidalger** [comment] 2016-02-12 03:01
Closing due to lack of reply from OP

**Closed as completed by davidalger** 2016-02-12 03:01 UTC
Labels: Progress: needs update
