### ISSUE TITLE
Unable to add a thumbnail picture of a video to a product

### ISSUE THREAD

**Issue by maxlussier** [magento/magento2#32978] opened 2021-05-09 13:38 UTC
### Preconditions (*)

1. Magento Open-Source 2.4.2
2. Ubuntu 20.04, PHP 7.4.19, MariaDB 10.4
2. With Patch MDVA-35092 applied
3. Sample Catalog data are installed

Not the same issue as: https://github.com/magento/magento2/issues/32897

### Steps to reproduce (*)

1. Go to admin. Catalog > Product.
2. Edit a product.
3. Go to section Images and Videos
4. Click on Add Video
5. Enter the following URL: https://vimeo.com/9123745
6. Leave all other inputs as they are being filled by Vimeo
7. Click on Save button

### Expected result (*)

1. The video should be saved as a media gallery entries for a product
2. The modal should close
3. You should be able to continue editing the product and save it.

### Actual result (*)

1. An error message appears under the Video URL input saying Wrong File.
2. Prevents from saving.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by maxlussier** [comment] 2021-05-09 13:39
@magento give me 2.4-develop instance

**Comment by maxlussier** [comment] 2021-05-09 14:00
Unable to reproduce the issue with the Magento instance.

Could it be because I'm running locally? The POST AJAX request: https://88fd4427d143c69df86eb9b576fdda22-2-4-develop.instances.magento-community.engineering/admin_f9e0/product_video/product_gallery/retrieveImage/?isAjax=true

I would need someone other than myself to validate a local setup on Ubuntu having the same issue.

**Comment by hostep** [comment] 2021-05-11 20:24
@maxlussier: can you try upgrading to Magento 2.4.2-p1 that got released just today. It contains a fix for Vimeo problems. It might fix your issue...

**Comment by maxlussier** [comment] 2021-05-15 00:49
Hi @hostep, thanks for looking into this issue. The fix you are talking about was included in the given instance and my issue is still occurring. Although I have to precise that the issue I'm having has nothing do to with Vimeo per se and has everything to do the fact that Magento is not able to validate, for a lack of better word, the vimeo product thumbnail.

Like I've said previously, I think this is environment related and it might be a non-problem since it only seems to occurred in my ubuntu local environment setup.

**Comment by engcom-Golf** [comment] 2021-06-01 13:50
@ajijshekh123 I have un-assigned this ticket from your name as It seems you are not working on it. I have assigned this to myself.

**Comment by ajijshekh123** [comment] 2021-06-01 15:10
Sorry @engcom-Golf - I missed this ticket. Thanks for verified the issue.

**Comment by engcom-Golf** [comment] 2021-06-02 07:34
@maxlussier Please confirm your issue is fixed?

**Comment by engcom-Golf** [comment] 2021-06-07 13:53
@maxlussier  I tried to reproduce this issue, but can't reproduce on Magento 2.4.2. It is working as expected. So considering this, I am closing this Issue.

**Closed as completed by engcom-Golf** 2021-06-07 13:53 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce

**Comment by sunilit42** [comment] 2021-06-16 13:28
@magento give me 2.4-develop instance
