### ISSUE TITLE
Can't duplicate Magento 2 configurable product

### ISSUE THREAD

**Issue by albsa** [magento/magento2#18208] opened 2018-09-23 10:30 UTC
### Preconditions

1. 2.2.5 & 2.2.6
2. PHP 7.1.21 

### Steps to reproduce

1. Create a configurable product with color attribute.
2. Upload several images and assign different variations
3. Try to duplicate the product

### Expected result

1. Duplicated configurable product

### Actual result

1. Infinite image creation loop untill process quits. It generates more than 25000 images when trying to duplicate
2. Page keeps loading and product never get's duplicated

**Comment by magento-engcom-team** [comment] 2018-09-23 10:30
Hi @albsa. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@albsa do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by albsa** [comment] 2018-09-23 12:05
### Additional information
My configurable products contains custom options.
I tried to duplicate a product without custom options and there it seems to duplicate without any issue.
I am not sure if this has anything to do with it, I am still searching.

**Comment by hostep** [comment] 2018-09-23 13:05
Hi @albsa, this sounds like a duplicate of https://github.com/magento/magento2/issues/9466, do you agree?

**Comment by albsa** [comment] 2018-09-23 13:38
@hostep The bug is in the same direction, the only thing is, as far as I understand from his comment, he succeeds duplicating a configurable product, at my end it seems stuck and keeps loading / generating pictures forever untill I quit the process. My product never gets duplicated.

**Comment by albsa** [comment] 2018-09-23 13:39
Also strange thing is, when I generate a new configurable product with all the same details, the error does not occur. It seems like this issue happens with products that are migrated from M1.

**Comment by hostep** [comment] 2018-09-23 14:18
We've seen this bug happening in the wild where it kept copying image files until the server's diskspace was completely full. And then the duplication didn't finish because of that.

The core issue of bug #9466 is the fact that it tries to re-save the product on and on and on until it finds an url_key which is not used by another product.
There is a high likelihood that migrating products from M1 to M2 doesn't fix duplicated url_key's in the process, so make sure all url_key's of all products are unique before migrating from M1 to M2. Once that's the case, the problem might still occur in M2, but will happen less noticeable, since there will be much fewer url_key duplicates.

Let's close this as a duplicate of #9466

**Closed as completed by hostep** 2018-09-23 14:18 UTC
Labels: Issue: Format is valid
