### ISSUE TITLE
Error when trying to change the sku on a configurable product in mage 2.0.9

### ISSUE THREAD

**Issue by Onkovat** [magento/magento2#6495] opened 2016-09-05 13:08 UTC
When trying to change the sku of a configurable product in magento 2.0.9 then this error appears:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db174m2001`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DE), query was: UPDATE `catalog_product_entity` SET `attribute_set_id` = ?, `type_id` = ?, `sku` = ?, `has_options` = ?, `required_options` = ?, `created_at` = '2016-08-23 11:09:45', `updated_at` = '2016-08-23 11:25:00' WHERE (`entity_id`=78)

The virtual child products can have their sku changed without problems though since the parent product's sku is shown in frontend for all childs also (shouldn't it change depending on options chosen?) then it should be changed also.
### Preconditions

Magento 2.0.9
Configurable product, three virtual products with different colors.
### Expected result

That it simply changes the sku everywhere needed.
### Actual result

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`db174m2001`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DE), query was: UPDATE `catalog_product_entity` SET `attribute_set_id` = ?, `type_id` = ?, `sku` = ?, `has_options` = ?, `required_options` = ?, `created_at` = '2016-08-23 11:09:45', `updated_at` = '2016-08-23 11:25:00' WHERE (`entity_id`=78)

Since I can't wait, is there a workaround?

**Comment by sevos1984** [comment] 2016-09-06 09:01
Can't reproduce on 2.0.9 clear install. Maybe you have upgraded from previous versions?

**Comment by Onkovat** [comment] 2016-09-06 11:16
sevos1984, maybe it behaves differently when the virtual products changed their sku upfront before changing the sku of the configurable product?

In any case, yes the project was a 2.0.7 where the products were created, then moved to a different subdomain and upgraded to 2.0.9.

**Comment by sevos1984** [comment] 2016-09-06 12:31
Tried to create configurable with virtual, then upgrade to 2.0.9 and change Sku and all works fine. Is there any problem with non virtual sub-products?

**Comment by sevos1984** [comment] 2016-09-26 12:14
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:14 UTC
Labels: bug report, Progress: needs update

**Comment by zhooravlik** [comment] 2018-05-14 19:32
The same error occurs on M2.2.3 on Import -> Products
