### ISSUE TITLE
changing order email address

### ISSUE THREAD

**Issue by leighrmassey** [magento/magento2#39082] opened 2024-08-21 12:24 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
I change the email address to mine. Click save come out then go back in and it reverts back to current.

### Steps to reproduce

I change the email address to mine. Click save come out then go back in and it reverts back to current.

### Expected result

I change the email address to mine. Click save come out then go back in and it reverts back to current.

### Actual result

I change the email address to mine. Click save come out then go back in and it reverts back to current.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-08-27 07:28
Hi @leighrmassey,

Thanks for your reporting and collaboration.

Could you please elaborate the steps to reproduce and differentiate the expected and actual results ,if possible please provide us screenshots.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-09 06:14
Hi @leighrmassey,


We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-09 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.x
