### ISSUE TITLE
Disabling of products as no stock but system re enables it with out authorization

### ISSUE THREAD

**Issue by Vinylcutters** [magento/magento2#38131] opened 2023-10-30 10:54 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

We Disabling products due to no stock but system re enables it with out authorization. Causing an issue as clients buying products and we dont have stock. Please fix. Thanks

### Expected result

Product to be disabled for future use.

### Actual result

We Disabling products due to no stock but system re enables it with out authorization. Causing an issue as clients buying products and we dont have stock. Please fix. Thanks

### Additional information

We Disabling products due to no stock but system re enables it with out authorization. Causing an issue as clients buying products and we dont have stock. Please fix. Thanks

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-31 06:03
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-31 10:48
Hi @Vinylcutters,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


We have disabled the products as no stock and we are not able to place the order for that products.Could you please check the issue in Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-13 05:54
Hi @Vinylcutters,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38131#issuecomment-1786967175 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:02
Hi @Vinylcutters,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-20 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.x
