### ISSUE TITLE
Wrong items showing while creating an order from admin

### ISSUE THREAD

**Issue by rani-priya** [magento/magento2#26865] opened 2020-02-13 17:54 UTC
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. navigate to backend -> sales -> order
2. view any order
3. then in another tab try create new order
4. in previous tab(step - 2) click on edit order and then select products in current tab where you are creating new order
5. select any random product and add to order
6. here you will see additional items of edited order

### Expected result (*)

1. only selected products should be added to the cart

### Actual result (*)

1. additional items of edited order are getting added to the cart

**Comment by krishprakash** [comment] 2020-02-14 06:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-14 06:47
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-14 06:47
Hi @krishprakash, here is your [Magento instance](https://i-26865-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26865-2-4-develop.instances.magento-community.engineering/admin_1abe](https://i-26865-2-4-develop.instances.magento-community.engineering/admin_1abe)
Login: `b21d79b5` Password: `39e0c2495e83`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-02-14 07:27
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31516` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by desaiun** [comment] 2020-02-29 09:27
Hi @rani-webkul, Magento default behavior as per browser session not as per browser tab.
I have check with the Magento 2.4-develop instance and reproduce this Issue but Magento Native order quote generate as per session and at a time only one session can be generate so if you try to create new order in another tab then previous tab order products already added in that new one.

**Comment by sdzhepa** [comment] 2020-07-23 17:47
Hello @rani-webkul
cc: @krishprakash 

Could you please provide more details about step "4. ...click on edit order "?
> 4. in previous tab(step - 2) click on edit order and then select products in current tab where you are creating new order

How exactly you edit old order and add/change products to it? I do not see a button for edit order items only for billing/shipping addresses

**Comment by sdzhepa** [comment] 2020-08-18 20:02
Closed as cannot reproduce

**Closed as completed by sdzhepa** 2020-08-18 20:02 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Reported on 2.3.x
