### ISSUE TITLE
Cache frontend 'default' is not recognized. As well as defaultcache is not configured

### ISSUE THREAD

**Issue by technicalrajni** [magento/magento2#37237] opened 2023-03-18 12:22 UTC
### Preconditions and environment

- Magento version 2.4.6
- fresh installation with php 8.1
- InvalidArgumentException: Cache frontend 'default' is not recognized. As well as defaultcache is not configured in /var/www/html/magentotest/project-community-edition/vendor/magento/framework/App/Cache/Frontend/Pool.php:157
Stack trace:
#0 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get()
#1 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/App/Cache/Type/Config.php(49): Magento\Framework\App\Cache\Type\FrontendPool->get()
#2 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend()
#3 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/Interception/PluginList/PluginList.php(227): Magento\Framework\Cache\Frontend\Decorator\Bare->load()
#4 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/Interception/PluginList/PluginList.php(190): Magento\Framework\Interception\PluginList\PluginList->_loadScopedData()
#5 /var/www/html/magentotest/project-community-edition/generated/code/Magento/Framework/App/State/Interceptor.php(22): Magento\Framework\Interception\PluginList\PluginList->getNext()
#6 /var/www/html/magentotest/project-community-edition/vendor/magento/module-developer/Model/Logger/Handler/Debug.php(71): Magento\Framework\App\State\Interceptor->getMode()
#7 /var/www/html/magentotest/project-community-edition/vendor/magento/module-developer/Model/Logger/Handler/Debug.php(56): Magento\Developer\Model\Logger\Handler\Debug->isLoggingEnabled()
#8 /var/www/html/magentotest/project-community-edition/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(31): Magento\Developer\Model\Logger\Handler\Debug->isHandling()
#9 /var/www/html/magentotest/project-community-edition/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle()
#10 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/Logger/Monolog.php(48): Monolog\Logger->addRecord()
#11 /var/www/html/magentotest/project-community-edition/vendor/monolog/monolog/src/Monolog/Logger.php(712): Magento\Framework\Logger\Monolog->addRecord()
#12 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/Logger/LoggerProxy.php(126): Monolog\Logger->error()
#13 /var/www/html/magentotest/project-community-edition/vendor/magento/framework/App/Bootstrap.php(269): Magento\Framework\Logger\LoggerProxy->error()
#14 /var/www/html/magentotest/project-community-edition/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#15 {main}

### Steps to reproduce

Install Latest magento 2 version via composer with php 8.1
After try to access the website this issue comes

### Expected result

Expected it should show me the magento 2 default website

### Actual result

Expected it should show me the magento 2 default website

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-20 13:23
Hi @rajni98,

Thank you for reporting and collaboration.

Verified the issue while installing 2.4.6 magento instance we are not able to reproduce the issue. Kindly refer the screenshots.


We are able to access the default website.


<img width="1501" alt="Screenshot 2023-03-20 at 2 57 22 PM" src="https://user-images.githubusercontent.com/51680745/226351816-41e9b7ca-e14f-43bf-a104-6eca7132a3f6.png">




<img width="1449" alt="Screenshot 2023-03-20 at 2 57 30 PM" src="https://user-images.githubusercontent.com/51680745/226351892-fffe2417-cef5-4059-a26e-2f05143e3906.png">



Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-31 08:27
Hi @rajni98,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-03-31 08:27 UTC
Labels: Issue: needs update, Reported on 2.4.6
