### ISSUE TITLE
Magento 2 Wishlist GraphQl Not Working. if the product which is not even related to user's wishlist removed.

### ISSUE THREAD

**Issue by ankithg03** [magento/magento2#33502] opened 2021-07-16 11:34 UTC
### Preconditions (*)

1. Magento ver 2.4.2
2. Magento ver 2.4.2-p1

### Steps to reproduce (*)

1. keep alot of products in your Magento.
2. add products to wishlist.(Must be Logged in User)
3. then delete a Product with id 5, if your wishlist id is 5 which is not any way related to that wishlist or to customer.

### Expected result (*)

1. The Proper Response of wishlist item and its product
2. The Screenshot Attached.
![screenshot-127 0 0 1_3003-2021 07 16-16_29_43 (1)](https://user-images.githubusercontent.com/67680823/125940793-92be894c-fc59-44da-aa9c-a3e9e9e631dc.png)

### Actual result (*)

1. Instead of the Proper Response of Wishlist item and its Product, the error was thrown called "The product that was requested doesn't exist..."
2.The Screenshot Attached.
![screenshot-127 0 0 1_3003-2021 07 16-16_29_43](https://user-images.githubusercontent.com/67680823/125941027-ad3b007d-69c5-482e-b493-594dbc6a532b.png)

### Note: GraphQl Query 
```
{
  wishlist {
    items_count
    updated_at
    items {
      id
      qty
      description
      product {
        id
        sku
        name
        stock_status
      }
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ankithg03** [comment] 2021-07-16 11:34
I'm Working on the issue

**Comment by Den4ik** [comment] 2021-07-19 09:25
@ankithg03 After removing product that contained in customer wishlist I receive empty response
```
{
  "data": {
    "wishlist": {
      "items_count": 0,
      "updated_at": "2021-07-19 08:48:31",
      "items": []
    }
  }
}
```

Wishlist items linked to product table and after removing the product wishlist item removed too.
May be you could add more details for reproducing the issue.

**Comment by glo80326** [comment] 2021-08-18 13:38
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Echo** [comment] 2021-08-18 13:40
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Echo** [comment] 2021-08-18 13:41
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-18 13:42
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-18 13:46
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-18 14:16
Hi @ankithg03 
We tried to reproduce this issue on 2.4-develop & were unable to do so.
Here are the Steps we followed,
1. On a clean instance of magento, Login as Customer on frontend.
2. Add couple of products to wishlist.
3. Send Request to GraphQL wishlist query & check if all the items added to wishlist are retrieved successfully.
4. Then delete a Product which was included in the wishlist, Send Request to GraphQL wishlist query.
**Response**: All the items added to wishlist were retrieved successfully expect the product that was deleted. **No Error** in Response.
<img width="1277" alt="Screenshot 2021-08-18 at 19 44 17" src="https://user-images.githubusercontent.com/51681435/129914287-d079d7c9-07d7-4f90-9f12-0da644f43e92.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional/missing steps regarding the same.

Thank you.

**Comment by engcom-Echo** [comment] 2021-09-01 07:28
Hi @ankithg03 
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported, we are closing this issue.
If this issue is still reproducible for you on magento **2.4-develop**, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Closed as completed by engcom-Echo** 2021-09-01 07:28 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
