### ISSUE TITLE
Magento 2.2.X - WYSIWYG editor, insert image directive not replaced by actual image URL

### ISSUE THREAD

**Issue by dverkade** [magento/magento2#12741] opened 2017-12-15 12:57 UTC
When the users adds an image in the WYSIWYG editor with the "Insert Image" option a URL is generated by Magento with a directive in it. This directive should be replaced when saving the page so that the directive URL is replaced by the correct media URL in Magento. Currently this does not happen and on the frontend the Directive URL is shown. This will result in broken images on the frontend. 

### Preconditions
1. Checked on Magento version 2.1.X, 2.2.0 and 2.2.1 

### Relations
Relates to:
#7167 2.2.0-dev - cms images are being added as __directive for path

Pull requests already fixing this issue, but closed without merging:
#12467 WYSIWYG JS - Directive URL not always properly detected 

### Steps to reproduce
1. Create a new CMS page in the backend of Magento
2. Open the WYSIWYG editor and use the "Insert Image" option in the toolbar to insert an image. (See screenshot below).
3. Save the page.
4. The admin user needs to logout of the backoffice.
5. Go to the CMS page on the frontend of Magento. The inserted image will be broken, when inspecting the HTML you will see that the image URL will be something like: "domain.com/admin/cms/wysiwyg/directive/___directive/e3ttZWRpYSB1cmw9Ind5c2l3eWcvQmxvZ19JbWczLnBuZyJ9fQ%2C%2C/key/4f92067f70cff318e8618a7e322e964261df0edae0581197d92cd51a93ba198d/"

![image](https://user-images.githubusercontent.com/1058480/34042786-8d866644-e19e-11e7-9372-46772eb47c92.png)
To reproduce, use this dialog in order to insert the image into the editor.

### Expected result
1. When switching with the "Show / Hide editor option" the directive URL should be replaced with the correct image URL. 
2. The URL needs to be replaced by the correct name of the image. So that on the frontend the correct image will be loaded. 

![image](https://user-images.githubusercontent.com/1058480/34042967-411c3080-e19f-11e7-9ace-93ee5181c4f0.png)
![image](https://user-images.githubusercontent.com/1058480/34042984-58856c50-e19f-11e7-9dbf-b2666edb410f.png)

### Actual result
1. The long directive URL is not replaced and is shown on the frontend resulting in broken images.

![image](https://user-images.githubusercontent.com/1058480/34043007-73c6151e-e19f-11e7-9ed6-b561ce02dfe4.png)
![image](https://user-images.githubusercontent.com/1058480/34043043-95009330-e19f-11e7-9283-6349655b7ed8.png)

**Comment by magento-engcom-team** [comment] 2017-12-15 13:48
@dverkade, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-15 13:48 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid

**Comment by dverkade** [comment] 2017-12-15 14:41
Hi @magento-engcom-team,

Thank you for your reply. We have tested this on Magento 2.2.2 on this works correct now. Please note that I could not find that this issue was resolved in the Magento 2.2.2 release notes. Searched for "directive" and "wysiwyg" and both did not mention resolving this issue.

Please also close this issue #7167  which is the same issue and is resolved in Magento 2.2.2 now. So this can be closed as well.
