### ISSUE TITLE
Elasticsearch doesn't find attribute value

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#26414] opened 2020-01-16 07:36 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Elasticsearch 6.8

### Steps to reproduce (*)

1. Configure Elasticsearch (https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html)
2. Add "color" attribute to default attribute set
3. Edit "color" attribute and color value, e.g. "red"
4. Make sure that color attribute is searchable
5. Create simple product with color "red"
<img width="866" alt="Screenshot 2020-01-16 at 08 35 00" src="https://user-images.githubusercontent.com/1945725/72503078-2ac4fc00-383b-11ea-89e0-fe8044e98185.png">
6. Clear cache
7. Reindex catalog
8. Open frontend and search for "red"

### Expected result (*)

1. Created product should be found

### Actual result (*)

1. Search returns no result
<img width="1272" alt="Screenshot 2020-01-16 at 08 35 59" src="https://user-images.githubusercontent.com/1945725/72503132-492af780-383b-11ea-9cb7-c84241fbbc67.png">

**Comment by engcom-Hotel** [comment] 2020-01-16 12:07
Hello @torhoehn 
I am not able to reproduce this issue on the latest Magento 2.4-develop.

**Testing scenario:**
1. Configure Elasticsearch (https://devdocs.magento.com/guides/v2.3/config-guide/elasticsearch/es-overview.html)
2. Add "color" attribute to default attribute set
3. Edit "color" attribute and color value, e.g. "red"
4. Make sure that color attribute is searchable
5. Create simple product with color "red"
![image](https://user-images.githubusercontent.com/51681618/72523802-43e4a180-3869-11ea-9732-dd6413922cb2.png)
6. Clear cache
7. Reindex catalog
8. Open frontend and search for "red"

**Result:**
As expected:
![image](https://user-images.githubusercontent.com/51681618/72523785-362f1c00-3869-11ea-9f2e-1b976a4ab34f.png)

So i have to close this issue as not reproducible on the Magento 2.4-develop.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

Thanks for your report!

**Closed as completed by engcom-Hotel** 2020-01-16 12:07 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by torhoehn** [comment] 2020-01-19 20:26
@engcom-Hotel  You're right, on 2.4-develop I can't reproduce it anymore. Could you please give me a hint what has changed that it's working again?

**Comment by engcom-Hotel** [comment] 2020-01-20 09:58
Hi @torhoehn
All I could find was https://github.com/magento/magento2/pull/18368#issuecomment-441576897, which means this problem has been fixed by the magento core team. 
I hope this helps :)

**Comment by torhoehn** [comment] 2020-01-20 10:00
@engcom-Echo Just found out that this commit fixes the problem: https://github.com/magento/magento2/commit/4844c67145e87ae77dc30b09907fa3dfbf181fd5
Thank you for your help!
