### ISSUE TITLE
Magento Upgrade from 2.3.x to Magento 2.4.3-p1 admin page JS issue- page builder pages not working (like product page, Category page, CMS pages)

### ISSUE THREAD

**Issue by gkmbala** [magento/magento2#35286] opened 2022-04-11 13:05 UTC
### Preconditions (*)

1. Magento 2.4.3-p1
2. Production environment only

### Steps to reproduce (*)

1. Once upgraded the M-2.3.x to M.2.4.3-p1 =>Admin -> Catalog -> products -> (any product) Edit-> Issue occurred (issue can't edit anything in product edit page)
2. Admin products edit page loader is not stopping. (Only production environment.)

### Expected result (*)

1. without error in admin product edit page, category page, and CMS pages (edit)

### Actual result (*)

1. Undefined padding error in the browser console, so we can't edit the admin product edit page and same as category pages and CMS pages.
2. vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js
line : "`if (typeof value === 'object' && **!!**(value.padding || value.margin)) {`"

### Error (*)
We can see the error in the browser console. (Uncaught TypeError: **!!**(value.padding || value.margin)) )
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during the Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-27 12:45
Hi @gkmbala,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.3.7 to 2.4.3-p1 in Production mode but could not able to reproduce the issue.
Steps performed:
Installed Magento 2.3.7 using composer create project
Changed the mode to production from Cli
Created few products from Admin
Upgraded to Magento 2.4.3-P1
Login to admin - Edit product - Save - No issue/errors
Content - Pages - Edit Existing page - edit with page builder - no issue. Saved successfully
Create New Product - No issue. Saved with no errors.
Kindly recheck the issue and provide missing steps / configuration details to reproduce the issue. Also, kindly check if any third party modules /extensions is causing this issue and [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) that are recommended for specific magento versions. 
Thank you.

**Comment by engcom-November** [comment] 2022-05-16 05:24
Hi @gkmbala ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-16 05:24 UTC
Labels: Issue: needs update

**Comment by writyou** [comment] 2022-09-22 14:23
magento2.4.5 erro

  if (typeof value === 'object' && !!(value.padding || value.margin)) {
                    allFilled = true;
                    _.flatten(_.map(value, _.values)).forEach(function(val) {
                        if (utils.isEmpty(val)) {
                            allFilled = false;
                            return allFilled;
                        }
                    });
                    return allFilled;
                }

**Comment by mnowakCode** [comment] 2022-09-27 12:01
I have the same issue. After updating Magento from version 2.3.7-p1 to 2.4.4 we can't edit products, categories and cms pages.
![image](https://user-images.githubusercontent.com/78545108/192519679-94fe3992-ecee-4aad-9db9-366d0ad0cba2.png)
![image](https://user-images.githubusercontent.com/78545108/192519724-3b8508b6-72ab-4caf-ac15-a8b1829529c3.png)

**Comment by scottbolasevich** [comment] 2022-10-26 20:39
same any fix?

**Comment by fortegente** [comment] 2023-06-19 16:58
Same here. Magento 2.4.6. Only disabling merge js and js bundling helped. But obviously it's not a good solution.
