### ISSUE TITLE
Wrong layout in downloadable and bundle product 

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#38149] opened 2023-11-06 10:00 UTC
### Preconditions and environment

- Magento version 2.4-develop
- Install sample data

### Steps to reproduce

1. Go to downloadable product 
2. Go to bundle product

### Expected result

Display same another product type (simple, configuable,...)
![image](https://github.com/magento/magento2/assets/78783748/3634851a-e72b-4318-a463-a046520496d5)

### Actual result

![image](https://github.com/magento/magento2/assets/78783748/f11b4a28-79af-4537-9d0d-c7f07edcf8d4)
![image](https://github.com/magento/magento2/assets/78783748/deb7e0a1-cb77-4611-9736-9afe69a17fc2)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-11-07 11:36
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-11-09 06:02
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-11-09 16:44
Hi @rogerdz 
Thanks for reporting and collaboration.
Verified the issue on magneto 2.4 instance and the issue has been confirmed.
We are seeing the wrong layout for downloadable and bundle products.
Please refer the screenshots.
<img width="1440" alt="product_layout" src="https://github.com/magento/magento2/assets/60198592/64ef7e21-fed8-469b-9b4f-cb6cb686c33a">

**Comment by engcom-Bravo** [comment] 2024-11-29 07:24
Hi @rogerdz,

Thanks for your Contribution!!.

Similar issue been confirmed here https://github.com/magento/magento2/issues/39403. since the PR is attached and ready to that issue we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-29 07:24 UTC
Labels: Issue: Confirmed, Component: Ui, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.x, Area: UI Framework
