### ISSUE TITLE
Size swatches for sold out sizes missing in frontend

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#30046] opened 2020-09-14 22:14 UTC
### Preconditions (*)

1. 2.3.5-p2 (but also previously reported on 2.4)

### Steps to reproduce (*)

1. Create config product with **one** color and several sizes
2. Make one size out of stock
3. Set Admin > Stores > Configuration > Catalog > Inventory > Stock Options > Display Out of Stock Products = Yes
4. Make size and color swatches

### Expected result (*)

1. Out of stock sizes show in frontend as crossed out swatch

### Actual result (*)

1. Out of stock swatches are missing entirely

This behavior is also inconsistent with config products with multiple colors. In that case the sizes render correctly with the option crossed out. In addition I think this should be independent from "Display Out of Stock Products". Either it always should show the crossed out swatches or this should be an independent config option.

This issue has been reported tons of times already but always has been closed incorrectly. Here a few examples:

https://github.com/magento/magento2/issues/26673
https://github.com/magento/magento2/issues/10454
https://github.com/magento/magento2/issues/23196
https://github.com/magento/magento2/issues/23196

Based on the ongoing activity in these tickets and that people keep filing tickets you can see that this still affects multiple users. **This behavior is not only inconsistent with multi color config products but also with any other e-commerce platform out there.**  This is not only a visual problem but it actually prevents me from building additional functionality that depends on these options to be visible in the front end.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lenaorobei** [comment] 2020-09-15 20:50
@magento I'm working on this

**Comment by lenaorobei** [comment] 2020-09-15 21:05
@magento add to contributors team

**Comment by joshdavenport** [comment] 2020-11-16 22:41
Really didn't want to leave a +1 type response here, but given the lack of attention this seems to have received over the last year or two I feel obliged to say that this is a real point of pain not just for us but apparently plenty of others too. We'd all highly value a fix for this.

Especially given in a recent upgrade from 2.2 to 2.3/2.4 previous workarounds we had in place are no longer working, it seems there are issues with community provided solutions too now.

**Comment by engcom-Alfa** [comment] 2020-11-19 11:53
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2020-11-19 12:28
Hi @MichaelThessel .

Unfortunately, we can't reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Manual testing scenario:**

1. Create config product with one color and several sizes
2. Make one size out of stock
3. Set Admin > Stores > Configuration > Catalog > Inventory > Stock Options > Display Out of Stock Products = Yes
4. Make size and color swatches

**Actual Result:** :heavy_check_mark: Out of stock sizes show in frontend as crossed out swatch

![2020-11-19_14-21](https://user-images.githubusercontent.com/51679138/99666196-532d1080-2a73-11eb-9168-370863a20277.png)
![2020-11-19_14-21_1](https://user-images.githubusercontent.com/51679138/99666207-558f6a80-2a73-11eb-885c-bff50f91c4e3.png)

@MichaelThessel Are you able to reproduce this issue on a fresh 2.4-develop instance?
Thanks!

**Comment by nordcomputer** [comment] 2020-11-19 12:43
I dont know, if its the same issue, but all the swatches will be removed (instead of greyed out), if you set all sizes qty to 0
You can test it in the development instance.

**Comment by nordcomputer** [comment] 2020-11-19 12:52
@magento give me 2.4-develop instance

**Comment by nordcomputer** [comment] 2020-11-19 13:07
So, i tested in the develop-instance. Created the product(s), set the Quantity to 0 for all sizes, set the option, to show out-of-stock products to yes and got this in frontend:
![grafik](https://user-images.githubusercontent.com/13378398/99670246-86ba6b80-2a70-11eb-8535-44f38cf5dbc8.png)

As you can see, the price and the "Add to cart" are missing, too

**Comment by MichaelThessel** [comment] 2020-11-19 17:10
Any chance you can link the commit that fixed that here? That way we can backport it into our current installs and don't have to wait for months till this makes it into a release? Thanks!

**Comment by nordcomputer** [comment] 2020-11-19 17:40
There is a fix for that? oO I am waiting since 2.2 for this issue being fixed....

**Comment by joshdavenport** [comment] 2020-11-19 20:34
@engcom-Alfa I believe in OPs original issue report, they must be referring to a configurable not actually configured by 2 two attributes - only one. Is that right @MichaelThessel? Doesn't matter if in the example of 2/3/4/whatever of the simple products happen to have the same color attribute value.

Here is behaviour I have seen in 2.2, 2.3 and 2.4:

* If product is configured by 1 attribute (e.g colour), 2 colours configured, and both are in stock: 
**Two swatches show.** 
**Good behaviour** ✅ 
* If product is configured by 1 attribute (e.g colour), 2 colours configured, and one is out stock: 
**Only one swatch shows, the other is not rendered at all.** 
**Bad behaviour** ❌ 
* If product is configured by 2 attributes (e.g. colour and size), one of the configurations is out of stock:
**The relevant swatch is rendered, and is crossed out.** 
**Good behaviour** ✅

**Comment by joshdavenport** [comment] 2020-11-19 20:35
@magento give me 2.4-develop instance

**Comment by joshdavenport** [comment] 2020-11-19 20:56
Yup, still happening. @engcom-Alfa please see better reproduction steps and proof, this is from the Magento instance above:

![image](https://user-images.githubusercontent.com/757828/99723032-85596500-2aa9-11eb-8308-4109c9f2fe5b.png)

**Comment by nordcomputer** [comment] 2020-11-19 22:06
That seems correct to me.

In addition: I still think, that this behavior directly leads to the problem I described. I didnt actually look into the code, but it seems like magento doesnt fetch the informations of out-of-stock child-products, so it doesnt get the informations for rendering those swatches - if EVERY child-product is out of stock, all informations are missing, so even the price doesnt get rendered.

**Comment by joshdavenport** [comment] 2020-11-19 22:57
Indeed. Basically hiding/showing of swatches based on the show/hide out of stock products config option is only half implemented. It should be obeyed fully in all scenarios or not at all.

**Comment by joshdavenport** [comment] 2020-12-10 19:20
Just to further corroborate this, I also followed my original steps from November in that instance and found that the swatches are indeed correctly showing now:

![image](https://user-images.githubusercontent.com/757828/101819100-b3681d00-3b1c-11eb-96f8-e1ef7fbfc2bf.png)

**Comment by robbie-thompson** [comment] 2020-12-11 16:29
@nordcomputer @joshdavenport +1 this behaviour is incredibly annoying and has gone on for too long for what is now a standard feature. I've created a separate issue [here](https://github.com/magento/magento2/issues/31268) which I believe better addresses this scenario, as OP's refers to something different.

**Comment by nordcomputer** [comment] 2021-02-25 17:14
I think, this behavior is still a thing...(magento 2.4.2) - so, I guess the stale-bot is wrong....

**Comment by df2k2** [comment] 2021-03-07 11:44
I commented in a related issue, but I post here as well.   I feel as though this is related to functionality using:

https://github.com/magento/magento2/blob/c36492997ce9aa7949ef59b201da1be2ebe537bc/app/code/Magento/Swatches/Model/SwatchAttributeCodes.php#L70

I wrote some code that used this method and then had to change it because when no options are available, the attribute is not recognized as a swatch attribute, so logic with comparisons will not work.

**Comment by MichaelThessel** [comment] 2021-03-18 18:05
Commenting to create activity.

**Comment by danyvega1990** [comment] 2021-03-24 18:10
I hope magento actually shows some interest on fixing this, they can say it's not a bug if they want, but just not giving a configuration than others e-commerce plattforms provides feels wrong plain and simple

**Comment by robbie-thompson** [comment] 2021-06-11 10:51
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 14 days if no further activity occurs. Is this issue still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? Thank you for your contributions!

Still relevant

**Comment by gino2014** [comment] 2021-06-23 05:44
Still relevant ...

**Comment by drdreamm** [comment] 2021-06-29 15:39
fix this please

**Comment by engcom-Delta** [comment] 2021-09-30 11:12
Hi @MichaelThessel ,

Issue is not reproducible on Magento 2.4 Develop. Hence closed.

**Closed as completed by engcom-Delta** 2021-09-30 11:12 UTC
Labels: Issue: needs update, Reported on 2.3.5-p2

**Comment by nordcomputer** [comment] 2021-09-30 11:24
@magento give me 2.4-develop instance

**Comment by nordcomputer** [comment] 2021-09-30 11:42
@magento give me 2.4-develop instance without extensions magento/module-two-factor-auth

**Comment by nordcomputer** [comment] 2021-09-30 11:43
@magento give me 2.4-develop without extensions magento/module-two-factor-auth instance

**Comment by nordcomputer** [comment] 2021-09-30 12:04
@engcom-Delta - are you sure, that it is not reproducible? 
It could be a bit tricky to reproduce....
I wanted to try myself, but I am not able to login to the develop instance because of 2-Factor -.-

**Comment by pagesailor** [comment] 2022-05-17 22:28
Still not working.
