### ISSUE TITLE
Multi store product not assigned correctly via REST API

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#4912] opened 2016-06-07 07:04 UTC
## Steps to reproduce
1. for adding the product: [POST] http://127.0.0.1/magento2/index.php/rest/V1/products.
2. for assigning the product with store id: [PUT] http://127.0.0.1/magento2/index.php/rest/store2/V1/products/ZZZ(product sku - ZZZ).
## Expected result
1. The product "ZZZ" should be assigned in main store and "store2" .
## Actual result
1. The product "ZZZ" will be assigned only in "store2".
2. It overwrites existing stores.

**Comment by mslabko** [comment] 2016-06-07 10:56
Hello @sasilinux ,

I cannot reproduce issue for develop branch - all works as expected.

Could you please provide more information - what version of Magento 2 you are using?
"main store" and "store2" is assigned to one website or different?

**Comment by sasilinux** [comment] 2016-06-07 11:51
main store and store2 is assigned to different website.

**Comment by sasilinux** [comment] 2016-06-07 12:12
When i search for How can i set a name or custom attribute for a specific storeview through REST API?
I get the answer from the post. They mentioned that PUT on www.mystorehost.com/rest/default_en/V1/products{sku}. so i did the same in Magento2. but the mainstore view overrides with the current store view.

**Comment by mslabko** [comment] 2016-06-07 12:28
Could you please check on develop branch? I've just checked case with 2 websites and it works as expected: if i do PUT http://127.0.0.1/magento2/index.php/rest/store2/V1/products/ZZZ with different name, then this name is stored only for store2, not for default.

**Comment by sasilinux** [comment] 2016-06-07 12:37
values changed correctly. But the Website id will overrides the existing. please check the db table catalog_product_website.

**Comment by mslabko** [comment] 2016-06-07 12:41
Which version of Magento you are using? For develop branch (or 2.1-rc) websites are assigned correctly. In your case after POST /rest/store_from_website_1/V1/products and PUT /rest/store_from_website_2/V1/products/{sku} product must be assigned to both websites (1, 2)

**Comment by sasilinux** [comment] 2016-06-07 12:49
i am using Magento 2.0.1

**Comment by oserediuk** [comment] 2016-06-07 14:41
Hello,@sasilinux! I have tried  to reproduce this issue, but it haven't been reproduced. 
My branch  is on the commit b366da3aee0155ffabb4772ea63f76e6e13f877e. Is you branch on the same commit? Please, clarify steps to reproduce

**Comment by sasilinux** [comment] 2016-06-08 04:58
Hi can u please tell me when 2.1.x will be released.

**Comment by sasilinux** [comment] 2016-06-08 04:59
currently we are working and customizing in magento 2.0.1. Also we have purchased some paid extensions and working on the same. so can u please guide me is it safe.?

**Comment by oserediuk** [comment] 2016-06-08 08:17
For find out release date, please, follow marketing updates.
GitHub issue tracker is intended for technical issues only, not questions and technical assistance. Please, refer to the Community Forums or Magento Stack Exchange site for technical questions. In your case, the programming questions forum is likely the most appropriate. https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2

**Closed as completed** 2016-06-08 10:09 UTC
