### ISSUE TITLE
Luma Theme - iPhone 7 - Cart Position

### ISSUE THREAD

**Issue by HRR1337** [magento/magento2#10418] opened 2017-08-03 09:46 UTC
### Preconditions

1.  Magento 2.1.7 with sample data / Default Theme
2.  Php 7.0 

### Steps to reproduce

1. Add product to cart
2. Click on Cart Icon

### Expected result

1. The cart icon + search stays on 1 row in theme

### Actual result

1. The cart icon + search goes on new row.

![luma-theme-cart](https://user-images.githubusercontent.com/4428675/28916088-568349ee-7841-11e7-8b29-6e87a5908363.jpg)

**Comment by slackerzz** [comment] 2017-08-03 12:28
take a look at https://github.com/magento/magento2/issues/8178

**Comment by misha-kotov** [comment] 2017-08-03 19:53
Closing this one as duplicate of #8178

**Closed as completed by misha-kotov** 2017-08-03 19:53 UTC

**Comment by HRR1337** [comment] 2017-08-04 05:45
Though its not really a duplicate. Luma is the theme that is default installed and activated. Its the business card of a Magento installation.

**Comment by misha-kotov** [comment] 2017-08-04 18:46
I added details for the Luma theme in the ticket, thank you.
