### ISSUE TITLE
Action drop-down in grid partly hidden (but scrollable)

### ISSUE THREAD

**Issue by pmzandbergen** [magento/magento2#35955] opened 2022-08-16 14:10 UTC
### Preconditions and environment

Magento `>= 2.4.4`

### Steps to reproduce

1. Create a customer
2. Add an address
3. Activate the action drop-down in the address grid, its partly hidden (but scrollable)

[Schermafbeelding 2022-08-16 om 16 05 33](https://user-images.githubusercontent.com/8101295/184899863-d191bdfc-fcc3-479e-9e1b-0aebfbcb6312.png)

### Expected result

It should be easy to use the action drop-down, e.g. without extra scrolling

### Actual result

You need to scroll to use the action drop-down

### Additional information

This is caused by the following PR:
https://github.com/magento/magento2/pull/31413

Specifically `position: relative;` on `.data-grid-actions-cell`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-17 08:06
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-08-17 12:13
Hi @pmzandbergen,

Thank you for reporting and collaboration. 

Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue. please refer the screenshot.

<img width="937" alt="Action" src="https://user-images.githubusercontent.com/51680745/185115404-0266d423-1ca0-4a52-8cd1-e06d3712da4b.png">



Let us know if we missing anything.

Thanks.

**Comment by pmzandbergen** [comment] 2022-08-17 12:15
@magento give me 2.4-develop instance

**Comment by pmzandbergen** [comment] 2022-08-17 12:18
Hi @engcom-Bravo 

Probably depends on the browser, I'll test it on a vanilla instance and report back.

**Comment by pmzandbergen** [comment] 2022-08-17 12:59
@magento give me 2.4.4 instance

**Comment by pmzandbergen** [comment] 2022-08-17 13:13
@magento give me 2.4.4 instance

**Comment by pmzandbergen** [comment] 2022-08-18 06:42
@magento give me 2.4.4 instance

**Comment by engcom-Bravo** [comment] 2022-09-01 06:28
Hi @pmzandbergen,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.


Thanks.

**Closed as completed by engcom-Bravo** 2022-09-01 06:28 UTC
Labels: Issue: needs update

**Comment by Nuranto** [comment] 2022-10-24 12:33
Still having this issue on 2.4.5.

**Comment by mrtuvn** [comment] 2023-02-10 07:41
Hi @Nuranto and @pmzandbergen
Instead remove overflow-x property in this line
https://github.com/magento/magento2/blob/2.4-develop/app/design/adminhtml/Magento/backend/web/css/source/forms/fields/_control-table.less#L28

Please let me know your results with above changes
I could create patch for this case
