### ISSUE TITLE
Edit configurations can't save products

### ISSUE THREAD

**Issue by duyetbv** [magento/magento2#22928] opened 2019-05-17 08:57 UTC
Edit configurations can't save products.

### Preconditions (*)
1. Magento 2.2
2. Magento 2.3

### Steps to reproduce (*)
all step to show issue above
step 1: click to Edit configurations button 
https://prnt.sc/npq139
step 2: Select new option for attribute
https://prnt.sc/npq1tk
step 3: Apply images for all
https://prnt.sc/npq2p0
Step 4: Generate products 
Step 5: Save it

After save shown error
https://prnt.sc/npq3fx

Also review below video: 
https://irinaschrotter.com/edit-config-error.wmv

### Expected result (*)
Product should be updated successfully.

### Actual result (*)
![error](https://user-images.githubusercontent.com/22341271/57916121-68444480-78bc-11e9-8b43-90f10ee4dc60.png)

I was checked all site magento 2
all site same error

please help me
Thanks

### Additional Information (*)
While edit configuration please add another product and upload image for that and generate the product and save this configurable product.

**Comment by duyetbv** [comment] 2019-05-17 09:11
Hi @krishprakash 
Nice to meet you
can you support for me?

**Comment by krishprakash** [comment] 2019-05-17 09:20
Hi @duyetbv.
I'm not able to reproduce this issue as per provided screenshots.
Please update the description with additional steps to reproduce this issue.
Also, Please follow issue reporting guideline to report an issue as explained with below link.
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
After that we can review in clean magento instance if issue is reproduced.
Thanks.

**Comment by duyetbv** [comment] 2019-05-17 09:26
HI There
video error: https://irinaschrotter.com/edit-config-error.wmv
I am using 2.3.1 version
But I was tried with 2.2.4 and other version same issue
I think it's core issue
Thanks

**Comment by magento-engcom-team** [comment] 2019-05-17 10:08
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99732`, `MAGETWO-99733` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by duyetbv** [comment] 2019-05-17 10:13
@magento-engcom-team 
I don't understand
you are fixing it? that right?

**Comment by duyetbv** [comment] 2019-05-17 10:18
@krishprakash 
let me know when resolved
Thnk so much

**Comment by krishprakash** [comment] 2019-05-17 10:21
Hi @duyetbv.
You will get notification once it's fixed.
Thanks.

**Comment by duyetbv** [comment] 2019-05-20 04:21
please give me your plan to fixed this issue
Thanks.

**Comment by tnsezer** [comment] 2019-05-20 09:51
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-20 09:51
Hi @tnsezer. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-20 09:52
Hi @tnsezer, here is your [Magento instance](https://i-22928-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22928-2-3-develop.instances.magento-community.engineering/admin](https://i-22928-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by duyetbv** [comment] 2019-05-21 07:51
ok @magento-engcom-team 
let me know once fixed
Thanks

**Comment by tnsezer** [comment] 2019-05-21 07:57
working on it

**Comment by tnsezer** [comment] 2019-05-21 10:53
I created pull request but it created new issue, someone needs to merge that issue with this issue
https://github.com/magento/magento2/pull/22959

**Comment by magento-engcom-team** [comment] 2019-09-04 20:30
Hi @duyetbv. Thank you for your report. 
The issue has been fixed in magento/magento2#23021 by @tnsezer in 2.3-develop branch
Related commit(s):
 - [869bd7e0b863896add20dca29f729acdebd415ba](https://github.com/magento/magento2/commit/869bd7e0b863896add20dca29f729acdebd415ba)
 - [daa96f487090fce5bc077564edb33d97fc35fd63](https://github.com/magento/magento2/commit/daa96f487090fce5bc077564edb33d97fc35fd63)
 - [61fa2cc2d46df71241fdfd1461c2e85da8548c7c](https://github.com/magento/magento2/commit/61fa2cc2d46df71241fdfd1461c2e85da8548c7c)
 - [9e4e46e3491182a930458134d486555c1f7e7096](https://github.com/magento/magento2/commit/9e4e46e3491182a930458134d486555c1f7e7096)
 - [f82e5a5855fd9ff6f67fd206507250e7d9ef1463](https://github.com/magento/magento2/commit/f82e5a5855fd9ff6f67fd206507250e7d9ef1463)
 - [3a45e91c243820f92bab26ca645ff647e7d4c68b](https://github.com/magento/magento2/commit/3a45e91c243820f92bab26ca645ff647e7d4c68b)
 - [cd9894a69efbb4c6e12e887f100a46953c5e574f](https://github.com/magento/magento2/commit/cd9894a69efbb4c6e12e887f100a46953c5e574f)
 - [86df1094d37edf114b3142fc688458b99d592a7b](https://github.com/magento/magento2/commit/86df1094d37edf114b3142fc688458b99d592a7b)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-09-04 20:30 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: ConfigurableProduct, Component: Admin
