### ISSUE TITLE
Magento ver. 2.4.6-p2 Braintree Payments module with PayPal through Braintree vault enabled showing Stored Accounts (PayPal) payment method when no accounts are saved

### ISSUE THREAD

**Issue by atIOCrON** [magento/magento2#38010] opened 2023-09-26 08:34 UTC
### Preconditions and environment

Magento ver. 2.4.6-p2

### Steps to reproduce

1. Stores > Configuration > Sales: Payment Methods
2. Set up Braintree
3. Enable PayPal through Braintree
4. Choose Vault Enabled = Yes
5. Sales > Orders > Create New Order
6. Choose an existing customer who does NOT have any saved PayPal vault information
7. Choose products and addresses
8. Get the payment methods

### Expected result

"Stored Accounts (PayPal)" is NOT shown as a payment method because there is nothing stored in the vault.

### Actual result

"Stored Accounts (PayPal)" is shown even though this payment method is not available.

### Additional information

If you try to place the order using "Stored Accounts (PayPal)" as the payment method you will get the following error because there is no PayPal payment method saved in the vault:

Order saving error: Public hash should be defined

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-28 06:11
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-28 11:40
Hi @atIOCrON,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.7-beta1 instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Stores > Configuration > Sales: Payment Methods
- Set up Braintree
- Enable PayPal through Braintree
- Choose Vault Enabled = Yes
- Sales > Orders > Create New Order
- Choose an existing customer who does NOT have any saved PayPal vault information
- Choose products and addresses
- Get the payment methods


<img width="1075" alt="Screenshot 2023-09-28 at 12 08 26 PM" src="https://github.com/magento/magento2/assets/51680745/a543ca79-0af7-4af4-a2b9-69add4f6c78c">



<img width="1175" alt="Screenshot 2023-09-28 at 12 09 37 PM" src="https://github.com/magento/magento2/assets/51680745/76b19022-ac27-403d-8a10-16032a8e1699">



<img width="1396" alt="Screenshot 2023-09-28 at 12 11 26 PM" src="https://github.com/magento/magento2/assets/51680745/2a24e4bd-ec8b-4c52-bb58-185c4601e83f">


"Stored Accounts (PayPal)" is NOT shown as a payment method.So  I request you to please try to reproduce the issue in the latest Version it might be possible the issue is resolved.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-10 05:53
Hi @atIOCrON,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-10 05:53 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
