### ISSUE TITLE
Error adding more than one product to es_CO

### ISSUE THREAD

**Issue by carloshernan007** [magento/magento2#8885] opened 2017-03-14 21:34 UTC
### Preconditions

1. Magento 2.1.5
2. PHP 5.6

### Steps to reproduce

1.  Set up the store in location Colombia (es_CO)
2.  Deploys static view files for es_CO (php ./bin/magento setup:static-content:deploy es_CO)
3.  Flush cache php ./bin/magento cache:flush
4. Go the frontend of the store in the product view add more 2 quantities.
5.  Only added one product this is the problem.

### Expected result

1. Add the quantity of products entered

### Actual result

1. Video: https://youtu.be/ywhy1H2e5mk

I check the checkout module in the controller cart and the class Add the problem is the filter.
`$params['qty'] = $filter->filter($params['qty']);`
because in the line the controller validate the format number for param qty  this return a date format.

In this filter method exist a series the validations of number format with regular expression this is the  rules list for number the result is false in all cases.
array {
  [0]=> "/^$/u"
  [1]=> "/^$/u"
  [2]=> "/^[++]{0,1}[0-9]{1,}(\,[0-9]{1,})*[eE][++]{0,1}[0-9]{1,}$/u"
  [3]=> "/^[\--]{0,1}[0-9]{1,}(\,[0-9]{1,})*[eE][\--]{0,1}[0-9]{1,}$/u"
}
I don't know where your save this rules.

Thanks for your help.

**Comment by veloraven** [comment] 2017-07-06 15:15
@carloshernan007 thank you for your report but I'm closing it as a duplicate of #6656

**Closed as completed by veloraven** 2017-07-06 15:15 UTC
