### ISSUE TITLE
Multiple category move/drag and drop doesn't work ~ unless page is refreshed in between

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5010] opened 2016-06-14 01:10 UTC
Mage 2.0.7

Create 3 categories
Drag category B into category A on the Category admin (folder tree on the left)
Once it completes, now drag category C into category A... it will complete, say it's save, look correct in the tree... but upon refreshing the page or navigating elsewhere in the folder tree the last (apparent) change will revert...

you cannot move 2 categories in sequence unless you re-save (refresh?) the category admin in-between

**Comment by ghost** [comment] 2016-06-14 10:14
This is also an issue for my install. Version 2.0.7

**Comment by tkacheva** [comment] 2016-08-19 10:58
@blizam @MattHans0n 
Category tree reloads after each category rearrangement and display categories the way they've been rearranged. Is this  still a reproducible issue on your side?
If so please provide the details of Magneto configuration and screenshots

**Comment by blizam** [comment] 2016-08-19 19:51
I can't immediately test this... I've rearranged cats a bit in 2.1.0 and didn't have any issues... I can test in a week or so when I move this site into prod and setup a separate test site/environment

**Comment by tkacheva** [comment] 2016-08-31 11:14
@blizam I'm closing the ticket due to lack of information from your side. Once you test and have issues to report, please feel free to reopen it.

**Closed as completed by tkacheva** 2016-08-31 11:14 UTC
Labels: Progress: needs update, Component: Catalog
