### ISSUE TITLE
Widget Layout Update section is not available

### ISSUE THREAD

**Issue by tranngan97** [magento/magento2#39129] opened 2024-08-30 11:06 UTC
### Preconditions and environment

Magento 2.4.7p-2

### Steps to reproduce

1. Go to Content -> Widget
2. Add layout update section to set on specific pages
3. Save and open the widget again

### Expected result

1. Layout Update section is available
2. Not see js error

### Actual result

Some time layout update is not available and show alot of js error
![image](https://github.com/user-attachments/assets/a7557f4e-cef0-4517-972e-1781f322ce97)
Error is gone after I refresh browser, but sometime it happen again

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-02 05:46
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-02 09:32
Hi @tranngan97,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.kindly refer the attached video.

**Steps to reproduce**

- Go to Content -> Widget
- Add layout update section to set on specific pages
- Save and open the widget again


There is no Js error and Layout Update section is available



https://github.com/user-attachments/assets/f5ea0de3-3dd6-4602-b766-247a7f6bdd19



Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-16 05:58
Hi @tranngan97,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-16 05:58 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
