### ISSUE TITLE
Product category url rewrite missing storeview specific url_key

### ISSUE THREAD

**Issue by juhanihaapala** [magento/magento2#26393] opened 2020-01-15 07:39 UTC
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Create 2 Store Views
2. Create category Category 1 
3. Create Category 2 under Category 1
4. Create store view specific url key for Category 1 for example `category-1-1`
5. Create new product add it to Category 2

### Expected result (*)

1. Generated url path for created product with category in store view to have the store view specific url_key for category 1 for example `category-1-1/category-2/product`

### Actual result (*)

1. Generated url path is generated with default category url_key for product `category-1/category-2/product`

Reason is here https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogUrlRewrite/Service/V1/StoreViewService.php#L83
this checks only the "current" category not hierarchial.

**Comment by magento-engcom-team** [comment] 2020-01-16 09:42
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30473` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by GovindaSharma** [comment] 2020-02-02 04:31
#MM20IN

**Comment by hostep** [comment] 2020-02-09 13:06
I'm closing this as a duplicate of https://github.com/magento/magento2/issues/11615
Fix is being worked on in https://github.com/magento/magento2/pull/26784

Thanks for the report!

**Closed as completed by hostep** 2020-02-09 13:06 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: UrlRewrite, Reproduced on 2.4.x, Fixed in 2.4.x, Event: mm20in, Reported on 2.4.0

**Comment by slavvka** [comment] 2020-03-17 05:17
Hi @juhanihaapala. Thank you for your report. 
The issue has been fixed in magento/magento2#26784 by @hostep in 2.4-develop branch
Related commit(s):
 - [cb685d15b2b590bdb4d99a3d4ebe563037d0aa31](https://github.com/magento/magento2/commit/cb685d15b2b590bdb4d99a3d4ebe563037d0aa31)
 - [acb8642c44d1ecb60ad023c81f6541fa9ebae47d](https://github.com/magento/magento2/commit/acb8642c44d1ecb60ad023c81f6541fa9ebae47d)
 - [97258e1a9ce97ad32971731eceac8fee32f66b74](https://github.com/magento/magento2/commit/97258e1a9ce97ad32971731eceac8fee32f66b74)
 - [6cf26dc19e2f80f0c2da445443d0b48a1974fc77](https://github.com/magento/magento2/commit/6cf26dc19e2f80f0c2da445443d0b48a1974fc77)
 - [0b941218dcc86dcbd518f5400934e995ad1f2e3c](https://github.com/magento/magento2/commit/0b941218dcc86dcbd518f5400934e995ad1f2e3c)
 - [b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908](https://github.com/magento/magento2/commit/b0c0c59900b4ddf8d70cf2ae9c9ec12805d13908)
 - [28fa34531f4c7cd4bcad46500ba027b9b58ff297](https://github.com/magento/magento2/commit/28fa34531f4c7cd4bcad46500ba027b9b58ff297)
 - [bf514b0b435a75f5688f56f8e9465af9bb3284c1](https://github.com/magento/magento2/commit/bf514b0b435a75f5688f56f8e9465af9bb3284c1)

The fix will be available with the upcoming 2.4.0 release.
