### ISSUE TITLE
Empty bin/ folder after composer update

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#4790] opened 2016-05-31 09:16 UTC
Literally the title. I used php composer.phar update in order to update to 2.0.6 (is it the latest? Idk) 

After the update, my bin/ folder was completly empty. Copying the content of the magento file of github and mirroring it to my server does not resolve this problem, it does not work anymore. 

> atroposstage@s316 [~/public_html]# php composer.phar update
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Nothing to install or update
> Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
> Generating autoload files
> atroposstage@s316 [~/public_html]# nano bin/magento
> atroposstage@s316 [~/public_html]# chmod u+x bin/magento
> atroposstage@s316 [~/public_html]# php-cli bin/magento

Latest console I/O

**Comment by mazhalai** [comment] 2016-05-31 13:52
@kingalca please provide what version did you update from?

**Comment by grasdaggel** [comment] 2016-06-01 14:54
We upgraded from 2.0.4. to 2.0.7.

**Comment by mazhalai** [comment] 2016-06-01 15:19
@kingalca can you please post contents of your root composer.json's require section?

Tried the following steps and cannot reproduce
- deploy and install 2.0.4
- composer require magento/product-community-edition 2.0.7 --no-update
- composer update
- bin/magento setup:upgrade

No errors.

**Comment by grasdaggel** [comment] 2016-06-02 08:19
I didn't made the "composer require magento/product-community-edition 2.0.7 --no-update" step. 

Will upload the JSON later!

**Comment by andimov** [comment] 2016-06-27 14:41
@grasdaggel we are closing issue since as non-responsive.
Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-06-27 14:41 UTC
Labels: Progress: needs update
