### ISSUE TITLE
2.1.0-rc1 does not include repo.magento.com

### ISSUE THREAD

**Issue by fooman** [magento/magento2#4673] opened 2016-05-24 14:34 UTC
## Steps to reproduce
1. Install Magento from `2.1.0-rc1` tag
## Expected result
1. `composer.json` includes 

```
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
```
## Actual result
1. `composer.json` without repositories defined

**Comment by mazhalai** [comment] 2016-05-26 14:10
@fooman did you mean the git tagged version? Yes this was removed intentionally so that travis builds would be able to run without additional authentication.

If it is missing from the composer.json from the zip from magento.com or the `composer create-project..` then it is an issue.

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-05-26 14:10 UTC

**Comment by fooman** [comment] 2016-05-26 14:31
@mazhalai yes this is from the git tagged version. In my view all installation methods should create the same working software irrespective of the source. When I download from repo.magento.com the code should be the same as what is on github. If that is not a given this will lead to even more hard to track down support issues.

Can't you just add your credentials in travis once:

![screenshot-travis-ci org 2016-05-26 16-19-24](https://cloud.githubusercontent.com/assets/455508/15577657/b6a54e6a-235d-11e6-9968-998520acd934.png)

and then use
https://github.com/fooman/sameorderinvoicenumber-m2/blob/develop/.travis.yml#L8 ?

**Comment by buskamuza** [comment] 2016-05-26 15:01
@fooman , these credentials will not work for PRs.
Also, git-based version is different in its nature, it already has everything packed instead of being composed by Composer from different packages. So it doesn't need this repository (at least it should not need). But Composer-based installation requires the repository to be included, so it is included there. There are more differences in `composer.json` for different types of deployment, as these are different types of projects.
Do you have a scenario for git-based installation, where you need `repo.magento.com` to be used?

**Comment by piotrekkaminski** [comment] 2016-05-26 20:26
Hey @fooman the git version is really only designed for contributions, not for regular usage. This might change in the future. But for everything else you should really use composer install.

**Comment by fooman** [comment] 2016-05-26 20:45
@piotrekkaminski understood - it's just because this installation method exists people will use it - which means that I, as an extension developer, will encounter merchants using them all. The more differences there are between the installation methods the more work for us. I will sort my thoughts on this and create a new issue for this broader discussion.

On a sidenote so far we have used installation from github for our CI simply because it allows us to have 1 process to test tagged releases and in-development versions. The new RC process might remove the need for the in-development versions.
