### ISSUE TITLE
Wrong dashboard totals with aggregated data 

### ISSUE THREAD

**Issue by gexxx05** [magento/magento2#36875] opened 2023-02-16 12:29 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP 8.1

### Steps to reproduce

1. Create some orders in your shop for testing (you need some older orders in the past few days)
2. Enable dashboard chart and use aggregated data
3. In dashboard select "Order" tab and in dropdown select "Today"
![screen03](https://user-images.githubusercontent.com/16879037/219361054-423eb12f-e042-4d3f-a506-590d4211b29c.jpg)
4. Change dropdown to "Last 24 hours"
![screen04](https://user-images.githubusercontent.com/16879037/219361262-afd42185-7a3f-4454-98e0-112bf090da7e.jpg)

### Expected result

The totals below the chart should be different.

### Actual result

The totals are the same whether i select "Today" or "Last 24 hours". 

### Additional information

The sql select for "Today":
`SELECT
	SUM(main_table.total_revenue_amount) AS revenue,
	SUM(main_table.total_tax_amount_actual) AS tax,
	SUM(main_table.total_shipping_amount_actual) AS shipping,
	SUM(orders_count) AS quantity
FROM sales_order_aggregated_created AS main_table
WHERE (period >= '2023-02-16 00:00:00' AND period <= '2023-02-16 23:59:59')
	AND (main_table.order_status NOT IN('Canceled'))
	AND (store_id = '0')`

And here the result without the SUM:
![screen05](https://user-images.githubusercontent.com/16879037/219363077-3a7bb482-0e15-43f7-8a52-4b00b80cd8a7.jpg)

The sql select for "Last 24 hours":
`SELECT
	SUM(main_table.total_revenue_amount) AS revenue,
	SUM(main_table.total_tax_amount_actual) AS tax,
	SUM(main_table.total_shipping_amount_actual) AS shipping,
	SUM(orders_count) AS quantity
FROM sales_order_aggregated_created AS main_table
WHERE (period >= '2023-02-15 11:58:12' AND period <= '2023-02-16 11:58:12')
	AND (main_table.order_status NOT IN('Canceled'))
	AND (store_id = '0')`

And here the result without the SUM:
![screen06](https://user-images.githubusercontent.com/16879037/219363183-a4ba4629-bc8d-49c1-ae87-28b645769d4c.jpg)

The result stay the same and so the total values. The problem is, that the field "period" in "sales_order_aggregated_created" is a date field and not datetime. The graph is also messed up because of this problem.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by devchris79** [comment] 2023-02-17 09:37
Hi @gexxx05, this is a repeat of my issue #36199 by the looks of it.

**Comment by gexxx05** [comment] 2023-02-17 10:06
Hi @devchris79,
Sorry, I didn't see your issue, although I was looking for related ones.

However, my problem does not only occur on page load and is more related to aggregate data.
The problem is with the options `today` and `24h`, because with aggregate data there is no time reference and so the result is not correct. When i switch to live data the sql selects table `sales_order` and field `created_at` which is a `timestamp` and so the result is correct.

But i can confirm that i have the same behaviour as you described in your issue.
On the first load the today data is not correct, but if i switch to `24h` and then back again, its correct.

Thank you

**Comment by engcom-Bravo** [comment] 2023-02-20 12:08
@devchris79 Thanks for your contribution & collaboration over here.

Hi @gexxx05,

Thanks for your contribution & collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible but There is an ongoing confirmed issue
https://github.com/magento/magento2/issues/36199 for the same. Kindly move on to this issue for latest updates / solutions on the same.

We are closing this as duplicate.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-20 12:08 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.4

**Comment by gexxx05** [comment] 2023-02-20 12:16
Thanks, but this is not the same as https://github.com/magento/magento2/issues/36199.
I have already described it here: https://github.com/magento/magento2/issues/36875#issuecomment-1434415074

**Comment by engcom-Bravo** [comment] 2023-02-20 13:03
@gexxx05 we have updated the main description of ongoing confirmed issue https://github.com/magento/magento2/issues/36199

Thanks.

**Comment by gexxx05** [comment] 2023-02-20 13:21
You're mixing things up here.
The description for this problem is only valid in this specific case if the setting "Use Aggregated Data" is set to "Yes".
The issue https://github.com/magento/magento2/issues/36199 has nothing to do with aggregated data at all and is already fixed with https://github.com/magento/magento2/commit/dd769504d2a56e510b1632e8f1a5f42c9571af52.

So I would not just copy descriptions together even though the errors are different.
But i will leave it for now.
