### ISSUE TITLE
Default store (Root category A) breadcrumbs are being returned for New Store (Root category B) when Product belongs to both root categories.

### ISSUE THREAD

**Issue by devpatil7** [magento/magento2#31253] opened 2020-12-10 19:17 UTC
### Preconditions (*)

1. Magento 2.4.1
2. Two root categories exists in Admin-Categories
3. Two stores exists with different root categories for each of it
4. Each Stores should have atleast one store view.
5. Each Root category should have one sub-category.
5. Product should belong to both stores. i.e. Assign product to all root and sub categories.

### Steps to reproduce (*)

1. Query - 
```
{
  "store": "engchildren"
}
query {
  products(filter: { url_key: { eq: "gabrielle-micro-sleeve-top"} }){
   	items {
      categories {
        name
        id
        url_path
        breadcrumbs {
          category_id
          category_name
          category_level
        }
      }
    } 
  }
}
```

### Expected result (*)

1. Store specific data should be returned.

### Actual result (*)

1. Response - 
```
{
  "data": {
    "products": {
      "items": [
        {
          "categories": [
            {
              "name": "Default Category",
              "id": 2,
              "url_path": null,
              "breadcrumbs": null
            },
            {
              "name": "Women",
              "id": 20,
              "url_path": "women",
              "breadcrumbs": null
            },
            {
              "name": "Tops",
              "id": 21,
              "url_path": "women/tops-women",
              "breadcrumbs": [
                {
                  "category_id": 20,
                  "category_name": "Women",
                  "category_level": 2
                }
              ]
            },
            {
              "name": "Toddlers",
              "id": 51,
              "url_path": "toddlers",
              "breadcrumbs": null
            }
          ]
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pronto2000** [comment] 2021-01-04 14:19
I can confirm the issue description and I can add some additional insights here. I created two stores: default (1) and second (2), running the GraphQL query similar to the one above ran the query below:
```
SELECT `cat_index`.`category_id` FROM `catalog_category_product_index_store1` AS `cat_index`
 INNER JOIN `store` ON store.store_id = 1
 INNER JOIN `store_group` ON store.group_id = store_group.group_id AND cat_index.category_id != store_group.root_category_id WHERE (product_id = 1200)
```
Please note that I created 2 websites, each having it's one store and each store has it's own root category and store_view. For the product (id = 1200) I assigned categories from both websites to it and as a separate option I enabled the first website only. 

The query above correctly assumes assumes that default store it 1 and tries to get the information from index_store1 using store_id 1. The result however is wrong because this table contains information from both stores (category 17 is from website 1 and category 34 is from website 2):
```
+-------------+
| category_id |
+-------------+
|          17 |
|          34 |
+-------------+
```
Inspecting tabel `catalog_category_product_index_store1` reveals that this table contains ALL category / product association and ALL rows have store_id = 1. `catalog_category_product_index_store2` exists as well, but it is empty.

here's a sample from `catalog_category_product_index_store1`
```
+-------------+------------+----------+-----------+----------+------------+
| category_id | product_id | position | is_parent | store_id | visibility |
+-------------+------------+----------+-----------+----------+------------+
|          17 |       1200 |     9999 |         0 |        1 |          4 |
|          34 |       1200 |       -1 |         1 |        1 |          4 |
+-------------+------------+----------+-----------+----------+------------+
```
while
```
 select count(*) from catalog_category_product_index_store2;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
```
It looks like the data stored in those index tables is fundamentally wrong and this is not a problem with GraphQL, but with indexing itself. 

Please note that while it's technically possible to filter out correct rows it's going to be a quick and dirty workaround ignoring the core problem which remains there potentially causing additional problem.

**Comment by sasha19957099** [comment] 2021-01-20 14:57
@magento I'm working on this

**Comment by niklaswolf** [comment] 2021-03-16 08:47
What's the state of this issue? Seems like there is a PR ready to be merged, but nothing happened since January...

**Comment by glo71317** [comment] 2022-05-23 09:27
Based on priority I am working on this issue's PR and fixing the PR comments and automation tests

**Closed as completed** 2022-05-30 19:50 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P1, Project: GraphQL, PAP, Progress: done, Area: APIs

**Comment by engcom-Alfa** [comment] 2022-05-31 08:20
Hello @dpatil-magento 
As I can see this issue got fixed in the scope of the internal Jira ticket `AC-2515` by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2515&type=commits

Based on Jira, target version is 2.4.5
