### ISSUE TITLE
Google Adwords menu items are not accessible when Google Analytics is not installed

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#30481] opened 2020-10-13 11:32 UTC
### Preconditions (*)
1. 2.4.0 deployed via composer

### Steps to reproduce (*)
1. Add the following snippet to composer.json
```
    "replace": {
        "magento/module-google-analytics": "*"
    },
```
2. composer install
3. php bin/magento setup:upgrade
4. php bin/magento cache:clean
5. Go to admin
6. Stores -> Configuration -> Sales

### Expected result (*)
1. I expect to see "Google API" menu item and config for Adwords

### Actual result (*)
1. "Google API" menu item is missing.

### Additional info from Engcom

Also reproducible on 2.4.1composer version
The Google menu is missing from Stores - Configuration - Sales
![google_sales](https://user-images.githubusercontent.com/51680745/96594575-71c4ae00-12f3-11eb-99a2-78234dfd1b22.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2020-10-20 13:44
Reproducible on Magento 2.4.0 composer via the provided steps
The Google menu is missing from Stores - Configuration - Sales
![google_sales](https://user-images.githubusercontent.com/51680745/96594575-71c4ae00-12f3-11eb-99a2-78234dfd1b22.png)

**Comment by magento-engcom-team** [comment] 2020-10-20 13:46
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38569` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gwharton** [comment] 2021-01-26 18:01
Bump

**Closed as not planned** 2024-08-10 08:22 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: GoogleAnalytics, Component: Composer, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.0

**Comment by engcom-Delta** [comment] 2024-08-12 06:38
Hi @gwharton ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to Reproduce**
1. Add snipet in composer.json
![image](https://github.com/user-attachments/assets/143e5bca-b807-40d0-a24c-c06efe58d078)
 2. Composer install
 3. php bin/magento setup:upgrade
4.php bin/magento cache:clean
5.Go to admin
6.Stores -> Configuration -> Sales
![image](https://github.com/user-attachments/assets/e4316241-0051-4994-a316-19cdc3b83e1d)
![image](https://github.com/user-attachments/assets/70bba6bb-a13f-4f02-96a9-1cf93f034237)

Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.
