### ISSUE TITLE
Nginx confm not working properly 

### ISSUE THREAD

**Issue by Sanjay-100** [magento/magento2#35129] opened 2022-02-22 09:44 UTC
after setup LEMP stack install the magneto,

link the magneto   "nginx.conf.sample'  to nginx config files. 
Product detail page not working 

![image](https://user-images.githubusercontent.com/98302784/155105709-83debd9f-d99d-4070-b24e-6e5ad6b99318.png)
home and categorises working.
![image](https://user-images.githubusercontent.com/98302784/155105780-c24fa2d5-0202-448c-80a5-5bad0df61fb1.png)

**Comment by Sanjay-100** [comment] 2022-02-22 09:46
Summary of the issue the nginx server config not working 
Information on your environment  : nginx version: nginx/1.18.0 (Ubuntu)
Steps to reproduce  ; step magento with LEMP stack 
Expected and actual results  : all page working fine with nginx config.

**Comment by engcom-Hotel** [comment] 2022-02-22 10:14
Hello @Sanjay-100,

It is doesn't seem to be a Magento core issue. I request you to please check logs and let us know if you found anything in that.

Thanks

**Comment by Sanjay-100** [comment] 2022-02-23 08:53
@engcom-Hotel   Thanks for replay  i know it was not magento core issue. but it was something issue with nginx config file issue.

**Comment by engcom-Hotel** [comment] 2022-03-04 09:44
Hello @Sanjay-100,

We have tried to reproduce the issue by installing fresh Magento 2.4-develop in the system with Nginx. But the issue is not reproducible for us. 

Please have a look at below screenshot for reference:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681618/156739469-eb4a759a-17eb-4d40-9c38-f344c9e145fe.png">

Thanks

**Comment by engcom-Hotel** [comment] 2022-03-21 08:09
Dear @Sanjay-100,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-03-21 08:09 UTC
Labels: Triage: Dev.Experience, Issue: needs update
