### ISSUE TITLE
Shipping address and billing address swapped

### ISSUE THREAD

**Issue by oe-bayram** [magento/magento2#13962] opened 2018-03-05 23:10 UTC
### Preconditions

1. Magento 2.2.2

### Steps to reproduce

1. Create a customer account
2. Create a billing address
3. Create a shipping address different from billing address

### Expected result

1. After an order billing address should be shown as billing address and shipping address as shipping address

### Actual result

Problem 1: In order details the shipping address is shown as billing address
Problem 2: If I want to get shipping address in Observer by "checkout_onepage_controller_success_action" event then "null" is given and as billing address the shipping address is given

**Comment by magento-engcom-team** [comment] 2018-03-06 11:30
@oe-bayram, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by gridl** [comment] 2018-03-23 10:51
#distributed-cd

**Comment by magento-engcom-team** [comment] 2018-03-23 10:52
@gridl thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by gridl** [comment] 2018-03-23 13:07
it seems like  unconditionally reassignment just after conditional ones:

```php
    /**
     * @param CartInterface $quote
     * @param AddressInterface $address
     * @param string $method
     * @return CartInterface
     */
    private function prepareShippingAssignment(CartInterface $quote, AddressInterface $address, $method)
    {
        $cartExtension = $quote->getExtensionAttributes();
        if ($cartExtension === null) {
            $cartExtension = $this->cartExtensionFactory->create();
        }

        $shippingAssignments = $cartExtension->getShippingAssignments();
        if (empty($shippingAssignments)) {
            $shippingAssignment = $this->shippingAssignmentFactory->create();
        } else {
            $shippingAssignment = $shippingAssignments[0];
        }

        $shipping = $shippingAssignment->getShipping();
        if ($shipping === null) {
            $shipping = $this->shippingFactory->create();
        }

        **$shipping->setAddress($address);
        $shipping->setMethod($method);**
        $shippingAssignment->setShipping($shipping);
        $cartExtension->setShippingAssignments([$shippingAssignment]);
        return $quote->setExtensionAttributes($cartExtension);
    }
}
```

**Comment by gridl** [comment] 2018-03-23 13:33
and in "TotalsInformationManagement"

```php
$this->validateQuote($quote);

        if ($quote->getIsVirtual()) {
            $quote->setBillingAddress($addressInformation->getAddress());
        } else {
            $quote->setShippingAddress($addressInformation->getAddress());
            $quote->getShippingAddress()->setCollectShippingRates(true)->setShippingMethod(
                $addressInformation->getShippingCarrierCode() . '_' . $addressInformation->getShippingMethodCode()
```

so, where are magic constant?
```php
    const SHIPPING_ADDRESS = 'shipping';

    /**
     * BillingAddress block name
     */
    const BILLING_ADDRESS = 'billing';
```

**Comment by barryvdh** [comment] 2018-04-19 08:01
So is this fixed? Or what happened?

**Comment by sheenu3091** [comment] 2018-05-19 08:01
Unable to reproduce the issue in magento 2.2.2

**Comment by tecjam** [comment] 2019-01-22 08:09
I'm seeing this issue on 2.2.3. Any fix for this?

**Comment by KalimuthuLakshmanan** [comment] 2019-05-04 05:21
#event-dmcdindia

**Comment by KalimuthuLakshmanan** [comment] 2019-05-04 05:24
i am working on this #dmdcindia1

**Comment by KalimuthuLakshmanan** [comment] 2019-05-04 05:29
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment] 2019-05-04 05:29
@KalimuthuLakshmanan thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by KalimuthuLakshmanan** [comment] 2019-05-04 06:04
Unable to reproduce the issue in magento 2.3

**Closed as completed by KalimuthuLakshmanan** 2019-05-04 06:04 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Event: dmcdindia1
