### ISSUE TITLE
PayPal Express Checkout IPN failed to change order status to Closed / Canceled after payment refunded from PayPal account

### ISSUE THREAD

**Issue by feelinc** [magento/magento2#10547] opened 2017-08-16 10:13 UTC
### Preconditions
1. v2.1.7 and v2.1.8 with sample data, fresh install.
2. PHP 7.x
3. MySQL Galera Cluster.
4. PayPal payment method is set up.
5. PayPal payment action: Authorization / Sale.
6. No IPN URL defined in PayPal merchant account, or try With IPN URL defined (same result).
7. Assign Order Status to State (optional, still having issue without this condition).

### Steps to reproduce
1. Place an order for any product types.
2. Pay using PayPal Express Checkout.
3. Refund the payment from PayPal merchant account.

### Expected result
1. Order status should be changed to Closed / Canceled
2. Total Refunded should show full amount refunded

### Actual result
1. IPN regarding PayPal refund received.
2. Credit Memo created.
3. Order status become Complete.
4. Total refunded zero.

### Actual result screenshot
![order-history-screenshot](https://user-images.githubusercontent.com/345562/29358541-9c8f8b3c-82a5-11e7-8c12-d854dfa89bb1.jpg)

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@feelinc, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-26 22:00 UTC
Labels: bug report, Component: Payment, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
