### ISSUE TITLE
Url Rewrite not changing

### ISSUE THREAD

**Issue by rugschoice** [magento/magento2#13625] opened 2018-02-13 07:29 UTC
We have change the product url, it changes in backend, but its not changing in front end. We have clear the cache and re index by dos prompt, even then it does not take effect. 

Also the product name is not changing in front end. we are using magento 2.2.0

Plz help in this regard, Thank you

**Comment by koenner01** [comment] 2018-02-13 08:19
@rugschoice, I think you better provide some more (detailed) info and follow the issue template otherwise the people of Magento are just gonna close this issue.

**Comment by magento-engcom-team** [comment] 2018-02-13 12:28
Do you have one website with only one store and only one store view assigned to the website?
Navigate to Stores > Settings > All Stores and tell us what you see there. If there are lot of them then please attach the screenshot or paste it as ASCII-table:
```
+--------------+--------------------+--------------------+
|   Web Site   |       Store        |     Store View     |
+--------------+--------------------+--------------------+
| Main Website | Main Website Store | Default Store View |
+--------------+--------------------+--------------------+
```
[ASCII-table generator](https://ozh.github.io/ascii-tables/)

**Comment by magento-engcom-team** [comment] 2018-02-13 12:30
@rugschoice, please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by magento-engcom-team** [comment] 2018-04-11 10:55
@rugschoice we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2018-04-11 10:55 UTC
Labels: Progress: needs update, Issue: Format is not valid
