### ISSUE TITLE
Url rewrites - Update attributes

### ISSUE THREAD

**Issue by snuffer82** [magento/magento2#35036] opened 2022-01-30 09:42 UTC
### Preconditions (*)

1. Magento CE 2.4.1-p1
2. Multiple website

### Steps to reproduce (*)

1. Create a new product
2. Use "update attributes" (bulk) to add the product on all websites

### Expected result (*)

1. Product is added on all websites
2. Product url rewrites are generated for all websites

### Actual result (*)

1. Product is added on all websites
2. No product url rewrites are generated for the selected websites

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Aquarvin** [comment] 2022-02-01 19:12
The issue is probably high related to this one https://github.com/magento/magento2/issues/34937, but completly the same. This one requires additional fix. The root cause of it is that it misses store ID. 
This is my proposition to solve this issue along with the https://github.com/magento/magento2/issues/34937 :
```diff --git a/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php b/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
--- a/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
+++ b/Observer/ProcessUrlRewriteOnChangeProductVisibilityObserver.php
@@ -43,12 +43,13 @@
         $event = $observer->getEvent();
         $attrData = $event->getAttributesData();
         $productIds = $event->getProductIds();
+        $storeId = $event->getStoreId();
         $visibility = $attrData[ProductInterface::VISIBILITY] ?? 0;

         if (!$visibility || !$productIds) {
             return;
         }

-        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility);
+        $this->adaptUrlRewritesToVisibility->execute($productIds, (int)$visibility, $storeId);
     }
 }


diff --git a/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php b/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
--- a/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
+++ b/Model/Products/AdaptUrlRewritesToVisibilityAttribute.php
@@ -65,11 +65,12 @@
      *
      * @param array $productIds
      * @param int $visibility
+     * @param int $storeId
      * @throws UrlAlreadyExistsException
      */
-    public function execute(array $productIds, int $visibility): void
+    public function execute(array $productIds, int $visibility, int $storeId): void
     {
-        $products = $this->getProductsByIds($productIds);
+        $products = $this->getProductsByIds($productIds, $storeId);

         /** @var Product $product */
         foreach ($products as $product) {
@@ -78,6 +79,7 @@
                     [
                         UrlRewrite::ENTITY_ID => $product->getId(),
                         UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
+                        UrlRewrite::STORE_ID => $storeId,
                     ]
                 );
             } elseif ($visibility !== Visibility::VISIBILITY_NOT_VISIBLE) {
@@ -110,13 +112,15 @@
      * Get Product Models by Id's
      *
      * @param array $productIds
+     * @param int   $storeId
      * @return array
      */
-    private function getProductsByIds(array $productIds): array
+    private function getProductsByIds(array $productIds, int $storeId): array
     {
         $productCollection = $this->productCollectionFactory->create();
         $productCollection->addAttributeToSelect(ProductInterface::VISIBILITY);
         $productCollection->addAttributeToSelect('url_key');
+        $productCollection->addStoreFilter($storeId);
         $productCollection->addFieldToFilter(
             'entity_id',
             ['in' => array_unique($productIds)]

**Comment by snuffer82** [comment] 2022-02-02 11:35
Hi, 
thank you for the quick support. I applied the fix suggested by @Aquarvin  but the url rewrites are not generated.

ps. after applying the fix i ran:
- bin/magento setup:upgrade
- bin/magento setup:di:compile
- bin/magento setup:static-content:deploy
- bin/magento cache:clean && php bin/magento cache:flush

thank you for any suggestions

**Comment by engcom-November** [comment] 2022-02-21 13:05
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
Multi website store setup
Create product and assign to only main website
Products Grid - Select Product - Update Attributes - Websites - Add Product To all Websites - Save
Product added to queue.
After Update attributes for products are successfully updated, Product added to all websites and URL rewrites are generated. **Note:** To update from CLI:  (bin/magento queue:consumers:start product_action_attribute.website.update &)
**No issue**
Admin - Marketing - URL Rewrites
![image](https://user-images.githubusercontent.com/60198231/154960522-dc361de2-6b14-4e39-857f-735ec88b7342.png)
![image](https://user-images.githubusercontent.com/60198231/154960646-910c0a8c-9e2a-412a-a485-65d150bfdc11.png)
@snuffer82 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-03-07 06:45
Hi @snuffer82 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-07 06:45 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.1
