### ISSUE TITLE
Saving the company is not possible as long as the company credit (credit limit) is not changed (for e.g. locale: German)

### ISSUE THREAD

**Issue by dimaMackert** [magento/magento2#36777] opened 2023-01-25 10:10 UTC
### Preconditions and environment

- Magento version 2.4.5-p1

### Steps to reproduce

The error occurs in the adminhtml/backend. The following procedure is related to the adminhtml/backend, not the frontend.

1. Login to the Backend
2. Click on your name at the top-right corner > Account Settings > Interface Locale and change change your account setting for Interface Locale to "Detusch (Deutschland) / German (Germany)
3. Create new Company and fill out all required fields (*)
4. Save company

### Expected result

Company is saved

### Actual result

Company cannot be saved, an message appears in the Company Credit tab with the message:
> Please enter a number 0 or greater, without comma in this field.

### Additional information

If you delete the amount in the credit limit and click on save, the company will be saved.
If you edit the company now, the amount is again with a comma in it (0,00) and this must be removed then again, so that the saving becomes possible.
The comma must be removed in any case, even if Magento writes it in there.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sunilit42** [comment] 2023-01-25 11:59
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Alfa** [comment] 2023-02-09 08:33
@magento give me 2.4-develop instance with extensions magento/B2B Features

**Comment by engcom-Alfa** [comment] 2023-02-09 08:47
@magento give me 2.4-develop instance with extensions magento/magento ee

**Comment by engcom-Alfa** [comment] 2023-02-09 08:58
@magento give me 2.4-develop instance with extensions magento/magento2b2b

**Comment by engcom-Alfa** [comment] 2023-02-09 13:31
@magento give me 2.4-develop instance with edition b2b

**Comment by engcom-Alfa** [comment] 2023-02-09 14:09
Hi @dimaMackert 

Thanks for reporting the ticket.
as per testing according to mentioned steps, the actual result and expected result, the issue is not reproducible and we are able to save the company successfully.
**Video Attachment**

https://user-images.githubusercontent.com/51679138/217835162-9b6741ae-ec67-411b-a7ce-1ef90a178323.mp4


however, following the additional information on the ticket, the behavior seems to be a valid field validation case, where it is working as per the current implementation only which helps the user to remove any incorrect typo. hence marking the ticket as can not reproduce and needs an update. kindly let me know if additional information is required to be considered as the scope of the expected result.

**Snapshot Attachment**
![36777_snap](https://user-images.githubusercontent.com/51679138/217835543-8ec36c2b-d879-4bfb-93ce-d5bc903c02a9.png)

**Comment by engcom-Alfa** [comment] 2023-02-21 14:09
Hey @dimaMackert 

closing the ticket since did not get any update for the past 2 weeks on the last comment of this ticket.

Regards
Arpit khare

**Closed as completed by engcom-Alfa** 2023-02-21 14:09 UTC
Labels: Component: Customer, Issue:  Cannot Reproduce, Issue: needs update, Area: B2B, Reported on 2.4.5-p1

**Comment by raquelperez899** [comment] 2023-02-23 15:57
@magento give me 2.4.5-p1 instance

**Comment by chapagain** [comment] 2023-02-27 20:39
There's a patch available for Adobe Commerce
https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-26/acsd-48661-company-credit-limit-comma-separator-validation.html?lang=en
