### ISSUE TITLE
i18n:collect-phrases does not include titles in layout files

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#35462] opened 2022-05-12 07:33 UTC
### Preconditions (*)

1.2.4.3-p2

### Steps to reproduce (*)

1. Take a look at `Magento_Customer/layout/override/base/customer_account_create.xml`. You will find the following line:    `<title>Create New Customer Account</title>`
2. Run `bin/magento i18n:collect-phrases --output=test.csv vendor/magento/module-customer/view/frontend/layout/`

### Expected result (*)

1. I would expect, that the title "Create New Customer Account" would be included in the `test.csv` file, as given translations for titles actually wor. 

### Actual result (*)

1. The phrase is not included in the exported file.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-06-02 13:22
Hello @norgeindian,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is reproducible for us. But I would like to suggest you a workaround to translate the `title` text here. 

I request you to please go through with [this link](https://community.magento.com/t5/Magento-2-x-PWA-Theming-Layout/How-to-translate-lt-title-gt-content/td-p/123708), it might resolve your issue. 

Or if you have any other use case and you need the text in the `CSV` file then please let us know.

Thanks

**Comment by schizek** [comment] 2022-06-03 19:46
I am reproducing the same issue on 2.4.4 of Adobe Commerce.  We need to provide translation files to our translators with all phrases as opposed to manually poking around after things have been translated and finding all these missed phrases.  It would be highly beneficial to include these within the output of `i18n:collect-phrases`.

**Comment by norgeindian** [comment] 2022-06-07 04:30
@engcom-Hotel , thanks for the idea, but I'm totally with @schizek .
This command should offer the possibility to make sure,that definitely all phrases, which must be translated, are included.
Currently, all automatically created language packs are missing these parts.
In the [Devdocs](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-i18n.html#config-cli-subcommands-xlate-dict-dict), the following is written down:

> To begin translating, use a command to generate a dictionary .csv file with a collected list of **all existing phrases and words**.

So this should be definitely fixed in my eyes, so that these phrases are included as well.

**Comment by engcom-Hotel** [comment] 2022-06-07 07:45
Hello @norgeindian,

Thanks for the feedback!

I am confirming this issue for further process.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-07 10:49
Hello @norgeindian,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3226 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3226&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-09-07 10:49 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Issue: needs update, Area: Framework, area: localization
