### ISSUE TITLE
Sort Order of related, crosssell and upsell products not saving in product edit pages in backend

### ISSUE THREAD

**Issue by tonybrown85** [magento/magento2#9799] opened 2017-05-30 16:44 UTC
### Preconditions

1. PHP Version 7.0.19
2. Linux cPanel VPS
3. Magento 2.1.5

### Steps to reproduce

1. Add related, crosssell, and upsell product against a product.
2. Change sort order of related, crosssell, and upsell products with ajax drag / drop
3. Save Product
4. Sort order doesn't save

### Expected result

1. Sort order should save in the order in which they were dragged / dropped in the system backend on each respective product

### Actual result

1. [Screenshot, logs]

As stated above the sort order of all related, crosssell, and upsell products should save against each respective product. The data doesn't save at all as I've ran product csv exports and there isn't any sorting data in those respective columns.

**Comment by IlnitskiyArtem** [comment] 2017-06-23 15:39
@tonybrown85, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70186 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-09-29 11:30
@tonybrown85, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Comment by tonybrown85** [comment] 2017-11-03 08:58
@magento-engcom-team This issue is not resolved guys. I've just upgraded to Magento 2.1.9 and this problem still persists. It drags the elements of related etc fine but doesn't save the sort order.

**Comment by sheepfy** [comment] 2021-02-18 12:54
@magento-engcom-team This issue is still present in Magento 2.4.2
![image](https://user-images.githubusercontent.com/17467949/108359806-1e0e9680-71f9-11eb-9a92-623680926f3c.png)
![image](https://user-images.githubusercontent.com/17467949/108359833-28309500-71f9-11eb-9879-a0e34d051f11.png)

**Comment by eiriksnilsen** [comment] 2021-03-19 14:15
I am experiencing the same thing on a recently built M2.4 site - is there any hope this will be fixed soon?

**Comment by sheepfy** [comment] 2021-03-19 14:18
@eiriksnilsen 
Fix is this PR https://github.com/magento/magento2/pull/32221
You can make a composer patch

**Comment by krishprakash** [comment] 2021-03-21 10:04
@magento give me 2.4-develop instance

**Comment by sheepfy** [comment] 2021-09-28 08:00
Any luck in getting this one merged and closed? It's been years..

**Comment by engcom-Bravo** [comment] 2022-12-19 07:59
Hi @tonybrown85,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.
Thanks.

**Closed as completed by engcom-Bravo** 2022-12-19 07:59 UTC
Labels: bug report, Component: Catalog, Issue:  Cannot Reproduce, Priority: P3, Progress: done, Issue: ready for confirmation, Issue: needs update
