### ISSUE TITLE
M2.2.2 Multiple Bugs with Product Videos on Mobile

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#13247] opened 2018-01-18 05:04 UTC
### Preconditions
1.  Magento 2.2.2
2.  PHP 7.1

### Steps to reproduce
1.  Add a YouTube Video to a product page
2.  Move it to second position and place a static image first

### Expected result
1.  YouTube video should play

### Actual result
1. YouTube video does not play
2. When the YouTube video is placed in the second position it does not play no matter how many times it is pressed on mobile devices
3. When the YouTube video is in the first position it needs to be pressed twice to start
4. Can view a demo on https://www.extenderman.com.au/test-product2.html

NB - THESE ISSUES ONLY OCCUR ON MOBILE DEVICES

**Comment by magento-engcom-team** [comment] 2018-01-18 13:58
@bondimedical3 Thanks for your report. We tried to reproduce Issue on your website, we opened it and played the video on iPhone 6 and HTC one x9 and it worked fine. Please let us know what mobile device did you use and make sure your mobile device is set up correctly. Also, please try to reproduce this issue on other mobile devices and please try to reproduce the issue with a clean instance of Magento.  Thank you

**Comment by bondimedical3** [comment] 2018-01-19 03:12
The play feature is extremely poorly designed. I have tried it multiple times and after about 30 attempts managed to get the video to start (not to mention the fact when you tap the screen it scrolls to the next image). Can you explain in detail the exact method to start the video? Also the video needs to be pressed again to begin? I am testing on Samsung Galaxy S8+ S7 edge and S5

EDIT: I have made a video so you can gain a better understanding of what I am experiencing -https://youtu.be/SBGXIsCFRO4

**Comment by magento-engcom-team** [comment] 2018-01-19 09:21
@bondimedical3, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by engcom-Delta** [comment] 2019-08-02 08:11
Hi @bondimedical3 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Delta** 2019-08-02 08:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
