### ISSUE TITLE
 Bug Report: Existing Image Name removed when image added via api

### ISSUE THREAD

**Issue by brideo** [magento/magento2#37835] opened 2023-08-03 00:37 UTC
### Preconditions and environment

- Magento version 2.4.6
- Rest API

### Steps to reproduce

POST https://exmple.com/rest/V1/products/some-sku/media

`{
    "entry": {
        "position": 9999,
        "media_type": "image",
        "label": "Some Product Label",
        "disabled": false,
        "types": [
            "image",
            "thumbnail",
            "small_image"
        ],
        "file": "1234.jpeg",
        "content": {
            "base64_encoded_data": "image_data",
            "type": "image\/jpeg",
            "name": "1001110080394.jpeg"
        }
    }
}`

### Expected result

* Image is added 

### Actual result

* Image is added with no name assigned. 

### Additional information

Replace the existing code within `Magento\Catalog\Model\Product\Gallery\GalleryManagement::create`:

```
// Existing code snippet
$product = $this->productInterfaceFactory->create();
$product->setSku($sku);
$product->setMediaGalleryEntries($existingMediaGalleryEntries);
try {
    $product = $this->productRepository->save($product);
} catch (\Exception $e) {
    if ($e instanceof InputException) {
        throw $e;
    } else {
        throw new StateException(__("The product can't be saved."));
    }
}
```

with 

```
// Corrected code snippet
$product = $this->productRepository->get($sku);
$product->setMediaGalleryEntries($existingMediaGalleryEntries);
try {
    $product = $this->productRepository->save($product);
} catch (\Exception $e) {
    if ($e instanceof InputException) {
        throw $e;
    } else {
        throw new StateException(__("The product can't be saved."));
    }
}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by brideo** [comment] 2023-08-03 00:47
https://github.com/magento/magento2/pull/37836 - fixed and created a PR here

**Comment by engcom-Bravo** [comment] 2023-08-03 09:07
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-03 12:36
Hi @brideo,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

`{ "entry": { "position": 9999, "media_type": "image", "label": "Some Product Label", "disabled": false, "types": [ "image", "thumbnail", "small_image" ], "file": "1234.jpeg", "content": { "base64_encoded_data": "image_data", "type": "image\/jpeg", "name": "1001110080394.jpeg" } } }`


<img width="1237" alt="Screenshot 2023-08-03 at 3 16 31 PM" src="https://github.com/magento/magento2/assets/51680745/a9476977-ace0-4055-8e40-c2fbea88905d">


<img width="1178" alt="Screenshot 2023-08-03 at 3 37 24 PM" src="https://github.com/magento/magento2/assets/51680745/d2767747-e717-4ce5-9a85-30a8b0cf33ed">



We have added image via REST API(name as Magento) and we are getting image name also could you please let us know if we are missing anything and also provide screenshots where exactly image name will be populated it will helps us to reproduce the issue.


Thanks.

**Comment by brideo** [comment] 2023-08-14 01:42
when you send images it removes the name attribute.

https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/37836.patch

**Comment by engcom-Bravo** [comment] 2023-08-17 09:41
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-17 12:26
Hi @brideo,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**We have send the images using API**

<img width="1146" alt="Screenshot 2023-08-17 at 4 11 08 PM" src="https://github.com/magento/magento2/assets/51680745/0d1c4e1f-aa96-41c3-afa4-38b5d698c929">

<img width="1406" alt="Screenshot 2023-08-17 at 4 16 40 PM" src="https://github.com/magento/magento2/assets/51680745/a834db9f-4608-4111-b1e6-012857261020">


**After sending the images we are able to get the name attribute.**


<img width="1160" alt="Screenshot 2023-08-17 at 4 13 01 PM" src="https://github.com/magento/magento2/assets/51680745/2efdb6e5-c364-4323-ba15-55a2a1a80549">



kindly let us know still if we are missing anything.Please provide screenshots if possible it will help us to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-28 06:09
Hi @brideo,

Kindly provide latest update on this comment  https://github.com/magento/magento2/issues/37835#issuecomment-1682195010 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-07 06:45
Hi @brideo,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-07 06:45 UTC
Labels: Issue: needs update, Reported on 2.4.6
