### ISSUE TITLE
Unable to login BO after upgrade to 2.4.4p3 with Msi disabled

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#37301] opened 2023-03-27 15:07 UTC
### Preconditions and environment

- Magento version 2.4.4
- All Magento_Inventory modules disabled

### Steps to reproduce

Disable all Magento_Inventory modules
Upgrade from magento 2.4.4p2 to 2.4.4p3
Login in the backoffice area

### Expected result

Access to the backoffice

### Actual result

The login page hangs on this error:

1 exception(s):
Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 16

Element 'resource': The attribute 'title' is required but missing.
Line: 14

#1 Magento\Framework\Acl\Builder\Proxy->getAcl() called at [vendor/magento/module-backend/Model/Auth/Session.php:258]
#2 Magento\Backend\Model\Auth\Session->processLogin() called at [vendor/magento/module-backend/Model/Auth.php:165]
#3 Magento\Backend\Model\Auth->login() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Magento\Backend\Model\Auth\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Magento\Backend\Model\Auth\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-admin-adobe-ims/Plugin/DisableAdminLoginAuthPlugin.php:56]
#6 Magento\AdminAdobeIms\Plugin\DisableAdminLoginAuthPlugin->aroundLogin() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#7 Magento\Backend\Model\Auth\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Backend\Model\Auth\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Model/Auth/Interceptor.php:23]
#9 Magento\Backend\Model\Auth\Interceptor->login() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:207]
#10 Magento\Backend\App\Action\Plugin\Authentication->_performLogin() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:159]
#11 Magento\Backend\App\Action\Plugin\Authentication->_processNotLoggedInUser() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:127]
#12 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Backend\Controller\Adminhtml\Denied\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\Backend\Controller\Adminhtml\Denied\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Denied/Index/Interceptor.php:32]
#15 Magento\Backend\Controller\Adminhtml\Denied\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#16 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#17 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#18 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#23 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#24 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]

### Additional information

Debug done editing /vendor/magento/framework/Config/Reader/Filesystem.php:166

            if ($configMerger && !$configMerger->validate($this->_schemaFile, $errors)) {
                $message = "Invalid Document \n";
                /**/$errors = $configMerger->validateDomDocument($configMerger->getDom(), $this->_schemaFile);
                $message.= print_r($errors, true) . "\n";
                $message.= $configMerger->getDom()->saveXML() . "\n";/**/
                throw new \Magento\Framework\Exception\LocalizedException(
                    new \Magento\Framework\Phrase($message . implode("\n", $errors))
                );
            }

for printing all config acl resources.

I found two missing titles
/vendor/magento/module-inventory-in-store-pickup-sales-api/etc/acl.xml
`<resource` id="Magento_InventoryInStorePickupApi::inStorePickup" title="In-Store Pickup">

/vendor/magento/module-inventory-source-selection-api/etc/acl.xml
`<resource` id="Magento_InventoryApi::source" title="Inventory Source">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-28 00:37
Hi @angelo983 ,

Verified the issue in 2.4.4-p2 magento instance,the issue is not reproducible.

**Kindly refer the below screenshots:**

<img width="1512" alt="inv1" src="https://user-images.githubusercontent.com/60198592/228096540-34cd4301-fb03-47b5-9271-a90c09ac1f6d.png">
<img width="1512" alt="inv2" src="https://user-images.githubusercontent.com/60198592/228096677-1cd2d076-6a0b-4d71-b880-4c0148b94df6.png">

**Steps to reproduce:**

1.Install 2.4.4 -p2 magento instance
2.upgrade to 2.4.4-p2 to 2.4.4 -p3
3.Run setup upgrade command
4.Disable all Magento_Inventory modules
5.Login into back office

Can able to login back office without any issues.Kindly provide more information if the issue is still reproducible.

Regards,

**Comment by angelo983** [comment] 2023-03-28 09:27
These are the modules that I disabled:
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryIndexer
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryReservations
Magento_InventoryReservationsApi
Magento_InventoryCache
Magento_InventorySalesAdminUi
Magento_InventorySalesApi
Magento_InventorySalesFrontendUi
Magento_InventoryShipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
Magento_InventoryShippingAdminUi
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryReservationCli
Magento_InventoryExportStock
Magento_CatalogInventoryGraphQl
Magento_InventorySetupFixtureGenerator
Magento_InventoryAdvancedCheckout
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryRequisitionList
Magento_InventoryGraphQl
Magento_InventoryBundleImportExport
Magento_InventoryBundleProductIndexer
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupGraphQl
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupQuoteGraphQl
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_InventoryInStorePickupFrontend
Magento_InventoryInStorePickupMultishipping
Magento_InventoryInStorePickupSalesAdminUi
Magento_InventoryInStorePickupWebapiExtension
Magento_InventoryCatalogFrontendUi
Magento_InventoryConfigurableProductFrontendUi
Magento_InventorySwatchesFrontendUi
Magento_InventoryVisualMerchandiser
Magento_InventoryWishlist

**Comment by engcom-Dash** [comment] 2023-03-31 04:25
Hi @angelo983 ,

Verified the issue the in 2.4.4-p3 which is upgraded from 2.4.4-p2 still the issue is not reproducible.As per your last comments i disabled the all module still the backend admin working properly. 

Kindly refer the screenshots: 
<img width="1512" alt="bo3" src="https://user-images.githubusercontent.com/60198592/229022296-59480742-27f5-4198-92e5-d0aec869df2e.png">
<img width="1512" alt="bo1" src="https://user-images.githubusercontent.com/60198592/229022246-0de5b8bb-bd40-4be4-ab68-5d40a50a9028.png">
<img width="1512" alt="bo2" src="https://user-images.githubusercontent.com/60198592/229022258-edbbfd40-4cff-44d6-8c05-e9236b4fd59f.png">

Regards,

**Comment by angelo983** [comment] 2023-03-31 04:59
If all other modules are active, please try to reset password and complete
the steps for a new password. I have an exception in this scenario too

Il Ven 31 Mar 2023, 06:25 Rajasekar Panneerselvam ***@***.***>
ha scritto:

**Comment by engcom-Dash** [comment] 2023-04-17 01:25
Hi @angelo983 ,

Thanks for your contribution,

Verified the issue in 2.4.4-p3 and the issue is not reproducible.
Kindly refer the screenshots:

1.List of Module disabled:
https://user-images.githubusercontent.com/60198592/231415292-b80a0b98-b42d-4aa7-b5bd-cd5bdd1ed223.png
2.After that we reset the password in admin panel and run setup upgrade the comments and verified backend able access or not
https://user-images.githubusercontent.com/60198592/231415079-18921b8f-ae0d-4f8c-a9cb-4a4627ede9b9.png

User can able to access the admin panel without any issue.

Regards,

**Comment by engcom-Dash** [comment] 2023-05-02 15:11
Hi @angelo983 


We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-05-02 15:11 UTC
Labels: Issue: needs update
