### ISSUE TITLE
Get Shipping Method as object from order instance gives undefined index.

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#20380] opened 2019-01-17 18:06 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Magento 2.2.x

### Steps to reproduce (*)

1. Create a downloadable or virtual product.
2. Place an order with this product.
3. In custom controller or anywhere load order with id.
   `$order = $this->orderFactory->create()->load($orderId); //your order id`
4. Now get shipping method as object.
`$order->getShippingMethod(true)->getMethod();`
5. It gives below error
`Notice: Undefined offset: 1 in /Users/mahesh/contribute/mage226/vendor/magento/module-sales/Model/Order.php on line 1223`

### Expected result (*)

1. It should return Null if order has no shipping method, so developers can manage it from their end.
2.

### Actual result (*)

1. 
![screenshot](https://user-images.githubusercontent.com/32479280/51338745-aec19800-1ab0-11e9-8b46-de08c487741c.png)

2.

**Comment by magento-engcom-team** [comment] 2019-01-17 18:06
Hi @maheshWebkul721. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@maheshWebkul721 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-17 18:08
@maheshWebkul721 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97697`, `MAGETWO-97698` were created

**Comment by magento-engcom-team** [comment] 2019-01-18 07:53
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-13 15:45
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#20381 by @maheshWebkul721 in 2.3-develop branch
Related commit(s):
 - [82b1707b9b5c3dab9c74ab6a9a11a93f98880515](https://github.com/magento/magento2/commit/82b1707b9b5c3dab9c74ab6a9a11a93f98880515)
 - [ccd301441585b21f23f8ae942ca4a2b0c05b06d1](https://github.com/magento/magento2/commit/ccd301441585b21f23f8ae942ca4a2b0c05b06d1)
 - [36cab08ed239081170a038212ec1531ec136abd3](https://github.com/magento/magento2/commit/36cab08ed239081170a038212ec1531ec136abd3)

The fix will be available with the upcoming  release.

**Closed as completed by magento-engcom-team** 2019-02-13 15:45 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-02-25 23:10
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#20866 by @maheshWebkul721 in 2.2-develop branch
Related commit(s):
 - [c495f31900cc2250bb63bcd57242d518aa894d92](https://github.com/magento/magento2/commit/c495f31900cc2250bb63bcd57242d518aa894d92)

The fix will be available with the upcoming 2.2.9 release.
