### ISSUE TITLE
Tabbing issue on product detail page

### ISSUE THREAD

**Issue by prakash2jcommerce** [magento/magento2#21077] opened 2019-02-08 13:58 UTC
### Preconditions (*)

1. 2.3.0

### Steps to reproduce (*)

1. In Frontend product listing page on list view mode click on Add Your Review link it will re-direct on product detail page. 

### Expected result (*)

1. Once arrived on Product details page only review tab need to open or active.
![image](https://user-images.githubusercontent.com/18117994/52482489-62f99e80-2bd7-11e9-9a59-97d9d7e36521.png)

### Actual result (*)

1. Once arrived on Product detail page 2 product both detail and review tabs are active.
![image](https://user-images.githubusercontent.com/18117994/52482442-48bfc080-2bd7-11e9-81fe-b4a97d5c6420.png)

**Comment by magento-engcom-team** [comment] 2019-02-08 13:58
Hi @prakash2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@prakash2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-08 14:09
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-08 18:07
Hi @amol2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by amol2jcommerce** [comment] 2019-02-08 18:10
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 18:10
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-08 18:10
Hi @amol2jcommerce, here is your [Magento instance](https://i-21077-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21077-2-3-develop.instances.magento-community.engineering/admin](https://i-21077-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-08 18:35
:white_check_mark: Confirmed by @amol2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-10 04:57
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-11 19:14
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-11 19:14
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-11 19:15
Hi @shikhamis11, here is your [Magento instance](https://i-21077-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21077-2-3-develop.instances.magento-community.engineering/admin](https://i-21077-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-11 19:32
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-11 19:32
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-11 19:32
Hi @shikhamis11, here is your [Magento instance](https://i-21077-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21077-2-2-develop.instances.magento-community.engineering/admin](https://i-21077-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-11 19:38
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98204`, `MAGETWO-98205` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-05 21:17
Hi @prakash2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21079 by @prakash2jcommerce in 2.3-develop branch
Related commit(s):
 - [7fc0ff766a4ca185366a8d5c52c1197a3b067131](https://github.com/magento/magento2/commit/7fc0ff766a4ca185366a8d5c52c1197a3b067131)
 - [01d7f5126d7ec13fd28e18c9bc4b65cc92f2faff](https://github.com/magento/magento2/commit/01d7f5126d7ec13fd28e18c9bc4b65cc92f2faff)
 - [c034338b65b835a875c7cfa6196e697f497fda4f](https://github.com/magento/magento2/commit/c034338b65b835a875c7cfa6196e697f497fda4f)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-05 21:17 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend, Component: Review

**Comment by magento-engcom-team** [comment] 2019-03-08 13:10
Hi @prakash2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21588 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [ab2de1505b5b98d746c3623269e19fdb283676b5](https://github.com/magento/magento2/commit/ab2de1505b5b98d746c3623269e19fdb283676b5)
 - [c6c6ead1aaaa5e45b992aff7d564a44c2276e083](https://github.com/magento/magento2/commit/c6c6ead1aaaa5e45b992aff7d564a44c2276e083)
 - [905085d16039d44c5a1159d2fc68a68062291f37](https://github.com/magento/magento2/commit/905085d16039d44c5a1159d2fc68a68062291f37)
 - [2d3a876863188a5c0b10abda33ff3c58e2f695f3](https://github.com/magento/magento2/commit/2d3a876863188a5c0b10abda33ff3c58e2f695f3)

The fix will be available with the upcoming 2.2.9 release.
