### ISSUE TITLE
Malformed sitemap

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37584] opened 2023-06-06 06:30 UTC
### Preconditions and environment

- Magento version 2.4.6-p1
- Anything else that would help a developer reproduce the bug : Remote stoage

### Steps to reproduce

1. Generate a sitemap, large enough to have 3 (or more..) sub-sitemap in the sitemapindex in a remote storage (I don't know if the issue also occurs when using local storage)
2. Remove products to have only 2 (or less than before) sub-sitemap in the sitemapindex
3. Generate sitemap again

### Expected result

```
 <?xml version="1.0" encoding="UTF-8"?>
  <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-1.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-2.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-3.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-4.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-5.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-6.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  </sitemapindex>
```

### Actual result

```
 <?xml version="1.0" encoding="UTF-8"?>
  <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-1.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-2.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-3.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-4.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-5.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  <sitemap><loc>https://www.domain.com/media/sitemap/sitemap-1-6.xml</loc><lastmod>2023-06-06T06:21:17+00:00</lastmod></sitemap>
  </sitemapindex>ml</loc><lastmod>2023-06-06T02:57:44+00:00</lastmod></sitemap>
   </sitemapindex>


```

### Additional information

It's probably because we are writing on file without remove (or truncate) it first.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment] 2023-09-21 12:19
@engcom-Delta it's probably a duplicate of https://github.com/magento/magento2/issues/36789

**Comment by engcom-Dash** [comment] 2023-10-03 13:20
Hi @Nuranto 
Thank you for reporting and collaboration.
Similar issue has been confirmed here [#](https://github.com/magento/magento2/issues/36789) 36789 we need to close this issue as Duplicate of this one [#](https://github.com/magento/magento2/issues/36789)36789 Kindly move onto this issue for latest updates / solutions on the same.
Thanks.

**Comment by engcom-Hotel** [comment] 2023-10-03 13:37
Duplicate of #36789

**Closed as completed by engcom-Hotel** 2023-10-03 13:37 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.6
