### ISSUE TITLE
Magento 2.4.1 logo size will not resize from admin

### ISSUE THREAD

**Issue by magentoexpert** [magento/magento2#31816] opened 2021-01-24 12:52 UTC
### Preconditions (*)

1. Magento 2.4.1
2.

### Steps to reproduce (*)

1. Install Magento software using composer
2. Install Magento 2.4.1 using composer
3. Install sample date using composer

### Expected result (*)

1. Go to Magento admin
2. Content / Configuration
3. Edit Default Website/Store/Store front them name
4. Header
5. Upload logo 371x65
6. Logo width 371
7. Logo height 65
8. Save
9. Clear cache
10. Flush cache
11. Customer view
12. The logo should be 371x65

### Actual result (*)

1. The logo does not resize
2. The logo width remains 170 which is the default

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by magentoexpert** [comment] 2021-01-24 15:47
Please note that the folder structure on Magento 2.4.1 installed with composer is completely different.
ALL the proposals put forward on the forum refer to obsolete folder structure /app/design/frontend/magento
This is empty
The new structure includes /pub folder where most files are found
I can work out where the design templates and css are for the frontend and for admin

**Comment by engcom-Alfa** [comment] 2021-01-25 08:02
Duplicate of #29721

**Closed as completed by engcom-Alfa** 2021-01-25 08:02 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.1
