### ISSUE TITLE
Mass Update attribute 

### ISSUE THREAD

**Issue by Top-CMS** [magento/magento2#37733] opened 2023-07-07 08:46 UTC
### Preconditions and environment

- Magento version 2.4.5-p1, 2.4.6, 2.43

### Steps to reproduce

In the backend:

1. Go to Catalog - Products
2. Select products which to update 
3. Dropdown Update attributes
4. Tab Advanced Inventory 
5. Out-of-Stock Threshold , give new number
6. Save, so now the Config value for Out-of-Stock Threshold for that product has been changed
7. But we want to undo that with many more products, we want to Use Config Settings for products
8. At Catalog - Productsselect product again -- Dropdown Update attributes --Tab Advanced Inventory 
9. Out-of-Stock Threshold "Change" and "Use Config Settings"  ---> Save
10. 

### Expected result

It should have the config value

### Actual result

In Backend it looks like product has been changed. But in the database cataloginventory_stock_item --> min_qty --> has not been changed. So for that product still the old value in step 5 is the value..

When saving the product manually, the expected result is there.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-07-07 10:05
@magento give me 2.4-develop instance

**Comment by Top-CMS** [comment] 2023-07-07 11:14
thanks for the Magento Instance, but one issue, I cant check in de database to see the  results in cataloginventory_stock_item --> min_qty

In backend looks good, but not in database.
To test that in this environment also cron has to be installed to run consumers:list

**Comment by engcom-Dash** [comment] 2023-07-10 13:07
Hi @Top-CMS ,

Could you please elaborate the  steps(7th step in steps to reproduce) and kindly provide related screenshots of this issue.its very easy to proceed further in this case.

Thanks

**Comment by engcom-Dash** [comment] 2023-07-21 11:13
@Top-CMS ,

Do you want further investigation regarding this issue??,Kindly provide more information about this issue, its very easy to proceed further in this issue.

Thanks!

**Comment by Top-CMS** [comment] 2023-07-24 07:39
I am on holiday now. I will update this over 2/3 weeks

Op vr 21 jul. 2023 13:13 schreef Rajasekar Panneerselvam <
***@***.***>:

**Comment by engcom-Dash** [comment] 2023-08-14 06:21
Hi @Top-CMS ,

Could you please elaborate steps to reproduce already mentioned is last [comment](https://github.com/magento/magento2/issues/37733#issuecomment-1628925129),We need more information regarding this issue and Kindly attach the screenshot.Its very easy to reproduce the issue.

Thanks.

**Comment by engcom-Dash** [comment] 2023-08-16 12:12
Hi @Top-CMS ,

verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly refer the below screenshots:
1.We changed Out-of-Stock Threshold as 20:
<img width="1504" alt="Screenshot 2023-08-16 at 5 32 58 PM" src="https://github.com/magento/magento2/assets/60198592/7678a5d1-ddf0-470e-a229-1497a4ef75cf">
<img width="1504" alt="Screenshot 2023-08-16 at 5 33 45 PM" src="https://github.com/magento/magento2/assets/60198592/60255c5a-47ea-4c1e-8294-5d78e3107b37">
2.We changed Out-of-Stock Threshold as 10:
<img width="1504" alt="Screenshot 2023-08-16 at 5 34 04 PM" src="https://github.com/magento/magento2/assets/60198592/7088c7a2-a651-47e3-9cad-75f248b33341">
<img width="1504" alt="Screenshot 2023-08-16 at 5 34 19 PM" src="https://github.com/magento/magento2/assets/60198592/b237fba1-2030-491f-ae19-f5818b1581ba">

**Comment by engcom-Dash** [comment] 2023-08-28 13:31
Hi @Top-CMS ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-28 13:31 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
