### ISSUE TITLE
Missing js vimeo library

### ISSUE THREAD

**Issue by angelo983** [magento/magento2#36279] opened 2022-10-12 16:53 UTC
### Preconditions and environment

- Magento 2.4.4
- Magento_PageBuilder enabled
- Js bundling enabled
- PHP 8.1
- Production mode

### Steps to reproduce

- Load an extension that require vimeo as library;
- Create a block of this type with height bigger than viewport height, but not loading any video in content;
- Switch to production mode with active js minification.

### Expected result

Div scrolling without problems

### Actual result

Scrolling hangs while scrolling

### Additional information

In console this error appears:
/*****************************/
homepage:1 Refused to execute script from '/vimeoWrapper.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
main.min.js:3 Error: Script error for "vimeoWrapper", needed by: Magento_PageBuilder/js/widget/video-background
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:17:53)
    at HTMLScriptElement.onScriptError (require.min.js:117:697)
require.min.js:127          GET /vimeoWrapper.min.js net::ERR_ABORTED 404

require.min.js:127          GET /vimeoWrapper.min.js net::ERR_ABORTED 404
/*****************************/

In /vendor/magento/module-page-builder/view/base/requirejs-config.js these resources are requested:
            'Magento_PageBuilder/js/resource/vimeo/player': 'vimeo/player',
            'Magento_PageBuilder/js/resource/vimeo/vimeo-wrapper': 'vimeo/vimeo-wrapper',

but in /vendor/magento/module-page-builder/view/base/web/js/resource vimeo folder is not present.
![image](https://user-images.githubusercontent.com/24254454/195402531-381ab4cf-e675-4cd1-84e3-ca00c07398c1.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-13 16:25
Hi @angelo983 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but unable to reproduce the issue on configuring product videos in both ways as mentioned below:
Steps:
1. Enabled Production mode.
2. Configured Vimeo video for a product by configuring in both ways. 1. As per Magento [docs](https://docs.magento.com/user-guide/v2.3/catalog/product-video.html) and 2. [devdocs](https://developer.adobe.com/commerce/frontend-core/guide/themes/product-video/)
3. Enabled JS bundling as per Magento [devdocs](https://developer.adobe.com/commerce/frontend-core/guide/themes/js-bundling/)
4. Access front end - Product details page - No issue and no errors in console observed.

Kindly confirm if you are using any 3rd party extensions / modules enabled that's causing the issue and recheck on Magento 2.4-develop instance as it is the upcoming 2.4.x release and provide missing configuration details if any if the issue is still reproducible.
Thank you.

**Comment by angelo983** [comment] 2022-10-17 14:54
@magento give me 2.4-develop instance

**Comment by johncarlson21** [comment] 2022-10-18 15:08
@magento give me 2.4-develop instance

**Comment by loic-paquin** [comment] 2022-10-27 03:36
I had the same issue, You probably ran a composer update after the release of 2.4.5. It is caused by the version 2.2.3 of the PageBuilder module. Also my pageBuilder in the BackOffice was unusable ( Sliders were not loading).

You can resolve the issue by typing the command : `composer require magento/module-page-builder:2.2.2`
After this, as usual compile + deploy static + clean cache

**Comment by engcom-November** [comment] 2022-10-27 06:49
Hi @loic-paquin , Thank you for the response.
There is an ongoing current Page builder issue which is confirmed and being tracked [here](https://github.com/magento/magento2/issues/36188). Please move onto this issue for latest updates / solutions on the same. As the issue not reproducible on clean 2.4develop instance, we are closing this issue. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-27 06:49 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update

**Comment by angelo983** [comment] 2022-11-04 08:02
Updates:
DevTools failed to load source map: Could not load content for https://5a6e47f9b7eaa11ced36627e0bf2d9f2.instances.magento-community.engineering/static/version1667504227/frontend/Magento/luma/en_US/vimeo/player.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

https://5a6e47f9b7eaa11ced36627e0bf2d9f2.instances.magento-community.engineering/set-of-sprite-yoga-straps.html

You can see this error in a fresh magento 2.4.x develop instance in a grouped product page
