### ISSUE TITLE
Float value calculation not returning exact zero

### ISSUE THREAD

**Issue by mack4hack** [magento/magento2#38478] opened 2024-02-27 11:45 UTC
### Preconditions and environment

- Magento: 2.4.6-p4
- PHP: 8.1
- Simple product having price $83.99
- A 100% discount coupon code also applicable on shipping amount
- Flat shipping with rate $205.98

### Steps to reproduce

**Frontend/Backend**
1. Add the Simple Product which having price $83.99 
2. apply coupon code (100% discount)
3. select flat shipping method ($205.98)
4. Observe the order total it will be Zero
5. Place the order

**Backend**
1. Open the order detail page
2. Click on the Invoice 
3. Select the checkbox to create a shipment
4. fill the tracking details
5. Submit the Invoice

### Expected result

Order must be "Completed"
State : complete  and Status : Completed

### Actual result

Order is getting "Closed"
State : closed and Status : Closed

### Additional information

File Path : vendor/magento/module-sales/Model/Order/Invoice/Total/Shipping.php
Line no: 41 $invoice->setGrandTotal($invoice->getGrandTotal() + $orderShippingAmount);

$invoice->getGrandTotal() + $orderShippingAmount returns a float 2.8421709430404E-14

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-28 05:52
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-02-28 09:37
Hi @mack4hack,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce
Frontend/Backend**

Add the Simple Product which having price $83.99
apply coupon code (100% discount)
select flat shipping method ($205.98)
Observe the order total it will be Zero
Place the order

**Backend**

Open the order detail page
Click on the Invoice
Select the checkbox to create a shipment
fill the tracking details
Submit the Invoice



![Screenshot from 2024-02-28 11-47-36](https://github.com/magento/magento2/assets/51680745/3ea9bd4b-ffcc-487d-8806-74d2ca077395)



![Screenshot from 2024-02-28 11-48-09](https://github.com/magento/magento2/assets/51680745/88dddd4d-38cb-48ab-8214-756bea11cb45)


Order is completed and status is also in completed state.

Kindly recheck the issue in Latest Magento 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by mack4hack** [comment] 2024-02-28 10:11
@magento give me 2.4.6-p4 instance

**Comment by mack4hack** [comment] 2024-02-28 10:17
Hi @engcom-Bravo , Thanks for checking the issue, I am not able to reproduce it on  2.4-develop instance.
I will try to verify it on  2.4.6-p4 instance and share the details

**Comment by mack4hack** [comment] 2024-02-28 13:43
@magento give me 2.4.6-p4 instance

**Comment by mack4hack** [comment] 2024-02-29 04:43
@magento give me 2.4.6-p4 instance

**Comment by mack4hack** [comment] 2024-02-29 07:44
@engcom-Bravo  can you please check this issue on  Magento 2.4.6-p4 version ?

**Comment by engcom-Bravo** [comment] 2024-03-01 09:28
Hi @mack4hack,

Thanks for your update.

It is recommended to verify the issues in latest Magento 2.4-develop instance.it might be possible issue has been fixed in Latest branch.

Thanks.

**Comment by tushardatar7** [comment] 2024-03-04 08:47
@magento I am working on it

**Comment by tushardatar7** [comment] 2024-03-04 08:47
@magento add to contributors team

**Comment by tushardatar7** [comment] 2024-03-04 08:49
@magento I am working on it

**Comment by engcom-Bravo** [comment] 2024-03-05 05:41
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-05 06:39
Hi @tushardatar7,

Thanks for your contribution for creating the PR.

We have verified the issue in Latest 2.4-develop instance as it is recommended and the issue is not reproducible.kindly refer the screenshots.

![Screenshot from 2024-03-05 11-30-26](https://github.com/magento/magento2/assets/51680745/e41ff915-e9c1-41b7-989e-01760c5a5de2)




![Screenshot from 2024-03-05 11-30-40](https://github.com/magento/magento2/assets/51680745/c2973ebf-72f7-48ce-ad71-afd64068f2b1)


The order status is completed.Could you please try to reproduce the issue in Magento 2.4-develop instance.

Thanks

**Comment by tushardatar7** [comment] 2024-03-05 07:13
Hi @engcom-Bravo 

Can you please confirm PHP version installed on develop instance. 
I am able to reproduce it on vanilla setup on local (using php8.1) but not on above demo instance.

Hi @mack4hack  - can you confirm PHP version you are using.

**Comment by engcom-Bravo** [comment] 2024-03-06 11:55
Hi @tushardatar7,

Thanks for your update.

We have verified the issue in Magento 2.4-develop instance(Local) with php 8.1 still we are not able to reproduce the issue.Could you please confirm in which Magento version you are checking the issue.

Thanks.

**Comment by tushardatar7** [comment] 2024-03-08 05:45
Hi @engcom-Bravo,

I got this issue on Adobe commerce 2.4.6-p4 version.
One of other project running on Adobe commerce 2.4.3-p2 also had same issue. It was fixed by patch added in PR.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-03-08 13:23
Hi @tushardatar7,

Thanks for your update.

We have checked the issue in Magento 2.4-develop instance with EE edition also and the issue is not reproducible.it is recommended to verify the issue in Latest Magento 2.4-develop instance.

It might be issue got fixed in Latest Magento 2.4-develop instance.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-03-20 04:38
Hi @mack4hack,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-20 04:38 UTC
Labels: Issue: needs update, Reported on 2.4.6-p4
