### ISSUE TITLE
Currency change, Bank Transfer but checkout page shows "Your credit card will be charged for"

### ISSUE THREAD

**Issue by oviliz** [magento/magento2#12526] opened 2017-12-02 22:32 UTC
Magento 2.2.0 and 2.2.1.

If I change currency, when I choose and proceed with the checkout choosing as Payment Method, **Bank Transfer** Payment, on the right column under Order Total it prints "Your **credit card** will be charged for".

Attaching picture.
![screenshot from 2017-12-02 22-10-15](https://user-images.githubusercontent.com/73616/33520316-a56b1806-d7b0-11e7-91cf-9fba65799ebe.png)

**Comment by magento-engcom-team** [comment] 2017-12-04 15:30
@oviliz, thank you for your report.
We've created internal ticket(s) MAGETWO-84973 to track progress on the issue.

**Comment by RomaKis** [comment] 2017-12-11 10:58
Looking at the code I can conclude that this is not a bug. This is message with base currency. And if base currency != quote currency it is shown.
![screenshot from 2017-12-11 12-57-19](https://user-images.githubusercontent.com/17450979/33827941-c09b9506-de72-11e7-9e23-b9fff6a31481.png)
![screenshot from 2017-12-11 12-58-23](https://user-images.githubusercontent.com/17450979/33827971-dab6fa2a-de72-11e7-95de-64b156a85e25.png)

Although this message is weird.
@magento-engcom-team, if it is correct M2 behavior close this ticket, if no - provide correct M2 behavior.

**Comment by oviliz** [comment] 2017-12-11 13:42
I believe it should simply say, "You will be charged for" rather than "Your credit card will be charged for", so it can apply for all kind of payment methods. That's all.

**Comment by ishakhsuvarov** [comment] 2017-12-12 11:36
@oviliz Fix for this issue has been delivered into `2.2-develop` and will be released in the next functional patch release.
Thank you for collaboration.

**Closed as completed by ishakhsuvarov** 2017-12-12 11:36 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is not valid
