### ISSUE TITLE
Paypal Order total mismatch - Price rounding issue

### ISSUE THREAD

**Issue by ArchanaMohan1** [magento/magento2#24915] opened 2019-10-08 06:49 UTC
@engcom-Charlie - We are facing the same  issue as  https://github.com/magento/magento2/issues/24233 .Below are the details.Do look into this.

**Preconditions** 

Magento 2.3.1 CE
Paypal Express checkout enabled
Tax Enabled

**Steps to reproduce** 

Add a fews products to the cart from the frontend.
Go to checkout and fill up address details including Country, State and Postal code So that tax would be applied.
Place order with PayPal express checkout

**Expected result** 
The order should be placed

**Actual result** 
It gives "The totals of the cart item amounts do not match order amounts." error.
PayPal is considering rounded price value of Subtotal and tax in its API.
 As you know, this does not match the Magento rounding method.

**Comment by ArchanaMohan1** [comment] 2019-10-08 07:41
@engcom-Charlie  -
This is the information we got from the paypal team.

![image](https://user-images.githubusercontent.com/45938529/66376374-2469ed00-e9cd-11e9-84fd-1fb949ead8cf.png)

**Comment by engcom-Charlie** [comment] 2019-10-08 11:09
Hello @ArchanaMohan1 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.
I am closing this issue because i have to verify issues only on 2.3-develop branch.
![image](https://user-images.githubusercontent.com/51680850/66384410-5ed08b80-e9c7-11e9-8b63-7f1e70a80a25.png)
If you still faced this issue on `2.3-develop` please create a new Issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-08 11:09 UTC
Labels: Issue: Format is valid

**Comment by matthewhaworth** [comment] 2019-11-06 15:57
I am also having this issue on 2.2.6.

I believe this is the same too: https://github.com/magento/magento2/issues/24233
