### ISSUE TITLE
Installation with Sample Data Removes Products from Category Pages on Initial Reindex

### ISSUE THREAD

**Issue by techgh0st** [magento/magento2#2722] opened 2015-12-15 15:03 UTC
After installation of Magento 2 Enterprise Edition for a client with sample data, reindexed via the CLI tool as shown:

``` bash
php bin/magento indexer:reindex
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
```

Then cleared the cache by doing the following:

``` bash
php bin/magento cache:clean
php bin/magento cache:flush
```

No issues were reported however all products stopped showing in their respective categories. The only fix I found for the issue was to re-save products in the backend to have them show correctly:
1. Products -> Catalog
2. Remove all filters so that every product is showing.
3. On the table, select the drop down and choose: Select All
4. The table updates to show: 2048 records found (2048 selected)
5. Under the Actions drop down, select :Change Status -> Enable

Once this was done, all products started to show on the frontend even after further re-indexing.

**Comment by ghost** [comment] 2015-12-15 18:36
I have never seen this. Why did you reindex after installing sample data? Was crontab set up? Did you see any other errors?

**Comment by techgh0st** [comment] 2015-12-17 20:02
1. Sample data was included with the package itself. This was not a magento installation that later installed sample data on it, but rather it is the Magento 2.0 package with the sample data installation that the client provided as it is the enterprise edition and not the community edition. 
2. Reindexing was done as the client claimed that all products stopped showing after they attempted to add a product. By default, the indexing is set to Update on Save and shortly after, no products were showing. This is when I decided to re-trace the installation, did nothing after the install other than reindex via the magento script as shown above, and resulted in the issue reported.
3. No errors were reported by the magento installation on the issue. Just that no products were visible after the installation of Magento 2 Enterprise Edition with Sample Data package and the fix was to re-save all products.
4. The cron tasks were indeed configured in the crontab.

**Comment by voleye** [comment] 2016-03-11 15:39
@techgh0st Thank you for your report. We have created a ticket "MAGETWO-50395" to track the progress of this issue.

**Comment by yaronish** [comment] 2016-04-14 07:53
@techgh0st Currently we can't reproduce this bug neither for Magento 2 EE 2.0.4 nor Magento 2 EE develop branch. I'm going to close this issue but feel free to add some information or report if problem exists for you with latest released version.
Thanks.

**Closed as completed by yaronish** 2016-04-14 07:53 UTC
Labels: Issue: Ready for Work, bug report
