### ISSUE TITLE
[2.3.5-p2 GraphQL] Aggrigation attribute options are not sorted in the same order as the product attribute options are in the backend

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#33176] opened 2021-06-08 10:08 UTC
### Preconditions (*)

1. Magento 2.3.5-p2

### Steps to reproduce (*)

1. Create a select attribute with a couple of options and make it filterable.
2. Change the order of these options in the backend.
3. Add a product with each of these options to a category.
4. Do a products graphql query for the aggregations. eg:
 ```
query products { 
    products(
        pageSize: 10, 
        currentPage: 1, 
        filter: {category_id:{eq:"82"}}, 
        sort: { position:DESC}
    ) {
        aggregations {
            __typename
            label
            count
            attribute_code
            options {
                label
                value
                count
                __typename
            }
        }
    }   
}
```

### Expected result (*)

1. I expect the aggregation options to be returned in the order they are sorted in the admin panel

### Actual result (*)

![Screenshot from 2021-06-08 12-06-17](https://user-images.githubusercontent.com/22170051/121167182-fdbf2200-c851-11eb-9c5a-83c6d901873b.png)
In this example Nederland is ordered below Ireland
![Screenshot from 2021-06-08 11-47-30](https://user-images.githubusercontent.com/22170051/121167259-0e6f9800-c852-11eb-8200-da1145b34106.png)
But in the results Nederland is above Ireland.

The results looks like the attribute options are always ordered by the option value_id instead of their position.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Hexmage** [comment] 2021-06-08 10:10
@magento give me 2.4-develop instance

**Comment by Hexmage** [comment] 2021-06-08 10:25
Works as intended on 2.4

**Comment by Hexmage** [comment] 2021-06-08 11:25
I'm now trying to figure out what change caused this to work, where it previously didn't

**Comment by engcom-Lima** [comment] 2021-06-11 10:18
Hi @Hexmage 

I tried to reproduce the issue on Magento v-2.4.2, Unfortunately can't reproduce the issue.

Graphql is not provide sorting on aggrigation attributes. Only can be sort product attributes using below attributes- 

- Product Name (name)
- Sort by the position assigned to each product.(position)
- Price (price)
- relevance SortEnum

It is not an issue. Hence closing this ticket. If you have any doubts or any other issue then you can raise the new ticket for the same.

Thanks for the understanding!

**Closed as completed by engcom-Lima** 2021-06-11 10:18 UTC
Labels: non-issue, Issue: ready for confirmation

**Comment by Hexmage** [comment] 2021-08-11 13:38
Did some more research and it appears that this does happen in 2.4. The issue is that Elasticsearch always returns the aggregations sorted by count desc followed by option_value_id asc. Apparently the develop instance does not do this, I'm guessing either it's not using elastic or it's elastic instance is configured differently.

So the issue has changed to not being able to determine what the elasticsearch results are sorted by. I don't think that it's possible to get a correctly sorted aggregation result out of elasicsearch itself as it only knows the count and oprion_value_id. So this would have to happen in the code that adds the label to the aggregation.
