### ISSUE TITLE
Je n'arrive pas à changer le language (passer de anglais UK à Français)

### ISSUE THREAD

**Issue by clahaut** [magento/magento2#33489] opened 2021-07-15 09:51 UTC
### Preconditions (*)

1. je me connecte, je souhaite changer la langue dans mes paramètres de compte
2. je ne peux sauvegarder en français

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2. je souhaite passer en français

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-19 09:35
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
Login to Admin
Navigate to Account Settings page
Interface Locale - Change the Language to UK English, provide admin password and Save Account - **No Issue**
Now change the language to  français (France) and Save Account - **No issue: User is able to switch Language from UK English to French**
@clahaut, kindly verify the issue on latest Magento version and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-02 07:17
@clahaut,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-02 07:17 UTC
Labels: Issue:  Cannot Reproduce, Component: Admin, Issue: needs update
