### ISSUE TITLE
Invalid date when i add product in magento 2.

### ISSUE THREAD

**Issue by SatishDubariya** [magento/magento2#10233] opened 2017-07-13 06:47 UTC
When i am trying to add product in catalog, i get an error of Invalid date.
### Preconditions
1. Magento 2.1.5
2. PHP Version 5.6.24

### Steps to reproduce
1. admin > products > catalog > add new product > fill details as per my requirement.
2. save product. 

### Expected result
1. Success message: Product Saved.

### Actual result
![invalid-date](https://user-images.githubusercontent.com/21054477/28153803-152c380c-67c5-11e7-8a26-7a3dd6082e37.png)

My interface locale is English (United Kingdom) / English (United Kingdom)

**Comment by veloraven** [comment] 2017-07-24 11:23
@SatishDubariya thank you for your report.
But I'm closing this issue as duplicate of #6323.

**Closed as completed by veloraven** 2017-07-24 11:23 UTC
Labels: bug report
