### ISSUE TITLE
Filtering by store view doesn't work

### ISSUE THREAD

**Issue by cozzamara** [magento/magento2#5152] opened 2016-06-22 08:41 UTC
## Steps to reproduce
1. Install Magento 2.0.7
2. Upgrade to Magento 2.1.0
3. Set up multiple store views
4. Navigate to Products -> Catalog 
5. Apply filter by Store View
## Expected result

Products are filtered by store view
## Actual result

Filter is ignored; products for all store views are still shown. 

This was not a problem in 2.0.7

**Comment by cozzamara** [comment] 2016-06-22 16:42
Not sure if that matters, but this was happening on 2.0.7 CE upgraded using command-line to 2.1.0.RC3 - not on freshly installed RC3.

**Comment by cozzamara** [comment] 2016-06-24 18:54
This is still a problem in 2.1.0 release upgraded from 2.0.7. 
Fresh new installation of 2.1.0 doesn't suffer from this problem

**Comment by sevos1984** [comment] 2016-09-16 08:59
I can't recreate it after upgrading from 2.0.9 to 2.1.1. Is this still actual?

**Comment by sevos1984** [comment] 2016-10-03 09:39
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-03 09:39 UTC
Labels: bug report, Progress: needs update, Component: Catalog
