### ISSUE TITLE
Configurable product goes to out of stock after the shipment is created for one child product

### ISSUE THREAD

**Issue by rajesh291994** [magento/magento2#37364] opened 2023-04-12 13:24 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

We have a multi website (2 website) and multi source configuration in our magento 2 setup

1. Assign single source to multiple stocks 
2. Assign a stock to all the websites
3. Create configurable product(2 options) and assign qty to source(10 qty to each product)
4. Place an order with one qty from frontend from one of the website
5. Create an shipment in for that particular order
6. You will notice that parent configurable product goes out of stock automatically. That product will be out of stock for both the website where only one qty is shipped

### Expected result

Parent configurable product should not go out of stock as only one item from child product is been shipped. 

### Actual result

Parent configurable product goes out of stock after creating shipment. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-13 08:37
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-13 13:54
Hi @rajesh291994,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

**We have Created a multi website (2 website) and multi source configuration in our magento 2 setup**

- 
- Assign single source to multiple stocks
- Assign a stock to all the websites
- Create configurable product(2 options) and assign qty to source(10 qty to each product)
- Place an order with one qty from frontend from one of the website
- Create an shipment in for that particular order
- You will notice that parent configurable product goes out of stock automatically. That product will be out of stock for both the website where only one qty is shipped




<img width="1478" alt="Screenshot 2023-04-13 at 2 50 28 PM" src="https://user-images.githubusercontent.com/51680745/231723140-851d90ba-f4b7-472d-ac81-c82deb3baaf3.png">



After shipment the configurable product is still in in stock.only 1 quantity of child product has been shipped.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by rajesh291994** [comment] 2023-04-17 07:32
@engcom-Bravo, I checked the scenarios in the sample magento 2.4.5 p1. It is reproducable kindly check the setting done
It has two websites:

1. Created two source named (india and usa)
2. Created two stock named (stock for india and Stock for usa)
3. Assign both source to both the stocks
![Screenshot from 2023-04-17 12-33-15](https://user-images.githubusercontent.com/84515190/232414851-90a16d37-ff89-4d7f-bf95-42894ddec463.png)
4. Created configurable product with two child and assigned the qty for all the sources
5. When we place order and create shipment. It's parent product goes out of stock automatically.
6. Please refer the video screen recording for the same
[Screencast from 17-04-23 12:30:09 PM IST.webm](https://user-images.githubusercontent.com/84515190/232415380-12cd50ff-8fd1-4fd5-b85b-949c6697954a.webm)

**Comment by engcom-Bravo** [comment] 2023-04-17 08:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-17 13:22
Hi @rajesh291994,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.



**Steps to reproduce**

- Created two source named (india and usa)
- Created two stock named (stock for india and Stock for usa)
- Assign both source to both the stocks
- Created configurable product with two child and assigned the qty for all the sources
- Place the order and create shipment.



<img width="1506" alt="Screenshot 2023-04-17 at 2 47 23 PM" src="https://user-images.githubusercontent.com/51680745/232474493-4a3dd5ab-b919-4519-81cd-4ee3b11f91c2.png">


<img width="1485" alt="Screenshot 2023-04-17 at 2 47 00 PM" src="https://user-images.githubusercontent.com/51680745/232474591-4c9f86c0-32c6-4ed4-8cdb-cd7b01f36483.png">



In frontend the product is still in stock.We have verified for both configurable product and simple product.After creating shipment the product is in still in stock.

<img width="1410" alt="Screenshot 2023-04-17 at 2 47 42 PM" src="https://user-images.githubusercontent.com/51680745/232474687-ed0569f0-1699-40bf-874c-95b7b3712719.png">




Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by rajesh291994** [comment] 2023-04-18 05:02
@engcom-Bravo, 
1. I not sure why it is not getting reproduced for you. 
2. Can I access the magento instance you worked on to reproduced the issue as that provided instances not seems to be working any more

**Comment by engcom-Bravo** [comment] 2023-04-18 09:11
Hi @rajesh291994,

Thanks for your update.

Please make a comment in this issue like @magento give me 2.4-develop instance it will give an Magento 2.4-develop instance to test.It will work upto some appropriate time. 

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by rajesh291994** [comment] 2023-04-18 11:07
@magento give me 2.4-develop instance it will give an Magento 2.4-develop instance to test. To reproduce the issue so that we can work on that

**Comment by engcom-Bravo** [comment] 2023-04-18 11:10
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-18 11:15
@rajesh291994 

Magento 2.4 develop has been created.please check and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by rajesh291994** [comment] 2023-04-18 11:17
@engcom-Bravo Thank you. Will setup the configuration and will update you here. Once reproduced

**Comment by engcom-Bravo** [comment] 2023-05-02 06:04
Hi @rajesh291994,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-02 06:04
Hi @rajesh291994,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-02 06:04 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by rajesh291994** [comment] 2023-06-20 12:09
@engcom-Bravo The issue is has occured again. And I figured out the reproducing step. Can we reopen this issue. I can setup an issue. If I get the magento instance
@magento give me 2.4-develop instance

**Comment by rajesh291994** [comment] 2023-06-20 12:42
@magento Thank you for the instance. It seems the issue is not reproducable in the given instance. Can I get the instance of 2.4.5 p1

**Comment by joshbaltzell** [comment] 2023-07-14 19:05
We are seeing this issue on a live site now too. We are running 2.4.4 on this instance. @rajesh291994 were you able to recreate this or resolve it?

**Comment by ryan-copeland** [comment] 2023-08-16 14:07
We are seeing the same issue in v2.4.4-p3. Configurable parent products are going out of stock when an order containing an associated simple is shipped.

Has anyone found the root cause of this issue yet?

**Comment by serzhik** [comment] 2024-10-18 20:41
It seems it is duplicated. Check https://github.com/magento/inventory/issues/3350, please
