### ISSUE TITLE
disable onepage checkout

### ISSUE THREAD

**Issue by PVoIWD** [magento/magento2#3392] opened 2016-02-12 21:17 UTC
Hello,

When you disable onepage checkout - there's no ability to check out on the front end. I have flushed the backend cache and browser cache.

https://drive.google.com/a/interiorwebdesign.com/file/d/0BwbQCbz5XlTOT2ZUTHVWX1RLYjA/view?usp=drivesdk
https://drive.google.com/a/interiorwebdesign.com/file/d/0BwbQCbz5XlTOQ2FlNlk0Sm9HTWs/view?usp=drivesdk

Thanks, PVo

**Comment by ishakhsuvarov** [comment] 2016-02-22 09:01
Hi @PVoIWD this seems to be and expected behaviour for this case.
What was your expected result?

**Comment by PVoIWD** [comment] 2016-02-22 19:55
If I select 'No', shouldn't this fall back to the multi-page checkout? I have found reference here:
https://drive.google.com/a/interiorwebdesign.com/file/d/0BwbQCbz5XlTOWWVPWFlqZ0NjUGc/view?usp=drivesdk

http://frontlinedev.com/how-to-enable-disable-one-page-checkout-magento/

I'm expecting it to work the same since this feature exists in Magento 1. Should it work differently, I think you guys should rename the setting to something else so it doesn't confused the user.

Thanks, PVo

**Comment by asemenenko** [comment] 2016-02-23 08:59
Hi @PVoIWD multi address checkout can be turned off with a different setting. I agree that we should combine those settings since its not quite obvious.

**Comment by PVoIWD** [comment] 2016-02-23 15:18
It's multi-page checkout I'm referring to, not multi-address. There is a separate setting for multi-address already. I still think this is a issue and shouldn't be working this way. Setting No for One-Page checkout should go back to multi-page checkout, NOT disable checkout entirely.

**Comment by ishakhsuvarov** [comment] 2016-02-24 13:33
@PVoIWD Multi-page checkout is not available in Magento 2, only available options are Onepage Checkout and Multiple Address Checkout.

**Comment by ishakhsuvarov** [comment] 2016-03-29 09:26
@PVoIWD Closing this ticket for now. Please feel free to reopen if you have any additional questions.

**Closed as completed by ishakhsuvarov** 2016-03-29 09:26 UTC

**Comment by maqlec** [comment] 2016-09-07 06:36
We have Magento 2.1.1 and multi-page checkout is not available, so maybe you should remove this option from panel or comment. It's only introduces confusion.
