### ISSUE TITLE
Error when updating category scheduled changes for a specific store view

### ISSUE THREAD

**Issue by GioDeGruyter** [magento/magento2#37210] opened 2023-03-14 21:18 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- PHP 8.1
- Setup with at least 2 store views

### Steps to reproduce

1. Navigate to Catalog > Categories in the admin section
2. Change the scope to a specific store view
3. Select any category
4. Create a new scheduled change for the category for the specific store view
5. Save the schedule and the category
6. Update the existing schedule, change the end date of the existing schedule and try to save it

### Expected result

The schedule is saved.

### Actual result

The following error occurs:
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/54057125/225136921-bf6ac0a0-c408-416b-b6df-a19b5ee628fa.png">

### Additional information

I was able to reproduce this issue on a clean 2.4.5-p1 installation with sample data.

The following log regarding the issue can be found in system.log:

`[2023-03-14T20:52:30.453553+00:00] report.CRITICAL: Exception message: Warning: Undefined array key "updated_in" in /app/vendor/magento/module-staging/Model/Operation/Update.php on line 174`

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-03-15 05:44
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-03-15 08:06
**Hi @GioDeGruyter ,**

_**Issue confirmed !**_

Verified the issue in 2.4-develop instance and the issue is reproducible,Hence we are confirming the issue.

_**Preconditions:**_

Magento Version 2.4-develop 
PHP Version 8.1
Multi store was created

_**Steps to reproduce:**_

- Navigate to Catalog > Categories in the admin section
- Change the scope to a specific store view
- Select any category
- Create a new scheduled change for the category for the specific store view
- Save the schedule and the category
- Update the existing schedule, change the end date of the existing schedule and try to save it

**_Kindly Refer the below screenshots:_**
<img width="1505" alt="st1" src="https://user-images.githubusercontent.com/60198592/225243421-33614579-9885-427f-a016-7ea9aa692206.png">
<img width="1505" alt="st2" src="https://user-images.githubusercontent.com/60198592/225243443-faee2608-98bc-4cbe-9a51-cac95369d838.png">
<img width="1505" alt="st3" src="https://user-images.githubusercontent.com/60198592/225243448-9b3ce0f6-1a3c-417a-a734-f28d5020fc0c.png">
<img width="1505" alt="st4" src="https://user-images.githubusercontent.com/60198592/225243450-6645b87e-1c77-4d22-9dca-d2d27b69ec7c.png">
<img width="975" alt="st6" src="https://user-images.githubusercontent.com/60198592/225245832-ec5527fc-370c-4f0e-bf1f-1c8753d9b93f.png">



We are trying to Update the existing schedule(**_change the end date of the existing schedule and try to save it_**),But we getting the error which is attached in above screenshot also we are getting same **_system.log_** as per the description and **_system.log_** screenshots also attached.This is actual result,So we are confirming the issue in 2.4-develop instance.

Regards,

**Comment by Zaahed** [comment] 2023-03-31 09:06
@magento I'm working on this

**Comment by vacla** [comment] 2023-04-14 15:38
Is there any update on this, or is there maybe already a patch available that we are able to apply to go around this?

**Comment by engcom-Dash** [comment] 2023-04-18 10:58
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-04-18 11:11
@magento give me 2.4-develop commerce instance

**Comment by engcom-Dash** [comment] 2023-04-19 11:14
Hi @GioDeGruyter ,

I tried to reproduce the  issue on the latest code base of 2.4-develop with multiple store views enabled, but was unable to do so.
Here are the steps followed,

Navigate to Catalog > Categories in the admin section
Change the scope to a specific store view
Select any category
Create a new scheduled change for the category for the specific store view
Save the schedule and the category
Update the existing schedule, change the end date of the existing schedule and try to save it
![image](https://user-images.githubusercontent.com/60198592/233056928-1bc8d9d4-e7ce-43dc-83a7-98172f75c2c3.png)![image](https://user-images.githubusercontent.com/60198592/233056928-1bc8d9d4-e7ce-43dc-83a7-98172f75c2c3.png)


This issue is no longer reproducible,Hence we are closing this issue.

Let us know if we are missing anything!

Regards,

**Closed as completed by engcom-Dash** 2023-04-19 11:14 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Admin UI, Reported on 2.4.5-p1

**Comment by GioDeGruyter** [comment] 2023-04-19 14:04
@engcom-Dash What is the upcoming release on the 2.4 develop branch? And is there a possibility we can patch this for our current version?

**Comment by Planet9store** [comment] 2023-05-05 03:29
@magento-admin 
I am encountering an issue related to "Error when updating category scheduled changes for a specific store view" in Magento. Are there any relevant patches available to address this problem? The required version is 2.4.5-p1

**Comment by GioDeGruyter** [comment] 2023-05-10 13:54
@magento-admin Could we reopen this issue? Since this has clearly not been fixed yet.

**Comment by bona-kim** [comment] 2023-07-27 07:24
@magento-admin I've tested on 2.4.6 enterprise clean environment but the issue is still there. 
Could you retest and reopen the issue?
<img width="1691" alt="Screenshot 2023-07-27 at 09 19 37" src="https://github.com/magento/magento2/assets/53227199/5965360c-e102-43b8-b877-140670e356cf">
<img width="1663" alt="Screenshot 2023-07-27 at 09 16 12" src="https://github.com/magento/magento2/assets/53227199/5380f7db-4da4-4776-8318-b5abfda899c8">

**Comment by GioDeGruyter** [comment] 2023-08-02 08:03
@magento-admin Any updates on this? Could this be reopened as @bona-kim asked?

**Comment by SandraKot** [comment] 2023-08-10 07:40
@magento-admin This seems to be issue as well on 2.4.5-p3, we get the same problem 
'error: : Something went wrong while saving the Magento\Catalog\Api\Data\CategoryInterface.' 

And then in logs:
report.CRITICAL: Exception: Warning: Undefined array key "updated_in" in /app/vendor/magento/module-staging/Model/Operation/Update.php on line 174 in /app/vendor/magento/framework/App/ErrorHandler.php:62

**Comment by monarch-sp** [comment] 2023-08-25 13:59
After spending an hour digging into the code, I have identified the issue. It appears that the problem lies within the **'vendor/magento/module-staging/Model/Operation/Update.php**' file

Override the **'vendor/magento/module-staging/Model/Operation/Update.php**' file in your module

Add 
        ```
$version = $this->versionInfoProvider->getVersionInfo(
            $entity,
            $this->resolveVersion(array_merge($entityData, $arguments))
            );
         $entityData['updated_in'] = $version->getUpdatedIn();
```

in processUpdate function

code should be.

```
private function processUpdate(
        EntityMetadataInterface $metadata,
        $entityType,
        $entity,
        $arguments
    ) {

 

if (isset($arguments['origin_in'])) {
             $version = $this->versionInfoProvider->getVersionInfo(
            $entity,
            $this->resolveVersion(array_merge($entityData, $arguments))
            );
         $entityData['updated_in'] = $version->getUpdatedIn();
            $needReschedule = $arguments['created_in'] != $arguments['origin_in']
                || $update->getRollbackId() != $entityData['updated_in'];
```

**Comment by linetsoscar** [comment] 2023-08-31 20:24
> After spending an hour digging into the code, I have identified the issue. It appears that the problem lies within the **'vendor/magento/module-staging/Model/Operation/Update.php**' file
> 
> Override the **'vendor/magento/module-staging/Model/Operation/Update.php**' file in your module
> 
> Add
> 
> ```
> $version = $this->versionInfoProvider->getVersionInfo(
>             $entity,
>             $this->resolveVersion(array_merge($entityData, $arguments))
>             );
>          $entityData['updated_in'] = $version->getUpdatedIn();
> ```
> 
> in **processUpdate** function
> 
> code should be.
> 
> ```
> private function processUpdate(
>         EntityMetadataInterface $metadata,
>         $entityType,
>         $entity,
>         $arguments
>     ) {
> 
>  
> 
> if (isset($arguments['origin_in'])) {
>              $version = $this->versionInfoProvider->getVersionInfo(
>             $entity,
>             $this->resolveVersion(array_merge($entityData, $arguments))
>             );
>          $entityData['updated_in'] = $version->getUpdatedIn();
>             $needReschedule = $arguments['created_in'] != $arguments['origin_in']
>                 || $update->getRollbackId() != $entityData['updated_in'];
>                 ....
>                 ...
> ```

COuld you share the way how did you fix it? i did the same thing as you, but still getting that error, please.

**Comment by GioDeGruyter** [comment] 2023-09-01 08:17
We had the same issue @linetsoscar. We've resolved it by setting the updated_in data on the entity itself as well:

`$entity->setData('updated_in', $version->getUpdatedIn());`

This results into:
`private function processUpdate(
        EntityMetadataInterface $metadata,
        $entityType,
        $entity,
        $arguments
    ) {

 

if (isset($arguments['origin_in'])) {
             $version = $this->versionInfoProvider->getVersionInfo(
            $entity,
            $this->resolveVersion(array_merge($entityData, $arguments))
            );
         $entityData['updated_in'] = $version->getUpdatedIn();
         $entity->setData('updated_in', $version->getUpdatedIn());
            $needReschedule = $arguments['created_in'] != $arguments['origin_in']
                || $update->getRollbackId() != $entityData['updated_in'];
                ....
                ...`

**Comment by linetsoscar** [comment] 2023-09-01 19:23
Thank u @GioDeGruyter  but i still have the problem, it is not redirecting, it keeps loading or the loading spinner doesnt disappear, but it is updating which is ok... isnt it happening in your case?

**Comment by linetsoscar** [comment] 2023-09-01 19:25
Here i have an image in order to show u that the spinner still  showing  
![Screenshot from 2023-09-01 15-23-45](https://github.com/magento/magento2/assets/97040270/2efdfe5f-3628-46d0-a275-b9610767d7bf)

**Comment by mamsincl** [comment] 2023-12-19 16:33
duplicated on Adobe Commerce 2.4.6-p3

----

fix we come up
- bring `$version` fetching earlier
- check if key `updated_in` does not exist against `$entityData`
- also check if property `updated_in` exists against `$version`
- then assign

----

```
diff --git a/vendor/magento/module-staging/Model/Operation/Update.php b/vendor/magento/module-staging/Model/Operation/Update.php
index 76a8b5bf..cbe8bbf8 100644
--- a/vendor/magento/module-staging/Model/Operation/Update.php
+++ b/vendor/magento/module-staging/Model/Operation/Update.php
@@ -168,6 +168,14 @@ class Update implements UpdateInterface
         }
         $update = $this->updateRepository->get($arguments['created_in']);
 
+        $version = $this->versionInfoProvider->getVersionInfo(
+            $entity,
+            $this->resolveVersion(array_merge($entityData, $arguments))
+        );
+        if (!isset($entityData['updated_in']) && $version->getUpdatedIn()) {
+            $entityData['updated_in'] = $version->getUpdatedIn();
+        }
+
         $needReschedule = false;
         if (isset($arguments['origin_in'])) {
             $needReschedule = $arguments['created_in'] != $arguments['origin_in']
@@ -178,10 +186,6 @@ class Update implements UpdateInterface
         }
 
         $identifier = $entityData[$metadata->getIdentifierField()];
-        $version = $this->versionInfoProvider->getVersionInfo(
-            $entity,
-            $this->resolveVersion(array_merge($entityData, $arguments))
-        );
         if ($version->getRowId() != null) {
             if ($update->getRollbackId()) {
                 $arguments['updated_in'] = $update->getRollbackId();
```

**Comment by MageCondition** [comment] 2024-09-06 08:27
@mamsincl Any news on this issue?
