### ISSUE TITLE
Magento B2B - Cannot Assign Customer Group ID

### ISSUE THREAD

**Issue by portchris** [magento/magento2#38187] opened 2023-11-15 14:53 UTC
### Preconditions and environment

- Magento Enterprise 2.4.6-p3
- Magento B2B 1.3.3-p3
- PHP 8.2
- Varnish 6.5.1
- Elasticsearch 7.7.1 
- Elasticsuite 2.10.16
- NGINX Proxy + PHP-FPM 1.23.4
- MariaDB 10.4.29-MariaDB-1:10.4.29+maria~ubu2004

### Steps to reproduce

Install fresh version of Magento:
```bash
    composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition .
    composer require magento/extension-b2b smile/elasticsuite
    composer update --lock
```
Create DB:
```mysql
CREATE DATABASE magento246;
```

Install and deploy
```bash
    bin/magento setup:install \
    --base-url=http://magento2-demo.localhost/ \
    --db-host=mysql \
    --db-name=magento246 \
    --db-user=user \
    --db-password=password \
    --admin-firstname=My \
    --admin-lastname=Name \
    --admin-email=email@test.com\
    --admin-user=developer \
    --admin-password=dev@2023 \
    --backend-frontname=admin \
    --language=en_AU \
    --currency=AUD \
    --timezone=Australia/Melbourne \
    --use-rewrites=1 \
    --search-engine=elasticsuite \
    --elasticsearch-host=elasticsearch7 \
    --elasticsearch-index-prefix=demo_ \
    --elasticsearch-port=9200 

    export COMPOSER_MEMORY_LIMIT=-1 && composer -n validate && composer -n install && php ./vendor/bin/ece-patches apply || true && rm -rf generated/* && php bin/magento deploy:mode:set production -s && php bin/magento setup:upgrade && php bin/magento maintenance:enable && php bin/magento module:disable Magento_TwoFactorAuth Magento_AdminAdobeImsTwoFactorAuth && php bin/magento setup:di:compile && touch pub/static/deployed_version.txt && php bin/magento setup:static-content:deploy -f en_AU en_US && php bin/magento cache:flush && php bin/magento cache:enable && php bin/magento maintenance:disable
```

Login to Admin with newly created user https://magento2-demo.localhost/admin/ navigate to:

> Admin > Customers > Companies

Create a new company + admin. Assign default customer group

Then, attempt to change the customer group via:

> Admin > Customers > All Customers > Check: Company Admin > Actions: Assign a Customer Group

### Expected result

The customer group is updated.

### Actual result

The customer group is NOT updated despite a success message displaying. 

### Is this a feature not a bug?

After looking into the code I've found the following: 
`vendor/magento/module-company/etc/di.xml`
```xml
    <type name="Magento\Company\Model\SaveHandlerPool">
        <arguments>
            <argument name="handlers" xsi:type="array">
                <item name="defaultRole" xsi:type="object">\Magento\Company\Model\SaveHandler\DefaultRole</item>
                <item name="superUser" xsi:type="object">\Magento\Company\Model\SaveHandler\SuperUser</item>
                <item name="salesRepresentative" xsi:type="object">\Magento\Company\Model\SaveHandler\SalesRepresentative</item>
                <item name="companyStatus" xsi:type="object">\Magento\Company\Model\SaveHandler\CompanyStatus</item>
                <item name="customerGroup" xsi:type="object">\Magento\Company\Model\SaveHandler\CustomerGroup</item>
            </argument>
        </arguments>
    </type>
```
`Magento\Company\Model\SaveHandler\CustomerGroup::execute`
```php
        if (!$initialCompany->getId() || $initialCompany->getCustomerGroupId() != $company->getCustomerGroupId()) {
            $customerIds = $this->customerResource->getCustomerIdsByCompanyId($company->getId());
            foreach ($customerIds as $customerId) {
                $customer = $this->customerRepository->getById($customerId);
                $customer->setGroupId($company->getCustomerGroupId());
                $this->customerRepository->save($customer);
            }
        }
```
So this appears to be purposely negated in favour of the companies customer group. Despite this however, there is still a misleading message to the end user and this feature should either work or not be there at all.

Since this action is still available as a feature, this _should_ still work to some capacity. That being:
If the customer is a company admin, this should be sufficient enough privileges to change the customer's group + company. Else throw a warning message.

### Magento WebAPI
Additionally, I have observed that it is no longer possible to update a customer's group ID via Web API. This appears to be a result of the request parameter's being reverted/reset in:

`Magento\Customer\Model\Plugin\UpdateCustomer::beforeSave`
```php
        if (!isset($bodyParams['customer']['Id']) && $customerId) {
            if ($customerId === $customerSessionId || $customerSessionId === 0) {
                $customer = $this->getUpdatedCustomer($customerRepository->getById($customerId), $customer);
            }
        }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-11-21 06:17
Hi @portchris,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

<img width="1213" alt="Screenshot 2023-11-20 at 1 25 55 PM" src="https://github.com/magento/magento2/assets/51680745/e35fd53e-a45a-4774-84b6-e0d5e85f339e">


Customer Group field is not editable.


As per the Magento devdocs only one customer group can be assigned to company we cannot change afterwards.please refer this document https://experienceleague.adobe.com/docs/commerce-admin/b2b/companies/account-company-customer-group.html?lang=en.

<img width="953" alt="Screenshot 2023-11-20 at 1 23 46 PM" src="https://github.com/magento/magento2/assets/51680745/e6e9bd91-b578-474b-b5a2-bf3c1f2b4f4b">


Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-05 10:36
Hi @portchris,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38187#issuecomment-1820305808 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by portchris** [comment] 2023-12-05 14:15
Hey @engcom-Bravo 

If that's the case then perhaps the Mass Action here should be better validated:
![image](https://github.com/magento/magento2/assets/6716849/0f64e511-428f-44e3-baa1-d867a7062549)

Because at the moment what's happening is a success message but nothing happens. It appears as a bug. 

[My patch (above)](https://github.com/magento/magento2/issues/38187#issuecomment-1812693741) By the way accounts for this and throws a warning if the customer is NOT a company admin.

**Comment by engcom-Bravo** [comment] 2024-01-15 08:16
Hi @portchris,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.



![Screenshot from 2024-01-15 11-26-24](https://github.com/magento/magento2/assets/51680745/0cd75c84-2466-4f6e-934c-ade0e4e1f8e3)



Mass action is working fine after success message appears for Assign a Customer Group the selected records has been changed for appropriate Group.

Could you please check the issue in Latest Magento 2.4-develop instance and please let us know if we are missing anything.

Thanks.

**Comment by portchris** [comment] 2024-01-15 12:04
Don't forget to install B2B module:

```bash 
 composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition .
    composer require magento/extension-b2b smile/elasticsuite
    composer update --lock
```

**Comment by engcom-Bravo** [comment] 2024-01-16 10:02
Hi @portchris,

Thanks for your update.

We have verified the issue Magento 2.4-develop instance with Enterprise edition with b2b modules and the issue is not reproducible,Could you please check the issue in Latest 2.4-develop instance with EE edition.

It is recommended to verify the issue in Magento 2.4-develop instance and let us know if we are missing anything.

Thanks

**Comment by engcom-Bravo** [comment] 2024-01-29 04:08
Hi @portchris,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-01-29 04:08 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
