### ISSUE TITLE
404 Error if create a shipment for order from Admin Panel using IE11 

### ISSUE THREAD

**Issue by honzakadlec** [magento/magento2#26551] opened 2020-01-27 13:20 UTC
### Preconditions (*)

1. Magento version  2.3.3 | `2.4-develop`
2. browser IE11

### Steps to reproduce (*)

1. In backend, go to order detail and ship it
2. it displayed the following error on IE11: https://screenshots.dbhq.tech/tracey/20-01-22-15-53-17.png

### Expected result (*)

1. Order shipment is created and succesfull message is shown
2.

### Actual result (*)

1. 404 page is shown with this:
2. https://screenshots.dbhq.tech/tracey/20-01-22-15-53-17.png

**Comment by krishprakash** [comment] 2020-01-28 04:45
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-28 04:45
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-28 04:46
Hi @krishprakash, here is your [Magento instance](https://i-26551-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26551-2-4-develop.instances.magento-community.engineering/admin_6f14](https://i-26551-2-4-develop.instances.magento-community.engineering/admin_6f14)
Login: `034915f7` Password: `3d2dd1da129c`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-01-28 04:58
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30842` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-01-28 04:58
Reproduced on latest instance:
![image](https://user-images.githubusercontent.com/46617848/73236587-ea5d6a80-41b8-11ea-9932-e2955e5cae16.png)

**Comment by sdzhepa** [comment] 2020-06-22 19:38
Hello @honzakadlec 
fyi: @dasharath-wagento @krishprakash 

The issue has been reviewed and triaged with Magento Product Manager.
Was decided to reject/close this issue because Magento stops supporting IE11
- [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements_browsers.html)

**Closed as completed by sdzhepa** 2020-06-22 19:38 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Progress: dev in progress, Triage: Done, Reported on 2.3.3
