### ISSUE TITLE
Adding unique root url for each store view in magento 2 is breaking the page

### ISSUE THREAD

**Issue by sateesh285** [magento/magento2#39158] opened 2024-09-12 05:55 UTC
### Preconditions and environment

- Magento version : 2.4.6
- When we are turning on Add Store Code to Urls to NO and adding unique url for each store view.
Eg We have english and arabic view store so we are trying to add /en/  to English store view and for arabic /ar/ to Arabic store view.

After opening the apge it is started giving error in browser and page is not loading proerly.

### Steps to reproduce

We have english and arabic view store so we are trying to add /en/  to English store view and for arabic /ar/ to Arabic store view.

After opening the apge it is started giving error in browser and page is not loading proerly.

![image](https://github.com/user-attachments/assets/00647fc4-419e-452f-98a5-24f8187c05ca)

### Expected result

Page should load properly after setting unique url for each store view.

### Actual result

Page is not loading properly after setting unique url for each store view.

### Release note

![image](https://github.com/user-attachments/assets/193a6730-8af3-47c6-ae71-1d81a96dd66c)
![image](https://github.com/user-attachments/assets/c799c0b5-ae74-4146-97cd-0da96952beee)
![image](https://github.com/user-attachments/assets/114ac934-4889-4370-bc73-17d894db4967)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-13 06:51
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-17 07:16
Hi @sateesh285,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screnshots.

<img width="1434" alt="Screenshot 2024-09-17 at 12 09 55" src="https://github.com/user-attachments/assets/1da2b8dc-e190-433c-8d4a-bed5142cf892">



<img width="1434" alt="Screenshot 2024-09-17 at 12 10 02" src="https://github.com/user-attachments/assets/09b8cbdf-17ba-4651-ac76-e7116c098ecb">


We are able to add the unique store codes for both store view and able to access successfully.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-30 05:48
Hi @sateesh285,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-09-30 05:48 UTC
Labels: Issue: needs update, Reported on 2.4.6
