### ISSUE TITLE
Results not paginated after upgrading to Magento 2.3.4

### ISSUE THREAD

**Issue by christianbookpwood** [magento/magento2#26578] opened 2020-01-29 13:35 UTC
### Preconditions (*)

Magento 2.3.4, PHP 7.3.13, Apache 2.4.6, CentOS 7.3.1611

### Steps to reproduce (*)

1. Install and configure Magento 2.3.3.
2. Configure a product catalog with greater than 24 products.
3. Configure paging controls to limit to 24 products per page for grid, 10 products per page for listing.
4. Upgrade Magento to 2.3.4.
5. View product listing.

### Expected result (*)

1. Product listing displays, limited to number of products set in pagination controls.

### Actual result (*)

1. Full product listing is displayed without pagination.

**Comment by christianbookpwood** [comment] 2020-01-29 13:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-29 13:46
Hi @christianbookpwood. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-29 13:46
Hi @christianbookpwood, here is your [Magento instance](https://i-26578-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26578-2-4-develop.instances.magento-community.engineering/admin_3774](https://i-26578-2-4-develop.instances.magento-community.engineering/admin_3774)
Login: `53ea486d` Password: `07f8867ba29a`
Instance will be terminated in up to 3 hours.

**Comment by christianbookpwood** [comment] 2020-01-29 13:47
> Hi @christianbookpwood, here is your [Magento instance](https://i-26578-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-26578-2-4-develop.instances.magento-community.engineering/admin_3774
> Login: `53ea486d` Password: `07f8867ba29a`
> Instance will be terminated in up to 3 hours.

I receive the following error when I try to access the admin:

Forbidden
You don't have permission to access this resource.

**Comment by christianbookpwood** [comment] 2020-01-29 15:14
> Hi @christianbookpwood, here is your [Magento instance](https://i-26578-2-4-develop.instances.magento-community.engineering).
> Admin access: https://i-26578-2-4-develop.instances.magento-community.engineering/admin_3774
> Login: `53ea486d` Password: `07f8867ba29a`
> Instance will be terminated in up to 3 hours.

There are a couple of issues that prevent me from reproducing on this instance:

1. The instance is running Magento 2.4-devel, but my issue occurs in Magento 2.3.3.
2. I need to be able to add multiple products to the catalog and render them on a page, in order to test pagination of the product listing. I was able to add multiple products, but they are not showing up in the product listing which I have added to the homepage. I believe this is because the indexers are invalid and the Magento cron jobs are not running.

**Comment by engcom-Bravo** [comment] 2020-01-31 15:30
Hello @christianbookpwood 

Thank you for your report.

Unfortunately, we are not able to reproduce this issue. After the upgrade, the listing remained 10, and only 10 products are displayed
![10_per page](https://user-images.githubusercontent.com/51680745/73551031-53114500-444e-11ea-8ebc-eb208ad7eb15.png)

Can you please attach a screenshot with your settings from _Stores - Configuration Catalog - Catalog - Storefront_ like this example?
![storefront](https://user-images.githubusercontent.com/51680745/73551563-48a37b00-444f-11ea-8c7e-c7e6e52ca3a6.png)

Thank you in advance

**Comment by christianbookpwood** [comment] 2020-01-31 17:33
> Hello @christianbookpwood
> 
> Thank you for your report.
> 
> Unfortunately, we are not able to reproduce this issue. After the upgrade, the listing remained 10, and only 10 products are displayed
> ![10_per page](https://user-images.githubusercontent.com/51680745/73551031-53114500-444e-11ea-8ebc-eb208ad7eb15.png)
> 
> Can you please attach a screenshot with your settings from _Stores - Configuration Catalog - Catalog - Storefront_ like this example?
> ![storefront](https://user-images.githubusercontent.com/51680745/73551563-48a37b00-444f-11ea-8c7e-c7e6e52ca3a6.png)
> 
> Thank you in advance

Unfortunately I cannot send you a screenshot from 2.3.4, as we have since downgraded to Magento 2.3.3 which has fixed the issue for us. Would a screenshot from 2.3.3 be of any use?

**Comment by engcom-Bravo** [comment] 2020-02-03 08:11
Hello @christianbookpwood 

Thank you for the response

Yes, please attach a screenshot from 2.3.3. We want to see the settings before the upgrade. 

Thank you

**Comment by christianbookpwood** [comment] 2020-02-03 16:27
> Hello @christianbookpwood
> 
> Thank you for the response
> 
> Yes, please attach a screenshot from 2.3.3. We want to see the settings before the upgrade.
> 
> Thank you

Here you go:

![storefront config](https://user-images.githubusercontent.com/48963551/73670933-14f76980-4678-11ea-949e-3c0abde235ae.png)

**Comment by engcom-Bravo** [comment] 2020-02-04 10:52
@christianbookpwood 

Unfortunately, we are not able to reproduce this issue with the provided settings. On product listing, still, 10 products are displayed, not all the products. And 24 on Grid

We noticed that you are using _Bestseller_ sorting. There is a possibility that this extension is causing the problem. 

Please, try to use one of the defaults sorting options: _Position_, _Product name_, _Price_
![listning](https://user-images.githubusercontent.com/51680745/73738189-ad5f1e00-474c-11ea-8535-1f917c7072c9.png)

If the issue is not reproducible on clean Magento without custom extensions, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)  

Thank you for your collaboration

**Closed as completed** 2020-02-04 10:54 UTC
Labels: Progress: needs update, Issue: Format is valid, Reported on 2.3.3

**Comment by Tezus** [comment] 2020-02-05 10:44
We also fetch the same issue on my development site.  after upgrade 2.3.4 when I open the category list page display all products or when I open second-page use pagination link. second-page display the same products. I think Magento gets the wrong collection.

**Comment by vipin12117** [comment] 2020-02-22 16:29
I am also facing same issue. Can magento tell what changed in collection pagination in 2.2 and 2.3 ?

**Comment by christianbookpwood** [comment] 2020-02-24 16:44
Just FYI, I found that in my case this was fixed when I upgraded the Mirasvit Sphinx Search Ultimate to 1.0.138:

https://mirasvit.com/docs/module-search-ultimate/current/changelog#1-0-138

**Comment by vipin12117** [comment] 2020-02-26 19:15
It is not working in default advance catalog search page. This is magento issue.

**Comment by christianbookpwood** [comment] 2020-02-26 19:38
> It is not working in default advance catalog search page. This is magento issue.

Ah, you're right. I just confirmed it's still happening for me on advanced search results, but not regular search results or category pages.

**Comment by vipin12117** [comment] 2020-02-28 16:25
Please apply this solution

https://support.magento.com/hc/en-us/articles/360035142371-Catalog-pagination-doesn-t-work-when-Elasticsearch-6-x-is-used

**Comment by vipin12117** [comment] 2020-03-04 15:12
see this Magento\CatalogSearch\Model\ResourceModel\Advanced\Collection

function _loadEntities

$currentSearchEngine = $this->_scopeConfig->getValue(self::SEARCH_ENGINE_VALUE_PATH);
        if ($this->_pageSize && $currentSearchEngine === EngineResolver::CATALOG_SEARCH_MYSQL_ENGINE) {
            $this->getSelect()->limitPage($this->getCurPage(), $this->_pageSize);
        }

I removed condition it solved my problems.
