### ISSUE TITLE
cannot switch store view when not using store code in urls

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#25437] opened 2019-11-01 16:45 UTC
### Preconditions (*)
1. Magento 2.3.1
2. 2 store views for example `gr` and `en`
3. Do not use store codes in urls  

### Steps to reproduce (*)
I'm not sure how to reproduce this here but I noticed on two websites that were migrated from Magento 1. I'll add the information I see on the relevant tables and perhaps this can be replicated. 

#### Table `url_rewrite`

| url_rewrite_id | entity_type | entity_id | request_path                   | target_path                  | redirect_type | store_id | description | is_autogenerated | metadata |
|----------------|-------------|-----------|--------------------------------|------------------------------|---------------|----------|-------------|------------------|----------|
| 36652275       | category    | 855       | paragogi-epexergasia-aera.html | catalog/category/view/id/855 | 0             | 6        | NULL        | 1                | NULL     |
| 36771645       | category    | 855       | paragogi-epexergasia-aera.html | catalog/category/view/id/855 | 0             | 2        | NULL        | 1                | NULL     |

#### Table `store`

| store_id | code  | website_id | group_id | name     | sort_order | is_active |
|----------|-------|------------|----------|----------|------------|-----------|
| 0        | admin | 0          | 0        | Admin    | 0          | 1         |
| 2        | gr    | 1          | 1        | Ελληνικά | 1          | 1         |
| 6        | en    | 1          | 1        | English  | 10         | 1         |

The url requested to switch store view from the store view switcher module

    /stores/store/switch/?___from_store=gr&___store=en&uenc=aHR0cHM6Ly93d3cuYWlyYmxvY2suZ3IvP19fX3N0b3JlPWVu

I've been stepping through the code and I can't see why it's failing. In detail on file
`vendor/magento/module-url-rewrite/Model/StoreSwitcher/RewriteUrl.php` I can see that it correctly identifies url_rewrite rule `36652275` and sets redirect url to `paragogi-epexergasia-aera.html` and returns this value. 

Then in file `vendor/magento/module-store/Controller/Store/SwitchAction.php`

it sends this discovered url to line

`$this->getResponse()->setRedirect($redirectUrl);`

Finally when this is executed I find myself in the same page and same store view I was before without any change. The peculiar thing is that if I manually set the url to `/paragogi-epexergasia-aera.html?___store=en` it immediately switches the language correctly by following the same trail of code with the same information. 

I do not see any place in the code where it actually sets the proper store view so I think the frontController is just matching the default store view's matching URL. 

### Expected result (*)
1. Show the proper store view

### Actual result (*)
1. Shows the same store view as before

**Comment by ioweb-gr** [comment] 2019-11-02 08:59
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-02 08:59
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-02 08:59
Hi @ioweb-gr, here is your [Magento instance](https://i-25437-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25437-2-3-develop.instances.magento-community.engineering/admin](https://i-25437-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment] 2019-11-02 09:07
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment] 2019-11-02 09:07
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by ioweb-gr** [comment] 2019-11-05 08:29
@magento give me 2.3.1 instance

**Comment by magento-engcom-team** [comment] 2019-11-05 08:29
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3.1 instance for you

**Comment by engcom-Charlie** [comment] 2019-11-06 10:59
Hello @ioweb-gr 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

If you still faced this issue on 2.3 please create a new Issue. 

I have to close this issue.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-06 10:59 UTC
Labels: Issue: Format is valid
