### ISSUE TITLE
Magento 2.3.2 wrong product url with multiple store views

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#25084] opened 2019-10-16 09:30 UTC
This issue is similar to (not the same as) #16134 which is marked as closed even if the url issue is not fixed:

### Preconditions (*)
- magento 2.3.2 (fresh install) on nginx 1.12.2 and php 7.1.31

### Steps to reproduce (*)
- create two or more store views
- create products programmatically (code instead of backend admin)

### Expected result (*)
- on frontend, url for products should be www.domain.com/url-key-of-product for all store views

### Actual result (*)
- on frontend, only the default store view has the correct url, the other store views all show the /view/id/{product_id}/s/{url-key} url

### Notes
- differently from issue #16134, backend has no issue (checkboxes are all checked, url key fields are correct on all store views)
- cleaning cache (from cli and backend) doesn't solve the issue
- reindex doesn't solve the issue
- using https://github.com/olegkoval/magento2-regenerate_url_rewrites extension works: after I run php bin/magento ok:urlrewrites:regenerate --entity-type=product I can finally see all the correct urls in all the stores
- category urls have issues too: if you create a category programmatically, the category on frontend is visible only in the default store view, while in backend all the other store views misses the url key field entirely. Again running olegkoval extension php bin/magento ok:urlrewrites:regenerate --entity-type=category fixes the problem

**Comment by kingletas** [comment] 2019-10-22 04:29
@LouNik1984 one thing you want to verify is that the product is associated with the other stores and it has generated the URLs. When you see URLs like `catalog/product/view/{id}` it usually means the URL rewrite was not found. Another thing, for the no default store you may start seeing the store __param if you access them from a separate store.

**Comment by LouNik1984** [comment] 2019-10-29 09:02
"one thing you want to verify is that the product is associated with the other stores and it has generated the URLs"

I'm not sure I understand correctly, but when I open the backend I can see that the website is correctly flagged for all store views, so apparently everything is right but if I check the rewrite table in database then the rows corrisponding to the other stores are missing (only the default store is there). Saving the product from backend, clearing cache and reindex doesn't help. Olegkoval works because it adds the missing rows in the rewrite table. 

"When you see URLs like catalog/product/view/{id} it usually means the URL rewrite was not found"

Yes, that's exactly the issue: the urls from additional stores are not written in the rewrite table. Olegkoval extension fixes this by adding the missing record in the database table. 

I did a bunch of tests and I think I understood the issue: 

I usually create the product for all store views and then update the products with only those fields which are store specific (such as description which changes based on store language). Because of this I only add the store_id key on product update. I test the product creation by adding the store_id = 0 and it seems to work: if I create a product specifying store_id = 0 in the data array, then the urls are created for all store views.

**Comment by LouNik1984** [comment] 2019-10-29 11:22
I noticed something else, this time during the update of the product: 

if I try to update a field for a specific store view (eg: the description field on the german store view), the new value is correctly saved but all the "use default value" checkboxes gets unchecked. I think that only the edited field should have the box unchecked

**Comment by engcom-Charlie** [comment] 2019-11-12 13:53
Hello @LouNik1984 

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

**Testing scenario:**

1. Create two or more store views
![image](https://user-images.githubusercontent.com/51680850/68676888-a8cb0500-0563-11ea-82f3-483d2ca6853f.png)

2. create products programmatically (code instead of backend admin)
My code:
![image](https://user-images.githubusercontent.com/51680850/68676958-d152ff00-0563-11ea-9916-a108be4d28d0.png)
3. Check product URL on all store views 

**Result:**
on frontend, URL for product = ` http://magento2pr3.loc/sample-simple-product11132555558885.html` for all store views
**Default store view:**
![image](https://user-images.githubusercontent.com/51680850/68677059-052e2480-0564-11ea-9452-59d727a8570f.png)
**test1:**
![image](https://user-images.githubusercontent.com/51680850/68677101-20992f80-0564-11ea-9275-b965f3c8ae13.png)
**test2:**
![image](https://user-images.githubusercontent.com/51680850/68677138-34449600-0564-11ea-99a2-4759486795f8.png)

**URL Rewrites:**
![image](https://user-images.githubusercontent.com/51680850/68677292-87b6e400-0564-11ea-9b8d-67bb7bcef267.png)

So i have to close this issue. 

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-12 13:53 UTC
Labels: Issue: Format is valid
