### ISSUE TITLE
Issue with bundle product backorder message on cart page

### ISSUE THREAD

**Issue by amitsamsukha** [magento/magento2#12448] opened 2017-11-27 06:15 UTC
### Preconditions

1. 
2. 

### Steps to reproduce

1. Add any bundle product (which have minimum 1 product out of stock ) in cart 
2. Set allow backorder and notify to customer setting in configuration
3. Now go on cart page, you will not see any message for backorder.
4. If you will add first out of stock product in cart then will add bundle product which have same out of stock product then you will see message on cart page with bundle product.
### Expected result

1. you must see backorder message on cart page because you have out of stock product in bundle product.

**Comment by magento-engcom-team** [comment] 2017-11-27 10:15
@amitsamsukha, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-27 10:16 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
