### ISSUE TITLE
$block->escapeHtml doesn't create valid json

### ISSUE THREAD

**Issue by pserrer** [magento/magento2#17467] opened 2018-08-09 13:42 UTC
The main problem is inside the file module-catalog/view/frontend/templates/product/breadcrumbs.phtml, but I guess, there are many other files, which have this as well.

    "product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>"

In our example, the product name contains a tab character, which results in

    "product": "Product	Name"

The javascript frontend now tries to parse this and complains about an unexpected token. A `json_encode` around `escapeHtml` should solve the issue, but I'm unsure, if this results in double encoded strings for some cases.

### Preconditions
1. Magento 2.2.5
2. There are no preconditions - this should happen on every instance..

### Steps to reproduce
1. Create a product with invalid chars inside the name (i.e. chr(9) - Tab)
2. View the product in the frontend

### Expected result
Valid json string generated

### Actual result
Json string contains invalid characters

**Comment by magento-engcom-team** [comment] 2018-08-09 13:42
Hi @pserrer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@pserrer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by pserrer** [comment] 2018-08-09 13:43
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-08-09 13:44
Hi @pserrer. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-08-09 13:44
Hi @pserrer, here is your [Magento instance](https://i-17467-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17467-2-2-5.engcom.dev.magento.com/admin](https://i-17467-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by pserrer** [comment] 2018-08-09 14:03
@magento-engcom-team I was able to reproduce the issue on vanilla Magento instance

**Comment by orlangur** [comment] 2018-08-09 14:29
@pserrer is there any use for tab character in product name? Workaround like https://stackoverflow.com/a/34486456 looks a bit overkilling to me.

**Comment by orlangur** [comment] 2018-08-09 14:49
@pserrer this is already fixed in `2.2-develop` https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/frontend/templates/product/breadcrumbs.phtml#L10 and will be released in `2.2.6`.

**Closed as completed by orlangur** 2018-08-09 14:49 UTC
Labels: Issue: Format is valid
