### ISSUE TITLE
Price filter does not take into account Special Price

### ISSUE THREAD

**Issue by thdoan** [magento/magento2#9505] opened 2017-05-04 10:52 UTC
### Preconditions

1. Magento 2.1.5

### Steps to reproduce

1. Go to http://magento2-demo.nexcess.net/men/bottoms-men.html
2. Filter by $20.00 - $29.99

### Expected result

1. The Caesar Warm-Up Pant (on sale for $28.00) should be returned by the filter.

### Actual result

1. Caesar Warm-Up Pant is not displayed.

**Comment by niranjanleanswift** [comment] 2017-05-17 08:33
It is still existing the 2.1.6 version too

**Comment by angelo983** [comment] 2017-06-20 10:44
It is still existing in the 2.1.7 version too

**Comment by veloraven** [comment] 2017-06-22 13:29
@thdoan please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by angelo983** [comment] 2017-06-26 17:11
### Preconditions


1. Magento 2.1.7

### Steps to reproduce

1. Default Magento2 installation with sample data
2. Apply rule price to configurable products

### Expected result
1. Filtering by price I see products in the range with special price

### Actual result
1. Filtering by price I see products in the range of the original price

**Comment by IlnitskiyArtem** [comment] 2017-07-04 10:16
@thdoan, Thanks for reporting this issue. 
We've created internal ticket MAGETWO-70446 to address this issue.

**Comment by AlexanderHuyghebaert** [comment] 2017-09-05 22:56
Is there already an update or patch for this? Still happens in 2.1.7

**Comment by magento-engcom-team** [comment] 2017-09-29 14:30
@thdoan, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-29 14:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by AlexanderHuyghebaert** [comment] 2017-09-29 14:36
And can you say where it is fixed? Because I won't upgrade anymore because each time everything is broken.

**Comment by AlexanderHuyghebaert** [comment] 2017-10-02 07:13
@magento-engcom-team : Can you say in which files this has been fixed?

**Comment by yosefkurniawan** [comment] 2017-10-06 07:24
hi, I am also looking for a solution on this. Is there any patch that we can apply on Magento version 2.1.x without upgrading to 2.2.0. ?

**Comment by AlexanderHuyghebaert** [comment] 2017-10-10 09:23
@magento-engcom-team : can you let us know where this has been fixed? Closing without reaction or helping people on 2.1.x is not what we want. It seems that you close all issues with saying: it's fixed in 2.2.x ...

**Comment by NagarajuKasa** [comment] 2017-12-06 10:18
@AlexanderHuyghebaert

Please let me know whether this issue has been fixed? since i am using magento 2 version 2.1.7 i am also looking for the solution api level. please help me

thanks

**Comment by AlexanderHuyghebaert** [comment] 2017-12-08 00:10
Since Magento does not support a fix, I made a fix myself. I've created cronjob that checks the prices of the child products and sets the final price in the index table

**Comment by robmacecs** [comment] 2018-02-19 15:51
Any information on where this fix was applied? Currently on M2.1.10 and have the exact same issue.

**Comment by CrowlaraZ** [comment] 2018-08-02 11:34
@magento-engcom-team Can you let us know which files this has been fixed? I am using 2.1.7, I cant upgrade, give some info for the files so i can fix them

**Comment by CrowlaraZ** [comment] 2018-08-23 10:37
@magento-engcom-team any help please?

**Comment by CrowlaraZ** [comment] 2018-08-27 07:07
@magento-engcom-team tnx for the support. kappa
