### ISSUE TITLE
media not restored from db when accessing images directly

### ISSUE THREAD

**Issue by markus2810** [magento/magento2#8065] opened 2017-01-06 18:24 UTC
### Preconditions

1. Setup media files to be stored in a Database
2. Press Synchronize and wait
3. Check if media db storage is working by uploading a file from wysiwyg editor e.g. home.jpg and add it to a page

### Steps to reproduce

1. Delete the file pub/media/wysiwyg/home.jpg
2. File is not displayed on the page anymore (verified that file exists in database
3. domain.com/pub/media/wysiwyg/home.jpg is returning 404

### Expected result

1. File is displayed correctly. Downloaded from database.

### Actual result

When I go over content->edit page->insert image. The file is loaded from the db and placed under ub/media/wysiwyg/home.jpg on the file system. After that, the direct access works again. I would expect the same load from db mechanism when the file is access directly using the url.

Am I missing something? Is this known issue?

magento version is 2.1.2

**Comment by davidwindell** [comment] 2017-01-16 11:08
https://github.com/magento/magento2/issues/5872

**Comment by veloraven** [comment] 2017-07-05 12:04
I'm closing this issue as a duplicate of #5872.
Internal ticket MAGETWO-56436 already exists

**Closed as completed by veloraven** 2017-07-05 12:04 UTC
Labels: bug report, Component: Catalog
