### ISSUE TITLE
cannot search orders

### ISSUE THREAD

**Issue by jadebaileywowcher** [magento/magento2#33552] opened 2021-07-21 11:23 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/87760355/126481078-24c25909-0cd0-45c1-81bc-8dfe44b37b0c.png)
2. i expect to be able to search for an order or an email and it wont allow me

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/87760355/126481113-9fbe47bc-290b-4756-aa28-07654be3e418.png)
2. when i click on sales, then orders, a pop up appears saying attention Something went wrong. and then i click ok, it states in a red banner Something went wrong with processing the default view and we have restored the filter to its original state.
and then spins continually not allowing me to search

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-22 05:48
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible at our end.
Steps performed:
Admin -> Sales -> Orders -> Search using Order ID -> No issue. Search Results are displayed as expected:
![image](https://user-images.githubusercontent.com/60198231/126594795-0ae18f7b-35f0-4909-a112-74ed79046f2c.png)
@jadebaileywowcher , Kindly check the issue on latest Magento version/2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-05 10:18
@jadebaileywowcher, We are closing this issue as there has been no latest update on the same.
Thank you

**Closed as completed by engcom-November** 2021-08-05 10:18 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
