### ISSUE TITLE
Custom created attributes unable to assign the parent product.

### ISSUE THREAD

**Issue by praveen-chelumalla** [magento/magento2#16525] opened 2018-07-04 09:09 UTC
### Description

The selected child products are unable to display in parent product means when we are creating a configurable product while we select attribute and then selecting an option, then generate simple products till now not any issues but after save the product price will blank and 0 simple products can display.

### Sample Code

Create Attribute : 

```
`$eavSetup->addAttribute(
                \Magento\Catalog\Model\Product::ENTITY,
                'primary_material',
                [
                    'group' => 'General',
                    'type' => 'varchar',
                    'backend' => '',
                    'frontend' => '',
                    'label' => 'Primary Material',
                    'input' => 'select',
                    'class' => 'primary_material',
                    'source' => '<Company Name>\Iframe\Ui\Component\Product\Iframe',
                    'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_WEBSITE,
                    'visible' => true,
                    'required' => true,
                    'user_defined' => true,
                    'default' => '',
                    'searchable' => false,
                    'filterable' => false,
                    'comparable' => false,
                    'visible_on_front' => false,
                    'used_in_product_listing' => true,
                    'unique' => false,
                    'apply_to' => ''
                ]
            );`

```
Option Source Model : 

```
`$this->_options = [
            ['label'=>'Sterling Silver - High Polished & Yellow Gold Plated', 'value'=>'SSHPYGP'],
            ['label'=>'Sterling Silver - High Polished & Rose Gold Plated', 'value'=>'SSHPRGP'],
            ['label'=>'Sterling Silver - High Polished & Rhodium Plated', 'value'=>'SSHPRP'],
            ['label'=>'Sterling Silver - High Polished & Black Rhodium Plated', 'value'=>'SSHPBRP'],
            ['label'=>'Sterling Silver - High Polished & Black Oxydized', 'value'=>'SSHPBO'],
            ['label'=>'Brass - High Polished & Yellow Gold Plated', 'value'=>'BRHPYGP'],
            ['label'=>'Brass - High Polished & Rose Gold Plated', 'value'=>'BRHPRGP'],
            ['label'=>'Brass - High Polished & Rhodium Plated', 'value'=>'BRHPRP'],
            ['label'=>'Brass - High Polished & Black Rhodium Plated', 'value'=>'BRHPBRP']
        ];`

```
### Preconditions

1. Magento CE 2.2.4 without sample data is installed.
2. This issue is available in a Magento 2.2.4, Magento 2.2.5 version.

### Steps to reproduce

1. Created one module to create attributes with using setup data.
2. Attribute options added to the source model.
3. Created one configurable product along with select custom attribute and with options and generate products and save.

### Note

While we creating attribute options in source model, please use value as a string not a numeric. 
It's working perfectly in Magento CE 2.2.3 Version.

### Expected result

![expected result](https://user-images.githubusercontent.com/32830727/42267772-8fe6655a-7f97-11e8-8418-bc3cad935881.png)

### Actual result

![actual resukt](https://user-images.githubusercontent.com/32830727/42267793-9cc7ac52-7f97-11e8-8486-b506b8e5ef8f.png)

**Comment by magento-engcom-team** [comment] 2018-07-04 09:09
Hi @praveen-chelumalla. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@praveen-chelumalla do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by paragpadsumbiya** [comment] 2018-07-04 09:45
@praveen-chelumalla Have you assign your custom attribute to any attribute set as at time of Product create we select attribute set and based on that attributes display .

**Comment by praveen-chelumalla** [comment] 2018-07-04 11:03
Yes assigned default attribute set.

**Comment by topranavp** [comment] 2018-07-16 07:11
@magento-engcom-team , Same here, Can able to reproduce the issue in V2.2.4 and V2.2.5. While creating custom drop-down attribute programmatically,  I am able to generate simple products of configurable which having alphabetic values, 
E.G.
$this->_options = [
            ['label'=>'First Option', 'value'=>'FIROPT'],
            ['label'=>'Second Option', 'value'=>'SECOPT'],

But not able to create product when we are having alphanumeric values.

E.g.
$this->_options = [
            ['label'=>'First Option', 'value'=>'1OPT'],
            ['label'=>'Second Option', 'value'=>'2OPT'],


in setup script sorce file path. Attaching files herewith for your reference.


[Setup.zip](https://github.com/magento/magento2/files/2196734/Setup.zip)

**Comment by engcom-backlog-nickolas** [comment] 2018-07-18 13:34
Hello @praveen-chelumalla, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-09-07 15:07
Hi @praveen-chelumalla 

Fix for this issue is now expected to be delivered with the upcoming patch 2.2.6.
For now you may use the following commits for reference: https://github.com/magento/magento2/search?q=MAGETWO-93668&type=Commits

Thanks

**Closed as completed by magento-engcom-team** 2018-09-07 15:07 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is valid, Component: ConfigurableProduct

**Comment by praveen-chelumalla** [comment] 2018-09-10 04:08
@magento-engcom-team Thank you so much to fixing the issue.
