### ISSUE TITLE
Weak validation of allowed Credit Card types on Checkout with Braintree

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#23707] opened 2019-07-15 13:30 UTC
### Preconditions (*)

1. Some physical product with status in stock
2. Braintree is configured this way:

Under **Basic Braintree Settings**
 - Environment: Sandbox
 - Payment Action: Authorize
 - Merchant ID: {{Merchant ID}}
 - Public Key: {{Public Key}}
 - Private Key: {{Private Key}}
 - Enable this Solution: Yes
 - Enable PayPal through Braintree: No
 - Vault Enabled: No

Under **Advanced Braintree Settings**
 - Merchant Account ID: {{Merchant Account ID}}
 - Advanced Fraud Protection: No
 - Debug: No
 - CVV Verification: Yes
 - Credit Card Types: *

Under **Country Specific Settings**
 - Payment from Applicable Countries: Specific Countries
 - Payment from Specific Countries: * except Great Britain
 - Country Specific Credit Card Types:
 - - Australia
 - - - American Express
 - - - Visa
 - - - MasterCard
 - - - Maestro International
 - - China
 - - - China Union Pay
 - - India
 - - - Visa  
3. Customer with Multiple address saved in Address Book
Default Billing Address = Default Shipping Address = Address 1
 - Address 1:
John Doe
Magento
6161 West Centinela Avenue
Culver City, California, 90230
United States
T: +15555555555
 - Address 2:
John Doe
Magento
217, Tower B, Spaze ITech park
Sohna Rd, Sector 49
Gurugram, Haryana, 122018
India
T: +919821745319

### Steps to reproduce (*)

1. Log in as Customer
2. Add product to cart
3. Click "Proceed to Checkout" button in the shopping mini cart
4. In the **Shipping Address** section select
John Doe 
217, Tower B, Spaze ITech Park, Sohna Rd, Sector 49
Gurugram, Haryana 122018
India
+919821745319
by clicking **Ship Here** button
5. Click **Next**button
6. Select **Credit Card (Braintree)**
7. Use `5555555555554444` as Credit Card number, `01/20` as expiration date and `123` as CVV.
8. :heavy_check_mark: Verify that MasterCard was used
9. :heavy_check_mark: Verify that inputs have green borders.
10. Enable **My billing and shipping address are the same**
11. :heavy_check_mark: Verify that MasterCard indication has gone
12. :x: Verify that inputs have red borders.
13. :x: Verify that message **Please, enter valid Credit Card Number** is present on the page
14. Place order

### Expected result (*)

1. Validation works if the shipping address was changed on checkout step page
2. Cannot place the order. The button **Place Order** is not available 

### Actual result (*)

1. Order can be placed even when you write the card number by hands again and see a validation message **Please, enter valid Credit Card Number**
2. Validation is not sensitive to the state change of the `input[name=billing-address-same-as-shipping]` checkbox

**Comment by magento-engcom-team** [comment] 2019-07-16 08:29
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-07-16 08:31
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18202` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AndyJAllen** [comment] 2019-08-08 19:19
This is also a problem on Payflow Pro... there are master card numbers that it wont recognize; and users cannot check out. Users get message "Please enter a valid credit card type number" when entering valid Mastercard numbers.

**Comment by AndyJAllen** [comment] 2019-08-08 19:59
The file that needs looked at is **credit-card-type.js** in _vendor\magento\module-payment\view\base\web\js\model\credit-card-validation\credit-card-number-validator_

Why is their a colon in the regex for Mastercard?

**Comment by magento-engcom-team** [comment] 2020-11-30 21:47
The report related to technology or functionality that was removed(or not supported) from the Magento code-base.
Or cannot be fixed and delivered in the scope of this public repository.

Examples:
- Removed payment methods. [Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html), [Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445). All questions, issue reports, and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
- Mysql search. Replaced with Elasticsearch 
- Not [Supported browsers](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#supported-browsers)
- Not supported [Operating systems](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html#operating-systems-linux-x86-64)
- Web Wizard install
- Not a bug 
- etc

**Closed as completed by magento-engcom-team** 2020-11-30 21:47 UTC
Labels: Area: Frontend, Issue: Confirmed, Reproduced on 2.3.x, Component: Braintree, Progress: done

**Comment by magento-engcom-team** [comment] 2021-02-24 13:35
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.
