### ISSUE TITLE
Wrong (full-) tax calculation on partial creditmemo (PDF totals)

### ISSUE THREAD

**Issue by lfritsche** [magento/magento2#9929] opened 2017-06-13 08:45 UTC
### Preconditions

1. Magento 2.1.6 (and tested on 2.0.4)
2. PHP 7.0 (and 5.6)
3. Display full tax summary on invoice,order,creditmemo,... -> YES

### Steps to reproduce

1. Creating a partial credit memo
2. Print creditmemo
3. wrong *full* tax calculation
![image](https://user-images.githubusercontent.com/15127451/27073406-054374b8-5024-11e7-92ee-b7a399dfd9ed.png)
Tax calculation is split into the different order taxes (Germany: 7% / 19%)
Correct would be:
Mwst/Tax (19%): 16,48€
reduzierte Mwst/ reduced Tax (7%): - dont display - because creditmemo does not contain any items with 7% tax class.

But instead these two lines are copied from the initial order and not re-calculated on the partial creditmemo.
The inital order contained products of both 7% and 19% tax class.

### Expected result

Mwst/Tax (19%): 16,48€
Mwst/Tax (7%): - dont display

### Actual result

1. tax overview copied from initial order and not re-calculated on creditmemo.

**Comment by fooman** [comment] 2017-06-14 01:38
I believe this https://github.com/magento/magento2/pull/9939 might fix this one

**Comment by lfritsche** [comment] 2017-06-14 08:01
@fooman Hi Kristof,

thank you for your immediate support.
Seems to be exactly what I was looking for.

https://github.com/magento/magento2/pull/9939/commits/ab0f7ef2996d63bac0e520f96140723cc9de92ef

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@lfritsche, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
