### ISSUE TITLE
Cart price rule (discount) is not applied for Purchase Order payment method

### ISSUE THREAD

**Issue by lisouski** [magento/magento2#30971] opened 2020-11-18 16:57 UTC
### Preconditions (*)

1. Magento 2.3.5 - 2.4.1
2. PHP 7.3

### Steps to reproduce (*)

1. Create Cart price rule with condition "If ANY  of these conditions are TRUE : Payment Method  is  Purchase Order"
2. Go to "payment method" step on check out;
3. Select any other payment method, then select "Purchase Order" method - discount (cart price rule) is not applied;

### Expected result (*)

1. Cart price rule (discount) should be applied if payment is "Purchase Order"

### Actual result (*)

1. Discount (cart price rule) is not applied for method "Purchase Order"

**Comment by engcom-Alfa** [comment] 2020-12-07 14:26
Hi @lisouski .

Unfortunately, we are not able to reproduce the issue on clean 2.4-develop. Looks like the problem has been already fixed.

**Manual testing scenario:**

1. Create Cart price rule with condition "If ANY of these conditions are TRUE : Payment Method is Purchase Order"

![Screenshot from 2020-12-07 16-18-54](https://user-images.githubusercontent.com/51679138/101362177-70057880-38a8-11eb-8b78-3351319bacd4.png)

2. Go to the "Payment method" step on checkout;
3. Select any other payment method, then select "Purchase Order" method - discount (cart price rule) is not applied;

**Actual Result:** :heavy_check_mark: Cart price rule (discount) is applied if payment is "Purchase Order"

![Peek 2020-12-07 16-24](https://user-images.githubusercontent.com/51679138/101362446-c7a3e400-38a8-11eb-9f0b-dde16394d37e.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-07 14:26 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5
