### ISSUE TITLE
.fail() and .always() not firing on this.getPlaceOrderDeferredObject() with HTTP 400 Errors

### ISSUE THREAD

**Issue by hopeseekr** [magento/magento2#35878] opened 2022-08-04 15:52 UTC
### Preconditions and environment

- Magento v2.4.3-p2
- Magento v2.4.4

It works fine in Magento v2.4.0 through v2.4.2-p2.

### Steps to reproduce

1. Create a Magento extension.
2. Overload the `placeOrderAction`.
3. Write the following code for `placeOrder`:
```js
    placeOrder: function (data, event) {
        var self = this;

        if (event) {
            event.preventDefault();
        }
        
        $('.s4messages').html('');

        if (this.validate()) {
            this.isPlaceOrderActionAllowed(false);

            this.getPlaceOrderDeferredObject()
                .done(function () { alert('success'); });
                .fail(function () { alert('failure'); });
                .always(function () { alert('always'); });
           }
    }
```

### Expected result

**Expected:** For the `.done()` to fire on success, for `.fail()` to fire if there is an HTTP 400 on the AJAX call, and `.always()` to fire everytime.

### Actual result

**Actual:**
1. `.done()` will always fire when there is no HTTP error status code (4xx, 5xx).
2. `.always()` will fire when there is no HTTP error status code (4xx, 5xx).
3. `fail()` nor `.always()` will never fire when there is an HTTP error status code (4xx, 5xx).

Instead, Magento's own JavaScript explodes with the following error:

```
knockout.js:3054 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at Object.prepend (knockout.js:3054:43)
    at Object.insertAfter (knockout.js:3062:48)
    at ko.utils.setDomNodeChildrenFromArrayMapping (knockout.js:6465:48)
    at Object.ignore (knockout.js:1563:45)
    at setDomNodeChildrenFromArrayMapping (knockout.js:6017:48)
    at ko.subscription._callback (knockout.js:6027:29)
    at Function.notifySubscribers (knockout.js:1401:50)
    at ko.subscription.notifyChanges [as _callback] (knockout.js:1909:60)
    at Function.notifySubscribers (knockout.js:1401:50)
    at Function.valueHasMutated (knockout.js:1645:46)
prepend @ knockout.js:3054
```

*This prevents the order process from happening.* The user has to hard-refresh the page to get to a working shopping cart, but then they are unable to place an order that has a sad path. No error messages are shown to the end-user, becuase the JS process encountered a terminal stop.

### Additional information

Instead, Magento's own JavaScript explodes with the following error:

```
knockout.js:3054 Uncaught TypeError: Cannot read properties of null (reading 'appendChild')
    at Object.prepend (knockout.js:3054:43)
    at Object.insertAfter (knockout.js:3062:48)
    at ko.utils.setDomNodeChildrenFromArrayMapping (knockout.js:6465:48)
    at Object.ignore (knockout.js:1563:45)
    at setDomNodeChildrenFromArrayMapping (knockout.js:6017:48)
    at ko.subscription._callback (knockout.js:6027:29)
    at Function.notifySubscribers (knockout.js:1401:50)
    at ko.subscription.notifyChanges [as _callback] (knockout.js:1909:60)
    at Function.notifySubscribers (knockout.js:1401:50)
    at Function.valueHasMutated (knockout.js:1645:46)
prepend @ knockout.js:3054
```

Upon drilling in, it's because `this.containerNode` is null on line 3054 of knockout.js.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hopeseekr** [comment] 2022-08-04 15:57
@magento give me 2.4-develop instance

**Comment by hopeseekr** [comment] 2022-08-05 12:39
It seems that Braintree, for one instance, has had to reimplement `this.getPlaceOrderDeferredObject()` to get around this problem:

![image](https://user-images.githubusercontent.com/1125541/183078932-b56e525e-5c22-4a5f-9118-a9523495b448.png)

**Comment by hopeseekr** [comment] 2022-08-15 21:27
https://github.com/magento give me 2.4-develop instance

**Comment by hopeseekr** [comment] 2022-08-15 21:27
@magento give me 2.4-develop instance

**Comment by hopeseekr** [comment] 2022-08-15 21:56
@magento give me 2.4-develop instance with extensions shift4/payment:1.1.20

**Comment by engcom-Hotel** [comment] 2022-08-18 13:44
Hello @hopeseekr,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We have made a custom module which has been attached with this comment below.

Let us know if we have missed anything.

[Magz.zip](https://github.com/magento/magento2/files/9374309/Magz.zip)

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-01 06:48
Dear @hopeseekr,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-09-01 06:48 UTC
Labels: Triage: Dev.Experience, Issue: needs update
