### ISSUE TITLE
Ajax Add to Cart not working (product page reloads) with Date / Date & Time / Time options

### ISSUE THREAD

**Issue by stevekem** [magento/magento2#35368] opened 2022-04-25 22:56 UTC
### Preconditions (*)
2.4.3p1
2.4.4
2.4-develop

### Steps to reproduce (*)
- Add any option of Date/Date & Time/Time type to product
- Add product to cart from product page

### Expected result (*)
Product is added to cart using Ajax and page does not reload

### Actual result (*)
Product added to cart NOT using Ajax and page reloads

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by stevekem** [comment] 2022-04-25 22:56
@magento give me 2.4-develop instance

**Comment by stevekem** [comment] 2022-04-26 03:40
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-26 08:49
Hello @stevekem,

Thanks for the reporting and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch and it seems that the behavior is expected. Please let us know if any use case in which this functionality is not working for you.

Thanks

**Comment by stevekem** [comment] 2022-04-26 15:57
@engcom-Hotel I verified the issue is present and reproducible on both 2.4.4 and 2.4-develop versions.

**Comment by stevekem** [comment] 2022-04-26 16:02
@engcom-Hotel If a product has a Date, Date & Time or Time option type assigned to it, when you add product to cart (with one of those options), Ajax does not work (button does not update "Adding....") but rather the product adds to cart I am assuming via POST Method??

**Comment by engcom-Hotel** [comment] 2022-04-27 09:27
Hello @stevekem,

We have rechecked the issue for both the Simple product and the Virtual product with the date/time option. And inspect the request. We found that for both Ajax calls are firing. You can have a look at the below screenshots for reference:

### For Simple Product
![SimpleProduct](https://user-images.githubusercontent.com/51681618/165487103-56439716-e51f-4047-8bf7-1079d6a23d21.jpg)

### For Virtual Product
![VirtualProduct2](https://user-images.githubusercontent.com/51681618/165487652-6196265a-efc7-418e-abde-c9960c041e9a.jpg)

It seems the expected behavior.

Thanks

**Comment by engcom-Hotel** [comment] 2022-04-28 11:30
Hello @stevekem,

Thanks for the reply!

We have again tried to reproduce the issue in Magento 2.4-develop and 2.4.4 but for us, the issue is not reproducible. Please find below the screencast for the reference and let us know if we have missed anything;


https://user-images.githubusercontent.com/51681618/165742769-5d35f2be-326c-4680-ac63-7ed7550da4d8.mov

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-02 10:19
Hello @stevekem,

Thanks for your reply!

We have further investigated the flow for both types of products with or without dates. Please find the below findings at our end:

### For without date

- Below request has been fired to add the product into the cart:
`<domain.com>checkout/cart/add/uenc/aHR0cDovL2xvY2FsLm1hZ2VudG8yY2U4LmNvbS90ZXN0cHJvZHVjdC5odG1s/product/2/`
- This request is returning `200` HTTP status code
- And added the product into the cart without refreshing the page. Please have a look at the below screenshot for reference:
![RequestScreenshot-1](https://user-images.githubusercontent.com/51681618/166213868-e79f84d2-890f-45d4-ad92-d91defcd6481.jpg)

But for the products with date, the behavior is different.

### For with date

- The Same request has been fired for adding the products into the cart
- And after adding the product to the cart, page is reloading with the `302` HTTP status code:
![RequestScreenshot-2](https://user-images.githubusercontent.com/51681618/166217505-c532e6ca-ea22-4248-b85c-3d9122b9faa8.jpg)

But in both cases, products are added to the cart. It seems an expected behavior. 

Please let us know if we have missed anything

Thanks

**Comment by stevekem** [comment] 2022-05-02 13:56
Hello @engcom-Hotel,
Thanks for your reply! Yes that is correct, in both cases the products are adding to cart BUT in case "Product w/date" page is reloading and NOT using Ajax, **this is the problem**.

Page should NOT reload at all in any case when adding product to cart, Ajax should always work.

**Comment by engcom-Hotel** [comment] 2022-05-20 07:28
Dear @stevekem,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-05-20 07:28 UTC
Labels: Issue: needs update, Reported on 2.4.4
