### ISSUE TITLE
I can't install extensions with the extension manager

### ISSUE THREAD

**Issue by Bohorques15** [magento/magento2#25224] opened 2019-10-22 17:01 UTC
### Preconditions (*)

2. Instal Magento 2.3.2
1. Try to install an extension with the extension manager

### Steps to reproduce (*)

1. In the magento admin, enter system > web setup wizard
2. Enter the extension manager, then review and install. select an extension and click to install it

I have looked around at several solutions and have tried the following:

Checked permissions for the /var files
Removed the .update_in_progress.flag and the .maintenance.flag

### Expected result (*)

1. Application successfully installed
2.

### Actual result (*)

1. 
![image](https://user-images.githubusercontent.com/29069397/67310551-fc4db400-f4cb-11e9-94ae-0c1822c53b37.png)

2.

**Comment by engcom-Charlie** [comment] 2019-11-21 11:12
Hello @Bohorques15 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the Magento 2.3.3 by provided steps.

**Testing scenario:**

1. In the Magento admin, enter System > Web Setup Wizard
2. Enter the extension manager, then review and install. select an extension and click to install it

**Result:**
Success(finished):
[Screenshot](https://ibb.co/tDCXVMv)

I can't confirm your issue, probably this issue was fixed. 
So i have to close it.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-21 11:12 UTC
Labels: Issue: Format is valid
