### ISSUE TITLE
Indexation in scheduled mode might loose some ids when indexing

### ISSUE THREAD

**Issue by dudzio12** [magento/magento2#37398] opened 2023-04-19 15:17 UTC
### Preconditions and environment

- Magento version 2.4.* (This bug is very old though)
- Indexes in scheduled mode

### Steps to reproduce

1. Add more than 1000 ids to any _cl table.
2. Run indexer in mview mode, for example by running cron job `indexer_update_all_views`.

### Expected result

All 1000+ ids should be indexed.

### Actual result

Some ids might not be indexed. This is because there is no sort order implemented in both ChangeLogBatchWalker classes logic.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dudzio12** [comment] 2023-04-19 15:17
I'm working on this

**Comment by ihor-sviziev** [comment] 2023-04-19 16:42
I think this is pretty related to https://github.com/magento/magento2/issues/30012 and https://github.com/magento/magento2/issues/37367.

**Comment by dudzio12** [comment] 2023-04-20 07:11
@ihor-sviziev - Not necessarily, this will not fix the issue with duplicated ids added to _cl table. The best way to fix it completely would probably be changing batching responsibility to PHP with array_unique instead of MysQL.

**Comment by engcom-Hotel** [comment] 2023-07-21 08:25
Hello @dudzio12,

Thanks for the report and collaboration!

We tried to reproduce this issue in the 2.4-develop branch and it seems the issue is not reproducible for us. For us we have more than 1000 entries in the `_cl` table and all are indexed.

I agree with @ihor-sviziev, that the issue is related to https://github.com/magento/magento2/issues/30012, and this issue is already confirmed. 

As per my comment here on this issue https://github.com/magento/magento2/issues/30012#issuecomment-1310391317, the SQL query always returns the same `id` to index, due to which indexing for all the records is not happening.

Please let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2023-08-04 05:13
Dear @dudzio12 ,

We have noticed that this issue has not been updated for a long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-08-04 05:13 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update, Reported on 2.4.x
