### ISSUE TITLE
Changing Region (state) in order address loses region

### ISSUE THREAD

**Issue by apsummers** [magento/magento2#12292] opened 2017-11-15 21:56 UTC
Changing the region (state/province) of an address for an order causes the region to be removed. Surprisingly, the changed region appears to be correct if you return to the Order Address Information page, but it is not displayed on the Order page.

### Preconditions

1. Magento 2.1.10
2. PHP 7.0.15

### Steps to reproduce

1. Create an order
2. On the order's page in the Admin UI, click "Edit" next to "Shipping Address"
3. On the Order Address Information page, change the region ("State/Province")
4. Save the address

### Expected result

1. The shipping address should display the new state that was saved

### Actual result

1. The state is gone entirely and only `<City>, <Postal Code>` is displayed

**Comment by magento-engcom-team** [comment] 2017-11-16 09:00
@apsummers, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-11-16 09:00 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
