### ISSUE TITLE
Graphql error for addSimpleProductsToCart request

### ISSUE THREAD

**Issue by nbrouka** [magento/magento2#30652] opened 2020-10-26 11:44 UTC
Hello, 
I am using Magento 2.4.1. Graphql request to add simple product with custom options returns an error.

```
`mutation {
  addSimpleProductsToCart (input: {
    cart_id: "erERkI1zZZJdvHEjsJ35cS9efTGPbioc",
    cart_items: {
      data: {
        sku: "Product1"
        quantity: 1
      },
      customizable_options: [
        {
          id: 1
          value_string: "value1"
        }
      ]
    }
  }) {
    cart {
      items {
        product {
           name
        }
        quantity
        ... on SimpleCartItem {
          customizable_options {
            label
            values {
              value
            }
          }
        }
      }
    }
  }
}`

`{
  "errors": [
    {
      "message": "Could not add the product with SKU Product1 to the shopping cart: Some of the selected options are not currently available.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addSimpleProductsToCart"
      ]
    }
  ],
  "data": {
    "addSimpleProductsToCart": null
  }
}`
```

![graphql-error](https://user-images.githubusercontent.com/15109611/97167697-4e3cb000-1798-11eb-856e-421143d12627.jpg)

What should be the correct request? What should be the request for different types of custom options (field, area, drop-down, radio buttons, checkbox, multiple select, and etc. )?

Also, according to the documentation in version 2.4.1, it is recommended to use addProductsToCart instead of addSimpleProductsToCart. What should be the request with customizable_options for addProductsToCart?

**Comment by shikhamis11** [comment] 2020-11-04 15:16
Hi @nbrouka 

try adding option id value in string format in product mutation like 
if the option title is `value1` and its id is `1` then the mutation should be like 

```
mutation {
  addSimpleProductsToCart (input: {
    cart_id: "erERkI1zZZJdvHEjsJ35cS9efTGPbioc",
    cart_items: {
      data: {
        sku: "Product1"
        quantity: 1
      },
      customizable_options: [
        {
          id: 1
          value_string: "1"
        }
      ]
    }
  }) {
    cart {
      items {
        product {
           name
        }
        quantity
        ... on SimpleCartItem {
          customizable_options {
            label
            values {
              value
            }
          }
        }
      }
    }
  }
}

```

**Comment by mauragcyrus** [comment] 2020-12-23 15:47
We will improve documentation for @doc annotation in the graphql schema file.

**Comment by engcom-Lima** [comment] 2021-06-21 12:29
Hi @nbrouka,

I tried to reproduce the issue at Magento V-2.4-develop. Can't reproduce the issue. Please find the screenshot for your reference .
<img width="1044" alt="Screenshot 2021-06-21 at 5 52 52 PM" src="https://user-images.githubusercontent.com/60198022/122761402-d177bc80-d2b9-11eb-862a-2c01b64a6b16.png">

I would like to suggest below points:
Before adding the product into cart, make sure your product must have customizable_options, if it is not set then you can set from backend admin - Catalog > Products ->Add/Edit -> Customizable Options

Hence closing this ticket. Please feel free to raise the new ticket or reopen the existing ticket with reproducible steps and details with screenshots.
Thanks

**Closed as completed by engcom-Lima** 2021-06-21 12:29 UTC
Labels: Project: GraphQL, Progress: done
