### ISSUE TITLE
Cancelling Invoice make order goes back to processing status

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#25999] opened 2019-12-11 16:49 UTC
Preconditions 
1. Magento version 2.3.3 - Nginx, Varnish, Redis, Php7.2
2. Add product to cart, go to checkout, place order and reach Sucess Page. Order has been placed
3. Open Dev Docs ==>> https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-invoice.html?itm_source=devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=invoice  
4- Read the page until the end and try to apply the following instruction ==>> "Log in to Admin. Click Sales > Invoices. The invoice is displayed in the grid. The status is Paid. Then click Sales > Orders. The status is Processing"
5- Log in to Admin and Click Sales > Invoice. Invoice is not paid because payment gateway canceled the payment. So it is pending. Check **order** status in invoice. Status is canceled. Then use **cancel** button in invoice. Reload. Check order status. Notice that status is **processing** and Invoice is not canceled. 

Expected Result
1. Invoice should be canceled and order status should not change to processing. Everything should be canceled
2. Go to Dev Docs and find an answer. 

Actual Result
1. You have to go back to order and cancel it manually
2. Invoice is pending status
3. Dev Docs didn't provide an answer

**Comment by gcampedelli** [comment] 2019-12-11 16:52
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2019-12-11 16:52
Hi @gcampedelli. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-11 16:53
Hi @gcampedelli, here is your [Magento instance](https://i-25999-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25999-2-4-develop.instances.magento-community.engineering/admin](https://i-25999-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by gcampedelli** [comment] 2019-12-11 17:09
Hi, I figured out the issue by creating and order. The problem is in the fact that Magento creates an invoice in sucessfull payment gateway reponse, which does not exactly mean that the amount has been paid by the customer. It just mean that the payment gateway has receive an intention of payment. Then it goes back to Magento and the magento system automatically create the invoice because it has a sucessfull request which does not mean exactly a sucessful transaction. But for Magento2 native payment methods, Magento2 does not generate automatic invoices. So, that's why engcom team is unable to find the issue. I can't install a payment gateway in the vanilla instance, but I confirm the issue in payment gateway integration.

**Comment by gcampedelli** [comment] 2019-12-11 17:11
You can also check this discussion here - https://github.com/mollie/magento2/issues/48 
In the payment gateeway integration I'm using I see this line => $payment->setIsTransactionPending(true); So, when It has a sucessful request, it sets pending true and that should not generate invoice. Am I wrong? Please, I need a light in it.

**Comment by devchris79** [comment] 2019-12-13 09:58
We use Ebizmarts Sage Pay Suite Pro and transactions will remain in the pending state until payment has been made or if a timed period has elapsed it will become cancelled (with no invoices set against it). Once payment is made it will move to the processing state.
An order can be closed by setting a credit against it from the invoice screen under "credit memo" this can also be made offline to not worry about the payment system.

We are using Magento 2.3.3. Although the sequence above has been true for many iterations of Magento. I would suggest the problem you describe is with the payment extension and not the Magento core.

**Comment by gcampedelli** [comment] 2019-12-13 11:59
I don't use Mollie. I use another payment gateway that acts like this. It creates invoice and it remain pending until gateway send that customer have payed the bill. If it is a credit card and it does not have declined it sends automatically and it back to processing and invoice to paid. But sometimes, for testing purposes we want it to be canceled and it cancel the order status, but invoice remain pending. So we can't cancel the invoice, whether we have to keep it pending or create a credit memo. But, if we press the button to cancel invoice, Magento and not the payment method makes order status goes back to processing. There is nothing in the payment method producing this behavior. So we read the suggestion made by a user of Mollie to try to understand if it could solve the problem, so if it cancel the order before invoice creation, then there is not need of so many manual operations. It happens not only with the payment method we have installed, but if majority of them. It just not happen with Magento Offline Payments because it does not create invoice. But for online payment, even if I'm not calling invoice anywhere, Magento creates an invoice. And it has the exactly behavior you mentioned. It creates an invoice Pending state. If it receives the payment, it changes invoice to Paid. But if it cancel, we have to create a credit memo or as you said "the sequence above has been true for many iterations of Magento". And our clients sometime hire other people  which doesn't understand the need of so many manual operation for a simple cancelation of an invoice (just to remember, at least here, we have to digitally sign the invoice to make it valid and pending state makes it confusing) and complaints are recurrent. And if we don't have an order because it hasn't been payed, why do we need a credit memo? Credit Memo, at least  I understand it like this  it is a document "reducing the amount that the buyer owes to the seller under the terms of an earlier invoice." But if for some reason, like credit analysis and promise of pay the invoice has been generated and payment has not been placed, then order has to be cancelled and invoice as well, there is no need to create a credit memo of the amount seller owns to the buyer. There no money involved.

**Comment by engcom-Echo** [comment] 2019-12-20 11:00
Hello @gcampedelli 

This issue is related to [19462](https://github.com/magento/magento2/pull/19462) and [19433](https://github.com/magento/magento2/pull/19433). 
Any invoiced orders in Magento cannot be canceled, but they can be closed. You need to issue a credit memo, which is refund in Magento.
 Please see the [comment](https://github.com/magento/magento2/pull/19433#issuecomment-443140805). It is possible to cancel the order without creating an invoice.

**Comment by engcom-Echo** [comment] 2019-12-23 09:57
Dev Docs will be updated as soon as possible. 
According to [this](https://github.com/magento/magento2/pull/19433#issuecomment-443140805) comment the issue is invalid and functionality works correctly.

**Closed as completed by engcom-Echo** 2019-12-23 09:57 UTC
Labels: non-issue, Issue: Format is not valid
