### ISSUE TITLE
Undefined Date Columns in Grid Default to current date / time

### ISSUE THREAD

**Issue by tedsalmon** [magento/magento2#12461] opened 2017-11-28 01:09 UTC
### Preconditions
1. Magento 2.0.0 - 2.2.1

### Steps to reproduce
1. Open Admin > Catalog  > Products
2. Under Columns, Select Any Column that has a date value such as "Set Product as new from date"

### Expected result
1. Products with an undefined value should display as a blank date

### Actual result
1. Products with an undefined value default to the current date and time

**Comment by tedsalmon** [comment] 2017-11-28 01:16
I have created a pull request for this issue here. https://github.com/magento/magento2/pull/12462

**Comment by mzeis** [comment] 2017-11-28 21:01
@tedsalmon and me found out this is a duplicate of #9869 so I'm closing this one. It will be fixed in 2.2.2.

**Closed as completed by mzeis** 2017-11-28 21:01 UTC
Labels: duplicate, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid
