### ISSUE TITLE
Tax is calculation wrong

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#36262] opened 2022-10-10 14:36 UTC
### Preconditions and environment

- Magento version 2.4.5

we have following setup:
System configuration: Product price is including TAX
Display Product Prices In Catalog: incl tax.

### Steps to reproduce

Setting: catalog prices entered from Magento Admin are excluding tax
Create product.
create tax zone.
Change setting of the catalog prices entered from Magento Admin to including tax.

### Expected result

product should be visible on frontend with the same price as in backend.

### Actual result

The tax still applies above the backend product price.

you can see information on screenshots:
<img width="844" alt="Schermafbeelding 2022-10-10 om 16 25 10" src="https://user-images.githubusercontent.com/37579149/194888781-3b3c1538-505a-4c7a-bba1-f25b4afe6d0b.png">
<img width="727" alt="Schermafbeelding 2022-10-10 om 16 25 31" src="https://user-images.githubusercontent.com/37579149/194888841-59978bbb-c6f3-41fb-9581-251915dcf70e.png">
<img width="361" alt="Schermafbeelding 2022-10-10 om 16 25 50" src="https://user-images.githubusercontent.com/37579149/194888902-f2196b93-d369-4d9f-9b2e-70a1d8f4775a.png">
<img width="402" alt="Schermafbeelding 2022-10-10 om 16 26 12" src="https://user-images.githubusercontent.com/37579149/194888977-7e5ea4f8-b49b-47e9-9a38-956529ce3a7f.png">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-11 06:55
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-11 11:29
Hi @Naberdz,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances..The price will be change in Frontend only(Including and Excluding) and not for backend for a product after the taxes will be added.Kindly provide more information about Configuration settings it will be helpful for us to proceed further.

Kindly go through with this [doc](https://docs.magento.com/user-guide/configuration/sales/tax.html) about configuration settings.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-25 06:21
Hi @Naberdz,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-25 06:21 UTC
Labels: Issue: needs update, Reported on 2.4.5
