### ISSUE TITLE
Magento 2.4.7-P1 Failing to save changes in some editing (Short Description,Description)fields.

### ISSUE THREAD

**Issue by Skyfly2021** [magento/magento2#38866] opened 2024-06-25 02:02 UTC
### Preconditions and environment

- Magento 2.4.7-P1
- OpenSearch 2.12
- Chrome Version 126.0.6478.127

### Steps to reproduce

When I edit the short Description field and click on save it stays on hold without any prompts

### Expected result

can be saved directly.

### Actual result

Cannot save edited fields
![062501](https://github.com/magento/magento2/assets/53896477/87bb1248-4915-4bf8-9d2a-13c770b2a8ad)
![062502](https://github.com/magento/magento2/assets/53896477/26d91140-e4f0-4976-a1a2-8df276bba646)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-06-28 08:02
Hi @Skyfly2021 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4.7-p1 and 2.4 dev instances but the issue is not reproducible.

We can save the changes in the description fields.

Please refer to the attached screen recording and let us know if we missed anything.

https://github.com/magento/magento2/assets/60198592/d74358b6-5256-4ddb-9821-eec557f2936b

**Comment by Skyfly2021** [comment] 2024-06-28 08:57
You need to repeat this place a few times, after clearing the browser cache or for the first time, he can save, please verify again.

**Comment by engcom-Dash** [comment] 2024-07-01 11:21
Hi @Skyfly2021 

Verified the issue again on Magento 2.4 dev and 2.4.7-p1 still unable to reproduce the issue.

Please take a look at the screenshots I've attached.

Let us know if we missed anything.

In 2.4 dev

<img width="1440" alt="Screenshot 2024-07-01 at 4 39 19 PM" src="https://github.com/magento/magento2/assets/60198592/ad4a1762-43a6-4418-b2a4-57cbf0aa214d">

In 2.4.7-p1

<img width="1440" alt="Screenshot 2024-07-01 at 4 39 09 PM" src="https://github.com/magento/magento2/assets/60198592/8c8e507f-0b66-471a-a37d-b4df6defbbf4">

**Comment by Skyfly2021** [comment] 2024-07-02 03:59
Can you give me the example, I'll test it

**Comment by engcom-Dash** [comment] 2024-07-04 12:20
Hi @Skyfly2021 

You can request 2.4 dev instance from bot by using `@magento give me 2.4-develop instance` and test the issue on that instance.

**Comment by engcom-Dash** [comment] 2024-07-09 06:30
@magento give me 2.4-develop instance

**Comment by Skyfly2021** [comment] 2024-07-09 14:45
> Hi @Skyfly2021
> 
> Admin access: https://36c34a09ea3976ea80d32e9c872bb474.instances-prod.magento-community.engineering/admin_72d0 Login: 1d032d0b Password: 97fad3229ea9
> 
> You can use the above 2.4 dev instance to verify the issue.
> 
> Please let us know if we missed anything.

Cannot be accessed, please see pictures
![070801](https://github.com/magento/magento2/assets/53896477/a6a818d6-2ebc-4f8a-81e8-4d484be4d7fc)

**Comment by Skyfly2021** [comment] 2024-07-09 15:12
> 7a4f5d5c24a2

In this version of Magento ver. dev-develop the above problem does not exist, is there a difference between this version and magento 2.4.7-p1?

**Comment by engcom-Dash** [comment] 2024-07-16 13:06
Hi @Skyfly2021 

The difference between the 2.4 dev instance and 2.4.7-p1 is the dev instance has the latest development code. 

Thanks.

**Comment by engcom-Dash** [comment] 2024-07-18 13:44
Hi @Skyfly2021 

Thanks for reporting and collaboration.

As confirmed in the above comments the issue is not reproducible in 2.4 dev instance so we are closing the issue.

Please feel free to reopen the issue if the issue persists again. 

Thanks.

**Closed as completed by engcom-Dash** 2024-07-18 13:44 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
