### ISSUE TITLE
Duplicated rows in csv export of Report Module

### ISSUE THREAD

**Issue by matias7** [magento/magento2#32799] opened 2021-04-20 20:45 UTC
### Preconditions (*)

1. You need to have several records in any of the Reports grids that have csv export feature
2. This happens in Magento 2.2.x, 2.3.x and also 2.4.x

### Steps to reproduce (*)

1. Log in in the admin dashboard
2. Go to Reports
3. Select any report (aka Abandoned Cart Report)
4. Create a filter (aka date filter)
5. Select Export button in csv

### Expected result (*)

1. The csv generated has the property number of rows corresponded to the number of rows that are displayed in the grid

### Actual result (*)

1. The csv generated has some duplicated rows so, the final result is a larger csv file with duplicated rows

ADDITIONAL: I fix this locally by removing of the file vendor/magento/module-backend/Block/Widget/Grid/Extended.php
this lines 
`$collection->setPageSize($this->_exportPageSize);
$collection->setCurPage($page);`

This is happening in every Export to csv Report

Sorry for my bad english I hope you can understand this issue

**Comment by VZeroCool** [comment] 2021-04-21 05:55
@magento give me 2.3-develop instance

**Comment by engcom-Oscar** [comment] 2021-04-21 08:15
Hi @matias7  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket. May you please provide report csv file with duplicated rows (or screenshot of it) for more details?

**Comment by matias7** [comment] 2021-04-21 11:30
Hi @engcom-Oscar of course, I will give you an example. This issue is difficult to reproduce in a fresh install because the sample-data doesn't include data in this report but look at this:

![image](https://user-images.githubusercontent.com/40697104/115545790-971e7e80-a27a-11eb-9f33-cea685703e73.png)

This report has 1258 rows for the current website (Guatemala) but, if I export this I have this report with duplicated rows:

![report_screenshot](https://user-images.githubusercontent.com/40697104/115546331-48251900-a27b-11eb-80be-b1b58e2d482a.png)

The resulting report has 2516 rows and the most of them are duplicated, the only way to get the original report it's by commenting that lines of code.

**Comment by engcom-Lima** [comment] 2021-06-01 14:52
Hi @matias7 

Unfortunately, Can't reproduce.

I tried export Customer/ Abandoned Carts
<img width="796" alt="Screenshot 2021-06-01 at 7 54 40 PM" src="https://user-images.githubusercontent.com/60198022/120343978-c9f67080-c316-11eb-897a-1c566414ff76.png">
<img width="961" alt="Screenshot 2021-06-01 at 7 59 24 PM" src="https://user-images.githubusercontent.com/60198022/120344067-dd094080-c316-11eb-8a1b-086308dd1b3e.png">

Can you please give me any instance for the same or please provide me reproducible steps.?

**Comment by engcom-Lima** [comment] 2021-06-14 10:49
Hi @matias7 

We did not get any response from your side. Hope your problem will get resolved. Hence closing this ticket.

If you have any issue then you can raise the new ticket. Thanks

**Closed as completed by engcom-Lima** 2021-06-14 10:49 UTC
Labels: Progress: needs update, Issue: needs update
