### ISSUE TITLE
Javascript function text renders in front-end checkout payment section billing-address

### ISSUE THREAD

**Issue by rahulbarotk** [magento/magento2#32668] opened 2021-04-05 10:44 UTC
On checkout payment page  in customer billing address javascript code gets rendered to the page when Google Tag Manager is enabled.

**Preconditions (*)**

- Magento 2.4.2 EE installed
- Google Tag Manager is enabled

**Steps to reproduce (*)**

- Enable and configure Google Tag Manager
- Add a product to cart
- Go to checkout
- Proceed to payment step

**Expected result (*)**
The address has correct street and render as expected

**Actual result (*)**
The address section includes a lot of javascript code text
![Checkout](https://user-images.githubusercontent.com/78153578/113566020-973b3f00-9629-11eb-8aaf-a5f00bcf2501.png)

**Related Issues**
[#26375](https://github.com/magento/magento2/issues/26375)

**Comment by DevAwesomeK** [comment] 2021-04-05 10:46
@magento give me 2.4-develop instance

**Comment by mrtuvn** [comment] 2021-04-05 11:20
You can reproduce issue here when magento only deploy community version! Current i think magento not support deploy commerce edition here

**Comment by ihor-sviziev** [comment] 2021-04-06 06:31
FYI it looks like there were few similar reports in past: https://github.com/magento/magento2/issues/31916 https://github.com/magento/magento2/issues/26375

**Comment by ihor-sviziev** [comment] 2021-04-06 06:33
@mrtuvn you can request b2b or ee version https://devdocs.magento.com/contributor-guide/contributing.html#customize-deployed-instances

**Comment by aboritskiy** [comment] 2021-04-13 08:35
we also having this issue on Magento Cloud 2.4.0 when Google Tag Manager is activated.
It happens for users that have their billing address saved before going to checkout.

**Comment by artttj** [comment] 2021-04-13 09:33
@magento give me 2.4.2 instance with edition ee

**Comment by aboritskiy** [comment] 2021-04-13 16:01
seems there is an official patch for this problem: https://support.magento.com/hc/en-us/articles/360058863531-MDVA-33289-Magento-patch-Javascript-in-address-at-checkout

**Comment by DevAwesomeK** [comment] 2021-04-20 07:04
Patch is not displaying in list of Magento Quality Patches for Magento 2.4.2 EE version. Can anyone please link patch.txt file here. Thanks!

**Comment by artttj** [comment] 2021-04-20 08:01
@DevAwesomeK Please see: 
https://github.com/magento/quality-patches/blob/master/patches/commerce/MDVA-33289_2.4.1.patch
https://github.com/magento/quality-patches/blob/master/patches/os/MDVA-33289_2.4.1.patch

**Comment by DevAwesomeK** [comment] 2021-04-20 08:04
Since patch is already available for this issue, closing the issue.

**Closed as completed** 2021-04-20 08:04 UTC
Labels: Issue: ready for confirmation

**Comment by ihor-sviziev** [comment] 2021-04-20 10:01
Hi @DevAwesomeK,
FYI I created an issue for the missing quality patch for Magento 2.4.2 https://github.com/magento/quality-patches/issues/50
