### ISSUE TITLE
[2.3.x] Layered Navigation does not return "No" option for boolean attributes when using elasticsearch

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#28565] opened 2020-06-05 13:57 UTC
"No" values are not included in layered nav aggregation options when using ElasticSearch as the search engine. This affects storefront and GraphQl scenarios in the same way.

**Steps to reproduce:**
1. Configure ElasticSearch as catalog search engine
2. Create a boolean (yes/no) type product attribute and add it the the default attribute set. Configure so that it will show up in layered navigation.
3. Create several products with a mix of "yes" and "no" for that boolean attribute. Give them a similar name so it's easy to return all of them in a search.
4. Reindex/Clean cache
5. Go to storefront and search using quick search

**Expected:**
Layered nav sidebar should show the attribute with both options (yes/no) and the matching product counts.

**Actual:**
The attribute is in the layered nav sidebar, but it only include the "yes" option even though there are matching "no" products in the search result. (note: When using MySQL search, both options are shown.)

**Comment by danielrenaud** [comment] 2020-06-09 20:38
@gallyamov Before getting too far in to this can you verify the issue still persists. It may have already been resolved in another ticket.

**Comment by gallyamov** [comment] 2020-06-11 10:52
@danielrenaud you are right, I was not able to reproduce this problem.
@nrkapoor please advise how to proceed in cases like this.

**Comment by nrkapoor** [comment] 2020-06-11 12:39
@gallyamov @danielrenaud We can close this issue.

**Comment by danielrenaud** [comment] 2020-06-11 13:58
Issue was already resolved: https://github.com/magento/magento2/commit/d788918891ff02ebdbeb8ca9b6cc1fab756719b9

**Closed as completed by danielrenaud** 2020-06-11 13:58 UTC
Labels: Reproduced on 2.3.x, Issue: Format is not valid, Project: GraphQL, PAP
