### ISSUE TITLE
Issue when setting both Default Billing and Default Shipping addresses

### ISSUE THREAD

**Issue by RegsonDR** [magento/magento2#28815] opened 2020-06-19 16:12 UTC
There seems to be an issue when trying to update a contact and set their default billing and default shipping in a single request with the Magento 2's Admin API. 

### Preconditions (*)
1.Magento ver. 2.2.5

### Steps to reproduce (*)
1. In the parameters, I have set the addresses and used default_billing & default_shipping which have been set to True, but in the api response only one of these default addresses get set. Sometimes the default_billing is set but not the default_shipping or sometimes the default_shipping is set but not the default_billing.
2. To reproduce, try to add 2 addresses into a customer, set one as default billing, and the other as default shipping.  Use the V1/customers/:id endpoint.

### Expected result (*)
1. In the response, the first address should be set to default billing and the 2nd should be set to default shipping.

### Actual result (*)
1. Below is an example of the parameters I have sent the API and the response I have received. Despite setting both default_billing & default_shipping in the parameters, the response only returned the default_shipping. 

Parameters:

`{
  "customer": {
    "id": "4792",
    "email": "lan-test@a2zcloud.eu.com",
    "firstname": "Bradley",
    "lastname": "Duncan",
    "addresses": [
      {
        "telephone": "N/A",
        "firstname": "Bradley",
        "lastname": "Duncan",
        "street": [
          "40 Boughton Rd"
        ],
        "city": "WHYGATE",
        "postcode": "NE48 8SZ",
        "region": {
          "region_code": "wiltshire",
          "region": "wiltshire",
          "region_id": 0
        },
        "region_id": 0,
        "countryId": "GB",
        "default_billing": true
      },
      {
        "telephone": "N/A",
        "firstname": "Bradley",
        "lastname": "Duncan",
        "street": [
          "24 milford street1"
        ],
        "city": "salisbury",
        "postcode": "SP1 2AP",
        "region": {
          "region_code": "wiltshire",
          "region": "wiltshire",
          "region_id": 0
        },
        "region_id": 0,
        "countryId": "GB",
        "default_shipping": true
      }
    ],
    "website_id": 1
  }
}`

Response:

`{
  "id": 4792,
  "group_id": 1,
  "default_shipping": "8667",
  "created_at": "2020-06-04 17:10:39",
  "updated_at": "2020-06-19 09:06:56",
  "created_in": "CW Store View",
  "email": "lan-test@a2zcloud.eu.com",
  "firstname": "Bradley",
  "lastname": "Duncan",
  "gender": 0,
  "store_id": 1,
  "website_id": 1,
  "addresses": [
    {
      "id": 8666,
      "customer_id": 4792,
      "region": {
        "region_code": "wiltshire",
        "region": "wiltshire",
        "region_id": 0
      },
      "region_id": 0,
      "country_id": "GB",
      "street": [
        "40 Boughton Rd"
      ],
      "telephone": "N/A",
      "postcode": "NE48 8SZ",
      "city": "WHYGATE",
      "firstname": "Bradley",
      "lastname": "Duncan"
    },
    {
      "id": 8667,
      "customer_id": 4792,
      "region": {
        "region_code": "wiltshire",
        "region": "wiltshire",
        "region_id": 0
      },
      "region_id": 0,
      "country_id": "GB",
      "street": [
        "24 milford street1"
      ],
      "telephone": "N/A",
      "postcode": "SP1 2AP",
      "city": "salisbury",
      "firstname": "Bradley",
      "lastname": "Duncan",
      "default_shipping": true
    }
  ],
  "disable_auto_group_change": 0,
  "extension_attributes": {
    "is_subscribed": false
  },
  "custom_attributes": [
    {
      "attribute_code": "extait_cookie_categories",
      "value": null
    }
  ]
}`

---
- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-22 04:33
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-22 04:33
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-22 04:34
Hi @swathishs, here is your [Magento instance](https://i-28815-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28815-2-4-develop.instances.magento-community.engineering/admin_1ba6](https://i-28815-2-4-develop.instances.magento-community.engineering/admin_1ba6)
Login: `16fe534e` Password: `df886882b4d0`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-22 06:52
@RegsonDR : The issue is not reproducible in Magento 2.4 develop instance.

Step to reproduce:
1. Create an admin token via rest API 
2. Post -{Baseurl}/rest/{Storecode}/V1/customers
3. Authorization - Bearer Token - Token -{Amin token }

Request;
{ "customer":
    {
        "lastname" : "s",
      "firstname" : "swathish",
      "email" : "swathish0@ziffity.com",
      "store_id": 1,
      "website_id": 1,
       "addresses": [
            {
                "defaultBilling": true,
                "firstname": "swathish",
                "lastname": "s",
                "company": "test",
                "street": [
                 "123 Oak Ave"
                ],
                "city": "City Nine",
                "region_id": 12,
                "region": "New York",
                "postcode": "10755",
                "country_id": "US",
                "telephone": "1234567890"
            },
            {
                "defaultShipping": true,
                "firstname": "test",
                "lastname": "test",
                "company": "test technology",
                "street": [
                "Test Street 10",
                "Tiny House 10"
                ],
                "city": "City Ten",
                "region_id": 12,
                "region": "California",
                "postcode": "91790",
                "country_id": "US",
                "telephone": "1234567890"
            }
        ]
    },
   "password" : "Ziffity@123"
}

Response:
{
    "id": 206,
    "group_id": 1,
    "default_billing": "409",
    "default_shipping": "410",
    "created_at": "2020-06-22 06:43:32",
    "updated_at": "2020-06-22 06:43:33",
    "created_in": "Default Store View",
    "email": "swathish0@ziffity.com",
    "firstname": "swathish",
    "lastname": "s",
    "store_id": 1,
    "website_id": 1,
    "addresses": [
        {
            "id": 409,
            "customer_id": 206,
            "region": {
                "region_code": "CA",
                "region": "California",
                "region_id": 12
            },
            "region_id": 12,
            "country_id": "US",
            "street": [
                "123 Oak Ave"
            ],
            "company": "test",
            "telephone": "1234567890",
            "postcode": "10755",
            "city": "City Nine",
            "firstname": "swathish",
            "lastname": "s",
            "default_billing": true
        },
        {
            "id": 410,
            "customer_id": 206,
            "region": {
                "region_code": "CA",
                "region": "California",
                "region_id": 12
            },
            "region_id": 12,
            "country_id": "US",
            "street": [
                "Test Street 10",
                "Tiny House 10"
            ],
            "company": "test technology",
            "telephone": "1234567890",
            "postcode": "91790",
            "city": "City Ten",
            "firstname": "test",
            "lastname": "test",
            "default_shipping": true
        }
    ],
    "disable_auto_group_change": 0,
    "extension_attributes": {
        "is_subscribed": false
    }
}

Attachments:
![image](https://user-images.githubusercontent.com/58288685/85257019-bb56d680-b482-11ea-95c8-293c32dd36ca.png)

**Comment by RegsonDR** [comment] 2020-06-22 08:21
@swathishs 
Sorry, I just tested this again, this issue only happens when updating a Customer.

Request Method: PUT
Request URL: {Baseurl}/rest/default}/V1/customers/:id
Headers:  {"Content-Type":"application/json","Authorization":"Bearer <TOKEN HERE>"}

**Comment by swathishs** [comment] 2020-06-22 08:42
@RegsonDR : Have tested using the above scenario also. The default shipping address and default billing address are updated correctly on Magento 2.4 develop instance.
1. Api:
![image](https://user-images.githubusercontent.com/58288685/85266809-075d4780-b492-11ea-824d-a5e619f2f27c.png)
2. Admin:
![image](https://user-images.githubusercontent.com/58288685/85266841-13490980-b492-11ea-97d9-5a56ff9a96fb.png)

**Comment by swathishs** [comment] 2020-06-22 08:43
Can you try to put body like this :
{ "customer":
    {
        "lastname" : "s",
      "firstname" : "swathish",
      "email" : "swathish0@ziffity.com",
      "store_id": 1,
      "website_id": 1,
       "addresses": [
            {
                "defaultBilling": true,
                "firstname": "swathi",
                "lastname": "s",
                "company": "ziff",
                "street": [
                 "55663 Oak Ave"
                ],
                "city": "new",
                "region_id": 12,
                "region": "New York",
                "postcode": "2345678",
                "country_id": "US",
                "telephone": "1234567890"
            },
            {
                "defaultShipping": true,
                "firstname": "iiii",
                "lastname": "qwer",
                "company": "test",
                "street": [
                "Street 10",
                "House 10"
                ],
                "city": "City",
                "region_id": 12,
                "region": "California",
                "postcode": "91790",
                "country_id": "US",
                "telephone": "1234567890"
            }
        ]
    },
   "password" : "Ziffity@123"
}

**Comment by RegsonDR** [comment] 2020-06-22 09:15
@swathishs 

The first time I execute this, I get this response:
`{
   "id":4796,
   "group_id":1,
   "created_at":"2020-06-22 08:20:09",
   "updated_at":"2020-06-22 09:12:25",
   "created_in":"CW Store View",
   "email":"lan-testing-5@a2zcloud.eu.com",
   "firstname":"swathish",
   "lastname":"s",
   "store_id":1,
   "website_id":1,
   "addresses":[
      {
         "id":8706,
         "customer_id":4796,
         "region":{
            "region_code":"CA",
            "region":"California",
            "region_id":12
         },
         "region_id":12,
         "country_id":"US",
         "street":[
            "55663 Oak Ave"
         ],
         "company":"ziff",
         "telephone":"1234567890",
         "postcode":"2345678",
         "city":"new",
         "firstname":"swathi",
         "lastname":"s"
      },
      {
         "id":8707,
         "customer_id":4796,
         "region":{
            "region_code":"CA",
            "region":"California",
            "region_id":12
         },
         "region_id":12,
         "country_id":"US",
         "street":[
            "Street 10",
            "House 10"
         ],
         "company":"test",
         "telephone":"1234567890",
         "postcode":"91790",
         "city":"City",
         "firstname":"iiii",
         "lastname":"qwer"
      }
   ],
   "disable_auto_group_change":0,
   "extension_attributes":{
      "is_subscribed":false
   },
   "custom_attributes":[
      {
         "attribute_code":"extait_cookie_categories",
         "value":null
      }
   ]
}`

the 2nd time I get this response:

`{
   "id":4796,
   "group_id":1,
   "default_billing":"8708",
   "default_shipping":"8709",
   "created_at":"2020-06-22 08:20:09",
   "updated_at":"2020-06-22 09:13:44",
   "created_in":"CW Store View",
   "email":"lan-testing-5@a2zcloud.eu.com",
   "firstname":"swathish",
   "lastname":"s",
   "store_id":1,
   "website_id":1,
   "addresses":[
      {
         "id":8708,
         "customer_id":4796,
         "region":{
            "region_code":"CA",
            "region":"California",
            "region_id":12
         },
         "region_id":12,
         "country_id":"US",
         "street":[
            "55663 Oak Ave"
         ],
         "company":"ziff",
         "telephone":"1234567890",
         "postcode":"2345678",
         "city":"new",
         "firstname":"swathi",
         "lastname":"s",
         "default_billing":true
      },
      {
         "id":8709,
         "customer_id":4796,
         "region":{
            "region_code":"CA",
            "region":"California",
            "region_id":12
         },
         "region_id":12,
         "country_id":"US",
         "street":[
            "Street 10",
            "House 10"
         ],
         "company":"test",
         "telephone":"1234567890",
         "postcode":"91790",
         "city":"City",
         "firstname":"iiii",
         "lastname":"qwer",
         "default_shipping":true
      }
   ],
   "disable_auto_group_change":0,
   "extension_attributes":{
      "is_subscribed":false
   },
   "custom_attributes":[
      {
         "attribute_code":"extait_cookie_categories",
         "value":null
      }
   ]
}`

It just goes back and forth between the 2 responses, one with both default_billing and default_shipping and one without both.

**Comment by swathishs** [comment] 2020-06-22 09:45
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-22 09:45
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-22 09:46
Hi @swathishs, here is your [Magento instance](https://i-28815-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28815-2-4-develop.instances.magento-community.engineering/admin_8265](https://i-28815-2-4-develop.instances.magento-community.engineering/admin_8265)
Login: `7986de5b` Password: `6c264568f11b`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-22 09:47
@RegsonDR : Check-in this 2.4 develop instance displayed above

**Comment by RegsonDR** [comment] 2020-06-22 10:22
Hi @swathishs, I've just checked this on the above instance and there are no issues. We are using Magento ver. 2.2.5, is there a way for me to do the same test on another 2.2.5 instance?

**Comment by swathishs** [comment] 2020-06-22 11:02
Hi @RegsonDR : Since the Magento is focusing development efforts on v2.4 development instance. And we are guided to test in 2.4 develop instance and confirm the issue.
If you want you can ask  2.2.5 instances to Magento for testing.

**Comment by swathishs** [comment] 2020-06-22 11:03
@magento give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2020-06-22 11:03
Hi @swathishs. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` and `2.4` release line

**Comment by swathishs** [comment] 2020-06-22 11:05
I think you can get only a 2.3.5-p1 instance and 2.4 instances in this.

Hi @RegsonDR , thank you for your report. According to the contributor's guide, Magento is focusing development efforts on v2.4.
I confirm that issue is not reproducible on the latest 2.4-develop branch.
Hence closing the issue

**Closed as completed** 2020-06-22 11:28 UTC
Labels: Issue: Format is valid, Reported on 2.2.x
