### ISSUE TITLE
Category URL in breadcrump is invalid after changing URL Key with Creating Permanent Redirect for old URL

### ISSUE THREAD

**Issue by jirichmiel** [magento/magento2#37972] opened 2023-09-08 08:16 UTC
### Preconditions and environment

Magento version 2.4.6.
Disabled cache.

### Steps to reproduce

1. Log in to admin panel and go to .
2. Go to Catalog / Categories.
3. Create a new category named **Foo**.
4. Create a new subcategory of **Foo** named **Bar**.
5. On frontend go to address **/foo/bar.html**.
6. There you see category page with breadcrumbs Home > Foo > Bar, where Foo points to **/foo.html** - IT'S CORRECT
7. Go to back to admin Catalog / Categories.
8. Changed Search Engine Optimization / Url Key of category Foo to **foo-new** with **checked** "Create Permanent Redirect for old URL" and save category.
9. On frontend go to new address **/foo-new/bar.html**.
10. There you see category page with breadcrumbs Home > Foo > Bar, where Foo point still to old **/foo.html** - WRONG

### Expected result

Crumb Foo in breadcrumb Home > Foo > Bar should point to new URL **/foo-new.html**. 

### Actual result

Crumb Foo in breadcrumb Home > Foo > Bar points to old  URL **/foo.html**.

### Additional information

I think that root cause is in https://github.com/magento/magento2/blob/05fa3de2e7cd628823b18ed4f6b73ac484d495ff/app/code/Magento/Catalog/Model/Category.php#L613-L618 where is finding seo url for category, but it searches also in redirects (a.k.a old request paths)

May be there should be placed an addtional condition  `UrlRewrite::REDIRECT_TYPE => 0` to filter redirects as it is doing for products, see https://github.com/magento/magento2/blob/05fa3de2e7cd628823b18ed4f6b73ac484d495ff/app/code/Magento/Catalog/Model/Product/Url.php#L148-L153

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-11 09:16
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-11 12:29
Hi @jirichmiel,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Log in to admin panel and go to .
- Go to Catalog / Categories.
- Create a new category named Foo.
- Create a new subcategory of Foo named Bar.
- On frontend go to address /foo/bar.html.
- There you see category page with breadcrumbs Home > Foo > Bar, where Foo points to /foo.html - IT'S CORRECT
- Go to back to admin Catalog / Categories.
- Changed Search Engine Optimization / Url Key of category Foo to foo-new with checked "Create Permanent Redirect for old URL" and save category.
- On frontend go to new address /foo-new/bar.html.
- There you see category page with breadcrumbs Home > Foo > Bar, where Foo point still to old /foo.html - WRONG


<img width="1276" alt="Screenshot 2023-09-11 at 2 58 55 PM" src="https://github.com/magento/magento2/assets/51680745/197baf08-0571-4c5c-8ff6-111d3839926c">




<img width="1359" alt="Screenshot 2023-09-11 at 2 59 04 PM" src="https://github.com/magento/magento2/assets/51680745/b563c0c0-6133-44aa-a141-4deadc24d902">


Crumb Foo in breadcrumb Home > Foo > Bar is pointing to new URL /foo-new.html.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-25 06:14
Hi @jirichmiel,

Kindly provide latest update on this comment  https://github.com/magento/magento2/issues/37972#issuecomment-1713781924 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-28 06:11
Hi @jirichmiel,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-28 06:11 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by hostep** [comment] 2023-11-18 12:23
Fix for this: https://github.com/magento/magento2/pull/38153
