### ISSUE TITLE
Export csv download or delete

### ISSUE THREAD

**Issue by SpaceWhite** [magento/magento2#23281] opened 2019-06-16 08:42 UTC
### Preconditions (*)
1. 2.3-develop

### Steps to reproduce (*)
1. Admin  -> System -> Data Transfer -> Export
2. Select product entity type (eg. Customer Addresses)
3. Click continue
4. Request is queued and page refresh
5. Scroll down a little bit and table with csv files will appear
6. Action -> Download or Delete on one of the file

### Expected result (*)
1. Admin are able to download or delete file when action -> download or delete is clicked

### Actual result (*)
1. It redirects to dashboard index page

**Comment by SpaceWhite** [comment] 2019-06-16 09:04
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-16 09:04
Hi @SpaceWhite. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-16 09:05
Hi @SpaceWhite, here is your [Magento instance](https://i-23281-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23281-2-3-develop.instances.magento-community.engineering/admin](https://i-23281-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Nazar65** [comment] 2019-06-17 19:32
@SpaceWhite as a workaround you can disable Admin secret key on URL then it works :smile: but actually as far i remember this should be fixed in 2.3-dev.

**Comment by engcom-Bravo** [comment] 2019-06-18 10:46
Not relevant for 2.2.

**Comment by magento-engcom-team** [comment] 2019-06-18 10:46
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17566` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by himanshu8dev** [comment] 2019-06-29 07:18
The issue is not reproducing as I have checked in Magento2.3

**Comment by SpaceWhite** [comment] 2019-06-29 14:47
@himanshu8dev The issue could only be reproduced on magento 2.3-develop branch

**Comment by magento-engcom-team** [comment] 2019-07-29 14:28
Hi @SpaceWhite, @geet07. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-17566` was closed as `non-reproducible` in `2.3-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2019-07-29 14:28 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid
