### ISSUE TITLE
The default store cannot be disabled

### ISSUE THREAD

**Issue by cscd98** [magento/magento2#6435] opened 2016-09-01 10:40 UTC
Magento 2.1.1 - Clean Install

Login to Admin - Goto Stores - All Stores. Click on the default store view

Enter a new name for the default store view.

Click on Save.

You get an error message:

```
The default store cannot be disabled
```

I am however not disabling it - I am just renaming it.

The status is still "Enabled"

**Comment by sevos1984** [comment] 2016-09-02 09:07
Internal ticket created MAGETWO-57979, thanks for reporting

**Comment by enrico69** [comment] 2016-09-16 15:44
I had the same problem. When I get the message, I noticed that the store was automatically put on "disabled" during the submission. Put it on enabled again and the renaming is correctly done.

**Comment by brideo** [comment] 2017-07-15 03:30
Any updates on this one?

**Comment by krisdante** [comment] 2017-09-17 09:49
I tried to reproduce on develop branch (e649b4cc630dfa638271aebc9efd649c5f4bfca9) and it is not reproducible anymore. Seems to be fixed in newest code.

**Comment by maksek** [comment] 2017-09-17 12:03
@krisdante did you try 2.1.x version?

**Comment by krisdante** [comment] 2017-09-17 12:14
2.1.8 it is the case, just wanted to mention that it is already fixed, so if somebody is planning PR - it makes not much sense.

**Comment by magento-engcom-team** [comment] 2017-09-20 23:08
@craigcarnell, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:08 UTC
Labels: Issue: Ready for Work, bug report, Component: Config, Issue: Format is not valid
