### ISSUE TITLE
Problem with region field

### ISSUE THREAD

**Issue by valibus** [magento/magento2#6590] opened 2016-09-13 09:42 UTC
### Preconditions
1. Magento 2.1 CE on PHP 7
2. In section configuration /general / state options
3. State is required for : Unselect all country. No one should be slected
4. Allow to choose state if it is optional for country : NO

We use this configuration cause we do not need to have region field in our store. We do not need it and it's one more field in form and that cool for the UX and conversion rate.
### Steps to reproduce
1. We had to remove manually the field cause the setup in configuration did not work properly (the field was still mandatory in back office) 
2. Try to confirm an order with an adress without region and you should have this message in front office. It will disapear depending on the order. Sometime if you create a new adress it won't appear. (appear in log files)
### Expected result
1. Be able to confirme order without the bug
### Actual result

`Next Exception: Report ID: webapi-57d7bf41422a0; Message: Recoverable Error: Object of class Magento\Customer\Model\Data\Region could not be converted to string in /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2915 in /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/framework/Webapi/ErrorProcessor.php:...
Stack trace:
#0 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/framework/Webapi/ErrorProcessor.php(...: Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/module-webapi/Controller/Rest.php(21...: Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/var/generation/Magento/Webapi/Controller/Rest/Inter...: Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/ourNameSpace/rec/src/releases/2016-09-13-08-25/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []`

**Comment by sevos1984** [comment] 2016-09-13 14:17
You cannot remove region attribute from magento as other modules dependent on it. Ignoring required setting is known issue https://github.com/magento/magento2/issues/5851

**Comment by sevos1984** [comment] 2016-09-27 14:03
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-27 14:03 UTC
Labels: bug report, Progress: needs update, Component: Framework/Webapi, Component: Customer
