### ISSUE TITLE
When VAT number validation fails by the VIES service, there is no trace about the exception message in the log files

### ISSUE THREAD

**Issue by hostep** [magento/magento2#36065] opened 2022-08-31 11:47 UTC
### Preconditions and environment

- Magento version: any

### Steps to reproduce

Look at the code over here: https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Customer/Model/Vat.php#L214-L218

1. In the code [over here](https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Customer/Model/Vat.php#L47), change the url to https://example.com/taxation_customs/vies/checkVatService.wsdl so we can simulate an unexpected error
2. In the Magento back office, go to Stores > Configuration > General > General > Store Information
3. For the Country field, pick an EU country (like France)
4. For the VAT Number field, enter something random, like 012345
5. Press the Validate VAT Number button
6. Inspect the var/log/exception.log file or system.log file

### Expected result

1. Expect that the exception message is logged somewhere, so that when an exception is occurring, it's easy to find the details in a log file

### Actual result

1. No exception message is being logged

### Additional information

We had a certain shop, where the VAT number validation kept on failing and there was no trace about why it happened, when we tried debugging on our local environment, no issue was found, it only happened on the staging server.

After some debugging directly on the staging server, we figured out that an exception was being thrown by that SoapClient and it was being [catched](https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/Customer/Model/Vat.php#L214-L218), but not logged:
```
javax.xml.rpc.soap.SOAPFaultException: IP_BLOCKED [] []
```

If we would have seen this in some log file, it would have been easier to figure out exactly why the vat number validation failed in our case.

### Release note

Exceptions thrown by the [VIES VAT validation service](https://ec.europa.eu/taxation_customs/vies/#/vat-validation) are now being logged in the `var/log/exception.log` file so it becomes easier to figure out what goes wrong when the validation doesn't work.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-25 06:39
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Hence updating the description with Manual steps to reproduce and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/197700616-14164429-e8a0-46ac-8543-68e9fcc2df95.png)
No error/exception is being logged in the log files.

**Comment by hostep** [comment] 2022-10-26 05:46
Thanks for confirming @engcom-November, note that there is already a PR open to fix this: https://github.com/magento/magento2/pull/36067

**Comment by ihor-sviziev** [comment] 2023-07-17 10:08
The fix for this issue was delivered to 2.4-develop branch in https://github.com/magento/magento2/commit/50b303edae8c26ceb24fc23dcb42b1ed2feb1b76 (changes from https://github.com/magento/magento2/pull/36067)
I'm closing this issue.

**Closed as completed by ihor-sviziev** 2023-07-17 10:08 UTC
Labels: Issue: Confirmed, Component: Framework/Exception, Triage: Dev.Experience, Component: Exception, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Progress: done, Issue: ready for confirmation, Reported on 2.4.x, Area: Framework
