### ISSUE TITLE
Unable to switch to production mode

### ISSUE THREAD

**Issue by baltechies** [magento/magento2#9159] opened 2017-04-07 07:27 UTC
When I trying to switch to production mode on magento version 2.1.5 then its throwing the errors like:

Interception cache generation... 7/7 [============================] 100% 3 mins 306.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content
Something went wrong while deploying static content. See the error log for details.
Command returned non-zero exit code:
`/usr/bin/php -f /opt/bitnami/apps/magento/htdocs/bin/magento setup:static-content:deploy en_US de_DE fr_FR it_IT`
-bash-4.2$ php bin/magento module:status

PHP Fatal error:  Uncaught Error: Class 'Magento\Indexer\Model\Config\Reader' not found in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Indexer...')
#2 /opt/bitnami/apps/magento/htdocs/app/code/Manadev/Core/Registries/ConfigurationReaders.php(32): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Indexer...')
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Manadev\Core\Registries\ConfigurationReaders->__construct(Object(Magento\Framework\ObjectManager\ObjectManager), Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/fram in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

PHP version is 7.0.6

**Comment by baltechies** [comment] 2017-04-07 07:42
I have issue when switching from default mode to Production.
When I trying to switch to production mode on magento version 2.1.5 then its throwing the errors like:

Interception cache generation... 7/7 [============================] 100% 3 mins 306.0 MiB
Generated code and dependency injection configuration successfully.
Compilation complete
Starting deployment of static content
Something went wrong while deploying static content. See the error log for details.
Command returned non-zero exit code:
/usr/bin/php -f /opt/bitnami/apps/magento/htdocs/bin/magento setup:static-content:deploy en_US de_DE fr_FR it_IT


		Incorrect dependency in class Magerips\SocialSharing\Block\SocialSharing in /opt/bitnami/apps/magento/htdocs/app/code/Magerips/SocialSharing/Block/SocialSharing.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 20

Interception cache generation... 7/7 [============================] 100% 3 mins 306.0 MiB
Generated code and dependency injection configuration successfully. [] []
[2017-04-07 06:36:12] main.ERROR: /usr/bin/php -f /opt/bitnami/apps/magento/htdocs/bin/magento setup:static-content:deploy en_US de_DE fr_FR it_IT 2>&1

PHP Fatal error:  Uncaught Error: Class 'Magento\Indexer\Model\Config\Reader' not found in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(88): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Indexer...', Array)
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Indexer...')
#2 /opt/bitnami/apps/magento/htdocs/app/code/Manadev/Core/Registries/ConfigurationReaders.php(32): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Indexer...')
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Manadev\Core\Registries\ConfigurationReaders->__construct(Object(Magento\Framework\ObjectManager\ObjectManager), Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/fram in /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 [] []

PHP version is 7.0.6
Magento version 2.1.5
Note: We have upgraded the magento version fro 2.0.7

**Comment by korostii** [comment] 2017-04-10 08:45
Looks like the Magento\Indexer\Model\Config\Reader doesn't exist anymore in the 2.1.5 codebase, see commit [abdbc941f03e34e0b78df9cfb129c9c0a76aebb4](https://github.com/magento/magento2/commit/abdbc941f03e34e0b78df9cfb129c9c0a76aebb4#diff-b7a8258d21050f32a135bff82e163911) . You must be having outdated code somewhere. 

The trace you provided seems to be incomplete, so it is not clear where this old class name is referenced from. In case it's somewhere in the generated code leftovers, I would suggest clearing `var/di`, `var/generation` and running `php bin/magento setup:di:compile` again.
If that doesn't help, I'd suggest checking 3rd-party and customized code (if you have any).

**Comment by korostii** [comment] 2017-04-10 10:38
Possible duplicate of #6185.

**Comment by fideliocc** [comment] 2017-04-11 16:18
Did you solve the module issue? If you do, try switching to production mode again for results. I have the same behavior and is only possible to switch with `--skip-compilation`. Then deploy the static content, manage permissions at /pub and /var, and site runs, but with wrong classes and design.

#9202

**Comment by magento-engcom-team** [comment] 2017-10-02 12:27
Hi @baltechies 
Looks like some of the third-party extensions you have installed are using class which does not exist in your version. Please refer to linked #9202 for more discussion on this topic.

**Closed as completed by magento-engcom-team** 2017-10-02 12:27 UTC
Labels: Issue: Format is not valid
