### ISSUE TITLE
Checkout Shipping form cache don't get empty [Magento 2.4.2]

### ISSUE THREAD

**Issue by pcies** [magento/magento2#32336] opened 2021-03-02 16:05 UTC
### Preconditions (*)

1. Magento CE 2.4.2 with sample data is installed.
2. Tested on 2.4.0, 2.3.5. Issue propably not reproducible in older versions than 2.4.0.

### Steps to reproduce (*)

1. Add Product to cart
2. Go to checkout
3. Fill shipping form with random data
4. Delete data from Address line 1.
5. delete data from Address line 2.
6. Refresh page.

### Expected result (*)

1. I expect, that after refreshing form, deleted data will not occur on form after refreshing.
2. I expect, that after refreshing page, mage-cache-storage with checkout-data shippingAddressFormData will have empty values.

### Actual result (*)

1. Because of some reason, after filling Address line 1 and deleting it's value, it will break caching of all inputs of this form. 
It is more visible on screenshots below:

2. Filling shipping form: 
![Screenshot from 2021-03-02 16-46-52](https://user-images.githubusercontent.com/78843535/109675419-14314f80-7b78-11eb-834e-c1331ef27ffc.png)
3. Deleting Data from Address, first line 1 , next line 2:
![Screenshot from 2021-03-02 16-49-54](https://user-images.githubusercontent.com/78843535/109675496-257a5c00-7b78-11eb-83b4-c5591b9490f2.png)
4. Deleting Data from Address first line 2, next line 1:
![Screenshot from 2021-03-02 16-50-57](https://user-images.githubusercontent.com/78843535/109675568-375bff00-7b78-11eb-85c3-ae3534a1df15.png)
5. Keep updating Address line 1 on keyup till last letter in input:
![Screenshot from 2021-03-02 16-53-32](https://user-images.githubusercontent.com/78843535/109675623-3f1ba380-7b78-11eb-8557-223badd7e8c8.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-04 10:25
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41161` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gixid192** [comment] 2021-03-08 09:30
I checked and saw that the file is updated based on this PR
https://github.com/magento/magento2/commit/b4ee601db5141316c0d268f83e95f32d4e341162#diff-06f8b0bb867918bd12b29c8adaf25535b2c9606103739e4baba2d74c9b2a482f

I don't know how to find the original PR to read full description about it. But the code is there for a reason, maybe we should ask in the original pr/thread?

**Comment by engcom-Bravo** [comment] 2024-07-15 07:48
Hi @pcies,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1321" alt="Screenshot 2024-07-15 at 13 15 37" src="https://github.com/user-attachments/assets/f853f39b-6feb-4f3b-a655-73eee4ec7c66">


<img width="1321" alt="Screenshot 2024-07-15 at 13 16 06" src="https://github.com/user-attachments/assets/f007b29f-80b1-4309-9c52-3489f6c5259b">




<img width="1321" alt="Screenshot 2024-07-15 at 13 17 16" src="https://github.com/user-attachments/assets/eae815b2-457a-4446-95d1-11a59c58d882">


shippingAddressFormData having empty data after deleting data.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-15 07:48 UTC
Labels: Issue: Confirmed, Component: Cache, Reproduced on 2.4.x, Severity: S3, Priority: P4, Progress: done, Issue: ready for confirmation, Reported on 2.4.2
