### ISSUE TITLE
Cart rules aren't working correctly

### ISSUE THREAD

**Issue by ezequielalba** [magento/magento2#5025] opened 2016-06-14 14:26 UTC
Created a couple of cart price rules, but seems to not work correctly. I reproduced the steps several times, and nothing. Don't know what could be. Anyone had the same issue recently? 

Have Magento 2.0.7 installed in a local environment.

**The rules are:**
"When the total qty of the product is 1"
"When the subtotal of the purchase is greater than 500$"
Then apply a discount of 10%.

No results.

**Comment by cpartica** [comment] 2016-06-21 01:40
creating internal issue MAGETWO-54591

**Comment by tkacheva** [comment] 2016-06-22 09:07
@ezequielalba Is this the condition you have created? 
![cart condition](https://cloud.githubusercontent.com/assets/5603216/16260840/c3bdbc30-3871-11e6-9b49-9c5739a148de.png)

**Comment by ezequielalba** [comment] 2016-06-23 13:16
For cart rule i can't put that condition you have at first, i got this:

![1](https://cloud.githubusercontent.com/assets/14914190/16304384/8a24d75a-392b-11e6-8371-423e11acfbc5.jpg)
![2](https://cloud.githubusercontent.com/assets/14914190/16304383/8a24a154-392b-11e6-941f-45fd51acf30c.jpg)

either way it doesn't seems to work.

**Comment by KrystynaKabannyk** [comment] 2016-06-23 16:45
Hello @ezequielalba, this issue has been fixed in the 2.1.0 Release, that's why I'm closing it. If you any questions or additional information regarding the issue feel free to reopen it or create a new one.

**Comment by KrystynaKabannyk** [comment] 2016-06-24 19:11
Sorry for the confusion, we double checked and unfortunately this issue didn't go to the 2.1.0 release, we are still investigating whether this is a bug, we will update you on this a little bit later.

**Comment by ezequielalba** [comment] 2016-06-24 20:15
Aw, well, let me know any news!

**Comment by tkacheva** [comment] 2016-06-29 13:07
@ezequielalba I can't reproduce the issue with conditions you have on Magento 2.1 
Here is what I have in condition
![shopping10_condition](https://cloud.githubusercontent.com/assets/5603216/16452902/73759886-3e13-11e6-8866-b1fc6e51b6ca.png)
and here is the rule applied:

![shopping10](https://cloud.githubusercontent.com/assets/5603216/16452916/823aa7e4-3e13-11e6-9c3a-14dd75ff009b.png)

Try to upgrade and check if you have the issue. Reopen if so

**Closed as completed by tkacheva** 2016-06-29 13:07 UTC
Labels: Issue: Ready for Work, bug report
