### ISSUE TITLE
Terms and Conditions validation not working on payment method change

### ISSUE THREAD

**Issue by magento2dev** [magento/magento2#22992] opened 2019-05-23 13:28 UTC
The default Magento_CheckoutAgreements module does not display error message for Terms and Condition checkbox even if it's not checked on payment change.

### Preconditions

1. Use Magento 2.2.7

### Steps to reproduce

1. Create a Terms and Conditions entry under Stores > Terms and Conditions and activate them under Stores > Sales > Checkout > Enable Terms and Conditions
2. Enable two payment method
3. On checkout payment step select a payment method
4. Click Place Order
5. Validation message for checkout agreements appears
6. Select a different payment method
7. Click Place Order
8. No error message is displayed even if you don't check the terms and conditions checkbox

### Expected result

1. Error message should be displayed to warn the user he must agree the terms and conditions

### Actual result

1. The order is placed

**Comment by AlexWorking** [comment] 2019-05-23 15:39
Hello @magento2dev. We've been not able to reproduce Your issue on the latest develop version. Could You please try to reproduce Your issue on 2.3-develop version as You are asked above:
![Advised](https://user-images.githubusercontent.com/27814011/58266210-e788bb00-7d89-11e9-891b-7eff39093d1a.png)
Thank You.

**Comment by magento2dev** [comment] 2019-05-23 15:43
Hello @AlexWorking,

Thanks for your reply but as I mentionned the issue is tested on Magento 2.2 not on 2.3. I did not test on 2.3 because I don't want to switch version and many people still have the issue on 2.2 as you can see on closed issue #6224 

Thanks for your help

**Comment by AlexWorking** [comment] 2019-05-24 08:57
@magento2dev, unfortunately if the issue is not reproducible on a 2.3-develop version we consider it as fixed and do not provide fixes for earlier versions. (Please expound and look at the Details to the stage 4 of our recheck flow a bit above from here 
![Supposed](https://user-images.githubusercontent.com/27814011/58315349-15b5db80-7e1a-11e9-9fea-67ac602b3049.png)
). But it's quite possible that we miss something in the Steps to Reproduce You provided, or do something incorrectly, or probably You have forgotten to tell us some essential nuance.  Therefore if You had a success in repproducing the issue on a develop instance You could help us to reproduce it ourselves and thus to confirm it. So maybe You will try? Thank You.

**Comment by sdzhepa** [comment] 2019-06-04 18:54
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-04 18:55
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-04 18:55
Hi @sdzhepa, here is your [Magento instance](https://i-22992-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22992-2-2-develop.instances.magento-community.engineering/admin](https://i-22992-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2019-06-04 20:20
Hello @magento2dev 


I tried to reproduce this issue on the vanilla Magento instance based on `2.2-develop` branch.
I used steps from this issue description and from closed https://github.com/magento/magento2/issues/6224

And I cannot reproduce the issue have to close it as `Cannot Reproduce` resolution

But feel free to provide additional details/steps and reopen it.

I suppose it could be some specific and missed precondition(s) or step.
Or the issue is already fixed for the latest 2.2.x release.



**Additional details and steps used to reproduce**
Note: Tried to reproduce using Google Chrome and FireFox browsers
1. Install clear vanilla Magento instance based on `2.2-develop`
2. Create test simple product and assign it to test category
3. Go to _Stores > Terms and Conditions_ and create a new one with Applied = Manual
-- ![22992_3](https://user-images.githubusercontent.com/3409584/58910785-08cb9e80-86dc-11e9-994a-b1f9be1d0efe.jpg)

4. Go to _Stores > SALES > Payment Method_ and enable 2 payments, for test I used:
-- Check / Money order
-- Purchase Order
5. Enable Terms and Condition for Checkout in _Stores > SALES > Checkout_
-- ![22992_5](https://user-images.githubusercontent.com/3409584/58910805-1719ba80-86dc-11e9-9974-07c7e7b16bdb.jpg)

6. Save Config and Flush all  Caches
7. Go to Storefront and add test product to the cart
8.  Complete Shipping Checkout step and go to the payment

**Actual Result** Validation message appears I cannot place order
![71A114FA-4C9C-4D24-B760-41D4F4B0878E](https://user-images.githubusercontent.com/3409584/58910850-2bf64e00-86dc-11e9-8296-491ad68bcbd6.GIF)

**Closed as completed by sdzhepa** 2019-06-04 20:20 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is valid
