### ISSUE TITLE
Uncaught Error: Cannot instantiate interface - 2.0.6 with PHP 7.0.6

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#4559] opened 2016-05-18 16:53 UTC
## Steps to reproduce
1. Updated to 2.0.5 to 2.0.6
- composer require magento/product-community-edition 2.0.6 --no-update
- composer update
- php bin/magento setup:upgrade
1. backend -> web setup wizard -> component manager

Same result by runing the following
- php -f bin/magento cache:clean
- php -f bin/magento cache:flush
- php -f bin/magento indexer:reindex
- rm -rf var/di
- rm -rf var/generation
- rm -rf pub/static/_requirejs
- rm -rf var/view_preprocessed
- rm -rf pub/static/frontend
- rm -rf pub/static/adminhtml
## Expected result
1. Show all component name/ module name/ etc....
## Actual result

![image](https://cloud.githubusercontent.com/assets/17633236/15367280/34764a92-1cdd-11e6-9148-bad84d89db1c.png)
**console**
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/setup/index.php/componentGrid/components

**PHP error log**
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73"
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "Stack trace:"
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "#0 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Zend\ServiceMan...')"
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "#1 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Zend\ServiceMan...')"
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "#2 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Zend\ServiceMan...', NULL, 'serviceLocator', 'Magento\Setup\M...')"
[18-May-2016 12:34:21] WARNING: [pool xxx] child 23903 said into stderr: "#3 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Facto..."
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Zend\ServiceManager\ServiceLocatorInterface in /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:73"
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "Stack trace:"
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "#0 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Zend\ServiceMan...')"
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "#1 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(236): Magento\Framework\ObjectManager\ObjectManager->get('Zend\ServiceMan...')"
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "#2 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(53): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Zend\ServiceMan...', NULL, 'serviceLocator', 'Magento\Setup\M...')"
[18-May-2016 12:35:33] WARNING: [pool xxx] child 20404 said into stderr: "#3 /var/www/vhosts/xxx/httpdocs/sample1/vendor/magento/framework/ObjectManager/Facto..."

**Comment by mazhalai** [comment] 2016-05-19 17:11
Duplicate of #4546

**Closed as completed by mazhalai** 2016-05-19 17:11 UTC
