### ISSUE TITLE
Aspect ratio calculation issue.

### ISSUE THREAD

**Issue by sergey-fedosimov** [magento/magento2#32546] opened 2021-03-18 11:53 UTC
### Preconditions (*)

1.  Magento 2.3.6-2.4.2

### Steps to reproduce (*)

1. Go to admin panel
2. Open WYSIWYG gallery from any place (cms page/cms block/...)
3. Upload an image with a ratio 1500x6
4. Look at the generated thumbnail in the gallery

### Expected result (*)
1. Thumbnail is generated and is shown in gallery correctly
2. 

### Actual result (*)
1. Thumbnail is broken
![image](https://user-images.githubusercontent.com/18401050/111621885-8dc47100-87f9-11eb-8313-3f83026aa16e.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-03-18 12:08
i can't reproduce issue in 2.4-develop branch. Image uploaded without break image

**Comment by engcom-Oscar** [comment] 2021-03-18 12:25
Hi @sergey-fedosimov  ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.

### Steps to reproduce (*)
1. Go to admin panel
2. Open WYSIWYG gallery from any place (cms page/cms block/...)
3. Upload an image with a ratio 1500x6
4. Look at the generated thumbnail in the gallery

**Actual Result:** :heavy_check_mark: 
Thumbnail is generated and is shown in gallery correctly
![Screenshot from 2021-03-18 14-24-03](https://user-images.githubusercontent.com/60198413/111625603-b64a6c00-87f5-11eb-89c8-688a539fcdc9.png)

So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-03-18 12:25 UTC
Labels: Issue: ready for confirmation, not-confirmed
