### ISSUE TITLE
Try to create theme - But nothing apply

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#1590] opened 2015-07-30 14:16 UTC
Hello,

I am trying to create new theme in magento 2.

I am trying to change background color.

So i copied web/css/source/_theme.less

And change @page__background-color: @color-white; to @page__background-color: @color-gray19;

But nothing changed into frontend side.

Already removed static files.

Also If i want to add more color code then i need to edit below file?

lib\web\css\source\lib\variables\_colors.less

**Comment by godban** [comment] 2015-07-30 16:49
Hello @sunilit42 

Seems you are doing everything right, let's try to catch what is wrong, please verify next things:
- You created new theme with next structure:
````
app/design/frontend/
├── YourVendorName
│   │   ├──YourThemeName
│   │   │   ├── web
│   │   │   │   ├── css
│   │   │   │   │   ├── source
│   │   │   │   │   │   ├── _theme.less
````
- You applied this theme as main in admin Stores -> Configuration -> Design -> Design Theme
- Chosen your theme, saved configuration and flushed cache
- Theme is applied and styles for example going from pub/static/frontend/YourVendorName/YourThemeName/...

I suggest problem in of some steps above

> Also If i want to add more color code then i need to edit below file?
>
> lib\web\css\source\lib\variables_colors.less

No, you shouldn't work with lib, it would lead to incompatibility.
Instead you can create new styles or override existing.

**Example of create new styles for new theme with blank theme parent:**
Create new parent less files
````
app/design/frontend/
├── YourVendorName
│   │   ├──YourThemeName
│   │   │   ├── web
│   │   │   │   ├── css
│   │   │   │   │   ├── styles-l.less, styles-m.less
````
Inside your new parent styles (styles-l.less, styles-m.less) you can add any new styles or imports.

**Example of override exisiting styles for new theme with blank theme parent:**
Let's say you don't like something that included in Magento 2 lib or sources or predefined theme, as example buttons (why not?). You can simply override existing buttons implementation with create new _buttons.less file in your theme. If path are matched your theme will override default file.

````
app/design/frontend/
├── YourVendorName
│   │   ├──YourThemeName
│   │   │   ├── web
│   │   │   │   ├── css
│   │   │   │   │   ├── source
│   │   │   │   │   │   ├── _buttons.less
````

**Comment by sunilit42** [comment] 2015-07-31 09:49
Hello,

Thanks for good explain but still same issue.

One more thing notice:
Just rename of theme name from pub/static/frontend/PackageName/Themename

When i refresh page all static content not able to create automatically, I already set Developer mode in htaccess.

So everytime i need to run below command:
magento setup:static-content:deploy

**Comment by godban** [comment] 2015-07-31 11:35
@sunilit42 

Renaming directories seems bad practice, after creation and call theme stored in DB.

![DB](http://i.imgur.com/1sK74Y7.png)

I can't reproduce your issue. Can you provide more info? Add some screenshot with path of static files in debugger or/and created theme structure?

**Comment by sunilit42** [comment] 2015-07-31 11:42
Hello,

What i did, i created new theme.

![image](https://cloud.githubusercontent.com/assets/2923438/9006597/e3affbc4-37a6-11e5-8ef6-f0418be5fa3a.png)

Then after i rename static folder or delete

![image](https://cloud.githubusercontent.com/assets/2923438/9006607/fe2ecf16-37a6-11e5-80ee-c56b39e70f57.png)

Also set theme in backend also.

Now when when i open my website 
![image](https://cloud.githubusercontent.com/assets/2923438/9006612/1618f066-37a7-11e5-802b-2d7f939b8a0c.png)

All resource can not able to create automatically in static folder.

Then i run below command 
magento setup:static-content:deploy

So everytime when i did css change i need to run above command.

**Comment by sunilit42** [comment] 2015-07-31 12:22
Hello,

![image](https://cloud.githubusercontent.com/assets/2923438/9007065/76f5a4f2-37ab-11e5-8441-a46278fbe4c1.png)

Create new theme and name of name demo theme.

Folder stucture of theme is 
![image](https://cloud.githubusercontent.com/assets/2923438/9007097/b8085098-37ab-11e5-8dd1-0ea8529c1b1c.png)

Frontend screenshot:- 
![image](https://cloud.githubusercontent.com/assets/2923438/9007103/c44d3206-37ab-11e5-97cd-0845c3505ac4.png)

Now i am trying to change color from  @color-gray19 to #ff5501 
![image](https://cloud.githubusercontent.com/assets/2923438/9007129/f66f4706-37ab-11e5-8e33-d125e2ee5720.png)

Now refresh page at frontend side
no changes is apply.

So rename static folder or delete it
![image](https://cloud.githubusercontent.com/assets/2923438/9007145/254fb966-37ac-11e5-9648-f7ee58b07f4b.png)

After rename, not able to create all files automatically


![untitled](https://cloud.githubusercontent.com/assets/2923438/9007214/dcdaa37a-37ac-11e5-8f35-8f8c8a5d986b.png)

So everytime when i will change something in css, i need to run below command?
magento setup:static-content:deploy

look forward your reply

**Comment by godban** [comment] 2015-07-31 12:42
@sunilit42 ok, now I see that theme is created and applied and trying to reach by correct path to pub.

Please verify that this files are missed in `pub/static/frontend/Test/mage2...` Please delete all renamed folders and 'pub/static' and show what you have after page refresh.

> So everytime when i will change something in css, i need to run below command?
> magento setup:static-content:deploy

No, you don't need that. Deleting of `pub/static/frontend/Test/mage2...` enough to rerun all process that generates static files for your theme.

**Comment by sunilit42** [comment] 2015-07-31 12:46
Already removed static folder 

![image](https://cloud.githubusercontent.com/assets/2923438/9007575/313e6e58-37b0-11e5-97a0-ba16c4777829.png)

Only requirejs folder created after remove it.

**Comment by godban** [comment] 2015-07-31 14:11
@sunilit42 gotcha, thank you for detailed screenshots
seems problem is in deletion .htaccess inside pub/static, try to recover it and delete only files that need to be recreated `pub/static/frontend/Test/mage2/...`

**Comment by sunilit42** [comment] 2015-08-03 06:42
Hello,

Thanks for that.

What i did, i copied that  htaccess file from repository.

But still one css missing- first time load.
![image](https://cloud.githubusercontent.com/assets/2923438/9032100/c8f21162-39d8-11e5-86e7-45e8df846f4a.png)


But second time when i refresh page it is working fine

**Comment by sunilit42** [comment] 2015-08-03 06:54
Also 
![image](https://cloud.githubusercontent.com/assets/2923438/9032263/677fba40-39da-11e5-8320-3089a2f93002.png)

I changed background color from _theme.css file  still not applied after refresh page.

Then i removed static files but still not showing changes.

Anything missing?

**Comment by godban** [comment] 2015-08-03 09:02
> But still one css missing- first time load.
> image

> But second time when i refresh page it is working fine

@sunilit42
It's known issue. Less php processing is slow on some environments and catch timeout for second file, so it's generates only for second request. Which gonna be when you refresh page second time.

I believe we have internal ticket for that.

> I changed background color from _theme.css file still not applied after refresh page.

> Then i removed static files but still not showing changes.

> Anything missing?

Doh. Well seems you did everything right, for me hard to say what's wrong. I created new themes couple times during last days and all was fine.

We need plan B. Can you upload your current repo to GitHub? Will try to debug fork directly.

**Comment by sunilit42** [comment] 2015-08-03 10:46
uploaded theme files on dropbox

https://www.dropbox.com/s/thm0398aivxaglt/Test.zip?dl=0

Thanks for your help

**Comment by apetrashova** [comment] 2015-08-04 16:04
I had the same situation and I deleted also the folder /var/view_preprocessed, or in backend System/"Cache Managed" clicked on button "Flush Static Files Cache". Maybe it will help.

**Comment by sunilit42** [comment] 2015-08-04 16:16
this is not a solution..every time when  I changed something in CSS then
remove all folder in developer mode

**Comment by annapet** [comment] 2015-08-04 16:18
I think so too! :)

**Comment by sunilit42** [comment] 2015-08-05 06:21
waiting for some good answer !!!

**Comment by sunilit42** [comment] 2015-08-05 08:23
@godban , is there any solution?

**Comment by godban** [comment] 2015-08-05 09:22
@sunilit42 as for your themethat you provided, I didn't find required `<preview_image>media/logo.png</preview_image>` preview image. It can break theme generation.

@sunilit42 @annapet 
> I had the same situation and I deleted also the folder

We found issue with copies of LESS source files that are created instead of symlinks in client side less compilation. That mean there is no chance to apply changes without deleting 'pub/static/frontend' manually now. Sorry about this.
We created internal ticket for that MAGETWO-40652 and will fixed asap.

**Comment by sunilit42** [comment] 2015-08-27 10:54
hey,

any news on this?

**Comment by godban** [comment] 2015-09-03 17:01
Hey @sunilit42,
sorry for delay, should be fixed now

**Comment by okorshenko** [comment] 2015-09-24 08:50
@sunilit42 Are you still able to reproduce this issue?

**Comment by sunilit42** [comment] 2015-10-02 08:33
one more question:

if i want to do some small changes into cssm then how i can do directly and test.

Because in magento2, that working based on saas, so it merge all css and creating css file, so much time consuming, how we can do quickly.

**Comment by vasuscoin** [comment] 2015-10-12 12:07
Hello,
Que: How "grunt watch" will work for newly created theme?

I installed Magento ver. 1.0.0-beta.

I have cloned from luma theme as child theme under /app/design/frontend/Vendor/lumaDark
Grunt is installed and its working fine. 

If I change something from  /app/design/frontend/Vendor/lumaDark/Magento_Checkout/web/css/source/module/_minicart.less file. it doesn't showing under Grunt watch from command line.

While If I change it from /pub/static/frontend/Vendor/lumaDark/Magento_Checkout/web/css/source/module/_minicart.less 

It showing file changes status in Command Line and less processing has been working fine.

So what the exact way to work with less as well as grunt watch parallel for run time less processing? 

Please help me..

**Comment by eug123** [comment] 2015-10-12 12:24
Hello, @vasuscoin 

Have you added your theme (Vendor/lumaDark) to the themes list grunt configuration file 
`dev/tools/grunt/configs/themes.js`?

http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-topics/css_debug.html#grunt_prereq

**Comment by vasuscoin** [comment] 2015-10-12 12:35
Hey @eug123 
Sorry for delay.
I have added them to `dev/tools/grunt/configs/theme.js` as well as added to  `dev/tools/grunt/configs/less.js`

**Comment by vasuscoin** [comment] 2015-10-12 12:40
@eug123 
I have attached theme.js & less.js screenshot. 
![less](https://cloud.githubusercontent.com/assets/648859/10428074/822253bc-710c-11e5-9fa4-00c8e400ea68.png)

**Comment by eug123** [comment] 2015-10-12 13:21
Sorry, @vasuscoin

Have skipped info about your magento version. 
There is an issue in beta - system creates copies of less files instead of symlinks, so changes in sources are not visible for watcher.
There is a discussion [about it](https://github.com/magento/magento2/issues/1787)
And here is a patch to fix symlink issue in beta - https://gist.github.com/godban/8cb178f9a84ed85f1eac

**Comment by vasuscoin** [comment] 2015-10-13 07:24
@eug123 
I tried to install patch. Unfortunately `app/code/Magento/Developer/Test/Unit/Console/Command/CssDeployCommandTest.php` file not found.

Where from I will received this file?

**Comment by eug123** [comment] 2015-10-13 08:38
Hi,
Merchant beta version of this file in the master branch
https://github.com/magento/magento2/blob/master/app/code/Magento/Developer/Test/Unit/Console/Command/CssDeployCommandTest.php

**Comment by vasuscoin** [comment] 2015-10-13 12:51
In which branch we have to work after cloned from `https://github.com/magento/magento2` ? develop or master ? 
I observed that there are some files & folders are missing in Master Branch.

**Comment by vasuscoin** [comment] 2015-10-13 12:57
I got answer for my query at `http://devdocs.magento.com/guides/v2.0/install-gde/install/composer-clone.html#instgde-prereq-compose-clone`
Thank you.

**Comment by sunilit42** [comment] 2015-10-13 13:40
Hello,

i am trying to use grunt watch command, in screen showing waiting command only.
![image](https://cloud.githubusercontent.com/assets/2923438/10456271/1d555f38-71de-11e5-9f44-dd74eef1190c.png)

**Comment by sunilit42** [comment] 2015-10-13 13:42
When i am using grunt watch command,it showing waiting screen only:
![image](https://cloud.githubusercontent.com/assets/2923438/10456289/4136ac36-71de-11e5-8ecf-1320159637a3.png)

**Comment by davidalger** [comment] 2015-11-10 21:32
Fixed.

**Closed by davidalger** 2015-11-10 21:32 UTC
Labels: acknowledged, bug, CS
