### ISSUE TITLE
Magento 2.3.5 empty notification 

### ISSUE THREAD

**Issue by rahmanQaiser** [magento/magento2#28825] opened 2020-06-22 11:43 UTC
Im getting empty notifications on the fronted. Can you please point out what is wrong with this. 
![image](https://user-images.githubusercontent.com/8874475/85283822-7002ef00-b4a7-11ea-8ca6-1050c8d422c6.png)

Thank you!

**Comment by swathishs** [comment] 2020-06-22 12:26
@rahmanQaiser :
Thank you for your report.
GitHub issue tracker is intended for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

**Comment by swathishs** [comment] 2020-06-22 12:44
@rahmanQaiser : Can you please add the details so that I can recreate the issue  
1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

**Comment by swathishs** [comment] 2020-06-22 14:18
@rahmanQaiser : Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

**Comment by swathishs** [comment] 2020-06-25 06:58
@rahmanQaiser : Thank you for your report. For GitHub issue tracker is for Magento core technical issues only
Kindly refer https://community.magento.com/ or https://magento.stackexchange.com/ for general discussion

Hence closing the ticket

**Closed as completed by swathishs** 2020-06-25 06:58 UTC
Labels: Issue: Format is not valid, Reported on 2.3.5
