### ISSUE TITLE
ES indices:admin/aliases/get permission required for wildcard index

### ISSUE THREAD

**Issue by celesteking** [magento/magento2#38041] opened 2023-10-03 23:49 UTC
### Preconditions and environment

Why would you guys require such a broad permission which would reveal to Magento all available aliases (and generally, all indexes either having or not aliases) on an ES server? We're trying to segregate users but this requirement stays in our way. It's unsafe and it's unnecessary, it exposes too much data.

Instead, you should use a wildcard to retrieve aliases confined to the index prefix:
`GET ${Elasticsearch-Index-Prefix}*/_alias`

- Magento ver. 2.4.6-p2

### Steps to reproduce

1. enable security plugin on your ES (opendistro in our case) server
2. configure Magento with, e.g., ES 7.x indexer
3. See ES server complaining about access denied attempts:
```c
[2023-10-03T00:03:52,096][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elax1] No index-level perm match for User [name=magento-test, backend_roles=[], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [indices:admin/aliases/get]] [RolesChecked [own_index, magento-test]]
[2023-10-03T00:03:52,096][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elax1] No permissions for [indices:admin/aliases/get]

```

Thanks.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-10-09 10:24
Hello @celesteking,

Thanks for the report and collaboration!

We tried to reproduce the issue with the mentioned steps in the 2.4-develop branch. But it seems the issue is not reproducible for us. Please have a look at the below screenshot for reference:

![image](https://github.com/magento/magento2/assets/51681618/97f3003f-c9cd-43b5-9abb-416a87f7e55d)

Please let us know in case anything is missed.

Thanks

**Comment by celesteking** [comment] 2023-10-09 10:56
What are your permissions for the magento user in ES?

Here are ours (actually, the role that's mapped to user):
```json
{
  "magento-test" : {
    "reserved" : false,
    "hidden" : false,
    "cluster_permissions" : [
      "cluster:monitor/main"
    ],
    "index_permissions" : [
      {
        "index_patterns" : [
          "magento_*"
        ],
        "dls" : "",
        "fls" : [ ],
        "masked_fields" : [ ],
        "allowed_actions" : [
          "create_index",
          "crud",
          "manage_aliases",
          "indices_monitor",
          "indices:admin/get",
          "indices:admin/delete",
          "indices:admin/aliases"
        ]
      }
    ],
    "tenant_permissions" : [ ],
    "static" : false
  }
}
```
Assuming role name is `magento-test` and the index prefix is `magento_`.

**Comment by engcom-Hotel** [comment] 2023-10-10 07:29
Hello @celesteking,

For us, the role is superuser, which has all the permissions. It seems that you have set up a separate user/role for your Magento instance.

Please let us know the API you have used to get the permission information from ES.

Thanks

**Comment by engcom-Hotel** [comment] 2023-11-03 06:35
Dear @celesteking,

We have noticed that this issue has not been updated for a period of long time. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-11-03 06:35 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6-p2

**Comment by KarlAustin** [comment] 2024-07-02 09:44
I can confirm we see the exact same behaviour.  If I look in our Opensearch logs I can see it:

```[node1.acustomer-live] No index-level perm match for User [name=acustomer_test, backend_roles=[acustomer_test_dashboard, acustomer_test_magento], requestedTenant=null] Resolved [aliases=[*], allIndices=[*], types=[*], originalRequested=[*], remoteIndices=[]] [Action [indices:admin/aliases/get]] [RolesChecked [own_index, acustomer_test_magento]]```

I have to setup a new permission for all indexes that allows `indices:admin/aliases/get`
