### ISSUE TITLE
Catalog Products Filter in 2.3.2 

### ISSUE THREAD

**Issue by bst2002git** [magento/magento2#23435] opened 2019-06-27 07:45 UTC
Preconditions (*)

Magento 2.3.2

Steps to reproduce (*)

Catalog -> Products set Filters: Status "Enabled" is not honored in 2.3.2 and vice versa
in 2.3-develop

Reproduced on 2.3.x, 2.3-develop

Expected result (*)

Show only products where Status=Enabled or vice versa

Actual result (*)

Products with status either "Enabled" or "Disabled" are displayed in grid

**Comment by bst2002git** [comment] 2019-06-27 07:48
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2019-06-27 07:48
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2019-06-27 07:48
Hi @bst2002git, here is your [Magento instance](https://i-23435-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-23435-2-3-2.instances.magento-community.engineering/admin](https://i-23435-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by bst2002git** [comment] 2019-06-27 08:05
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-27 08:06
Hi @bst2002git. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-27 08:06
Hi @bst2002git, here is your [Magento instance](https://i-23435-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23435-2-3-develop.instances.magento-community.engineering/admin](https://i-23435-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mattijv** [comment] 2019-06-27 13:43
Can confirm. The issue is caused by the new `addAttributeToFilterAllStores` method [here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Ui/DataProvider/Product/ProductCollection.php#L81).

Unfortunately the sql generated by that method forgets to add an attribute_id condition, which means any attribute of the same type with the same value will match. In the sample data, for example, most (all?) products have tax_class_id with value 2, which will match the status=2 filter without the attribute_id condition.

**Comment by magento-engcom-team** [comment] 2019-06-27 14:05
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17852`, `MC-17853` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bst2002git** [comment] 2019-06-27 14:52
I've applied the patch and it seems to work for me

**Comment by YiffyToys** [comment] 2019-07-09 06:07
> I've applied the patch and it seems to work for me

Where is that patch? I don't see any commits referencing #23435 automatically here or any commit linked in this ticket.

**Comment by bst2002git** [comment] 2019-07-09 07:40
it is not a patch in the true sense...
look here: https://github.com/magento/magento2/pull/23444/files

**Comment by alexandrosk** [comment] 2019-07-10 12:49
@bst2002git Thank you!

**Comment by magento-engcom-team** [comment] 2019-07-11 19:08
Hi @bst2002git. Thank you for your report. 
The issue has been fixed in magento/magento2#23444 by @mattijv in 2.3-develop branch
Related commit(s):
 - [4adee3b19c1396251d29c54df3eb874d5c985388](https://github.com/magento/magento2/commit/4adee3b19c1396251d29c54df3eb874d5c985388)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-07-11 19:08 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Filter

**Comment by lamasfoker** [comment] 2019-09-27 08:01
Please reopen this issue, the patch does not work. As @firewolf said in the comment of the commit the store id is missing. Replace $condition with this:
```        
            $condition = "({$pKey} = {$fKey}) AND ("
            . $this->_getConditionSql("{$tableName}.value", $condition)
            . ') AND ('
            . $this->_getConditionSql("{$tableName}.attribute_id", $attributeId)
            . ') AND ('
            . $this->_getConditionSql("{$tableName}.store_id", $this->getDefaultStoreId())
            . ')';
```

**Comment by mattijv** [comment] 2019-09-27 08:52
@lamasfoker See my comment here https://github.com/magento/magento2/pull/23444#issuecomment-535853070. This issue, as it pretains to the current intended functionality, is (I believe) solved.

If you think the current Magento functionality is not the one you want/expect, please open a separate issue to discuss it.
