### ISSUE TITLE
File not repopulating when editing/reordering products with custom option in cart

### ISSUE THREAD

**Issue by iamgurjitsingh** [magento/magento2#7911] opened 2016-12-21 13:25 UTC
### Preconditions

1. Magento 2.0.6

### Steps to reproduce

    Create a product with a required custom option file field
    Upload a file, add to cart
    Edit cart, edit product with file
    Submit product
    Cart throws an error, saying that one or more required fields were not submitted (the file does not get resubmitted/repopulated)

@fhennessy

### Expected result

1. edit must works fine.
 

How can we fix this in version 2.0.6?

**Comment by veloraven** [comment] 2016-12-30 12:59
@gurjit-singh thank you for your feedback.
If you need an advice or discussion how to fix the issue in the specific version please  refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you want it to be treated  as an issue with fix in some future version please add actual result to your description.

**Comment by iamgurjitsingh** [comment] 2016-12-30 13:04
@veloraven Thank you very much for your response. 

Can you please give me some more details or help to find this problem? I am not able to see the same in your provided sites. 

Looking forward to your reply soon.

Thanks
GS

**Comment by veloraven** [comment] 2017-01-03 12:29
@gurjit-singh the GitHub issue tracker is intended for technical issues only which can be fixed in next releases.
As I understand, you are interested in fixing an issue in the particular already released Magento version. In this case please submit your question to resources specified above as it is not GitHub scope.

**Comment by veloraven** [comment] 2017-01-18 15:02
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-01-18 15:02 UTC
Labels: Progress: needs update
