### ISSUE TITLE
Custom Attributes - Used for Sorting in Product Listing - ElasticSearch Sort Order Incorrect

### ISSUE THREAD

**Issue by kestraly** [magento/magento2#33810] opened 2021-08-16 10:15 UTC
1. Magento 2.3x - 2.4x
1. ElasticSearch 7
1. Using custom attributes to sort catalog

### Steps to reproduce (*)

1. Enable "Used for Sorting in Product Listing" for attribute "color" - Dropdown
1. Add color to attribute set default
1. Populate attribute color option values in no specific order, such as grey, black, blue, orange, green, yellow
1. Assign products to use attribute color
1. Reindex bin/magento index:reindex
1. Go to frontend category and select color from the sort by options

### Expected result (*)

1. Products sorted according to their color attribute option name
1. Attribute Option Values Added Random Order: ![report-3](https://user-images.githubusercontent.com/13368757/129547791-9be6f240-eb3c-4152-b2c7-4df094089283.jpg)
1. Attribute Option Values Re Ordered To Be Alphabetical: ![report-4](https://user-images.githubusercontent.com/13368757/129547794-231aed2a-c23c-40ce-8672-0a19daccd352.jpg)

### Actual result (*)

1. Products are sorted by their attribute option value id, in essense sorted in the order they were added to the attribute
1. Incorrectly sorted ![report-2](https://user-images.githubusercontent.com/13368757/129547796-5b7f8655-8957-4a00-9a67-8d13487ce414.jpg)

##  

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
 - < > Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - <X> Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by kestraly** [comment] 2021-08-16 10:17
@magento give me 2.4.3 instance

**Comment by kestraly** [comment] 2021-08-16 10:31
Reproduced in 2.4.3

https://e930fff37bbf67bbd049302464383cfb-2-4-3.instances.magento-community.engineering/color-sorting.html?product_list_order=color

@magento give me 2.4-develop instance

**Comment by kestraly** [comment] 2021-08-16 10:44
Reproduce in 2.4-develop instance

https://e930fff37bbf67bbd049302464383cfb-2-4-develop.instances.magento-community.engineering/color-sorting.html?product_list_order=color

**Comment by devchris79** [comment] 2021-08-16 11:09
The category sort order has been awful since Elasticsearch and there is a few issues around it:
#31758 #32522 #31043

Even the most basic sort by position doesn't work...

**Comment by kestraly** [comment] 2021-08-16 11:51
@devchris79  - It's been driving me crazy. But all my attempts to resolve have come up blank and no resolve in 2.4.3

**Comment by engcom-Lima** [comment] 2021-08-18 13:57
Hi @kestraly,

Thank you for reporting this issue.

Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
1. Enabled "Used for Sorting in Product Listing" for attribute "color" doom Dropdown.
2. Added color in default Attribute Set.
3. Created new products with different colors assigned to each one of them.
4. Did reindexed using bin/magento index:reindex
5. Checked on front-end to sort based on color order but results were inaccurate.
6. The results were coming based on attribute option value id but not according to their color attribute name. 
**Issue:** Inaccurate results based on color sort-order.

**Comment by pmonosolo** [comment] 2021-08-24 19:40
This HAS got to be a priority. Its basically making catalog browsing unusable!

**Comment by chernenm** [comment] 2021-09-02 21:08
hello @kestraly,

Thank you for reporting this issue. But this is actually by design behavior. The attribute values sort order has nothing to do with sorting products by this attribute on storefront. Products are supposed to be sorted by attribute values names. Attribute values sort order is only for displaying the values list in Admin.

**Comment by kestraly** [comment] 2021-09-02 21:12
@chernenm -No no no.. This issue is not closed. The sort order has no bearing on either the attribute name or the attribute postion. Instead it's only attribute value_id. If you compare the sort of MYSQL sorting to EaslticSearch. You will find that if your colours are sorted alphbetically. If you sort in ElasticSearch, it sorts by attribute value_id.

If you want people to use Magento, pay more attention to the details. This issue needs to be reopened.

I only referenced the sort order, because that would be the ideal for 99% of the customers I deal with, but sorting by name should at least work. The issue is the SORT BY NAME DOES NOT WORK FOR ATTRIBUTES!

**Comment by chernenm** [comment] 2021-09-02 21:52
Hi @kestraly,

Yes, I agree, sorting by name must work if this is broken now, I would prioritize it higher. Could I please update the expected result in this case, since sorting products by using the attribute values sort order would be a new feature request instead.

**Comment by kestraly** [comment] 2021-09-02 21:59
@chernenm - 

If you delete all the attribute values of color. Then re add them as Red, Orange, Black, Blue, Pink. 

On the category page, if you select sort by color, they will sort on the order they were added to the attribute, so they will sort as Red, Orange, Black, Blue, Pink, rather than by name.

* Side note *
If you re-order the attribute values in the admin (which store users think is the cause of the issue to not sort correctly), it still doesn't resolve the issue, because it has no bearing on the sort order by design, which was the same in Magento 1.

But main issue is, it doesn't sort by attribute name. Thank you.

**Comment by engcom-November** [comment] 2021-09-03 11:47
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Frontend - Category page  - Sort By - Attribute Name is not working
Admin - Stores - Attributes - Product - Choose Color Attribute - Storefront Properties - Used for Sorting in Product Listing - yes
Properties - Add different random options and save
Add the products with different Color Attribute options and save
Reindex and clear cache
Front-end - Category page - Sort By - Color Attribute
Issue: Sorting is not working
Products are sorted in which the Attribute options are added from Admin
![image](https://user-images.githubusercontent.com/60198231/132000401-1c061661-2405-44d7-be2d-0ee1c3de3f5b.png)

**Comment by pmonosolo** [comment] 2021-09-03 21:37
If anybody is looking for a temporary solution Mirasvit Advanced Sort plugin is working well on 2.4.3.

**Comment by vandijkstef** [comment] 2022-02-16 11:12
> If anybody is looking for a temporary solution Mirasvit Advanced Sort plugin is working well on 2.4.3.

While this did change some ordering, it didn't order how it should. ASC/DESC also not working.

Any updates on this issue? I see a lot of PR stuff passing by, but it seems stale?

**Comment by engcom-Alfa** [comment] 2022-04-13 09:44
Hi @kestraly ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/979aee04b0ebcf51c1c3dfc45e6ca89466686bdf).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Closed as completed** 2022-04-13 09:45 UTC
Labels: Issue: Confirmed, Component: Elasticsearch, Reproduced on 2.4.x, Priority: P1, Progress: done, Component: Attributes, Reported on 2.4.x, Area: Product
