### ISSUE TITLE
User menu sub items not visible for access n browser

### ISSUE THREAD

**Issue by shu1313** [magento/magento2#2229] opened 2015-10-31 12:04 UTC
When we open the menu bar in Google chrome  / opera , we cant see Index and compile
We cant move the menu up or down to access other buttons.

attached screenshot below 
![mag2 menu move ssue](https://cloud.githubusercontent.com/assets/12825344/10863495/92afd11c-7ff5-11e5-959e-dfcffeb7fd2b.JPG)

**Comment by MomotenkoNatalia** [comment] 2015-11-03 14:06
Hi @shu1313 , thank you for report.
Could you please specify your screen resolution.

**Comment by shu1313** [comment] 2015-11-03 14:16
Hi, 
my screen resolution is 1366 X 768I am not sure what is the problem but sometimes it is working and sometimes it is not

 Date: Tue, 3 Nov 2015 06:07:22 -0800

**Comment by vzabaznov** [comment] 2016-06-22 12:04
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by MomotenkoNatalia** [comment] 2016-07-18 13:20
@shu1313 We will do fixes under MAGETWO-49758.

**Comment by magento-engcom-team** [comment] 2017-10-10 08:30
@shu1313, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed by magento-engcom-team** 2017-10-10 08:30 UTC
Labels: acknowledged, bug report, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in develop, Frontend, G1 Failed, G2 Passed, G3 Passed
