### ISSUE TITLE
Extension Attribute not working on Magento 2.0.4

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#4366] opened 2016-05-02 03:45 UTC
Hi,

I am create extension attribute with this code : 

``` php
public function beforeSaveAddressInformation(
        \Magento\Checkout\Model\ShippingInformationManagement $subject,
        $cartId,
        \Magento\Checkout\Api\Data\ShippingInformationInterface $addressInformation
    ) {
        $extAttributes = $addressInformation->getExtensionAttributes();
        $optin = $extAttributes->getOptin();
        $quote = $this->quoteRepository->getActive($cartId);
        $quote->setOptin($optin);
    }
```

and this is working when i am using Magento 2.0.1, but why on Magento 2.0.4, `$extAttributes` always `NULL` ?

Regards,
Ivan

**Comment by Vinai** [comment] 2016-05-02 14:03
If you check the return type hint for `\Magento\Checkout\Api\Data\ShippingInformationInterface::getExtensionAttributes()` it explicitly states that the return value might be `null`.
According to other examples in the core, the "right thing to do" seems to be to inject an `ShippingInformationExtensionFactory`.  
Then use something like 

```
$extAttributes = $addressInformation->getExtensionAttributes() ?: $this->extensionAttributesFactory->create();
```

Since this isn't a bug but rather the expected behavior, I'll close this issue. If you have further questions please refer to http://magento.stackexchange.com/ or https://community.magento.com/t5/Programming-Questions/bd-p/devqa

**Closed as completed by Vinai** 2016-05-02 14:03 UTC
