### ISSUE TITLE
GraphQl getProductFiltersByCategory return wrong category_id

### ISSUE THREAD

**Issue by vmishra341** [magento/magento2#35220] opened 2022-03-24 06:11 UTC
### Preconditions (*)

1. Magento CE and EE version 2.4.3-p1

### Steps to reproduce (*)

1. get the products details filter by category 
2. use below Graphql Queries both return wrong result.

query getProductFiltersByCategory($categoryIdFilter: FilterEqualTypeInput!) {
    products(filter: { category_id: $categoryIdFilter }) {
      aggregations {
          attribute_code
          count
          amshopby_filter_data{categories_filter}
          label
          options {
              count
              label              
              value
          }
      }

    }
}
and use below filter Variable 
{ "categoryIdFilter": { "eq": "1680" } }
here 1680 is Parent Category

OR
{
  products(filter: {category_id: {eq: "1680"}}) {
    aggregations {
      attribute_code      
      label
      options {
        label       
      }
    }    
  }
}

### Expected result (*)

1. https://prnt.sc/9LHi6lNKba4b
2. Query should written the Sub category of Parent category just like its showing on website frontend.

### Actual result (*)
It returning all the categories instead of sub category of provided category Id just like its showing on Luma theme frontend

1. https://prnt.sc/o8Il0-XrPsLL
2 .https://prnt.sc/XQ_DsCReuayf

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-03-25 10:30
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-25 11:30
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-25 12:09
Verified the issue on  Magento 2.4-develop branch but cannot able to reproduce the issue:
On applying filter category Id, ID specific Category is retrieved in the response. 
![image](https://user-images.githubusercontent.com/60198231/160118039-ed9e1df0-5d8c-4d7e-9ea7-f59876b06afa.png)
@vmishra341 kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by vmishra341** [comment] 2022-03-25 12:28
Hi @engcom-November ,

Please check the below attached screenshot and check category id 3 on both GraphQL and Luma frontend.

![image](https://user-images.githubusercontent.com/56992673/160120473-a2664401-9cec-4c39-829c-c1c35b4640ad.png)
![image](https://user-images.githubusercontent.com/56992673/160120604-f84c3d70-0c0f-4263-8562-257b54c3347c.png)

There are additional categories showing in GraphQL but on luma frontend only subcategories are showing.

**Comment by vmishra341** [comment] 2022-03-28 06:57
@engcom-November is there any update from your end for my last response on this?

**Comment by engcom-November** [comment] 2022-03-28 11:45
Verified the issue on Vanilla Magento 2.4-develop instance with sample data and the issue is reproducible:
Other categories are retrieved in the response:
![image](https://user-images.githubusercontent.com/60198231/160391036-0bc95630-8080-49ef-a8aa-2dd451a1cba0.png)
![image](https://user-images.githubusercontent.com/60198231/160391077-d0be9e3e-b1c4-4ede-be5a-f22365e7a7ae.png)
![image](https://user-images.githubusercontent.com/60198231/160391135-e3eca1bd-fc97-45e3-8ee3-1d3b84be33e6.png)

**Comment by vmishra341** [comment] 2022-04-07 04:22
any update on this issue? any patch which we can use to resolve it?

**Comment by Usik2203** [comment] 2022-04-29 09:04
@magento I am working on this

**Comment by Usik2203** [comment] 2022-04-29 10:32
Hello @vmishra341 
After some time of investigation i see that default Magento GraphQl functionality allow us extract sub category of Parent category just like its showing on website frontend. 
**_You should use next GraphQl query_** 
<pre>
query {
    products(filter: {
        category_id: {
            eq: "4"
        }
    }) {
        aggregations (filter: {category: {includeDirectChildrenOnly: true}}) {
	attribute_code
	options {
		count
		label
		value
	   }
	}
    }
}
</pre>
**_Result_** 
<img width="305" alt="Screenshot 2022-04-29 at 13 22 09" src="https://user-images.githubusercontent.com/13517181/165928231-407d004b-afe4-42a5-accb-7542b934fe0f.png">

<img width="311" alt="Screenshot 2022-04-29 at 13 22 44" src="https://user-images.githubusercontent.com/13517181/165928257-a4075f9e-e41b-468a-8eaa-470010fa4d30.png">

<img width="313" alt="Screenshot 2022-04-29 at 13 23 17" src="https://user-images.githubusercontent.com/13517181/165928284-e7320693-4cfa-48da-a134-2772f52c87c0.png">

@engcom-November i think this issue  can be closed. 
Thank you !

**Comment by vmishra341** [comment] 2022-04-29 10:53
@Usik2203 I am getting attached error when I run the provided query
![image](https://user-images.githubusercontent.com/56992673/165931283-79d030ff-5c0c-4169-afcc-0906421eebfa.png)

**Comment by Usik2203** [comment] 2022-04-29 11:08
@vmishra341 I was checking this issue for `2.4-develop` branch  https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L323 
Seems issue still present for `2.4.3-p1` 
Thanks!

**Comment by vmishra341** [comment] 2022-04-29 11:40
@Usik2203 Yes that issue was already resolved in Magento 2.4.4 version but in 2.4.3-p1 and p2 still that issue exists. I have already integrated the fix in my 2.4.3-p1 version.

**Comment by engcom-Hotel** [comment] 2022-05-26 11:50
Hello @vmishra341,

This issue is already addressed and merged. You can refer to the below link for reference:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L323

Hence closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-05-26 11:50 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P1, Project: GraphQL, Progress: done, Area: Product, Reported on 2.4.3-p1
