### ISSUE TITLE
GraphQL response not compliant with UI behavior

### ISSUE THREAD

**Issue by laurentiumagureanu** [magento/magento2#30921] opened 2020-11-13 16:03 UTC
### Preconditions (*)

1. Magento 2.4.1 CE

### Steps to reproduce (*)

The bug described below affects Bundle and Configurable Product. Might affect other kinds of product grouping but I haven't tested.

1. Create or edit a **Bundle** or **Configurable** Product
2. Add products to bundle or configuration
3. Save the bundle/configuration.
4. Open one of the products previously added to the bundle/configuration
5. Add some customizable options and save the product
6. Open the bundle/configuration in the store Frontend. The item with customizable options is not displayed. **This is normal behavior**.
7. Query the bundle product via graphQL (example query below). The item with customizable options is part of the response. **The response should reflect the UI behavior**.

```graphql
{
  products(filter: {url_key: {eq: "test-bundle"}}) {
    items {
      sku
      name
      ... on BundleProduct {
        items {
          option_id
          title
          options {
            id
            label
          }
        }
      }
    }
  }
}
```

```graphql
{
  products(filter: {url_key: {eq: "chaz-kangeroo-hoodie"}}) {
    items {
      sku
      name
      ... on ConfigurableProduct {
        variants {
          product {
            sku
            name
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. The graphQL response for items with customizable options in a Bundle or Configurable Product should have the same behavior as the UI Frontend

### Actual result (*)

1. Bundle in the Magento UI (Joust Duffle Bag has Customizable options):
![image](https://user-images.githubusercontent.com/6639076/99090329-25f5e380-25d7-11eb-8550-e1d6160f853b.png)

2. GraphQL Bundle Product Response:
![image](https://user-images.githubusercontent.com/6639076/99092817-54c18900-25da-11eb-8d96-9853c414b3f0.png)

3. Configurable Product int the UI (the XS-Black variation has customizable options)
![image](https://user-images.githubusercontent.com/6639076/99091635-d1536800-25d8-11eb-99b2-67b40db06ac3.png)

4. GraphQL Configurable Product Response:
![image](https://user-images.githubusercontent.com/6639076/99092584-01e7d180-25da-11eb-8a85-d69041c7edb6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by laurentiumagureanu** [comment] 2020-11-13 16:04
@magento export issue to Jira project MCLOUD as Bug

**Comment by korovitskyi** [comment] 2020-11-26 09:33
@magento I am working on this

**Comment by korovitskyi** [comment] 2020-11-26 09:39
@magento add to contributors team

**Comment by korovitskyi** [comment] 2020-11-26 09:40
@magento I am working on this

**Comment by laurentiumagureanu** [comment] 2020-12-02 15:33
@magento export issue to Jira project MCLOUD as Story

**Comment by engcom-Alfa** [comment] 2022-08-24 07:59
Hi @laurentiumagureanu Thanks for your contribution here.

As we have re-tried to reproduce the issue in `2.4-develop` code branch multiple times in recent months, we are unable to reproduce it at all. The issue might have fixed any other code fixes implicitly.
Here is the complete report about the past work we have performed wrt this issue - [31072#issuecomment-1225329053](https://github.com/magento/magento2/pull/31072#issuecomment-1225329053).
Hence, we are closing this issue for time being.

We request you, please re-try yourself to reproduce the issue in Magento `2.4-develop` code branch. If the issue is still existing, kindly re-define the steps to reproduce and other relevant info that helps us to reproduce our-end as well.
You may report a fresh issue as well, if there are any changes in the issues now.

Thanks!

**Closed as completed by engcom-Alfa** 2022-08-24 07:59 UTC
Labels: Component: CatalogGraphQl, Component: ConfigurableProductGraphQl, Reproduced on 2.4.x, Component: BundleGraphQl, Priority: P1, Severity: S3, Severity: S1, Project: GraphQL, Progress: done, Area: APIs
