### ISSUE TITLE
AwsS3 PHP8 compatibility issue

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35729] opened 2022-07-06 11:21 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP 8.1

### Steps to reproduce

I don't know how to reproduce, I find that error in production logs, but without trace.

However, it should be fixed anyway by adding a cast on `$path` variable, or better : manage the case where `$path` variable is empty or/and null

### Expected result

no error

### Actual result

```.CRITICAL: TypeError: preg_replace(): Argument #3 ($subject) must be of type array|string, null given in /var/www/html/vendor/magento/module-aws-s3/Driver/AwsS3.php:302```

### Additional information

Concerned code : 
`Magento\AwsS3\Driver\AwsS3`

```
 public function getRealPathSafety($path)
    {
        //Removing redundant directory separators
        $path = preg_replace(
            '~(?<!:)\/\/+~',
            '/',
            $path
        );

        if (strpos($path, '/.') === false) {
            return $path;
        }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by simonmaass** [comment] 2022-07-06 17:25
I can confirm this error on our magento 2.4.4 and php 8.1 instance. This error occurs when trying to upload an image in the product description:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/32599710/177608354-8b54a370-39de-4222-8fe3-82f405440f91.png">

In the system logs i can see the following error:
```
[2022-07-06T16:04:32.635581+00:00] .CRITICAL: TypeError: preg_replace(): Argument #3 ($subject) must be of type array|string, null given in /vendor/magento/module-aws-s3/Driver/AwsS3.php:302
Stack trace:
```

**Comment by engcom-Hotel** [comment] 2022-08-09 09:10
Hello @Nuranto @simonmaass,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop instance but the issue is not reproducible for us. We are able to upload the image while adding a product description. Please refer to the below screenshot:

![image](https://user-images.githubusercontent.com/51681618/183610953-c9652973-1cbd-4e2b-963d-ead192cf4882.png)

For AWS S3 is enabled. Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-08-23 05:38
Dear @Nuranto @simonmaass,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-23 05:38 UTC
Labels: Issue: needs update, Reported on 2.4.4
