### ISSUE TITLE
[GRAPHQL] product_links always return the product in graphql call even if linked product is disabled.

### ISSUE THREAD

**Issue by Hexmage** [magento/magento2#37207] opened 2023-03-14 13:50 UTC
### Preconditions and environment

- Magento 2.4.5-p1, most likely older versions as well.
- Install magento demo data.

### Steps to reproduce

1. Go to product with sku `24-UG02` and disable it (entity_id 18 by default).
2. Reindex catalogsearch
3. Call the following GraphQl query to request the product links for `SKU 24-UG07` which has `24-UG02` as a related product by default:
```
query productDetail{
    productDetail: products(filter: {url_key: {eq: "dual-handle-cardio-ball"}}) {
        items {
            sku
            product_links {
                sku
                link_type
                linked_product_sku
                linked_product_type
                position
            }
        }
    }
}
```

### Expected result

Graphql response:
```
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "sku": "24-UG07",
                    "__typename": "SimpleProduct",
                    "categories": [
                        {
                            "name": "Gear",
                            "path": "1/2/3",
                            "url_key": "gear"
                        },
                        {
                            "name": "Fitness Equipment",
                            "path": "1/2/3/5",
                            "url_key": "fitness-equipment"
                        },
                        {
                            "name": "Collections",
                            "path": "1/2/7",
                            "url_key": "collections"
                        }
                    ],
                    "product_links": [
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-UG06",
                            "linked_product_type": "simple",
                            "position": 4
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-WG081-gray",
                            "linked_product_type": "simple",
                            "position": 1
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-WG085_Group",
                            "linked_product_type": "grouped",
                            "position": 3
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG081-gray",
                            "linked_product_type": "simple",
                            "position": 1
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG082-pink",
                            "linked_product_type": "simple",
                            "position": 3
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG085",
                            "linked_product_type": "simple",
                            "position": 2
                        }
                    ]
                }
            ]
        }
    }
}
```

### Actual result

GraphQl response:
```
{
    "data": {
        "productDetail": {
            "items": [
                {
                    "sku": "24-UG07",
                    "__typename": "SimpleProduct",
                    "categories": [
                        {
                            "name": "Gear",
                            "path": "1/2/3",
                            "url_key": "gear"
                        },
                        {
                            "name": "Fitness Equipment",
                            "path": "1/2/3/5",
                            "url_key": "fitness-equipment"
                        },
                        {
                            "name": "Collections",
                            "path": "1/2/7",
                            "url_key": "collections"
                        }
                    ],
                    "product_links": [
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-UG06",
                            "linked_product_type": "simple",
                            "position": 4
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-UG02",
                            "linked_product_type": "simple",
                            "position": 2
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-WG081-gray",
                            "linked_product_type": "simple",
                            "position": 1
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "related",
                            "linked_product_sku": "24-WG085_Group",
                            "linked_product_type": "grouped",
                            "position": 3
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG081-gray",
                            "linked_product_type": "simple",
                            "position": 1
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG082-pink",
                            "linked_product_type": "simple",
                            "position": 3
                        },
                        {
                            "sku": "24-UG07",
                            "link_type": "crosssell",
                            "linked_product_sku": "24-WG085",
                            "linked_product_type": "simple",
                            "position": 2
                        }
                    ]
                }
            ]
        }
    }
}
```
### Additional information

The disabled product is not requestable directly through the product graphql endpoint as intended.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-03-15 05:20
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-03-15 13:45
Hi @Hexmage,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.We have Created a product and disabled.

<img width="1408" alt="Screenshot 2023-03-15 at 3 35 11 PM" src="https://user-images.githubusercontent.com/51680745/225304203-ad40b6c3-6010-46c5-956e-53a9ed486044.png">


2.We have created a product and added disabled product to this product.

![fewbfwb-Products-Inventory-Catalog-Magento-Admin](https://user-images.githubusercontent.com/51680745/225304426-23d25fdf-4d79-4adc-b235-511f49e2ca54.png)


We are not getting disabled product in the response.


<img width="1456" alt="Screenshot 2023-03-15 at 3 33 34 PM" src="https://user-images.githubusercontent.com/51680745/225304558-9d982dde-f8aa-44a0-983c-f41ace9eecda.png">


Kindly let us know if we are missing anything.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Hexmage** [comment] 2023-03-16 09:02
https://github.com/magento give me 2.4-develop instance

**Comment by Hexmage** [comment] 2023-03-16 09:02
@magento give me 2.4-develop instance

**Comment by Hexmage** [comment] 2023-03-16 09:38
@engcom-Bravo 
Locally I always see the disabled products. 

In the instance I just spun up. I can't get the products graphql endpoint to return any products at all. But the urlresolver endpoint is returning data so I'm not sure what I'm doing wrong there. Which makes it currently impossible for me to try and reproduce the issue.

**Comment by engcom-Bravo** [comment] 2023-03-16 13:11
Hi @Hexmage,

Thanks for your update.

We are facing similar issue in above instance.we will update on this accordingly.


<img width="1462" alt="Screenshot 2023-03-16 at 4 06 44 PM" src="https://user-images.githubusercontent.com/51680745/225626997-efbdb5dc-109d-47c9-be0c-ed3bbd7092bc.png">



We have verified the issue in our local 2.4 develop instance.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-10 06:07
Hi @Hexmage,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-10 06:07 UTC
Labels: Project: GraphQL, Issue: needs update, Reported on 2.4.5-p1

**Comment by Hexmage** [comment] 2023-04-11 14:45
@engcom-Bravo 
Well we couldn't reproduce the issue on a development instance because those were broken so we can now finally verify if it's actually broken.
