### ISSUE TITLE
Readiness Check: Checking PHP Version

### ISSUE THREAD

**Issue by razbakov** [magento/magento2#1073] opened 2015-03-03 10:48 UTC
## UnexpectedValueException

File:
```
/srv/www/magento2.test.kirchbergerknorr.de/public/vendor/composer/composer/src/Composer/Package/Version/VersionParser.php:370
```

Message:
```
Could not parse version constraint 5.5.21-1+deb.sury.org~precise+2: Invalid version string "5.5.21-1+deb.sury.org~precise+2"
```

Stack trace:
```
#0 /vendor/composer/composer/src/Composer/Package/Version/VersionParser.php(237): Composer\Package\Version\VersionParser->parseConstraint('5.5.21-1+deb.su...')
#1 /setup/src/Magento/Setup/Controller/Environment.php(69): Composer\Package\Version\VersionParser->parseConstraints('5.5.21-1+deb.su...')
#2 /vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Environment->phpVersionAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /setup/index.php(25): Zend\Mvc\Application->run()
#13 {main}
```

**Comment by vpelipenko** [comment] 2015-03-03 11:26
@razbakov, thank you for posting the issue. It is a duplicate of #1066, that's why it will be closed. Please refer to #1066 for further updates. By the way, checking PHP version is already fixed and will be available on public at the end of this week. Stay tuned!

**Closed by vpelipenko** 2015-03-03 11:26 UTC
Labels: bug, PS
