### ISSUE TITLE
When you select the checkbox for the category you want to assign, the check box for parent categories should be set automatically

### ISSUE THREAD

**Issue by loid345** [magento/magento2#30482] opened 2020-10-13 12:04 UTC
All versions of magento2

When selecting categories, it is logical that the product should also be displayed in the parent categories. But this is not happening. There is a high probability that the user will not check the box on the parent categories and the product will only be displayed on the page of one category, but it will not be displayed in the parent categories. To improve the user experience and reduce errors when selecting categories, checkboxes must be set automatically for parent categories in the category tree.

Selecting a single category
![2020-10-13_14-54-38](https://user-images.githubusercontent.com/20200970/95857911-f730e700-0d64-11eb-9626-71a0d4c8b0b3.png)

Choosing the right category
![2020-10-13_14-58-43](https://user-images.githubusercontent.com/20200970/95858141-47a84480-0d65-11eb-8e0f-2a7cd6ff1c75.png)

**Comment by magento-engcom-team** [comment] 2020-10-13 17:05
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38422` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2020-10-13 17:05
Hi @volanar. Thank you for your report.
This is good point to update user experience so Based on your suggestion I'm approved this as Feature Request

**Comment by pemann** [comment] 2020-10-16 06:52
With this change how could one differentiate if a product is set (also) to parent category or not? Or would this change mean that a product is set to parent categories automatically? I think it is a good idea to improve the graphical UI here, but proposed solution is not good. Parent (not explicitly checked) checkboxes should be gray or just the names could be bolded or something like that.

**Comment by volanar** [comment] 2020-10-16 16:21
> С этим изменением, как можно было отличить продукт (также) от родительской категории или нет? Или это изменение будет означать, что продукту автоматически присвоены родительские категории? Я считаю, что здесь неплохо улучшить графический интерфейс, но предлагаемое решение не подходит. Родительские флажки (явно не отмеченные) должны быть серыми, или просто имена могут быть выделены жирным шрифтом или что-то в этом роде.

I think this is an unnecessary feature. Any product created for a child category must be mapped to the parent category. Why complicate it?

**Comment by pemann** [comment] 2020-10-17 09:02
The amount of work that is required to order products in parent categories (by position) increases a lot if each product is also set to parent categories and those will have (default) position 0. This is a big change and will complicate the everyday life of developers and shop owners. Also it will have negative effect of performance since a product will have more categories, which means more joins etc in database. I think you should have a better reason for such a big change. I do agree that the UI of category selection should be made better, but I disagree that product should be automatically set to parent categories.

**Comment by volanar** [comment] 2020-10-17 12:20
> The amount of work that is required to order products in parent categories (by position) increases a lot if each product is also set to parent categories and those will have (default) position 0. This is a big change and will complicate the everyday life of developers and shop owners. Also it will have negative effect of performance since a product will have more categories, which means more joins etc in database. I think you should have a better reason for such a big change. I do agree that the UI of category selection should be made better, but I disagree that product should be automatically set to parent categories.

If I go to the phones category, I want to see all phones from all child categories, not an empty category. To improve performance, you need to optimize the category tree, and not leave the parent categories without products.

**Comment by pemann** [comment] 2020-10-19 05:06
@volanar if you set a category as "anchor", then it will show all the products from child categories.

**Comment by ProkopovVitaliy** [comment] 2020-10-26 12:50
@magento I am working on this

**Comment by sivaschenko** [comment] 2020-11-06 12:27
@volanar @ProkopovVitaliy I don't think this feature should be added as this behavior is handled by `Anchor` category option (`Display Settings` fieldset)

**Closed as completed** 2020-11-12 09:54 UTC
Labels: feature request, Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done
