### ISSUE TITLE
PageBuilder save very slow in Chrome

### ISSUE THREAD

**Issue by quanghien95** [magento/magento2#37798] opened 2023-07-25 09:12 UTC
### Preconditions and environment

- Magento version: 2.4.5-p2 and 2.4.6
- PageBuilder is enabled
- Chrome 112 and newer
- CMS page with pagebuilder content

### Steps to reproduce

1. Use Chrome version 112 or above
2. Edit CMS Page, Product or anything that has PageBuilder.
3. Save page. It takes very long time or save or loading forever. 
JS file is loading from the networks instead of browser cache, so that saving is very slow

### Expected result

The content saving quickly.
JS file should getting from browser cache

### Actual result

JS files always loading from the networks. 
The content saving very slow. Sometime its stuck forever.

### Additional information

I see that the issue happen when page builder rendering in iframe. Some js file is always loading from networks instead of browser cached. So that we have to spent more time to wait until all js file is loading correct. 
Sometime, when network is slow. The spin loading forever and the content is not save and we will lost the current work.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by quanghien95** [comment] 2023-07-25 09:15
@magento give me 2.4-develop instance
@magento I am working on this

**Comment by quanghien95** [comment] 2023-07-25 09:16
@magento add to contributors team

**Comment by hostep** [comment] 2023-07-25 09:36
Sounds like a duplicate of https://github.com/magento/magento2/issues/37516 ?

This might fix your issue: https://github.com/magento/magento2/issues/37516#issuecomment-1634682775

Let us know if that did the trick? And then close this ticket. Thanks! 🙂

**Comment by quanghien95** [comment] 2023-07-25 10:12
@hostep 
Thanks for your information. 
I read this issue #37516. But its not fix my issue. 
These js file always loading from networks instead of browser cache when page builder open. 
In case slow network. It can take very long time to save the cms content.
Let me update the issue description for more clear.

I can reproduce this issue in current 2.4-develop instance
Please kindly check this video screenshot:

https://github.com/magento/magento2/assets/11818221/7287fb9a-1072-4b7d-9b5d-e3be95d1145b

**Comment by quanghien95** [comment] 2023-07-25 10:47
This Is the PR to fixing this issue:
https://github.com/magento/magento2-page-builder/pull/854

**Comment by norgeindian** [comment] 2023-07-27 11:06
@quanghien95 , I included the fix, but unfortunately it did not change anything for me. The page still needs 30 secs to save. But I actually have the problem on product pages. Does that make a difference?

**Comment by quanghien95** [comment] 2023-07-27 11:57
@norgeindian 
This should be the same. You also need to apply this patch and patch #37516 together.
Check the network and make sure that some js file is loading correct from browser cache instead of from networks

**Comment by norgeindian** [comment] 2023-08-02 14:44
@quanghien95 , thanks for the clarification. With both patches together, it actually works. Thanks a lot for the fix.

**Comment by thanhndwgentech** [comment] 2023-08-17 12:17
Thank you! It works for me. The PageBuilder was very slow before

**Comment by thanhndmagento** [comment] 2023-08-17 12:18
Thank you! It works for me. The PageBuilder was very slow before

**Comment by engcom-Delta** [comment] 2023-09-14 12:36
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2023-09-15 08:46
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2023-09-15 12:05
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Issue occurs when page builder rendering in iframe. Some js file is always loading from networks instead of browser cached.


	1	Using Chrome version 112 or above
	2	Edit CMS Page, Product or anything that has PageBuilder.
	3	Save page. It takes very long time or save or loading forever. JS file is loading from the networks instead of browser cache, so that saving is very slow


https://github.com/magento/magento2/assets/51681379/3e917996-8492-4b8f-b159-b6ead65fae21
<img width="1435" alt="Screenshot 2023-09-15 at 3 00 56 PM" src="https://github.com/magento/magento2/assets/51681379/fa89a34a-f379-4727-8528-10e487b09783">

**Comment by norgeindian** [comment] 2023-10-12 08:51
Seems to be fixed in `2.4.5-p5`

**Comment by engcom-Bravo** [comment] 2024-12-26 06:28
Hi @quanghien95,

As per this comment https://github.com/magento/magento2/issues/39076#issuecomment-2361866133 issue has been fixed  hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-26 06:28 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Component: PageBuilder, Area: Content, Reported on 2.4.6
