### ISSUE TITLE
order is not coming in default order in magento 2 admin

### ISSUE THREAD

**Issue by TalibSaifi003** [magento/magento2#38559] opened 2024-04-01 12:42 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

I am facing an issue with order grid sorting in Magento 2 admin.
orders are not coming in default order. it should come in descending order but it's coming in ascending order.
please refer to the loom video.it will help you to understand the issue
https://www.loom.com/share/4a399cf9ca154022b7967ac89adf0600?sid=88e981f7-b09b-4a7d-97b3-c9eff4a155cd

### Expected result

the newest order should come on the top.

### Actual result

first order is coming on the top

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-04-02 03:30
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-04-02 03:43
Hi @TalibSaifi003,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Orders-Operations-Sales-Magento-Admin](https://github.com/magento/magento2/assets/51680745/a2532a44-1cc0-4a77-b938-57708f2a5b09)



![Orders-Operations-Sales-Magento-Admin (1)](https://github.com/magento/magento2/assets/51680745/6e03125f-cf20-4d12-bf30-cf7e856b91f7)



Sorting is working fine in both ascending order and descending order.

Kindly check the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible and check if any third party modules causing the issue.

Thanks.

**Comment by TalibSaifi003** [comment] 2024-04-02 17:18
Hii @engcom-Bravo 
i am getting issue on magento 2.4.3-p1 version.
did you check on that version

**Comment by engcom-Bravo** [comment] 2024-04-03 07:27
Hi @TalibSaifi003,

Thanks for your update.

It is recommended to verify the issues in Latest 2.4-develop instance and it might be issue has been fixed in Latest branch.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-04-15 05:35
Hi @TalibSaifi003,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-04-15 05:35 UTC
Labels: Issue: needs update, Reported on 2.4.x
