### ISSUE TITLE
Problem front page Bundle product

### ISSUE THREAD

**Issue by Danieleeffe1** [magento/magento2#35226] opened 2022-03-24 17:17 UTC
### Prerequisites (*)
<! ---
Magento 2.4.3-p1
->
1.
2.

### Steps to reproduce (*)
<! ---
Important: Provide a clear set of steps to reproduce this bug. We cannot provide support without clear instructions on how to reproduce.
->
1. I have created a product bundle

### Expected result (*)
<! --- Tell us what you expect to happen. ->
1. See The product bundle on the front page

### Current result (*)
<! --- Tell us what happened instead. Include error messages and problems. ->

When the bundle product is called on the front page it generates an error

The page displays this:

```
<div id="layer-product-list">
                    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":{"mode":"product_list_mode","direction":"product_list_dir","order":"product_list_order","limit":"product_list_limit","modeDefault":"grid","directionDefault":"asc","orderDefault":"label","limitDefault":12,"url":"https:\/\/m2.vetrinissime.it\/kit-vetrina.html","formKey":"oU1LxFKDabyAQ6YC","post":false}}'>
                                        <div class="modes">
                            <strong class="modes-label" id="modes-label">Mostra come</strong>
                                                <strong title="Griglia"
                            class="modes-mode active mode-grid"
                            data-value="grid">
                        <span>Griglia</span>
                    </strong>
                                                                <a class="modes-mode mode-list"
                       title="Lista"
                       href="#"
                       data-role="mode-switcher"
                       data-value="list"
                       id="mode-list"
                       aria-labelledby="modes-label mode-list">
                        <span>Lista</span>
                    </a>
                                        </div>
                        <p class="toolbar-amount" id="toolbar-amount">
            <span class="toolbar-number">1</span> elemento    </p>
                            <div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter">Ordina per</label>
    <select id="sorter" data-role="sorter" class="sorter-options">
                    <option value="position"
                                >
                Posizione            </option>
                    <option value="name"
                                >
                Nome prodotto            </option>
                    <option value="price"
                                >
                Prezzo            </option>
                    <option value="label"
                                    selected="selected"
                                >
                in evidenza            </option>
            </select>
            <a title="Imposta&#x20;la&#x20;direzione&#x20;decrescente"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span>Imposta la direzione decrescente</span>
        </a>
    </div>
                        </div>
    <script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": {"productType":["simple","virtual","downloadable","bundle","grouped","configurable"]}        }
    }
</script>
        <div class="products wrapper grid products-grid">
        <ol class="products list items product-items">
                                    <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_199"
                     data-container="product-grid">
                                                            <a href="https://m2.vetrinissime.it/kit-tropical-small.html"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <span class="product-image-container"
      style="width:240px;">
    <span class="product-image-wrapper"
          style="padding-bottom: 125%;">
                <img class="product-image-photo"
                        src="https://m2.vetrinissime.it/static/version1648141364/frontend/Firma/Vetrinissime/it_IT/Magento_Catalog/images/product/placeholder/small_image.jpg"
             max-width="240"
             max-height="300"
             alt="Kit TROPICAL small"/>
    </span>
</span>
                    </a>
                    <div class="product details product-item-details">
                                                <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="https://m2.vetrinissime.it/kit-tropical-small.html">
                                Kit TROPICAL small                            </a>
                        </strong>
                                                <div class="price-box price-final_price" data-role="priceBox" data-product-id="199" data-price-box="product-id-199">
            <p class="price-from">
            

<span class="price-container price-final_price&#x20;tax&#x20;weee"
        >
            <span class="price-label">Dal</span>
        <span  id="from-199"                data-price-amount="31.842001"
        data-price-type="minPrice"
        class="price-wrapper "
    ><span class="price">31,84 €</span></span>
        </span>
                    </p>
        <p class="price-to">
            

<span class="price-container price-final_price&#x20;tax&#x20;weee"
        >
            <span class="price-label">Al</span>
        <span  id="to-199"                data-price-amount="288.042004"
        data-price-type="maxPrice"
        class="price-wrapper "
    ><span class="price">288,04 €</span></span>
        </span>
                    </p>
    </div>
                        
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                                                            Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Flat::getLinkField() in /var/www/html/magento2/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php:1066
Stack trace:
#0 /var/www/html/magento2/vendor/magento/module-bundle/Model/Product/SingleChoiceProvider.php(42): Magento\Eav\Model\Entity\Collection\AbstractCollection->exportToArray()
#1 /var/www/html/magento2/vendor/magento/module-bundle/Plugin/Catalog/Model/Product/Type/AbstractType.php(46): Magento\Bundle\Model\Product\SingleChoiceProvider->isSingleChoiceAvailable()
#2 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Bundle\Plugin\Catalog\Model\Product\Type\AbstractType->afterIsPossibleBuyFromList()
#3 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Bundle\Model\Product\Type\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/html/magento2/generated/code/Magento/Bundle/Model/Product/Type/Interceptor.php(32): Magento\Bundle\Model\Product\Type\Interceptor->___callPlugins()
#5 /var/www/html/magento2/vendor/magento/module-catalog/Block/Product/AbstractProduct.php(137): Magento\Bundle\Model\Product\Type\Interceptor->isPossibleBuyFromList()
#6 /var/www/html/magento2/vendor/magento/module-catalog/Block/Product/ListProduct.php(383): Magento\Catalog\Block\Product\AbstractProduct->getAddToCartUrl()
#7 /var/www/html/magento2/vendor/magento/module-catalog/view/frontend/templates/product/list.phtml(85): Magento\Catalog\Block\Product\ListProduct->getAddToCartPostParams()
#8 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#9 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#10 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#11 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#12 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#13 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#14 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#16 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#17 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#18 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#19 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(525): Magento\Framework\View\Layout\Interceptor->renderElement()
#20 /var/www/html/magento2/vendor/magento/module-catalog/Block/Category/View.php(100): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#21 /var/www/html/magento2/vendor/magento/module-catalog/view/frontend/templates/category/products.phtml(15): Magento\Catalog\Block\Category\View->getProductListHtml()
#22 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#23 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#24 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#25 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#26 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#27 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#28 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#29 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#30 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#31 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#32 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#33 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(529): Magento\Framework\View\Layout\Interceptor->renderElement()
#34 /var/www/html/magento2/vendor/mageplaza/module-ajax-layered-navigation/view/frontend/templates/products.phtml(24): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#35 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/m...')
#36 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render()
#37 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView()
#38 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#39 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#40 /var/www/html/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#41 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#42 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#43 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#44 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#45 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#46 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#47 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#48 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#49 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#50 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#51 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#52 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#53 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#54 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#55 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#56 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#57 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#58 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#59 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#60 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#61 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#62 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#63 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#64 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#65 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#66 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#67 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#68 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#69 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#70 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#71 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#72 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#73 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#74 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#75 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#76 /var/www/html/magento2/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#77 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#78 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#79 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#80 /var/www/html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#81 /var/www/html/magento2/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#82 /var/www/html/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#83 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#84 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#85 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#86 /var/www/html/magento2/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#87 /var/www/html/magento2/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#88 /var/www/html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#89 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#90 /var/www/html/magento2/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#91 {main}
```

**Comment by engcom-November** [comment] 2022-03-25 09:25
Hi @Danieleeffe1 ,
Thank you for reporting and collaboration. However this issue looks like a duplicate of https://github.com/magento/magento2/issues/33935. Issue is reproducible for bundle products with same exception stack trace when Catalog - "Use Flat Catalog Product" set to 'Yes'. Kindly recheck and elaborate steps if different issue/steps to reproduce.
Thank you

**Comment by engcom-November** [comment] 2022-04-07 12:38
Hi @Danieleeffe1 ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-07 12:38 UTC
Labels: Issue: needs update
