### ISSUE TITLE
Filter navigation issue

### ISSUE THREAD

**Issue by eragag** [magento/magento2#36449] opened 2022-11-09 13:56 UTC
### Preconditions and environment

After Upgrade from 2.4.3-p1 to 2.4.5 or 2.4.5-p1
PHP8.1
Elasticsearch 7.10.x

### Steps to reproduce

Frontend:

I choose in Layered navigation Men-> Jackets and in Filter navigation Size XL
or i enter Jacket in the search box and choose size in the filter navigation

### Expected result

Now all men's jackets should be displayed in XL. 

If you enter in the search field jacket with filter navigation size XL all jackets in XL should be displayed. 

### Actual result

in the layered navigation, items are displayed correctly without any Filters
After entering a search string “Jacket”, an incorrect item count is displayed. 
With filter navigation "size xl" activated , many items are displayed that do not match the attribute "Size XL" with same incorrect item count and the query takes a long time up to 4 seconds. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-11-10 06:58
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-10 07:23
Hi @eragag ,

We are trying to reproduce the issue in 2.4-develop branch...But we are not able to reproduce the issue.
We got expected results....when we trying to filter with Size XL its displaying all the jackets....when we enter the product name with particular size its displaying all the products with the particular size.

Steps:
1.install magento instance
2.go to frontend
3.filter with size XL
4.enter the product name in search bar
5.its showing all the products with respective size and name

Screenshot:
<img width="1512" alt="Screenshot 2022-11-10 at 12 49 07 PM" src="https://user-images.githubusercontent.com/60198592/201026094-a22717c8-0a46-49b5-b5ac-463f0e873143.png">



let us know if we missing anything
thanks!!!

**Comment by eragag** [comment] 2022-11-11 10:10
Hi! Thanks for Answer

I can't reproduce the problem in the test environment either. The error occurs only with a large amount of products, in our case it is about 6000. 
I suspect that this is related to the attribute sets and number of attributes with filter navigation enabled.
 
Products that have few attributes are usually displayed correctly. The more complex the attribute sets of the products are, the more wrong products are displayed.

**Comment by engcom-Dash** [comment] 2022-11-14 06:15
Hi @eragag ,

We are tried as per your comment... we installed more then 6000 products with magento instance...we weorked the issue with magento 2.4.4 and we are getting same expected results.
Steps we followed:
1.Install magento instance
2.Install more then 6000 products
3.go to frontend
4.filter with Size Large
5.enter the product name in search bar
6.its showing all the products with respective size and name

Screenshots:
<img width="1512" alt="Screenshot 2022-11-14 at 11 26 05 AM" src="https://user-images.githubusercontent.com/60198592/201588214-39ce0eff-b5c8-4319-9392-2949e3a9a1e8.png">


<img width="1512" alt="Screenshot 2022-11-14 at 11 42 26 AM" src="https://user-images.githubusercontent.com/60198592/201588337-a59be969-0d8f-463f-af59-4f2c3043b0fb.png">


Let us know if we are missing anything!!!

Thanks!!!

**Comment by shane-clickingmad** [comment] 2022-11-18 12:34
Same issue here on a couple of 2.4.5-p1 sites.

One of the sites only has 71 total products so I dont think the quantity of products is a factor here.

Same issue with both PHP 8.0 and 8.1
Elastic Search 7.9.3

For us, navigating to a category page and selecting any filter doesnt narrow the results. Haven't been able to narrow it down.

**Comment by engcom-Dash** [comment] 2022-11-28 09:08
Hi @eragag ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2022-11-28 09:08 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
