### ISSUE TITLE
Bundle item options missing tax in cart and minicart

### ISSUE THREAD

**Issue by cfarnleitner** [magento/magento2#31994] opened 2021-02-08 19:48 UTC
### Preconditions
1. Magento 2.4.0
2. and Magento 2.4.1 (earlier versions not tested)
3. Magento 2.4-develop

### Steps to reproduce (*)
1. Create one or more simple products with a tax class (above 0%) and a price (excl tax)
2. Create a dynamic-price bundle product holding one or more of these simple products
3. Set display prices for cart (Display Prices) and catalog (Display Product Prices In Catalog) as "Including tax"
4. Provide catalog prices as "Excluding tax" (Calculation Settings -> Catalog Prices), i.e. prices in products entered without tax

### Expected result (*)
1. Add bundle product to cart
1. Minicart and Cart page likewise display bundle items ('item-options' listing) including tax (i.e. respect the Display Prices setting for bundle item options)

### Actual result (*)
1. Minicart and Cart page likewise display bundle item options excluding tax always,
Cart screen: ![image](https://user-images.githubusercontent.com/8795380/107271779-ff680d00-6a4c-11eb-8e73-a4eec82fcffd.png)
Mini cart screen: 
![image](https://user-images.githubusercontent.com/8795380/107272075-700f2980-6a4d-11eb-82c2-aa08edfa11f8.png)

reference screen from product detail view which in fact show correct taxation for bundle items (when configured accordingly): 
![image](https://user-images.githubusercontent.com/8795380/107271965-4a822000-6a4d-11eb-894b-55353a628be4.png)

As given in the screens, the tax calculation as such is correct. However, having bundle item options in cart displaying excluding tax when all other prices are displayed including tax will give customers a tough time when trying to figure out why the sum of bundle option items do not add up to the displayed row total.

**Comment by engcom-Delta** [comment] 2021-02-09 12:42
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-02-09 13:54
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40814` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saphaljha** [comment] 2021-02-11 18:54
@magento I am working on this issue

**Comment by real34** [comment] 2021-04-15 04:55
Hi!

@saphaljha did you have the opportunity to make some progress on this?

**Comment by mleger31** [comment] 2021-06-23 13:13
Hi @saphaljha, Have you made any progress in resolving this bug?
Thank you :)

**Comment by rsalmon42** [comment] 2021-08-10 12:16
Hi @saphaljha,
Could you share any progress on this issue ?
Thanks

**Comment by real34** [comment] 2021-12-03 15:10
Hi, any news on this?

**Comment by wzulauf** [comment] 2023-01-09 18:33
Hi, @saphaljha is there any news on this issue ?

**Comment by rsalmon42** [comment] 2023-10-26 09:17
Hi @saphaljha 
Could you share any progress on this issue ?
Thanks

**Comment by engcom-Bravo** [comment] 2024-07-11 05:23
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-11 05:55
Hi @cfarnleitner,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


**Steps to reproduce** 

- Create one or more simple products with a tax class (above 0%) and a price (excl tax)
- Create a dynamic-price bundle product holding one or more of these simple products
- Set display prices for cart (Display Prices) and catalog (Display Product Prices In Catalog) as "Including tax"
- Provide catalog prices as "Excluding tax" (Calculation Settings -> Catalog Prices), i.e. prices in products entered without tax



<img width="641" alt="Screenshot 2024-07-11 at 11 20 07" src="https://github.com/magento/magento2/assets/51680745/a4dbd45d-42ab-4137-8d72-1546172b247b">



<img width="1284" alt="Screenshot 2024-07-11 at 11 20 43" src="https://github.com/magento/magento2/assets/51680745/2931d85c-34e0-400a-9f05-47cd6ef883b2">



<img width="1284" alt="Screenshot 2024-07-11 at 11 21 45" src="https://github.com/magento/magento2/assets/51680745/97d1b32b-7e97-4a78-8baf-6a8784816d33">



MInicart and cart page showing including tax for bundle item options.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-11 05:55 UTC
Labels: Issue: Confirmed, Component: Pricing, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Tax
