### ISSUE TITLE
Frontend products are not sorted out by attribute sorting position

### ISSUE THREAD

**Issue by afavata** [magento/magento2#4641] opened 2016-05-23 13:43 UTC
### Preconditions (*)
Magento 2.3.x & 2.4-develop

### Steps to reproduce (*)
1. Magento theme luma or blank 
2. Create many colors as attribute (backend menu/store/product/color). Dispose a sorting sequence of colors by drugging one by one to the desired position in the list. Set "Used for Sorting in Product Listing" to yes. Save

3. Apply the different color attribute to as many products as possible.
4. Refresh Cache
5. Browse frontend web site to show all the products recently updated with the color.
6. Click on "sort order" and select "color".

### Expected result (*)
It's expected that products are shown in the frontend sorted out by the attribute position set in the backend.

Example: if in the backend color attribute is set in this manner: Red (1st position), Green (2nd position), Blue (3rd position), Black (4th position), etc. It's expected products are shown in the frontend in the same sequence: 
1st - all Red products 
2nd - all Green products
3rd - all Blue products
4th - all Black products

### Actual result (*)
The actual result is that all products are shown in the frontend sorted out by the color name.

Example: if in the backend color attribute is set in this manner: Red (1st position), Green (2nd position), Blue (3rd position), Black (4th position), etc. Result is that products are shown in the frontend in the following sequence: 
1st - all Black products 
2nd - all Blue products
3rd - all Green products
4th - all Red products

**Comment by afavata** [comment] 2016-10-25 12:49
any news on this issue...

**Comment by mukdam** [comment] 2017-05-13 05:41
any update

**Comment by smoskaluk** [comment] 2017-06-21 08:43
Thanks for posting, Internal ticket created MAGETWO-70040

**Comment by magento-engcom-team** [comment] 2017-10-05 11:30
@afavata, thank you for your report.
We've created internal ticket(s) MAGETWO-70040 to track progress on the issue.

**Comment by minhducck** [comment] 2018-03-26 09:37
Hi Guys, Is there any update on this issue?
I'm using Magento EE 2.1.9

**Comment by LuciferStrome** [comment] 2019-05-04 04:16
#dmcindia1

**Comment by LuciferStrome** [comment] 2019-05-04 04:17
#dmcdindia1

**Comment by LuciferStrome** [comment] 2019-05-04 04:18
i am working on it

**Comment by magento-engcom-team** [comment] 2019-12-10 09:17
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29609` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2020-02-07 07:33
@engcom-Charlie 
I see this issue was created in 2016, was confirmed on 2.1, 2.2, 2.3 and on 2.4.
I just tried to understand what's actually the issue is, how important it is - and it's quite hard for me to understand priority of it.

Could you add some screenshots? I think visually will be much easier to understand this issue.

**Comment by engcom-Charlie** [comment] 2020-02-07 09:29
Hi, @afavata I can't reproduce this issue by following steps:
1. Go to the default color attribute and add some colors(e.g. Red Blue Black Green)
![image](https://user-images.githubusercontent.com/51680850/74017083-3b7d1380-499c-11ea-8598-3fa6429ba237.png)
2. Change their position by drugging one by one to the desired position in the list
![image](https://user-images.githubusercontent.com/51680850/74017151-5a7ba580-499c-11ea-93a7-0513fd40177d.png)
3. Set "_Used for Sorting in Product Listing_" to **Yes**
(1)Red 2)Green 3)Blue 4)Black) and save
3. Add to attribute set
![image](https://user-images.githubusercontent.com/51680850/74017186-741ced00-499c-11ea-9bba-910268572cd1.png)
4. Apply the different color attributes to as many products as possible.
5. Check on the frontend with sort order by color
**Actual result**: Now it's work as expected.
![image](https://user-images.githubusercontent.com/51680850/74017025-1e484500-499c-11ea-8beb-f625412a47a7.png)
@ihor-sviziev @vikalps4 Now I test it again and the issue is not reproducible.

@vikalps4 if You agree with me could You close this issue?

**Comment by sdzhepa** [comment] 2020-07-17 16:34
Due to https://github.com/magento/magento2/issues/4641#issuecomment-583306796 issue is not reproducible on the latest `2.4-develop` code. 
There is no feedback or additional details.
Closed as cannot reproduce

**Closed as completed by sdzhepa** 2020-07-17 16:34 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Component: Search, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Event: dmcdindia1, Reproduced on 2.4.x
