### ISSUE TITLE
Cookies problem in backoffice after deploy in environments with Varnish

### ISSUE THREAD

**Issue by merodio7** [magento/magento2#34893] opened 2021-12-28 09:49 UTC
### Preconditions (*)
1. Magento 2.4.3p1  (but probably also with 2.4.3)
2. Varnish 

1. Admin User in backoffice, working as usual.
2. Deploy in PRE / PROD (the environments in which we have varnish). 
3. Admin User is shown a message "An error has happened during application run. See exception log for details". Backoffice is not available.
4. Admin User go to navigator --> options, delete the magento environment (PRE / PROD) cookies.
5. Admin User has backoffice available.

In the Integration server, we don't have Varnish and it seems this problem doesn't happen.

### Expected result 
1. Admin user can get into backoffice
### Actual result (*)
1. Backoffice like point 3 (not available)
![image](https://user-images.githubusercontent.com/29289358/147552830-f9a649a8-6597-4fca-9ccd-5892a5012c67.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-12-28 15:12
Hi @merodio7,

Thank you for reporting the issue.

We tried to reproduce the issue on Magento 2.4.3-p1/2.4-dev by using the steps provided but the issue is not reproducible on the fresh installation.
Please provide more detailed steps (error/system logs, screenshots) to reproduce this issue. 

Thanks

**Comment by merodio7** [comment] 2021-12-29 07:12
Hello,

In the test did you have Varnish? I think the problem happens with the
2.4.3p1 (and probably with 2.4.3) but it only happens in the preproduction
and production servers in which we have it installed. In the integration
server, I think I haven't seen the message. Also this is a new system, we
started with the version 2.4.2 (enterprise) and with this one i don't
remember to see the message.

My thoughts are that you are in a backoffice session, you have some
cookies, and then when a new deploy is done Magento looks for different
cookies than the cookies you have probably because varnish is doing a cache
or something like that.

Yours, Daniel

**Comment by engcom-Echo** [comment] 2022-01-12 06:35
Hi @merodio7,

We have tried this issue on the fresh installation with Varnish and without Varnish in both cases, Magento works fine.
Could you please provide the exact steps to reproduce the issue ? 

Thanks

**Comment by engcom-Hotel** [comment] 2022-01-31 15:47
Dear @merodio7,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-01-31 15:47 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by Giakie** [comment] 2022-05-09 09:25
I'm having the very same issue, the workaround is to clear all the cookies and refresh the page, but it's not something I can ask my client to do every time
thanks

**Comment by engcom-Hotel** [comment] 2022-05-20 14:40
Hello @Giakie,

Please let us know more about your issue. Please help us in the reproduction steps.

Thanks
