### ISSUE TITLE
Sales Emails going via wrong email address magento 2.2.x

### ISSUE THREAD

**Issue by RishiRanjan21** [magento/magento2#20251] opened 2019-01-12 12:55 UTC
Sales Emails going via wrong email address magento 2.2.x

e6hyxhdbac97@a2plvcpnl117217.prod.iad2.secureserver.net

**Comment by magento-engcom-team** [comment] 2019-01-12 12:55
Hi @Rtechhub. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Rtechhub do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by hostep** [comment] 2019-01-12 15:31
@Rtechhub: thanks for the report.

I'm closing this because it duplicates https://github.com/magento/magento2/issues/14952

There is a fix in the works in: https://github.com/magento/magento2/pull/18472 for Magento 2.2.x.
For Magento 2.3.x, this fix was recently approved: https://github.com/magento/magento2/pull/18471

**Closed as completed by hostep** 2019-01-12 15:31 UTC
Labels: Issue: Format is not valid
