### ISSUE TITLE
Product Filter by Name in Admin Panel Magento 2.1.10, 2.1.9

### ISSUE THREAD

**Issue by lalittmohan** [magento/magento2#12702] opened 2017-12-14 10:53 UTC
### Preconditions
1.Install Magento 2.1.9,2.1.10 with sample data with luma theme
2. Magento admin panel ->PRODUCTS->INVENTORY->CATALOG

### Steps to reproduce

1. Open catalog in admin panel to search products by name
2. Give space before type product name when search by filter in search box by name 
3. Give space two time after product type or use Capital letter or small letter instead of exact product name.
4.  Product filter by use Case-sensitive.
5.  If product have two words in name then if one space come after product name it's not searchable.

### Expected result

1. Product should be searched by name as sometimes space come by mistake.

### Actual result

1. Products doesn't filter by name.

**Comment by magento-engcom-team** [comment] 2017-12-14 11:47
@lalittmohan, thank you for your report.
The issue is already fixed in 2.3.0, 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-14 11:47 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
