### ISSUE TITLE
Any reason for not printing Exception Message in ObjectManager\Factory\AbstractFactory::createObject?

### ISSUE THREAD

**Issue by marvinhinz** [magento/magento2#26550] opened 2020-01-27 12:00 UTC
### Summary (*)
When debugging an error that prevents object creation, the original exception message is not printed, its just logged. I think it would improve the developer experience when working on cli code, to see the message instantly and not having it to look up in the log.

Source of the RuntimeException:
magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php::createObject

### Examples (*)
CLI Output: 
```
In AbstractFactory.php line 124:
  [Magento\Framework\Exception\RuntimeException]                               
  Type Error occurred when creating object:   
  Leonex\Import\Model\Transformer\ProductData\Categories
  Exception trace: [...]
```      
system.log:
                                                  
`[2020-01-27 11:36:15] main.CRITICAL: Type Error occurred when creating object: Leonex\Import\Model\Transformer\ProductData\Categories, Too few arguments to function Leonex\ETL\Logger\AbstractLog::__construct(), 0 passed in /srv/projects/rb/htdocs/magento/app/code/Leonex/Import/Model/Transformer/ProductData/Categories.php on line 63 and exactly 1 expected [] []`
                                                                

### Proposed solution
Printing the exception message too.

**Comment by engcom-Hotel** [comment] 2020-01-28 14:17
Hello @sdzhepa 
This issue looks like feature request. Could you transfer this issue to the feature request repository?
Thanks for collaboration!

**Comment by slavvka** [comment] 2020-05-21 00:01
Hi @marvinhinz. Thank you for your report. 
The issue has been fixed in magento/magento2#26572 by @marvinhinz in 2.4-develop branch
Related commit(s):
 - [f2b46df5b6a681d63e4254abdb13b49733574db1](https://github.com/magento/magento2/commit/f2b46df5b6a681d63e4254abdb13b49733574db1)
 - [00971d065a6cc353b83ace91dd65f06efe2640fe](https://github.com/magento/magento2/commit/00971d065a6cc353b83ace91dd65f06efe2640fe)
 - [f7f5696dc1241b886dc5bedefad8f39e691ea2c9](https://github.com/magento/magento2/commit/f7f5696dc1241b886dc5bedefad8f39e691ea2c9)
 - [f619400ac3282291a95885905d1fc44d7868c2fe](https://github.com/magento/magento2/commit/f619400ac3282291a95885905d1fc44d7868c2fe)
 - [6448147a2521ad3df0a876f20d6e02206451cbab](https://github.com/magento/magento2/commit/6448147a2521ad3df0a876f20d6e02206451cbab)

The fix will be available with the upcoming 2.4.0 release.

**Closed as completed by slavvka** 2020-05-21 00:01 UTC
Labels: Issue: Ready for Work, improvement, feature request, Issue: Confirmed, Issue: Format is valid, Component: ObjectManager, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S4, Triage: Done

**Comment by magento-engcom-team** [comment] 2020-05-21 23:21
Based on the provided information internal tickets `MC-34529` were created.

**Comment by magento-engcom-team** [comment] 2020-05-21 23:37
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34529` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._
