### ISSUE TITLE
Category products filter error

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [magento/magento2#6841] opened 2016-10-02 10:28 UTC
### Preconditions
1. Magento CE 2.1.1 without sample data is installed.
2. Test category is set up (Anchor: "Yes", Dispaly mode: "Product only")
3. Test products is created and set up (3 products with diffrent visability: "Catalog", "Search", "Catalog, Search")
4. Setup catalog:
   4.1. Configuration -> Catalog -> Catalog -> Products per Page on Grid Allowed Values = "2,3"
   4.2. Configuration -> Catalog -> Catalog ->Products per Page on Grid Default Value = "2"
### Steps to reproduce
1. In category page you will see 2 products
2. In paginator you will see "Items 1-2 of 3" and 2 pages. In second page "We can't find products matching the selection."
3. In layer navigation you will see price filter with 3 products

**But 3 products never show on category page, because one of product have visability "Search"**
### Expected result
1. In category page you will see 2 products
2. In paginator I expected to see "2 Items" and 1 pages
3. In layer navigation I expected to price filter with 2 products

**Comment by dthampy** [comment] 2016-10-24 23:20
Thank you for the detailed bug report. Internal jira ticket ->MAGETWO-60031

**Comment by alithenu** [comment] 2017-08-15 07:04
This issue solved?if yes, what was the solution?pls help

**Comment by Serhiy-Nazarov** [comment] 2017-08-22 14:15
@veloraven
Is this bug fixed in 2.1.8?
http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html
"The Category page now displays the correct total count of products."

**Comment by cs5chester** [comment] 2017-08-22 14:43
In 2.1.8 problem still appears.

**Comment by magento-engcom-team** [comment] 2017-10-04 11:30
@Serhiy-Nazarov, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-04 11:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is not valid
