### ISSUE TITLE
SSL cert error - xampp

### ISSUE THREAD

**Issue by nmallepally** [magento/magento2#4834] opened 2016-06-02 13:27 UTC
I have installed magento 2 on localhost xampp. When i try to connect to the magneto market place using web setup wizard ->system configuration, ti gives me an ssl error saying that (SSL certificate problem: unable to get local issuer certificate). Can you help me resolve this, im attaching the same as well.
![ssl cert error](https://cloud.githubusercontent.com/assets/19605497/15746341/0e3b3ea8-28ce-11e6-8a53-2d70321781b3.png)

**Comment by antonlazarchenko** [comment] 2016-06-02 14:53
http://curl.haxx.se/ca/cacert.pem - copy the whole page and save it in a: "cacert.pem" file.
Then in your php.ini file insert or edit the following line: curl.cainfo = "[pathToThisFile]\cacert.pem"

I suppose this is not an issue. :)

**Comment by nmallepally** [comment] 2016-06-02 16:06
okay, thank you. i thought this was an issue with magento 2. 
After adding that, it still gives me an error. (error setting certificate verify locations: CAfile: C:\xampp\apache\conf\extra\cacert.pem CApath: none ) if you can give me a possible help to this, it will be great thanks a mil.

**Comment by antonlazarchenko** [comment] 2016-06-02 16:09
@nmallepally, give me configuration string from php.ini and location of your cacert.pem file.
Also make sure you restarded apache after changing php.ini.

**Comment by nmallepally** [comment] 2016-06-02 16:15
here is my file
[php.txt](https://github.com/magento/magento2/files/296028/php.txt)

**Comment by antonlazarchenko** [comment] 2016-06-02 16:24
Don't know. If you really placed there correct file with correct content and restarted apache - everything should be ok. I did exactly the same and it works.

**Comment by nmallepally** [comment] 2016-06-02 16:31
Hi
okay .did you check the file which i sent you?. Is that correct??. I have restarted the Apache but it shows me an error. still, or is it something with file encoding??.

**Comment by nmallepally** [comment] 2016-06-02 16:44
it worked for me thank you. Thats brilliant and thanks a mil.
can you give me any reference for fixing this errors.
![error update](https://cloud.githubusercontent.com/assets/19605497/15753168/945eeb0e-28e9-11e6-80a2-e5cb4c065580.png)

**Comment by mebbopakko** [comment] 2016-07-06 10:14
@antonlazarchenko Thanks your solution worked like a charm for me :)

**Comment by andimov** [comment] 2016-08-16 15:49
@antonlazarchenko 
Thanks for assistance!
@mebbopakko 
I'll close this issue as 'not a bug'. Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-08-16 15:49 UTC

**Comment by dheeraj17** [comment] 2016-11-13 10:15
i am having a similar problem...i have already followed the above steps but still i am getting another issue....it says..."error setting certificate verify locations: CAfile: C:\xampp\apache\conf\extra\cacert.pem CApath: none"..pls help! thanks..:)
