### ISSUE TITLE
Sales Order shipping address region_code

### ISSUE THREAD

**Issue by jhildreth** [magento/magento2#3969] opened 2016-04-01 15:34 UTC
The shipping address returned under extension_attributes on a sales order retrieved via the API in 2.0.4 seems to include the full state name for U.S. states in both the "region" and "region_code" properties.

I expected "region_code" to include the two-character state abbreviation ("VT" instead of "Vermont" for example).

**Comment by piotrekkaminski** [comment] 2016-06-09 23:29
Internal ID MAGETWO-54153

**Comment by magento-engcom-team** [comment] 2017-10-20 11:30
@jhildreth, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-20 11:30 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
