### ISSUE TITLE
Magento throws 'No such entity' when add to cart product (after upgrade version 2.4.7 p2)

### ISSUE THREAD

**Issue by dilipjha100** [magento/magento2#39117] opened 2024-08-27 12:34 UTC
### Preconditions and environment

version 2.4.7 p2)
after upgrade Magento 2.4.7 p2 form magento 2.4.6-p5 
I have got the error message 'No such entity with customerId = ' but product are added to cart.products

### Steps to reproduce

![image](https://github.com/user-attachments/assets/8462cb0d-0e77-410f-b597-644ed6f61f8b)

### Expected result

![image](https://github.com/user-attachments/assets/e0984c39-dbdc-4b6b-b64e-0dc5bdbb20ca)

### Actual result

When add to cart i have got the error message .

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-04 09:35
Hi @dilipjha100,

Thanks for your reporting and collaboration.

We have verified the issue and the issue is not reproducible.Kindly refer the screenshots.

We are able to add the product to the cart.

<img width="1427" alt="Screenshot 2024-09-04 at 13 44 26" src="https://github.com/user-attachments/assets/ca14da5b-9725-4b27-b200-dcef14d83553">


Kindly recheck the issue if any third party modules causing the issue and let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-16 05:59
Hi @dilipjha100,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-16 05:59 UTC
Labels: Issue: needs update, Reported on 2.4.7-p2
