### ISSUE TITLE
Free shipping cart rules do not apply

### ISSUE THREAD

**Issue by Larke12** [magento/magento2#37945] opened 2023-08-31 18:52 UTC
### Preconditions and environment

- Magento 2.4.6-p1
- Setup free shipping promotion as denoted in documentation: https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-free-shipping.html

### Steps to reproduce

1. Setup a cart rule for all customer groups with no coupon, following the setup as denoted in the documentation.
2. Ensure shipping methods with cost are available: Flat Rate and/or Table Rates.
3. Add product(s) to cart that triggers the condition (i.e. If All of these conditions are True: Subtotal equals or greater than 50)
4. Provide estimated shipping information or full shipping address, view shipping costs.

### Expected result

All shipping methods with cost should show as $0.00 or on selection denote a deduction of equal value.

### Actual result

No discount is applied to offer free shipping on any methods.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-01 10:29
Hi @Larke12,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Setup a cart rule for all customer groups with no coupon, following the setup as denoted in the documentation.
- Ensure shipping methods with cost are available: Flat Rate and/or Table Rates.
- Add product(s) to cart that triggers the condition (i.e. If All of these conditions are True: Subtotal equals or greater than 50)
- Provide estimated shipping information or full shipping address, view shipping costs.


![Test-Promotions-Marketing-Magento-Admin (4)](https://github.com/magento/magento2/assets/51680745/6a00df13-02c7-4d65-a106-f86372508bec)




![Shopping-Cart (9)](https://github.com/magento/magento2/assets/51680745/d2f18716-fa03-4a13-891c-fb8cba6dfb9b)




All shipping methods showing $0 as a shipping costs.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by TiffanyElNino** [comment] 2023-09-07 11:49
@Larke12 I encountered the same problem with 3rd party shipping methods, maybe it helps you as well. These custom shipping methods were setting their rate based on the comparison `$request->getFreeShipping() === true`, but in some responses the result of getFreeShipping() is an int(1), due to a [recent string cast change](https://github.com/magento/magento2/commit/bd149447d03f30dfd7cbda19c28a8140a87e0c9f) which results in a false expression.

**Comment by engcom-Bravo** [comment] 2023-09-08 11:07
@TiffanyElNino Thanks for your contribution & collaboration over here.

Hi @TiffanyElNino,

Can you please provide latest update on this comment https://github.com/magento/magento2/issues/37945#issuecomment-1702531112 and also please check issue is causing due to any third party extensions if so please refer the solution here https://github.com/magento/magento2/issues/37945#issuecomment-1710011886.

Please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-12 06:14
Hi @Larke12,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-12 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
