### ISSUE TITLE
catalog inventory_stock_status is completely redundant

### ISSUE THREAD

**Issue by gibbotronic** [magento/magento2#25752] opened 2019-11-26 10:48 UTC
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Look at the database table

### Expected result (*)

1. No data duplication. 
2. A sensible database structure.
3. Useful comments against columns so that you know what the column is for.

### Actual result (*)

1. The table is a repeat of catalog_stock_item for no obvious reason.

Related to https://github.com/magento/magento2/issues/4916 (which was inexplicably closed without rectifying this issue 3 years ago), the cataloginventory_stock_status table still has:
- a floating stock_id (not linked to anything via a FK, eg. cataloginventory_stock.stock_id would be good)
- a floating website_id (not linked to anything via FK, eg. store_website.website_id would be good), seems to be a complete duplicate of cataloginventory_stock.website_id anyway!
- qty is a duplicate of cataloginventory_stock_item.qty but as there is no relationship between the two it would be possible to update one and not the other - inconsistency!
- stock_status is .....? who knows??? Is it an enum of some sort? db_schema.xml for CatalogInventory reveals nothing about the table and the comments merely repeat the column name (next to useless) so who knows what it's for?

The table looks like it could be dropped with no adverse effects. From profiling I can see that it is used but have no idea why because all of the data in it appears to be held in catalog inventory_stock_item already.

**Comment by gibbotronic** [comment] 2019-11-26 10:48
> do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
Yes

This table is visible on 2.3.2 in its current baffling form.

**Comment by engcom-Charlie** [comment] 2019-11-28 09:52
Hello @gibbotronic 
Could you make a PR for this issue?

**Comment by magento-engcom-team** [comment] 2019-11-28 09:53
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29242` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mattijv** [comment] 2019-12-03 10:01
@gibbotronic The `cataloginventory_stock_status` is used as an index table, i.e. it contains precalculated values for the stock status of the product (is it considered to be in stock or out of stock) and the qty. Determining these values from the cataloginventory_stock_item can require some costly logic and is therefore precalculated into the the status table with the `cataloginventory_stock` indexer.

Why Magento has the website_id and stock_id columns in the table when they are essentially hard coded to values 0 and 1 respectively is a separate question. I think they are/were for future proofing, but seems like the MSI decided to implement multiple stocks differently?

I'm not super knowledgeable on this part of Magento, so apologies is some of that is wrong.

**Comment by mattijv** [comment] 2019-12-04 10:28
To add: I think this is a non-issue and should be closed.

**Comment by sdzhepa** [comment] 2020-08-18 21:09
Closed due to https://github.com/magento/magento2/issues/25752#issuecomment-561092265 https://github.com/magento/magento2/issues/25752#issuecomment-561576861

**Closed as completed by sdzhepa** 2020-08-18 21:09 UTC
Labels: Issue: Ready for Work, improvement, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: DB
