### ISSUE TITLE
Language switcher redirects to the homepage on Magento 2.2.5

### ISSUE THREAD

**Issue by genyuk** [magento/magento2#16758] opened 2018-07-12 17:34 UTC
### Preconditions
Fresh Magento 2.2.5 install with just two test categories.

### Steps to reproduce
1. Go to any category or product page
http://goodolddisc.com/video-games.html

2. Switch to another language (let's say en->fr)

3. Switch the language one more time (fr->en)

### Expected result

1. Expecting to be on the same product or category page 

### Actual result

1. Switcher redirects to the home page

it is reopen of issue #16454

**Comment by magento-engcom-team** [comment] 2018-07-12 17:34
Hi @genyuk. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@genyuk do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by larsroettig** [comment] 2018-07-12 21:47
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-07-12 21:47
Hi @larsroettig. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-07-12 21:47
Hi @larsroettig, here is your [Magento instance](https://i-16758-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16758-2-2-5.engcom.dev.magento.com/admin](https://i-16758-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by larsroettig** [comment] 2018-07-12 22:18
Hi Community Team,
i can reproduce this Issue.

- Install Blank 2.2.5 install
- Create a new Storeviews set and assign this to **Main Website Store**
<img width="1318" alt="stores___settings___stores___magento_admin" src="https://user-images.githubusercontent.com/5289370/42662376-ab3b8baa-8631-11e8-8da2-0c2104391e32.png">

1. Enable Stores - Configuration - General - Add Store Code to Urls
2. Create new empty category page
3. Go to Frontend - default store in your category page
4. Switch Store 

### Expected result
Expecting to be on the same product or category page

### Actual result
Switcher redirects to the home page

**Comment by larsroettig** [comment] 2018-07-12 22:31
Hi @genyuk i close your issue is duplicated by #14674

**Closed as completed by larsroettig** 2018-07-12 22:31 UTC
Labels: bug report, Issue: Clear Description, Reproduced on 2.2.x, Issue: Format is valid, Release Line: 2.2, Component: Store

**Comment by realGomez** [comment] 2018-07-19 04:34
Which guy solved this issue? I have a similar issue.2.2.2[#16454](https://github.com/magento/magento2/issues/16454)； same issue in2.2.5.

**Comment by realGomez** [comment] 2018-07-24 05:07
rewrite  \Magento\Catalog\Controller\Adminhtml\Category\Save;  
`class Save extends \Magento\Catalog\Controller\Adminhtml\Category\Save
{
    private function resolveCategoryId()
    {
        $categoryId = (int)$this->getRequest()->getParam('id', false);

        return $categoryId ?: (int)$this->getRequest()->getParam('entity_id', false);
    }

    protected function _initCategory($getRootInstead = false)
    {
        $categoryId = $this->resolveCategoryId();
        $storeId = (int)$this->getRequest()->getParam('store',$this->getRequest()->getParam('store_id'));
        $category = $this->_objectManager->create(\Magento\Catalog\Model\Category::class);
        $category->setStoreId($storeId);

        if ($categoryId) {
            $category->load($categoryId);
            if ($storeId) {
                $rootId = $this->_objectManager->get(
                    \Magento\Store\Model\StoreManagerInterface::class
                )->getStore(
                        $storeId
                    )->getRootCategoryId();
                if (!in_array($rootId, $category->getPathIds())) {
                    // load root category instead wrong one
                    if ($getRootInstead) {
                        $category->load($rootId);
                    } else {
                        return false;
                    }
                }
            }
        }

        $this->_objectManager->get(\Magento\Framework\Registry::class)->register('category', $category);
        $this->_objectManager->get(\Magento\Framework\Registry::class)->register('current_category', $category);
        $this->_objectManager->get(\Magento\Cms\Model\Wysiwyg\Config::class)
            ->setStoreId($this->getRequest()->getParam('store'));
        return $category;
    }
}`



first rewrite your top category url key（example shoes  -> shoespc）;click save button;Restore the URL back to its original（example sshoespc  -> shoes） and save it again. That's OK.

**Comment by krnshah** [comment] 2018-07-25 06:20
Still i have facing the same issue in magento 2.2.5. it will redirect to home page while using the language switcher. do we have any other solution for this???

**Comment by archonkulis** [comment] 2018-08-14 04:51
I can also reproduce the same issue. At first, I thought the issue is because I had set different URLs for different store views ( although even this worked on 2.2.3 ), but I tried also with the same URLs for different store views and still was redirected to the homepage. The client says it wasn't like this on 2.2.3.. c'mon, guys. Minor upgrade and he reported a few bugs already.

**Comment by doeri** [comment] 2019-05-04 16:59
Hello everybody!

Do we have a solution for this issue?
I am encountering the same issue on Magento 2.3.1

I have created two pages with the same url and assigned different stores for each page, however it still redirects to home.

Could I have your assistance here please?
