### ISSUE TITLE
Backend product grid filter qty 0

### ISSUE THREAD

**Issue by rikwillems** [magento/magento2#11814] opened 2017-10-27 12:22 UTC
I want to filter my products in the backend to show all products that have a quantity of 0.

### Steps to reproduce
Have a product with qty = 0
Set filter Quantity from: 0
Set filter Quantity to: 0

### Expected result
Filtered product to show the product with qty = 0

### Actual result
All products are shown.

**Comment by magento-engcom-team** [comment] 2017-10-27 12:39
@rikwillems, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-27 12:39 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
