### ISSUE TITLE
Login as Customer from Admin is not working for 1st time when Store URL is changed in Magento multi store steup 

### ISSUE THREAD

**Issue by engcom-November** [magento/magento2#34848] opened 2021-12-20 10:35 UTC
### Preconditions (*)

1. Magento 2.4-develop having multi Store setup

### Steps to reproduce (*)

1. Stores - Configuration - Customer Configuration - Share Customer Accounts - Set to Website and Save
2. Stores - Configuration - Customers - Enable Login as Customer and set Store To Login To - "Auto-detection" - Save
3. Front end - Create a Customer in 2nd Store website
4. Admin - Stores - Configuration - General - Web - Change scope to 2nd Store view - change Base URLs & Base URLs (Secure) - Enter URL's with same URL of 1st Store URL and Save
5. Reindex and clear cache
6. Admin - Customers - All Customers - Edit 2nd Store customer - Login as Customer - **No issue. User is logged in to store front.**
7. Close session  
8. Now change back the URL's of 2nd Store to old values and Save (Admin - Stores - Configuration - General - Web - Change scope to 2nd Store view - change Base URLs & Base URLs (Secure) to old URL values)
9. Clear cache
8. Open Front end - 1st website Store
9. Go to - Admin - Customers - All Customers - Edit 2nd Store customer - Login as Customer - **Issue: User is not logged in. User is displayed with login page to sign in**

### Expected result (*)

1. [Screenshots, logs or description]
2. User should be logged in to 2nd store

### Actual result (*)

1. [Screenshots, logs or description]
2.Issue: User is not logged in. User is displayed with login page to sign in
![image](https://user-images.githubusercontent.com/60198231/146753822-01c7a681-1e34-4de1-bcc9-d27dc9c6adb5.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vass30** [comment] 2021-12-29 13:42
@magento I am working on this

**Comment by vass30** [comment] 2022-02-23 15:44
Hello @engcom-Alfa 
I could not get the result described in the ticket because after manipulations with Base Url  customer remains logged in..

**Comment by engcom-Bravo** [comment] 2024-09-24 07:41
@vass30 Thanks for your Contribution!!.

As per this comment https://github.com/magento/magento2/issues/34848#issuecomment-1048920521 issue is no more reproducible.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-24 07:41 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Component: LoginAsCustomer, Progress: done, Reported on 2.4.x, Area: Account
