### ISSUE TITLE
Call to a member function getTypeId() on bool

### ISSUE THREAD

**Issue by sannam-wesco** [magento/magento2#37626] opened 2023-06-16 16:15 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- Execute Graphql Mutation from Postman
- 

### Steps to reproduce

1. Requisition Lists, addProductsToRequisitionList → Add a valid SKU that is not isVisibleInCatalog
2. What is happening:
  a. \Magento\RequisitionList\Model\RequisitionListProduct::getProduct will return false
  b. \Magento\GroupedRequisitionList\Plugin\Model\RequisitionListItem\SaveHandler::aroundSaveItem will  try to access the product getTypeId property. But since product is false, the process crashes.

### Expected result

1. it should not report as an error back in response "report.ERROR: Call to a member function getTypeId()".

### Actual result

1. Getting error as "report.ERROR: Call to a member function getTypeId() on bool"

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Adward345** [comment] 2023-06-17 08:53
The error message "Call to a member function getTypeId() on boo" typically indicates that you are trying to invoke the getTypeId() method on a variable or object that is not of the expected type or does not have that method defined.

The error message suggests that the variable or object in question is of type "boo" instead of the expected type. It's important to ensure that you are working with the correct object or variable and that it has the necessary methods defined.

To troubleshoot this issue, you can follow these steps:

Check the variable or object: Verify the variable or object you are trying to invoke the getTypeId() method on. Make sure it is the correct object and that it is instantiated properly.

Review the object's definition: Examine the class or object definition to ensure that the getTypeId() method is actually defined within that class. Check for any typos through[ viptools-apk](https://topfollowapks.net/viptools-apk/) or incorrect method names.

**Comment by engcom-Bravo** [comment] 2023-06-21 10:52
@Adward345 Thanks for your contribution & collaboration over here.

Hi @sannam-wesco,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Requisition Lists, addProductsToRequisitionList → Add a valid SKU that is not isVisibleInCatalog


We have created a product with visibility as **Not Visible Individually**


<img width="1397" alt="Screenshot 2023-06-21 at 3 29 35 PM" src="https://github.com/magento/magento2/assets/51680745/d494e04c-fb8f-4fe7-8cf2-d556f88c739e">


We are not getting any error in the response.

<img width="1087" alt="Screenshot 2023-06-21 at 3 26 46 PM" src="https://github.com/magento/magento2/assets/51680745/03fd4796-a2af-408f-bc2e-c47cd1b20541">


Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by sannam-wesco** [comment] 2023-06-21 15:17
@engcom-Bravo 

Issue is still exist. 

Steps to reproduce
1. in Magento Admin side. go to products -> Edit any product and disable the product. 

![image](https://github.com/magento/magento2/assets/126261786/058f801b-b491-4150-bc4e-6b6e731cf9ea)

**Comment by engcom-Bravo** [comment] 2023-06-22 08:10
Hi @sannam-wesco,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance with ee edition and the issue is not reproducible.Kindly refer the screenshots.



**Steps to reproduce**

- in Magento Admin side. go to products -> Edit any product and disable the product. to make it inVisibleInCatalog to No
- Go to postman and try to add that product to requisition list.

We have disabled the product Simple.

<img width="1400" alt="Screenshot 2023-06-22 at 12 55 06 PM" src="https://github.com/magento/magento2/assets/51680745/e5016e49-22d3-46b2-928e-51668895f4b9">

We are getting as `The SKU was not found`.

<img width="1031" alt="Screenshot 2023-06-22 at 12 54 57 PM" src="https://github.com/magento/magento2/assets/51680745/8497601e-c78e-4fc1-b9cc-cb8d8667aa41">



Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-06 05:37
Hi @sannam-wesco,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-06 05:37 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
