### ISSUE TITLE
Can not set Negative number for Out of stock threshold

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#25866] opened 2019-12-01 14:52 UTC
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

As this document: the out of stock threshold can be negative number
https://docs.magento.com/m2/ce/user_guide/catalog/inventory-backorders.html#out-of-stock-threshold

1. Go to backend
2. Store->configurations
3. Catalog -> Inventory
4. in Product Stock Options, set "Backorders" is "Allow qty below 0" and  Out of stock threshold is -8
5. Save

### Expected result (*)

1. Save -8 to config
### Actual result (*)

1. Save 0 to config

**Comment by krishprakash** [comment] 2019-12-01 15:36
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-01 15:36
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-01 15:37
Hi @krishprakash, here is your [Magento instance](https://i-25866-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25866-2-3-develop.instances.magento-community.engineering/admin](https://i-25866-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-12-01 15:43
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29288` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment] 2019-12-02 22:18
Closing as duplicate of magento/magento2#25158

**Closed as completed by dmytro-ch** 2019-12-02 22:18 UTC
Labels: Issue: Ready for Work, Component: Config, duplicate, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Backend
