### ISSUE TITLE
Unable to modify articles

### ISSUE THREAD

**Issue by Fluidhub** [magento/magento2#38955] opened 2024-07-19 14:12 UTC
### Preconditions and environment

- Magento version ver. 2.4.4-p2

### Steps to reproduce

1. Open catalogue
2. Select a product and modify
3. Save

### Expected result

Have the modify saved

### Actual result

Modifications cannot be saved

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-07-23 05:36
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-07-23 06:17
Hi @Fluidhub 

Thanks for reporting and collaboration.

Verified the issue on Magento 2.4 dev instance but the issue is not reproducible.

Steps to reproduce

1. Open catalogue
2. Select a product and modify
3. Save

Able to modify the products and save successfully.

Please refer to the attached screen recording and let us know if we missed anything.


https://github.com/user-attachments/assets/7c167426-19ff-4590-bff3-3ef367666b2c

**Comment by engcom-Bravo** [comment] 2024-08-08 05:38
Hi @Fluidhub,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-08 05:38 UTC
Labels: Issue: needs update, Reported on 2.4.4-p2
