### ISSUE TITLE
Redis data error in all of our environments as of yesterday

### ISSUE THREAD

**Issue by TonyDeStefano** [magento/magento2#33250] opened 2021-06-15 20:10 UTC
### Preconditions (*)

1. Magento 2.2

### Steps to reproduce (*)

We can no longer deploy our magento instance in any of our environments. Even with unchanged code. We get this error every time:

php bin/magento
Warning: snappy_uncompress : data error in /var/www/html/magento/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php on line 1239

I tried changing from "snappy" to all other compression options and get the same error except snappy is replaced by the other method (like gzip, etc) 

### Expected result (*)

That we can run setup:upgrade

### Actual result (*)

We cannot run setup:upgrade

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-06-23 09:36
Hi @TonyDeStefano ,

Please provide the complete steps to reproduce this issue.

**Comment by engcom-Hotel** [comment] 2021-07-15 11:16
Hello @TonyDeStefano,

We are unable to get a response from you since last more than 14 days. So we are closing this issue for now.

If you still facing the issue, either you can reopen it or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-15 11:16 UTC
Labels: Issue: needs update
