### ISSUE TITLE
Magento 2.4..3-p1|2 PayflowPro returns 117 - Failed Merchant Rule Check

### ISSUE THREAD

**Issue by gitchrisqueen** [magento/magento2#36357] opened 2022-10-21 20:30 UTC
### Preconditions and environment

Magento version - 2.4.3-p1
Paypal Payflow Pro Account Transaction Settings:
- Allow Non-referenced Credits:  No
-  Credits may exceed original transaction amount: No
- Allow reference transactions: Yes

The 2nd authorization amount fails with "Failed Merchant Rule Check" error. This is not the prior secure token transaction request for $0 which does succeed.

### Steps to reproduce

- Fresh install Magento 2.4.3.p1|p2
- Install sample data
- Plug in PayPal Payflow Pro credentials, set to test mode. Submit a credit card order with their test cards
- Place order

### Expected result

Order is placed with the correct AMT sent to paypal

### Actual result

Initial AMT sent is always $0. Then second AMT is sent with the order amount but fails with a 117 error code response from paypal.

Here's a Payflow Pro response dump with some omitted personal data:

array (
'request' =>
array (
'user' => '',
'vendor' => 'removed',
'partner' => 'removed',
'pwd[14]' => 'removed',
'verbosity' => 'HIGH',
'BUTTONSOURCE' => 'Magento_2_Enterprise',
'tender' => 'C',
'trxtype' => 'A',
'amt' => 0,
'currency' => 'CAD',
'createsecuretoken' => 'Y',
'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
'returnurl' => 'url removed/',
'errorurl' => 'url removed',
'cancelurl' => 'url removed',
'disablereceipt' => 'TRUE',
'silenttran' => 'TRUE',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'street' => '101 C st',
'city' => 'montrel',
'state' => 'MB',
'zip' => 'GA1',
'country' => 'CA',
'email' => '[daklkdlsl@gmail.com](mailto:daklkdlsl@gmail.com)',
'shiptofirstname' => 'Semetics',
'shiptolastname' => 'Sam',
'shiptostreet' => '101 C st',
'shiptocity' => 'montrel',
'shiptostate' => 'MB',
'shiptozip' => 'GA1',
'shiptocountry' => 'CA',
),
'result' =>
array (
'result' => '0',
'securetoken' => '4mdwUGfoBPUiZkuMqtna9gQN4',
'securetokenid' => 'JE2l2eMJuCUbK70vg02WLvaNmLmanM7V',
'respmsg' => 'Approved',
'result_code' => '0',
),
) [] []
array (
'request' =>
array (
'user' => '',
'vendor' => 'removed',
'partner' => 'removed',
'pwd[14]' => 'removed',
'verbosity' => 'HIGH',
'BUTTONSOURCE' => 'Magento_2_Enterprise',
'tender' => 'C',
'custref' => '8000582462',
'invnum' => '8000582462',
'comment1' => '8000582462',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'street' => '101 C st',
'city' => 'montrel',
'state' => 'MB',
'zip' => 'GA1',
'country' => 'CA',
'email' => '[daklkdlsl@gmail.com](mailto:daklkdlsl@gmail.com)',
'shiptofirstname' => 'Semetics',
'shiptolastname' => 'Sam',
'shiptostreet' => '101 C st',
'shiptocity' => 'montrel',
'shiptostate' => 'MB',
'shiptozip' => 'GA1',
'shiptocountry' => 'CA',
'trxtype' => 'A',
'origid' => 'B70PB0FE7CC5',
'amt' => '44.87',
'currency' => 'CAD',
'itemamt' => '32.73',
'taxamt' => '2.14',
'freightamt' => '10.00',
'discount' => '0.00',
),
'result' =>
array (
'result' => '117',
'pnref' => 'B10PB28CDE88',
'respmsg' => 'Failed merchant rule check',
'transtime' => '2022-10-20 11:03:41',
'firstname' => 'Semetics',
'lastname' => 'Sam',
'amt' => '44.87',
'cardtype' => '0',
'result_code' => '117',
),
) [] []

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-25 11:16
Hi @gitchrisqueen ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but the issue is not reproducible.
Payflow payment is working fine in test mode and after successful payment 4 entries are logged in payment.log file. 2 entries are the authorization request and redirect sent to paypal with AMT=0 which is not effecting the payment transaction or anywhere. 4th entry in log file is the actual payment details request/response where AMT is being correctly sent. No 117 error "Failed Merchant Rule Check" has been observed in the payment.log file.
![image](https://user-images.githubusercontent.com/60198231/197759073-8cfad0e4-6ee3-40a5-b3d7-5cb205cce8af.png)

Kindly recheck the issue on Magento 2.4-develop instance as it is the upcoming 2.4.x release and have latest code base and provide missing steps / configuration details if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-11-08 04:36
Hi @gitchrisqueen ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-08 04:36 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
