### ISSUE TITLE
Credit card type not detecting after entering 4 digits for master card and discover card

### ISSUE THREAD

**Issue by tavantlaxmish** [magento/magento2#35574] opened 2022-06-03 06:27 UTC
**Preconditions (*)**
Magento 2.4.1
Default magento setup

**Steps to reproduce (*)**
Add product to cart
Go to checkout page
Under payment section,  start type card numbers
After entering 4 digits of card number, it is not hilighting the card type for master/discover card

**Expected result**
After entering the 4 digits of card it should hilight the card type for master/discover cards

**Actual result**
Not hilighting the type of card after entering 4 digits for master/discover card.

**Comment by engcom-Hotel** [comment] 2022-06-03 14:54
Hello @tavantlaxmish,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but for us, the issue is not reproducible. After entering four numbers of CC, it automatically detects the type and highlights the same. Please refer the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/171878985-c713c451-a659-4b0e-9f9c-dd83b33d7f3d.png)

Let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-06-20 06:19
Dear @tavantlaxmish,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-06-20 06:19 UTC
Labels: Triage: Dev.Experience, Issue: needs update
