### ISSUE TITLE
Async Bulk API: Update products returns error: "product" is required. Enter and try again

### ISSUE THREAD

**Issue by abcpremium** [magento/magento2#36881] opened 2023-02-17 14:21 UTC
### Preconditions (*)
Magento 2.4.3-p1
PHP 7.4

### Steps to reproduce (*)
`PUT` method for `https://my-shop-domain.com/rest/employees_en/async/bulk/V1/products/bySku`

"employees_en" is my store_code

RequestBody before JSON encoding:
```
$body = [
   0 => [
       'product' => [my product data here],
       'saveOptions' => true
   ],
   1 => [
       'product' => [my other product data here],
       'saveOptions' => true
   ],
   2 => ...
];
```

### Expected result (*)
Getting back my Bulk UUID

### Actual result (*)
"product" is required. Enter and try again

**Comment by engcom-Bravo** [comment] 2023-02-20 12:15
Hi @abcpremium,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have used` PUT` method `https://e4542dc82f3d14442fc20c2226915339.instances.magento-community.engineering//rest/async/V1/products/24-MB01`

We are able to get the BULK UUID.

<img width="891" alt="Screenshot 2023-02-20 at 4 56 55 PM" src="https://user-images.githubusercontent.com/51680745/220103970-4bb8bb9d-94dd-4c77-90f9-7d2af15c9e27.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by abcpremium** [comment] 2023-02-20 13:08
> engcom-Bravo

Hey, well as I can see, you didn't use the bulk endpoint. It should be "/rest/employees_en/async/bulk/V1/products/bySku"

**Comment by engcom-Bravo** [comment] 2023-02-21 09:17
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-02-21 13:56
Hi @abcpremium,

Thanks for your update.

As per Magento devdocs https://developer.adobe.com/commerce/webapi/rest/use-rest/bulk-endpoints/ for enabling bulk operations we need to install and configure RabbitMQ.

Before that Use the `bin/magento queue:consumers:start async.operations.all` command to start the consumer that handles asynchronous and bulk API messages.


Kindly Provide us Payload it will helpful us.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-03-01 11:54
Hi @abcpremium,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

We have configured our instance with RabbitMQ.We are able to update the product using `PUT` method.We are able to get
`Bulk UUID`




<img width="1291" alt="Screenshot 2023-03-01 at 3 06 47 PM" src="https://user-images.githubusercontent.com/51680745/222132118-5bcc443a-22ed-4b66-857e-c39b39123721.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by abcpremium** [comment] 2023-03-02 16:03
> Hi @abcpremium,
> 
> Thanks for your update.
> 
> Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.
> 
> We have configured our instance with RabbitMQ.We are able to update the product using `PUT` method.We are able to get `Bulk UUID`
> 
> <img alt="Screenshot 2023-03-01 at 3 06 47 PM" width="1291" src="https://user-images.githubusercontent.com/51680745/222132118-5bcc443a-22ed-4b66-857e-c39b39123721.png">
> 
> Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.
> 
> Thanks.

Yeah well I updated my test instance to the latest version now, however now I get a new issue saying that my consumer is missing authorization for Magento_Catalog::attributes_attributes. Note: I selected "ALL" for the resource access within the integration...

**Comment by abcpremium** [comment] 2023-03-03 08:11
So I got it me a fresh Magento installation with the latest version and got a new error now:

TypeError: Argument 1 passed to Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver::resolveBulkItemParams() must be of the type array, string given, called in /var/www/share/pimcore.abcpremium.de/htdocs/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php on line 123 and defined in /var/www/share/pimcore.abcpremium.de/htdocs/vendor/magento/module-webapi-async/Controller/Rest/Asynchronous/InputParamsResolver.php:178

**Comment by engcom-November** [comment] 2023-03-06 05:28
Hi @abcpremium ,
Thank you for the response. The above issue is a duplicate of this [issue](https://github.com/magento/magento2/issues/35370) and has been take care in [commits](https://github.com/magento/magento2/search?q=ACP2E-763&type=commits). Hence the issue is not reproducible on 2.4-develop instance. Kindly check the commits for possible solution or recheck the issue on Magento 2.4-develop instance as it is upcoming 2.4.x release and have latest code base and elaborate missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2023-03-20 05:26
Hi @abcpremium ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-20 05:26 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1

**Comment by abcpremium** [comment] 2023-03-24 10:26
Uhmmm.... well I got this working now, however when I want to bulk create 32 products, Magento only creates 11 of them. When I then execute this a second time, 5 more get created, but never all 32 products. And my Bulk Action Log in the Admin backend is always empty?
