### ISSUE TITLE
Can't sort by "Websites" in the Products > Catalog list

### ISSUE THREAD

**Issue by blizam** [magento/magento2#6208] opened 2016-08-17 18:42 UTC
2nd to last column in the table of your Proudcts titled "Websites" -- clicking the column header the page grays as if it's trying to re-order, and the little down arrow icon appears on the right of the header cell... but the list never actually sorts by what Website it's associated with

### Preconditions
1. Mage 2.1.0
2. PHP7, CentOS
3. at least two websites are created
4. two products are created and each one is assigned to different website

### Steps to reproduce
1. go to products grid 
2. by clicking on grid's head try to sort by Websites

### Actual result
Products are not sorted

### Expected result
 Products are sorted

**Comment by victor-v-rad** [comment] 2016-08-25 14:28
Hi @blizam 
I have managed to reproduce the issue and created internal ticket MAGETWO-57630

**Comment by magento-engcom-team** [comment] 2017-10-10 09:30
@blizam, thank you for your report.
We've created internal ticket(s) MAGETWO-57630 to track progress on the issue.

**Comment by sambolek** [comment] 2018-09-27 09:11
#mm18hr

**Comment by magento-engcom-team** [comment] 2018-09-27 09:11
@sambolek thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2019-01-02 19:34
Hi @milindsingh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-03 05:12
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by shikhamis11** [comment] 2019-02-03 05:12
#MM19IN

**Comment by pwaszkis** [comment] 2019-03-21 16:59
#snowdog-oss

**Comment by magento-engcom-team** [comment] 2019-03-21 16:59
@pwaszkis thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by edenduong** [comment] 2019-07-24 14:44
We need to disable sort this field.
Because one product which can belong many websites.
It can not be sorted.

**Comment by kisroman** [comment] 2019-09-29 12:05
This issue was fixed in https://github.com/magento/magento2/issues/20511.

**Closed as completed by kisroman** 2019-09-29 12:05 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Event: snowdog-oss
