### ISSUE TITLE
Upgrade 2.4.2 to 2.4.3 error: Integrity constraint violation

### ISSUE THREAD

**Issue by zeekinfo** [magento/magento2#34845] opened 2021-12-19 15:46 UTC
I was trying to upgrade from 2.4.2 to 2.4.3 in my test environment. While trying to run bin/magento setup:upgrade,

The below error appeared:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '249191' for key 'PRIMARY', query was: ALTER TABLE catalog_url_rewrite_product_category ADD CONSTRAINT PRIMARY KEY (url_rewrite_id)

How to fix these issues

**Comment by ihor-sviziev** [comment] 2021-12-20 08:57
Hi @zeekinfo,
Thank you so much for your report!
I'm closing this issue as a duplicate of https://github.com/magento/magento2/issues/33770.

**Closed as completed by ihor-sviziev** 2021-12-20 08:57 UTC
Labels: duplicate, Issue: ready for confirmation
