### ISSUE TITLE
Bulk API operation not starting

### ISSUE THREAD

**Issue by vijay-prevaj** [magento/magento2#31741] opened 2021-01-18 11:16 UTC
### Preconditions (*)

1. magento version 2.3.4-p2
### Steps to reproduce (*)

1. Install magento 2.3.4-p2
2. configure rabbitmq
3. Create new product with REST API URL (rest/all/async/bulk/V1/products/bySku).
`[
	{
		"product": {
			"sku": "Z-Z0EE1",
			"name": "Printed Dress",
			"status": 1,
			"visibility": 4,
			"price":17
    	}
	},
	{
  		"product": {
		    "sku": "Z00JN",
		    "name": "Black WATCH",
		    "status": 1,
		    "visibility": 4,
		    "price":77
  		}
  	}
]`
4. Run (bin/magento queue:consumers:start async.operations.all) to store items in magento.

### Expected result (*)

1. Product need to be created in admin with given name and sku.

### Actual result (*)

1. Admin show (Task "Topic async.magento.catalog.api.productrepositoryinterface.save.put": -2 item(s) are currently being updated.-2 item(s) have been scheduled for update.)
2. In bulk action page the status always show 'In Progress'

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-01-19 08:15
Hi @vijay-prevaj .
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Everything works as expected.

_**Precondition:**_
 Configured RabbitMQ;

**Manual testing scenario:**
1. Run in console: `php bin/magento queue:consumers:start async.operations.all`;
2. Create new product with REST API:
**POST** `http://magento24.loc/rest/all/async/bulk/V1/products`
![Screenshot from 2021-01-19 10-02-37](https://user-images.githubusercontent.com/51679138/105005129-8ffa9100-5a3d-11eb-9303-456763843bae.png)
:o: you forgot to add required attribute `"attribute_set_id"`
3. Send;

**Actual Result:** :heavy_check_mark:  The products were created successfully

![Screenshot from 2021-01-19 10-06-15](https://user-images.githubusercontent.com/51679138/105005495-14e5aa80-5a3e-11eb-84fb-ad1a605bb3cd.png)

![Screenshot from 2021-01-19 10-08-43](https://user-images.githubusercontent.com/51679138/105005786-71e16080-5a3e-11eb-9c96-251092da33a4.png)

4. If you need to update the information you use:
**PUT** `http://magento24.loc/rest/all/async/bulk/V1/products/bySku`
5. Change, for example **price**, and send **PUT** request

**Actual Result:** :heavy_check_mark: The prices were successfully updated.

![Screenshot from 2021-01-19 10-12-40](https://user-images.githubusercontent.com/51679138/105006230-0946b380-5a3f-11eb-87b2-2c9c7afc4674.png)
![2021-01-19_10-13](https://user-images.githubusercontent.com/51679138/105006235-0ba90d80-5a3f-11eb-98f9-56d0eae8858a.png)

@vijay-prevaj Could you take a look?
Thanks!

**Comment by miteshdhaduk** [comment] 2021-01-19 19:45
> Hi @vijay-prevaj .
> Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. Everything works as expected.
> 
> _**Precondition:**_
> Configured RabbitMQ;
> 
> **Manual testing scenario:**
> 
> 1. Run in console: `php bin/magento queue:consumers:start async.operations.all`;
> 2. Create new product with REST API:
>    **POST** `http://magento24.loc/rest/all/async/bulk/V1/products`
>    ![Screenshot from 2021-01-19 10-02-37](https://user-images.githubusercontent.com/51679138/105005129-8ffa9100-5a3d-11eb-9303-456763843bae.png)
>    o you forgot to add required attribute `"attribute_set_id"`
> 3. Send;
> 
> **Actual Result:**  The products were created successfully
> 
> ![Screenshot from 2021-01-19 10-06-15](https://user-images.githubusercontent.com/51679138/105005495-14e5aa80-5a3e-11eb-84fb-ad1a605bb3cd.png)
> 
> ![Screenshot from 2021-01-19 10-08-43](https://user-images.githubusercontent.com/51679138/105005786-71e16080-5a3e-11eb-9c96-251092da33a4.png)
> 
> 1. If you need to update the information you use:
>    **PUT** `http://magento24.loc/rest/all/async/bulk/V1/products/bySku`
> 2. Change, for example **price**, and send **PUT** request
> 
> **Actual Result:**  The prices were successfully updated.
> 
> ![Screenshot from 2021-01-19 10-12-40](https://user-images.githubusercontent.com/51679138/105006230-0946b380-5a3f-11eb-87b2-2c9c7afc4674.png)
> ![2021-01-19_10-13](https://user-images.githubusercontent.com/51679138/105006235-0ba90d80-5a3f-11eb-98f9-56d0eae8858a.png)
> 
> @vijay-prevaj Could you take a look?
> Thanks!

First I call rest api and then execute `php bin/magento queue:consumers:start async.operations.all`.

I wait many times but product not updated.

**Comment by vijay-prevaj** [comment] 2021-01-20 09:07
@engcom-Alfa Issue is reproduced in magento version 2.3.4-p2.

**Comment by engcom-Alfa** [comment] 2021-01-21 11:54
@miteshdhaduk @vijay-prevaj 
Unfortunately, even in this scenario, the error is not reproduced. Looks like the problem has already been fixed in 2.4-develop.

_**Precondition:**_
 Configured RabbitMQ;

**Manual testing scenario:**

2. Create new product with REST API:
**PUT** `http://magento24.loc/rest/all/async/bulk/V1/products/bySku`
![Screenshot from 2021-01-21 13-46-58](https://user-images.githubusercontent.com/51679138/105347172-33d76e80-5bef-11eb-9295-5a80387476b8.png)

3. Send;

**Actual Result:** :heavy_check_mark:  Response: 202 Accepted.

![Screenshot from 2021-01-21 13-47-05](https://user-images.githubusercontent.com/51679138/105347273-5c5f6880-5bef-11eb-9558-4559a4ac4427.png)

4. Go to Admin -> System -> Bulk Actions -> Details;

**Actual Result:** :heavy_check_mark:  Status: Pending...
![Screenshot from 2021-01-21 13-42-19](https://user-images.githubusercontent.com/51679138/105347473-a0eb0400-5bef-11eb-9dbe-f4a99f35fe8f.png)

5. Run in console: `php bin/magento queue:consumers:start async.operations.all`;
6. Go to Admin -> System -> Bulk Actions -> Details again

**Actual Result:** :heavy_check_mark:  2 items has been successfully updated.

![Screenshot from 2021-01-21 13-43-24](https://user-images.githubusercontent.com/51679138/105347672-e3acdc00-5bef-11eb-8290-03aa4be89576.png)

![Screenshot from 2021-01-21 13-49-36](https://user-images.githubusercontent.com/51679138/105347765-05a65e80-5bf0-11eb-986a-e69792f44652.png)

@vijay-prevaj Are you able to reproduce it on fresh 2.4-develop?
Thank you!

**Comment by vijay-prevaj** [comment] 2021-02-01 13:00
@engcom-Alfa  I able to replicate the issue in Magento fresh enterprise edition (2.4.1). Here is the operation status response.

`{
  "operations_list": [
    {
      "id": 1,
      "bulk_uuid": "b82119f4-4587-43a3-86be-e7faebb291a6",
      "topic_name": "async.magento.catalog.api.productrepositoryinterface.save.post",
      "serialized_data": "{\"entity_id\":null,\"entity_link\":\"\",\"meta_information\":\"{\\\"product\\\":{\\\"sku\\\":\\\"Z-Z00JN\\\",\\\"name\\\":\\\"Moschino Ladies Crystal Teddy Zip-up Hoodie In Black\\\",\\\"status\\\":1,\\\"visibility\\\":4,\\\"price\\\":77}}\"}",
      "result_serialized_data": null,
      "status": 4,
      "result_message": null,
      "error_code": null
    },
    {
      "id": null,
      "bulk_uuid": "b82119f4-4587-43a3-86be-e7faebb291a6",
      "topic_name": "async.magento.catalog.api.productrepositoryinterface.save.post",
      "serialized_data": "{\"entity_id\":null,\"entity_link\":\"\",\"meta_information\":\"{\\\"product\\\":{\\\"sku\\\":\\\"Z-Z0EE1\\\",\\\"name\\\":\\\"Versace Multicolor Barocco Signature Printed Dress\\\",\\\"status\\\":1,\\\"visibility\\\":4,\\\"price\\\":17}}\"}",
      "result_serialized_data": null,
      "status": 4,
      "result_message": null,
      "error_code": null
    }
  ],
  "user_type": 2,
  "bulk_id": "b82119f4-4587-43a3-86be-e7faebb291a6",
  "description": "Topic async.magento.catalog.api.productrepositoryinterface.save.post",
  "start_time": "2021-02-01 11:02:38",
  "user_id": 41,
  "operation_count": 2
}`

**Comment by vijay-prevaj** [comment] 2021-02-04 05:35
@engcom-Alfa Are you able to reproduce the issue in Magento commerce edition.

**Comment by engcom-Alfa** [comment] 2021-02-09 08:59
Hi @vijay-prevaj. Thank you for your report.
We are not able to reproduce the issue on the commerce edition too. Everything works as expected.
Perhaps the problem may be due to the wrong configuration of the RabbitMQ server.

Magento EE
**Manual testing scenario:**

1. Create new product with REST API:
**PUT** `http://magento24.loc/rest/all/async/bulk/V1/products/bySku`
![Screenshot from 2021-01-21 13-46-58](https://user-images.githubusercontent.com/51679138/105347172-33d76e80-5bef-11eb-9295-5a80387476b8.png)

3. Send;
4. Go to Admin -> System -> Bulk Actions -> Details;

**Actual Result:** :heavy_check_mark:  Status: In Progress
![Screenshot from 2021-02-09 10-50-50](https://user-images.githubusercontent.com/51679138/107339647-97a1d880-6ac5-11eb-96f4-8020f2d29993.png)

5. Run in console: `php bin/magento queue:consumers:start async.operations.all`;
6. Go to Admin -> System -> Bulk Actions -> Details again

**Actual Result:** :heavy_check_mark:  2 items has been successfully updated.

![Screenshot from 2021-02-09 10-51-37](https://user-images.githubusercontent.com/51679138/107339690-a4263100-6ac5-11eb-9c19-89de4a80ff52.png)
![Screenshot from 2021-02-09 10-51-48](https://user-images.githubusercontent.com/51679138/107339696-a6888b00-6ac5-11eb-85cd-5973a51b7ae8.png)

So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-09 08:59 UTC
Labels: Issue: needs update, not-confirmed, Reported on 2.3.4-p2

**Comment by birjit-corra** [comment] 2023-06-14 05:47
@vijay-prevaj How did you resolved this issue?

**Comment by wpplayer** [comment] 2023-10-10 14:32
Got the same error.


![mag](https://github.com/magento/magento2/assets/43295658/98c1b390-62f9-424a-bb35-d05bc64b984e)
