### ISSUE TITLE
Country dropdown showing 0 as one of the allowed countries for certain store in Magento 2.1.4

### ISSUE THREAD

**Issue by ajaykrshukla** [magento/magento2#8576] opened 2017-02-16 14:15 UTC
For some unknown reason after I had upgraded to Magento 2.1.4 country dropdown for some allowed countries show one extra option with text 0. Please suggest what can be done as I have checked from the DB config table and it is saving correct data but on country dropdown it has this issue.

**Comment by avoelkl** [comment] 2017-02-16 14:24
Hi @ajaykrshukla, where does the extra option with text 0 show up? In the frontend? Only in the backend? For customer addresses in the customer account, during checkout,....?
Can you maybe also add a screenshot?

**Comment by EmilyPepperman** [comment] 2017-02-16 14:24
We are updating to 2.1.4 today... so want to check we don't have this issue as well. Thanks!

**Comment by ajaykrshukla** [comment] 2017-02-17 04:20
@avoelkl I am getting the 0 as one of the option on the frontend registration form and on the my account section address add/edit form.

**Comment by avoelkl** [comment] 2017-02-17 16:39
Hi @ajaykrshukla,
I just tried this with a brand new installation of Magento CE 2.1.4 and I am not able to reproduce this error. Neither during checkout, nor in the customer account section when i add a new address or edit an existing one. The countries show up as expected.
From which version did you upgrade to 2.1.4?

**Comment by vrann** [comment] 2017-03-13 17:49
@ajaykrshukla closing as not reproducible, please feel free to reopen if needed.

**Closed as completed by vrann** 2017-03-13 17:49 UTC
