### ISSUE TITLE
Magento Admin is Super Slow for Browsing and Editing Products even though main website is fast - Why is this the case?

### ISSUE THREAD

**Issue by bshellma** [magento/magento2#36191] opened 2022-09-23 20:22 UTC
### Preconditions and environment

- Magento's current version
- I have an eCommerce store with thousands of products

### Steps to reproduce

1. Go to the admin page
2. Search for a product series or individual product
3. Choose whether to see 20-999 results on a page
4. Whether it is 1 product, 20, or 999 products, you must wait 3-5 minutes for the result to load
5. Why is this an issue for the admin page when I can search products instantly on my main website?
6. Magento please fix the admin page speed!

### Expected result

I expect 1-30 second load times on the admin page when searching for products.

### Actual result

I have to wait 3-5 minutes for the search query to load the results on my Magento admin page.
I only have to wait a few seconds when searching for products on my main website.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-26 07:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-26 12:06
Hi @bshellma,


Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop branch and 2.4.5 and the issue is not reproducible.Kindly refer the attached videos.


https://user-images.githubusercontent.com/51680745/192266256-cf4e8cbf-ab4a-403d-9834-5a54bef1dd96.mov




https://user-images.githubusercontent.com/51680745/192266392-71af1bdb-1066-429e-a155-b537a6bc947d.mov




Please let us know we miss anything.



Thanks.

**Comment by 50xSolutions** [comment] 2022-09-28 09:49
Hi @bshellma , we had this same issue when upgrading from Magento 2.3 to Magento 2.4. Can you please check in Stores - Configuration - Advanced - System what value is in Max Session Size in Admin?

![image](https://user-images.githubusercontent.com/23242787/192747738-9cb1e9ce-418f-44be-808f-7b59026def6e.png)

We have to even disable the max size for a while, because the admin panel was incredibly slow when we first launch it....

**Comment by engcom-Bravo** [comment] 2022-10-10 10:58
@50xSolutions Thanks for your contribution.


@bshellma Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

**Comment by engcom-Bravo** [comment] 2022-10-25 06:21
Hi @bshellma,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-25 06:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
