### ISSUE TITLE
Shopping Cart issue when creating customer through backend magento 2

### ISSUE THREAD

**Issue by subineseller** [magento/magento2#26787] opened 2020-02-10 08:29 UTC
### Preconditions (*)

1. Magento Version 2.3.3

### Steps to reproduce (*)

1. Create a Customer Account via Magento 2 Admin
2. Navigate to that customer's shopping cart from backend.
3. It will load all the data's of the quote_items table.

### Expected result (*)

1. Expected to be blank when creating new customer

### Actual result (*)

1. New customer created from backend -> https://prnt.sc/r00lje
2. Its showing 1 lack + shopping cart items

**Comment by subineseller** [comment] 2020-02-10 08:31
@magento give me 2.3.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-10 08:31
Hi @subineseller. Thank you for your request. I'm working on Magento 2.3.3-develop instance for you

**Comment by krishprakash** [comment] 2020-02-10 09:02
Hi @subineseller. Not able to reproduce the issue as provided steps by you. 
Click [this link](https://nimb.ws/7AMQ6K) for reference
Please provide more detail to reproduce this issue
Thanks.

**Comment by subineseller** [comment] 2020-02-10 09:09
> Hi @subineseller. Not able to reproduce the issue as provided steps by you.
> Click [this link](https://nimb.ws/7AMQ6K) for reference
> Please provide more detail to reproduce this issue
> Thanks.

Hi Can you check this on 2.3.3.
if the already created customers have the shopping cart items.
then the newly created customer shopping cart will load that data from quote_item table.
 i have checked the 2 installation with version 2.3.3 both have the same issue.
if you want i can take a screencast for you.

**Comment by krishprakash** [comment] 2020-02-10 09:24
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-10 09:24
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-10 09:25
Hi @krishprakash, here is your [Magento instance](https://i-26787-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26787-2-4-develop.instances.magento-community.engineering/admin_65a4](https://i-26787-2-4-develop.instances.magento-community.engineering/admin_65a4)
Login: `b7c8cbee` Password: `b34965ad2e5c`
Instance will be terminated in up to 3 hours.

**Comment by subineseller** [comment] 2020-02-10 09:33
@magento give me 2.3.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-10 09:33
Hi @subineseller. Thank you for your request. I'm working on Magento 2.3.3-develop instance for you

**Comment by krishprakash** [comment] 2020-02-10 09:40
Issue is already fixed in latest magento 2.3.4 
Related issue: #26437 
Review the fixes at related PR: 26489
So closing this ticket
Thank you for your report !

**Closed as completed by krishprakash** 2020-02-10 09:40 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.3

**Comment by subineseller** [comment] 2020-02-10 09:41
Ok.. Thanks for the update. i will update the version to 2.3.4
