### ISSUE TITLE
Product > Product in Websites > "Changes have been made to this Section" Pencil Icon always present

### ISSUE THREAD

**Issue by blizam** [magento/magento2#5512] opened 2016-07-07 05:17 UTC
Ever since upgrading to 2.1.0 all my Products have this Pencil Icon present on the "Product in Websites" option

**Comment by antboiko** [comment] 2016-07-07 12:13
Hi @blizam , thanks for reporting this issue. We've created internal ticket MAGETWO-55157.

Best,
Anton.

**Comment by magento-engcom-team** [comment] 2017-10-12 13:34
@blizam, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-12 13:34 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by blizam** [comment] 2017-10-12 14:42
sweet!

**Comment by C4rter** [comment] 2017-12-15 10:18
Can somebody show me the commit that fixed this? We are having a similar issue with a custom tab and don't know the reason or how to fix it.
