### ISSUE TITLE
Database Media Storage - Admin Product Edit page does not handle product images correctly in database storage mode

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#21604] opened 2019-03-06 17:28 UTC
### Preconditions (*)
1. Magento 2.2-develop or 2.3-develop

### Steps to reproduce (*)
1. Vanilla install of 2.2-develop or 2.3-develop
2. Change mode to database storage, synchronise and save settings
3. Add new product and assign an image
4. Save the product
5. Verify that the image is present in the filesystem (2.3-develop will fail this test due to #21546. Don't worry, carry on the test as we are going to clear the images anyway in Step 8)
6. Edit the product and view the images section. Verify image displays correctly in the images and videos section. (2.3-develop will fail this test due to #21546. Don't worry, carry on the test as we are going to clear the images anyway in Step 8)
7. Now simulate running on a new node in a cluster by clearing pub/media/catalog
8. Now refresh the product edit page.
9. Verify that the product image is still shown correctly

### Expected result (*)
1. When the admin page is refreshed, Magento should realise we are in database storage mode, and see that the image does not exist locally in pub/media/catalog. It should be copied from the database to  local storage and then should be displayed on the product edit page.

### Actual result (*)
1. Placeholder image is shown with 0 size.

**Comment by magento-engcom-team** [comment] 2019-03-06 17:28
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-07 08:21
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-07 12:12
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98608`, `MAGETWO-98609` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-06-08 22:20
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#21605 by @gwharton in 2.3-develop branch
Related commit(s):
 - [5f6e24fa20087d3d37063bfab77ffca42625c9c5](https://github.com/magento/magento2/commit/5f6e24fa20087d3d37063bfab77ffca42625c9c5)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-06-08 22:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by magento-engcom-team** [comment] 2019-06-11 21:15
Hi @gwharton. Thank you for your report. 
The issue has been fixed in magento/magento2#21606 by @gwharton in 2.2-develop branch
Related commit(s):
 - [6e58603ea1a168743e4f4eb0dd053c20320c9cff](https://github.com/magento/magento2/commit/6e58603ea1a168743e4f4eb0dd053c20320c9cff)

The fix will be available with the upcoming 2.2.10 release.
