### ISSUE TITLE
Cannot get product list using the SOAP API

### ISSUE THREAD

**Issue by 3m0** [magento/magento2#2971] opened 2016-01-12 17:59 UTC
I've been trying to get the product list using the following soap request:

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:def="http://magento.upop.com.br/soap/default?services=catalogProductRepositoryV1">
   <soap:Header/>
   <soap:Body>
      <def:catalogProductRepositoryV1GetListRequest>
         <searchCriteria>
            <filterGroups>
            </filterGroups>
         </searchCriteria>
      </def:catalogProductRepositoryV1GetListRequest>
   </soap:Body>
</soap:Envelope>
```

However, all I get is the following response:

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring>SoapServer::SoapServer(): Invalid parameters</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

It says that the parameters are invalid, but I don't see what is invalid, since the filterGroups can be empty.

**Comment by ericahoekerd** [comment] 2016-02-05 08:36
this will works, filter on enityt_id > 0;

> `<searchCriteria><filterGroups><item><filters><item><field>entity_id</field><value>0</value><conditionType>gt</conditionType></item></filters></item></filterGroups></searchCriteria>`

**Comment by maksek** [comment] 2016-05-09 21:02
Hi @3m0, have you resolved the issue?

**Comment by nobuttsalex** [comment] 2016-05-18 11:40
This seems to be an issue on 2.0.5 and maybe earlier versions. I am able to make SOAP API calls to my instance on the dev branch but cannot make the same call to my instance on 2.0.5.

**Comment by veloraven** [comment] 2016-11-01 14:04
@3m0 is this issue still actual?
If it is please describe detailed steps, actual result and expected result.
If it is not, please close it.

**Comment by veloraven** [comment] 2016-11-16 07:42
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-11-16 07:42 UTC
Labels: Progress: needs update
