### ISSUE TITLE
Downloadable products showing out-of-stock in front end

### ISSUE THREAD

**Issue by tijo2248** [magento/magento2#23564] opened 2019-07-04 04:50 UTC
Hi,
Magento version 2.3.2
Downloadable products showing out-of-stock in front end and in-stock in back end.
i have tried my best, cleared cache, reindex, etc.. but no luck. 

i have added download file, manage stock is 1000. 
its showing in-stock in back end.

**Comment by krishprakash** [comment] 2019-07-04 04:59
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-04 04:59
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-04 04:59
Hi @krishprakash, here is your [Magento instance](https://i-23564-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23564-2-3-develop.instances.magento-community.engineering/admin](https://i-23564-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-07-04 05:09
Hi @tijo2248. Thank you for your report.
Not able to reproduce the issue as described by you.
Please provide additional steps to reproduce the issue also follow issue reporting guideline to report an issue
https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Thanks.

**Comment by krishprakash** [comment] 2019-07-18 12:32
Hi @tijo2248. 
I'm closing this issue as not reproducible and also no any response from you.
Feel free to reopen if you confirm that issue is reproduce in venilla magento instace.
Thanks

**Closed as completed by krishprakash** 2019-07-18 12:32 UTC
Labels: Progress: needs update, Issue: Format is not valid
