### ISSUE TITLE
Configurable product final price uses a deactivated associated product's price

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6447] opened 2016-09-01 13:26 UTC
when the minimal price of all children stems from a deactivated and/or out of stock product, its price is still used as final price in the catalog listing and product page
### Preconditions
1. CE 2.1.1
2. configurable product SKU 123 with 3 children (SKU 1: price $1, SKU 2: price $2, SKU 3: price $3)
3. multi-store (1 website, 2 languages) -  not sure if relevant tho
4. no full page cache
### Steps to reproduce
1. go to category listing, ensure you see product SKU 123 with price $1 (from SKU 1)
2. edit SKU 1 in backend on default store level
3. deactivate product and save
4. `cache:clean`
5. in the frontend, reload the category page
### Expected result
1. price for product SKU 123 is now $2
### Actual result
1. price for product SKU 123 is still $1

same thing for "out of stock".

a manual `catalog_product_flat` reindex is required to get the price from $1 to $2. the copy-on-save cron reindex does not pick this up.

**Comment by sevos1984** [comment] 2016-09-02 09:30
Internal ticket created MAGETWO-57982, thanks for reporting

**Comment by magento-engcom-team** [comment] 2017-10-02 06:30
@heldchen, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-02 06:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
