### ISSUE TITLE
Multiple order issue Paypal

### ISSUE THREAD

**Issue by sunilit42** [magento/magento2#29013] opened 2020-07-06 15:40 UTC
### Preconditions (*)

1. Magento 2.4
2. configure Paypal method with authorizing setting 
Can be related to [28916](https://github.com/magento/magento2/issues/28916)

### Steps to reproduce (*)

- Add Product in Cart
- Go to the checkout page
- Place an order with PayPal Express 
- It will redirect to paypal/express/review/ page
- Place order
- Redirecting to Success pae
- Now go back to PayPal/express/review/ page (Alt + <-)
- Now Click on Place Order button 
- It will display "PayPal Express Checkout Token does not exist." error but Order Placed successfully wit
![Screenshot_34](https://user-images.githubusercontent.com/60198022/87941354-b1d18600-caa3-11ea-9532-c82f489b435c.png)
### Expected result (*)

1. One order with one quote

### Actual result (*)

1. multiple order with same quote 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2020-07-20 13:15
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36014` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2020-07-29 03:10
Looks like this issue was already fixed in 2.4-develop branch in https://github.com/magento/magento2/commit/e9a65b4ac6e696d33e5a3912e7925ebb02d6ead6.
@engcom-Lima could you confirm that issue isn’t reproducing anymore?

**Comment by zhartaunik** [comment] 2020-07-29 21:43
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-29 21:43
Hi @zhartaunik. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-29 21:45
Hi @zhartaunik, here is your [Magento instance](https://i-29013-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29013-2-4-develop.instances.magento-community.engineering/admin_6cea](https://i-29013-2-4-develop.instances.magento-community.engineering/admin_6cea)
Login: `92672880` Password: `4811ec2ac475`
Instance will be terminated in up to 3 hours.

**Comment by zhartaunik** [comment] 2020-07-29 21:50
@ihor-sviziev 
I can confirm that issue does not reproduce anymore. Checked on clean Magento.

**Comment by ihor-sviziev** [comment] 2020-07-30 04:55
@zhartaunik Thank you for confirmation! I'm closing this issue.

**Closed as completed by ihor-sviziev** 2020-07-30 04:55 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Paypal, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P1, Severity: S1, Triage: Done, Progress: done, Reported on 2.4.0
