### ISSUE TITLE
Temando module issue with Split DB enabled

### ISSUE THREAD

**Issue by nileshti** [magento/magento2#23227] opened 2019-06-12 12:22 UTC
### Preconditions (*)

1. Magento Commerce 2.3.1
2. Split DB enabled and configured

### Steps to reproduce (*)

1. While doing Magento Upgrade from Commerce 2.3.0 to Commerce 2.3.1
2. Composer update command executed successfully
3. While executing php bin/magento setup:upgrade command below error getting:

> Module 'Temando_Shipping'
> Upgrading Schema..SQLSTATE[42502]: Base table or view not found: 1146 Table 'skinitdb_quote.temando_quote_collection_point' doesn't exist, query was: DESCRIBE `temando_quote_collection_point`

### Expected result (*)

1. added screenshot
2.  Temando Module uses connection name "checkout" and "sales" inside for new custom table creation/upgrade on file path: vendor/temando/module-shipping-m2/Setup/SetupSchema.php
3. in previous version, these are under "default" connection. so in this version also, Temando modules should use default connection name for custom tables.
### Actual result (*)

1. added screenshot
![2019-06-12_17-36](https://user-images.githubusercontent.com/25169040/59350631-38ad1e80-8d3a-11e9-8a59-1338ab6f7538.jpg)
![2019-06-12_16-25](https://user-images.githubusercontent.com/25169040/59350633-3945b500-8d3a-11e9-8e70-dec28c66df9f.jpg)
![2019-06-12_17-46](https://user-images.githubusercontent.com/25169040/59350634-3945b500-8d3a-11e9-9908-b24800fcbcca.jpg)
![2019-06-12_17-44](https://user-images.githubusercontent.com/25169040/59350636-3945b500-8d3a-11e9-8bc0-b9fdad979f2a.jpg)

2. In this version also (Commerce 2.3.1), Temando modules should use default connection name for custom tables.

**Comment by sdzhepa** [comment] 2019-11-04 18:04
Hello @nileshti 

We reverified this issue on the latest code base related to `2.3.3` and we not able to reproduce it now.
Possibly this issue has been fixed in the current version of Magento and Temando module.

But if you still have this issue I would strongly recommend reporting this bug into Enterprise Support associated with your account.

[Current repository](https://github.com/magento/magento2) and [issue tracker](https://github.com/magento/magento2/issues) aimed at Magento Open Source version only and the main focus is community contribution/collaboration. It described in [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) and it is a part of the issue report template:
> Verify, that the issue you are about to report does not relate to the Magento Commerce. GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub. You can report Commerce-related issues in one of two ways:
> - You can use the Support portal associated with your account
> - If you are a Partner reporting on behalf of a merchant, use the Partner portal.

**Closed as completed by sdzhepa** 2019-11-04 18:04 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Bundled Extension
