### ISSUE TITLE
setup:static-content:deploy exit code 0 when there are ParseErrors

### ISSUE THREAD

**Issue by mkidon** [magento/magento2#33184] opened 2021-06-08 16:07 UTC
### Preconditions (*)

1. Magento 2.4.2
2. Clean up var/view_preprocessed and pub/static/frontend dirs
3. Make some error in one of the less files. For example remove semicolon from https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less#L13

### Steps to reproduce (*)

1. Run bin/magento setup:static-content:deploy -f
2. Check exit code: echo $?

### Expected result (*)

1. Exit code is 1

### Actual result (*)

1. Exit code is 0

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

It is important for CI processes that magento scripts returns proper exit codes.

![Screenshot 2021-06-08 at 17 59 49](https://user-images.githubusercontent.com/8032249/121219904-7212b900-c884-11eb-80b5-24936a1105da.png)

**Comment by hostep** [comment] 2021-06-09 10:28
This might get fixed by https://github.com/magento/magento2/commit/d4f83c84340d6210adbff722fb306b96bf53ddbd#diff-345c262926556e221869005ce905bd890ab0a5e46bb3e2afe20c3ea9e8695772 (which is part of [MC-42026: [Cloud] Custom theme is not applied and the default LUMA theme is used.](https://github.com/magento/magento2/search?q=MC-42026&type=commits), sorry I can't find a clean merge commit, they merged [a bunch of different tickets all together](https://github.com/magento/magento2/commit/97ec8344ded7168adee48fd18407150be325f8dc), which is not really good)

Not sure though, the code changes sound related.

**Comment by engcom-November** [comment] 2021-07-15 10:34
Verified the issue on Magento 2.4-develop branch and the issue is resolved:
**Steps performed:**
Clean up var/view_preprocessed and pub/static/frontend dirs
>rm -rf var/*  pub/static/*
Made some error in below file: 
For example remove semicolon from https://github.com/magento/magento2/blob/2.4-develop/app/design/frontend/Magento/luma/Magento_Theme/web/css/source/_module.less#L13
![image](https://user-images.githubusercontent.com/60198231/125773859-2508c962-d5b8-4b3d-a198-e6cc7db24687.png)
Ran >bin/magento setup:static-content:deploy -f
Ran >echo $?
Result: Exit code is 1
![image](https://user-images.githubusercontent.com/60198231/125774265-8bacf574-efa6-44c3-9236-ad3cb80c3dc4.png)

**Comment by engcom-November** [comment] 2021-07-15 15:00
Hi @mkidon ,
As mentioned in the above [comment](https://github.com/magento/magento2/issues/33184#issuecomment-880586831), issue is not reproducible on Magento 2.4-develop branch. Hence, closing this issue.
Thank you.

**Closed as completed by engcom-November** 2021-07-15 15:00 UTC
Labels: Issue:  Cannot Reproduce, Component: Console, Reported on 2.4.2
