### ISSUE TITLE
exception.log missing

### ISSUE THREAD

**Issue by siliconalchemy** [magento/magento2#36054] opened 2022-08-30 16:17 UTC
### Preconditions and environment

- Magento version 2.4.5
- PHP 8.1 (FPM)
- Apache2.4
- Ubuntu 20.04

This Magento install has 

### Steps to reproduce

Trigger an exception/error (for example reCAPTCHA error detailed in #34975), or make `generated/` directory read-only to trigger a read-only error.

### Expected result

I expect to see an error and trace in var/log/exception.log

### Actual result

No exception.log exists.  Errors do seem to appear in system.log, but I don't know if they are everything that should be in exception.log.

### Additional information

This instance of Magento has been updated since 2.0 to 2.2 and 2.4.  In the past exception.log was always present with errors/exceptions.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by amokato** [comment] 2022-09-05 11:48
We have the same issue since 2.4.4

**Comment by amokato** [comment] 2022-09-23 07:57
Any updates on this? Nobody seems to care about such a severe issue.

**Comment by hostep** [comment] 2022-09-23 11:09
@sdzhepa: can we have somebody to verify this? This indeed sounds like a P0 or P1 prio if it's true. Thanks!

I can **not** confirm that this is true on Magento 2.4.3-p3 on production shops of ours, it works as expected over there. We haven't tried 2.4.4 or 2.4.5 yet in production, so I can't speak about those versions yet.

**Comment by amokato** [comment] 2022-09-23 12:38
We're having this issue on 2.4.4 (CE). It seems that some errors are written to the system.log.

**Comment by kamephis** [comment] 2022-09-28 16:16
In our case the exceptions seem to be written into the system.log instead of the exception.log (2.4.4 CE). The exception.log stays empty.

**Comment by engcom-November** [comment] 2022-09-30 09:40
Verified the issue on fresh instance of 2.4.5 Project-community-edition and the issue is reproducible. exception.log file is missing in var/log folder. No errors are written into exception.log. Only all errors are written into system.log file.
**Note**: There is no issue when the Magento is upgraded to 2.4.5 from 2.4.3 Project-community-edition. exception.log file is present in this case and all the errors/exceptions are getting written into exception.log file as expected.
Hence confirming this issue.

**Comment by engcom-November** [comment] 2022-10-21 04:07
Hi @siliconalchemy ,
Reviewed the issue again and after internal discussion, it has been concluded that this is not an issue. Magento has changed the way to write into exception.log File.
To print the log in exception.log, `exception` parameters must be given in context.
1. $this->logger->critical($e, ['exception' => $e]);
2. $this->logger->log('CRITICAL', $e->getMessage(), ['exception' => $e]);
Kindly recheck and let us know if you are still facing any issues.
Thank you.

**Comment by siliconalchemy** [comment] 2022-10-21 10:41
@engcom-November  - Ah!  Haha that's a really funny april fools joke!!

Oh wait, it's the middle of October, it's not April 1st.

** THIS IS A BUG **
var/log/exception.log is a well established log for critical errors.  This is not about custom code/modules, user logging.  This is fundamental, built in logging from standard usage of Magento.  References to it are littered throughout the official Magento documentation.  Have a look.  
** THIS IS A BUG **

eg.
https://devdocs.magento.com/cloud/project/log-locations.html
`Exception log: var/log/exception.log`

https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configure-cron-jobs.html
`Jobs with an ERROR status are always logged as CRITICAL in <install_directory>/var/log/exception.log.`

etc etc

**Comment by adriansanta** [comment] 2022-10-21 10:52
100% agree with @siliconalchemy 

Having all kind of log severities in the same file (system.log) really makes it difficult to use and defeats the purpose of log severity in the first place. We have to employ various workarounds (like parsing rules) to filter out "noise" lines in order to have a realistic overview of actual issues.

Furthermore, exception.log is not populated not only by custom/third party code, but also by Magento core code itself.

At least we could expect from core team to list this so-called "feature" in their release notes, as a backwards incompatible change. But ideally, this should be fixed to work as in the previous versions.

**Comment by kamephis** [comment] 2022-10-21 13:47
I agree, this is by far not a feature. Please take your time and fix this. It has been month and nothing happened.

**Comment by briangmoore77** [comment] 2022-10-24 14:33
This needs to be fixed asap. do you know how many sites are trying to get updated to 2.4.4 or 2.4.5 by 11/28? Lots... They all need that exception.log to be working like it is stated to work and how it has always worked.

**Comment by engcom-November** [comment] 2022-10-25 09:45
Hello @siliconalchemy @adriansanta @kamephis @jurvi @briangmoore77,
We have discussed this issue again internally and after further analysis came across the below commit:
https://github.com/magento/magento2/commit/8e6aedc8130be01669b04f99c19ab3f48e4c0691
We are confirming this issue and further analysis is in progress.
Thank you.

**Comment by MeetKamal** [comment] 2022-10-27 06:14
Hello @engcom-November  - We are facing same issue.  Do we have any temp solution to enable exception.log,  As lots of client facing issues.

**Comment by jurvi** [comment] 2022-10-28 13:50
I would be also interested in a temp solution if such exists, two clients are now missing exception.log making problem debugging unnecessarily harder.

**Comment by Shaikh-Samir** [comment] 2022-10-31 09:20
@MeetKamal 

We have verified this issue in our local environment and found work around(temporary) solution for it.

File path where need to replace core code:
vendor/magento/framework/Logger/Handler/System.php

Please replace below code:
```
public function write(array $record): void
    {
        if (isset($record['context']['exception'])) {
            $this->exceptionHandler->handle($record);

            return;
        }
        $record['formatted'] = $this->getFormatter()->format($record);

        parent::write($record);
    }
```


With :
```
public function write(array $record): void
    {
        	
        if (isset($record['context']['exception']) || $record['level'] == 500) {
            $this->exceptionHandler->handle($record);

            return;
        }
        $record['formatted'] = $this->getFormatter()->format($record);

        parent::write($record);
    }
```

**Comment by MeetKamal** [comment] 2022-10-31 14:54
Hi @Shaikh-Samir  -  Thank you for the Work around, Have tested and it seems working :)

**Comment by briangmoore77** [comment] 2022-11-18 22:44
Is this going backwards? I figured this would be fixed by now.

**Comment by PaperDS** [comment] 2022-11-23 09:49
Still no exception.log in M2.4.5-p1

**Comment by Shaikh-Samir** [comment] 2022-11-23 10:01
> Still no exception.log in M2.4.5-p1

Hello @PaperDS 
We have tested this work around solution in M2.4.5-p1 as well and its working correctly in our project.

Thank you.

**Comment by hostep** [comment] 2022-11-23 20:35
This might be fixed under [ACP2E-1287: log exception to exception.log](https://github.com/magento/magento2/search?q=ACP2E-1287&type=commits) (untested), unfortunately no clean merge commit, so you'll probably want to add those 4 separate commits together in a patch.

**Comment by Shaikh-Samir** [comment] 2022-11-24 07:40
> @
> 
> > > Still no exception.log in M2.4.5-p1
> > 
> > 
> > Hello @PaperDS We have tested this work around solution in M2.4.5-p1 as well and its working correctly in our project.
> > Thank you.
> 
> I've applied your work around and it works perfectly. Many thanks. I just don't like editing core code :-)

Yes got your point, its not best practice to edit in core code of framework, actually i also don't like to do this. So that  mentioned it work around fix (as temporary solution).

**Comment by onlinebizsoft** [comment] 2022-11-24 15:34
We also re-look at this one as well
https://github.com/magento/magento2/issues/13128

**Comment by engcom-Hotel** [comment] 2022-11-25 08:02
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1287 by the internal team
Related commits: https://github.com/magento/magento2/search?q=ACP2E-1287&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-11-25 08:02 UTC
Labels: Issue: Confirmed, Component: Exception, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Install & Administer, Area: UI Framework, Reported on 2.4.5

**Comment by hostep** [comment] 2023-01-02 14:04
If anyone wants a patch based on the commits from above (which work on Magento 2.4.5, haven't tested on 2.4.4), this one can be applied against the `magento/framework` composer package:
[ACP2E-1287-Framework.txt](https://github.com/magento/magento2/files/10332007/ACP2E-1287-Framework.txt)

**Comment by UglyWillDuckling** [comment] 2023-03-01 10:31
> If anyone wants a patch based on the commits from above (which work on Magento 2.4.5, haven't tested on 2.4.4), this one can be applied against the `magento/framework` composer package: [ACP2E-1287-Framework.txt](https://github.com/magento/magento2/files/10332007/ACP2E-1287-Framework.txt)

Thanks for the patch.

**Comment by andy-igoo** [comment] 2023-04-11 12:26
Just a quick note to say this worked for me: https://magento.stackexchange.com/questions/361276/exception-log-is-missing-in-magento2-4-4

```patch
--- a/vendor/magento/framework/Logger/Handler/System.php
+++ b/vendor/magento/framework/Logger/Handler/System.php
@@ -55,7 +55,7 @@
      */
     public function write(array $record): void
     {
-        if (isset($record['context']['exception'])) {
+        if (isset($record['context']['exception']) || $record['level'] == Logger::CRITICAL) {
             $this->exceptionHandler->handle($record);

             return;

```

**Comment by Eddcapone** [comment] 2023-06-28 09:49
> Hello,
> 
> As I can see this issue got fixed in the scope of the internal Jira ticket ACP2E-1287 by the internal team Related commits: https://github.com/magento/magento2/search?q=ACP2E-1287&type=commits
> 
> Based on the Jira ticket, the target version is 2.4.6.
> 
> Thanks

Is there a patch available or do we have to wait until 2.4.6?

**Comment by siliconalchemy** [comment] 2023-06-28 10:08
2.4.6 is out and includes this patch/fix.

**Comment by Eddcapone** [comment] 2023-06-29 08:04
@siliconalchemy So we have to upgrade to 2.4.6 to fix it?

**Comment by MeetKamal** [comment] 2023-06-29 08:14
Hi @Eddcapone - For the temp purpose you can try the below solution
https://magento.stackexchange.com/questions/361276/exception-log-is-missing-in-magento2-4-4

We tried that and it seems working.

**Comment by Eddcapone** [comment] 2023-06-29 08:51
@MeetKamal But this requires us to do a change in the core. Why is there no official patch?

**Comment by vardhmankamani1** [comment] 2023-06-29 09:05
@Eddcapone Here i am attach the patch file, you can use this patch untill the your system is not being updated to the 2.4.6
[exception_log.zip](https://github.com/magento/magento2/files/11903935/exception_log.zip)

**Comment by hostep** [comment] 2023-06-29 11:10
Or use [my earlier referenced patch](https://github.com/magento/magento2/issues/36054#issuecomment-1368973950) that is based on the official Adobe fix? (A lot time of could have been won if you just had read all the comments in this thread 😉)

**Comment by Eddcapone** [comment] 2023-06-29 12:14
My question is wheter there is an official patch and if not why?

**Comment by hostep** [comment] 2023-06-29 14:53
There isn't as far as I know, at least I can't find one when searching using [their quality patches tool](https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html).
So either take one of the solutions here from the thread, or make one yourself if you don't trust it (which is what I would recommend), or upgrade to 2.4.6-p1, or if you really want an official patch, create an issue or pull request here: https://github.com/magento/quality-patches (but knowing Adobe, it might take some weeks/months/years until you'll get one)

**Comment by Eddcapone** [comment] 2023-06-30 08:18
@hostep, Thx! It is beyond me how there is no official patch for such an important bug

**Comment by Eddcapone** [comment] 2024-01-09 09:41
Is there a patch already?

**Comment by moazzamsali** [comment] 2024-01-09 11:03
> Is there a patch already?

No I created the new one because on my site exception logs were not creating

**Comment by Eddcapone** [comment] 2024-01-10 15:34
Why do they close it if there is no official patch?

**Comment by hostep** [comment] 2024-01-10 19:36
@Eddcapone: it was fixed in Magento 2.4.6, so why shouldn't they close it?
As for a patch, I mentioned one over here: https://github.com/magento/magento2/issues/36054#issuecomment-1368973950

**Comment by Eddcapone** [comment] 2024-01-16 11:52
@hostep Because not everyone can just upgrade to 2.4.6 and your patch is not official.

**Comment by hostep** [comment] 2024-01-16 17:16
😆 In that thought process they need to leave open every ticket for forever and never close one, because there will always be a user that can't update to some version.

Anyway, if a fix has been published, they close the issue, it's as simple as that.

My patch isn't official, that's very true, if you don't trust it, then please make your own patch, the commits with fixes were already mentioned earlier: https://github.com/magento/magento2/issues/36054#issuecomment-1327131002

There is no other way you'll get what you want, so please get into the habit of creating your own patches for bugs you need to have fixed, you're bound to run into another bug in the future that has been fixed in some commit, so it's a good skill to have to turn those commits into patches.

**Comment by Eddcapone** [comment] 2024-01-19 08:52
@hostep That was not my thought process. My thought process is that this ticket is only finished, if there is a valid solution. And a valid solution requires a patch for older versions. And I've tried your patch earlier and it was not working.
