### ISSUE TITLE
Gift wrap options are not displayed in Magento2 front end

### ISSUE THREAD

**Issue by Deepthi57** [magento/magento2#4667] opened 2016-05-24 12:45 UTC
Steps to reproduce
Magneto Enterprise Endition
Version: 2.0.3
Steps:
1. Go to Magento admin
2. Go to Stores-.Configuration->Sales->Sales
3. Set "yes" for all the options under Gift Options Section
4. Save the config
5. Go to stores->Other Settings->Gift Wraping
6. Add Gift Wrapping
7. Go to View and Edit cart from Magento front end
8. Look for Gift wrap options
Observation:
Option to ad gift wrap does not display in frontend

![gift_options](https://cloud.githubusercontent.com/assets/17591809/15504187/5adea8d4-21db-11e6-801e-03a5ccd40e7a.png)
![no_option_for_gift_wrap](https://cloud.githubusercontent.com/assets/17591809/15504188/5ae1b6b4-21db-11e6-9ac4-7b83d10abebd.png)
![gift_wrap_setting_in_magento](https://cloud.githubusercontent.com/assets/17591809/15504186/5ade21ca-21db-11e6-9d2e-498400076d60.png)

**Comment by Deepthi57** [comment] 2016-05-26 05:24
Hi, This is important.Kindly requesting you to prioritize this. 
Thanks in advance

**Comment by ishakhsuvarov** [comment] 2016-05-26 06:13
@Deepthi57 We are looking into the issue. Does this reproduce on clean installation? Have you tried to upgrade form 2.0.3?

**Comment by sdzhepa** [comment] 2016-05-27 14:23
Hello @Deepthi57  

I have verified this issue on 2.0.3 using described steps and settings. I cloned develop branch and perform "git checkout tags/2.0.3"
And  I cannot reproduce it.

What I did:
- used clear Magento instance(just installed).
- created only 1 simple product
- 1 Gift wrapping is created
- Set "yes" for all the options under Gift Options Section
- verified flow for Guest and for Registered customer

In each case link for Gift Options(Wrapping, Messages, Printed card) is presented on shopping cart page

It seems there is(are) some other preconditions or settings.
Probably You have some extension installed.
Do you have some JS errors in browser console after Shopping cart page is fully loaded?

**Comment by Deepthi57** [comment] 2016-05-28 14:19
Hi,
Thanks got checking.  I have installed the latest version and it's working
fine. Thanks for the help

**Comment by ishakhsuvarov** [comment] 2016-05-30 07:53
@Deepthi57 Thank you for the update. Closing the issue for now, please reopen if you have any additional questions.

**Closed as completed by ishakhsuvarov** 2016-05-30 07:53 UTC
Labels: Progress: needs update
