### ISSUE TITLE
Uncaught ReferenceError: Unable to process binding "if: function(){return label }"

### ISSUE THREAD

**Issue by maheshwaran-1343** [magento/magento2#35754] opened 2022-07-11 13:02 UTC
I have the issue when I go to **Admin -> Product --> Add Grouped Product**. Anyone facing this issue.

**Error :** 
![image](https://user-images.githubusercontent.com/68689275/178269759-3610751f-98f0-468e-b7e2-e4ffb25da33c.png)

**Output :** 
![image](https://user-images.githubusercontent.com/68689275/178270038-396bbf2c-eb84-4688-8d17-d27b6e7485b6.png)

**Comment by engcom-November** [comment] 2022-07-12 10:51
Hi @maheshwaran-1343 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and 2.4.4 project-community-edition as well but could not reproduce the issue.
User is able to create and save grouped product. No console errors were observed.
![image](https://user-images.githubusercontent.com/60198231/178473811-64f93670-b40c-4734-a37b-5820e4ccf810.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and is upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-07-26 12:09
Hi @maheshwaran-1343 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-26 12:09 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update
