### ISSUE TITLE
Credit memo decreased product qty

### ISSUE THREAD

**Issue by VladyslavSikailo** [magento/magento2#27236] opened 2020-03-11 07:04 UTC
### Preconditions (*)
1. Empty installation of Magento 2.3.4 EE

### Steps to reproduce (*)
1. Create simple product in BO with Quantity > 1, in stock, default category, with weight.
2. Go to PDP and place order with that product.
3. In `inventory_reservation` table -1 reservation was created
4. Go to BO->Sales->Orders->{Your order}->Invoice->Submit Invoice
5. Click `Credit Memo` -> Refund Offline

### Expected result (*)
1. In `inventory_reservation` table reservations should not be created, because we doesn't check `return to stock` checkbox.
2. Product qty should not be changed.

### Actual result (*)
1. In `inventory_reservation` table +1 reservation was created
2. Qty of product was decremented. (`cataloginventory_stock_item` table)

**Comment by swathishs** [comment] 2020-06-05 10:55
@Dren7755: Tested the issue in 2.4 community edition the issue is not reproducible.

Please find the attachment below:

1.Product stock(Check quantity):
![image](https://user-images.githubusercontent.com/58288685/83868525-a838cc80-a748-11ea-9b59-6befff14b826.png)

2. After order placed(Check quantity):
![image](https://user-images.githubusercontent.com/58288685/83868650-e46c2d00-a748-11ea-9ee3-4f9c790262c0.png)

3. Invoice order:
![image](https://user-images.githubusercontent.com/58288685/83868721-04035580-a749-11ea-94b6-a31ee4626b54.png)

4. Credit memo(without checkbox):
![image](https://user-images.githubusercontent.com/58288685/83868752-11204480-a749-11ea-9d5d-281b4e719085.png)

![image](https://user-images.githubusercontent.com/58288685/83868799-209f8d80-a749-11ea-8b2d-55780ca7742f.png)

5. Product quantity does not update:
![image](https://user-images.githubusercontent.com/58288685/83868848-3614b780-a749-11ea-98f4-0a9956d0f4ab.png)

**Comment by swathishs** [comment] 2020-06-05 14:17
Since Magento CE we cant reproduce the issue it may be specific for EE

Hi @Dren7755, all issue specific for Magento EE should be reported in the EE repo

@sdzhepa - It seems this issue-specific for Magento EE and should be fixed in the EE repository.

EngCom team, please confirm and transfer this issue to https://github.com/magento/partners-magento2ee/issues

Closing this issue

**Closed as completed by swathishs** 2020-06-05 14:17 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
