### ISSUE TITLE
Error: Script error for "jquery/jquery-storageapi", needed by: mage/collapsible

### ISSUE THREAD

**Issue by openarun** [magento/magento2#37323] opened 2023-04-02 13:01 UTC
### Preconditions and environment

- 2.4.5+

I recently upgraded from 2.4.4 to 2.4.5.

### Steps to reproduce

1. Open admin panel.
2. Goto System
3. Goto Configuration
4. Click on any collapsible menu tab.

### Expected result

When clicked on any collapsible tab, it should be open up the menu.

### Actual result

Error: Script error for "jquery/jquery-storageapi", needed by: mage/collapsible

PS: I noticed that the request to /static/version1680379731/adminhtml/Magento/backend/en_US/js-storage/storage-wrapper.min.js is also 404.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-03 14:49
Hi @openarun,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- Upgraded from 2.4.4 to 2.4.5.
- Open admin panel.
- Goto System
- Goto Configuration
- Click on any collapsible menu tab.



<img width="1455" alt="Screenshot 2023-04-03 at 3 49 51 PM" src="https://user-images.githubusercontent.com/51680745/229522287-410b7a42-7168-4caa-9c49-3d6f86d8a125.png">




https://user-images.githubusercontent.com/51680745/229522313-3e0158a8-b13f-4a28-ad2c-96d01efee0f9.mov




Kindly let us know if you are still facing any issue.



Thanks.

**Comment by ananth-iyer** [comment] 2023-04-07 05:15
@openarun "jquery/jquery-storageapi" is removed. I seem upgrade did not go properly, remove vendor folder then run composer install. Are you using any bundling tools?
RequireJS dependency is changed here:
https://github.com/magento/magento2/blob/1df4565907d40f14ee1c753cc2de2ce567bfa8d7/app/code/Magento/Theme/view/base/requirejs-config.js#L72

**Comment by engcom-Bravo** [comment] 2023-04-10 13:47
@ananth-iyer Thanks for your contribution & collaboration over here 

@openarun Kindly refer this https://github.com/magento/magento2/issues/37323#issuecomment-1499945384. and please let us know if you are still facing any issue.

We are able to upgrade successfully from Magento 2.4.4 to 2.4.5.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-04-25 06:02
Hi @openarun,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-04-25 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.5
