### ISSUE TITLE
Updating a category through the REST API  will uncheck "Use Default Value" on a bunch of attributes

### ISSUE THREAD

**Issue by stanleyyuenyiu** [magento/magento2#30047] opened 2020-09-15 02:27 UTC
### Preconditions (*)
- using Magento 2.4
- Mysql 8.0
- php-fpm 7.4
- nginx 1.18
- require 1 website with more than 1 store view
- Create some sub categories under default category at default store
- Using Admin token

### Steps to reproduce (*)
Call REST API with below script, replace the parameter for your own environment 

```
curl --location --request PUT 'https://{your domain}/rest/{your store code}/V1/categories/{your sub category id}' \
--header 'Authorization: Bearer {your admin token}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "category": {
        "name": "ENG NAME",
    }
}'

```
### Expected result (*)
When you access the category detail in admin and switch to related store view 

Expect only name field will uncheck "Use Default Value"

### Actual result (*)
Below fields will also uncheck "Use Default Value"
-  Enable Category
-  Include in Menu
-  URL Key

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by shikhamis11** [comment] 2020-09-15 11:27
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-09-15 12:26
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37665` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hostep** [comment] 2020-09-17 16:26
This is a known issue and exists for a long time, it's a duplicate of https://github.com/magento/magento2/issues/17186 btw (and strongly related to https://github.com/magento/magento2/issues/9186, but that's for products)
We [reported](https://github.com/magento/magento2/issues/9186#issuecomment-453638054) it to the Magento Enterprise support at the beginning of 2018 and it's still not fixed ...

**Comment by crabbynguyen** [comment] 2020-10-09 07:47
@magento I am working on this

**Comment by crabbynguyen** [comment] 2020-10-09 07:48
@magento add to contributors team

**Comment by crabbynguyen** [comment] 2020-10-09 07:48
@magento I am working on this

**Closed as completed** 2020-10-19 13:07 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Risk: low, Progress: done, CD, Reported on 2.4.0

**Comment by hostep** [comment] 2020-10-19 15:50
This got closed without specifying a reason, strange ... But let us leave it like this because it's a duplicate of https://github.com/magento/magento2/issues/17186

**Comment by sdzhepa** [comment] 2020-10-23 18:14
@hostep @crabbynguyen @stanleyyuenyiu 

The issue was closed by mistake.
At this moment, due to an internal jira ticket, this issue has been fixed and delivered with internal PR.
Related commits can be found using search based on internal ticket key `MC-37665`

https://github.com/magento/magento2/search?q=MC-37665&type=commits
