### ISSUE TITLE
Catalog Images Resizes not fetching width and height from Luma view.xml

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#24723] opened 2019-09-25 11:00 UTC
### Preconditions (*)

1. Magento2.2.2 fresh install Lume theme
2. 

### Steps to reproduce (*)

1.Create a product and add at least one image at size 700X900
2. NOTE load product page in frontend after all the bellow Further Debug has been completed.

### Expected result (*)

1. [Screenshots, logs or description]
2. I expected the image to be resized as specified in path `.../vendor/magento/theme-frontend-luma/etc/view.xml`:  From: https://github.com/magento/magento2/blob/2.2/app/design/frontend/Magento/luma/etc/view.xml from one of:
```
<image id="product_page_image_medium" type="image">
                <width>700</width>
                <height>560</height>
            </image>
            <image id="product_page_main_image" type="image">
                <width>700</width>
                <height>560</height>
            </image>
            <image id="product_page_main_image_default" type="image">
                <width>700</width>
                <height>560</height>
            </image>
```

### Actual result (*)

1. [Screenshots, logs or description]
2. Instead the image size is 544x700 

Further Debug file path: `.../vendor/magento/module-catalog/Helper/Image.php` From: https://github.com/magento/magento2/blob/2.2/app/code/Magento/Catalog/Helper/Image.php

```
 /**
     * Set image properties
     *
     * @return $this
     */
    protected function setImageProperties()
    {
        $this->_getModel()->setDestinationSubdir($this->getType());
        $this->_getModel()->setWidth($this->getWidth());
        $this->_getModel()->setHeight($this->getHeight());
        //Debug log start
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $this->_getModel()->getId();
        $logger->info('type:'.$this->getType().' | width:['.$this->getWidth().'] height:['.$this->getHeight().']');
         //Debug log end 
         ...
```

The above logs out in /var/log/test.log':
```
2019-09-25T10:33:47+00:00 INFO (6): type:image | width:[265] height:[265]
2019-09-25T10:33:47+00:00 INFO (6): type:thumbnail | width:[88] height:[110]
2019-09-25T10:33:47+00:00 INFO (6): type:image | width:[700] height:[700]
2019-09-25T10:33:47+00:00 INFO (6): type:image | width:[] height:[]
2019-09-25T10:33:47+00:00 INFO (6): type:thumbnail | width:[88] height:[110]
2019-09-25T10:33:47+00:00 INFO (6): type:image | width:[700] height:[700]
2019-09-25T10:33:47+00:00 INFO (6): type:image | width:[] height:[]
2019-09-25T10:33:47+00:00 INFO (6): type:small_image | width:[240] height:[300]
2019-09-25T10:33:47+00:00 INFO (6): type:small_image | width:[270] height:[340]
2019-09-25T10:33:47+00:00 INFO (6): type:small_image | width:[75] height:[90]
2019-09-25T10:33:47+00:00 INFO (6): type:small_image | width:[240] height:[300]
2019-09-25T10:33:47+00:00 INFO (6): type:small_image | width:[270] height:[340]
2019-09-25T10:33:47+00:00 INFO (6): type:thumbnail | width:[75] height:[90]
```
You can see 2 lines type:image which has width and height empty. Lines 4 and 7 . This should have a value of width:[700] height:[560]. But is Empty.

Little more inspecting fotorama config in chrome tool screen shoot attached show correct values from luma theme:
<img width="419" alt="Screenshot 2019-09-25 at 12 09 30" src="https://user-images.githubusercontent.com/3495481/65595849-89652200-df8d-11e9-9b5d-2d7345adb28a.png">

Thanks
Juliano

**Comment by engcom-Charlie** [comment] 2019-09-26 07:39
Hello @lano-vargas 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-26 07:39 UTC
Labels: Issue: Format is valid
