### ISSUE TITLE
shopping cart item are remove before credit card approve or decline is confirmed.

### ISSUE THREAD

**Issue by shelbypo** [magento/magento2#36598] opened 2022-12-12 22:05 UTC
### Preconditions and environment

- Magento version 2.3.7
I am working with PayPal advance payment with the Iframe with the button to access the paypal link for the iframe for payment the cart remove items and if the card is declined the redirect the home page displays in the iframe and the customer has to select product all over.

### Steps to reproduce

Paypal checkout

### Expected result

decline credit error

### Actual result

it return the home page in the iframe and cart item are lost

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-13 12:20
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-12-13 17:12
Hi @shelbypo ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.
Items are not removed from shopping cart page if the payment is declined for both logged in user and guest user. User is redirected back to checkout page if the payment is failed. And for successful payment, order placed successfully. Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible.
![image](https://user-images.githubusercontent.com/60198231/207399061-7b62cf73-23a3-462f-8d50-d30638575036.png)
![image](https://user-images.githubusercontent.com/60198231/207399126-2d7d7ea4-3301-4eff-a183-cdff55df042a.png)
Thank you.

**Comment by engcom-November** [comment] 2022-12-28 04:25
Hi @shelbypo ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-28 04:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
