### ISSUE TITLE
Export process running out of memory

### ISSUE THREAD

**Issue by adamzero1** [magento/magento2#32492] opened 2021-03-16 12:03 UTC
### Preconditions (*)
Can replicate on 2.3.5-p1, looking at the codebase this should be reproducible for any version beyond this.
1. Have a product catalog with a lot of products (>200K)
2. Have a php memory limit of 2G
3. ensure cron is running

### Steps to reproduce (*)
1. Initiate a "product" export from the Admin. (System => Data Transfer - Export)

### Expected result (*)
1. At some point the export file will be available.

### Actual result (*)
1. File is never generated.
2. Running the consumer manually (with something like: `php bin/magento queue:consumers:start --single-thread --max-messages=100 -vvv -- exportProcessor`, causes an "Out Of Memory" exception)

I understand that memory_limit settings can be increased, however, I believe this issue is application-specific as great care has been taken to take into account the current `memory_limit` settings, see [here](app/code/Magento/CatalogImportExport/Model/Export/Product.php#L822). 
The bug is caused by this logic not being used/re-used correctly

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adamzero1** [comment] 2021-03-16 12:04
@magento I am working on this

**Comment by adamzero1** [comment] 2021-03-16 12:05
@magento add to contributors team

**Comment by adamzero1** [comment] 2021-03-16 12:05
@magento I am working on this

**Comment by engcom-Hotel** [comment] 2022-11-16 16:27
Hello @adamzero1,

Thanks for the reporting and collaboration!

We are requested to review this issue in the latest Magento 2.4-develop or the latest released version. and let us know if the issue is reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment] 2022-12-01 07:04
Dear @adamzero1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-12-01 07:04 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update
