### ISSUE TITLE
Issue: Incorrect Data on Magento 2 Dashboard

### ISSUE THREAD

**Issue by SerhiiMandrykin** [magento/magento2#39137] opened 2024-09-03 12:12 UTC
### Preconditions and environment

- Magento version: 2.4.7
- Commit that caused the bug: https://github.com/magento/magento2/commit/dd769504d2a56e510b1632e8f1a5f42c9571af52
- Suggestion: rollback the commit

### Steps to reproduce

1. Go to frontend.
2. Place 2 orders.
3. Change the creation date of the first order: -20h (in `sales_order` table)
4. Go to Magento 2 Dashboard

### Expected result

Totals in the dashboard bar are calculated correctly

### Actual result

Totals are not calculated correctly:
![image](https://github.com/user-attachments/assets/8ad0202e-b74c-4dcf-baef-c575554ae7ca)

### Workaround:
1. Switch to a different timeframe: 
![image](https://github.com/user-attachments/assets/663c284e-1408-4006-831a-9bea26f7ca51)
2. Switch back to 24h:
![image](https://github.com/user-attachments/assets/4df67685-ecff-49e8-afa0-de84fa7dcb11)
3. The totals are calculated correctly:
![image](https://github.com/user-attachments/assets/ede3d455-b25e-4b68-9ad5-d3c39fc51729)

### Additional information

This bug was caused by https://github.com/magento/magento2/commit/dd769504d2a56e510b1632e8f1a5f42c9571af52 and this line: `$period = $this->getRequest()->getParam('period', $firstPeriod);`

Setting `$firstPeriod` as a default value IS NOT correct because it would be `today` instead of `24h` (see `\Magento\Backend\Model\Dashboard\Period::getDatePeriods`)

BUT by loading the dashboard there is no `period` parameter in the request so `24h` is pre-selected:
![image](https://github.com/user-attachments/assets/d5c4da04-376d-4515-b448-460fda177e47)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by SerhiiMandrykin** [comment] 2024-09-03 12:23
I prepared a fix in https://github.com/magento/magento2/pull/39138

**Comment by devchris79** [comment] 2024-09-03 13:04
Hi @SerhiiMandrykin does the fix work for the circumstances that were outlined in #36199 ?

**Comment by SerhiiMandrykin** [comment] 2024-09-03 13:09
@devchris79 works well for me

**Comment by engcom-Delta** [comment] 2024-09-12 12:11
Hi @SerhiiMandrykin ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and issue is not reproducible . Kindly refer the screenshots.

**Steps to reproduce -** 
1. Go to frontend.
2. Place 2 orders.
3. Check the Dashboard before changing the creation date 
![image](https://github.com/user-attachments/assets/6f2bf3c8-2cdd-40ed-8c0e-2f68be72672b)
4. Change the creation date of the first order: -20h (in sales_order table)
![image](https://github.com/user-attachments/assets/a8c719e4-27f1-462e-9b71-2c227d8a277e)
5. Go to Magento 2 Dashboard, observe data is displaying as expected
![image](https://github.com/user-attachments/assets/f1e108ff-b2fc-4557-8d7d-3f66c50cb0fb)

Please let us know if any other steps are needed to be performed.
Thanks.

**Comment by SerhiiMandrykin** [comment] 2024-09-12 12:22
Hi @engcom-Delta ,

On your first screenshot it says 2 orders and amount $1150
but it shows only one on the chart
![image](https://github.com/user-attachments/assets/f1478955-6624-476a-9e22-a414c1387bb2)

**Comment by engcom-Delta** [comment] 2024-09-30 08:46
Hi @SerhiiMandrykin ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-30 08:46 UTC
Labels: Component: Admin, Priority: P2, Progress: done, Issue: ready for confirmation, Issue: needs update, Area: Admin UI, Reported on 2.4.7
