### ISSUE TITLE
Sales order Bundle product item alignment issue

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#19501] opened 2018-12-01 10:54 UTC
### Preconditions (*)

1. Magento 2.3 - Develop

### Steps to reproduce (*)

1. Admin -> Sales -> Order -> Create New Order
2. Select Customer -> Add Product 
3. Choose Bundle Product -> Configure

### Expected result (*)

1. https://prnt.sc/lpavw8

### Actual result (*)

1. https://prnt.sc/lpaxe9

**Comment by magento-engcom-team** [comment] 2018-12-01 10:54
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-03 12:39
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-12-03 14:02
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96871`, `MAGETWO-96872` were created

**Comment by magento-engcom-team** [comment] 2019-01-15 12:17
Hi @saphaljha. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-29 03:48
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#19502 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [5d7cd50277d2a9115e839b694fda01b76548bf4d](https://github.com/magento/magento2/commit/5d7cd50277d2a9115e839b694fda01b76548bf4d)
 - [fbf5ebb57de8836ac9ac7480cec7afa0deca8ff8](https://github.com/magento/magento2/commit/fbf5ebb57de8836ac9ac7480cec7afa0deca8ff8)
 - [9c0458974065d77e62ac95bbf18f85dae79c1cc5](https://github.com/magento/magento2/commit/9c0458974065d77e62ac95bbf18f85dae79c1cc5)
 - [2479f44fea5de69563b5d1579d65679da261b250](https://github.com/magento/magento2/commit/2479f44fea5de69563b5d1579d65679da261b250)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-29 03:48 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend
