### ISSUE TITLE
Email preview is blank (silently fails when provided with not valid HTML)

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#37337] opened 2023-04-05 11:45 UTC
### Preconditions and environment

- Magento version 2.4.5+
Since introduction of `\Magento\Framework\Filter\Input\PurifierInterface` for `\Magento\Framework\Filter\Input\MaliciousCode` the external package `ezyang/htmlpurifier` to purify HTML is used.

It purifies HTML here: `\HTMLPurifier::purify`  but based on tokens (kind of AST for HTML). So during tokenization the package `\HTMLPurifier_Lexer_DOMLex::tokenizeHTML` allows the code to silently fail without any error or logs.
![Selection_106](https://user-images.githubusercontent.com/3192770/230069534-12842a2f-92ab-4a1c-8480-5644b6fb41e5.png)

https://github.com/ezyang/htmlpurifier/blob/909dda6621cf06eb5ac1ea80955306c818d7122f/library/HTMLPurifier/Lexer/DOMLex.php#L76

This will result in blank preview page without any tip where to start debugging!
![comeon](https://user-images.githubusercontent.com/3192770/230070019-3b8b2ab1-094d-4921-b84f-616054fcc794.jpg)

### Steps to reproduce

1. Create email template with invalid HTML
2. Preview this template
3. See blank page

### Expected result

In case invalid HTML is feed into template processor, the meaningful errors/warnings are shown.

### Actual result

The preview page silently respond with blank page with no logs

### Additional information

Possible workaround is to inject custom purifier into `\Magento\Framework\Filter\Input\MaliciousCode` 
Partly related to https://github.com/magento/magento2/pull/35816 
### Release note

In case invalid HTML is feed into template preview processor, the meaningful warnings are shown

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-04-20 04:49
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-04-20 05:44
Hi @ilnytskyi ,
Thank you for reporting and collaboration. Verified the behavior on Magento 2.4-develop instance with below steps performed but the issue is not reproducible.
Steps performed:
1. Create Email template from Admin - marketing - Email Templates - Add new Template
2. Load any email template
3. Modify Template content with invalid html
4. Preview Template
**No issue:** No blank content is displayed when previewed. Invalid content added is displayed without any errors. This seems to be expected behavior as when tried in other html editors also, no error messages are displayed when invalid html scripts are ran for example in: https://www.w3schools.com.
Kindly recheck on 2.4-develop instance and provide supporting documentation / proofs to consider this as valid bug.
![image](https://user-images.githubusercontent.com/60198231/233268950-2b08f018-3dee-4b0b-a9ab-5387a7adef95.png)
![image](https://user-images.githubusercontent.com/60198231/233269013-2f00e2f3-7599-4cd4-8893-0ad1d6bf53b4.png)
![image](https://user-images.githubusercontent.com/60198231/233269104-081ab1a3-929c-4374-a65f-c3a72011dad5.png)
![image](https://user-images.githubusercontent.com/60198231/233269063-c77e30d6-2b7d-4ee8-ae4d-1893a1004f85.png)

**Comment by engcom-November** [comment] 2023-05-03 03:39
Hi @ilnytskyi ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-05-03 03:39 UTC
Labels: Issue: needs update, Reported on 2.4.5
