### ISSUE TITLE
Luma theme - Product Added to Cart Success Message Reloads on All Pages

### ISSUE THREAD

**Issue by taylordipentino** [magento/magento2#5530] opened 2016-07-07 21:21 UTC
## Steps to reproduce
1. Install Magento 2.0.7 from magento.com (I think it also happens with Magento 2.1)
2. Create a new navbar category with a product in it.
3. With Luma theme enabled, navigate to the category page and click "Add to Cart" on thumbnail or navigate to the product page and click "Add to Cart".
## Expected result
1. Product is added to cart and displays the success pop-up once, then goes away on reload or page change.
## Actual result
1. Product is added to cart and the success pop-up is displayed.
2. The success pop-up continues to load no matter which other pages you visit on the store.

**Comment by tkacheva** [comment] 2016-07-08 15:55
@taylordipentino I can't reproduce on 2.1. Message disappears upon page reload

**Comment by taylordipentino** [comment] 2016-07-08 16:00
Hmm. Strangely I cannot seem to reproduce it on 2.0.7 now either, which is where I originally discovered the issue. I guess it's not a real issue, then.

**Comment by taylordipentino** [comment] 2016-07-11 03:22
Just figured out what was causing the issue. Having Admin->Stores->Configuration->General->Web->Default Cookie Settings->Cookie Restriction Mode set to "No" seemed to be why it was occurring. I noticed that when the issue would occur, the only way I could make the notice go away was by deleting my browser's cookies. Changing this setting to "Yes" seemed to have made it stop happening. This is on Magento 2.0.7, not sure if it is still an issue in 2.1.

**Comment by plentyhappy** [comment] 2016-07-12 14:46
Cookie restriction mode did not work for me.  Even if the problem was solved, the cookie message might scare away customers (in my opinion).

Here's a similar thread:

https://github.com/magento/magento2/issues/5301#issuecomment-232067439

**Comment by dthampy** [comment] 2016-07-12 22:37
An internal ticket MAGETWO-54866 has already been created by Support and In Progress for the same issue from a different gitHub ticket

**Comment by veloraven** [comment] 2016-09-27 12:58
Internal ticket for develop branch - MAGETWO-54866, fix is in commit 9515999
Internal ticker for branch 2.1 - MAGETWO-56956, fix is in commit 39b35ec
Internal ticket for branch 2.0 - MAGETWO-56955, fix is in commit 592ded2

**Closed as completed by veloraven** 2016-09-27 12:58 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Component: Checkout, Issue: Format is not valid

**Comment by bondimedical3** [comment] 2016-12-27 03:25
None of the above fixes work!

**Comment by Koc** [comment] 2017-06-21 11:40
still occurs on 2.1.7. Please reopen

**Comment by bondimedical3** [comment] 2017-06-21 22:16
I agree. I have submitted multiple tickets about this issue but they simply ignore it and close the issue. Very unprofessional.

**Comment by rotanev** [comment] 2017-07-24 16:04
Temporary solution (saves his time and nerves):

1. Make copy of `vendor/magento/module-theme/view/frontend/web/js/view/messages.js` file:
<pre>
[magento@server webhome]# cp vendor/magento/module-theme/view/frontend/web/js/view/messages.js \
app/design/frontend/&lt;VendorName&gt;/&lt;theme&gt;/Magento_Theme/web/js/view/messages.js
</pre>

2. Find next line:
<pre>
$.cookieStorage.set('mage-messages', '');
</pre>
3. Replace with next:
<pre>
$(document).ready(function() {
      $.cookieStorage.set('mage-messages', '');
});
</pre>

P.S. @bondimedical3 - try this solution, may help

**Comment by bondimedical3** [comment] 2017-07-25 05:43
Your solution doesn't work. I am still seeing the same messages on every page.
![magento](https://user-images.githubusercontent.com/10808588/28557464-f65e1262-714f-11e7-98e8-5af4df4a7edf.jpg)

**Comment by ikis1520** [comment] 2017-09-29 14:29
How @rotanev not work for my I change from document.ready to use setTimeout and work fine thanks @rotanev 

Temporary solution (saves his time and nerves):

    Make copy of vendor/magento/module-theme/view/frontend/web/js/view/messages.js file:

[magento@server webhome]# cp vendor/magento/module-theme/view/frontend/web/js/view/messages.js \
app/design/frontend/<VendorName>/<theme>/Magento_Theme/web/js/view/messages.js

    Find next line:

$.cookieStorage.set('mage-messages', '');

    Replace with next:

setTimeout(function(){
                $.cookieStorage.set('mage-messages', '');
            },3000);

**Comment by thebreakfastcowboy** [comment] 2017-11-28 21:16
Wrapping $.cookieStorage.set('mage-messages', '') in the setTimeout function helped me out, for the record. Thanks for posting that, @ikis1520 !
