### ISSUE TITLE
Magento HTP 500 Error 

### ISSUE THREAD

**Issue by BUNIT1** [magento/magento2#36586] opened 2022-12-08 15:49 UTC
### Preconditions and environment

Magento ver. 2.3.5-p2

- Magento/Backstage is having issues with allowing customers to log into their accounts. Customers are receiving password reset emails, but are unsuccessful with signing in. Clear browser data cookies and history. Also, if you try to go through the process of creating a new order in Magento, it loads up to the HTP 500 Error. 
- Experience has been replicated by 6 other agents and two customers 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
![Screen Shot 2022-12-08 at 8 38 34 AM](https://user-images.githubusercontent.com/120118900/206492358-5db4e9e9-71c2-43f9-935b-fdd16081bf48.png)
![Screen Shot 2022-12-08 at 8 38 34 AM](https://user-images.githubusercontent.com/120118900/206492358-5db4e9e9-71c2-43f9-935b-fdd16081bf48.png)
![Screen Shot 2022-12-08 at 8 45 22 AM](https://user-images.githubusercontent.com/120118900/206492362-483b5884-61f7-4161-a5ba-0db629ff3d0e.png)
![Screen Shot 2022-12-08 at 8 45 22 AM](https://user-images.githubusercontent.com/120118900/206492362-483b5884-61f7-4161-a5ba-0db629ff3d0e.png)

### Steps to reproduce

1. Click on Orders
2. Create an order
3. Website store order
4. Add product 
5. Fill out customer information 
6. Submit order
7. Land on HTP 500 error 

### Expected result

Hoping to be able to place orders without getting that error messages and customers will be able to sign back in. 

### Actual result

Can go through the steps of creating order, but get an HTP 500 error screen when trying to submit the order. 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-09 09:53
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-09 10:26
Hi @BUNIT1,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Click on Orders
2.Create an order
3.Website store order
4.Add product
5.Fill out customer information
6.Submit order

We are able to place the order without any error.

<img width="1393" alt="Screenshot 2022-12-09 at 3 53 52 PM" src="https://user-images.githubusercontent.com/51680745/206681060-0f23a4bc-6756-4331-b82d-e2f814f6fadb.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by BUNIT1** [comment] 2022-12-09 15:49
Screen Recording 2022-12-09 at 8.27.20 AM.mov
<https://drive.google.com/file/d/1M81Ea0DAfgMlJgY-CmLSk1U5C3DlU5OF/view?usp=drive_web>
Hey, I unfortunately am still experiencing this same issue. Uploading
recording for reference:


Baylie Nixon // Team Lead, OpCX, Seeds

C: +1.801.580.0016 // E: ***@***.***

**Comment by engcom-Bravo** [comment] 2022-12-12 09:59
Hi @BUNIT1,

Thanks for your Update.

We are not able to see the your reference video.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-27 06:05
Hi @BUNIT1,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-27 06:05 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.5-p2
