### ISSUE TITLE
Customer session function getCustomerGroupId() doesn't work as expected 

### ISSUE THREAD

**Issue by ArnoVDC** [magento/magento2#23051] opened 2019-05-29 12:46 UTC
### Preconditions (*)
See Summary

### Steps to reproduce (*)
See Summary

### Expected result (*)
See Summary

### Actual result (*)
See Summary

### Summary(*)
In the `\vendor\magento\module-customer\Model\Session.php` class you have a function getCustomerGroupId(). I assume (and red the php documentation) that this returns the customer group Id of the current logged in user. In my case this returns 1. But if you execute `getCustomer()->getGroupId()` you will get a different result. In my case this was 4.

### Examples(*)
I tried it with logging: 
```
 public function __construct(
    LoggerInterface $logger,
    Session $customerSession,
  ) {
    $this->_customerSession = $customerSession;
    $this->_logger = $logger;
  }

public function logUserGroup(){
   $customerGroupId = $this->_customerSession->getCustomerGroupId();
    $test = $this->_customerSession->getCustomer()->getGroupId();

    $this->_logger->debug('customer group id: ' . print_r($test, TRUE));
    $this->_logger->debug('customer group id2: ' . print_r($this->_customerSession->getCustomerGroupId(), TRUE));
}
```

### Extra notes

- I tested this with all cache disabled
- I Create a user with default groupid: 1 then changed it to Group id 4
- This is my first Magento issue so please be nice 😉 

Maybe this function should not return the correct group id or I'm missing something

**Comment by magento-engcom-team** [comment] 2019-05-29 16:25
@AlexWorking Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-05-29 23:45
:white_check_mark: Confirmed by @okorshenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17095`, `MC-17096` were created

**Issue Available**: @okorshenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by MaxSouza** [comment] 2019-09-14 17:34
#mm19br

**Comment by MaxSouza** [comment] 2019-09-14 17:39
@ArnoVDC 

After customer group change, did you make logout on storefront? Because customer group id is in session of browser.

**Closed as completed** 2019-09-16 19:40 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Event: mm19br

**Comment by ArnoVDC** [comment] 2019-11-28 14:30
@MaxSouza 

Yes I did. The flow was: create customer=> change group in de backoffice => logout in storefront => login => check php logs after new login
