### ISSUE TITLE
Magento 2.4.5-p1 Bundles MSI stock problem

### ISSUE THREAD

**Issue by Ranjana42** [magento/magento2#37829] opened 2023-08-02 05:17 UTC
### Preconditions and environment

- Magneto version 2.4.5-p1
- PHP 8.1.21

### Steps to reproduce

- Create an inventory source and assign it to a stock with the main website selected
- Add a simple product, add stock quantity > 2 for it
- Add a bundle product, assign the simple product with amount 2
- Visit the product page of the bundle product

### Expected result

The bundle product should show in stock as the simple product has enough stock.

### Actual result

The bundle product shows out of stock.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Ranjana42** [comment] 2023-08-02 05:22
@magento give me 2.4-develop instance

**Comment by Ranjana42** [comment] 2023-08-02 05:54
@magento can you please disable MSI from magento

**Comment by engcom-Bravo** [comment] 2023-08-03 05:36
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-08-03 12:35
Hi @Ranjana42,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create an inventory source and assign it to a stock with the main website selected
- Add a simple product, add stock quantity > 2 for it
- Add a bundle product, assign the simple product with amount 2
- Visit the product page of the bundle product


**WITH MSI** The product is still showing in Product Page.


<img width="1397" alt="Screenshot 2023-08-03 at 12 15 58 PM" src="https://github.com/magento/magento2/assets/51680745/9e54cd59-bdb6-437c-8ad5-f4772eda42c1">




<img width="1474" alt="Screenshot 2023-08-03 at 12 16 41 PM" src="https://github.com/magento/magento2/assets/51680745/11fe8822-89a3-401a-a71c-46068aaca6e0">



**WITHOUT MSI** also product is showing in still in stock.


<img width="1416" alt="Screenshot 2023-08-03 at 12 21 06 PM" src="https://github.com/magento/magento2/assets/51680745/e2a7e1e7-8ee1-46e5-8a55-f3f0e3560e12">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible and please let us know if we are missing anything.

Thanks.

**Comment by hostep** [comment] 2023-08-03 20:18
@Ranjana42: [the release notes for MSI module version 1.2.6](https://experienceleague.adobe.com/docs/commerce-admin/inventory/release-notes.html?lang=en#v1.2.6) (which is included in Magento 2.4.6) mentions some fixes for bundled products and in or out of stock statuses. Maybe you could try to upgrade and see if the problem goes away by doing so?

Just guessing here 🙂

**Comment by engcom-Bravo** [comment] 2023-08-04 11:18
@hostep Thanks for your contribution & collaboration over here.

@Ranjana42 Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/inventory/release-notes.html?lang=en#v1.2.6 and please let us know if you are still facing any issue.

<img width="1043" alt="Screenshot 2023-08-04 at 11 23 11 AM" src="https://github.com/magento/magento2/assets/51680745/7d9401cd-3ecd-4e5f-aec7-5ac1d8f532c4">


Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-16 06:06
Hi @Ranjana42,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-16 06:06 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
