### ISSUE TITLE
Can't add an order manually in back

### ISSUE THREAD

**Issue by jgutierrezs** [magento/magento2#35345] opened 2022-04-21 04:56 UTC
### Preconditions (*)

1. Magento Ver 2.4.4
2. There is no complex procedure to emulate the bug, simply log in as administrator, add a new order, choose the customer, product and when we click to add product to the order nothing happens and the session is lost.

### Steps to reproduce (*)

1. Login with user administrator
2. Add Order
3. Select Customer
4. Select Product
5. Add Product to Order
6. It does not add the product, it does not indicate any error, simply nothing happens and the session is lost.

### Expected result (*)

1. The product is expected to be added to the order.
2.

### Actual result (*)

1. The product is not added to the order and the session is lost.
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-04-21 05:42
@magento give me 2.4.4 instance

**Comment by engcom-Hotel** [comment] 2022-04-21 05:43
@magento give me 2.4-develop instance

**Comment by jgutierrezs** [comment] 2022-04-21 05:57
Hello good afternoon, in this environment the bug does not occur. It does
correctly add the product to the order in the backend.

**Comment by engcom-Hotel** [comment] 2022-04-21 08:08
Hello @jgutierrezs,

We have tried to reproduce this issue in Magento 2.4.4 and 2.4-develop branches, but for us, the issue is not reproducible. Please refer the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/164409326-0b08d722-61c7-497b-8e0d-f5c6913c7ab2.png)

Please suggest to us if we need to use any specific type of product like simple, configurable product, etc.

Thanks

**Comment by sdzhepa** [comment] 2022-04-21 13:14
@magento give me 2.4-develop instance

**Comment by jgutierrezs** [comment] 2022-04-21 21:50
I can't reproduce the problem in this environment either.

I tell you that the version of PHP that I have installed is 8.0.

Thanks

**Comment by engcom-Hotel** [comment] 2022-04-22 06:49
Hello @jgutierrezs,

Thanks for the reply!

As per the [system requirement](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html), Magento 2.4.4 requires `PHP 8.1`. And also as mentioned in the main description, we have tried to reproduce the issue, but the issue is not reproducible for us.

Please go through with [my comments](https://github.com/magento/magento2/issues/35345#issuecomment-1104847538) here and let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-06 08:24
Dear @jgutierrezs,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-05-06 08:24 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by marseilleantiquites** [comment] 2022-10-27 09:47
Hello, 

I encounter exactly the same problem like @jgutierrez and I would have been interested in a way to solve this problem because as far as I am concerned I already use php8.1 ! 

> Cher@jgutierrezs,
> 
> Nous avons remarqué que ce problème n'a pas été mis à jour pendant une période de 14 jours. Par conséquent, nous supposons que ce problème est résolu maintenant, nous le fermons donc. Veuillez créer un nouveau ticket ou rouvrir ce ticket si vous avez besoin de plus d'aide à ce sujet.
> 
> Salutations
