### ISSUE TITLE
API - No error when updating stock when auto increment is exceeded in inventory_source_item 

### ISSUE THREAD

**Issue by bjornmeat** [magento/magento2#32540] opened 2021-03-18 08:16 UTC
### Preconditions (*)

1. Magento 2.4.1
2. Magento Rest API

### Steps to reproduce (*)

1. Table inventory_source_item table with source_item_id larger than 4294967295
2. Post source item update to rest/V1/inventory/source-items
3. Response will be 200 ok

### Expected result (*)

1. Response from API should be error updating, since data is not stored
2.

### Actual result (*)

1. Response from API is 200 ok 
2. Data is not saved, since max value of primary key source_item_id is type INT with max value of 4294967295

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-30 12:59
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41645` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by vovsky** [comment] 2021-04-30 13:53
@magento I am working on this

**Comment by engcom-Delta** [comment] 2024-09-09 11:09
Hi @bjornmeat ,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce -**
1. Table inventory_source_item table with source_item_id larger than 4294967295, Observe DB does not allow to provide source_item_id larger than 4294967295
![image](https://github.com/user-attachments/assets/1973401b-c360-40f4-999d-4b05476c573d)
2. Post source item update to rest/V1/inventory/source-items
![image](https://github.com/user-attachments/assets/4e77af5f-5dfc-4adb-a22c-bd6640540155)
3. Response will be 200 ok
![image](https://github.com/user-attachments/assets/15d3aceb-a342-4f0e-854d-0277c4efd968)
Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.
Thanks.

**Closed as completed by engcom-Delta** 2024-09-09 11:09 UTC
Labels: Issue: Confirmed, Component: Webapi, Component: Inventory, Reproduced on 2.4.x, Priority: P3, Progress: done
