### ISSUE TITLE
Minifying templates breaks when two consecutive comments exist and first is //

### ISSUE THREAD

**Issue by iwkse** [magento/magento2#34880] opened 2021-12-23 22:46 UTC
I've noticed when you use // with phtml the static generator is going to strip the comment, it doesn't happen the same when using # or /* */

### Preconditions (*)
Tested with 2.4.2

### Steps to reproduce (*)
1. Write in a phtml template file, something like: 
```
<span><?php // foo ?><?php // bar ?></span>
```
### Expected result (*)
```
<span><?php ?><?php ?></span>
```
### Actual result (*)
```
<span><?php</span>
```
---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by mrtuvn** [comment] 2021-12-28 23:23
PR Fix here https://github.com/magento/magento2/pull/33016

**Comment by engcom-Hotel** [comment] 2021-12-31 06:59
Hello @iwkse,

We have tried to reproduce the issue in Magento 2.4-develop branch and it is reproducible for us with the given steps in the main description.

Hence confirming the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-14 11:18
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2058 by the internal team
Related commits: https://github.com/search?q=AC-2058&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-09-14 11:18 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Framework

**Comment by maaarghk** [comment] 2023-07-07 14:45
did anyone test it or did you just put it out there for a laugh to see what would happen

**Comment by engcom-Hotel** [comment] 2023-07-10 13:19
Hello @maaarghk,

As per the process, we are testing all the PRs before merging them and as I can see in its related JIRA, there is a QA comment that this issue has been fixed. 

But still, if you found that the issue is still not fixed, then please let us know in more detail. We will be happy to reopen this to work on this.

Thanks
