### ISSUE TITLE
when installing magento 246 in php 8.1.4 then showing invalid token type

### ISSUE THREAD

**Issue by bhushanmeetanshi** [magento/magento2#37500] opened 2023-05-15 12:58 UTC
### Preconditions and environment

- Magento version :magento 2.4.6
- execute this command:- composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.6 m246 in windows using xampp php 8.1.4

### Steps to reproduce

1. install xampp 8.1.4
2. open xampp shell
3. go through the htdocs path
4. execute this command:-  composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition:2.4.6 m246
5. input personal access token

### Expected result

Command should be executed successfully after installation and after input git personal access key

### Actual result

when installing magento 246 in php 8.1.4 then showing invalid token type

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-05-16 12:10
Hi @bhushanmeetanshi ,
Thank you for reporting and collaboration. Verified the issue by trying to install both project-community-edition:2.4.6 (using composer create-project command) and 2.4.6-develop instance (using git clone command) but the issue is not reproducible. Please note that github personal access token is not required when trying to install using composer create-project command for open source version and instead ensure using valid public key and private key from https://account.magento.com/ .
Github personal access token is required when trying to do git cone from magento-gl repository and check if the token is expired / invalid from github settings - developer settings - personal access token - generate new access token if expired.
Thank you.

**Comment by engcom-Dash** [comment] 2023-06-08 09:42
Hello @bhushanmeetanshi ,

As we are not able to get the latest update on the issue. We are closing the issue for now. Please feel free to reopen it or ask us to reopen.

Thanks

**Closed as completed by engcom-Dash** 2023-06-08 09:42 UTC
Labels: Issue: needs update, Reported on 2.4.6
