### ISSUE TITLE
Admin -> Customer: Postcode edit within grid doesnt works (magento 2.1)

### ISSUE THREAD

**Issue by antonlazarchenko** [magento/magento2#6665] opened 2016-09-19 13:13 UTC
At admin panel in "Customer" section I tried to make quick eidt of postcode for specified customer inside grid, but information didn't save at all and no error messages displayed.
### Preconditions

Magento 2.1 CE
PHP 7.0.10
10.1.17-MariaDB  
### Steps to reproduce
1. Enter to admin panel and follow to "Customers" -> "All customers"
2. Inside customer grid click to postcode field of any customer account (postcode field should be empty)
3. Fill any test postcode number and save customer info.
### Expected result

Magento should save postcode. Otherwise it should display any error message.
### Actual result

Information didn't save and no error displayed. Success message shortly appeared instead of error.
### Additional instructions

Follow theese steps at screenshots to reproduce
![image](https://cloud.githubusercontent.com/assets/2114943/18632876/5c7cfe3a-7e82-11e6-9369-834a2cdc9362.png)

Choose customer, edit empty zip code and press save.
![image](https://cloud.githubusercontent.com/assets/2114943/18632937/a59988cc-7e82-11e6-9662-a504334c345e.png)

This you can see after pressing save but "success message" quickly disappears
![image](https://cloud.githubusercontent.com/assets/2114943/18633045/155d23da-7e83-11e6-842c-c6a4f184720e.png)

And then you can see nothing changes.

Only if I set information inside account (screenshot below) then I could edit postcode within grid of all customers.
![image](https://cloud.githubusercontent.com/assets/2114943/18633170/a06f38f0-7e83-11e6-87a3-dcdb23fb1c58.png)

**Comment by sevos1984** [comment] 2016-09-21 12:00
Have you run customer grid indexer?

**Comment by antonlazarchenko** [comment] 2016-09-21 12:47
@sevos1984 yes, I did. After updating postcode all indexes were "ready" and also I did indexer:reindex to make sure. It doesn't helps.

**Comment by sevos1984** [comment] 2016-09-26 12:05
Internal ticket created MAGETWO-58953. Thanks for reporting.

**Comment by magento-engcom-team** [comment] 2017-10-06 11:30
@antonlazarchenko, thank you for your report.
We've created internal ticket(s) MAGETWO-58953 to track progress on the issue.

**Comment by keyurshah070** [comment] 2017-10-23 10:31
Started Investing on this @okobchenko  @ishakhsuvarov

**Comment by keyurshah070** [comment] 2017-10-23 10:40
can we add postcode field as same as country (non editable ) ? as post code is part of customer address so to only save post code is not possible.  It create an issue with other field also, like city,phone . Any suggestion  on this ? @okobchenko @ishakhsuvarov

**Comment by keyurshah070** [comment] 2017-10-23 19:30
Any suggestions @okobchenko

**Comment by magento-engcom-team** [comment] 2019-01-30 13:32
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment] 2019-01-30 13:34
![2019-01-30 15 33 30](https://user-images.githubusercontent.com/13456702/51984637-82d8e600-24a4-11e9-88c6-7a8c7e569559.gif)
Issue is not reproducible in latest `2.3-develop` branch. Closing the issue for now.

**Comment by vasilii-b** [comment] 2019-01-30 13:40
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-30 13:40
Hi @vasilii-b. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-30 13:40
Hi @vasilii-b, here is your [Magento instance](https://i-6665-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-6665-2-2-develop.instances.magento-community.engineering/admin](https://i-6665-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kisroman** [comment] 2019-09-29 11:55
This issue was fixed by https://github.com/magento/magento2/commit/c2c2fd5.

**Closed as completed by kisroman** 2019-09-29 11:55 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
