### ISSUE TITLE
Minicart shows no product even when I have products in cart

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4010] opened 2016-04-05 11:03 UTC
Sometimes, when I have products in cart, this is shown:

![image](https://cloud.githubusercontent.com/assets/9195659/14279634/a6830756-fb04-11e5-916f-0385c4df6ff6.png)

Then, I add 1 product, and the minicart started to show this new added product together with the old products in cart:

![image](https://cloud.githubusercontent.com/assets/9195659/14279666/e3710e74-fb04-11e5-8c9a-86f0e159e4ac.png)

Regards
Jaime

**Comment by ishakhsuvarov** [comment] 2016-04-05 13:00
@jaimestuardo Thank you for reporting this issue. Could you please provide more information on the steps to reproduce the issue? Which way did you add products which are not shown?

**Comment by jaimestuardo** [comment] 2016-04-14 01:25
I have found how to reproduce it. 
1. Disable purchase of guests
2. Load frontend not logged in and add a product to shopping cart (just 1 of it)
3. The product is added to mini cart
4. Try to purchase. Shopping cart will be displayed telling that guest purchase is disabled
5. Go to login page and authenticate (in this page, you will see a 1 in the minicart indicator)
6. My account page will be loaded and the minicart indicator will be empty. If you click it, you will see that there is no product in cart.
7. Add a new product (just 1 of it)
8. Then, you will see 2 in the minicart indicator. If you click it, you will see the product just added besides the product you added before.

**Comment by sdzhepa** [comment] 2016-04-14 13:44
@jaimestuardo, We have tried, but could not reproduce this issue on the latest code from repo. (commit f93b8daf1db281820161).
We use next steps(based on Your comment)

Preconditions:
- Latest Magento 2 version is installed
- Allow Guest Checkout = No (STORES > Configuration > Sales > Checkout > Checkout Options)
  (!) All other Magento 2 settings in default state as after install
- Simple product is created
- Test customer is created(without any product in cart)

Steps to reproduce:
- Go to Storefront as Guest 
- Add Simple product to cart
  Result: Product is added to cart, Mini cart has 1 Simple product. Red Icon with number 1 is presented near mini cart

Test flow #01:
1 Click "Go to Checkout" from mini cart
Result: Modal window with ability to Sign In or Create an Account is appeared
2 Sign In as customer from preconditions
Result: Customer is successfully logged in. Mini cart has 1 Simple product. Red Icon with number 1 is presented near mini cart
3 Add Simple product to cart again
Result: Two product is presented in Mini cart(Simple product, qty=2) Red Icon with number 2 is presented near mini cart

Test flow #02:
1 Click link 'Sign In' in the top of the page
Result: Page "Customer Login" is opened
2 Sign In as customer from preconditions
Result: My Account(My Dashboard) page is opened. Customer is successfully logged in. Mini cart has 1 Simple product. Red Icon with number 1 is presented near mini cart
3 Add Simple product to cart again
Result: Two product is presented in Mini cart(Simple product, qty=2) Red Icon with number 2 is presented near mini cart

Test flow #03:
1 Go to shopping cart page(link 'View and edit cart' from mini cart)
Result: Simple product with qty=2 is presented
2 Click "Proceed to Checkout" button(from Summary section)
Result: Modal window with ability to Sign In or Create an Account is appeared
3 Click "Create an Account" and create new customer
Result: New customer is created. My Account(My Dashboard) page is opened. Mini cart has 1 Simple product. Red Icon with number 1 is presented
4 Add Simple product to cart again
Result: Two product is presented in Mini cart(Simple product, qty=2) Red Icon with number 2 is presented near mini cart

Probably you are using not latest code base or need clarification in steps/preconditions etc.

**Comment by jksimoniii** [comment] 2016-04-14 19:03
@jaimestuardo @sdzhepa @ishakhsuvarov 

I am seeing the same issues on iOS devices

**Comment by jksimoniii** [comment] 2016-04-14 19:08
I think we have drilled it down to an issue related to these lines of code in Magento_Checkout::cart/minicart.phtml.  summary_count results in undefined on Safari iOS while 0 in other browsers

```
            <!-- ko if: cart().summary_count -->
                <!-- ko text: cart().summary_count --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
```

**Comment by ishakhsuvarov** [comment] 2016-04-15 06:44
@jksimoniii Looks like you are using the installation from `2.0` branch. There is a fix for that in `develop` branch. Any chance you could verify that?

**Comment by jksimoniii** [comment] 2016-04-15 21:42
@ishakhsuvarov Great, thanks!  Looks like that will solve the problem we are having.  Will this be wrapped in the 2.1 release ?

**Comment by ishakhsuvarov** [comment] 2016-04-20 09:15
@jksimoniii Yes, the fix should be included in the 2.1

**Comment by jaimestuardo** [comment] 2016-05-16 12:44
How can I solve the problem momentarily using version 2.0.4?

**Comment by jaimestuardo** [comment] 2016-05-19 22:56
I have updated to 2.0.6 and problem still exists.

**Comment by piotrekkaminski** [comment] 2016-06-09 18:36
@jaimestuardo can you check on 2.1RC? it should be fixed there. If problem persists, please open a new issue.

**Closed as completed by piotrekkaminski** 2016-06-09 18:36 UTC
Labels: Progress: needs update

**Comment by kvSanthosh** [comment] 2016-06-27 05:46
I have the same issue in 2.0.7, this is found when we enable Persistent Shopping Cart, if we have some product in our cart when we re login the mini cart will show 0 items and when we add some product the cart will show the existing products and newly added one together.

**Comment by pantaoran** [comment] 2016-07-13 06:35
I think these issues are the same as the big discussion in #3572

**Comment by apurv-anand** [comment] 2016-09-25 10:30
+1. Facing same issue in M2.1.1

**Comment by pboisvert** [comment] 2016-09-25 19:37
@apurv-anand this ticket is closed. If you are experiencing an issue, can you open a new ticket and provide full system info and steps to reproduce"

**Comment by iprabhakar** [comment] 2016-12-14 06:24
I am using M2.1.2 facing same issue, when I add product after login the not showing in mini cart. Please help me to resolve this issue.

**Comment by dambrogia** [comment] 2016-12-20 01:29
This solved the problem for me, I have read elsewhere that is could possibly cause validation when adding items into your cart (product is out of stock, etc.), but I haven't looked further into that. Anyone who would like to would be welcomed to enlighten me with their information :)

I did this simple fix and haven't had a problem since.

Reference to @fhennessy 's answer:
https://github.com/magento/magento2/issues/5377#issuecomment-243308475

**Comment by priyatoshojha** [comment] 2016-12-20 10:40
@domdambrogia 
I have product in cart after login and when I logout and again login then no product in minicart and when I add any product in cart then my minicart is updated and show the prev added products.
Please let me know if you have resolved this issue.

**Comment by iprabhakar** [comment] 2016-12-20 18:08
I have same issue, after enable Full Page Cache this issue is resolved.

**Comment by priyatoshojha** [comment] 2016-12-21 07:46
@iprabhakar  
Thanks, Yes it worked for me after enable full page cache, 
So can you please explain why its connected with FPC . 
Please let me know if any one knows.

**Comment by FloWord** [comment] 2017-03-17 07:23
My Solution for refresh Problem:
https://github.com/magento/magento2/issues/5377

You simply need to change
"bindSubmit": false
to
"bindSubmit": true
