### ISSUE TITLE
Can not save "CMS Block" with empty content

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#23800] opened 2019-07-20 03:36 UTC
**Fill All Required Field but can not save CMS Block.**

We can save the CMS Page with the empty content but we can not save 'CMS Block' with empty content. We should remove the validate in CMS Block form (**like the CMS Page**) (**And as  it displays - with no required symbol**).

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to Backend.
2. Select Content->Blocks->Add New Block
3. Fill all **required field** with '*'
4. Click Save

![test](https://user-images.githubusercontent.com/8234209/61573512-21e8ad00-aada-11e9-98f3-103db9e39704.gif)

### Expected result (*)

1. Save successfully with the empty content
### Actual result (*)

1. No thing happened. No notification.

**Comment by edenduong** [comment] 2019-07-20 03:36
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-20 03:36
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-20 03:37
Hi @edenduong, here is your [Magento instance](https://i-23800-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23800-2-3-develop.instances.magento-community.engineering/admin](https://i-23800-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2019-07-20 03:53
@krishprakash: Please confirm for me this issue :)

**Comment by krishprakash** [comment] 2019-07-20 13:52
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-20 13:52
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-20 13:53
Hi @krishprakash, here is your [Magento instance](https://i-23800-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23800-2-3-develop.instances.magento-community.engineering/admin](https://i-23800-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-07-20 14:01
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18364` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rogyar** [comment] 2019-07-21 14:05
Hi @edenduong. Thank you for the report. Definitely, there's an issue. But the issue is rather in the absent validation message than in the saving a CMS block with an empty message. 
We should carefully think about the use cases of empty CMS blocks. I can't figure out many of them (an empty CMS page has much more use cases though). 
On the other hand, there's a possibility that store admin creates a CMS block and forgets to put content. This scenario may result in additional time for looking for the empty block in page contents. 
So my point here is, we should fix the validation message for the empty content block instead of allowing empty blocks.

**Comment by edenduong** [comment] 2019-07-23 16:18
Hello @rogyar,
Thank you for your feedback.
I think we can use the empty CMS block. Because the admin or developer can create the page with the empty block for the layout (the content staff can modify it later.). The layout with some empty block content which the staff can add it depends on their requirements. It may be useful for preparing the website page.
I see in the DB, that field also "Can be null":

![image](https://user-images.githubusercontent.com/8234209/61728660-debf6000-ad9f-11e9-9524-4231e7ce788e.png)

As the CMS Page, I think we also can leave them empty .

**Comment by rogyar** [comment] 2019-07-24 04:35
Hi @edenduong. That makes sense. Another use case that comes in mind is for some languages the store owner might want to have the content empty. Thank you for providing the additional info.

**Comment by magento-engcom-team** [comment] 2019-08-09 15:40
Hi @edenduong. Thank you for your report. 
The issue has been fixed in magento/magento2#23801 by @edenduong in 2.3-develop branch
Related commit(s):
 - [1435253ef734fa6ad145c2477d2eff57862c8df0](https://github.com/magento/magento2/commit/1435253ef734fa6ad145c2477d2eff57862c8df0)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-08-09 15:40 UTC
Labels: Issue: Ready for Work, Component: Cms, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend
