### ISSUE TITLE
Paypal Express - product page shortcut button image not loading in sandbox mode

### ISSUE THREAD

**Issue by joe-vortex** [magento/magento2#37799] opened 2023-07-25 12:10 UTC
### Preconditions and environment

- Magento version - 2.4.4-p4
- Enable paypal checkout shortcut button on product page
- Paypal is in sandbox mode

### Steps to reproduce

1. Enable paypal checkout in config - sandbox mode
2. Enable shortcut button on product page
3. input type image is rendered from [magento/module-paypal/view/frontend/templates/express/shortcut_button.phtml](https://github.com/magento/magento2/blob/ca30c47787db932b9431e42226bb918e95c932d9/app/code/Magento/Paypal/view/frontend/templates/express/shortcut.phtml#L36)
4. image url is used https://github.com/magento/magento2/blob/ca30c47787db932b9431e42226bb918e95c932d9/app/code/Magento/Paypal/Model/Config.php#L1418

### Expected result

Paypal express shortcut button loads image and shows to user

### Actual result

https://fpdbs.sandbox.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecshortcut&locale=en_GB never loads and button does not show

### Additional information

This may be a temporary issue with paypal domain, howevever a fallback image should be provided, perhaps with a curl to check it's working.
https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecshortcut&locale=en_GB forwards to https://www.paypalobjects.com/en_GB/i/btn/btn_xpressCheckout.gif so this is limited to sandbox mode.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-01 13:15
Hi @joe-vortex,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Enable paypal checkout in config - sandbox mode
- Enable shortcut button on product page



<img width="1424" alt="Screenshot 2023-08-01 at 12 35 15 PM" src="https://github.com/magento/magento2/assets/51680745/1ca70a7c-094a-46e4-bc78-1f65abe0c8b5">




<img width="1485" alt="Screenshot 2023-08-01 at 12 35 35 PM" src="https://github.com/magento/magento2/assets/51680745/61646ac0-aeb4-4f64-9930-3124084b13ca">



Paypal express shortcut button loads image and shows to user.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by joe-vortex** [comment] 2023-08-01 13:18
@engcom-Bravo 
Unfortunately this is still not working. Please recheck. You can verify that https://fpdbs.sandbox.paypal.com/dynamicimageweb?cmd=_dynamic-image&buttontype=ecshortcut&locale=en_GB does not load. Please ensure you are using sandbox mode. Even if this URL resolved, it breaks functionality if it doesn't work, so the module should have a image file included. My client has raised the issue with us that their customers are unable to checkout with paypal from the minicart/cart because of this.
Thanks
Joe

**Comment by engcom-Bravo** [comment] 2023-08-02 12:56
Hi @joe-vortex,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Enable paypal checkout in config - sandbox mode
- Enable shortcut button on product page


We have used Sandbox paypal credentials only for placing an order.Could you please check latest version of the Magento.



https://github.com/magento/magento2/assets/51680745/a744d66a-1cc0-4d3b-b698-35c1c987ab85



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Franciscof-Serfe** [comment] 2023-08-02 14:37
@magento give me 2.4.4-p4 instance

**Comment by joe-vortex** [comment] 2023-08-02 14:39
Thanks for looking into this @Franciscof-Serfe - I don't know how else I can explain that there is still an issue, despite sharing the resulting URL that anyone can access and see it's not loading. It is part of the module so it needs to be fixed.

**Comment by engcom-Bravo** [comment] 2023-08-21 06:03
Hi @joe-vortex,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-21 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.4-p4
