### ISSUE TITLE
Unable to Retrieve Cookie Messages on a site within a subdirectory

### ISSUE THREAD

**Issue by NathanDayFE** [magento/magento2#32915] opened 2021-04-30 12:29 UTC
### Preconditions (*)

1.Magento 2.3.6
2. Site Created in a Sub Directory e.g. `/fr`

### Steps to reproduce (*)

1. Submit a Contact Us form

### Expected result (*)

1. Success or Error Message Displays

### Actual result (*)

1. No Messages Displayed

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

After looking into this a bit i discovered that in vendor/magento/module-theme/view/frontend/web/js/view/messages.js on line 32 it attempts to read the cookie messages from `$.cookieStorage` this has already been intiialised by `customer-data.js` and the path has been set to `/`. however on line 42 of the same file it resets the cookie using `$.mage.cookies` this has a path set to whatever has been configured for the cookie path, `/fr` in this example. because of this an empty cookie is created for `mage-messages` with the FR path. The next time that `messages.js` attempts to read the cookie 2 cookies exist one with the path `/` containing the actual message(s) and one with the path `/fr`, `$.cookieStorage.get` will traverse the path and return the contents of the first cookie it finds, in this case the empty cookie for `/fr`, this should be a relatively simple fix by adding the path `/` when setting the `mage-messages` cookie on line 42 of `messages.js`.

**Comment by mrtuvn** [comment] 2021-05-01 14:56
Hi Can you provide more details how do you setup website in sub folder ? Meaning you setup 2 sites right below
First folder contain main website
magento_root/

This folder contain second website ?
magento_root/fr/

**Comment by NathanDayFE** [comment] 2021-05-04 07:35
> Hi Can you provide more details how do you setup website in sub folder ? Meaning you setup 2 sites right below
> First folder contain main website
> magento_root/ <= run domain global.something.com
> 
> This folder contain second website ?
> magento_root/fr/ <= run domain fr.something.com

@mrtuvn In this particular case there are multiple websites running at the root directory with one website having 2 store views `DE` and `FR`, I wasn't the person to set this up in this way but what i can see is that the languages were setup in sub directories so that the language code displayed in the URL. I understand it's quite a common method to achieve this.

in this instance we have `example.com`, `example.co.uk` setup at the magento root with `example.ch/de` and `example.ch/fr` setup using the `de` and `fr` directories respectively.  the base URL and the Cookie paths have been configured to include the sub direcotry

**Comment by mrtuvn** [comment] 2021-05-16 04:38
i think common owner store will set multiples website like this
example.com/uk/ for uk website and example.com/de/ for de website (Magento allowed we set config like this in backend). Cookie path for each store need to re-config for each website scope

Can we reproduce in latest code base ?
You can request instance from magento CI with command above "magento give.."

**Comment by igorsKolcinsMagebit** [comment] 2021-09-03 14:04
Hey,
I have faced the same issue on **Magento 2.4.3.**
Two storeviews:
example.com/en/us
example.com/en/de

Messages were saved into cookies, but with path "/". Store view relative path "/en/us" or "/en/de" was empty.

I applied the changes from [#32617](https://github.com/magento/magento2/pull/32617) and the problem was **fixed**.

**Comment by engcom-Hotel** [comment] 2021-09-30 11:24
Dear @NathanDayFE,

It might be the issue with cookie_path. I request you to please try to implement the fix mentioned in [PR](https://github.com/magento/magento2/pull/32617) and let us know if this help you.

Thanks

**Comment by engcom-Hotel** [comment] 2021-10-14 06:56
Dear @NathanDayFE,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-10-14 06:56 UTC
Labels: Issue: needs update, Reported on 2.3.6
