### ISSUE TITLE
Campare list page broken in magento 2.3.5

### ISSUE THREAD

**Issue by santosh-ks153** [magento/magento2#29641] opened 2020-08-18 15:46 UTC
### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2020-08-18 16:14
It's hard to determine based on the very little information in this ticket, but it's probably a duplicate of https://github.com/magento/magento2/issues/27920 which got fixed in https://github.com/magento/magento2/pull/27926

**Comment by sdzhepa** [comment] 2020-08-18 18:09
@santosh-ks153

Could you please provide detailed steps and results?
 Summary of the issue
>Information on your environment
>Steps to reproduce
> Expected and actual results


Is it possible to reproduce on the latest `2.4-develop` code?
Is it possible to reproduce on the latest release Magento 2.3.5p2 composer code?

**Closed as completed** 2020-09-21 13:02 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done, Reported on 2.3.5
