### ISSUE TITLE
PHPDoc result type is wrong for \Magento\Framework\Data\Form\Element\AbstractElement::addElement() method

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2455] opened 2015-11-21 07:32 UTC
https://github.com/magento/magento2/blob/2.0.0/lib/internal/Magento/Framework/Data/Form/Element/AbstractElement.php#L87

Should be:

```
@return AbstractElement
```

**Comment by vzabaznov** [comment] 2016-06-22 13:11
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:11
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:11 UTC
Labels: Progress: needs update

**Comment by adragus-inviqa** [comment] 2016-07-14 08:38
@vzabaznov - he gave you an actual github link to your own repo. How hard is it to click it? You people are starting to behave more and more like automatons.
