### ISSUE TITLE
Message returned by static integrity composer test is confusing

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#3537] opened 2016-02-24 19:57 UTC
I created module using "vendor/foobar" name in `composer.json` and used Vendor_FooBar namespace. The I run static tests and I get following error:

```
For the module 'Vendor_FooBar', the expected package name is 'vendor/foobar'
```

This error message is confusing because it says it expects package name I already used. As far as I understand it should say following:

```
For the module 'Vendor_FooBar', the expected package name is 'vendor/module-foo-bar'
```

If my assumption is correct, value of `$this->convertModuleToPackageName($moduleName)` should be used instead of `$packageName` in message returned in `\Magento\Test\Integrity\ComposerTest::assertConsistentModuleName` method.

I can do PR if it's helpful.

**Comment by mzeis** [comment] 2016-05-30 10:04
I experienced the same problem and can confirm that the suggestion by @wojtekn works.

**Comment by duhon** [comment] 2016-06-22 16:28
Hello @wojtekn 

To allow us to research the issue, please, provide description according to the template.
Also please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by wojtekn** [comment] 2016-06-22 19:33
@duhon I think my description is enough to reproduce it, I even provided possible fix there. Don't be lazy.

**Comment by piotrekkaminski** [comment] 2016-08-26 03:00
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Message-returned-by-static-integrity-composer-test-is-confusing/idi-p/45307).

**Closed as completed by piotrekkaminski** 2016-08-26 03:00 UTC
Labels: improvement
