### ISSUE TITLE
Discount code error “Request does not match any route”

### ISSUE THREAD

**Issue by alexcrz** [magento/magento2#4946] opened 2016-06-10 00:53 UTC
Hi, I'm using magento 2.0.7, and I'm getting an error on the www.xxxx.xx/checkout/#payment page when I try to add the discount code, saying `Request does not match any route`. The code works if I try to add it in the cart , but not here. Also if I try to insert it while inspecting the page , I get this `https://xxxx.xxx/rest/default/V1/guest-carts/c31f5a164842f064cb237c6239618a7e/coupons/heyyou Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by komsitr** [comment] 2016-06-21 02:30
I have the same issue with Magento 2.1.0-rc2

**Comment by alexcrz** [comment] 2016-06-21 08:52
Still didn't found any solution, and now I'm getting a similair error with the paypal payment gateway. If I try to use it by inspecting the page, I get some /rest/default/V1.. 404 error.

**Comment by komsitr** [comment] 2016-06-21 09:12
@alexcrz I try debugging the code until reach Zend Framework HTTP Request class. In my case, the problem looks like nothing to do with Magento but Apache settings with Mod Security blocks PUT request.

From the dump of request variable, I got REDIRECT_REDIRECT_REQUEST_METHOD value = PUT but the key REQUEST_METHOD were changed to GET. The redirection seems to be from Error 501. This is the information I have right now. I will update my solution once found.

**Comment by oserediuk** [comment] 2016-06-22 13:09
Hello! Hello! To allow us research the issue, please, provide description according to the template.

**Comment by komsitr** [comment] 2016-06-22 16:12
Hi all,

The issue is fixed in my case. It causes by a rule in mod_security. There is nothing wrong with Magento code.

Basically you need to follow this step.
1. See Apache error log, find which rule id cause the problem.
2. Override that rule in your local .conf file
3. restart/grateful apache

Sidenote to Magento team:
.htaccess file only handle mod_security, but in our server it is now mod_security2. You might considering adjust this line in .htaccess

```
<IfModule mod_security2.c>
</IfModule>
```

**Comment by andimov** [comment] 2016-08-16 07:44
@alexcrz 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
Please feel free to reopen if it's needed.
@komsitr 
Thank you for solution!

**Closed as completed by andimov** 2016-08-16 07:44 UTC
Labels: Progress: needs update

**Comment by ywsw** [comment] 2018-07-20 15:49
@komsitr I am having this same issue (coupon code working in shopping cart with GET method but not working in checkout page which uses PUT method) and I do not have mod_security in my apache. Do you have any suggestions for me to get this working?

I am using Magento 2.2.5 and Apache 2.4

SOLUTION: (in my case) I was using POUND as a reverse proxy so I can use Varnish for HTTPS and by default POUND blocks PUT and DELETE requests. By adding in the command "xHTTP 1" between the ListenHTTPS in the POUND config, PUT and DELETE requests are now allowed. Issue solved. I hope this can be of help to someone.
