### ISSUE TITLE
Invalid input datetime format of value in Others locale 2.3.2

### ISSUE THREAD

**Issue by andy17612** [magento/magento2#24696] opened 2019-09-23 10:33 UTC
### Preconditions (*)

1.Magento 2.3.2 & 2.3-develop
2.Japen or China locale in admin 
* Backend-> Admin -> change the Backend admin panel language to Chinese

### Steps to reproduce (*)

1.Create or edit product
2.Change date field for new from to anything
3.Click Save

### Expected result (*)

1. Product Saves with new from date

### Actual result (*)

1.Error occurs stating "Invalid input datetime format of value '2019/9/24'
![image](https://user-images.githubusercontent.com/51680850/65513025-17d09980-dee3-11e9-8f8b-85af4007cb70.png)

If choose EN is working, but in others locale, like JP showing chinese will be error.

### Additional information
https://github.com/magento/magento2/issues/24696#issuecomment-534514561

> Not a local options,
> Please follow this step ;
> Backend-> Admin -> change the Backend admin panel language to Chinese (Taiwan,hongkong,China) or Japanese and then go to product > add or edit product > add a “special price or new product”date time, it will be showing “xxxx年xx月xx日” not a xxxx/xx/xx.

**Comment by engcom-Charlie** [comment] 2019-09-24 09:04
Hello @andy17612 
I cannot reproduce this issue on a fresh Magento 2.3-develop & 2.3.2
**Manual testing scenario:**

1. Set Chinese locale
![image](https://user-images.githubusercontent.com/51680850/65497745-61a98780-dec3-11e9-9702-039dbd332b25.png)
2. Create or edit product
3. Change date field for new from to anything
4. Click Save

**Actual result:**
Product saved
![image](https://user-images.githubusercontent.com/51680850/65497500-06779500-dec3-11e9-8054-2c361a3ec01d.png)
![image](https://user-images.githubusercontent.com/51680850/65497617-32931600-dec3-11e9-9359-3f57c0520946.png)

So i have to close this issue.
Thanks for your report!

**Comment by andy17612** [comment] 2019-09-24 11:25
Hi @engcom-Charlie.

Not a local options, 
Please follow this step ;
Backend-> Admin -> change the Backend admin panel language to Chinese (Taiwan,hongkong,China) or Japanese and then go to product > add or edit product > add a “special price or new product”date time, it will be showing “xxxx年xx月xx日” not a xxxx/xx/xx.

Thank you

**Comment by magento-engcom-team** [comment] 2019-09-24 12:53
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20372` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ravi-chandra3197** [comment] 2019-09-24 14:08
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-24 14:08
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-24 14:09
Hi @ravi-chandra3197, here is your [Magento instance](https://i-24696-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24696-2-3-develop.instances.magento-community.engineering/admin](https://i-24696-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by andy17612** [comment] 2019-09-25 04:14
I'm looking forward to your fix. thank you @engcom-Charlie

**Comment by andy17612** [comment] 2019-10-09 10:14
@geet07 Hi, May i know it is fixed in magento 2.3.3 now? or still working?

**Comment by frilogg** [comment] 2020-05-13 18:24
Anyone from @magento-devops that can advice when this matter will be resolved as it still a issue in the latest Magento Version?

**Comment by andy17612** [comment] 2020-06-07 20:27
@frilogg Do you have a solution?

**Comment by andy17612** [comment] 2020-06-28 07:17
@engcom-Charlie Do you have a solution? Thanks

**Comment by andy17612** [comment] 2020-07-30 08:31
@magento-engcom-team This problem is solved on 2.4 ??

**Comment by chapagain** [comment] 2020-08-02 05:12
A temporary quick fix can be the following:

- Click your user name on the top right in your admin panel.
- Click on the `Account Settings` submenu.
- Try to change `Interface Locale` to a different one (I changed from English US to English UK)
- Save
- Now, go to `Catalog > Products` and try to save any product with a change in `Set Product as New From` date.

You should be able to save the product successfully.

_Ref: https://magento.stackexchange.com/a/219936/1883_

**Comment by sdzhepa** [comment] 2020-09-15 20:40
Hello @andy17612 

During work on https://github.com/magento/magento2/pull/25372 that should fix this issue
was confirmed then issue cannot be reproduced on the latest `2.4-develop` branch.
This PR was closed because we are not able to deliver changes to the previous Magento versions through this repository.
We can accept, collaborate, fix, and deliver issues that actually on the `2.4-develop` only.
This information is mentioned in several public documents
- [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)  
- [GitHub Issues Processing Workflow: Verification](https://github.com/magento/magento2/wiki/GitHub-Issues-Processing-Workflow#verification)
-  [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) _this link exists in each new [issue report template](https://raw.githubusercontent.com/magento/magento2/2.4-develop/.github/ISSUE_TEMPLATE/bug_report.md)_


Closed this issue as cannot reproduce on the latest `2.4-develop`

**Closed as completed by sdzhepa** 2020-09-15 20:40 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Locale, Priority: P3, Severity: S2, Triage: Done, Progress: done
