### ISSUE TITLE
Invalid email format

### ISSUE THREAD

**Issue by kassner** [magento/magento2#33590] opened 2021-07-26 09:47 UTC
### Preconditions

1. Magento 2.4.2;

### Steps to reproduce

1. Go to checkout;
2. Use the e-mail address `test+å@example.com`

### Expected result

1. Order should be placed successfully for valid email formats;
2. For any invalid email formats entered in Shipping page, error message should be displayed in Shipping page itself but not on Payment page
![image](https://user-images.githubusercontent.com/60198231/126977085-43df9d02-4717-4eb5-84bc-2c7a3d7c6ee3.png)

### Actual result

1. `Invalid email format`: error message is getting displayed in Payment page after clicking "Place Order" button

![Screenshot from 2021-07-26 11-58-22](https://user-images.githubusercontent.com/301255/126970970-083d8362-9ae1-47e4-bf74-b4f04faa92bb.png)

### Debug

POST to `/rest/default/V1/guest-carts/:cartId/payment-information`:

Request:

![Screenshot from 2021-07-26 11-58-42](https://user-images.githubusercontent.com/301255/126971067-af23d581-adf6-4234-a448-4a54cb6cdac2.png)

Response:

![Screenshot from 2021-07-26 11-58-52](https://user-images.githubusercontent.com/301255/126971088-2cf0aae6-2a81-4054-b86a-26ad5a2c8ab6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kassner** [comment] 2021-07-26 09:48
@magento give me 2.4-develop instance

**Comment by kassner** [comment] 2021-07-26 10:05
As I understand from the RFC5321 and RFC5322, any unicode character can be used in the `local-part`.

It also mentions quoted-strings, but we can't use those either:

![Screenshot from 2021-07-26 12-01-57](https://user-images.githubusercontent.com/301255/126971718-06ee1d1a-7b52-433a-966a-1e7dca0120f1.png)

**Comment by engcom-November** [comment] 2021-07-26 10:42
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
**Steps:**
1. Front-end - Add a product to Cart and proceed to checkout
2. Enter email address: test+å@example.com, fill the form and click on Next button
3. Click on Place Order button
**Issue:** "Invalid email format" error message is getting displayed in payment page
Note: For any other invalid email formats used in shipping page, "Please enter a valid email address (Ex: johndoe@domain.com)" error message is displayed in Shipping page itself (http://yourstore.com/checkout/#shipping) but no payment page (http://yourstore.com/checkout/#payment).
![image](https://user-images.githubusercontent.com/60198231/126976031-dddf4ac7-0b40-4643-b704-6906639c4281.png)

**Issue:**
![image](https://user-images.githubusercontent.com/60198231/126976343-37370536-a7ed-4415-af51-dcc2324f4b08.png)

**Comment by magento-engcom-team** [comment] 2021-07-26 10:49
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42910` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ngorupaha** [comment] 2022-03-14 16:50
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by ngorupaha** [comment] 2022-03-14 17:06
magento give me 2.4-develop instance

**Comment by ngorupaha** [comment] 2022-03-14 17:46
@magento I am working on this

**Closed as completed** 2022-06-11 14:22 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Cart & Checkout
