### ISSUE TITLE
Region (State/Province) does not respect **Stores->Configuration->General->State Options->State is Required For** configuration in both shipping and billing address forms in checkout. 

### ISSUE THREAD

**Issue by id-graziano** [magento/magento2#10587] opened 2017-08-18 15:09 UTC
## Preconditions

1. Magento CE 2.1.8 Developer Mode
2. PHP 7.0.20
3. Apache 2.4

### Shipping Address
1. Download Magento CE 2.1.8 from Magento site, install with sample data.
2. Log in to admin panel, go to **Stores->Configuration->General->State Options->State is Required For** and add United Kingdom by cmd/ctrl + clicking (mac/windows). Save the configuration.
3. Remove `var/cache/*` `var/view_preprocessed/*` `pub/static/frontend/*`.
4. Go to frontend add a product to your cart, proceed to checkout.
5. Fill out the entire form, making sure to select **United Kingdom** for the country. Do not fill out the **State/Province** field.
6. Press **Next**
--**Expected/Actual Result SA1**
### Billing Address
7. Un-check **[√] My billing and shipping address are the same**.
8. Fill out the entire form, making sure to select **United Kingdom** for the country. Do not fill out the **State/Province** field.
9. Press the **Update** button to save your new billing address.
--**Expected/Actual Result BA1**
10. Press the **Place Order** button.
--**Expected/Actual Result BA2**

## Expected result

- **SA1**. The form validation should indicate that the **State/Province** field is required, that I haven't filled it in, and not let me proceed to the next checkout step.
- **BA1**. The form validation should indicate that the **State/Province** field is required, that I haven't filled it in, and not let me proceed with updating the billing address.
- **BA2**. The back end should validate my address as well, and notice that I am placing an order without all the required fields, sending an error back to the user indicating that they did not provide a **State/Province** for the shipping address and the billing address.

## Actual result

- **SA1**. The form validation succeeds and I proceed to **Checkout->Payment**. My shipping address in the **Billing Address** form does not contain a **State/Province**.
- **BA1**. The form validation succeeds and my billing address is updated.
- **BA2**. The order is placed and there are no errors.

![stores- configuration- general- state options- state is required for](https://user-images.githubusercontent.com/30085002/29464742-0adf087a-83f4-11e7-8f23-ca6d3968636a.png)
![checkout- shipping](https://user-images.githubusercontent.com/30085002/29464140-2db159f4-83f2-11e7-92db-df8f512c2e0a.png)
![checkout- payment](https://user-images.githubusercontent.com/30085002/29464752-1376c054-83f4-11e7-862d-1c635ed13713.png)
![checkout- payment- billing address](https://user-images.githubusercontent.com/30085002/29464765-214973d4-83f4-11e7-9ffe-e0fb91048c3a.png)
![checkout- payment- billing address2](https://user-images.githubusercontent.com/30085002/29464768-26c46fee-83f4-11e7-93da-3508d858c4aa.png)
![checkout- success](https://user-images.githubusercontent.com/30085002/29465491-c30620f8-83f6-11e7-9da9-5e4d51747539.png)

**Comment by VasylShvorak** [comment] 2017-08-25 10:44
@id-graziano Thanks for reporting this issue.This issue is already addressed in internal ticket MAGETWO-64159.

**Comment by id-graziano** [comment] 2017-08-25 15:51
@VasylShvorak Is there a place I can view that ticket? I have fixed this bug and wouldn't mind submitting a PR for the fix.

**Comment by magento-engcom-team** [comment] 2017-09-27 22:00
@id-graziano, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:00 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
