### ISSUE TITLE
Searching via product repository excludes out of stock products

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#28207] opened 2020-05-13 09:15 UTC
### Preconditions (*)
1. Magento 2.3.4
2. One out of stock product

### Steps to reproduce (*)
Try to search for an out of stock product using the following code 

```php
 /**
         * @var $qb SearchCriteriaBuilder
         */
        $qb = $this->searchCriteriaBuilderFactory->create();
        $criteria = $qb->addFilter($attributeCode, $value, 'eq')
            ->create()
        ;
        $productList = $this->productRepository->getList($criteria);

```

You will notice that out of stock products are excluded

I checked the process and it seems at around 
vendor/magento/module-catalog/Model/ProductRepository.php:632

Where the collection is loaded the filter for out of stock products is magically added. So adding        `die($collection->getSelectSql(true));`

Before the `$collection->load()` yields this sql for my example

```
SELECT `e`.*,
       IF(at_status.value_id > 0, at_status.value, at_status_default.value)             AS `status`,
       IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS `visibility`,
       `at_io_softone_id`.`value`                                                       AS `io_softone_id`
FROM `catalog_product_entity` AS `e`
         INNER JOIN `catalog_product_entity_int` AS `at_status_default`
                    ON (`at_status_default`.`entity_id` = `e`.`entity_id`)
                        AND (`at_status_default`.`attribute_id` = '97') AND `at_status_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND
                                                                  (`at_status`.`attribute_id` = '97') AND
                                                                  (`at_status`.`store_id` = 1)
         INNER JOIN `catalog_product_entity_int` AS `at_visibility_default` ON (`at_visibility_default`.`entity_id` =
                                                                                `e`.`entity_id`) AND
                                                                               (`at_visibility_default`.`attribute_id` = '99') AND
                                                                               `at_visibility_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_int` AS `at_visibility`
                   ON (`at_visibility`.`entity_id` = `e`.`entity_id`) AND
                      (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 1)
         LEFT JOIN `catalog_product_entity_text` AS `at_io_softone_id`
                   ON (`at_io_softone_id`.`entity_id` = `e`.`entity_id`) AND
                      (`at_io_softone_id`.`attribute_id` = '167') AND (`at_io_softone_id`.`store_id` = 0)
WHERE ((at_io_softone_id.value =
        '631'));
```

and after the load yields this sql

```
SELECT `e`.*,
       IF(at_status.value_id > 0, at_status.value, at_status_default.value)             AS `status`,
       IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS `visibility`,
       `at_io_softone_id`.`value`                                                       AS `io_softone_id`,
       `stock_status_index`.`stock_status`                                              AS `is_salable`
FROM `catalog_product_entity` AS `e`
         INNER JOIN `catalog_product_entity_int` AS `at_status_default`
                    ON (`at_status_default`.`entity_id` = `e`.`entity_id`)
                        AND (`at_status_default`.`attribute_id` = '97') AND `at_status_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND
                                                                  (`at_status`.`attribute_id` = '97') AND
                                                                  (`at_status`.`store_id` = 1)
         INNER JOIN `catalog_product_entity_int` AS `at_visibility_default` ON (`at_visibility_default`.`entity_id` =
                                                                                `e`.`entity_id`) AND
                                                                               (`at_visibility_default`.`attribute_id` = '99') AND
                                                                               `at_visibility_default`.`store_id` = 0
         LEFT JOIN `catalog_product_entity_int` AS `at_visibility`
                   ON (`at_visibility`.`entity_id` = `e`.`entity_id`) AND
                      (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 1)
         LEFT JOIN `catalog_product_entity_text` AS `at_io_softone_id`
                   ON (`at_io_softone_id`.`entity_id` = `e`.`entity_id`) AND
                      (`at_io_softone_id`.`attribute_id` = '167') AND (`at_io_softone_id`.`store_id` = 0)
         INNER JOIN `cataloginventory_stock_status` AS `stock_status_index`
                    ON e.entity_id = stock_status_index.product_id
WHERE ((at_io_softone_id.value = '631'))
  AND (stock_status_index.stock_status = 1)
```

As you can see the stock status filter is added automatically even though I didn't add it. 

### Expected result (*)
1. The product is returned 

### Actual result (*)
1. The product is not returned

**Comment by ioweb-gr** [comment] 2020-05-13 09:18
I'm unable to test on the demo instance because it needs coding so someone else will have to try and reproduce it on the demo instance.

**Comment by DavidEu000** [comment] 2020-08-19 06:49
There is a setting in backend: System - Configuration - Catalog - Inventory - Stock Option - Display Products Availability in Stock on Storefront. The default value is No and it will exclude out of stock products via product repository.

For using API, it is better to create a plugin to remove this limitation instead of changing the above setting!

**Comment by ioweb-gr** [comment] 2020-09-01 18:27
The problem is that creating a Plugin for frontend, it will remove the limitation for every other call as well. 

I just don't see why this should be enforced everywhere in the frontend on the collection level without a way to disable it for a specific query. I mean I'm selecting products via the repository based on custom search criteria for a reason, but extra search criteria is automatically injected in my selection without a way to turn it off for a specific query and I think it's counter-intuitive.

**Comment by ioweb-gr** [comment] 2021-01-29 07:23
This is seriously affecting dev experience. We don't want to show out of stock products in lists, but we may want to use those in certain situations. Programmatically altering a query the developer is writing just because the area is frontend automatically is not expected or documented behaviour

**Comment by ioweb-gr** [comment] 2021-04-15 14:13
Not stale

**Comment by engcom-Lima** [comment] 2021-06-08 10:19
Hi @ioweb-gr 

Unfortunately can't reproduce the issue.

Can you please provide me the reproducible steps and details with screenshots.?

It would be very helpful in this.

**Comment by engcom-Lima** [comment] 2021-06-17 09:19
Hi @ioweb-gr 

Hoping this issue will not be there. Hence closing this ticket.

Please feel free to raise the new ticket if you have any other issue.

**Closed as completed by engcom-Lima** 2021-06-17 09:19 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update, Reported on 2.3.4

**Comment by DenisMir** [comment] 2024-01-27 09:53
Why is this issue closed. It is still not possible to query for products including out of stock ones with the normal product repository. That doesn't make any sense.
