### ISSUE TITLE
Customer group is NULL in guest orders

### ISSUE THREAD

**Issue by mad-develop** [magento/magento2#35440] opened 2022-05-06 12:11 UTC
### Additional Information
Paypal Express doesn't seems to be affected. I don't know why. 

### Preconditions (*)
1. Magento 2.4.4
2. Payment Method: Checkmo

### Steps to reproduce (*)
1. Order as Guest

### Expected result (*)
1. Order should have "NOT LOGGED IN" as customer group (DB: sales_order.customer_group_id = 0)

### Actual result (*)
1. Customer group is empty (DB: sales_order.customer_group_id = NULL)

### Screenshot
![grafik](https://user-images.githubusercontent.com/40065929/167128653-740ee565-61e8-4bfa-9f48-6d3ede708651.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mad-develop** [comment] 2022-05-06 12:14
@magento give me 2.4-develop instance

**Comment by mad-develop** [comment] 2022-05-06 12:30
Confirmed on 2.4-develop
![grafik](https://user-images.githubusercontent.com/40065929/167131602-ed7ef7f0-9b33-4385-ad80-cbd26b88903d.png)

**Comment by Manju-crz** [comment] 2022-05-07 15:04
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-09 10:46
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-09 11:37
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Hence confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/167402069-3c046289-2ac4-45ee-b411-70ef1fffb778.png)

**Comment by nazarklovanych** [comment] 2022-05-13 08:18
@magento I am working on this

**Comment by nisha-vaghela** [comment] 2022-05-20 05:21
@magento i am working on this

**Comment by nazarklovanych** [comment] 2022-05-20 06:32
@nisha-vaghela as you can there is already PR created, so on what you are working on ?

**Comment by hubertus2017** [comment] 2022-05-27 11:50
Just upgraded to M2.4.4 . The same issue with empty customer group. 

The missing customer groups is critical because it leads to incomplete confirmation emails ({{depend order.getIsNotVirtual()}} in emails ) and to order export issues..... A quick fix is needed!

**Comment by engcom-Hotel** [comment] 2022-09-07 10:54
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-3031 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-3031&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-09-07 10:54 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Component: Order grid, Area: Order, Reported on 2.4.4

**Comment by mobweb** [comment] 2023-01-10 10:41
This is a critical issue for us, as it totally messes up our whole workflow for guest orders. Is there no fix/patch available to fix this immediately?

**Comment by TomMeijnaerts** [comment] 2023-02-24 15:06
[magento-module-quote-model-quotemanagement-php.patch](https://github.com/magento/magento2/files/10825539/magento-module-quote-model-quotemanagement-php.patch)

for anyone searching for a patch
