### ISSUE TITLE
Admin Grid Mass action Select / Unselect All issue

### ISSUE THREAD

**Issue by minesh0111** [magento/magento2#9610] opened 2017-05-12 07:09 UTC
Admin Grid Mass Action `Select All ` and `Unselect All` work only on `primary_key` of collection object no matter if we set other field as mass action filed using grid method `setMassactionIdField` other than `primar_key`

### Preconditions
1. Magento version 2.1.3

### Steps to reproduce

1. Found this issue while creating custom module where i need mass action id filed other than `primary_key` of collection. 

### Expected result

1. It should `Select All` and `Unselect All`  on click of option
2. It should post `MassactionIdField`  on submit

### Actual result

1. Checkbox `checked` and `unchecked` not working on click of option
2. Always post  `primary_key` value of collection on submit

**Comment by magento-engcom-team** [comment] 2017-09-20 22:08
@minesh0111, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed** 2017-09-20 22:08 UTC
Labels: Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
