### ISSUE TITLE
Magento_InventoryInStorePickup acl.xml invalid schema - missing title attribute

### ISSUE THREAD

**Issue by alex-james** [magento/magento2#32697] opened 2021-04-09 09:47 UTC
### Preconditions (*)

1. PHP 7.4.9
2. Magento 2.4.2

### Steps to reproduce (*)

1. With the Magento_InventoryApi module enabled and cache cleared, attempt a backend login

### Expected result (*)

1. Login to dashboard

### Actual result (*)

1. Logic exception thrown in Magento\Framework\Config\Reader\Filesystem::_readFiles()

Exception #0 (LogicException): Could not create an acl object: Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 13

The issue is because the acl.xml file for this module (vendor/magento/module-inventory-in-store-pickup-sales-api/etc/acl.xml) contains resource nodes with no "title" attribute, this fails the schema validation defined in: vendor/magento/framework/Acl/etc/acl_merged.xsd

 <xs:attribute name="title" type="typeTitle" use="required" />

To workaround this issue either:
1. Disable the Magento_InventoryInStorePickup module or
2. Add title="" to the vendor/magento/module-inventory-in-store-pickup-sales-api/etc/acl.xml file or
3. Update the vendor/magento/framework/Acl/etc/acl_merged.xsd to set the title attribute as optional

**Comment by mrtuvn** [comment] 2021-04-10 09:38
attribute title already set to optional in codebase !? Are you sure update magento version to more recently stable version ?
Refer this code below
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Acl/etc/acl.xsd#L51

**Comment by mrtuvn** [comment] 2021-04-10 09:39
attribute title already set to optional in codebase !? Are you sure update magento version to more recently stable version ?
Refer this code below

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Acl/etc/acl.xsd#L51

**Comment by alex-james** [comment] 2021-04-12 07:59
Not acl.xsd, acl_merged.xsd - see: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Acl/etc/acl_merged.xsd

**Comment by engcom-Oscar** [comment] 2021-04-13 09:25
Hi @alex-james ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket. May you share more details in description, please. Do you use composer  version of Magento, or from git?

**Comment by alex-james** [comment] 2021-04-13 09:35
The project was composer installed, the fundamental issue here is that this file in the repo specifies title as required:
https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Acl/etc/acl_merged.xsd

Yet a composer install of magento/module-inventory-in-store-pickup (v1.1.0) includes an /etc/acl.xml that does not contain title attributes.

**Comment by alex-james** [comment] 2021-04-15 13:57
@engcom-Oscar According to the XSD title needs to be present in ALL the <resource> nodes, your screenshot shows it only present in the final one.

**Comment by alex-james** [comment] 2021-04-15 14:08
@mrtuvn Agreed but the penultimate one <resource id="Magento_InventoryInStorePickupApi::inStorePickup> is surely unique to the Magento_InventoryInStorePickupApi module and this does not have a title

**Comment by mrtuvn** [comment] 2021-04-15 22:03
https://github.com/magento/inventory/blob/1.2-develop/InventoryInStorePickupApi/etc/acl.xml#L14
From codebase i see attribute title already here. Can you verify with your version

**Comment by alex-james** [comment] 2021-04-16 07:45
Sorry @mrtuvn this is the line I am referring to that does not contain a title attribute:
<img width="389" alt="Screenshot 2021-04-16 at 08 44 07" src="https://user-images.githubusercontent.com/17109175/114990121-1b928b00-9e90-11eb-84b3-af4da7937b6c.png">
and yes, we are using version 2.4.2

**Comment by mrtuvn** [comment] 2021-09-15 08:33
Can you recheck with latest code ? 2.4.3 if you have
Feel free create pull request for missing parts at 
https://github.com/magento/inventory

**Comment by engcom-November** [comment] 2021-09-30 11:02
Hi @alex-james ,
We are not able to reproduce this issue on Magento latest versions and 2.4-develop having Magento_InventoryApi module enabled. We are closing this issue as there has been no latest update on the same. Kindly reopen/create new ticket if you are still facing this issue and provide missing steps if any.
Thank you.

**Closed as completed by engcom-November** 2021-09-30 11:02 UTC
Labels: Issue: needs update
