### ISSUE TITLE
Simple Product video does not play when in Configurable Product on frontend. 

### ISSUE THREAD

**Issue by btwq** [magento/magento2#8744] opened 2017-03-02 00:58 UTC
### Preconditions

1. Magento 2.1.5
2. PHP 7.0
3. MySQL Percona 5.6

### Steps to reproduce

1. Add vimeo video link to a simple product A. 
2. Setup Configurable product B which contains product A as a variant. 
2. When viewing product A on frontend, video icon displayed on thumbnail and when clicking on preview, video plays correctly 
3. When viewing product B on frontend, thumbnail does not indicate video. Cannot play video when clicking on preview. 

### Expected result

1. We should be able to play videos whether viewing product as simple or as configurable on frontend. 

### Actual result

1. Configurable product thumbnail does not indicate video. Cannot play video 

See CONFIGURABLE product example ![screen shot 2017-03-02 at 10 38 01 am](https://cloud.githubusercontent.com/assets/14045909/23488215/4cd355b8-ff3f-11e6-8f66-6075abd8039b.png)
See SIMPLE product example ![screen shot 2017-03-02 at 10 37 53 am](https://cloud.githubusercontent.com/assets/14045909/23488214/4cd1c36a-ff3f-11e6-9156-9e634c8b3570.png)

**Comment by eduard-kistner** [comment] 2017-07-03 10:30
Hi @btwq ,
just cause i found your Issue before the acknowledged one, maybe its a possible duplicate of #6360 ?!

**Comment by magento-engcom-team** [comment] 2017-09-29 14:30
@btwq, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-29 14:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by nmallepally** [comment] 2018-01-15 12:38
Hi @magento-engcom-team 

I still have this error in Magento 2.1.8.
embedded youtube video displays as a static image on the configurable product.

Any workaround on 2.1.8 to fix this issue?.

Thanks
