### ISSUE TITLE
Voiding a payment moves the order into processing status

### ISSUE THREAD

**Issue by asim-blueprintprep** [magento/magento2#36565] opened 2022-12-05 16:26 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.4-p2
PHP 8.1

If an order in pending is voided, it forces a status move to processing - voiding should leave the order in it's current state. For stripe, processing is after payment is taken, which means some customers are gaining access to things that they haven't paid for.

### Steps to reproduce

1. Place an order that hasn't taken payment yet(stripe declined card )
2. in admin open the order
3. the order is in pending
4. void the order
5. the order is now in processing

### Expected result

The order is left in it's state/status

### Actual result

The order is moved to processing

### Additional information

![Screenshot 2022-12-05 at 16 25 20](https://user-images.githubusercontent.com/85678471/205688963-8820ef3a-db5b-41f1-a7c7-25bd5a6f5c9e.png)
![Screenshot 2022-12-05 at 16 25 47](https://user-images.githubusercontent.com/85678471/205689065-d2e19c4d-afe8-490a-9cf4-f0ef225cd02e.png)

The hard coded move to processing comes from:

vendor/magento/module-sales/Model/Order/Payment.php

`protected function _void($isOnline, $amount = null, $gatewayCallback = 'void')
`

`$this->setOrderStateProcessing($message);
`

```
/**
     * Sets order state to 'processing' with appropriate message
     *
     * @param \Magento\Framework\Phrase|string $message
     */
    protected function setOrderStateProcessing($message)
    {
        $this->getOrder()->setState(Order::STATE_PROCESSING)
            ->setStatus($this->getOrder()->getConfig()->getStateDefaultStatus(Order::STATE_PROCESSING))
            ->addStatusHistoryComment($message);
    }
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by asim-blueprintprep** [comment] 2022-12-05 16:53
https://github.com/magento give me 2.4-develop instance

**Comment by asim-blueprintprep** [comment] 2022-12-05 16:55
@magento give me 2.4-develop instance

**Comment by asim-blueprintprep** [comment] 2022-12-06 09:39
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-12-06 13:01
Hi @asim-blueprintprep ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but cannot able to reproduce the issue with provided steps.
We do not have "Void" option for payments made using check / money order. Hence cancelled the order from magento admin for a Pending Order and the status is updated as "Cancelled". Please refer the screenshot below.
![image](https://user-images.githubusercontent.com/60198231/205918972-190fb187-a683-4878-a3d3-815d71371ec3.png)
![image](https://user-images.githubusercontent.com/60198231/205919021-b70749e3-fe80-4de8-a847-bfc795400a6e.png)
Kindly recheck the issue on Magento 2.4-develop instance and elaborate steps to reproduce if you are still facing any issues.
Thank you.

**Comment by asim-blueprintprep** [comment] 2022-12-06 13:26
Hi,
The issue is NOT with cancelling. The issue is with voiding. I am aware cancelling changes the state correctly. Please remove the screenshots from an unrelated test.

**Comment by asim-blueprintprep** [comment] 2022-12-06 13:26
@magento give me 2.4-develop instance

**Comment by asim-blueprintprep** [comment] 2022-12-06 13:29
How can I test if this won't create one?

**Comment by asim-blueprintprep** [comment] 2022-12-06 14:30
@engcom-November A work around for a local environment, so you can see the core magento bug:
edit:
`vendor/magento/module-payment/Model/Method/AbstractMethod.php`
and comment out:

```
/*if (!$this->canVoid()) {
            throw new \Magento\Framework\Exception\LocalizedException(__('The void action is not available.'));
        }*/
```

and

`vendor/magento/module-sales/Block/Adminhtml/Order/View.php`
and comment out:
```
//if ($this->_isAllowedAction('Magento_Sales::invoice') && $order->canVoidPayment()) {
            $message = __('Are you sure you want to void the payment?');
            $this->addButton(
                'void_payment',
                [
                    'label' => __('Void'),
                    'onclick' => "confirmSetLocation('{$message}', '{$this->getVoidPaymentUrl()}')"
                ]
            );
        //}
```

This will allow you to simulate online payment - and the void button will appear. 

I have done this with bank transfer and money order:

![Screenshot 2022-12-06 at 14 28 19](https://user-images.githubusercontent.com/85678471/205939015-995834e4-ab24-4002-b30e-66b2d618fa9f.png)
![Screenshot 2022-12-06 at 14 28 23](https://user-images.githubusercontent.com/85678471/205939050-c3309ad9-2c57-4df1-8e38-2374632dd02d.png)

As noted previously, there is a function which hard codes it to move the order to processing

```
/**
     * Sets order state to 'processing' with appropriate message
     *
     * @param \Magento\Framework\Phrase|string $message
     */
    protected function setOrderStateProcessing($message)
    {
        $this->getOrder()->setState(Order::STATE_PROCESSING)
            ->setStatus($this->getOrder()->getConfig()->getStateDefaultStatus(Order::STATE_PROCESSING))
            ->addStatusHistoryComment($message);
    }
```

**Comment by engcom-November** [comment] 2022-12-07 10:43
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-12-08 11:00
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-12-08 11:52
Hi @asim-blueprintprep ,
Verified the issue again on Magento 2.4-develop instance and is working fine if a **processing** order is voided. 
As per Magento officials [docs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/point-of-purchase/assist/order-update.html?lang=en#void-a-processing-order) , we can VOID an order only if the order status is "Processing" and not captured.
As per Magento [docs](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/order-management/orders/order-processing.html), Only sales orders that are not invoiced, have a status of Processing, and a payment setting of authorize, can be voided.
**Scenarios tested:**
**Scenario 1:** Made payment using Payflow PRO. Order status is Processing. Void button displayed - Voided the payment - Order status is Processing.
**Scenario 2:** Created invoice for a Processing Order with "not capture option" - VOID button is displayed. Voided the payment. Order status is processing. 
![image](https://user-images.githubusercontent.com/60198231/206439553-1fd3849b-2e61-4d56-a424-b1b117a85905.png)

![image](https://user-images.githubusercontent.com/60198231/206439480-4e5f3061-43ce-46eb-8477-c765b0ba18d7.png)
Can you please provide supporting documents / proofs showing Pending orders can be voided. Kindly recheck the behavior on Magento 2.4-develop instance and provide steps for valid use case scenario.
Thank you.

**Comment by asim-blueprintprep** [comment] 2022-12-08 13:06
@engcom-November

Yes, stripe creates orders in pending regardless if if theyve been paid or not. As per a copy of my email chain with stripe:

> Hi Alex,
> 
> We have received feedback from customers who prefer the old checkout flow from versions 2.x of the module. In versions 2.x, orders were not placed in Pending status when a payment failed. In versions 3.x we made this change due to limitations we had at the time with the new PaymentElement

See below screenshots:
![Screenshot 2022-12-08 at 13 04 14](https://user-images.githubusercontent.com/85678471/206453853-bb9e8243-a76b-454b-a2d0-fac294d04a92.png)
![Screenshot 2022-12-08 at 13 04 18](https://user-images.githubusercontent.com/85678471/206453855-8f2fc4d6-0915-435b-875a-ba1d2a20250b.png)
![Screenshot 2022-12-08 at 13 04 21](https://user-images.githubusercontent.com/85678471/206453857-74f888af-0e5f-481d-9664-37494b57e90f.png)

As you can clearly see in the above, an order is created in pending, and void button is visible. I believe it is not an admin clicking it, but a webhook that comes back to void it.

This then moves the order into processing.

This is an issue either with the logic of if voiding is allowed, or with voiding moving it into processing.

Thanks,

**Comment by asim-blueprintprep** [comment] 2022-12-08 13:10
As a follow up, here is official stripe documentation:
https://stripe.com/docs/plugins/adobe-commerce/troubleshooting?locale=en-GB#order-stuck-in-pending-status

> Order stuck in pending status
> When creating an order, the initial status is Pending, which indicates that the authorization of the payment by the customer’s bank is still pending.

Again, I CANNOT show you on a develop-instance as I cannot give you our stripe credentials.

The screenshots and documentation clearly demonstrate an ability to void a pending order.

**Comment by asim-blueprintprep** [comment] 2022-12-08 13:15
Extra follow up screenshots:
![Screenshot 2022-12-08 at 13 14 31](https://user-images.githubusercontent.com/85678471/206455723-0c6cd02b-7c4f-4d01-8c16-5c07c519f330.png)
![Screenshot 2022-12-08 at 13 14 36](https://user-images.githubusercontent.com/85678471/206455724-67d76583-26b2-477a-b82e-7c4abe0b6cc3.png)

**Comment by engcom-November** [comment] 2022-12-09 15:45
Hi @asim-blueprintprep ,
Thank you for the response. Stripe payment is a 3rd party package / extension and code of this extension is not part of https://github.com/magento/magento2 git repository. This issue is not reproducible with Magento built in default payment methods. Void button will not be displayed for Pending Orders. Community cannot able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Comment by engcom-November** [comment] 2022-12-26 11:21
Hi @asim-blueprintprep ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-26 11:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
