### ISSUE TITLE
Propose not to show the «Please re-run Magento compile command» message in the developer mode as a response on the «bin/magento setup:upgrade» command because the compilation is done automatically on demand in the developr mode

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#3011] opened 2016-01-16 13:43 UTC

**Comment by ktomk** [comment] 2016-01-21 22:04
instead perhaps suggest `generation:flush`. same perhaps true for the default mode. but I wonder if it's really necessary, the developer should foster the understanding, then the message is clear to understand. it's perhaps good to run once over it and question it. would not be possible if the message is being removed.

**Comment by okorshenko** [comment] 2016-03-08 17:37
@dfediuk could you please update issue description using the following format: 

## Steps to reproduce
1. Install Magento from `develop` branch.
2. [Example] Add Configurable Product to the cart.
3. ...

## Expected result
1. [Example] Configurable product added to the shopping cart.
2. ...

## Actual result
1. [Example] Error message appears: "Cannot save quote".
2. [Screenshot, logs]
3. ...

**Comment by mazhalai** [comment] 2016-05-09 19:06
@mage2pro closing due to non-responsiveness

**Closed as completed by mazhalai** 2016-05-09 19:06 UTC
Labels: Progress: needs update
