### ISSUE TITLE
Configurable option swatch image cache not updated when changing image for simple product

### ISSUE THREAD

**Issue by yuriichayka** [magento/magento2#35270] opened 2022-04-06 07:47 UTC
Configurable swatch option images aren't updated in the cache if you change them for simple products only. Looks like there is simply no logic for this in Magento - by immediate cache invalidation by tag, or by some indexer.
So, image uploading for child products invalidates cache only for such particular products, without checking parent configurables.

### Preconditions (*)

1. Magento 2.4.3 CE/EE
2. PHP 7.4.27
3. Ealsticsearch
4. Redis used for caching block html

### Steps to reproduce (*)

1. Have a Configurable product with some swatch options configured(size/color);
2. Open such Configurable PDP for caching its elements;
3. Change an image for some configurable child product to a new one in Magento Admin.
4. DO NOT flush Magento cache;
5. Refresh Configurable PDP again and select changed  swatch option.

### Expected result (*)

1. New image is shown for the swatch option on configurable PDP after updating an image for related child product.

### Actual result (*)

1. Configurable swatch option still has old child image, unless you flush configurable cache/or block_html cache.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [+ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-08 12:35
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-11 07:52
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-11 09:44
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Created Configurable Product with Swatch option "Color"  (Initial value - Black) and save
Front end - Product Details page - Option displayed as expected.
![image](https://user-images.githubusercontent.com/60198231/162711449-0db5dd17-1682-4eb6-a28d-081b0ef2d5cc.png)
 From admin - Product edit page - Edit configurations - Changed the swatch color option to Red and save
Refresh Product details page without cache flush
Select option
No issue: Swatch option is updated as expected in both admin and front-end
![image](https://user-images.githubusercontent.com/60198231/162711905-6e96e369-f1f6-422b-b93c-81355e3c9cd4.png)
![image](https://user-images.githubusercontent.com/60198231/162711957-fe3cff15-03f2-42fa-8b36-7eb8338f1928.png)
@yuriichayka kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by yuriichayka** [comment] 2022-04-11 11:07
Hello @engcom-November 
The problem is related not to the color swatch image, but to the image of the option product itself. 
I mean when you select all swatch options, the main image of the product is updated. 
I didn't describe it properly I guess

NEW STR:

1. Have a Configurable product with some swatch options configured(size/color);
2. **Configure for some child products different product images, so when you select such an option - the main image changes.**
3. Open such Configurable PDP for caching its elements;
4. Change **the product image** for some configurable child products to a new one in Magento Admin.
5. DO NOT flush Magento cache;
6. Refresh Configurable PDP again and select changed swatch option.



Can you please reproduce it with new steps?

**Comment by engcom-November** [comment] 2022-04-12 06:39
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-12 10:48
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-12 11:55
Verified the issue again on Magento 2.4-develop branch using above mentioned steps but still we are not able to reproduce the issue. Please find the attached video of steps performed and child product main image is getting changed as expected when swatch option is selected in PDP without cache flush
https://user-images.githubusercontent.com/60198231/162954964-e9a47f88-7740-455a-a13b-e4efac96d472.mp4

**Comment by engcom-November** [comment] 2022-04-26 06:01
Hi @yuriichayka ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-26 06:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
