### ISSUE TITLE
GraphQL: Configurable product returns disabled products as variants

### ISSUE THREAD

**Issue by lilbumblebear** [magento/magento2#34053] opened 2021-09-10 14:24 UTC
### Preconditions (*)
1. Magento 2.4.3

### Steps to reproduce (*)
1.  Create a configurable product
2. Create variants
3. Make one variant disabled
4. Configurable product returns the disabled variant in graphql response

### Expected result (*)

I expect to only get variants that are enabled and available in the given website 

### Actual result (*)

1. disabled product was included in the variants

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

*The workaround is to mark the disabled product as out of stock*  I do feel like this is critical data for developers/users using PWA or other frontend systems.

**Comment by shikhamis11** [comment] 2021-09-11 14:09
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2021-09-11 14:44
@lilbumblebear thank you for opening this issue. I am able to reproduce this issue on Magento 2.4.3 but not able to reproduce it on the 2.4-develop instance. seems it is already fixed by the internal team. 
Please check commits 
[f3f73ab6b8caf1796dc5b5dcf40bf076b1c2ecd1](https://github.com/magento/magento2/commit/f3f73ab6b8caf1796dc5b5dcf40bf076b1c2ecd1
)
[d81e4852c1d201a1ef355af68eca8947e8260895](https://github.com/magento/magento2/commit/d81e4852c1d201a1ef355af68eca8947e8260895)

**Closed as completed by shikhamis11** 2021-09-11 14:44 UTC
Labels: Issue: ready for confirmation
