### ISSUE TITLE
Unable to select products to associate with a configurable product

### ISSUE THREAD

**Issue by alryalls** [magento/magento2#36014] opened 2022-08-24 17:24 UTC
### Preconditions and environment

- Magento version is 2.4.2

### Steps to reproduce

1. Add a new configurable product.
2. Select Attribute Set, Product Name, SKU, Price, leave product disabled. 
3. Save.
4. Select all other required values, i.e. categories, country of manufacture, etc.
5. Select Create Configurations to create the dummy product/s (required to enable the 'Add Products Manually' link).
6. Choose your attribute.
7. Skip SKU, image, price at this time.
8. Click Next to create the dummy products.
9. Done.
10. Save.
11. Scroll down to the dummy products you just created and either select Add Products Manually (some are not selectable, their checkboxes greyed out). Or select 'Choose a different product'. Complete these steps.
12. In both cases, after saving the configurable product, they are no longer in the associated products list.

### Expected result

The associated products to appear in the configurable product's list

### Actual result

The associated products are missing from the list after saving the configurable product.

### Additional information

Configurable products logic seems very strange. There is a known issue when adding a configurable product's associated products (variations), in that you have to create a dummy configuration (product), and Save, to make the 'Add Products Manually' link appear, thus allowing you to (supposedly) add your product variations.

There are two extra issues though. When you 'Add Products Manually' **some** checkboxes are disabled so you cannot proceed.

The other method (problem) is to click the Select link next to a dummy product you created earlier and select 'Choose a Different Product'. This lets you proceed and you can see it in the configurable product's admin page - until you Save, at which point it disappears.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alryalls** [comment] 2022-08-24 17:25
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-25 07:42
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-26 07:30
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-26 11:44
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-26 12:27
Hi @alryalls ,

We are able to reproduce the issue in 2.4-develop instance.

Magento Version: 2.4-develop
PHP                    : 8.1
Preconditions      : Magento version is 2.4.2
Here i attached the screenshots for your reference:
![Screenshot from 2022-08-26 17-46-44](https://user-images.githubusercontent.com/60198592/186902032-05706ed4-7a44-4205-81ea-06d94d60deef.png)
![Screenshot from 2022-08-26 17-46-41](https://user-images.githubusercontent.com/60198592/186902055-20b79bbe-799a-41ea-9fb7-99cab93e3155.png)

Steps to reproduce : 
1. Install Magento instance
2. Create configurable Product with Disable Mode and Select SKU,Country of Manufacture,Price,Name.
3. Create Configuration with Products
4. Add products Manually
5. Skip SKU, image, price at this time.
6. Save the Product
7. Select the some Dummy Products using Add products Manually Option
8. The added products should display in product list
9. But the associated products is not displaying in product list

Expected Result:

The associated products to appear in the configurable product's list

Actual Result:

The associated products are missing from the list after saving the configurable product.

We are getting actual results after saving the configurable product.

Let us know if we missing anything...

Thanks!!!

**Comment by alryalls** [comment] 2022-09-29 10:54
so is it being worked on, or....?

**Comment by Bashev** [comment] 2022-12-29 20:07
@alryalls why you are looking for "config" in Product Grid, when products which are associated with configurable product (variants) had own names. 

I'm trying to reproduce it on 2.4.5-p1, but looks like works as expected.

**Comment by engcom-Dash** [comment] 2023-02-24 09:07
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-03-13 11:35
Hi @alryalls ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-03-13 11:35 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: needs update, Reported on 2.4.2, Area: Admin UI
