### ISSUE TITLE
Customer table "lock wait timeout exceeded" error when saving customer with many addresses

### ISSUE THREAD

**Issue by david-kominek** [magento/magento2#10783] opened 2017-09-05 20:52 UTC
### Preconditions

1. RHEL6
2. Magento CE 2.1.7
3. PHP 7.0.17 (cli) (built: Mar 16 2017 08:18:11) ( NTS )
4. mysql  Ver 14.14 Distrib 5.6.35, for Linux (x86_64)

### Steps to reproduce

1. Create a customer with over 400 addresses
2. Attempt to place an order with that customer
3. API request takes forever and eventually fails

### Expected result

1. Order should be placed successfully

### Actual result

1. See error below:
`
Zend_Db_Statement_Exception: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction, query was: UPDATE `mage_customer_entity` SET `website_id` = ?, `email` = ?, `group_id` = ?, `store_id` = ?, `created_at` = '2017-09-05 18:19:13', `updated_at` = '2017-09-05 19:15:50', `disable_auto_group_change` = ?, `created_in` = ?, `firstname` = ?, `lastname` = ?, `password_hash` = ?, `rp_token` = ?, `rp_token_created_at` = ?, `default_billing` = ?, `default_shipping` = ?, `confirmation` = ?, `failures_num` = ?, `first_failure` = ?, `lock_expires` = ? WHERE (`entity_id`=79) in /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/html/magento-2.1.7/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `mage_cu...', Array)
#5 /var/www/html/magento-2.1.7/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `mage_cu...', Array)
#6 /var/www/html/magento-2.1.7/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('UPDATE `mage_cu...', Array)
#7 /var/www/html/magento-2.1.7/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Magento\Framework\DB\Adapter\Pdo\Mysql->query('UPDATE `mage_cu...', Array)
#8 /var/www/html/magento-2.1.7/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1423): Zend_Db_Adapter_Abstract->update('mage_customer_e...', Array, '(`entity_id`=79...')
#9 /var/www/html/magento-2.1.7/vendor/magento/module-eav/Model/Entity/VersionControl/AbstractEntity.php(91): Magento\Eav\Model\Entity\AbstractEntity->_processSaveData(Array)
#10 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Eav\Model\Entity\VersionControl\AbstractEntity->save(Object(Magento\Customer\Model\Customer\Interceptor))
#11 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callParent('save', Array)
#12 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'save', Object(Magento\Customer\Model\ResourceModel\Customer\Interceptor), Array, 'clean_cache')
#13 /var/www/html/magento-2.1.7/vendor/magento/framework/App/Cache/FlushCacheByTags.php(71): Magento\Customer\Model\ResourceModel\Customer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Customer\Model\Customer\Interceptor))
#14 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Customer\Model\ResourceModel\Customer\Interceptor), Object(Closure), Object(Magento\Customer\Model\Customer\Interceptor))
#15 /var/www/html/magento-2.1.7/var/generation/Magento/Customer/Model/ResourceModel/Customer/Interceptor.php(26): Magento\Customer\Model\ResourceModel\Customer\Interceptor->___callPlugins('save', Array, Array)
#16 /var/www/html/magento-2.1.7/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Customer\Model\ResourceModel\Customer\Interceptor->save(Object(Magento\Customer\Model\Customer\Interceptor))
#17 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->save()
#18 /var/www/html/magento-2.1.7/var/generation/Magento/Customer/Model/Customer/Interceptor.php(26): Magento\Customer\Model\Customer\Interceptor->___callPlugins('save', Array, Array)
#19 /var/www/html/magento-2.1.7/vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php(193): Magento\Customer\Model\Customer\Interceptor->save()
#20 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Customer\Model\ResourceModel\CustomerRepository->save(Object(EntrustDatacard\Customer\Model\Data\Customer), NULL)
#21 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callParent('save', Array)
#22 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'save', Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Array, 'update_newslett...')
#23 /var/www/html/magento-2.1.7/vendor/magento/module-newsletter/Model/Plugin/CustomerPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(EntrustDatacard\Customer\Model\Data\Customer), NULL)
#24 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Newsletter\Model\Plugin\CustomerPlugin->aroundSave(Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Object(Closure), Object(EntrustDatacard\Customer\Model\Data\Customer), NULL)
#25 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Custome...', 'save', Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Array, 'transactionWrap...')
#26 /var/www/html/magento-2.1.7/vendor/magento/module-customer/Model/Plugin/CustomerRepository/TransactionWrapper.php(44): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(EntrustDatacard\Customer\Model\Data\Customer), NULL)
#27 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Customer\Model\Plugin\CustomerRepository\TransactionWrapper->aroundSave(Object(Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor), Object(Closure), Object(EntrustDatacard\Customer\Model\Data\Customer))
#28 /var/www/html/magento-2.1.7/var/generation/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php(26): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->___callPlugins('save', Array, Array)
#29 /var/www/html/magento-2.1.7/vendor/magento/module-quote/Model/CustomerManagement.php(66): Magento\Customer\Model\ResourceModel\CustomerRepository\Interceptor->save(Object(EntrustDatacard\Customer\Model\Data\Customer))
#30 /var/www/html/magento-2.1.7/vendor/magento/module-quote/Model/QuoteManagement.php(432): Magento\Quote\Model\CustomerManagement->populateCustomerInfo(Object(Magento\Quote\Model\Quote))
#31 /var/www/html/magento-2.1.7/vendor/magento/module-quote/Model/QuoteManagement.php(391): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote), Array)
#32 /var/www/html/magento-2.1.7/vendor/magento/module-quote/Model/QuoteManagement.php(349): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote))
#33 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Quote\Model\QuoteManagement->placeOrder(55, NULL)
#34 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('placeOrder', Array)
#35 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Quote\\M...', 'placeOrder', Object(Magento\Quote\Model\QuoteManagement\Interceptor), Array, 'QuoteManagement...')
#36 /var/www/html/magento-2.1.7/app/code/EntrustDatacard/Quote/Model/Plugin/QuoteManagement.php(47): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(55, NULL)
#37 /var/www/html/magento-2.1.7/vendor/magento/framework/Interception/Interceptor.php(142): EntrustDatacard\Quote\Model\Plugin\QuoteManagement->aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), 55, NULL)
#38 /var/www/html/magento-2.1.7/var/generation/Magento/Quote/Model/QuoteManagement/Interceptor.php(26): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('placeOrder', Array, Array)
#39 [internal function]: Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder(55, NULL)
#40 /var/www/html/magento-2.1.7/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)
#41 /var/www/html/magento-2.1.7/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()
#42 /var/www/html/magento-2.1.7/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /var/www/html/magento-2.1.7/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /var/www/html/magento-2.1.7/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#45 /var/www/html/magento-2.1.7/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
`

**Comment by david-kominek** [comment] 2017-09-05 21:23
Additionally, the addresses section of the admin backend when editing a customer is unbearably slow. To the point that I have to wait 20 minutes or more for some customers. These customers have at times up to 800 addresses.

Updating a customer through the Customer REST API also exhibits the same issue.

**Comment by magento-engcom-team** [comment] 2017-09-11 02:13
Hi @david-kominek look like you are trying to use the system in a not designed way. Normally, one customer does not have 400+ address. We will check our performance measurements and thresholds.

**Comment by magento-engcom-team** [comment] 2017-10-23 12:40
@david-kominek, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-23 12:40 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Progress: on hold, Issue: Format is valid
