### ISSUE TITLE
JS error in the customer data

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#31920] opened 2021-02-01 12:40 UTC
Originally this issue was reported in https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d#commitcomment-44080850 by @HenKun.

The following commit https://github.com/magento/magento2/commit/5983e1733d56b1b2f15fb4f0e64094a3a4f3145d leads to similar issues described in https://github.com/magento/magento2/pull/24847.

### Preconditions (*)

1. Magento 2.4.1, or 2.4-develop

### Steps to reproduce (*)

1. Add the following code to the page on frontend:
```html
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>
```
2. Go to the frontend, see the console

### Expected result (*)

1. In the console you should see an empty array, like this: 
![image](https://user-images.githubusercontent.com/1873745/106459907-3a8d9d80-649b-11eb-97fc-9daf626f9ae6.png)

### Actual result (*)

1. in the console we see the following error:
![image](https://user-images.githubusercontent.com/1873745/106459804-16ca5780-649b-11eb-9ae9-99eadd442c41.png)

### Additional info from Engcom
Add the script to, for example, /app/code/Magento/Customer/view/frontend/templates/form/edit.phtml
![script](https://user-images.githubusercontent.com/51680745/106472483-6284fd00-64ab-11eb-9551-87abc2f4069b.png)

1. In the Storefront, Sign In as a Customer
2. Go to _My Account_
3. Click **Edit** under _Contact Information_
4. Observe the dev console

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-01 14:37
Hello @ihor-sviziev 

Thank you for your report. We Confirm that the issue is reproducible on the latest 2.4-develop. Additional info is added to teh description.

**Comment by magento-engcom-team** [comment] 2021-02-01 14:39
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40701` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by pusachev** [comment] 2021-02-10 13:35
Same issue after upgrade to 2.4.2

**Comment by ihor-sviziev** [comment] 2021-02-10 13:59
@pusachev, you can apply https://github.com/magento/magento2/pull/31940 as a patch

**Comment by pusachev** [comment] 2021-02-10 14:09
@ihor-sviziev  yep I see it. 

Thanks

**Comment by gabrieldagama** [comment] 2021-06-16 10:57
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#31940 by @ihor-sviziev in 2.4-develop branch
Related commit(s):
 - [240253770cf2c41430d494c17730fe6484cbc18f](https://github.com/magento/magento2/commit/240253770cf2c41430d494c17730fe6484cbc18f)
 - [43ed528974031bf41e8cf94b51566b8e1feb24a5](https://github.com/magento/magento2/commit/43ed528974031bf41e8cf94b51566b8e1feb24a5)
 - [8ae5bf9b6a1816e1236d2706c043e98cac469a3c](https://github.com/magento/magento2/commit/8ae5bf9b6a1816e1236d2706c043e98cac469a3c)

The fix will be available with the upcoming 2.4.3 release.

**Comment by Viper9x** [comment] 2021-09-07 09:18
> Hi @ihor-sviziev. Thank you for your report.
> The issue has been fixed in #31940 by @ihor-sviziev in 2.4-develop branch
> Related commit(s):
> 
> * [240253770cf2c41430d494c17730fe6484cbc18f](https://github.com/magento/magento2/commit/240253770cf2c41430d494c17730fe6484cbc18f)
> * [43ed528974031bf41e8cf94b51566b8e1feb24a5](https://github.com/magento/magento2/commit/43ed528974031bf41e8cf94b51566b8e1feb24a5)
> * [8ae5bf9b6a1816e1236d2706c043e98cac469a3c](https://github.com/magento/magento2/commit/8ae5bf9b6a1816e1236d2706c043e98cac469a3c)
> 
> The fix will be available with the upcoming 2.4.3 release.

@gabrieldagama The fix didn't merge into 2.4.3 yet, so it does not available in 2.4.3

**Comment by pkarsai** [comment] 2022-09-21 13:27
After this was fixed, the fix was removed by this commit: https://github.com/magento/magento2/commit/405ee6ebdfb9a3df7455153eb11af2f91fdba562

So in version 2.4.5 the bug is back again... 🤦🏻‍♂️

**Comment by gkopec** [comment] 2022-10-18 08:13
Is there any patch for that?

**Comment by pkarsai** [comment] 2022-10-18 08:23
@gkopec, I created this from the PR:

```diff --git a/vendor/magento/module-customer/view/frontend/web/js/customer-data.js b/vendor/magento/module-customer/view/frontend/web/js/customer-data.js
index 213aa105b..6bff87d67 100644
--- a/vendor/magento/module-customer/view/frontend/web/js/customer-data.js
+++ b/vendor/magento/module-customer/view/frontend/web/js/customer-data.js
@@ -17,7 +17,9 @@ define([
 ], function ($, _, ko, sectionConfig, url) {
     'use strict';
 
-    var options = {},
+    var options = {
+            cookieLifeTime: 86400 //1 day by default
+        },
         storage,
         storageInvalidation,
         invalidateCacheBySessionTimeOut,
@@ -30,6 +32,22 @@ define([
     url.setBaseUrl(window.BASE_URL);
     options.sectionLoadUrl = url.build('customer/section/load');
 
+    /**
+     * Storage initialization
+     */
+    function initStorage() {
+        $.cookieStorage.setConf({
+            path: '/',
+            expires: new Date(Date.now() + parseInt(options.cookieLifeTime, 10) * 1000),
+            samesite: 'lax'
+        });
+        storage = $.initNamespaceStorage('mage-cache-storage').localStorage;
+        storageInvalidation = $.initNamespaceStorage('mage-cache-storage-section-invalidation').localStorage;
+    }
+
+    // Initialize storage with default parameters to prevent JS errors while component still not initialized
+    initStorage();
+
     /**
      * @param {Object} invalidateOptions
      */
@@ -217,14 +235,7 @@ define([
         /**
          * Storage init
          */
-        initStorage: function () {
-            $.cookieStorage.setConf({
-                path: '/',
-                expires: new Date(Date.now() + parseInt(options.cookieLifeTime, 10) * 1000)
-            });
-            storage = $.initNamespaceStorage('mage-cache-storage').localStorage;
-            storageInvalidation = $.initNamespaceStorage('mage-cache-storage-section-invalidation').localStorage;
-        },
+        initStorage: initStorage,
 
         /**
          * Retrieve the list of sections that has expired since last page reload.
@@ -389,7 +400,10 @@ define([
          */
         'Magento_Customer/js/customer-data': function (settings) {
             options = settings;
+
+            // re-init storage with a new settings
             customerData.initStorage();
+
             invalidateCacheBySessionTimeOut(settings);
             invalidateCacheByCloseCookieSession();
             customerData.init();
```

**Comment by Viper9x** [comment] 2022-10-18 10:40
@gkopec The fix for this issue was accidentally removed in magento 2.4.4 and 2.4.5. I've created a pull request for that: https://github.com/magento/magento2/pull/36177

You can use this patch for 2.4.5: https://github.com/magento/magento2/commit/847c7997143d3c90b26f94480a9fe202f499faf7.diff

**Comment by ihor-sviziev** [comment] 2022-10-18 12:32
Re-opened since it was reverted. https://github.com/magento/magento2/issues/31920#issuecomment-1253711103

**Comment by engcom-Bravo** [comment] 2022-12-20 12:03
Hi @ihor-sviziev,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshost.


**Steps to reproduce** 

1.Add the following code to the page on frontend:
```
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        console.log(customerData.getExpiredSectionNames());
    });
</script>
```
2.Go to the frontend, see the console


In Console we are getting Error.


<img width="1507" alt="Screenshot 2022-12-20 at 2 33 47 PM" src="https://user-images.githubusercontent.com/51680745/208662559-3a2ec251-1e80-47bd-bc7d-59118e4262a0.png">




Hence confirming this issue.  

Thanks.

**Closed as completed** 2023-03-02 14:33 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Reported on 2.4.1, Area: Account

**Comment by kanevbg** [comment] 2023-08-24 14:52
up, 2.4.x-develop seems to still produce the error (tested with firefox).

**Comment by AndresInSpace** [comment] 2024-08-22 19:16
It appears this has not been fully addressed.
The patch added a check for storage, at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L272

Needs same check at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L263 
as it's within the same method getExpiredSectionNames

Additionally customer-data has a race condition with it's mixin and the AjaxComplete event...
the ajaxcomplete fires before the mixin is loaded due to customer-data loading in requirejs for the mixin to be applied, then an ajax event fires before mixin is loaded (requirejs settimeout)
