### ISSUE TITLE
Style changes do not show

### ISSUE THREAD

**Issue by victorchiriac89** [magento/magento2#6214] opened 2016-08-18 01:41 UTC
Magento 2.1 (github version)
php 5.6
Mysql 5.6

While building my own theme:

``` document
app/design/MyTheme/theme/registration.php
```

``` php
  <?php
  \Magento\Framework\Component\ComponentRegistrar::register(
      \Magento\Framework\Component\ComponentRegistrar::THEME,
      'frontend/MyTheme/theme',
      __DIR__
  );
```

``` document
app/design/MyTheme/theme/theme.xml
```

``` xml
  <?xml version="1.0"?>
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>My theme</title>
    <parent>Magento/blank</parent>
</theme>
```

I added the theme and registered and deployed it and the theme works fine.

But I wanted to do overrides to the Magento_Theme module css so I added some changes here:

``` document
app/design/MyTheme/theme/Magento_Theme/web/css/source/_module.less
```

**StepX**

``` comment
Clear cache 
and/or 
remove processed css/less from root_project_dir#/pub/static/mytheme/...

and/or
root_project_dir# php bin/magento cache:clean && php bin/magento cache:flush

and/or
root_project_dir# chmod -R 777 var/ app/etc pub/static

and/or
Cleared browser cache + tried different browser

and/or
root_project_dir# chmod -R 777 pub/static var/ app/etc && php56 bin/magento setup:static-content:deploy
```

After I tried to add:

``` document
app/design/MyTheme/theme/Magento_Theme/layout/default_head_blocks.xml
```

``` xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
        <css src="css/styles-m.css" />
        <css src="css/styles-l.css" media="screen and (min-width: 768px)"/>
        <css src="css/print.css" media="print" />
    </head>
</page>
```

Then tried StepX again.

Then I tried adding style to theme as described in:

``` url
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-topics/css-themes.html
```

``` document
app/design/MyTheme/theme/web/css/_styles.less
```

``` less
// Theme colors
@theme-light-blue:#98DDDE;
.page-header {
        .panel.wrapper {
            .lib-css(background-color, @theme-light-blue);
        }
    }
```

or

``` less
// Theme colors
@theme-light-blue:#98DDDE;
.page-header {
        .panel.wrapper {
            background: @theme-light-blue;
        }
    }
```

Then tried StepX again.

Is there any way I can update Magento_Theme/web/css/source/_module.less css, I probably did it completely wrong or there is a bug here.

**Comment by robinhuy** [comment] 2016-08-19 08:23
I'm using same environment, and try to making simple style changes in client-side compilation mode with this tut [CSS quick mode guide](http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/css-guide/css_quick_guide_mode.html#client-side)
But I can't see section Developer in STORES > Configuration > ADVANCED (there are 2 sections: Admin and System)

So I try making simple style changes in server-side (or using with Grunt) but it does not work. I must run command `bin/magento setup:static-content:deploy` to apply new styles when change less files.

I'm using Magento 2.1 github version

**Comment by eug123** [comment] 2016-11-29 17:37
Hi,

Thank you @victorchiriac89 have you tried also to clean [var/view_preprocessed directory](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_mode.html#server-side).
Alse you can clean static files from the admin panel `System->Cache Management` "Flush Static Files Cache" button in the bottom of the page.

Please let us know if this works for you.

**Comment by MomotenkoNatalia** [comment] 2016-12-13 17:38
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by MomotenkoNatalia** 2016-12-13 17:38 UTC
Labels: Progress: needs update, Area: Frontend
