### ISSUE TITLE
Product Import: Additional data: Invalid URL key

### ISSUE THREAD

**Issue by Alex-James17** [magento/magento2#10697] opened 2017-08-29 12:52 UTC
### Actual Result
When performing a product import with a category field which begins with a comma, a General Exception is raised with a spurious error message and no rows are imported.

### Preconditions
Running Magento 2.2 on PHP 5.6.28 with MySQL 5.6.34 on MAMP under MacOS 10.12.6

### Steps to reproduce
1. System > Import > Products
2. Choose "Add/Update
3. Select a CSV file containing a "categories" column with a comma as the first character
4. Click Check Data then Import

### Expected Result
I would expect the error message to indicate an issue with the clearly invalid category field (column 5 in my file) rather than pointing at the url_key field (column 18 in my file).

**Comment by misha-kotov** [comment] 2017-08-29 15:36
@Alex-James17 can you attach a sample file please. 
And can you clarify - does the column header value have the comma or the values under the header?

**Comment by Alex-James17** [comment] 2017-08-30 10:50
File attached, the comma should be in one of the values rows, not the header as per the attachment.

[invalid-category.csv.zip](https://github.com/magento/magento2/files/1263289/invalid-category.csv.zip)

**Comment by misha-kotov** [comment] 2017-08-30 20:45
Thanks - internal issue is MAGETWO-72101

**Comment by avdb** [comment] 2017-09-26 08:28
I would like to look into this issue

**Comment by okorshenko** [comment] 2017-09-26 08:48
@avdb  I've sent you an invite to join Magento Team on the GitHub. Please, accept the invite

**Comment by avdb** [comment] 2017-09-26 08:54
@okorshenko done

**Comment by okorshenko** [comment] 2017-10-04 21:18
@Alex-James17, thank you for your report. The issue is already fixed in 2.2-develop branch (PR: #11049 by @avdb) and will be available in the Magento 2.2.2 release

**Closed as completed by okorshenko** 2017-10-04 21:18 UTC
Labels: Issue: Ready for Work, bug report, Component: ImportExport, Issue: Clear Description, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-04 21:25
Internal ticket to track issue progress: MAGETWO-80229

**Comment by magento-engcom-team** [comment] 2018-02-08 22:59
Hi @Alex-James17. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1361 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 716f9afd694b6d7e5423bd2dbdabeeb45797886b
 - 595527a919eafd309f8b2a1d1339b312f6546f7b
 - 8c05a29b711ca03ecb866fc384122b3e46c08ccd
 - 63958cdc14bf3b44ad5fd95aafc626d8e25ca3e3
 - 78c2c2159b6c5aacc27e4fc918a1ed56a9df9b5f
 - 7f2dc2965a2d46e935770a7acdef8f260bd5fdc6
 - aee74586a9d28c1f47fd2ba3bae5e5871b779be9
 - 92f85860ce9725e34922a523e5137e656322c394
 - bf178ca5c3c10a50e3eba6e64fdf905e75d0b4c5
 - ecafa804c26054499b42c6820f0996035eb39dbc
 - a15208e96c06248d740ee65d154eda30226c848a
 - 76716b84a92f009253039cd06b9e47367384655f
 - 490785fffd885f85a7292c9144783cf2576b6b66
 - 6fe62802f5a529cd113697df79021bdb1dda9f53
 - 33e40ece8246363429be614440622600394a4516
 - 7b1bec8edb2eedea399eb78f891f1d6873cb1955
 - dbe5fc792279802f83d7110285c15fb2eede8d95
 - 22c6937f6db6a2ed17188f24097e0f9a194dc295
 - ca7da3fd58edca05b70a2af1768743ffc0294b72
 - b55a5d1a497279f72735e577ba60327dba178b6e
 - 65b745f7a94b2ba699a68f2825a63c9d78615f1c
 - b0a5a52df60a765748f15a7e0391f6b50535de21
 - 97dd9ad59c7d6bf9d4cf673a8e22708c480b1967
 - aa28366cc7378a972497e186fa8fb955684f74aa
 - 0fc86d89ab491fe7fc246d025662658844cd15a4
 - f11994acc1e220eb620d3baa63da8427d53e5797
 - 04445d07887870ba47dd2e97006c94d656f85942

The fix will be available with the upcoming 2.3.0 release.

**Comment by allblued** [comment] 2019-02-11 04:51
magento2.3.0
same problem

**Comment by csimby** [comment] 2019-04-02 18:26
Same problem at me too.

**Comment by ulukai-ork** [comment] 2019-04-08 15:50
Magento 2.3.1 still buggy :(

**Comment by ulukai-ork** [comment] 2019-04-08 16:01
Magento 2.3.1 still buggy :(

**Comment by Misco** [comment] 2019-04-20 23:53
i get same error, exportet from shop, import this error 2.3.1

**Comment by danieljoeblack** [comment] 2019-11-06 21:33
This issue is also happening when there are two slashes in a category.

    ex. Atv/Filters//Fuel

This is on Magento 2.3.1

**Comment by Puru2016** [comment] 2020-02-02 10:17
I am still facing this issue in 2.3.2.
I have already created categories and importing the products using CSV.
I am getting same error:-
`Additional data: Invalid URL key`

Please let me know what is proper fix for this issue.

**Comment by luluhAlkhamisi** [comment] 2020-03-03 06:17
do you find the solution or not? it occurs to me

**Comment by ame5hca** [comment] 2021-01-20 09:03
Any solution to this issue. I am getting the same issue on my Magento 2.3.4 version.?
