### ISSUE TITLE
Magento2 admin media library (storage root) will not load on Magento version 2.4.2

### ISSUE THREAD

**Issue by burgh8wp** [magento/magento2#33538] opened 2021-07-20 14:27 UTC
Preconditions (*)

1. 2.4.2 and 2.4.2-p1
2. Version 2.4.1 the issue does not occur
3. PHP settings are identical on same server/same site between versions 2.4.1 and 2.4.2

Steps to reproduce (*)

1. Add or edit a static block or page from Magento admin
2. Click on insert/edit image. Click on search icon from popup.
3. Storage root section shows loading icon which spins continuously until timeout. Stores with small amount of folders/images does load, but takes substantially longer than Magento version 2.4.1 does.

Expected result (*)

1. Upon page load, the folder tree should show under storage root which sit in media area

Actual result (*)

1. Page loads continuously until timeout, and folders will not show

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround.

**Comment by engcom-November** [comment] 2021-07-22 12:30
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
**Steps performed:**
1. Admin - Content - Elements - Blocks - Add New Block/ Edit existing block
2. Click on "Insert/Edit Image"
3. Click on Search icon - No issue : Page is loaded immediately and folder structure is displayed as expected
4. Upload image - Add selected and Save - No issue.
Note: This is not reproducible for Admin - Content - Elements - Pages as well.
![image](https://user-images.githubusercontent.com/60198231/126639228-e9527c82-0fcc-4216-bfc4-77f33897a108.png)

**Comment by engcom-November** [comment] 2021-08-05 10:25
@burgh8wp we are closing this issue as there has been no latest update on the same.
Thank you

**Closed as completed by engcom-November** 2021-08-05 10:25 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2

**Comment by burgh8wp** [comment] 2021-08-12 11:57
@engcom-November 

You haven't tested on a site with large volume of media files, hence inability to replicate the issue. It is definitely present in version 2.4.2 and 2.4.2-p1 we have yet to test on 2.4.3 but have created the below workaround:

/app/code/ImageFix/PatchMedia/Block/Adminhtml/Wysiwyg/Images/tree.php

Contents of above file as below:

```
<?php

namespace Webguru\PatchMedia\Block\Adminhtml\Wysiwyg\Images;

class Tree extends \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree {
    /**
     * @var \Magento\Framework\Serialize\Serializer\Json
     */
    private $serial;

    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Cms\Helper\Wysiwyg\Images $cmsWysiwygImages
     * @param \Magento\Framework\Registry $registry
     * @param array $data
     * @param \Magento\Framework\Serialize\Serializer\Json|null $serializer
     * @throws \RuntimeException
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Cms\Helper\Wysiwyg\Images $cmsWysiwygImages,
        \Magento\Framework\Registry $registry,
        array $data = [],
        \Magento\Framework\Serialize\Serializer\Json $serial,
        \Magento\Framework\Serialize\Serializer\Json $serializer = null
    ) {
        parent::__construct(
            $context, $cmsWysiwygImages, $registry, $data, $serializer
        );
		$this->serial = $serial;
    }

    public function getTreeJson()
    {
        $storageRoot = $this->_cmsWysiwygImages->getStorageRoot();
        $collection = $this->_coreRegistry->registry(
            'storage'
        )->getDirsCollection(
            $this->_cmsWysiwygImages->getCurrentPath()
        );
        $jsonArray = [];
        foreach ($collection as $item) {
            $data = [
                'text' => $this->_cmsWysiwygImages->getShortFilename($item->getBasename(), 20),
                'id' => $this->_cmsWysiwygImages->convertPathToId($item->getFilename()),
                'path' => substr($item->getFilename(), strlen($storageRoot)),
                'cls' => 'folder',
            ];

            $hasNestedDirectories = count(glob($item->getFilename() . '/*', GLOB_ONLYDIR)) > 0;

            // if no nested directories inside dir, add 'leaf' state so that jstree hides dropdown arrow next to dir
            if (!$hasNestedDirectories) {
                $data['state'] = 'leaf';
            }

            $jsonArray[] = $data;
        }
        return $this->serial->serialize($jsonArray);
    }
}
```
