### ISSUE TITLE
Inventory update of Configurable Product fails when database uses prefixes

### ISSUE THREAD

**Issue by vbidou** [magento/magento2#38045] opened 2023-10-05 09:47 UTC
### Preconditions and environment

- Magento version: 2.4.6-p1
- Database encoding: utf8mb3_general_ci
- Setup Magento to use Database prefix. 
- Example of Prefix: tst_
- Establish prefix in app/etc/env.php
- Rename all Tables of the Database with the prefix defined.
- Flush Cache and Redeploy Magento.

### Steps to reproduce

After you setup Magento with Database prefix, create a configurable product A0 with 2 Simple Products inside A1 and A2.
Then assign inventory source to the two simple products.
Then try to set the inventory quantity for the Simple Products A1 and A2.

### Expected result

The set quantity is saved and the quantity is recorded in the inventory Table.

### Actual result

Error message appears (example) when trying to save:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gtfnvnbmcy.cataloginventory_stock_status' doesn't exist, query was: UPDATE `cataloginventory_stock_status` SET `stock_status` = ? WHERE (product_id = 745) `

And the quantity is not saved.

Under this example of error, the product ID 745 is set for the Configurable product A0 and not for the Simple Products A1 and A2.

### Additional information

I tried to modify the Inventory quantity in the Simple Products A1 and A2 who is part of Configurable Product A0 and also inside Configurable Product A0 directly. It gives the same error. It means that the Simple Product who is belonging to a Configurable Product uses the same saving protocol or script. 

It seems that the SAVING action does not allow to assign the expected prefix to the database updating query. In the above example, it should point to table gtfnvnbmcy.tst_cataloginventory_stock_status instead of gtfnvnbmcy.cataloginventory_stock_status

Other information: It seems that the processor of the saving is located in this path:
/public_html/vendor/magento/module-inventory-indexer/Model/ResourceModel/UpdateLegacyStockStatus.php
This .php code calls the Table name cataloginventory_stock_status which is OK. But prefix is not added.

### Release note

I can provide screen captures and testing results on demand.
We Tested on Production server, Test Server and also on a fresh-new Magento installation: Same outcomes.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vbidou** [comment] 2023-10-11 08:10
Dear Team,
My developer was able to define a temporar fix that we deployed successfully, but it is only a patch which is outside the folder vendor/magento. If you identify and fix the issue in future Magento release, we will remove this temporar fix from the installation before the upgrade sequence.
Best regards

**Comment by iphigenie** [comment] 2023-12-12 16:13
I have just bumped into this one.

The problem is always the same:

There are multiple versions of getTableName() across the Magento classes and NOT ALL OF THEM add the prefix properly

For example I have encountered that
`$this->resourceConnection->getTableName() ` adds prefix 
but
`$this->resourceConnection->getConnection()->getTableName() ` does NOT add prefix

(Now it should be consistent and `$this->resourceConnection->getConnection()->getTableName() ` should add prefix surely?)

So in the file /public_html/vendor/magento/module-inventory-indexer/Model/ResourceModel/UpdateLegacyStockStatus.php

```
    /**
     * Update legacy stock status for given skus.
     *
     * @param array $dataForUpdate
     */
    public function execute(array $dataForUpdate): void
    {
        $connection = $this->resource->getConnection();
        $tableName = $connection->getTableName('cataloginventory_stock_status');
```

should probably be

```
        $connection = $this->resource->getConnection();
        $tableName = $this->resource->getTableName('cataloginventory_stock_status');
```

**Comment by vbidou** [comment] 2023-12-13 16:28
Brilliant demonstration iphigenie !
@engcom-Dash, do you think it can be fixed in the core of magento ?
You haven't responded to this one yet.
Please update us.

**Comment by engcom-Dash** [comment] 2023-12-18 14:37
Hi @vbidou 

Thanks for reporting and collaboration.

Verified the issue in magento developer instance and the issue is not reproducible.
The quantity is being saved and getting updated in the inventory table.
Please refer the attached screenshots.
<img width="1440" alt="Inventory" src="https://github.com/magento/magento2/assets/60198592/0a951572-e81f-42ed-a202-cee8cb58423c">

<img width="1440" alt="Inventory_Admin" src="https://github.com/magento/magento2/assets/60198592/d6f83b63-df86-44c6-bcd0-7036991c22dd">

**Comment by vbidou** [comment] 2023-12-18 14:46
Indeed it seems to work on your side.
Which Magento version have you used ?
Have you added a prefix to the database ?
Have you used customized storage locations (not default one) ? (In my case I used customized MSI storage source)
Have you tried to update and save those quantities both in Simple and Grouped products ? No error ?
Thank you for the support.

**Comment by iphigenie** [comment] 2023-12-18 16:43
@engcom-Dash I can see the test has prefix but did it have sources set up or is it on default inventory?

Adding some context - I was testing configurable on my site as tired of bumping into issues with Grouped products. And creating a configurable product with 1 child and I bumped into that error.

I can't remember if I told it to skip configuring inventory at product creation or if I went through assigning sources and stock levels - but on save it had created the product but failed on the stock information

Live site of long existence. Version open source ver. 2.4.6-p3. MSI with 2 sources on 1 site. 

I made the code change mentioned above and it no longer has that error on creation.

But there is a bug on editing to create further process, which I suspect means that there's another place where the same error is happening.

**Comment by vbidou** [comment] 2023-12-18 17:02
I have the same reading. We should use MSI and not default inventory source. In my case I created the MSI post-factum the product creation.
@engcom-Dash please feedback on this. Thank you.

**Comment by engcom-Dash** [comment] 2023-12-26 15:05
Hi @vbidou 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4-developer instance and the issue is reproducable.

When the database uses prefixed the inventory update of configurable products is failing.
We are seeing the below error when trying to save:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gtfnvnbmcy.cataloginventory_stock_status' doesn't exist, query was: UPDATE cataloginventory_stock_statusSETstock_status= ? WHERE (product_id = 745)

Please refer the screenshot attached.
<img width="1440" alt="Inventory_Error" src="https://github.com/magento/magento2/assets/60198592/14879da3-1e0e-454f-9045-392a714fb04b">

**Comment by iphigenie** [comment] 2024-01-02 11:36
Just a quick nudge that the issue BEHIND this is an inconsistency between variants of getTableName

in the context here

$this->resourceConnection->getTableName()  adds prefix
but
$this->resourceConnection->getConnection()->getTableName()  does NOT add prefix

This needs to be documented very clearly OR perhaps made more consistent

**Comment by ajung2** [comment] 2024-04-04 14:42
We have the same problem fixed it tmp with a patch.
Patch:
[UpdateLegacyStockStatus_2.4.6.txt](https://github.com/magento/magento2/files/14872920/UpdateLegacyStockStatus_2.4.6.txt)

**Comment by engcom-Bravo** [comment] 2024-05-27 12:02
Hi,

Internal team has started to work on it

Thanks.

**Comment by engcom-Dash** [comment] 2024-06-01 15:25
Hi @vbidou 

Verified the issue on the latest Magento 2.4 dev instance but the issue is no longer reproducible.

Steps to reproduce :

1. After you setup Magento with Database prefix, create a configurable product A0 with 2 Simple Products inside A1 and A2.
2. Then assign inventory source to the two simple products.
3. Then try to set the inventory quantity for the Simple Products A1 and A2.

 Please verify the attached screenshot:

<img width="1440" alt="Screenshot 2024-06-01 at 8 54 35 PM" src="https://github.com/magento/magento2/assets/60198592/4b625c11-09ac-4251-b0d2-bd145f18b753">

**Comment by vbidou** [comment] 2024-06-01 22:21
Thanks.
Which M2 version have you used ?
Which DB prefix have you set ?

**Comment by engcom-Dash** [comment] 2024-06-03 08:42
Hi @vbidou 

We have tested in Magento 2.4 dev instance.
 
DB prefix : tst_

Please verify the attached screenshot

<img width="1440" alt="Screenshot 2024-06-03 at 2 11 05 PM" src="https://github.com/magento/magento2/assets/60198592/fad82e87-560f-4b77-ad3c-1050abd0e7af">

**Comment by vbidou** [comment] 2024-06-03 09:52
Thanks for the follow-up.
Interesting.
I tested on Magento version: 2.4.6-p1. Is it possible that you Dev version received a fix meanwhile ? 
Which version this Dev instance plays on ?

**Comment by engcom-Dash** [comment] 2024-06-04 10:05
Hi @vbidou,

We tested the issue on Magento versions 2.4-dev, 2.4.6-p6-dev, and 2.4.6-p1-dev, and this issue is already fixed in all dev versions, and the issue is not reproducible anymore. I've included the screenshot below for your reference.

<img width="1440" alt="Screenshot 2024-06-04 at 3 22 00 PM" src="https://github.com/magento/magento2/assets/60198592/cd32662f-df44-468f-be60-35ae394ec2b3">

**Comment by engcom-Dash** [comment] 2024-06-17 08:01
Hi @vbidou 

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you still face it.

Thank you.

**Closed as completed by engcom-Dash** 2024-06-17 08:01 UTC
Labels: Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Inventory / MSI, Reported on 2.4.6-p1
