### ISSUE TITLE
Importing Customers with custom attributes fails

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#16736] opened 2018-07-12 09:53 UTC
### Preconditions

1. Magento2.2.3

### Steps to reproduce

1.  Create a custom customer attribute like [here](https://www.mageplaza.com/magento-2-module-development/magento-2-add-customer-attribute-programmatically.html)
2. Export the customer Main file from System > Export , don't exclude any attributes
3. alter the customer main file 
4. Import the customer Main file from System > Import

### Expected result
The customer data including custom attributes gets imported correctly
1. [Screenshots, logs or description]

### Actual result
1. Spinner keeps hanging on the import. 

Following error is shown in the last admin/import/start/key/ request 

Call to a member function getBackendModel() on null in /Volumes/Projects/magento2/septodont-shop/vendor/magento/module-customer-import-export/Model/Import/Customer.php on line <i>413
![screen shot 2018-07-12 at 11 55 50](https://user-images.githubusercontent.com/9752966/42627276-d48dc1e0-85cc-11e8-8b05-cb33c12c7558.png)

**Comment by magento-engcom-team** [comment] 2018-07-12 09:53
Hi @duckchip. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@duckchip do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by philippsander** [comment] 2018-07-12 10:09
no information and duplicate of https://github.com/magento/magento2/issues/16737

**Closed as completed by philippsander** 2018-07-12 10:09 UTC
Labels: Issue: Format is valid
