### ISSUE TITLE
Reorder not working in 2.4.7-p1

### ISSUE THREAD

**Issue by mistergdin** [magento/magento2#38881] opened 2024-06-26 19:03 UTC
### Preconditions and environment

- Magento version 2.4.7-p1

### Steps to reproduce

1. Install the Magento version 2.4.7-p1
2. Place an order
3. Try to reorder

### Expected result

Redirect to cart to place the new order.

### Actual result

TypeError: Magento\Sales\Model\Reorder\Reorder::execute(): Argument #2 ($storeId) must be of type string, int given, called in vendor/magento/module-sales/Controller/AbstractController/Reorder.php on line 87 and defined in vendor/magento/module-sales/Model/Reorder/Reorder.php:147

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-06-27 04:23
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-27 05:01
Hi @mistergdin,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.



https://github.com/magento/magento2/assets/51680745/1f5853fe-cd02-4bd6-a96d-41ae8d1b6cd1




It is redirected to the cart and we are able to place the reorder.

Kindly recheck the issue and check if any third party modules causing the issue.

Thanks.

**Comment by mistergdin** [comment] 2024-06-27 12:15
Thanks!

It is working indeed, it must have been the environmental issue.

**Comment by engcom-Bravo** [comment] 2024-06-28 04:39
Hi @mistergdin,

Thanks for your update.

Since the issue has been resolved we are closing the issue. please feel free to reopen the issue if you are still facing any issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-28 04:39 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1

**Comment by sunilit42** [comment] 2024-11-20 18:58
Hello,

I m facing same issue, which environment related issue

**Comment by sunilit42** [comment] 2024-11-20 19:04
https://github.com/magento give me 2.4-develop instance
