### ISSUE TITLE
We can't find products matching the selection.

### ISSUE THREAD

**Issue by shomanath6** [magento/magento2#36765] opened 2023-01-22 23:43 UTC
Receiving "We can't find products matching the selection." on every category page of site (spandexhouse.com)
- Product pages work
- Back end looks fine on admin panel: products are in stock, enables, assigned to website and categories. Categories are enabled. All attributes are available.
- Change happened after last upload: I uploaded ~60 products last night using CSV. Used all typical processes.
- Tested mass image upload function for first time: went to server to upload images, images weren't reading, so I removed the images and just uploaded how I usually do, manually on admin panel.
- Site was working hours after upload, but changed overnight.

**Comment by FadedOut** [comment] 2023-01-23 02:20
@shomanath6 Just a thought, but is your elasticsearch running? Not saying this is the problem, but if elasticsearch went down this is the exact problem you'll run into. Most of the site will work fine but you won't get products to show on category pages. Also you won't be able to save products either. 

Simple ways to test:
-Try saving a product - if it gives some error at the top of the product page (I forget exactly what it says) then elastic search is probably down.
-Going to "Stores > Configuration > Catalog > Catalog > Catalog Search you'll find a section all about the elasticsearch (like hostname, server port, etc.), there will be a button saying "Test connection". Click that and if it says filled to find nodes (or something like that) then elasticsearch is down.
-You can use a simple "htop" command in your cpanel/whm terminal and you can see if the process for elasticsearch shows up. 
-You can also use the "Process Manager" under "System Health" in WHM (if you have access)
-You can also run the command "service elasticsearch.service status" and it will tell you if it is running or not

If elasticsearch is down, that is most likely the problem. If it is running, it could be something else and would require more information (logs, etc.).

If elasticsearch is the culprit (sounds like it might be as you probably ran out of resources for it after importing the products), you'll want to look into providing more RAM for it. Doing some research on increasing the RAM for elasticsearch will keep it alive longer during RAM intensive processes like importing and CRONs (though it will still terminate to save the server from crashing). 

Something like modifying /etc/elasticsearch/jvm.options.d/jvm.options with the following might help:
-Xms2g
-Xmx2g

Though remember, the system itself will use around 2gb of RAM, so dedicating 2gb to elasticsearch means when CRONs (and other tasks like composer update or importing/updating products) run you'll be around 4-4.5gb of RAM usage. You want to have a 6GB server to run the site comfortably and not have elasticsearch always terminating. If you're running elasticsearch on the same server that is.

**Comment by engcom-Bravo** [comment] 2023-01-24 13:24
@FadedOut Thanks for your contribution & collaboration over here.

Hi @shomanath6,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Kindly Run `php bin/magento indexer:reindex`

Kindly check Sources and Stocks apply default stock to your website and let us know if you are still facing any issur.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-06 09:07
Hi @shomanath6,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-06 09:07 UTC
Labels: Issue: needs update, Reported on 2.4.x
