### ISSUE TITLE
Google optimizer interceptor causes crash error reports when 404 should happen. 

### ISSUE THREAD

**Issue by iphigenie** [magento/magento2#31316] opened 2020-12-17 10:10 UTC
I have been seeing the number of error report files mushroom since moving to 2.4.1

when i look at the corresponding error report, the error is 

    "Entity is not found in registry.","1":"#1 Magento\\GoogleOptimizer\\Block\\Code\\Category->getIdentities() called at [vendor\/magento\/module-page-cache\/Model\/Layout\/LayoutPlugin.php:96]

Now **I have never enabled nor used Google Optimizer** and couldn't even see where it was in configuration so I disabled all 3 extra google modules for now to get rid of the error

Anyone else have this issue?
why is it in my interceptors when I am not using it and have not configured it?
can it be disabled somewhere in admin?
Why would it be looking up URLs and dying when they don't exist instead of letting a normal 404 happen?

These are my guesses, I am filing this for access to try to replicate:

### Preconditions (*)
 
Magento 2.4.1
Google optimizer installed as part of normal deployment. Never used.

### Steps to reproduce (*)

Ask for an url that doesnt exist but contains a string that matches the url-key of a category

### Expected result (*)

the site should go to the no-route mode and either give a 404 response or any extensions/code registered to perhaps handle redirects to new pages should kick in.

### Actual result (*)

The google optimizer interceptor jumps in and fails.

An error report is triggered

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

This will affect people who have done a Magento 1 to Magento 2 migration, or perhaps changed implementation. Instead of being able to use the 404 and search/redirect tools to channel old URLs to new ones, the google optimizer causes extra load and errors. Not user friendly, but also could allow a bad bot to sink the site in tens of thousands of error reports, which in turn can seriously affect the site

**Comment by iphigenie** [comment] 2021-01-25 19:19
I have disabled the optimizer at the module:disable level but I still do not understand why it actively intercepts when not actually configured to be active in admin - that seems very badly coded

**Comment by iphigenie** [comment] 2021-04-14 10:06
I have tried to re-enable the optimizer and had errors happen again.
Google optimizer, even if not configured and therefore not used, intercepts and triggers on URL

**Comment by iphigenie** [comment] 2021-04-15 16:25
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-06-14 06:53
HI @iphigenie 
If its extension and after analysis from code perspective  it looks like problem with extension
please communicate with extension owner on marketplace  
If fix should be applied in this extension that is NOT part of git magento/magento2 repo we are not able to fix it here
Well anyhow, if it is specific to Magento code, we need a detailed steps to reproduce. A step by step procedure reproducing in the latest Magento version please.

**Comment by iphigenie** [comment] 2021-06-15 21:04
Hi @engcom-Alfa might be the case, so many extensions inject in URL rewrites - though for me disabling google optimizer removes the error. I can't reproduce it all that easily on vanilla with demo date - could be it needs a specific rewrite configuration and error configuration and cache etc. 

Since disabling the module is a fix and i have no urgent need for that module I'll let it sit

**Comment by engcom-Alfa** [comment] 2021-06-16 13:17
Well, Kindly test with the latest Magento version when you will be resuming back on this, and can report a fresh ticket in case of any issues relevant to Magento with all the Preconditions, Detailed steps to reproduce, expected and actual results.
So, I am closing this ticket for now.
Thanks

**Closed as completed by engcom-Alfa** 2021-06-16 13:17 UTC
Labels: Issue: needs update
