### ISSUE TITLE
Issue: Configurable product salable is not update correct in cataloginventory_stock_status

### ISSUE THREAD

**Issue by quanghien95** [magento/magento2#37958] opened 2023-09-05 10:45 UTC
### Preconditions and environment

- Magento version: 2.4.6-p2
- PHP: 8.2
- Nginx: 1.18
- Elastic Search 7.17.8
- Ubuntu 20

### Steps to reproduce

1. Create a configurable product as normally
2. Generate child product , choose Skip quantity at this time, Hit save
3. After save product, parent product and child product created with out of stock (we can check in this table cataloginventory_stock_status)
4. Try to change Stock status of parent product to Instock, then change to out of stock
5. Change Stock status of parent product to **In stock**, Update and add stock to some child product 
6. Stock Status of parent product in this table (cataloginventory_stock_status) is **0** , but in admin it still display **In Stock**
7. Try to save parent product again but the result is the same

### Expected result

In admin, parent product still display: In stock 
But when check in table cataloginventory_stock_status, the stock status row of parent product is 0
Product is not display in category page. 
When access directly with url, it display out of stock

### Actual result

Stock status of parent product (in this table cataloginventory_stock_status) should be change to **1** . Stock status in admin should be same of cataloginventory_stock_status table
Parent product should display "in stock" when have at least one child product is in stock and parent product stock status "In stock" in admin

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-09-06 12:21
Hi @quanghien95,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create a configurable product as normally
- Generate child product , choose Skip quantity at this time, Hit save
- After save product, parent product and child product created with out of stock (we can check in this table cataloginventory_stock_status)
- Try to change Stock status of parent product to Instock, then change to out of stock
- Change Stock status of parent product to In stock, Update and add stock to some child product
- Stock Status of parent product in this table (cataloginventory_stock_status) is 0 , but in admin it still display In Stock
- Try to save parent product again but the result is the same


<img width="533" alt="Screenshot 2023-09-06 at 12 55 04 PM" src="https://github.com/magento/magento2/assets/51680745/c2f835d0-159d-4ab8-85ff-380bc2651e98">




<img width="1218" alt="Screenshot 2023-09-06 at 12 55 56 PM" src="https://github.com/magento/magento2/assets/51680745/3f5ead07-ff5a-4d3a-84b2-826bbd686a05">



<img width="824" alt="Screenshot 2023-09-06 at 12 56 07 PM" src="https://github.com/magento/magento2/assets/51680745/6e0fd463-37c8-41e0-97fb-c4276d402c62">




In admin Parent product is in **IN STOCK** and in the table cataloginventory_stock_status is changed to 1 since we have changed parent product to in stock and we are able to access the product in frontend.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-21 06:14
Hi @quanghien95,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37958#issuecomment-1708243195 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-25 06:14
Hi @quanghien95,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-25 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.6-p2
