### ISSUE TITLE
setup:upgrade runs install() of <module>/Setup/InstallData.php inside a disabled module

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#2622] opened 2015-12-07 10:09 UTC
If I am developing a module and run `php bin/magento module:status` afterwards, I can see it is on the _List of disabled modules_ as it should be. But when I run now `php bin/magento setup:upgrade`, the install() method inside my <module>/Setup/InstallData.php is run and the module is enabled automatically.

Is this the desired behavior of `php bin/magento setup:upgrade`?

**Comment by Vinai** [comment] 2015-12-07 13:42
It has been so from the beginning, so my guess is yes.
That said, this issue tracker is only intended for bug reports. Please consider asking in the [official Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) first next time.
If this answers your question, please close this issue. If you would like to propose a change to this behavior however, this thread would be the right place. In that case please post your reasons here and leave the issue open.

**Comment by bh-ref** [comment] 2015-12-07 14:37
I propose to change the command `php bin/magento setup:upgrade` so that disabled (or not yet enabled) modules are not affected by it in any way.

**Comment by Vinai** [comment] 2015-12-07 14:39
Thanks, lets see what the response of one of the core team is then.

**Comment by mazhalai** [comment] 2015-12-07 15:46
@bh-ref @Vinai This has been possibly fixed in MAGETWO-45555, if not we will create a new ticket to fix it.

**Comment by Vinai** [comment] 2015-12-08 12:30
Thanks for the update @mazhalai. Is MAGETWO-45555 already in the public develop branch?

**Comment by mazhalai** [comment] 2015-12-08 15:05
@Vinai Not yet in public develop branch. I will post an update here when it is merged.

**Comment by Vinai** [comment] 2015-12-09 21:49
I just played with the command a little, and the current behavior is as follows:
- If the module is not yet listed in app/etc/config.php, then it will be added in an enabled state
- If the module is already listed in app/etc/config.php, then the activation state is not changed

This behavior actually makes sense. Curious to see what MAGETWO-45555 changes. Presumably the command will then add unknown modules in disabled state.

**Comment by ghost** [comment] 2015-12-09 21:55
From MAGETWO-4555:

Steps to reproduce:
1.  Enable all modules for uninstalled application
2.  Disable Magento_AdminNotification module, when the application is not installed yet
3.  Install Magento application
4.  Enable Magento_AdminNotification module through CLI

Expected result :
Message: The following modules have been enabled: Magento_AdminNotification

Actual result:
Message: No modules were changed.

**Comment by mazhalai** [comment] 2015-12-21 17:23
@bh-ref A fix has been posted in the develop branch. Please open a new issue if it still persists.

**Closed as completed by mazhalai** 2015-12-21 17:23 UTC
