### ISSUE TITLE
Bug with saving Cart price rule

### ISSUE THREAD

**Issue by tiamo** [magento/magento2#3393] opened 2016-02-12 22:37 UTC
I can't updating "Cart price rule".  If tab "Manage coupon codes" visible, field "times_used" sending as array, but in database this field is integer format.

**Comment by NadiyaS** [comment] 2016-06-08 11:40
Hi @tiamo ,
cart price rule is editable without bugs on version 2.0.7. 
Please upgrade your code. If you still have the same problem on 2.0.7 version, please, add all necessary steps to reproduce. 

Thanks.

**Comment by NadiyaS** [comment] 2016-06-23 11:39
The Issue is closed as not reproducible.
If you still have encountered this bug feel free to reopen it and provide all necessary details to reproduce it (Magento version, steps to reproduce, also all external extensions should be disabled)

**Closed as completed by NadiyaS** 2016-06-23 11:39 UTC
Labels: Progress: needs update
