### ISSUE TITLE
URL rewrites use default url_key when products are imported in default scope

### ISSUE THREAD

**Issue by HenKun** [magento/magento2#35199] opened 2022-03-16 09:49 UTC
### Preconditions (*)
1. Magento 2.4.1

### Steps to reproduce (*)
1. Create a product with `url_key` set to `key_default` on default scope
2. Override `url_key` to `key_store` in store view scope
3. Import a csv with the product
   a) `store_view_code` column is empty, so that it applies for default scope
   b) `url_key` is set to default key `key_default`

### Expected result (*)
1. URL rewrites are only regenerated for store views, where there is no overriden url_key, i.e where the default `url_key` really applies 
OR
2. URL rewrites for store views with overriden url_key keep the overriden url_key and do not use the default value

### Actual result (*)
1. URL rewrites for store views with overriden `url_key` use the `url_key` present in the import file (for both canonical and category/product URLs)
Note 1: The store view specific url_key is not changed or deleted after import, it is still correct, only the rewrite has used the wrong key.
Note 2: The path of the categories use the correct url_key if they were overriden, only the product url_key is wong

### Reason

In `vendor/magento/module-catalog-url-rewrite/Observer/AfterImportDataObserver.php` on line 283 `populateGlobalProduct()` is called, since the scope of the imported product row is global.

In this method, all applicable websites and store ids are iterated and afterwards added by `addProductToImport()`.

In `generateUrls()` on line 378 the URL rewrites are now generated. Note that due to the last step, the imported product is added for all store views it is visible in. 

In `canonicalUrlRewriteGenerate` on line 410 the request path for the URL rewrite is now generated. Here lies the problem. `$product` has set the imported default `url_key` value, and although the `$storeId` is passed to `$this->productUrlPathGenerator->getUrlPathWithSuffix()` it is only used for the suffix. 

In a nutshell: The imported `url_key` is blindly used, without any check if `url_key` was overridden previously for a specific store view. This can have critical SEO impacts if not noticed.

### Possible solution

The `AfterImportDataObserver` shouldn't use the data from the import to regenerate the URL rewrites. It only should trigger a regeneration with the finally imported data and load the product per store view (e.g. like it is done after category saved)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-03-17 05:45
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-17 09:42
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-17 09:43
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-21 11:46
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-24 05:21
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-24 10:05
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
Created product with url_key: key-default
Edit product - Changed the scope - Default Store view - url_key changed to: key-store
Save
Access Front-end product using yourstore.com/key-store.html - User is able to access the page
![image](https://user-images.githubusercontent.com/60198231/159892329-b4aa6333-6c6c-4214-9da2-a0c00a4123ae.png)

Url rewrites are generated as expected.
![image](https://user-images.githubusercontent.com/60198231/159892537-73fc0b19-86ce-4ce6-bd20-46ec4973ad17.png)

Admin - System - Import - Product - CSV should contain product with url_key set to:  key-default and import.
Issue: URL rewrites of key-store are removed. URL rewrites for store views with overriden url_key use the url_key present in the import file 
Open the Product edit page - change scope to Default Store view and verify url_key. its still set as "key-store"
But unable to access the product on front-end using /key-store.html 
![image](https://user-images.githubusercontent.com/60198231/159891756-b7142010-ba38-4d03-a77e-e8f68c39c63c.png)
![image](https://user-images.githubusercontent.com/60198231/159891842-b0a38963-7a84-4989-a05f-dfbe50bac7a0.png)

**Comment by koenner01** [comment] 2022-04-06 09:59
I can append an additional problem to this ticket; We are running into a similar issue but for us it's caused by the `_populateForUrlGeneration` function in the observer mentioned by @HenKun 

We are running multiple imports right after each other but they don't all contain the "vital fields" required for the observer.
```
protected $vitalForGenerationFields = [
    'sku',
    'url_key',
    'url_path',
    'name',
    'visibility',
    'save_rewrites_history'
];
```

If you ommit the url_key and/or name in the import data, faulty rewrites will be generated on storeview scope.

I agree with the fact that this observer should not be using import data to create the url rewrites. It should instead load the products for specified stores and use that data to make sure everything needed is loaded and the values are correct.

**Comment by engcom-Hotel** [comment] 2022-08-26 10:46
Hello @<reporter>,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2701 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2701&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Comment by engcom-Bravo** [comment] 2022-09-01 08:57
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-09-01 12:00
Hi @HenKun,


Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch we are able to reproduce the issue. Kindly refer the screenshots.


Created product with url_key: key-default
Edit product - Changed the scope - Default Store view - url_key update to: key-store
Save
Access Front-end product using yourstore.com/key-store.html - User is able to access the page.



<img width="935" alt="3617" src="https://user-images.githubusercontent.com/51680745/187907369-425a0db9-a4d1-4434-b820-a5d524d20a26.png">



Url rewrites are generated as expected.

<img width="931" alt="3617 1" src="https://user-images.githubusercontent.com/51680745/187907531-89b76ca4-3779-41a4-9c8e-4d22a215c2b2.png">



Admin - System - Import - Product - CSV should contain product with url_key set to: key-default and import.
Issue: URL rewrites for store views with overriden url_key use the url_key present in the import file
URL rewrites of key-store are removed.
Open the Product edit page - change scope to Default Store view and verify url_key. its still set as "key-store"


<img width="936" alt="3617 2" src="https://user-images.githubusercontent.com/51680745/187907727-e2308b22-3dea-4581-a547-18f95027e0de.png">



But unable to access the product on front-end using /key-store.html

<img width="917" alt="3617 3" src="https://user-images.githubusercontent.com/51680745/187907938-36418b79-867c-4b62-8a4e-ea0197bf3b31.png">


<img width="937" alt="3617 4" src="https://user-images.githubusercontent.com/51680745/187908023-8ba5b347-88ef-4288-9bb8-5c04a31c616d.png">



Hence confirming this issue.


Thanks.

**Comment by faizan-shk** [comment] 2022-11-09 06:54
This issue is fixed in scope of https://jira.corp.adobe.com/browse/ACPT-488 and no longer reproducible on 2.4-develop.
Hence we can close this issue.

**Comment by engcom-Hotel** [comment] 2022-11-09 08:02
Thanks @faizan-shk for the updates. We are closing this issue.

**Closed as completed by engcom-Hotel** 2022-11-09 08:02 UTC
Labels: Issue: Confirmed, Component: UrlRewrite, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.1, Area: Search, Area: SEO

**Comment by HenKun** [comment] 2023-08-30 12:08
@faizan-shk While there are changes in `AfterImportDataObserver` on the develop branch, the changes are not released until 2.4.6-p2. Is there any schedule when the changes will go into effect?

**Comment by leonhelmus** [comment] 2024-03-15 10:49
@engcom-Hotel  this issue still exists :(

**Comment by engcom-Hotel** [comment] 2024-03-18 07:59
Hello @leonhelmus,

Please try the below patch and let us know if this works for you:

[7746.patch](https://github.com/magento/magento2/files/14632698/7746.patch)

Thanks
