### ISSUE TITLE
Preview Email Template cut off

### ISSUE THREAD

**Issue by vincent2090311** [magento/magento2#23754] opened 2019-07-18 03:45 UTC
### Preconditions (*)

1. Magento 2.3.2
2.PHP 7.1
3.Nginx 1.17

### Steps to reproduce (*)

1.Add new email template under marketing > Email Templates
2.Load any default magento email template > save without change
3.Go to email templates grid > click preview

### Expected result (*)

Can view full email templates

### Actual result (*)

1. Preview screen is cut off
![Capture 2019-07-18 at 10 36 35](https://user-images.githubusercontent.com/8340835/61427622-0c904900-a949-11e9-80d3-7ee91bee762e.png)

**Comment by ajijshekh123** [comment] 2019-07-18 05:26
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-18 05:26
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-18 05:27
Hi @ajijshekh123, here is your [Magento instance](https://i-23754-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23754-2-3-develop.instances.magento-community.engineering/admin](https://i-23754-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-07-18 05:39
Give me @magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-18 05:40
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by ajijshekh123** [comment] 2019-07-18 05:57
@vincent2090311 - I have reviewed this issue in Magento 2.3 Instance. I have loaded the different Email template Ex:- Create an Account, Order, Credit, Invoice. All the Email template is proper loading.

**See attached the screenshot:**

![2019-07-18 (1)](https://user-images.githubusercontent.com/24711761/61432659-be7e4400-a94e-11e9-85fb-607206637caa.png)

![2019-07-18](https://user-images.githubusercontent.com/24711761/61432660-be7e4400-a94e-11e9-981f-56732fa2df40.png)

@vincent2090311 - Let me know if you have reproduced this issue in Fresh Magento 2.3 Instance. If you didn't find this issue again let me know so I will close this issue.

**Comment by vincent2090311** [comment] 2019-07-18 06:20
@ajijshekh123
I checked on develop instance and its not using iframe so it doesnt have issue. Pls try to setup new magento installation on your PC, you will see preview email template is iframe

**Comment by ajijshekh123** [comment] 2019-07-18 06:25
@vincent2090311 - This issue I can review only Magento instance which is given by the Magento Team. If this issue is reproduced in Default Magento Instance I will add the tag reproduce otherwise I can't test Magento instance which is available in my system. 

Thanks.

**Comment by ajijshekh123** [comment] 2019-07-19 10:35
@vincent2090311 - feel free to reopen this issue when you will reproduce this issue in fresh Magento Instance.

**Comment by vincent2090311** [comment] 2019-07-19 12:36
@ajijshekh123 
Im still able to replicate issue on fresh magento 2.3.2 installation
<img width="1426" alt="Screen Shot 2019-07-19 at 7 34 57 PM" src="https://user-images.githubusercontent.com/8340835/61535375-53229800-aa5c-11e9-9782-577d2550e05c.png">

**Comment by ajijshekh123** [comment] 2019-07-19 12:43
Give me @magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-19 12:43
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-19 12:44
Hi @ajijshekh123, here is your [Magento instance](https://i-23754-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23754-2-3-develop.instances.magento-community.engineering/admin](https://i-23754-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2019-07-19 12:49
@vincent2090311 - Again, Not able to Reproduce.

![2019-07-19 (3)](https://user-images.githubusercontent.com/24711761/61536189-af33ef00-aa51-11e9-85ca-d0f892ca5c49.png)

**Comment by adamlukaszewski** [comment] 2019-07-23 20:50
Hi same here. I have also the same issue. E-Mail preview will be cut off due the iframe height.

![image](https://user-images.githubusercontent.com/119235/61746423-f268c780-ad9b-11e9-9849-6784562d5d0b.png)

I am running on a 2.3.2 instance (community).

Here is the generated HTML code (iframe available):

![image](https://user-images.githubusercontent.com/119235/61746507-204e0c00-ad9c-11e9-83d9-4db764e6ba3b.png)

**Comment by vincent2090311** [comment] 2019-07-30 06:00
@ajijshekh123 
Could you re-open this issue? Not just me face the issue, other people get the same issue with me.

**Comment by ajijshekh123** [comment] 2019-07-30 06:19
Okay @vincent2090311

**Comment by hoangnm89** [comment] 2019-07-30 07:09
I'm getting the same issue with 2.3.2 fresh installation. 
i tried on 2.3.1, no issue.

i think this is a clue for who want to fix the issue, sorry i have not tried yet.

**2.3.1 adminhtml_email_template_preview.xml**
https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Email/view/adminhtml/layout/adminhtml_email_template_preview.xml


```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="admin-1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <update handle="empty" />
    <body>
        <referenceContainer name="root">
            <block name="preview.page.content" class="Magento\Framework\View\Element\Template" template="Magento_Email::template/preview.phtml">
                <block class="Magento\Email\Block\Adminhtml\Template\Preview" name="content" as="content"/>
            </block>
        </referenceContainer>
    </body>
</page>
```


**2.3.2 adminhtml_email_template_preview.xml**
https://github.com/magento/magento2/blob/2.3.2/app/code/Magento/Email/view/adminhtml/layout/adminhtml_email_template_preview.xml
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="admin-1column" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <attribute name="id" value="html-body"/>
        <attribute name="class" value="preview-window"/>
        <referenceContainer name="backend.page" remove="true"/>
        <referenceContainer name="menu.wrapper" remove="true"/>
        <referenceContainer name="root">
            <block name="preview.page.content" class="Magento\Backend\Block\Page" template="Magento_Email::preview/iframeswitcher.phtml"/>
        </referenceContainer>
    </body>
</page>
```

**Comment by engcom-Charlie** [comment] 2019-07-30 07:29
I reproduce this issue on:
**2.3-develop**
![image](https://user-images.githubusercontent.com/51680850/62109329-b90cec00-b2b4-11e9-8786-b903c25262a4.png)

**2.3.2**
![image](https://user-images.githubusercontent.com/51680850/62109364-cf1aac80-b2b4-11e9-82bf-6ee754cd26a7.png)

Iframe height is so small. I confirm this issue.

**Comment by magento-engcom-team** [comment] 2019-07-30 07:29
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18734` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by BrentRobert** [comment] 2019-10-06 12:11
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-06 12:11
Hi @BrentRobert. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-06 12:11
Hi @BrentRobert, here is your [Magento instance](https://i-23754-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23754-2-3-develop.instances.magento-community.engineering/admin](https://i-23754-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-30 19:23
Hi @vincent2090311. Thank you for your report. 
The issue has been fixed in magento/magento2#24881 by @BrentRobert in 2.3-develop branch
Related commit(s):
 - [3374a5a9d11ee3a5577fd5f25a600852a9875039](https://github.com/magento/magento2/commit/3374a5a9d11ee3a5577fd5f25a600852a9875039)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-30 19:23 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Email, Component: Admin

**Comment by AndyJAllen** [comment] 2019-11-11 16:23
Where is that css file located in a composer installation? I don't even see a css folder in \vendor\magento\module-backend\view\adminhtml\web

**Comment by hemendrametawolf** [comment] 2023-03-03 06:27
I am still facing this issue on magento 2.4.4-p1

**Comment by hemendrametawolf** [comment] 2023-03-03 06:28
@magento give me 2.4.4-p1 instance

**Comment by hemendrametawolf** [comment] 2023-03-03 06:32
@magento give me 2.4.4 instance

**Comment by AndyJAllen** [comment] 2023-03-03 15:56
Do yourself a favor and look at WordPress + WooCommerce plugin. Magento is a disaster and many of us jumped ship. Many free & cheap modules to hook into a barebones e-commerce site to do almost anything a business would need. I also recommend Flatsome theme for their very nice UX builder feature.
