### ISSUE TITLE
Paypall trx is refused because of double, order is processed as if it was succesfull

### ISSUE THREAD

**Issue by richardreen** [magento/magento2#25222] opened 2019-10-22 16:24 UTC
Preconditions (*)

Magento 2.3.3
Php 7.3

Steps to reproduce (*)

Customer wants to pay a order with Paypall. Customer sees an succesfull booking and order.
In the backend we see now two succesfull orders  which are equal. Both have the status processing.
On our paypal account we see only 1 booking. Customer is also having 1 correct booking in their account
Talking to paypall about this, they have only one correct transaction, so there is something wrong in the software (=magento 2.3.3). Paypall did not have any issues today which could be a cause of this problem!

In the payment.log we see this:

    'TOKEN' => 'EC-111484486J071683F',
    'SUCCESSPAGEREDIRECTREQUESTED' => 'false',
    'TIMESTAMP' => '2019-10-22T09:54:28Z',
    **'CORRELATIONID' => '99985f31b4cbc',**
    'ACK' => 'Failure',
    'VERSION' => '72.0',
    'BUILD' => '53734851',
    'L_ERRORCODE0' => '10415',
    'L_SHORTMESSAGE0' => 'Transaction refused because of an invalid argument. See additional error messages for details.',
    'L_LONGMESSAGE0' => 'A successful transaction has already been completed for this token.',
    'L_SEVERITYCODE0' => 'Error',

in the backend we see for this order : 
![Screenshot_20191022_181205](https://user-images.githubusercontent.com/18627705/67307491-e2769600-f4f8-11e9-82ef-18b494c7dc91.png)

The system.log is filled with
2019-10-22 09:54:28] main.CRITICAL: PayPal NVP gateway errors: A successful transaction has already been completed for this token (#10415: Transaction refused because of an invalid argument. See additional error messages for details). Correlation ID: 99985f31b4cbc. Version: 72.0. [] []
[2019-10-22 09:54:33] main.CRITICAL: Exception message: Wij kunnen de express betaling niet initialiseren.
Trace: <pre>#1 Magento\Paypal\Controller\Express\AbstractExpress\PlaceOrder->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#2 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callParent('execute', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#3 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#4 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callPlugins('execute', array(), array(array('pluginAfterActio...'))) called at [generated/code/Magento/Paypal/Controller/Express/PlaceOrder/Interceptor.php:26]
#5 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#6 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#7 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#8 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Magento/Paypal/Controller/Express/PlaceOrder/Interceptor.php:104]
#10 Magento\Paypal\Controller\Express\PlaceOrder\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/App/FrontController.php:159]
#11 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#, &Magento\Paypal\Controller\Express\PlaceOrder\Interceptor#00000000723373630000000030180d93#) called at [vendor/magento/framework/App/FrontController.php:98]
#12 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#15 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000723370830000000030180d93#, &Closure#00000000723370550000000030180d93#, &Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#16 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#17 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000723370830000000030180d93#, &Closure#00000000723370550000000030180d93#, &Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#18 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/swissup/module-amp/Plugin/Framework/FrontController.php:48]
#19 Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#00000000723370830000000030180d93#, &Closure#00000000723370550000000030180d93#, &Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#21 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#22 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000072335a500000000030180d93#) called at [vendor/magento/framework/App/Http.php:137]
#23 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#24 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#25 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000072335a210000000030180d93#) called at [index.php:39]

As this is a payment issue  we can not remake this in a vanilla instance of M 2.3.3.

Expected result(*):
No second or more trx of the same to paypal
If Paypal report failure the order should fale also

Actual result(*)
A wrong approved order!!.

**Comment by engcom-Charlie** [comment] 2019-10-24 13:27
Hello @richardreen 

We are not able to reproduce this issue on the latest 2.3-develop(2.3.3 code is merged) branch by following **steps:**

1. Place order via PayPal 
2. Check order in backend for duplicates 
3. Check `system.log`

**Result:**
No duplicates and no errors in `system.log`

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-24 13:27 UTC
Labels: Issue: Format is valid

**Comment by dan-ding** [comment] 2019-12-02 17:33
I don't know how to re-produce this yet - but it does happen on occasion with Paypal Express.
2.3.2-xyz 
Missing "last transaction id" makes it pretty obvious. 

Paypal payment events in order:
SetExpressCheckout => Authorization is successful (with what seems to be correct invnum/order number)  
GetExpressCheckoutDetails => is successful  
DoExpressCheckoutPayment (paymentaction - authorization) => is successful  

Then for some reason **many seconds** (maybe a **lot of many's**) later:  
DoExpressCheckoutPayment (paymentaction - authorization) is fired again; fails with the error "A successful transaction has already been completed for this token."

notes
1) Order has created timestamp near(and after) second, failed, DoExpressCheckoutPayment, not the first.
2) There is no transaction associated with the order (obviously)
3) There are no errors recorded near or related to the above events (not including the error on the second authorization).

the admin reflects what's in (or not in the database) tables:
sales_order_payment has an incomplete entry (missing last transaction id)
sales_payment_transaction has no entries (obviously)

**Comment by aligent-lturner** [comment] 2020-07-02 23:46
We're also seeing this happen on 2.3.5-p1
One successful order, and then one (or more) failed payment attempts also resulting in orders in Magento, each without a transaction ID.

**Comment by netfarma** [comment] 2020-09-09 15:32
Hi,

This happen also on 2.4.0

to reproduce issue just open on new browser tab return_url (paypal/express/onAuthorization) from Paypal with token and PayerID in it.
you can generate any number of orders paid

It happens becouse of muted error
`vendor/magento/module-paypal/Model/Api/Nvp.php : 1294`

`
        /**
         * The response code 10415 'Transaction has already been completed for this token'
         * must not fails place order. The old Paypal interface does not lock 'Send' button
         * it may result to re-send data.
         */
        if (in_array((string)ProcessableException::API_TRANSACTION_HAS_BEEN_COMPLETED, $this->_callErrors)) {
            return;
        }
`

and in the same file You can see that this errors is not imported to api object:
`public function callDoExpressCheckoutPayment()
    {
        $this->_prepareExpressCheckoutCallRequest($this->_doExpressCheckoutPaymentRequest);
        $request = $this->_exportToRequest($this->_doExpressCheckoutPaymentRequest);
        $this->_exportLineItems($request);

        if ($this->getAddress()) {
            $request = $this->_importAddresses($request);
            $request['ADDROVERRIDE'] = 1;
        }

        $response = $this->call(self::DO_EXPRESS_CHECKOUT_PAYMENT, $request);
        $this->_importFromResponse($this->_paymentInformationResponse, $response);
        $this->_importFromResponse($this->_doExpressCheckoutPaymentResponse, $response);
        $this->_importFromResponse($this->_createBillingAgreementResponse, $response);
    }`


PayPal response below
`
...
    'ACK' => 'Failure',
    'VERSION' => '72.0',
    'BUILD' => '54871143',
    'L_ERRORCODE0' => '10415',
    'L_SHORTMESSAGE0' => 'Transaction refused because of an invalid argument. See additional error messages for details.',
    'L_LONGMESSAGE0' => 'A successful transaction has already been completed for this token.',
    'L_SEVERITYCODE0' => 'Error',

`

There should be new set of imported fields to discover errors

`
protected $_paymentErrorInformationResponse = [
        'ACK',
        'L_ERRORCODE0',
        'L_SHORTMESSAGE0',
        'L_LONGMESSAGE0',
        'L_SEVERITYCODE0'
    ];
`
and

`$this->_importFromResponse($this->_paymentErrorInformationResponse, $response);`

to get access to this informations

To resolve in right way You can add plugin on after call() method and check if response contains errors..

hope this help

**Comment by Kalashreeprem** [comment] 2020-12-16 08:28
> Hi,
> 
> This happen also on 2.4.0
> 
> to reproduce issue just open on new browser tab return_url (paypal/express/onAuthorization) from Paypal with token and PayerID in it.
> you can generate any number of orders paid
> 
> It happens because of muted error
> `vendor/magento/module-paypal/Model/Api/Nvp.php : 1294`
> 
> `/** * The response code 10415 'Transaction has already been completed for this token' * must not fails place order. The old Paypal interface does not lock 'Send' button * it may result to re-send data. */ if (in_array((string)ProcessableException::API_TRANSACTION_HAS_BEEN_COMPLETED, $this->_callErrors)) { return; }`
> 
> and in the same file You can see that this errors is not imported to api object:
> `public function callDoExpressCheckoutPayment()
> {
> $this->_prepareExpressCheckoutCallRequest($this->_doExpressCheckoutPaymentRequest);
> $request = $this->_exportToRequest($this->_doExpressCheckoutPaymentRequest);
> $this->_exportLineItems($request);
> 
> ```
>     if ($this->getAddress()) {
>         $request = $this->_importAddresses($request);
>         $request['ADDROVERRIDE'] = 1;
>     }
> 
>     $response = $this->call(self::DO_EXPRESS_CHECKOUT_PAYMENT, $request);
>     $this->_importFromResponse($this->_paymentInformationResponse, $response);
>     $this->_importFromResponse($this->_doExpressCheckoutPaymentResponse, $response);
>     $this->_importFromResponse($this->_createBillingAgreementResponse, $response);
> }`
> ```
> 
> PayPal response below
> `
> ...
> 'ACK' => 'Failure',
> 'VERSION' => '72.0',
> 'BUILD' => '54871143',
> 'L_ERRORCODE0' => '10415',
> 'L_SHORTMESSAGE0' => 'Transaction refused because of an invalid argument. See additional error messages for details.',
> 'L_LONGMESSAGE0' => 'A successful transaction has already been completed for this token.',
> 'L_SEVERITYCODE0' => 'Error',
> 
> `
> 
> There should be new set of imported fields to discover errors
> 
> `protected $_paymentErrorInformationResponse = [ 'ACK', 'L_ERRORCODE0', 'L_SHORTMESSAGE0', 'L_LONGMESSAGE0', 'L_SEVERITYCODE0' ];`
> and
> 
> `$this->_importFromResponse($this->_paymentErrorInformationResponse, $response);`
> 
> to get access to this informations
> 
> To resolve in right way You can add plugin on after call() method and check if response contains errors..
> 
> hope this help

Can you able to solve this? we are also seeing this happen.

**Comment by carylewis** [comment] 2021-03-02 17:22
Why is this issue closed? We are seeing this in Magento 2.3.5p2 EE.

**Comment by demandre** [comment] 2021-12-23 12:39
Same Here on Magento 2.4.0 CE

**Comment by dearste** [comment] 2023-07-26 05:33
2.4.3-p3 here, ssame issue..any fix?

**Comment by parthppwd** [comment] 2024-01-04 20:08
Anyone able to fix this? Facing the same issue even with Magento 2.4.5-p1
