### ISSUE TITLE
Magento 2 - Magento ver. 2.1.0

### ISSUE THREAD

**Issue by ghost** [magento/magento2#8394] opened 2017-02-02 15:38 UTC
When signed into an account. I then went through the checkout process. I then selected PayPal as my payment option. I then received an error

`1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with cartId = 

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): No such entity with cartId = 
#0 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-quote/Model/QuoteRepository.php(197): Magento\Framework\Exception\NoSuchEntityException::singleField('cartId', NULL)
#1 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-quote/Model/QuoteRepository.php(101): Magento\Quote\Model\QuoteRepository->loadQuote('load', 'cartId', NULL, Array)
#2 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(24): Magento\Quote\Model\QuoteRepository->get(NULL, Array)
#3 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-quote/Model/QuoteRepository.php(127): Magento\Quote\Model\QuoteRepository\Interceptor->get(NULL, Array)
#4 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Quote/Model/QuoteRepository/Interceptor.php(50): Magento\Quote\Model\QuoteRepository->getActive(NULL, Array)
#5 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-quote/Model/Quote/Item/Repository.php(69): Magento\Quote\Model\QuoteRepository\Interceptor->getActive(NULL)
#6 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-checkout/Model/Cart/ImageProvider.php(44): Magento\Quote\Model\Quote\Item\Repository->getList(NULL)
#7 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-checkout/Model/DefaultConfigProvider.php(281): Magento\Checkout\Model\Cart\ImageProvider->getImages(NULL)
#8 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\DefaultConfigProvider->getConfig()
#9 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Checkout/Model/DefaultConfigProvider/Interceptor.php(26): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->___callPlugins('getConfig', Array, Array)
#10 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): Magento\Checkout\Model\DefaultConfigProvider\Interceptor->getConfig()
#11 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-checkout/Block/Cart/Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#12 /var/www/vhosts/kays-medical/htdocs/app/design/frontend/Yoma/kaysmedical/Magento_Checkout/templates/cart/shipping.phtml(23): Magento\Checkout\Block\Cart\Shipping->getCheckoutConfig()
#13 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/vhosts...')
#14 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Shipping), '/var/www/vhosts...', Array)
#15 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/vhosts...')
#16 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#17 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#18 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('checkout.cart.s...')
#19 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.s...')
#20 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.cart.s...')
#21 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.cart.s...', true)
#22 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.cart.s...')
#23 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('cart.summary')
#24 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('cart.summary')
#25 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('cart.summary')
#26 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('cart.summary', true)
#27 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('cart.summary')
#28 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#29 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main')
#34 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#35 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#36 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#37 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#38 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#39 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#40 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#41 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#42 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#43 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#44 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#45 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#46 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#47 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#48 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#49 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#50 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#51 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#52 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#53 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#54 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#55 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#56 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#57 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#58 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#59 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#60 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#61 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#63 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#64 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#65 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#67 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#68 /var/www/vhosts/kays-medical/htdocs/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#69 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#70 /var/www/vhosts/kays-medical/htdocs/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#71 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /var/www/vhosts/kays-medical/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#73 /var/www/vhosts/kays-medical/htdocs/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#74 {main}`

**Comment by sshymko** [comment] 2017-02-02 19:05
Possibly duplicate of #6522

**Comment by veloraven** [comment] 2017-02-03 08:54
@RobertBroley thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by veloraven** [comment] 2017-07-03 06:39
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-07-03 06:39 UTC
Labels: Progress: needs update
