### ISSUE TITLE
requirejs load all JS instead of lazyload

### ISSUE THREAD

**Issue by asiapatrick** [magento/magento2#30484] opened 2020-10-13 15:54 UTC
requirejs-config.js

### Preconditions (*)
affected all versions
1. 2.2
2. 2.3
3. 2.4

### Steps to reproduce (*)
see requirejs-config.js
it evaluate all config by require(config).  Then it would load all JS.
the proper config should be
var config = {}

I try to generate requirejs-config.js manually.  It reduce a lot of unused javascript files.  This issue make magento extreme slow.  

Pls note that this should be S0.

**Comment by mrtuvn** [comment] 2020-10-14 12:31
Can you provide more specific about steps to reproduce ?
default requirejs-config.js is being merged across all modules/themes into one file and put in head tag
IMO the good way is only lazy load js files actived/enabled modules and active theme. All js in disabled modules should not be included

**Comment by engcom-Delta** [comment] 2021-01-12 14:07
Hi @asiapatrick thank you for your report. Please add more details for issue explanation to make it easier to understand(e.g.,screenshots, code snippets, what result you expect to see)

**Comment by mrtuvn** [comment] 2021-01-13 16:19
> I try to generate requirejs-config.js manually. It reduce a lot of unused javascript files
Can you describe more ?

**Comment by engcom-Delta** [comment] 2021-02-05 07:50
@asiapatrick  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2021-02-05 07:50 UTC
Labels: Issue: needs update, not-confirmed, Reported on 2.3.x
