### ISSUE TITLE
address2 & timing of store wrong

### ISSUE THREAD

**Issue by ajaybhan** [magento/magento2#13813] opened 2018-02-23 08:45 UTC
Dear Sir,

Address1 of our store " Computerwise Services" is wrong wherein it should be below Acharya Niketan [spelling Mistake)
Address2 of our store " Computerwise Services" is wrong wherein it should be " below Akash Institute" not syndicate bank

also timing should be till 8:30 pm 

Store ID : 2-SIUD-2085

Regards

Ajay Bhan

**Comment by ajaybhan** [comment] 2018-02-23 08:45
Dear Sir,

Address1 of our store " Computerwise Services" is wrong wherein it should be be : Acharya Niketan [spelling Mistake)
Address2 of our store " Computerwise Services" is wrong wherein it should be " below Akash Institute" not syndicate bank

also timing should be till 8:30 pm

Store ID : 2-SIUD-2085

Regards

Ajay Bhan

**Comment by magento-engcom-team** [comment] 2018-02-23 11:47
Hello @ajaybhan. Thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version
 - [x] Steps to reproduce
 - [x] Expected result
 - [x] Actual result

**Comment by magento-engcom-team** [comment] 2018-03-02 12:41
Closing due to lack of updates.

**Closed as completed** 2018-03-02 12:40 UTC
Labels: Progress: needs update, Issue: Format is not valid
