### ISSUE TITLE
PayPal Express Checkout Requiring Site Login on Firefox

### ISSUE THREAD

**Issue by devonto** [magento/magento2#7613] opened 2016-11-29 16:22 UTC
When clicking on the "PayPal Checkout" button from the mini cart or cart page and using Firefox, you are directed to the customer login page.

### Preconditions
1. Magento 2.1.1
2. Guest checkout enabled
3. PayPal Express Checkout enabled

### Steps to reproduce
1. Use Firefox (currently testing in safe mode on v50.0.1
2. Add product to basket
3. From the minibasket click on the PayPal logo

### Expected result
1. Redirected to PayPal site to log in and complete transaction

### Actual result
1. Sent to customer login/register page on the site (/customer/account/login/?context=checkout)

This is working as expected on Chrome and Edge.

**Comment by YevSent** [comment] 2016-12-26 16:19
Hi @devonto,  we cannot reproduce this issue.

Tested on Magento 2.1.3, Firefox 50.1.0.

Please, specify more details: debug.log, error log from browser console, etc.

**Comment by alena-marchenko** [comment] 2017-01-19 14:40
HI @devonto 

We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue.

**Closed as completed by alena-marchenko** 2017-01-19 14:40 UTC
Labels: bug report, Progress: needs update, Component: Payment

**Comment by thangasujithas** [comment] 2020-01-23 10:34
The same problem exists for me too. When clicking on the "PayPal Checkout" button from the mini cart, It redirects me to customer login but when i am a customer it redirects to the paypal login page

**Comment by harrigo** [comment] 2021-03-19 16:36
I have also just noticed this, not sure how it has happened seems to worked 100s of times in tests and now i'm suddenly getting exactly this in chrome which has been tested previously stops if go incognito and doesn't happen in any other browser. Ever find out anything about this?
