### ISSUE TITLE
Bug: a widget condition is dropped when the widget editor is opened

### ISSUE THREAD

**Issue by dmitry-fedyuk** [magento/magento2#2360] opened 2015-11-13 10:42 UTC
https://mage2.pro/t/181

**Comment by shiftedreality** [comment] 2016-01-14 16:12
Internal ticket MAGETWO-47932 was created for this issue

**Comment by magento-engcom-team** [comment] 2017-10-13 07:19
@dmitry-fedyuk, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed by magento-engcom-team** 2017-10-13 07:19 UTC
Labels: acknowledged, bug report, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in develop, Frontend, G1 Failed, G3 Passed
