### ISSUE TITLE
Magento 2.4.2-p1 | MySQL doesn't yet support drop existing primary key without adding a new primary key

### ISSUE THREAD

**Issue by TheRealHunzik** [magento/magento2#38114] opened 2023-10-24 06:06 UTC
### Preconditions and environment

- Magento 2.4.2-p1
- PHP 7.4
- Mysql  8.0
- composer 2
- Docker images running on Kubernetes 

### Steps to reproduce

1. Pull latest Code Instance
2. run composer install
3. run setup:upgrade

### Expected result

Setup upgrade should run succesfully

### Actual result

SQLSTATE[42000]: Syntax error or access violation: 1235 This version of MySQL doesn't yet support 'existing primary key drop without adding a new primary key. In @@sql_generate_invisible_primary_key=ON mode table should have a primary key. Please add a new primary key to be able to drop existing primary key.', query was: ALTER TABLE `widget_instance_page_layout` DEFAULT CHARSET='utf8', DEFAULT COLLATE='utf8_general_ci'

### Additional information

we have same architecture and replica on our UAT which is working fine

also we took a latest DUMP and same code on UAT which is also working fine

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-31 10:48
Hi @TheRealHunzik,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Pull latest Code Instance
- run composer install
- run setup:upgrade




<img width="802" alt="Screenshot 2023-10-31 at 12 32 52 PM" src="https://github.com/magento/magento2/assets/51680745/f67563ad-307f-49ee-8e27-2f80ddf15889">



We have pulled Latest Code instance and Setup Upgrade was done Successfully.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-14 06:03
Hi @TheRealHunzik,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38114#issuecomment-1786967323 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-20 06:03
Hi @TheRealHunzik,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-20 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.2-p1
