### ISSUE TITLE
Unable to checkout using Braintree PayPal and Virtual product

### ISSUE THREAD

**Issue by sebi-p** [magento/magento2#25906] opened 2019-12-04 18:00 UTC
### Preconditions (*)
1. Clean install of Magento 2.3.3
2. PHP 7.2
3. Braintree PayPal enabled

### Steps to reproduce (*)
1. Create a Virtual Product
2. Enable Braintree PayPal (any environment, Sandbox or Production)
![bS1](https://user-images.githubusercontent.com/51681435/70244322-ded36180-177c-11ea-84d4-9e1b9dc64edc.png)
3. Add virtual product to cart
4. Start the **guest** checkout using the normal Magento2 checkout (https://www.magento2.dev/index.php/checkout/) and **not** the PayPal quick checkout which redirects to https://www.magento2.dev/index.php/braintree/paypal/review/
5. Select the Braintree PayPal payment method
6. Login to PayPal by clicking the "Pay with PayPal" checkout button
7. Click "Place Order"

### Expected result (*)
1. Billing address is fetched from the logged in PayPal account
2. Order successfully placed 

### Actual result (*)
1. "Place Order" fails with the following error:
![image](https://user-images.githubusercontent.com/11634722/70167209-e6d4c800-16ce-11ea-8752-868942f5ac03.png)
2. The API request to /index.php/rest/default/V1/guest-carts/***/payment-information fails with the following log:
`<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\Braintree\Model\Paypal\OrderCancellationService::execute() must be of the type string, null given, called in /magento2/vendor/magento/module-braintree/Plugin/OrderCancellation.php on line 81 and defined in /magento2/vendor/magento/module-braintree/Model/Paypal/OrderCancellationService.php:47
Stack trace:
#0 /magento2/vendor/magento/module-braintree/Plugin/OrderCancellation.php(81): Magento\Braintree\Model\Paypal\OrderCancellationService-&gt;execute(NULL)
#1 /magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Braintree\Plugin\OrderCancellation-&gt;aroundPlaceOrder(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), '2', Object(Magento\Quote\Model\Quote\Payment\Interceptor))
#2 /magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor-&gt;Magento\Framework\I in <b>/magento2/vendor/magento/module-braintree/Model/Paypal/OrderCancellationService.php</b> on line <b>47</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/***"}]}}`
3. The var/report/api/*** contains:
`Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Braintree\\Model\\Paypal\\OrderCancellationService::execute() must be of the type string, null given`

### Additional information
1. I've debugged the file module-braintree/Plugin/OrderCancellation.php and the exception thrown is this:
`Please check the billing address information. "firstname" is required. Enter and try again. "lastname" is required. Enter and try again. "street" is required. Enter and try again. "city" is required. Enter and try again. "telephone" is required. Enter and try again. "postcode" is required. Enter and try again. "countryId" is required. Enter and try again. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Please check the billing address information. \"firstname\" is required. Enter and try again. \"lastname\" is required. Enter and try again. \"street\" is required. Enter and try again. \"city\" is required. Enter and try again. \"telephone\" is required. Enter and try again. \"postcode\" is required. Enter and try again. \"countryId\" is required. Enter and try again. at /magento2/vendor/magento/module-quote/Model/QuoteValidator.php:107)"}`
2. The PayPal quick checkout mentioned in "Steps to reproduce" step 4 (https://www.magento2.dev/index.php/braintree/paypal/review/) does not fail and the order is placed successfully
3. The Magento2 default PayPal Express payment method (**not** the Braintree version) does not fail and the order is placed successfully
4. The same errors appear if "PayPal through Braintree" is not enabled (step 5) and go to 7 step.

**Comment by sebi-p** [comment] 2019-12-04 21:51
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-04 21:51
Hi @sebi-p. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-04 21:52
Hi @sebi-p, here is your [Magento instance](https://i-25906-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25906-2-3-develop.instances.magento-community.engineering/admin](https://i-25906-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sebi-p** [comment] 2019-12-04 22:06
I cannot reproduce the issue on 2.3-develop.
Is there a specific PR that addressed this?

**Comment by magento-engcom-team** [comment] 2019-12-05 14:45
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29445` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajithkumar-maragathavel** [comment] 2019-12-10 09:42
@magento give me 2.2 instance

**Comment by ajithkumar-maragathavel** [comment] 2019-12-11 15:04
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-11 15:04
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-11 15:05
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-25906-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25906-2-4-develop.instances.magento-community.engineering/admin](https://i-25906-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajithkumar-maragathavel** [comment] 2019-12-11 18:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-11 18:46
Hi @ajithkumar-maragathavel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-11 18:46
Hi @ajithkumar-maragathavel, here is your [Magento instance](https://i-25906-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25906-2-4-develop.instances.magento-community.engineering/admin](https://i-25906-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ajithkumar-maragathavel** [comment] 2019-12-11 19:14
Closing this issue, since It is not reproducible in 2.4-develop branch.
I can able to place order using Paypal through Braintree using a Virtual product.

I have attached screenshot for reference
![SS-1](https://user-images.githubusercontent.com/47966038/70652254-53743780-1c78-11ea-8c29-99e1f33bb5ba.png)
![SS-2](https://user-images.githubusercontent.com/47966038/70652285-5ec76300-1c78-11ea-8894-5fbe48737611.png)

**Closed as completed** 2019-12-11 19:14 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Braintree, Partner: Ziffity, Fixed in 2.4.x

**Comment by chris-pook** [comment] 2020-04-20 12:37
If anyone is looking for the cause of this issue in 2.3.3 or below, I believe the fix referred to above is an unchecked variable as fixed here:

https://github.com/magento/magento2/commit/18a83d6de6d850a732d16aed2c95fb99dbcd6702#diff-123aaca295c4956e7dc6076a2bac45d7L75-R75

**Comment by chris-pook** [comment] 2022-05-10 10:41
@magento-engcom-team @ajithkumar-maragathavel Hi, I'm pretty sure the fix applied to the magento/module-braintree extension for this has not made it to the paypal/module-braintree-core extension now packaged in Magento 2.4.

Note the code in Magento/Braintree (no longer available in 2.4.x) is different to that in paypal/module-braintree-core:

https://github.com/magento/magento2/blob/2.3.7/app/code/Magento/Braintree/Plugin/OrderCancellation.php#L78
![image](https://user-images.githubusercontent.com/4628660/167610372-7a46ae49-01b7-49ff-9471-f9f94950d25a.png)

![image](https://user-images.githubusercontent.com/4628660/167610488-a70a95de-1031-4bf6-b595-9d5f633f7574.png)

I'd say this needs reopening.

**Comment by ClintTec** [comment] 2022-05-23 17:25
> @magento-engcom-team @ajithkumar-maragathavel Hi, I'm pretty sure the fix applied to the magento/module-braintree extension for this has not made it to the paypal/module-braintree-core extension now packaged in Magento 2.4.
> 
> Note the code in Magento/Braintree (no longer available in 2.4.x) is different to that in paypal/module-braintree-core:
> 
> https://github.com/magento/magento2/blob/2.3.7/app/code/Magento/Braintree/Plugin/OrderCancellation.php#L78 ![image](https://user-images.githubusercontent.com/4628660/167610372-7a46ae49-01b7-49ff-9471-f9f94950d25a.png)
> 
> ![image](https://user-images.githubusercontent.com/4628660/167610488-a70a95de-1031-4bf6-b595-9d5f633f7574.png)
> 
> I'd say this needs reopening.

Agreed.

TypeError: Argument 1 passed to PayPal\Braintree\Model\Paypal\OrderCancellationService::execute() must be of the type string, null given, called in \vendor\paypal\module-braintree-core\Plugin\OrderCancellation.php on line 75 and defined in \vendor\paypal\module-braintree-core\Model\Paypal\OrderCancellationService.php:47
Stack trace:
#0 \vendor\paypal\module-braintree-core\Plugin\OrderCancellation.php(75): PayPal\Braintree\Model\Paypal\OrderCancellationService->execute(NULL)

**Comment by chris-pook** [comment] 2022-05-30 08:33
Hi @magento-engcom-team, please can this be reopened?

**Comment by n2diving-dgx** [comment] 2022-06-02 09:36
Yes, issue needs to be re-opened

My M2.4.4 (php7.4) system is logging the error as well, although I can't figure out the condition required to trigger the error:
 
main.CRITICAL: TypeError: Argument 1 passed to PayPal\Braintree\Model\Paypal\OrderCancellationService::execute() must be of the type string, null given, called in /vendor/paypal/module-braintree-core/Plugin/OrderCancellation.php on line 75 and defined in /vendor/paypal/module-braintree-core/Model/Paypal/OrderCancellationService.php:47

**Comment by florinm8** [comment] 2022-12-14 12:58
I'm having this issue on m2.4.5 if the $quote->getHasErrors() is true. Instead of throwing the quote validation exception and receive the message in frontend the type error is raised because of $incrementId is null

**Comment by xaevik** [comment] 2023-01-26 13:36
We are also experiencing this on 2.4.5 EE during QA testing, the bug was never resolved in the enterprise edition. We're making a composer patch to resolve it.

![image](https://user-images.githubusercontent.com/62903002/214848865-7dd45ef0-bc1f-4b20-8f44-79cfcef4ecd2.png)

**Comment by mpchadwick** [comment] 2025-12-26 17:37
This issue is occurring on 2.4.6-p13. In all cases it looks to be with GooglePay orders.
