### ISSUE TITLE
Specify the table when adding field when applySelectionOnTargetProvider() in  Magento\Ui\Component\MassAction\Filter.php

### ISSUE THREAD

**Issue by adaudenthun** [magento/magento2#17863] opened 2018-08-30 08:17 UTC
Hi!
About the MassAction in admin Grid. When have a custom grid and apply custom \Magento\Sales\Model\ResourceModel\Order\Grid\Collection and override _initSelect for add join group etc ...
So, when we join some tables, we have the error 'ambiguous column name'.

### Preconditions
Since Magento version 2.2.0 to now.

1. Have a custom collection grid like :
`
class Collection extends \Magento\Sales\Model\ResourceModel\Order\Grid\Collection
{
    protected function _initSelect()
    {
        parent::_initSelect();
        $this->getSelect()
            ->join('XXXXXX')
           ->group("XXXXX");
        return $this;
    }
}
` 

### Steps to reproduce
When have this custom grid :
1. Try to apply a mass action

### Expected result

1. Do the mass action

### Actual result

1.  error 'ambiguous column name' : 
"SQLSTATE[23000] ..... Column 'entity_id' in where clause is anbiguous ........ SELECT ... JOIN .... WHERE ... AND ('entity_id' IN('X') "

Normaly we should have in the where clause :  AND (' **main_table.** entity_id' IN('X') )

To fix this, i propose to add 'main_table.' here : Magento\Ui\Component\MassAction\Filter.php funtion applySelectionOnTargetProvider() replace '->setField($dataProvider->getPrimaryFieldName())' to ->setField('main_table.'.$dataProvider->getPrimaryFieldName())

**Comment by magento-engcom-team** [comment] 2018-08-30 08:18
Hi @adaudenthun. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@adaudenthun do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adaudenthun** [comment] 2018-08-30 08:36
I can do a pull request for fix it ;)

**Comment by engcom-Charlie** [comment] 2019-12-31 09:56
Hello @adaudenthun 

We are closing this issue as not relevant.

The issue has been fixed in magento/magento2#18658 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [53a06a9ba12c0f4be0b28fdf6f9cf45540cebae6](https://github.com/magento/magento2/commit/53a06a9ba12c0f4be0b28fdf6f9cf45540cebae6)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest Magento 2.4-develop branch. 

Thank you for collaboration

**Closed as completed by engcom-Charlie** 2019-12-31 09:56 UTC
Labels: Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Ui
