### ISSUE TITLE
Minicart thumbnail image showing wrong size in frontend which is half of image size in XML file

### ISSUE THREAD

**Issue by csvikram44** [magento/magento2#35275] opened 2022-04-07 06:30 UTC
After upgrading Magento version from 2.3.5-p1 to 2.4.3-p1, I am facing the problem of minicart thumbnail size. I found that in the view.xml file, the width and height of half the size set for the minicart thumbnail shows in the frontend minicart. 

**Note:** It works fine in my old Magento version that the size which is in view.xml file shows the width and height of the size in the frontend.

### Preconditions (*)
1. Magento version 2.4.3-p1

### Steps to reproduce (*)

**Important:** By the way, this is the default issue in both Blank and Luma themes.

1. Create any one product and upload the thumbnail image of the product in it.
1. Go to Front End and add product to cart.
1. You will see thumbnail images of the product in the minicart.
1. If you inspect it, the image loads the same size as it would in **view.xml* but in the upper HTML tag *<span class="product-image-container">** takes half width and height attribute and due to that minicart design is breaking and showing small thumbnail image.
1. For example, if you enter the 150x150 width and height in the **view.xml** file, then it will show 75x75 px inline width and height attributes in the upper <span> HTML tag.
`<image id="mini*cart_product*thumbnail" type="thumbnail">
                <width>75</width>
                <height>75</height>
            </image>`

### Expected result (*)

1. Prodcut item width and height of the <span> tag should be 150px shown which is given in the **view.xml** file
![](https://user-images.githubusercontent.com/16976794/162133886-d6b743c0-772d-41bb-b25b-12c127d5f222.png)

![](https://user-images.githubusercontent.com/16976794/162133909-530b515f-6e00-42b3-9537-cb58141d1bea.png)

### Actual result (*)

1. It is showing 75x75 px width & height in <span> tag. **See above screenshots**

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < > Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- < > Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by csvikram44** [comment] 2022-04-07 08:02
@magento give me a 2.4-develop instance.

**Comment by csvikram44** [comment] 2022-04-07 08:25
@magento When will I get the update from your side?

**Comment by csvikram44** [comment] 2022-04-07 08:43
@magento give me a 2.4-develop instance.

**Comment by ihor-sviziev** [comment] 2022-04-07 13:08
Hi @csvikram44,
That was a fix for the issue https://github.com/magento/magento2/issues/24735, so I believe everything is right there.

**Comment by csvikram44** [comment] 2022-04-07 13:49
@ihor-sviziev My problem is not with the blurry image. In MiniCart, a thumbnail image of half the size of the image entered in the XML file appears in the MiniCart.

**File path:** 
`app/design/frontend/{Vendor}/{theme-name}/etc/view.xml`

`<image id="mini_cart_product_thumbnail" type="thumbnail">
                <width>75</width>
                <height>75</height>
            </image>`

**See below screenshot**, I added 75px width & height for **mini_cart_product_thumbnail** in the **view.xml** file but it shows 37.5px width and due to that it looks small. Instead of showing 37.5px, It should be the 75px width that is entered in the **view.xml** file.

![image](https://user-images.githubusercontent.com/16976794/162213884-6811abf2-732c-4ae8-817a-3c8476f71aa0.png)

**Comment by csvikram44** [comment] 2022-04-07 14:03
@ihor-sviziev But why do I need to load a double-size thumbnail image? If I add 10 items to the mini cart then the page load will increase because it loads twice the size of images which is not correct. Also, it was running fine in the old version.

Is there any other reason behind doubling the image size?
**Note:** A developer will enter the size in view.xml that he wants to display on the frontend and not double that.

**Comment by csvikram44** [comment] 2022-04-07 14:07
@ihor-sviziev I hope you understand my point properly. In my view, this is an issue and because of this, all developers will have to face this problem whenever they upgrade from the lower to the latest Magento version.

**Comment by csvikram44** [comment] 2022-04-07 16:07
@ihor-sviziev Thanks for the update.

I checked by uploading different images, and none of the images are getting blurred. But there are a lot of chances of loading issues increasing in speed on mobile when multiple product items are added. Please think about it one more time and update me.

**Comment by engcom-Delta** [comment] 2022-04-08 17:19
Hi @csvikram44 ,
Thank you for reply and we tried to reproduce the issue on Magento 2.4 Develop and found that issue is reproducible.
Product item width and height of the tag is not same on Minicart when compared to view.xml.

View.xml
=======
<img width="1440" alt="Screenshot 2022-04-08 at 10 26 24 PM" src="https://user-images.githubusercontent.com/51681379/162490449-16940fab-7b76-45e8-b0e5-9935e104bc46.png">

**in Mini cart & Shipping page:**
<img width="1440" alt="Screenshot 2022-04-08 at 10 22 44 PM" src="https://user-images.githubusercontent.com/51681379/162490567-6a291341-97af-42be-8bc6-60e0ddd57111.png">
<img width="1440" alt="Screenshot 2022-04-08 at 10 22 44 PM" src="https://user-images.githubusercontent.com/51681379/162490613-05b41646-8428-4d72-b565-d4796200df2c.png">

Hence , issue has been confirmed.

**Comment by olegpola** [comment] 2022-05-06 13:01
https://github.com/magento I am working on this

**Comment by olegpola** [comment] 2022-05-07 09:01
@magento I am working on this

**Comment by Viper9x** [comment] 2022-09-20 11:29
Hi @csvikram44 
This issue is invalid.
In the changes in PR [24743](https://github.com/magento/magento2/pull/24743/) @dmdanilchenko changed the `width` (and `height`) in both HTML and XML files:
app/code/Magento/Catalog/view/frontend/web/template/product/image_with_borders.html
app/design/frontend/Magento/blank/etc/view.xml
app/design/frontend/Magento/luma/etc/view.xml
You can take a look at PR's changed files here: https://github.com/magento/magento2/pull/24743/files

You guys had this issue because you declared width and height for`<image id="mini_cart_product_thumbnail" type="thumbnail">` in your custom theme. But with the new change in PR [24743](https://github.com/magento/magento2/pull/24743/), the width and height size should be double in <your theme dir>/etc/view.xml.

Conclusion: The correct solution is double the size of height and width for `<image id="mini_cart_product_thumbnail" type="thumbnail">` in <your theme dir>/etc/view.xml, not changing any from app/code/Magento/Catalog/view/frontend/web/template/product/image_with_borders.html.

**Comment by Rickertje** [comment] 2023-03-08 13:23
Can somebody comment on the status of this issue? Some say this is a valid issue and others say it is not. Imho the need to double the size in view.xml just to get back to how things were before seems a somewhat strange solution to the issue description.

**Comment by Viper9x** [comment] 2023-03-08 13:29
@Rickertje This issue should be closed. The need to double the size in view.xml is for fixing issue #24735. If you are still confused, please read my comment above (I've just updated it to say the change in order to fix #24735).
@engcom-Delta could you check my comment and mark this issue as closed?

**Comment by ihor-sviziev** [comment] 2023-03-10 10:45
Hi @csvikram44,
I do agree with @Viper9x, the image should be 2x sized.
I'm closing this issue as not relevant.

**Closed as not planned by ihor-sviziev** 2023-03-10 10:45 UTC
Labels: Issue: Confirmed, non-issue, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Cart & Checkout
