### ISSUE TITLE
Internal Server Error in PUT /pub/rest/default/V1/bundle-products/options/

### ISSUE THREAD

**Issue by mlf20** [magento/magento2#35921] opened 2022-08-12 09:03 UTC
### Preconditions and environment

- Magento version: 2.4

### Steps to reproduce

1. Retrieve  auth token from the admin endpoint /V1/integration/admin/token
2. Request endpoint:
``` 
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer' <AUTH TOKEN> -d '{}' -X PUT http://<MAGENTO_URL>/pub/rest/default/V1/bundle-products/options/DZ.pdf?option=
```

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code as an error is thrown as getProductFromLocalCache() takes a null argument which is not handled. 

### Additional information

output of var/log/system.log:
```
[2022-08-01T10:37:43.276366+00:00] main.CRITICAL: TypeError: Magento\Catalog\Model\ProductRepository::getProductFromLocalCache(): Argument #1 ($sku) must be of type string, null given, called in /bitnami/magento/vendor/magento/module-catalog/Model/ProductRepository.php on line 284 and defined in /bitnami/magento/vendor/magento/module-catalog/Model/ProductRepository.php:813
Stack trace:
#0 /bitnami/magento/vendor/magento/module-catalog/Model/ProductRepository.php(284): Magento\Catalog\Model\ProductRepository->getProductFromLocalCache()
#1 /bitnami/magento/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(23): Magento\Catalog\Model\ProductRepository->get()
#2 /bitnami/magento/vendor/magento/module-bundle/Model/OptionManagement.php(41): Magento\Catalog\Model\ProductRepository\Interceptor->get()
#3 [internal function]: Magento\Bundle\Model\OptionManagement->save()
#4 /bitnami/magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#5 /bitnami/magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#6 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#7 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#8 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#9 /bitnami/magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#10 /bitnami/magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#11 /bitnami/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#12 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#13 /bitnami/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#14 {main} [] []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mlf20** [comment] 2022-08-12 09:03
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-08-12 12:05
Hi @mlf20 ,
Thank you for raising an issue , We tried to reproduce with provided steps, in fact we are not able to reproduce the error after running endpoint on Magento 2.4 develop. Here is the screenshot for reference.

<img width="989" alt="Screenshot 2022-08-12 at 5 32 19 PM" src="https://user-images.githubusercontent.com/51681379/184350362-6a578e23-c376-4f1f-89ac-3ba526df0fd6.png">

Please review and confirm the steps.

Note : Kindly request to review issue description and steps.

**Comment by mlf20** [comment] 2022-08-12 12:14
Hi @engcom-Delta,

Thanks for looking into this, please note that the endpoint with the error is /pub/rest/default/V1/bundle-products/options/{optionId}. The request should be formed as:
`
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer' <AUTH TOKEN> -d '{}' -X PUT http://<MAGENTO_URL>/pub/rest/default/V1/bundle-products/options/DZ.pdf?option=
`

To reproduce this:
1. Retrieve the admin token from the relevant endpoint
2. Then use that token to access the /pub/rest/default/V1/bundle-products/options/{optionId} endpoint.

I was able to confirm this on the 2.4 develop instance provided by Magento Deployment Service.

I hope this makes sense.

**Comment by engcom-Delta** [comment] 2022-08-23 13:47
Hi @mlf20 ,
Thank you for providing the inputs , we tried to replicate on magento 2.4 instance but we are not facing the same error. 
it would be great help what was your request body that you were trying.

in my local i have tried below endpoint and request body.

Endpoint[PUT]: http://local.magento.com/rest/default/V1/bundle-products/options/0

Body :
{
  "option": {
    "option_id": 0,
    "title": "option1",
    "required": true,
    "type": "Multiple Select",
    "position": 0,
    "sku": "Bundle1",
    "product_links": [
      {
        "id": "0",
        "sku": "MB-2401",
        "option_id": 0,
        "qty": 1,
        "position": 0,
        "is_default": true,
        "price": 34,
        "price_type": null,
        "can_change_quantity": 0,
        "extension_attributes": {}
      }
    ],
    "extension_attributes": {}
  }
}

Response: 
<img width="873" alt="Screenshot 2022-08-23 at 7 15 58 PM" src="https://user-images.githubusercontent.com/51681379/186174661-68549bbb-6533-4b01-8e86-5ae98ec084ec.png">

This is the data issue i believe.

**Comment by mlf20** [comment] 2022-08-23 14:04
Hi @engcom-Delta,

I have gone over my logs and the payload in thebody should be '{}' 

This reproduces the issue on a 2.4 develop instance as shown below:

<img width="854" alt="Screenshot 2022-08-23 at 15 01 24" src="https://user-images.githubusercontent.com/83755999/186178924-02e6724f-387b-408c-a305-96e69cfc6842.png">

**Comment by engcom-Delta** [comment] 2022-08-25 13:57
Hi @mlf20 ,
Thank for your quick turnaround. We tried again magento 2.4 delovelop instance, it works fine .
Please find below screenshot  and video for reference.

<img width="1013" alt="Screenshot 2022-08-25 at 5 51 36 PM" src="https://user-images.githubusercontent.com/51681379/186683577-d2ec312f-4fd9-4197-a6e5-f9f3fa979399.png">

https://www.loom.com/share/30b8d9ac9ce34cdab74d9b9b27efebb7

**Comment by mlf20** [comment] 2022-08-26 10:55
Hi @engcom-Delta,

It appears that you have used a request body that includes all the correct parameters. However, the error is triggered when setting the entire body to be empty json, as I have shown in the above request body this should be simply: {}. This will reproduce the error. 

Many thanks

**Comment by engcom-Delta** [comment] 2022-08-29 10:08
Hi @mlf20 ,
Thank you for the update , We have tried with empty json :{} in entire body and triggered ,we got "field name is required. Enter and try again" error. please review the screenshot.

<img width="995" alt="Screenshot 2022-08-29 at 3 32 52 PM" src="https://user-images.githubusercontent.com/51681379/187177888-cec44e73-02cf-4fef-a480-1d9a70cf3972.png">

**Comment by engcom-Delta** [comment] 2022-09-12 12:22
Hi @mlf20 ,

We have noticed that, this issue has not been updated for a period of 14 Days.Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2022-09-12 12:22 UTC
Labels: Issue: needs update
