### ISSUE TITLE
Alignment of terms & conditions checkbox

### ISSUE THREAD

**Issue by torhoehn** [magento/magento2#25801] opened 2019-11-28 14:18 UTC
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Create and activate Terms & Conditions under Stores -> Settings -> Terms and Conditions with longer checkbox text
2. Enable Terms & Conditions under Stores -> Configuration -> Sales -> Checkout -> Checkout Options
3. On a mobile device go to the second step of the Checkout

### Expected result (*)

1. Checkbox and text should be aligned correctly

### Actual result (*)

1. Checkbox and text isn't aligned correctly. 
<img width="298" alt="Screenshot 2019-11-28 at 15 12 17" src="https://user-images.githubusercontent.com/1945725/69813301-33f9fb00-11f2-11ea-8918-7047ac9b83d5.png">

**Comment by torhoehn** [comment] 2019-11-28 14:19
#cd-cologne

**Comment by torhoehn** [comment] 2019-11-28 14:20
#cd-cologne19

**Comment by krishprakash** [comment] 2019-11-29 05:02
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-29 05:03
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-29 05:03
Hi @krishprakash, here is your [Magento instance](https://i-25801-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25801-2-3-develop.instances.magento-community.engineering/admin](https://i-25801-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-29 05:11
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29262` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-06-25 21:19
Looks like as 
Duplicate of #24060

**Comment by sdzhepa** [comment] 2020-07-30 17:27
Closed as duplicate of https://github.com/magento/magento2/issues/24060

**Closed as completed by sdzhepa** 2020-07-30 17:27 UTC
Labels: Issue: Ready for Work, Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Event: cd-cologne19
