### ISSUE TITLE
about Downloadable Product Zero Subtotal Checkout Issue...

### ISSUE THREAD

**Issue by mugua** [magento/magento2#25177] opened 2019-10-21 06:02 UTC
### Preconditions (*)

1. Magento 2.3.3 & 2.3-develop
2. PHP 7.3.10

### Steps to reproduce (*)

1. Create a Zero Downloadable Product, set it can be download “INVOICED”
2. set Zero Subtotal Checkout Order status Processing and Auto INVOICE

### Expected result (*)

1. User Order status should be "Complete"
2. User Downloadable should be "Aviable"

### Actual result (*)

1. User Order status is "Closed"
2. User Downloadable is "Pending"

**Comment by mugua** [comment] 2019-10-21 06:08
1: User placed order sucessed,  and choose the Zero Subtotal Checkout payment, It should be complete, why I got a Closed status?
2: the Downloadable product has invoice, why it still stay in Pending status?

**Comment by mugua** [comment] 2019-10-25 04:23
any feedback?

**Comment by magento-engcom-team** [comment] 2019-11-18 08:17
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23220` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by plastikschnitzer** [comment] 2020-04-04 01:22
I ran into the same issue on Magento 2.3.4
Any hotfix available?

**Comment by plastikschnitzer** [comment] 2020-04-05 21:11
I could reproduce the issue on a vanilla Magento 2.4-dev instance here: https://github.com/magento/magento2/issues/27590#issuecomment-609459330

**Comment by trunglv** [comment] 2020-04-27 11:33
Quick fixing : 
- Reference Class:  Magento\Sales\Model\ResourceModel\Order\Handler\State
```
<?xml version="1.0" encoding="UTF-8"?>
<config>
    <preference for="Magento\Sales\Model\ResourceModel\Order\Handler\State" type="FixBugs\VirtualOrderStatus\Sales\Model\ResourceModel\Order\Handler\State" />
</config>

```
-- Adjust : If grand-total > 0 so don't set order status to be CLOSED
```
<?php

namespace FixBugs\VirtualOrderStatus\Sales\Model\ResourceModel\Order\Handler;

use Magento\Sales\Model\Order;

class State extends \Magento\Sales\Model\ResourceModel\Order\Handler\State {
    
    public function check(Order $order)
    {
        
        $currentState = $order->getState();
        if ($currentState == Order::STATE_NEW && $order->getIsInProcess()) {
            $order->setState(Order::STATE_PROCESSING)
                ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_PROCESSING));
            $currentState = Order::STATE_PROCESSING;
        }

        if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
            if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
                && !$order->canCreditmemo()
                && !$order->canShip()
                && $order->getGrandTotal() > 0        
            ) {
                $order->setState(Order::STATE_CLOSED)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));
                
            } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip()) {
                $order->setState(Order::STATE_COMPLETE)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
            }
        }
        return $this;
    }
}
```

**Comment by j-robin-hunter** [comment] 2020-05-08 06:17
I also have this same issue on 2.3.4

**Comment by mugua** [comment] 2020-05-10 15:43
> Quick fixing :
> 
> * Reference Class:  Magento\Sales\Model\ResourceModel\Order\Handler\State
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <config>
>     <preference for="Magento\Sales\Model\ResourceModel\Order\Handler\State" type="FixBugs\VirtualOrderStatus\Sales\Model\ResourceModel\Order\Handler\State" />
> </config>
> ```
> 
> -- Adjust : If grand-total > 0 so don't set order status to be CLOSED
> 
> ```
> <?php
> 
> namespace FixBugs\VirtualOrderStatus\Sales\Model\ResourceModel\Order\Handler;
> 
> use Magento\Sales\Model\Order;
> 
> class State extends \Magento\Sales\Model\ResourceModel\Order\Handler\State {
>     
>     public function check(Order $order)
>     {
>         
>         $currentState = $order->getState();
>         if ($currentState == Order::STATE_NEW && $order->getIsInProcess()) {
>             $order->setState(Order::STATE_PROCESSING)
>                 ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_PROCESSING));
>             $currentState = Order::STATE_PROCESSING;
>         }
> 
>         if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
>             if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
>                 && !$order->canCreditmemo()
>                 && !$order->canShip()
>                 && $order->getGrandTotal() > 0        
>             ) {
>                 $order->setState(Order::STATE_CLOSED)
>                     ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));
>                 
>             } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip()) {
>                 $order->setState(Order::STATE_COMPLETE)
>                     ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
>             }
>         }
>         return $this;
>     }
> }
> ```

Thanks for your fix, it is fine for me now, the magento official still haven't give solution to solve this issue,
@magento-engcom-team, any better fix method for this issue ?

**Comment by mugua** [comment] 2020-05-10 15:46
> I ran into the same issue on Magento 2.3.4
> Any hotfix available?
> 
> This issue cancelled my Magento 2 migration for the moment, so any quick fix would be highly appreciated!

@trunglv  his fix is well for me. you can try it...

**Comment by mugua** [comment] 2020-05-10 15:48
> I also have this same issue on 2.3.4

try @trunglv  method...

**Comment by mugua** [comment] 2020-05-10 16:32
@truntrun just check the code you offer, it means if grand total>0，the po status shoud be close. If grand total <=0, the po status will show complete.
does this influence other POs grand total >0?

**Comment by j-robin-hunter** [comment] 2020-05-11 03:52
This fix will not work if you are wanting to create a 'free' virtual product, for example the opportunity to download a demo or test product

**Comment by trunglv** [comment] 2020-05-11 04:27
Hi @j-robin-hunter , @mugua 
My use case for my fix: A customer purchases a free downloadable product but he can't download a file due to Order Status is Closed.  
It depends on your use cases, so maybe you will make different changes by rewriting  Magento\Sales\Model\ResourceModel\Order\Handler\State. ....
Anyway, another solution, maybe better,  is to check whether an order is "Zero Subtotal Checkout Payment", If yes, we will prevent order status to be CLODED 
```
if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
            if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
                && !$order->canCreditmemo()
                && !$order->canShip()
                && $order->getPayment()->getMethod() != 'free'      
            ) {
                $order->setState(Order::STATE_CLOSED)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));
                
            } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip()) {
                $order->setState(Order::STATE_COMPLETE)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
            }
        }
```
@j-robin-hunter : I think you can set configuration values of Zero Subtotal Checkout payment : 
- New Order Status => Processing 
- Automatically Invoice All Items => Yes  
Maybe it will help.

**Comment by j-robin-hunter** [comment] 2020-05-11 04:43
This fix would work for our use case. However, I do wonder if this state check is a good idea as it clearly able to 'break' the documented order process workflow which would only allow the status to be closed if a refund is issued. This check clearly makes decisions to close the order on whether an item can be shipped. 

For completeness, we do have the order status set to processing and automatically invoice all items so provided the order status is not set to closed this ought to allow the workflow to continue.

**Comment by mugua** [comment] 2020-05-11 05:28
@trunglv @j-robin-hunter  If a virtual product or a downloadable product's price is >0 , they both don't need Creditmemo & Ship, if suing the code using "&& $order->getPayment()->getMethod() != 'free'". it still goto closed status again... so i think "&& $order->getGrandTotal() < 0" is better than the last fix method, BTW, it is still the hotfix now, we can wait for the magento official fix method soon...

**Comment by plastikschnitzer** [comment] 2020-05-24 14:55
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-24 14:55
Hi @plastikschnitzer. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-24 14:56
Hi @plastikschnitzer, here is your [Magento instance](https://i-25177-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25177-2-4-develop.instances.magento-community.engineering/admin_6a5d](https://i-25177-2-4-develop.instances.magento-community.engineering/admin_6a5d)
Login: `fed670cf` Password: `d8a2e579f19c`
Instance will be terminated in up to 3 hours.

**Comment by plastikschnitzer** [comment] 2020-05-24 15:20
Hi @magento I can confirm the issue still exists on the latest 2-4-dev instance.

**Comment by j-robin-hunter** [comment] 2020-06-02 06:01
The code in $order->canInvoice() also appears to be broken for a bundled product, also resulting in the order becoming CLOSED when it is shipped.

Within $order->canInvoice() the following code will not return true 

```php
foreach ($this->getAllItems() as $item) {
    if ($item->getQtyToInvoice() > 0 && !$item->getLockedDoInvoice()) {
        return true;
    }
}
return false;
```
This means that the check function in the State class will also close the order. Again this is wrong behaviour caused by the same check and the same code.

**Comment by j-robin-hunter** [comment] 2020-06-02 07:25
In Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save controller the shipment is 'registered' and all items are marked as shipped. This results in the check() function in Magento\Sales\Model\ResourceModel\Order\Handler\State checking the canShip() status while the order is still in the PROCESSING state.

Since all items are now marked as shipped the order cannot now be shipped and test results in the order status being marked as CLOSED

**Comment by KineoMichaelT** [comment] 2020-06-24 06:37
Still an issue in 2-5, so adding the details from my investigation to see if it's helpful.

@j-robin-hunter The check location for the hotfix should resolve the issue, but it's the opposite of your concern.  It's the documented workflow that is currently broken.  Ultimately, the error is coming from Magento/Sales/Order::canCreditmemoForZeroTotal in which it determines if the amount refunded = amount paid, it must be fully refunded, not taking to account that for zero total checkouts 0=0 and isn't really refunded.  That error propagates up to the State check as $order->canCreditmemo() returns false when otherwise it should be returning true.

I don't know enough about the other implications of changing this at the source though, so trunglv's fix is the safest without a magento developer taking a look.

**Comment by maynard321** [comment] 2020-06-24 16:52
New to this, so forgive me if I'm barking up the wrong tree.
It seems that that error comes in the logic of checking **!$order->canShip()**  - this whole section is asking "is something wrong", and "it can't ship" is being thought of as "yes, something is wrong". However, the test **"isVirtual"** is included in the **canShip** testing, and while every other part of **canShip** is "something is wrong", **isVirtual** is not wrong.
So I've changed that line to **&& (!$order->canShip() && !$order->getIsVirtual())** and it seems to work:

```
if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
    if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
        && !$order->canCreditmemo()
        && (!$order->canShip() && !$order->getIsVirtual())
     ) {
        $order->setState(Order::STATE_CLOSED)
            ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));
    } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip()) {
        $order->setState(Order::STATE_COMPLETE)
            ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
    }
}
```

**Comment by curkle** [comment] 2020-09-15 04:14
```
 public function check(Order $order)
    {
        $currentState = $order->getState();
        if ($currentState == Order::STATE_NEW && $order->getIsInProcess()) {
            $order->setState(Order::STATE_PROCESSING)
                ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_PROCESSING));
            $currentState = Order::STATE_PROCESSING;
        }

        if (!$order->isCanceled() && !$order->canUnhold() && !$order->canInvoice()) {
            if (in_array($currentState, [Order::STATE_PROCESSING, Order::STATE_COMPLETE])
                && !$order->canCreditmemo()
                && !$order->canShip()
                && ($order->getGrandTotal() > 0 || $this->isFreePaymentFullyRefunded($order)) // check if it is free payment and also all refunded
            ) {
                $order->setState(Order::STATE_CLOSED)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_CLOSED));

            } elseif ($currentState === Order::STATE_PROCESSING && !$order->canShip()) {
                $order->setState(Order::STATE_COMPLETE)
                    ->setStatus($order->getConfig()->getStateDefaultStatus(Order::STATE_COMPLETE));
            }
        }
        return $this;
    }

    private function isFreePaymentFullyRefunded(Order $order)
    {
        $totalInvoicedItem = 0;
        $totalRefundItem = 0;

        foreach ($order->getItems() as $item) {
            $totalInvoicedItem += $item->getQtyInvoiced();
            $totalRefundItem  += $item->getQtyRefunded();
        }

        return $totalRefundItem > 0 && $totalRefundItem == $totalInvoicedItem;

    }
```

add function check if all item has been refund.  it should work

**Comment by magento-quality-patches** [comment] 2020-10-19 01:55
The patch solving a similar issue is available in [Magento Quality Patches](https://support.magento.com/hc/en-us/articles/360047139492) package (MQP)
 
**Patch**
MDVA-28656: Fixes the issue where if an order was placed with no payment information required (for example, with 100% discount) and an invoice was created for the order, the order status changes to Closed instead of Complete.
 
**Compatible versions**
Magento OpenSource/Commerce/Commerce Cloud 2.3.1 - 2.3.5, 2.4.0
 
:warning: We strongly recommend testing all patches in a staging or development environment before deploying to production.
 
**Applying a patch - Magento OpenSource/Commerce**
 
1. `$ composer require magento/quality-patches`
2. `$ ./vendor/bin/magento-patches apply MDVA-28656`
 
See [MQP Magento Commerce documentation](https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/mqp.html)
 
**Applying a patch - Magento Commerce Cloud**
See [MQP Magento Commerce Cloud documentation](https://devdocs.magento.com/cloud/project/project-patch.html)

**Comment by plastikschnitzer** [comment] 2021-03-12 07:56
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-05-17 07:45
Hi @mugua,

Thanks for your reporting and collaboration.

We have verified the issue in 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached screenshot.

**Steps to reproduce**

- Create a Zero Downloadable Product, set it can be download “INVOICED”
- set Zero Subtotal Checkout Order status Processing and Auto INVOICE



<img width="1435" alt="Screenshot 2024-05-17 at 13 10 31" src="https://github.com/magento/magento2/assets/51680745/feba44f5-4bbd-46b8-8201-7e10f0f015d4">


<img width="1435" alt="Screenshot 2024-05-17 at 13 11 06" src="https://github.com/magento/magento2/assets/51680745/d533a2bc-0201-4fef-ae6c-8ca0f48a6fd3">

User Order status should be "Complete" andUser Downloadable should be "Available".

Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-17 07:45 UTC
Labels: Component: Payment, Component: Checkout, Issue: Confirmed, Reproduced on 2.3.x, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Cart & Checkout
