### ISSUE TITLE
Very specific header set in main REST controller resulting in a redirection to /checkout/noroute/

### ISSUE THREAD

**Issue by MatthieuCardin** [magento/magento2#38020] opened 2023-09-28 14:55 UTC
Hello, we've found a well-hidden bug in checkout, when paying for a quote containing only virtual products gives an error.

**Steps to reproduce:**
1. Checkout a virtual quote order (Only virtual products) At this point, the only tab is the payment one. The shipping tab does not exist since there is no product to ship.
2. Obtain a payment error
3. The page displays the error, then redirects to /checkout/noroute/

**We've found the source of the problem:**

1. The place-order.js file redirects if the ajax call fails, depending on a request header:  
```
...
).fail(
    function (response) {
        errorProcessor.process(response, messageContainer);
        redirectURL = response.getResponseHeader('errorRedirectAction');
  
        if (redirectURL) {
            setTimeout(function () {
                errorProcessor.redirectTo(redirectURL);
            }, 3000);
        }
    }
...
```
4. The `Magento\Webapi\Controller\Rest` controller adds the value '#shipping' systematically. In the case of a virtual quote, the "shipping" tab does not exist. This line is questionable because it adds a header specific to checkout APIs in a context that is too general:
```
...
} catch (CouldNotSaveException $e) {
     $maskedException = $this->_errorProcessor->maskException($e);
    $this->_response->setException($maskedException);
    $this->_response->setHeader('errorRedirectAction', '#shipping'); // Should be done differently
 } 
...
``` 
5. The step-navigator.js file that manages tabs navigation does not find "#shipping" so redirects to "noroute":
```  
 if ($.inArray(hashString, this.validCodes) === -1) {
    window.location.href = window.checkoutConfig.pageNotFoundUrl;

    return false;
}
``` 

**Reference:**
https://github.com/magento/magento2/blob/c22a9db44a704b892b81746dc5f707fd87f6e5bf/app/code/Magento/Webapi/Controller/Rest.php#L206C7-L206C77

### Additional Steps to reproduce

- Enable PayPal Advance. (I have invalid PayPal credentials but as long as it throws an Exception, it should redirect).
- Add a virtual product.
- Go to checkout.
- Select Payflow Advanced.
- Enter the billing address.
- Click Continue to initial the PayPal Advance. (Receive 400 status on payment-information).
- Redirected to no route.

**Comment by engcom-Bravo** [comment] 2023-09-29 08:55
Hi @MatthieuCardin,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.

**Steps to reproduce:**


- Checkout a virtual quote order (Only virtual products) At this point, the only tab is the payment one. The shipping tab does not exist since there is no product to ship.



https://github.com/magento/magento2/assets/51680745/d36ea7f1-07a7-4368-a3f7-be3823558752





We are able to place the order successfully for the virtual product there is no payment error.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by MatthieuCardin** [comment] 2023-09-29 12:55
@engcom-Bravo I think you've misunderstood the problem. The wrong redirection to checkout/noroute happens **when there is a payment error**. For example, when a customer enters the wrong cc number. 

The call to `/V1/guest-carts/:cartId/payment-information` or `/V1/carts/mine/payment-information`, so `\Magento\Checkout\Model\PaymentInformationManagement::savePaymentInformationAndPlaceOrder` **must throw a CouldNotSaveException**

**Comment by MoT3rror** [comment] 2023-09-29 14:01
I can reproduce and it happens if the payment processor returns any exception. 

I think changing GuestPaymentInformationManagement and PaymentInformationManagement to throw `PaymentException` than `CouldNotSaveException` would solve it.

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php#L152-L161

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/Model/PaymentInformationManagement.php#L162-L171

**Comment by engcom-Hotel** [comment] 2023-10-11 10:27
Hello @MoT3rror,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch but the issue is not reproducible for us. We have tried to throw an error so that `CouldNotSaveException` occurs. 

We have only a virtual product in the cart and tried to checkout with the same. But the page is not redirecting but remains on the same checkout page with an error message as below:

![image](https://github.com/magento/magento2/assets/51681618/74d1eea4-a4e0-4549-838f-afbfc889b5e2)

We request you to try to reproduce the issue in the 2.4-develop branch and let us know if it is reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment] 2023-10-12 08:17
Hello @MoT3rror,

Thanks for the reply!

With the PayPal payment method, the issue can be reproducible. Please refer to the below below screencast for reference:

[Checkout.webm](https://github.com/magento/magento2/assets/51681618/4d971e0a-a8c3-4fb4-9e00-f1e0776aca37)

Hence confirming the issue.

Thanks

**Comment by engcom-Charlie** [comment] 2024-01-18 10:39
As per [this](https://github.com/magento/magento2/pull/38031#issuecomment-1898221897) update, closing this issue now. Please feel free to reopen for any further updates.

Thank you!

**Closed as completed by engcom-Charlie** 2024-01-18 10:39 UTC
Labels: Component: Checkout, Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.x, Area: Cart & Checkout
