### ISSUE TITLE
Backend > Customers > Cannot edit an address when French language is selected

### ISSUE THREAD

**Issue by MarianneCA** [magento/magento2#33357] opened 2021-06-25 15:05 UTC
Magento ver. 2.4.1-p1
Commerce Cloud

### Steps to reproduce (*)

This bug occurs if French language is selected for the backend.

Backend > Customers > Select a customer > Addresses

Next to the Default billing address and Default Shipping address blocks, the "Edit" links cannot be selected because they overlap with the French translations of "Default billing addres" and "Default Shipping address" titles. Please see screen shot.

![magento_BO](https://user-images.githubusercontent.com/75482796/123444642-6559c900-d5d7-11eb-978b-a83bb95cf218.jpg)

### Expected result (*)

Move "Edit" links so that they can be selected when French language is activated.

- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-06-28 06:48
![Screenshot from 2021-06-28 13-48-06](https://user-images.githubusercontent.com/1908873/123592518-801a8080-d817-11eb-9a2c-15635051a739.png)
can't reproduce same problem as your scenario

**Comment by MarianneCA** [comment] 2021-06-28 07:12
Hello, 

Thank you for checking but you are not in the right location (you are on an order details page, and you need to be on a customer details page).

You need to go in the backend to:
Backend > Customers > Select a customer > Addresses
Or when French language is activated:
Backend > Clients > Select a customer > Adresses
The problem occurs on a Customer page, when the Address tab is selected.

Kind regards, 
Marianne Le Menestrel

**Comment by mrtuvn** [comment] 2021-06-28 07:53
aah i see ! came wrong place
Thanks for let me know

**Comment by engcom-Delta** [comment] 2021-06-28 11:57
Hi @MarianneCA,

I have verified this issue on Magento 2.4 Develop Backend & observed we unable to reproduce it .it works as expected.

Steps followed:
1. Log in to backend(Magento 2.4 Develop admin)
2. Click on Admin icon --> select Account settings
3. Chang the Language to France (Activate) for Interface Locale field & Click on Save button 
4. Click on Customers --> Select 1 customer --> click on 'Edit' link
5. Select Addresses & Verify the default shipping address & Billing address
6. Observed that Edit button is not overlapped 
Kindly find the attached snapshots for reference.
![Account_languageSET](https://user-images.githubusercontent.com/51681379/123632773-f332ef80-d835-11eb-8075-680ad1026e61.jpg)
![Addresses_Edit_link](https://user-images.githubusercontent.com/51681379/123632804-faf29400-d835-11eb-9725-46b579d6b1bd.jpg)

Hence added the label 'Needs update'.

Thanks

**Comment by mrtuvn** [comment] 2021-06-28 13:01
@engcom-Delta you should test with long text case. Ui visual should be cover for as much as case possible

**Comment by MarianneCA** [comment] 2021-06-28 15:14
Thank you Tu, I'll transfer the patch to our technical team.
Kind regards, 
Marianne

**Comment by sdzhepa** [comment] 2021-07-01 16:59
@engcom-Delta 
Could you please recheck this issue according to https://github.com/magento/magento2/issues/33357#issuecomment-869663893
also you can switch to the French locale as described in the description 
> overlap with the French translations of "Default billing address" and "Default Shipping address" titles

**Comment by engcom-Delta** [comment] 2021-07-12 11:55
Hi @sdzhepa,
Yes, I verified again and found that Edit link is overlapping the address .Please find the attached snapshot for reference.

Hence , Marking the issue is 'Issue Confirmed
![Uploading OverLapping the Edit button.jpg…]()

'

**Comment by magento-engcom-team** [comment] 2021-07-15 12:21
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2021-07-15 12:22
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42858` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2021-07-29 11:03
Hi @MarianneCA. Thank you for your report. 
The issue has been fixed in magento/magento2#33368 by @mrtuvn in 2.4-develop branch
Related commit(s):
 - [a1a7dd2fb829a691cf007ba7dfab9b4369ad220f](https://github.com/magento/magento2/commit/a1a7dd2fb829a691cf007ba7dfab9b4369ad220f)

The fix will be available with the upcoming 2.4.3 release.

**Closed as completed by gabrieldagama** 2021-07-29 11:03 UTC
Labels: Issue: Confirmed, Component: Admin, Fixed in 2.4.x, Priority: P1, Progress: done, Reproduced on 2.4.2
