### ISSUE TITLE
Add Simple Products Manually to Configurable Product Give Wrong Result

### ISSUE THREAD

**Issue by alexwijanarko** [magento/magento2#33976] opened 2021-09-02 15:23 UTC
### Preconditions (*)
1. Magento Community Edition 2.3.4 with sample data
2. PHP 7.3

### Steps to reproduce (*)
1. Edit Configurable Products via admin
2. Go to Configurations tab
2. Add Products Manually
![image](https://user-images.githubusercontent.com/7570336/131868450-cdeccb0f-5ee0-42e2-af19-db39b922c906.png)
3. On Select Associated Product, click **Select All**
4. Remove some of the products
![image](https://user-images.githubusercontent.com/7570336/131870145-fb6124fc-1c2e-4e87-a3e5-8b34ab0141f9.png)
_in this example, only **56 products** selected_
5. Click **Done**

### Expected result (*)
1. only 56 products selected

### Actual result (*)
1. more than 56 products selected
![image](https://user-images.githubusercontent.com/7570336/131870644-49aac7e6-b6fc-4e95-ba7a-1631561013a6.png)
2. checking on another page of the result make website crash

### Example (*)
![errorConfigurableProduct](https://user-images.githubusercontent.com/7570336/131994226-435d1dab-2050-4881-9e97-3be064060f9a.gif)

---
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by ajijshekh123** [comment] 2021-09-03 05:12
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-09-03 10:05
Hi @alexwijanarko,

I tried to reproduce this issue on 2.4-develop branch but simple products are coming as expected. Please find the attached screenshot of the same.

<img width="1341" alt="Screenshot 2021-09-03 at 2 57 50 PM" src="https://user-images.githubusercontent.com/60198022/131985615-80c85bfb-8e95-46f7-8a06-1a717f52729f.png">

I initially configured 3 products with attribute color to the 'Configurations' tab, then added 17 more products based on the same configurations. It is showing 20 total products now.

Looks like you already had Configurable Products in the 'Configurations' tab before you edited the same. So the list just got added with the new 56 products. Is it so ? If not, can you please provide more details or what you did differently so that we can try to reproduce on 2.4-develop instance ?

Thanks

**Comment by alexwijanarko** [comment] 2021-09-03 10:43
Hi @engcom-Lima ,
it's always happen when on "Select Associated Product" page, there are more than 1 page of products result, then click "Select All"

Example : 
set to 5 products per page
![image](https://user-images.githubusercontent.com/7570336/131993018-27d01424-a2c9-4dbe-9739-80bf9c5d9fc1.png)
result
![image](https://user-images.githubusercontent.com/7570336/131993092-69f67379-e32d-4447-9f86-6e8391483aa4.png)

**Comment by alexwijanarko** [comment] 2021-09-03 10:52
![errorConfigurableProduct](https://user-images.githubusercontent.com/7570336/131994226-435d1dab-2050-4881-9e97-3be064060f9a.gif)

**Comment by engcom-Lima** [comment] 2021-09-07 09:19
Hi @alexwijanarko,

Thank you for the video.

Verified the issue and it is reproducible on 2.4-develop branch with sample products.

Below is what I did to reproduce it:

1. Created a configurable product, added attribute and added some simple products and saved.
2. Edit Configurations and changed attribute and remove all previous products.
3. Clicked on ‘Add products manually’.
4. On ‘Select Associated Product’ pop up, made ‘5 per page’ results, clicked on page 2 of the products, selected all from the list and saved.
5. Checked on ‘Configurations’ page and all sample products appeared instead of selected ones.

Attached screenshots of the same.

<img width="1437" alt="Screenshot 2021-09-07 at 2 09 08 PM" src="https://user-images.githubusercontent.com/60198022/132319216-5d675fd6-d835-460d-80f5-554b7cd3a5c2.png">

<img width="1440" alt="Screenshot 2021-09-07 at 2 09 50 PM" src="https://user-images.githubusercontent.com/60198022/132319246-f7924b04-683a-4bac-8ded-68b5beb0432c.png">

**Comment by alexwijanarko** [comment] 2022-03-10 01:50
Hi, it's been a couple months.
Any update related this issue?

**Comment by engcom-Bravo** [comment] 2024-06-25 04:20
Hi @alexwijanarko,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1344" alt="Screenshot 2024-06-25 at 09 46 35" src="https://github.com/magento/magento2/assets/51680745/9938222e-32f6-4499-b893-33cb0e559caa">



![Chaz-Kangeroo-Hoodie-Products-Inventory-Catalog-Magento-Admin](https://github.com/magento/magento2/assets/51680745/a2e1bf38-2d16-4140-9e7d-f3d48a64f39f)



Only 6 products were selected.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-25 04:20 UTC
Labels: Issue: Confirmed, Component: ConfigurableProduct, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Product
