### ISSUE TITLE
reindex take too much time for some query

### ISSUE THREAD

**Issue by hankzhh** [magento/magento2#10506] opened 2017-08-11 22:06 UTC
reindex catalog_product_category looks still take a lot of time. and the mysql query log shows some sql are not "resaonable": select from catalog_category_product_index and immediately insert into the same table.

### Preconditions

1. Magento v2.1.8 mysql v5.7 php v7
2. 7 store views and total sku number is about 50k.

### Steps to reproduce

1. enable mysql query log.
2. php bin/magento indexer:reindex catalog_product_category
3. check mysql query log

### Expected result

1. dont execute some ineffective sql.

### Actual result

1. [Screenshot, logs]
## 20555 ## QUERY
SQL: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 595000 OFFSET 5000 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
AFF: 0
TIME: 5.3163

## 20555 ## QUERY
SQL: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 600000 OFFSET 5000 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
AFF: 0
TIME: 5.2262

## 20555 ## QUERY
SQL: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 605000 OFFSET 5000 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
AFF: 0
TIME: 5.4333

## 20555 ## QUERY
SQL: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 610000 OFFSET 5000 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
AFF: 0
TIME: 5.4589

## 20555 ## QUERY
SQL: INSERT INTO `catalog_category_product_index` (`category_id`, `product_id`, `position`, `is_parent`, `store_id`, `visibility`) SELECT `catalog_category_product_index`.* FROM `catalog_category_product_index` ORDER BY `catalog_category_product_index`.`category_id` ASC
 LIMIT 615000 OFFSET 5000 ON DUPLICATE KEY UPDATE `category_id` = VALUES(`category_id`), `product_id` = VALUES(`product_id`), `position` = VALUES(`position`), `is_parent` = VALUES(`is_parent`), `store_id` = VALUES(`store_id`), `visibility` = VALUES(`visibility`)
AFF: 0
TIME: 5.5602

**Comment by choukalos** [comment] 2017-08-15 14:56
Hi @hankzhh,

- What are your PHP memory and MySQL configuration settings?
- How long are your index times, can you provide details by indexer?
- Have you looked at tuning indexer performance [Dev Docs Page](http://devdocs.magento.com/guides/v2.2/config-guide/prod/prod_perf-optimize.html)?

**Comment by hankzhh** [comment] 2017-08-17 19:02
class Full extends \Magento\Catalog\Model\Indexer\Category\Product\AbstractAction
{
    /**
     * Whether to use main or temporary index table
     *
     * @var bool
     */
    protected $useTempTable = false;                **### //should set it to "true"?**
..........................................
.........................................
........................................
    protected function publishData()
    {
        $select = $this->connection->select()->from($this->**getMainTmpTable**());
        $queries = $this->prepareSelectsByRange($select, 'category_id');
        foreach ($queries as $query) {
            $this->connection->query(
                $this->connection->insertFromSelect(
                    $query,
                    $this->getMainTable(),
                    ['category_id', 'product_id', 'position', 'is_parent', 'store_id', 'visibility'],
                    \Magento\Framework\DB\Adapter\AdapterInterface::INSERT_ON_DUPLICATE
                )
            );
        }
    }

**Comment by magento-engcom-team** [comment] 2017-12-05 08:30
@hankzhh, thank you for your report.
The issue is already fixed in develop branch, 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-05 08:30 UTC
Labels: bug report, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2018-01-19 21:24
@magento-engcom-team Will this be fixed in 2.1.x since this was the version the issue was originally reported against?
