### ISSUE TITLE
CategoryList graphql query returning only 20 categories

### ISSUE THREAD

**Issue by RanjitBShinde** [magento/magento2#36091] opened 2022-09-06 11:27 UTC
### Preconditions and environment

Magento Version 2.4.4-p1

### Steps to reproduce

1. Create more than 20 categories/sub categories from backend
2. Call below graphql query using Postman or Altair GraphQL Client
```
{
  categoryList {
    uid
    name
    children_count
    children {
      uid
      children_count
      name
      children {
        uid
        name
        children_count
        children {
          uid
          children_count
          name
        }
      }
    }
  }
}

```
### Expected result

It should return all the active categories

### Actual result

it returning only 20 categories/children categories

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-09-13 12:10
Hi @RanjitBShinde,


Thank you for reporting and collaboration.


Kindly refer this Magento [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/security-configuration.html).As per this doc the query depth value will be 20(Default value) Defines the maximum depth of nodes that query can return.


Thanks.

**Comment by RanjitBShinde** [comment] 2022-09-13 12:45
@engcom-Bravo  Thank you for the reply.

We are using this gql query to load the menu items in the front store. Default Venia PWA also using same gql. In our case, we have more than 20 categories and we need to show them in the menu. This query don't have any pageSize input parameter as well.

Thanks

**Comment by engcom-Bravo** [comment] 2022-09-14 13:23
Hi @RanjitBShinde,


Thanks for quick Response.

 Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
 We are creating categories(23) in our instance from backend.we are able to get all active categories.Kindly refer 
 screenshots.


<img width="1512" alt="Screenshot 2022-09-14 at 6 51 28 PM" src="https://user-images.githubusercontent.com/51680745/190165469-3caa0be4-877a-4be6-a535-497e528640f1.png">



Kindly refer this [document](https://devdocs.magento.com/guides/v2.4/graphql/security-configuration.html) for categories graphql query.


Please let us know we miss anything.

Thanks.

**Comment by RanjitBShinde** [comment] 2022-09-14 13:43
Hi @engcom-Bravo 

Thanks for looking into it.

Looks like you are using categories graphql query. We are facing issue for **categoryList** query, which is used in default pwa venia to fetch header menu. Please refer below screenshot.

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/16210367/190170418-2a2c86ed-c8a6-4161-930a-66b11be8dceb.png">

**Comment by lilbumblebear** [comment] 2022-09-15 17:42
I have a similar issue with categoryList query, where children appear for some menu items, but not others.  

Ex I have a structure similar to this:

Category A
- SubCategory B
Category C
- SubCategory D
Category E
Category F
Category G
- SubCategory H

I get A, C, E, F and G returned in my results, but only G has children defined, the others are blank.

Perhaps there is a setting I am missing in the UI, but I have made sure subcategories D and B are set to include_in_menu and have products (that are available).

**Comment by engcom-Bravo** [comment] 2022-09-19 12:28
Hi @RanjitBShinde,

Thanks for quick response.


Kindly refer this [document](https://devdocs.magento.com/guides/v2.4/graphql/queries/category-list.html).As per document the categoryList query returns 20 nodes.


<img width="963" alt="Screenshot 2022-09-19 at 5 38 24 PM" src="https://user-images.githubusercontent.com/51680745/191013855-9305cfd9-a25c-47a6-a6bf-b9c674e9b4a6.png">



Kindly count the nodes in your categoryList query screenshot starting from default category in your result.


Please let us know we miss anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-03 06:41
Hi @RanjitBShinde,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-03 06:41 UTC
Labels: Issue: needs update, Reported on 2.4.4-p1

**Comment by edas11** [comment] 2023-09-25 07:37
I believe `queryDepth` is or at least should be about depth, not the number of categories. And anyway looks like `queryDepth` is not used here. In `\Magento\CatalogGraphQl\Model\Category\Filter\SearchCriteria::buildCriteria` I see hard-coded page size 20 instead of `queryDepth`. If I increase this hard-coded value I get more categories in menu. I think there should be an option to choose page size in `categoryList` query.
