### ISSUE TITLE
Web Setup Wizard

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#3742] opened 2016-03-12 03:24 UTC
How are you supposed to go from the Web Setup Wizard back to the Admin?

**Comment by katmoon** [comment] 2016-03-12 09:14
There should be links to Magento Admin and Magento Storefront after installation completes.

**Comment by bondimedical3** [comment] 2016-03-12 09:31
But if I want to look at the Component Manager to see what modules I have installed how do I get back to the Admin?

**Comment by katmoon** [comment] 2016-03-12 11:26
Hi @bondimedical3 

I'm not sure what kind of problem you experience. Do you mean, what should you do if you forget the link to Admin?

![3-12-2016 1-18-52 pm](https://cloud.githubusercontent.com/assets/1260101/13722643/a1fcbd24-e855-11e5-84f6-e33026051777.png)

Here are the links to Admin displayed after installation completes. You define it during installation, so you can enter any name that is suitable to you.

**Comment by ghost** [comment] 2016-03-12 15:32
If you have command-line access, you can display the Admin URI: [`magento info:adminuri`](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-adminurl.html#instgde-cli-displayurl)

**Comment by bondimedical3** [comment] 2016-03-12 20:52
I am talking about this page.
![screenshot_2016-03-13-07-51-52](https://cloud.githubusercontent.com/assets/10808588/13725261/957fd5d6-e8f0-11e5-8faf-8f95b406a238.png)

**Comment by mazhalai** [comment] 2016-03-14 17:19
@bondimedical3 once you login to admin, go to **System > Web Setup Wizard.** to access this page. You cannot go back to admin from this page, since during upgrade or component update, the Magento2 application (admin included) may not be in a stable state. You will have to access admin directly.

Closing since this is not a bug, but expected behavior.

**Closed as completed** 2016-03-14 17:21 UTC
