### ISSUE TITLE
Product Image Issue

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#13465] opened 2018-02-02 08:02 UTC
### Preconditions

1. Magento-2.1.7, PHP 7, MySQL 5.x
2. Nginx

### Steps to reproduce

1. Add some configurable product with the options **Blue**, **White**.
2. Make a sample image named **sample-blue.jpg** and **sample-white.jpg**
3. Add this sample image **sample-blue.jpg** to all the simple associated product having option Blue.
4. Delete this sample image from any one product.

### Expected result

1. This sample image got deleted from only the product we deleted from admin.

### Actual result

1. Sample image disappeared/delete from all the products having this sample image **sample-blue.jpg**.

**Comment by rishabhrkrai** [comment] 2018-02-02 09:18
One thing I missed, all these products were imported from CSV. Before import, I put all the images in **var/import** folder.

**Comment by orlangur** [comment] 2018-02-02 10:41
If you want images to be managed separately for different simple products, you shouldn't associate single image `sample-blue.jpg` with multiple products in the first place.

**Comment by magento-engcom-team** [comment] 2018-02-02 14:53
High @RishabhRkRai. Thanks for applying. You See due to actual Magento's logic each product with image should be associated with the separate image file. And if You remove the image from a product the corresponding image file is deleted from its directory. In Your case all Blue products have the same corresponding file sample-blue.jpg. So if You try now to remove the image from at least one of the Blue products it will delete sample-blue.jpg from its directory and all the other Blue products this image file were associated with will lost the image too. So if You want to resolve Your problem for now You should consider that. If You created products via Admin this problem wouldn't arise. But as You did it via import we admit You should have been at least somehow notified about the situation in case You want to remove image from one of those products. So we will create our internal ticket for fixing this issue.

**Comment by rishabhrkrai** [comment] 2018-02-02 17:09
Hi @magento-engcom-team , I'll take care to this. Is this a bug?

**Comment by orlangur** [comment] 2018-02-03 22:03
> Is this a bug?

Does not sound as a bug.

> You should have been at least somehow notified about the situation in case You want to remove image from one of those products

Yeah, some warning/validation during import wouldn't hurt. Modification of deletion process to check if some product in some store still has the image attached could be too hard from performance perspective and not even possible in case admin user does not have enough permissions in all stores.

**Comment by magento-engcom-team** [comment] 2018-02-05 07:35
Hi @RishabhRkRai again. We are sorry for not doing it at the first time and therefore probably confusing You but we are glad to inform You that this issue seems to be fixed in 2.2.2 version.

**Comment by magento-engcom-team** [comment] 2018-02-05 07:38
@RishabhRkRai, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-03-05 17:23
@RishabhRkRai The issue is already fixed in 2.2.2 onward.
Closing ticket for now. Please reopen if you need any further assistance with this.

**Closed as completed by magento-engcom-team** 2018-03-05 17:23 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by Ctucker9233** [comment] 2018-04-29 00:12
@magento-engcom-team What are the commits for this issue?
