### ISSUE TITLE
Issues Found on Grid Multi-Select Column

### ISSUE THREAD

**Issue by mahesh-rajawat** [magento/magento2#24400] opened 2019-09-01 09:04 UTC
### Preconditions (*)

1. Magento 2.3-develop and Magento 2.3.2
2.

### Steps to reproduce (*)

**Issue First:** 
1. Open any grid having some records.
2. Click on Header Checkbox to select all record on current page. https://prnt.sc/p09pr0
3. Now unselect some record, on click particular row: https://prnt.sc/p09pya
4. Again click on Header Checkbox, here is the issue.
5. Now you will see all records are unselected but header checkbox is selected. https://prnt.sc/p09qh6

**Issue Second**
1.  Now Select the per page record to 1 https://prnt.sc/p09rfr
2. And select all record on current page by clicking header checkbox. https://prnt.sc/p09rrj
3. Go to second page you will see that the header checkbox is selected on all remaining pages.
https://prnt.sc/p09s42 

### Expected result (*)

1. https://prnt.sc/p09qof
2.

### Actual result (*)

1. https://prnt.sc/p09qh6
2.

**Comment by magento-engcom-team** [comment] 2019-09-02 10:27
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19785` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by emotaphp** [comment] 2019-09-14 14:05
#mm19br

**Comment by magento-engcom-team** [comment] 2019-09-14 14:05
@emotaphp thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by shikhamis11** [comment] 2020-02-02 05:04
#MM20IN

**Comment by sdzhepa** [comment] 2020-06-12 16:08
It looks like 
Duplicate of #24348

**Comment by VladimirZaets** [comment] 2020-06-17 17:36
Closet as a duplicate of #24348

**Closed as completed by VladimirZaets** 2020-06-17 17:36 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Theme, Component: Admin, Event: mm19br, Fixed in 2.4.x, Event: mm20in, Priority: P3, Severity: S2

**Comment by magento-engcom-team** [comment] 2020-09-19 11:50
Hi @maheshWebkul721. Thank you for your report. 
The issue has been fixed in magento/magento2#29968 by @engcom-Hotel in 2.4-develop branch
Related commit(s):
 - [1f6e82fede343e6e239aaedc854ea6d63317272c](https://github.com/magento/magento2/commit/1f6e82fede343e6e239aaedc854ea6d63317272c)
 - [e837bdc66501762a46418e2fdfea3746295f690f](https://github.com/magento/magento2/commit/e837bdc66501762a46418e2fdfea3746295f690f)
 - [591e04e80f0727840ac9ec8035caa055e148a930](https://github.com/magento/magento2/commit/591e04e80f0727840ac9ec8035caa055e148a930)
 - [8a9546f7f0a938a9752508fe6ffa090cd4d76f00](https://github.com/magento/magento2/commit/8a9546f7f0a938a9752508fe6ffa090cd4d76f00)
 - [f019712ea87afd04e7f6ec521f40f28c0894a8a5](https://github.com/magento/magento2/commit/f019712ea87afd04e7f6ec521f40f28c0894a8a5)
 - [4a20d6efc56b97e3ea73886b4a9ce51eefc322e2](https://github.com/magento/magento2/commit/4a20d6efc56b97e3ea73886b4a9ce51eefc322e2)
 - [70df4f05f74ecbb87355ac7c60fce6407436406b](https://github.com/magento/magento2/commit/70df4f05f74ecbb87355ac7c60fce6407436406b)
 - [a85a63b7fb59ae7cf92c3c1a2dc65afe49fcba3d](https://github.com/magento/magento2/commit/a85a63b7fb59ae7cf92c3c1a2dc65afe49fcba3d)
 - [462f12379f7a03c3acac35ff23e4295848bb0f24](https://github.com/magento/magento2/commit/462f12379f7a03c3acac35ff23e4295848bb0f24)

The fix will be available with the upcoming 2.4.2 release.
