### ISSUE TITLE
B2B Module 1.3.1 - Backend configuration site not loading because of error "Notice: Undefined index: title"

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32916] opened 2021-04-30 13:03 UTC
### Preconditions (*)

1. 2.4.2 EE
2. Magento 2 - B2B 1.3.1

### Steps to reproduce (*)

1. Load backend
2. Delete title of a shipping method to make it empty.
3. Navigate to System -> Configuration -> General -> B2B Features

### Expected result (*)

1. Should load 

### Actual result (*)

1. Error is getting logged into var/log/exception.log and only an empty site is showing:

`Notice: Undefined index: title in /home/company/staging-m2.company.de/vendor/magento/module-company-shipping/Model/Source/ShippingMethod.php on line 48 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: title in /home/company/staging-m2.company.de/vendor/magento/module-company-shipping/Model/Source/ShippingMethod.php on line 48`

![image](https://user-images.githubusercontent.com/16349349/116698798-16235d80-a9c5-11eb-8bc3-5e85a6ed7e93.png)

### Additional Information:

I echoed out the title, this is what I get

```
2021-04-30T13:13:57+00:00 INFO (6): carrier: dhl
2021-04-30T13:13:57+00:00 INFO (6): DHL
2021-04-30T13:13:57+00:00 INFO (6): carrier: fedex
2021-04-30T13:13:57+00:00 INFO (6): Federal Express
2021-04-30T13:13:57+00:00 INFO (6): carrier: instore
2021-04-30T13:13:57+00:00 INFO (6): In-Store Pickup Delivery
2021-04-30T13:13:57+00:00 INFO (6): carrier: flatrate
2021-04-30T13:13:57+00:00 INFO (6):
2021-04-30T13:13:57+00:00 INFO (6): carrier: tablerate
2021-04-30T13:13:57+00:00 INFO (6): Best Way
2021-04-30T13:13:57+00:00 INFO (6): carrier: freeshipping
2021-04-30T13:13:57+00:00 INFO (6): Versandkostenfrei
2021-04-30T13:13:57+00:00 INFO (6): carrier: ups
2021-04-30T13:13:57+00:00 INFO (6): United Parcel Service
2021-04-30T13:13:57+00:00 INFO (6): carrier: usps
2021-04-30T13:13:57+00:00 INFO (6): United States Postal Service

```

As you can see there is an entry which is empty (Flatrate).

Proposed fix:

```
    public function toOptionArray()
    {
        $options = [];

        $carriers = $this->scopeConfig->getValue('carriers');

        foreach ($carriers as $carrierCode => $carrier) {

            $shippingTitle = empty($carrier['title']) ? $carrierCode : $carrier['title'];  // Use Carrier Code as a fallback (or even better, we could check if there is a default carrier title set in the config and use that)

            if (!isset($carrier['active']) || !$carrier['active']) {    // Added isset, because error is thrown, if the shipping method is not active
                $shippingTitle .= __(' (disabled)');
            }

            $options[] = ['value' => $carrierCode, 'label' => $shippingTitle];
        }

        return $options;
    }

```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by reense** [comment] 2021-07-12 07:54
For people having the same issue, [i've prepared a patch here.](https://gist.github.com/reense/0b0bf0d50620d2e73a349856a23d1e6e)

**Comment by engcom-November** [comment] 2021-07-16 08:28
Verified the issue on Magento 2.4-develop branch having EE and B2B modules installed, but the issue is not reproducible with mentioned steps:
Steps performed:
Navigate to Admin -> Configured UPS Shipping Method (Stores - Configuration - Sales - Shipping Methods - UPS)
Removed Title of UPS Shipping method and Saved
Clear cache
Navigate to Stores -> Configuration -> General -> B2B Features
**No issue: Page is loading as expected.**
Note FYI: B2B Features page is loading and since the Title is empty for UPS Shipping method, method is not displayed under B2B Shipping methods.
![image](https://user-images.githubusercontent.com/60198231/125917098-2dfc859b-1ef6-445e-b980-e2240083b49a.png)
@Eddcapone, can you please recheck the issue on 2.4-develop branch and provide the missing steps if the issue is still reproducible.
Thank you

**Comment by engcom-November** [comment] 2021-07-30 05:43
@Eddcapone, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-07-30 05:43 UTC
Labels: Issue:  Cannot Reproduce, Component: Backend, Issue: needs update, Reported on 2.4.2
