### ISSUE TITLE
Regular expression Error in ZendFramework

### ISSUE THREAD

**Issue by karyna-t** [magento/magento2#34800] opened 2021-12-13 08:11 UTC
An issue with a regular expression was found. Line:
https://github.com/magento/zf1/blob/master/library/Zend/Db/Statement.php#L198

Executed with some Sql queries it can return NULL, which means that the function had an [error](https://www.php.net/manual/en/function.preg-replace.php#refsect1-function.preg-replace-returnvalues).

I reproduced the issue with a specific query from PageBuilder module (see _Steps to reproduce_ section).
In this case the error was: `PREG_BACKTRACK_LIMIT_ERROR - Backtrack limit exhausted`
This problem is known as **Catastrophic backtracking**. ([regex101](https://regex101.com/r/rXWOrZ)) , most likely the pattern is not entirely correct.

To fix the related issue on PHP 8.1., which caused by the issue described, a temporary fix was introduced:
https://github.com/magento/zf1/pull/42
However, it doesn't fix the issue itself. It only makes the method behaviour same as it was on PHP < 8.1.

### Preconditions (*)
Reproducible on PHP 7.4, 8.0, 8.1

### Steps to reproduce (*)
A possible way to reproduce the issue:
Execute `\Magento\PageBuilder\Setup\Patch\Data\UpgradePageBuilderStripStyles` Data patch and set a debug point on a problematic line.
I run into the error with a query
```
SELECT MAX(block_id) as max, COUNT(*) as cnt FROM (SELECT `cms_block`.`block_id`, `cms_block`.`content` FROM `cms_block` WHERE (content IS NOT NULL) AND (content LIKE ('%data-content-type=\"%')) AND (`cms_block`.`block_id` > 0) ORDER BY `cms_block`.`block_id` ASC
 LIMIT 50000) AS `t`
```

Function `preg_last_error_msg` may be useful to check the preg_replace error, because preg_replace doesn't throw any warning or notice.

### Expected result (*)
A correct execution of a `preg_replace` function on the mentioned line with all queries. Pattern has to be fixed.

### Actual result (*)
Some Sql queries will not be executed, existing code replaces them with an empty string because of `preg_replace` error.

**Comment by karyna-tsymbal-atwix** [comment] 2021-12-13 08:13
may be a fix, however it's only a suggestion, didn't check it in details
https://regex101.com/r/rbq5JH/1

**Comment by engcom-Hotel** [comment] 2022-12-26 12:42
Hello @karyna-tsymbal-atwix,

Thanks for the report and collaboration!

We have tried to reproduce the issue in the Magento 2.4-develop branch but the issue is not reproducible for us. Can you please try to reproduce the issue in the latest development branch and update us with the latest steps to reproduce it?

Thanks

**Comment by engcom-Hotel** [comment] 2023-01-09 17:13
Dear @karyna-tsymbal-atwix,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-01-09 17:13 UTC
Labels: Triage: Dev.Experience, Issue: needs update
