### ISSUE TITLE
Suggestions is not working in GraphQL

### ISSUE THREAD

**Issue by mhafizumer** [magento/magento2#37858] opened 2023-08-08 08:08 UTC
### Preconditions and environment

Magento version (2.4.6-p1 CE)
Magento add the **suggestions** attribute in GraphQL for the product Type Query

![image](https://github.com/magento/magento2/assets/67052331/149fc183-7d70-4e4d-bd09-a8b6a07d7928)

But when we fetch the data, suggestions are not showing even if the requested query has results because I have checked Magento to add suggestions when the search result has zero $totalcount in results.

https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php#L161

### Steps to reproduce

I am using Altair GraphQL chrome extension. Query is

```
{
  products(
	search: "metro"

   ) {
	page_info{
  	current_page
  	page_size
  	total_pages
	},
	suggestions {
  	search
	}
	items {
  	name
  	sku
  	calculated_sqm_price
  }
}
}
```
When the query has result : 

![image](https://github.com/magento/magento2/assets/67052331/2988ad26-9b32-46ff-97da-578687b2a654)

When Query has no result 

![image](https://github.com/magento/magento2/assets/67052331/23753b4d-0d72-4355-8c44-c42800be0c74)

### Expected result

I want to give matching terms in suggestion as Magento frontend return

![image](https://github.com/magento/magento2/assets/67052331/67cfad55-72e0-4830-8191-8381af840039)

I have debugged when the total count is zero and then triggered this resolver **Magento\CatalogGraphQl\Model\Resolver\Products\Query\Suggestions::execute**

https://github.com/magento/magento2/blob/d846142a3ab8b49597dfb8bd7508d875efdab19a/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Suggestions.php#L52

But the $suggestionItems are empty.

### Actual result

The Actual result is suggestions are null

![image](https://github.com/magento/magento2/assets/67052331/d4910b5b-05d7-423a-8e44-4cde32040657)

I have check 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-08-17 06:36
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-08-18 09:44
Hi @mhafizumer ,

verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly refer the below screenshots:
<img width="1504" alt="Screenshot 2023-08-18 at 3 03 05 PM" src="https://github.com/magento/magento2/assets/60198592/8074bd7f-5538-4366-a708-622fe34b0c94">

**Comment by mhafizumer** [comment] 2023-08-18 11:09
hello @engcom-Dash  as clearly seen in your screenshot as well, those suggestions are null and you are saying the **issue is not reproducible**. let me reiterate my query regarding suggestions
The suggestions remain empty in both cases, either we have a matching result referring to [screenshot1](https://user-images.githubusercontent.com/67052331/259029374-2988ad26-9b32-46ff-97da-578687b2a654.png
)
OR 
we have no result referring to [screenshot2](https://user-images.githubusercontent.com/67052331/259029942-23753b4d-0d72-4355-8c44-c42800be0c74.png
)

Does "suggestions" mean in Graphqls product() query that to show related products name
Please guide us in this regard

**Comment by engcom-Dash** [comment] 2023-08-22 09:45
Hi @mhafizumer ,

Thanks for the inputs !

As per the [DevDocs](https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/) when we are using suggestions its does not return any values and same time its return matching items which is related to given array.Kindly refer the below screenshots:
<img width="895" alt="Screenshot 2023-08-22 at 2 45 04 PM" src="https://github.com/magento/magento2/assets/60198592/6876d7ee-81a0-4bf4-9b62-81e97ebbcbee">

Thanks.

**Comment by nuzil** [comment] 2023-08-31 09:09
Sorry @engcom-Dash 
I tried to understand your answer but could not really understand a logic behind.

Lookins on screenshot you refers too: 

_An array that contains suggested search words. This object is returned when the value specified in the search input parameter does not return any results_

So as @mhafizumer mentioned in his example, when he is doing the search via GQL there are no items being return (thats correct), but in case there are no items, "suggestions" tag have to return suggestions for a user. But Magento still do not return any.

If you can make an example with values inside of suggestings, then it will be more clear.

Thanks

**Comment by engcom-Bravo** [comment] 2023-09-08 06:27
@magento give me 2.4-develop instance

**Comment by attatm** [comment] 2023-09-08 06:40
we already fix this issue for our site 
Please let us know if you need our assistance

**Comment by mhafizumer** [comment] 2023-09-08 09:20
I have fixed it on my end, but I am waiting for Magento end to fix it permanently.

In the custom module "schema.graphqls" file overrides Magento product()

```
type Products @doc(description: "Contains the results of a `products` query.") {
    suggestions (search: String!): [SearchSuggestion] @doc(description: "An array of search suggestions for case when search query")
    @resolver(class: "Vendor\\CustomModule\\Model\\Resolver\\SearchSuggestions")
}

type SearchSuggestion @doc(description: "A string that contains search suggestion") {
    term: String @doc(description: "Suggested term")
    count: Int @doc(description: "Number of results for the term")
}

```

**Resolver class :** 


```
<?php

namespace Vendor\\CustomModule\Model\Resolver;

use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Exception\GraphQlInputException;
use Magento\Framework\GraphQl\Query\ResolverInterface;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Smile\ElasticsuiteCore\Model\Autocomplete\Terms\DataProvider as AutocompleteDataProvider;
use Magento\Search\Model\QueryFactory;

class SearchSuggestions implements ResolverInterface
{
    private $autocompleteDataProvider;
    private $queryFactory;

    public function __construct(
        AutocompleteDataProvider $autocompleteDataProvider,
        QueryFactory $queryFactory
    ) {
        $this->autocompleteDataProvider = $autocompleteDataProvider;
        $this->queryFactory = $queryFactory;
    }

    public function resolve(
        Field       $field,
                    $context,
        ResolveInfo $info,
        array       $value = null,
        array       $args = null
    ) {
        $this->validateArgs($args);
        $this->queryFactory->get()->setQueryText($args['search']);
        $suggestions = $this->autocompleteDataProvider->getItems();
        return $this->formatSuggestions($suggestions);
    }

    private function formatSuggestions($suggestions)
    {
        $formattedSuggestions = [];
        foreach ($suggestions as $suggestion) {
            $formattedSuggestions[] = [
                'term' => $suggestion->getTitle(),
                'count' => $suggestion->getNumResults(),
            ];
        }
        return $formattedSuggestions;
    }

    private function validateArgs($args)
    {
        if (!isset($args['search'])) {
            throw new GraphQlInputException(
                __("'search' input argument is required.")
            );
        }
    }
}
```

**Comment by attatm** [comment] 2023-09-08 09:21
Thanks Umar for Sharing

**Comment by engcom-Bravo** [comment] 2023-09-08 11:50
@nuzil Thanks for your contribution & collaboration over here.

Hi @mhafizumer,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1378" alt="Screenshot 2023-09-08 at 12 21 03 PM" src="https://github.com/magento/magento2/assets/51680745/05f95d38-917e-4edc-aa37-9e40adbac47d">



<img width="1260" alt="Screenshot 2023-09-08 at 12 17 38 PM" src="https://github.com/magento/magento2/assets/51680745/3ccc5b38-a0d6-44d4-a8c9-b7bf6b54aa1f">



As per Document https://developer.adobe.com/commerce/webapi/graphql/schema/products/queries/products/#searchsuggestion-attributes  The SearchSuggestion object provides an array of suggested search terms.We are able to get the suggested search terms.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.Please let us know if we are missing anything.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-21 06:14
Hi @mhafizumer,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-21 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
