### ISSUE TITLE
Uncaught TypeError: Cannot read property 'items' of null for restricted permission user

### ISSUE THREAD

**Issue by mohitka** [magento/magento2#22308] opened 2019-04-12 13:59 UTC
### Preconditions (*)

1. I have tested and found this issue in Magento versions **2.2.4** and **2.2.7**. Not tested in other versions yet.

### Steps to reproduce (*)

1. Login to the backend with a user with full backend permission.
2. Create a new user role from **System** >> **User Roles** with **Custom** Resource Access. For example, select only the **Dashboard** from the resources list. (You can choose any other)

![create-role](https://user-images.githubusercontent.com/40565507/56042443-b794d380-5d58-11e9-9e18-c498ec5962e6.png)

3. After creating the role, create a new admin user with the role which you created in the previous step.
4. Login to the backend with new user's login credentials in another browser or after logging out the current user.
5. Open the browser's console and check the error mentioned below.

```
Uncaught TypeError: Cannot read property 'items' of null
    at UiClass.onRequestComplete (data-storage.js:270)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)
```

### Expected result (*)

1. The above-mentioned error should not be there for ACL restricted user.

### Actual result (*)

1. **Error Message:**
```
Uncaught TypeError: Cannot read property 'items' of null
    at UiClass.onRequestComplete (data-storage.js:270)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)
```
2. **Screenshot of the Error:**
![console-error](https://user-images.githubusercontent.com/40565507/56042647-312cc180-5d59-11e9-8a21-08496bfa416f.png)

**Comment by shikhamis11** [comment] 2019-04-12 15:43
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-12 15:43
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-12 15:44
Hi @shikhamis11, here is your [Magento instance](https://i-22308-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22308-2-2-develop.instances.magento-community.engineering/admin](https://i-22308-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-04-12 15:54
@mohitka Thank You for your report.
I checked the issue on magento 2.3.1 and 2.2.8 versions the error is showing with restricted user is 
`TpeError: data is null` and this issue is already reported Please check #20198

**Comment by shikhamis11** [comment] 2019-04-13 07:55
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-13 07:55
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-13 07:56
Hi @shikhamis11, here is your [Magento instance](https://i-22308-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-22308-2-2-develop.instances.magento-community.engineering/admin](https://i-22308-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by mohitka** [comment] 2019-04-15 07:11
Hi @shikhamis11, @magento-engcom-team,

I think these issues may seem similar, but these are not the same issues.

I am not able to reproduce the issue mentioned in #20198. I have tested it in Magento versions **2.2.4**, **2.2.5**, **2.2.6** and **2.2.7**.

Please reopen the issue if you find it worth.

Thanks

**Comment by mohitka** [comment] 2019-04-18 09:41
@shikhamis11 @magento-engcom-team 
Is there anyone who can consider this issue to be reopened?

**Comment by jafar247commerce** [comment] 2019-05-06 11:48
@mohitka , yes i am also facing same issue in version 2.2.6, can anybody help me in resolving it?
Thanks

**Comment by shikhamis11** [comment] 2019-05-06 11:54
Hi @mohitka , I have reopened the issue.
please check the issue at 2.2-develop instance and share screenshot if you are able to reproduce the issue

**Comment by jafar247commerce** [comment] 2019-05-06 12:00
@shikhamis11 , yes i can reproduce the issue in 2.2.6 version, I am getting the console error, once i logged in with new admin user.

**Comment by jafar247commerce** [comment] 2019-05-06 12:04
![js-error](https://user-images.githubusercontent.com/44928714/57223869-264a1180-7025-11e9-85b3-5cf30d20d20b.png)

**Comment by jafar247commerce** [comment] 2019-05-06 12:18
@shikhamis11, @mohitka 
Facing this issue still in 2.3.0 version
Because of this i am not able to see any orders in sales order grid. 
Please anyone look into it and update me. Thanks

**Comment by AlexWorking** [comment] 2019-05-07 10:04
Hello @mohitka. We've managed to reproduce Your issue on 2.2.9 version but it's not reproducible on 2.3 develop version. Seems it has been fixed there. So according to the stage 4 of the comment above (m2-assistant bot) we are supposed to close the issue.

**Closed as completed by AlexWorking** 2019-05-07 10:04 UTC
Labels: Issue: Format is valid

**Comment by jonaschen623** [comment] 2019-08-27 02:22
after adding resource 'Basic Configuration Section' under 'Stores->Settings->Configuration', My local loaded fine. Hope this would help someone else.

![image](https://user-images.githubusercontent.com/1915539/63736091-0c835180-c8d6-11e9-80fc-458ec8b50af7.png)
