### ISSUE TITLE
PayPal via Braintree payment order invoice generate Authorize to capture Issue

### ISSUE THREAD

**Issue by vishaltajpara** [magento/magento2#26852] opened 2020-02-13 04:20 UTC
### Preconditions (*)
Magento Ver. 2.3.3.
Magento 2.3.5 p1

### Steps to reproduce (*)
1. Go to Admin and set Braintree payment method as Sandbox mode with setting Payment Action as Authorize.
![braintree_001](https://user-images.githubusercontent.com/29942583/74401022-f77b8a00-4e45-11ea-889b-d42882595be8.png)
2. Go to front end and place order one order using Braintree Payment Gateway.
3. When you can place order using Braintree than order place with Authorize and not create invoice because we have set as order authorize.
4. After order place go to admin check order's  transactions tab.
5. You can show one entry with authorization it's okay
6. But when i am create invoice against of the order than capture the order payment invoice time.,
### Expected result (*)
 After create invoice I have checked in order's Transactions tab for record so I need two entry of the transaction like one of the Authorization and one of the capture with same transaction ID.
![stripe](https://user-images.githubusercontent.com/29942583/74401879-a02ae900-4e48-11ea-8989-36e018912d2d.png)
### Actual result (*)
After create invoice I have checked in order's Transactions tab for record so it's first transaction record update which it's wrong

See the attached screenshot stripe payment method of the correct and i needed this type of entry.

![braintree_003](https://user-images.githubusercontent.com/29942583/74401021-f6e2f380-4e45-11ea-9fa8-52dee5bfbdf2.png)
**Additional information:**
Using PayPal via Braintree payment method admin setting Payment Action: Authorization. 
Place order and this order invoice generate by admin.
Authorize to capture successfully can not create new line than update Authorize record.

**Comment by magento-engcom-team** [comment] 2020-07-14 19:36
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35859` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-08-17 20:46
Hello @vishaltajpara

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because we are not able to process contribution to the `2.3.x` release line through this public repository. See details [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)
And starting from `2.4.0` release, code related to this payment was removed from Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Closed as completed by sdzhepa** 2020-08-17 20:46 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Braintree, Reproduced on 2.3.5p1, Reported on 2.3.3
