### ISSUE TITLE
Layered navigation showing attribute of zero quantity configurable product

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#5068] opened 2016-06-17 03:43 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Add new configurable product with size or color
3. Associate product with size for eg 40 have 0 quantity and not invisible status
4. Set Catalog > Inventory > Showing Out of Stock product to "No"
## Expected result
1. Layered navigation not showing that associated product in product listing page
## Actual result
1. Layered navigation showing attributes of those associated products.

Here is what layered navigation showing: 
![screenshot 2016-06-17 10 38 07](https://cloud.githubusercontent.com/assets/3891429/16140127/34e180de-3478-11e6-99b4-dac7b4864f62.png)

And inside product page:
![screenshot 2016-06-17 10 41 13](https://cloud.githubusercontent.com/assets/3891429/16140126/34d90ee0-3478-11e6-9dfd-6ae704f803f7.png)

**Comment by nntoan** [comment] 2016-07-13 06:56
Any updates? @yaronish @MomotenkoNatalia

**Comment by sevos1984** [comment] 2016-09-16 09:46
This is known issue, internal ticket MAGETWO-56525. Thanks for reporting.

**Comment by lucscu** [comment] 2016-11-02 08:32
Why this bug is so little discussed? Isn't it very important for who sells only configurable products?

**Comment by pobrassard** [comment] 2016-11-05 23:01
@LucScu i agree, it's really annoying.

@sevos1984 Any updates?

Thanks

**Comment by nntoan** [comment] 2016-11-18 09:40
4 months and 1 day for a **very** important issue, could Magento team set higher priority for this problem? Because I think all Magento merchants in the world are using configurable products...

@sevos1984

**Comment by fjgosselin** [comment] 2016-11-19 17:39
Very frustrating for users... Imagine you filter for Medium shirts but you still see 200 products and 150 of them have no medium size... This needs to be resolved fast @sevos1984

**Comment by lucscu** [comment] 2016-11-21 10:07
@sevos1984 are you alive?

**Comment by pobrassard** [comment] 2016-11-22 20:28
@valdislav Are you aware of this problem. I think this issue needs to be reassigned.

Thanks :)

**Comment by sergi-omit** [comment] 2016-12-12 07:57
Any updates? Somebody has could apply any fix?

**Comment by tuxman999** [comment] 2017-01-16 21:00
Hello People...    has anyone figured this out??

**Comment by tuxman999** [comment] 2017-01-16 23:25
The problem we had is using bundled items. When an item in the bundle reaches zero, that item attributes still show up in the layered navigation results even though the item is set to zero. 

We figured out a work around for this when using bundled products. 

In order to hide an item in the layered navigation, you must disable the item and it will not show in the layered navigation. 

If you don't want to disable all of the items manually when an item quantity get to zero, there is a setting to hide Out of Stock items. 
Open Admin panel of Magento store and navigate to System – > Configuration – > Catalog– > Inventory – > Stock Options Section.
Set Display Out of Stock product to No:
Click Save Config button to apply changes.


This will not disable the items. This will Not Display Items that are Out of Stock.

**Comment by lucscu** [comment] 2017-06-27 08:09
I fixed reindexing catalog_product_attribute, so i setted a cron to reindex it every night.

**Comment by smokygeek17** [comment] 2017-08-08 15:45
any news?

**Comment by nntoan** [comment] 2017-08-10 09:13
@smokygeek17 Seems "fixed" on 2.1

**Comment by mikehenze** [comment] 2017-08-10 09:18
Coming in 2.2

**Comment by magento-engcom-team** [comment] 2017-10-17 08:30
@nntoan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-17 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2017-10-17 10:41
@nntoan, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9
