### ISSUE TITLE
item getName() returns wrong name

### ISSUE THREAD

**Issue by hershkoy** [magento/magento2#31423] opened 2020-12-23 11:50 UTC
I am trying to print the name of an item inside an order in Magento 2.3.3.
The item is a variation, and for some reason `$item->getName()` doesn't return the full name of the item. Instead it returns some kind of a general name, like the parent of the variation or something.

This is the data from mysql from this item. The correct name is '1', but the `getName()` returns '2'.

[![enter image description here][1]][1]

This is the code:
```
$order = $this->_objectManager->get('Magento\Sales\Api\Data\OrderInterface')->loadByIncrementId($OrderNumber);
$items = $order->getAllItems();
foreach($items as $item){
	echo "item:".$item->getName()."\n";
}
```

I tried some other ways to get the correct name,such as `getData('name')`. Also `$item->getProductOptions()['simple_name']` both return the wrong name. Another thing that I tried is getting the name of the parent of the item:

```
$product = $this->_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($productId);
if(isset($product[0])){
	$product = $this->_objectManager->create('Magento\Catalog\Model\Product')->load($product[0]);
	$name = $product->getName();
}
```

How can I get the correct name of the item?

  [1]: https://i.stack.imgur.com/tEaf9.png

**Comment by dverkade** [comment] 2021-04-18 20:14
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Lima** [comment] 2021-06-04 13:23
Hi @hershkoy ,

Unfortunately, Can't reproduce the issue.

We have verify this issue in Magento current release (2.4.2) and this is not reproducible. You can find the screenshot of order shipment from backend and the name of the product in frontend is showing correctly.

Please find attachments regarding this.

![FrontEnd](https://user-images.githubusercontent.com/60198022/120807489-a117ea80-c565-11eb-8f1c-925703beaa9b.png)
<img width="943" alt="Screenshot 2021-06-04 at 4 01 00 PM" src="https://user-images.githubusercontent.com/60198022/120807670-d290b600-c565-11eb-8680-7aa444c8725e.png">

![Shipment](https://user-images.githubusercontent.com/60198022/120807529-ae34d980-c565-11eb-829b-b16dbe4ca2d8.png)

Can you please provide us more details or reproducible steps?

**Comment by engcom-Lima** [comment] 2021-06-18 11:07
Hi @hershkoy, I hope that your issue is resolved because we did not get any update on this since more than 14 days. Hence closing the ticket.

Please feel free to raise the new ticket if you have any other issue. We will be happy to work for you.

**Closed as completed by engcom-Lima** 2021-06-18 11:07 UTC
Labels: Triage: Dev.Experience, Issue: needs update
