### ISSUE TITLE
Magento 2 0.74.0-beta8 installation failed 

### ISSUE THREAD

**Issue by mariarti** [magento/magento2#1276] opened 2015-05-12 20:39 UTC
Installation is incomplete.
Check the console log for errors before trying again.

Installing admin user...

Enabling caches:
Current status:
Array
(
[config] => 1
[layout] => 1
[block_html] => 1
[view_files_fallback] => 1
[view_files_preprocessing] => 1
[collections] => 1
[db_ddl] => 1
[eav] => 1
[full_page] => 1
[translate] => 1
[config_integration] => 1
[config_integration_api] => 1
[config_webservice] => 1
)

Installing sample data:
[ERROR] exception 'Magento\Framework\Exception\LocalizedException' with message 'Area code is already set' in /var/www/html/magento2/lib/internal/Magento/Framework/App/State.php:137
Stack trace:
#0 /var/www/html/magento2/setup/src/Magento/Setup/Model/SampleData.php(66): Magento\Framework\App\State->setAreaCode('adminhtml')
#1 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(1123): Magento\Setup\Model\SampleData->install(Object(Magento\Framework\ObjectManager\ObjectManager), Object(Magento\Setup\Model\WebLogger), 'magento2')
#2 [internal function]: Magento\Setup\Model\Installer->installSampleData(Array)
#3 /var/www/html/magento2/setup/src/Magento/Setup/Model/Installer.php(288): call_user_func_array(Array, Array)
#4 /var/www/html/magento2/setup/src/Magento/Setup/Controller/Install.php(87): Magento\Setup\Model\Installer->install(Array)
#5 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Install->startAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/html/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/html/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/html/magento2/setup/index.php(26): Zend\Mvc\Application->run()
#16 {main}

I do it on fresh OS from scratch. Previous version (0.74.0-beta5) installation was without any issues. 

I use sample-data installation before setup from web:
$ composer require magento/sample-data:0.74.0-beta7
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing magento/sample-data-media (0.42.0-beta2)
    Downloading: 100%         

  - Installing magento/sample-data-fixtures (0.74.0-beta7)
    Downloading: 100%         

Writing lock file
Generating autoload files

**Comment by mbrinton01** [comment] 2015-05-13 02:18
Hello @mariarti, thank you for reporting this issue. It is a duplicate of https://github.com/magento/magento2/issues/1252, so I am closing this issue. You may follow the resolution on the other issue.

**Closed by mbrinton01** 2015-05-13 02:18 UTC
