### ISSUE TITLE
Unable to Change Attribute Set with Multiple Select Attribute

### ISSUE THREAD

**Issue by walrus28** [magento/magento2#11794] opened 2017-10-27 01:59 UTC
I am unable to change from an attribute set containing a multiple select attribute to one without it. 

### Preconditions

1. Magento 2.1

### Steps to reproduce

1. Create new attribute, test, of type "Multiple Select" and assign it a couple of values 
2. Create multiple attribute sets, default, testset1, testset2, and testset3. 
3. Assign the attribute test to the attribute sets testset1 and testset2. Do not assign it to default or testset3. 
4. Reindex & clean caches. 
5. Go to Products - Inventory - Catalog and click "Add Product". The attribute set default should be selected. 
6. Change the attribute set to testset3. 
7. Change the attribute set to testset1.
8. Change the attribute set to testset2. 
9. Change the attribute set to either default or testset3. 

### Expected result

1. "Please wait..." should appear briefly and the page should load the attribute selected (either default or testset3). 

### Actual result

1. "Please wait..." appears and does not disappear. The selected attribute set does not load.

**Comment by magento-engcom-team** [comment] 2017-10-27 07:53
@walrus28, thank you for your report.
We've created internal ticket(s) MAGETWO-82875 to track progress on the issue.

**Comment by p-bystritsky** [comment] 2017-12-27 13:48
The issue is already fixed in 2.2-develop.

**Closed as completed by p-bystritsky** 2017-12-27 13:48 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue: Format is valid
