### ISSUE TITLE
filter by date in order grid still filters by US date when user locale is set to international

### ISSUE THREAD

**Issue by IanFiretoys** [magento/magento2#25247] opened 2019-10-23 15:46 UTC
### Preconditions (*)

1. Magento 2.3.2
2. Magento/backend adminhtml
3. Default store locale set to English (United Kingdom)

### Steps to reproduce (*)

1. change your admin user's locale to english (united kingdom), or any locale that uses the DD/MM/YYYY date format (most places outside the USA)
2. go to order grid and open filters
3. using the calendar, choose a from date, it will successfully enter the date as an international format (DD/MM/YYYY) in this case it was 3rd of october, 03/10/2019
![image](https://user-images.githubusercontent.com/33158810/67410086-74db7000-f5b3-11e9-91ba-dbfd8d352415.png)
4.  choose a to date, i chose 4th of october, 04/10/2019
![image](https://user-images.githubusercontent.com/33158810/67410226-b3712a80-f5b3-11e9-9610-1f00b2700fd7.png)
5. apply filters

### Expected result (*)

1. the order grid to display all orders between the 3rd of october and the 4th of october (1 day's worth)
2.

### Actual result (*)

1. the order grid shows 1 month's worth of orders, from the 10th of march, to the 10th of april (10/03/2019 to 10/04/2019 in MM/DD/YYYY format)
2. ![image](https://user-images.githubusercontent.com/33158810/67410476-12cf3a80-f5b4-11e9-90ae-ef18ba7b629b.png) 
(columns removed for customer privacy)

as you can see, the locale is clearly not being adopted by the filters on the grid, **only** by the calendar popup, which makes setting the locale by user make the situation actually worse

**Comment by IanFiretoys** [comment] 2019-10-23 16:02
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-23 16:02
Hi @IanFiretoys. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-23 16:03
Hi @IanFiretoys, here is your [Magento instance](https://i-25247-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25247-2-3-develop.instances.magento-community.engineering/admin](https://i-25247-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by IanFiretoys** [comment] 2019-10-23 16:13
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2019-10-23 16:13
Hi @IanFiretoys. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2019-10-23 16:14
Hi @IanFiretoys, here is your [Magento instance](https://i-25247-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-25247-2-3-3.instances.magento-community.engineering/admin](https://i-25247-2-3-3.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by IanFiretoys** [comment] 2019-10-23 16:25
> Hi @IanFiretoys. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [x]  Summary of the issue
> * [x]  Information on your environment
> * [x]  Steps to reproduce
> * [x]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @IanFiretoys do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [ ]  yes
> * [x]  no
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

**Comment by magento-engcom-team** [comment] 2019-10-23 16:25
Hi @IanFiretoys. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-23 16:26
Hi @IanFiretoys, here is your [Magento instance](https://i-25247-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25247-2-3-develop.instances.magento-community.engineering/admin](https://i-25247-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by IanFiretoys** [comment] 2019-10-23 16:31
appears to be fixed in 2.3-develop

**Comment by engcom-Echo** [comment] 2019-11-19 12:36
Hello @IanFiretoys 

Thank you for your report and collaboration!
This issue is duplicate of [#25642](https://github.com/magento/magento2/issues/25642).
So I close it.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-11-19 12:36 UTC
Labels: duplicate, Issue: Format is valid

**Comment by chris-pook** [comment] 2022-06-07 09:55
For anyone stuck looking for an answer on this to patch an old version of Magento, see #22173.
