### ISSUE TITLE
API  catalog product render list response missing search criteria and total count

### ISSUE THREAD

**Issue by jigneshkhunt** [magento/magento2#24719] opened 2019-09-25 08:42 UTC
### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Go to the [postman](https://www.getpostman.com/) and use this URL and param with the GET method
URL: http://www.example.com/rest/V1/products-render-info
2. Param:

```
searchCriteria[filter_groups][0][filters][0][field] => category_id
searchCriteria[filter_groups][0][filters][0][value] => 4 ( Any Category id )
searchCriteria[filter_groups][0][filters][0][condition_type] => eq
searchCriteria[sort_orders][0][field] => name
searchCriteria[sort_orders][0][direction] => ASC
storeId => 1
currencyCode => USD
searchCriteria[pageSize] => 5
searchCriteria[currentPage] => 1 
```

### Expected result (*)

1. As per the getList method code, the response should contain items with data, Search criteria with filters and sort options and the total number of products

2. getList Method code:
![getList](https://user-images.githubusercontent.com/12657201/65583851-91c55900-df9d-11e9-9fc0-cc77103c01f2.png)

### Actual result (*)

1. In response, we get items data only.

**Comment by jigneshkhunt** [comment] 2019-09-25 08:46
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-25 08:46
Hi @jigneshkhunt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-25 08:47
Hi @jigneshkhunt, here is your [Magento instance](https://i-24719-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24719-2-3-develop.instances.magento-community.engineering/admin](https://i-24719-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jigneshkhunt** [comment] 2019-09-25 08:54
Reproduced on 2.3.x

**Comment by jigneshkhunt** [comment] 2019-09-25 09:06
> Hi @engcom-Charlie. Thank you for working on this issue.
> In order to make sure that issue has enough information and ready for development, please read and check the following instruction: 
> 
> * [ ]  1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).DetailsIf the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.
> * [ ]  2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.
> * [ ]  3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
> * [ ]  4. Verify that the issue is reproducible on `2.3-develop` branchDetails- Add the comment `@magento give me 2.3-develop instance` to deploy test instance on Magento infrastructure.  - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
> * [ ]  5. Add label `Issue: Confirmed` once verification is complete.
> * [ ]  6. Make sure that automatic system confirms that report has been added to the backlog.

Yes, i am able to reproduce the issue on vanilla Magento instance using given steps.

**Comment by magento-engcom-team** [comment] 2019-09-25 09:06
Hi @jigneshkhunt. Thank you for your request. I'm working on Magento 2.3-develop instance` to deploy test instance for you

**Comment by jigneshkhunt** [comment] 2019-09-25 09:07
> able to reproduce the issue on vanilla Magento instance

Yes, I am able to reproduce the issue on vanilla Magento instance using given steps.

**Comment by jigneshkhunt** [comment] 2019-09-25 09:08
> Hi @jigneshkhunt. Thank you for your report.
> To help us process this issue please make sure that you provided the following information:
> 
> * [ ]  Summary of the issue
> * [ ]  Information on your environment
> * [ ]  Steps to reproduce
> * [ ]  Expected and actual results
> 
> Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue:
> 
> `@magento give me 2.3-develop instance` - upcoming 2.3.x release
> 
> For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#contributor-assist) documentation.
> 
> @jigneshkhunt do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?
> 
> * [x]  yes
> * [ ]  no
> 
> * Join [Magento Community Engineering Slack](http://tinyurl.com/engcom-slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

Yes, I am able to reproduce the issue on vanilla Magento instance using given steps.

**Comment by magento-engcom-team** [comment] 2019-09-25 09:08
Hi @jigneshkhunt. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-25 09:08
Hi @jigneshkhunt, here is your [Magento instance](https://i-24719-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24719-2-3-develop.instances.magento-community.engineering/admin](https://i-24719-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-09-25 09:53
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20444` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jigneshkhunt** [comment] 2019-09-25 10:09
I am working on it.

**Comment by luanalves** [comment] 2020-04-04 19:05
PR created https://github.com/magento/magento2/pull/27591

**Comment by engcom-Bravo** [comment] 2024-11-04 05:25
Hi,

Since the Related PR's has been closed we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-11-04 05:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Webapi, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Area: APIs
