### ISSUE TITLE
Multistore Layered Navigation shows attribute value from children product on another store

### ISSUE THREAD

**Issue by oceane410** [magento/magento2#38112] opened 2023-10-23 13:26 UTC
### Preconditions and environment

- Magento 2.4.3
- Multistore website

### Steps to reproduce

1 . Create one configurable product in store A and B
2. Create some child product for this product, but at least one product is created only on store B and as a new value for one attribute (ex : color)
3. Reindex
4. Go on category page in store A

### Expected result

We should see in the color filter only the values that actually exist in store A

### Actual result

The color filter shows all values available in the configurable product without excluding values that are specific to store B.

### Additional information

I made a patch that forced the catalogsearch_fulltext indexer to take values from children's products that are available in the current store and ignore the others.
After reindex I have the correct values available on each of the stores.

[fix-multistore-indexer-layernavigation.txt](https://github.com/magento/magento2/files/13070807/fix-multistore-indexer-layernavigation.txt)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-25 10:40
Hi @oceane410,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create one configurable product in store A and B
- Create some child product for this product, but at least one product is created only on store B and as a new value for one attribute (ex : color)
- Reindex
- Go on category page in store A


<img width="986" alt="Screenshot 2023-10-25 at 3 02 18 PM" src="https://github.com/magento/magento2/assets/51680745/1d03c40a-81ff-42c4-b9cd-d37a3ff17ac6">



<img width="1005" alt="Screenshot 2023-10-25 at 3 02 26 PM" src="https://github.com/magento/magento2/assets/51680745/c450a457-ad06-4a21-953d-ec9784c78e9b">




We are able to see the color filter only that exists in other store.



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-07 06:13
Hi @oceane410,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38112#issuecomment-1778985960 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-13 05:54
Hi @oceane410,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-13 05:54 UTC
Labels: Issue: needs update, Reported on 2.4.3
