### ISSUE TITLE
Magento 2 Import

### ISSUE THREAD

**Issue by kingdominteriors** [magento/magento2#2590] opened 2015-12-03 13:21 UTC
Hi,

I have setup an attribute that allows for multi options to be selected. When I go into a product an assign  multiple options and save that product it works fine. But if I try to import this information via import (CSV File) it comes up with the following error:

Value for 'supplier_collection' attribute contains incorrect value, see acceptable values on settings specified for Admin in rows: 1

It seems to accept the values fine if it is just 1 option but if i want to select 2 I have to do this manually.

Any help would be much appreciated.

Kind regards

Brian

**Comment by yaronish** [comment] 2016-01-15 08:37
@kingdominteriors 
Can't reproduce on latest develop branch. 
I can successfully create product with multiple select attribute and assign few options to it.
After export to CSV file, my attribute appears in column additional_attributes in next format: `multiselectattr=a|b` where 'a' and 'b' options of my attribute.
After import just exported CSV file options 'a' and 'b' correctly assigned to 'multiselectattr' for my product.

I can suggest that you have incorrect format your multiselect's options are represented in CSV file.

Please verify your issue on latest develop and let me know if it still exists.

Thanks.

**Comment by vzabaznov** [comment] 2016-03-12 09:28
@kingdominteriors  I'm closing the ticket since there is no response for more than 2 weeks.
Please feel free to reopen if you have any questions

**Closed as completed by vzabaznov** 2016-03-12 09:28 UTC
