### ISSUE TITLE
Interlaced PNG images are not resized, placeholder shown instead with PHP 7.4.27

### ISSUE THREAD

**Issue by the-line** [magento/magento2#35038] opened 2022-01-31 11:12 UTC
### Preconditions (*)
1. Magento 2.4.3-p1
2. PHP 7.4.27

### Steps to reproduce (*)
1. Add a PNG image to a product and save it
2. View the product on the frontend or in the products list in the Admin environment

### Expected result (*)

1. Thumbnail of image is shown in Admin environment and Fotorama on frontend

### Actual result (*)

1. The default placeholder image is shown instead of the thumbnail

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Problem is that since PHP 7.4.27 the call to imagecreatefromstring will emit a warning Exception that is catched by Magento. Because of this exception, the image is not resized and the placeholder image is returned instead.

The Exception is thrown at /vendor/magento/framework/Image/Adapter/Gd2.php in the method open() at line 82:
```
$this->_imageHandler = call_user_func(
    $this->_getCallback('create', null, sprintf('Unsupported image format. File: %s', $this->_fileName)),
    $this->_fileName
);
```

The exception is catched in /vendor/magento/module-catalog/Helper/Image.php in the method getUrl() at line 556:
```

} catch (\Exception $e) {
    return $this->getDefaultPlaceholderUrl();        
}
```

A workaround is ignoring the error in /vendor/magento/framework/Image/Adapter/Gd2.php in the method open() at line 82:

```
@$this->_imageHandler = call_user_func(
    $this->_getCallback('create', null, sprintf('Unsupported image format. File: %s', $this->_fileName)),
    $this->_fileName
);
```

**Comment by hostep** [comment] 2022-01-31 14:24
Hmm, this might be related to https://bugs.php.net/bug.php?id=71316 (included in PHP 7.4.27, 8.0.14 & 8.1.0)
Looks like this can be triggered by an invalid color profile in the png file.
From first sound, this doesn't really look like a bug in Magento. If you upload an invalid image file, it makes sense that it gets refused and the placeholder is shown? I haven't looked deep into this yet, so maybe I missed something. Feel free to provide more info!

But since this was a change in the GD library, you might be able to circumvent this by changing the image processor to ImageMagick (if you have the php `imagick` extension installed). It will also result in higher quality resized images in my experience.
Configuration setting for this is available under Stores > Configuration > Advanced > Developer > Image Processing Settings > Image Adapter (in developer mode), or via `bin/magento config:set dev/image/default_adapter IMAGEMAGICK` (in production mode, can be reverted by restoring it back to `GD2`)

**Comment by the-line** [comment] 2022-01-31 15:51
Is is related to that specific PHP change.

It can be triggered by a invalid color profile. That should trigger a exception as it does now.

It also happen when a interlaced PNG image is read. The exception I got was:
gd-png: libpng warning: Interlace handling should be turned on when using png_read_image

Although it is correct that in GD the method png_set_interlace_handling should be called first, PHP doesn't do this.

The problem is that GD will automatically call this method and process the image correctly and emit a warning. This warning will throw a Exception in the latest PHP versions. Previous versions will ignore this warning, thus not giving any exception.

The exception is thrown by the PHP method imagecreatefrompng(), so I think than PHP doesn't call png_set_interlace_handling  while it should.

Also, the image isn't invalid, as far as I know.

Good to know that ImageMagick can be used instead. I will check if this is a good solution for our website.

**Comment by engcom-November** [comment] 2022-02-22 07:55
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Uploaded PNG image for a product and Thumbnail of image is shown every where - No issue
![image](https://user-images.githubusercontent.com/60198231/155087061-c13c6f84-09f9-423e-8ab3-4379b3f4ec86.png)
![image](https://user-images.githubusercontent.com/60198231/155087108-3aff8a62-921d-4b13-bd32-6e6e7347d438.png)
@the-line kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by the-line** [comment] 2022-02-22 16:53
Try it with the following image:
https://www.dchaircosmetics.com/media/catalog/product/cache/bfb4627d111a798e98fdfb011538d81c/b/o/boef-hairfiber-.png

Also, it only happens with PHP 7.4.27 or newer.

**Comment by the-line** [comment] 2022-02-23 08:59
@magento give me 2.4-develop instance

**Comment by the-line** [comment] 2022-02-23 09:45
@magento give me 2.4-develop instance

**Comment by the-line** [comment] 2022-02-23 15:36
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-02-25 11:51
Verified the issue on Magento 2.4-develop branch having PHP version 7.4.27 with above image but cannot able to reproduce the issue.
![image](https://user-images.githubusercontent.com/60198231/155710575-e64cdcb2-58c0-4dc3-bf65-0321dd3629eb.png)

![image](https://user-images.githubusercontent.com/60198231/155710538-02ea1252-5371-4aca-b8c9-eae9f00355e2.png)

![image](https://user-images.githubusercontent.com/60198231/155710499-e02b5737-94fa-4e53-8e26-d9424b4ddb58.png)
@the-line kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you

**Comment by engcom-November** [comment] 2022-03-10 12:37
Hi @the-line ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-10 12:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3-p1
