### ISSUE TITLE
Bulk API requests 'Maximum items of type "%type" is %max'

### ISSUE THREAD

**Issue by ThisIsRuddy** [magento/magento2#34154] opened 2021-09-24 10:58 UTC
### Preconditions (*)
1. Magento 2.4.3
2. MSI Enabled
2. Catalog Items > 20

### Steps to reproduce (*)
1. Attempt to post bulk API source-items request with greater than 20 items `{{MAGE_BASE_URL}}/rest/async/bulk/V1/inventory/source-items`
Or send POST request to /rest/V1/inventory/source-items with more than 20 product items
```
[
    {
        "sourceItems": [
            {
                "sku": "CH-380-4325",
                "source_code": "CREDEN",
                "quantity": 1,
                "status": 1
            }, 
            ...(20 more items)...
        ]
    }
]
```

### Expected result (*)
1. Requests processed with 20+ items

### Actual result (*)
1. Response error 'too many items'
```
{
    "message": "Maximum items of type \"%type\" is %max",
    "parameters": {
        "type": "\\Magento\\InventoryApi\\Api\\Data\\SourceItemInterface",
        "max": 20
    }
}
```

I have found the message in the following file but there is no mention of how to increase the default max items for this type either in the code or via the documentation. I only saw 1 mention of bulk on the 2.4.3 release notes which was no relevant to this.
`vendor/magento/framework/Webapi/Validator/EntityArrayValidator.php`

Any idea how I can extend this? Can the docs be updated?

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by hostep** [comment] 2021-09-26 17:13
Hi @ThisIsRuddy: can you check the following links: https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html#apply-mc-43048__set_rate_limits__243patch-to-address-issue-with-api-rate-limiting & https://support.magento.com/hc/en-us/articles/4406893342093.
The second link contains a patch that is most likely going to solve your issue.

I'm guessing that this will get solved as well in Magento 2.3.7-p2 and 2.4.3-p1 which are [to be released in about 3 weeks](https://devdocs.magento.com/release/).

**Comment by ThisIsRuddy** [comment] 2021-09-27 09:32
@hostep cheers man ! 👍

**Comment by engcom-November** [comment] 2021-09-27 09:38
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:
post bulk API source-items request with greater than 20 items is not working:
Issue observed for below POST requests on adding category items more than 20
/rest/V1/inventory/source-items
/async/bulk/V1/inventory/source-items
**Reponse:**
`
{
    "message": "Maximum items of type \"%type\" is %max",
    "parameters": {
        "type": "\\Magento\\InventoryApi\\Api\\Data\\SourceItemInterface",
        "max": 20
    }
}
`

**Comment by engcom-Alfa** [comment] 2021-10-06 11:52
As per the Magento feature, limited the maximum items to 20, and if anybody wants to have it for more than this limit, surely they can use the given fix mentioned in the [above-comment](https://github.com/magento/magento2/issues/34154#issuecomment-927339385). Hence closing this issue.

In case of any issues relevant to Magento, kindly test in latest Magento version and report a bug with all detailed information like Preconditions, details steps to reproduce, expected and actual results along with screen shots / screen recordings possibly.

For any clarifications, you may take a look into the [Magento User Guide](https://docs.magento.com/user-guide/).

**Comment by hostep** [comment] 2021-10-06 14:56
@sdzhepa, @sidolov: @engcom-Alfa must be joking, do you guys know more about if a fix for this is coming in an upcoming version of Magento? Only having the ability to update 20 stock items at the same time using the API is a bit silly, right?

**Comment by engcom-Alfa** [comment] 2021-11-12 11:13
Thanks for your thoughts on this @hostep; We are going to cross check in 2.4.3-p1 version too and will re-discuss about the consideration of it!
Thanks

**Comment by ThisIsRuddy** [comment] 2021-11-12 14:51
> @sdzhepa, @sidolov: @engcom-Alfa must be joking, do you guys know more about if a fix for this is coming in an upcoming version of Magento? Only having the ability to update 20 stock items at the same time using the API is a bit silly, right?

Thisssss +1 - it's a bulk API endpoint not a standard one so it should have a lot higher default surely?

**Comment by sidolov** [comment] 2021-11-12 15:59
@hostep agree with you, thank you for highlighting this!

**Comment by hostep** [comment] 2021-11-15 12:05
@engcom-Delta: you do have the [MSI module](https://github.com/magento/inventory) installed, right? That one defines [the route](https://github.com/magento/inventory/blob/d8be487cedff1dcad64d20f3375a3ce28e08dc57/InventoryApi/etc/webapi.xml#L98-L103)? It's mentioned in the preconditions.
And in fact this issue was [already confirmed](https://github.com/magento/magento2/issues/34154#issuecomment-927697675) by your colleague @engcom-November, so not sure why you need to re-confirm this again?

**Comment by engcom-Delta** [comment] 2021-12-09 09:12
HI @hostep,
We verified this issue again in Magento 2.4 Develop with latest branch , Issue is reproducible. Hence added the label 'Issue confirmed'
.Please find the attached screenshot for reference.
![Response_400](https://user-images.githubusercontent.com/51681379/145367484-b313128a-76c4-418a-85f3-f32f7dae844d.JPG)

**Comment by amenk** [comment] 2021-12-16 12:52
Happens also for `PUT /rest/V1/products/attributes/test_attribute` with lots of options.

**Closed as completed** 2022-08-29 12:56 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: APIs
