### ISSUE TITLE
CatalogCategoryLink API Elasticsearch index not refreshed

### ISSUE THREAD

**Issue by nthurston** [magento/magento2#28073] opened 2020-05-01 18:24 UTC
### Preconditions (*)

1. Magento 2.3.4
2. Search Engine: Elasticsearch 6.0
3. Indexes: On Schedule

### Steps to reproduce (*)

1. Call catalogCategoryLink API to add a product to a category

### Expected result (*)

1. Product should be visible in the category after cron index

### Actual result (*)

1. Product is not visible in the category until a manual reindex of catalog_category_product index

**Comment by pmcnamaracpc** [comment] 2020-09-03 20:03
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2020-09-03 20:03
Hi @pmcnamaracpc. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by pmcnamaracpc** [comment] 2020-09-03 20:25
@magento-engcom-team give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment] 2020-09-03 20:25
Hi @pmcnamaracpc. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment] 2020-09-03 20:27
Hi @pmcnamaracpc, here is your [Magento instance](https://i-28073-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-28073-2-3-5-p2.instances.magento-community.engineering/admin_6e13](https://i-28073-2-3-5-p2.instances.magento-community.engineering/admin_6e13)
Login: `fe5b3c91` Password: `cecc68b427e4`
Instance will be terminated in up to 3 hours.

**Comment by pmcnamaracpc** [comment] 2020-09-03 20:41
So I'm able to setup the conditions with this product data, but looks that I can't setup the crontab on this instance to reindex by schedule.

Can you ssh to these temporary instances? Am not finding anything about that on the code contributions page on the wiki.

**Comment by pmcnamaracpc** [comment] 2020-09-04 19:06
I created separate magento instances on my own server to recreate the issue, where I can setup the cron as needed to replicate.

I was able to replicate the issue in 2.3.4. It does not seem to apply to 2.3.5-p1 or 2.3.5-p2. I have not tried on 2.4.0

1. I first setup demo data to have products
2. disabled Dotmailer mods since they broke swagger (https://github.com/dotmailer/dotmailer-magento2-extension/issues/557),
3. Set indexes to schedule, set search engine to elasticsearch 6.0
4. Went to swagger to use integrationAdminTokenServiceV1 to get an oauth token
5. Used catalogCategoryLinkRepositoryV1 to add a product to a category

Using catalogCategoryLinkRepositoryV1's put option, 
{
  "productLink": {
    "sku": "24-MB01",
    "position": 123450,
    "category_id": "10",
    "extension_attributes": {}
  }
}

This product was visibly in the category in the admin panel, but not in the category. I then tried moving a 2nd product via the admin panel instead of api, and cron reindex that as normal.

**Comment by pmcnamaracpc** [comment] 2020-09-11 17:41
I have confirmed this is also fixed on 2.4.0

1. Setup demo data
2. disabled dotmailer
3. setup cron, elasticsearch 7.x
4. used twoFactorAuthGoogleAuthenticateV1's post to get a token
5. catalogCategoryLinkRepositoryV1's put

{
"productLink": {
"sku": "24-MB01",
"position": 123450,
"category_id": "10",
"extension_attributes": {}
}
}

The cron's reindex showed the product in the category as intended. Seems this issue only affects outdated versions of Magento.

**Comment by nthurston** [comment] 2020-09-25 18:13
Closing as seems fixed in later versions per @pmcnamaracpc .

**Closed as completed** 2020-09-25 18:13 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.4
