### ISSUE TITLE
Theme with no static files won't get deployed

### ISSUE THREAD

**Issue by davidverholen** [magento/magento2#7569] opened 2016-11-25 15:28 UTC
see https://github.com/magento/magento2/issues/4725

### Preconditions

1. Magento 2.1.2

### Steps to reproduce

1. Create a new Theme with any parent
2. Do not add any static files

### Expected result

1. Theme will get deployed with static files from parent theme

### Actual result

1. theme does not get deployed
2. setup:static-content:deply --theme=Any/theme results in error

In the deploy command, the installed themes are determined by collecting all themes from all static files. If a theme does not have static files it will not get deployed

adding any static file to the theme can be used as a workaround

**Comment by donniesg** [comment] 2017-08-15 08:04
This problem is still around on 2.1.8. I have some child themes that only modifies layouts xml and not css are working fine in development mode but kept getting ignored by setup:static-content:deploy in production mode. Adding an empty.less file in web/css folder helps.

**Comment by appymedia** [comment] 2017-08-25 22:09
Same issue here.  I know its not the place to rant but whatever...  Magento 2 should not be marked production ready.  On a simple store setup I have ran into countless bugs, it borders on ridiculous.  Yes I use CE but I would have touched it had I known the state it was truly in.  I stupidly assumed because of the size of Magento and the time v2 had been in the wild it would be fine, my mistake.  I won't make the same mistake twice.

**Comment by orlangur** [comment] 2017-08-25 23:24
@appymedia well, I would not say this particular issue is a showstopper of any kind. There are quite a lot of companies successfully running live stores since 2.0 GA, so, it's just a matter of professionalism.

**Comment by appymedia** [comment] 2017-08-29 19:52
Professionalism? I will give you an example of lack of professionalism, this bug.  Reported NOV 2016, 9 month ago, yes 9 months later and it still exists and I STILL waste time finding this issue to resolve my problem.  I have done a similar process with circa 20 bugs getting my simple site live, most of the issues accepted and jus....well....still there....months and sometimes years in the wild, its what I said it was, ridiculous.  I am not alone.  You know when things are bad when you find stuff like this....

https://www.facebook.com/magentoissatan/

Can't wait to get away from it, should have just put together my own specific solution in the first place.  Might miss all the bells and whistles but I can build what I need over time and not suffer like this!

**Comment by orlangur** [comment] 2017-08-29 20:48
@appymedia I have no idea how trivial the fix is, however, as you see a simple workaround exists thus this bug obviously is not of high priority. More than that, theme without a single `.less` file is not so frequent situation.

**Comment by appymedia** [comment] 2017-08-29 21:08
9 months isn't low priority, its no priority.  An as I said this isn't the only bug I ran into.  What you hear from me here is the compound frustration of DAYS working into WEEKS of wasted time with bugs.  I'm a PHP dev in the day, I've commercially wrote code in c#, PHP, c, c++, assembly language etc for over 20 years.  Its not like I'm a super noob looking for a 'plug and play' solution.  I've also managed servers for over 10 years as well so environment issues I accept but as I keep repeating Magento needs to sort out what its doing and stop people believing this is stable.  Personally I think this is beta software and should be presented as such, GA, no way.

**Comment by orlangur** [comment] 2017-08-29 21:23
@appymedia I truly understand your frustration and would be a bit happier myself if Magento would not contain bugs at all. Just that I believe there are much more important issues among 2500+ reported and whoever knows how much existent than this particular one. Like problems with indexing, payment, shipping methods. 

Seeing a little wider picture I also notice how the things are moving in the right direction, main priorities to my understanding should be automated testing (especially for bugs to avoid regressions) and analyzing community feedback in a timely manner. Having all crucial scenarios covered with tests it is not possible to have buggy product, right? 😉

**Comment by appymedia** [comment] 2017-08-29 21:34
Indeed, completely agree.  I do think the GA was way too early.  An if they wanted to do it they should be fixing bugs like crazy because years later after release and after I talk with more dev's a lot of them are not having a great time and working round a lot of issues.  Could be fantastic software, just the handling of things.  Bring on the unit testing!

**Comment by korostii** [comment] 2017-08-31 12:19
> Having all crucial scenarios covered with tests it is not possible to have buggy product, right?

Well, you could still have some counter-intuitive and mind-blowing behavior treated as "intended". 
My favorite example so far: https://github.com/magento/magento2/issues/5299#issuecomment-311011178

Enforcing such backward behavior through tests won't help in any way, thus there's always room for human error causing bugs. (And, to go even further, the tests can have bugs in them. Would you mind covering your tests with some more tests?)

**Comment by korostii** [comment] 2017-08-31 12:29
Also, technically there's over 8800 reported issues. Those 2500 are just the ones which aren't resolved yet. Neither of those numbers can help you understand whether the "things are moving in the right direction"

I found the following filter to be more informative:
https://github.com/magento/magento2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A2.1.x%20label%3Aacknowledged%20

There are more than 700 of issues admitted to be present on current stable branch (2.1.x). Among those, in its one year of existence, only 200 got fixed (add to that the fact some of these fixes aren't even released and stay on branch develop).

I would say that fixing *half a bug per day* on the average isn't good enough.

**Comment by hostep** [comment] 2017-08-31 17:58
To add some constructive feedback, I believe this is a duplicate of https://github.com/magento/magento2/issues/3754 which got fixed in the develop branch with [MAGETWO-52102](https://github.com/magento/magento2/commit/6a9744dcd6d99cd65992374198df82fdb1eac758)

**Comment by orlangur** [comment] 2017-08-31 18:24
@hostep great, thanks for your finding :wink: It's much more advisable to check if the issue is still present in `develop` branch than write another dozen of "useful" comments on how slow Magento is in fixing bugs.

@appymedia,
> Reported NOV 2016, 9 month ago, yes 9 months later and it still exists and I STILL waste time finding this issue to resolve my problem.

It was fixed in Jun 2016 actually, FIVE months before this issue creation. All what was needed to figure this out was to check same steps against installation from `develop` branch. However, at that time process of `2.1.x` bugfixes contribution did not exist yet and according to old process this issue would be simply closed with "fixed in `develop`" remark. 

Now such process is established and any constructive community member may make Magento better for himself and others.

**Comment by appymedia** [comment] 2017-08-31 21:29
Ok, since we are determined to keep harping on about this.

The issue is not fixed, having it fixed in a develop branch doesn't help if you want to grab a stable package and get running.  So I guess what I should have done is visit the Magento site and using my future seeing ability assume the develop branch on github is the way to go, my mistake.

I'm betting you don't actually work in the commercial world.  If you did you would know time is money, we don't have days to setup dev environments to diagnose and test Magento bugs.  Actually being fair I might have if it was 1-2 bugs but seriously I shit you not I ran into them daily.  My last count was 23 issues.  I mean WTF?  In a major release thats over a year old?  Never had that happen with ANY other piece of software.

Think what you want and be as deluded as you like.  If you enjoying sifting though github, good for you.  I enjoy getting on and making great experiences for my clients.  As I told you I'm not a noob dev, my mistake was thinking Magento could save me time.  Instead I lost a lot of time and flexibility because of the bugs and not to mention the ohhhh soooo MANY layers and technologies being employed in Magento.  It is an advertisement for like every web tech and design pattern you can find?  I don't have 6 months to spend learning the Magento way.  I've used a LOT of other web frameworks in my time and been able to get in and stuff done but forget it with Magento.

Potentially a good product however too buggy for production (sorry, it is) and too complex for an SME who need to react fast and don't have 6 months to waste learning it to perform basic stuff.

My original point stands Magento should never have released it in its current state, its beta.  You are beta testing, enjoy!

**Comment by magento-team** [comment] 2017-09-06 14:32
Internal ticket to track issue progress: MAGETWO-72253

**Comment by magento-engcom-team** [comment] 2017-10-06 16:13
Hi @davidverholen the issue has been fixed in 2.1.10 and will be available soon

**Closed as completed by magento-engcom-team** 2017-10-06 16:13 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Fixed in 2.1.x, Issue: Format is valid
