### ISSUE TITLE
product grid select all -> update attributes not working for all selected products

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#23110] opened 2019-06-03 13:17 UTC
### Preconditions (*)
1. Magento 2.3.1 
2. A good amount of products to test

### Steps to reproduce (*)
1. Set the grid limit to a number below the full number of products in the store. 
2. E.g. you have 21 products and the grid size is 20 rows. 
3. Click on checkbox -> select all 
4. Click on update attributes 
5. Update any attribute 

You will see that only the products that are shown are saved as if you clicked just select the visible ones. 

### Expected result (*)
All selected products get updated.

### Actual result (*)
Only visible products are updated. 

![2019-06-03_16-13-01](https://user-images.githubusercontent.com/20220341/58804620-f3db0680-861a-11e9-8f73-8bb38c786c9d.gif)

**Comment by ioweb-gr** [comment] 2019-06-03 13:17
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-03 13:17
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-03 13:18
Hi @ioweb-gr, here is your [Magento instance](https://i-23110-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23110-2-3-develop.instances.magento-community.engineering/admin](https://i-23110-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment] 2019-06-03 13:24
OK in develop instance this behaviour has changed compared to 2.3.1. It's now saying the message was added to queue instead of how many products are saved however I cannot test if it actually works because the actual process hasn't been executed after a few minutes. Perhaps on the  test instance the message queue is not functioning properly.

**Comment by AlexWorking** [comment] 2019-06-03 13:45
Hi @ioweb-gr. Thank you for your report. This issue is a duplicate of at least #22986. So we are supposed to close it.

**Closed as completed by AlexWorking** 2019-06-03 13:45 UTC
Labels: Issue: Format is valid
