### ISSUE TITLE
No spaces available between attributes of the critical path CSS links

### ISSUE THREAD

**Issue by onepack** [magento/magento2#27327] opened 2020-03-18 09:58 UTC
### Preconditions (*)

1. PHP 7.2
2. Magento 2.3.4

### Steps to reproduce (*)

1. Enable the CSS critical path
2. Check the source of the page

### Expected result (*)

1. Expected to see the correct critical path URLs
2. 

### Actual result (*)

1. I get an error in Firefox sourcecode of the page that there are no spaces available between attributes of the critical path CSS links
2. Example:
```
<link rel="preload" as="style" media="all" .
                         onload="this.onload=null;this.rel='stylesheet'"href="https://www.domain.coml/pub/static/version1584400998/_cache/merged/eab50c6fab344632384864f164c807d1.min.css">
<link rel="preload" as="style" media="screen and (min-width: 768px)" .
                         onload="this.onload=null;this.rel='stylesheet'"href="https://www.domain.com/pub/static/version1584400998/frontend/Vendor/theme/us_US/css/styles-l.min.css">


```

**Comment by maheshWebkul721** [comment] 2020-03-18 11:23
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-18 11:23
Hi @maheshWebkul721. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by mrtuvn** [comment] 2020-03-18 13:37
@onepack This problem already fixed in https://github.com/magento/magento2/pull/26764

**Comment by engcom-Lima** [comment] 2020-07-23 13:17
Hello @onepack 
I'm not able to reproduce issue by steps you described on clean 2.4-develop. I have no any errors in console.
![Screenshot_53](https://user-images.githubusercontent.com/60198022/88290808-f9ece480-ccff-11ea-9745-8d236804c250.png)
Looks like this issue was fixed in  https://github.com/magento/magento2/pull/26764

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Lima** 2020-07-23 13:17 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
