### ISSUE TITLE
B2B quick order not working with Gift Card product type

### ISSUE THREAD

**Issue by rahulbarotk** [magento/magento2#33258] opened 2021-06-16 11:55 UTC
B2B quick order add to cart throws error when gift card is added.

**Preconditions (*)**
- Magento 2.4.2 EE installed
- B2B modules are installed

**Steps to reproduce (*)**
- Enable Quick order in B2B configuration
- On frontend quick order page add gift card sku in **Enter SKU or Product Name** field
- Then click on Add to Cart

**Expected result (*)**
- It should redirect to cart page with warning 1 product requires your attention.

**Actual result (*)**
- It redirects to following url "http://local.m242ee.com/quickorder/sku/uploadfile/" and shows error as below in the browser. 

`Error: Call to undefined method Magento\Catalog\Api\Data\ProductExtension::getDiscounts() in /var/www/html/m242ee/vendor/magento/module-sales-rule/Model/Quote/Discount.php:284 Stack trace: #0 /var/www/html/m242ee/vendor/magento/module-sales-rule/Model/Quote/Discount.php(176): Magento\SalesRule\Model\Quote\Discount->aggregateDiscountPerRule() #1 /var/www/html/m242ee/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(274): Magento\SalesRule\Model\Quote\Discount->collect() #2 /var/www/html/m242ee/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals() #3 /var/www/html/m242ee/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callParent() #4`

Severity: **S0**

Check [this](https://www.awesomescreenshot.com/video/4149846?key=52390b1a60334a2acba817718538d0df)

**Comment by engcom-November** [comment] 2021-08-25 10:09
Verified the issue on Magento 2.4-develop branch having EE and B2B Modules enabled and the issue is not reproducible.
**Steps performed:**
Enable Quick order in B2B configuration (Stores - Configuration - General - B2B Features - Enable Quick Order and save)
Create a Gift Card from Admin - Catalog - Prodicts - Add Gift Card and Save
Reindex and Clear Cache
Front end - Quick Order - Enter Product Sku - Add to Cart
No issue: redirected to cart page with warning 1 product requires your attention.
![image](https://user-images.githubusercontent.com/60198231/130771584-d115b247-0f79-42e8-b783-5b2407484660.png)
![image](https://user-images.githubusercontent.com/60198231/130771603-7a04c44e-ba80-4a16-8807-46750d3dccf6.png)

@DevAwesomeK Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-08 05:59
Hi @DevAwesomeK ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-08 05:59 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
