### ISSUE TITLE
customer-data.js error after login and adding item to cart

### ISSUE THREAD

**Issue by b-juszczyk** [magento/magento2#33079] opened 2021-05-26 11:08 UTC
### Preconditions (*)

1. Magento 2.4.2 after update from 2.3.4
2.

### Steps to reproduce (*)

1. Login as customer
2. Go to category view
3. Add item to cart

### Expected result (*)

1. Item is added to cart
2. No errors in console
3. Message about adding product to cart

### Actual result (*)

1. Error in customer-data.js (after login)
![image](https://user-images.githubusercontent.com/26605458/119649338-cb113480-be22-11eb-915a-34e7bd689253.png)

2. Error in customer-data.js (after adding to cart)
![image](https://user-images.githubusercontent.com/26605458/119649747-45da4f80-be23-11eb-8e74-9edf11f4fa6b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by darvin55** [comment] 2021-05-26 11:08
@magento give me 2.4-develop instance

**Comment by darvin55** [comment] 2021-05-26 12:17
It is strange that variable `sectionNames` in customer-data.js (line 80, 81) looks like this:
![image](https://user-images.githubusercontent.com/26605458/119658095-09135600-be2d-11eb-8574-2e192ca23078.png)

**Comment by darvin55** [comment] 2021-05-26 12:20
I am not able to re-produce it also, but I can give you all informations about it if you want.

**Comment by engcom-Echo** [comment] 2021-05-26 12:22
Hi @darvin55 ,

If you are not able to reproduce the issue on latest 2.4-develop branch then it might have been fixed in interim releases. In that close we would be closing this issue . Let us know if you need any other details from us.

Thanks

**Closed as completed** 2021-05-28 05:39 UTC
Labels: Issue: needs update

**Comment by darvin55** [comment] 2021-05-28 05:40
The problem was that when call `customerData.reload()` in custom JS, i was passing `messages` as a string, not as an array.
