### ISSUE TITLE
Magento 2 Installation Stops at 0%

### ISSUE THREAD

**Issue by getrengcle** [magento/magento2#2942] opened 2016-01-09 12:45 UTC
Okay, after 4 years of waiting, finally Magento 2 is available. Yay!
Upgraded my PHP to 5.6.16 and  MySQL to 5.6.21 and Apache to 2.2.31
Tried to install on my VPS, running CENTOS 6.7
Passed readiness check.
Then when installing, it stops right at 0%

It says:
Installation is incomplete. 
Check the console log for errors before trying again.

Console log says:
Starting Magento installation:
File permissions check...
Enabling Maintenance Mode...
Installing deployment configuration...

It's lacking of information.
I've read about https://github.com/magento/magento2/issues/815, tried all the pointers there, but nothing solved my case.

Please help, I'm a newbie.
![20160109](https://cloud.githubusercontent.com/assets/16622932/12216082/f4257056-b708-11e5-8fe2-d9ade3396c1e.jpg)

**Comment by ghost** [comment] 2016-01-09 15:36
Two suggestions: look in your web server logs and try installing via [command line](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli.html). Either way, you might see better errors.

**Comment by mazhalai** [comment] 2016-01-11 15:03
@getrengcle you can enable developer mode by running this command in your console. This will give your more stack trace errors: `<magento root>/bin/magento deploy:mode:set developer`

**Comment by daim2k5** [comment] 2016-01-30 23:20
@getrengcle i close the issue because you didn't answered. If you have still the problem please reopen the issue.

**Closed as completed by daim2k5** 2016-01-30 23:20 UTC

**Comment by alihashir** [comment] 2016-02-01 13:33
I am new to magento...and installing it on my local Wamp server... i am last step and installation stops at 65% ...see the following screenshoot and please help me how to fix it...Thanks.
![megento](https://cloud.githubusercontent.com/assets/15688053/12718728/47f88d6a-c912-11e5-8e79-b31cf7579574.PNG)

**Comment by mazhalai** [comment] 2016-02-01 14:41
@alihashir please do not post on closed issues. This issue is caused by you php `session.save_path` setting in your php.ini file. It is not readable by the apache user. Please create `tmp/` folder and give required permissions, or change the setting to point to another writable folder.

**Comment by akshay-vyas** [comment] 2018-09-30 10:10
Starting Magento installation:
File permissions check...

Required extensions check...


and it stops there

**Comment by amustci065** [comment] 2018-12-23 20:00
Im very new to Magento, Would really appreciate everyones here. been trying to install for the past 2 days now.  Installation stops at 69% 
![installation issue](https://user-images.githubusercontent.com/33057348/50387154-b9794f00-06f5-11e9-90a4-4ec5bbebca3f.png)
![installation issue -2](https://user-images.githubusercontent.com/33057348/50387175-77044200-06f6-11e9-9fda-40ff72f3f9e3.png)

**Comment by DanielRuf** [comment] 2018-12-25 12:50
> please do not post on closed issues

Please open new issues.
