### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'const'

### ISSUE THREAD

**Issue by rathodsunny005** [magento/magento2#35562] opened 2022-06-01 08:24 UTC
### Preconditions and environment

- Magento version 2.4.4
- Production mode
- without sample data
- with the below configurations

```
Merge Javascript file: Yes
Enable javascript bundling: No
Minify javascript file: Yes
```

### Steps to reproduce

Just open the backend (admin) panel you will see this error, in-fact mostly the admin side pages gets this error.

### Expected result

open admin side pages without any js error.

### Actual result

Got the JS error pls find attached a screenshot.

![image](https://user-images.githubusercontent.com/7411684/171360472-27c5f04e-c806-4b12-be6d-01203f06a435.png)

### Additional information

Due to this error, Google 2FA is not working, getting screen without google auth textbox.
pls check screenshot.

![image](https://user-images.githubusercontent.com/7411684/171360897-4fd9cac8-3066-4e2d-9820-8da53c12a369.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-02 06:05
Hi @rathodsunny005 ,
This issue is a duplicate of https://github.com/magento/magento2/issues/35325 and fixed in commit: https://github.com/magento/magento2/search?q=AC-2880&type=commits. We are closing this issue. Please check for updates / solutions from above.
Thank you.

**Closed as completed by engcom-November** 2022-06-02 06:05 UTC
Labels: duplicate, Issue: ready for confirmation
