### ISSUE TITLE
Unable to checkout via Braintree with ReCaptcha V2 or V3 Invisible

### ISSUE THREAD

**Issue by n2diving-dgx** [magento/magento2#37241] opened 2023-03-19 23:40 UTC
### Preconditions and environment

Upon upgrading our production site from M2.4.5-p2 to M2.4.6 we discovered customers were unable to checkout via Credit Card using the Braintree Payments extension V4.5.0 bundled in to M2.4.6  The cause was found to be the ReCaptcha V3 security enabled on the Credit Card checkout.

See detailed steps below to reproduce the issue using a fresh unaltered M2.4.6 install with Luma Store sample data and Braintree sandbox credentials with ReCAPTCHA V3 Invisible security.   If you wish you may repeat test using ReCAPTCHA V2 Invisible security, hung result is the same as with V3.

Only workaround to protecting checkout using Braintree Credit Card Payment method is reCAPTCHA V2 (I'm not a robot) challenge.  According to Google this is the least secure of the three ReCAPTCHA options.

```
Building Magento 2.4.6
+ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
+ /usr/local/apache/bin/httpd -v
Server version: Apache/2.4.46 (Unix)
Server built:   Jun 16 2021 21:29:21
+ mysql -V
mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)
+ php -v
PHP 8.1.17 (cli) (built: Mar 17 2023 09:39:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
+ php /usr/local/bin/composer -V
Composer version 2.3.5 2022-04-13 16:43:00


```

### Steps to reproduce

Fresh Install of M2.4.6 in environment as above
Login to backend

Nav to Admin>Stores>Configure>General>Web>Default Cookie Settings
If necessary, set the Cookie Domain to the appropriate domain value (so you will be able to login on front end)
Save Config
Nav to Admin>Stores>Configure>Security>Google reCAPTCHA Storefront 
Enter known valid credentials for Google Recaptcha V2 (robot), V2 (invisible), and V3.
On Storefront Enable Customer Login and Braintree payment form for reCAPTCHA V2 (I am not a robot)
Save Config
Nav to Admin>Stores>Configure>Sales>Payment Methods
Select Merchant Country as United States and Save Config
Configure Braintree Payments (by GENE Commerce v4.5.0) 
Enter known valid sandbox credentials for Merchant ID, Public Key, Private Key and Validate Credentials
Enable Card Payments = Yes and Save Config 
Flush Magento Cache

On Frontend, successfully Sign In using Demo Customer Access credentials
Answer ReCaptcha "I'm not a robot." challenge
Add Affirm Water Bottle to cart
Proceed to Checkout
Shipping Method select Fixed Flat Rate 
Payment Method select Credit Card
Enter Card # 4111 1111 1111 1111   Expiration: 12/2023  Security Code: 123
Answer ReCaptcha "I'm not a robot." challenge
Click blue "Place Order" button
Observe "spinner" appears for a moment and then automatically redirects to
"Thank you for your purchase!" success page with order number
Logout of Customer Account

Return to backend
Nav to Admin>Stores>Configure>Security>Google reCAPTCHA Storefront> Storefront
Change Enable Customer Login and Braintree payment form to reCAPTCHA V3 Invisible and Save Config
Flush Magento Cache

On Frontend, successfully Sign In using Demo Customer Access credentials
Verify "Protected by reCAPTCHA" badge appears next to "Sign In" button
Add Affirm Water Bottle to cart
Proceed to Checkout
Shipping Method select Fixed Flat Rate 
Payment Method select Credit Card
Enter Card # 4111 1111 1111 1111   Expiration: 12/2023  Security Code: 123
Verify "Protected by reCAPTCHA" badge appears to the left of "Place Order" button
Click dark blue "Place Order" button
Place Order button turns light blue and ...
Order Page is HUNG, UNABLE TO PLACE ORDER using ReCAPTCHA V3 Invisible security

### Expected result

Upon clicking Place Order button, the order is placed successfully with ReCAPTCHA V3 Invisible security enabled on Braintree Credit Card payment method, customer is redirected to the success page.

### Actual result

Upon clicking dark blue Place Order button, the button turns light blue and order page is HUNG, unable to place order with ReCAPTCHA V3 Invisible security enabled on Braintree Credit Card payment method, and Customer is NOT redirected to the success page

### Additional information

The issue appears to only affect protecting Braintree Credit Card payment method with reCAPTCHA, in the limited testing of an frontend Customer Sign In using any version of reCAPTCHA does not appear to affect the login.

Checkout via Credit Card protected with ReCAPTCHA V3 Invisible security was working correctly for M2.4.5-p2 in both production and sandbox environments.  I also tested M2.4.6 using our Braintree production credentials instead of sandbox, but there was no difference using either set of credentials - the Place Order hangs and attempting to place an order protected with either version of V2 or V3 Invisible ReCAPTCHA fails.  

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by n2diving-dgx** [comment] 2023-03-20 00:19
I would appreciate it if some other user with different Google reCaptcha and Braintree credentials would test in their environment to see if the issue with protecting Braintree checkout via credit cards as described above is reproduceable on M2.4.6

**Comment by engcom-Dash** [comment] 2023-03-20 07:19
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-03-20 08:34
Hi @n2diving-dgx ,

**_Issue Confirmed !_**

Verified the issue in 2.4-develop instance and 2.4.6 magento instance and its reproducible,Hence we are confirming the issue.

**_Preconditions:_**
Magento Version 2.4-develop
Magento version 2.4.6
PHP version 8.1

**_Steps to reproduce:_**

1.Install Fresh 2.4.6 Magento instance
2.Go to Backend and Configuration and Security
3.Select Google recaptcha Store Frontend
4.Enter API website and Secret key of _**Recaptcha invisible v3**_
5.Save Configuration and clear cache.
6.Again go  to Configuration and Sales and Payment methods
7.Select Braintree Payment Configuration 
8.Enter Public key ,Private key and validate the credentials and enable card payment
9.save Configuration and clear cache
10.Go to front login with customer
11.Select any product and place the order with Credit card and enter card details as per main description
12.Trying to place order with Recaptcha invisible with v3

**_Kindly refer the below screenshots_**:( **Recaptcha Invisible v3**)
<img width="1512" alt="re2" src="https://user-images.githubusercontent.com/60198592/226280912-1a8c656d-4982-40cb-868a-11121f655dec.png">
<img width="1512" alt="re3" src="https://user-images.githubusercontent.com/60198592/226280960-b5b2df68-946b-4148-9b7e-c7cbeec122e2.png">
<img width="1512" alt="re4" src="https://user-images.githubusercontent.com/60198592/226280995-adcf7aba-adb2-4835-82ef-b6bbff939dae.png">
<img width="1512" alt="re6" src="https://user-images.githubusercontent.com/60198592/226281135-088bcecb-c819-4bc2-8c00-e10f0b58b038.png">

In magento 2.4.6 version Order Page is HUNG, **_UNABLE TO PLACE ORDER_** using **_ReCAPTCHA V3_** Invisible security.Same thing we are trying to reproduce in 2.4-develop instance and we can place the order successfully.

_**Kindly refer the below screenshots:**_

<img width="1512" alt="re7" src="https://user-images.githubusercontent.com/60198592/226282005-423ee9ec-a905-4234-8196-15fba803f425.png">
<img width="1512" alt="re8" src="https://user-images.githubusercontent.com/60198592/226282091-7cccc9fb-58b9-44b0-a36b-4a04ef480f06.png">

In 2.4-develop instance we can place the order successfully both **_RECAPTCHA V2 AND INVISIBLE V3_** But We in magento 2.4.6 instance we got Actual result as per the description,Hence we confirming the issue.

Regards,

**Comment by engcom-Hotel** [comment] 2023-03-21 12:06
@engcom-Dash As per the discussion in triage call, we need to recheck this issue.

Thanks

**Comment by rostilos** [comment] 2023-05-12 09:17
@magento I am working on this

**Comment by JosephLeedy** [comment] 2023-06-01 13:19
Any updates on this?

**Comment by mamsincl** [comment] 2023-06-14 15:15
+1 please

**Comment by bosskar231** [comment] 2023-07-05 09:56
Hi,
is there any patch available now for this issue.

**Comment by colyield** [comment] 2023-07-26 08:29
+1 Got the same problem. Waiting for a solution.

**Comment by itaymesh** [comment] 2023-08-02 09:46
+1 
is there any patch available now for this issue?

**Comment by colyield** [comment] 2023-09-05 05:40
Upgraded to 2.4.6p2, problem is still there. And just noticed that the "I am not a robot" v2 Recapcha actually is not working at all. Even if the checkbox is not checked, still can make the payment successfully..

**Comment by ThisIsRuddy** [comment] 2023-09-08 15:43
Just spent 2 days trying to find what was causing our checkout to fail silently.

I finally arrived in the right place! 

Any update on this ridiculousness?

**Comment by ThisIsRuddy** [comment] 2023-09-11 09:42
I analysed the ACSD-50345_1.1.4-p1.patch and it only brings in a few changes from the upgraded re-captcha (1.1.3) which is already present in 2.4.6-p2 so no fix there I'm afraid.

**Comment by Amiga4ever** [comment] 2023-09-19 13:42
Still issue exist. I don't see any other way to block card attacks. Our big client on latest Magento build stil encounter it.. Please fix it.

**Comment by kartikmaniyar** [comment] 2023-09-22 18:14
Thank you everyone for your feedback!

Apologies for not getting any responses from the Magento/Adobe Team.

[GENE Commerce](https://www.gene.co.uk/) is responsible for developing the Magento Braintree extension. I would like to tell you that this ReCaptcha issue is already been fixed in Magento **v2.4.7-beta1** that has already been released on June 13, 2023. Here, you can find the v2.4.7-beta1 release notes for **Braintree**: https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-7.html?lang=en#braintree

We already have a patch for Google ReCaptcha v2 or V3 Invisible issue with Braintree in Magento/Adobe v2.4.6 and its patch versions. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227825-patch-for-unable-to-checkout-via-braintree-with-google-recaptcha-v2-or-v3-invisible-in-magento-v2-4-6-and-v2-4-6-p1-p2

Also if you have any technical issues or concerns regarding our Magento Braintree extension, you can reach out to us by raising a support ticket from here: https://support.gene.co.uk/support/home

**Comment by Amiga4ever** [comment] 2023-09-22 20:14
_"We already have a patch for Google ReCaptcha v2 or V3 Invisible issue with Braintree in Magento/Adobe v2.4.6 and its patch versions. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227825-patch-for-unable-to-checkout-via-braintree-with-google-recaptcha-v2-or-v3-invisible-in-magento-v2-4-6-and-v2-4-6-p1-p2"_

- how to implement this patch ?

**Comment by CHallski** [comment] 2023-09-23 01:41
@Amiga4ever Assuming you're using a deploy structure that leverages cweagans (or similar module like vaimo) for patch installation, it's as straightforward as downloading that patch, adding it to your patches folder, and adding the reference to your composer.patches.json. At that point it'll be picked up and applied the next time you run _composer install_.

If not then you'd have to manually apply it (git apply <patchfile>), but that won't survive for very long (any reinstall of vendor will wipe it out), so I'd only do that in a local test environment.

I've just tested this locally with a 2.4.6-p2 instance we were prepping and the patch does resolve the issue (makes sense, it's basically a clone of the relevant portion of ACSD-50345 to `magento/module-re-captcha-checkout/view/frontend/web/js/model/place-order-mixin.js`, applied to the Braintree core module mixin).

**Comment by matejslo** [comment] 2024-03-26 19:08
> _"We already have a patch for Google ReCaptcha v2 or V3 Invisible issue with Braintree in Magento/Adobe v2.4.6 and its patch versions. You can download the patch from this link: https://support.gene.co.uk/support/solutions/articles/35000227825-patch-for-unable-to-checkout-via-braintree-with-google-recaptcha-v2-or-v3-invisible-in-magento-v2-4-6-and-v2-4-6-p1-p2"_
> 
> * how to implement this patch ?


This patch dosen't work in my situation.

**Comment by digitalrisedorset** [comment] 2024-05-01 08:05
@magento I am working on this

**Comment by digitalrisedorset** [comment] 2024-05-01 08:36
Can I check whether we want to fix this issue on 2.4.7? or on develop? This issue has been here for a while and before I start, I'd like to understand what is the most recent situation with this issue. Also, on develop environment, I can't see any reCaptcha modules

**Comment by engcom-Dash** [comment] 2024-05-13 12:11
HI @n2diving-dgx 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4.7 instance but the issue is not reproducable.

Steps to reproduce:

1.Install Fresh 2.4.7 Magento instance
2.Go to Backend and Configuration and Security
3.Select Google recaptcha Store Frontend
4.Enter API website and Secret key of Recaptcha invisible v3
5.Save Configuration and clear cache.
6.Again go to Configuration and Sales and Payment methods
7.Select Braintree Payment Configuration
8.Enter Public key ,Private key and validate the credentials and enable card payment
9.save Configuration and clear cache
10.Go to front login with customer
11.Select any product and place the order with Credit card and enter card details as per main description
12.Try to place order with Recaptcha invisible with v3

We are able to place the order with creditcard and Recaptcha invisible v3 successfully.

Please refer the attached screenrecording. Do let us know if we have missed anything.

https://github.com/magento/magento2/assets/60198592/0f29c2a5-4fd7-444d-90f4-cd3485fa9102

**Comment by digitalrisedorset** [comment] 2024-05-23 10:38
Apologies, I am a bit slow with this issue. I have a version installed remotely and with sample data and with security packages also. Now, for practical reasons, I will use the develop branch. The reason for me to use the develop branch is to resolve the issue on a place that will handle the version 2.4.7 and the coming version and the assumption I am making is these 2 versions are close enough for this scenario to be realistic.

**Comment by digitalrisedorset** [comment] 2024-06-11 08:12
I can also place order successfully with 2.4.7 and the same recaptcha setting as in the post, so I will unassign myself from this task

**Comment by engcom-Dash** [comment] 2024-06-17 08:23
Hi @n2diving-dgx 

As per the above comments, the issue is not reproducible in 2.4.7.

We are closing the issue.

Please feel free to reopen the ticket if the issue persists again.

**Closed as completed by engcom-Dash** 2024-06-17 08:23 UTC
Labels: Issue: Confirmed, Component: Braintree, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Admin UI, Reported on 2.4.6
