### ISSUE TITLE
[REST API] Translation issues with the customizable options on catalogProductRepositoryV1

### ISSUE THREAD

**Issue by teoteo** [magento/magento2#11141] opened 2017-09-29 15:01 UTC
### Preconditions
I can see the solved issue Translation issues with the customizable options #8251 
Setting options with Rest API for **store_views** the options are added to **all** scope
I use [PUT https://URL/index.php/rest/en/V1/products/{sku}](http://devdocs.magento.com/swagger/index_22.html)
on Magento version: Community edition 2.2

### Steps to reproduce
Set a Magento store with store views with short codes=**en** and **it**;
create a product with sku=10505c01010101a
#### Step 1
Send PUT request https://URL/index.php/rest/all/V1/products/010505c01010101a
```
{"product": {
    "options":[
      {
      "product_sku":"010505c01010101a",  
      "title":"License",
      "type":"radio",
      "sort_order":null,
      "is_require":true,
      "price_type":null,
      "values":[
        {
        "title":"Standard license ALL",
        "sort_order":1,
        "price":null,
        "price_type":"fixed",
        "sku":"standard"
        },
        {
        "title":"Royalty free license All",
        "sort_order":2,
        "price":60,
        "price_type":"fixed",
        "sku":"rf"
        },
        {
        "title":"Covers and advertising license ALL",
        "sort_order":3,
        "price":180,
        "price_type":"fixed",
        "sku":"adv"
        }
      ]}
    ]
  }
}
```
![step1](https://user-images.githubusercontent.com/789650/31021071-086deee6-a535-11e7-88ff-d9b74a592614.png)

#### Step 2
Send PUT request https://URL/index.php/rest/en/V1/products/010505c01010101a
```
{"product": {
    "options":[
      {
      "product_sku":"010505c01010101a",  
      "title":"License EN",
      "type":"radio",
      "sort_order":null,
      "is_require":true,
      "price_type":null,
      "values":[
        {
        "title":"Standard license EN",
        "sort_order":1,
        "price":null,
        "price_type":"fixed",
        "sku":"standard"
        },
        {
        "title":"Royalty free license EN",
        "sort_order":2,
        "price":60,
        "price_type":"fixed",
        "sku":"rf"
        },
        {
        "title":"Covers and advertising license EN",
        "sort_order":3,
        "price":180,
        "price_type":"fixed",
        "sku":"adv"
        }
      ]}
    ]
  }
}
```
#### Step 3
Send PUT request https://URL/index.php/rest/it/V1/products/010505c01010101a
```
{"product": {
    "options":[
      {
      "product_sku":"010505c01010101a",  
      "title":"License IT",
      "type":"radio",
      "sort_order":null,
      "is_require":true,
      "price_type":null,
      "values":[
        {
        "title":"Standard license IT",
        "sort_order":1,
        "price":null,
        "price_type":"fixed",
        "sku":"standard"
        },
        {
        "title":"Royalty free license IT",
        "sort_order":2,
        "price":60,
        "price_type":"fixed",
        "sku":"rf"
        },
        {
        "title":"Covers and advertising license IT",
        "sort_order":3,
        "price":180,
        "price_type":"fixed",
        "sku":"adv"
        }
      ]}
    ]
  }
}
```

### Expected result
Titles for first option:

1. **Standard license ALL** for scope store;
2. **Standard license EN** for scope en;
3. **Standard license IT** for scope it;

### Actual result
The option titles are overwritten for all scopes from the last PUT request:
After **Step 1**:
![after-step1](https://user-images.githubusercontent.com/789650/31021928-a6fde668-a537-11e7-83de-d7262e942522.png)
![after-step1a](https://user-images.githubusercontent.com/789650/31021929-a7233f08-a537-11e7-9bc4-85054fc38914.png)

After **Step 2**:
![after-step2](https://user-images.githubusercontent.com/789650/31021945-afff0bd4-a537-11e7-9a59-6aa03eaa9dc7.png)
![after-step2a](https://user-images.githubusercontent.com/789650/31021946-afff4342-a537-11e7-89f8-d69ebcb326c8.png)

After **Step 3**:
![after-step3](https://user-images.githubusercontent.com/789650/31021966-bd342172-a537-11e7-8522-72352cdf1a06.png)
![after-step3a](https://user-images.githubusercontent.com/789650/31021968-bd55a9dc-a537-11e7-8112-38dfc66c9dee.png)

**Comment by magento-engcom-team** [comment] 2017-10-02 11:30
@teoteo, thank you for your report.
We've created internal ticket(s) MAGETWO-80574 to track progress on the issue.

**Comment by sanjay-wagento** [comment] 2018-05-19 08:31
I am working on this at #dmcdindia

**Comment by sanjay-wagento** [comment] 2018-05-19 08:43
@magento-engcom-team , I cannot reproduce the issue in the latest 2.2-develop branch (Magento ver. 2.2.6-dev)

**Comment by magento-engcom-team** [comment] 2018-05-26 12:47
Hi @teoteo 
Could you please check if the issue is reproducible for you? Looks like it was fixed in later version.

**Comment by magento-engcom-team** [comment] 2018-06-11 15:16
@teoteo we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2018-06-11 15:16 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Event: dmcdindia

**Comment by samcantineau** [comment] 2020-02-03 13:57
I'd like this issue reopened, as it is still present in version 2.3. There is currently no way that I am able to specify customizable option titles on a store view level, everything else gets overwritten.

**Comment by cosmicvibes** [comment] 2020-06-15 13:10
This is still the case on 2.3.4, please reopen.

**Comment by ValeSauer** [comment] 2021-06-08 14:54
This is still not working in Magento ver. 2.4.2-p1, please open.
