### ISSUE TITLE
Magento 2 hardcoded attribute sets in interface

### ISSUE THREAD

**Issue by redboxmarcins** [magento/magento2#4677] opened 2016-05-24 17:11 UTC
0
down vote
favorite

Is there any reason why Attribute sets are hardcoded in magento 2 in interfaces?

Example in Magento\Customer\Api\CustomerMetadataInterface has const ATTRIBUTE_SET_ID_CUSTOMER=1

Magento\Rma\Api\RmaAttributesManagementInterface has it too as ATTRIBUTE_SET_ID=9

Because of that - when you have non standard attribute set Ids (f.e. after data migration from M1) - you cannot save any custom attributes as they belong somewhere else

Example:

Customer entity save in admin happens in \Magento\Customer\Controller\Adminhtml\Index\Save

and data from request is populated using data object helper

```
$this->dataObjectHelper->populateWithArray(
                    $customer,
                    $customerData,
                    '\Magento\Customer\Api\Data\CustomerInterface'
                );
```

and that helper is trying to load all custom attributes using

Magento\Customer\Model\Metadata\CustomerMetadata method getAllAttributesMetadata()

```
public function getAllAttributesMetadata()
    {
        /** @var AbstractAttribute[] $attribute */
        $attributeCodes = $this->attributeMetadataDataProvider->getAllAttributeCodes(
            self::ENTITY_TYPE_CUSTOMER,
            self::ATTRIBUTE_SET_ID_CUSTOMER
        );

        $attributesMetadata = [];

        foreach ($attributeCodes as $attributeCode) {
            try {
                $attributesMetadata[] = $this->getAttributeMetadata($attributeCode);
            } catch (NoSuchEntityException $e) {
                //If no such entity, skip
            }
        }

        return $attributesMetadata;
    }
```

As you can see if your attribute set Id is non default one, all custom attributes will not be included there, so no data will be populated.

eav_entity_table has column for default_attribute_set_id per entity and it is not hardcoded ther

**Comment by mazhalai** [comment] 2016-05-24 21:03
@redboxmarcins thank you for reporting, we have an internal ticket to fix this issue: MAGETWO-53451
However, since this involves backward incompatible changes, the next window for this change is 2.4

**Comment by redboxmarcins** [comment] 2016-05-24 22:11
@mazhalai this issue is quite serious as data migration tool is generating 2 attribute sets or more per eav_entity_type - so in this case any custom attributes for customer entity cannot be saved.

Wouldnt be possible to replace hardcoded ID with id taken from eav_entity_type ?

**Comment by redboxmarcins** [comment] 2016-05-25 08:25
Easy fix is below, so I create a plugin to handle it

```
 /**
     * @param CustomerMetadataInterceptor $subject
     * @param \Closure $proceed
     * @return array
     */
    public function aroundGetAllAttributesMetadata(CustomerMetadataInterceptor $subject, \Closure $proceed)
    {
        $entityType = $this->typeFactory->create()->loadByCode($subject::ENTITY_TYPE_CUSTOMER);
        /** @var AbstractAttribute[] $attribute */
        $attributeCodes = $this->attributeMetadataDataProvider->getAllAttributeCodes(
            $subject::ENTITY_TYPE_CUSTOMER,
            $entityType->getDefaultAttributeSetId() // this is added to get accurate attribute Set Id, not hardcoded one
        );

        $attributesMetadata = [];
        foreach ($attributeCodes as $attributeCode) {
            try {
                $attributesMetadata[] = $subject->getAttributeMetadata($attributeCode);
            } catch (NoSuchEntityException $e) {
                //If no such entity, skip
            }
        }

        return $attributesMetadata;
    }
```

**Comment by redboxmarcins** [comment] 2016-05-25 08:43
I found another occurrence of that in Customer Repository 
Magento\Customer\Model\ResourceModel\CustomerRepository

```

 // Need to use attribute set or future updates can cause data loss
        if (!$customerModel->getAttributeSetId()) {
            $customerModel->setAttributeSetId(
                \Magento\Customer\Api\CustomerMetadataInterface::ATTRIBUTE_SET_ID_CUSTOMER
            );
        }
```

and in Magento\Customer\Model\Customer

```
public function updateData($customer)
    {
        $customerDataAttributes = $this->dataObjectProcessor->buildOutputDataArray(
            $customer,
            '\Magento\Customer\Api\Data\CustomerInterface'
        );

        foreach ($customerDataAttributes as $attributeCode => $attributeData) {
            if ($attributeCode == 'password') {
                continue;
            }
            $this->setDataUsingMethod($attributeCode, $attributeData);
        }

        $customAttributes = $customer->getCustomAttributes();
        if ($customAttributes !== null) {
            foreach ($customAttributes as $attribute) {
                $this->setDataUsingMethod($attribute->getAttributeCode(), $attribute->getValue());
            }
        }

        $customerId = $customer->getId();
        if ($customerId) {
            $this->setId($customerId);
        }

        // Need to use attribute set or future updates can cause data loss
        if (!$this->getAttributeSetId()) {
            $this->setAttributeSetId(
                CustomerMetadataInterface::ATTRIBUTE_SET_ID_CUSTOMER
            );
        }

        return $this;
    }
```

**Comment by redboxmarcins** [comment] 2016-05-25 14:24
Related to https://github.com/magento/magento2/issues/4694

**Comment by redboxmarcins** [comment] 2016-06-17 11:14
Another reference is Magento\Customer\Api\AddressMetadataInterface::ATTRIBUTE_SET_ID_ADDRESS

will that be fixed in 2.1 or 2.2?

**Comment by magento-engcom-team** [comment] 2017-10-30 13:30
@redboxmarcins, thank you for your report.
We've created internal ticket(s) MAGETWO-53451 to track progress on the issue.

**Comment by pyyick** [comment] 2018-09-13 05:35
Still present on Magento 2.2.5

**Comment by magento-engcom-team** [comment] 2019-01-29 09:37
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-12-09 22:53
@redboxmarcins, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-12-09 22:53 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid
