### ISSUE TITLE
Navigating in the categories tree leads to errors in Redis: "Redis session exceeded concurrent connections"

### ISSUE THREAD

**Issue by netzkollektiv** [magento/magento2#38851] opened 2024-06-20 13:30 UTC
### Preconditions and environment

- v.2.4.7-p1
- Redis enabled

### Steps to reproduce

1. Go to the backend
2. Navigate to Manage Categories
3. Add categories until you have a huge category tree with many subordinate categories
4. Open some child-nodes in categories tree by clicking on the arrow next to the category in the tree
5. Watch the logs and network logs

### Expected result

No error occurs when navigating through the categories tree in the admin.

### Actual result

About half of the requests fail:

```
curl 'https://www.shop.com/minad/catalog/category/categoriesJson/key/cbba38596330878bdc5085ede5a0244bcb55e944d2c46ced02f103084a3fc2cd/?isAjax=true' \
  --data-raw 'id=25466&store=0&form_key=3cM2Gt4PVMHQFtTM'
```
=> 500 Internal Server Error

With the following message in exception log:

```[2024-06-20T11:31:43.761771+00:00] main.CRITICAL: Cm\RedisSession\ConcurrentConnectionsExceededException in /var/www/html/web/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php:531
Stack trace:
#0 /var/www/html/web/vendor/magento/framework/Session/SaveHandler/Redis.php(84): Cm\RedisSession\Handler->read()
#1 /var/www/html/web/vendor/magento/framework/Session/SaveHandler.php(213): Magento\Framework\Session\SaveHandler\Redis->read()
#2 /var/www/html/web/vendor/magento/framework/Session/SaveHandler.php(126): Magento\Framework\Session\SaveHandler->callSafely()
#3 [internal function]: Magento\Framework\Session\SaveHandler->read()
#4 /var/www/html/web/vendor/magento/framework/Session/SessionManager.php(187): session_start()
#5 /var/www/html/web/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(149): Magento\Framework\Session\SessionManager->start()
#6 /var/www/html/web/vendor/magento/framework/Session/SessionManager.php(124): Magento\Backend\Model\Auth\Session\Interceptor->start()
#7 /var/www/html/web/vendor/magento/module-backend/Model/Auth/Session.php(104): Magento\Framework\Session\SessionManager->__construct()
#8 /var/www/html/web/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(14): Magento\Backend\Model\Auth\Session->__construct()
#9 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Backend\Model\Auth\Session\Interceptor->__construct()
#10 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#11 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#12 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#13 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#14 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#15 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#16 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(125): Magento\Framework\ObjectManager\Factory\Compiled->get()
#17 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(86): Magento\Framework\ObjectManager\Factory\Compiled->parseArray()
#18 /var/www/html/web/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Compiled->create()
#19 /var/www/html/web/vendor/magento/framework/App/FrontController.php(109): Magento\Framework\ObjectManager\ObjectManager->get()
#20 /var/www/html/web/generated/code/Magento/Framework/App/FrontController/Interceptor.php(14): Magento\Framework\App\FrontController->__construct()
#21 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\FrontController\Interceptor->__construct()
#22 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#23 /var/www/html/web/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Compiled->create()
#24 /var/www/html/web/vendor/magento/framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#25 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#26 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#27 /var/www/html/web/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#28 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#29 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#30 /var/www/html/web/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#31 /var/www/html/web/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#32 /var/www/html/web/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#33 {main}

Next Magento\Framework\Exception\LocalizedException: Redis session exceeded concurrent connections in /var/www/html/web/vendor/magento/framework/Session/SaveHandler/Redis.php:86
Stack trace:
#0 /var/www/html/web/vendor/magento/framework/Session/SaveHandler.php(213): Magento\Framework\Session\SaveHandler\Redis->read()
#1 /var/www/html/web/vendor/magento/framework/Session/SaveHandler.php(126): Magento\Framework\Session\SaveHandler->callSafely()
#2 [internal function]: Magento\Framework\Session\SaveHandler->read()
#3 /var/www/html/web/vendor/magento/framework/Session/SessionManager.php(187): session_start()
#4 /var/www/html/web/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(149): Magento\Framework\Session\SessionManager->start()
#5 /var/www/html/web/vendor/magento/framework/Session/SessionManager.php(124): Magento\Backend\Model\Auth\Session\Interceptor->start()
#6 /var/www/html/web/vendor/magento/module-backend/Model/Auth/Session.php(104): Magento\Framework\Session\SessionManager->__construct()
#7 /var/www/html/web/generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(14): Magento\Backend\Model\Auth\Session->__construct()
#8 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Backend\Model\Auth\Session\Interceptor->__construct()
#9 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#10 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#11 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#12 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#13 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#14 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#15 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(125): Magento\Framework\ObjectManager\Factory\Compiled->get()
#16 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(86): Magento\Framework\ObjectManager\Factory\Compiled->parseArray()
#17 /var/www/html/web/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Compiled->create()
#18 /var/www/html/web/vendor/magento/framework/App/FrontController.php(109): Magento\Framework\ObjectManager\ObjectManager->get()
#19 /var/www/html/web/generated/code/Magento/Framework/App/FrontController/Interceptor.php(14): Magento\Framework\App\FrontController->__construct()
#20 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\FrontController\Interceptor->__construct()
#21 /var/www/html/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#22 /var/www/html/web/vendor/magento/framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Compiled->create()
#23 /var/www/html/web/vendor/magento/framework/App/Http.php(115): Magento\Framework\ObjectManager\ObjectManager->get()
#24 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#25 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#26 /var/www/html/web/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#27 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#28 /var/www/html/web/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#29 /var/www/html/web/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#30 /var/www/html/web/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#31 /var/www/html/web/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#32 {main} {"report_id":"9ab6e212dd05f9cecc56387e18e3ab7bdedc521ec4958b4a3e6564a8f5c49011","exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Redis session exceeded concurrent connections at /var/www/html/web/vendor/magento/framework/Session/SaveHandler/Redis.php:86)
[previous exception] [object] (Cm\\RedisSession\\ConcurrentConnectionsExceededException(code: 0):  at /var/www/html/web/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php:531)"} []
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2024-06-24 13:10
Also running into this problem over here. In our case it not only happens when clicking the arrow, but also when just clicking a deeper level of category itself, in that case it's even worse, we sometimes see > 70 similar ajax requests happening simultaneous of which a lot are failing.
One of our shops with this problem is hosted on hypernode.com and we notice we get a bunch of HTTP status codes 429 back, because their rate limiter sees way too many requests happening at the same time from the same source IP.

I think the problem got introduced by https://github.com/magento/magento2/commit/67f1b8f0c89cc83302bc7781a10dca931b8e7097, more specifically [in this piece of code](https://github.com/magento/magento2/blob/2.4.7-p1/app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/tree.phtml#L264-L289).

I'm not exactly sure what this code is supposed to do, but it sounds wrong to me to perform tens if not hundreds of similar ajax requests for info when you can try to get the necessary info as well within a single request.

Maybe @Atul-glo35265 is around to try to explain how that code is supposed to work and if there isn't a way to optimise it so it doesn't send all those ajax requests in a loop, but bundle them up in a single request somehow?
/cc @kandy

**Comment by kandy** [comment] 2024-06-25 14:43
@hostep Are you sure that this issue is not reproducible on version < 2.4.7?
My assumption that this issue caused by switching from http1 to http2 that allow up to 100 parallel request to server

Usually BFF  (like graphql) responsibly for batching requests, so implementing batching like `/tree/child/?ids=[1,2,3,4]`  is optimal for now

**Comment by lamskoy** [comment] 2024-06-25 15:34
This happens in 2.4.7 and 2.4.7-p1 for me

**Comment by hostep** [comment] 2024-06-25 16:01
> @hostep Are you sure that this issue is not reproducible on version < 2.4.7?
> My assumption that this issue caused by switching from http1 to http2 that allow up to 100 parallel request to server
> Usually BFF (like graphql) responsibly for batching requests, so implementing batching like /tree/child/?ids=[1,2,3,4] is optimal for now

I can double check with 2.4.6, but since the category tree code was refactored in 2.4.7, I don't think it will trigger on anything lower than 2.4.7.
Simultaneous request with HTTP/2 is good for dealing with static assets by the browser (images, scripts, css, ...). So one connection that fetches the html (outputted by a single php process) and then fetching all the other assets simultaneously over 1 and the same TCP connection (which have nothing to do with php usually).
But in this case, you are sending tens if not hundreds of ajax requests (almost) simultaneously, which the server than has to start processing with php, and validating the sessions for each request to make sure you are authenticated and then fetching per tiny request the info it needs. This seems not a good behavior in my opinion, way too much overhead, way too many php processes that are doing things. Just fetch the info you need with one single ajax request and deal with the big response in the frontend js code.

**Comment by engcom-Delta** [comment] 2024-06-26 12:28
Hi @netzkollektiv ,

Verified the issue on 2.4-develop and 2.4.7  and we are not able to reproduce this issue.

Preconditions and environment

1.Redis enabled

Steps to reproduce:-

1.Go to the backend
2.Navigate to Manage Categories
3.Open some child-nodes in categories tree by clicking on the arrow next to the category in the tree
4.Watch the logs and network logs

Redis enabled

<img width="871" alt="Screenshot 2024-06-26 at 5 46 15 PM" src="https://github.com/magento/magento2/assets/51681379/5faaa60d-6da6-41f6-a039-2dee46502649">

Admin

<img width="1438" alt="Screenshot 2024-06-26 at 5 46 38 PM" src="https://github.com/magento/magento2/assets/51681379/5245753f-7218-402c-a17a-f3c51e28a52a">

Manage Categories

<img width="1439" alt="Screenshot 2024-06-26 at 5 47 07 PM" src="https://github.com/magento/magento2/assets/51681379/81f1cd80-9357-4f9d-9d90-efdadbed4f8e">

Open some child-nodes in categories tree 

<img width="1435" alt="Screenshot 2024-06-26 at 5 48 24 PM" src="https://github.com/magento/magento2/assets/51681379/7dc4d4d9-b145-4f97-9d60-e37d9bc17717">

logs

<img width="934" alt="Screenshot 2024-06-26 at 5 57 17 PM" src="https://github.com/magento/magento2/assets/51681379/9b5b31b6-a997-4793-992e-4bb94082ada4">


Please refer the attached screenshots and let us know if we missed anything.

**Comment by netzkollektiv** [comment] 2024-06-26 12:34
> Add categories until you have a huge category tree with many subordinate categories

You need a lot of categories to reproduce the issue, not just 4. See also comment of @hostep

**Comment by lucasjor** [comment] 2024-06-27 20:11
I'm having the same issue, same error message. Strangely it is not being consistent along all our environments, even with all of them having the same Redis configuration.
![image](https://github.com/magento/magento2/assets/1675051/f4341916-059e-4a67-81ac-2004681a66d1)

**Comment by hostep** [comment] 2024-06-27 20:44
The issue is not the Redis configuration, the issue is those hundreds of concurrent calls to that categoriesJson url, @kandy I hope you understand it better by now?

**Comment by LinkImaging** [comment] 2024-06-28 18:36
Also, seeing this issue.  As usual, Magento fails to test at scale.  This is probably the 20th time I've seen an issue triggered when there are thousands of records and Magento says "We tested with 2 records and it's fine".  

Why shouldn't everyone here just move to OroCommerce, BigCommerce, Shopify, Webflow, or one of the other platforms?  Magento2 has drastically reduced in quality over the last 5 years.

**Comment by engcom-Delta** [comment] 2024-07-02 15:09
Hi @netzkollektiv ,

Verified the issue on 2.4.7 again.

Preconditions

1.Redis enabled

Steps to reproduce:-

1.Go to the backend
2.Navigate to Manage Categories
3.Add categories until you have a huge category tree with many subordinate categories
4.Open some child-nodes in categories tree by clicking on the arrow next to the category in the tree
5.Watch the logs and network logs


Actual Result:

We are getting "Redis session exceeded concurrent connections" error and we can see many XHR requests coming to PageBuilder previews.


admin panel


<img width="1436" alt="Screenshot 2024-07-02 at 7 45 20 PM" src="https://github.com/magento/magento2/assets/51681379/5230fc86-bdc3-4450-a307-6462a396a0b5">


"Redis session exceeded concurrent connections" error on logs

<img width="1439" alt="Screenshot 2024-07-02 at 8 25 09 PM" src="https://github.com/magento/magento2/assets/51681379/a33b2f98-41e6-466c-b049-4a2648b15da6">


network logs


<img width="1440" alt="Screenshot 2024-07-02 at 7 48 27 PM" src="https://github.com/magento/magento2/assets/51681379/ec4058bd-d22f-4e0c-bc7c-145e182578ee">


<img width="1439" alt="Screenshot 2024-07-02 at 7 49 11 PM" src="https://github.com/magento/magento2/assets/51681379/1a338866-7e51-4347-b92a-f6205d6f75d5">


Could you please let us know for network logs , what kind of error you have reported as it is not mentioned in the issue above.

**Comment by lamskoy** [comment] 2024-07-11 08:48
> Has someone a temporary fix ?

increase max_concurrency inside app/etc/env.php
```
'session' => [
        'save' => 'redis',
        'redis' => [
            'host' => 'localhost',
            'port' => '6379',
       ...
            'max_concurrency' => '6',
       ...
        ]
    ],
```

Bad practice, but could help

**Comment by hostep** [comment] 2024-07-11 08:59
Indeed, that's a workaround for the Redis problem, it won't help with hosting companies that have rate limiters setup though.

The refactoring to the category tree that was done in Magento 2.4.7 should be taken a close look at and refactored again so it doesn't require hundreds of ajax calls to get the necessary info.

When I first looked at this issue, removing [the foreach here](https://github.com/magento/magento2/blob/2.4.7-p1/app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/tree.phtml#L264-L289) also solved the issue, but I have no idea if this has repercussions...

**Comment by Atul-glo35265** [comment] 2024-07-22 13:20
Hi @hostep 
Thanks for your contribution and finding the issue.

This [particular code](https://github.com/magento/magento2/blob/2.4.7-p1/app/code/Magento/Catalog/view/adminhtml/templates/catalog/category/tree.phtml#L264-L289) is responsible for getting the children of categories at level 3 or further. If we comment out that foreach loop, the triangle button will become invisible and the user won't be able to traverse to categories at level 4. Please refer attached screenshot.

We need to check the feasibility of optimizing the code for this issue. Once the issue is confirmed from our internal community team, we will investigate it further.

![categoryIssue](https://github.com/user-attachments/assets/6295dd6e-e56e-4fed-a27f-3c42f992e8bc)

**Comment by hostep** [comment] 2024-07-22 13:39
Thanks for shedding a bit of light onto the problem!

There is no need to wait on confirmation, the issue was already confirmed by many people in this thread. To repeat: you shouldn't try to reproduce the Redis error. You just need to have a big category tree, with many levels, then open the inspector in your browser and see the hundreds of simultaneous ajax requests going to `catalog/category/categoriesJson`. This is bad design and needs to be reworked to only a single ajax request if possible.

**Comment by engcom-Bravo** [comment] 2024-07-23 11:12
Hi @hostep,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

<img width="1440" alt="Screenshot 2024-07-23 at 10 29 22" src="https://github.com/user-attachments/assets/511ba55c-1d1b-47b4-8e96-45f86c022481">

**Comment by hostep** [comment] 2024-08-06 19:17
Potential fix: https://github.com/magento/magento2/pull/39018, thanks to @sheepfy! (I haven't tested it yet)

**Comment by engcom-Bravo** [comment] 2024-08-07 10:15
Hello,

Internal team has started to work on it

Thanks

**Comment by hostep** [comment] 2024-09-11 20:47
Probably fixed by: https://github.com/magento/magento2/commit/1a27a04884cb900008903536003cb4064d558716 ?

**Closed as completed** 2024-09-12 05:59 UTC
Labels: Issue: Confirmed, Component: Console, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Other Developer Tools, Reported on 2.4.7-p1

**Comment by engcom-Bravo** [comment] 2024-09-12 06:01
@hostep Thanks for your contribution!!.

Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-12751 by the internal team
Related commits:1a27a04

Based on the Jira ticket, the target version is 2.4.8-beta1.

Thanks

**Comment by kevincream** [comment] 2024-10-31 12:38
After applying the changes from commit: https://github.com/magento/magento2/commit/1a27a04884cb900008903536003cb4064d558716
The categories wont get the active-category / no-active-category class anymore. Any idea how to fix this?

**Comment by hostep** [comment] 2024-10-31 14:13
@kevincream, I _think_ this got fixed a few days ago with [ACP2E-3350: Disabled Categories are no longer have their names grayed out in the category tree](https://github.com/magento/magento2/commit/efd35a9e8adf86f09dc5a0a821e2b9c26a36a3fd)

**Comment by kevincream** [comment] 2024-11-01 07:33
@hostep Awesome, i got it working again!
