### ISSUE TITLE
Create a coupon code(cart price rule) which can be used only once by any user

### ISSUE THREAD

**Issue by JananiKrishnan** [magento/magento2#7390] opened 2016-11-10 10:01 UTC
### Preconditions
1. Magento CE 2.1.2 installed 

### Steps to reproduce
1. Go to create cart price rules
2.  Create a rule with auto generate coupon codes and also uses per coupon as 1 and uses per customer as 1
3. Save the coupon

### Expected result
1.  The coupon should apply only once . For example, users A  and B have coupon code **123abc** , the coupon will be applied once who uses first. The other user cannot be able to use it.

### Actual result
1. The coupon can be applied by both A and B only once.

**Comment by olysenko** [comment] 2016-11-25 15:48
Hi, thank you for your report. Internal ticket  MAGETWO-57870 was created

**Comment by magento-engcom-team** [comment] 2017-10-05 08:30
@JananiKrishnan, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Issue: Format is valid
