### ISSUE TITLE
The new added size can not be saved

### ISSUE THREAD

**Issue by Sylvesterx1** [magento/magento2#14094] opened 2018-03-14 08:51 UTC
### Preconditions

1. Latest version 2.2.3
2. Linux Debian 9

### Steps to reproduce

1. Go to **Store** --> **features** --> **Products**
2.  Edit size field
3.  Add new size and try save it
* When I only change filed example size XS to L and save then work OK. But when I add new field and try to save it then I received error.

### Expected result

1.  I added new sizes, filled the entire list. When trying to save it receives an error. 
`Admin is a required field in the each row.`

### Actual result

1. 
![image](https://user-images.githubusercontent.com/35328055/37391980-3d76efa6-276d-11e8-906a-b60be03347ef.png)

**Comment by paragpadsumbiya** [comment] 2018-03-14 10:22
@Sylvesterx1  I have tried this with same os and same version but cant reproduce this issue .Can you please clean catch and try again .

**Comment by Sylvesterx1** [comment] 2018-03-14 11:29
@paragpadsumbiya  Please check our movie: https://streamable.com/1xas6

**Comment by paragpadsumbiya** [comment] 2018-03-14 11:44
@Sylvesterx1 thanks for video . I have tried same way but cant find issue .Let @magento-engcom-team to review your issue .By mean time can you please install fresh set up and try again .

**Comment by magento-engcom-team** [comment] 2018-03-14 15:28
Hello @Sylvesterx1. Thanks for reporting. In order not to encounter "Admin is a required field in the each row." You need to fill in not only option values for admin but also the descriptions for those values (Opis.. as we see in Your language). As for the other message in Your video it seems to be a bug but we need to recheck it. We'll do that soon.

**Comment by Sylvesterx1** [comment] 2018-03-14 17:38
@magento-engcom-team  I've filled all the boxes as you said, and now I'm trying to save.

Still the same error, please check below:
![image](https://user-images.githubusercontent.com/35328055/37420363-ec212578-27b6-11e8-80a2-5ca086fa25b4.png)

**Comment by magento-engcom-team** [comment] 2018-03-15 06:40
@Sylvesterx1, Right next to Admin* column the Discription for admin column should be displayed. That must be not empty. Please see screenshot.
![swatches](https://user-images.githubusercontent.com/31669971/37447833-8459b830-282c-11e8-8977-f8f6a3e05f3e.png)

**Comment by magento-engcom-team** [comment] 2018-03-15 07:13
@Sylvesterx1, we've acknowledged the issue and added to our backlog in part of "The value of Admin scope can't be empty" error message appearance.

**Comment by Sylvesterx1** [comment] 2018-03-15 08:58
OK so this should solve the problem but just tell me because I have a lot of languages. This field is too small to see what it writes. How to solve it ?
![image](https://user-images.githubusercontent.com/35328055/37453231-602da920-2837-11e8-9105-684df69856d5.png)

**Comment by paragpadsumbiya** [comment] 2018-03-15 10:09
@Sylvesterx1 @magento-engcom-team Look lik this issue is appreaing with multiple store views .It is working fine when you have only one store in English .

@Sylvesterx1 For spacing issue there is one more issue same for placeholder when there are multiple store views . #14107

**Comment by magento-engcom-team** [comment] 2018-03-15 12:01
Hi again, @Sylvesterx1. There is definitely a bug that many fields are being not displayed enough if You have many store views. It will be processed with the issue #14107. Temporally You can solve this problem by using "Tab" key on the keyboard. When You have filled in the field of Admin value for the swatch press Tab key and You'll get into the next field the description field for admin. Thus You may fill it in.

**Comment by ishakhsuvarov** [comment] 2018-03-15 13:59
@Sylvesterx1 Closing this report as duplicate of #13053.
Please continue tracking under that id.

Thank you for collaboration.

**Closed as completed by ishakhsuvarov** 2018-03-15 13:59 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
