### ISSUE TITLE
Transactional Email logo not updating

### ISSUE THREAD

**Issue by noprobz09** [magento/magento2#9991] opened 2017-06-20 09:58 UTC
### Preconditions
Magento 2.1.3
PHP version 7.0.8
MySQL version 5.7.13

### Steps to reproduce
Transactional Email
To update Email logo

### Expected result
The updated email logo will show

### Actual result
updated email logo not showing

**Screenshots:**
https://www.screencast.com/t/i6AHj951YidQ

**Comment by hostep** [comment] 2017-06-20 11:28
@noprobz09: this has been reported at least 10 times before, please try searching for existing issues before creating a new one, tnx :)

Anyway, the issue was already fixed on the develop branch and was backported to the 2.1-develop branch and will most likely be released in the next 2.1.x release.
See https://github.com/magento/magento2/issues/5352 for more details.

**Comment by korostii** [comment] 2017-06-20 11:48
> this has been reported at least 10 times before

Well, to be perfectly honest, fix ( 23103c0 ) was done more than a *year*(sic!) ago and yet it's still not available in the latest released version. So whose fault is that?

I wouldn't blame users for reporting it 10 times more. 
It's not as if there's an easy workaround available for everyone (like, for example, "update to 2.1.7")

**Comment by hostep** [comment] 2017-06-20 13:08
@korostii: chill chill, instead of whining everywhere about issues not being fixed in a new release, you could be a lot more helpful by creating backports of fixes yourself like I am doing. It seems to be the only way to quickly make Magento more stable then the state it is in today.
I agree with you that it should be Magento's responsibility to backport these fixes, but it seems that they are too busy with all kinds of other stuff (creating new features for the Enterprise Edition or something like that, who knows). If we take matters into our own hand it will go much quicker :)

**Comment by korostii** [comment] 2017-06-20 15:53
@hostep: There is this bottleneck called "Community Engineering Team". It seems that both backporting and processing Pull Requests falls under their jurisdiction and the team is quite small.

As far as I understand, they decided to focus on Pull requests precisely because backporting _everything_ would take too much effort: there were dozend if not hundreds of fixes missing from 2.1 and only present on develop. Thus [it was decided to backport the top-voted issues only](https://community.magento.com/t5/Magento-DevBlog/GitHub-Issue-Priority/ba-p/60088#M15). When that failed, they switched to [PRs as a way to prioritize backporting](https://community.magento.com/t5/Magento-DevBlog/Pull-Requests-for-2-1-x-Patch-Releases/ba-p/65630). 

So please keep that in mind: that's still just a fast line for fixes which you _really really_ need ASAP, like that tinyMCE fix you pushed through (great job, by the way!). 

IMHO the pull requests add much more overhead onto Magento's devs than backporting itself would. 
Seeing pull requests section flooded with these backports makes me sad. 
I'd rather see one major improvement like #9367 processed by Magento.


> other stuff (creating new features for the Enterprise Edition or something like that, who knows)

My guess would be "preparing 2.2 for the alpha release", actually. In any case, it's quite annoying.

I am sorry if my comments bother you, but I feel it's necessary to remind the guys at Magento that there's a lot of people awaiting those fixes. I just hope eventually Magento manages to improve the bugfixing pace, because it's the responsible thing to do. Besides, it does them much good in PR terms, even if it costs a couple more people attached to the job.

**Comment by drsholtes** [comment] 2017-06-20 18:57
It'd be really cool if this platform worked!

**Comment by andidhouse** [comment] 2017-06-21 21:38
i think this is about 10 minutes to fix for a magento core team member - instead it is reported here at least 10 times and hundreds of people spend hours on this topic.

I really do not like how magento handles obvious simple bugs - this is far from professional in my point of view.

**Comment by maurice-j** [comment] 2017-07-04 09:48
Dirty Fix: v2.1.7
The email image you upload goes to:
pub/media/logo/stores/1/yourlogo.jpg
Magento is looking for (and links to)
pub/media/email/logo/stores/1/yourlogo.jpg

I manually created the pub/media/email/logo/stores/ structure on our server and added the images files myself. They now link correctly and the email contain the correct logo.

**Comment by magento-engcom-team** [comment] 2017-09-29 13:30
@noprobz09, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-29 13:30 UTC
Labels: bug report, Issue:  Cannot Reproduce, Issue: Format is valid
