### ISSUE TITLE
Magento 2.2.6 Error, view Shipment details in backend "Uncaught Error: Call to a member function getParentItem() on null"

### ISSUE THREAD

**Issue by feelcomfort** [magento/magento2#18383] opened 2018-10-04 12:50 UTC
### Preconditions

1. Magento 2.2.6
2. Incoming Order
3. Create Shipment

### Steps to reproduce

1. Sales/Shipment
2. Clicking "view" on any shipmend

![1 sales_shipment](https://user-images.githubusercontent.com/43548743/46474801-1c88d300-c7e4-11e8-8ec7-0dfb4b052774.JPG)

### Expected result

1. Shipment overview

### Actual result

1. In all new shipment-views this error appears:

fatal error: Uncaught Error: Call to a member function getParentItem() on null in /var/www/magento2/vendor/magento/module-shipping/view/adminhtml/templates/view/items.phtml:19

![3 fatal error](https://user-images.githubusercontent.com/43548743/46476075-8c4c8d00-c7e7-11e8-8724-25bc6c1c987c.JPG)

This problem only appears in backend in the shipment-view. 
Orders, Invoices etc. work fine.

Does anyony know how to handle this error?

Thanks for help.

**Comment by magento-engcom-team** [comment] 2018-10-04 12:50
Hi @feelcomfort. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@feelcomfort do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by torhoehn** [comment] 2018-10-05 21:45
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment] 2018-10-05 21:45
Hi @torhoehn. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment] 2018-10-05 21:45
Hi @torhoehn. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-10-05 21:46
Hi @torhoehn, here is your [Magento instance](https://i-18383-2-2-6.engcom.dev.magento.com).
Admin access: [https://i-18383-2-2-6.engcom.dev.magento.com/admin](https://i-18383-2-2-6.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by torhoehn** [comment] 2018-10-05 21:54
@feelcomfort Could not reproduce you issue on vanilla instance so I'll close this issue.

<img width="1333" alt="screenshot 2018-10-05 at 23 52 36" src="https://user-images.githubusercontent.com/1945725/46561895-ec335880-c8f9-11e8-846e-17b5e1f266a7.png">

**Closed as completed by torhoehn** 2018-10-05 21:54 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by rauwebieten** [comment] 2019-02-19 11:09
We had the same problem. Turns out to be missing shipment data from a migration. This caused some shipment id's to be used twice... We fixed our db-data, and the problem was gone.
