### ISSUE TITLE
Admin global search - submit by enter doesn't work

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#10275] opened 2017-07-18 11:27 UTC
When I'm trying to submit search form from keyboard - it doesn't work, but if I just click to value in drop-down - it works as expected.

### Preconditions
1. Magento 2.1.7 installed via composer

### Steps to reproduce
1. Go to Magento 2 admin panel
2. Click "Search" icon in header
3. Put some query (as example 7029) in search field, wait for autocomplete
4. Select "\<your query\>"  in Products option with arrow keys on keyboard
5. Click enter button
![image](https://user-images.githubusercontent.com/1873745/28314904-0f561a5c-6bc5-11e7-8cc2-1a683c9b1739.png)

### Expected result
1. Browser should be redirected to products grid page with selected query

### Actual result
1. Browser was redirected to the current page with additional get parameter: ?query=#

**Comment by AlexWorking** [comment] 2017-07-24 12:52
Hello, @ihor-sviziev. Based on Your issue an internal ticket was created - MAGETWO-70961. As the issue is fixed You'll be informed. Thank You for reporting.

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@ihor-sviziev, thank you for your report.
We've created internal ticket(s) MAGETWO-70961 to track progress on the issue.

**Comment by romainruaud** [comment] 2017-10-05 12:33
I'm working on it #SQUASHTOBERFEST

**Comment by okorshenko** [comment] 2017-10-05 14:20
@romainruaud could you please accept the invitation to magento/magento2 on the GitHub?

**Comment by romainruaud** [comment] 2017-10-05 14:22
@okorshenko done !

**Comment by magento-team** [comment] 2017-10-26 18:02
Internal ticket to track issue progress: MAGETWO-81146

**Comment by okorshenko** [comment] 2017-10-26 18:26
The issue has been fixed in 2.2-develop branch and will be available with 2.2.2 release soon

**Closed as completed by okorshenko** 2017-10-26 18:26 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-team** [comment] 2018-01-26 18:05
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1284 by @magento-engcom-team in 2.3-develop branch
Related commit(s):


The fix will be available with the upcoming patch release.

**Comment by shachiarkatkar** [comment] 2018-03-07 05:19
Is there any way to search complete string instead of each word? For example i want to search customer with full name but i get results based on first name

**Comment by ihor-sviziev** [comment] 2018-03-07 05:40
@shachiarkatkar AFAIK no
