### ISSUE TITLE
CurrencyConverterApi requsts exchange rate also if from and to currency are the same

### ISSUE THREAD

**Issue by maja76** [magento/magento2#36734] opened 2023-01-12 08:49 UTC
### Preconditions and environment

- Magento version: 2.3.6

If you need for example 8 currency rates, Magento also tries to fetch a currency rate for a base currency, even if from and to currency is the same. So at the end, Magneto wants to fetch 9 currency rates and you have to take and pay a bigger plan. 

### Steps to reproduce

Add the amount of different currency rates you have in your plan, other then your base currency. Try to get API answers. 

### Expected result

No error message for requesting too much exchange rates. 

### Actual result

Currency Update Warnings

WARNING: You have exceeded your maximum conversion per request. (max: 8 vs actual:9)

### Additional information

Possible solution:
Change /vendor/magento/module-directory/Model/Currency/Import/CurrencyConverterApi.php

Change private function getServiceURL

 foreach ($currenciesTo as $currencyTo) {
                if ($currencyFrom == $currencyTo) continue; # ADD THIS LINE
                $currencyQueryParts[] = sprintf('%s_%s', $currencyFrom, $currencyTo);
            }

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-16 11:29
Hi @maja76,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is reproducible. Kindly refer the screenshots.


We have tried with Free Currency Converter API.As per Currency Converter Api document https://free.currencyconverterapi.com/ for Free API we can request for 2 Currency pairs.

For 2 Pairs it is working fine.

<img width="1450" alt="Screenshot 2023-01-16 at 4 55 41 PM" src="https://user-images.githubusercontent.com/51680745/212667482-700779a5-c36b-4263-823e-bc99494f4f97.png">



For above 2 pairs we are getting a warning, it is not a bug it is expected behaviour because as per document we can request for only 2 currency pairs.



<img width="1417" alt="Screenshot 2023-01-16 at 1 21 37 PM" src="https://user-images.githubusercontent.com/51680745/212667449-59d9dd32-1b83-4cc0-bcd8-833482ad1b83.png">










For 8 pairs and above we need to upgrade to premium and prepaid plans as per document https://www.currencyconverterapi.com/pricing. 




For updating currency rates kindly go through with this [doc](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/site-store/currency/currency-update.html?lang=en) and also make sure that cron should be enabled.



Kindly let us know if you are still facing any issue.


Thanks.

**Comment by maja76** [comment] 2023-01-17 11:15
Your sample only has one required currency pair, AFN/USD, 
but Magento also requests the USD/USD pair, which doesn't make sense as it is always 1. 
This means that the free request limit is reached due to one unnecessary request. 
If you would not request USD/USD pair, you could request one more useful currency pair for free. 

Same issue for us, we have 9 currencies, one of them is the base currency. 
So we need 8 currency pairs and bought a plan for 8 currency pairs. 
But Magento also requests the exchange rate for the base currency, which is always 1. 
So we would need a plan for 9 exchange rates, instead of 8. 

So best would be to avoid this unnecessary request. Then nobody has to choose a bigger plan for an unnecessary request.

**Comment by engcom-Bravo** [comment] 2023-01-19 12:57
Hi @maja76,

Thanks for your update.

USD is Base currency.Since USD is base currency as per configuration we cannot remove USD in Allowed currencies list that in the case Magento considers USD is also a one pair of request.

We tried to remove USD


<img width="1319" alt="Screenshot 2023-01-19 at 3 35 53 PM" src="https://user-images.githubusercontent.com/51680745/213448087-9f3e4138-7689-4b63-a465-1e8be7c48f8f.png">



As per Currency Converter document https://www.currencyconverterapi.com/pricing when we take Premium services we can request n number of currency pairs.


Thanks.

**Comment by engcom-Hotel** [comment] 2023-02-03 12:19
Dear @maja76,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-03 12:19 UTC
Labels: Issue: needs update, Reported on 2.3.6
