### ISSUE TITLE
WYSIWYG is not working and removes images in product

### ISSUE THREAD

**Issue by wenpingguo** [magento/magento2#7618] opened 2016-11-30 01:19 UTC
### Preconditions

1. Magento 2.1.2 CE 

### Steps to reproduce

1. go to admin and select a product
2. Go to product "description" field and insert an image or more 
3. Click "Show / Hide Editor" 
4. Click "Show / Hide Editor" 

### Expected result

1. In step3, I should be able to preview the image I added.
2. In step4, I should be able to see the image html again.

### Actual result

1. you cannot preview the image
![p1](https://cloud.githubusercontent.com/assets/19483820/20735790/843d5c38-b6f6-11e6-804a-613176e72fa7.png)
2. The image url have been removed
![p2](https://cloud.githubusercontent.com/assets/19483820/20735794/908e96e6-b6f6-11e6-8406-8dd042da1fe4.png)

Other issue, sometime "Show / Hide Editor" is not working.

**Comment by slopukhov** [comment] 2016-11-30 15:53
@wenpingguo thank you for your feedback.
I cannot reproduce this issue. Could you provide information about your environment and what browser you are using (if there are any JS errors in it)?

**Comment by hostep** [comment] 2016-11-30 18:55
Duplicate of https://github.com/magento/magento2/issues/7215 & https://github.com/magento/magento2/issues/6138

**Comment by wenpingguo** [comment] 2017-02-20 06:28
Hi
Do we have any update here? Looks it is getting worse. WYSIWYG will remove or re-arrange html.
I tested the following cases when creating and save static blocks in magento 2.1.3 CE.
I want to create anchor a tag with background in a div container.

**Test case1 html remove**
1. Create a static block with the html contents below in html view.
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce"></div></a>`
2. Click "save and continue edit"
3. switch between WYSIWYG and html
Expect result in html view, you should see
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce"></div></a>`
actually result:
`<div class="arrow bounce"></div>`
4. switch between WYSIWYG and html again
Expect result in html view:
`<div class="arrow bounce"></div>`
actually result:
You see nothing

**Test case2 html remove**
1. Create a static block with the html contents below in html view.
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce">dd</div></a>`
2. Click "save and continue edit"
3. switch between WYSIWYG and html
Expect result in html view:
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce">dd</div></a>`
actually result:
`<div class="arrow bounce">dd</div>`

**Test case3 html re-arrange**
1. Create a static block with the html contents below in html view.
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce">dd</div>ff</a>`
2. Click "save and continue edit"
3. switch between WYSIWYG and html
Expect result:
`<a id='arrow_bounce'  href="#help_section"><div class="arrow bounce">dd</div>ff</a`
actually result:
```
<div class="arrow bounce">dd</div>
<p><a id="arrow_bounce" href="#help_section">ff</a></p>
```

Test Video record: http://take.ms/bNHDw

**Comment by magento-team** [comment] 2017-08-01 01:09
Internal ticket to track issue progress: MAGETWO-70435

**Closed as completed** 2017-09-18 18:41 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Component: Catalog, Fixed in 2.1.x, Issue: Format is valid
