### ISSUE TITLE
Remote Storage Error

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#34997] opened 2022-01-20 10:32 UTC
### Preconditions (*)

1. Magento 2.4.3-p1
2. Remote storage enabled (S3)

### Steps to reproduce (*)

1. Delete a product image directly in S3 to simulate a missing file
2. Load the related product edit page.

### Expected result (*)

1. Image is not displayed.

### Actual result (*)

1. Product form is not displayed, error instead :  `Notice: Undefined index: media/catalog/product/t/e/test-inexistant-image.jpg in /var/www/html/vendor/magento/module-remote-storage/Driver/Adapter/Cache/Generic.php on line 197`

### Proposed patch

Replace `if (!$meta[$path]) {`
with `if (!($meta[$path] ?? false)) {`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-08-09 09:02
Hello @Nuranto,

Thanks for the reporting!

We have tried to reproduce the issue in the Magento 2.4-develop branch but the issue is not reproducible for us. After deleting the image from S3 directly, we have an empty box instead of that image. Please have a look at the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/183609498-96aad903-6dc1-4bac-88c0-ed573106eae6.png)

Please let us know in case we have missed anything.

Thanks

**Comment by Nuranto** [comment] 2022-08-09 13:03
Hello @engcom-Hotel

Just to be sure, have you tried to purge cache ? Because remote-storage metadatas are stored in cache. (Btw, I think they should not be cached, but that's another issue : https://github.com/magento/magento2/issues/35820 :)

**Comment by engcom-Hotel** [comment] 2022-08-10 11:59
Hello @Nuranto,

Thanks for the reply!

We have tried this after clearing the cache as well. But the outcome is the same as mentioned in this comment https://github.com/magento/magento2/issues/34997#issuecomment-1209111738.

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-08-24 05:53
Dear @Nuranto,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-24 05:53 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
