### ISSUE TITLE
Unable to upload the same Vimeo video twice

### ISSUE THREAD

**Issue by avstaylime** [magento/magento2#33390] opened 2021-06-30 08:09 UTC
### Preconditions (*)

1. Discovered on Magento 2.3.5-p1.
2. To my knowledge, still not fixed in 2.4.x.

### Steps to reproduce (*)

1. Upload a Vimeo video to one of products in the catalog and save.
2. Go to another product and add the same Vimeo video and try to save the product.

### Expected result (*)

1. Video has been successfully added.

### Actual result (*)

1. The error below prevents the video from being assigned to the product. 
![image](https://user-images.githubusercontent.com/82515176/123924611-ce07c380-d992-11eb-9df4-4bb3a86e1821.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by avstaylime** [comment] 2021-06-30 08:11
To fix the issue, we edited `vendor/magento/framework/File/Uploader.php`, the method `public static function getNewFileName($destinationFile)`

```
{
    $fileInfo = pathinfo($destinationFile);
    if (file_exists($destinationFile)) {
        $index = 1;
        $baseName = $fileInfo['filename'] . (!empty($fileInfo['extension']) ? '.' . $fileInfo['extension'] : '') ;
        while (file_exists($fileInfo['dirname'] . '/' . $baseName)) {
            $baseName = $fileInfo['filename'] . '_' . $index . (!empty($fileInfo['extension']) ? '.' . $fileInfo['extension'] : '') ;
            $index++;
        }
        $destFileName = $baseName;
    } else {
        return $fileInfo['basename'];
    }

    return $destFileName;
}
```

**Comment by engcom-Delta** [comment] 2021-06-30 11:04
Hi @avstaylime,

Tried reproducing the issue on Magento 2.4 Develop, it is producible and able to see the same,
Followed Steps:
1. Log into Backend
2. Click on 'Catalog--> Product'
3. Select anyone product and go to Images & Video
4. Click on Add Video
5. Provide vimeo video url and select the video url
6. Click on Save button
7. Again open another product and go to vimeo video url 
8. Provide site video url , title and save
9.  observe that error displayed.

Please find the attached snapshots.
![vimeo_video](https://user-images.githubusercontent.com/51681379/123950140-ff978380-d9c0-11eb-9bb5-70319020947f.jpg)

Hence, labelled as 'Issue confirmed'.

Thanks

**Comment by hostep** [comment] 2021-06-30 19:19
Sounds like a duplicate of https://github.com/magento/magento2/issues/33276 & https://github.com/magento/magento2/issues/33266

Possible fix: https://github.com/magento/magento2/pull/33260 (I'm not 100% sure because the line numbers in the error are different)

**Comment by magento-engcom-team** [comment] 2021-07-01 08:23
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42762` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-09-01 21:11 UTC
Labels: Issue: Confirmed, Component: ProductVideo, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.3.5-p1, Area: Product
