### ISSUE TITLE
Magento ver. 2.4.3-p1 : Not Showing Success or Error Message in Front end 

### ISSUE THREAD

**Issue by srikanthpolisetty1326** [magento/magento2#36673] opened 2022-12-26 14:51 UTC
### Preconditions and environment

- Magento version : 2.4.3-p1

### Steps to reproduce

1) when we are trying to log in or create a customer account it was not showing a Success or Error Message in Front end

### Expected result

 Success or Error Message in Front end

### Actual result

1) when we are trying to log in or create a customer account it was not showing a Success or Error Message in Front end

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-27 06:23
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-27 11:50
Hi @srikanthpolisetty1326,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are getting both success and error message in frontend.


<img width="1376" alt="Screenshot 2022-12-27 at 12 31 58 PM" src="https://user-images.githubusercontent.com/51680745/209662475-9e61b070-70c9-49a8-a5ac-180bc8074db8.png">


<img width="1286" alt="Screenshot 2022-12-27 at 12 55 13 PM" src="https://user-images.githubusercontent.com/51680745/209662499-cf5afd85-da10-4540-a8a9-31fa506748cf.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by engcom-Bravo** [comment] 2023-01-09 06:07
Hi @srikanthpolisetty1326,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-01-09 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
