### ISSUE TITLE
Sorting by 'Websites' not working in product grid in backoffice

### ISSUE THREAD

**Issue by KiraLis** [magento/magento2#20511] opened 2019-01-23 11:33 UTC
### Preconditions (*)

Magento Version : CE 2.2X
Magento Version : CE 2.3.X

### Steps to reproduce (*)

1. Navigate to admin catalog product grid
2. Using "Columns" selection add Websites'' column in the grid

### Expected result (*)

Sort by 'Websites' should be working fine.

### Actual result (*)

Sort by 'websites' product attribute not working. See below screen.

![screenshot from 2019-01-23 13-28-44](https://user-images.githubusercontent.com/36077391/51603758-5e649300-1f13-11e9-8826-dcd381cbce7b.png)

![screenshot from 2019-01-23 13-28-35](https://user-images.githubusercontent.com/36077391/51603799-7b996180-1f13-11e9-8a3c-121cd66008f3.png)

**Comment by magento-engcom-team** [comment] 2019-01-23 11:33
Hi @KiraLis. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@KiraLis do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-23 11:34
Hi @XxXgeoXxX. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-23 11:35
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-01-23 11:37
Hi @dipti2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment] 2019-01-23 11:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-23 11:37
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-23 11:38
Hi @GovindaSharma, here is your [Magento instance](https://i-20511-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20511-2-3-develop.instances.magento-community.engineering/admin](https://i-20511-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-23 11:44
@GovindaSharma Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-23 11:44
@nainesh2jcommerce Thank you for verifying the issue.

Unfortunately, not enough information was provided to created internal ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-01-23 11:45
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97886`, `MAGETWO-97887` were created

**Comment by magento-engcom-team** [comment] 2019-03-16 15:00
Hi @KiraLis. Thank you for your report. 
The issue has been fixed in magento/magento2#20512 by @XxXgeoXxX in 2.3-develop branch
Related commit(s):
 - [0dfe0f0980a8be7f5ab62d5572126a0a8802ea21](https://github.com/magento/magento2/commit/0dfe0f0980a8be7f5ab62d5572126a0a8802ea21)
 - [e61b399ae9a37f00a58482f6f87bc1e06b84a97d](https://github.com/magento/magento2/commit/e61b399ae9a37f00a58482f6f87bc1e06b84a97d)
 - [fa49579fe1bf893349d78f5bc1c9661043784590](https://github.com/magento/magento2/commit/fa49579fe1bf893349d78f5bc1c9661043784590)
 - [8170bd78fc71757f78abb5a1a0bb06f8f9d9c621](https://github.com/magento/magento2/commit/8170bd78fc71757f78abb5a1a0bb06f8f9d9c621)
 - [f4d1442ead35e67ef7a49e07fdc186a034752338](https://github.com/magento/magento2/commit/f4d1442ead35e67ef7a49e07fdc186a034752338)
 - [93da772ece99f9b332829a08e39c7f4dc9ceb92e](https://github.com/magento/magento2/commit/93da772ece99f9b332829a08e39c7f4dc9ceb92e)
 - [5362c5a76d7b6dac663addada2aee67987cdf945](https://github.com/magento/magento2/commit/5362c5a76d7b6dac663addada2aee67987cdf945)
 - [f57e5e883f3b948813f02aa6226b47e6bf58eb9f](https://github.com/magento/magento2/commit/f57e5e883f3b948813f02aa6226b47e6bf58eb9f)
 - [a6f266d476ac2d3a685c63af08997742d0b4a52f](https://github.com/magento/magento2/commit/a6f266d476ac2d3a685c63af08997742d0b4a52f)
 - [a32d27b3b5360ba72380da65fac6c7f091f7124f](https://github.com/magento/magento2/commit/a32d27b3b5360ba72380da65fac6c7f091f7124f)
 - [c76d248559c30d956868e055ba14fef6029aef27](https://github.com/magento/magento2/commit/c76d248559c30d956868e055ba14fef6029aef27)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-16 15:00 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
