### ISSUE TITLE
Price not saved for different website

### ISSUE THREAD

**Issue by elioermini** [magento/magento2#38297] opened 2023-12-18 13:12 UTC
### Preconditions and environment

- Magento version 2.4.6-p3
- PHP 8.2
- Setup with 2 websites: Default and Test
- Price Scope: Website

### Steps to reproduce

Set the price of a product to 10$ in the default store.
Switch to the Test store
Set the price of the product to 11$ in the Test store
Save

### Expected result

Changes were successfully applied. Success message is shown when saving is complete and the prices in the Test store is 11$.

### Actual result

Success message is shown, but the price in the Test store is unchanged and the “Use Default” checkbox is still checked.

### Additional information

This is to reopen the issue https://github.com/magento/magento2/issues/35737 which is closed but has no information about which PR / diff fixes the issue so we could create a patch till the fix is added to a stable release.

Current Workaround: Instead of switching scope, click on Advanced Pricing, there under Tier Prices, select website Test and add the price

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by elioermini** [comment] 2023-12-18 13:14
@magento give me 2.4-develop instance

**Comment by elioermini** [comment] 2023-12-18 13:30
On dev-develop is fine, is it possible to patch 2.4.6-p3? Main visible change on develop is also that all the checkboxes "Use Default Value" are unchecked

**Comment by elioermini** [comment] 2023-12-18 14:10
I've included in the description the current workaround:

Instead of switching scope, click on Advanced Pricing, there under Tier Prices, select website Test and add the price

**Comment by engcom-Bravo** [comment] 2023-12-19 10:10
Hi @elioermini,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


**Steps to reproduce**

1. Set the price of a product to 10$ in the default store.
2. Switch to the Test store
3. Set the price of the product to 11$ in the Test store
4. Save

Changes were successfully applied and price is in test store is $11.

It might be possible the issue has been fixed in Latest 2.4-develop Instance and also thanks for your workaround.

Thanks..

**Comment by elioermini** [comment] 2023-12-19 11:29
@engcom-Bravo hi is it possible to find out what is the fix that was applied to develop, or whether there is a known patch for it?

**Comment by engcom-Bravo** [comment] 2023-12-28 07:10
Hi @elioermini,

Thanks for your Update.

We have to tried to find out the fix but we are not able to find.Since the issue is not reproducible in Latest Magento 2.4-develop instance and the fix will be released in coming Latest releases.

Thanks.

**Closed as completed by engcom-Bravo** 2023-12-28 07:10 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3

**Comment by msilinskas** [comment] 2023-12-28 10:24
@engcom-Bravo is it posible to get a patch for this issue?

**Comment by ioweb-gr** [comment] 2024-04-16 15:28
Any luck finding the root cause for this and how to patch it?
