### ISSUE TITLE
Varnish does not appear to be configured for a public folder web root (at least, with NGINX)

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#11692] opened 2017-10-24 13:57 UTC
### Preconditions

1. Magento 2.4-develop
2. Varnish 4/5/6

### Steps to reproduce

1. Set up a server according to the provided recommendations, with NGINX as the HTTP host and using the public folder
2. Export varnish as shown by Magento
3. Install varnish configuration

### Expected result

1. Server works

### Actual result

1. Varnish doesn't work (specifically, it returns a 503 and complains about upstream being down). Additionally, there are a bunch of messages in the NGINX error log about "404 /pub/health_check.php not found"

File is here: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/PageCache/etc/varnish5.vcl

As you can see, it has the `pub` hardcoded. I might suggest doing detection in the application, and adjusting the probe root accordingly.

**Comment by orlangur** [comment] 2017-10-24 15:04
I believe it's handled properly in other lines of the same file: `if (req.url ~ "^/(pub/)?(media|static)/") {`

Not sure why root `index.php` it still not removed in favor of `pub/index.php` though.

**Comment by andrewhowdencom** [comment] 2017-11-01 16:25
I'm not sure -- I don't know if Varnish caches it's own probes? To me that wouldn't make sense. Docs aren't helpful here: 

https://varnish-cache.org/docs/4.0/reference/vcl.html#reference-vcl-probes

Additionally, tailing nginx logs seems to support this (with the `pass` directive disabled): 

```
127.0.0.1 - - [01/Nov/2017:17:23:30 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:23:35 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:23:40 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:23:45 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:23:50 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:23:55 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:00 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:05 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:10 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:15 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:20 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
127.0.0.1 - - [01/Nov/2017:17:24:25 +0100] "GET /health_check.php HTTP/1.1" 200 5 "-" "-" "-"
```

**Comment by andrewhowdencom** [comment] 2017-11-01 16:28
Oh also I patched this to remove the `pub`. Specifically, we route based on virtualhosts rather than ports:

```
backend default {
    .host = "127.0.0.1";
    .port = "80";
    .first_byte_timeout = 600s;
    .probe = {
        # SITEWARDS CHANGES START
        # The normal probe configuration does not allow setting specific headers for request[1]. So, the below snippet
        # manually constructors the request to include the Host header.
        #
        # [1] https://varnish-cache.org/lists/pipermail/varnish-misc/2011-October/021298.html
        .request =
            "GET /health_check.php HTTP/1.1"
            "Host: magento.local"
            "Connection: close";
        # SITEWARDS CHANGES END
        .timeout = 2s;
        .interval = 5s;
        .window = 10;
        .threshold = 5;
   }
}
```

**Comment by magento-engcom-team** [comment] 2017-11-10 12:52
Hi @andrewhowdencom 
Could you please let us know if the issue is still actual? Thank you

**Comment by andrewhowdencom** [comment] 2017-11-10 12:55
Looks like it. As mentioned, i customised the VCL in production for us as above, for various reasons. But the 2.2 develop branch still has the path hard-coded.

I imagine the rule "if you need two versions of index.php you'll probably need two versions of health_check.php" holds true. 

https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/PageCache/etc/varnish5.vcl#L13

**Comment by magento-engcom-team** [comment] 2017-11-13 08:30
@andrewhowdencom, thank you for your report.
We've created internal ticket(s) MAGETWO-83718 to track progress on the issue.

**Comment by erfanimani** [comment] 2019-04-03 05:02
This is still an issue.

### Preconditions

- Magento 2.3.1
- Varnish 4
- Run Magento out of pub (web root being `pub` — the proper way to run PHP apps)

### Steps to reproduce

- Click Export VCL for Varnish 4

### Expected result

- Nothing breaks

### Actual result

- Website down because health check URLs have `pub` in them for whatever reason

Specifically the following lines:

Line 12: `.url = "/pub/health_check.php";` (why is /pub there? of course backend origin is going to 404, making Varnish think that the node is down..)

Line 65:

    # Bypass health check requests
    if (req.url ~ "/pub/health_check.php") {
        return (pass);
    }

**Comment by erfanimani** [comment] 2019-07-29 03:59
How is this still open after multiple years? Or maybe we're all expected to investigate the exported VCL file and catch the error ourselves?

**Comment by erfanimani** [comment] 2019-07-29 04:01
Never mind — seems to be fixed in 2.3.3: https://github.com/magento/magento2/issues/22143

**Comment by magento-engcom-team** [comment] 2019-12-26 09:43
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30080` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment] 2020-09-28 12:00
Hi @andrewhowdencom .

According to the Magento documentation in part [**Advanced Varnish configuration**](https://devdocs.magento.com/guides/v2.3/config-guide/varnish/config-varnish-advanced.html) described that:      `      
The health_check.php script is located in the pub directory. If your Magento root directory is pub, then be sure to change the path in the url parameter from /pub/health_check.php to health_check.php.`
If you manually change the path to `.url = "/health_check.php";` everything work correctly.



1. Install Varnish (ver. 4 for example);
2. Configure Varnish and your web server;

**Manual testing scenario:**

1. Set document root to /pub  ([devdocs](https://devdocs.magento.com/guides/v2.3/install-gde/tutorials/change-docroot-to-pub.html));
2. Go to Admin->Stores->Configuration->Advanced->System->Full Page Cache;
3. Choose "Varnish Cache" from "Caching Application" drop down and click on "Save" button;
4. Then click on "**Export VCL for Varnish 4**" button and open it;
5. Change `/pub/health_check.php` to `health_check.php` and Save;
6. Copy the file to the /etc/varnish/ directory;
7. Open home page;

**Actual Result:** :heavy_check_mark:  Server works

![varnish 2](https://user-images.githubusercontent.com/51679138/78107138-96137880-73fd-11ea-8feb-c11fe13cf0c3.png)

@andrewhowdencom Could you take a look?
Thanks!

**Comment by engcom-Alfa** [comment] 2020-10-13 12:18
@andrewhowdencom  , I am closing this issue now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for the collaboration!

**Closed as completed by engcom-Alfa** 2020-10-13 12:18 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Cache, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done

**Comment by andrewhowdencom** [comment] 2020-10-14 17:01
I think the desired result on this one would be to detect what mode the store is running in (given that it itself can introspect and determine what the suitable varnish configuration would be), and export things appropriately without requiring developer input.

**Comment by matteolavaggi** [comment] 2021-03-24 11:38
There is some point that need to be fixed also in 2.4

1) If you Change /pub/health_check.php to health_check.php in probe section of backend i suppose you also need to change the bypass section also, or varnish will cache result of first check
```
# Bypass health check requests
    if (req.url ~ "/health_check.php") {
        return (pass);
    }
```

2) My varnish still unable to check the file also if i can curl it from the varnish host, also after reboot of magento web server, varnish and proxy.

```
sudo varnishlog -g raw -i backend_health
         0 Backend_health - default Still sick 4---X-R- 0 5 10 0.002558 0.000000 HTTP/1.1 404 Not Found
         0 Backend_health - default Still sick 4---X-R- 0 5 10 0.002298 0.000000 HTTP/1.1 404 Not Found 
```

```
curl -i https://magento2/health_check.php
HTTP/2 200 
```

Any idea? Restarterd fpm and nginx. I can reach the page with a browser and get a 200 status

**Comment by rou9e** [comment] 2021-06-29 16:10
@matteolavaggi Same problem for me on 2.4.2. Did you manage to fix this ?

**Comment by matteolavaggi** [comment] 2021-06-29 18:01
No, this seem to be a bug not yet fixed, I can only suppose this is related in the way varnish ask for that file and in the way Magento index handle it. I've disable probe check to be able use varnish .

**Comment by rou9e** [comment] 2021-06-30 07:57
Damn. Struggling for 2 days on this.
I may have find a [solution](https://github.com/magento/magento2/issues/11692#issuecomment-341159295) : 

```
backend default {
	.host = "127.0.0.1";
	.port = "80";
	.first_byte_timeout = 600s;
	.probe = {
		#.url = "/health_check.php";
		.request =
			"GET /health_check.php HTTP/1.1"
			"Host: my-website.com.localhost"
			"Connection: close";
		.timeout = 2s;
		.interval = 5s;
		.window = 10;
		.threshold = 5;
	}
}
```

On my instance, http server (backend) would be setup on _my-website.com.localhost_ and http cache (varnish) on _my-website.com_

```
my-website.com.localhost 127.0.0.1 - - [30/Jun/2021:09:50:35 +0200] "GET /health_check.php HTTP/1.1" 200 0 "-" "-"
my-website.com.localhost 127.0.0.1 - - [30/Jun/2021:09:50:40 +0200] "GET /health_check.php HTTP/1.1" 200 0 "-" "-"
my-website.com.localhost 127.0.0.1 - - [30/Jun/2021:09:50:45 +0200] "GET /health_check.php HTTP/1.1" 200 0 "-" "-"
my-website.com.localhost 127.0.0.1 - - [30/Jun/2021:09:50:50 +0200] "GET /health_check.php HTTP/1.1" 200 0 "-" "-"
my-website.com.localhost 127.0.0.1 - - [30/Jun/2021:09:50:55 +0200] "GET /health_check.php HTTP/1.1" 200 0 "-" "-"
```

I hope it helps

**Comment by jorgb90** [comment] 2021-11-11 13:41
@rou9e Thanks that helped! Got probe working now instead of removing it! 👍
