### ISSUE TITLE
Maximum execution time of 60 seconds exceeded & Allowed memory size of bytes exhausted

### ISSUE THREAD

**Issue by sanjaykesari28** [magento/magento2#36834] opened 2023-02-09 13:25 UTC
### Preconditions and environment

Hello Team,
We are using magento version - 2.4.5-p1 and 2.10 version of smile elasticsuite. In new relic log, we are getting below error continuously. Please help to fix this issue 

Error class: E_ERROR
Transaction name: [unknown](https://one.newrelic.com/nr1-core/errors/overview/Mjk0MjMxMHxBUE18QVBQTElDQVRJT058NzUyNzUwMTQy?account=2942310&duration=604800000&filters=%28domain%20IN%20%28%27APM%27%2C%20%27EXT%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27SERVICE%27%29%29&state=ef6b8f96-b9b5-a78f-cfd2-f95f55fcc32a)
Error message
Maximum execution time of 60 seconds exceeded
URL host: www.jaspal.com
URL Path: /en/catalogsearch/result/index/
Stack Trace
 in GuzzleHttp\Ring\Client\CurlFactory::GuzzleHttp\Ring\Client\{closure} called at ? (?)
 in curl_exec called at /app/fpkici6hpuyvi/vendor/ezimuel/ringphp/src/Client/CurlHandler.php (89)
 in GuzzleHttp\Ring\Client\CurlHandler::_invokeAsArray called at /app/fpkici6hpuyvi/vendor/ezimuel/ringphp/src/Client/CurlHandler.php (68)
 in GuzzleHttp\Ring\Client\CurlHandler::__invoke called at /app/fpkici6hpuyvi/vendor/ezimuel/ringphp/src/Client/Middleware.php (30)
 in GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure} called at /app/fpkici6hpuyvi/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php (265)
 in Elasticsearch\Connections\Connection::Elasticsearch\Connections\{closure} called at /app/fpkici6hpuyvi/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php (241)
 in Elasticsearch\Connections\Connection::performRequest called at /app/fpkici6hpuyvi/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php (110)
 in Elasticsearch\Transport::performRequest called at /app/fpkici6hpuyvi/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php (63)
 in Elasticsearch\Namespaces\AbstractNamespace::performRequest called at /app/fpkici6hpuyvi/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php (79)
 in Elasticsearch\Namespaces\IndicesNamespace::analyze called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php (199)
 in Smile\ElasticsuiteCore\Client\Client::analyze called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Index.php (229)
 in Smile\ElasticsuiteThesaurus\Model\Index::getSynonymRewrites called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Index.php (135)
 in Smile\ElasticsuiteThesaurus\Model\Index::computeQueryRewrites called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Index.php (110)
 in Smile\ElasticsuiteThesaurus\Model\Index::getQueryRewrites called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php (131)
 in Smile\ElasticsuiteThesaurus\Plugin\QueryRewrite::getWeightedRewrites called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php (88)
 in Smile\ElasticsuiteThesaurus\Plugin\QueryRewrite::aroundCreate called at /app/fpkici6hpuyvi/vendor/magento/framework/Interception/Interceptor.php (135)
 in Smile\ElasticsuiteCore\Search\Request\Query\Fulltext\QueryBuilder\Interceptor::Magento\Framework\Interception\{closure} called at /app/fpkici6hpuyvi/vendor/magento/framework/Interception/Interceptor.php (153)
 in Smile\ElasticsuiteCore\Search\Request\Query\Fulltext\QueryBuilder\Interceptor::___callPlugins called at /app/fpkici6hpuyvi/generated/code/Smile/ElasticsuiteCore/Search/Request/Query/Fulltext/QueryBuilder/Interceptor.php (23)
 in Smile\ElasticsuiteCore\Search\Request\Query\Fulltext\QueryBuilder\Interceptor::create called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Builder.php (119)
 in Smile\ElasticsuiteCore\Search\Request\Query\Builder::createFulltextQuery called at /app/fpkici6hpuyvi/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Builder.php (84)
------------------------------------------------------------------------------------------------------------------

### Steps to reproduce

We are getting this error into new relic report

### Expected result

Please help to fix this issue

### Actual result

Please help to fix this issue

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2023-02-13 05:03
Hi @sanjaykesari28 , Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance as per [System requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) installed and the issue is not reproducible.
Connection to new relic is successful and no errors observed in both new relic logs and Magento logs.
![image](https://user-images.githubusercontent.com/60198231/218374165-9ef2148d-0785-4cdc-8144-6825ef11e92a.png)
Smile elasticsuite is a 3rd party intergration. Kindly check if the issue caused due to 3rd party modules and recheck the issue on Magento 2.4-develop instance as per Magento system requirements and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by sanjaykesari28** [comment] 2023-02-27 13:00
Hello Support,

Thanks for update. As we are using cloud edition so we can not test this fresh magento setup. We have already shared our newrelic setup screenshot and in screenshot we can see this error is coming. May be this issue is occurring due to large catalog size. Please suggest if we can fix this error in our magento setup by increase php max execution time OR any other php/mysql global variable value. We really need to fix this ASAP. Quick reply would be appreciated. Thanks

**Comment by engcom-November** [comment] 2023-03-03 04:10
Hi @sanjaykesari28 ,

Thank you for the response. For the error ""PHP Fatal error: Maximum execution time of 60 seconds exceeded in…, you can update the maximum execution time by setting a custom max_execution_time value in your php.ini file and redeploying. Kindly refer the Magento devdocs - [Common PHP Fatal Errors and solutions](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/common-php-fatal-errors-and-solutions.html?lang=en) with example solutions that may help resolve your issue.
For the error: "Fatal error: Allowed memory size of .. bytes exhausted..", try running the following commands or refer the [devdocs](https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/app/php-settings.html) for PHP settings.

`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`
`php bin/magento setup:di:compile`
`php bin/magento cache:flush`
`php bin/magento cache:clean`

/*To Run Command Forcefully */
`php -f bin/magento`

/*To run command with memory limit 4G*/
`php -d memory_limit=4G bin/magento`

/*To run command with max memory limit */
`php -d memory_limit=-1 bin/magento`

Thank you.

**Comment by engcom-November** [comment] 2023-03-16 04:37
Hi @sanjaykesari28 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-03-16 04:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
