### ISSUE TITLE
Product URL issue with setting "Use Categories Path for Product URLs" set to 'Yes'

### ISSUE THREAD

**Issue by rav-redchamps** [magento/magento2#2839] opened 2015-12-30 09:48 UTC
**Issue Description:**

When we have two store views assigned to a store and we turn on setting  "Use Categories Path for Product URLs" then product URL for first store view became non seo friendly like below:

http://local.magento2.com/index.php/catalog/product/view/id/1924/category/28/

**Steps to replicate:**

1) In clean installation of Magento 2.0 create new store view for example "New Store View" andd attach it to store "Main Website Store".

2) Turn setting Catalog > Search Engine Optimization > "Use Categories Path for Product URLs" to 'Yes'

3) Go to any category page in front end and notice product URL on "Default Store View". They will appear like "http://local.magento2.com/index.php/catalog/product/view/id/1924/category/28/" where as on "New Store View" they will be "http://local.magento2.com/index.php/women/bottoms-women/shorts-women/fiona-fitness-short.html".

**Comment by antboiko** [comment] 2015-12-30 12:49
Hi @ravinders-121 , thank you for your inquiry. Please provide me some details. Is it the same one product and category you are accessing with these two URLs?

**Comment by rav-redchamps** [comment] 2015-12-30 12:55
Hi @antboiko

This issue is for all categories and all products after you follow steps under section 'Steps to replicate:' in my initial comment.

The two URLs I specified are of same product one is SEO friendly(available on newly created store view) and other is not (available on default store view).

Please free to let me know in case  you need any further details.

**Comment by tigerx7** [comment] 2016-01-02 17:14
This is probably a duplicate of: https://github.com/magento/magento2/issues/2619 Good find on that it doesn't happen on the additional storeview. This may be a good temporary workaround for now.

**Comment by vzabaznov** [comment] 2016-03-10 10:32
Seems like it cannot be reproduced on current develop branch
@ravinders-121 fell free to write comment, or open a new GitHub issue if you feel that issue has not been resolved

**Closed as completed by vzabaznov** 2016-03-10 10:32 UTC
