### ISSUE TITLE
Cart Price Rules are applied incorrectly for orders that contain Bundle Product Items 

### ISSUE THREAD

**Issue by vbyno** [magento/magento2#27351] opened 2020-03-19 08:09 UTC
### Preconditions (*)
Magento 2.3.1

### Steps to reproduce (*)

1. Create a Cart Price rule which add **$1** discount to whole order
![image](https://user-images.githubusercontent.com/2923624/77044741-a1f84700-69c8-11ea-8b6c-d83f2fba4187.png)
2. Create a bundle product containing at least 2 products
2. Create an order that matches the Price rule and contains that bundle product.
![image](https://user-images.githubusercontent.com/2923624/77044860-d79d3000-69c8-11ea-850b-1af8f8949f43.png)

### Expected result (*)
1. The total discount is **$1** 

### Actual result (*)
1. The total discount is **$0.5**

**Comment by ajijshekh123** [comment] 2020-03-20 05:39
Hi @vbyno,
I have reviewed this issue in Magento 2.3 Instance. Sometimes, Discount amount is properly displayed in cart page but the checkout page wrong discount amount is displayed.
In the Admin section, the wrong discount is displayed.
See attached the screenshot:
**FrontEnd:**

![Cart_AfterloadingTime](https://user-images.githubusercontent.com/24711761/77139221-24e9d200-6a9b-11ea-89cf-c15efe2b0bb4.jpg)

![Cart_OnloadingTime](https://user-images.githubusercontent.com/24711761/77139223-261aff00-6a9b-11ea-9f1a-e34299b3bd33.jpg)

![Checkout_DiscountAmount_Issue](https://user-images.githubusercontent.com/24711761/77139224-26b39580-6a9b-11ea-87db-c928612bd55e.jpg)

**Admin Section:**
![Issue](https://user-images.githubusercontent.com/24711761/77139228-2a471c80-6a9b-11ea-9e86-2938578add2c.jpg)

Thanks.

**Comment by ajijshekh123** [comment] 2020-03-20 09:13
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-20 09:13
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-20 09:14
Hi @ajijshekh123, here is your [Magento instance](https://i-27351-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27351-2-4-develop.instances.magento-community.engineering/admin_5c08](https://i-27351-2-4-develop.instances.magento-community.engineering/admin_5c08)
Login: `8953caeb` Password: `6b4d59b84e0c`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-03-20 09:29
@vbyno - Issue not reproduced in the Latest Magento 2.4 Instance.
See attached the screenshot:

![2 4 Discount issue](https://user-images.githubusercontent.com/24711761/77151169-67230b80-6abb-11ea-8c82-4a6b26dc6103.jpg)

![2 4 Discount issue_FrontEnd](https://user-images.githubusercontent.com/24711761/77151172-68543880-6abb-11ea-9e73-bf2c9a69df56.jpg)

Thanks.

**Comment by vbyno** [comment] 2020-03-20 11:36
Thank you , @ajijshekh123! 
I was trying to check how the combination of the rules works on that 2.4 instance. It seems to me, it works incorrect. Could you please elaborate?
Steps:
1) In addition to the $1 discount for whole order (created by you), I've created a new one 10% discount rule
![image](https://user-images.githubusercontent.com/2923624/77160069-42c13200-6aaf-11ea-91cf-52ed4444f543.png)
2) Create a new order (in Admin panel):
![image](https://user-images.githubusercontent.com/2923624/77160127-6dab8600-6aaf-11ea-94d4-43ba1b471e8b.png)

Expected behaviour:
Total discount is $**221** (2200 * 0.01 + $1)

Actual behaviour:
Total discount is $**220.90**

I understand that it might be a different issue, but we can check it now, since we already have it set

**Comment by kirtinariya1** [comment] 2020-04-25 10:15
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-25 10:15
Hi @kirtinariya1. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-25 10:16
Hi @kirtinariya1, here is your [Magento instance](https://i-27351-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27351-2-4-develop.instances.magento-community.engineering/admin_4815](https://i-27351-2-4-develop.instances.magento-community.engineering/admin_4815)
Login: `3fe7f393` Password: `a1c7dcb71305`
Instance will be terminated in up to 3 hours.

**Comment by kirtinariya1** [comment] 2020-04-25 12:14
Can't reproduce the issue.
it's working as expected.

![Screenshot from 2020-04-25 17-42-43](https://user-images.githubusercontent.com/28681937/80279587-5bf77700-871c-11ea-808e-c5864cae3e48.png)

**Comment by vbyno** [comment] 2020-04-25 12:18
@kirtinariya1 , thanks for checking! Have you tried the issue I've described [here](https://github.com/magento/magento2/issues/27351#issuecomment-601656068) , or the initial one?

**Comment by kirtinariya1** [comment] 2020-04-25 12:33
@vbyno I have checked both scenario.

**Comment by sdzhepa** [comment] 2020-06-15 15:57
Based on multiple comments above "non-issue", "expected behavior", "cannot reproduce"
we can close this issue

**Closed as completed by sdzhepa** 2020-06-15 15:57 UTC
Labels: Component: Checkout, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Bundle, Component: Rule, Reported on 2.3.1
