### ISSUE TITLE
Using 'widget_filters' in the wysiwyg editor config results in Forbidden page in modal

### ISSUE THREAD

**Issue by koenner01** [magento/magento2#25505] opened 2019-11-07 11:10 UTC
Currently when trying to use 'widget_filters' wysiwyg editor configuration data property, the insert widgets modal doesn't work.

### Preconditions (*)
1. PHP7.2
2. CE 2.3.3 (Also reproduced on CE.2.2.8)

### Steps to reproduce (*)
1. Have (or create) a shit load of widgets in your project (that have is_email_compatible = 0)
2. In Adminhtml go to Marketing > Communications > Newsletter Template
3. Click "Add new template"
4. In the wysiwyg editor try to insert a widget

### Expected result (*)
1. The insert widget model shows up with a list of widgets to insert

### Actual result (*)
1. The insert widget model shows up with a "Forbidden: You don't have permission to access this resource." page.

The issue is due to the fact that the skipped widgets are being encoded and appended to the "../admin/widget/index/skip_widgets/" url. If we are trying the skip A LOT of widgets the encoded widgets generate gigantic strings. This causes the POST request to fail because it cannot be processed. (according to google the maximum url size is 2048 characters).

You can check how many widgets are skipped (and how long the encoded widgets are) in \Magento\Widget\Model\Widget\Config::getWidgetWindowUrl

Potential fix would be to add this encoded property in the post data as the request is a POST request...

**Comment by engcom-Charlie** [comment] 2019-11-19 12:05
Hello @koenner01 

We are not able to reproduce this issue on the latest 2.3-develop branch.

**Testing scenario:**

1. Have (or create) a shit load of widgets in your project (that have is_email_compatible = 0)
2. In Adminhtml go to Marketing > Communications > Newsletter Template
3. Click "Add new template"
4. In the wysiwyg editor try to insert a widget(changed values of ​​`is_email_compatible` to 0)
![image](https://user-images.githubusercontent.com/51680850/69139653-9e5fbc80-0ac9-11ea-9e81-edb890b9706e.png)

**Result:**
The insert widget model shows up with a list of widgets to insert:
![image](https://user-images.githubusercontent.com/51680850/69139690-b8999a80-0ac9-11ea-9e07-5978e3c90bf0.png)

So i have to close this issue.
Thanks for your report!

**Comment by koenner01** [comment] 2019-11-19 12:09
How many widgets do you have that have is_email_compatible set to 0 ?

The issue appears when you really have a LOT (numbers varies as the class path is being used in the encoded string.

Please try to reproduce this by scaling up the amount of widgets you have.

**Comment by engcom-Charlie** [comment] 2019-11-19 12:58
@koenner01 
I set 0 for all available widgets

**Comment by engcom-Charlie** [comment] 2019-11-20 12:01
@koenner01 could you verify it on Magento 2.3-develop?

**Comment by engcom-Charlie** [comment] 2019-12-05 14:49
We are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Charlie** 2019-12-05 14:49 UTC
Labels: Progress: needs update, Issue: Format is valid
