### ISSUE TITLE
Backend Product Edit Page Loads Indefinitely - JavaScript Console Error: Uncaught TypeError: value is null (Firefox Only)

### ISSUE THREAD

**Issue by nikoelgatito** [magento/magento2#36863] opened 2023-02-15 04:17 UTC
### Preconditions and environment

- Magento Version 2.4.3-p3 (2.4.3+)
- The Magento_PageBuilder module is installed and enabled.
- The latest version of the Firefox browser is installed.

### Steps to reproduce

1. Navigate to the backend product edit page using the Firefox browser.

### Expected result

The backend product edit page loads normally.

### Actual result

The backend product edit page loads indefinitely and the JavaScript error "Uncaught TypeError: value is null" is displayed in the console.

**Important Note:**
For some reason, this bug is not triggered if the developer tools/console is already open when opening the backend product edit page. In order to reproduce this issue, it is important to first open the backend product edit page and then open the developer console.

### Cause & Solution:

The issue is caused by the fact that the function passed when adding the 'required-entry' rule does not verify if the `value` variable is `null` before using it as an `object` in the validator-rules-mixin.js file. The error is triggered even if there is an `object` type verification before trying to access the object's properties, since the type of a `null` value is `object` in JavaScript.

**File Path:**
vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js

Simply adding `&& value !== null` is enough to prevent this issue from occurring.

Please refer to the patch below for more details.

**Git Diff Patch:**
```
diff --git a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js
--- a/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js
+++ b/vendor/magento/module-page-builder/view/adminhtml/web/js/form/element/validator-rules-mixin.js
@@ -234,7 +234,7 @@
                 var allFilled;
 
                 // Validation only for margins and paddings
-                if (typeof value === 'object' && !!(value.padding || value.margin)) {
+                if (typeof value === 'object' && value !== null && !!(value.padding || value.margin)) {
                     allFilled = true;
 
                     _.flatten(_.map(value, _.values)).forEach(function (val) {`

```

After reviewing the latest version of the validator-rules-mixin.js file, it seems that this issue is still present, as the function still does not verify if the `value` variable could be `null` before attempting to access its properties.

**Link to the Latest File Version:**
[https://github.com/magento/magento2-page-builder/blob/47efafdc662272dfea91c4abd1968e63f9aa38df/app/code/Magento/PageBuilder/view/adminhtml/web/js/form/element/validator-rules-mixin.js#L237](https://github.com/magento/magento2-page-builder/blob/47efafdc662272dfea91c4abd1968e63f9aa38df/app/code/Magento/PageBuilder/view/adminhtml/web/js/form/element/validator-rules-mixin.js#L237)

### Workaround:
Use another browser.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nikoelgatito** [comment] 2023-02-15 04:27
@magento give me 2.4-develop instance

**Comment by nikoelgatito** [comment] 2023-02-15 04:42
After testing on the 2.4-develop instance provided on the same Firefox browser version, it seems that this issue cannot simply be reproduced on a vanilla Magento instance. However, since simply passing a null value to the 'required-entry' validation rule would trigger this issue, applying the fix provided would be preferable to prevent the likelihood of triggering this issue through future additions or customizations.

**Comment by engcom-Dash** [comment] 2023-02-15 18:15
Hi @nikoelgatito ,

Verified the issue in 2.4-develop instance and the issue is not reproducible.

Preconditions:
Magento Version - 2.4-develop
PHP 8.1

Steps:
1.Install Magento Instance
2.Install Page Builder in the Magento
3.Go to Admin Panel
4.Click on Sales >> Order
5.Edit the order.

Screenshots:
<img width="1512" alt="Screenshot 2023-02-15 at 11 30 19 PM" src="https://user-images.githubusercontent.com/60198592/219117204-0c86e5c8-22be-496e-a98f-2d1bf6d2d7af.png">
<img width="1512" alt="Screenshot 2023-02-15 at 11 42 19 PM" src="https://user-images.githubusercontent.com/60198592/219117226-3fc86900-6101-4468-a0e9-437043216636.png">

Let us know if we are missing Anything

Thanks.

**Comment by engcom-Dash** [comment] 2023-02-27 23:17
Hi @nikoelgatito ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Dash** 2023-02-27 23:17 UTC
Labels: Issue: needs update, Reported on 2.4.3-p3
