### ISSUE TITLE
Email styles not applied when using client-side less compilation

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#32969] opened 2021-05-07 09:10 UTC
When sending out emails in developer mode and client-side less compilation, all less compilation is disabled and emails appear unstyled.

### Preconditions (*)

1. Magento CE 2.3.4
2. PHP 7.3.X

### Steps to reproduce (*)

1. Set Magento in developer mode
2. Enable client-side less compilation
3. Make Magento send out an email (order-status update)

### Expected result (*)

1. A styled email

### Actual result (*)

1. The email is completely unstyled. LESS code is still visible in the email source:

``` HTML
<!-- Extracted from email - Some character escaping going on -->

<style type=3D"text/css">=0A        =0A=0A =20=
      =0A=0A=0A=0A=0A=0A@import 'source/lib/_lib.less'; // Global lib=0A=
@import 'source/lib/variables/_email.less'; // Global email variables=0A=
@import 'source/_theme.less'; // Global variables override=0A@import 'so=
urce/_variables.less'; // Local theme variables=0A@import 'source/_email=
-variables.less'; // Theme variables for emails=0A=0A=0A=0A@import (refe=
rence) 'source/_email-base.less'; // Contains primary email styles=0A@im=
port (reference) 'source/_email-extend.less'; // Contains theme-specific=
 adjustments to email styles=0A=0A=0A=0A=0A@import (reference) '../Magen=
to_Bundle/css/source/_email.less';=0A@import (reference) '../Magento_Rma=
/css/source/_email.less';=0A@import (reference) '../Magento_Sales/css/so=
urce/_email.less';=0A=0A=0A=0A=0A@import 'source/lib/_responsive.less';=
=0A=0A@media-target: 'all';=0A=0A=0A=0A=0A.email-non-inline();=0A=0A   =20=
</style>
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

While non-critical, I've spend a full day trying to debug this. In that case of email, LESS should always be parsed. Client side less compilation in email is never going to work.

**Comment by engcom-Echo** [comment] 2021-06-01 09:02
Hi Vandijkstef,

We followed the steps to reproduce , but were not able to reproduce the issue. In our case email was sent with all attached style.
Please refer the below screenshot

<img width="1007" alt="Screenshot 2021-06-01 at 2 28 54 PM" src="https://user-images.githubusercontent.com/51681435/120296758-11b0d400-c2e6-11eb-85a9-39fdfc291c04.png">

Thanks

**Comment by vandijkstef** [comment] 2021-06-02 13:42
Hi @engcom-Echo ,

Thats unfortunate. Ill will indeed try to reproduce the issue on 2.4-develop myself.
Won't be able to dive into in the coming days, but it's on my list.

**Comment by engcom-Echo** [comment] 2021-06-15 09:59
Hi @vandijkstef ,

Were you able to test the same on 2.4-develop ?

Thanks

**Comment by vandijkstef** [comment] 2021-06-16 09:27
Hi @engcom-Echo ,

Not yet. I've been moving houses in the last weeks, hence the delay.
Will have a look at it either tomorrow or saturday

**Comment by engcom-Hotel** [comment] 2021-06-29 07:13
Hi @vandijkstef,

It seems that your issue has been resolved, since we are not receiving your comment. We are closing this ticket for now, if you are still facing the issue and any new issue, you can create new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-06-29 07:13 UTC
Labels: Component: Email, Issue: needs update, Reported on 2.3.4
