### ISSUE TITLE
Magento 2.3.5 Review Link on click error

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#29870] opened 2020-09-02 14:05 UTC
### Preconditions (*)

1.Magento2.3.5
2.Have products

### Steps to reproduce (*)

1.Navigate to product page
2.clicks on the link : Be the first to review this product
<img width="623" alt="Screenshot 2020-09-02 at 15 03 59" src="https://user-images.githubusercontent.com/3495481/91993664-8fcb5480-ed2d-11ea-948e-b508e889e7f4.png">

### Expected result (*)

1. [Screenshots, logs or description]
2. Scroll and open reviews tab.

### Actual result (*)

1. [Screenshots, logs or description]
2.error in console.
<img width="865" alt="Screenshot 2020-09-02 at 15 02 37" src="https://user-images.githubusercontent.com/3495481/91993503-5db9f280-ed2d-11ea-8e80-2a6fc6a4e705.png">

File: http://magento2.com/static/version1599053492/frontend/Magento/luma/nl_NL/jquery.js
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-09-08 04:48
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-09-08 04:48
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-09-08 04:49
Hi @ajijshekh123, here is your [Magento instance](https://i-29870-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29870-2-4-develop.instances.magento-community.engineering/admin_3142](https://i-29870-2-4-develop.instances.magento-community.engineering/admin_3142)
Login: `09d574dc` Password: `5088b896a987`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-09-08 04:55
Hi @lano-vargas,
Verified this issue in the latest Magento 2.4 Instance but not reproduced this issue as per your steps and configuration
PFA:
![image](https://user-images.githubusercontent.com/24711761/92434454-7c047000-f1bd-11ea-920d-e5d67769407e.png)

Thanks

**Comment by ajijshekh123** [comment] 2020-09-08 04:56
@magento give me 2.3.5p1-develop instance

**Comment by magento-engcom-team** [comment] 2020-09-08 04:56
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5p1-develop instance for you

**Comment by ajijshekh123** [comment] 2020-09-08 05:46
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-09-08 05:46
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-09-08 05:47
Hi @ajijshekh123, here is your [Magento instance](https://i-29870-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29870-2-3-5-p1.instances.magento-community.engineering/admin_fe70](https://i-29870-2-3-5-p1.instances.magento-community.engineering/admin_fe70)
Login: `e15f225d` Password: `919758413c3c`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-09-08 05:57
Hi @lano-vargas,
Verified issue in the Latest Magento 2.3.5p1 Instance but not able to reproduce the issue.
**PFA:**
![image](https://user-images.githubusercontent.com/24711761/92438282-24b6cd80-f1c6-11ea-959f-96d1042c8a0e.png)

Thanks.

**Comment by ajijshekh123** [comment] 2020-09-08 05:57
@magento give me 2.3.5-p2 instance

**Comment by magento-engcom-team** [comment] 2020-09-08 05:57
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.3.5-p2 instance for you

**Comment by magento-engcom-team** [comment] 2020-09-08 05:58
Hi @ajijshekh123, here is your [Magento instance](https://i-29870-2-3-5-p2.instances.magento-community.engineering).
Admin access: [https://i-29870-2-3-5-p2.instances.magento-community.engineering/admin_0191](https://i-29870-2-3-5-p2.instances.magento-community.engineering/admin_0191)
Login: `e1e071c7` Password: `cb8bd24bdcc5`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-09-08 06:01
Hi @lano-vargas,
Verified Issue in Magento 2.3.5p2 Instance but not able to reproduce the issue.
PFA:
![image](https://user-images.githubusercontent.com/24711761/92438688-e1109380-f1c6-11ea-8cfb-7675e396c4b5.png)

Thanks.

**Comment by ajijshekh123** [comment] 2020-09-08 06:05
Hi @lano-vargas,
This error is related to the Third-party extension Or it may be some irrelevant component issue.
Please verify this issue its proper end and Update the scenario.

Thanks

**Comment by lano-vargas** [comment] 2020-09-08 09:01
Hi @ajijshekh123 Thanks for the update.

It's strange I think there are things that could have influenced the bug which I don't think instances given has. E.G: I have website nl, store nl_store and store view nl_store_view. Also have building a theme for nl but once I change back to Luma theme this error occurs, I've setup:upgrade, clean:cache, flush compile etc...
maybe that's where the bug is... what I notice that when changing to luma `baseUrl` nl_NL is still in the link : `/static/version1599554930/frontend/Magento/luma/nl_NL` 

I can be a trick one...

**Comment by mrtuvn** [comment] 2020-09-10 03:00
Do you have customise on theme ? Maybe some block related reviews moved away and link will not work anymore

**Comment by mrtuvn** [comment] 2020-09-22 14:02
I can confirm this problem may come from customise theme or custom module work with review block default
Here is review tab define
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/view/frontend/layout/catalog_product_view.xml#L21
tab content link to tab id #tab-label-reviews
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/view/frontend/templates/review.phtml#L17

**Comment by engcom-Alfa** [comment] 2020-11-09 13:30
Hi @lano-vargas .

Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop. 

**Manual testing scenario:**

1.Navigate to product page
2. Click on the link: _Be the first to review this product_

**Actual Result:** :heavy_check_mark: Scrolled and opened reviews tab without JS errors.

![Peek 2020-11-09 15-20](https://user-images.githubusercontent.com/51679138/98547126-60424680-22a0-11eb-9371-ad5c0906430a.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-09 13:30 UTC
Labels: Area: Frontend, Component: Review, not-confirmed, Reported on 2.3.5
