### ISSUE TITLE
Setting image keep frame to false in theme's view.xml does not work

### ISSUE THREAD

**Issue by brendanmckeown** [magento/magento2#4622] opened 2016-05-23 01:49 UTC
## Steps to reproduce
1. In the current theme's view.xml file, add `<frame>false</frame>` to a specific image type as instructed in the docs: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-images.html . This image should also have a `width` and `height` setting and `aspect_ratio` set to true. For example:

```
            <image id="category_page_grid" type="small_image">
                <width>460</width>
                <height>460</height>
                <aspect_ratio>true</aspect_ratio>
                <frame>false</frame>
            </image>
```
1. Clear image cache, refresh a page with this specific image type.
## Expected result
1. Image should keep its aspect ratio, not have any added white frame, and size should be within the configured width and height.

<img width="474" alt="screen shot 2016-05-22 at 9 41 50 pm" src="https://cloud.githubusercontent.com/assets/1933201/15458318/1b586c34-2066-11e6-9efc-734a02060840.png">
## Actual result
1. Image is forced to width and height with white frame, and does not keep original aspect ratio.

<img width="476" alt="screen shot 2016-05-22 at 9 42 15 pm" src="https://cloud.githubusercontent.com/assets/1933201/15458320/1f567ce0-2066-11e6-9258-66b9adf45bff.png">

Cause:
The value from view.xml is passed to the method \Magento\Catalog\Model\Product\Image::setKeepFrame – which casts the string "false" to the boolean true. Therefore, it is not possible to set keep_frame to false from within the view.xml. 

```
    /**
     * @param bool $keep
     * @return $this
     */
    public function setKeepFrame($keep)
    {
        $this->_keepFrame = (bool)$keep;
        return $this;
    }
```

After creating a plugin to convert the string value to an integer (which properly casts to a boolean), the image frame is not added.

```
    public function beforeSetKeepFrame($image, $keep)
    {
        if (is_string($keep)) {
            $keep = (strtolower($keep) === 'true') ? 1 : 0;
        }
        return [$keep];
    }
```

**Comment by leoquijano** [comment] 2016-05-24 03:25
I can confirm the issue: 

Setting the value to "false" in `view.xml` will make it true: 
`(bool) "false" = true`

Setting the value to "0" in `view.xml` will make it empty:
`empty("0") = true`

Thanks @brendanmckeown for the workaround, it does work.

**Comment by zanilee** [comment] 2016-05-24 13:57
Hi, @brendanmckeown!

Thank you for reporting this issue. Internal ticket MAGETWO-53411

**Comment by Yonn-Trimoreau** [comment] 2016-06-01 15:07
+1

**Comment by markdavies** [comment] 2016-10-23 18:27
This is still an issue months later, any update?

**Comment by PascalBrouwers** [comment] 2016-12-21 09:46
@rgoncharuk Can you merge the pull request https://github.com/magento/magento2/pull/7262 ?
It passed all checks, etc.

**Comment by ishakhsuvarov** [comment] 2017-03-24 07:56
@brendanmckeown @markdavies @PascalBrouwers 
PR #7262 is now merged into the `develop` branch. Issue should be fixed. Closing.

**Closed as completed by ishakhsuvarov** 2017-03-24 07:56 UTC
Labels: Issue: Ready for Work, bug report

**Comment by stianmartinsen** [comment] 2017-04-20 07:52
@brendanmckeown Before PR #7262 is live, do you have any idea why your fix works smoothly in dev mode, but not in production mode?

**Comment by tigerx7** [comment] 2017-05-08 04:49
@stianmartinsen I may have found the reason why... by correcting the boolean value for keepFrame, it exposed a bug in https://github.com/magento/magento2/blob/2.1/app/code/Magento/Catalog/Model/Product/Image/ParamsBuilder.php in which build() checks the frame parameter with the empty function `$frame = !empty($imageArguments['frame'])` which will evaluate that if statement as false since empty will return true on a false value. Since the if statement is evaluated as false, `ParamsBuilder::build()` uses the classes default value for keepFrame which is true.

```php
$frame = !empty($imageArguments['frame'])
    ? $imageArguments['frame']
    : $this->keepFrame;
```

So although the images are being created correctly now, since ParamsBuilder is returning the incorrect parameters that are used for the MD5 cache directory hash, the url path returned to the frontend gallery is pointing to the wrong cache directory.

This one was a frustrating bug to hunt down since it was giving the impression that the original problem fixed by PR https://github.com/magento/magento2/pull/7262 was still occurring. I have no idea why empty() is being used to check the existence of the frame argument in `build()`. Perhaps `isset()` was meant to be used? I really wish Magento had a much more improved QA; too many critical bugs are still making their way into releases.
