### ISSUE TITLE
Adding special price to bundle product breaks admin catalog grid in Magento 2.4.5

### ISSUE THREAD

**Issue by dphilipps** [magento/magento2#36731] opened 2023-01-11 15:41 UTC
### Preconditions and environment

- 2.4.5-p1

### Steps to reproduce

Create a bundle product
Add Special Price (under Advanced Pricing)
Save product
In Catalog grid, search for the product you created

### Expected result

Product should be listed in grid

### Actual result

Error message is displayed and product not displayed
"Something went wrong with processing the default view and we have restored the filter to its original state."

Exception:
main.CRITICAL: TypeError: Unsupported operand types: string / int in 
vendor/magento/module-bundle/Ui/DataProvider/Product/Modifier/SpecialPriceAttributes.php:80

Cannot continue to use grid until filters are cleared and on some occasions UI bookmarks need to be deleted

### Additional information

The condition causing the error is $item[$priceAttribute] is formatted as a string with a currency symbol which throws the numberFormatter exception.
$item[$priceAttribute] = $numberFormatter->format($item[$priceAttribute] / 100);

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dphilipps** [comment] 2023-01-11 15:42
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-12 16:15
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-12 23:34
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-13 01:51
Hi @dphilipps ,

We are trying to reproduce the issue in 2.4-develop branch,But we are not able to reproduce the issue.
 Magento version -2.4develop
PHP 8.1

Steps we followed by:

1.Install fresh instance
2.Create one Bundle product 
3.Go to advance pricing in bundle product and add special price
4.Check the Product grid product is available or not.

Screenshot for your reference:
<img width="1512" alt="Screenshot 2023-01-13 at 7 13 15 AM" src="https://user-images.githubusercontent.com/60198592/212218468-0f13c658-73d9-4aa3-b28d-27de2902befb.png">
<img width="1512" alt="Screenshot 2023-01-13 at 7 14 12 AM" src="https://user-images.githubusercontent.com/60198592/212218496-397221d5-9372-48ec-b884-02068c78f83a.png">

After adding the special price for the bundle product...the product displaying in product grid.

Let us know if we are missing anything!!!

Thanks!!!

**Comment by dphilipps** [comment] 2023-01-19 10:18
@magento give me 2.4.5-p1 instance

**Comment by dphilipps** [comment] 2023-01-19 14:04
Hi @engcom-Dash 

- I have reproduced this locally on a fresh composer install of 2.4.5-p1 (I simply added a special price to Luma's Sprite Yoga Companion Kit). 
- I cannot reproduce it on the Magento instance of 2.4.5-p1 above.

This leads me to wonder if it may be environment specific such as ICU PHP library as the issue seems to be to do with formatting currency (in this case removing the currency symbol for bundle special prices which are represented as a %). 

In which case it might not have been 'fixed' in the dev branch and I am might see to same issue exhibit itself on my environment when the next version of Magento is released.

Do you have a local 2.4.5-p1 you can test on?

**Comment by dphilipps** [comment] 2023-01-19 14:12
For anyone else who runs into this and needs to get their product grid working again:

Stores->Attributes->Product->Special Price->Properties and set "Add to Column Options" = NO.  

This will remove the ability to include Special Price as a column on the grid and will stop the error regardless of whether or not 'Special Price' was already added as a column on the grid.

**Comment by hostep** [comment] 2023-01-19 21:59
Sounds similar to: https://github.com/magento/magento2/issues/36284 which was fixed in https://github.com/magento/magento2/commit/9456a2659f3466046e1d5c7eb45ae60bd4703934

Not sure if it's exactly the same, but maybe it's a fix to try out?

**Comment by engcom-Dash** [comment] 2023-01-20 03:15
Hi @dphilipps ,

Thanks for the information!!!
Verified the issue 2.4.5-p1 local instance and we got same results.After giving special price in advance pricing the respective product is displaying in product grid.
Screenshots: 
<img width="948" alt="Screenshot 2023-01-20 at 8 36 30 AM" src="https://user-images.githubusercontent.com/60198592/213610037-1de8b371-0400-4c02-bf02-5a3ff8eb19da.png">
<img width="1512" alt="Screenshot 2023-01-20 at 8 37 50 AM" src="https://user-images.githubusercontent.com/60198592/213610053-900245ec-09e4-4fc5-b954-64b2f0953da3.png">
<img width="1512" alt="Screenshot 2023-01-20 at 8 39 38 AM" src="https://user-images.githubusercontent.com/60198592/213610059-4dd314fe-d727-492f-b704-1f96b0cd46dd.png">
<img width="1498" alt="Screenshot 2023-01-20 at 8 40 04 AM" src="https://user-images.githubusercontent.com/60198592/213610082-ef4568d1-bc1b-41e9-8fc8-9c7129aefab8.png">

**Comment by engcom-Hotel** [comment] 2023-02-03 12:17
Dear @dphilipps,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-02-03 12:17 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
