### ISSUE TITLE
PHP Error instead of 404/getting redirected when accessing any directory in <root>/catalog/product/compare/

### ISSUE THREAD

**Issue by MikeD-J** [magento/magento2#33764] opened 2021-08-12 08:38 UTC
### Preconditions (*)
1. Magento 2.4.2-p2 (but presumably more versions).
2. Also reproducible on Magento 2.4-develop having B2B and EE Modules
3. Issue also observed in 2.4.3 

### Steps to reproduce (*)
1. Redirect to any directory within <root>/catalog/product/compare/ (e.g. https://www.quooker.nl/catalog/product/compare/)

### Expected result (*)
1. Getting 404 error page result (or getting redirected to a custom 404 page if present).

**Magento 2.4-develop clean instance behavior:**
On trying to access URL: <root>/catalog/product/compare/   , User is automatically routed to <root>/default/catalog/product_compare/
![image](https://user-images.githubusercontent.com/60198231/129351719-33b29c14-f86b-4a00-aee3-017151806b00.png)

### Actual result (*)
1. Getting either 'An error has happened during application run. See exception log for details.' or 'Error: Cannot instantiate abstract class Magento\Catalog\Controller\Product\Compare in /Users/michael/Sites/magentowebshop/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121' depending on verbosity.

![image](https://user-images.githubusercontent.com/60198231/129351656-54d01489-42bb-40e0-8573-8817fc897a7f.png)

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by engcom-November** [comment] 2021-08-13 07:22
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
On searching using the URL - /catalog/product/compare/  , User is redirected to URL: /catalog/product_compare/ and the page is accessible:
![image](https://user-images.githubusercontent.com/60198231/129319832-67bbfc95-471c-44c3-8fc6-126a76616667.png)
![image](https://user-images.githubusercontent.com/60198231/129319865-34dae586-cf55-4da7-813a-68f9a8f52100.png)
![image](https://user-images.githubusercontent.com/60198231/129319880-0a2d31a3-6b68-4aa7-b62b-9c8673c138da.png)

@MikeD-J , Kindly recheck the issue on Magento 2.4-develop branch and confirm if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-13 11:35
Verified the issue again on Magento 2.4-develop having EE and B2B Modules and the issue is reproducible.
**Note: Issue is not reproducible on Magento 2.4-develop clean instance.**
Issue is reproducible on Magento 2.4-develop having EE and B2B modules enabled and 2.4.3 Magento version as well.
**Steps to reproduce:**
Magento frontend - Navigate to URL:  http://magento.local/index.php/catalog/product/compare/
"An error has happened during application run. See exception log for details." is displayed in UI
![image](https://user-images.githubusercontent.com/60198231/129351394-2793315d-f92a-4b17-b987-c788981628bc.png)

Magento root/Var/log/exception.log:
...
[2021-08-13 11:26:51] main.CRITICAL: Error: Cannot instantiate abstract class Magento\Catalog\Controller\Product\Compare in /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /var/www/html/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /var/www/html/magento/vendor/magento/framework/App/ActionFactory.php(44): Magento\Framework\ObjectManager\ObjectManager->create()
#3 /var/www/html/magento/vendor/magento/framework/App/Router/Base.php(306): Magento\Framework\App\ActionFactory->create()
#4 /var/www/html/magento/vendor/magento/framework/App/Router/Base.php(167): Magento\Framework\App\Router\Base->matchAction()
#5 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Router\Base->match()
#6 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Router\Base\Interceptor->___callParent()
#7 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Router\Base\Interceptor->Magento\Framework\Interception\{closure}()
#8 /var/www/html/magento/generated/code/Magento/Framework/App/Router/Base/Interceptor.php(23): Magento\Framework\App\Router\Base\Interceptor->___callPlugins()
#9 /var/www/html/magento/vendor/magento/framework/App/FrontController.php(144): Magento\Framework\App\Router\Base\Interceptor->match()
#10 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#11 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#12 /var/www/html/magento/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#14 /var/www/html/magento/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#15 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#16 /var/www/html/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#18 /var/www/html/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#19 /var/www/html/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#20 /var/www/html/magento/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#21 {main} [] []
...

Magento 2.4-develop clean instance behavior: User is redirected to below URL automatically
http://magento.local/index.php/catalog/product_compare/ - Working fine
![image](https://user-images.githubusercontent.com/60198231/129351380-f30b866c-4b9a-41bc-8a23-17bea6e2812d.png)

**Comment by magento-engcom-team** [comment] 2021-08-13 11:40
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-43086` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-November** [comment] 2021-08-24 11:23
@MikeD-J , can you please confirm from where you are getting this url from store fonrt
https://www.quooker.nl/catalog/product/compare/
Thank you.

**Comment by MikeD-J** [comment] 2021-08-24 12:54
Nowhere, I was checking some meta tags on product compare pages and I directed to there directly in the url-bar by accident. That's when I got the unexpected behavior as described in this issue above.

**Closed as completed** 2022-01-19 14:48 UTC
Labels: Issue: Confirmed, Component: Url, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.3, Component: Frontend, Area: Content
