### ISSUE TITLE
Magento ver. 2.4.0 Cron scheduler not working XML site map.

### ISSUE THREAD

**Issue by vermarajesh60** [magento/magento2#33147] opened 2021-06-04 08:13 UTC
I have setup cron scheduler to create dynamic sitemap.xml over the website it's not working manual is working.

### Preconditions (*)

1. Magento 2.4-develop
2. Setup cron over the server

### Steps to reproduce (*)

1. Admin - Enable Sitemap (Stores - Configuration - Catalog - XML Sitemap)
2. Generate sitemap (Marketing - Seo & Search - Sitemap - Add Site map and Generate) - Sitemap is generated in Magento Root/pub/sitemap.xml
3. Setup and run Magento cron over the server

### Expected result (*)

1. Sitemap should be updated after running cron

### Actual result (*)

1. Sitemap is not getting updated from the Cron.
Note: Manual sitemap generation is working fine
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-06-04 13:50
Hi @vermarajesh60 ,

Can you please elaborate the steps to reproduce and expected/actual result so that we can re-produce the same.

Thanks

**Comment by vermarajesh60** [comment] 2021-06-06 06:31
Hi Anirban,

Thank you for your reply.

I have just configured the xml sitemap setting in the admin section and
manually generated the sitemap, after that i have set up the magento cron
over the server but the sitemap was not updated from cron. I have watched
sitemp after 2 -3 day but still the sitemap is not updated.

Even in the cron table there is no scheduler to update the sitemap.

Let me know if you need more clarification on the same.

Thanks again.

**Comment by vermarajesh60** [comment] 2021-06-08 00:51
Hi Anirban,

Have you checked anything on the above problem ?. Let me know if there is
anything required from my side.

**Comment by vermarajesh60** [comment] 2021-06-11 06:43
Hi Anirban,

Have you found anything to solve this problem?.

**Comment by engcom-November** [comment] 2021-06-23 14:57
Verified the issue on Magento 2.4-develop version and the issue is reproducible.
Steps to reproduce:
1. Admin - Enable Sitemap (Stores - Configuration - Catalog - XML Sitemap)
2. Generate sitemap (Marketing - Seo & Search - Sitemap - Add Site map and Generate) - Sitemap is generated in Magento Root/pub/sitemap.xml
3. Setup and run Magento cron over the server
Issue: Sitemap is not getting updated after running Cron jobs even after scheduled time.

**Comment by vermarajesh60** [comment] 2021-06-26 08:43
Are you guys looking into it?.

**Comment by magento-engcom-team** [comment] 2021-07-01 13:38
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42767` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Bashev** [comment] 2022-08-27 09:20
@magento give me 2.4-develop instance

**Comment by Bashev** [comment] 2022-08-27 11:51
this looks like to be fixed.

May cause problems if you are migrated from magento 1 and in the core_config_data you have migrated records for sitemaps.

Check ````SELECT * FROM core_config_data where path like 'crontab/default/jobs/sitemap_generate/%';```` and remove all of them. After that will be triggered correct instance of Sitemap Observer.

**Comment by lauraseidler** [comment] 2022-11-11 10:23
Is there any update on this? We are running into the same issue on 2.4.4-p2. Any workaround?

> May cause problems if you are migrated from magento 1 and in the core_config_data you have migrated records for sitemaps.
> 
> Check `SELECT * FROM core_config_data where path like 'crontab/default/jobs/sitemap_generate/%';` and remove all of them. After that will be triggered correct instance of Sitemap Observer.

For us, this is not the case (not migrated from Magento 1, and that query returns 0 rows)

**Comment by mpurish** [comment] 2023-03-09 12:39
Any update on this? I have a similar issue on Magento community 2.4.5 - cron is running successfully, but there's no sitemap job

**Comment by mohammedceil** [comment] 2023-05-12 12:54
@mpurish : for the time being use the **Wyomind** cron schedular module for cron job schedules and executions.

**Comment by JMLucas96** [comment] 2024-01-02 09:57
Any updates? Same issue there.

**Comment by frekvent-szabolcs** [comment] 2024-02-29 08:04
Keep in mind, that the sitemap generation does not update the file if nothing is changed. I tried to schedule the sitemap generation a few times and it only changed the file If I created a new product/cms page it can add to the sitemap.

**Comment by engcom-Bravo** [comment] 2024-06-17 04:02
Hi @vermarajesh60,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1439" alt="Screenshot 2024-06-17 at 09 31 26" src="https://github.com/magento/magento2/assets/51680745/4445632a-26d1-45ab-b228-ffe90e7b7efd">



The sitemap got generated after running Cron.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-17 04:02 UTC
Labels: Issue: Confirmed, Component: Sitemap, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.0, Reproduced on 2.4.2, Area: SEO
