### ISSUE TITLE
Cart rule Buy X only applies to single product but can be defined on category basis

### ISSUE THREAD

**Issue by indefinitedevil** [magento/magento2#19168] opened 2018-11-12 11:45 UTC
We have noticed an issue with applying cart price rules to a category in combination with a Buy X rule. Namely that the Buy X condition only works when there are enough items of a single product, and doesn't consider if there are enough products from the condition which is what we expected.

If there is an offer for "Get a discount for every two things you buy from this category", we expect it to count items on a category basis, and not on an individual product basis. You should be able to buy one of product X and one of product Y to get the discount, rather than having to buy two of product X to get the discount.

This may be related to #9214.

### Preconditions (*)

1. Magento 2.2.6

### Steps to reproduce (*)

1. Create a new Cart Price Rule with Rule Information as follows:

| Attribute | Value |
|------------------------------------|-----------------------|
| Rule Name | Test Rule |
| Active | Yes |
| Websites | All |
| Customer Groups | All |
| Coupon | No Coupon |

2. Set Conditions to:

||||||
|---|---|---|---|---|
| if | **ALL** | of these conditions are | **TRUE** |
| if | **Total quantity >= 2** | for subselection of items in cart matching | **ALL** | of these conditions |
| | **Category** | **is** | [category ID with available products] |

3. Set Actions to:

| Attribute | Value |
|---|---|
| Apply                              | Fixed amount discount |
| Discount Amount                    | 5                    |
| Maximum Qty Discount is Applied To | 0                     |
| Discount Qty Step (Buy X)          | 2                     |
| Apply to Shipping Amount           | No                    |
| Discard subsequent rules           | Yes                   |
| Free Shipping                      | No                    |

Set "Apply the rule only to cart items matching the following conditions (leave blank for all items)" to

||||||
|---|---|---|---|---|
| if | **ALL** | of these conditions are | **TRUE** |
| | **Category** | **is** | [category ID with available products] |

4. Save rule
5. Test 1: Go to frontend and add two different products from selected category to the cart (one of each)
6. Test 2: Go to frontend and add two different products from selected category to the cart (three of each)

### Expected result (*)

Test 1: Discount is applied to both items in the cart as they are both in the targeted category and there are two items in cart ($10 discount)
Test 2: Discount is applied to all items in the cart as there is an even number of items and they are all in the targeted category ($30 discount)

### Actual result (*)

Test 1: Discount is applied to no products as discounts are only applied if there are enough quantity of a single product, not a combined total of products ($0 discount)
Test 2: Discount is applied to four products (two from first product, two from second) and the third product of each is disregarded for discount purposes. ($20 discount)

**Comment by magento-engcom-team** [comment] 2018-11-12 11:46
Hi @indefinitedevil. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@indefinitedevil do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by indefinitedevil** [comment] 2018-11-12 11:46
@magento-engcom-team give me 2.2.6 instance

**Comment by magento-engcom-team** [comment] 2018-11-12 11:46
Hi @indefinitedevil. Thank you for your request. I'm working on Magento 2.2.6 instance for you

**Comment by magento-engcom-team** [comment] 2018-11-12 11:47
Hi @indefinitedevil, here is your [Magento instance](http://34.228.235.121/i-19168-2-2-6/).
Admin access: [http://34.228.235.121/i-19168-2-2-6//admin](http://34.228.235.121/i-19168-2-2-6//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-11-12 12:11
Hi @TomashKhamlai. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by TomashKhamlai** [comment] 2018-11-12 13:43
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-12 13:43
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-12 13:43
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-19168-2-3-develop/).
Admin access: [http://34.228.235.121/i-19168-2-3-develop//admin](http://34.228.235.121/i-19168-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by TomashKhamlai** [comment] 2018-11-13 09:03
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2018-11-13 09:03
Hi @TomashKhamlai. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-11-13 09:04
Hi @TomashKhamlai, here is your [Magento instance](http://34.228.235.121/i-19168-2-2-develop/).
Admin access: [http://34.228.235.121/i-19168-2-2-develop//admin](http://34.228.235.121/i-19168-2-2-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ewengcameron** [comment] 2018-11-15 15:37
Any update on this? We are experiencing this issue on 2.2.6.

**Comment by magento-engcom-team** [comment] 2018-12-21 12:09
@lisovyievhenii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97287`, `MAGETWO-97288` were created

**Comment by mannanmughal** [comment] 2019-03-10 05:17
I'm having the same issue, is there a solution provided yet?

**Comment by mannanmughal** [comment] 2019-03-10 05:17
> We have noticed an issue with applying cart price rules to a category in combination with a Buy X rule. Namely that the Buy X condition only works when there are enough items of a single product, and doesn't consider if there are enough products from the condition which is what we expected.
> 
> If there is an offer for "Get a discount for every two things you buy from this category", we expect it to count items on a category basis, and not on an individual product basis. You should be able to buy one of product X and one of product Y to get the discount, rather than having to buy two of product X to get the discount.
> 
> This may be related to #9214.
> 
> ### Preconditions (*)
> 1. Magento 2.2.6
> 
> ### Steps to reproduce (*)
> 1. Create a new Cart Price Rule with Rule Information as follows:
> 
> Attribute	Value
> Rule Name	Test Rule
> Active	Yes
> Websites	All
> Customer Groups	All
> Coupon	No Coupon
> 1. Set Conditions to:
> 
> if	**ALL**	of these conditions are	**TRUE**	
> if	**Total quantity >= 2**	for subselection of items in cart matching	**ALL**	of these conditions
> **Category**	**is**	[category ID with available products]	
> 1. Set Actions to:
> 
> Attribute	Value
> Apply	Fixed amount discount
> Discount Amount	5
> Maximum Qty Discount is Applied To	0
> Discount Qty Step (Buy X)	2
> Apply to Shipping Amount	No
> Discard subsequent rules	Yes
> Free Shipping	No
> Set "Apply the rule only to cart items matching the following conditions (leave blank for all items)" to
> 
> if	**ALL**	of these conditions are	**TRUE**	
> **Category**	**is**	[category ID with available products]	
> 1. Save rule
> 2. Test 1: Go to frontend and add two different products from selected category to the cart (one of each)
> 3. Test 2: Go to frontend and add two different products from selected category to the cart (three of each)
> 
> ### Expected result (*)
> Test 1: Discount is applied to both items in the cart as they are both in the targeted category and there are two items in cart ($10 discount)
> Test 2: Discount is applied to all items in the cart as there is an even number of items and they are all in the targeted category ($30 discount)
> 
> ### Actual result (*)
> Test 1: Discount is applied to no products as discounts are only applied if there are enough quantity of a single product, not a combined total of products ($0 discount)
> Test 2: Discount is applied to four products (two from first product, two from second) and the third product of each is disregarded for discount purposes. ($20 discount)

I'm having the same issue, is there a solution provided yet?

**Comment by orlythatscool** [comment] 2019-04-23 19:44
+1

**Comment by victortodoran** [comment] 2020-07-20 17:07
I don't know why is this labeled as an issue.

> If there is an offer for "Get a discount for every two things you buy from this category", we expect it to count items on a category basis, and not on an individual product basis. You should be able to buy one of product X and one of product Y to get the discount, rather than having to buy two of product X to get the discount. (Excerpt from the ticket)

The [documentation](https://docs.magento.com/user-guide/marketing/price-rules-cart-buy-x-get-y-free.html) clearly states what this feature is.

> Buy X quantity of product, get Y quantity for free.

More so.

In the Conditions section you configure the conditions the decide where the current rule can be applied or not on a cart. Then the configured Action is applied to all Items that match the Action Conditions. 

This is a feature request. Not an issue.

**Closed as completed** 2021-01-05 21:58 UTC
Labels: Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: SalesRule, Priority: P2, Progress: done

**Comment by vkolesny** [comment] 2021-01-05 22:12
L3 ticket, which is related to this GitHub issue, was closed as Not a Bug due to the Product Owner clarification:
"Discount Qty Step (Buy X)" is not supposed to be working in a way as merchant is expecting. It is only supposed to be used for "Buy X get Y Free" discount type, which is applied per cart item but not for sub-selection of products in cart.
In order create such cart rule as merchant is expecting we need to design a new rule type, but not fix a behavior of the current one.
