### ISSUE TITLE
Remove unneeded region definitions from the /checkout page.

### ISSUE THREAD

**Issue by pynej** [magento/magento2#6997] opened 2016-10-13 15:23 UTC
### Preconditions
1. Magento 2.1.1
2. PHP 5.6
3. Apache
### Steps to reproduce
1. In admin go to Store > Configuration >  General > Allowed Countries change this list to some limited set.  (We selected only United States for example.)
2. Clear all Magento caches.
3. Go to the Checkout page
### Expected result

1. Template/JSON code embedded in page should not have region_id definitions for all the disabled regions.
### Actual result

1. There is still 320KB of region definitions loaded on every /checkout request for all the regions we have disabled.  This is a major killer of performance on the checkout page as it has to download this data every time, wont be cached, and all the non-us region data in this case will never be used as we configured the site to only allow the us region.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-17 15:40
@pynej thank you for reporting! We created internal issue MAGETWO-59796, but additional investigation is necessary if the fix could be backward compatible.

**Comment by pynej** [comment] 2016-10-17 19:09
As an aside, we were sort of able to work around this issue by correctly configuring gzip compression on php files served under SSL.  This is really a workaround as the file is still large and the data still hd to be decompressed and processed unnecessarily.

**Comment by adragus-inviqa** [comment] 2016-10-24 15:44
Maybe related to this "feature request" - https://github.com/magento/magento2/issues/4217 ?

_It was moved to the forums, as I clearly wasn't serious about the problem. The trollface didn't help my cause. I think they'll move yours to the forums, too, @pynej. Clearly not a bug._

**Comment by SerhiyShkolyarenko** [comment] 2016-10-25 06:56
MAGETWO-40098 implies another approach and more changes, so it's a story in terms of scrum.

**Comment by SerhiyShkolyarenko** [comment] 2016-11-23 13:58
We are closing the issue as MAGETWO-59685 fix is delivered to the develop branch. Thank you!

**Closed as completed by SerhiyShkolyarenko** 2016-11-23 13:58 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout

**Comment by magento-team** [comment] 2017-08-01 01:09
Internal ticket to track issue progress: MAGETWO-67725
