### ISSUE TITLE
hyphen use in domain name , checkout not working Magento 2.4

### ISSUE THREAD

**Issue by kalvinder123** [magento/magento2#35794] opened 2022-07-22 06:18 UTC
### Preconditions and environment

- Magento version :2.4.3
- Anything else that would help a developer reproduce the bug
We have copied our site on domain cpp-ca.com (domain name have '-') , when you will register on site and login
and go for checkout, You will redirect on account page.
We have tested same site with other domain , subdomains , it working well, Only stop to work when  hyphen '-' use in domain name.

How we can solve this urgent bug??

### Steps to reproduce

1-> if domain have hyphen in url for ex:  abc-xyz.com
2-> get register as customer and login to site
3-> Add to cart and try to checkout , you will be redirect back on my account page, you will not able to checkout.
4-> Same site if you will use with other simple domain/subdomain even IP, it will work fine, only stop to work when hyphen '-' in domain name

### Expected result

expected result, when product in cart, and we go for checkout , it should work 
with domain which have hyphen '-' in url

### Actual result

Site redirected to my account page and customer not able to place the order

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kalvinder123** [comment] 2022-07-22 06:31
I have provide all the steps and live domain for test, kindly test and help

**Comment by engcom-November** [comment] 2022-07-27 12:17
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-07-28 09:51
Hi @kalvinder123 ,
Thank you for reporting and collaboration. Verified the issue on magento 2.4-develop branch with below steps but could not able to reproduce the issue.
Steps performed:
1. Setup multi store website with hyphen (-) in domain. Ex: http://gr-mg24ce-local/
2. Front-end  - Created customer account and logged in
3. Added product to cart and checkout
4. Placed order with Money order
No issue: Order placed successfully. User is not routed to account information page.
![image](https://user-images.githubusercontent.com/60198231/181476341-ce4d3cc0-d405-4673-96b4-e487f8cff5af.png)
Kindly recheck the issue on Magento 2.4-develop branch as it is the upcoming 2.4.x release and provide missing steps if the issue is still reproducible. Also check configuration details: any 3rd party extensions/modules enabled and [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) compatible for specific magento versions.
Thank you.

**Comment by engcom-November** [comment] 2022-08-11 11:38
Hi @kalvinder123 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-11 11:38 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
