### ISSUE TITLE
Problem with command setup:upgrade

### ISSUE THREAD

**Issue by Toregam** [magento/magento2#13936] opened 2018-03-03 13:22 UTC
### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. go to promt
2.I do the command: php bin/magento setup:upgrade

### Expected result

1. it was successful

### Actual result

1. The command doesn't find some folders.
what can i do?
![immagine](https://user-images.githubusercontent.com/32936901/36934739-37c4b3ae-1eee-11e8-872e-b48b9f5fd449.png)

**Comment by magento-engcom-team** [comment] 2018-03-05 08:55
@Toregam, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation.

**Comment by ankurvr** [comment] 2018-03-09 08:31
@Toregam That's not an issue. While cleaning if directory does not exist that means nothing to clean up. It will not create any problem in execution of your project.

**Comment by magento-engcom-team** [comment] 2018-04-11 11:12
@Toregam we are closing this now as suggestion in the comment above seems to be correct.
Thank you @ankurvr.

**Closed as completed by magento-engcom-team** 2018-04-11 11:12 UTC
Labels: Progress: needs update, non-issue, Issue: Format is valid
