### ISSUE TITLE
Rule with attribute scope global throws error on frontend

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#12674] opened 2017-12-13 14:56 UTC
When you configure a Catalog Products List Widget on a CMS page and use a rule condition on a multi select attribute and select more than one value, the cms page throws an error. This only happens if the selected attribute's scope is set to global, if it is set to something else, everything works fine.

### Precondition
- CE/EE 2.1.10

### Steps to reproduce
- Clean instance with sample data
- Open a cms page and add a Catalog Products List Widget
- Set the attribute "Material" to scope global (this is important)
- Add a rule condition and use "Material" as attribute. Select "contains" and select all values possible
- Save the widget and the cms page and open the cms page on the frontend

### Expected result
- The product list widget loads correctly

### Actual result
- The following error is thrown: "Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "2" already exists."

**Comment by magento-engcom-team** [comment] 2017-12-13 16:42
@sydekumf ,

**Comment by magento-engcom-team** [comment] 2017-12-13 16:43
@sydekumf , thank you for your report.
Please, add the following information:
 - [ ] Preconditions: Magento version

**Comment by magento-engcom-team** [comment] 2017-12-19 10:30
@sydekumf, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2017-12-19 10:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is not valid
