### ISSUE TITLE
Magento 2 CustomerAddressId missing for backend orders

### ISSUE THREAD

**Issue by boseasha** [magento/magento2#28793] opened 2020-06-18 09:47 UTC
### Preconditions (*)

In Magento 2 ,for backend orders created the customer_address_id is missing/NULL for sale order addresses
1.2.2.8
2.2.3.3

### Steps to reproduce (*)

1.Go to Magento 2 backend login. Create a new order for a new customer from Sales->Orders->Create New Order After the creation of Order you can see the customer_address_id in sales_order_address table as NULL for both shipping and billing address.
2.Again create a new order with the customer created last time and choose the address created in last order with the shipping address same as billing.

After the order creation when you check the sales_order_address table,we can see the customer_address_id is available for billing address but not for shipping address .

### Expected result (*)

1.The customer_address_id should be updated in sales_order_address table for botth billing and shipping address
2.The customer_address_id should be updated in sales_order_address table for shipping address

### Actual result (*)

1. NULL value for customer_address_id in both 
2.NULL value for customer_address_id in shipping address 

### Additional information
- issue has been confirmed on the latest `2.4-develop` code, detailed steps https://github.com/magento/magento2/issues/28793#issuecomment-647474485
- main precondition: when creating new address select checkbox use same for shipping address
- example of real business scenario https://github.com/magento/magento2/issues/28793#issuecomment-646537298

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-19 03:33
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-19 03:33
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-19 03:35
Hi @swathishs, here is your [Magento instance](https://i-28793-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28793-2-4-develop.instances.magento-community.engineering/admin_637e](https://i-28793-2-4-develop.instances.magento-community.engineering/admin_637e)
Login: `e437b8e4` Password: `cc755d2b6a1d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-19 04:10
@boseasha : The issue is not reproducible in 2.4-develop instance. I tried using the above step. Please find the attachment below:

1.  New order creation via admin billing address and shipping address different
![image](https://user-images.githubusercontent.com/58288685/85095961-922f0f80-b210-11ea-9b11-d3ccac89d91f.png)

2. After the creation of order:
![image](https://user-images.githubusercontent.com/58288685/85095997-a8d56680-b210-11ea-9f18-216fd9c9c240.png)

3. New order creation via admin billing address and shipping address same with last customer
![image](https://user-images.githubusercontent.com/58288685/85096053-cf939d00-b210-11ea-947a-86b2c3e8aa43.png)

4. After the creation of order:
![image](https://user-images.githubusercontent.com/58288685/85096107-efc35c00-b210-11ea-874c-bd1615252026.png)

**Comment by boseasha** [comment] 2020-06-19 09:21
@swathishs  Thanks for checking the issue.But i believe the issue is not fixed in magento 2.3.5 too.

My issue that in the database table ,the customer_address_id is missing....All the data are saved .
Please reconfirm

**Comment by boseasha** [comment] 2020-06-19 09:32
I can also explain a scenario in which i come up with this issue in magento default.

I have some custom customer address attributes,So after the order placing from backend admin side,i need to update them as well.In such a case where we dont have the customer_address_id for the sales orders can come up with a question like this.
Hope u can understand what I am referring to....  If we have the customer_Address_id we can update the extra attributes based on that. Since its missing we need a solution.

**Comment by swathishs** [comment] 2020-06-22 12:05
@boseasha: The issue is reproducible in Magento 2.4 develop instance.

Please find the attachment below:

1. Create default billing address and shipping address as same than in customer page after placing order default shipping address not set
![image](https://user-images.githubusercontent.com/58288685/85285296-4b5e4580-b4ae-11ea-8c6e-a09d05dd25b1.png)

2. Order page:
![image](https://user-images.githubusercontent.com/58288685/85285327-5b762500-b4ae-11ea-8d73-720b5942df16.png)

3. Sales order table:
![image](https://user-images.githubusercontent.com/58288685/85285368-70eb4f00-b4ae-11ea-9ddc-34d3c151105b.png)

**Comment by swathishs** [comment] 2020-06-22 12:14
1. Different address for billing and shipping address
![image](https://user-images.githubusercontent.com/58288685/85286189-c6742b80-b4af-11ea-9375-9910a04f6c87.png)

 2.Order page:
![image](https://user-images.githubusercontent.com/58288685/85286241-e4419080-b4af-11ea-9de5-cc791215f24d.png)

3. sales_order_address:
![image](https://user-images.githubusercontent.com/58288685/85286326-0d622100-b4b0-11ea-9cba-10ed85bd233d.png)

**Comment by magento-engcom-team** [comment] 2020-06-22 12:16
:white_check_mark: Confirmed by @swathishs 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35344` were created

**Issue Available**: @swathishs, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by slavvka** [comment] 2020-08-01 09:16
Hi @boseasha. Thank you for your report. 
The issue has been fixed in magento/magento2#29139 by @engcom-Echo in 2.4-develop branch
Related commit(s):
 - [c899815846aab642ed05e4f21aecc41367490cb3](https://github.com/magento/magento2/commit/c899815846aab642ed05e4f21aecc41367490cb3)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by slavvka** 2020-08-01 09:16 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.3
