### ISSUE TITLE
Cart isn't active issue - Creating duplicate orders

### ISSUE THREAD

**Issue by hamzagmi** [magento/magento2#38308] opened 2023-12-21 14:02 UTC
### Preconditions and environment

- Magento version 2.4.5
- Pwa Studio 

### Steps to reproduce

On our websites, we are facing duplicate order's due to an error since months now, and we can"t fix it:
Summary of the issue:

1/ consumers create an order by clicinkg on Submit order on the checkout page

2/ After few seconds wait, an error message _The cart isn’t active_ appear at the bottom right (see screenshot):

The cart isn’t active

![image](https://github.com/magento/magento2/assets/106997325/e57f07fe-5c6a-4440-879f-a68c75eac9c3)

3/ Consumer thinks his order is KO, so he retry multiple times to do other orders

4/ The order is in reality OK. All the other tries are KO and on canceled order status

5/ The consumer can see multiple authorization payment into his bank account + account history 

6/Consumers create a ticket to consumer service saying why i have done 4 orders? is my order ok? 

What we have done so far:
We have increased our timeout:

graphql request --> 150 seconds
All other requests --> 10 seconds

On the logs, this error seems to happen everyday, we also have it on staging environment...

|= root@ec2-admin-marcelle-m245-01 :: /data/marcelle.com/magento/shared/var/log =|
|=> cat system.log | grep -a "report.ERROR: The cart isn't active."
[2023-12-19T12:49:32.482804+00:00] report.ERROR: The cart isn't active.
[2023-12-19T12:49:42.022850+00:00] report.ERROR: The cart isn't active.
[2023-12-19T12:49:48.037794+00:00] report.ERROR: The cart isn't active.
[2023-12-19T14:10:22.302240+00:00] report.ERROR: The cart isn't active.
[2023-12-19T14:10:24.818524+00:00] report.ERROR: The cart isn't active.
[2023-12-19T14:10:26.807996+00:00] report.ERROR: The cart isn't active.
[2023-12-19T19:00:07.797024+00:00] report.ERROR: The cart isn't active.
[2023-12-19T20:11:49.504360+00:00] report.ERROR: The cart isn't active.
[2023-12-19T20:56:24.089155+00:00] report.ERROR: The cart isn't active.

I have also attached the logs when I did my tests
On my last test, the issue happened on mobile on 1 of my 3 tests orders (2 desktop, 1 mobile)
[marcelle-751059-tests15-12-2023 (1).txt](https://github.com/magento/magento2/files/13742601/marcelle-751059-tests15-12-2023.1.txt)

### Expected result

We need to avoid to have this error message on marcelle, the process should be:

1/ consumers create an order by clicinkg on Submit order

2/ It shows confirmation page and consumers is aware his order is ok.

### Actual result

1/ consumers create an order by clicinkg on Submit order on the checkout page

2/ After few seconds wait, an error message _The cart isn’t active_ appear at the bottom right (see screenshot):

The cart isn’t active

![image](https://github.com/magento/magento2/assets/106997325/e57f07fe-5c6a-4440-879f-a68c75eac9c3)

3/ Consumer thinks his order is KO, so he retry multiple times to do other orders

4/ The order is in reality OK. All the other tries are KO and on canceled order status

5/ The consumer can see multiple authorization payment into his bank account + account history 

6/Consumers create a ticket to consumer service saying why i have done 4 orders? is my order ok? 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-12-28 04:06
Hi @hamzagmi 

Thanks for reporting and collaboration.
Verified the issue in pwa stuido. Not able to reproduce the issue.
We are able to place the orders successfully and not seeing the cart isnt active error message.
Please refer the screenshots.
<img width="1440" alt="pwa-ss" src="https://github.com/magento/magento2/assets/60198592/fe8f4df4-169b-4896-a6f4-c54b3ace2c4e">
<img width="1440" alt="pwa-ss1" src="https://github.com/magento/magento2/assets/60198592/1bc0c385-deee-4024-b180-95759d335a88">

**Comment by engcom-Dash** [comment] 2024-01-11 12:59
Hi @hamzagmi 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-01-11 12:59 UTC
Labels: Issue: needs update, Reported on 2.4.5
