### ISSUE TITLE
children_count can become negative after deleting categories

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#27969] opened 2020-04-24 10:54 UTC
### Preconditions

1. Install clean Magento 2.3.4

### Steps to reproduce

1. Log in into admin backend
2. Navigate to Catalog -> Categories
3. Click "Add Subcategory"
4. Fill category name with "Parent 1", Save
5. Click "Add Subcategory"
6. Fill category name with "Child 1", Save
7. Click "Add Subcategory"
8. Fill category name with "Child 2", Save
9. Click "Add Subcategory"
10. Fill category name with "Child 3", Save. At this point this category should have level = 5
![2020-04-29_18-51-36](https://user-images.githubusercontent.com/3409584/80658140-edcbf080-8a4a-11ea-94e2-67814030a3bd.png)

11. Click on "Child 1" category
12. Delete category

### Expected result

1. Categories are deleted and children_count for remaining categories are valid eg. catalog_category_entity look as follows:

```
1    3    0    2020-02-05 18:38:54    2020-04-24 10:50:38    1    0    0    2
2    3    1    2020-02-05 18:38:54    2020-04-24 10:50:38    1/2    1    1    1
15    3    2    2020-04-24 10:49:35    2020-04-24 10:50:38    1/2/15    1    2    0
```

### Actual result

1. Categories are deleted but children_count for remaining categories are negative -  catalog_category_entity look as follows:

```
1    3    0    2020-02-05 18:38:54    2020-04-24 10:50:38    1    0    0    -1
2    3    1    2020-02-05 18:38:54    2020-04-24 10:50:38    1/2    1    1    -2
15    3    2    2020-04-24 10:49:35    2020-04-24 10:50:38    1/2/15    1    2    -3
```

![screenshot](https://user-images.githubusercontent.com/51679138/80585245-a843ff00-8a1b-11ea-9fd1-ea4d44ac08c5.png)

**Comment by engcom-Alfa** [comment] 2020-04-29 10:17
The issue is reproducible on a fresh 2.4-develop instance.

**Actual Result:**

Categories are deleted but children_count for remaining categories are negative
![screenshot](https://user-images.githubusercontent.com/51679138/80585245-a843ff00-8a1b-11ea-9fd1-ea4d44ac08c5.png)

**Comment by magento-engcom-team** [comment] 2020-04-29 10:23
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33835` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ProkopovVitaliy** [comment] 2020-04-29 12:31
I`m working on it.

**Comment by sdzhepa** [comment] 2020-04-29 14:10
@ProkopovVitaliy  fyi [Assigning an issue](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#assigning-an-issue)

**Comment by magento-engcom-team** [comment] 2020-06-24 03:01
Hi @wojtekn. Thank you for your report. 
The issue has been fixed in magento/magento2#28044 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [0dfd146b819b9bfd0ca0cd72e41e8c56c3debcae](https://github.com/magento/magento2/commit/0dfd146b819b9bfd0ca0cd72e41e8c56c3debcae)
 - [0fea657d349e9f509ee980cc2e1eabcdc41c7f84](https://github.com/magento/magento2/commit/0fea657d349e9f509ee980cc2e1eabcdc41c7f84)
 - [fc65f5b3ca97449c21c29ca4bf38b2b48d776577](https://github.com/magento/magento2/commit/fc65f5b3ca97449c21c29ca4bf38b2b48d776577)
 - [ce3d97f86e8a858e1877c8888eacf6e21f603c19](https://github.com/magento/magento2/commit/ce3d97f86e8a858e1877c8888eacf6e21f603c19)
 - [e7b6e452f74b9178a15ceac2b68f2904aace6a45](https://github.com/magento/magento2/commit/e7b6e452f74b9178a15ceac2b68f2904aace6a45)
 - [b07a831bf8b47876f2624349272e4cd6029ee03b](https://github.com/magento/magento2/commit/b07a831bf8b47876f2624349272e4cd6029ee03b)
 - [85ecd6edfd0790312ff192ec08378c754b45074d](https://github.com/magento/magento2/commit/85ecd6edfd0790312ff192ec08378c754b45074d)
 - [fd7663f9d14b1e7e22f35f3be795d7dce22a5bfc](https://github.com/magento/magento2/commit/fd7663f9d14b1e7e22f35f3be795d7dce22a5bfc)
 - [0242849f73e1c4b9728832ecd44ff467b307ea25](https://github.com/magento/magento2/commit/0242849f73e1c4b9728832ecd44ff467b307ea25)
 - [1ff938c3e1603810f2650f502a3405dded07203b](https://github.com/magento/magento2/commit/1ff938c3e1603810f2650f502a3405dded07203b)
 - [caf9ae2112cf37db04cce4a545e7cca8c7f6c151](https://github.com/magento/magento2/commit/caf9ae2112cf37db04cce4a545e7cca8c7f6c151)
 - [80e3107caaaf4173ffebeeedb92ec179ca47010e](https://github.com/magento/magento2/commit/80e3107caaaf4173ffebeeedb92ec179ca47010e)
 - [5300e3eb24bd11ae687974937078fb7976630fb2](https://github.com/magento/magento2/commit/5300e3eb24bd11ae687974937078fb7976630fb2)
 - [62ee4a28c4d32eb5d428492753c856d3cc71879f](https://github.com/magento/magento2/commit/62ee4a28c4d32eb5d428492753c856d3cc71879f)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-06-24 03:01 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.4

**Comment by huynhlehieunam** [comment] 2021-09-26 08:51
Do you guys have script to recalculate children count without deleting old category?

**Comment by WebKenth** [comment] 2021-10-15 09:29
> Do you guys have script to recalculate children count without deleting old category?

I have an sql statement that you could execute to recalculate it

```
UPDATE catalog_category_entity as a SET children_count = (SELECT count(a.entity_id) FROM (select * from catalog_category_entity) as b WHERE b.path LIKE CONCAT(a.path, '/%'));
``` 

Might take a while to execute it: here's an example
``` 
UPDATE catalog_category_entity as a SET children_count = (SELECT count(a.entity_id) FROM (select * from catalog_category_entity) as b WHERE b.path LIKE CONCAT(a.path, '/%'));

Query OK, 207 rows affected (17.063 sec)
Rows matched: 9834  Changed: 207  Warnings: 0
```

Not sure if it's bullet proof but it basically just counts the rows where the path is like the current row count

if you take a specific category you can simulate it by running 

Just replace the id's with one of your category Id's
Here im taking the category with an id of 25009 and using it's path to find all children
```
select * from catalog_category_entity where path like "1/2/25827/25009%"; 
```

**Comment by WebKenth** [comment] 2022-03-29 09:52
It is the year 2022 and this bug is still present
