### ISSUE TITLE
Wysiwyg editor issue when edit and save

### ISSUE THREAD

**Issue by pradeepnew** [magento/magento2#23864] opened 2019-07-24 14:05 UTC
The issue comes when I created a new block, put the content and save. Everything is fine at this stage. When I edit anything in content then save it again it will show the below issue.
When using {{config path='web/unsecure/base_url'}} for anchor tags then the string followed by the closing curly braces is removed. The original link removed and only the base URL is showing. 
For example, If URL is 

> {{config path='web/unsecure/base_url'}}apparel 

then its showing only as below(it removed apparel)

> {{config path='web/unsecure/base_url'}}
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.1

### Steps to reproduce (*)

1. Go to the admin panel and create a new block
2. Add some content which having anchor tags href as {{config path='web/unsecure/base_url'}}apparel  then Save the block.
3. Now edit anything except anchor href and save, Now all such href attributes values are changed.

### Expected result (*)

1. Href should not be changed {{config path='web/unsecure/base_url'}}apparel

### Actual result (*)

1. https://drive.google.com/file/d/1ccczA7r_xd139aox_r-aBDuJRBc7wDCs/view

**Comment by magento-engcom-team** [comment] 2019-07-25 06:52
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-07-25 06:52
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18586` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krzksz** [comment] 2019-12-02 21:01
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-02 21:01
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-02 21:02
Hi @krzksz, here is your [Magento instance](https://i-23864-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23864-2-3-develop.instances.magento-community.engineering/admin](https://i-23864-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment] 2019-12-02 21:11
Thanks for the contribution! I tested it using the steps you provided and I'm not able to reproduce the issue anymore so I'm closing this issue. Feel free to reopen it with updated reproduction steps.

**Closed as completed by krzksz** 2019-12-02 21:11 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Framework/Wysiwyg
