### ISSUE TITLE
Sort by quantity does not work with elasticsearch

### ISSUE THREAD

**Issue by tavatir** [magento/magento2#28924] opened 2020-06-29 17:27 UTC
### Preconditions (*)

1. Magento 2.4-develop
2. Magento version 2.3.3
3. ElasticSearch 6.8.10

### Steps to reproduce (*)

1. Set "Display Out of Stock Products" to yes.
2. Set "Used for Sorting in Product Listing" to yes for Quantity attribute.
3. Set elasticsearch as search engine.
4. Check if products ordered by stock availability on a category or search page.

### Expected result (*)

1. Products should be ordered by quantity.

### Actual result (*)

1. Out of and in stock products displayed in a certain mixed order.

![Peek 2020-11-10 12-18](https://user-images.githubusercontent.com/51679138/98661379-0c426b00-234f-11eb-897b-fd7254b2e6f2.gif)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by swathishs** [comment] 2020-06-30 06:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-30 06:46
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-30 06:47
Hi @swathishs, here is your [Magento instance](https://i-28924-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28924-2-4-develop.instances.magento-community.engineering/admin_d2f8](https://i-28924-2-4-develop.instances.magento-community.engineering/admin_d2f8)
Login: `986c2a5e` Password: `60d2bf07ae7d`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-09 04:58
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-09 04:58
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-09 04:59
Hi @swathishs, here is your [Magento instance](https://i-28924-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28924-2-3-5-p1.instances.magento-community.engineering/admin_a72f](https://i-28924-2-3-5-p1.instances.magento-community.engineering/admin_a72f)
Login: `91398503` Password: `b36fbc3d9300`
Instance will be terminated in up to 3 hours.

**Comment by sumil3890** [comment] 2020-08-20 20:25
Hello,

Sorting is not working in magento 2.3.5p2 with elastic serach 6 version.

**Comment by engcom-Oscar** [comment] 2020-09-25 12:32
Hi @tavatir, thank you for your report.
Did you select 'Quantity' option for sorting when check products order by stock availability on a category or search page?
![image](https://user-images.githubusercontent.com/60198413/94267478-56f55880-ff44-11ea-8ef0-cb850eba1da8.png)

**Comment by magento-engcom-team** [comment] 2020-11-10 10:21
:white_check_mark: Confirmed by @engcom-Alfa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38990` were created

**Issue Available**: @engcom-Alfa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by GuillaumeBrook** [comment] 2020-11-19 17:03
The attribute "quantity_and_stock_status" isn't indexed in Elasticsearch even if you set it to ""Used for Sorting in Product Listing" because it's value isn't actually in "catalog_product_entity_int".

It should be useful that Magento index in ES something like "is_in_stock" or "is_saleable".
The quantity is something more complex I guess due to bundle and configurable products.

I don't know if it worked with MySQL.
Anyway, looking forward this feature for 2.4 and ES ;)

**Comment by Aravindh468** [comment] 2021-01-05 15:01
I am also in need of the same functionality as I couldn't able to sort by Stock Status/Quanity. In previous magento versions (prior to Magento 2.4)it worked fine but in Elastic search Quantity sorting is not working.

The Product attribute "quantity_and_stock_status" is indexed in Elasticsearch only for In-stock products and didn't saved for Out of stock products. So it is not possible from Magento end to sort based on Stock Status.

So it would be better if "is_salable" attribute is indexed in Elastic search. Eagerly waiting for this workaround in Magento.

**Comment by mbissonho** [comment] 2021-06-16 12:09
Is there any update on this?

**Comment by IgorPostnikov** [comment] 2021-08-04 10:12
?

**Comment by nd1996** [comment] 2022-08-08 12:01
Any Updates on this issue?

Or anyone has any quick fix

**Comment by engcom-Dash** [comment] 2022-09-06 12:41
@magento give me 2.4-develop instance

**Closed as completed** 2024-05-22 07:52 UTC
Labels: Component: CatalogInventory, Priority: P3, Progress: done, Reported on 2.3.3

**Comment by kapilpandya2203** [comment] 2024-09-18 10:58
Hi @engcom-Bravo @engcom-Hotel , 
I checked in Dev branch and the issue is still reproducible.
please check attached video for reference.
https://www.loom.com/share/165a9f41ed944d60b3e13707d6324c5e?sid=e6b3a8a9-9824-4d3e-bb54-fc66adda2ae9
