### ISSUE TITLE
Sorting in a search does not work if sorting by the catalog default sort

### ISSUE THREAD

**Issue by worldpac** [magento/magento2#7532] opened 2016-11-23 03:31 UTC
We've changed our default product listing sort from Position to Name. When a user does a product search, and you change the sort from Relevance to Name, it just reloads the page. Choosing any other sort option works fine.

We are running Magento 2.0.6, on PHP-FPM 5.5.9, MariaDB 15.1, and Nginx 1.4.6.

#### Admin
1. Change the default sort to Name: 
   Stores->Configuration->Catalog->Catalog->Store Front->Product Listing Sort by->Name
#### Front end
1. Search for products.
2. Change the sort to Name.

### Expected result
1. Products should be sorted by Name.

### Actual result
1. Page simply reloads with no change in the sort. The sorter remains set to Relevance.

### Troubleshooting
1. I've removed all static content and re-deployed it using setup:static-content:deploy.
2. Adding the sort URL parameter directly into the URL makes the page sort as expected.
   e.g. `product_list_order=name`
3. I've debugged toolbar.js and found that if the sort name you've chosen matches the default sort then it strips out the sort parameter. See lines 76-78 in `pub/static/frontend/Magento/luma/en_US/Magento_Catalog/js/product/list/toolbar.js`
```javascript
 76  if (paramValue == defaultValue) {
 77     delete paramData[paramName];
 78  }
```

**Comment by worldpac** [comment] 2016-11-23 03:33
I've examined the same file in the 2.0.10 version (current as of this comment), and the files are identical, so I'm assuming an upgrade isn't going to fix my problem.

**Comment by worldpac** [comment] 2016-11-23 04:08
This gets the job done*. It allows the sort parameter to be deleted if you are not on a search page (i.e. if you're on a category page). I'd love to hear better suggestions.

in `app/code/Magento/Catalog/view/frontend/web/js/product/list/toolbar.js`
```javascript
76  if(!document.body.classList.contains('catalogsearch-result-index')) {
77      if (paramValue == defaultValue) {
78          delete paramData[paramName];
79      }
80  }
```

\* classList does not work on IE9 or earlier. That's ok for us, but may not be for others.

**Comment by olysenko** [comment] 2016-11-24 09:29
Hi, thank you for your report. Your issue is a duplicate of #5730 (see comments additionally to original description). Closed as duplicate

**Closed as completed by olysenko** 2016-11-24 09:29 UTC
Labels: bug report, Component: Search
