### ISSUE TITLE
URL issue on Magento 2.2.8 Multi-store 

### ISSUE THREAD

**Issue by ebofi** [magento/magento2#23433] opened 2019-06-27 04:53 UTC
### Summary of the issue
The site was migrated from Magento 1.9.8 to Magento 2.2.5 and later updated to 2.2.8
We have a issue when creating multi-store website on magento 2

We have 3 multi stores one for English language, Spanish and Italy. And among this English is our main site with domain example.com

I had created a new website using magento store and changed the URL of newly created store to abc.com. all created successful using siteground.com/tutorials/magento/multistore/ ( add-on Method)

But when I go to  example.com some of the products URL's are changed to abc.com domain.

We are using Magento 2.2.8

We had done running Magento Re-index, Flush to resolve, but its not fixing it.
And we had removed the newely created website from store configuration and now the example.com Domain works fine without any urls to abc.com

### Information on your environment
PHP 7.1.30
Magento 2.2.8
centos-release-7-6.1810.2.el7.centos.x86_64
Server version: 5.7.26 MySQL Community Server (GPL)

### Steps to reproduce

1. We had migrated 1.9.8 to 2.2.5 using magento migration Tool 
2. Then Updated to 2.2.8 using composer
3. Created a new website using magento store configuration
( siteground.com/tutorials/magento/multistore/ ( add-on Method) )
4. My main site url is example.com and after we created a new website using store configuration, now some of the products urls of my main site is changed to newly created site ( abc.com) 

###   Expected and actual results

1. Create new site using magento store configuration
2. Changed the URLS of newly created website to New URLS 
3. Followed the siteground tutorial ( addon method)
4. Both sites to work individually without urls being shown each other.

**Comment by ebofi** [comment] 2019-06-28 06:58
any help on this

**Comment by engcom-Charlie** [comment] 2019-08-27 13:02
Hello @ebofi 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to branch 2.2-develop was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.
See Accepted pull requests and ported code for more details

If you still faced this issue on 2.3 please create a new Issue with all required details according to Issue reporting guidelines

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-08-27 13:02 UTC
Labels: Issue: Format is not valid
