### ISSUE TITLE
Blank install of Magento 2.4.1 via composer breaks on setup:install command.

### ISSUE THREAD

**Issue by msyhr** [magento/magento2#30575] opened 2020-10-20 22:11 UTC
### Preconditions (*)

1. PHP - 7.4.9
2. Apache 2.4

### Steps to reproduce (*)

1. Run Composer Command
`composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento2`
2. Attempt to run command-line installation.
`php bin/magento setup:install --base-url=http://241.loc/ --db-host=mysql --db-name=241 --db-user=root --db-password= --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=elastic --elasticsearch-port=9200
`

### Expected result (*)

1. Magento Installs

### Actual result (*)

1. Fatal Error
`Fatal error: Declaration of Psr\Log\LoggerInterface\Proxy::emergency($message, array $context) must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = NULL) in /shared/httpd/24/htdocs/magento2/generated/code/Psr/Log/LoggerInterface/Proxy.php on line 93
`
The proxy generated has functions like below:

`public function alert($message, array $context)`

However, if you change them directly to:

`public function alert($message, array $context = array()) `

---
The command will then run successfully, however it will break all bin/magento setup:xxx commands the next time the code is regenerated.

**Comment by msyhr** [comment] 2020-10-20 22:27
As a side note, repeating this above process in the identical environment, but specifying:

`composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.0 magento2
`
successfully install the software. Then updating the composer.json entry to 

`"magento/product-community-edition": "2.4.1"`

will cause the same issue.

**Comment by qsolutions-pl** [comment] 2020-10-22 11:25
experiencing the same issue

**Comment by sdzhepa** [comment] 2020-10-22 16:41
Hello @msyhr qsolutions-pl 
@ihor-sviziev @lbajsarowicz 

Thank you for collaboration!

After multiple attempts on different envs and sked different people to check it on their envs

We are not able to reproduce this issue by the provided steps.



At this point, I suppose some important steps/configuration/etc. information is missed in the description.
As possible advice, I would propose to clean composer caches
```
composer clearcache
```


---

Tested on next envs configurations:
- Apache(2.4.18) | Nginix(1.15.12) |Nginix(1.17.10)
- PHP 7.4.7 | PHP 7.4.5
- elastic: 7.7
- SQL mariadb 10.4 | mariadb 10.3.14 | mysql 14.14(Distr 5.7.31)
- composer 1.10.6 | 1.9.1
- w/o | redis 5.0


Tested using the next steps

1. Get  Magento using composer
- `composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento2`
- `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.1 magento2_2`

2. Install magento using CLI script from the description
- also checked with "--backend-frontname"(missed in description) and with several other additional parameters


Result: Magento sucessfuly installed. No Fatal errors. Sorefront is available

**Comment by Knase** [comment] 2020-10-26 12:52
Hi, I have the same bug with PHP 7.4.11. But if I use  PHP 7.3 ,  The class Proxy created correctly.
` bin/magento   setup:di:compile `
`PHP Fatal error:  Declaration of Psr\Log\LoggerInterface\Proxy::emergency($message, array $context) must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = NULL) in m2/generated/code/Psr/Log/LoggerInterface/Proxy.php on line 93
`
`/usr/bin/php7.3 bin/magento   setup:di:compile ` - This works without the bugs.

**Comment by ihor-sviziev** [comment] 2020-10-26 12:58
Hi @Knase,
Question 1: there might be incorrect php version used. what is php -v shows for you with php 7.4?
Question 2: are you using some extensions that adds plug-in to the logger? If so - could you provide some sample module in order to be able to reproduce the issue?

**Comment by Knase** [comment] 2020-10-26 13:10
I am using php 7.4.11
` php -v 
PHP 7.4.11 (cli) (built: Oct 18 2020 19:39:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
`
I installed magento 2.4.1
` composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.1 m2`
`bin/magento setup:install \
--base-url=http://magento.ll \
--backend-frontname=admin \
--db-host=localhost \
--db-name=magento \
--db-user=magento \
--db-password=magento \
--admin-firstname=admin \
--admin-lastname=admin \
--admin-email=admin@admin.com \
--admin-user=magento \
--admin-password=magento \
--language=en_US \
--currency=USD \
--timezone=America/Chicago \
--search-engine=elasticsearch7 \
--elasticsearch-host=localhost \
--elasticsearch-port=9200 \
--use-rewrites=1;`
I got the fatal error during `bin/magento setup:install`. I fixed the file `generated/code/Psr/Log/LoggerInterface/Proxy.php`.  But if I run the command ` bin/magento   setup:di:compile` or remove the file `generated/code/Psr/Log/LoggerInterface/Proxy.php`, Magento 2 will create this file with errors.

**Comment by ihor-sviziev** [comment] 2020-10-26 13:12
@Knase could you provide your composer.lock file?

**Comment by Knase** [comment] 2020-10-26 13:17
@ihor-sviziev 
There is my the  composer.lock file
[composer.lock.txt](https://github.com/magento/magento2/files/5438960/composer.lock.txt)

**Comment by zenfork** [comment] 2020-10-28 17:00
I have same issue on after upgrading Magento Cloud 2.3.6 to 2.4.1 version with PHP 7.3.23.
This error happens on `setup:upgrade` and any other commands of `bin/magento`

**Comment by msyhr** [comment] 2020-10-28 17:49
Re-opening since other people seem to be running into this issue now. 

Some Information from me about my setup: 

I'm using https://github.com/cytopia/devilbox for local development

OS 20.04.1 LTS (Focal Fossa)
Docker version 19.03.13, build 4484c46d9d


[PHP](https://github.com/devilbox/docker-php-fpm-7.4/blob/master/Dockerfile)
[APACHE](https://github.com/devilbox/docker-apache-2.4/blob/master/Dockerfile)
[MYSQL](https://github.com/devilbox/docker-mysql/blob/master/Dockerfiles/mysql-8.0)

`devilbox@php-7.4.9 in /shared/httpd/magento2/htdocs $ php -v
PHP 7.4.9 (cli) (built: Aug  6 2020 19:20:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

Virtual Host Below:

[magento2.txt](https://github.com/magento/magento2/files/5453902/magento2.txt)
`
Composer Lock Below:
[composer.lock.txt](https://github.com/magento/magento2/files/5453908/composer.lock.txt)

Still fails every time for me. Using a version in the composer command (2.4.0) works flawlessly. Upgrade will create the issue, create-project with no version will create the issue.

**Comment by ihor-sviziev** [comment] 2020-10-28 20:41
@sdzhepa could you try to reproduce this issue again? Seems like more people getting this issue

**Comment by qsolutions-pl** [comment] 2020-10-29 10:33
Same issue with the upgrade from 2.3.x to 2.4.0 / 2.4.1

**Comment by sdzhepa** [comment] 2020-10-29 17:43
@ihor-sviziev @qsolutions-pl @Knase @msyhr

Thank you for the details 

I asked my team to review and investigate it one more time.
Previously we investigated it quite deeply and 4 persons tested it no different envs....
Seems some important precondition or condition or step is missed

**Comment by zenfork** [comment] 2020-10-29 18:14
I guess, for me it was a file permissions problem. These steps help me, when I upgrading from 2.4.0 to 2.4.1:
1. Go to Magento 2 folder
2. `sudo chown -R :apache .` (for Devilbox I used my user as owner - `sudo chown -R 1000:1000 .`)
3. `rm -rf generated/code/*`

**Comment by ihor-sviziev** [comment] 2020-10-30 11:57
Hi @msyhr @qsolutions-pl,
Could you try to remove the generated/* folder? Does the issue reproducing after that?

**Comment by belvgdarik** [comment] 2020-10-30 13:17
@msyhr Have you found any solution?

**Comment by engcom-Delta** [comment] 2020-10-30 13:30
@msyhr @qsolutions-pl Unfortunately I am not able to reproduce issue with clean magento installation on my enviroment
Could you please clarify again:
Is this clean magento installation on clean database?
Or it is magento upgrade?

**Comment by engcom-Bravo** [comment] 2020-10-30 14:12
I was not able to reproduce the issue on my machine. 
Server version: Apache/2.4.29 (Ubuntu)

**Comment by msyhr** [comment] 2020-10-30 15:55
> @msyhr @qsolutions-pl Unfortunately I am not able to reproduce issue with clean magento installation on my enviroment
> Could you please clarify again:
> Is this clean magento installation on clean database?
> Or it is magento upgrade?

Clean install clean DB (environment information in my last post)

Installing 2.4.0 works successfully (specifying the version in the composer create-project)

Installing with no version or upgrading via changing version in composer.json after a working 2.4.0 install causes the issue. I'm going to try to replicate this on one of our Dev servers instead of via local dev (docker) and report back.

**Comment by msyhr** [comment] 2020-10-30 16:08
> Hi @msyhr @qsolutions-pl,
> Could you try to remove the generated/ folder? Does the issue reproducing after that?

Same result, command fails as soon as the broken proxy is created. The only way I've gotten past this step is by manually changing the functions. However, this fails again as soon as generated/ is cleared again.

**Comment by msyhr** [comment] 2020-10-30 16:20
@ihor-sviziev  

No sure if this would be of any help. Zip of my generated folder. This is what is created when I run the setup:install CLI after composer create-project has finished. 

[generated.zip](https://github.com/magento/magento2/files/5466271/generated.zip)

**Comment by engcom-Delta** [comment] 2020-10-30 21:01
@msyhr I tried fresh magento installation without version on the composer create-project step  - installation successfully
Env:
- PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:13)
- Apache/2.4.18 (Ubuntu)

**Testing scenario 1:**
1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
2. Install magento
`php bin/magento setup:install --base-url=http://magento2dev.loc/ --db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=123123q --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200`
**Result:**
:heavy_check_mark: Magento installed without errors

**Testing scenario 2:**
 1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.0 .`
2. Install magento
`php bin/magento setup:install --base-url=http://magento2dev.loc/ --db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=123123q --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200`
3. Upgrade to 2.4.1 according https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html#manage-packages
`cp composer.json composer.json.bak`
`composer remove magento/product-community-edition --no-update`
`composer require magento/product-community-edition=2.4.1 --no-update`
`composer update`
`rm -rf var/cache/*`
`rm -rf var/page_cache/*`
`rm -rf generated/code/*`
`bin/magento setup:upgrade`
**Result:**
:heavy_check_mark: Magento upgraded to version 2.4.1 without errors

**Comment by msyhr** [comment] 2020-10-30 22:40
@engcom-Bravo @engcom-Dash could either of you provide your phpinfo(); for you setups. I'd like to compare with my docker instance as this now has to be an ENV issue on my end (devilbox)

**Comment by textarea** [comment] 2020-10-30 23:28
same issue upgrading from 2.3.5 to 2.4.1, downgraded to 2.4.0 solved
PHP 7.3.23

**Comment by engcom-Delta** [comment] 2020-11-02 12:30
@msyhr sure.
![image](https://user-images.githubusercontent.com/51681379/97868152-e0ecca00-1d17-11eb-8140-b56ac891bafc.png)

**Comment by textarea** [comment] 2020-11-03 23:06
> @msyhr I tried fresh magento installation without version on the composer create-project step - installation successfully
> Env:
> 
> * PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:13)
> * Apache/2.4.18 (Ubuntu)
> 
> **Testing scenario 1:**
> 
> 1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .`
> 2. Install magento
>    `php bin/magento setup:install --base-url=http://magento2dev.loc/ --db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=123123q --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200`
>    **Result:**
>    ✔️ Magento installed without errors
> 
> **Testing scenario 2:**
> 
> 1. `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.0 .`
> 2. Install magento
>    `php bin/magento setup:install --base-url=http://magento2dev.loc/ --db-host=localhost --db-name=magento2dev --db-user=root --db-password="123123q" --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=123123q --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-port=9200`
> 3. Upgrade to 2.4.1 according https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html#manage-packages
>    `cp composer.json composer.json.bak`
>    `composer remove magento/product-community-edition --no-update`
>    `composer require magento/product-community-edition=2.4.1 --no-update`
>    `composer update`
>    `rm -rf var/cache/*`
>    `rm -rf var/page_cache/*`
>    `rm -rf generated/code/*`
>    `bin/magento setup:upgrade`
>    **Result:**
>    ✔️ Magento upgraded to version 2.4.1 without errors

Clean install 2.4.1, php 7.3.23

![ezgif-4-ecb74d9b7e97](https://user-images.githubusercontent.com/1927403/98050185-6fa13a00-1e31-11eb-9f8c-4a3c98dcc1b7.gif)

**Comment by ihor-sviziev** [comment] 2020-11-04 04:29
Question - are you using composer 1.x or composer 2? Version 2 is not currently supported

**Comment by krisdass** [comment] 2020-11-04 05:35
Hi Team,

I am facing this issue with vanilla installation 
PHP Fatal error:  Declaration of Psr\Log\LoggerInterface\Proxy::emergency($message, array $context) must be compatible with Psr\Log\LoggerInterface::emergency($message, array $context = NULL) in /var/www/html/m241/generated/code/Psr/Log/LoggerInterface/Proxy.php on line 93

My environment:
OS : Linux Mint 18.2 Sonya
PHP: 7.4.11
Composer: 1.10.13
Magento: 2.4.1

With PHP 7.3, it is not working for me either !

**Comment by textarea** [comment] 2020-11-04 06:39
Hi @ihor-sviziev, I'm using Composer version 1.10.16

**Comment by ihor-sviziev** [comment] 2020-11-04 08:14
Interesting... I just tried to do the same on php 7.4 and php 7.3 - issue isn't reproducing for me.

Could someone who have this issue post those two files:
```
generated/code/Psr/Log/LoggerInterface/Proxy.php
vendor/psr/log/Psr/Log/LoggerInterface.php
```

**Comment by textarea** [comment] 2020-11-04 08:18
Hi @ihor-sviziev
here are mines
[Archive.zip](https://github.com/magento/magento2/files/5486401/Archive.zip)

**Comment by ihor-sviziev** [comment] 2020-11-04 08:22
Interesting... files vendor/psr/log/Psr/Log/LoggerInterface.php are equal, but in your `generated/code/Psr/Log/LoggerInterface/Proxy.php` we have
```php
    /**
     * {@inheritdoc}
     */
    public function emergency($message, array $context)
    {
        return $this->_getSubject()->emergency($message, $context);
    }
```
while in my I have
```php
    /**
     * {@inheritdoc}
     */
    public function emergency($message, array $context = [])
    {
        return $this->_getSubject()->emergency($message, $context);
    }
```
Default value is not defined.

**Comment by krisdass** [comment] 2020-11-04 09:08
> Hi @ihor-sviziev, I'm using Composer version 1.10.16

Even i have issue with this composer version as well

**Comment by krisdass** [comment] 2020-11-04 09:13
> Interesting... I just tried to do the same on php 7.4 and php 7.3 - issue isn't reproducing for me as well.
> 
> Could someone who have this issue post those two files?
> 
> ```
> generated/code/Psr/Log/LoggerInterface/Proxy.php
> vendor/psr/log/Psr/Log/LoggerInterface.php
> ```
> 
> Or even full project (clean installation, w/o any custom extensions)?

PFA files for your reference, i am facing this in vanilla installation as well !

[files.zip](https://github.com/magento/magento2/files/5486721/files.zip)

**Comment by ihor-sviziev** [comment] 2020-11-04 10:51
@textarea @krisdass still don't have any valid idea.

I just looked that code actually generated from
https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L86 ->
https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L122 ->
https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L169 ->
https://github.com/magento/magento2/blob/5a836abef542dffa23bd131f74d9f9afc9860c17/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php#L380-L395 ->
https://github.com/magento/magento2/blob/5a836abef542dffa23bd131f74d9f9afc9860c17/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php#L356-L371


And basically in this method it goes ValueGenerator is actually Laminas\Code\Generator\ValueGenerator.

I just looked - seems like all these places weren't changed since magento 2.3 (except switching from Zend to Laminas, but no real changes were there), also the latest Laminas code package version was released on December 2019 https://github.com/laminas/laminas-code/releases/tag/3.4.1

Now I have following ideas:
1. you have somehow different version of some package than me
2. you have some different php settings than me.

In order to process further investigation, could someone from you provide following things?
1. full zip of the code for clean magento installation that fails for you
2. php version in the CLI - run following comand: `php -v`
3. php configuration in the CLI - run following comand: `php -i`

**Comment by textarea** [comment] 2020-11-04 11:04
@ihor-sviziev 
magento full code in https://we.tl/t-I5WRn8yUvM, php -i info in attached phpinfo.txt and php version in attached phpversion.txt
[phpinfo.txt](https://github.com/magento/magento2/files/5487325/phpinfo.txt)
[phpversion.txt](https://github.com/magento/magento2/files/5487326/phpversion.txt)

**Comment by ihor-sviziev** [comment] 2020-11-04 11:27
@textarea I see you have installed psr pecl extension. I believe it might causing such issues. Could you try to remove/disable it, remove all files from `generated/code/` folder and try again?

**Comment by denchev** [comment] 2020-11-04 11:39
I have the same issue. I upgraded Magento via composer.json from 2.3.5-p2 to 2.4.1.
PHP version is: 7.3.20

If I manually modify the file (generated/code/Psr/Log/LoggerInterface/Proxy.php to has a default value of $context to NULL, then Magento starts working again. 

Oddly I the exact same files are working fine when I use them on an instance with PHP 7.3.22 (with Docker container) but have the issue with using 7.3.20 without Docker.

**Comment by denchev** [comment] 2020-11-04 11:46
@ihor-sviziev I followed your advice and removed the PSR extension. It worked! I checked with my docker container and it doesn't have it installed. So it makes sense why it was working there but not on the environment without docker. I had the extension installed because I also have Phalcon based site on that machine too.
Thanks! ... now I have to remove Phalcon :D

**Comment by textarea** [comment] 2020-11-04 11:58
@ihor-sviziev yes it works after psr pecl remove.
Also for me now phalcon has to be removed ;)
Thanks!

**Comment by ihor-sviziev** [comment] 2020-11-04 12:31
**For everyone who will have the same issue:**
please check if you have installed `psr` php extension (you could check it with `php -m`). In case if it's installed - please uninstall or disable it.

**Comment by pusachev** [comment] 2020-11-04 13:29
Any Idea why we need remove extension instead fix code generated ?

**Comment by ihor-sviziev** [comment] 2020-11-04 13:33
@pusachev I strongly believe this is the issue in the psr pecl extension. I'm going to report it soon to their issue tracker

**Comment by krisdass** [comment] 2020-11-04 13:48
> @textarea @krisdass still don't have any valid idea.
> 
> I just looked that code actually generated from
> https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L86
> 
> ->
> https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L122
> 
> ->
> https://github.com/magento/magento2/blob/170425c4ddf139ceda21288452ef06e0e464afa1/lib/internal/Magento/Framework/ObjectManager/Code/Generator/Proxy.php#L169
> 
> ->
> https://github.com/magento/magento2/blob/5a836abef542dffa23bd131f74d9f9afc9860c17/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php#L380-L395
> 
> ->
> https://github.com/magento/magento2/blob/5a836abef542dffa23bd131f74d9f9afc9860c17/lib/internal/Magento/Framework/Code/Generator/EntityAbstract.php#L356-L371
> 
> And basically in this method it goes ValueGenerator is actually Laminas\Code\Generator\ValueGenerator.
> 
> I just looked - seems like all these places weren't changed since magento 2.3 (except switching from Zend to Laminas, but no real changes were there), also the latest Laminas code package version was released on December 2019 https://github.com/laminas/laminas-code/releases/tag/3.4.1
> 
> Now I have following ideas:
> 
> 1. you have somehow different version of some package than me
> 2. you have some different php settings than me.
> 
> In order to process further investigation, could someone from you provide following things?
> 
> 1. full zip of the code for clean magento installation that fails for you
> 2. php version in the CLI - run following comand: `php -v`
> 3. php configuration in the CLI - run following comand: `php -i`

Hi @ihor-sviziev 

PHP Version

PHP 7.4.11 (cli) (built: Oct 10 2020 19:44:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans

PHP Info attached 
[php_details.txt](https://github.com/magento/magento2/files/5488143/php_details.txt)

**Comment by ihor-sviziev** [comment] 2020-11-04 14:00
Hi @krisdass,
Please review my comment https://github.com/magento/magento2/issues/30575#issuecomment-721704953, seems like you just need to remove psr php extension.

**Comment by krisdass** [comment] 2020-11-04 14:25
Hi @ihor-sviziev,
Actually i need to run code scanning with magento2 PSR standards. I use codesniffer and code beautifier cbf to do this. 
For this PSR module is required i think.

Let me try and update you.

**Comment by ihor-sviziev** [comment] 2020-11-04 15:24
@krisdass I think it shouldn't be required, but definitely let us know if it is

**Comment by hostep** [comment] 2020-11-04 15:51
@ihor-sviziev : since this was reported by many people, I think we need to do something properly about this.

Could we maybe add the following to the `composer.json` file?

```json
    "conflict": {
        "ext-psr": "*"
    },
```

**Comment by ihor-sviziev** [comment] 2020-11-04 15:53
@hostep good point, but I hope it will be fixed on the php extension side soon, so it will not be correct. Let's wait at least for some response.

**Comment by denchev** [comment] 2020-11-04 16:07
@ihor-sviziev Even if it is fixed on the extension level, there will be instances that could not/will not upgrade that easily. Could we at least update documentation (https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements-tech.html) and add another note that "specific version XX.XX of extension PSR can caused issue"?

**Comment by krisdass** [comment] 2020-11-05 04:31
Hi @ihor-sviziev,
I was able to set the project and run commands after disabling php psr module.
I will check & update about codesiffer & code beautifier tool output !

Thanks @ihor-sviziev

**Comment by magento-engcom-team** [comment] 2020-11-05 07:27
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38918` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2020-11-05 07:28
I created PR for updating docs in order to highlight that `psr` php extension might cause such issues.
https://github.com/magento/devdocs/pull/8185

**Comment by ihor-sviziev** [comment] 2020-11-05 15:31
Ok... we got responce from the author of `psr` extension, seems like PHP 7 API isn't supporting default values, so it can't be fixed for php 7.3 and php 7.4, but could be fixed for php 8.0, and it will be done in https://github.com/jbboehr/php-psr/pull/79.

So currently we have two options:
1. ✔ Add docs for not using `psr` php extension with Magento 2 to the docs - I already did in https://github.com/magento/devdocs/pull/8185, hope someone will review it soon
2. ❔ [not sure] Add conflict with ext-psr to the composer.json file
3. ❔ [not sure] Add compatibility with `psr` extension in the magento2

For now I think adding just a warning to the docs should be enough, I still thinking about implementation of 2nd or maybe 3rd option.

**Comment by msyhr** [comment] 2020-11-05 22:33
@zenfork and any others using Devilbox running into this issue, I can confirm disabling the psr extension solves the issue.

You'll need to edit the entry to add "psr" in the .env of your devilbox root.

`PHP_MODULES_DISABLE=oci8,PDO_OCI,pdo_sqlsrv,sqlsrv,rdkafka,swoole,psr,phalcon `

**Comment by pusachev** [comment] 2020-11-06 09:48
Hey. I have a question. Why we need create proxy for LoggerInterface object? What this profit we have from this "optimization"?

**Comment by ihor-sviziev** [comment] 2020-11-06 09:51
@pusachev TBH I don't really know. Feel free to investigate it 😃

**Closed as completed** 2020-11-10 13:05 UTC
Labels: Component: Framework/ObjectManager, Component: Framework/Code, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S1, Progress: done, Reported on 2.4.1

**Comment by qsolutions-pl** [comment] 2020-11-26 09:45
This issue is also related to an `upgrade`:
2.3.4 -> 2.4.0
2.3.5 -> 2.4.0
2.3.6 -> 2.4.0
and the same with upgrade to 2.4.1

**Comment by ihor-sviziev** [comment] 2020-11-26 09:54
@qsolutions-pl FYI we added info that `psr` extension causing issue to the docs:
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

**Comment by jissereitsma** [comment] 2020-12-05 09:48
@pusachev @ihor-sviziev I bumped into this same issue and was able to solve it by removing the PSR extension (Ubuntu with PHP 7.3: `apt-get remove php7.3-psr`). However, the question of @pusachev intrigued me: Why is the proxy needed in the first place? I tried it and this gave the error `Circular dependency: Magento\Framework\Logger\Monolog depends on Magento\Framework\Interception\PluginListGenerator`. In other words, the reason why a DI proxy is needed is to fix the circular dependency at constructor time, while at the moment a method of `PluginListGenerator` is called where logging is needed, this issue is fixed already. So, there is no (easy) way to remove the proxy itself.

**Comment by ihor-sviziev** [comment] 2020-12-08 22:03
@jissereitsma I believe the only one valid fix will be introducing some not dynamically created logger proxy with the same logic inside

**Comment by magento-engcom-team** [comment] 2021-02-15 07:10
Hi @msyhr, @ihor-sviziev, @engcom-Delta. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-38918` was closed as `Complete`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by ihor-sviziev** [comment] 2021-02-15 09:45
@sidolov @sivaschenko @gabrieldagama i don’t see any commits related to internal ticket if using search https://github.com/magento/magento2/search?q=MC-38918&type=commits . Could you please provide us some info how we can find the fix ?

**Comment by gabrieldagama** [comment] 2021-02-15 14:36
Hi @ihor-sviziev, this issue was manually closed on our Jira Project because the GitHub one was already closed for some time. Apparently, our bot has added the message about the fix, but, there is no fix.

If this still an issue, please feel free to reopen it!

Thanks!

**Comment by hostep** [comment] 2021-02-15 16:31
@gabrieldagama, @sdzhepa: this is really bad behavior of the bot, I've seen this happening a few times before in other tickets. Placing automated comments like these put people at ease, they believe that an issue will actually be fixed if a bot leaves this comment even if we can't find a reference to it in the commits (because we've grown accustomed by now that publishing code to github can sometimes take a few days or weeks even if a ticket is already closed before that happens).

Can you investigate this bot and fix it so it doesn't leave incorrect comments like these anymore in the future?

**Comment by saharin88** [comment] 2021-02-17 00:28
There was nothing I could do (module:enable etc.) due to this error.
I add to \Magento\Framework\Code\Generator\EntityAbstract::extractParameterDefaultValue before return $value this code
` if($this->getSourceClassName() === '\Psr\Log\LoggerInterface' && $parameter->name === 'context') {$value = new ValueGenerator(array(), ValueGenerator::TYPE_ARRAY);}`

**Comment by ahmedch1** [comment] 2021-03-15 18:57
I got same error , anyone knows how to solve it?
Thanks in advance

**Comment by ihor-sviziev** [comment] 2021-03-15 19:08
@ahmedch1 make sure you don't have installed psr php extension. If you have such - please remove it

**Comment by murtuza1234** [comment] 2021-04-20 12:24
@jissereitsma great mate your solution works like charm, a dozen thank you
