### ISSUE TITLE
Upgrading from Magento 2.2.6 to 2.3.4 composer update problems

### ISSUE THREAD

**Issue by techguysourav** [magento/magento2#27013] opened 2020-02-25 18:25 UTC
### Preconditions (*)

1.Magento 2.2.6
2. PHP 7.2

### Steps to reproduce (*)

1.composer require magento/product-community-edition=2.3.4 --no-update
2. composer require --dev allure-framework/allure-phpunit:~1.2.0 friendsofphp/php-cs-fixer:~2.13.0 lusitanian/oauth:~0.8.10 magento/magento-coding-standard:~1.0.0 magento/magento2-functional-testing-framework:~2.3.14 pdepend/pdepend:2.5.2 phpunit/phpunit:~6.5.0 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.3.1 --sort-packages --no-update
3. composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update
4. composer update

### Expected result (*)

1. No errors during update

### Actual result (*)

1. 
![Screenshot from 2020-02-25 23-54-41](https://user-images.githubusercontent.com/20403436/75275233-389e7180-582a-11ea-9729-05c3210273c1.png)

**Comment by tapaswee** [comment] 2020-02-26 10:12
Hi @sourav88,
Please follow the below steps for Upgrading from Magento 2.2.6 to 2.3.4.

1.change in composer.json file 
 "version": "2.2.6", to  "version": "2.3.4" 
and "magento/product-community-edition": "2.2.6" to "magento/product-community-edition": "2.3.4".

2.Run below commands
-composer require magento/product-community-edition=2.3.4 --no-update
-composer require --dev phpunit/phpunit:~6.2.0 friendsofphp/php-cs-fixer:~2.10.1 lusitanian/oauth:~0.8.10 pdepend/pdepend:2.5.2 sebastian/phpcpd:~3.0.0 squizlabs/php_codesniffer:3.2.2 --no-update
-composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update

3.Now open the  composer.json  file and add  Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/  into the “psr-4” section.
The psr-4 section in your composer file should now look like below:
"autoload": {
    "psr-4": {
        "Magento\\Framework\\": "lib/internal/Magento/Framework/",
        "Magento\\Setup\\": "setup/src/Magento/Setup/",
        "Magento\\": "app/code/Magento/",
        "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
    },
   
}
4.composer update
5.php bin/magento setup:upgrade
6.php bin/magento setup:static-content:deploy -f

**Comment by sourav88** [comment] 2020-02-29 16:47
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-29 16:47
Hi @sourav88. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-29 16:47
Hi @sourav88, here is your [Magento instance](https://i-27013-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27013-2-4-develop.instances.magento-community.engineering/admin_a1a0](https://i-27013-2-4-develop.instances.magento-community.engineering/admin_a1a0)
Login: `d13d8992` Password: `e1a2331e16d1`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment] 2020-02-29 17:39
@sourav88: this is an issue caused by that `magestore/magento2-language-vi-vn` module (like you can see at the bottom of your screenshot).
It does not support PHP versions higher then 7.0: https://github.com/Magestore/magento2-language-vi-vn/blob/a952046c37e2e876962be0be87e8e0795a432dbe/composer.json#L10

You'd probably best remove this module and then try the upgrade again.
You can maybe try https://github.com/magento-l10n/language-vi_VN as an alternative?

Closing, as this does not seem like a bug in Magento2.

**Closed as completed by hostep** 2020-02-29 17:39 UTC
Labels: Issue: Format is valid, Reported on 2.3.1

**Comment by sourav88** [comment] 2020-02-29 18:31
I solved this issue by switching php from v7.2 to v7.1.  

Make sure if we are uprading the magento version from 2.x to 2.3.4, php7.1 should be work.
