### ISSUE TITLE
mergeCarts mutation for the same bundle product throws exception

### ISSUE THREAD

**Issue by zia1177** [magento/magento2#37704] opened 2023-07-03 19:57 UTC
### Preconditions and environment

- Adobe Commerce ver. 2.4.6-p1
- This issue only occurs through mergeCarts mutation. So, try the steps to reproduce using PWA frontend or postman.
- Error triggers from the following file on line 109
vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php

### Steps to reproduce

1. Login to a customer account and add a bundle product to the cart.
2. Logout and add the same bundle product to the guest cart.
3. Now log back in to the previous customer account.

### Expected result

Guest cart should merge with customer cart.

### Actual result

Throws the following input InputException
"Can't check requested quantity for products without Source Items support."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-04 06:20
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-04 07:56
Hi @zia1177,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- Login to a customer account and add a bundle product to the cart.
- Logout and add the same bundle product to the guest cart.
- Now log back in to the previous customer account.



https://github.com/magento/magento2/assets/51680745/833e4212-c21f-454a-b134-4f3586cd16dd



Guest cart is merging with customer cart with logged customer.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by zia1177** [comment] 2023-07-04 13:05
@engcom-Bravo  This issue is coming through mergeCarts mutation. Try this using postman or some other clients

**Comment by engcom-Bravo** [comment] 2023-07-10 10:10
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-10 10:30
Hi @zia1177,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance with EE edition and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Login to a customer account and add a bundle product to the cart.
- Logout and add the same bundle product to the guest cart.
- Now log back in to the previous customer account.



<img width="1266" alt="Screenshot 2023-07-10 at 3 57 52 PM" src="https://github.com/magento/magento2/assets/51680745/c45c1b02-c2fd-4ea6-b7df-d4dbfe3fffd6">

Guest cart is merged with Customer cart.

Kindly recheck the behaviour on Magento 2.4-develop instance with EE edition.and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-21 06:23
Hi @zia1177,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37704#issuecomment-1628670080 still you are working on the issue and let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-28 06:09
Hi @zia1177,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-28 06:09 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1

**Comment by gnumus** [comment] 2024-01-30 18:26
Just faced the issue on my project. @zia1177 have you had a chance to find workaround?
