### ISSUE TITLE
Cart Price Rules based on Shipping Method can't be applied in basket

### ISSUE THREAD

**Issue by magedev** [magento/magento2#8089] opened 2017-01-10 11:23 UTC
### Preconditions
1. Magento EE v2.1.2 with sample data
2. Cart Price Rule configured as follows:
    * Rule Name: FREEDELIVERY
    * Websites: Main Website
    * Customer Groups: Select all customer groups
    * Coupon: Specific Coupon
    * Coupon Code: FREEDELIVERY
    * [CONDITIONS]: 
        * If All of these conditions are TRUE: 
            * Shipping Method  is  [tablerate] Table Rate 
    * [ACTIONS]: 
        * Apply: Fixed amount discount for whole cart
        * Discount Amount: 15
### Steps to reproduce

1. Add any physical product to your basket
2. Go to basket (follow the "View and edit Cart" link)
3. On a right hand side in the "Summary" section expand the "Estimate Shipping and Tax" block
4. Select "Best Way / Table Rate" shipping method
5. Apply "FREEDELIVERY" coupon code

### Expected result

1. The coupon should be applied deducting 15 from the Grand Total

### Actual result
1. "The coupon code "FREEDELIVERY" is not valid" message appears at the top of the page.

Once the customer proceeds to Review & Payments step in the checkout and goes back to a basket he can successfully apply the coupon code.

**Comment by veloraven** [comment] 2017-01-10 15:48
@magedev thank you for your report.
Could you please let us know if you have reported the same issue via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant?
As I can see this issue should affect both editions, so this information is needed to avoid duplicates in our internal system.
And reporting EE issues via Support or Partner portal allow for proper tracking of issues at the account level.

**Comment by magedev** [comment] 2017-01-11 09:33
Hi @veloraven 

I haven't reported this issue via Support portal, shall I copy it there or would sorting out this issue in CE also fix the problem in EE?

**Comment by veloraven** [comment] 2017-01-20 10:24
@magedev thank you for update.
We can leave this issue here. But it is better to report such issues via Support or Partner portal for better tracking, etc.

**Comment by oleg-onufer** [comment] 2017-06-20 13:16
This issue  is a duplicate of this one https://github.com/magento/magento2/issues/8172
Internal ticket was created for this issue --MAGETWO-69940

**Closed as completed** 2017-06-21 07:03 UTC
Labels: bug report, Component: Tax, Issue: Format is valid

**Comment by lewisvoncken** [comment] 2017-10-18 14:53
I'm working on it #SQUASHTOBERFEST
