### ISSUE TITLE
Reservation duplication for virtual products

### ISSUE THREAD

**Issue by vitaliy-golomoziy** [magento/magento2#32677] opened 2021-04-06 20:22 UTC
### Preconditions (*)
Magento version: 2.3.6

1. Create a virtual product that has inventory
2. Configure Authorize.net payment method (or any method that captures an order and creates an invoice)

### Steps to reproduce (*)

1. Place an order for a qty=1 of the virtual product created above with a credit card so that invoice is created automatically

### Expected result (*)
1. One reservation placed and stock quantity decremented by 1

### Actual result (*)
1.  Three reservations placed and stock quantity decremented by 3

What happens is that  Magento\InventoryShipping\Observer\VirtualSourceDeductionProcessor is called every time when invoice is created. It has the following code which, I guess, supposed to prevent double executions:

```
    private function isValid(InvoiceInterface $invoice): bool
    {
        if ($invoice->getOrigData('entity_id')) {
            return false;
        }

        return $this->hasValidItems($invoice);
    }

```
However, it doesn't work because getOrigData is always empty. So the check never passed, and the body of the observer is executed every time the invoice object is saved, which is 3 in my case. 

It results in multiple records in the database:
```
|            472 |        1 | 1-2/01/202156 |   1.0000 | {"event_type":"invoice_created","object_type":"order","object_id":"213"}  |
|            473 |        1 | 1-2/01/202156 |   1.0000 | {"event_type":"invoice_created","object_type":"order","object_id":"213"}  |
|            474 |        1 | 1-2/01/202156 |  -1.0000 | {"event_type":"order_placed","object_type":"order","object_id":"213"}     |
|            475 |        1 | 1-2/01/202156 |   1.0000 | {"event_type":"invoice_created","object_type":"order","object_id":"213"}  |
```
and multiple stock decrements. 

---
Severity: S1

- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by engcom-Alfa** [comment] 2021-05-31 07:30
HI @vitaliy-golomoziy 
I have tried reproducing the same issue in Magento 4.2-develop version and seems to be not reproducible.
Can you please provide the more information to reproduce.
Something like: which payment gateway you have used, and what are the product settings you had done.
Possibly please do a screen record and attached over here in the comment section.
Prior to that, kindly upgrade to the latest version and give a try.

**Comment by fernando-sa** [comment] 2021-06-02 20:26
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-06-14 06:23
Since there is no update to me in last ~14 days on my last comment, I am closing this ticket.
In case of any issue in future relevant to it in the latest versions, kindly report with a new ticket having all the reproducible information.
Thanks

**Closed as completed by engcom-Alfa** 2021-06-14 06:23 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: ready for confirmation, Reported on 2.3.6
