### ISSUE TITLE
Incorrect 'longblog' database definition, should be 'longblob'

### ISSUE THREAD

**Issue by hostep** [magento/magento2#35108] opened 2022-02-15 16:00 UTC
### Steps to reproduce (*)
1. Look at this line: https://github.com/magento/magento2/blob/2d446475953e907c9844d493857d172bc9956bd8/app/etc/di.xml#L1615

### Expected result (*)
1. seeing `longblob`

### Actual result (*)
1. seeing `longblog`

### Discussion
Accidentally noticed this, no idea if this can cause problems in any way in Magento, but it looks a bit sloppy 🙂 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dudzio12** [comment] 2022-02-15 22:29
I was curious, so investigated a little bit what's going on wth that typo.

Since we use now declarative schema, the issue is not likely to popup, but there are some third party modules which still uses old `SchemaInterface` classes.

So if we try to add a column with type `longblob` (which is NOT listed in `\Magento\Framework\DB\Ddl\Table`, it's just `blob` type there) or update a column (with old `UpgradeSchema` or `SetupSchema` classes) to that type, we we'll end up with `Undefined index: longblob in .../Magento/Framework/Setup/SchemaListener.php on line 138` error.

Thanks for the report @hostep, it's now fixed by #35109.

**Comment by engcom-Hotel** [comment] 2022-02-16 01:48
Hello @hostep,

Thanks for posting this issue!

@dudzio12 Thanks for the detailed explanation.

We have investigated the issue and found that `longblog` has been written in the [file](https://github.com/magento/magento2/blob/65714d45005bd2aa0edae90b0de27ffa58a6ef71/app/etc/di.xml#L1615), which is not the valid data type. Hence confirming this issue.

Thanks

**Closed as completed** 2022-04-22 18:15 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.x, Area: Framework
