### ISSUE TITLE
PP Express Checkout Return Gives Server 500. Emails of BCC issue.

### ISSUE THREAD

**Issue by vishalpatel14** [magento/magento2#25630] opened 2019-11-18 08:01 UTC
### Preconditions (*)

1. Magento CE 2.3.3 without sample data is installed.
2. Paypal Express Checkout Return Orders Email gives Server 500 error.
3. Admin order Comment Gives server 500 error

### Steps to reproduce (*)

1. Go To PP Express Checkout and Return Back on Successful Transaction Gives Server 500 Error
2. Admin order Comment Add Ajax gives server 500 error .

### Expected result (*)

1. Customer Need to redirect to Thank you page with BCC emails fired
2. Admin order Comment Add with Ajax response and emails need to be fired.

### Actual result (*)

1. Adding Error Log Below.

<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Template::setVars() must be of the type array, null given, called in vendor/magento/framework/Mail/Template/TransportBuilder.php on line 368 and defined in vendor/magento/module-email/Model/Template.php:403
Stack trace:
#0 vendor/magento/framework/Mail/Template/TransportBuilder.php(368): Magento\Email\Model\Template-&gt;setVars(NULL)
#1 vendor/magento/framework/Mail/Template/TransportBuilder.php(380): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTemplate()
#2 vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Magento\Framework\Mail\Template\TransportBuilder-&gt;prepareMessage()
#3 vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(91): Magento\Framework\Mail\Template\TransportBuilder-&gt;getTransport()
#4 vendor/magento/mod in <b>vendor/magento/module-email/Model/Template.php</b> on line <b>403</b><br />

**Comment by vishalpatel14** [comment] 2019-11-18 08:03
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-18 08:03
Hi @vishalpatel14. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-18 08:03
Hi @vishalpatel14, here is your [Magento instance](https://i-25630-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25630-2-3-develop.instances.magento-community.engineering/admin](https://i-25630-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by vishalpatel14** [comment] 2019-11-18 08:19
do you confirm that you were able to reproduce the issue on vanilla Magento instance following steps to reproduce?

I have tried to produce same as Magento vanila instance but emails is not working their hence we cant check that feature.

**Comment by engcom-Charlie** [comment] 2019-11-20 10:30
Hello @vishalpatel14 
I can't confirm your issue because he GitHub issue tracker is intended for Magento Core technical issues only. In your case was used Admin order Comment(third party extension). 
Please refer to the Admin order Comment extension support, for advice or general discussion about this issue.

Fresh Magento 2.3-develop works fine:
![image](https://user-images.githubusercontent.com/51680850/69230873-c0704200-0b90-11ea-80e6-66f5337e2504.png)
![image](https://user-images.githubusercontent.com/51680850/69230989-ff9e9300-0b90-11ea-8b35-a7da7667b82a.png)
![image](https://user-images.githubusercontent.com/51680850/69231007-075e3780-0b91-11ea-8355-edde9a2dc6a9.png)

So i have to close this issue.
Thanks for your report!

**Comment by vishalpatel14** [comment] 2019-11-20 10:46
Hello Team,

We have not install any 3 party extensions. Also the bug is in core files itself. We are using the Download copy from  https://magento.com/tech-resources/download with version 2.3.3.

We have the fresh copy installed in 2 VPS servers and at both places we have this same issue. 

After success payment customer redirect to Thank you page and in Admin order emails we have "," separated Send Order Email Copy To and Send Order Email Copy Method as "Separate Email". 

On thank you page when this emails needs to be fired we have the issue and the logs mentions are of the core bug itself.

![git_admin_order](https://user-images.githubusercontent.com/16519746/69232201-94fd4f80-0bb0-11ea-8f93-6dd7d8cb1a78.png)


![git_admin_order_comment](https://user-images.githubusercontent.com/16519746/69232359-ed345180-0bb0-11ea-9ab6-7e407166e191.png)

Attaching both Screen shot for your reference. So you have know the admin side configurations. 

Please Note : We have pure Magento install and with no 3 Party Extensions and Errors is in core code.

**Comment by vishalpatel14** [comment] 2019-11-20 10:59
Hello Team,

We have not install any 3 party extensions. Also the bug is in core files itself. We are using the Download copy from  https://magento.com/tech-resources/download with version 2.3.3.

We have the fresh copy installed in 2 VPS servers and at both places we have this same issue. 

After success payment customer redirect to Thank you page and in Admin order emails we have "," separated Send Order Email Copy To and Send Order Email Copy Method as "Separate Email". 

On thank you page when this emails needs to be fired we have the issue and the logs mentions are of the core bug itself.

![git_admin_configuration](https://user-images.githubusercontent.com/16519746/69233448-f0304180-0bb2-11ea-85e5-382b053fbd35.png)


![git_comment_issue](https://user-images.githubusercontent.com/16519746/69233350-c119d000-0bb2-11ea-8785-74de405b41da.png)


Attaching both Screen shot for your reference. So you have know the admin side configurations. 

Please Note : We have pure Magento install and with no 3 Party Extensions and Errors is in core code.

**Comment by engcom-Charlie** [comment] 2019-11-20 11:23
@vishalpatel14 i test it again and i still can't reproduct this issue on a clean Magento 2.3.3 

**Testing scenario:**

1. Configure Send Order Email Copy to "youremail"
2. Place order via PP Express Checkout
3. Check mail

**Results:**
![image](https://user-images.githubusercontent.com/51680850/69234650-552a6e00-0b98-11ea-9bab-253e0f8f115c.png)
![image](https://user-images.githubusercontent.com/51680850/69234692-6f644c00-0b98-11ea-8cd0-4a59606b3f3c.png)
**Admin comets copy:**
![image](https://user-images.githubusercontent.com/51680850/69234811-bb16f580-0b98-11ea-9c6b-ad405aa7d8a8.png)
**Order copy:**
![image](https://user-images.githubusercontent.com/51680850/69234830-c79b4e00-0b98-11ea-9ca6-5e010d7d5aeb.png)

So this issue should be closed.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

Thank you for contribution and collaboration!

**Closed as completed by engcom-Charlie** 2019-11-20 11:23 UTC
Labels: Issue: Format is valid

**Comment by vishalpatel14** [comment] 2019-11-20 12:23
Hello @engcom-Charlie 

I have debug the code and found the bug in core code how i can share you that so you can make this in next upcoming release?

**Comment by vishalpatel14** [comment] 2019-11-20 12:28
The Bug issue with the core file log as below.
/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php

Buggy function is:  public function sendCopyTo()

**Comment by engcom-Charlie** [comment] 2019-11-20 12:30
@vishalpatel14 you can try to make a commit(or PR) to repository, but i can't confirm this bug

**Comment by vishalpatel14** [comment] 2019-11-20 13:01
Hello @engcom-Charlie 

I just checked with the same file on github repository and found that some one have solved it in that file. So the question is why the download copy dont have that new changed files? As we download the files from Magento website it have bugs files.

**Comment by engcom-Charlie** [comment] 2019-11-20 13:18
@vishalpatel14 ah, sorry. That is happened because 2.3-develop branch is updating everyday with new fixes. Version on website is stable(version which was released before and it not updating with new fixes). All fixes will be available in next release(2.3.4).

**Comment by vishalpatel14** [comment] 2019-11-20 13:23
@engcom-Charlie So this will be not updated to the Magento official website download folder. Than who ever comes and download from their will have errors. Magento should updated the changes to the Stable Download version as thousand of people might be downloading the files from Magento website.

**Comment by engcom-Charlie** [comment] 2019-11-20 13:38
@vishalpatel14 probably, but I think it’s more convenient to release a product. This question already belongs to business.

**Comment by vishalpatel14** [comment] 2019-11-20 13:48
@engcom-Charlie Okay but you can request to Magento people about this issue. May be they consider the important things. You may than close the Ticket.

**Comment by engcom-Charlie** [comment] 2019-11-20 13:51
@vishalpatel14 i will ask it for you. But re-opening of this ticket doesn't make sense.
