### ISSUE TITLE
Contact form exception inside processTemplate - typo contacts_email_email_template vs contact_email_email_template

### ISSUE THREAD

**Issue by flecxie** [magento/magento2#6153] opened 2016-08-13 13:48 UTC
FYI: was getting the following error message when trying to send a message on the contact form of our CE 2.1.0 site:

> We can't process your request right now. Sorry, that's all we know.

Debugging with xdebug I found that things go wrong inside the processTemplate function in vendor/magento/module-email/Model/Template.php when executing the following instruction:

`$this->loadDefault($templateId);   
`

Note that we didn't have a contact form template defined, Configuration -> General -> Contacts -> Email Template just has 'Contact Form (Default)'. Variable $templateId has the following default content:

`$templateId          = (string) 'contacts_email_email_template';
`

Gets passed to these functions then:

`$this->emailConfig->getTemplateFilename($templateId, $designParams);
`

`$module = $this->getTemplateModule($templateId);
`

`return $this->_getInfo($templateId, 'module');
`

When the following function is called I could see that $data has an entry called contact_email_email_template (note contact_ <-> contacts_):
`$data = $this->_dataStorage->get()
`

Didn't dig further but looks like a simple typo in Magento CE 2.1.0 somewhere. After loaded an e-mail template (under Marketing -> Email templates) for this form & enabling it under Configuration -> General -> Contacts -> Email Template everything is fine.

**Comment by wert2all** [comment] 2016-08-15 12:44
Maybe issue is a copy of #6153

**Comment by sevos1984** [comment] 2016-09-12 13:24
Have you tried updating to latest release version?

**Comment by sevos1984** [comment] 2016-09-26 12:17
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:17 UTC
Labels: bug report

**Comment by greg-io7** [comment] 2017-06-12 21:03
This issue is still occurring in v2.1.3  .... I "fixed" it by following the steps above to create a new custom template.
