### ISSUE TITLE
Comment about VAT number displayed under different field in Customer Configuration

### ISSUE THREAD

**Issue by wojtekn** [magento/magento2#804] opened 2014-12-14 19:06 UTC
Comment "To show VAT number on frontend, set Show VAT Number on Frontend option to Yes." is displayed under "Enable Automatic Assignment to Customer Group" field in System -> Configuration -> Customers -> Customer Configuration.

It should be displayed under "Show VAT Number on Frontend" field.
![screenshot 2014-12-14 15 50 36](https://cloud.githubusercontent.com/assets/727413/5428653/8b26d52e-83cc-11e4-8e2a-698f2afc2ef5.png)

**Comment by vpelipenko** [comment] 2015-01-09 13:12
Thank you for reporting this issue. It is addressed to assigned PO.

**Comment by choukalos** [comment] 2015-01-21 14:51
Tracking in internal ticket - MAGETWO-32869; will close this github issue out when internal ticket is closed.

**Comment by vpelipenko** [comment] 2015-01-26 11:36
The issue is fixed and will be delivered in the next update.

**Comment by vpelipenko** [comment] 2015-02-07 09:48
@wojtekn, suggested update is implemented and available from 0.42.0-beta7. Please, check the latest version.

**Comment by vpelipenko** [comment] 2015-02-10 16:05
Fixed. Closed.

**Closed by vpelipenko** 2015-02-10 16:05 UTC
Labels: acknowledged, bug, CS

**Comment by wojtekn** [comment] 2015-02-11 21:54
Thanks @vpelipenko, it looks good now.
