### ISSUE TITLE
Discount applied getting disappeared after login in Magento 2.2.6

### ISSUE THREAD

**Issue by ameshca** [magento/magento2#21362] opened 2019-02-20 13:24 UTC
### Preconditions (*)

* Magento 2.2.6
* PHP 7.1.9
* MySQL 5.7.19
* Ubuntu 16.04.5 LTS

### Steps to reproduce (*)

1. First login as customer
2. Empty the cart
3. Logout customer
4. Add a product to the cart
5. Apply a discount coupon
6. Login with same customer
7. Go to cart page

### Expected result (*)

1. In the cart page the previously applied coupon will be present

### Actual result (*)

1. Disappeared the applied coupon code.

Note : While checking we have found that empty values for most of the attributes in the quote table for the logged in customer.

**Comment by magento-engcom-team** [comment] 2019-02-20 13:24
Hi @ameshca. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ameshca do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-20 15:36
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-20 15:37
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-20 15:38
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-20 15:38
Hi @shikhamis11, here is your [Magento instance](https://i-21362-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21362-2-2-develop.instances.magento-community.engineering/admin](https://i-21362-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-20 16:08
@ameshca Thank you for your report.
this issue is not reproducable at current magento 2.2-develop instance message here if you are able to reproduce at current magento instance

**Closed as completed by shikhamis11** 2019-02-20 16:08 UTC
Labels: Issue: Format is valid

**Comment by ameshca** [comment] 2019-02-21 04:52
Actually this issue is only in 2.2.6 version and not coming all the time. We have reproduced this issue in default magento installation also.
Also there was a magento issue #21355 that minicart total showing 0. We think that these are related issues, because at the time when the minicart total 0 showing issue happens and if any coupon was applied then that will not be shown. We have checked the database and at this time the corresponding quote fields are empty. Can you please recheck that scenario.

**Comment by shikhamis11** [comment] 2019-02-21 04:56
Ok I will recheck
