### ISSUE TITLE
Search suggestion not collapse once enter value,remove it and click on out side 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32488] opened 2021-03-16 10:13 UTC
Search suggestion not collapse once enter value,remove it and click on out side 

### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

1. Admin -> Dashboard Page
2. Click on Search box 
3. Enter keyword like "Ver"
4. It will appear the suggestion panel 
5. Now remove the value from search box and Click on out side 
6. Observe that the suggestion panel still appear 

### Expected result (*)
Suggestion panel should be collapse

### Actual result (*)
Suggestion panel not collapse

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-03-16 10:14
@magento give me 2.4-develop instance

**Comment by krishprakash** [comment] 2021-03-16 10:21
Reproduce the issue on latest instance:

![image](https://user-images.githubusercontent.com/46617848/111293656-82ddd500-866f-11eb-80dc-717ef8531d9e.png)

**Comment by magento-engcom-team** [comment] 2021-03-16 10:22
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41344` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-05-06 12:39 UTC
Labels: Issue: Confirmed, Issue:  Cannot Reproduce, Component: Admin, Progress: done

**Comment by magento-engcom-team** [comment] 2021-05-06 12:41
Hi @renard123. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41344` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.
