### ISSUE TITLE
Receiving an error message when clicking on a product tax class

### ISSUE THREAD

**Issue by roettinger** [magento/magento2#35949] opened 2022-08-15 17:02 UTC
### Preconditions and environment

- Magento version 2.3.2
-When clicking on a product tax class, we receiving the error attached
![product_class_error_message](https://user-images.githubusercontent.com/111303256/184680670-c9dc854d-0169-4ce0-ab06-4f27dacd2378.PNG)

### Steps to reproduce

Click on any product tax class

### Expected result

Should be able to see the details of how that product tax class is configured without receiving an error message

### Actual result

![product_class_error_message](https://user-images.githubusercontent.com/111303256/184680919-b7380ae2-8686-41f1-b327-1a4100b9b642.PNG)

### Additional information

Are taxes are not calculating correctly on our websites so we are trying to triage this issue to fix it ASAP. We're unable to do so until this issue is resolved.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-16 12:11
Hi @roettinger,

Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.

We are able to Configure Tax Classes.

<img width="940" alt="Tax" src="https://user-images.githubusercontent.com/51680745/184876021-651aa71e-a7e5-4a47-b4ca-62d922208ee0.png">


Thanks.

**Comment by hostep** [comment] 2022-08-25 19:36
The stacktrace mentions taxjar, so I'm assuming this is a 3rd party module? Maybe try upgrading it or talk with their support about this?

**Comment by engcom-Bravo** [comment] 2022-08-30 05:20
Hi @roettinger,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-08-30 05:20 UTC
Labels: Issue: needs update
