### ISSUE TITLE
Catalog rule with 'is not one of' not working with multiple SKU condition

### ISSUE THREAD

**Issue by arjun-tm** [magento/magento2#39204] opened 2024-09-24 09:03 UTC
### Preconditions and environment

Magento 2.4 or above

### Steps to reproduce

1. Include SKU attribute in promo rule conditions Store > Attributes > Product > Edit SKU > Use for Promo Rule Conditions > Yes
2. Create Catalogue rule, fill required values
3. While configuring conditions, choose Product attribute SKU and condition as 'is not one of'.
4. Add multiple SKUs from the product grid to be considered for the rule.

### Expected result

1. Catalogue rule not applied to selected SKUs

### Actual result

1. Catalogue rule was not applied only to the first product from the selection but all other products were applied the rule.

### Additional information

This issue is similar to the [issue #21618 ](https://github.com/magento/magento2/issues/21618) but the thread was closed as it was working as expected with **is one of** condition.

The issue can be fixed if the SKUs selected doesn't have any spaces in between as XX,XY,YX,YY etc if there is a space in between the SKUs, then the condition fails to work as expected.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-26 06:28
Hi @arjun-tm,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

![Test-Catalog-Price-Rule-Promotions-Marketing-Magento-Admin-09-26-2024_11_29_AM](https://github.com/user-attachments/assets/2fa4dddf-e682-429b-b550-55d9328764ed)



![Test-09-26-2024_11_29_AM](https://github.com/user-attachments/assets/30db99ab-080b-4f7f-bdbf-b2779c318000)



Catalogue rule not applied to selected SKUs

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by arjun-tm** [comment] 2024-09-26 10:47
@engcom-Bravo  Sorry this is not the condition, as stated in the issue heading, you need to add multiple SKUs. The SKU can be selected from the product grid and on submission, the SKUs are listed as comma separated with spaces in between them. In this scenario only the first SKU is considered for the rule and all other SKUs after that are invalidated.

**Comment by engcom-Bravo** [comment] 2024-09-27 05:20
Hi @arjun-tm,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


![Test-Catalog-Price-Rule-Promotions-Marketing-Magento-Admin-09-27-2024_10_46_AM](https://github.com/user-attachments/assets/6d982761-1dc6-4e3e-9a8b-99cfd6596d8a)


![Test-09-27-2024_10_45_AM](https://github.com/user-attachments/assets/37d2ec03-06fb-43da-97b7-ece72a9808f0)



We have created rule for multiple skus and rule is not applied to selected SKUs.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-08 04:35
Hi @arjun-tm,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-10-08 04:35 UTC
Labels: Issue: needs update, Reported on 2.4.x
