### ISSUE TITLE
Magento 2 Related Products rule always returns the same products which meet the rule requirements

### ISSUE THREAD

**Issue by mtwegrzycki** [magento/magento2#32489] opened 2021-03-16 10:27 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
1. Add e.g. 10 products (more than "Result limit" from point 2.) to Magento store, which meet the specified Related/Cross-Sell/Up-Sell "Products to Display" conditions.
2. Set "Result limit" for rule e.g. on 2.
3. Search a product which meets the "Product to Match" conditions
4. Check the Related/Cross-Sell/Up-Sell products

### Expected result (*)
1. I get different products for each searching.

### Actual result (*)
1. I always get the same two products. There are the products with the lowest IDs, which meet rule conditions.
2. It does not matter how much products from database meet the rule conditions.
3. It is caused by SQL query to get products from database for specified rule.
4. Always the same two products are returned from database. Result from database should be randomized.

Maximum "Result limit" is 20 and it is fine for performance, but currently, if we have e.g. 50 products which meet the rule conditions, only first 20 products with the lowest IDs will be displayed to customer and it is not good from business perspective.
Results should be randomized on database query level.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mtwegrzycki** [comment] 2021-03-16 10:27
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2021-03-19 09:36
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41444` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Kiraberos** [comment] 2022-11-11 11:59
@magento I am working on this

**Comment by Kiraberos** [comment] 2022-11-11 15:05
@mtwegrzycki  I want to clarify:
What did you mean about 'Set "Result limit" for rule e.g. on 2.'?
In the admin panel we didn't set result limits for related, upsell and cross-sell.
According to the project, I can't find a use for this condition 'related-rule'.
![image](https://user-images.githubusercontent.com/70772975/201363277-2eb2fde9-0558-4685-9ec3-4cac73473acc.png)

In **Magento/Catalog/view/frontend/templates/product/list/items.phtml** I see that such conditions exist, but it looks like there should be an appropriate functionality for these conditions.
There is a **$shuffle** variable to which the value from the function is assigned **isShuffled()**.This functionality should solve this problem.
![image](https://user-images.githubusercontent.com/70772975/201363493-e50398ab-fcbf-4474-8319-bac03eb3330d.png)
But this functionality is in the commercial version. The module is responsible for it **Magento_TargetRule**.
And thanks to this functionality we can randomize the result for related, upsell and cross-sell products.

Therefore, perhaps you should reconsider this pr and the task.

**Comment by engcom-Bravo** [comment] 2024-12-12 04:41
Hi @mtwegrzycki,

Thanks for reporting and collaboration.

we have verified the issue in Latest 2.4-develop instance with EE edition and the issue is no more reproducible.Hence we are closing this issue Please feel free to reopen the issue if the issue still exists.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-12 04:41 UTC
Labels: Component: Catalog, Issue: Confirmed, Component: Rule, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Catalog
