### ISSUE TITLE
Eav Group Repository Order not changing.

### ISSUE THREAD

**Issue by LucianMihalache** [magento/magento2#23634] opened 2019-07-09 09:16 UTC
### Preconditions (*)

1. I tried on magento 2.3.1.
2. Fresh and developer instances.

### Steps to reproduce (*)

1. The problem is that you cannot update the order of a group in an attribute set by repository. It does not have support for it.

Basically, I am trying to update the groups of some attribute set via rest api.
The code asks for a specific format

>     {
>       "group": {
>         "attribute_group_id": "string",
>         "attribute_group_name": "string",
>         "attribute_set_id": 0,
>         "extension_attributes": {
>           "attribute_group_code": "string",
>           "sort_order": "string"
>         }
>       }
>     }

But it does not work. When I debugged what was being received by the site, it returned:

>    (vendor/magento/module-eav/Model/Attribute/GroupRepository.php::save())
>    
>    
>    2019-07-09T09:06:01+00:00 INFO (6): Array
>    
>     (
>         [attribute_group_name] => Product Details
>         [attribute_group_id] => 336
>         [attribute_set_id] => 39
>     )

While my posted data was:

>    2019-07-09T08:46:02+00:00 INFO (6): Array
>    
>     (
>         [group] => Array
>             (
>                 [attribute_group_name] => Product Details
>                 [extension_attributes] => Array
>                     (
>                         [sort_order] => 1
>                         [attribute_group_code] => product-details
>                     )
>     
>                 [attribute_group_id] => 336
>                 [attribute_set_id] => 39
>            )
>     
>     )

After the repository saves the group (calls resource->save()), it returns: 

>     2019-07-09T09:06:01+00:00 INFO (6): Array
>     (
>         [attribute_group_name] => Product Details
>         [attribute_group_id] => 336
>         [attribute_set_id] => 39
>         [attribute_group_code] => product-details
>         [sort_order] => 83
>     )

Which is normal, because in the group model, in beforeSave, there is 

>    (vendor/magento/module-eav/Model/ResourceModel/Entity/Attribute/Group.php::_beforeSave())
>    
>     if (!$object->getSortOrder()) {
>             $object->setSortOrder($this->_getMaxSortOrder($object) + 1);
>      }

### Expected result (*)

1. To be able to set the order of some attribute groups

### Actual result (*)

1. Saving an attribute group by its repository auto-increments its old order.

**Comment by LucianMihalache** [comment] 2019-07-09 09:23
I updated the question with more details and valid data.

**Comment by engcom-Charlie** [comment] 2019-07-09 10:12
Hello @LucianMihalache ! Thank you for report 
Can you show which Rest Api calls did you use when reproduce this issue ?

**Comment by LucianMihalache** [comment] 2019-07-09 10:16
@engcom-Charlie 
Isn't there only one rest api call for this?
/rest/all/V1/products/attribute-sets/groups.

**Comment by magento-engcom-team** [comment] 2019-07-09 18:12
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17997` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by LucianMihalache** [comment] 2019-07-10 06:56
@engcom-Charlie thank you for looking into this.
Can you please look into https://github.com/magento/magento2/issues/23172 too?
It is about attribute groups too.
The problem is that you can't filter the group repository (with attribute set id filter and attribute group filter) with any other condition_type than =
More details there.

**Comment by edenduong** [comment] 2019-07-13 14:47
@LucianMihalache : the attribute_group_code group field is also not saved in the database. You should change "product-details" to other value like "product-detail-1". It was saved because there is the source code check if the attribute_group_code is empty, it will automatically get the attribute_group_code  value  base on the attribute_group_name 

                   $attributeGroupCode = trim(
                        preg_replace(
                            '/[^a-z0-9]+/',
                            '-',
                            $this->translitFilter->filter(strtolower($groupName))
                        ),
                        '-'
                    );

I fixed this issue in the Pull Request https://github.com/magento/magento2/pull/23690

**Comment by magento-engcom-team** [comment] 2019-08-19 23:00
Hi @LucianMihalache. Thank you for your report. 
The issue has been fixed in magento/magento2#23690 by @edenduong in 2.3-develop branch
Related commit(s):
 - [79410c8a82e9c346128d8dcc9cd382fb6557dad9](https://github.com/magento/magento2/commit/79410c8a82e9c346128d8dcc9cd382fb6557dad9)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-08-19 23:00 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Api
