### ISSUE TITLE
special characters should be filtered from the SKU field as they break secondary functionality

### ISSUE THREAD

**Issue by IanFiretoys** [magento/magento2#35257] opened 2022-04-01 09:00 UTC
### Preconditions (*)

1. 2.4.x
2.

### Steps to reproduce (*)

1. create a new product with an ampersand or slash in the `name` field
2. allow the `sku` field to autopopulate from the name
3. save the product
4. try and call the product's data with any REST GET api, or change the SKU

### Expected result (*)

1. information is called, or sku is successfully changed upon save
2.

### Actual result (*)

1. SKU change and REST calls both fail without useful errors
2. as you can't change the SKU due to the breaking error here, the product must then be deleted and remade

either a filter should be put on the functionality that autofills the `SKU` field from the `name` field, or a validation needs adding to the `SKU` field so you can't save a new product with special characters in.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by gaganmagento** [comment] 2022-04-01 09:59
@magento I am working on this

**Comment by gaganmagento** [comment] 2022-04-01 10:00
@magento add to contributors tea

**Comment by gaganmagento** [comment] 2022-04-01 10:00
@magento add to contributors team

**Comment by engcom-Hotel** [comment] 2022-04-04 10:57
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-04-04 11:34
Hello @IanFiretoys,

We have tried to reproduce the issue in Magento 2.4-develop branch but for us the issue is not reproducible. Please have a look into the below screenshots for reference:

**Product create with Ampersand(&) and Dash(-)**
![Previous-1](https://user-images.githubusercontent.com/51681618/161534972-85efc7a9-0972-4008-9790-8dc88f0f7bcd.jpg)

**Edit with REST API (​/V1​/products​/{sku})**
![After-1](https://user-images.githubusercontent.com/51681618/161535175-d8d83406-4278-43c6-9d6d-363f175e3623.jpg)

Please tell us the API which is failing for you. 

Thanks

**Comment by IanFiretoys** [comment] 2022-04-04 12:26
it was /rest/V1/inventory/get-product-salable-quantity/

**Comment by engcom-Hotel** [comment] 2022-04-05 07:34
Hello @IanFiretoys,

We have tried with the above mentioned API response as well but still the issue is not reproducible for us. Please have a look into the below screenshot for reference:

![image](https://user-images.githubusercontent.com/51681618/161702488-2f35642d-18ee-4c55-b4e4-9759a3e8ae10.png)

Thanks

**Comment by IanFiretoys** [comment] 2022-04-05 12:41
testing the direct REST calls on our environment, i can see that those requests are working ok. in this case it might be a 3rd party extension that is interfering with the calls and causing them to fail when loaded along with the rest of the product page.

```
TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in/public_html/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php on line 108 and defined in /public_html/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
```

**Comment by engcom-Hotel** [comment] 2022-04-06 06:30
Hello @IanFiretoys,

Thanks for the reply!

As the functionality is working fine and the issue is due to some third party extension, we are closing this issue for now.

Thanks

**Closed as completed by engcom-Hotel** 2022-04-06 06:30 UTC
Labels: Triage: Dev.Experience, Issue: needs update
