### ISSUE TITLE
Missing preference for DriverInterface

### ISSUE THREAD

**Issue by FreekVandeursen** [magento/magento2#24667] opened 2019-09-20 09:35 UTC
### Preconditions (*)
1. Magento 2.2.9 and 2.3.2

### Steps to reproduce (*)
1. Create a class and inject \Magento\Framework\Filesystem\Directory\Read in the constructor (or \Magento\Framework\Filesystem\Directory\Write)
2. Get the class via the object manager

### Expected result (*)
1. Class instance gets created

### Actual result (*)
1. Fatal error "Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface"

Apparently this DriverInterface gets a preference in the setup/config/di.config.php, but is unusable outside setup context.

**Comment by georgebabarus** [comment] 2019-09-21 10:09
I guess you should use one of it's implementation or use your own instead using interface preferences.
\Magento\Framework\Filesystem\Driver\File
\Magento\Framework\Filesystem\Driver\Http
\Magento\Framework\Filesystem\Driver\Https
\Magento\Framework\Filesystem\Driver\Zlib

The idea is that on setup it is clear that the process is dependent on single/local file system. And that's why it is defined a preference for this interface. But on a installed Magento instance it is not clear which one you want to use.

**Comment by xpoback** [comment] 2019-09-21 13:03
It it is suggested to use [a factory ](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Filesystem/Directory/ReadFactory.php) for instantiation of Read or Write. It'll inject the needed driver.
There is no preference because there is no "preferred" driver. I guess, Magento are'n going to change anything at this place.

**Comment by georgebabarus** [comment] 2019-09-21 13:57
Hi, Setup application is definitively dependent and implemented on local file-system since its only purpose is to install the application and so it is right to assume that the DriverInterface is always this type \Magento\Framework\Filesystem\Driver\File.

There are multiple implementation of file-system drivers, and for your purpose you should use 
\Magento\Framework\Filesystem\Directory\ReadFactory to create instances you need like this: $directory = $readFactory->create('path', DriverPool::FILE);

I assume you can close this ticket.

**Comment by FreekVandeursen** [comment] 2019-09-26 11:11
Thanks for the advice @xpoback and @georgebabarus , I didn't realize a factory was intended to be used to get a directory read instance here.

However, I wonder if this issue is still valid. After all, we now have classes marked as `@api` that cannot be injected into a constructor because of the missing preference. Shouldn't that at least be noted in the comments somewhere that these classes are not supposed to be used directly?

**Comment by georgebabarus** [comment] 2019-09-30 08:16
I wold say that the issue is not relevant for following reason: even if you have preference for driver interface this will not solve your problem since you also should specify the path parameter in the constructor of read class. Usually you don't have this path at dependency injection layer to pass it as config. 

So it is clear to use factory class for this purpose.

"A public interface is a set of code that third-party developers can call, implement, or build as a plug-in. Magento guarantees that this code will not change in subsequent releases without a major version change.

Public interfaces for a module are marked with @api annotation."
https://devdocs.magento.com/guides/v2.3/extension-dev-guide/api-concepts.html

**Comment by engcom-Charlie** [comment] 2019-10-01 10:41
Hello everyone! 
I am closing this issue because it is not relevant. 
Thanks for contributing!

**Closed as completed by engcom-Charlie** 2019-10-01 10:41 UTC
Labels: Issue: Format is valid
