### ISSUE TITLE
[Performance] Braintree - Request access token only when it's needed

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/magento2#25343] opened 2019-10-29 10:43 UTC
From https://github.com/magento/magento2/pull/25223#issuecomment-546616818:
Requesting of Access token takes ~200ms -> it's significantly slowing down the cart/checkout page.  On cart page for instance we don't really need this access token because we're not working with Braintree there at all, but it's still requesting it.

### Preconditions (*)
1. Magento 2.3.3 & 2.3-develop
2. Configured Braintree
3. Enable xdebug and put breakpoint here https://github.com/magento/magento2/blob/8eb592157ea4feead18e071869ec3b1bd5e5f619/app/code/Magento/Braintree/Model/Adapter/BraintreeAdapter.php#L108

### Steps to reproduce (*)
1. Go to shopping cart

### Expected result (*)
1. Access token isn't retrieved (code isn't paused on breakpoint)

### Actual result (*)
1. Access token is retrieved (code is paused on breakpoint)

### Additional info

In the admin panel client token retrieved by AJAX, only when it's really needed https://github.com/magento/magento2/pull/25223#issuecomment-546820900 but on frontend - it's not. 

I think the optimal way - to request client token also on frontend with AJAX request, **only when it's needed**.

**Comment by magento-engcom-team** [comment] 2019-10-30 18:58
Hi @ihor-sviziev. Thank you for your report. 
The issue has been fixed in magento/magento2#25223 by @andrey-legayev in 2.3-develop branch
Related commit(s):
 - [0fe0cdcc30a925422756452224bebdd667542e9c](https://github.com/magento/magento2/commit/0fe0cdcc30a925422756452224bebdd667542e9c)
 - [fb31ed9096a249a3f47e38000878b913829a44ed](https://github.com/magento/magento2/commit/fb31ed9096a249a3f47e38000878b913829a44ed)
 - [7c026f4f600acac429628eb7923b3f99973f9780](https://github.com/magento/magento2/commit/7c026f4f600acac429628eb7923b3f99973f9780)
 - [8eb592157ea4feead18e071869ec3b1bd5e5f619](https://github.com/magento/magento2/commit/8eb592157ea4feead18e071869ec3b1bd5e5f619)

The fix will be available with the upcoming 2.3.4 release.

**Comment by ihor-sviziev** [comment] 2019-10-30 19:05
Hi @sdzhepa,
You linked this issue. The issue is related, but it’s different.
#25223 fixes issue when module is disabled, but this issue for not requesting this token until it’s not needed at all. For instance on cart page it’s not really needed in both cases - when module is enabled or disabled
I reopened this issue

**Comment by magento-engcom-team** [comment] 2019-10-31 10:23
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22615` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by gabrieldagama** [comment] 2020-09-22 16:50
Hi @ihor-sviziev,

The Braintree module was removed from our repository and this issue should be reported directly to the extension provider on Magento Marketplace. I'm closing this issue for now.

Thanks.

**Closed as completed by gabrieldagama** 2020-09-22 16:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Braintree, Triage: Dev.Experience, Severity: S2, Progress: done

**Comment by onlinebizsoft** [comment] 2021-08-10 13:37
@gabrieldagama in this document
 https://docs.magento.com/user-guide/payment/braintree.html?_ga=2.106970375.409298059.1628601884-833781139.1615374538

It says "Beginning with Magento 2.4.0, the Braintree extension is included in the release" but you said it was removed from your repository?

**Comment by ihor-sviziev** [comment] 2021-08-10 14:14
@onlinebizsoft, it is a mistake in the docs.
I created PR for fixing it https://github.com/magento/merchdocs/pull/1429

**Comment by ihor-sviziev** [comment] 2021-08-16 19:48
@onlinebizsoft, according to https://github.com/magento/merchdocs/pull/1429#discussion_r689712158, since Magento 2.4.0, we have bundled official extension from the marketplace, it's not a part of Magento anymore

**Comment by onlinebizsoft** [comment] 2021-08-17 04:00
@ihor-sviziev I'm not sure how I should understand this
1. So since 2.4.0, Braintree is included or not included in a default installation? Or we still need to update composer to install it separately?
2. Which is the correct one recommended to use?
https://marketplace.magento.com/paypal-module-braintree.html -> I see it is maintained by Gene but there is no update since long time, bad feedback
https://github.com/genecommerce/module-braintree-magento2 -> it is more active but it is not on the marketplace
Or both will be same?

**Comment by ihor-sviziev** [comment] 2021-08-17 06:05
@onlinebizsoft, I asked for explanation in https://github.com/magento/merchdocs/pull/1429.

**Comment by onlinebizsoft** [comment] 2021-08-23 10:29
> Hi @sdzhepa,
> You linked this issue. The issue is related, but it’s different.
> #25223 fixes issue when module is disabled, but this issue for not requesting this token until it’s not needed at all. For instance on cart page it’s not really needed in both cases - when module is enabled or disabled
> I reopened this issue

@kartikmaniyar @ladonenko
