### ISSUE TITLE
Class \Magento\Framework\Data\Form\Element\Textarea breaks specification of the parent class \Magento\Framework\Data\Form\Element\AbstractElement by not calling the method getBeforeElementHtml (getAfterElementHtml is called)

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#2202] opened 2015-10-27 17:23 UTC
`\Magento\Framework\Data\Form\Element\AbstractElement::getAfterElementHtml()`
https://github.com/magento/magento2/tree/80c5e2b00170b290909f65f8922a7ebcb315ed1a/lib/internal/Magento/Framework/Data/Form/Element/AbstractElement.php#L385-L388

`\Magento\Framework\Data\Form\Element\AbstractElement::getBeforeElementHtml()`
https://github.com/magento/magento2/tree/80c5e2b00170b290909f65f8922a7ebcb315ed1a/lib/internal/Magento/Framework/Data/Form/Element/AbstractElement.php#L395-L398

`\Magento\Framework\Data\Form\Element\Textarea` calls `getAfterElementHtml` but not `getBeforeElementHtml`
https://github.com/magento/magento2/tree/80c5e2b00170b290909f65f8922a7ebcb315ed1a/lib/internal/Magento/Framework/Data/Form/Element/Textarea.php#L84-L88

**Comment by dfediuk** [comment] 2015-10-27 17:46
I have temporary fixed it for myself with a plugin: https://mage2.pro/t/150

**Comment by alankent** [comment] 2015-10-27 18:04
(Side note - how did you find the experience of creating a plugin?)

**Comment by dfediuk** [comment] 2015-10-27 18:23
I think the plugins is the **top one** feature of Magento 2.
It would be great to plug-in not only to the public methods but to the protected methods too.
It would help to solve the ploblems like https://github.com/magento/magento2/issues/2165 in a more efficient way (now I was forces to **override all the class** because the problem methods are protected and can not be plugged in).

**Comment by vzabaznov** [comment] 2016-06-22 13:05
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-06-22 13:06
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:19
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed by vzabaznov** 2016-07-14 08:19 UTC
Labels: needs update, PS
