### ISSUE TITLE
A lot of untranslatable phrases in app/code/Magento/Ui/view/base/web/templates/grid/paging.html

### ISSUE THREAD

**Issue by mage2pro** [magento/magento2#1788] opened 2015-09-04 10:39 UTC
For example: https://github.com/magento/magento2/blob/74867e1561e1ac45cac41034e8cb4b0a01e87fab/app/code/Magento/Ui/view/base/web/templates/grid/paging.html#L24

As I see, the template does not use any translator. How does it expected to be translated to another language?

**Comment by godban** [comment] 2015-09-04 13:58
Hello @dfediuk,
thank you for this report, you are right there is some text nodes without translation.

As for this page, it would be fixed with next pull request, guys already changed this pagination template.

But for for make sure, that we are not missed anything else, we will double check all grid templates.

**Comment by dfediuk** [comment] 2015-09-04 14:26
When you will fix it please note that just adding **bind-attr i18n** is not sufficient because of https://github.com/magento/magento2/issues/1791 bug.

**Comment by piotrekkaminski** [comment] 2015-10-07 22:56
@godban can you put in the comments the Jira issue?

**Comment by piotrekkaminski** [comment] 2015-10-14 04:05
@tkacheva can you look into it?

**Comment by anton-huz** [comment] 2016-06-14 16:15
Dmitry, the issue is not actual anymore. I'm going to close it.
But I can agree that Magento still has places for improvement in the i18n scope.

Thanks for your care for Magento's code base.

**Closed by anton-huz** 2016-06-14 16:15 UTC
Labels: acknowledged, CS
