### ISSUE TITLE
Product list widget not working in cms block or cms page

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#5398] opened 2016-07-01 08:43 UTC
I have cms block in which I have product list widget, conditions are a just category.
The block is on the page, additional text is there, but the product list is blank. no errors were given or anything. If I modify serialised data, it shows error, meaning that block is being parsed, but no output.

Issue occurs on multi store setup on non default store.

having this issue on versions 2.1.0 and 2.0.7.

**Comment by kandrejevs** [comment] 2016-07-01 08:48
And conditions are not being parsed in widget edit view. They are in serialized string but when you open widget editing interface, all conditions are blank again.

**Comment by samuellinde** [comment] 2016-07-02 06:45
Having the same issue with 2.1.0 CE.

**Comment by veloraven** [comment] 2016-07-28 14:34
@kandrejevs thank you for your report.
Could you please provide description according to the template: with steps, actual result and expected result? For easier information perceiving.

**Comment by allanpaiste** [comment] 2016-08-07 16:20
**Steps to reproduce**
1. Install Magento from `develop` branch.
2. log into admin
3. navigate to CONTENT >> Elements >> Blocks
4. create a new block (or use any existing one if you have demo data)
5. edit the content (the wysiwyg portion of the block edit form)
6. insert widget (should be the second option in the wysiwyg editor toolbar)
7. select widget type: Catalog Product List
8. add a couple of conditions for the widget (last form element for that widget).
9. save the widget (after which the widget edit form disappears and widget placeholder is added to the content)
10. _{OPTIONAL}_ Turn off the wysiwyg editor from "Show/Hide Editor" (just to confirm that the the rules configuration was saved correctly into the widget directive).
11. _{OPTIONAL}_ Turn on the wysiwyg editor from "Show/Hide Editor".
12. re-edit the widget

**Expected result**

Previously configured rules should still be there and configured the same way as before

**Actual result**

Rules have been reset. you have to reconfigure them from zero if you want to re-save the widget

**Additional information**

This works just fine when configured via CONTENT >> Elements >> Widgets

**Comment by allanpaiste** [comment] 2016-08-08 00:48
Seems to have been fixed in develop branch.

https://github.com/magento/magento2/commit/3ff19bf82a2ff2e4b7c3e9223cb53083fb60c72d

`$request['values']['conditions'] = $this->getConditionsHelper()->decode($request['values']['conditions_encoded']);
`

**Comment by AVoskoboinikov** [comment] 2016-08-31 09:31
Closing this ticket because of existing fix in develop branch.

**Closed as completed by AVoskoboinikov** 2016-08-31 09:31 UTC
Labels: bug report, Component: Cms

**Comment by hezide** [comment] 2017-02-26 19:47
this is since aug 2016, anyone knows in which version the fix is gonna be delivered?

**Comment by dio5** [comment] 2017-04-28 10:13
Bump. Still not working in 2.1.6...

**Comment by sanket-adhvaryu** [comment] 2017-07-01 16:39
Not working in 2.1.7

**Comment by BuysTooMuch** [comment] 2018-08-23 00:43
Somehow, unbelievably, over two years later, still **not working in 2.2.5**
