### ISSUE TITLE
Magento 2.2.1, export products all store views

### ISSUE THREAD

**Issue by cytracon** [magento/magento2#12356] opened 2017-11-20 10:40 UTC
Just tried to do an export of all products from all store views. But it just does export the default products. 

There is no way to export all products incl. the store view related ones.

**Comment by magento-engcom-team** [comment] 2017-11-20 11:54
@cytracon, thank you for your report.
The issue is already fixed in develop branch, 2.1.10

**Comment by cytracon** [comment] 2017-11-20 11:57
thanks, but I have the 2.2.1 version. did you fix it in 2.2.2 dev as well?

**Comment by magento-engcom-team** [comment] 2017-11-20 21:03
@cytracon, thank you for your report.
We've created internal ticket(s) MAGETWO-84181 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2017-12-12 12:25
@cytracon The issue is already fixed: [#11926](https://github.com/magento/magento2/pull/11926).

**Closed as completed by magento-engcom-team** 2017-12-12 12:25 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by cytracon** [comment] 2017-12-15 09:26
Still doesn't work with Magento 2.2.2, not fixed ...

**Comment by jyrkij** [comment] 2018-01-11 07:47
I'm having this exact issue in 2.2.2

**Comment by jessicagatto** [comment] 2018-01-31 13:26
Me too. It doesn't work with Magento EE  2.2.2

**Comment by ttcoelhoo** [comment] 2018-02-20 17:57
Me also, Magento Open Source 2.2.2. But it was working before on 2.1.x

**Comment by gemini9988** [comment] 2018-02-23 08:45
Does not work in Magento Open Source 2.2.2. It was working before we upgraded from 2.1

**Comment by Pomerian** [comment] 2018-02-25 07:37
Me too. Freshly installed Magento EE 2.2.2 has products export bug.

**Comment by KevinMace** [comment] 2018-03-02 10:59
I can report we're also seeing this issue in 2.2.2 Commerce.

**Comment by RomaKis** [comment] 2018-03-02 12:10
This issue have been fixed in https://github.com/magento/magento2/pull/11926.

**Comment by jeffliu68** [comment] 2018-07-12 04:11
Me too, in EE 2.2.2 only default store view exported. But import works if store_view_code is set.

**Comment by haljeshi** [comment] 2019-01-15 07:32
Having the same problem in Magento Open Source 2.2.3

**Comment by jignesh26** [comment] 2019-05-28 12:53
Have same issue in Magento ver. 2.2.3

**Comment by ESiebrandt** [comment] 2019-07-11 14:58
Issue still exists in 2.3.0 as well

**Comment by ShapesGraphicStudio** [comment] 2019-07-30 09:11
Indeed, still having this issue in 2.3.0 too.
