### ISSUE TITLE
Ui_component column sortOrder doesn't work

### ISSUE THREAD

**Issue by Bravarg** [magento/magento2#4620] opened 2016-05-22 15:05 UTC
I creating a new adminhtml grid, and I have found a problem with setting up columns positions.
## Steps to reproduce
1. For example open the ui_component of adminhtml catalog product list Magento/Catalog/view/adminhtml/ui_component/product_listing.xml.
2. Section "columns". Elements "column" have "sortOrder" config, which should sort columns in grid. 
3. Decrease value "sortOrder" of "name" column to 15.
   ![screenshot_149](https://cloud.githubusercontent.com/assets/11926404/15454581/eb5ee35c-2045-11e6-8544-d1174a36cc74.png)
## Expected result
1. The column "name" should be moved between ID and Thumbnail
   ![screenshot_150](https://cloud.githubusercontent.com/assets/11926404/15454584/fa380c14-2045-11e6-871a-19064d52c619.png)
## Actual result
1. Column aren't being moved.

I assume the bug is in Ui module. The file Magento/Ui/view/base/web/js/grid/listing.js contains mehtod "updatePositions" that setting up columns position by their index instead of element sortOrder. The working solution for me is replace "index" for "elem.sortOrder".
![screenshot_151](https://cloud.githubusercontent.com/assets/11926404/15454618/e247abfe-2046-11e6-944e-28a34e9c1859.png)

**Comment by anton-huz** [comment] 2016-05-23 13:47
Hi @rawick ,
Thanks for catch! We will investigate issue under MAGETWO-53310 task.

Stay in touch.

**Comment by anton-huz** [comment] 2016-05-26 07:22
@rawick could you do:

 `TRUNCATE `ui_bookmark`;` in scope of your MYSQL db.
Grids UI have such feature as _"Bookmarks"_. It allows to save Grid's state per user. It's ON by default. Looks like you got cached value.

**Comment by Bravarg** [comment] 2016-05-26 07:31
@guz-anton I cleared all the caches, include this table and pub/static/ content. the problem is exactly in ignoring xml attribute "sortOrder". Yes, you can replace columns in ui_component, clear cached table and it will be ok, but attribute "sortOrder" won't has any usage anyway.

**Comment by anton-huz** [comment] 2016-05-26 08:21
@rawick
`sortOrder` is used on upper level than you point. Before Grid (via `listing.js`) applying `position` some actions are done by [`layout.js`](https://github.com/magento/magento2/blob/develop/app/code/Magento/Ui/view/base/web/js/core/renderer/layout.js#L276).

On Grid level with `position` works Bookmark UI component. It uses component's indexes. And it expected behavior. `position` has other value than `sortOrder`.

You can find in mysql db records in `ui_bookmark` table. If you drop it your changes from `xml` will be applied.

So under "clear caches" after changing "sortOrder" in xml you should do:
- clear mysql table `ui_bookmark`. E.g.:  
  `mysql -uroot -p -e 'USE `magento_db_name`;TRUNCATE `ui_bookmark`;'`
- clear caches for xml configuration. E.g.:  
  `sudo -u www-data rm -rf var/cache/*`

**Comment by anton-huz** [comment] 2016-06-09 12:18
Currently I'm closing issue as one that "Cannot reproduce".

@rawick please comment here if any additional info you'll have.

**Closed as completed by anton-huz** 2016-06-09 12:18 UTC
Labels: Issue: Format is not valid

**Comment by JanisE** [comment] 2017-11-27 13:17
Deleting the related `ui_bookmark` table rows fixed this for me, but is that really the expected behaviour - to not be able to (re-)define the column order by XML or at least reset the order by clearing a cache, instead of manually editing database?

**Comment by PivitParkour94** [comment] 2019-10-31 04:47
Is clearing the ui_bookmark table supposed to be built into a cache type or something in the future? It seems a little bit too devvy for someone who's just testing a new version of a ui_component...

**Comment by PivitParkour94** [comment] 2019-11-06 23:42
If anyone is interested, I made a Feature Request with a proposed solution to the clearing of the ui_bookmark table that doesn't require technical DB knowledge
https://github.com/magento/community-features/issues/215

**Comment by dchaykas** [comment] 2019-12-19 22:29
2.2.8 same issue, adding "sortOrder" attribute to <column> node has no effect (even with clearing cache) until the table ui_bookmark is truncated.

**Comment by younkim** [comment] 2021-01-07 03:16
This still happens in 2.4.1.
