### ISSUE TITLE
Quote ids created without adding product to cart

### ISSUE THREAD

**Issue by Medeka** [magento/magento2#36821] opened 2023-02-08 22:11 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1

We upgraded to Magento 2.4.5-p1 and noticed quote table is getting very big in a few days. This appears to be due to the following problem:

When a visitor is logged in on frontend and visits a product view page that is not cached, a new quote_id is created in 'quote' table. When customer visits 10 unique product view pages, without adding them to cart, 10 quote_ids with zero quote items are added to the quote table. 

When this user adds a product to cart the first quote id on his session is counting the items.

### Steps to reproduce

1. Disable page cache
2. Create a customer account
3. Login on frontend
4. Visit three different product view pages
6. Do not add products to cart

### Expected result

Quote table includes maximum one quote id for this session

### Actual result

Four quote ids are created:
- When user is getting logged in the first id is created
- For every single product page view a new quote_id is added

### Additional information

When we disable 'PayPal_Braintree' the problem is solved.
We don't have set any configuration on PayPal_Braintree, all settings are default (we don't use these payment methods)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-02-09 11:26
Hi @Medeka,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Disable page cache
2.Create a customer account
3.Login on frontend
4.Visit three different product view pages
5.Do not add products to cart.


<img width="1470" alt="Screenshot 2023-02-09 at 2 27 58 PM" src="https://user-images.githubusercontent.com/51680745/217797815-2d8b2ca7-fbd4-429a-80d0-ab432c33587e.png">

Before visiting the Product view Pages


<img width="1509" alt="Screenshot 2023-02-09 at 2 26 36 PM" src="https://user-images.githubusercontent.com/51680745/217797880-131947b4-d1c5-42e2-b5f0-9e2446df2ec3.png">
<img width="1504" alt="Screenshot 2023-02-09 at 2 24 52 PM" src="https://user-images.githubusercontent.com/51680745/217797930-f83bb9cd-0a39-420c-90c5-e03ec3603a4a.png">


After Visiting the Product view Pages

<img width="1512" alt="Screenshot 2023-02-09 at 2 25 56 PM" src="https://user-images.githubusercontent.com/51680745/217798128-92219896-7a6e-45bb-b5d3-1ceece0e57eb.png">


There are no multiple quote id's for a product.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-21 06:03
Hi @Medeka,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-21 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1
