### ISSUE TITLE
Unable to retrieve orders by date range searchCriteria through Web API

### ISSUE THREAD

**Issue by wilcovanesch** [magento/magento2#27308] opened 2020-03-17 09:25 UTC
### Preconditions

1. 2.3.4

### Steps to reproduce

Provide appropriate values for DOMAIN and TOKEN and execute:

curl -X GET "https://DOMAIN/rest/default/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=created_at&searchCriteria[filter_groups][0][filters][0][value]=2020-03-16 00:00:00&searchCriteria[filter_groups][0][filters][0][condition_type]=from&searchCriteria[filter_groups][1][filters][0][field]=created_at&searchCriteria[filter_groups][1][filters][0][value]=2020-03-15 00:00:00&searchCriteria[filter_groups][1][filters][0][condition_type]=to&fields=items[created_at]" -H "accept: application/json" -H "Authorization: Bearer TOKEN"

### Expected result

Something akin to:

SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE ((`created_at` >= '2020-03-16 07:49:39')) AND ((`created_at` <= '2020-03-17 07:49:43'))

### Actual result

SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE ((`` >= '')) AND ((`created_at` = '')) AND ((`` = '2020-03-17 07:49:39')) AND ((`` <= '')) AND ((`created_at` = '')) AND ((`` = '2020-03-16 07:49:43'))

Which understandably fails (Column not found: 1054 Unknown column '' in 'where clause').

**Comment by wilcovanesch** [comment] 2020-03-17 09:29
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-03-17 09:29
Hi @wilcovanesch. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by wilcovanesch** [comment] 2020-03-18 11:35
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-18 11:35
Hi @wilcovanesch. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by engcom-Alfa** [comment] 2021-01-05 12:24
Hi @wilcovanesch .
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
Everything works as expected.

**Precondition:**

Have 3 orders created in 2021-01-05 for example
![Screenshot from 2021-01-05 14-16-15](https://user-images.githubusercontent.com/51679138/103645459-af36f000-4f60-11eb-9edc-da43f289900f.png)


**Manual testing scenario:**

Send **GET** request `http://magento24.loc/rest/default/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=created_at&searchCriteria[filter_groups][0][filters][0][value]=2021-01-04 00:00:00&searchCriteria[filter_groups][0][filters][0][condition_type]=from&searchCriteria[filter_groups][1][filters][0][field]=created_at&searchCriteria[filter_groups][1][filters][0][value]=2021-01-06 00:00:00&searchCriteria[filter_groups][1][filters][0][condition_type]=to&fields=items[created_at]`

![Screenshot from 2021-01-05 14-18-23](https://user-images.githubusercontent.com/51679138/103645588-ead1ba00-4f60-11eb-9a15-4300ffa7ea89.png)

**Actual Result:** :heavy_check_mark: Received a list of orders by search criteria by date range. 200 OK


![Screenshot from 2021-01-05 14-21-43](https://user-images.githubusercontent.com/51679138/103645861-5b78d680-4f61-11eb-998f-5139dee401dc.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-01-05 12:24 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4
