### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state error 

### ISSUE THREAD

**Issue by CelinaNguyen114** [magento/magento2#32945] opened 2021-05-05 08:04 UTC
Hi Magento Supporter, 

Currently, when we access the Admin with the Sale role only and  go to orders. We will get a  “Something went wrong with processing the default view and we have restored the filter to its original state” error. Could you please take a look and give us advice on how to fix it? 

### Preconditions (*)

Magento CE 2.3.6-p1
Linux (x86_64)
PHP 7.3.28
mysql  Ver 15.1 Distrib 10.3.28-MariaDB

### Steps to reproduce (*)

Step 1: access the Admin with the Sale role only. 
Step 2: Goto orders.

### Expected result (*)

we will no longer see the “ Something went wrong ….”  error when we go to orders with a Sales role. 

### Actual result (*)

 Appear “ Something went wrong ….”  error . 
![something error](https://user-images.githubusercontent.com/83684394/117112387-2f584f80-adb3-11eb-92f7-cd215d8aeaa0.png)

Thanks!
Celina

**Comment by engcom-Oscar** [comment] 2021-05-06 08:10
Hi @CelinaNguyen114 Thank you for your report.
Unfortunately, we are not able to reproduce the issue. Looks like we miss some important preconditions, so may you please recheck and update description?

**Comment by CelinaNguyen114** [comment] 2021-05-06 09:07
Hi @engcom-Oscar, 

Thank you for your feedback, 

Good to note: This has only happened with non-administrator ID’s ( Sale level/role )  

Steps to reproduce (*)
Step 1: access the Admin with the Sale role only.
Step 2: Go to view an order; you will see this error: 

![Screenshot_9](https://user-images.githubusercontent.com/83684394/117270806-c987c880-ae83-11eb-923b-9ebaaea7a3c9.png)

Preconditions (*)
Magento CE 2.3.6-p1
Linux (x86_64)
PHP 7.3.28
mysql Ver 15.1 Distrib 10.3.28-MariaDB

Could you please check it again and let us know if you need further information to diagnose?   

Thank You!
Celina

**Comment by engcom-Oscar** [comment] 2021-05-27 11:21
Hi @CelinaNguyen114 
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
**Actual Result:** :heavy_check_mark: 
![Screenshot from 2021-05-27 14-19-13](https://user-images.githubusercontent.com/60198413/119817511-be5e1080-bef6-11eb-89b6-0249d25698af.png)

So, we have to close this ticket.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) if you are still facing this issue on the latest `2.4-develop` branch.
Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-05-27 11:21 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
