### ISSUE TITLE
Magento 2.1.2 deletes itself | extension activation + rollback

### ISSUE THREAD

**Issue by magenx** [magento/magento2#8017] opened 2017-01-02 19:18 UTC
### Preconditions
1.  Magento 2.1.2

### Steps to reproduce
1.  Upload new extension
2.  Activate from admin web setup wizard
3.  On activation error click rollback

### Expected result
1. All files must be safe and working

### Actual result
1. all files just gone, only (pub,update,var) folders left
2. admin errors 403 in browser console
3. after page reload 403 error, white page...

```
Enable Magento2_Blog Status:

Update application is not running

Error in Update! 
Please refer to documentation Doc link to perform manual rollback.

To attempt automatic rollback, please click the "Rollback" button.

Rollback
```

```

[2017-01-02 14:49:02 CET] Job "rollback {"backup_file_name":"/home/magento/public_html/var/backups/1483025627_filesystem_code.tgz"}" has been started
[2017-01-02 14:49:02 CET] Restoring archive from "/home/magento/public_html/var/backups/1483025627_filesystem_code.tgz" ...
[2017-01-02 14:49:03 CET] An error occurred while executing job "rollback {"backup_file_name":"/home/magento/public_html/var/backups/1483025627_filesystem_code.tgz"}": Invalid argument, /home/magento/public_html/var/backups/1483025627_filesystem_code.tar cannot be found
[2017-01-02 14:49:03 CET] Job "rollback {"backup_file_name":"/home/magento/public_html/var/backups/1483025627_filesystem_media.tgz"}" has been started
[2017-01-02 14:49:03 CET] Restoring archive from "/home/magento/public_html/var/backups/1483025627_filesystem_media.tgz" ...
[2017-01-02 14:49:04 CET] An error occurred while executing job "rollback {"backup_file_name":"/home/magento/public_html/var/backups/1483025627_filesystem_media.tgz"}": Invalid argument, /home/magento/public_html/var/backups/1483025627_filesystem_media.tar cannot be found

```

**Comment by xmav** [comment] 2017-01-24 13:49
@magenx Issue for "Not possible to enable module under Web Setup wizard" is already addressed in internal ticket MAGETWO-57936. I’ve added your report on this issue to that ticket.
But I cannot reproduce second part of this issue(deleted files).
Please provide the detailed steps we must follow to reproduce.
How did you create backup?
In addition, identify the web server you are running, the versions of PHP and MySQL, and any other information needed to reproduce your issue.

**Comment by jmackiol-dotsource** [comment] 2017-02-01 12:31
I have experienced a similar issue when switching from _development_ -> _production_ -> _development_ mode or sometimes when clicking the "clear static files" button in cache management.
All content was gone because a " /"  instead of "/" is used when removing all content - and this seems to fall back to the root of the application.
In my case the German translation (from https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE) seems to cause the issue - as a tag "ui/grid/filters/elements/select" is translated with spacing characters ...
At lease this issue did not occur yet after removing the string from the translation tag.

**Comment by magenx** [comment] 2017-02-01 15:18
backup was created i guess by magento clicking on button backup during module activation.
this is backup/rollback automatic procedure. then clicked rollback button.
as you can see backup/rollback is looking for different files, tgz | tar, is that ok?
not sure what was there, as i dont really want to test it again...

**Comment by xmav** [comment] 2017-02-06 17:30
@magenx 
I see only one way to reproduce this issue(for now). It can be reproduced if clean (remove all files) var/backups/ while rollback is in progress.

**Comment by magenx** [comment] 2017-02-06 17:37
as i understand backup was not created at all... look at the file names

**Comment by xmav** [comment] 2017-02-06 21:45
In that case there  will be messages like: 

> WARNING: There is a problem with backup files! Performing rollback from these files may cause the Magento application to be unstable
> Backup file does not exist for "code"
> Backup file does not exist for "db"

This message 
`[2017-01-02 14:49:03 CET] An error occurred while executing job "rollback {"backup_file_name":"/home/magento/public_html/var/backups/1483025627_filesystem_code.tgz"}": Invalid argument, /home/magento/public_html/var/backups/1483025627_filesystem_code.tar cannot be found`
indicates that file exists and there was a problem to process it. 
One of the first steps is to create  .tar from .tgz (1483025627_filesystem_code.tar from 1483025627_filesystem_code.tgz).
Next step is to process that .tar file.
`Invalid argument, /home/magento/public_html/var/backups/1483025627_filesystem_code.tar cannot be found` indicates that file does not exist.

**Comment by xmav** [comment] 2017-02-06 21:55
But you are right that failed(by any reason) rollback procedure may lead to deleted files.
This issue is already addressed in internal ticket MAGETWO-38592. I’ve added your report on this issue to that ticket.

**Comment by gediminaskv** [comment] 2017-03-24 08:47
I have same issue with 2.1.5 cron job. When cron job has started, files were being deleted. As soon as I noticed this, I changed file permissions back to recommended for production mode and files stopped disappering.

http://magento.stackexchange.com/questions/165876/cronjob-started-rollback-and-files-were-deleted-why

**Comment by vrann** [comment] 2017-03-30 15:46
Commits in 2.2:
f1b21ad
c411a46
1331ad2
6ccc9f1

**Comment by qaiserali** [comment] 2017-05-29 09:02
I can have a look to this issue

**Comment by adamjezek98** [comment] 2017-10-02 13:42
Also experienced this few times. Once when switching to developer via command line and once when installing module ([generated from mage2gen](https://mage2gen.com/load/9e9a75ed-e70f-4438-87fc-fce992cc07a0)) over web setup wizard. Only folders dev, phpserver and pub were not deleted. All backups files were stored in var folder, so they are gone. 

Magento version  Magento-CE-2.2.0-2017-09-25-08-19-44
PHP 7.0, Apache2, Ubuntu 17.04 server

Are you sure the issue was caused by wrong german translation? My store language is set to English (default), currency CZK. This happening on production server wouldn't be nice...

**Comment by hubertus2017** [comment] 2017-12-11 14:17
Hello,
same problem: Backup file does not exist for "db"

 but the DB file is there! No backup files are deleted! 
Manual rollback via command line is possible.

Success for media and code backup files...

**Comment by oviliz** [comment] 2017-12-23 01:38
I'm queuing to this as I was installing a market extension when something went wrong and the Rollback gave me the same answer, `Backup file does not exist for "db"`.
When doing it via command line `bin/magento setup:rollback -c 1513983064_filesystem_code.tgz -d 1513983064_db.sql`, it succeeds apparently (composer is playing up at this point but probably another issue) **but the db.sql file is deleted**... what a mess!! :(

That -d, http://devdocs.magento.com/guides/v2.2/install-gde/install/cli/install-cli-backup.html, must stand for `delete` for some reason...

**Comment by magento-engcom-team** [comment] 2018-03-14 15:30
@magenx, thank you for your report.
The issue is already fixed in 2.2.3, 2.3.0

**Closed as completed by magento-engcom-team** 2018-03-14 15:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Setup, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Event: distributed-cd

**Comment by Jeeva-Rathinam** [comment] 2018-05-02 04:54
Anyone have solution?

**Comment by oviliz** [comment] 2018-05-30 22:43
The solution is to upgrade Magento, @Jeeva-Rathinam

**Comment by Vishrootways** [comment] 2020-04-11 05:15
I got the same issue on Magento 2.3.3, I never faced this before. 

The issue is all the files and folders will be from "/app/design/frontend/Compnay_Name/Theme_Name/web" folder after I run below commands.

1) I first run below commands remove one directory from \app\code\Rootways for that I first go to this location in SSH then run below commands
rm -r payment/
2) then run below commands from website root directory
php bin/magento s:up
php bin/magento c:f
php bin/magento c:c
php bin/magento indexer:reindex

After that many files and folders will be removed from serverl places from the website.

Can anyone suggest us how to find out this issue?
