### ISSUE TITLE
Widgets on home page bug

### ISSUE THREAD

**Issue by gustavnilsson14** [magento/magento2#3025] opened 2016-01-18 11:15 UTC
Adding a product list widget via the Content > Pages > Home page and only filling the title with 'test' produces "We're sorry, an error has occurred while generating this email." on the homepage.

**Comment by niknah** [comment] 2016-02-09 06:11
I didn't get an error, but it was blank with no errors.  It inserted this code...

<p>&nbsp;{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" products_count="10" template="product/widget/content/grid.phtml" conditions_encoded="a:1:[i:1;a:4:[s:4:`type`;s:50:`Magento|CatalogWidget|Model|Rule|Condition|Combine`;s:10:`aggregator`;s:3:`all`;s:5:`value`;s:1:`1`;s:9:`new_child`;s:0:``;]]" }}</p>

After I removed the "conditions_encoded..." bit it worked.

<p>&nbsp;{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" products_count="10" template="product/widget/content/grid.phtml" }}</p>

To use the "new products" widget you need to remove the bit that says "display_type..."

Almost none of the widgets work.  You'd think this would be one of the first things a new user does when they make a new site.  The only widgets that are working for me are "product link", "orders and return".

**Comment by peterjaap** [comment] 2016-03-15 16:50
The problem is the missing extension name in the template argument. Add 'Magento_Catalogwidget::' before the template, like this;

```
template="Magento_Catalogwidget::product/widget/content/grid.phtml" 
```

Then it will work. This is a bug in the core.

**Comment by sangatpedas** [comment] 2016-03-21 10:06
Same issue and I tried Peter Jaap's approach but no result, following niknah's approach delivered the expected results

**Comment by antonlazarchenko** [comment] 2016-07-26 14:07
I confirm that Peter Japp's solution doesn't works for me too. 
I have two custom blocks and one custom widget at home content page. 
Sendmail is fake.

**Comment by webspeaks** [comment] 2016-08-13 14:27
This error is quite misleading. In my case an error in MySql query was causing this.
You should enable developer mode the get the exact error. 
`php ./bin/magento deploy:mode:set developer`

**Comment by veloraven** [comment] 2016-08-16 12:49
@gustavnilsson14 is this issue still actual?
Please, provide the used Magento version and information if it was clear install or upgrade from some other version if yes.
Please close this issue if it is not actual now.

**Comment by veloraven** [comment] 2016-08-31 11:26
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-08-31 11:26 UTC
Labels: Progress: needs update

**Comment by myselfgaurav** [comment] 2016-10-25 20:06
hi i got same error could not figure why so below is code in my front page:

**Comment by rikwillems** [comment] 2018-05-03 08:28
Although maybe a bit late but the answer by @peterjaap is actually the solution except for a typo. Notice the capital W.
`template="Magento_CatalogWidget::product/widget/content/grid.phtml"`
