### ISSUE TITLE
Customer Create fails

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#28251] opened 2020-05-18 07:21 UTC
### Preconditions (*)

1. 2.3.2
2.

### Steps to reproduce (*)

1. followed exact directions from https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-customer.html 
2.

### Expected result (*)

1. [Screenshots, logs or description]
2. should give 200 and create account

### Actual result (*)

1. [Screenshots, logs or description]
2.
`"message": "No such entity with %fieldName = %fieldValue, %field2Name = %field2Value",
    "parameters": {
        "fieldName": "email",
        "fieldValue": "jdoe@example.com",
        "field2Name": "websiteId",
        "field2Value": "1"
    },
    "trace": "#0 /home/example/public_html/vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php(326): Magento\\Customer\\Model\\CustomerRegistry->retrieveByEmail('jdoe@example.co...', '1')\n#1 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository->get('jdoe@example.co...')\n#2 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository\\Interceptor->___callParent('get', Array)\n#3 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository\\Interceptor->Magento\\Framework\\Interception\\{closure}('jdoe@example.co...')\n#4 /home/example/public_html/generated/code/Magento/Customer/Model/ResourceModel/CustomerRepository/Interceptor.php(39): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository\\Interceptor->___callPlugins('get', Array, Array)\n#5 /home/example/public_html/vendor/magento/module-customer/Model/AccountManagement.php(866): Magento\\Customer\\Model\\ResourceModel\\CustomerRepository\\Interceptor->get('jdoe@example.co...')\n#6 /home/example/public_html/generated/code/Magento/Customer/Model/AccountManagement/Interceptor.php(141): Magento\\Customer\\Model\\AccountManagement->createAccountWithPasswordHash(Object(Magento\\Customer\\Model\\Data\\Customer), 'ce82c5035bb7d75...', '')\n#7 /home/example/public_html/vendor/magento/module-customer/Model/AccountManagement.php(851): Magento\\Customer\\Model\\AccountManagement\\Interceptor->createAccountWithPasswordHash(Object(Magento\\Customer\\Model\\Data\\Customer), 'ce82c5035bb7d75...', '')\n#8 /home/example/public_html/generated/code/Magento/Customer/Model/AccountManagement/Interceptor.php(128): Magento\\Customer\\Model\\AccountManagement->createAccount(Object(Magento\\Customer\\Model\\Data\\Customer), 'Password1', '')\n#9 [internal function]: Magento\\Customer\\Model\\AccountManagement\\Interceptor->createAccount(Object(Magento\\Customer\\Model\\Data\\Customer), 'Password1', '')\n#10 /home/example/public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#11 /home/example/public_html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#12 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#13 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#14 /home/example/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 /home/example/public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#16 /home/example/public_html/vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 /home/example/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#18 /home/example/public_html/vendor/magento/framework/App/Bootstrap.php(261): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#19 /home/example/public_html/index.php(40): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#20 {main}"
}`

**Comment by dmcmillin** [comment] 2020-05-18 07:23
@magento give me 2.3 instance

**Comment by CarmineDamore78** [comment] 2020-05-20 13:47
@magento give me 2.3 instance

**Comment by engcom-Alfa** [comment] 2020-05-22 13:01
Hi, @dmcmillin . Thank you for your report.

Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop

**Manual testing scenario:**

1. Followed exact directions from https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-customer.html 
2. Sent request:
```
{
  "customer": {
    "email": "jdoe@example.com",
    "firstname": "Jane",
    "lastname": "Doe",
    "addresses": [
      {
        "defaultShipping": true,
        "defaultBilling": true,
        "firstname": "Jane",
        "lastname": "Doe",
        "region": {
          "regionCode": "NY",
          "region": "New York",
          "regionId": 43
        },
        "postcode": "10755",
        "street": [
          "123 Oak Ave"
        ],
        "city": "Purchase",
        "telephone": "512-555-1111",
        "countryId": "US"
      }
    ]
  },
  "password": "Password1"
}
```
![Screenshot from 2020-05-22 15-49-32](https://user-images.githubusercontent.com/51679138/82670028-1a87b800-9c45-11ea-9ef4-8102f6baeb45.png)

**Actual Result:** :heavy_check_mark: The customer was successfully created

![Screenshot from 2020-05-22 15-49-54](https://user-images.githubusercontent.com/51679138/82670138-43a84880-9c45-11ea-95dd-1bd8f931f7c2.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-05-22 13:01 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: dev in progress, Reported on 2.3.2

**Comment by dmcmillin** [comment] 2020-05-24 01:03
some customers might not be using 2.4 but rather 2.3.5 which is what's available from both composer and https://magento.com/tech-resources/download

please advise.
