### ISSUE TITLE
[Magento 2.4.4] Class magento/zendframework1/library/Zend/Pdf/NameTree.php not compatible with PHP 8.1

### ISSUE THREAD

**Issue by magentix** [magento/magento2#35335] opened 2022-04-20 10:00 UTC
### Preconditions (*)

1. Magento 2.4.4
2. PHP 8.1

### Steps to reproduce (*)

1. Go to the **Sales Shipments** page in admin. Select shipments and the "Print Shipping Labels" action.

### Expected result (*)

1. Get a PDF with all the shipment labels

### Actual result (*)

1. PHP crashes with the following error :

```
Fatal error: During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of Zend_Pdf_NameTree::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/magento/zendframework1/library/Zend/Pdf/NameTree.php on line 117
```

The error happens with the *Magento\Shipping\Model\Shipping\LabelGenerator::combineLabelsPdf* method.

**Additional Information:**
Please refer below comment:

https://github.com/magento/magento2/issues/35335#issuecomment-1103902652

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-20 12:58
Verified the issues on Magento 2.4-develop branch and 2.4.4 versions and the issue is reproducible on 2.4.4 instance but not on 2.4-develop branch.
Steps performed:
1. Configure Fedex shipping method as per https://jira.corp.magento.com/browse/MC-27213
2. Frontend - Login as customer - Created Order
3. Submit Invoice from admin
4. Ship - Create Shipping Label and Submit
5. Go to Sales - Shipments - Select shipment and Print Shipping Labels 
Issue: 
![image](https://user-images.githubusercontent.com/60198231/164235594-49f0245b-b76b-4d2d-aa6d-93c07806897b.png)

**Comment by Vishrootways** [comment] 2022-06-27 12:59
Facing the same issue. If this is a known issue then does any patch available to fix this issue?

**Comment by hostep** [comment] 2022-06-27 13:14
@Vishrootways: try updating `magento/zendframework1 ` to version 1.15.1, see https://github.com/magento/zf1/pull/46#issuecomment-1165267804

**Comment by Vishrootways** [comment] 2022-07-01 10:40
@hostep Updating magento/zendframework1 to version 1.15.1 works. Thank you

**Comment by Nuranto** [comment] 2022-07-11 08:36
This is issue is partially fixed in 1.15.1.

I still got error, but in different file :  

```
PHP Fatal error: During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of Zend_Memory_Value::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/magento/zendframework1/library/Zend/Memory/Value.php 
```

=> `magento/zendframework1/library/Zend/Memory/Value.php`

**Comment by hostep** [comment] 2022-07-11 14:41
@Nuranto: could you report this as a new issue on https://github.com/magento/zf1/issues? I think it will get picked up sooner that way, thanks! 🙂

**Comment by engcom-November** [comment] 2022-09-14 10:15
Hi @magentix 
As I can see this issue got fixed in the scope of the internal Jira ticket AC-2892 by the internal team
Related commits: d0e6289cc682de0024f531bc508499c4b3f2dc26 and 7f6bbfdf0f797e8af7971ce2893ffc721dcd5ea3
Based on Jira, target version is 2.4.5
Thank you.

**Comment by SPbryan007** [comment] 2023-02-01 20:07
@magento give me 2.4.5-p1 instance

**Closed as completed** 2024-12-10 07:43 UTC
Labels: Component: Shipping, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Shipping, Reported on 2.4.4
