### ISSUE TITLE
Deleting Addresses From Customer Doesn't Delete Them

### ISSUE THREAD

**Issue by Any-Documentation-Would-be-Great** [magento/magento2#34494] opened 2021-11-01 17:04 UTC
I delete an address from a customer. I hit save customer. The page reloads and the deleted addresses are back. Every time I do this for the last 2 months. The addresses are NOT duplicated in our ERP. They are only duplicated in magento, and magento refuses to do what it says it does. I would like my customer to not have to rifle through 300 duplicate addresses to place an order.

### Preconditions (*)

1. 2.4.2-P1
2. 

### Steps to reproduce (*)

1.  Pretty obvious steps. Read above.
2. 
3. 

### Expected result (*)

1. ADDRESS GETS DELETED

### Actual result (*)

1. YOU SAY SCREW ME AND PUT THE ADDRESS BACK AND DON'T ACTUALLY DO ANYTHING

**Comment by engcom-Hotel** [comment] 2021-11-04 09:38
Hi @Any-Documentation-Would-be-Great,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-develop but the delete address functionality is working as expected and it is deleting the user address on delete activity.

Steps followed to reproduce issue:
1. Visit the Customer->All Customer-> (Select any customer)-> Go to Address tab.
2. Add a new address if it does not exist or select the already added address.
3. Select the delete action from the Action dropdown.
4. Confirm the delete action and click on “Save and Continue Edit” or “Save Customer’.
4. Observe the address tab (See the attached screenshots).

It looks like the issue is caused due to some other add-ons or might be an environmental issue. So in order to do further analysis of this issue, please update the below queries:
1. Can you share some of the screenshots/short videos of the error you got?
2. Verify the logged issue for PHP/Env and try to delete the address after resolving the PHP/env issue.

If the issue still persists provide the details, accordingly I’ll try to reproduce it again.

<img width="1440" alt="Screenshot 2021-11-03 at 6 29 29 PM" src="https://user-images.githubusercontent.com/51681618/140291150-5dbd12f1-b8d8-4c99-9b99-0a4bf4b842a0.png">
<img width="1440" alt="Screenshot 2021-11-03 at 6 30 19 PM" src="https://user-images.githubusercontent.com/51681618/140291160-00788951-733a-4889-83a6-73c0909073a6.png">
<img width="1440" alt="Screenshot 2021-11-03 at 6 30 59 PM" src="https://user-images.githubusercontent.com/51681618/140291163-b94061b9-8dbc-4e96-9d5e-3d2a2ee63455.png">

Thanks

**Comment by Any-Documentation-Would-be-Great** [comment] 2021-11-04 15:30
I'll attach a video of my process but what the hell is number 2 talking about? "Verify the logged issue for PHP/Env and try to delete the address after resolving the PHP/env issue." 

Do you guys have an actual support system anywhere in existence? Why are we paying for a service that hosts it's "Ticket System" on GITHUB? Seriously. You should be able to know exactly what environment I'm running. You should know everything about my system because we are PAYING YOU TO HOST IT. If you don't know these things, why am I here? Who can I call or talk to who DOES know anything about my system/add-ons? This feels is like trying to get help with a free download made by someone in their basement rather than something we pay thousands of dollars a year for.

Get a real support system for the professional grade software you are advertising and **taking money** for.

https://user-images.githubusercontent.com/90729445/140356067-f0208864-4cd5-4fb8-a762-59a7c457d3ef.mp4

**Comment by sdzhepa** [comment] 2021-11-11 18:37
Hello @Any-Documentation-Would-be-Great 

Looking at the comments I assume it's some miscommunication is happened..which lead to the wrong expectation. Sorry for that. Let me try to shed more light on it and provide an explanation

First of all, you are absolutely right - this GitHub repository and tracker is not any kind of official Magento support portal.

**Official Magento support portal: https://support.magento.com/**

- In this part of [Magento Help Center User Guide](https://support.magento.com/hc/en-us/articles/360000913794) you can find answer on [How to submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#support-tickets)


This GitHub repository and issue tracker is aimed at the community collaboration around Magento Open Source.
Any person from the community can report an issue and after it passed all required gates everyone can take the issue in progress and propose Pull Request with the solution/fix. When this Pull Request passes Code Review and all quality requirements, it will be merged into the main repository branch `2.4-develop` and will be available in the next release version. More details about requirements and rules for issues processing can be found in these documents
- [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
- [GitHub issue processing workflow](https://devdocs.magento.com/contributor-guide/processing-workflow.html)


Due to all requirements for Issue reporting and according to the Issue processing workflow for this repository,
@engcom-Hotel took the issue in progress and tried to reproduce it.
Unfortunately, he was not able to reproduce it based on the information provided in the description.
So, he provided the [comment](https://github.com/magento/magento2/issues/34494#issuecomment-960594167) with exact "Steps to reproduce" and requested additional details. Details that could help(and required) to confirm the issue and move it to the "Ready for development" stage. Additionally, he assumed that some valuable information can be in logs and asked to check it. @engcom-Hotel does not have(and should not have) any access to your production website or codebase or environment etc.  He followed rules and verified this issue on the clean/vanilla installation. 


I hope this explanation will help to clarify the situation.

**Comment by Any-Documentation-Would-be-Great** [comment] 2021-11-11 19:38
Thanks @sdzhepa for giving me a real answer. I cannot submit a ticket still even after creating an account, but that is their problem now!

Nowhere in Magento itself is there any refence to that website for support, or that ticketing system. This is a MASSIVE failure on whoever is in charge of this design. "Report an Issue" Should link to your ticket system, not here. If this is a place for community collaboration it should not be the only link for help that exists in the entire application.

**Comment by engcom-Hotel** [comment] 2022-02-02 08:13
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-02 08:49
Hello @Any-Documentation-Would-be-Great,

We have tried to reproduce the issue in Magento's cloud instance but there also we are not able to reproduce the issue. Please have a look into below recorded video for reference:

https://user-images.githubusercontent.com/51681618/152121594-2646ae7a-4452-448a-8599-0482dfd87718.mp4

Thanks

**Comment by engcom-Hotel** [comment] 2022-02-16 01:51
Dear @Any-Documentation-Would-be-Great,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 01:51 UTC
Labels: Issue: needs update
