### ISSUE TITLE
Order status isn't fetched  label per store view  properly in GraphQL

### ISSUE THREAD

**Issue by vmalyk** [magento/magento2#33644] opened 2021-07-31 10:20 UTC
### Preconditions (*)
1. Magento 2.4.2 or higher
2. Multi store view configuration

### Steps to reproduce (*)
1. Setup order status labels per store view :
   
<img width="1278" alt="Снимок экрана 2021-07-31 в 13 13 35" src="https://user-images.githubusercontent.com/5318027/127736701-7a04f92f-5a1c-4be8-965d-b3efbcd5b178.png">

2. Request orders for logged in customer:
```
query {
     customer {
         orders {
              items {
                   status
               }
         }
     }
}
```

### Expected result (*)
1. Response contains label that specified in Admin for current store view 

### Actual result (*)
1. Status is return from default store view for website or if it's not specified - return "Status Label" value

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by vmalyk** [comment] 2021-07-31 10:21
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2021-07-31 10:59
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2021-07-31 11:36
@magento give me 2.4.2 instance

**Comment by shikhamis11** [comment] 2021-07-31 12:03
hi @vmalyk 
I tried reproducing this issue on 2.4-develop as well as 2.4.2 instances. I think it seems working fine. Let me know if it requires an additional step to reproduce this issue. 

I followed the below step 
created 2 stores and set the Order status labels differently for each store like below 

<img width="631" alt="Screenshot 2021-07-31 at 5 22 49 PM" src="https://user-images.githubusercontent.com/25526037/127739126-25cf4750-085d-4e3d-ba60-cbeb48a1207d.png">

**done the same for Processing order status.** 

and tried getting customer orders for each store 
and getting the correct order status for both stores. 

<img width="670" alt="Screenshot 2021-07-31 at 5 28 12 PM" src="https://user-images.githubusercontent.com/25526037/127739198-a38cf3e8-c523-4a08-95b0-a1f4271d73a1.png">

<img width="697" alt="Screenshot 2021-07-31 at 5 28 31 PM" src="https://user-images.githubusercontent.com/25526037/127739212-dd532db8-e5fe-4910-92b0-03636993c4a7.png">


Note: right now customer orders are being filtered at the store view level. for which a PR is already in progress https://github.com/magento/magento2/pull/33451

**Comment by engcom-Echo** [comment] 2021-08-17 14:20
@magento give me 2.4-develop instance

**Comment by engcom-Echo** [comment] 2021-08-17 14:44
Hi @vmalyk 

We tried to reproduce this issue on 2.4-develop & were unable to do so.
Here are the Steps we followed,
1. Created multiple stores and set different Order status labels for each store.
<img width="1273" alt="Screenshot 2021-08-17 at 19 58 46" src="https://user-images.githubusercontent.com/51681435/129745513-51b72fb9-2b5e-4c79-bb0e-ab70687109ba.png">
2. Placed orders from these stores through their respective customers.
3. Tried to retrieve the customer orders for each store. We are able to get the correct order status label for the respective stores.
<img width="1273" alt="Screenshot 2021-08-17 at 19 56 07" src="https://user-images.githubusercontent.com/51681435/129746389-7a6395f0-8558-4e72-8369-015c3d662fca.png">

So kindly recheck this issue on Magento 2.4-develop branch and if the issue is still reproducible, please provide more details or additional steps regarding the same.
Thank you.

**Comment by engcom-Echo** [comment] 2021-09-09 13:34
Hi @vmalyk 
Since we didn't get any updates from you & since we couldn't reproduce the issue being reported, we are closing this issue.
If this issue is still reproducible for you on magento **2.4-develop**, please feel free to reopen this issue & provide more details or additional/missing steps regarding the same.

Thank you

**Comment by engcom-November** [comment] 2021-11-18 13:47
Verified the issue on Magento 2.4-develop branch and the issue is reproducible for Store view other than default store:
Steps:
Admin - Stores - Settings - Order Status - Edit Processing status - Saved labels for multiple store views
GraphQL - Run the Query for other store view using customer having Processing Order
Issue: Empty response is returned
![image](https://user-images.githubusercontent.com/60198231/142425831-cb2ec8ab-8736-4d21-9c53-8b72d7810439.png)

Note: There is no issue for Default Store view:
![image](https://user-images.githubusercontent.com/60198231/142426788-16c82968-4bd1-44d8-93ad-d022dec35ae9.png)

**Comment by engcom-November** [comment] 2022-09-29 14:12
Hi @vmalyk ,
We verified the issue again on Magento 2.4-develop instance and the issue is not reproducible anymore. Store view specific order status labels are retrieved as expected for all stores. We are closing this issue. Kindly create new issue if you are still facing any issues.
![Uploading image.png…]()

Thank you.

**Closed as completed by engcom-November** 2022-09-29 14:12 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Area: Order
