### ISSUE TITLE
Gift options showing incorrectly in the basket Magento 2.1.2

### ISSUE THREAD

**Issue by sma09sjb** [magento/magento2#7422] opened 2016-11-14 12:38 UTC
Gift options are showing for products when they shouldn't be.

### Preconditions
1. Magento version 2.1.2

### Steps to reproduce
1. Disable gift options in the backend
![image](https://cloud.githubusercontent.com/assets/19289786/20265067/c208bc52-aa66-11e6-8381-4431709bb50c.png)

2. Disable gift options against the product
![image](https://cloud.githubusercontent.com/assets/19289786/20265072/d5d7ea6e-aa66-11e6-8cbb-a4ec93ca435c.png)

3. Seeing gift options on the frontend 
![image](https://cloud.githubusercontent.com/assets/19289786/20265086/f5e80820-aa66-11e6-8349-335d5e82b80a.png)

### Expected result
1. No gift options visible on the frontend 

### Actual result
![image](https://cloud.githubusercontent.com/assets/19289786/20265086/f5e80820-aa66-11e6-8349-335d5e82b80a.png)

**Comment by veloraven** [comment] 2016-11-16 14:42
@sma09sjb thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for help and questions answers  please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.

**Comment by sma09sjb** [comment] 2016-11-16 16:36
Updated the ticket, can this be looked at urgently please.

**Comment by SerhiyShkolyarenko** [comment] 2016-11-23 14:28
@sma09sjb I spotted custom theme on your screenshots. Is this issue reproducible for you on clean magento installation without any custom modules and themes? Is it reproducible for you on develop branch?
I tried these steps on develop branch and Magento worked fine:
![shopping_cart_without_gift_options](https://cloud.githubusercontent.com/assets/15108140/20565273/914e5b5a-b199-11e6-8df4-62ba1684cde4.png)

**Comment by AirmanAJK** [comment] 2016-12-07 20:37
This is a bug in the file "\vendor\magento\module-gift-message\view\frontend\web\js\model\gift-message.js" at Line 131:

return itemConfig.hasOwnProperty('is_available') ? itemConfig['is_available'] : isGloballyAvailable;

This logic gives priority to individual items wanting to show a gift message over the global option. It should be the other way around. Here is my proposed fix:

return isGloballyAvailable && itemConfig.hasOwnProperty('is_available') ? itemConfig['is_available'] : false;

**Comment by roseofgold** [comment] 2017-01-04 01:18
I am having the same problem.

Magento 2.1.2
Magento Blank theme

**Comment by AlexanderRakov** [comment] 2017-03-03 13:58
I run into the same issue. After quick debugging I found that for reproducing you need to complete next steps:
1. Disable gift options in Config->Sales
2. Open the product in admin
3. Open **gift options** (Autosettings section), make sure **Use Config Settings** is selected
4. Click save button.

A record with value = **2** will be added to catalog_product_entity_varchar for the produtct. **2** - is option value of **gift_message_available** attribute.
Next: if open \Magento\GiftMessage\Model\GiftMessageConfigProvider and look at 183th row, $isMessageAvailable variable will have value **2** that will be converted into bool type and then will be used in JS.
Hope this info will help to fix the issue ASAP.

**Comment by AlexanderRakov** [comment] 2017-03-03 16:12
It's fixed in 2.1.4
https://github.com/magento/magento2/commit/5f2825e01885aff4704ecb7d2049232c4dbbd4fc

**Comment by magento-engcom-team** [comment] 2017-10-11 10:30
@sma09sjb, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-11 10:30 UTC
Labels: bug report, Component: Checkout, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
