### ISSUE TITLE
"Store name" field is not escaped in Amazon Amazon_Core/js/simplepath

### ISSUE THREAD

**Issue by salgua** [magento/magento2#24112] opened 2019-08-12 13:42 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. enter in the "stores -> configuration -> general -> store name" field a string containing a single quote (')
2. go in "stores -> configuration -> sales -> payment methods" opening the chrome inspector, you will see the error in the console. The error is present after the  "Amazon_Core/js/simplepath" string.

### Expected result (*)

1. I expect to see no errors and to be able to configure payment methods

### Actual result (*)

1. the presence of this error prevents the configuration of payment systems

**Comment by engcom-Charlie** [comment] 2019-08-13 07:39
Hello @salgua 
I can't reproduce this issue on fresh Magento 2.3-develop.
So i close this issue. If you can reproduce it on 2.3-develop version please provide your steps.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-13 07:39 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Component: Backend, Component: Admin

**Comment by sudheers-kensium** [comment] 2019-08-13 08:06
Issue reproduced on Magento EE 2.3.1 not in Magento CE.

**Comment by engcom-Charlie** [comment] 2019-08-13 08:10
@sudheers-kensium ok, i will test on EE

**Comment by engcom-Charlie** [comment] 2019-08-13 08:37
@sudheers-kensium so i still cant reproduce:
1. Store name field containing a single quote (')
![image](https://user-images.githubusercontent.com/51680850/62926909-2729d680-bdbe-11e9-8453-fbec8256787a.png)
2. No any errors in console
![image](https://user-images.githubusercontent.com/51680850/62927038-69ebae80-bdbe-11e9-8db9-faab080fae9e.png)

**Comment by sudheers-kensium** [comment] 2019-08-13 08:58
@engcom-Charlie Thanks for your response. I have followed below steps.
1) I have entered Store Name like "Sudheer's" and saved
2) Go to Sales -> Payment Methods -> Enable Cash On Delivery Payment Method and click on Save config not working (Save Config button not working)

**Comment by engcom-Charlie** [comment] 2019-08-13 09:30
@sudheers-kensium i tried to reproduce follow your steps and all works fine(saved the configuration with any errors in console).

**Comment by engcom-Charlie** [comment] 2019-08-13 09:31
@sudheers-kensium please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.
