### ISSUE TITLE
Shipping address is not validated in checkout when proceeding step as logged in user with default shipping address

### ISSUE THREAD

**Issue by DanieliMi** [magento/magento2#18990] opened 2018-11-01 09:59 UTC
### Summary
The shipping address is not beeing validated (correctly?) for logged in users with addresses. If you already have customers in your shop and make changes to your address settings for your store this can lead to bad usability experience for your customers because they need to leave the checkout make change sin address book and then go back to checkout.

### Preconditions (*)

1. v.2.2.6

### Steps to reproduce (*)

1. Create a User
2. Go to My Account > Address Book
3. Add an default address (without a state)
4. In Admin Backend go to Stores > Configuration > General > State Options
5. Required State for a Country of your choice (I tested with Germany and United States)
6. With your created user put a product in your cart and proceed to checkout
7. Your created default address should be selected by default as shipping address
8. Proceed to step 2
9. Place Order

### Expected result (*)

I expected to be stopped when trying to get to step 2 (Review & Payments) due to missing region in shipping address. I expected to get prompted to add the missing region.

### Actual result (*)

It is possible to reach step 2 and press the Place Order button. Then I get the error message of the missing regionId.

**Comment by magento-engcom-team** [comment] 2018-11-01 09:59
Hi @DanieliMi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DanieliMi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by DanieliMi** [comment] 2018-11-01 10:04
I confirm i can reproduce the issue on vanilla Magento 2.2.6

**Comment by magento-engcom-team** [comment] 2018-11-01 10:38
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-01 11:20
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96059`, `MAGETWO-96060` were created

**Comment by magento-engcom-team** [comment] 2018-11-02 09:04
Hi @StasKozar. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-12-12 20:41
Hi @DanieliMi. Thank you for your report. 
The issue has been fixed in magento/magento2#19038 by @StasKozar in 2.3-develop branch
Related commit(s):
 - [43e2c4dae51a62e169eed7ae6761f565d6780692](https://github.com/magento/magento2/commit/43e2c4dae51a62e169eed7ae6761f565d6780692)
 - [b545997c49beec86291b4a28741c43d01c53c41e](https://github.com/magento/magento2/commit/b545997c49beec86291b4a28741c43d01c53c41e)
 - [66c1155ec7eb044df27435a5eb8bc20147359e72](https://github.com/magento/magento2/commit/66c1155ec7eb044df27435a5eb8bc20147359e72)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-12 20:41 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
