### ISSUE TITLE
sql error on changing scope of "category_ids" attribute (website->global) in MultiSite setup

### ISSUE THREAD

**Issue by andrewsladen** [magento/magento2#8143] opened 2017-01-15 13:02 UTC
### Preconditions
1. CentOS release 6.8 (Final)
2. kernel 2.6.32-642.13.1.el6.x86_64
3. Apache 2.4.6-5.el6
4. PHP 7.0.14
5. MySQL 5.6.35-2.el6
6. Magento CE 2.1.2
7. Magento in MultiSite configuration - several Websites, each with Single Store and StoreView

### Steps to reproduce
1. Go to edit page for category_ids attribute
2. Change Scope from Global to Website
3. Save
4. Now go back and change Scope from Website back to Global
5. Save

### Expected result
1. Attribute save is successful, scope is now Global again

### Actual result
1. Page shows following SQL Error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribute_id' in 'where clause', query was: DELETE FROM `mid_catalog_product_entity` WHERE (attribute_id = '105') AND (store_id IN 1,2,3,5)
1.1. Our table prefix is "mid_"
2. Attribute Scope is not changed - still at "Website"
3. See screenshot attached of error

![sql_error_category_id_change_scope_website_global](https://cloud.githubusercontent.com/assets/4032651/21962643/e6b03bfe-db7e-11e6-9da7-b27c71a7e9f6.PNG)

**Comment by xmav** [comment] 2017-01-26 14:48
@andrewsladen Thanks for reporting this issue. 
We've created internal ticket MAGETWO-63707 to address this issue.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:58
@andrewsladen, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:58 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Format is valid
