### ISSUE TITLE
POST /rest/V1/shipment does not change OrderItems qtyShipped

### ISSUE THREAD

**Issue by ddeppner** [magento/magento2#3799] opened 2016-03-16 04:27 UTC
## Steps to reproduce
1. Create a new shipment in the Admin screens and add items from a previously placed order to it.
2. POST to /rest/V1/shipment to create a new shipment with the items from a different order that has previously been placed.
3.  select item_id,qty_shipped from sales_order_item;
## Expected result
1.  sales_order_items qty_shipped field should show 0 for all items affected by either #1 or #2 above.
## Actual result
1. qty_shipped is 0 for shipments created in the Admin panel.
2. qty_shipped is NOT 0 for shipments created via the API

If there was an API call to allow me to manually change the qtyShipped via /V1/orders/items/{id} then I could solve this, but there are only GET options for salesOrderItemRepositoryV1.

**Comment by ddeppner** [comment] 2016-03-16 04:32
Because the qty_shipped is not updated when creating a shipment via API, the "Ship" command is still available in the Admin screens, and a user can create another shipment with the same items in it, creating future problems.

**Comment by NadiyaS** [comment] 2016-03-18 10:20
Hi @ddeppner,
thanks for reporting this issue. It is already being tracked by MAGETWO-50295 ticket.
This issue will be closed as duplicate of #3307.

**Closed as completed by NadiyaS** 2016-03-18 10:20 UTC
