### ISSUE TITLE
Products appear on page 1 also appear on page 2

### ISSUE THREAD

**Issue by phuc128t** [magento/magento2#5071] opened 2016-06-17 08:28 UTC
## Steps to reproduce
1. Install Magento 2.1rc3
2. Add for simple products and set paging at 3,9,13. Default products by grid is 3
## Expected result

Products appear on page 1 must not appear on page 2...
## Actual result

Products appear on page 1 also appear on page 2...
![page2](https://cloud.githubusercontent.com/assets/1607243/16144890/0d1f8226-34a0-11e6-9325-3e711680e9b1.jpg)
![page1](https://cloud.githubusercontent.com/assets/1607243/16144889/0d14979e-34a0-11e6-8a75-aede3a23419d.jpg)
This happens in both cases cache enable or disable

**Comment by mslabko** [comment] 2016-06-17 15:56
Hello @eric128 
I cannot reproduce it on rc3. Could you please provide detailed steps? 
Also, please can you check that product SKU on 1st page and 2nd is the same

**Comment by phuc128t** [comment] 2016-06-18 03:38
Hi mslabko,

I have 4 products (3 simples and 1 configurable). See attached.
The reproduce steps are simple. I just install 2.1rc3 and add 4 products above. And then have storefront configured as attached. All caches are enabled.

You will see issue above. I captured screens for you again.
This is a fresh version and no customization. I also see it happens on 2.0.7 and hope it fixed in 2.1.

I think products appear randomly on each page so products on page 1 can be appeared again on page 2.

Let me know if you need more information.

Page 1:
![page1_again](https://cloud.githubusercontent.com/assets/1607243/16168822/a462d37c-3540-11e6-85a8-c508238157ca.jpg)

Page2:
![page2_again](https://cloud.githubusercontent.com/assets/1607243/16168821/a45cc0d6-3540-11e6-8508-11f77c055fe7.jpg)

Backend screens:
![cahes](https://cloud.githubusercontent.com/assets/1607243/16168825/a472dd80-3540-11e6-88c4-9d779976f9de.jpg)
![4products](https://cloud.githubusercontent.com/assets/1607243/16168824/a46ec100-3540-11e6-9907-a1593361c9ba.jpg)
![storefront_setting](https://cloud.githubusercontent.com/assets/1607243/16168823/a467e95c-3540-11e6-8794-741fb4cefa9e.jpg)

**Comment by mslabko** [comment] 2016-06-21 11:01
@eric128 Thank you for clarifying. Could you provide PHP and MySQL version?

**Comment by phuc128t** [comment] 2016-06-22 02:02
Sure, see below:
srv@websrv:~$ mysql --version
mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

srv@websrv:~$ php -v
PHP 7.0.7-4+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by mslabko** [comment] 2016-06-22 07:55
It looks like issue reproduced for php7 only. Internal ticket created: MAGETWO-54602

**Comment by springerin** [comment] 2016-06-25 08:23
I have same issue even with php 
PHP 5.5.31 (cli) (built: Jan  9 2016 12:08:06) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by magento-engcom-team** [comment] 2017-10-13 11:30
@eric128, thank you for your report.
We've created internal ticket(s) MAGETWO-54602 to track progress on the issue.

**Comment by OlgaBurtyka** [comment] 2018-04-14 09:51
#kharkiv-cd

**Comment by magento-engcom-team** [comment] 2018-04-14 09:52
@OlgaBurtyka thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by maniprakash** [comment] 2018-05-19 04:34
Working on #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 04:34
@maniprakash thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by maniprakash** [comment] 2018-05-19 06:08
@eric128 Followed the steps as per your instructions. But can't reproduce this issue in the 2.2.0 version.

**Comment by magento-engcom-team** [comment] 2018-05-26 10:31
@maniprakash Thank you for research.
@eric128 Closing this ticket now, as issue does not seem to be reproducible anymore.

**Closed as completed by magento-engcom-team** 2018-05-26 10:31 UTC
Labels: Issue: Ready for Work, bug report, Progress: needs update, Issue: Clear Description, Issue: Confirmed, Issue: Format is not valid, help wanted, Event: dmcdindia
