### ISSUE TITLE
Web install - step 3- web configuration urls are always reset to default

### ISSUE THREAD

**Issue by rodrigowebjump** [magento/magento2#27592] opened 2020-04-04 19:15 UTC
### Preconditions (*)
1. Install Magento using browser

### Steps to reproduce (*)
1. Install Magento using web installation
2. On step 3 click on next step, change the Magento admin address
3. Click on next
4. Them click on back

### Expected result (*)
1. The admin address must keep the same

### Actual result (*)
1. The admin address is changed to the initial random generated value
![image](https://user-images.githubusercontent.com/635466/78459445-6f6c7080-768f-11ea-92e1-6f8aae6ee722.png)

**Comment by magento-engcom-team** [comment] 2020-04-07 09:14
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33133` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment] 2020-06-25 14:15
I'm closing this Issue because the decision already exists - https://github.com/magento/magento2/search?q=MC-33843&type=Commits

**Closed as completed by engcom-Echo** 2020-06-25 14:15 UTC
Labels: Issue: Ready for Work, Component: Setup, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Event: Global-Contribution-Day, Severity: S3, Priority: P4, Triage: Done
