### ISSUE TITLE
Product Prices are shown as zero (0,00)

### ISSUE THREAD

**Issue by mher7** [magento/magento2#33906] opened 2021-08-25 13:31 UTC
**Summary of the issue:**
Correct prices are initially loaded but then are shown as 0,00 €.
Happens on category page, product page as well as in the cart. In cart order total is also shown as 0,00 €.

**Information on your environment:**
We are running MariaDB 10.3 and PHP 7.3 for the test. I know system requirements are a little higher. But I don’t think the problem is connected to DB or PHP-Version.

**Steps to reproduce:**
I did a clean and fresh installation of magento community edition 2.4.3 via composer. 
Then created a simple product, with
- name: “TestSimple”
- price: 99 €
- Tax Class: none
- Quantity: 123
- Weight: 12
- Assign previously created category “testCategory”
- Visibility: Catalog,Search

**Expected Result:**    
Product shows price of 99 €.
![image](https://user-images.githubusercontent.com/29476734/130799530-63825b1e-7143-4287-806a-0965263a69cb.png)

**Actual Result:**
When loading the category or product page the price shows 99 € and while loading changes to 0,00 €.
![image](https://user-images.githubusercontent.com/29476734/130799437-da67c9d0-f58c-49aa-93fe-36bfb1798815.png)

**Comment by ihor-sviziev** [comment] 2021-08-25 14:26
Hi @mher7,
This is a duplicate of https://github.com/magento/magento2/issues/33798.

We weren't able to reproduce it https://github.com/magento/magento2/issues/33798#issuecomment-905464086 in the past. Maybe, you could provide some additional info to reproduce the issue?

**Closed as completed by ihor-sviziev** 2021-08-25 14:26 UTC
Labels: duplicate, Issue: ready for confirmation
