### ISSUE TITLE
Newsletter name and email wrong way around so name cannot be set

### ISSUE THREAD

**Issue by cylix99** [magento/magento2#7055] opened 2016-10-17 14:52 UTC
https://github.com/magento/magento2/blob/develop/app/code/Magento/Newsletter/Model/Queue.php#L239

getNewsletterSenderEmail and getNewsletterSenderName are the wrong way around
### Preconditions

1. 
2. 
### Steps to reproduce

1.  Send a newsletter setting email to email address and name to short name and email failed
2. 
3. 
### Expected result

1.  to fix line 239 should read
   ['name' => $this->getNewsletterSenderName(), 'email' => $this->getNewsletterSenderEmail()]
### Actual result

1. [Screenshot, logs]

**Comment by veloraven** [comment] 2016-10-18 08:12
@cylix99 thank you for your report.
Please identify which version of Magento you are running.
Please provide more detailed steps. 
Please also provide expected and actual results in format what exactly you expect to get and get actually.

**Comment by mark-aculus** [comment] 2016-10-25 20:50
I can confirm that I am having the exact same issue as @cylix99.  

I am running Magento 2.1.0

I am using one module to send emails out through SMTP.  It is possible that it has aggravated the situation, otherwise, I think newsletters wouldn't really work for anyone.  This is the custom module I am using:

https://www.magentocommerce.com/magento-connect/smtp-pro-email-free-custom-smtp-email.html

To cause the issue, I simply create a newsletter with sender name:  "Sales" and sender email:  "sales@example.com".  Next I queue up the newsletter and wait.  Eventually the UI will say the newsletter was successfully sent, but I won't see it in my inbox.

Like @cylix99 I saw the same issue in the code that he mentioned.  My work-around has been to just make sure sender name and sender email are both email addresses.  When I do this the email sends through without a problem.

I think cylix99 has the right fix.  It looks like a typo in the code to me.

**Comment by veloraven** [comment] 2017-07-06 11:03
@cylix99 , @mark-aculus this issue was fixed in develop branch by commit 9b7dd77e2b0534479cb35060ad14908f1aed1116 from PR #6354

**Comment by korostii** [comment] 2017-07-06 11:23
Hi @veloraven, I see that you've added a needs update label.
Would you please care to explain, what exact kind of information do you need from community in order to proceed with backporting an existing fix to the 2.1.x branch?

**Comment by magento-engcom-team** [comment] 2017-09-13 21:41
The issue has been fixed and will be available with next minor release
@korostii it would be great if you can create a Pull Request to 2.1-develop branch with a backport. Please join Magento Community Contribution Team. You did a great job 👍  on review and commenting issues and pull requests, but we are looking for your own pull requests!

**Comment by korostii** [comment] 2017-09-14 08:11
Hi @magento-engcom-team , 

Thanks a lot for your words of encouragement, I really appreciate it.
I hope eventually I'll get to PRing, as well :) 
Unfortunately, I only have so many hours in a day. Thus I have to prioritize, just like everybody else.

Keep up the good job & have a nice day!

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@cylix99, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-26 22:00 UTC
Labels: bug report, Component: Sales, Issue: Clear Description, Fixed in 2.3.x, Issue: Format is valid
