### ISSUE TITLE
Missing "Customer Group Price" label when adding new customer group price rule

### ISSUE THREAD

**Issue by edenduong** [magento/magento2#24640] opened 2019-09-18 10:23 UTC
### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Create New Product form
3. Click "Advanced Pricing"
4. In "Customer Group Price", click "Add"
=> label "Customer Group Price" suddenly disappear.

### Expected result (*)

![image](https://user-images.githubusercontent.com/8234209/65140544-fda54000-da38-11e9-84b6-546b2a3ab694.png)

### Actual result (*)

![image](https://user-images.githubusercontent.com/8234209/65140567-08f86b80-da39-11e9-8e4b-abaacb6f6115.png)

**Comment by magento-engcom-team** [comment] 2019-09-18 10:26
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20226` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by drpayyne** [comment] 2020-02-02 06:20
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-02 06:21
Hi @drpayyne. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-02 06:21
Hi @drpayyne, here is your [Magento instance](https://i-24640-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-24640-2-4-develop.instances.magento-community.engineering/admin_48cf](https://i-24640-2-4-develop.instances.magento-community.engineering/admin_48cf)
Login: `4c8c7575` Password: `e2f7fc9e4895`
Instance will be terminated in up to 3 hours.

**Comment by drpayyne** [comment] 2020-02-02 06:27
Issue seems to be fixed in `2.4-develop` and is not reproducible. Closing.

**Closed as completed by drpayyne** 2020-02-02 06:27 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Pricing
