### ISSUE TITLE
Make FreeShipping Rules more obvious in admin

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#33970] opened 2021-09-02 00:33 UTC
### Summary (*)

Better understanding on how to create free shipping promotions.

### Examples (*)

We need to apply shipping costs to checkout and have an idea how taxes are applied to these shipping rates, and at the same time create a promotion involving it but it is not so obvious how to create it in admin. 

So in order to do so, we have to get the shipping costs to cart and give 100% discount for this costs. Only enable freeshipping and apply settings to methods that allows it is not enough. If we use table rates and we want give 100% discount, we have to create a cart rule. But how to create it in marketing > cart rule is not obvious. 

Create a cart rule. Leave conditions empty. 
In Actions "Give percent of price discount"

Translation should consider in option "Give percent of price or shipping discount"
"Apply to Shipping Amount" should be translated (just as an example) - "Apply only to shipping amount or products declared in conditions bellow"

"Discount amount is applied to subtotal and shipping amount separately","Discount is applied to subtotal and shipping amount separately. If you want to create a rule to apply only to shipping, please, declare bellow a condition where products prices are equal 0"

### Proposed solution
Change Label Strings or create translation files considering step by step on how to do it. And update documentation until further improvements in usability. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by gcampedelli** [comment] 2021-09-15 13:35
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2021-09-17 05:21
Hi @gcampedelli,

Since this is not an issue related to Magento Dev, we are closing this. Please raise a fresh ticket or reopen this ticket if you think the issue is related to Magento Development with updated **Issue Description** and **'Steps to reproduce'**.

Regards

**Closed as completed by engcom-Lima** 2021-09-17 05:21 UTC
Labels: Triage: Dev.Experience, Issue: needs update
