### ISSUE TITLE
REST API - mine cart select shipping address

### ISSUE THREAD

**Issue by RUjmiak** [magento/magento2#5180] opened 2016-06-23 10:37 UTC
## Steps to reproduce
1. create mine cart
2. add product to carts
3. select billing address for mine cart (POST /V1/carts/mine/billing-address)
## Expected result
1. API call for select shipping address the same as Billing Address. There is few api calls which are not working as we expected

GET /V1/carts/mine/shipping-methods
response: "message": "Shipping address not set."

I know that there is POST /V1/carts/mine/shipping-information but there I need to send shipping address and shipping method...

So question: Is it possible to select shipping address to mine cart?

Thx

**Comment by veloraven** [comment] 2016-06-23 14:22
@RUjmiak , please provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.
Please specify API calls "which are not working as we expected", expected and actual results for them, so that we can check the problem and fix it.
If you only need an answer to your question, please refer to the Community Forums or Magento Stack Exchange for technical questions.

**Comment by RUjmiak** [comment] 2016-06-23 15:37
@veloraven Sorry

Version: Magento 2.0.5

GET Customers/me

{
    "id": 4,
    "group_id": 1,
    "default_billing": "5",
    "default_shipping": "5",
    "created_at": "2016-06-10 09:19:18",
    "updated_at": "2016-06-22 15:40:21",
    "created_in": "Default Store View",
    "email": "test3@gmail.com",
    "firstname": "Rastislav",
    "lastname": "Ujmiak",
    "gender": 1,
    "store_id": 1,
    "website_id": 1,
    "addresses": [
        {
            "id": 5,
            "customer_id": 4,
            "region": {
                "region_code": null,
                "region": null,
                "region_id": 0
            },
            "region_id": 0,
            "country_id": "SK",
            "street": [
                "test 10"
            ],
            "company": "test technology",
            "telephone": "1234567890",
            "postcode": "91790",
            "city": "City Ten",
            "firstname": "Rasto",
            "lastname": "test",
            "default_shipping": true,
            "default_billing": true
        }
    ],
    "disable_auto_group_change": 0
}

**POST /V1/carts/mine/shipping-information**
with data
{
  "addressInformation": {
    "shippingAddress": {
      "customerAddressId": 5
    },
    "shippingMethodCode": "string",
    "shippingCarrierCode": "string"
  }
}

response
{
    "message": "Invalid address id %1",
    "parameters": [
        5
    ]
}

**Comment by SerhiyShkolyarenko** [comment] 2016-09-15 12:17
Hi @RUjmiak!
About your first comment: we realized, that `"useForShipping": true` is ignored by `/V1/carts/mine/billing-address` service on POST request. Corresponding internal issue is MAGETWO-58269. It was reported in #6557.
Your second comment seems to describe another flow. Could you please describe it in a step-by-step manner?

**Comment by SerhiyShkolyarenko** [comment] 2016-09-30 09:34
As far as second part is not confirmed for 15 days we are closing this issue as duplicate of #6557. Please feel free to create a new issue for that part if it is reproducible still.

**Closed as completed by SerhiyShkolyarenko** 2016-09-30 09:34 UTC
Labels: bug report, Component: Framework/Webapi, Component: Checkout

**Comment by mygovernance** [comment] 2018-04-16 05:58
{"message":"Invalid address id %1","parameters":[84]}
issue is coming while posting shipping information to cart
