### ISSUE TITLE
The js error when swipe gallery images on the product page (touch events)

### ISSUE THREAD

**Issue by glevhen** [magento/magento2#34282] opened 2021-10-08 11:01 UTC
Magento 2.4.3
Open product page in chrome browser and swipe product images in the gallery
make sure you swiping via touch event (you can use chrome mobile device emulation or real devices for this)
Swiping product images cause js errors
`fotorama.js:1222 Unable to preventDefault inside passive event listener invocation.`
![image](https://user-images.githubusercontent.com/16398798/136543911-f8d02ed5-82ee-4dff-ab1f-74a93cac7152.png)

the issue caused by this commit https://github.com/magento/magento2/commit/2f5b57a0c0e20e47068e6e9552a85b4e6c28f0a2#diff-c4a96bcd0b56dc98fdc1c5af6c8a86d6560587bbc80caabe9b3ccabd047675d0

because fotorama call `e.preventDefault` 
https://github.com/magento/magento2/blob/2.4-develop/lib/web/fotorama/fotorama.js#L1222
inside of passive event listener
https://github.com/magento/magento2/blob/2.4-develop/lib/web/fotorama/fotorama.js#L1143

**Comment by glevhen** [comment] 2021-10-08 15:42
https://github.com/magento/magento2/pull/34162
https://github.com/magento/magento2/pull/34162/commits/3eda0c8ba176a25e15bae7444b1698c69987fee4

**Comment by mrtuvn** [comment] 2022-06-12 05:10
https://github.com/magento/magento2/pull/35017
Seem this update may fit with your case

**Comment by mrtuvn** [comment] 2023-05-18 00:09
Can you verify with latest code upstream 2.4-develop ?
Thanks

**Comment by engcom-Hotel** [comment] 2024-10-07 07:52
Hello @glevhen,

We have tried to reproduce the issue in the latest 2.4-develop branch and the issue is no more reproducible for us.

Hence closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2024-10-07 07:52 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Component: Image, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.3, Area: Content
