### ISSUE TITLE
Static Content deploy parallel jobs (--jobs) not working in PHP docker images

### ISSUE THREAD

**Issue by sinamiandashti** [magento/magento2#24628] opened 2019-09-17 09:33 UTC
### Summary (*)
If you use official php-fpm docker image (php:7.1-fpm) for your magento store , the parallel deploying of static content is not working ... i dont know what is causing this or what extension or configure build of php is needed for this functionality.

### Examples (*)
`php bin/magento setup:static-content:deploy --jobs=8 -f en_US de_DE`

### Proposed solution
I have no idea , i was trying to check if its related to pthread php extension , but I found that it removed from php 7.1 and upper.

**Comment by hostep** [comment] 2019-09-17 18:20
Hi @sinamiandashti 

Do the following threads help you?
- https://github.com/magento/magento2/pull/22607 (fix coming in Magento 2.3.3)
- https://github.com/magento/magento2/pull/22886 (fix coming in Magento 2.3.4)

If not: can you clearly explain what "is not working" means exactly? Do you see errors? Does it just stop? Are files being generated?

**Comment by sinamiandashti** [comment] 2019-09-17 20:41
no,
Actually in normal  server with php 7.1 cli or even in Valet server's php cli  if you use --jobs=4 for example it works and static content deployed in 4 parallel jobs - but when you do the same in a DockerFile ... with using php:7.1-fpm image ... if use --jobs=4 or any number it not works and only deploy in 1 single job , no parallel jobs . some how the flag is bypassed .

**Comment by hostep** [comment] 2019-09-18 07:02
Ah, so that means you are missing the `pcntl` php extension. If you install that one in your docker container it should start working again.

**Comment by sinamiandashti** [comment] 2019-09-18 11:23
Fixed with installing the pcntl extension

Can i create a pull request for this document page ? https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-static-view.html

that people should have pcntl installed for using this feature @hostep

**Comment by hostep** [comment] 2019-09-18 13:55
@sinamiandashti: very good idea to update the documentation with missing info regarding the `pcntl` extension! You can create a pull request at https://github.com/magento/devdocs/

Let us close this issue, since it's not a bug in Magento itself.

Thanks again!

**Closed as completed by hostep** 2019-09-18 13:55 UTC
Labels: Issue: Format is valid
