### ISSUE TITLE
Coupon "Fixed amount discount for whole cart" apply for bundle product not working well

### ISSUE THREAD

**Issue by doanhpv-0200** [magento/magento2#36249] opened 2022-10-06 06:27 UTC
### Preconditions and environment

- Magento version: 2.4.4
- Coupon for rule `Fixed amount discount for whole cart` not working well for bundle product

### Steps to reproduce

1. Create 2 bundles item with 2 (or more product) with price is $500 and $1000 (2 bundles with same items but order is difference)
2. Create 1 coupon with rule `Fixed amount discount for whole cart` with discount is between price of 2 product above (eg: $700)
3. Add bundle to cart
4. To to checkout page
5. Apply coupon
    5.1. Bundle 1: $1000 - $500 total discount is $700
    5.2. Bundle 2: $500 - $1000 total discount is $1200 (_$500 + $700_)

### Expected result

5. Apply coupon
    5.1. Bundle 1: $1000 - $500 total discount is $700
    5.2. Bundle 2: $500 - $1000 total discount is $700

### Actual result

5. Apply coupon
    5.1. Bundle 1: $1000 - $500 total discount is $700
    5.2. Bundle 2: $500 - $1000 total discount is $1200

### Additional information

I found problem is  when it use `$ruleDiscount` instead of `$availableDiscountAmount` https://github.com/magento/magento2/blob/eb1e3a0c9bb2cd740e21726808061e6cf6a95982/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php#L121-L140

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-06 12:41
Hi @doanhpv-0200 ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance but unable to reproduce the issue. Please find the steps performed below:
**Steps performed:**
1. Created Bundle product with 2 Bundle options (Ship Bundle Items - Separately)
![image](https://user-images.githubusercontent.com/60198231/194314037-d0f2175c-6508-492d-b0ce-066a5413205a.png)
2. Created cart price rule : Fixed amount discount for whole cart - 700
3. Front end - Selected 2 Bundle options for the product and added to cart
4. Proceed to checkout
5. Applied coupon
**No issue:** $700 discount is applied on the whole cart.
![image](https://user-images.githubusercontent.com/60198231/194314405-3fa1b5df-92ac-4e9f-8089-93016ebd93ca.png)
Also, as per Magento [devdocs](https://docs.magento.com/user-guide/v2.3/marketing/price-rules-cart-create.html), Fixed amount discount for whole cart represents "Discounts the entire cart by subtracting a fixed amount from the cart total"
Can you please recheck the behavior on Magento 2.4-develop instance and elaborate/ provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-19 12:41
Hi @doanhpv-0200 ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-19 12:41 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.4
