### ISSUE TITLE
Cannot create credit memo in 2.4.3 - Error: Please enter positive number in this field

### ISSUE THREAD

**Issue by caricell** [magento/magento2#34182] opened 2021-09-28 16:28 UTC
### Preconditions (*)

1. 2.4.3
2.

### Steps to reproduce (*)

1. SALES>ORDERS>GO TO ANY ORDER>SELECT INVOICES FROM THE LEFT COLUMN>OPEN THE INVOICE> CREDIT MEMO> REFUND OFFLINE OR >REFUND
**2.**

### Expected result (*)

1. Credit memo should create and send appropriate notifications, update available stock, etc.
2.

### Actual result (*)

1. "Please enter positive number in this field" appears in all enterable fields. Changing the amounts to any number does not remove the error. This appears to be occurring because Magento has now inserted the currency TYPE figure into these fields, (such as "$" ) and the system does not see this as a positive number, so it fails validation.
2.

---
![screen1](https://user-images.githubusercontent.com/78441828/135127739-78a6937d-747a-43a2-99f2-678fa0abc6dc.jpg)

Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

[x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by caricell** [comment] 2021-09-28 16:31
Note: This is in a Magento multi-store environment

**Comment by engcom-November** [comment] 2021-09-29 07:52
Verified the issue on Magento 2.4-develop branch having multi store setup but the issue is not reproducible on all the stores.
Steps performed:
Front-end - Add product to cart - Proceed to checkout - Submit payment using Paypal Express Checkout
Admin - Sales - Orders - View Order - Create Invoice
Credit Memo generated with decimal values - **No issue**
![image](https://user-images.githubusercontent.com/60198231/135226119-63917b55-9887-47e9-b13b-d4f0d6b97b3d.png)

![image](https://user-images.githubusercontent.com/60198231/135225940-9c7124ab-c2b1-4c1d-a3b0-775081e172e8.png)
@caricell , kindly recheck the issue on Magento 2.4-develop branch as it has the latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by caricell** [comment] 2021-09-29 12:58
Hello and thank you for looking into this issue. While I do not have the 2.4-develop branch, I did reconfirm that this issue is occurring on BOTH stores of my two-store multi-store setup. If you were able to reproduce it on some, but not all, stores, then there must be some issue there, correct?

**Comment by caricell** [comment] 2021-10-01 14:56
I have resolved this issue by going to STORES>CURRENCY SYMBOLS in Admin, UNCHECKED the "use standard" box and entered the "$" manually. Then SAVED the page, and refreshed cache as requested, and VOILA... I can now create credit memos successfully. See attached for where to apply this fix.
![credit memo fix](https://user-images.githubusercontent.com/78441828/135641733-596c4498-56fb-47ea-87bd-b8bd47166fbf.jpg)
.

**Comment by engcom-November** [comment] 2021-10-04 12:10
Hi @caricell 

Verified the issue again after upgrading from 2.4.2-P1 to 2.4.3 but unable to reproduce this issue

**Steps performed:**
Upgraded 2.4.2-P1 having multi store setup to 2.4.3
Login to Admin - Sales - Orders - View Processing Order - Invoices - Credit Memo - Refund Offline with decimal values - **No issue. Refunded successfully.**
Login to Admin - Sales - Orders - View Pending Order (Purchased from other store) - Create Invoice - Credit Memo - Refund Offline with decimal values - **No issue.**
![image](https://user-images.githubusercontent.com/60198231/135849009-26ac2060-6264-411b-8066-2420ca354df0.png)

**Comment by caricell** [comment] 2021-10-04 23:45
Please see above for the workaround I used to clear up the issue. A smple re-saving of the STORES>Currency setting in admin resolved the issue. I cannot determine what caused the problem initially.

**Comment by sohelrana09** [comment] 2021-10-12 11:30
This is still an issue with 2.4.3-p1 for multi-store setup.

**Comment by hoanglan87** [comment] 2021-10-12 13:32
Hi everyone, seem this patch https://github.com/magento/magento2/issues/33856#issuecomment-904606945 fixed the problem for us, please try it to see if it works for you.

**Comment by ihor-sviziev** [comment] 2021-10-18 06:16
As it was confirmed, the issue has been fixed in https://github.com/magento/magento2/commit/ae304d43cd36322b1ff8145d70c9b2e9aeb0cde. This commit wasn't included to any release yet, so for now you can apply it as a patch

**Closed as completed** 2021-10-18 06:15 UTC
Labels: Component: Payment, Fixed in 2.4.x, Issue: needs update, Reported on 2.4.3, Area: Payments

**Comment by dylanngo95** [comment] 2022-08-03 08:33
These issues still on M 2.4.4 EE with PHP 7.4.28
Thanks.

**Comment by pmonosolo** [comment] 2022-09-27 16:54
I have an override for Currency.php from 2.4.3 days, and when upgrading to 2.4.5 the override fixes the issue.

**Comment by dbashyal** [comment] 2023-01-05 06:14
> I was able to work around this issue by going to STORES>CURRENCY SYMBOLS in Admin, UNCHECKED the "use standard" box and entered the "$" manually. Then SAVED the page, and refreshed cache as requested, and VOILA... I can now create credit memos successfully. See attached for where to apply this fix. ![credit memo fix](https://user-images.githubusercontent.com/78441828/135641733-596c4498-56fb-47ea-87bd-b8bd47166fbf.jpg) .

This seems to have solved the issue in Magento 2.4.3-p3 as well.

**Comment by Darkwolf81** [comment] 2023-03-01 13:20
@dbashyal @caricell 
Did you get it to work, when default currency symbol is the same you enter?
My default is €, when i unckeck "use default" and enter the €symbol, it checks the "use default" again. Only when its different, it stays unchecked.
If i enter sonethong other, clean cache and check the creditmemo, it shows the € symbol. Maybe this only works for new orders?
