### ISSUE TITLE
Magento 2.4.2 to 2.4.3 Upgrade Issue use php 8 function

### ISSUE THREAD

**Issue by magedevel** [magento/magento2#33755] opened 2021-08-11 15:56 UTC
### Preconditions (*)

1. Try to upgrade from version 2.4.2-p1 to 2.4.3
2. MSI modules are disabled using a replace on composer.

### Steps to reproduce (*)
1. execute: composer require magento/product-community-edition=2.4.3 --no-update
3. execute : composer update

### Expected result (*)

1. Magento was updated to version 2.4.3

### Actual result (*)

1. Has got an error : 
`Fatal error: Uncaught Error: Call to undefined function Magento\Framework\Filesystem\Directory\str_contains() in /var/www/html/vendor/magento/framework/Filesystem/Directory/DenyListPathValidator.php:74
`
 Class \Magento\Framework\Filesystem\Directory\DenyListPathValidator use a PHP 8.0 function. (str_contains)

```
....
foreach ($this->fileDenyList as $file) {
            $baseName = pathinfo($actualPath, PATHINFO_BASENAME);
            if (str_contains($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
                throw new ValidatorException(
                    new Phrase('"%1" is not a valid file path', [$path])
                );
            }
        }
```
### Notes
Based on requirement this version should work on PHP 7.4
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

And in the release note (https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html) you wrote:
Magento 2.4.3 is not yet compatible with PHP 8.x, but the following platform upgrades bring us closer to future compatibility with  PHP 8.x.

**Comment by hostep** [comment] 2021-08-11 18:20
Is a duplicate of https://github.com/magento/magento2/issues/33680, hopefully [this comment](https://github.com/magento/magento2/issues/33680#issuecomment-894580187) can help you further

**Comment by magedevel** [comment] 2021-08-12 07:36
I can confirm that the work around works.

**Comment by ihor-sviziev** [comment] 2021-08-12 08:22
Hi @magedevel,
I'm closing this issue as duplicate of https://github.com/magento/magento2/issues/33680

**Closed as completed by ihor-sviziev** 2021-08-12 08:22 UTC
Labels: duplicate, Fixed in 2.4.x, Issue: ready for confirmation, Reported on 2.4.3
