### ISSUE TITLE
Sales / Order grid - Status Column

### ISSUE THREAD

**Issue by fabotha** [magento/magento2#39270] opened 2024-10-17 08:47 UTC
### Preconditions and environment

- Magento version 2.4.7

### Steps to reproduce

View the sales / order / grid
Add a column to view called status
The contents of this column is actually the order state

### Expected result

For a heading of status you would expect to see the status of the order

### Actual result

Status column shows the state of the order

### Additional information

Please fix and also include the state and status of the order on the sales / order grid

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-10-18 05:12
Hi @fabotha,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


<img width="1333" alt="Screenshot 2024-10-18 at 10 26 15" src="https://github.com/user-attachments/assets/ea88704f-7000-4050-9ef6-4a707e088c27">



<img width="1333" alt="Screenshot 2024-10-18 at 10 27 49" src="https://github.com/user-attachments/assets/e8f23881-a8f1-4c3c-bf19-0bb46d1b4ba8">


The column status showing status of the order only.

Kindly recheck the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by fabotha** [comment] 2024-10-18 06:57
Hi
Sorry this was raised in error.

Please close

Thanks
Frank




Please note we have a new email address
***@***.******@***.***>

We ship Airsoft products all over the world.
Tax free (20% off) at checkout to all countries.

Marui recoil Specials - repairs, upgrade, lipo conversion and custom work

Latest products - www.fire-support.co.uk/latest_products.php<http://www.fire-support.co.uk/latest_products.php>

OPEN 4 Days a week, Tue - friday 9am - 5.30pm
Alternate Saturdays 10-5
see https://www.fire-support.co.uk/openingtimes.php
Please always reply with our email in yours so we can track the conversation.

Frank - Director
Tel 01733 247171

**Comment by engcom-Bravo** [comment] 2024-10-21 03:47
Hi @fabotha,

Thanks for your update.

We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-21 03:47 UTC
Labels: Issue: needs update, Reported on 2.4.7
