### ISSUE TITLE
Percent of product price discount not working with exclude sku condition

### ISSUE THREAD

**Issue by ravi-chandra3197** [magento/magento2#36528] opened 2022-11-24 11:48 UTC
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1. Set SKU attribute 'use for promo rule conditions' true.
2. Add coupon code test with exclude product by SKU
3. Add few product in cart and apploy coupon code

### Expected result

Discount should apply for all product except exclude product using sku condition.

### Actual result

Discount apply in all product without excluding product mention rule

### Additional information

Here is ref. snapshot for the same.
![test10-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/43946827/203777216-244f160c-e433-4966-9405-66150d453fc3.png)
![Joust-Duffle-Bag](https://user-images.githubusercontent.com/43946827/203777222-6358fcee-ce5a-4550-bdf8-24dba8c5a1e3.png)
![Shopping-Cart](https://user-images.githubusercontent.com/43946827/203777225-5607497b-2c8a-4c07-9b60-60c1f384727a.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-11-24 14:01
Hi @ravi-chandra3197,


Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

1.Set SKU attribute 'use for promo rule conditions' true.
2.Add coupon code test with exclude product by SKU
3.Add few product in cart and apploy coupon code


![Test-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/203802514-4139ee11-e15a-4ca8-afaa-f7634079066c.png)



<img width="1405" alt="Screenshot 2022-11-24 at 5 51 05 PM" src="https://user-images.githubusercontent.com/51680745/203802581-c2062317-debf-4958-a219-83e4b7bc0c8e.png">



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by ravi-chandra3197** [comment] 2022-11-28 05:31
Hello @engcom-Bravo 
Can you add few other product and then apply coupon code.
Actual result discount should apply other product exclude mention product, but discount apply in all product.
![Joust-Duffle-Bag](https://user-images.githubusercontent.com/43946827/204201160-19ab10f4-a14a-4e2e-9fbb-e3cc3614ce55.png)
![Shopping-Cart](https://user-images.githubusercontent.com/43946827/204201161-b081a13d-be69-40c2-871b-ee97c768e6c7.png)

![test10-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/43946827/204201150-9e7b7eb5-976a-418f-baf7-014b5c4c1fc0.png)

**Comment by engcom-Bravo** [comment] 2022-11-30 05:47
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-30 09:13
Hi @ravi-chandra3197,

Thanks for your Update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Set SKU attribute 'use for promo rule conditions' true.
2.Add coupon code test with exclude product by SKU
3.Add few product in cart and apply coupon code.

`Cart Price Rule`

![Add-Promotions-Marketing-Magento-Admin](https://user-images.githubusercontent.com/51680745/204753985-43e2ea8a-6001-4183-8fa3-95bd48eb1b42.png)


It is working fine when single product in a cart as per Cart Price Rule.


<img width="1465" alt="Screenshot 2022-11-30 at 2 31 18 PM" src="https://user-images.githubusercontent.com/51680745/204754226-395814d8-5130-45d4-b509-81c43e44e6c5.png">





When we have multiple products in a cart.it is not working as per Cart price rule.in cart price rule we have given a condition it is not applicable for `SKU SIMPLE` but it is applying.



![Shopping-Cart](https://user-images.githubusercontent.com/51680745/204754382-f58ce9b7-25a9-49a4-8ee4-039983c4a49b.png)




Hence confirming this issue.

Thanks.

**Comment by Kannakiraj123** [comment] 2022-12-13 06:22
@magento I am working on this

**Comment by Kannakiraj123** [comment] 2022-12-13 11:08
@magento give me 2.4-develop instance

**Comment by Kannakiraj123** [comment] 2022-12-16 06:09
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-04-18 13:00
Hi @ravi-chandra3197,

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Set SKU attribute 'use for promo rule conditions' true.
- Add coupon code test with exclude product by SKU
- Add few product in cart and apply coupon code




<img width="1334" alt="Screenshot 2023-04-18 at 2 38 48 PM" src="https://user-images.githubusercontent.com/51680745/232732005-76be6ad3-02b3-499f-8f47-932f88c39181.png">



<img width="1379" alt="Screenshot 2023-04-18 at 2 38 36 PM" src="https://user-images.githubusercontent.com/51680745/232732104-12064a31-9e1e-4099-aaa8-b0ec3e1309fc.png">



Product with Sku Mobile is excluded and discount is applying for other product.

"Conditions section serves to specify conditions that will be applied to whole cart.
If you want to apply conditions for a certain products you need to set them in Actions tab under "Apply the rule only to cart items matching the following conditions (leave blank for all items)"


Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/cart-rules/price-rules-cart-create.html?lang=en#step-2%3A-describe-the-conditions.



<img width="918" alt="Screenshot 2023-04-18 at 2 48 22 PM" src="https://user-images.githubusercontent.com/51680745/232732706-00529a4a-4593-4050-b93c-805f09c298b9.png">



Kindly let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-04 06:05
Hi @ravi-chandra3197,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-04 06:05 UTC
Labels: Component: Rule, Priority: P1, Progress: done, Issue: needs update, Area: Product, Reported on 2.4.5
