### ISSUE TITLE
Menu widget submenu alignment

### ISSUE THREAD

**Issue by slackerzz** [magento/magento2#7897] opened 2016-12-20 11:18 UTC
### Preconditions
1. Magento 2.0.x, 2.1.x

### Steps to reproduce

1. hover a menu item which contains some nested elements

### Expected result

1. the submenu relative to the "Bottoms 2" element in the image should be aligned next to it

### Actual result

![menu](https://cloud.githubusercontent.com/assets/3061752/21348284/a241f354-c6ac-11e6-839a-48c5accde3da.jpg)
If you move your mouse slowly you'll never be able to click any of the submenu items

The js from the widget calculates coordinates for the submenu:
![coords](https://cloud.githubusercontent.com/assets/3061752/21348362/13cbc554-c6ad-11e6-8312-4dee2ce75670.png)

but then we have this LESS
https://github.com/magento/magento2/blob/develop/lib/web/css/source/lib/_navigation.less#L403

Simply removing the to ```!important``` rules does not fix the problem, there is something wrong also in the coords calculated via js

Since this widget is based on https://jqueryui.com/menu/ that works as expected i think that something went wrong and someone tried to fix it with an  ```!important``` to overwrite an inline style added via js

**Comment by AlexWorking** [comment] 2017-06-21 11:11
Hi @slackerzz. An internal ticket MAGETWO-70053 has been created  based on Your issue. You'll be immediately notified after the issue is resolved. Thank You for appliance.

**Comment by magento-engcom-team** [comment] 2017-10-03 10:30
@slackerzz, thank you for your report.
We've created internal ticket(s) MAGETWO-80700 to track progress on the issue.

**Comment by Abdulrahimbadiyal** [comment] 2018-05-19 11:02
I'm working on it #15176

**Comment by Abdulrahimbadiyal** [comment] 2018-05-19 11:03
I'm working on it #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 11:03
@Abdulrahimbadiyal thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by hitesh-wagento** [comment] 2018-06-01 05:33
I am working on this

**Comment by magento-engcom-team** [comment] 2018-06-02 12:58
Hi @slackerzz. Thank you for your report. 
The issue has been fixed in magento/magento2#15645 by @hitesh-wagento in 2.2-develop branch
Related commit(s):
 - [2694906a296fb94049dd348ffb3636e6f30370e2](https://github.com/magento/magento2/commit/2694906a296fb94049dd348ffb3636e6f30370e2)

The fix will be available with the upcoming 2.2.6 release.

**Closed as completed by magento-engcom-team** 2018-06-02 12:58 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, triage wanted

**Comment by sidolov** [comment] 2018-06-04 08:06
Hi @slackerzz. Thank you for your report. 
The issue has been fixed in magento/magento2#15714 by @dmytro-ch in 2.1-develop branch
Related commit(s):
 - [57fed5a09f515904a87f71b01e146c90c0ec2123](https://github.com/magento/magento2/commit/57fed5a09f515904a87f71b01e146c90c0ec2123)

The fix will be available with the upcoming 2.1.15 release.

**Comment by sidolov** [comment] 2018-06-05 07:29
Hi @slackerzz. Thank you for your report. 
The issue has been fixed in magento/magento2#15764 by @hitesh-wagento in 2.3-develop branch
Related commit(s):
 - [ecc5f7b4ae8c43f588710bb6bc7c6183ccaf2538](https://github.com/magento/magento2/commit/ecc5f7b4ae8c43f588710bb6bc7c6183ccaf2538)

The fix will be available with the upcoming 2.3.0 release.

**Comment by sidolov** [comment] 2018-06-05 07:30
Hi @slackerzz. Thank you for your report. 
The issue has been fixed in magento/magento2#15709 by @dmytro-ch in 2.3-develop branch
Related commit(s):
 - [14bf8af3db1683cbf4aeb5ca5924d8fd119e6d5a](https://github.com/magento/magento2/commit/14bf8af3db1683cbf4aeb5ca5924d8fd119e6d5a)

The fix will be available with the upcoming 2.3.0 release.
