### ISSUE TITLE
MAGETWO-96957 introduce a new bug

### ISSUE THREAD

**Issue by thomas-kl1** [magento/magento2#23451] opened 2019-06-27 15:34 UTC
### Preconditions (*)

- Magento 2.2.9
- or apply this commit: https://github.com/magento/magento2/commit/bd3fcb00f44def21b6d45b2908dd33e7d75efa3a

### Steps to reproduce (*)

1. Implement new grid `Magento\Backend\Block\Widget\Grid` (I know it's deprecated)
2. The gris MUST use an EAV collection type
3. Add following massaction block: `Magento\Backend\Block\Widget\Grid\Massaction`

### Expected result (*)

1. Everything is working well

### Actual result (*)

1. 1 exception(s):
Exception #0 (Zend_Db_Select_Exception): No table has been specified for the FROM clause

**Comment by engcom-Foxtrot** [comment] 2019-07-24 12:02
@thomas-kl1, thank you for collaboration. Can you please provide strong motivation why this PR should be merged? It works fine with Product collection, but it's only because of [\Magento\Catalog\Model\ResourceModel\Product\Collection::MAIN_TABLE_ALIAS value](https://github.com/magento/magento2/blob/7ffabd074c457edb7a3f2d8eacbc21a1dd188692/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L48). I'm not sure if your solution will work in other cases.

**Comment by magento-engcom-team** [comment] 2019-07-26 17:23
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18686` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-10-08 19:15
Hi @thomas-kl1. Thank you for your report. 
The issue has been fixed in magento/magento2#23452 by @thomas-kl1 in 2.3-develop branch
Related commit(s):
 - [81a542b7ed6fc9db6715475f047906767d06775c](https://github.com/magento/magento2/commit/81a542b7ed6fc9db6715475f047906767d06775c)
 - [f15b76fcf0342b2b320037b5f913ba274f4f3d6d](https://github.com/magento/magento2/commit/f15b76fcf0342b2b320037b5f913ba274f4f3d6d)
 - [a6cec0ae32858439c2812ca32e4711be44e7a8a2](https://github.com/magento/magento2/commit/a6cec0ae32858439c2812ca32e4711be44e7a8a2)
 - [ab04d7e7a79aa2ac15075243cc450a38baea3f74](https://github.com/magento/magento2/commit/ab04d7e7a79aa2ac15075243cc450a38baea3f74)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-08 19:15 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Backend
