### ISSUE TITLE
New theme does not show in "Stores > Configuration > Design

### ISSUE THREAD

**Issue by mitul69** [magento/magento2#5856] opened 2016-07-28 09:46 UTC
Desing page show me the Search Engine Robots  instead of the design settings
![admin-desgin-option](https://cloud.githubusercontent.com/assets/612252/17208409/3ee94426-54d6-11e6-8fb6-25fc234ddb5b.png)

**Comment by quienti** [comment] 2016-07-28 11:23
Not a bug, read here => https://github.com/magento/magento2/issues/5307

**Comment by andimov** [comment] 2016-07-29 10:45
@mitul69 
Thank you for reporting!
@quienti 
Thank you for the assistance!

This is a duplicate of closed issue. I'm closing this one too.

**Closed as completed by andimov** 2016-07-29 10:45 UTC
