### ISSUE TITLE
Fedex domestic shipping for Poland not working

### ISSUE THREAD

**Issue by MajorKuprich** [magento/magento2#35175] opened 2022-03-10 10:42 UTC
### Steps to reproduce (*)

1. Configure Fedex in Magento 2.4.3.

### Expected result (*)

1. Fedex shipping methods displayed in checkout.

### Actual result (*)

1. Fedex shipping methods not displayed in checkout.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-03-10 12:49
@magento give me 2.4-develop instance

**Comment by MajorKuprich** [comment] 2022-03-14 10:40
@engcom-November hello, how are You

Could I get any information about reproduce this issue on Magento instance, please?

**Comment by engcom-November** [comment] 2022-03-15 11:11
Hi @MajorKuprich Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch and Fedex shipping methods are displayed as expected for US domestic Shipping:
![image](https://user-images.githubusercontent.com/60198231/158364871-f78f6547-db7d-4279-9e45-3765e49ea543.png)
But are not displayed for Poland shipping Address:
![image](https://user-images.githubusercontent.com/60198231/158365049-2a1c741a-a68a-494b-9c97-83ee0d6a1e43.png)
However Fedex shipping depends on Shipping Origin settings and valid shipping address zip-code. Kindly provide the shipping origin and shipping address details to verify the issue for Poland.
Please recheck the issue on Magento 2.4-develop branch provide missing steps if the issue is still reproducible.

Use below credentials for FedEx configuration:- 
Developer Test Key:  kRh9xdYLexZqRS4Q

Test Account Number:  510087100
Test Meter Number:  119177071
Test Password: E7ROeY3zp4xFcsTEuBB6FRAmK
Sandbox mode: Yes
Hub ID: 5531

**Comment by MajorKuprich** [comment] 2022-03-16 12:20
Hello @engcom-November,

How are You doing?

I've completed the data for Poland on provided environment:
- shipping origin
- shipping address

The result hasn't changed.

![](https://i.imgur.com/g1yfS56.png)
![](https://i.imgur.com/h4pgfEw.png)

Have You got any idea what I'm doing wrong? :(

**Comment by engcom-November** [comment] 2022-03-24 05:00
Hi @MajorKuprich ,
Re-verified the issue again on Magento 2.4-develop branch and cannot reproduce the issue for Poland Shipping as well.
Please check the below configuration used:
Admin - Stores - Configuration - General - Store Information: US Address
Shipping origin:
![image](https://user-images.githubusercontent.com/60198231/159845412-d95c71c3-7f75-4a25-a77d-68a44813ecfd.png)
Fedex Shipping methods are displayed for below Poland Shipping Address and user is able to place order - No issue.
![image](https://user-images.githubusercontent.com/60198231/159845495-c0f81c57-b12b-423f-ae36-2bfdacf8c0e4.png)
Kindly recheck the issue on Magento 2.4-develop branch and let us know if you are still facing any issues.
Thank you.

**Comment by engcom-Delta** [comment] 2022-04-07 01:43
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-04-07 01:43 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
