### ISSUE TITLE
Customer address unique attribute not validated

### ISSUE THREAD

**Issue by bartlubbersen** [magento/magento2#7845] opened 2016-12-16 11:31 UTC
### Preconditions
1. Magento 2.1.3
2. PHP7

### Steps to reproduce
1. Add a new customer address attribute that should be unique.
2. Save the value in two different addresses with the same value. (via Admin)

### Expected result
1. It should throw an error that the value must be unique.

### Actual result
1. It is saving both addresses with the same value.

### Comment
I tested this with two existing addresses and with adding a new address in both cases the problem exists.

**Comment by veloraven** [comment] 2016-12-19 10:41
@bartlubbersen thank you for your report.
What Magento edition do you use?
New customer address attributes are enable in Enterprise Edition only. So if you use EE please report this issue via the Support portal of your account or Partner portal if you are a partner reporting on behalf of a merchant. Github is intended for Community edition reports given no account management for CE users. This will allow for proper tracking of issues at the account level.
If you use Community Edition please address your question at  [programming questions forum](https://community.magento.com/t5/Programming-Questions/bd-p/programming-magento-2) or [Magento Stack Exchange](http://magento.stackexchange.com/). As it is not a native behavior of Magento CE and we can not treat it as an issue

**Comment by bartlubbersen** [comment] 2017-06-16 12:18
@veloraven,
We are using CE and not enterprise, however this still is a bug and not a question. Since you can also add custom address attributes via setup scripts, so it still needs solving.

**Comment by ishakhsuvarov** [comment] 2017-06-16 14:28
@bartlubbersen Please look into the Pull Request #9712 proposed by @bka and @storbahn 
It is aimed to fix this issue, and is already merged in the branch `develop`. Hope that helps for now.

**Comment by magento-engcom-team** [comment] 2017-10-12 14:23
@bartlubbersen, thank you for your report.
We've created internal ticket(s) MAGETWO-81796 to track progress on the issue.

**Comment by mukdam** [comment] 2018-02-06 16:43
Also issue in customer attribute unique in magento 2.2.0

**Comment by sdzhepa** [comment] 2020-10-08 20:22
We are not able to reproduce this on the latest code `2.4-develop`
Seems it was already fixed

**Closed as completed by sdzhepa** 2020-10-08 20:22 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Progress: done
