### ISSUE TITLE
Magento 2 puts excessive load on servers

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#4978] opened 2016-06-10 23:15 UTC
I have noticed there are cron jobs running at night from my Magento 2 site which puts excessive load on my server. I receive multiple errors from my VPS, High 5 minute load average, email queue size alert, mysql crashing etc. Whenever I suspend the Magento 2 site there is not a single warning message. Please investigate this. (Magento 2.0.7)

**Comment by orlangur** [comment] 2016-06-11 13:27
I really doubt there is enough data for investigation :)

Cron jobs are doing a lot of useful stuff in Magento 2 and cannot be just dropped. You need to find out what exactly the bottleneck is on your specific environment and site first. Analyze MySQL crash dumps, slow SQL logs and so on.

Those symptoms looks more like a server configuration issue, so that system reaches some limits and starts to behave abnormal.

**Comment by davidalger** [comment] 2016-06-11 20:40
Usually when this type of problem exists on a VPS, it's due to an undersized VPS. MySql for example can be killed by the linux kernel if the system has a small RAM allocation and the pressure on the RAM becomes high enough. Unless you can provide details and sufficient information to provide cause to investigate this as a bug, there is nothing here to look into. Maybe post what size VPS you're running on? As @orlangur said, way too vague to address!

For the time being, I'm closing as not a bug, and recommend you head over to the [Community Forums](https://community.magento.com) or [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions (if you have any) about how to get it running smoothly.

**Closed as completed by davidalger** 2016-06-11 20:40 UTC

**Comment by bondimedical3** [comment] 2016-06-11 21:56
This is not a server issue as my VPS has plenty of resources. I have ran tests and with the 4 Magento 1 stores I already have on there I can add 3 additional Magento 1 stores without any issues. This is my VPS - https://www.digitalpacific.com.au/hosting/dedicated-hosting/virtual-private-servers/managed/vps-2/ - my server meets all the requirements as outlined in your official documentation - http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html and there is plenty of memory allocated to the Magento 2 store.

**Comment by Tofandel** [comment] 2018-07-04 14:28
I can confirm this issue, same happens with my server, 32Go of ram + 16Go swap and i7 8 core cpu, a normal size store, yet randomly when some magento cron run there is a spike of cpu and memory usage at 32Go..

![image](https://user-images.githubusercontent.com/6115458/42282586-4fa752dc-7fa7-11e8-8e34-9704c985ed28.png)

It's crashing every other website on this server because of this and makes the ssh inaccessible (self ddos basically) .. So I had to put some scripts to restart apache and mysql when the server reaches more than 18Go of ram

But it's less than ideal.. It causes downtime and a lot of useless charge..

Magento version 2.2.3

I'll update to 2.2.5 and see if this still happens

**Comment by Tofandel** [comment] 2018-07-04 14:30
I believe it's https://github.com/magento/magento2/issues/15190
