### ISSUE TITLE
Invalid quote shipping address data when switching address

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#34590] opened 2021-11-09 13:07 UTC
### Preconditions
1. Customer with at least two addresses in its address book

### Steps to reproduce
1. Login to a customer account
2. Create at least two addresses: one with a company as default shipping address + one without company
3. Go to the checkout
4. Switch to the address without company

### Expected result (*)
1. The `$shippingAddress` variable in `\Magento\Quote\Model\ShippingMethodManagement::getShippingMethods` method should have the company set to null
2.  The `$shippingAddress` variable in `\Magento\Quote\Model\ShippingMethodManagement::getShippingMethods` method should have the destination address ID and not the one of the previously selected address

### Actual result (*)
1. The company is kept from the original address.

---

The issues seems to be due to the fact that when entering the `\Magento\Quote\Model\ShippingMethodManagement::getShippingMethods` method, the `$address` parameter contains the destination address data but empty fields such as company are not present in the object.
Then, the Quote shipping address is merged with these data, which causes every empty fields from the destination address not to be set as null in the quote shipping address.

This can cause multiple issues, especially with shipping methods that use the quote's shipping address for example as the collectRates() method is called after this method and thus have the wrong values.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-11-10 09:21
Hello @Axel29,

We have tried to reproduce this issue in Magento 2.4-develop but we are not able to do the same. For us after changing address `company` is set to `null` and `address_id` is showing correct id i.e. 7 for our case, please refer to the below screenshot for reference:

![141085150-eb5e08a8-1bd3-4492-b028-b06b804cf9ab](https://user-images.githubusercontent.com/51681618/141085776-0c638a5a-1718-4411-8df8-437ce3996d22.png)

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by Axel29** [comment] 2021-11-16 11:26
Hi @engcom-Hotel ,

You're watching the `$shippingAddress` variable not the `$address` passed in params.

If the destination address (thus the `$address` parameter) has no company, it is not set in it.
Thus, if the `$shippingAddress` (which is the quote's address before changing) has a company, it will stay.

Here's a screenshot of the bug:

![image](https://user-images.githubusercontent.com/3015249/141976924-8eba12d5-3fec-4bad-b5d1-3a3b3cd0317c.png)

This breakpoint is set right after the `$shippingAddress->addData($this->extractAddressData($address));` line.

I've just tested it on a native checkout with Magento 2.4.3-p1 and had the same issue as Magento 2.3.5-p2.

**Comment by Axel29** [comment] 2021-12-01 09:54
Up @engcom-Hotel just to make sure the issue doesn't get closed automatically :)

**Comment by engcom-Hotel** [comment] 2021-12-01 11:19
Hello @Axel29,

I have tried to inspect the code as per your instructions, but still, we are unable to reproduce the issue. Please have a look at below screenshot:
![01122021-1](https://user-images.githubusercontent.com/51681618/144225400-a82f87bc-7f77-42af-8686-27bec2c49559.jpg)

Let us know in case we missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-15 10:23
Dear @Axel29,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-15 10:23 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
