### ISSUE TITLE
JS minify field is not disabled in developer configuration

### ISSUE THREAD

**Issue by DanielRuf** [magento/magento2#21384] opened 2019-02-21 13:25 UTC
### Preconditions (*)

1. Magento 2.2.7
2.

### Steps to reproduce (*)

1. Go to the stores - configuration - advanced - developer 
2. See the dropdown which is not disabled

### Expected result (*)

1. The field should be also disabled
2.

### Actual result (*)

1. ![bildschirmfoto 2019-02-21 um 14 23 34](https://user-images.githubusercontent.com/827205/53171944-75ff6c00-35e4-11e9-9696-2c0d4f0557b3.png)
2.

**Comment by magento-engcom-team** [comment] 2019-02-21 13:25
Hi @DanielRuf. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@DanielRuf do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-22 07:47
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-22 07:51
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98373` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ananth-iyer** [comment] 2019-02-23 06:32
* @magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-23 06:32
Hi @ananth-iyer. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-23 06:32
Hi @ananth-iyer, here is your [Magento instance](https://i-21384-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21384-2-2-develop.instances.magento-community.engineering/admin](https://i-21384-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-23 08:04
Hi @ananth-iyer. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-16 13:28
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#21444 by @ananth-iyer in 2.3-develop branch
Related commit(s):
 - [a5bdc38d3531bf93cd46fdc4e5e4f6bbe5056b32](https://github.com/magento/magento2/commit/a5bdc38d3531bf93cd46fdc4e5e4f6bbe5056b32)
 - [ab2d0e48f01fbec862571f3716972a3c9d9109a3](https://github.com/magento/magento2/commit/ab2d0e48f01fbec862571f3716972a3c9d9109a3)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-16 13:28 UTC
Labels: Issue: Ready for Work, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-03-20 13:35
Hi @DanielRuf. Thank you for your report. 
The issue has been fixed in magento/magento2#21800 by @ananth-iyer in 2.2-develop branch
Related commit(s):
 - [095b9f4ef371d9e5692f42b655c81294f14c5137](https://github.com/magento/magento2/commit/095b9f4ef371d9e5692f42b655c81294f14c5137)

The fix will be available with the upcoming 2.2.9 release.
