### ISSUE TITLE
Currency not changed on Checkout Cart Summary when multiple currency enabled & switched from header Magento 2.4.0

### ISSUE THREAD

**Issue by vinaysikarwar** [magento/magento2#29566] opened 2020-08-16 08:47 UTC
### Preconditions (*)

1. Magento Version 2.4.0 with fresh setup & Cache Enabled

### Steps to reproduce (*)

1. Fresh Magento 2.4.0 setup
2. Enable the Cache
3. Enable Multiple Currencies
4. go to Frontend, Add product to Cart
5. Go to Cart
6.. Change Currency from Switcher
7. You will see Currency not updated in summary. due to caching. It should not be cached or refresh the summary. check the screenshot https://tinyurl.com/yy582n63

### Expected result (*)

1. [https://tinyurl.com/yy582n63]
2. Currency should changed when switched by customer.

### Actual result (*)

1.Check screenshot https://tinyurl.com/yy582n63
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Oscar** [comment] 2020-08-17 12:22
Hi @vinaysikarwar 

Thank you for your report and collaboration!

I closing this issue, because I was unable to reproduce it using provided Steps to Reproduce from the Description section on clean 2.4-develop and 2.4.0 composer version of Magento. Perhaps the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the Description section and reopen this issue.

**Closed as completed by engcom-Oscar** 2020-08-17 12:22 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.4.0

**Comment by vinaysikarwar** [comment] 2020-08-17 12:48
@engcom-Oscar I think you have not cache enabled or not checked in cart and checkout page.

This is fresh magento setup https://www.magetech.in/

1. If you go here https://www.magetech.in/test-product.html and add product to Cart.
2. Now go to Cart https://www.magetech.in/checkout/cart/
3. Change currency from top, you will see Item price & Symbol changed in Item Grid but in summary section Item Price & Symbol not changed.

This is fresh Magento setup and with version 2.4.0

**Comment by koushikch7** [comment] 2021-02-26 06:53
should reopen the ticket, this is the same for me as well.

**Comment by koushikch7** [comment] 2021-02-26 06:55
@magento reopen the ticket
