### ISSUE TITLE
Order hasCreditmemo() critical failure

### ISSUE THREAD

**Issue by MagicLegend** [magento/magento2#35078] opened 2022-02-10 08:49 UTC
### Preconditions (*)

1. In our exact case: Magento 2.4.0. But I confirmed the bug is present in every version branch from 2.0 & up, thus it is still present in [2.5-develop](https://github.com/magento/magento2/blob/6ac4cda5de1147c529fb8102bbe0cf6d59984153/app/code/Magento/Sales/Model/Order.php#L1990-L1998).
2. Call `hasCreditmemos()` during the order creation process.

### Steps to reproduce (*)

1. Add plugin for `Magento\Sales\Model\Order` `canCreditmemo()` function
2. In that plugin, call `hasCreditmemo()`
3. Place an order with a payment method that immediately invoices, in our case the default Paypal implementation did this

### Expected result (*)

1. No issues

### Actual result (*)

1. The order creation process will fail, leading to **the order not getting created, _but the customer still being charged_**.
The error:
```
main.ERROR: Call to a member function count() on bool {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Call to a member function count() on bool at /var/www/public/vendor/webonyx/graphql-php/src/Error/Error.php:174, Error(code: 0): Call to a member function count() on bool at /var/www/public/vendor/magento/module-sales/Model/Order.php:1961)"} []
```

### Possible solutions:

So the issue is that it is possible to get in a state where `$this->getCreditmemosCollection()` can return `false`, which is an unexpected value for the `hasCreditmemo()` function. The way I see it, there are two possible solutions:

1. Update `getCreditmemosCollection()` to never return `false`

[`Magento\Sales\Model\Order`](https://github.com/magento/magento2/blob/2cb012bfe3c1e22d5a4f296805160e8cf1b6c9a3/app/code/Magento/Sales/Model/Order.php#L1952-L1967)
```php
    /**
     * Retrieve order creditmemos collection
     *
     * @return CreditmemoCollection
     */
    public function getCreditmemosCollection()
    {
        if (empty($this->_creditmemos)) {
            if ($this->getId()) {
                $this->_creditmemos = $this->_memoCollectionFactory->create()->setOrderFilter($this)->load();
            } else {
                return $this->_memoCollectionFactory->create(); // <<< Change
            }
        }
        return $this->_creditmemos;
    }
```

2. Update `hasCreditmemo()` to expect a possible `false`

[`Magento\Sales\Model\Order`](https://github.com/magento/magento2/blob/2cb012bfe3c1e22d5a4f296805160e8cf1b6c9a3/app/code/Magento/Sales/Model/Order.php#L2006-L2014)
```php
    /**
     * Check order creditmemos availability
     *
     * @return bool
     */
    public function hasCreditmemos()
    {
        return $collection = $this->getCreditmemosCollection() ? (bool) $collection->count() : false;
    }
```
(Of course this could be written a bit more verbose as well)

For our customer this turned into a very critical issue real fast, since it leads to the order creation process failing - but left customers still being charged for their purchase. Hence I'm putting this issue down as a S0, since it is easy to accidentally trigger using nothing but core Magento code and payment methods.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-07-26 05:04
Hello @MagicLegend,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch, but for us, the issue is not reproducible. We have followed the below steps:

1. Created Plugin for under Magento\Sales\Model\Order under app/code/Magento/Sales/etc/di.xml
2. Plugin look like the below:
```
namespace Magento\Sales\Plugin;

use Magento\Sales\Model\Order;

/**
 * Plugin for Order
 */
class OrderPlugin
{
    /**
     *
     * @param Order $subject
     * @return bool
     */
    public function afterCanCreditmemo(Order $subject)
    {
       echo "Plugin CanCreditmemo<br/>";
       $subject->hasCreditmemos();
    }
}
```
3. Placed an Order successfully via Paypal Payment method

Note: we have tried with Before & After Plugin, but were not able to reproduce the issue.

This Plugin doesn't get called during the order placement process. 

Please let us know in case we have missed anything.

Thanks

**Comment by MagicLegend** [comment] 2022-08-04 08:29
Hello @engcom-Hotel,

Thank you for taking a look at it. Have you verified your Paypal configuration to immediately invoice? It might be an interaction with one of the about 100 modules we have installed, I'm not 100% sure. I'd need to spin up a new instance myself to test it out. However, I'm afraid that I won't have time for that in the coming week or two.

But, even with just code analysis you have to agree with me that there is a code issue here, and that it's possible to cause this exception during checkout if the right requirements are met:

https://github.com/magento/magento2/blob/6ac4cda5de1147c529fb8102bbe0cf6d59984153/app/code/Magento/Sales/Model/Order.php#L1936-L1951

If `$this->getId()` returns a falsy value, this function will return `false`. Where the code here will try to call `->count()` on that `false`:

https://github.com/magento/magento2/blob/6ac4cda5de1147c529fb8102bbe0cf6d59984153/app/code/Magento/Sales/Model/Order.php#L1990-L1998

Thus resulting in an exception, and in our case leaving the customer billed without an order actually being created. This issue should appear _any time in the order process_ where `$this->getId()` is still a falsy value, and you try to call `$order->hasCreditmemo()`.

Thank you.

**Comment by engcom-Echo** [comment] 2022-08-08 13:56
Hello @MagicLegend,

We have tried to reproduce the issue in Magento 2.4-develop branch, but for us, the issue is not reproducible. We have followed the below steps:

1. Created Plugin for under Magento\Sales\Model\Order under app/code/Magento/Sales/etc/di.xml
2. Plugin look like the below:

```
namespace Magento\Sales\Plugin;

use Magento\Sales\Model\Order;

/**
 * Plugin for Order
 */
class OrderPlugin
{
    /**
     *
     * @param Order $subject
     * @return bool
     */
    public function afterCanCreditmemo(Order $subject)
    {
       echo "Plugin CanCreditmemo<br/>";
       $subject->hasCreditmemos();
    }
}

```
4. Placed an Order successfully via Paypal Payment method
5. And click on invoice for particular order and got Invoiced successfully

Note: we have tried with Before & After Plugin, but we are not able to reproduce the issue and we have check PayPal Configuration is successfully configured.
This Plugin doesn't get called during the order placement process.

Please check if i missed anything and kindly check on Magento 2.4-develop branch and provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by MagicLegend** [comment] 2022-08-09 07:26
Hi @engcom-Echo,

Let me repeat my previous message:

> Hello @engcom-Hotel,
> 
> Thank you for taking a look at it. **Have you verified your Paypal configuration to immediately invoice?** It might be an interaction with one of the about 100 modules we have installed, I'm not 100% sure. I'd need to spin up a new instance myself to test it out. However, I'm afraid that I won't have time for that in the coming week or two.
> 
> ### **But, even with just code analysis you have to agree with me that there is a code issue here**, and that it's possible to cause this exception during checkout if the right requirements are met:
> 
> https://github.com/magento/magento2/blob/6ac4cda5de1147c529fb8102bbe0cf6d59984153/app/code/Magento/Sales/Model/Order.php#L1936-L1951
> 
> If `$this->getId()` returns a falsy value, this function will return `false`. Where the code here will try to call `->count()` on that `false`:
> 
> https://github.com/magento/magento2/blob/6ac4cda5de1147c529fb8102bbe0cf6d59984153/app/code/Magento/Sales/Model/Order.php#L1990-L1998
> 
> Thus resulting in an exception, and in our case leaving the customer billed without an order actually being created. **This issue should appear _any time in the order process_ where `$this->getId()` is still a falsy value, and you try to call `$order->hasCreditmemo()`.**
> 
> Thank you.

(Emphasis added for clarity)

**Comment by engcom-Echo** [comment] 2022-08-09 13:28
Hello @MagicLegend,

Thanks for raising your concern.

In order to proceed further with any community issue we first have to reproduce it and then we can proceed with the confirmation of the same.

We have tried to reproduce the issue in Magento 2.4-develop branch, but for us, the issue is not reproducible. We have followed the below steps:

1. Created Plugin for under Magento\Sales\Model\Order under app/code/Magento/Sales/etc/di.xml
2. Plugin look like the below:

```
namespace Magento\Sales\Plugin;

use Magento\Sales\Model\Order;

/**
 * Plugin for Order
 */
class OrderPlugin
{
    /**
     *
     * @param Order $subject
     * @return bool
     */
    public function afterCanCreditmemo(Order $subject)
    {
       echo "Plugin CanCreditmemo<br/>";
       $subject->hasCreditmemos();
    }
}

```
4.Placed an Order successfully via Paypal Payment method
5. And click on invoice for particular order and got Invoiced successfully

Note:- we have analysed the code and debug the code but we are not getting any single time the  $this->getId() as falsy value please suggest us how or when we can get this value as false so that we can able to reproduce this issue.

Please check if i missed anything and kindly check on Magento 2.4-develop branch and provide more information with exact steps and screenshot so that we can reproduce this issue.

Thanks

**Comment by engcom-Echo** [comment] 2022-08-23 12:23
Hello @MagicLegend,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-23 12:23 UTC
Labels: Triage: Dev.Experience, Issue: needs update
