### ISSUE TITLE
Create new order admin page jumps up down

### ISSUE THREAD

**Issue by bhavik43** [magento/magento2#23317] opened 2019-06-19 05:47 UTC
Create new order admin page jumps up down

### Preconditions (*)
magento 2.3

-> Selected customer should have items in wish list,shopping cart,last ordered,Recently viewed.

### Steps to reproduce (*)
1. Go to Admin
2. Sales > Orders
3. Create New Order
4. Select any customer
5. Without do anything click on Submit order

### Expected result (*)
Page should not be jumping and navigate to validation message.

### Actual result (*)
Without add any product click on submit order page jumps up and down.

**Comment by krishprakash** [comment] 2019-06-19 05:49
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-19 05:49
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-19 05:50
Hi @krishprakash, here is your [Magento instance](https://i-23317-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23317-2-3-develop.instances.magento-community.engineering/admin](https://i-23317-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-06-19 06:34
Hi @bhavik43. 
I'am not able to reproduce this issue as mentioned steps by you on clean magento instance.
seems like this related to your custom modules.
Please review once in clean magento instance
Closing this as cannot reproduce.
Feel free to reopen if you phase this issue in latest instance.
Thanks.

**Closed as completed by krishprakash** 2019-06-19 06:34 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
