### ISSUE TITLE
For configurable product, select the colour swatches but the colour of the image not change accordingly

### ISSUE THREAD

**Issue by Khushbu-Webkul-QA** [magento/magento2#25404] opened 2019-10-31 13:20 UTC
### Preconditions (*)

1. Magento version: 2.3.3 with Sample Data 
2. PHP Version: 7.2

### Steps to reproduce (*)

1. At category page and at product detail page go to configurable product
2. Select the color swatch 

### Expected result (*)

The color of the product image changes depending on the selected color
![color2](https://user-images.githubusercontent.com/51681435/69714498-2a4b9700-110f-11ea-8d48-eca46fe09c0d.png)

### Actual result (*)

The color of the product image does not change depending on the selected color.
![Screenshot (33)](https://user-images.githubusercontent.com/45037885/67950139-295a3f00-fc0f-11e9-8b7e-30d90cfea8d5.png)
![Screenshot (32)](https://user-images.githubusercontent.com/45037885/67950140-295a3f00-fc0f-11e9-9b88-a00ae91cfbd1.png)
![Screenshot from 2019-11-27 12-21-22](https://user-images.githubusercontent.com/51681435/69715233-98dd2480-1110-11ea-98a2-9ccf24aa1ec9.png)

**Comment by Khushbu-Webkul-QA** [comment] 2019-10-31 13:22
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-31 13:22
Hi @Khushbu-Webkul-QA. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-31 13:23
Hi @Khushbu-Webkul-QA, here is your [Magento instance](https://i-25404-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25404-2-3-develop.instances.magento-community.engineering/admin](https://i-25404-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Echo** [comment] 2019-11-26 14:42
Hello @Khushbu-Webkul-QA 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3-develop and 2.3.3 branches by provided steps.

**Testing scenario:**

**Preconditions:**

1. Magento version: 2.3.3 or 2.3-develop 
2. PHP Version: 7.2
3. Js,css, html merged and minified
4. Flat catalog/category - Yes
5. Mode : production

**Steps to reproduce:**

1. Add simple data
2. php bin/magento setup:upgrade
3. At category page and at product detail page of configurable product select the colour swatch

**Result:** 
Colour of the product image is change accordingly
![color2](https://user-images.githubusercontent.com/51681435/69643108-8066fe80-106b-11ea-94b4-6ba045c6e473.png)
Thank you!

**Comment by Khushbu-Webkul-QA** [comment] 2019-11-27 06:02
I have installed a fresh magento version 2.3.3, and i have again faced this issue

**Comment by magento-engcom-team** [comment] 2019-11-27 10:23
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29220` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by nkajic** [comment] 2019-12-12 10:37
> I have installed a fresh magento version 2.3.3, and i have again faced this issue

Hi @Khushbu-Webkul-QA 
It seems that this is fixed in 2.4-develop from github, but I can't track exact PR involved in this. I found serval duplicate tickets but not PR that fixed this (I want it for patch).

**Comment by drpayyne** [comment] 2020-02-06 06:52
Hi @engcom-Echo, were you able to reproduce this after https://github.com/magento/magento2/issues/25404#issuecomment-558660542?

**Comment by engcom-Echo** [comment] 2020-02-06 08:24
Hi, @drpayyne. It is not reproduced on the 2.4-develop.

**Comment by drpayyne** [comment] 2020-02-06 08:31
@engcom-Echo, I think we can close this, then.

**Comment by sdzhepa** [comment] 2020-08-04 22:01
Due to comment in this thread 
> It is not reproduced on the 2.4-develop.
>  I think we can close this, then.

Closed as fixed in `2.4-develop`

**Closed as completed by sdzhepa** 2020-08-04 22:01 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: SampleData
