### ISSUE TITLE
Importing: non-default multiple value separator can't be used in additional_images column

### ISSUE THREAD

**Issue by gediminaskv** [magento/magento2#11026] opened 2017-09-25 13:37 UTC
### Preconditions

1. Mage 2.1.8 and earlier
2. PHP7

### Steps to reproduce

1. Generate CSV file for product images import with fields:  `sku` , `additional_images` etc.
2. Use different multiple values separator ie ;
3. Add some images to `additional_images` row.

### Expected result

1. Product images imports successfuly.

### Actual result

1. Get an error during importing process: `Wrong URL/path used for attribute additional_images in row(s)...`
2. If you use default multiple value separator , (comma), import goes well. It throws an error when something different than comma  is used to separate image files. It only happens with `additional_images` column!

**Comment by magento-engcom-team** [comment] 2017-09-27 22:00
@gediminaskv, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:00 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
