### ISSUE TITLE
Deleting a product does not remove all associated attribute values from database

### ISSUE THREAD

**Issue by thanasisgalanis** [magento/magento2#6757] opened 2016-09-26 16:51 UTC
When delete a product some attribute values are still in database, especially in table **catalog_product_entity_varchar**. After that, for some reason which I can not understand and have not yet been able to reproduce, if i use the import procedure to add products, some products take one of the deleted products **entity_id** (i thing the last deleted one, but i am not sure yet) and of course the remaining associated with that **entity_id** values.
### Preconditions
1. Magento CE 2.1.0
2. PHP 7.0.11
3. MySQL 5.6.33-log
### Steps to reproduce
1. Create a product with name value "Test Deleted Product"
2. Write down the **entity_id** (product_id)
3. Delete this product
4. Check in database for records associated with deleted **entity_id**
### Expected result
1. You must not find any records associated with deleted **entity_id**
### Actual result
1. You find remaining values in table **catalog_product_entity_varchar**

**Comment by saoque** [comment] 2016-11-18 14:07
If you doing it via Install\upgrade script magento disable all FK constraints in DB inside $setup->startSetup() method, its really a hole in architecture, as same happens with everything that have relations, as solution i would recommend you to do $setup->endSetup() before your actions, and start it again later.

**Comment by slopukhov** [comment] 2016-11-28 14:01
@sakisplus thank you for your feedback.
Please, recheck it on the latest 2.1 version of Magento.
If the problem is still relevant, please, describe in which product types and what attributes are not removed?

**Comment by thanasisgalanis** [comment] 2016-11-28 15:45
Yes I can confirm that the problem persists in version 2.1.2.

### Preconditions
1. Magento CE 2.1.2
2. PHP 7.0.13
3. MySQL 5.6.34
### Steps to reproduce
1. Create a **Simple Product** with name value "Test Deleted Product 212"
![create product](https://cloud.githubusercontent.com/assets/6130645/20675131/eedbd3c6-b593-11e6-8669-2b8b62d97ed5.png)
2. Write down the **entity_id** (product_id)
![write down entity_id](https://cloud.githubusercontent.com/assets/6130645/20675152/fb98dfb4-b593-11e6-8cfd-861c200a2ae9.png)
3. Delete this product
![delete product](https://cloud.githubusercontent.com/assets/6130645/20675169/05b64798-b594-11e6-8aa6-cef87ba26dc4.png)
4. Check in database for records associated with deleted **entity_id**
### Expected result
1. You must not find any records associated with deleted **entity_id**
### Actual result
1. You find remaining values in table **catalog_product_entity_varchar**
![chech database](https://cloud.githubusercontent.com/assets/6130645/20675185/155775fa-b594-11e6-90a2-2fe15baaba21.png)

**Comment by slopukhov** [comment] 2016-11-28 16:07
Looks like this is environment issue. Did you change the mysql settings or turn off foreign keys?

**Comment by slopukhov** [comment] 2016-11-28 16:14
Also, please, check the availability of the foreign keys in the table catalog_product_entity_varchar.
![foreign keys](https://cloud.githubusercontent.com/assets/8982177/20675862/7a32849a-b596-11e6-9495-fef2b73bb1d4.png)

**Comment by thanasisgalanis** [comment] 2016-11-28 17:45
I'm afraid I do not have the required knowledge to answer your question. Could you guide me?

**Comment by slopukhov** [comment] 2016-11-29 07:38
@sakisplus Could you describe what environment you use (operating system version and other information)?
Also you can check the necessary environment specifications in the [next ](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) documentation

**Comment by thanasisgalanis** [comment] 2016-11-29 17:58
Cloud Server
Operating System: linux - CENTOS 6.8
Architecture: x86_64
cPanel Version: 60.0 (build 25)
Apache Version: 2.4.23
PHP Version: 7.0.13 *and all required PHP extensions installed*
MySQL Version: 5.6.34

Magento 2 installed using composer

**Comment by thanasisgalanis** [comment] 2016-11-29 23:28
@slopukhov Your assumption that this is an environment problem, seems to be correct. With the environment below problem not reproduced!

**Test No.2**
Vagrant + Virtualbox
Operating System: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64)
Architecture: x86_64
PHP Version: 7.0.12-1+deb.sury.org~trusty+1 
MySQL Version: mysqlnd 5.0.12-dev

Magento 2.1.2

**Comment by slopukhov** [comment] 2016-11-30 09:22
@sakisplus Thanks, I'm closing the ticket. 
Please feel free to create new if you have additional questions.

**Closed as completed by slopukhov** 2016-11-30 09:22 UTC
Labels: bug report, Component: Catalog
