### ISSUE TITLE
Category theme is not applied to product

### ISSUE THREAD

**Issue by chaikivskyi** [magento/magento2#33428] opened 2021-07-06 13:33 UTC
### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)
1. Configure a separate theme for the category on the category edit page in admin panel
2. Enable " Apply Design to Products"
3. Go to the product page

### Expected result (*)

1. Product use the same theme as a category

### Actual result (*)

1. Product use default theme

---

- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._

**Comment by chaikivskyi** [comment] 2021-07-06 13:34
@magento I am working on this

**Comment by mrtuvn** [comment] 2021-07-06 15:13
i can't reproduce problem like description
Tested with my own local instance (latest code 2.4-develop)
![Screenshot from 2021-07-06 22-12-35](https://user-images.githubusercontent.com/1908873/124624688-4b599980-dea7-11eb-9917-83eb7df97e3b.png) (Category tops)
![Screenshot from 2021-07-06 22-12-38](https://user-images.githubusercontent.com/1908873/124624718-56142e80-dea7-11eb-988c-c4cb1a2961d6.png) (Details of product Chaz Kangeroo Hoodie)

**Comment by chaikivskyi** [comment] 2021-07-06 20:04
@mrtuvn I can't be sure that you understand the issue by your screenshots.
I can explain the issue on the code level. 
https://github.com/magento/magento2/commit/7f6e9a842c3ca0d1971920c44d2e84f51b8bb5f8 - it is a related commit to this issue which exists in the 2.4-develop branch, but  I think the author missed some details. 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Controller/Product/View.php#L198 - in my opinion, we should setCategory to a product like in the https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Helper/Product.php#L460. Because the function getDesignSettings do not return the right value from category when the product does not contain a category.

**Comment by mrtuvn** [comment] 2021-07-07 01:43
So i think you can update more details in preconditions for QA/QC team can  easier reproduce your scenario
From my experience products in category list page already set `category_id` for each products listed in block `app/code/Magento/Catalog/Block/Product/ListProduct.php`

**Comment by chaikivskyi** [comment] 2021-07-07 06:21
@mrtuvn Controller `Product/View.php` does not work on the product listing. It is a product page. Please, do next steps to reproduce the issue:
1. Create a new theme
2. Apply a theme for only one category and enable the setting ` Apply Design to Products` https://imgur.com/zqHGfAG
3. Create new layout rules for the `catalog_product_view` handle in the new theme. These rules will not be applied on the product page.

**Comment by mrtuvn** [comment] 2021-07-21 07:29
cc: @tsviklinskyi Can you check comment https://github.com/magento/magento2/issues/33428#issuecomment-875045393

**Comment by chaikivskyi** [comment] 2021-07-21 08:12
> cc: @tsviklinskyi Can you check comment [#33428 (comment)](https://github.com/magento/magento2/issues/33428#issuecomment-875045393)
> Seem we miss specific case customer go directly to product without visit category page. In this case product may not contain category information so design will not apply

No, products loaded via repository will never have a category, even when we go to the product page from the category page.

**Comment by chaikivskyi** [comment] 2021-07-26 13:27
@mrtuvn Issue described in this ticket is not related to your case.

**Comment by engcom-Bravo** [comment] 2024-08-06 05:06
Hi @chaikivskyi,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1440" alt="Screenshot 2024-08-06 at 10 34 21" src="https://github.com/user-attachments/assets/000040a3-11d7-43c2-9aaf-e1044678f1b7">



<img width="1440" alt="Screenshot 2024-08-06 at 10 34 06" src="https://github.com/user-attachments/assets/e6601fbd-7eaf-4474-8cb9-81333d3b2d73">


Product use the same theme as a category

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-06 05:06 UTC
Labels: Component: Catalog, Issue: Clear Description, Issue: Confirmed, Component: Theme, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Reported on 2.4.x, Area: Catalog
