### ISSUE TITLE
Delete address by REST APIs with customer token not working

### ISSUE THREAD

**Issue by peteandmad** [magento/magento2#31806] opened 2021-01-22 10:35 UTC
### Preconditions (*)

1. Magento 2 REST APIs

### Steps to reproduce (*)

1. unable to delete address with customer token
2. DELETE http://{base url}/rest/V1/addresses/{18} with auth token
3. (with admin token it work fine)

### Expected result (*)

1. Selected address should be deleted from list

### Actual result (*)

1. 401 Unauthorized http://{base url}/rest/V1/addresses/18
{"message":"Consumer is not authorized to access %resources","parameters":{"resources":"Magento_Customer::manage"}}

**Comment by engcom-Bravo** [comment] 2021-01-22 14:57
Hello @peteandmad 

Thank you for your report.

This is actually the expected behavior because the Customer token CANNOT access customerAddressRepositoryV1
Admin has access to delete the Customers address 

We have to close this issue. Please feel free to comment or create new tickets according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2021-01-22 14:57 UTC
Labels: Issue: ready for confirmation, not-confirmed
