### ISSUE TITLE
Open page with 404 error by click on "?" button on "Store View Specific Labels"

### ISSUE THREAD

**Issue by ku4er007** [magento/magento2#32084] opened 2021-02-10 12:13 UTC
Mac Catalina 10.15.7
Safari 13.1.3

### Preconditions (*)

1. Logged in admin Magento 2.0
2.

### Steps to reproduce (*)

1. Click on side menu "Marketing - Promotions - Cart Price Rules"
2. Click on "Add new Rule"
3. Open menu "Labels"
4. Click on "?" button near "Store View Specific Labels" section title

### Actual result (*)

1. Open page with 404 error
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-02-10 13:07
Hi @ku4er007.
Thank you for your report.
We are not able to reproduce this issue. Everything works as expected.

**Actual Result:** :heavy_check_mark: Linked [page](https://docs.magento.com/user-guide/configuration/scope.html) is succesfully opened

![Screenshot from 2021-02-10 15-04-09](https://user-images.githubusercontent.com/51679138/107513872-8a621800-6bb1-11eb-979e-653f26d405ee.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-10 13:07 UTC
Labels: Issue: ready for confirmation, not-confirmed

**Comment by ku4er007** [comment] 2021-02-10 13:24
ср, 10 февр. 2021 г. в 15:07, Oleksii Stasiv <notifications@github.com>:
