### ISSUE TITLE
Customer Edit Issue when there is a newsletter queue associated with it.

### ISSUE THREAD

**Issue by chichitsai0517** [magento/magento2#30645] opened 2020-10-24 19:29 UTC
### Preconditions (*)

Installed a fresh copy of Magento 2.3.5-P2 with no sample data. Upgrade using composer to 2.4 (where we see the issue) and then upgrade to 2.4.1 (where issue is still present). 

1. I tried on 2.4.0 and 2.4.1 and they both have the same issue. 
1. Reproducible on 2.4-develop

### Steps to reproduce (*)

1. Add a new customer which is also subscribed to newsletter.
1. Create a a newsletter in Marketing>Newsletter Templates
1. Queue the newsletter
1. Go to customer and try to edit their information - This is what we get (https://prnt.sc/v642qm)
1. Go create a new customer and subscribe to newsletter (however this new customer is not and has not been in any newsletter queue yet) - When we go and edit this customer, everything is ok  (https://prnt.sc/v64460).

### Expected result (*)

1. See Screenshot (https://prnt.sc/v64460)

### Actual result (*)

1. See Screenshot (https://prnt.sc/v642qm)

**Comment by mohanelamurugan** [comment] 2020-10-26 06:16
@magento give me 2.4-develop instance

**Comment by mohanelamurugan** [comment] 2020-10-26 06:39
Unable to reproduce this issue, Works fine on both 2.4 and 2.4.1

## Steps followed:

- Create a new customer with newsletter subscription.
- Create a newsletter and queue it.
- Edit the customer created.

**Comment by engcom-Bravo** [comment] 2020-10-26 10:06
Hello @chichitsai0517 

Thank you for your report 

We confirm that we are able to reproduce the issue on 2.4.1
![Repro](https://user-images.githubusercontent.com/51680745/97159123-0e1f0280-1783-11eb-8f7d-74322d645e42.png)

However, it is **already fixed on 2.4-develop**, and will be delivered in the next release 
![develop](https://user-images.githubusercontent.com/51680745/97159271-46264580-1783-11eb-8e92-05cb9f101311.png)

So we are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you

**Comment by engcom-Bravo** [comment] 2020-10-26 14:26
Let's leave this issue opened until the 2.4-develop and 2.4.1 are synchronized

**Comment by chichitsai0517** [comment] 2020-10-26 14:27
Is there a temporary solution to fix this until the next release?

**Comment by ioweb-gr** [comment] 2020-10-28 22:37
It would be very helpful to know which commits fix it so that we can apply the patch on our crippled instances.

**Comment by engcom-Bravo** [comment] 2020-10-29 13:02
After the 2.4-develop and 2.4.1 synchronization, the issue is **reproducible** on 2.4-develop also.
We confirm the issue and move it to Ready for Development

**Comment by magento-engcom-team** [comment] 2020-10-29 13:04
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38789` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by fedekrum** [comment] 2020-11-04 22:04
> Is there a temporary solution to fix this until the next release?

Yes, there is. Erase the queue and problem solved.

**Comment by engcom-Bravo** [comment] 2020-11-05 14:26
> Is there a temporary solution to fix this until the next release?

https://github.com/magento/magento2/pull/30727

**Closed as completed** 2020-11-14 16:18 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Component: Ui, Component: Newsletter, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.1
