### ISSUE TITLE
After upgrade to Magneto 2 CE from 2.1.2 - 2.1.3, the right editing panel from product -> inventory -> categories is missing

### ISSUE THREAD

**Issue by harrywutech** [magento/magento2#7834] opened 2016-12-15 19:58 UTC
### Preconditions

1. Magento 2 CE 2.1.3
2. PHP 5.6
3. MySQL 5.5

### Actual result

1. [Screenshot, logs]
![bug](https://cloud.githubusercontent.com/assets/3589130/21239856/9607b40e-c2bd-11e6-8dac-5655ea723ffb.png)

**Comment by SolPin** [comment] 2016-12-15 20:12
Check if the CMS edit part is also missing. I have the same issue after 2.1.2 > 2.1.3

**Comment by harrywutech** [comment] 2016-12-15 20:23
Thanks Solpin, yes, the CMS part is also missing too
![bug2](https://cloud.githubusercontent.com/assets/3589130/21240693/4630988e-c2c1-11e6-8108-1935cb9046c5.png)

**Comment by thanasisgalanis** [comment] 2016-12-15 20:59
## Preconditions
- Magento 2 CE 2.1.3
- Apache 2.4.23
- PHP 7.0.14
- MySQL 5.6.34

## Try to:
- delete static files
- clear cache
- and finaly **setup:static-content:deploy**
  (don't forget you language content if you use other than default)

### Categories edit page
![2016-12-15 22 45 53](https://cloud.githubusercontent.com/assets/6130645/21241502/9503adc8-c318-11e6-87c7-58b36289c50b.png)

### Cms edit page
![2016-12-15 22 50 26](https://cloud.githubusercontent.com/assets/6130645/21241609/0cd69c2a-c319-11e6-9aee-c3f0c1366b1b.png)

**Comment by SolPin** [comment] 2016-12-15 22:01
I have tried this, but without result. The panels are still missing.

**Comment by harrywutech** [comment] 2016-12-15 22:18
I tried the solution, still missing.

**Comment by andidhouse** [comment] 2016-12-16 09:43
i can not confirm this. we upgraded from 2.1.2 to 2.1.3 and categories and cms pages work like before. i think you missed some command here.

**Comment by SolPin** [comment] 2016-12-16 12:00
We tried all but no results what so ever, and we didn't missed any command.

**Comment by andidhouse** [comment] 2016-12-16 12:02
@SolPin can you post here the ssh commands you did run to make shure pls?

**Comment by SolPin** [comment] 2016-12-16 12:50
composer require magento/product-community-edition 2.1.3 --no-update
composer update
rm -rf var/di var/generation
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento indexer:reindex

**Comment by atrane21** [comment] 2016-12-16 15:14
I am having the same issue and solution above did not work.

**Comment by andidhouse** [comment] 2016-12-16 15:20
you can try to:

rm -rf /var/cache/nginx/* (if you use nginx)
rm -rf /var/www/html/magento2/pub/static/*
rm -rf /var/www/html/magento2/var/view_preprocessed/*
rm -rf /var/www/html/magento2/var/di/*
rm -rf /var/www/html/magento2/var/cache/*
rm -rf /var/www/html/magento2/var/page_cache/*

php bin/magento setup:static-content:deploy && php bin/magento setup:static-content:deploy de_DE (your country code here like de_DE)
php bin/magento cache:clean && php bin/magento cache:flush
php bin/magento indexer:reindex
php bin/magento setup:upgrade
php bin/magento setup:di:compile

**Comment by atrane21** [comment] 2016-12-16 15:43
After some more looking around it seems like when i select a product in the backend to edit it, it doesn't show anything there as well.

**Comment by phillipmeyer** [comment] 2016-12-16 17:12
I have this same problem, cannot access anything that can be edited including: Categories, Products, Product Attributes and CMS page. However, I can still see that CMS pages still exist and the product attributes can be sorted.

**Comment by SolPin** [comment] 2016-12-16 18:42
I made a fresh new 2.1.3 install - installed all the additional extensions - copy the database - but the result is the same.!! No data/entry screen for CMS, Customers, Categories, Products, etc
I have 11 storeviews (languages: including Chinese and Japanese) and Installed the Porto 2.4.4 theme.

Also it's not possible to change a Theme - Default Theme shows also no info just white space.

**Comment by kandy** [comment] 2016-12-17 20:02
Can you change the  mode to develop and  enable display errors in php (ini settings display_errors = 1) and try go to some page in browser private mode?

**Comment by phillipmeyer** [comment] 2016-12-18 11:28
Hi @kandy ,

I already have that active but I don't see any errors on screen, it just doesn't show any parts of the pages that let me edit anything.

I also can't see anything that looks relevant in the logs. Here are some extracts...

From magento/var/log/system.log : There are a whole lot of entries which start 'main.INFO: Add of item with id Magento_' and then the following...
[2016-12-18 11:20:04] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_3d41d8cd98f00b204e9800998ecf8427e and handles : Please correct the XML data and try again.  [] []
[2016-12-18 11:20:09] main.INFO: Cache file with merged layout: LAYOUT_adminhtml_STORE1_32c857da9ad039a9e5ba1a8de0f556f19 and handles default, cms_page_edit: Please correct the XML data and try again.  [] []
[2016-12-18 11:20:09] main.CRITICAL: Broken reference: the 'header' tries to reorder itself towards 'global.notices', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-12-18 11:20:09] main.CRITICAL: Broken reference: the 'page.breadcrumbs' tries to reorder itself towards 'notifications', but their parents are different: 'page.wrapper' and 'notices.wrapper' respectively. [] []
[2016-12-18 11:20:09] main.CRITICAL: Broken reference: the 'global.search' tries to reorder itself towards 'notification.messages', but their parents are different: 'header.inner.right' and 'header' respectively. [] []


From magento/var/log/debug.log
[2016-12-18 11:17:36] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://www.millsmeyer.com/mageadmin_F1Pp6x/admin/index/index/key/81eb8d7ad768b286b79e015f3e715db4aedaa4463abcc276965af8c08bf9c94b/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-12-18 11:18:03] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []
[2016-12-18 11:18:03] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []



From /var/log/error_log:
[Sun Dec 18 11:19:38.383684 2016] [mpm_prefork:notice] [pid 2985] AH00169: caught SIGTERM, shutting down
[Sun Dec 18 11:19:38.557309 2016] [suexec:notice] [pid 22908] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Sun Dec 18 11:19:38.585233 2016] [auth_digest:notice] [pid 22909] AH01757: generating secret for digest authentication ...
[Sun Dec 18 11:19:38.585796 2016] [lbmethod_heartbeat:notice] [pid 22909] AH02282: No slotmem from mod_heartmonitor
[Sun Dec 18 11:19:38.608442 2016] [mpm_prefork:notice] [pid 22909] AH00163: Apache/2.4.23 (Amazon) OpenSSL/1.0.1k-fips configured -- resuming normal operations
[Sun Dec 18 11:19:38.608467 2016] [core:notice] [pid 22909] AH00094: Command line: '/usr/sbin/httpd'

**Comment by phillipmeyer** [comment] 2016-12-18 11:51
**THIS FIXED IT**

Oh my god, I missed your comment about private mode. I tried logging in with another device in private mode and everything worked. So I have deleted all website data on my Mac that is related to this site and now I have full access to everything again.

This previously caused me a problem when I wiped my Magento 2 install and totally reinstalled it. When I did that a while ago I couldn't access it at all until I deleted all cookies and storage as well. I wish I had thought of that but I don't understand why that is causing a problem. It's frustrating because I have to delete all Safari's data (for all sites) on my iPad to make it work again.

I thought it might have been linked to "Enable HTTPD Strict Transport Security HSTS" and/or "Upgrade Insecure Requests" but I tried to disabled that and it didn't help.

Any thoughts how to avoid having to delete all the website data for future updates?

(It may be worth mentioning I force https for fronted and admin)

**Comment by Liontwins** [comment] 2016-12-21 07:49
Clearing the browser cache did the trick for me!

**Comment by veloraven** [comment] 2016-12-21 19:25
@hanxiangwu did you try to clean browser cache including offline website data?

**Comment by veloraven** [comment] 2016-12-21 19:25
@philippebernou , @Liontwins thank you for updates.

**Comment by phillipmeyer** [comment] 2016-12-21 19:28
Hi @veloraven I use a Safari on a Mac and just cleared all cookies and website data related to the specific site on my iPad I had to completely wipe everything to get it to work again. However, you could try your browser in private mode to see if that works.

**Comment by veloraven** [comment] 2017-01-03 12:32
I'm closing this issue as there was no response from the author for more than two weeks.
And issue seems to be fixed for other users.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2017-01-03 12:32 UTC
Labels: Progress: needs update
