### ISSUE TITLE
Can't invoice on Magento 2.3.2 :(

### ISSUE THREAD

**Issue by TzumB** [magento/magento2#23950] opened 2019-07-30 15:30 UTC
### Preconditions (*)

1. 2.3.2
2. Magento Back-end creating-and-invoicing orders

### Steps to reproduce (*)

1. I have created a new order, messed around with the order status to test the e-mails,
2. Pressed "Invoice", ticked "email copy of invoice" en clicked "Submit Invoice"

### Expected result (*)

1. I'd expected Magento to continue to create the invoice and close the order
2.

### Actual result (*)

1. This error message: "The invoice can't be saved at this time. Please try again later."
2. 

I am sorry, I am quite new to Magento and a rookie when it comes to GitHub but please bear with me.
Hope some one knows of a fix!

Thanks,
Twan

**Comment by TzumB** [comment] 2019-07-30 15:45
I have just discovered that the error only occurs when I have a virtual product on the order.
I am trying to invoice a service (virtual product) together with some materials (simple product) and this is where the error happens.
When I remove the virtual product from the order it WILL invoice!

**Comment by shikhamis11** [comment] 2019-08-01 17:00
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-01 17:00
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-01 17:00
Hi @shikhamis11, here is your [Magento instance](https://i-23950-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23950-2-3-develop.instances.magento-community.engineering/admin](https://i-23950-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-08-01 17:21
Hello @TzumB 
Thank you for reporting this issue , but I am not able to reproduce it either on magento 2.3- develop instance or magento 2.3.2 . Please try to reproduce it on the magento 2 develop instance and share screenshots if you are able to reproduce it

**Comment by shikhamis11** [comment] 2019-08-09 11:44
Hello @TzumB 
I am closing this issue now .. message here If you are still able to reproduce it. also share screenshots if available

**Closed as completed by shikhamis11** 2019-08-09 11:44 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by zeekinfodev** [comment] 2020-07-13 08:24
Hi 

anyone  how to fix this problem The invoice can't be saved at this time. Please try again later.

**Comment by gilbertsohal** [comment] 2020-12-17 01:18
I m facing same problem after upgraded from 2.3.4 to 2.3.6. Getting error when trying to submit invoice 
(The invoice can't be saved at this time. Please try again later.)

Is there anyone who can please help?
