### ISSUE TITLE
Errors during compilation: \Customization\Block\Specialproductlist

### ISSUE THREAD

**Issue by luantran1311** [magento/magento2#28271] opened 2020-05-19 03:31 UTC
### Preconditions (*)

1. Magento CE 2.3.5-p1

### Steps to reproduce (*)

1.  run **php bin/magento setup:di:compile**
2.  **Errors during compilation: \Customization\Block\Specialproductlist
Incompatible argument type: Required type: \Magento\Catalog\Api\CategoryRepositoryInterface. Actual type: array; File: /app/code/Customization/Block/Specialproductlist.php**

### Expected result (*)

1. code compiled successfully

### Actual result (*)

1. An error shows up during compilation
![image](https://user-images.githubusercontent.com/19511189/82293837-646b6680-99d7-11ea-8b50-c60eeeba27a6.png)

**Comment by lbajsarowicz** [comment] 2020-05-19 09:15
This is not Magento-related issue. The problem is caused by the Customization module.

**Comment by PascalBrouwers** [comment] 2020-05-25 10:29
Extended the \Magento\CatalogWidget\Block\Product\ProductsList class to include \Magento\Catalog\Api\CategoryRepositoryInterface in it's constructor. Getting the same error.

**Comment by lbajsarowicz** [comment] 2020-05-25 10:31
Thanks for your report @PascalBrouwers , reopening the issue for further investigation and fix.

**Comment by PascalBrouwers** [comment] 2020-05-25 11:16
Nevermind. I see now the CategoryRepositoryInterface was added to the \Magento\CatalogWidget\Block\Product\ProductsList constructor.

I did not update the parent::__construct call accordingly.

@lbajsarowicz  you can close the issue

**Closed as completed** 2020-05-25 12:52 UTC
Labels: Issue: Format is valid, Reported on 2.3.5-p1
