### ISSUE TITLE
Catalog product action multi select search label icon alignment issue 

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#19642] opened 2018-12-08 09:42 UTC
### Preconditions (*)

1. Magento 2.3 Develop

### Steps to reproduce (*)

1. Admin -> Catalog -> Products -> Open any product ->  click onAttribute Set 

### Expected result (*)

1. Search icons should be aligned properly it is a little bit cut from the bottom side.
2. It should be looking consistency like top search icon. http://prntscr.com/lsaev1

### Actual result (*)

1. http://prntscr.com/lsadyz

**Comment by magento-engcom-team** [comment] 2018-12-08 09:42
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-12-20 18:01
@shikhamis11 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97269` were created

**Comment by magento-engcom-team** [comment] 2019-01-07 19:15
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#19643 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [f72c0133edd733dfa2526860e2e0414e6e0d626b](https://github.com/magento/magento2/commit/f72c0133edd733dfa2526860e2e0414e6e0d626b)
 - [f49c56952484d268b5b9cc4fa12d994e5dac8b43](https://github.com/magento/magento2/commit/f49c56952484d268b5b9cc4fa12d994e5dac8b43)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-07 19:15 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
