### ISSUE TITLE
Session size of 276672 exceeded allowed session max size of 256000 - but in Magento 2.4.3 backend

### ISSUE THREAD

**Issue by groomershop-mt** [magento/magento2#33748] opened 2021-08-11 11:38 UTC
**UPDATE**: as per discussion, we agreed that is ok to have a low limit for session size to prevent DDOS attacks, value can be changed via the admin panel if needed. 
Another problem that should be addressed is - suppressed problem, without any error notification to the user and solution for the issue should be provided. 

After upgrading to Magento 2.4.3, when we log into backend (admin panel), everypage hangs/is loading about 30 seconds.

In logs we see exceptions:
Session size of 276672 exceeded allowed session max size of 256000.

We are ursing Redis for sessions.

Does anybody else have similar issue after upgrading to Magento 2.4.3?

From redis-cli monitor we see that in each second is repeated:
1628681344.757076 [3 127.0.0.1:34310] "hincrby" "sess_1g2sgh25saul85a424puad785d" "lock" "1"

### Steps to reproduce (*)
Upgrade Magento 2.4.2-p1 to 2.4.3
Configured Magento to use Redis for session storage
Stores -> Configuration -> Advanced -> System -> Security - Max Session Size in Admin and Max Session Size in Storefront set to 100 and Saved
Navigate to any page from Admin -

### Expected result (*)
 It should not break/impact any store functionality
### Actual result (*)
Page load time is increased to more than 30 sec

**Comment by jorgb90** [comment] 2021-08-11 12:06
Confirmed! Exact same issue here after upgrade to Magento 2.4.3!

**Comment by groomershop-mt** [comment] 2021-08-11 12:15
From https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/reference.html
We have found that a field/setting  e.g. system/security/max_session_size_admin has been added.
It's default value is 256000. After increasing it, the problem is solved.

Now the sesssion record is being saved - it has size over 256000. We have check this record and there is a lot of date with privileges settings - we have quite a lot of extensions installed, so there is more privileges, then in clear Magento setup.

**Comment by jorgb90** [comment] 2021-08-11 12:34
Yes thats it. Why not set it as "0" to disable it? What can go wrong?

**Comment by achatpc** [comment] 2021-08-11 13:04
Hello,

Same issue,

I have edit:

/vendor/magento/module-security/etc/config.xml

....
        <system>
            <security>
                <max_session_size_admin>512000</max_session_size_admin>
                <max_session_size_storefront>512000</max_session_size_storefront>
            </security>
        </system>
....

**Comment by in-session** [comment] 2021-08-11 14:17
Had this morning also the same problem, the value should be set in any case high or to 0

**Comment by achatpc** [comment] 2021-08-11 15:00
You can also change this in your /app/etc/env.php for avoid lock issues:

'disable_locking' => '0', to 'disable_locking' => '1' in your redis session settings section

**Comment by timpea** [comment] 2021-08-12 10:58
Same problem here, when trying to create an order in the admin, could add the 1st product fine, adding any additional products to the order would cause it to hang.  @achatpc fix above worked

**Comment by mrtuvn** [comment] 2021-08-12 16:06
Weird thing i still got admin work without any hang  or loading long
Setup redis session and cache frontend as default. All caches enabled in developer mode

preconditions 
bin/magento config:set web/secure/offloader_header X-Forwarded-Proto
bin/magento config:set web/secure/use_in_frontend 1
bin/magento config:set web/secure/use_in_adminhtml 1
bin/magento config:set web/seo/use_rewrites 1

Updated to 2.4.3
then set max_session_size_admin to 1000

Log show 
[2021-08-12 16:02:54] main.WARNING: Session size of 87533 exceeded allowed session max size of 1000. [] []
Do i miss something! Can this issue reproduce in local test server

**Comment by mrtuvn** [comment] 2021-08-12 16:15
Look likes updates in this commit
https://github.com/magento/magento2/commit/c2a591c4b5e382057260ee2199d133e094762ed8

**Comment by n2diving-dgx** [comment] 2021-08-14 00:43
Upon upgrading from 2.3.7 to 2.4.3 I was unable to complete an admin login, the MFA would succeed and then loop back to asking for the MFA again.  Chased this for hours thinking it was a MFA issue.   Simply disabling Two Factor Authentication would allow a successful login and all looked good.    The looping on MFA was apparently related to the session limit issue.   The default value for 'session limit' was 256000 and needs to be much larger at least for our installation.    Increased to 512000, which resolved the issue.

**Comment by marvinhinz** [comment] 2021-08-16 13:33
Having the same issue after upgrading to 2.4.3

**Comment by mrtuvn** [comment] 2021-08-16 13:44
Yes problem still exist but curiously if we put value to something does magento will got session size go beyound of that ??

**Comment by marvinhinz** [comment] 2021-08-16 14:10
@mrtuvn it seems its the write call is only executed when the size is not exceeded yet or the max size is null. 

https://github.com/magento/magento2/blob/c2a591c4b5e382057260ee2199d133e094762ed8/lib/internal/Magento/Framework/Session/SaveHandler.php#L130

If the max size is exceeded, the current session data is retrieved and saved again, this seems to create a loop thats constantly locking the session handler. @michaelyu0123 can you maybe explain the idea / intended behaviour behind this?

**Comment by michaelyu0123** [comment] 2021-08-16 17:26
@marvinhinz It is as you said, the original intention was just to set the session content to what is already stored. However this was a missed case in which if the session size prior to upgrade is already above our default session size limitation. A bug is opened internally to resolve this issue. Thank you.

**Comment by michaelyu0123** [comment] 2021-08-16 17:32
@marvinhinz It is as you said, the original intention was just to set the session content to what is already stored.
@groomershop-mt, could you please provide the steps to reproduce this issue? Thank you.

**Comment by marvinhinz** [comment] 2021-08-16 17:45
@michaelyu0123 wouldnt it be sufficent to just discard the "to-be-saved" data and throw an exception when the limit is reached?

**Comment by michaelyu0123** [comment] 2021-08-16 18:12
@marvinhinz, that is something that will be looked into once we are able to fully reproduce the issue internally. Thanks.

**Comment by aaronsilber** [comment] 2021-08-16 18:29
We are experiencing what look to be very similar symptoms to the bug described here, but on Magento 2.3.7-p1. It looks like the changes to SaveHandler.php are also present in this security-only release.

**Comment by pmonosolo** [comment] 2021-08-16 19:58
My issue was showing up as a different error:
A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

^^^ this would pop up on every admin page.

The URL that was failing:
http://magento.test/admin/mui/index/render/key/479b831574442521ca469efdc376886fde3c57d23eebbaced4a6a7f65a44bf10/?namespace=notification_area&sorting[field]=created_at&sorting[direction]=asc&isAjax=true

^^^ looks like it was some kind of notification area Ajax update. Notification area where "indexers are invalid" shows up was not there so, no data was coming through. 

The response to the error was:
UI component could not be rendered because of system exception
error code: "0"

In exception logs, I was getting:
[2021-08-13 22:48:42] main.CRITICAL: Unable to unserialize value. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value. at /var/www/php/vendor/magento/framework/Serialize/Serializer/Serialize.php:35)"} []

Security session setting to 512000 did not work. Only after I set it to 0 it worked.

**Comment by DuckThom** [comment] 2021-08-18 13:45
I was running into the same issue on the admin panel on a couple of projects. I noticed that Magento dumps the entire admin user model + relations (namely, all the ACL permissions) into the session, which is a lot of data. Currently our average admin session size seems to be around 543000 without any special modifications to the admin panel. If this is also the case on clean installations (in our case, we're using Commerce) then the default value of 256000 seems to be way too low.

**Comment by birdman002** [comment] 2021-08-18 20:10
This issue took me a week to figure out when we got access to it in July (Commerce) finally realizing like DuckThom said it dumps literally all the ACL permissions into the session. Default 256000 seems like a lot but when its all the ACL info then it renders TFA useless as well we can't edit order because of this issue. You can replicate this issue by assigning like 7-9 admin user roles to one person and then try logging into the admin with it. Hoping support can provide a fix for this. This is delaying our upgrade to this version

**Comment by hostep** [comment] 2021-08-18 20:29
@nathanjosiah: tagging you in here, you might be interested in this, especially in the previous comment.

**Comment by nathanjosiah** [comment] 2021-08-18 23:32
@hostep thanks for the heads up. Looking into this

**Comment by WebHostingAce** [comment] 2021-08-19 12:17
I was having the same issue. 2.4.3 admin hangs randomly. I will try the session "Max Session Size in Admin" set to 0. Thank you everyone who involved in this.

**Comment by refueledinc** [comment] 2021-08-19 12:33
I'm having the same issue with M2.4.3 and admin taking 30 seconds and Redis showing locking happening.

Any chance you guys have Amasty and Mirasvit extensions? If so, could you share which ones? I've been debugging this issue for over 20 hours and see some oddities in Redis monitor especially with mirasvit.

**Comment by birdman002** [comment] 2021-08-19 18:26
@refueledinc we do have amasty extensions, but this issue can be replicated on a vanilla instance of 2.4.3. Take a look at your ACL permissions if you have a lot of user roles that will cause this issue to happen. Magento is storing all the ACL role resources in the session data. I have no tried any of the above solutions of changing the session size

**Comment by refueledinc** [comment] 2021-08-20 09:19
@birdman002 I wasn't able to replicate on vanilla magento despite having 8 roles. However, the issue does happen when I start enabling amasty/mirasvit modules. I do agree it appears to be ACL and session related. For now, increasing the value of "Max Session Size in Admin" fixed the problem for me.

**Comment by kovalchukVM** [comment] 2021-08-20 11:26
faced the same issue on Magento commerce `v.2.3.7-p1` and Redis used for session, as @marvinhinz wrote above the issue is in `write` function in file
[lib/internal/Magento/Framework/Session/SaveHandler.php](https://github.com/magento/magento2/blob/c2a591c4b5e382057260ee2199d133e094762ed8/lib/internal/Magento/Framework/Session/SaveHandler.php)
```php
    public function write($sessionId, $data)
    {
        $sessionMaxSize = $this->sessionMaxSizeConfig->getSessionMaxSize();
        $sessionSize = strlen($data);

        if ($sessionMaxSize === null || $sessionMaxSize >= $sessionSize) {
            return $this->callSafely('write', $sessionId, $data);
        }

        $this->logger->warning(
            sprintf(
                'Session size of %d exceeded allowed session max size of %d.',
                $sessionSize,
                $sessionMaxSize
            )
        );

        return $this->callSafely('write', $sessionId, $this->read($sessionId));
    }
```
at the moment when Magento calls `write($sessionId, $data)` the session is still locked by the previous call of
https://github.com/magento/magento2/blob/c2a591c4b5e382057260ee2199d133e094762ed8/lib/internal/Magento/Framework/Session/SaveHandler.php#L100


supposed that lock will be released here
https://github.com/magento/magento2/blob/c2a591c4b5e382057260ee2199d133e094762ed8/lib/internal/Magento/Framework/Session/SaveHandler.php#L119
but in case `$sessionSize` is higher than `$sessionMaxSize` the session will be read once again
https://github.com/magento/magento2/blob/c2a591c4b5e382057260ee2199d133e094762ed8/lib/internal/Magento/Framework/Session/SaveHandler.php#L130
which actually can not be done as it is still locked by the previous call. Then depending on Redis setting `break_after_adminhtml` (which is 30 by default) the process gets into the loop and waits that time, then takes the lock to read session data.

I don't really see any point in reading session data again, as we already have it loaded in `$data`, also it causes the session to be locked.

I believe the `public function write($sessionId, $data)` should be like
```php
    public function write($sessionId, $data)
    {
        $sessionMaxSize = $this->sessionMaxSizeConfig->getSessionMaxSize();
        $sessionSize = strlen($data);

        if (null !== $sessionMaxSize && $sessionSize >= $sessionMaxSize) {
            $this->logger->warning(
                sprintf(
                    'Session size of %d exceeded allowed session max size of %d.',
                    $sessionSize,
                    $sessionMaxSize
                )
            );
        }

        return $this->callSafely('write', $sessionId, $data);
    }
```

**Comment by kovalchukVM** [comment] 2021-08-20 11:57
the issue can be simply reproduced even for the frontend:

- go to admin panel Stores -> Configuration -> Advanced -> System -> Security
- set `Max Session Size in Storefront` to some small number like `100`
- clear the case
- visit e.g. `/checkout/cart/` page 
- it load time is increased ~30 seconds.

I'm pretty sure that `Max Session Size` was intended to let devs know that session size has increased by adding warning message to logs, and anyway it should not break/impact any store functionality

**Comment by convenient** [comment] 2021-09-06 16:30
Seen on 2.3.7-p1

**Comment by engcom-November** [comment] 2021-09-07 14:48
Verified the issue after upgrading from 2.4.2-p1 to 2.4.3 and the issue is reproducible with below steps:
Stores -> Configuration -> Advanced -> System -> Security -Max Session Size in Admin is set to 100 and saved
Configured Magento to use Redis for session storage
Stores -> Configuration -> Advanced -> System -> Security - Max Session Size in Admin and Max Session Size in Storefront set to 100 and Saved
Navigate to any page from Admin - 
Issue: Page load time is increased to more than 30 sec

**Comment by oneserv-heuser** [comment] 2021-11-16 13:40
@ihor-sviziev Can you please reopen this ticket. It's still an issue and the solution provided is not convinent. We're experiencing the issue after adding multiple user roles (acl). Then every user which has specific rights cannot login to the adminhtml anymore or its very slow. Admin users with full rights can still login easily.

Confirmed on magento 2.4.3-p1.

**Comment by ihor-sviziev** [comment] 2021-11-17 09:51
The issue is still not resolved.

On Magento 2.3.7-p2, the admin user mode is getting saved into the session. That significantly increases the size of the session. Custom extensions also write some data to the session, even when no data is stored.

I think we should re-open this issue for further investigation.
/CC @sidolov @kandy

**Comment by ihor-sviziev** [comment] 2021-11-17 09:56
@sidolov, could you check why the issue can't be exported to Jira after re-opening the Github case?

**Comment by sidolov** [comment] 2021-11-17 19:39
@ihor-sviziev because the issue already exists, it was re-opened.

**Comment by engcom-Hotel** [comment] 2021-11-30 10:32
Hello @groomershop-mt,

As per the expert advice, limiting max session size was introduced as a DDOS measure and the session size can be increased via the admin panel. I don't think any change is required for this ticket.

Hence we are closing the issue.

Thanks

**Comment by oneserv-heuser** [comment] 2021-11-30 11:01
@engcom-Hotel Why? @ihor-sviziev reopened the ticket 13 days ago and stated that the issue is not resolved. So please reopen this ticket and leave it open until a **real** solution is provided. This ticket is getting ridicolous.

**Comment by marvinhinz** [comment] 2021-11-30 12:26
@engcom-Hotel please read the issue comments again carefully. The problem is not resolved. The session limit is okay, but its not okay to have an unresponsive application without appropriate error message when the limit is exceeded.

**Comment by drew7721** [comment] 2021-12-09 21:07
Hello,

Just want to report that this is also happening in version `2.3.7-p2`

It would be nice to mention this in the release notes as currently there is no mention at the moment.

**Closed as completed** 2021-12-23 12:58 UTC
Labels: Issue: Confirmed, Component: Backend, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.4.3, Area: Performance, Area: Upgrades - Upgrade Compatibility Tool

**Comment by ihor-sviziev** [comment] 2021-12-23 13:19
@sidolov @sivaschenko  why this issue was closed without any comments?

**Comment by hostep** [comment] 2021-12-23 13:26
It's probably because of [AC-1170 Session size of 276672 exceeded allowed session max size of 256000](https://github.com/magento/magento2/commit/1b84b623f36282e9a95eddbb8205b8d45a9ca77b) which got merged an hour ago.

It would also be very nice if an answer could come to [this question I posted yesterday](https://github.com/magento/magento2/issues/34064#issuecomment-999628356).

**Comment by mrtuvn** [comment] 2022-01-08 02:53
![new-message](https://user-images.githubusercontent.com/1908873/148629038-23f6396d-ece0-44cb-803c-f129ab25a6c1.png)
Now how we deal with this. Tested in latest code base

**Comment by tuyennn** [comment] 2022-05-11 15:34
Confirm it was still on 2.4.3-p2 anyone could update this ticket status?

**Comment by evs-xsarus** [comment] 2022-06-01 09:41
@mrtuvn that seems to be fixable by setting the frontend max session size because of this check: https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Session/SaveHandler.php#L133

```
./bin/magento config:set system/security/max_session_size_admin 1048576
./bin/magento config:set system/security/max_session_size_storefront 1048576
```

Replace 1048576 with a size you that suits you.
