### ISSUE TITLE
Bug on category count (performance issue)

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#34109] opened 2021-09-17 10:08 UTC
In src/vendor/magento/module-catalog/Model/ResourceModel/Category/Collection.php

Line 330-333 :

```
                $productsCount = isset($categoriesProductsCount[$item->getId()])
                    ? (int)$categoryProductsCount[$item->getId()]
                    : $this->getProductsCountFromCategoryTable($item, $websiteId);
```

should be 

```
                $productsCount = isset($categoryProductsCount[$item->getId()])
                    ? (int)$categoryProductsCount[$item->getId()]
                    : $this->getProductsCountFromCategoryTable($item, $websiteId);
```

( categoriesProductsCount instead of categoryProductsCount )

This is causing performance issue on backend category page especially when having a big amount of categories/products.

**Comment by ihor-sviziev** [comment] 2021-09-17 10:26
Hi @Nuranto,
Could you create a PR with suggested changes and add a bit more info on how to reproduce it?

**Comment by Nuranto** [comment] 2021-09-17 12:03
There is nothing to reproduce since it is just a performance issue.

Actually, I did more tests and it seems the table `catalog_category_product_index` is used for fetching pairs, but that table seems deprecated, so that fix doesn't fix performance issue after all by its own. It's quite difficult to use it since there is no index for admin store. But I will make a PR for this.

**Comment by engcom-Hotel** [comment] 2022-08-29 08:36
Hello @Nuranto,

Thanks for the report and collaboration!

We have verified the issue by looking into the codebase and we have found that the variable with the name `$categoriesProductsCount` is not defined anywhere in its scope. But we are using `isset` method on that, due to this it is not giving any error and simply calling `$this->getProductsCountFromCategoryTable($item, $websiteId)` method. 

The correct variable name should be `$categoryProductsCount` instead of `$categoriesProductsCount`. Hence confirming the issue.

Thanks

**Comment by damienwebdev** [comment] 2023-04-07 19:43
@Nuranto's original analysis here is correct. There was a bug fixed by https://github.com/magento/magento2/pull/35216

However, the actual problem here is **not fully corrected by** https://github.com/magento/magento2/pull/35216 but #35216 is part of the fix.

@Nuranto goes on to explain here: https://github.com/magento/magento2/pull/35216#issuecomment-1371194515 the actual issue in v2.4.3+ - including current `2.4-develop`).

To be even more clear he was even kind enough to provide a PR here (that was closed): https://github.com/magento/magento2/pull/34111

In essence, for triage, the bug is as follows:

When Magento goes to compute the "edit category" screen for the root category, it loads a list of all of the categories to fulfill the tree UI structure. Importantly, part of the information retrieved for those categories is the number of products in that category. 

Currently, because of two separate bugs, this computation is prohibitively expensive and (for me) results in the entire "Edit Categories" UI to be completely unusable.

The bugs are as follows:

1. A typo in the code remedied by https://github.com/magento/magento2/pull/35216
2. A completely inaccurate table name `catalog_category_product_index` that should be `catalog_category_product_index_{WEBSITE_ID}`

@Nuranto was kind enough to fix the second one here: https://github.com/magento/magento2/pull/34111

**Comment by damienwebdev** [comment] 2023-04-08 14:43
Additionally, in all likelihood, the original indexer here should be re-worked to use common table expressions as it is now supported in all major versions of db's currently supported by Magento (and Laminas DB has support for it).

```
with recursive category_tree (entity_id, parent_id) as (
  select     entity_id,
             parent_id
  from       catalog_category_entity
  where      parent_id = 1
  union all
  select     c.entity_id,
             c.parent_id
  from       catalog_category_entity c
  inner join category_tree
          on c.parent_id = category_tree.entity_id
)
select * from category_tree;
```

**Comment by Nuranto** [comment] 2023-04-10 07:59
@damienwebdev Thank you, I feel less lonely on this :p

**Comment by damienwebdev** [comment] 2023-04-10 12:31
@Nuranto that's a really interesting insight that I had not considered. There's likely a decent number of individuals with older databases where this table was never truncated and, as a result, the data probably looks somewhat correct (although in reality it is completely nonsensical).

Thanks for this realization, it will probably help along the way.

**Comment by engcom-Bravo** [comment] 2023-12-15 05:24
Hi,

internal team started working on this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-04 08:50
Hi @Nuranto,

We have checked this issue on magento 2.4-develop and As per the latest codebase and we have found that the variable $categoriesProductsCount name has been changed and the issue no longer reproducible. Hence we are closing this issue.Please find the attached screenshot for your references.

![Screenshot 2023-12-14 at 6 40 09 PM](https://github.com/magento/magento2/assets/51680745/8f7eeb4f-362d-4946-80f0-e6306a05d28a)


Thanks.

**Comment by ihor-sviziev** [comment] 2024-01-04 14:54
Hi @engcom-Bravo,
I double-checked - the change was merged in https://github.com/magento/magento2/pull/35216.
The last comment states that it's not fixing the original issue https://github.com/magento/magento2/pull/35216#issuecomment-1625154983.


So the correct fix should be porting changes from https://github.com/mage-os/mageos-magento2/pull/25 + https://github.com/mage-os/mageos-magento2/pull/47.

I think we should re-open this issue

**Comment by Nuranto** [comment] 2024-01-08 07:42
Hi @engcom-Bravo,

I agree with @ihor-sviziev's answer. The typo is fixed, but does not fix the real issue.

**Comment by engcom-Bravo** [comment] 2024-01-10 07:47
@ihor-sviziev Thanks for reopening the issue.

Hi @Nuranto,

Could you please update the description with the steps to reproduce and also Expected result and Actual result it will help us to proceed further.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-10-30 06:11
Hi @Nuranto,

This issue is being closed since it has not been updated in a long time.Please feel free to reopen or raise a new ticket if the issue still exists.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-30 06:11 UTC
Labels: Triage: Dev.Experience, Priority: P2, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Framework
