### ISSUE TITLE
GraphQL: Retrieve a simple product when querying for a url_key of a simple product that has a parent configurable product

### ISSUE THREAD

**Issue by lilbumblebear** [magento/magento2#34052] opened 2021-09-10 14:18 UTC
*As a developer, when I use the products query for url_key and search for a simple product with a parent configurable product, I want to get back the simple product (if it is available in the website) not the configurable product.*

Ex: In default Magento, if I have a simple product that is a part of a configurable product, and the simple product is set to "Search, Catalog or Catalog/Search" visibility, I can get to a webpage for the simple product only.

However, in graphql, if I try to retrieve the product for the simple product's url_key or sku, I get the configurable product back.

**Comment by shikhamis11** [comment] 2021-10-09 14:33
@lilbumblebear Thank you for reporting this issue 
I tried reproducing this issue It is only showing additional data while filtering products with `url_key`
the product filter works fine if you are searching with `sku`
also, I find one other issue https://github.com/magento/magento2/issues/33623 
both seem similar. Please check if both are the same then we can close this one

**Comment by engcom-November** [comment] 2021-12-02 12:30
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Steps performed:
Created Simple Product and assigned to Configurable Product
Ran Below GraphQL query for Simple Product - No issue: Simple Product Response is retrieved.
Products Query used:
`
{
  products(filter: { sku: { eq: "testsimple1111" } }) {
    items {
      name
      sku
      url_key
      stock_status
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    total_count
    page_info {
      page_size
    }
  }
}
`
![image](https://user-images.githubusercontent.com/60198231/144422193-0976bb00-988e-48f2-9726-6c95b2eb7f29.png)
@lilbumblebear kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-12-16 13:05
Hi @lilbumblebear ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-12-16 13:05 UTC
Labels: Issue:  Cannot Reproduce, Project: GraphQL, Issue: needs update
