### ISSUE TITLE
Translate attribute in html files doesnt work when using colon as part of the value

### ISSUE THREAD

**Issue by Januszpl** [magento/magento2#24546] opened 2019-09-10 22:16 UTC
### Preconditions (*)
Magento 2.3.1 (possible 2.3.2)

### Steps to reproduce (*)
1. Add product to cart
2. Open mini cart (no errors in console)
3. Edit minicart/content.html in Magento Checkout module  and add here
`<span class="text" translate="'My Cart'"/>`
colon sign as part of value for translate attribute
`<span class="text" translate="'My Cart:'"/>`

### Expected result (*)
1. show translation and no error in console

### Actual result (*)
1. JS error
```
Uncaught SyntaxError: Unable to parse bindings.
Bindings value: i18n: {'My Cart:'}
Message: Unexpected token }
    at new Function (<anonymous>)
    at createBindingsStringEvaluator (knockout.js:2992)
    at createBindingsStringEvaluatorViaCache (knockout.js:2983)
    at ko.bindingProvider.parseBindingsString (knockout.js:2969)
    at ko.bindingProvider.getBindingAccessors (knockout.js:2951)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3310)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2183)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2150)
    at Function.evaluateImmediate (knockout.js:2111)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1964)
```

### Extra info:
Using data-bind or ko comments work as expected

**Comment by marcelo011982** [comment] 2019-09-14 14:23
#mm19br

**Comment by magento-engcom-team** [comment] 2019-09-14 14:23
@marcelo011982 thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by engcom-Charlie** [comment] 2019-10-11 13:23
Hello @Januszpl 

We are not able to reproduce this issue on the lates 2.3-develop.

**Manual testing scenario:**
1. Add product to cart
2. Open mini cart (no errors in console)
3. Edit minicart/content.html in Magento Checkout module  and add here
`<span class="text" translate="'My Cart'"/>`
colon sign as part of value for translate attribute
`<span class="text" translate="'My Cart:'"/>`
![image](https://user-images.githubusercontent.com/51680850/66643834-3bf0e200-ec28-11e9-8f43-8b23d03f9b03.png)

4. Clear cache 
5. Add product to cart again 
6. Check console

**Actual result:**
Show translation and no error in console
![image](https://user-images.githubusercontent.com/51680850/66641280-190fff00-ec23-11e9-9453-b7e0345a6a3f.png)

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-11 13:23 UTC
Labels: Issue: Format is valid, Event: mm19br
