### ISSUE TITLE
"User Error: expected iterable, but did not find one for field CategoryTree.children" after saving a parent category through CategoryRepository

### ISSUE THREAD

**Issue by drc0** [magento/magento2#30668] opened 2020-10-27 18:20 UTC
I have a parent_category and subcategory, If I use Magento\Catalog\Api\CategoryRepositoryInterface::save this stores in the catalog_category_entity_text table the children attribute value for the parent_category and subcategory entities.

Subsequent calls to Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\CategoryTree::getTree fails.

Using $category->save() does not create the record in catalog_category_entriy_text and the call to getTree above returns children data.

An example could be using the following graphql query:

```
query{
  category(id: 9){
    children {
      id
    }
    id
  }
}
```

### Preconditions (*)
1. Magento 2.4.0

### Steps to reproduce (*)
1. Create a category and subcategory
2. Save the parent category through the category repository 
3. Query the graphql endpoint with the above query and notice the error

### Expected result (*)
1. Children data to be returned as the category whould have been saved withtout the repository ($category->save())

### Actual result (*)
1.  main.ERROR: User Error: expected iterable, but did not find one for field CategoryTree.children. {"exception":"[object] (GraphQL\\Error\\Error(code: 0): User Error: expected iterable, but did not find one for field CategoryTree.children. at /var/www/html/m24/vendor/webonyx/graphql-php/src/Error/Error.php:174, GraphQL\\Error\\InvariantViolation(code: 0): User Error: expected iterable, but did not find one for field CategoryTree.children. at /var/www/html/m24/vendor/webonyx/graphql-php/src/Utils/Utils.php:319)"} []

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by rahulbarot** [comment] 2020-10-31 13:25
@drc0 I have followed steps to reproduce the issue on M2.4.0 and i found that initially there is no record with children attribute in catalog_category_entity_text table, but when i saved the category using Magento\Catalog\Api\CategoryRepositoryInterface::save it creates new record with parent id and it's subcategories as value.Check the below code I've tried

$categoryRepository = $objectManager->create('Magento\Catalog\Api\CategoryRepositoryInterface');
$category = $categoryRepository->get(9);
$category->setName('Demo');
$categoryRepository->save($category);

**Comment by drc0** [comment] 2020-10-31 14:09
@rahulbarot thanks for the answer, can you tell me now in your case, after rthe repository save and having checked that the table catalog_category_entity_text table has the children row, a graphql query like this one what returns?

```
query{
  category(id: 9){
    children {
      id
    }
    id
  }
}
```

what about the same query **before** the repository save (or by deleting the row in the mentioned table).

thanks

**Comment by rahulbarot** [comment] 2020-11-02 05:27
Before repository save it returns the result as expected, but after save it shows internal server error and following log is generated in exception.log
`main.ERROR: User Error: expected iterable, but did not find one for field CategoryTree.children. {"exception":"[object] (GraphQL\\Error\\Error(code: 0): User Error: expected iterable, but did not find one for field CategoryTree.children. at /var/www/html/m24/vendor/webonyx/graphql-php/src/Error/Error.php:174, GraphQL\\Error\\InvariantViolation(code: 0): User Error: expected iterable, but did not find one for field CategoryTree.children. at /var/www/html/m24/vendor/webonyx/graphql-php/src/Utils/Utils.php:319)"} []`

**Comment by drc0** [comment] 2020-11-02 08:18
@rahulbarot thank I've updated the initial issue with correct statements.

**Comment by rut4** [comment] 2020-11-27 15:40
The issue is related to the method of `\Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\ExtractDataFromCategoryTree::mergeCategoriesTrees`.

The hotfix is adding at the top of the method the following code:
```php
if (isset($tree2['children']) && is_string($tree2['children'])) {
     unset($tree2['children']);
}
```
It's a quick fix so I suppose the solution should be refined.

**Comment by danslo** [comment] 2021-03-18 13:56
Can confirm this bug, although in a slightly different variation.

Please see https://github.com/magento/magento2/pull/28209/files

The patch in above PR also fixes this issue.

**Comment by drc0** [comment] 2021-03-18 14:08
> Can confirm this bug, although in a slightly different variation.
> 
> Please see #28209
> 
> The patch in above PR also fixes this issue.
> 
> ```diff
> diff --git a/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php b/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> index b38a2c9bb04d..daafe0047b30 100644
> --- a/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> +++ b/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php
> @@ -53,6 +53,7 @@ public function execute(\Iterator $iterator): array
>          while ($iterator->valid()) {
>              /** @var CategoryInterface $currentCategory */
>              $currentCategory = $iterator->current();
> +            $currentCategory->setCustomAttribute('children', []);
>              $iterator->next();
>              if ($this->areParentsActive($currentCategory, $rootCategory, (array)$iterator)) {
>                  $pathElements = explode("/", $currentCategory->getPath());
> ```

I would rather not set a default value for children, I think that is expected to be not set if empty, but probably is is a nuisance specific to my codebase that uses scandipwa on frontend

**Comment by danslo** [comment] 2021-03-18 14:46
> I would rather not set a default value for children, I think that is expected to be not set if empty, but probably is is a nuisance specific to my codebase that uses scandipwa on frontend

I can see an argument for both `null` as well as an empty array. I'll leave it up to core devs capable hands :)

**Comment by engcom-Hotel** [comment] 2021-11-25 12:46
Hello @drc0,

Please try to reproduce this issue in Magento 2.4-develop and let us know if this is still reproducible for you.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-24 08:50
Dear @drc0,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-24 08:50 UTC
Labels: Component: CatalogGraphQl, Project: GraphQL, Issue: needs update, Reported on 2.4.0

**Comment by TELESONOSATELLITE** [comment] 2021-12-24 08:55
Bonjour, je suis intéressé de acheter une copie légal magento2 comment ?

**Comment by przmak** [comment] 2022-06-08 11:28
Currently having this on ver. 2.4.2-p2
