### ISSUE TITLE
"Add to Cart" button should not be shown if the salable quantity is 0 or less

### ISSUE THREAD

**Issue by MeeranKasvala** [magento/magento2#38905] opened 2024-07-05 06:07 UTC
### Preconditions and environment

- Magento version 2.4.4-p8

### Steps to reproduce

- Make an order of a product and buy everything 
- Example Product qty is 1  in stock, buy 1
- Go to magento admin and this product QTY should be 1 and Salable QTY should be 0.

### Expected result

- We should NOT have the "add to cart" Button

### Actual result

- Add to cart button is available
- When we try to cart, we get a message "**The requested qty is not available**".

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-07-05 10:00
Hi @MeeranKasvala,

Thanks  for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and we are able to see the add to cart button.Kindly refer the screenshots.

<img width="1429" alt="Screenshot 2024-07-05 at 12 49 21" src="https://github.com/magento/magento2/assets/51680745/53e8417c-3dc9-42e0-98d3-c4683df30b1b">



<img width="1429" alt="Screenshot 2024-07-05 at 12 49 29" src="https://github.com/magento/magento2/assets/51680745/510bac38-079d-403a-92b8-7930adf73143">


For out of stock products there will be no add to cart button.We can see by enabling Backorders under advanced inventory for salable quantity 0.

Kindly let us know if you are still facing any issue.

Thanks.

**Comment by MeeranKasvala** [comment] 2024-07-05 11:50
Hello @engcom-Bravo

Thanks for response

We have checked that the backorder service is disabled, but the "Add to Cart" button is still showing.

If the backorder service is enabled, orders can be placed successfully.

However, if backorders are enabled and we try to place an order, we encounter an error when pressing the "Add to Cart" button:

**Error Message: "The requested qty is not available."**

**Comment by engcom-Bravo** [comment] 2024-07-10 05:26
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-10 06:17
Hi @MeeranKasvala,

Thanks for your update.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Make an order of a product and buy everything
- Example Product qty is 1 in stock, buy 1
- Go to magento admin and this product QTY should be 1 and Salable QTY should be 0.



<img width="1431" alt="Screenshot 2024-07-10 at 11 16 04" src="https://github.com/magento/magento2/assets/51680745/f1690966-3f69-4a87-829d-cb4b4526b34b">



<img width="1382" alt="Screenshot 2024-07-10 at 11 16 42" src="https://github.com/magento/magento2/assets/51680745/d6fc3639-34f6-47c3-bc66-d4be0f6057c0">



There is no Add to Cart button for the product.

Kindly check the issue in Latest 2.4-develop instance and elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-07-22 08:12
Hi @MeeranKasvala,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-22 08:12 UTC
Labels: Issue: needs update, Reported on 2.4.4-p8
