### ISSUE TITLE
Footer not showing on content pages

### ISSUE THREAD

**Issue by ThwQwirkyShop** [magento/magento2#32803] opened 2021-04-21 11:10 UTC
Hi,

Version: Magento ver. 2.4.2

When I have created a new page via "Content > Pages > new page" - The footer does not show on these pages. 

There is no footer on this page: https://qwirkyshop.com/terms-and-conditions

Please advise? 

Thanks in advance.

**Comment by mrtuvn** [comment] 2021-04-21 12:38
In this case i don't think this is magento issue
Please check from your side 
1/ Maybe page-footer block remove in page `terms-and-conditions`
2/ Some one accidently hide/remove it for specific page

**Comment by engcom-Oscar** [comment] 2021-04-26 10:06
Hi @ThwQwirkyShop ! Thank you for your report.
Unfortunately, we are not able to reproduce the issue on a fresh 2.4-develop by following steps from this ticket.
So, we have to close this ticket.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Oscar** 2021-04-26 10:06 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: ready for confirmation
