### ISSUE TITLE
How can I have Visual Swatch and Drop-down for Color attribute.

### ISSUE THREAD

**Issue by pbvkrishna** [magento/magento2#7071] opened 2016-10-18 13:25 UTC
I am trying to have Visual Swatch and Drop-Down for Color attribute on Product details page.

In the configuration, I see only one to select. Is there any way to have both or any customization is also fine.

Help me to get it fixed

**Comment by veloraven** [comment] 2016-11-01 17:43
@pbvkrishna 
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue than please create new GitHub report following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-01 17:43 UTC
