### ISSUE TITLE
Product query results issue : Bundle child product graphql

### ISSUE THREAD

**Issue by prabhakaran777** [magento/magento2#33623] opened 2021-07-29 08:01 UTC
### Preconditions (*)

1. Magento 2.4.2 with elastic search instance
2. Create Bundle Product
3. While fetching any one of child products in product query showing wrong data (items)

### Steps to reproduce (*)

1.Create Bundle product

![Screenshot 2021-07-29 at 13-12-37 Bundle Product Test 1 Products Inventory Catalog Magento Admin](https://user-images.githubusercontent.com/49685489/127452041-7962dccf-9df2-4f18-9846-71ecf3754dca.png)

2.Fetch any one of child product

Request 

   ```
{
  products(filter:{
    url_key:{
    eq:"bin-with-lid"
    }
  }){
    items{
      id
      name
      url_key
    }
  }
}
```

Response : 

```
{
  "data": {
    "products": {
      "items": [
        {
          "id": 194,
          "name": "Bundle product custom price",
          "url_key": "bundle-product-custom-price"
        },
        {
          "id": 193,
          "name": "Bundle Product Chair",
          "url_key": "bundle-product-chair"
        },
        {
          "id": 192,
          "name": "Bundle Product Test 1",
          "url_key": "bundle-product-test-1"
        },
        {
          "id": 4,
          "name": "Bin with lid",
          "url_key": "bin-with-lid"
        }
      ]
    }
  }
}
```

### Expected
 result (*)

1. Expected Result Must be only that product in items
2.   Response 
 ```
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "name": "Bin with lid",
          "url_key": "bin-with-lid"
        }
      ]
    }
  }
}
```

### Actual result (*)

1. Response : 

```
{
  "data": {
    "products": {
      "items": [
        {
          "id": 194,
          "name": "Bundle product custom price",
          "url_key": "bundle-product-custom-price"
        },
        {
          "id": 193,
          "name": "Bundle Product Chair",
          "url_key": "bundle-product-chair"
        },
        {
          "id": 192,
          "name": "Bundle Product Test 1",
          "url_key": "bundle-product-test-1"
        },
        {
          "id": 4,
          "name": "Bin with lid",
          "url_key": "bin-with-lid"
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by MyroslavDobra** [comment] 2021-07-29 10:10
@magento give me 2.3-develop instance

**Comment by shikhamis11** [comment] 2021-07-29 15:36
@magento give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2021-07-29 16:24
It only shows additional data while filter with `url_key`. Graphql for product filter works as expected with `sku`.

```
{
  products(filter: { sku: { eq: $sku } }) {
    items {
      id
      name
      url_key
    }
  }
}
```

**Comment by magento-engcom-team** [comment] 2021-07-29 16:25
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42941` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by korovitskyi** [comment] 2021-08-03 15:49
@magento I am working on this

**Comment by joggienl** [comment] 2021-11-18 16:31
@shikhamis11 is the behaviour of the graphql api intentional, that if I query for a product and use the `url_key` as filter, I get all products where this `url_key` is used?

This would explain why beside the SimpleProduct the BundleProduct (or ConfigurableProduct) where this SimpleProduct is also used, is returned. But it does not explain why it does not do this when you pass the `sku` as a filter.

I actually use this behaviour, because it is nice to know if a SimpleProduct is part of a ConfigurableProduct or BundleProduct, so I would like to know if it is intentional.

**Comment by joggienl** [comment] 2022-02-14 20:23
I am curious, I've asked my previous question some time ago. When using GraphQL to get products via the urlKey, why is getting the BundleProduct and/or ConfigurableProduct besides the SimpleProduct considered a bug?

When looking at this differently, if you would want to use the SimpleProduct to be able to identify any parent Product, how would you do that using GraphQL (or any other way)?

**Comment by IsraaMohamedTech** [comment] 2022-09-07 12:48
I still faced this issue

**Comment by engcom-Hotel** [comment] 2022-11-02 10:51
Hello,

We have received feedback for this ticket from PO and I think we should close this issue as not a bug because it really looks like it was designed intentionally, probably to support use cases when we need to support navigation from bundle PDP to its simple, so it's not a good idea to break this since there might be extensions which already using it.  

Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-11-02 10:51 UTC
Labels: Issue: Confirmed, Component: CatalogGraphQl, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Area: Product

**Comment by adarshkhatri** [comment] 2023-02-12 23:37
I disagree. If this is by design then why Luma is working otherwise? 

Luma works as expected. But GraphQl is over-smart and gives me parent product data. This is definitely not by design. Or perhaps a broken feature. 

Need a fix for sure.
