### ISSUE TITLE
PHP 7.0 feature of using 'self' as return type results in fatal error

### ISSUE THREAD

**Issue by allanpaiste** [magento/magento2#24443] opened 2019-09-04 10:42 UTC
This report addresses an issue that has been talked about before, but has not yet received a solution that would be viable in the long run as the focus has been mostly on making sure that Magento2 code does not use certain PHP7 features rather than making Framework fully capable of supporting all that PHP7 has to offer.

Therefore the description has been written in a form where existing code is manipulated with to make sure that there's no way to perceive this as a issue that deserves a solution of [removing the appearance of the problem](https://github.com/magento/magento2/commit/9c9a3fd069493c9e88406a4b6ee79d41835c8d2a) (which is fine as an isolated containment of the issue but I would humbly advise against closing the [ticket](https://github.com/magento/magento2/issues/22769) based on said containment).

Same issue reported in different scenarios in:

https://github.com/magento/magento2/issues/22769
https://github.com/magento/magento2/issues/23084
https://github.com/magento/magento2/issues/11905

This issue created on purpose to have an open issue on this topic as all that were previously reported have since been closed (with "fixed" flag).

### Environment
1. OS: Ubuntu 18.04.2 LTS (Bionic Beaver)

### Preconditions
1. Use any Magento release (report based on [2.3.2](https://packagist.org/packages/magento/community-edition#2.3.2), which at the time of reporting was the latest release), sample data not needed.
2. All generated files are removed (`rm -rf generated`)
3. Application deploy mode is on 'developer' (`bin/magento deploy:mode:set developer`)

### Steps to reproduce
1. [terminal] modify Magento\Framework\HTTP\PhpEnvironment\Response :: **setHeader** method by adding a 'self' return type to it:

   `sed -i 's/\(ion setHeader(.*\)/\1: self/g' vendor/magento/framework/HTTP/PhpEnvironment/Response.php`
1. [browser] navigate to the home page/main page of the store.

### Expected result
1. Page loads without any issues 
2. Looking at generated Interceptor class, one should see:

```
public function setHeader($name, $value, $replace = false) : 
\Magento\Framework\HTTP\PhpEnvironment\Response
```

### Actual result
1. Page load crashes with fatal error:

```
Fatal error: Declaration of Magento\Framework\App\Response\Http\Interceptor
::setHeader($name, $value, $replace = false): Magento\Framework\App\Response\Http 
must be compatible with Magento\Framework\HTTP\PhpEnvironment\Response
::setHeader($name, $value, $replace = false): Magento\Framework\HTTP\PhpEnvironment\Response 
in ../generated/code/Magento/Framework/App/Response/Http/Interceptor.php on line 7
```

2. Interceptor reads: 

```
public function setHeader($name, $value, $replace = false) : 
\Magento\Framework\App\Response\Http
```

**Comment by engcom-Charlie** [comment] 2019-09-05 06:39
Hello @allanpaiste !
I can't reproduce this issue with PHP 7.1. 

**Manual testing scenario:**

1. Used Magento 2.3.2
2. All generated files are removed (rm -rf generated)
3. Application deploy mode is on 'developer' (bin/magento deploy:mode:set developer)
4. [terminal] modify Magento\Framework\HTTP\PhpEnvironment\Response :: setHeader method by adding a 'self' return type to it:
`sed -i 's/\(ion setHeader(.*\)/\1: self/g' vendor/magento/framework/HTTP/PhpEnvironment/Response.php`
5. navigate to the home page/main page of the store.

We can't use PHP 7.0 with Magento 2.3.x because Magento 2.3 supports only PHP 7.1.3 & 7.2.0. 
![image](https://user-images.githubusercontent.com/51680850/64317602-e5f1a480-cfc0-11e9-88f4-167877e841b7.png)
https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html
So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-05 06:39 UTC
Labels: Issue: Format is valid

**Comment by allanpaiste** [comment] 2019-09-05 17:04
Hi,

The report refers to using Bionic Beaver distribution of Ubuntu which ships with 7.2.X, why you'd use any other version in the context where OS is specified is beyond me. 

I guess I should have specified the PHP version that this distribution ships with (7.2.19).

Could we have a discussion about the issue before deciding to close them? There are other tickets that have pointed out the same exact issue.

**Comment by allanpaiste** [comment] 2019-09-05 17:13
Changed scenario and added more details to the step. Would have gladly updated the steps on this issue if I had a chance before it got moved to DONE.
