### ISSUE TITLE
when try to Docker Image unable to create and  the Magento is not Bulding

### ISSUE THREAD

**Issue by Ayaanuddin** [magento/magento2#37449] opened 2023-05-02 04:45 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
Magento-2.4.2

### Steps to reproduce

we have reproduce so many times

### Expected result

when docker Image is created and when we try to connect to Database and Elastic search we are unable to process it

### Actual result

when docker Image is created and when we try to connect to Database and Elastic search we are unable to process it

### Release note

when docker Image is created and when we try to connect to Database and Elastic search we are unable to process it

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-02 12:30
Hi @Ayaanuddin,

Thank you for reporting and collaboration.


To speed up the processing of this issue, please provide us with the following information:

* Summary of the issue
* Information on your environment
* Steps to reproduce
* Expected and actual results.

We can able to see that both Expected results and Actuals results are same.Kindly provide more information.

Thanks.

**Comment by Ayaanuddin** [comment] 2023-05-03 04:58
Hi Venkat ,
Thanks for connecting ..
I have Issue with Dev Environment ,
its Loading very slow


   - Summary of the issue--Dev Environment is working very Slow
   - Information on your environment--- Docker Image with Build composer
   --PHP-8.1 and  Magento-2.4.5 and
   - Steps to reproduce--
   - Expected and actual results.--Working Very Slow and Earlier it was
   very Fast

KINDLY TREAT ON Priority--



Regards
Md Ayaan udddin
+91-7013806220

**Comment by engcom-Bravo** [comment] 2023-05-12 12:18
@magento give me 2.4-develop instance

**Comment by Ayaanuddin** [comment] 2023-05-12 12:25
Hi Venkat,
Thanks for connecting with me..
I am unable to understand the message..

Please eloborate what you require..


Md Jeelani
+91-7013806220

**Comment by Ayaanuddin** [comment] 2023-05-12 12:35
hi Team,
iam able to access magento page and Luma page as well..

kindly suggest what can be done improve slowness issue in Dev Environment.
this are client where we cannot give Access
if the solution works we will subscribe you


Regards
Md Jeelani
+91-7013806220

**Comment by Ayaanuddin** [comment] 2023-05-12 12:49
Hi Magento and Team,
the Magento Dev Env is slow
Anything fom DevOps side can be done to overcome this issue or
Any thing can be developer End to overcome this issue


Regards
Md Jeelani
+91-7013806220

**Comment by engcom-Bravo** [comment] 2023-05-12 13:59
Hi @Ayaanuddin,

Thanks for your update.

Please check if any 3rd party extensions / modules enabled is causing the issue.Kindly elaborate your steps to reproduce.it will help us to reproduce the issue.

Thanks.

**Comment by Ayaanuddin** [comment] 2023-05-12 15:18
Hi Venkata,
When I try to load the Magento page in Dev normal way ,
It causing the issue
I can reproduce the issue.
If setup the call..


Regards
Md Jeelani

**Comment by Ayaanuddin** [comment] 2023-05-15 04:44
Hi Magento,
any updates

**Comment by engcom-Bravo** [comment] 2023-05-18 06:12
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-18 13:16
Hi @Ayaanuddin,

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


When click on any magento page we are getting response with in short time.Please elaborate steps to reproduce it will help us to reproduce the issue and check any third party modules causing the issue.



https://github.com/magento/magento2/assets/51680745/a9d75fd2-15c8-4808-a3d2-fe433b92d184



Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.



Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-29 06:13
Hi @Ayaanuddin,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-29 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.2
