### ISSUE TITLE
Getting a full list of customerGroups with searchCriteria

### ISSUE THREAD

**Issue by dwaynebartels** [magento/magento2#16910] opened 2018-07-18 09:49 UTC
Endpoints like customerGroup/search need searchCriteria to get a full list of items. 
What we did in Magento 2.1.X is adding V1/customerGroups/search/?searchCriteria to get a list.
but since 2.2.4 this doesn't work anymore and we found different solutions to the problem. 
One of them is sending invalid searchCriteria like V1/customerGroups/search/?searchCriteria=[] OR a question mark V1/customerGroups/search/?searchCriteria=? OR whatever. 
The API doesn't care and gives you a full list unless the searchCriteria is VALID.
So I Imagine that when we fix our problem by sending invalid searchCriteria to get a List, things might change for the better in a later version of Magento and we have to FIX it again.. Which brings me to my Point. 

When we want to get a List of something without providing searchCriteria.

### Preconditions
1. Magento 2.2.4
2. Postman 

### Steps to reproduce
1. Use V1/customerGroups/search/?searchCriteria to get a list (worked in 2.2.3 and before)
2. Get a Fatal Error:
```
{
    "messages": {
        "error": [
            {
                "code": 500,
                "message": "Fatal Error: 'Uncaught TypeError: Argument 1 passed to Magento\\Customer\\Model\\ResourceModel\\GroupRepository\\Interceptor::getList() must be an instance of Magento\\Framework\\Api\\SearchCriteriaInterface, string given in /home/xxxxxxxxxxxxxxxx/generated/code/Magento/Customer/Model/ResourceModel/GroupRepository/Interceptor.php:46\nStack trace:\n#0 [internal function]: Magento\\Customer\\Model\\ResourceModel\\GroupRepository\\Interceptor->getList('')\n#1 /home/xxxxxxxxx/vendor/magento/module-webapi/Controller/Rest.php(330): call_user_func_array(Array, Array)\n#2 /home/xxxxxxxxxxxxxxxxx/vendor/magento/module-webapi/Controller/Rest.php(239): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#3 /home/xxxxxxxxxxxxx/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /home/xxxxxxxxxxxxx/vendor/magento/framework/Interception/Interceptor.php(138): Magent' in '/home/xxxxxxxxxxxxxxxxxx/generated/code/Magento/Customer/Model/ResourceModel/GroupRepository/Interceptor.php' on line 46",
                "trace": "Trace is not available."
            }
        ]
    }
}
``` 
3. Use V1/customerGroups/search/?searchCriteria={whatever it doesn't matter} to get a list
4. Get a full list with customerGroups

### Expected result
1. A full list or at least a decent error message.

### Actual result
1. 500 Fatal Error

**Comment by magento-engcom-team** [comment] 2018-07-18 09:49
Hi @dwaynebartels. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dwaynebartels do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dwaynebartels** [comment] 2018-07-18 09:51
@magento-engcom-team yes

**Comment by engcom-backlog-nickolas** [comment] 2018-07-18 10:33
Hello @dwaynebartels, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-10-22 19:32
Hi @eduard13. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by dwaynebartels** [comment] 2018-12-04 09:15
Please do not close this issue because of inactivity. 
We want to see this fixed.

**Comment by engcom-November** [comment] 2024-10-21 09:06
As this is quite old issue, we tried to verify this on latest 2.4-develop branch and the issue is not reproducible, hence closing this.

Thank you.

**Closed as completed by engcom-November** 2024-10-21 09:06 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: APIs
