### ISSUE TITLE
More issues related to the customer data loaded by js

### ISSUE THREAD

**Issue by pitbulk** [magento/magento2#30498] opened 2020-10-15 10:15 UTC
### Description
In ticket https://github.com/magento/magento2/issues/28428 I reported a bug that affected customer data not retrieved after executing a custom login controller, that was fixed by: https://github.com/magento/magento2/pull/29081

One of my customers reported 2 more different bugs that I consider are related with the customer data loaded by javascript as well

- If in the Magento instance exists customers with similar fullname (same lastname for example), the message that appears on the welcome message mismatch the fullname (wrong is loaded). It was verified that the data of the logged user that appears on the profile view is different than the one loaded on the customer data object loaded by js for printing the welcome message

- After login, if the user proceeds to checkout, the login popup appear even if the user was previously logged.
  Similar than the issue described here:  https://github.com/mageplaza/magento-2-social-login/issues/197

On 2.4.1 and 2.4.2 a new issue appeared as well:
- After login, I can access user account and verify Im logged in, after that I add a new item to the cart, ans when visiting the cart, the login auth popup appears. It seems that something is wrong with the user session on the frontend.

### Preconditions
 - Magento 2.3.4, 2.3.5, 2.4, 2.4.1
 - Custom Login controller

My login controller is similar than the [PostLogin](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Customer/Controller/Account/LoginPost.php#L187) code 

```
$customerSession->setCustomerDataAsLoggedIn($customer);
if ($this->getCookieManager()->getCookie('mage-cache-sessid')) {
    $metadata = $this->getCookieMetadataFactory()->createCookieMetadata();
    $metadata->setPath('/');
    $this->getCookieManager()->deleteCookie('mage-cache-sessid', $metadata);
}

$resultRedirect = $this->resultRedirectFactory->create();
return $resultRedirect->setUrl($targetURL);
```

The extension also forces sections to be invalidated after my custom login, by adding a etc/frontend/sections.xml as documented on [page-caching](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html)
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Customer:etc/sections.xsd">
    <action name="sso/saml2/acs">
        <section name="*"/>
    </action>
</config>
```

### Steps to reproduce
I implemented this simple custom login controller that will allow reproducing the issue:
https://github.com/pitbulk/magento-custom-login

If in a private browser I log in with a user that has the same lastname as others, I experience the issues described.

The issue exists on Magento 2.3.4, 2.3.4-p2, 2.3.5-p1 and 2.4.1

### Expected result

- customer data properly loaded even if existing customer accounts with the same lastname
- If the user is logged in, clicking on the checkout link will never open a popup for authentication

### Actual result

After enabling a private browser, and log in 

- wrong welcome message is loaded, data from other customer prompted
-  If the user is logged in, click on the checkout link, a popup for authentication appears
   Similar to the situation described here: https://github.com/mageplaza/magento-2-social-login/issues/197

**Comment by david-kominek** [comment] 2020-10-16 17:02
Also seeing the second issue in 2.3.5-p2.

> After login, if the user proceeds to checkout, the login popup appear even if the user was previously logged.

**Comment by pitbulk** [comment] 2020-10-26 12:24
any progress with this issue? I believe it impact any extension implementing custom login controller.

**Comment by wilzon008** [comment] 2020-12-10 19:30
I am one of the customers affected by this issue. There are still a lot of people running Magento 2.3.x. Thank in advance to anyone who can help implement this fix.

**Comment by cundd** [comment] 2020-12-11 09:31
We are also not able to update our customer's system to a secure version, because this issue makes it impossible. :(

**Comment by pitbulk** [comment] 2020-12-21 11:02
Is there anything we can do in order to get this bug fixed?

**Comment by james05** [comment] 2021-01-08 18:07
Also experiencing on 2.4.1. I cannot go live without this fixed.

**Comment by pitbulk** [comment] 2021-01-08 18:13
@complexthings are you able to help here?

**Comment by pitbulk** [comment] 2021-05-13 21:17
Can Magento team take any action on this ticket?

**Comment by cundd** [comment] 2021-06-21 08:26
Nice to see that somethings going on here!

**Comment by pitbulk** [comment] 2021-07-09 12:02
@engcom-Bravo do you have an ETA on when you gonna be able to work on this ticket?
Happy to help on its resoution.

**Comment by engcom-Hotel** [comment] 2021-12-24 12:15
Hello @pitbulk,

We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know if it is still reproducible for you.

Thanks

**Comment by pitbulk** [comment] 2021-12-30 14:17
Yes, it is reproducible, basically there is a js that belong to the customer-data.js that defines a listener:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Customer/view/frontend/web/js/customer-data.js#L423

which invalidates customer data.

During external SSO, the normal login flow is not used, not submit click, so that invalidation was never executed, and that generated the issues described here.

**Comment by engcom-Hotel** [comment] 2022-01-03 07:51
Hello @pitbulk,

Thanks for the reply!

We have tried to reproduce the issue in the clean Magento 2.4-develop instance with the Custom SSO module defined in the main description, but for us, the issue is not reproducible. We have followed the below steps:

1. Install the Custom SSO/login module from [repo](https://github.com/pitbulk/magento-custom-login).
2. Create 2 accounts with the same last names ie `Abhinav Pathak` & `Rajesh Pathak`.
3. Change the values for `Login.php` on line no. 79 to 81 as follows:
```
$email = "abhinav.pathak@test.com";
$firstname = "Abhinav";
$lastname = "Pathak";
```
4. When we tried to access the endpoint `DOMAIN/mysso/custom/login`, then it is redirected to the account page with the mentioned account in step 3, please have a look at the below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/147907628-e97de04f-22b0-4dd0-baa5-b485bef9b5fe.png)
5. And also while checkout it is not asking to log in, I can order the item successfully and the order goes into correct user account:
![image](https://user-images.githubusercontent.com/51681618/147908866-23986f0e-28d5-4fff-838b-727b139c6909.png)

Please let us know if we missed anything in order to reproduce it.

Thanks

**Comment by pitbulk** [comment] 2022-01-03 12:10
Instead accesing directly to DOMAIN/mysso/custom/login,

can you instead simulate a POST from a domain different than Magento's instance domain?

**Comment by engcom-Hotel** [comment] 2022-01-06 10:25
Hello @pitbulk,

Thanks for the reply!

We have tried this as well. We can find the added product in the cart as a guest in the logged-in user cart.

Thanks

**Comment by pitbulk** [comment] 2022-01-09 23:52
@magento give me 2.4-develop instance

**Comment by pitbulk** [comment] 2022-01-13 00:53
Hi @engcom-Hotel,

I was not able to reproduce it on 2.4-develop.  I reproduced the issue on the official releases:
2.3.4, 2.3.4-p2, 2.3.5-p1, 2.4.1 and 2.4.2

**Comment by engcom-Hotel** [comment] 2022-01-13 07:32
Hello @pitbulk,

Thanks for the confirmation!

That means the has been fixed in develop branch and it will fix in a future release as well. Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-01-13 07:32 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.3.4
