### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by Lilgamesh** [magento/magento2#38106] opened 2023-10-20 13:17 UTC
### Preconditions and environment

- Magento version : 2.4.5
- The rollback button in System > Backups not working

### Steps to reproduce

1.Navigate to Admin Panel
2.Open System
3. Open Backup
4. Choose one file want to backup and click to rollback

### Expected result

It will backup file when we click rollback

### Actual result

Nothing happen 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-23 09:44
Hi @Lilgamesh,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Navigate to Admin Panel
- Open System
- Open Backup
- Choose one file want to backup and click to rollback


<img width="1421" alt="Screenshot 2023-10-23 at 12 06 15 PM" src="https://github.com/magento/magento2/assets/51680745/4416c3aa-b455-4e59-88ca-e25a1283ea0a">




We are able to do Rollback and able to download the backup files.

Kindly refer this document https://experienceleague.adobe.com/docs/commerce-admin/systems/tools/backups.html?lang=en regarding system Backups.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-03 06:02
Hi @Lilgamesh,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38106#issuecomment-1774814601  still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-07 06:13
Hi @Lilgamesh,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38106#issuecomment-1774814601 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-11-09 06:13
Hi @Lilgamesh,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-11-09 06:13 UTC
Labels: Issue: needs update, Reported on 2.4.5
