### ISSUE TITLE
Change different product price on selecting different product swatches on category pages

### ISSUE THREAD

**Issue by ankurverma5540** [magento/magento2#19276] opened 2018-11-20 10:19 UTC
### Steps to reproduce (*)

1. Create Configurable products with swatches. Create a catalog price rule so that products have sale price. 
2. Now on category page old price will not show for configurable products. Now follow this link to show configurable products old prices
https://magento.stackexchange.com/questions/196090/magento-2-display-old-price-and-special-price-in-category-list
3. Try to use same color swatches for different products. e.g. red color for multiple products in category. So that multiple red colors swatches configurable products show one after another. Now click on Swatches on category page, the price will be change for multiple products

### Expected result (*)

1. Only Specific products price should be changed on category page
2.

### Actual result (*)

1. Create Configurable products with swatches. Create a catalog price rule so that products have sale price. 
2. Now on category page old price will not show for configurable products. Now follow this link to show configurable products old prices
https://magento.stackexchange.com/questions/196090/magento-2-display-old-price-and-special-price-in-category-list
3. Try to use same color swatches for different products. e.g. red color for multiple products in category. So that multiple red colors swatches configurable products show one after another. Now click on Swatches on category page, the price will be change for multiple products
![issue](https://user-images.githubusercontent.com/43195414/48767045-cc09fe00-ecdb-11e8-8d09-ce8fa4b58516.png)

**Comment by magento-engcom-team** [comment] 2018-11-20 10:19
Hi @ankurverma5540. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ankurverma5540 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by ankurverma5540** [comment] 2018-11-20 11:09
yes

**Comment by DanielRuf** [comment] 2018-11-20 11:14
> yes

You can tick the boxes ;-)

**Comment by magento-engcom-team** [comment] 2018-11-21 14:32
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-21 15:33
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96563`, `MAGETWO-96564` were created

**Comment by magento-engcom-team** [comment] 2018-11-24 09:46
Hi @hardik-krish. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by ankurverma5540** [comment] 2018-11-27 03:41
Is there any progress regarding this issue?

**Comment by magento-engcom-team** [comment] 2019-01-15 12:22
Hi @sdzhepa. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-15 12:22
Hi @sarfarazbheda. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-11 08:16
Hi @ankurverma5540. Thank you for your report. 
The issue has been fixed in magento/magento2#19376 by @sarfarazbheda in 2.3-develop branch
Related commit(s):
 - [6c5dd94b88bcb34f620c7e84d5aa458bd2132307](https://github.com/magento/magento2/commit/6c5dd94b88bcb34f620c7e84d5aa458bd2132307)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-11 08:16 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Component: ConfigurableProduct, Component: Swatches

**Comment by magento-engcom-team** [comment] 2019-03-14 15:30
Hi @ankurverma5540. Thank you for your report. 
The issue has been fixed in magento/magento2#21695 by @mage2pratik in 2.2-develop branch
Related commit(s):
 - [a4a487829684c76c3b5dfd7e5786a9352dfb915f](https://github.com/magento/magento2/commit/a4a487829684c76c3b5dfd7e5786a9352dfb915f)

The fix will be available with the upcoming 2.2.9 release.
