### ISSUE TITLE
product categorybackend loading slow

### ISSUE THREAD

**Issue by Ajmshossain** [magento/magento2#37628] opened 2023-06-17 07:52 UTC
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by Ajmshossain** [comment] 2023-06-17 07:53
When i open catelog product is just show loading.

**Comment by piyushsingh-adrosonic** [comment] 2023-06-17 08:43
Same issue with my Magento 2.4.2 as well.

**Comment by engcom-Dash** [comment] 2023-06-19 06:28
@magento give me 2.4.6 instance

**Comment by manavluhar** [comment] 2023-06-19 06:30
Hello @Ajmshossain , @piyushsingh-adrosonic 

Check if your issue is resolved by:

For **developer sites**
```
bin/magento config:set admin/usage/enable 0;
bin/magento cache:clean;
```

For **production sites**

*Store->Configuration->System->Advanced->Admin->Admin Usage->Enable Admin Usage Tracking : **No**


possible related issue / possible duplicate of : https://github.com/magento/magento2/issues/37618

**Comment by engcom-Dash** [comment] 2023-06-19 09:40
Hi @Ajmshossain ,

We are trying to reproduce the issue and its reproducible in 2.4-develop instance.Kindly refer the below screenshots,
<img width="1505" alt="Screenshot 2023-06-19 at 3 07 32 PM" src="https://github.com/magento/magento2/assets/60198592/012e40c3-6ac4-4bba-b514-e723d24ee8ef">
The issue is look likes Duplicate of [37618](https://github.com/magento/magento2/issues/37618)
Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Dash** 2023-06-19 09:40 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.x
