### ISSUE TITLE
Product quantity stock Not decrease when Order is placed

### ISSUE THREAD

**Issue by adamraya** [magento/magento2#5945] opened 2016-08-02 17:47 UTC
I created several products via backend using Magento CE 2.0.2, I upgraded to Magento CE 2.1, when I place an order on those products created on Magento CE 2.0.2, quantity not decrease. However on new products created via backend Magento CE 2.1 it's working fine.

No messages are being displayed to show why the stock is not being lowered. 
The magento debug and system logs show no real issues.
### Steps to reproduce
1. Create a product via backend on Magento CE 2.0.2
2. Upgrade to Magento CE 2.1
3. Place an order on those products previously created using Magento CE 2.0.2
### Expected result

The quantity should decrease.
### Actual result

The quantity is not being lowered.

**Comment by magentodevleper** [comment] 2016-08-04 10:35
We are facing the same issue with our website. We upgraded our website to Magento 2.1 from 2.0.4. While placing an order, the product quantity is not decreased. It remains the same.

This is causing a huge trouble managing stock. Does any one have an update on this and the cause for it?

**Comment by dthampy** [comment] 2016-08-04 23:16
internal jira ticket -MAGETWO-56448 has been created for this issue

**Comment by janiscaunecm** [comment] 2016-08-17 15:21
This happens because of change in app/code/Magento/CatalogInventory/Model/Configuration.php.

When you save a product, it's stock item gets created and saved in DB with a website_id assigned. Previously this would take current website's ID, now it is hardcoded to zero.

As a result, there may be stock items for product that have website_id != 0 and since now Magento searches for the ones with website_id=0, those will never get updated.

This whole website scope stock management seems to be a big mess, especially since according to this https://github.com/magento/magento2/issues/473 it was not supposed to be there.

There is no easy fix since you'd need to 
a) convert all stock items to have website_id=0 
b) make sure Magento only uses website_id=0 for future queries and future stock items (might be fixed in 2.1 though)

**Comment by JamboMedia** [comment] 2016-08-24 08:38
Same problem over here. Updated to Magento 2.1, after that the stock is not decreasing.

Will this be fixed in Magento 2.1.1?

**Comment by anthony-blackbird** [comment] 2016-09-07 08:25
Hello.

This bug is still existing, any update on this ?

**Comment by NadiyaS** [comment] 2016-09-15 13:22
Hi,
this issue was already fixed and will be delivered soon,
for now you can use quick fix :
Run MySQL query `update cataloginventory_stock_item set website_id = 0 where website_id = 1;`
and then run in CLI `php bin/magento index:reindex cataloginventory_stock`.

**Comment by NadiyaS** [comment] 2016-09-15 13:23
This issue is closed as duplicate of #5222

**Closed as completed by NadiyaS** 2016-09-15 13:23 UTC
Labels: Issue: Ready for Work, bug report
