### ISSUE TITLE
Email templates blank when using JS minification

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26325] opened 2020-01-09 06:31 UTC
And here we go again.

### Preconditions (*)
1. Magento 2.3.3

### Steps to reproduce (*)

1. Create email template or use sample data
1. Enable JS minification in developer settings
1. Enable production mode
1. Clear cache, deploy etc.
1. Click preview template

### Expected result (*)

Working preview of email template.

### Actual result (*)

Blank template.

404 error to jquery.js which does not exist (because it is jquery.min.js).

**Comment by sudheers-kensium** [comment] 2020-01-10 10:01
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-10 10:01
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-10 10:01
Hi @sudheers-kensium, here is your [Magento instance](https://i-26325-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26325-2-4-develop.instances.magento-community.engineering/admin](https://i-26325-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-01-10 10:11
@Zyles I am not able to reproduced in Magento 2.4-develop instance. So I am closing this issue.

**Closed as completed** 2020-01-10 10:11 UTC
Labels: Issue: Format is valid, Reported on 2.3.3

**Comment by Zyles** [comment] 2020-01-10 11:34
Do you know how to read step by step instructions?

The instance you tested on is in developer mode.

Start over and try again.

**Comment by sudheers-kensium** [comment] 2020-01-10 11:40
@Zyles We don't have access to enable production mode in vanilla Magento instance, so I have tested in my local instance I am not able to reproduced.

**Comment by Zyles** [comment] 2020-01-10 11:49
Please provide link to install instructions on where to get 2.4-develop for local.

**Comment by sudheers-kensium** [comment] 2020-01-10 11:54
We can clone or download the from github.
