### ISSUE TITLE
REST API: Can't update custom option through /V1/products/options/{optionId}

### ISSUE THREAD

**Issue by thomasnordkvist** [magento/magento2#5972] opened 2016-08-03 18:15 UTC
### Preconditions

1. Magento version 2.1
### Steps to reproduce

1. Install magento
2. Create a product with sku: test-sku
3. Add a custom option by POST: rest/V1/products/option with body:

> { 
>  "option": {
>     "product_sku" : "test-sku",
>     "title" : "Option title",
>     "type" : "area",
>     "price_type" : "fixed"
>   }
> }

Try to update the option by PUT: rest/V1/products/option/(option_id created from POST) with body

> { 
>  "option": {
>     "product_sku" : "test-sku",
>     "option_id" : (option_id created from POST),
>     "title" : "Option title changed",
>     "type" : "area",
>     "price_type" : "fixed"
>   }
> }
### Expected result

1. The title should have been updated.
### Actual result

1. New options get added instead of updating old. This happens in all store view so it's not possible to add translated titles to different store views.

Maybe related to #5885 and #5931

**Comment by NotAndD** [comment] 2017-01-20 08:17
Still here in 2.1.3, custom options can't be updated as a PUT request create a new one instead of updating the old one. 
The only way to update is to create a new one and delete the old one? Seems like a weird and not efficient workaround.

**Comment by mbrinton01** [comment] 2017-01-27 15:40
@misha-kotov please investigate this issue. Possibly related to MAGETWO-59315. Could not reproduce on _develop_ branch.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:28
@thomasnordkvist, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:28 UTC
Labels: bug report, Component: Framework/Webapi, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
