### ISSUE TITLE
Email templates preview problem

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#30123] opened 2020-09-21 06:39 UTC
. 

### Preconditions (*)

1. Magento 2.3.3 CE AWS Ec2 with Apahce and mariadb

### Steps to reproduce (*)

1. Setup 2 store view with arabic and english
2. Set arabic view as default
3. Go to backend, Marketing > Email Templates > Add new Template
4. Load default New order template
5. Click on Preview template

### Expected result (*)

1. As some content added in english in preview it should show english 
2.

### Actual result (*)

1.Showing ararbic content in preview
2. As a shopper we set default store as arabic but for backend admin there should be option to choose preview language. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2021-01-26 11:00
Hi @VZeroCool . Thank you for your report!
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
Everything works as expected.

**Manual testing scenario:**
1. Setup 2 store view with arabic and english
2. Set arabic view as default
3. Go to backend, Marketing > Email Templates > Add new Template
4. Load default New order template
5. Click on Preview template

**Actual Result:** :heavy_check_mark: As some content added in english in preview it should show english

![Screenshot from 2021-01-26 12-57-03](https://user-images.githubusercontent.com/51679138/105836691-38789a00-5fd6-11eb-8647-25dfe0944b21.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-01-26 11:00 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.3

**Comment by kweij** [comment] 2024-01-25 09:56
This issue is not resolved. In the description is written "for backend admin there should be option to choose preview language".

I must admit that the initial description is a bit hard to read (probably no english mother tongue), but it ends with a proper formulated RFC: the lacking feature to preview an email template for a certain store.

Here I have a new (manual testing) scenario:
- Setup 2 store view with arabic and english
- Set arabic view as default
- Go to backend, Marketing > Email Templates > Add new Template
- Load default New order template
- Click on Preview template
- Select a store to preview the email in <- This is the missing feature 
- See the whole preview in english <- This is not possible

The point of this reported issue seems quite clear to me (maybe because I'm here to report the same), but it wasn't picked up initially. So I request to reopen this issue.
