### ISSUE TITLE
User Roles Not displayed while creating new role

### ISSUE THREAD

**Issue by rais24** [magento/magento2#9491] opened 2017-05-03 13:08 UTC
### Preconditions

1. N/A
2. N/A

### Steps to reproduce

1. Go To User System > Roles > Add New Role
2. Edit newly created Role
3.  Go to Role Resources
4. Select Custom from Resource Access
5. User Role tree not showing

### Expected result

1. User Role tree should display

### Actual result

1.  User Role tree not showing

**Comment by korostii** [comment] 2017-05-04 15:08
Duplicate of #5803

**Comment by rais24** [comment] 2017-05-05 04:49
Thank You!

**Closed as completed** 2017-05-05 04:49 UTC
