### ISSUE TITLE
Cart Price Rule Not Working With Two SKUs in conditions.

### ISSUE THREAD

**Issue by gauravkhatri99** [magento/magento2#23740] opened 2019-07-17 09:41 UTC
I am facing the issue with Cart Price Rule with two SKUs in the condition. 

### Preconditions (*)
1. Using Magento 2.3.1
2. PHP version: 7.1.11

### Steps to reproduce (*)
1. Goto Cart Price Rule in Magneto back-end. 
2. Create a condition as the shared screenshot.
![conditions](https://user-images.githubusercontent.com/12871787/61364568-c46b1b00-a8a3-11e9-8605-270164ce219e.png)
3. I want to apply this rule if both of these two SKUs exist in the cart if I select ANY instead of ALL it works but I want with ALL.

### Expected result (*)
The discount should be applied in the cart as showing in the discount section.
![expectedResult](https://user-images.githubusercontent.com/12871787/61364842-38a5be80-a8a4-11e9-9f40-9f20c61190a6.png)

### Actual result (*)
The discount is not showing in the summary section.
![checkout](https://user-images.githubusercontent.com/12871787/61364900-53783300-a8a4-11e9-9cfc-c0b02f2c0f43.png)

Can anyone help to find a solution for this?

**Comment by shikhamis11** [comment] 2019-07-17 09:51
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-17 09:51
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-17 09:51
Hi @shikhamis11, here is your [Magento instance](https://i-23740-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23740-2-3-develop.instances.magento-community.engineering/admin](https://i-23740-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2019-07-17 10:03
Hi @gauravkhatri99 ,

You should modify the condition to:
![image](https://user-images.githubusercontent.com/8234209/61366921-bf629780-a8b4-11e9-9065-c4626702e8b1.png)

**Comment by magento-engcom-team** [comment] 2019-07-17 10:04
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18222`, `MC-18223` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by edenduong** [comment] 2019-07-17 10:06
Hi @shikhamis11,
It is not bug. Because no product has the attribute SKU are **both**  A and B, ( 1 product - 1 SKU)
Please change the condition in my previous comment. It will satisfy the requirement.

**Comment by shikhamis11** [comment] 2019-07-17 10:11
hello @edenduong 
thanks for your info I will recheck it and will close the issue if it is not valid

**Closed as completed** 2019-09-27 11:21 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Rule
