### ISSUE TITLE
After product save meta description populated with page builder code from product description

### ISSUE THREAD

**Issue by DegrizNet** [magento/magento2#38649] opened 2024-04-23 07:37 UTC
### Preconditions and environment

- Magento version 2.4.6
- php 8.1

### Steps to reproduce

1. Go to catalog / product in admin
2. Click add product
3. Input basid info like name, sku, qty. When check you see meta description populated with product name
4. add Description via Page builder
5. Save product and after check meta description

https://github.com/magento/magento2/assets/5030172/f79620a5-b3a2-4496-b7f4-abf10bcb326a

### Expected result

Meta description should be empty of populated with data before product is saved.

### Actual result

Meta description is populated with Page builder html tags.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-04-24 07:07
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-24 07:38
Hi @DegrizNet 

Thanks for reporting and collaboration.

Verified the issue on magneto 2.4 dev instance and the issue is not reproducable.

We are seeing the product name in meta description after product save.

Steps to reproduce

1. Go to catalog / product in admin
2. Click add product
3. Input basid info like name, sku, qty. When check you see meta description populated with product name
4. add Description via Page builder
5. Save product and after check meta description

Please refer the attached screenshots and let us know if we missed anything.

https://github.com/magento/magento2/assets/60198592/d987c5bb-6f14-4737-8aeb-ffa274d4ba97

<img width="1440" alt="Screenshot 2024-04-24 at 1 04 05 PM" src="https://github.com/magento/magento2/assets/60198592/507864a9-4c51-483c-8637-53bd1b80eaed">

<img width="1440" alt="Screenshot 2024-04-24 at 12 03 53 PM" src="https://github.com/magento/magento2/assets/60198592/6fe72a5c-a75a-44b0-8091-e82dc6faf4dc">

**Comment by engcom-Dash** [comment] 2024-04-25 08:48
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-04-25 09:02
Hi @DegrizNet 

Verified the issue again on magento 2.4 dev instance. But still not able to reproduce the issue.

Please refer the screen recording.

https://github.com/magento/magento2/assets/60198592/7c1a2343-fea9-45af-b0a8-f5ae76bb4bc4

The screenshots attached are not loading. Can you please add the screenshots again?

Thanks.

**Comment by engcom-Dash** [comment] 2024-05-02 08:49
Hi @DegrizNet 

As per you above comment we are closing this issue. Please feel free to raise a new issue or reopen this issue if you are facing the issue again.

Thanks.

**Closed as completed by engcom-Dash** 2024-05-02 08:49 UTC
Labels: Issue: needs update, Reported on 2.4.6
