### ISSUE TITLE
Magento 2.3 Error: "Invalid Form Key. Please refresh the page." When creating Bundled Products

### ISSUE THREAD

**Issue by mateuszrusiecki** [magento/magento2#31209] opened 2020-12-08 14:52 UTC
### Preconditions
1. Magento 2.3.5-p2
2. PHP 7.3
3. max_input_vars=100000

### Steps to reproduce
1. Create new bundled products
2. Add 20 options with single product attached to each
3. Save the bundled product
 
### Expected result
1. Bundled product saved successfully.

### Actual result
1. Unable to save bundled product, error: "Invalid Form Key. Please refresh the page."

**Comment by Pavel-Fekete** [comment] 2020-12-09 08:49
Hello @mateuszrusiecki 

I Couldn't reproduce this issue on the latest 2.4-develop
Bundled product (with 20 options) saved successfully and displayed on the frontend
![Bundled product](https://user-images.githubusercontent.com/67371013/101606429-0f8f4c00-3a0c-11eb-9427-d39d48eef79d.gif)

**Comment by mateuszrusiecki** [comment] 2020-12-09 14:19
@Pavel-Fekete sorry, the issue appears when there is 30+ options. And turns out that this is max_input_vars related. I changed the value wrong - for cli instead of fpm. After increasing it to 10000 and restarting fpm it worked.

But issue still persist. There "Invalid Form Key. Please refresh the page." message is useless, and debug log provide no informations whatsoever. 

So you can set max_input_vars to some low value like 100 and see the error.

**Comment by mateuszrusiecki** [comment] 2020-12-09 14:40
oh for fuck sake, now half of my options vanished after saving. This is so piece of shit...

**Comment by itisraza** [comment] 2020-12-10 11:32
Hello @mateuszrusiecki

Besides changing max_input_vars, please try changing max_input_nesting_level and max_input_time as well to some higher values. Hope this will help

Regards,
Raza.

**Comment by engcom-Alfa** [comment] 2020-12-15 12:06
Hi @mateuszrusiecki. Thank you for your report!
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop. Everything works as expected.

**Manual testing scenario:**
`max_input_vars=100000`

1. Create new bundled products;
2. Add 35 options with a single product attached to each;
3. Save the bundled product;

**Actual Result:** :heavy_check_mark: Bundled product saved successfully.

![Peek 2020-12-15 14-02](https://user-images.githubusercontent.com/51679138/102212849-8467f780-3ede-11eb-99f9-651e3a0f01d6.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-15 12:06 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5-p2

**Comment by mateuszrusiecki** [comment] 2020-12-15 14:12
@engcom-Alfa I think I mentioned in few paces that I use 2.3 NOT 2.4 but whatever. Did you set max_input_vars=100? I pretty sure that it will fail wit only 100
