### ISSUE TITLE
Weee tax (Fixed product Tax) appears duplicated in the last product of the order

### ISSUE THREAD

**Issue by r1tt3r** [magento/magento2#35775] opened 2022-07-15 23:04 UTC
### Preconditions and environment

- Magento version 2.4.4
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1 - Enable Fixed product Tax on Store > Configuration > Sales > Tax
2 - Create a new product attribute for Fixed product tax
![image](https://user-images.githubusercontent.com/9289149/179322177-aa472f93-fefb-4e74-904d-39a2f60e9caf.png)
3 - Add this attribute to the attribute group desired
4 - Set the FPT at product registration in two or more products
5 - Add these products to the cart (2 or more with FPT)
6 - Place the order

### Expected result

The fixed product tax should appears in each item

### Actual result

The FPT appears duplicated (triplicate, etc) on the last order item at admin panel.

<img width="1774" alt="Screen Shot 2022-07-15 at 19 20 23" src="https://user-images.githubusercontent.com/9289149/179322344-2f842feb-2e97-4d01-831c-1ba5c4705220.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by r1tt3r** [comment] 2022-07-15 23:39
I found a commit in the develop branch to fix that issue: https://github.com/magento/magento2/commit/b182ae51863d5f738674869ad8bd6145629f4a73
Thank you @bubasuma

**Comment by engcom-November** [comment] 2022-07-18 11:07
Hi @r1tt3r ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but couldn't reproduce the issue.
Fixed Product taxes are displayed as expected in admin panel for orders created from both front end and admin - No issue.
![image](https://user-images.githubusercontent.com/60198231/179498718-7009e990-f53b-47ae-9cfc-07c2d28858d1.png)
Kindly recheck the issue on Magento 2.4-develop branch as its the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.

**Comment by engcom-November** [comment] 2022-08-01 09:34
Hi @r1tt3r ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-08-01 09:34 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by Kudja** [comment] 2022-09-08 22:03
Can confirm same issue on 2.4.4

![image](https://user-images.githubusercontent.com/8101375/189233951-136b7025-c782-465c-b798-ad7cca53634f.png)

**Comment by adaudenthun** [comment] 2022-09-27 09:17
Can confirm same issue on 2.4.3-p3
