### ISSUE TITLE
Import History: Unable to download error report file

### ISSUE THREAD

**Issue by florinm8** [magento/magento2#28691] opened 2020-06-11 17:51 UTC
### Preconditions (*)

1. Magento version: 2.3.5-p1
2. Issue was not reporoducing in version 2.3.3
3. Issue is caused by the addition of ``$this->_directoryHandle->delete($this->_destination);``
in ``\Magento\ImportExport\Model\Export\Adapter\Csv::destruct`` method. (the error file generated is deleted from disk before Validate action is finished)

### Steps to reproduce (*)

1. Login to admin area and navigate to System -> Import
2. Start a product import process with a csv file that contains invalid data (eg: missing a required attribute)
3. Press Check Data button
4. After validation fails click on the link provided in the Validation result area
![image](https://user-images.githubusercontent.com/15091464/84421016-9ca34500-ac23-11ea-9f76-afbbac6931d9.png)
5. Or manually navigate to System -> Import history and click the Download link from "Error File" column
![image](https://user-images.githubusercontent.com/15091464/84421242-f146c000-ac23-11ea-9b9e-aade7601fbc7.png)

### Expected result (*)

1. The error file should be offered for download

### Actual result (*)

1. Page reload and nothing is downloaded

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sidolov** [comment] 2020-06-11 18:45
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-11 18:45
Hi @sidolov. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-11 18:47
Hi @sidolov, here is your [Magento instance](https://i-28691-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28691-2-4-develop.instances.magento-community.engineering/admin_3e14](https://i-28691-2-4-develop.instances.magento-community.engineering/admin_3e14)
Login: `e2151d8d` Password: `00e9382c2552`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment] 2020-06-11 18:49
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-11 18:49
Hi @sidolov. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-11 18:52
Hi @sidolov, here is your [Magento instance](https://i-28691-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28691-2-4-develop.instances.magento-community.engineering/admin_007f](https://i-28691-2-4-develop.instances.magento-community.engineering/admin_007f)
Login: `240591f7` Password: `be585de14ffd`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-06-12 03:36
@florinm8: Since the issue is duplicate. Please refer this ticket for your reference - https://github.com/magento/magento2/issues/28420

Hence closing the ticket

**Closed as completed by swathishs** 2020-06-12 03:36 UTC
Labels: duplicate, Issue: Format is valid, Reported on 2.3.3
