### ISSUE TITLE
Web base urls configuration fields filtered

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#16152] opened 2018-06-15 08:50 UTC
### Preconditions

1. Magento: 2.2.3
2. PHP: 7

### Steps to reproduce

1. Set up Magento with pub folder as webroot
2. Set base URLs manually in configuration (Store > Configuration > General > Web) using placeholders (e.g: `{{unsecure_base_url}}media/` for configuration path `web/unsecure/base_media_url`)
3. Save configuration

### Expected result

1. The configuration should be saved in database with the value entered
2. The page should reload with the value entered displayed

![image](https://user-images.githubusercontent.com/3015249/41459372-b9b94e0a-7089-11e8-848c-256e64005ee7.png)

### Actual result

1. The value is correctly set in database

![image](https://user-images.githubusercontent.com/3015249/41459464-f3fcbeee-7089-11e8-985d-be9278495d17.png)

2. The value displayed is filtered, displaying the website's unsecure / secure base URL instead of placeholders

![image](https://user-images.githubusercontent.com/3015249/41459408-cf2efd48-7089-11e8-9f75-c620caed8f4a.png)

This bugs is critical as if the Magento is a multi-website's instance that have several domain / subdomains, if the configuration is saved again, since the value is filtered, the placeholder will disappear from database and the full website's URL will be used in database too, causing the other websites to be broken.

**Comment by hostep** [comment] 2018-06-15 09:20
@Axel29: thanks! Good to see other people are running into this problem as well.

I'm going to close this though, as it's a duplicate of https://github.com/magento/magento2/issues/15972

**Closed as completed by hostep** 2018-06-15 09:20 UTC
Labels: Issue: Format is valid

**Comment by Axel29** [comment] 2018-06-15 09:47
Hi @hotstep, thank you for your feedback, I didn't find your issue.
