### ISSUE TITLE
New/Custom ACL rules have dangerous defaults

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#37620] opened 2023-06-15 15:12 UTC
### Preconditions and environment

- Mage 2.4.4
- PHP 8.1

### Steps to reproduce

- Create a new module
- Add ACL rule to the new module
- Create an API route on that module using that ACL rule
- Call the API route (using accessToken)

### Expected result

It is expected that:

- tokens/users with access to All Resources are able to call said route
- token/users with limited access are NOT able to call said route
    - After all, their permission settings show the new ACL rule UNCHECKED at this stage

### Actual result

Tokens/Users with limited access ARE able to call said route. 

### Additional information

The issue is a bad fallback/default AND/OR a disconnect between the visual configuration and what is actually happening.

- The authorization_rule table is not automagically getting entries with the new ACL rule
- So, as there is no entry in that table that specifically denies the permission, access is assumed

I see multiple possibilities to combat this issue:

- Assume new ACL rules are active for users with limited access; So when there is no entry in the authorization_rule table, the visual configuration should show the rule as ENABLED (making this a just a visual bug)
- Assume new ACL rules are denied for users with limited access; This is likely a massive change in behaviour.
    - This could also be solved by writing DB entries (allow) for limited users/integrations when Magento discovers the new ACL rule.

Once you save the permission settings, the database entries are created and the permission rules do what you expect them to do. But you have to remember to do that for each integration and role, after deploy.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-06-27 14:21
Hi @vandijkstef ,
Thank you for reporting and collaboration,

Verified the issue in 2.4-develop instance and the issue is not reproducible, Kindly refer below the screenshots:

<img width="893" alt="Screenshot 2023-06-23 at 8 36 29 PM" src="https://github.com/magento/magento2/assets/60198592/9e964b1a-6f42-43a8-a769-4232049d37f6">
<img width="1498" alt="Screenshot 2023-06-27 at 3 09 34 PM" src="https://github.com/magento/magento2/assets/60198592/f67323ed-33de-44e9-89f7-095ee85945fb"
<img width="897" alt="Screenshot 2023-06-23 at 8 34 57 PM" src="https://github.com/magento/magento2/assets/60198592/ca1444fc-4528-4370-9222-752d475e8dcb">

**We followed the steps you mentioned.**:

- Created a new module
- Assigned ACL rule to the module
- Created API route to that module
- Created 2 users, admin and admin2
- Admin has access to everything.
- Admin2 do not have access to the new module.
- We called the API endpoints in postman using access token.
- As we can see admin can access the API
- Here admin2 cannot access the resource as he do not have permission.

Hence we can see that ACL rules are working fine.

Let us know if we are missing anything!

Thanks

**Comment by engcom-Hotel** [comment] 2023-06-30 07:52
Hello @vandijkstef,

Thanks for the quick response!

We have tried to reproduce the issue in 2.4-develop as per your latest comment here https://github.com/magento/magento2/issues/37620#issuecomment-1609628576, but still, the issue is not reproducible for us.

Please refer to the below screencast for reference:


https://github.com/magento/magento2/assets/51681618/9a61dafc-3a85-496b-b033-f9b24bca02b2

Please let us know if we missed anything.

Thanks

**Comment by vandijkstef** [comment] 2023-06-30 09:48
Thank you for investigating. I've reviewed the screencast and I might have some ideas:

- I've installed and enabled the module first, then added new api-routes with a new ACL resource (So the new rules/routes are only processed by `di:compile & cache:clear` and not by `setup:upgrade`)
- I've used an integration w/ accesstoken, not an actual user. 

Essentially I was in a state where the modules ACL rules where NOT present in the `authorization_rule` table. Removing the entries for that modules ACL in that table will assume 'allowed' while the permission view shows the boxes unchecked (denied). Saving the permissions (obviously) restores the entries in the database.

**Comment by engcom-Hotel** [comment] 2023-07-04 07:10
Hello @vandijkstef,

Thanks for the response!

We tried to reproduce the issue as per your latest comment here https://github.com/magento/magento2/issues/37620#issuecomment-1614414108, but we are getting the expected response. 

Please have a look at the below screenshot for your reference:

![image](https://github.com/magento/magento2/assets/51681618/15154cde-2158-4164-950b-09270e16b736)

It might be possible that the issue has been resolved in the latest development branch, so we request you to please try to reproduce the issue in the 2.4-develop branch and let us know if you are still able to reproduce the issue.

Thanks

**Comment by engcom-November** [comment] 2023-08-29 12:53
Hello @vandijkstef,

We have noticed that this issue has not been updated since long time. Hence we assume that the issue is fixed now, so we are closing it. Please feel free to raise a new one or reopen this issue if you need more assistance on this.

Thanks.

**Closed as completed by engcom-November** 2023-08-29 12:53 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4
