### ISSUE TITLE
Quantity decrease by two for vitual product, if Asynchronous sending is enabled

### ISSUE THREAD

**Issue by manan-india** [magento/magento2#28473] opened 2020-06-02 10:58 UTC
### Preconditions (*)

1. cron should be enabled
2. smtp should be configured

### Steps to reproduce (*)

1. Enable the configuration: Stores>Configuration>Sales>Sales Email>General Settings>Asynchronous sending
2. Place an order for a virtual product.
3. Generate an invoice
4. wait for 2-3minutes(to successfully job done by cron)

### Expected result (*)

1. Qunatity decreased by 1

### Actual result (*)

1. Qunatity decreased by 2

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-12-04 14:24
Hi @manan-india .
Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.
Everything works as expected.

**Manual testing scenario:**

1. Enable the configuration: Stores>Configuration>Sales>Sales Email>General Settings>Asynchronous sending
2. Place an order for a virtual product.
3. Generate an invoice
4. Run cron (to successfully job done by cron)

**Actual Result:** :heavy_check_mark: Qunatity decreased by 1

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-04 14:24 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.4.0
