### ISSUE TITLE
Duplicate call to $this->getLinkField();

### ISSUE THREAD

**Issue by will-b** [magento/magento2#9017] opened 2017-03-26 13:24 UTC
There is a duplicate call to the getLinkField method inside Magento/Catalog/Model/ResourceModel/Category.php
in the getChildren method

```
$linkField = $this->getLinkField();
$attributeId = $this->getIsActiveAttributeId();
$backendTable = $this->getTable([$this->getEntityTablePrefix(), 'int']);
$connection = $this->getConnection();
$checkSql = $connection->getCheckSql('c.value_id > 0', 'c.value', 'd.value');
$linkField = $this->getLinkField();
```

### Preconditions

1. Magento version 2.1.3
2. Or Magento develop branch

### Steps to reproduce

1. Inspect code of Magento/Catalog/Model/ResourceModel/Category.php

### Expected result

1. Expect $this->getLinkField() not to be called more than required

### Actual result

1. $this->getLinkField() is unnecessarily called a second time

**Comment by davidalger** [comment] 2017-03-28 22:16
@will-b Mind opening a PR with the suggested fix? I agree from the code you noted above, there is a duplicate call there.

**Comment by will-b** [comment] 2017-03-30 10:43
@davidalger created PR

**Comment by davidalger** [comment] 2017-03-30 17:19
@will-b Super, thanks! I'll close this out once the PR is merged into the mainline.

**Comment by magento-team** [comment] 2017-07-31 22:49
Internal ticket to track issue progress: MAGETWO-66959

**Comment by magento-engcom-team** [comment] 2017-09-20 22:56
@will-b, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:56 UTC
Labels: Issue: Ready for Work, Fixed in 2.2.x, Issue: Format is valid
