### ISSUE TITLE
Magento 2 removes html element from email templates if it has a class with display: none

### ISSUE THREAD

**Issue by Januszpl** [magento/magento2#7348] opened 2016-11-08 13:25 UTC
### Preconditions

1.  Magento 2.1

### Steps to reproduce

1. Add new custom email template in admin panel

```
<!--
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<!--@subject {{trans "Header"}} @-->
<!--@vars {
"var logo_height":"Email Logo Image Height",
"var logo_width":"Email Logo Image Width",
"var template_styles|raw":"Template CSS"
} @-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <style type="text/css">
        {{var template_styles | raw}}

        {{css file="css/email.css"}}


    </style>
</head>
<body>
{{inlinecss file="css/email-inline.css"}}
<div class="show-me">Show</div>
<div class="hide-me">hide me</div>
</body>
</html>
```

2. add  in _email-extended.less 
```
.hide-me {
    display: none!important;
}
```

4. check if both elements element exist in the preview (before remove cache/view_preproccessed in /var)

### Expected result

1. I should see in source
```
<main id="anchor-content" class="page-content">
...
<div class="show-me" style="display: block;">Show</div>
<div class="hide-me" style="display: none!important;">Hide</div>
</main>
...
```

### Actual result

1. But I see only div with class show-me 
```
<main id="anchor-content" class="page-content">
...
<div class="show-me" style="display: block;">Show</div>
</main>
...
```

**Comment by rganin** [comment] 2016-11-08 15:18
Thanks for reporting. The issue is caused by emogrifier library.
Internal ticket created: MAGETWO-60669

**Comment by rganin** [comment] 2016-11-08 18:46
@Januszpl if you are creating a mobile-friendly template I can suggest to use `@media` directive for all inline styles including default as a quick workaround until the issue fix is delivered, like:

```
@media screen and (min-width: 769px) {
    /* default styles */
}
@media screen and (max-width: 768px) {
    /* mobile styles */
}
```

Or at least for css classes that are responsive for visibility.

**Comment by magento-engcom-team** [comment] 2017-10-18 07:30
@Januszpl, thank you for your report.
We've created internal ticket(s) MAGETWO-60669 to track progress on the issue.

**Comment by nemesis-back** [comment] 2017-10-26 22:51
I will work on it #SQUASHTOBERFEST

**Comment by vladimnir** [comment] 2017-10-27 15:09
Hi @Januszpl , i think that your issue is that you are trying to modify the blank theme , you should do it in Luma's theme , i did that and it's working fine  
![lumatheme](https://user-images.githubusercontent.com/15436431/32110943-ff4ef94e-bb06-11e7-833f-b0daece9a7a3.png)

![hide](https://user-images.githubusercontent.com/15436431/32110989-2b3a0058-bb07-11e7-8dbf-aa96c1dd575c.png)
As you can see here the hide text was hidden

**Comment by Januszpl** [comment] 2017-10-27 17:59
@vladimnir it my case it was also not visible. The problem was with the html output.
1) can you check source? and show generated output?
2) can you send mail and check in mail content the source?

In both case you should see in source div with class "hide-me" after div "show-me" (in html source, not on the generated page in browser)

**Comment by magento-engcom-team** [comment] 2018-08-20 11:05
Hi @Januszpl

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 12:01
@Januszpl, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 12:01 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, triage wanted
