### ISSUE TITLE
dev:urn-catalog:generate broken when vendor is in parent of rootDir

### ISSUE THREAD

**Issue by Flyingmana** [magento/magento2#2293] opened 2015-11-08 00:40 UTC
file structure:  

projectRoot: `/work/cotya/dashboard/`  
vendorDir: `/work/cotya/dashboard/vendor/`  
magentoRoot: `/work/cotya/dashboard/build/`  

`/work/cotya/dashboard/build$ php-5.6 bin/magento dev:urn-catalog:generate ./misc.xml`  
fails with 

```
[Magento\Framework\Exception\FileSystemException]                                                                                         
  Cannot read contents from file "/work/cotya/dashboard/build/work/cotya/dashboard/vendor/magento/module-ui/view/base/layout/default.xml" 
```

reason seems to be that `\Magento\Framework\Filesystem\Driver\File::getRelativePath` cant resolve absolute paths, which are not below the given basePath and `getAbsolutePath` just adds to the given basePath. I assume that is correct behavior for most cases.  
My feeling is, that `$this->rootDirRead->readFile` is not the best way here to read the files. Replacing with a pure `file_get_contents` seems to solve the problem.

**Comment by Flyingmana** [comment] 2015-11-08 00:52
I have to correct this, the problem seems to reach a bit wider to be a general problem with file access of modules inside the vendor directory

**Comment by alankent** [comment] 2015-11-08 01:54
There is a known restriction that files currently must be under Magento base directory. We are looking to remove this restriction in the future, but no ETA yet. It has to compete with other work items. (I think it would be useful to allow modules under app/code, vendor/, and directories off somewhere else - gives you a bit more flexibility, like what you are trying to do. E.g. you can check out module source code in independent directories, but use them all in your one Magento site as a developer - later packaging them up for download via Composer.)

**Comment by Flyingmana** [comment] 2015-11-08 16:23
I see... As Magento inside the root of the project is not an option (I dont like the hassle with all the gitignore rules and it would make my customized to server deployment harder) I successfully tried as workaround, to put the vendor inside the magento root.

```
    "config": {
      "vendor-dir": "build/vendor_dir"
    },
```

**Comment by ivanweiler** [comment] 2015-11-09 08:38
It seems same problem exists with installed sample data, they are also outside base directory, symlinked.
```
ivanweiler@Rocky:/var/www/magento2$ php bin/magento dev:urn-catalog:generate .idea/misc.xml

[Magento\Framework\Exception\FileSystemException]
Cannot read contents from file "/var/www/magento2/var/www/magento2-sample-data/app/code/Magento/CatalogRuleSampleData/etc/module.xml" 
```
Where:
/var/www/magento2/ - magento2 folder
/var/www/magento2-sample-data/ - sample data folder, symlinked

module.xml path is resolved wrong for symlinked modules.

**Comment by vrann** [comment] 2015-11-10 02:17
@Flyingmana Magento modules in the vendor directory should be supported right now. It seems like a valid issue with the tool which should be fixed.

**Comment by magento-engcom-team** [comment] 2017-11-07 04:20
Looks like the issue has been fixed in latest releases. Please try 2.2.0 and let us know if the issue is still valid.

**Closed by magento-engcom-team** 2017-11-07 04:20 UTC
Labels: acknowledged, Application Framework, bug report, G1 Failed
