### ISSUE TITLE
Magento crashes on large product Import

### ISSUE THREAD

**Issue by adampwright** [magento/magento2#36842] opened 2023-02-10 13:16 UTC
### Preconditions and environment

Version: 2.4.5-p1 (but, I've had this happen on previous versions)
CSV file for Import: 
[amz-upload-magento_trimmed.csv](https://github.com/magento/magento2/files/10713973/amz-upload-magento_trimmed.csv)

(CVS contains circa 1600 rows with some pretty large strings)

### Steps to reproduce

1. Navigate to Import section
2. Select Products, Add & Replace, 100 error tolerance, Stop On Error. 
3. Check data
4. Import

### Expected result

Import all products successfully. 

### Actual result

Data checks out fine, then on clicking Import, sits with the loading spinner as expected:

![1](https://user-images.githubusercontent.com/57555666/218099930-ed85e328-e83c-48dd-8bcd-551f79b57e28.jpg)

Then, after a few minutes, maybe 10ish or so, a console.log message, and an image on the page crashes. It sits in this state for an infinite number of hours, and will never finish the import. 

![2](https://user-images.githubusercontent.com/57555666/218100124-e5342d04-b12b-442b-8913-f376bed43ba0.jpg)

Then, since my Magento is sat in this state infinitely. I've had it sit for hours before, and no Import Successful. I hit refresh and get this:

![3](https://user-images.githubusercontent.com/57555666/218100341-a7a53d15-dcdf-463d-80b3-66c4c63f1b8a.jpg)

After waiting 5-10 minutes, or sometimes requiring a server restart, I am finally able to use Magento again, and find that some of the products have imported, but most have not. (600 of the 2600, was the most amount).

### Additional information

I thought at first this could be due to system resources running out so as a test, I temporarily upped my EC2 server to an m3.x-large. Which is a ridiculous amount of power for a currently 1x user Magento. And this still happens. 

I dont know at this point whether this is a Magento issue, a PHP settings issue, or something else, as I cannot find logging or any error messages with feedback on this. 

Note: That the Import process works just find on smaller imports (Lets say up to 100).

Help appreciated, I'm pulling my hair out with this. If this isn't a Magento bug, hopefully you guys can point me in the right direction. Thanks!

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by adampwright** [comment] 2023-02-10 13:18
@magento give me 2.4-develop instance

**Comment by adampwright** [comment] 2023-02-10 16:41
Update. Edited Import CSV to include full S3 links, not paths, so can be used on development instance. Also trimmed down to 1300 rows, from 2600 as the file upload limit in php.ini appears to be lower than my server. 

The CSV: 
[amz-upload-magento_trimmed.csv](https://github.com/magento/magento2/files/10709456/amz-upload-magento_trimmed.csv)

Still sitting on "Please wait..." 2hr 30mins later. Is this normal? 1300 rows isn't THAT big. 

![devinst](https://user-images.githubusercontent.com/57555666/218147053-50920dee-05b3-433d-9daa-9f4f8ccd0f76.jpg)

**Comment by adampwright** [comment] 2023-02-10 17:32
Three hours later, and it was still the same above, so I hit refresh. And now the dev instance has crashed. 

![3](https://user-images.githubusercontent.com/57555666/218157681-85692560-56a4-4da9-916e-33a423d9e4c6.jpg)

**Comment by mrkhoa99** [comment] 2023-02-11 08:51
hi @adampwright can you just try with one product import and see error?
I also note that if we want to import product images from external server. In the CSV data, enter the full URL for each image type such as base_image, small_image, thumbnail_image, or additional_images.
For example,  http://azm.com/images/image.jpg

**Comment by adampwright** [comment] 2023-02-11 15:32
@magento give me 2.4-develop instance

**Comment by adampwright** [comment] 2023-02-11 16:25
> hi @adampwright can you just try with one product import and see error? I also note that if we want to import product images from external server. In the CSV data, enter the full URL for each image type such as base_image, small_image, thumbnail_image, or additional_images. For example, http://azm.com/images/image.jpg
> 
> Please, try again with one product first.

Updated the CSV. Works with 1, works with 20, fails with 50.

**Comment by engcom-Dash** [comment] 2023-02-13 13:29
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-02-13 17:46
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-02-13 18:35
Hi @adampwright ,

Verified the issue in 2.4-develop instance and we are not able reproduce the issue.
Magento version 2.4-develop instance
PHP 8.1
Steps:
1.Install Magento instance'
2.Go to Import
3.Select Products, Add & Replace, 100 error tolerance, Stop On Error.
4.Check data
Screenshot:
<img width="1512" alt="Screenshot 2023-02-13 at 11 58 37 PM" src="https://user-images.githubusercontent.com/60198592/218544830-3ee9e09d-773e-4d92-9420-1d9a9e3bc198.png">


When we are checking the data,We are getting some different.

**Comment by adampwright** [comment] 2023-02-13 20:52
> c974c4194a92

Hello, still had my store_codes in the CSV. Removed them now:

Try again with this CSV. Thanks:

[amz-upload-magento_trimmed.csv](https://github.com/magento/magento2/files/10726204/amz-upload-magento_trimmed.csv)

**Comment by engcom-Dash** [comment] 2023-02-15 10:33
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-02-15 17:36
Hi @adampwright ,

Thanks for your information.

Verified the issue in 2.4-develop instance,Hence we are confirming the issue.

Preconditions:
Magento Version - 2.4-Develop
PHP Version -8.1

Steps to Reproduce :
1.Navigate to Import section
2.Select Products, Add & Replace, 100 error tolerance, Stop On Error.
3.Check data
4.Import

Screenshots:
<img width="1512" alt="Screenshot 2023-02-15 at 6 29 51 PM" src="https://user-images.githubusercontent.com/60198592/219106944-231abe86-a189-4644-8bd7-4f0f0dd65cfc.png">
<img width="1264" alt="Screenshot 2023-02-15 at 10 51 55 PM" src="https://user-images.githubusercontent.com/60198592/219106985-7df56f26-e309-4e23-ab80-b9f80debaefd.png">

As per description We are getting Actual result.

Let us know if we are missing anything.

Thanks.

**Comment by engcom-November** [comment] 2023-02-22 05:13
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-02-22 06:46
Verified the issue again on Magento 2.4-develop instance and the issue is reproducible with large valid product data for Add/update operation as well.
With valid and large product csv data - import check is passed but product import is failing with 504 gateway timeout error.
Page load is stuck and resulting in 504 gateway error
![image](https://user-images.githubusercontent.com/60198231/220543735-720a789b-4a56-4e7e-9de1-86483830a5db.png)
Hence confirming this issue.

**Comment by engcom-November** [comment] 2023-05-04 12:29
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-23 06:14
Hi @adampwright,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-23 06:14 UTC
Labels: Component: ImportExport, Priority: P1, Progress: done, Issue: needs update, Area: Admin UI, Reported on 2.4.5-p1
