### ISSUE TITLE
Magento 2.3.7-p2 - bundle product with >1 qty in last place in list of products causes multiples of bundle to be added to cart

### ISSUE THREAD

**Issue by ciderpunx** [magento/magento2#35566] opened 2022-06-01 13:50 UTC
### Preconditions and environment

- Magento version

2.3.7-p2

- Anything else that would help a developer reproduce the bug

Using the ultimo theme

### Steps to reproduce

Create a new bundle product, all options default.

Add options to product. 

For the last option set:
   Input type: Any 
   Product: Any 1 product
   Price:0 
   Price type: fixed
   Default qty: >1 (e.g. 2)
   Required: checked
i.e.: 
![Screenshot 2022-06-01 at 14-46-42 TESTCASE 2 Newly created bundle _ Products _ Inventory _ Catalog _ Magento Admin - New Internationalist ethical shop](https://user-images.githubusercontent.com/133149/171420304-a5844f3e-5ae3-4745-841a-4e433e868ff8.png)

Save product and go to product view in front end.
Add one of the bundle to cart.

### Expected result

1 of the bundle product is in the cart.

### Actual result

2 of the bundle product are in the cart.

### Additional information

If the product is moved to the penultimate place on the back end, the problem goes away. 

![Screenshot 2022-06-01 at 14-47-04 TESTCASE 2 Newly created bundle _ Products _ Inventory _ Catalog _ Magento Admin - New Internationalist ethical shop](https://user-images.githubusercontent.com/133149/171420160-23cf719b-3322-4507-980c-24ea19a3010c.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-02 12:57
Hi @ciderpunx ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue with below steps performed:
1. Created Bundle product with below configuration:
2. Front-end - Added one of the bundle item to cart
No issue: Only one item is added to cart
![image](https://user-images.githubusercontent.com/60198231/171634118-5537fe1f-7f55-427d-b11d-e3df3daadf90.png)
![image](https://user-images.githubusercontent.com/60198231/171634247-6ccb336c-fd6d-4826-987b-4f2daf6a48ba.png)
![image](https://user-images.githubusercontent.com/60198231/171634303-7490c2cc-f290-47f7-85a8-42f8571a4b91.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by isxam** [comment] 2022-06-03 08:54
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-06-17 11:12
Hi @isxam ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-17 11:12 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
