### ISSUE TITLE
Disabeling js merge,bundle,minify does not work in admin

### ISSUE THREAD

**Issue by Taral-Patoliya** [magento/magento2#10605] opened 2017-08-21 13:46 UTC
When disabling the js, and css ,merge, minify and bundling for default scope and keeping them enabled for website and store view scope, the admin still loads minified and bundled js

### Preconditions
1. Magento Version : 2.1.3

### Steps to reproduce
1. Disable  js merge, minify, bundling for default scope in system config
2. Enable the same in Website scope
3. Enable the same in store view scope

### Expected result

1. Admin should load all the js files separately
2. Frontend should load bundled files

### Actual result
1.Admin loads all the files bundled

**Comment by hostep** [comment] 2017-08-21 19:41
This is a duplicate of https://github.com/magento/magento2/issues/6638 (which was unfortunately closed due to Magento support people not understanding the problem :p).
It's certainly a bug, but a very low priority one in my opinion.

@Taral-Patoliya: any particular reasons for wanting this behaviour? Just out of curiousity :) We no longer need this ourselves, as it was a workaround for an unrelated issue which we were having, but which was fixed later on.

**Comment by Taral-Patoliya** [comment] 2017-08-22 13:28
@hostep We need to disable this behavior because we are getting js errors while accessing tiny_mce in backend for CMS Pages and Blocks, the tiny mce does not work with the js merged and bundled. 

Please have a look at below screenshot 
![screenshot from 2017-08-22 18 59 19](https://user-images.githubusercontent.com/10272277/29567876-227fcb88-876c-11e7-9c2b-cd8d6799ab07.png)

**Comment by okorshenko** [comment] 2017-09-07 19:52
@Taral-Patoliya thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [x] Preconditions: Magento version

**Comment by Taral-Patoliya** [comment] 2017-09-08 09:29
@okorshenko I have updated the issue, and added the precondition

**Comment by roma-glushko** [comment] 2017-09-23 13:45
I'll work on this one. Just to let you know. Thanks.

**Comment by roma-glushko** [comment] 2017-10-06 12:53
I would like to leave an update here. 
I have investigated this issue and create  PR https://github.com/magento/magento2/pull/11270 to fix it.

Looking forward to your review.

Thanks.

**Comment by hostep** [comment] 2017-10-07 09:32
Nice job @roma-glushko!

But since in Magento 2.2.0, the developer tab is [no longer available in production mode](http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/technical-details.html#config-deploy-admin), should effort still be put into fixing this bug? Unless you can still manipulate these settings from the config.php file? (which I haven't verified yet)

**Comment by versdivers** [comment] 2018-06-27 07:17
This is still an issue in Magento 2.2.4 and therefor the editors are not working like @Taral-Patoliya  explained

**Comment by hostep** [comment] 2018-06-27 18:30
@versdivers: the editors aren't working properly because some module will most likely have overwritten the default `<minify_exclude>` configuration of Magento which disables minifying for the tiny_mce editor js files, and overwriting that setting by another module will cause the editor to no longer work properly. You can read more about this issue over here: https://github.com/magento/magento2/issues/11577

In Magento 2.2.4 you are most likely running into the issue because one of the Klarna modules which get included in 2.2.4 by default is overwriting that setting. You can fix it by disabling those Klarna modules, or updating them, I think I saw an update coming through using composer and it no longer seem to include this problem.

I'm also not considering this a bug anymore, I think the real bug is that you are able to change this setting over website & storeview scope. I believe it would be better if you could only configure this setting on a global level. The static content deploy mechanism is completely new in Magento 2 so we can no longer compare to how minifying worked in Magento 1.

**Comment by versdivers** [comment] 2018-06-27 20:38
@hostep I do believe that you can make the merging a scoped level setting.  I mean.. Both the merged and the normal files are getting generated anyways.  Just make them load the one or the other based on the scoped level...

the tiny_mce is a bug indeed. But if there is a setting and it doesnt work that classifies as a bug. even tough removing the scope level is the fix

**Comment by hostep** [comment] 2018-06-28 07:28
> Both the merged and the normal files are getting generated anyways.

Ah, I wasn't aware of this, sorry, request sound reasonable then :)

**Comment by versdivers** [comment] 2018-07-04 02:39
Well i am running a production website that merges everything. I still have the normal pub/static/frontend/vendor/theme/store/... filles and i also have the merged filles. If i have some time i will dig into the code to see where we can adjust some things. If i do not forget it. For now my biggest problem is solved with the update of Klarna module with composer

**Comment by denysaw** [comment] 2018-11-15 20:40
This SHOULD be fixed for sure! Because Merging and Bundling JS in admin area for us caused error in completeLoad() method of lib/web/requirejs/require.js on Catalog -> Products page. It TOTALLY STUCKS in FF, and mostly totally stucks in Chrome! This is another huge stone to Magento's "stability". I even don't pray you will read this and fix this bug in a year. Community version should be fixed by a community, we got it long time ago. Thanks for the attention!

**Comment by CompactCodeEU** [comment] 2018-11-15 20:44
@denysaw what version are you using? on 2.2.6 we do not have any issue with merging

**Comment by denysaw** [comment] 2018-11-15 21:02
2.2.6 CE, sure. I console.logged all js files, which goes thru evaluation and there're just Magento's files ( Dunno even what to think. My only chance was to disable merge/bundle in admin area. But it's unreal, yep. Even tried to add scope 'store' rows in DB with configs (merge/bundling) just for store. Nothing (

**Comment by CompactCodeEU** [comment] 2018-11-15 21:39
How is Magento installed? Did you composer install it or? maybe run a composer update. There needs to be some difference between our installations.

**Comment by magento-engcom-team** [comment] 2019-01-10 13:17
Hi @engcom-backlog-tomash. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-10 14:05
@engcom-backlog-tomash Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97560`, `MAGETWO-97561` were created

**Comment by engcom-November** [comment] 2022-09-08 12:12
Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.
Configured JS bunding in Production mode as per [devdocs](https://developer.adobe.com/commerce/frontend-core/guide/themes/js-bundling/) and no Js errors were observed on admin UI and frontend. Kindly recheck the issue on Magento 2.4-develop branch as it is having latest code base and upcoming 2.4.x release. Please provide missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/189118704-4c1ca85d-048c-4894-bf71-66bea4d7e761.png)

**Comment by engcom-Dash** [comment] 2022-11-03 08:29
@magento give me 2.4-develop branch

**Comment by engcom-Dash** [comment] 2022-11-03 08:31
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-11-03 10:20
Hi @ Taral-Patoliya,

We are worked the issue with 2.4-develop instance...we are not able to reproduce the issue.we are getting actual result.
Steps we followed:

1.Install  magento Instance
2.go to stores
3.Click Advanced Go to developer
4.Click Js settings
5.Disable Js merge, minify, bundling for default scope in system config
6.Enable the same in Website scope
7.Enable the same in store view scope
8.In admin Panel all the Js files loaded separately

We are getting expected result as per your description.

I attached the screenshots for your Clarification:
These Screenshots refer Stores configuration as per your steps to reproduce.
<img width="1512" alt="Screenshot 2022-11-03 at 3 28 01 PM" src="https://user-images.githubusercontent.com/60198592/199694768-91fc0836-8023-424c-879d-eee3ef88a8a9.png">
<img width="1512" alt="Screenshot 2022-11-03 at 3 28 19 PM" src="https://user-images.githubusercontent.com/60198592/199694780-ee30b50e-4321-48fd-be5a-0ae62ea297eb.png">

<img width="1512" alt="Screenshot 2022-11-03 at 2 46 59 PM" src="https://user-images.githubusercontent.com/60198592/199695451-098af6dc-c4f7-4a90-b010-be41cada03a2.png">


Once the configuration admin Loaded all the Js files loaded separately....
<img width="1512" alt="Screenshot 2022-11-03 at 3 29 40 PM" src="https://user-images.githubusercontent.com/60198592/199695072-19f004c6-07d3-43fe-9770-e9113387926d.png">
<img width="1512" alt="Screenshot 2022-11-03 at 3 31 50 PM" src="https://user-images.githubusercontent.com/60198592/199695149-5995ab28-34a5-4f78-b460-c24d179461e5.png">

Let us know if we missing anything !!!

Thanks!!!

**Comment by hostep** [comment] 2022-11-03 11:00
@engcom-Dash: it kind of looks good I think (not sure why files aren't bundled in the admin that sounds like a problem still).
But next to this test, can you also try the reverse by:

- Disabling Js merge, minify, bundling for default scope in system config
- Enabling them in Website scope
- Enabling them same in store view scope

Which you said you did, but according to your screenshots you did the exact opposite...

**Comment by denysaw-gaming** [comment] 2022-11-03 11:27
How to unsubscribe of this channel? Magento is finally dead, but I'm still getting notifications of this thread and GitHub bugs to unsubscribe me ((

**Comment by hostep** [comment] 2022-11-03 12:07
@denysaw-gaming: There should be an `Unsubscribe` button on the right side of this ticket. If there is only a `Subscribe` button, press it and then press `Unsubscribe` afterwards, that should hopefully do the trick :)
Or stop watching the project entirely in github, that might also help ...

If you want to see what the future of Magento looks like, I would suggest you start following https://mage-os.org/ instead where we will try to continue with moving it forward without Adobe's help.

**Comment by denysaw** [comment] 2022-11-03 12:13
@hostep Thanx ;) I got I was logged in with different account. And Github was unable to unsubscribe me cuzz of that.

**Comment by engcom-Dash** [comment] 2023-01-11 00:43
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-11 02:12
Hi @hostep ,

Thanks for contribution with us,

1.We verified the issue according to your last comment...we are not able to reproduce the issue and we are trying to reproduce the issue in 2.4-develop branch.
2.As per your instructions we trying to reproduce the issue reversed by
reverse by:

Disabling Js merge, minify, bundling for default scope in system config
Enabling them in Website scope
Enabling them in store view scope

Magento version-2.4-develop
PHP 8.1

Steps we followed:
1.Install magento Instance
2.go to stores
3.Click Advanced Go to developer
4.Click Js settings
5.Enable Js merge, minify, bundling for default scope in system config
6.Disable the same in Website scope
7.Disable the same in store view scope

We are getting error in console and Js file or bundled files not loaded in both admin panel and store view.


Screenshots for your reference:
<img width="1512" alt="Screenshot 2023-01-11 at 7 29 56 AM" src="https://user-images.githubusercontent.com/60198592/211701800-11a0202c-2657-4f94-9432-b33d96680cbb.png">
<img width="1512" alt="Screenshot 2023-01-11 at 7 30 20 AM" src="https://user-images.githubusercontent.com/60198592/211701819-800b13c6-cabf-41b4-aeb7-7a5d547f580c.png">
<img width="1512" alt="Screenshot 2023-01-11 at 7 30 33 AM" src="https://user-images.githubusercontent.com/60198592/211701829-7e6617c0-6595-4517-b656-75c62135feef.png">
<img width="1512" alt="Screenshot 2023-01-11 at 7 41 14 AM" src="https://user-images.githubusercontent.com/60198592/211701836-97b1ccde-668d-4f31-b246-4e0e7de15196.png">
<img width="1512" alt="Screenshot 2023-01-11 at 7 41 18 AM" src="https://user-images.githubusercontent.com/60198592/211701839-519ca761-60f8-4346-8e92-93fc9aaf7503.png">

Let us know if we are missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2023-02-24 10:28
Hi @Taral-Patoliya ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-02-24 10:28 UTC
Labels: Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Component: Developer, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Issue: On Hold, Issue: needs update, Area: Admin UI
