### ISSUE TITLE
Product image issue with multiple store views Magento 2.1.0

### ISSUE THREAD

**Issue by storepeinture** [magento/magento2#6259] opened 2016-08-20 17:20 UTC
Product images in multi store view (multiple language store views) cannot be hidden independently.

### Preconditions

1. Magento CE 2.1.0 without sample data is installed
2. Template Extension Smartwave Porto installed
3. No other extensions installed
### Steps to reproduce

1. Create a multiple store views (e.g. French and English) under one main website
2. Create a configurable product (e.g. differenz sizes of a shirt)
3. Switch store view to French store view
4. Add a product image with a FRENCH Language Label and check Thumbnail, Base Image, and Small Image -> Save!
5. Switch store view to English store view
6. Add a product image with an ENGLISH Language Label and check Thumbnail, Base Image, and Small Image -> Save!
7. In bothe store views, both images (French and English) are visible
8. Still in English store view: Hide the French image -> Save!
9. Switch store view to French store view
10. Go to images and hide the ENGLISH product image -> Save!
11. On the French store view, only the French image is displayed. On the English store view, only the English image is displayed. Also on the front-end, in the French store you can only see the French product image and in the English store you only see the English image
12. After some 2 to 5 hours all product images are hidden in the store view. In the back-end product site the products are NOT HIDDEN.
13. It is possible to do the setup as described and the site will display images correctly for a few hours until the error is created again.
### Expected result

1. Setup the images for French and English Store View
2. The English images are shown in the English store front-end and the same goes for the French store view
### Actual result

1. At first images are shown correctly
2. After some hours the images are disabled in the front end, and NO IMAGES are shown in either store front-end

**Comment by picamator** [comment] 2016-08-30 06:24
@storepeinture thank you for issue report. 
Unfortunately we cannot reproduce that problem.
Could you please add information about:
1. Do you have any crons running?
2. Do you notice images disappearance after some actions such as adding new product or cache clearing etc.? Could you provide those actions?

**Comment by storepeinture** [comment] 2016-09-02 23:55
Dear picamator,
thank you for your response.
I can answer your questions as follows:
1. I have no scheduled cron jobs running.
2. Cache is disabled since I'm in development mode. But I believe that it happens when I make a change to the configurable product in "All Store Views" (e.g. change the category for both store views, or change the global SKU). (Under "All Store Views" none of the images have a check-mark as base, small and thumbnail.)

What's irritating is, that everything else seems to be left untouched. In my opinion, this is still a bug. If I make changes to a configurable product in "All Store Views" and save, that should not change the local settings in the local store views.

For example, settings under "Search Engine Optimization" are left untouched, e.g. the meta-description is still written in the local store language (French and English).
The only thing that I find is altered are that the check-marks on product images for "Base", "Small", and "Thumbnail" are removed! So the images wont display anymore. 

In my opinion this should be changed to be coherent with other functionality inside Magento 2.

Thanks for responding!

**Comment by picamator** [comment] 2016-09-05 14:55
@storepeinture thank you for adding details. We have managed to reproduce it.
Internal ticket was created MAGETWO-58053.

**Comment by veloraven** [comment] 2017-06-19 17:22
Internal ticket for ver. 2.1 - MAGETWO-58436
This issue was already fixed for develop branch

**Comment by magento-engcom-team** [comment] 2017-09-20 22:31
@storepeinture, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:31 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
