### ISSUE TITLE
getPriceFormat calculates wrong precision in CentOS when using some special currencies

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#12090] opened 2017-11-07 22:11 UTC
for currencies that have Swedish rounding (https://en.wikipedia.org/wiki/Cash_rounding), `Magento\Framework\Locale\Format::getPriceFormat()` returns the wrong number precision in some operating systems (tested with CentOS)

### Preconditions
1. Magento 2.2.0
2. PHP 7.0.19
3. CentOS Linux 7 (Core)

### Steps to reproduce
1. set store locale to `de_CH`
2. check html source for `/checkout/cart/` and look for `priceFormat` json value

### Expected result
1. precision should be 2: `"priceFormat":{"pattern":"CHF\u00a0%s","precision":2,"requiredPrecision":2,"decimalSymbol":".","groupSymbol":"'","groupLength":3,"integerRequired":1}` 

### Actual result
1. precision is set to 1: `"priceFormat":{"pattern":"CHF\u00a0%s","precision":1,"requiredPrecision":1,"decimalSymbol":".","groupSymbol":"'","groupLength":3,"integerRequired":1}`

the centos format represents the number format with swedish rounding, while the debian locale format for example doesn't:

`php -r '$formatter = new \NumberFormatter("de_CH", \NumberFormatter::CURRENCY); echo $formatter->getPattern();'`:
centos: `¤ #,##0.05;¤-#,##0.05`
debian: `¤ #,##0.00;¤-#,##0.00`

`Magento\Framework\Locale\Format::getPriceFormat()` only counts `0` when calculating the precision, where it really should check for all after-decimal-point numbers to properly respect the locale settings in different OSes. the result is that in CentOS in a de_CH store, prices are now displayed rounded wrongly, f.e. during checkout.

this is a regression newly introduced in 2.2 with the use of `NumberFormatter`. it can be fixed for `de_CH` by changing the regex like so: `$format = preg_replace("/[^015\#\.,]/", '', $format);`, but there might be further work needed for currencies that have a format of `0.50` (see wikipedia page)

**Comment by magento-engcom-team** [comment] 2017-11-09 08:30
@heldchen, thank you for your report.
We've created internal ticket(s) MAGETWO-83513 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2019-03-20 12:12
Hi @josefbehr. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by HirokazuNishi** [comment] 2019-03-20 12:21
@josefbehr @heldchen Did you try https://github.com/magento/magento2-jp ? CurrencyPrecision module may help you.

**Comment by magento-engcom-team** [comment] 2019-12-10 14:37
@heldchen, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-12-10 14:37 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
