### ISSUE TITLE
getFullActionName() returns __ on CMS & Category Pages

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#35594] opened 2022-06-09 05:36 UTC
### Preconditions and environment

- Magento 2.4.4
- FPC enabled
- Observe the event `controller_action_predispatch`

### Steps to reproduce

1. Observe the event `controller_action_predispatch` in `app/code/Vendor/Module/etc/frontend/events.xml`.  
And observer looks like
```
public function execute(Observer $observer)
{
    $request = $observer->getEvent()->getRequest();
    $fullActionName = $request->getFullActionName();
    file_put_contents(BP . '/var/log/http.log', $fullActionName . PHP_EOL, FILE_APPEND | LOCK_EX);
    // $fullActionName gives ___ value 
    // for CMS & Category pages (M2.4.4)
    // ...    
}
```
2. Go to Homepage(/) or any CMS page, Example: `/about-us`

### Expected result

`$fullActionName` should give `cms_page_view`

### Actual result

`$fullActionName` is giving `__`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-06-09 09:16
Hello @MagePsycho,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch, by following the below steps:
1. Make some code changes to debug and ddd a breakpoint in file `https://github.com/magento/magento2/blob/a8543fed035d85c667195e95f69476d51f98381b/lib/internal/Magento/Framework/App/Request/Http.php#L395`:
```
public function getFullActionName($delimiter = '_')
    {
        $full_action_name = $this->getRouteName() .
            $delimiter .
            $this->getControllerName() .
            $delimiter .
            $this->getActionName();
        return $full_action_name;
    }
```
2. Trying to access the `about-us` page from the frontend. 

As per our observation initially, when program execution breaks on the breakpoint we can see the value of variable `$full_action_name` is `__`, but after some more hits in the same request the value of that variable has been the expected one i.e. `cms_page_view`. Please refer to the below screencast for the reference:


https://user-images.githubusercontent.com/51681618/172811562-5406e685-4d39-488e-963a-28a6d1e08ddb.mp4

But the page is rendering without any issue. We request you to tell us the use case in which you are not able to proceed further due to this.

Thanks

**Comment by MagePsycho** [comment] 2022-06-09 10:42
@engcom-Hotel 

Try to observe the event `controller_action_predispatch` in `app/code/Vendor/Module/etc/frontend/events.xml`.  

Where the observer may look like this, for example
```
public function execute(Observer $observer)
{
    $request = $observer->getEvent()->getRequest();
    $fullActionName = $request->getFullActionName();
    file_put_contents(BP . '/var/log/http.log', $fullActionName . PHP_EOL, FILE_APPEND | LOCK_EX);
    // $fullActionName gives ___ value 
    // for CMS & Category pages (M2.4.4)
    // ...    
}
```
And go to any CMS page, Example: `/about-us` (Make sure the FPC is enabled and you are visiting the page more than once)

You will always get the value as `__`

Note this also happens with the event `controller_front_send_response_before`

**Comment by engcom-Hotel** [comment] 2022-06-21 13:00
Hello @MagePsycho,

I have followed the same way. Please consider the screencast in this https://github.com/magento/magento2/issues/35594#issuecomment-1150877551. I need to ask about the use case where the functionality is breaking for you.

Thanks

**Comment by MagePsycho** [comment] 2022-06-27 07:14
It's working for the `cms_page_view` but not for `cms_index_index` (Homepage).
Can you please debug with the same approach for the Homepage (/)?

**Comment by engcom-Hotel** [comment] 2022-06-28 11:27
Hello @MagePsycho,

Thanks for the reply!

We have checked it for `HomePage` as well. But here also the issue is not reproducible for us. Please refer the below screencast for reference:


https://user-images.githubusercontent.com/51681618/176167597-fe98a994-9a85-49f8-818d-f2ed0c26b709.mp4

Please let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-07-12 07:02
Dear @MagePsycho,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-07-12 07:02 UTC
Labels: Triage: Dev.Experience, Issue: needs update
