### ISSUE TITLE
Bundle product options deleted incorrectly

### ISSUE THREAD

**Issue by davekleijn** [magento/magento2#30347] opened 2020-10-05 14:17 UTC
When creating a bundle product with more than 20 options, it is not possible to delete one option. All options that are not on the first page will be removed. Also an Javascript error is shown in the console log.

### Preconditions (*)
1. Magento 2.4.0
2. PHP 7.3.19

### Steps to reproduce (*)
1. Create a bundle product
2. Add more than 20 product options (important for getting multiple pages)
3. Add one product to each option (choose random simple product from sample data)
4. Save the bundle product
5. Go to the second page of bundle options
6. Click on the remove icon for removing the product of the option
7. Click on the remove icon of the option itself
7. Save the product

### Expected result (*)
1. One option is deleted and all other options are still not deleted

### Actual result (*)
1. All bundle options on the second page are removed
2. Javascript error message is shown in console log

![screenshot-magento](https://user-images.githubusercontent.com/17762698/95090626-c5e16700-0725-11eb-9915-b47fcd95daef.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [*] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2020-10-10 04:49
#dmcdindia2020

**Comment by krishprakash** [comment] 2020-10-10 04:52
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-10-10 05:33
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38332` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment] 2020-10-10 09:10
#dmcdindia2020

**Comment by raoulguillermo** [comment] 2022-02-09 20:19
I'm experiencing the same issue in magento 2.3.5 using php 7.3
Any solutions on this matter?

**Comment by engcom-Bravo** [comment] 2024-05-28 06:13
Hi @Davie82,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1384" alt="Screenshot 2024-05-28 at 11 38 27" src="https://github.com/magento/magento2/assets/51680745/40badc42-403a-4f0d-98d9-0cdc8edabeaf">


One option is deleted and all other options are still not deleted

Hence We are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-28 06:13 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Component: Bundle, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Event: dmcdindia2020, Reported on 2.4.0
