### ISSUE TITLE
"Something went wrong with processing the default view and we have restored the filter to its original state." 

### ISSUE THREAD

**Issue by The-Tool-Room** [magento/magento2#34082] opened 2021-09-14 23:57 UTC
### Steps to reproduce (*)
On loading Admin - Catalog - Products, below error message is getting displayed on UI.
Something went wrong with processing the default view and we have restored the filter to its original state.

I've tried logging out, refreshing I can't seem to remove this error. 
Restart elastic search, reindex and clear cache - No luck. Error message is displayed.

### Expected result (*)
Catalog - Products page should be displayed with page size set

### Actual result (*)
![image](https://user-images.githubusercontent.com/60198231/134893416-e1c0553a-4078-46d2-83ca-b7b755e110bc.png)

**Workaround:**
User have to remove entry in ui_bookmark table using below command to resolve this issue.
(> TRUNCATE ui_bookmark;)

**Comment by The-Tool-Room** [comment] 2021-09-14 23:58
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-09-15 07:38
Hi @The-Tool-Room ,

This issue is not reproducible on Magento 2.4-develop branch and also on latest Magento open source version: 2.4.3.
If you are using older Magento version, please check below possible cases that may help you resolve the issue:

1. If any of the products have null as SKU value (Or SKU number deleted), there may be possibility of this error. Update 'sku' in "catalog_product_entity" table in DB for products having NULL value. 
(run SELECT * FROM catalog_product_entity WHERE sku IS NULL to check all products having null and update them / empty them)
2  There may be possibility of this error for user/admin with limited access roles. Admin - System - User Roles - try enabling all product-related resources and Order related resources and see if it works for you.
3. Remove the entry from the ui_bookmark table  (> TRUNCATE ui_bookmark;)

Kindly recheck the issue on Magento 2.4-develop branch and elaborate / provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-27 10:35
This issue is intermittently reproducible on Magento 2.4-develop branch.
Magento 2.4-develop with Inventory Modules enabled
Catalog have products more than 100
On loading Admin - Catalog - Products - with pagination set to 200, below error message is getting displayed on UI.
Something went wrong with processing the default view and we have restored the filter to its original state.
![image](https://user-images.githubusercontent.com/60198231/134892843-59721030-6a21-4991-9968-bb03fcf1934c.png)

**Comment by engcom-November** [comment] 2021-09-28 12:56
Cannot able to reproduce this issue on clean Magento 2.4-develop instance with above steps performed. Hence closing this issue.
@The-Tool-Room , if you come across this issue on Magento 2.4-develop branch, kindly reopen/create new ticket with elaborated steps to reproduce the issue.
Thank you.

**Closed as completed by engcom-November** 2021-09-28 12:56 UTC
Labels: Component: Catalog, Issue:  Cannot Reproduce, Reproduced on 2.4.x, Progress: done, Issue: needs update, Reported on 2.4.x, Area: Catalog
