### ISSUE TITLE
414 (Request-URI Too Large) when using export customer csv in magento 2.1.4

### ISSUE THREAD

**Issue by Jalondhara** [magento/magento2#10584] opened 2017-08-18 11:04 UTC
I have fetched issues when I export large customer csv data in magento 2.1.4 site.

Request-URI Too Large : The requested URL's length exceeds the capacity limit for this server.

https://www.xyz.com/manage/mui/export/gridToCsv/key/c9ec82e0c91fb4cc7c92fbacaabe74f89e7f2a659cac725ddb667e240081bbc8/?filters%5Bplaceholder%5D=true&search=&namespace=customer_listing&selected%5B%5D=1756&selected%5B%5D=1755&selected%5B%5D=1754&selected%5B%5D=1753&selected%5B%5D=1752&selected%5B%5D=1751&selected%5B%5D=1750&selected%5B%5D=1749&selected%5B%5D=1748&selected%5B%5D=1747&selected%5B%5D=1746&selected%5B%5D=1745&selected%5B%5D=1744&selected%5B%5D=1743&selected%5B%5D=1742&selected%5B%5D=1741&selected%5B%5D=1740&selected%5B%5D=1739&selected%5B%5D=1738&selected%5B%5D=1737&selected%5B%5D=1736&selected%5B%5D=1735&selected%5B%5D=1734&selected%5B%5D=1733&selected%5B%5D=1732&selected%5B%5D=1731&selected%5B%5D=1730&selected%5B%5D=1729&selected%5B%5D=1728&selected%5B%5D=1727&selected%5B%5D=1726&selected%5B%5D=1725&selected%5B%5D=1724&selected%5B%5D=1723&selected%5B%5D=1722&selected%5B%5D=1721&selected%5B%5D=1720&selected%5B%5D=1719&selected%5B%5D=1718&selected%5B%5D=1717&selected%5B%5D=1716&selected%5B%5D=1715&selected%5B%5D=1714&selected%5B%5D=1713&selected%5B%5D=1712&selected%5B%5D=1711&selected%5B%5D=1710&selected%5B%5D=1709&selected%5B%5D=1708&selected%5B%5D=1707&selected%5B%5D=1706&selected%5B%5D=1705&selected%5B%5D=1704&selected%5B%5D=1703&selected%5B%5D=1702&selected%5B%5D=1701&selected%5B%5D=1700&selected%5B%5D=1699&selected%5B%5D=1698&selected%5B%5D=1697&selected%5B%5D=1696&selected%5B%5D=1695&selected%5B%5D=1694&selected%5B%5D=1693&selected%5B%5D=1692&selected%5B%5D=1691&selected%5B%5D=1690&selected%5B%5D=1689&selected%5B%5D=1688&selected%5B%5D=1687&selected%5B%5D=1686&selected%5B%5D=1685&selected%5B%5D=1684&selected%5B%5D=1683&selected%5B%5D=1682&selected%5B%5D=1681&selected%5B%5D=1680&selected%5B%5D=1679&selected%5B%5D=1678&selected%5B%5D=1677&selected%5B%5D=1676&selected%5B%5D=1675&selected%5B%5D=1674&selected%5B%5D=1673&selected%5B%5D=1672&selected%5B%5D=1671&selected%5B%5D=1670&selected%5B%5D=1669&selected%5B%5D=1668&selected%5B%5D=1667&selected%5B%5D=1666&selected%5B%5D=1665&selected%5B%5D=1664&selected%5B%5D=1663&selected%5B%5D=1662&selected%5B%5D=1661&selected%5B%5D=1660&selected%5B%5D=1659&selected%5B%5D=1658&selected%5B%5D=1657&selected%5B%5D=1656&selected%5B%5D=1655&selected%5B%5D=1654&selected%5B%5D=1653&selected%5B%5D=1652&selected%5B%5D=1651&selected%5B%5D=1650&selected%5B%5D=1649&selected%5B%5D=1648&selected%5B%5D=1647&selected%5B%5D=1646&selected%5B%5D=1645&selected%5B%5D=1644&selected%5B%5D=1643&selected%5B%5D=1642&selected%5B%5D=1641&selected%5B%5D=1640&selected%5B%5D=1639&selected%5B%5D=1638&selected%5B%5D=1637&selected%5B%5D=1636&selected%5B%5D=1635&selected%5B%5D=1634&selected%5B%5D=1633&selected%5B%5D=1632&selected%5B%5D=1631&selected%5B%5D=1630&selected%5B%5D=1629&selected%5B%5D=1628&selected%5B%5D=1627&selected%5B%5D=1626&selected%5B%5D=1625&selected%5B%5D=1624&selected%5B%5D=1623&selected%5B%5D=1622&selected%5B%5D=1621&selected%5B%5D=1620&selected%5B%5D=1619&selected%5B%5D=1618&selected%5B%5D=1617&selected%5B%5D=1616&selected%5B%5D=1615&selected%5B%5D=1614&selected%5B%5D=1613&selected%5B%5D=1612&selected%5B%5D=1611&selected%5B%5D=1610&selected%5B%5D=1609&selected%5B%5D=1608&selected%5B%5D=1607&selected%5B%5D=1606&selected%5B%5D=1605&selected%5B%5D=1604&selected%5B%5D=1603&selected%5B%5D=1602&selected%5B%5D=1601&selected%5B%5D=1600&selected%5B%5D=1599&selected%5B%5D=1598&selected%5B%5D=1597&selected%5B%5D=1596&selected%5B%5D=1595&selected%5B%5D=1594&selected%5B%5D=1593&selected%5B%5D=1592&selected%5B%5D=1591&selected%5B%5D=1590&selected%5B%5D=1589&selected%5B%5D=1588&selected%5B%5D=1587&selected%5B%5D=1586&selected%5B%5D=1585&selected%5B%5D=1584&selected%5B%5D=1583&selected%5B%5D=1582&selected%5B%5D=1581&selected%5B%5D=1579&selected%5B%5D=1578&selected%5B%5D=1577&selected%5B%5D=1576&selected%5B%5D=1575&selected%5B%5D=1574&selected%5B%5D=1573&selected%5B%5D=1572&selected%5B%5D=1571&selected%5B%5D=1570&selected%5B%5D=1569&selected%5B%5D=1568&selected%5B%5D=1567&selected%5B%5D=1566&selected%5B%5D=1565&selected%5B%5D=1564&selected%5B%5D=1563&selected%5B%5D=1562&selected%5B%5D=1561&selected%5B%5D=1560&selected%5B%5D=1559&selected%5B%5D=1558&selected%5B%5D=1557&selected%5B%5D=1556&selected%5B%5D=1555&selected%5B%5D=1554&selected%5B%5D=1553&selected%5B%5D=1552&selected%5B%5D=1551&selected%5B%5D=1550&selected%5B%5D=1549&selected%5B%5D=1548&selected%5B%5D=1547&selected%5B%5D=1546&selected%5B%5D=1545&selected%5B%5D=1544&selected%5B%5D=1543&selected%5B%5D=1542&selected%5B%5D=1541&selected%5B%5D=1540&selected%5B%5D=1537&selected%5B%5D=1536&selected%5B%5D=1535&selected%5B%5D=1534&selected%5B%5D=1533&selected%5B%5D=1532&selected%5B%5D=1531&selected%5B%5D=1530&selected%5B%5D=1529&selected%5B%5D=1528&selected%5B%5D=1525&selected%5B%5D=1524&selected%5B%5D=1523&selected%5B%5D=1522&selected%5B%5D=1521&selected%5B%5D=1520&selected%5B%5D=1519&selected%5B%5D=1518&selected%5B%5D=1517&selected%5B%5D=1516&selected%5B%5D=1515&selected%5B%5D=1514&selected%5B%5D=1513&selected%5B%5D=1512&selected%5B%5D=1511&selected%5B%5D=1510&selected%5B%5D=1509&selected%5B%5D=1508&selected%5B%5D=1507&selected%5B%5D=1506&selected%5B%5D=1505&selected%5B%5D=1504&selected%5B%5D=1503&selected%5B%5D=1502&selected%5B%5D=1501&selected%5B%5D=1500&selected%5B%5D=1499&selected%5B%5D=1498&selected%5B%5D=1497&selected%5B%5D=1496&selected%5B%5D=1495&selected%5B%5D=1494&selected%5B%5D=1493&selected%5B%5D=1492&selected%5B%5D=1491&selected%5B%5D=1490&selected%5B%5D=1489&selected%5B%5D=1488&selected%5B%5D=1487&selected%5B%5D=1486&selected%5B%5D=1485&selected%5B%5D=1484&selected%5B%5D=1483&selected%5B%5D=1482&selected%5B%5D=1481&selected%5B%5D=1480&selected%5B%5D=1479&selected%5B%5D=1478&selected%5B%5D=1477&selected%5B%5D=1476&selected%5B%5D=1475&selected%5B%5D=1474&selected%5B%5D=1473&selected%5B%5D=1472&selected%5B%5D=1471&selected%5B%5D=1470&selected%5B%5D=1469&selected%5B%5D=1468&selected%5B%5D=1467&selected%5B%5D=1466&selected%5B%5D=1465&selected%5B%5D=1464&selected%5B%5D=1463&selected%5B%5D=1462&selected%5B%5D=1461&selected%5B%5D=1460&selected%5B%5D=1459&selected%5B%5D=1458&selected%5B%5D=1457&selected%5B%5D=1456&selected%5B%5D=1455&selected%5B%5D=1454&selected%5B%5D=1453&selected%5B%5D=1452&selected%5B%5D=1451&selected%5B%5D=1450&selected%5B%5D=1449&selected%5B%5D=1448&selected%5B%5D=1447&selected%5B%5D=1446&selected%5B%5D=1445&selected%5B%5D=1444&selected%5B%5D=1443&selected%5B%5D=1442&selected%5B%5D=1441&selected%5B%5D=1440&selected%5B%5D=1439&selected%5B%5D=1438&selected%5B%5D=1437&selected%5B%5D=1436&selected%5B%5D=1435&selected%5B%5D=1434&selected%5B%5D=1433&selected%5B%5D=1432&selected%5B%5D=1431&selected%5B%5D=1430&selected%5B%5D=1429&selected%5B%5D=1428&selected%5B%5D=1427&selected%5B%5D=1426&selected%5B%5D=1425&selected%5B%5D=1424&selected%5B%5D=1423&selected%5B%5D=1422&selected%5B%5D=1421&selected%5B%5D=1420&selected%5B%5D=1419&selected%5B%5D=1418&selected%5B%5D=1417&selected%5B%5D=1416&selected%5B%5D=1415&selected%5B%5D=1414&selected%5B%5D=1413&selected%5B%5D=1412&selected%5B%5D=1411&selected%5B%5D=1410&selected%5B%5D=1409&selected%5B%5D=1408&selected%5B%5D=1407&selected%5B%5D=1406&selected%5B%5D=1405&selected%5B%5D=1404&selected%5B%5D=1403&selected%5B%5D=1402&selected%5B%5D=1401&selected%5B%5D=1400&selected%5B%5D=1399&selected%5B%5D=1398&selected%5B%5D=1397&selected%5B%5D=1396&selected%5B%5D=1395&selected%5B%5D=1394&selected%5B%5D=1393&selected%5B%5D=1392&selected%5B%5D=1391&selected%5B%5D=1390&selected%5B%5D=1389&selected%5B%5D=1388&selected%5B%5D=1387&selected%5B%5D=1386&selected%5B%5D=1385&selected%5B%5D=1384&selected%5B%5D=1383&selected%5B%5D=1382&selected%5B%5D=1381&selected%5B%5D=1380&selected%5B%5D=1379&selected%5B%5D=1378&selected%5B%5D=1377&selected%5B%5D=1376&selected%5B%5D=1375&selected%5B%5D=1374&selected%5B%5D=1373&selected%5B%5D=1372&selected%5B%5D=1371&selected%5B%5D=1370&selected%5B%5D=1369&selected%5B%5D=1368&selected%5B%5D=1367&selected%5B%5D=1366&selected%5B%5D=1365&selected%5B%5D=1364&selected%5B%5D=1363&selected%5B%5D=1362&selected%5B%5D=1361&selected%5B%5D=1360&selected%5B%5D=1359&selected%5B%5D=1358&selected%5B%5D=1357&selected%5B%5D=1356&selected%5B%5D=1355&selected%5B%5D=1354&selected%5B%5D=1353&selected%5B%5D=1352&selected%5B%5D=1351&selected%5B%5D=1350&selected%5B%5D=1349&selected%5B%5D=1348&selected%5B%5D=1347&selected%5B%5D=1346&selected%5B%5D=1345&selected%5B%5D=1344&selected%5B%5D=1343&selected%5B%5D=1342&selected%5B%5D=1341&selected%5B%5D=1340&selected%5B%5D=1339&selected%5B%5D=1338&selected%5B%5D=1337&selected%5B%5D=1336&selected%5B%5D=1335&selected%5B%5D=1334&selected%5B%5D=1333&selected%5B%5D=1332&selected%5B%5D=1331&selected%5B%5D=1330&selected%5B%5D=1329&selected%5B%5D=1328&selected%5B%5D=1327&selected%5B%5D=1326&selected%5B%5D=1325&selected%5B%5D=1324&selected%5B%5D=1323&selected%5B%5D=1322&selected%5B%5D=1321&selected%5B%5D=1320&selected%5B%5D=1319&selected%5B%5D=1318&selected%5B%5D=1317&selected%5B%5D=1316&selected%5B%5D=1315&selected%5B%5D=1314&selected%5B%5D=1313&selected%5B%5D=1312&selected%5B%5D=1311&selected%5B%5D=1310&selected%5B%5D=1309&selected%5B%5D=1308&selected%5B%5D=1307&selected%5B%5D=1306&selected%5B%5D=1305&selected%5B%5D=1304&selected%5B%5D=1303&selected%5B%5D=1302&selected%5B%5D=1301&selected%5B%5D=1300&selected%5B%5D=1299&selected%5B%5D=1298&selected%5B%5D=1297&selected%5B%5D=1296&selected%5B%5D=1295&selected%5B%5D=1294&selected%5B%5D=1293&selected%5B%5D=1292&selected%5B%5D=1291&selected%5B%5D=1290&selected%5B%5D=1289&selected%5B%5D=1288&selected%5B%5D=1287&selected%5B%5D=1286&selected%5B%5D=1285&selected%5B%5D=1284&selected%5B%5D=1283&selected%5B%5D=1282&selected%5B%5D=1281&selected%5B%5D=1280&selected%5B%5D=1279&selected%5B%5D=1278&selected%5B%5D=1277&selected%5B%5D=1276&selected%5B%5D=1275&selected%5B%5D=1274&selected%5B%5D=1273&selected%5B%5D=1272&selected%5B%5D=1271&selected%5B%5D=1270&selected%5B%5D=1269&selected%5B%5D=1268&selected%5B%5D=1267&selected%5B%5D=1266&selected%5B%5D=1265&selected%5B%5D=1264&selected%5B%5D=1263&selected%5B%5D=1262&selected%5B%5D=1261&selected%5B%5D=1260&selected%5B%5D=1259&selected%5B%5D=1258&selected%5B%5D=1257&selected%5B%5D=1256&selected%5B%5D=1255&selected%5B%5D=1254&selected%5B%5D=1253&selected%5B%5D=1252
![request_url_too_large](https://user-images.githubusercontent.com/31101994/29456421-282488da-8433-11e7-80a8-8379711e7094.png)

**Comment by orlangur** [comment] 2017-08-18 11:43
Please always try freshest version available (namely `2.1.8` in this case) prior to issue report. This could have been fixed in 048d2e6991d964f8ee770a3377cc5fde62802f63.

**Comment by Jalondhara** [comment] 2017-08-22 13:41
Hello, Please help me for resolved this issue.

**Comment by orlangur** [comment] 2017-08-22 13:50
Please check if the issue is still reproduced if you upgrade to `2.1.8`.

**Comment by Jalondhara** [comment] 2017-08-22 13:52
I need to resolved this issue on magento 2.1.4 version.

**Comment by orlangur** [comment] 2017-08-22 13:58
This is not a recommended way, you can try to apply commit I mentioned or other related to fix changes at your own risk though.

Issue shall be closed if it is not reproducible on latest `2.1.x` version.

**Comment by Jalondhara** [comment] 2017-08-22 14:08
Our current site is live, In this site most of the customers and orders So we can not upgrade this site. Please give me another way for resolved this issue.

**Comment by orlangur** [comment] 2017-08-22 14:59
Of course you should not upgrade production site. Just use your staging/local environment to check it and then deploy to production.

The ultimate way to obtain fixes is version upgrade. Old version bug reports are out of scope for this repository.

**Comment by piotrkwiecinski** [comment] 2017-08-22 15:17
@Jalondhara you could replace the 2.1.4 class with implementation put  mentioned by @orlangur using custom module and DI or use plugin as it's public method, but it would be done on your own risk as said above and upgrade is recommended.

**Comment by orlangur** [comment] 2017-09-06 17:52
No sign the issue is reproducible on `2.1.8`.

**Closed as completed by orlangur** 2017-09-06 17:52 UTC
