### ISSUE TITLE
With enabled cache KO object exists on page initialization that should be loaded only after add to cart action

### ISSUE THREAD

**Issue by kandrejevs** [magento/magento2#4522] opened 2016-05-16 07:38 UTC
I added a new object to section, that is loaded on `checkout/cart/add` action. Problem is that this KO object binding exists on page initialization if the cache is enabled.
## Steps to reproduce
1. Add new KO object to `checkout/cart/add` action
2. Create KO template, that outputs data from this object wrapped in if statement. Insert template in product page.
3. Enable cache
4. Add product to cart or sometimes it appears even without adding items to cart.
5. Browse other products.
## Expected result

Data inside KO template should only be outputed after product is added to cart and KO bindings are loaded via section.
## Actual result

With enabled cache binded KO object exists on page initialization and content inside KO template appears after page is loaded.

Note, my new KO binding is made in the same way as "cart" section, but cart KO binding does not exist at page initialization.

**Comment by palamar** [comment] 2016-06-22 16:45
@ kandrejevs 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by kandrejevs** [comment] 2016-07-04 11:14
@palamar issue is still present in 2.1.0 and 2.0.7 versions.

**Comment by anton-huz** [comment] 2016-07-15 10:15
Hi @kandrejevs ,
We are going to investigate under MAGETWO-55442 internal ticket.

**Comment by kandrejevs** [comment] 2016-07-28 13:33
let me know, if you need code example

**Comment by magento-engcom-team** [comment] 2017-11-29 15:30
@kandrejevs, thank you for your report.
We've created internal ticket(s) MAGETWO-55442 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-07-30 06:15
Hi @kandrejevs

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-08-20 08:46
@kandrejevs thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-08-20 08:46 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, triage wanted
