### ISSUE TITLE
Deadlock on url_rewrite when importing

### ISSUE THREAD

**Issue by stephansteiner** [magento/magento2#25882] opened 2019-12-03 07:19 UTC
When importing a large CSV file containing simple products, I get a database error:

Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: INSERT  INTO `url_rewrite` (`redirect_type`,`is_autogenerated`,`metadata`,`description`,`entity_type`,`entity_id`,`request_path`,`target_path`,`store_id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?)

This worked fine in Magento 2.3.1. I noticed the error after upgrading to Magento 2.3.3

The issue seems to be related to a change in the vendor/magento/module-catalog-url-rewrite/Model/Storage/DbStorage.php in function prepareSelect.
When removing this statement
```
['relation.category_id', 'relation.product_id']
```
from 
```
$select->joinLeft(
            ['relation' => $this->resource->getTableName(Product::TABLE_NAME)],
            'url_rewrite.url_rewrite_id = relation.url_rewrite_id',
            ['relation.category_id', 'relation.product_id']
        );
```

the import works fine again as it did before.

### Preconditions (*)
- Magento 2.3.3
- create a csv file of products to be imported 

### Steps to reproduce (*)
1. In Magento 2.3.3 open the System > Data Transfer > Import section.
2. Use the following settings: Entity Type: Product, Import Behavior: Add/Update, Validation Strategy: Stop on error
3. Select csv file previously created and start import

### Expected result (*)
After validation of csv file, import should succeed.

### Actual result (*)
Database error with serialization failure (Deadlock found)

**Comment by engcom-Charlie** [comment] 2019-12-03 11:41
Hello @stephansteiner 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the Magento 2.3.3

**Testing scenario:**
1. Export products
![image](https://user-images.githubusercontent.com/51680850/70047942-c7a44080-15d1-11ea-9c3d-b1db7477fe81.png)
2. Download CSV file
3. In Magento 2.3.3 open the System > Data Transfer > Import section.
4. Use the following settings: Entity Type: Product, Import Behavior: Add/Update, Validation Strategy: Stop on error
![image](https://user-images.githubusercontent.com/51680850/70048008-f28e9480-15d1-11ea-8e85-96f5ee26157c.png)

5. Select CSV file previously created and start import
6. Check Data
![image](https://user-images.githubusercontent.com/51680850/70048069-21a50600-15d2-11ea-8aba-81489020fdb5.png)

**Result:**
Import finished successfully.
![image](https://user-images.githubusercontent.com/51680850/70048110-3d101100-15d2-11ea-998b-144f457da447.png)

So i have to close this issue.
If you have any updates inform me please.

**Closed as completed by engcom-Charlie** 2019-12-03 11:41 UTC
Labels: Issue: Format is valid
