### ISSUE TITLE
Category Rule - product not assigned automatically unless category is manually re-saved

### ISSUE THREAD

**Issue by ozzman6154** [magento/magento2#20188] opened 2019-01-11 00:17 UTC
Hi there,

It is observed that category rule related to "clone category" does not work unless the category where the category rule is applied is manually re-saved.

### Preconditions:
1. Magento version is Magento Commerce Cloud 2.1.10
2. It can be reproduced on a plain install of Magento

### Steps to reproduce:
1. Login to Magento admin
2. Select a store view
3. Ensure there are two categories (a parent category A and subcategory B) to test this scenario.
4. In subcategory B, create a category rule with condition "Category Clone ID equals {category A ID}. 5.Save subcategory B.
6. Navigate to Products -> Catalog
7. Edit a sku and assign subcategory B to this sku.
8. Save this sku

Expected result: 
Product is assigned to subcategory B. Number of products in subcategory B is incremented by 1. Product is assigned to Category A as clone ID equals Category A. Number of products in Category A is incremented by 1. 

Actual result: 
Product is assigned to subcategory B. Number of products in subcategory B is incremented by 1. Product is assigned to Category A as clone ID equals Category A. Number of products in Category A is NOT incremented by 1. 

It is observed that when the sku is assigned directly from within Category interface, the expected result is met.  But when the sku is assigned from Product -> Catalog -> Edit Product, it does not get assigned to the clone category.

**Comment by magento-engcom-team** [comment] 2019-01-11 00:17
Hi @ozzman6154. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ozzman6154 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-11 01:49
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by irajneeshgupta** [comment] 2019-01-11 06:40
@ozzman6154 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only.
You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner por

**Closed as completed by irajneeshgupta** 2019-01-11 06:40 UTC
Labels: Issue: Format is valid
