### ISSUE TITLE
No way to delete an image from the Media Storage

### ISSUE THREAD

**Issue by dfediuk** [magento/magento2#2369] opened 2015-11-14 11:47 UTC
![](https://mage2.pro/uploads/default/original/1X/fb690e25f340f9edcfaa5f9ada8ddde1d2ecfd3a.png)

Similar to https://github.com/magento/magento2/issues/2305

**Comment by shiftedreality** [comment] 2016-01-14 16:00
Thank you for reporting

Internal ticket MAGETWO-47939 was created

**Comment by eddielau** [comment] 2016-01-15 19:36
@dfediuk We tried it and the "Delete File" button should show up after you click on an image. How did you get to this page? And what is the "storage configuration for media" under Stores > Configuration > Advanced > System?

**Comment by eddielau** [comment] 2016-01-28 16:35
Please see screenshot.
![screen shot 2016-01-28 at 10 34 40 am](https://cloud.githubusercontent.com/assets/5254230/12651104/d966615c-c5aa-11e5-8a2a-36b7b655bdcb.png)

**Comment by mazhalai** [comment] 2016-01-28 16:37
@dfediuk  Please have a look at screenshot provided by @eddielau Closing since this is non-reproducible.

**Closed by mazhalai** 2016-01-28 16:37 UTC
Labels: acknowledged, needs update, PS
