### ISSUE TITLE
Removing a product from all websites in admin causes an  SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by oskar-olaussen** [magento/magento2#35133] opened 2022-02-23 14:37 UTC
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Go to product edit page in admin. You must be in scope "All Store views" and the product must not be visible individually
![image](https://user-images.githubusercontent.com/82803128/155339674-21b49a23-7d81-45fe-b43a-e9647cace197.png)

2. Remove all websites under "Product in Websites" and hit save.

### Expected result (*)

1. Product is saved succesfully.

### Actual result (*)

1. SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1, query was: DELETE `url_rewrite` FROM `url_rewrite` WHERE (`entity_id` IN ('1')) AND (`entity_type` IN ('product')) AND (`store_id` IN ('1', ))

![image](https://user-images.githubusercontent.com/82803128/155340182-ae33a1af-3e6a-4493-a0d9-3cc8affb5b28.png)

### Possible cause

In Magento\CatalogUrlRewrite\Observer\ProductProcessUrlRewriteSavingObserver we have
`private function deleteObsoleteRewrites(Product $product): void
    {
        //do not perform redundant delete request for new product
        if ($product->getOrigData('entity_id') === null) {
            return;
        }
        $oldWebsiteIds = $product->getOrigData('website_ids') ?? [];
        $storesToRemove = $this->getStoresList->execute(
            array_diff($oldWebsiteIds, $product->getWebsiteIds())
        );
        if ((int)$product->getVisibility() === Visibility::VISIBILITY_NOT_VISIBLE) {
            $isGlobalScope = $product->getStoreId() == Store::DEFAULT_STORE_ID;
            $storesToRemove[] = $isGlobalScope ? $product->getStoreIds() : $product->getStoreId();
        }
        if ($storesToRemove) {
            $this->urlPersist->deleteByData(
                [
                    UrlRewrite::ENTITY_ID => $product->getId(),
                    UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
                    UrlRewrite::STORE_ID => $storesToRemove,
                ]
            );
        }
    }`

If we are in the global scope and all of the websites are removed an empty array is appended to $storesToRemove[].

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-02-23 14:46
@magento give me 2.4-develop instance

**Comment by engcom-Delta** [comment] 2022-03-07 02:13
Hi @oskar-olaussen ,
Thank you for raising an issue , We tried to reproduce the issue on Magento 2.4 Develop latest branch but issue is not reproducible. Hence request to review the provided steps.

Steps followed:
1. Go to product edit page in admin. You must be in scope "All Store views" and the product must not be visible individually
<img width="1440" alt="Screenshot 2022-03-07 at 7 34 15 AM" src="https://user-images.githubusercontent.com/51681379/156955933-31e2e614-75c7-47ac-99b6-b5111de8d8f9.png">

2. Remove all websites under "Product in Websites" and hit save.
<img width="1440" alt="Screenshot 2022-03-07 at 7 35 07 AM" src="https://user-images.githubusercontent.com/51681379/156955997-897a5b22-4587-45c1-8ae0-ceb08f64f450.png">
3. Save it
<img width="1440" alt="Screenshot 2022-03-07 at 7 36 19 AM" src="https://user-images.githubusercontent.com/51681379/156956026-5d3dd8e3-38ca-4e6c-bb54-adef7c7a6adb.png">

Thanks

**Comment by neddy236** [comment] 2022-03-19 00:25
@magento I am working on this

**Comment by neddy236** [comment] 2022-03-19 00:25
@magento add to contributors team

**Comment by neddy236** [comment] 2022-03-19 00:26
https://github.com/magento I am working on this

**Comment by neddy236** [comment] 2022-03-19 00:26
@magento I am working on this

**Comment by neddy236** [comment] 2022-03-19 00:38
Issue is found on `app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php` line:107

` if ((int)$product->getVisibility() === Visibility::VISIBILITY_NOT_VISIBLE) {
            $isGlobalScope = $product->getStoreId() == Store::DEFAULT_STORE_ID;
            $storesToRemove[] = $isGlobalScope ? $product->getStoreIds() : $product->getStoreId();
        }`

basicly `$storesToRemove` has this value with every website removed with my tests Array ( [0] => 1 [1] => 2 [2] => 3 [3] => 4 [4] => Array ( ) )

Also I don't find anypoint of assigning default store view id which is 0 to the array (which by the way works fine) because url_rewrites do not get generated in store_id 0

Simple proposal is to array_filter the `$storesToRemove` variable on itself to remove any possible empty values from the array as they are not needed

Sql query result AFTER proposed fix.

`'SELECT `url_rewrite`.* FROM `url_rewrite` WHERE (`entity_id` IN ('1')) AND (`entity_type` IN ('product')) AND (`store_id` IN ('1', '2', '3', '4'))'`

Sql query result BEFORE proposed fix.

`'SELECT `url_rewrite`.* FROM `url_rewrite` WHERE (`entity_id` IN ('1')) AND (`entity_type` IN ('product')) AND (`store_id` IN ('1', '2', '3', '4', ))'`

**Comment by engcom-Hotel** [comment] 2022-07-18 10:25
Hello @oskar-olaussen,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2567 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2567&type=commits

Based on the Jira ticket, the target version is 2.4.6

Thanks

**Closed as completed by engcom-Hotel** 2022-07-18 10:25 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Product
