### ISSUE TITLE
Arrows (.fotorama__thumb__arr) don't work in product gallery

### ISSUE THREAD

**Issue by adamvarga** [magento/magento2#25652] opened 2019-11-19 12:37 UTC
### Preconditions (*)
1. 2.3.3 Open Source and Commerce Edition with Sample Data

### Steps to reproduce (*)
1. Navigate to product page
2. Check product with thumbnails in product gallery
3. The little arrows don't work

### Expected result (*)
1. The arrows `.fotorama__thumb__arr ` work or not existed, in previous version the arrows were not there

### Actual result (*)

The little arrows next to the thumbs only make sense if there are more pictures than there is room for, although I only have 3 pictures, the arrows are displayed, which makes no sense.
I marked those with red circle on the screenshot.

Why are this litte arrows displayed? And if they ever appear, why don't work. 
So either show and work, or hide completely. 

![fotorama_arrows_disabled](https://user-images.githubusercontent.com/17138890/69146853-006ff000-0ad1-11ea-94e1-fd46b2f4b9a5.png)

**Comment by sudheers-kensium** [comment] 2019-11-19 13:14
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-19 13:14
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-19 13:15
Hi @sudheers-kensium, here is your [Magento instance](https://i-25652-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25652-2-3-develop.instances.magento-community.engineering/admin](https://i-25652-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2019-11-19 13:40
@adamvarga This is not an issue, because you have only 3 images so arrows not displaying. If you have more images then arrows will display. 

![image](https://user-images.githubusercontent.com/50358141/69151214-37112f00-0b00-11ea-813b-8dabacfa8d71.png)

**Comment by adamvarga** [comment] 2019-11-19 13:47
@sudheers-kensium The little arrows next to the thumbs only make sense if there are more pictures than there is room for,  although I only have 3 pictures, the arrows are displayed, which makes no sense. 
I marked those with red circle on the screenshot.

Why are this litte arrows displayed? And if they ever appear, why don't work. That is the question... 
So either show and work, or hide completely. What do you think?

![fotorama_arrows_disabled](https://user-images.githubusercontent.com/17138890/69151750-85f89d80-0adb-11ea-8e46-6a0d033dadfe.png)

**Comment by adamvarga** [comment] 2019-11-19 14:08
@sudheers-kensium I have removed a few product images from your test page (https://i-25652-2-3-develop.instances.magento-community.engineering/test.html). **I have also only three image**, **the arrows are displayed anyway** ...

![Bildschirmfoto 2019-11-19 um 15 06 11](https://user-images.githubusercontent.com/17138890/69153367-67e06c80-0ade-11ea-9767-79ff5840b512.png)

**Comment by magento-engcom-team** [comment] 2019-11-19 14:29
@sudheers-kensium Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-19 14:30
:white_check_mark: Confirmed by @sudheers-kensium 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-28947` were created

**Issue Available**: @sudheers-kensium, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment] 2019-11-22 16:44
Hi @adamvarga. Thank you for your report. 
The issue has been fixed in magento/magento2#25666 by @alexey-rakitin in 2.3-develop branch
Related commit(s):
 - [f97f68d88009eae7aef52c3404df84635e1a659b](https://github.com/magento/magento2/commit/f97f68d88009eae7aef52c3404df84635e1a659b)

The fix will be available with the upcoming 2.3.5 release.

**Closed as completed by VladimirZaets** 2019-11-22 16:44 UTC
Labels: Issue: Ready for Work, Component: Catalog, Area: Frontend, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: MediaGallery
