### ISSUE TITLE
Catalog Widget. Select with product conditions displays incorrect attributes.

### ISSUE THREAD

**Issue by evgeniykapelko** [magento/magento2#32203] opened 2021-02-17 13:42 UTC
### Preconditions (*)

1. Magento 2.4.1
2. Install last version magento/module-page-builder

### Steps to reproduce (*)

1. Go to Admin > Content > Pages > Home page
2. Content -> click button Edit with Page Builder
3. Add Content -> Products -> click Edit
4. Open Conditions

### Expected result (*)

1. In the select in the Product Attributes section, attributes are loaded that have the configuration value is_used_for_promo_rules=0 in the database.
2. Example Dynamic SKU
![08288a2105](https://user-images.githubusercontent.com/30687423/108212108-29e55480-7136-11eb-9149-66b0f595def0.jpg)

### Actual result (*)

1. Attributes with the value is_used_for_promo_rules = 0 should not be included in the condition.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [1] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by evgeniykapelko** [comment] 2021-02-17 13:43
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-03-07 05:39
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-03-07 06:44
Hi @evgeniykapelko,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce (*)**

- Go to Admin > Content > Pages > Home page
- Content -> click button Edit with Page Builder
- Add Content -> Products -> click Edit
- Open Conditions

is_used_for_promo_rules=0 is used for promo rule conditions like cart price rules not for product conditions in page builder content.

We have checked for cart price rules it is working fine looks like it is an expected behaviour.

Thanks

**Comment by engcom-Bravo** [comment] 2024-03-21 05:35
Hi @evgeniykapelko,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-03-21 05:35 UTC
Labels: Priority: P4, Progress: done, Issue: needs update, Reported on 2.4.1
