### ISSUE TITLE
Garbage tags and no error messages In multishipping

### ISSUE THREAD

**Issue by giedriusmarkevicius** [magento/magento2#34035] opened 2021-09-09 15:04 UTC
If we do the multishipping order with two failed payments, in "Failed to Order" section we will see garbage tags instead of an address and no error messages.
We can get this error in production if we use a credit card with insufficient funds. For example we can authorize two products, but get an error message for the rest of the products. But this will happen with any payment error. In this example I am writing a simple simulation of an error to reproduce by adding an additional code in a payment plugin - simulate errors on specific amount.

### Preconditions (*)
1. magento 2.4.2-p1
2. Payment plugin with support of multishipping

### Steps to reproduce (*)
1. Add code at beginning of  `function authorize` or `function capture`. (depends on what the payment plugin uses)
 `if (50 == $amount) {
	  throw new \Magento\Framework\Exception\LocalizedException(__('This payment failed.'));
 }`
2. add product for $45 in a cart and update quantity to 4. (for default sample data it is a "Push It Messenger Bag").
3. in multishipping checkout shipping screen choose "free shipping" for two products and "Flat Rate" (5$) for the rest of two products.

### Expected result (*)
I should see two orders in "Successfully Ordered" section and the other two orders in "Failed to Order" section, with formatted addresses and error messages ('This payment failed.' in this way).

### Actual result (*)

I see two orders in "Successfully Ordered" block but the other two orders in "Failed to Order" block, with no error messages and magento tags instead of addresses.

[preview image](https://ibb.co/QfZV7Ws)

---
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-10-21 13:23
Hello @giedriusmarkevicius,

We have tried to reproduce the issue in Magento 2.4-develop branch with the Stripe payment method. But we are unable to reproduce the same.

Can you please tell us which payment method you have used when you get this issue?

Thanks

**Comment by engcom-Hotel** [comment] 2021-11-04 07:15
Dear @giedriusmarkevicius,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-11-04 07:15 UTC
Labels: Triage: Dev.Experience, Issue: needs update
