### ISSUE TITLE
Uploading a new product image with the same name results in the same image in cache

### ISSUE THREAD

**Issue by kolaente** [magento/magento2#25531] opened 2019-11-08 15:36 UTC
### Preconditions (*)

1. Magento version: 2.2.9 (I'll try to reproduce this in 2.3 and update here)
1. PHP 7.1.33-1+ubuntu18.04.1+deb.sury.org+1

### Steps to reproduce (*)

I'm using these two test images here: https://gist.github.com/kolaente/1fc602c0837f0fa12de615b249784c0e

1. Remove all product images
2. Upload a new one: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_blue.json`
3. Upload a second one: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_blue.json`
4. Verify bothe were uploaded correctly and one has an increment: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: Bearer $BEARER" | jq`
This should look something like this:
```json
    [
      {
        "id": 20454530,
        "media_type": "image",
        "label": null,
        "position": 1,
        "disabled": false,
        "types": [],
        "file": "/p/r/product_image_new.jpg"
      },
      {
        "id": 20454531,
        "media_type": "image",
        "label": null,
        "position": 2,
        "disabled": false,
        "types": [],
        "file": "/p/r/product_image_new_1.jpg"
      }
    ]
```     
5. Delete the last product image, the one with the incement: `curl -X DELETE $MAGENTO_URL/rest/V1/products/F1237/media/20454531 -H "Authorization: Bearer $BEARER" | jq`
6. Verify it is gone: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: Bearer $BEARER" | jq`
```json
    [
      {
        "id": 20454530,
        "media_type": "image",
        "label": null,
        "position": 1,
        "disabled": false,
        "types": [],
        "file": "/p/r/product_image_new.jpg"
      }
    ]
```
7. Upload a new product image, the red one this time: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_red.json`
8. Verify it's there: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: Bearer $BEARER" | jq`
```json
    [
      {
        "id": 20454530,
        "media_type": "image",
        "label": null,
        "position": 1,
        "disabled": false,
        "types": [],
        "file": "/p/r/product_image_new.jpg"
      },
      {
        "id": 20454532,
        "media_type": "image",
        "label": null,
        "position": 2,
        "disabled": false,
        "types": [],
        "file": "/p/r/product_image_new_1.jpg"
      }
    ]
```

The images in the admin backend are fine: 

### Expected result (*)

1. Two different product images should show up on the product page, a red one and a blue one.

### Actual result (*)

1. Two images show up, both being the same blue one.
![grafik](https://user-images.githubusercontent.com/13721712/68579225-ebadaf80-0473-11ea-99a0-9b35581a9c21.png)

In the admin area, I see both images the way it should be: 
![grafik](https://user-images.githubusercontent.com/13721712/68579277-0122d980-0474-11ea-9092-90bcd94696a5.png)

### The problem

It looks like the second image being uploaded gets the same increment id as the one before, but the cache does not get invalidated. I think this should happen in `\Magento\Catalog\Model\Product\Gallery\GalleryManagement::update`. But it's all a bit wired since the image increment Id is not always based on the ones before. Maybe this is only an api issue. 

In `magento/module-catalog/Helper/Image.php:514` it is checked if a cached image exists and if that's the case, no new cache image is created. This makes sense since we don't want to re-create all cached images every time we save a product. However, these cache images don't get invalidated when a new image is saved. The problem with this is the function in `magento/module-catalog/Model/Product/Image/Cache.php:98` which handles the image resizing / saving / etc. does not know if an image was changed. It seems to just take an array with images and saves them, with the mentioned problem.

### Possible solutions

1. Save the original hash of the image when first creating it. Then, when saving the image check if the hash changed and invalidate the cache.
2. Save the image latest increment globally, and then use that instead of building it from the image.
3. (dirty workaround, do not use) Patch `\Magento\Catalog\Model\Product\Image::isCached` to always return true. This would result in recreating all image every time the product is saved. In that case, we could also just remove the check itself.

**Comment by kolaente** [comment] 2019-11-08 15:36
@magento give me 2.2.9-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-08 15:36
Hi @kolaente. Thank you for your request.
Unfortunately, I can only deploy instances for `2.3` release line

**Comment by kolaente** [comment] 2019-11-08 15:37
@magento give me 2.3 instance

**Comment by kolaente** [comment] 2019-11-08 15:38
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-08 15:38
Hi @kolaente. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-08 15:38
Hi @kolaente, here is your [Magento instance](https://i-25531-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25531-2-3-develop.instances.magento-community.engineering/admin](https://i-25531-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by kolaente** [comment] 2019-11-11 09:03
It looks like this is a bit more difficult to reproduce than I thought. I'll do some more checks and update the issue here.

**Comment by kolaente** [comment] 2019-11-11 11:12
I've updated the issue description with better steps to reproduce and possible solutions.

**Comment by engcom-Charlie** [comment] 2019-11-11 15:20
Hello @kolaente 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch.

**Manual testing scenario:**
1. Remove all product images
2. Upload a new one: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_blue.json`
3. Upload a second one: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_blue.json`
4. Verify bothe were uploaded correctly and one has an increment: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: Bearer $BEARER" | jq`
![image](https://user-images.githubusercontent.com/51680850/68598033-a5be0f00-04a6-11ea-9df8-6442083b37d3.png)

5. Delete the last product image, the one with the incement: `curl -X DELETE $MAGENTO_URL/rest/V1/products/F1237/media/20454531 -H "Authorization: Bearer $BEARER" | jq`
![image](https://user-images.githubusercontent.com/51680850/68598051-b2dafe00-04a6-11ea-81de-2bb0838cd77d.png)

6. Verify it is gone: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: 
![image](https://user-images.githubusercontent.com/51680850/68598063-be2e2980-04a6-11ea-808e-e8af9e0dd515.png)

7. Upload a new product image, the red one this time: `curl -X POST $MAGENTO_URL/rest/V1/products/F1237/media -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @image_red.json`
![image](https://user-images.githubusercontent.com/51680850/68598122-dd2cbb80-04a6-11ea-9e92-a4721ea402a1.png)

8. Verify it's there: `curl -X GET $MAGENTO_URL/rest/V1/products/F1237/media -H "Authorization: Bearer $BEARER" | jq`
![image](https://user-images.githubusercontent.com/51680850/68598181-fb92b700-04a6-11ea-92f4-6b7585050885.png)

**Result:**
Two different product images are displayed on the product page, a red one and a blue one.
![image](https://user-images.githubusercontent.com/51680850/68598365-53c9b900-04a7-11ea-90dd-694a595cda5f.png)


We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-11 15:20 UTC
Labels: Issue: Format is valid

**Comment by kolaente** [comment] 2019-11-11 16:59
@engcom-Charlie Hmm okay, thanks for checking. Do you think this was fixed in 2.3?

**Comment by engcom-Charlie** [comment] 2019-11-12 09:31
@kolaente probably fixed, but i can't find a commit

**Comment by thomas-upecom** [comment] 2023-06-21 15:40
@koalente
Is it ok with your new magento version ?
i have got the same issue and i m on the 2.4.3-p2 
I  have to create thousand of products by api , with images , and sometimes , images are mixed between products. But not all of them . I don't understand why . 
Any suggestion what is the issue?

**Comment by unity-state** [comment] 2024-09-26 19:46
the ssame issue in magento 2.4.5

**Comment by cptX** [comment] 2025-11-09 08:03
Same issue in 2.4.8-p2
