### ISSUE TITLE
Magento 2.1.3 - Refund report shows wrong date

### ISSUE THREAD

**Issue by popduyhan** [magento/magento2#9106] opened 2017-04-03 06:06 UTC
Currently i am using Magento version 2.13

I use Refund Report to know which orders have been returned in this month. Here is my situation:

### Preconditions
Magento 2.1.3
PHP 5.6

### Steps to reproduce
An order was created in 10th March. A credit memo was created in 15th March and refund had been made. Accountant generates a report in 25th March.

### Expected result 
The refund in report should show the date is 15th March.

### Actual result

The refund in report shows the date is 10th March.

**Comment by smoskaluk** [comment] 2017-06-30 13:32
@popduyhan When you generated that refund report, did you choose in Date Used "Order Created" or "Last Credit Memo Created Date"?

**Comment by popduyhan** [comment] 2017-07-02 04:02
Hi @smoskaluk, when i generated that refund report, i choose the option "Last Credit Memo Created Date"
but it showed the created date of orders, it didn't show the created date of Credit Memo. 
It's the issue that i want to report.

**Comment by smoskaluk** [comment] 2017-07-03 13:00
Internal ticket MAGETWO-70421 created

**Comment by magento-engcom-team** [comment] 2017-10-11 19:03
@popduyhan, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 19:03 UTC
Labels: Issue: Ready for Work, bug report, Component: Sales, Issue: Clear Description, Issue: Format is valid

**Comment by alexpoletaev** [comment] 2017-11-24 15:29
@magento-engcom-team could you please provide a link to commit with the fix. We have this issue too on 2.1.9 , but we are not ready to update our instance to 2.2.0 at the moment. Thanks.

**Comment by alexpoletaev** [comment] 2017-11-24 18:13
Here is another issue https://github.com/magento/magento2/issues/5317 and the [fix](https://github.com/magento/magento2/commit/adae1ed9c261598360afda66b3e86823259d47f5) for it.
