### ISSUE TITLE
Same product quantity not increment when added with guest user.

### ISSUE THREAD

**Issue by krishprakash** [magento/magento2#21375] opened 2019-02-21 05:20 UTC
Preconditions (*)
1. Magento 2.2.x
2. Magento 2.3.x

Steps to reproduce (*)
1. Login >>Add product X to the cart from **Listing** page
2. Logout
3. Add product X to the cart from  **product detail page** as guest user
4.  Login using same account.
5. Review the cart

Expected result (*)

Product Qty should be incremented not added separately after login if same product is already added into cart. 

Actual result (*)

![test](https://user-images.githubusercontent.com/46617848/53145329-cc10e700-35c5-11e9-9503-e1efae601f56.png)

**Comment by magento-engcom-team** [comment] 2019-02-21 05:20
Hi @krishprakash. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@krishprakash do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Jitheesh** [comment] 2019-02-21 06:41
Hi @krishprakash 

I can replicate this issue on Magento 2.3 develop instance on following scenario. 

1. Login, Add product X to basket from **Listing** page
2. Logout
3. Add product X to basket from  **product view** page as guest user
4. Login using same account.
5. Review basket, Basket will contains same product as two item


This issue is because of additional buy request parameters while we adding product from product view page. 

After customer login Magento will load customer quote and merge this into current quote, while merging quotes, it will compare quote items.

https://github.com/magento/magento2/blob/310648c7f2d1280502f0b92e3dcc28894f7faf86/app/code/Magento/Quote/Model/Quote/Item/Compare.php#L69-L87

quoteOptionFromViewPage

`array (
  'info_buyRequest' => 
  array (
    'product' => '1',
    'item' => '1',
  ),
)`


quoteOptionFromListingPage
`array (
  'info_buyRequest' => 
  array (
    'product' => '1',
  ),
)`

Item comparison failed because of 'item' parameter in the buy request.  


https://github.com/magento/magento2/blob/310648c7f2d1280502f0b92e3dcc28894f7faf86/app/code/Magento/Catalog/view/frontend/templates/product/view/form.phtml#L25


same issue will happen if you add related products along with main product.

**Comment by dipti2jcommerce** [comment] 2019-02-21 07:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-21 07:20
Hi @dipti2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-21 07:21
Hi @dipti2jcommerce, here is your [Magento instance](https://i-21375-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21375-2-3-develop.instances.magento-community.engineering/admin](https://i-21375-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-21 07:33
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-21 07:33
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-21 07:34
Hi @shikhamis11, here is your [Magento instance](https://i-21375-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21375-2-2-develop.instances.magento-community.engineering/admin](https://i-21375-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-21 07:44
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-21 07:44
@Jitheesh yes you are right I am able to reproduce the issue with your provided step
@krishprakash  it will be better if you update Steps to reproduce (*) as it is not reproducable in all scenarios

**Comment by magento-engcom-team** [comment] 2019-02-21 07:45
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98355`, `MAGETWO-98356` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-25 17:16
Hi @shikhamis11. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-02-28 10:28
Hi @Jitheesh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-04-16 14:10
Hi @krishprakash. Thank you for your report. 
The issue has been fixed in magento/magento2#21501 by @Jitheesh in 2.3-develop branch
Related commit(s):
 - [30dbc79466e6fc383caae2cfa743eb81147e3540](https://github.com/magento/magento2/commit/30dbc79466e6fc383caae2cfa743eb81147e3540)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-16 14:10 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: Sales, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-04-25 19:13
Hi @krishprakash. Thank you for your report. 
The issue has been fixed in magento/magento2#22378 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [57af527696d73c9488afbb15f9642785ef110819](https://github.com/magento/magento2/commit/57af527696d73c9488afbb15f9642785ef110819)

The fix will be available with the upcoming 2.2.9 release.

**Comment by cgsoratto** [comment] 2019-10-17 10:58
I found! The problem is in the 'StripeIntegration_Payments' module. There is an observer for 'checkout_cart_product_add_after' that always changes the "code" to "additional_options".

app/code/StripeIntegration/Payments/Observer/AddInitialFeeObserver.php
