### ISSUE TITLE
Add to cart message stuck on every page

### ISSUE THREAD

**Issue by bondimedical3** [magento/magento2#6686] opened 2016-09-21 06:34 UTC
I have just done a new installation of 2.1.1 and am finding the green Add to Cart message is appearing on every page.

![magento2](https://cloud.githubusercontent.com/assets/10808588/18700175/2fe96c80-8019-11e6-8ccc-46c5efc62153.jpg)

**Comment by veloraven** [comment] 2016-09-23 13:33
@bondimedical3 thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by bondimedical3** [comment] 2016-09-23 22:16
Please read my issues carefully as I have already included steps to reproduce the result and the expected result. This is a bug which hundreds of people are experiencing and something you should be aware of unless you are out of touch with users of your software.

I will repeat it again.

Steps to reproduce:
1. Do an installation of latest version of Magento 
2. Place an order.

Actual Result:
1. Add to cart message is on every page.

Expected Result:
1. Add to cart message is not supposed to be appearing on every page.

**Comment by pboisvert** [comment] 2016-09-23 23:15
this appears to be a duplicate of #5530 and internal ticket for this is MAGETWO-54866

here is the pull request where this is fixed https://github.com/magento/magento2ce/pull/416

this is not released to 2.1.x yet but resolved in mainline; will flag for porting to 2.1.x branch to get into patch.

**Comment by bondimedical3** [comment] 2016-09-24 01:11
The pull request seems to lead to a 404 page?

**Comment by pboisvert** [comment] 2016-09-24 04:12
@bondimedical3 my bad--that link is to a private repo--I didn't notice and thought i could share that link. Think this fix will drop as part of next patch that we hope will go next week.

As an alternative and with a massive disclaimer that this still needs testing still, you can find the code changes at the following link courtesy of the always helpful Piotr Kaminski https://gist.github.com/piotrekkaminski/8ae3b9b353825e29948d332e31e765db

**Comment by veloraven** [comment] 2016-09-27 12:57
Internal ticket for develop branch - MAGETWO-54866, fix is in commit 9515999 
Internal ticker for branch 2.1 - MAGETWO-56956, fix is in commit 39b35ec
Internal ticket for branch 2.0 -  MAGETWO-56955, fix is in commit 592ded2

**Closed as completed by veloraven** 2016-09-27 12:57 UTC
Labels: Issue: Ready for Work, bug report

**Comment by Ctucker9233** [comment] 2016-10-11 16:25
@veloraven can you repost the link for the 2.1 fix commit? Looks like only the develop commit got linked.

**Comment by bondimedical3** [comment] 2016-10-13 06:50
I have updated to 2.1.2 and the issue is still there. I have done some further testing and it only appears to be present in the main browser I use, Chrome. I cannot reproduce the issue in FireFox, Internet Explorer or Opera. Please try to reproduce the issue by adding a product to the cart using the latest version of Chrome browser and navigating to another page.
![magento](https://cloud.githubusercontent.com/assets/10808588/19339167/6dadcd58-916d-11e6-8bca-26299ebea0ee.jpg)

**Comment by hhsiao** [comment] 2017-02-03 12:36
What I found out is this:
1.  "module-theme/view/frontend/web/js/view/message.js" is responsible for grabbing "mage-messages" out of the cookies, and then set "mage-messages" to nothing
2.  When you click on "Add Cart" (or anything that adds anything to the message), message gets added into "mage-messages" as cookie value

Problem is altho #1 does set "mage-messages" to nothing, but somehow "mage-messages" was restored by the time the page finish loading....

I fixed this in a completely ghetto way... 
Basically my messages.js looks like below:

`
define([
    'jquery',
    'uiComponent',
    'underscore',
    'Magento_Customer/js/customer-data',
    'jquery/jquery-storageapi',
], function ($, Component, _, customerData) {
    'use strict';

    return Component.extend({
        defaults: {
            cookieMessages: [],
            messages: []
        },

        /** @inheritdoc */
        initialize: function () {
            this._super();

            this.cookieMessages = $.cookieStorage.get('mage-messages');
            this.messages = customerData.get('messages').extend({
                disposableCustomerData: 'messages'
            });

            if (!_.isEmpty(this.messages().messages)) {
                customerData.set('messages', {});
            }
            $.cookieStorage.set('mage-messages-length', this.cookieMessages.length);
            $.cookieStorage.set('mage-messages', '[]');
            $( window ).unload(function($) {
                var ca = document.cookie.split('; ');
                var mageMessages = 'mage-messages=';
                var mageMessagesLength = 'mage-messages-length=';
                var mageMessagesObj = [];
                var mageMessagesLengthObj = 0;
                for(var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    if (c.indexOf(mageMessages) == 0) {
                        mageMessagesObj = JSON.parse(decodeURIComponent(c.substring(mageMessages.length, c.length)));
                    } else if (c.indexOf(mageMessagesLength) == 0) {
                        mageMessagesLengthObj = JSON.parse(c.substring(mageMessagesLength.length, c.length));
                    }
                }
                document.cookie = 'mage-messages=' + encodeURIComponent(JSON.stringify(mageMessagesObj.slice(mageMessagesLengthObj))).replace(/%2B/g, '+');
            });
        }
    });
});
`

I basically kept track of how many message was displayed, and then slice them off the front when the page unload.  I welcome any better fixes... cause the way I fixed it... like I say... is pretty lame.

**Comment by hhsiao** [comment] 2017-02-03 14:08
Scratch my previous comment... it doesn't quite work.  If the user submit before minicart is completely loaded, it'll break (as in it doesn't show any message at all).

Anyone know where the code is that append the new item into "mage-messages" cookie?
