### ISSUE TITLE
Tier price on configurable product sorting sometimes wrong

### ISSUE THREAD

**Issue by matin73** [magento/magento2#12194] opened 2017-11-11 18:43 UTC
In some cases sorting of configurable products in combination with swatches is not correct done.

### Preconditions
PHP 7.0.25
MySQL 5-7

### Steps to reproduce
Saving tier prices for configurable product for each article - same prices. Sorting in admin is correct, but some of the articles have in frontend wrong sorting

### Expected result
Sorting should be for all articles the same - starting with smallest number - like;
    Buy 12 for 5,88 € each and save 8%
    Buy 96 for 4,80 € each and save 25%
    Buy 300 for 3,96 € each and save 38%

### Actual result
Some of the configurable articles have correct sorting, and some not. see screenshots
![admin](https://user-images.githubusercontent.com/3177275/32692449-8f331866-c718-11e7-8491-f1cfcdba41c1.png)
![fronend](https://user-images.githubusercontent.com/3177275/32692450-8f5688be-c718-11e7-9a71-55e6b1f32064.png)

**Comment by magento-engcom-team** [comment] 2017-11-13 10:30
@matin73, thank you for your report.
We've created internal ticket(s) MAGETWO-83733 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2019-01-18 11:38
Hi @vshatylo. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-26 20:50
Hi @matin73. Thank you for your report. 
The issue has been fixed in magento/magento2#20407 by @vshatylo in 2.3-develop branch
Related commit(s):
 - [f4d09473f93e80b0c6c99bac45f925b9a7e122d2](https://github.com/magento/magento2/commit/f4d09473f93e80b0c6c99bac45f925b9a7e122d2)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-01-26 20:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
