### ISSUE TITLE
Shipping Issue Unavailable Country is available front-end

### ISSUE THREAD

**Issue by Lewiscowles1986** [magento/magento2#3364] opened 2016-02-10 23:23 UTC
So I've been playing around on Magento 2 community and it looks like only allowing certain shipping destinations is not stopping others from being selected, and not warning the customer...

I Have child-themed, however it looks like even in the bundled themes this issue persists

![configuration settings stores magento admin](https://cloud.githubusercontent.com/assets/2605791/12965263/a8a01cd2-d04c-11e5-85de-41e296bf4049.png)

![shopping cart](https://cloud.githubusercontent.com/assets/2605791/12965266/b0eea534-d04c-11e5-8a71-a712d0ce9f53.png)

It lets me checkout, but the checkout looks like this (could be separate issue)
![checkout](https://cloud.githubusercontent.com/assets/2605791/12965317/25d37262-d04d-11e5-9292-de4567d46999.png)

I do have five store views, but I've only used the global config to setup shipping via the table shipping rates, which I have imported successfully.

While it's great being able to have multi-currency, multi-language, and a shipping table rate for setting per country / country + region, if it doesn't work in a way that is clear to the end user, then it could be a problem.

**Comment by chris-brabender** [comment] 2016-03-14 19:08
Can second this issue and add that "Allowed Countries" seems to not work also under Configuration -> General > Country Options

![screen shot 2016-03-14 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/5144830/13756452/4e89bd0c-e9f6-11e5-90b7-df60d25c6e2d.png)

![screen shot 2016-03-14 at 3 08 33 pm](https://cloud.githubusercontent.com/assets/5144830/13756528/a8187552-e9f6-11e5-84aa-4e9e13706ce3.png)

![screen shot 2016-03-14 at 3 08 39 pm](https://cloud.githubusercontent.com/assets/5144830/13756532/a9d1718c-e9f6-11e5-8131-cd8db98ed010.png)

**Comment by lucscu** [comment] 2016-05-30 10:02
Why no one reply to this huge bug?

**Comment by NadiyaS** [comment] 2016-05-31 07:33
Hi @Lewiscowles1986 , @chris-brabender ,
thank you for reporting this issue and we are sorry for delay. This bug really exists on 2.0.7 version. But it is fixed on current develop branch. You can upgrade your code from develop branch or wait until next release.
Feel free to reopen this issue if you will have the same problem on next Magento version.

**Closed as completed by NadiyaS** 2016-05-31 07:33 UTC

**Comment by lucscu** [comment] 2016-05-31 08:48
Thx @NadiyaS 
I'm personally waiting for next release and hope to finally go live with my project.

**Comment by andidhouse** [comment] 2016-06-20 10:29
We have the same bug in 2.0.7. At the checkout ALL countries are shown - not just the selected in then backend. Is there a way to fix this on 2.0.7 as this is a major bug not allowing anyone to go live with wrong shipping countries?

Will this be fixed in 2.1 or sooner? Is there any information when 2.1 is coming?

Thanks!

**Comment by perry3181** [comment] 2016-07-29 09:07
Hi @NadiyaS

My project running 2.0.7 also have this issue, could you let me know which files / folders need to be replaced?
I can find the fixed files / folders in current develop branch?
Thanks!

**Comment by lucscu** [comment] 2016-07-29 13:37
@perry3181 have you upgrade to 2.0.8?

**Comment by NadiyaS** [comment] 2016-07-29 13:44
Hi @perry3181 , 
if you do not want to do upgrade to 2.1 version you can upgrade your code to 2.0.8. It is the best way to fix this problem, and not to change files separately.

**Comment by perry3181** [comment] 2016-07-29 14:20
Hi @LucScu and @NadiyaS,

I not yet upgrade to 2.0.8. Actually, I want to upgrade to 2.1 few weeks ago, but not success. Due to the below error. Then I spent much time to restore the system to 2.0.7. So that I give up to upgrade to 2.1 until I find the solution.

Do you guys know if upgrade from 2.0.7 to 2.0.8 will have the same issue "Webapi does not exist"?
I remember that I upgraded 2 times, from 2.0.1 to 2.0.3, 2.0.3 to 2.0.7, the upgrade process is smooth and without error message in console log. 

[2016-07-04 14:15:02 UTC] An error occurred while executing job "setup:upgrade {"command":"setup:upgrade"}": Could not complete setup:upgrade {"command":"setup:upgrade"} successfully: Class Magento\Framework\App\Cache\Type\Webapi does not exist

**Comment by perry3181** [comment] 2016-07-29 14:24
Hi @LucScu and @NadiyaS,

I just go to the system upgrade page, it still stick with the console log and can't be exit :(

![screen shot 2016-07-29 at 10 21 45 pm](https://cloud.githubusercontent.com/assets/20721447/17251335/e7bbc772-55da-11e6-9ea4-4b9dc1c7379f.png)

**Comment by lucscu** [comment] 2016-07-29 15:55
there is an error like everywhere, you have to find how to fix it by yourself.

**Comment by pboisvert** [comment] 2016-07-29 16:56
@perry3181 This issue has been closed as the original issue reported has been resolved. If you wish to report an upgrade issue please file a new issue and provide all steps to reproduce the error you are seeing.
