### ISSUE TITLE
Quick search by SKU in XX-XX not working correctly

### ISSUE THREAD

**Issue by mpurish** [magento/magento2#23447] opened 2019-06-27 15:06 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Create a product with SKU in XX-XX format, for example 00-01, and reindex.
2. Search for 00-01 in Quick search.

### Expected result (*)

1. Search would return product with SKU from search field.

### Actual result (*)

1. Quick search returns no results: 
<img width="1551" alt="Screenshot 2019-06-27 at 15 53 18" src="https://user-images.githubusercontent.com/10667011/60277342-45fb0900-98f5-11e9-8e10-d8ac4194e578.png">

2. Advanced search by SKU returns correct result: 
<img width="1440" alt="Screenshot 2019-06-27 at 15 53 35" src="https://user-images.githubusercontent.com/10667011/60277401-5dd28d00-98f5-11e9-9f81-4cf594696f9a.png">

**Comment by krishprakash** [comment] 2019-06-27 15:30
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-27 15:30
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-27 15:31
Hi @krishprakash, here is your [Magento instance](https://i-23447-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23447-2-3-develop.instances.magento-community.engineering/admin](https://i-23447-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-06-27 15:41
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-27 15:41
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-27 15:41
Hi @krishprakash, here is your [Magento instance](https://i-23447-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23447-2-2-develop.instances.magento-community.engineering/admin](https://i-23447-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-06-27 15:53
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17856`, `MC-17857` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ravi-chandra3197** [comment] 2019-06-28 10:58
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-28 10:58
Hi @ravi-chandra3197. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-28 10:59
Hi @ravi-chandra3197, here is your [Magento instance](https://i-23447-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23447-2-3-develop.instances.magento-community.engineering/admin](https://i-23447-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by RonakParmar** [comment] 2019-06-29 05:33
@magento-engcom-team I am working on this issue.

**Comment by mpurish** [comment] 2019-07-09 16:36
Hi @ravi-chandra3197, do you know if there's already a fix for this issue?

Thanks

**Comment by anujwebkul** [comment] 2019-09-07 06:32
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-07 06:32
Hi @anujwebkul. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-09-07 06:33
Hi @anujwebkul, here is your [Magento instance](https://i-23447-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23447-2-3-develop.instances.magento-community.engineering/admin](https://i-23447-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-10-16 19:13
Closed as cannot reproduce on the latest `2.4-develop` code.
But if you still faced the issue please create a new report for 2.4 with detailed steps

![2020-10-16_14-12-43](https://user-images.githubusercontent.com/3409584/96299505-c695bb00-0fb9-11eb-9f5d-d0290e4d7834.jpg)

**Closed as completed by sdzhepa** 2020-10-16 19:13 UTC
Labels: Issue: Ready for Work, Area: Frontend, Component: Search, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Progress: done
