### ISSUE TITLE
"Magento ver. 2.0.2" is not changed in adminhtml after upgrade to 2.0.3

### ISSUE THREAD

**Issue by flancer64** [magento/magento2#3939] opened 2016-03-31 08:02 UTC
I see that 2.0.3 version is used in composer.json:

```
  "require": {
    "magento/product-community-edition": "2.0.3",
    ...
  }
```

but "Magento ver. 2.0.2" still appeared in the bottom of the adminhtml pages.

**Comment by kkrieger85** [comment] 2016-03-31 09:03
Maybe it's due to

```
<?php
/**
 * Application interface
 *
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magento\Framework;

interface AppInterface
{
    /**
     * Default application locale
     */
    const DISTRO_LOCALE_CODE = 'en_US';

    /**
     * Magento version
     */
    const VERSION = '2.0.2';

    /**
     * Launch application
     *
     * @return \Magento\Framework\App\ResponseInterface
     */
    public function launch();

    /**
     * Ability to handle exceptions that may have occurred during bootstrap and launch
     *
     * Return values:
     * - true: exception has been handled, no additional action is needed
     * - false: exception has not been handled - pass the control to Bootstrap
     *
     * @param App\Bootstrap $bootstrap
     * @param \Exception $exception
     * @return bool
     */
    public function catchException(App\Bootstrap $bootstrap, \Exception $exception);
}
```

**Comment by designhunger** [comment] 2016-03-31 10:42
@kkrieger85 Yes, that's the reason. It seems as if this file is not updated within the upgrade to 2.0.3.

**Comment by kkrieger85** [comment] 2016-03-31 10:46
@designhunger Here on github, it seems, that this file is uploaded correctly: https://github.com/magento/magento2/blob/2.0.3/lib/internal/Magento/Framework/AppInterface.php

**Comment by kkrieger85** [comment] 2016-03-31 10:47
@flancer64 Did you use `composer update` after changing composer.json?

**Comment by nobuttsalex** [comment] 2016-03-31 10:54
Mine still says 2.0.2 bottom right even though I'm on version 2.0.3

**Comment by kkrieger85** [comment] 2016-03-31 11:07
@nobuttsalex How did you update your Magento?

**Comment by PingusPepan** [comment] 2016-03-31 11:27
I updated through Magento Setup Tool (Setup Wizard) and have the same problem.
Setup Wizard says that I have the 2.0.3 CE version and in update_status.log is:

```
- Removing magento/framework (100.0.4)
- Installing magento/framework (100.0.5)
```

and
`Composer update completed successfully`
so I think there was no problem while updating.

Instead it looks like the composer files were updated, but it still downloaded version 2.0.2 files. I checked magento\module-catalog module and the files are from version 2.0.2 even though in composer.json it says it is the 2.0.3 version (100.0.4)

**Comment by designhunger** [comment] 2016-03-31 11:31
So maybe the repo on repo.magento.com is corrupted with old files. Is there any chance to check this?

**Comment by flancer64** [comment] 2016-03-31 11:41
@kkrieger85 I have installed new instance

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition
```

**Comment by nobuttsalex** [comment] 2016-03-31 12:36
@kkrieger85 I changed composer.json from 2.0.2 to 2.0.3 and ran a composer update

**Comment by kkrieger85** [comment] 2016-03-31 13:16
Well, I also updated via composer. In Backend it seems, I use 2.0.2 but there is the wrong version number in source code.

As @designhunger mentioned before, maybe their repo.magento.com is not up to date.

**Comment by afavata** [comment] 2016-03-31 13:47
I've just installed a fresh Magento 2.0.3 downloaded from [https://www.magentocommerce.com/download?_ga=1.89211352.2107838742.1459335729](url) and the admin's panel shows 2.0.2.

**Comment by diegocam** [comment] 2016-03-31 13:56
I agree. I just downloaded the latest 2.0.3 version, but I still see "version 2.0.2" in the admin:

![image](https://cloud.githubusercontent.com/assets/4230798/14177939/8cb85b32-f726-11e5-8a81-dd3563cb8648.png)

I even tried doing it different ways (through composer, and manually through a zip) but still nothing. My local environment is windows running WAMP with PHP 5.5 

 You would think its an easy issue to fix, but who am I to know.

Thanks guys. Awesome product by the way.

**Comment by PingusPepan** [comment] 2016-03-31 13:58
@diegocam the problem is that if you see version 2.0.2 you actually are still on the 2.0.2 version.

**Comment by mazhalai** [comment] 2016-03-31 14:04
@all thank you! We have created MAGETWO-51410 to fix this

**Comment by diegocam** [comment] 2016-03-31 14:23
Hi @mazhalai What exactly does `MAGETWO-51410` mean? is that a bug code? How can we track it? Sorry, im new to this.

**Comment by diegocam** [comment] 2016-03-31 14:24
@PingusPepan That may be the issue. Initially I thought it could just be that footer not being updated, but it may be deeper than that as you mentioned. Thanks for the followup.

**Comment by mazhalai** [comment] 2016-03-31 14:24
@diegocam It is our internal tracking ticket, sorry it it not available publicly.

**Comment by elenleonova** [comment] 2016-04-01 01:13
Hi, there was a packaging issue with 2.0.3. In order to fix that, we have issued the 2.0.4 release. Please, go straight to the new version. 
I'm closing the issue, feel free to reopen it if you continue to see such issues.

**Closed as completed** 2016-04-01 01:13 UTC
Labels: Issue: Ready for Work

**Comment by flancer64** [comment] 2016-04-01 03:46
Yes, it works. "Magento ver. 2.0.4" is appeared on the bottom of the adminhtml pages. Thanks.

**Comment by designhunger** [comment] 2016-04-01 06:01
Thanks for the fast reaction! Works like charme ;)
