### ISSUE TITLE
Sort by Product Name on Search

### ISSUE THREAD

**Issue by rishabhrkrai** [magento/magento2#7404] opened 2016-11-11 11:53 UTC
When search for any product then all the Sort By is working good except "Product Name"

### Preconditions

1. I use Magento 2.1.1
2. PHP version is 5.6.x

### Steps to reproduce

1. Search any thing
2. Then sort the product collection by product name. 

### Expected result

1. Product is showing on a sorting manner with product name.

### Actual result

1. Page is loading but product is not sort by name and url is not changed.

If I give direct url with sort then it sort the product collection like http://xyz.com/catalogsearch/result/index/?q=39246&product_list_order=name

**Comment by Zarina2222** [comment] 2016-11-14 06:47
@RishabhRkRai I had same problem. I think your catalog's default `Sort by` is set to `Product name` (Admin -> Stores -> Configuration -> Catalog -> Catalog -> Storefront -> Product Listing Sort by). If I set it to `Product name`, I can't sort search results by `Product name` (url not changing as you said) and if I set it to `Price` I can't sort search results by `Price`. I solved that interesting bug by setting catalog's default `Sort by` to `Position` (because search results are automatically sorted by Position, it's works). I hope you understand what I tried to explain.

**Comment by rishabhrkrai** [comment] 2016-11-16 07:52
@Juigeli thanks for this. But what to do with **catalog search**. I set default sort by **Product name**. But in code magento by default set it to **Relevance** and when i sort by the product name, page refresh but nothing has changed.

**Comment by Zarina2222** [comment] 2016-11-18 06:03
@RishabhRkRai I don't know why Catalog Product Listing Sort by-setting effects to Catalog search, as I said, it's interesting bug. But you can try set it to Position and check if that fix your search. Remember flush the cache.

**Comment by olysenko** [comment] 2016-11-24 09:32
Hi, thank you for your report. Your issue is a duplicate of #5730 (see comments additionally to original description). Closed as duplicate

**Closed as completed by olysenko** 2016-11-24 09:32 UTC
Labels: bug report, Component: Catalog, Component: Search
