### ISSUE TITLE
Product Price is mismatch in invoice and invoice PDF magento for Bundle Product  2.2.1

### ISSUE THREAD

**Issue by digvijay2017** [magento/magento2#12856] opened 2017-12-22 10:08 UTC
I am getting different price in invoice and invoice PDf for the bundle product. Actually, The price in the invoice pdf are wrong. I am getting right price in order, order email, invoice, invoice email or everywhere in the application, but invoice PDf price is wrong only Bundle product. 

### Preconditions
1. Install Magento 2.2.1
1. Create Bundle product in application.
1. In Magento Admin go to Stores - Tax Rules and Add New Tax Rule
![34373744-2e6633ec-eb03-11e7-9fbe-2aa2ffa9a13c](https://user-images.githubusercontent.com/51680745/71518848-7e3bce00-28bd-11ea-9f85-808ff5473661.png)
1. Go to Stores - Configuration - Sales - Tax and enable the following settings 
![34373758-3a995126-eb03-11e7-857f-3b38d4fbf36c](https://user-images.githubusercontent.com/51680745/71518892-c4912d00-28bd-11ea-9db8-02b3ce5c7881.png)

### Steps to reproduce
1. Create the order with bundle product.
1. Create the invoice, then download the invoice PDF.

### Expected result

1. Price in the invoice PDF should be same as invoice page or order page.
Invoice Screen shot:

![screenshot from 2017-12-22 14-38-25](https://user-images.githubusercontent.com/30342958/34294353-26eaab4e-e72e-11e7-9ddb-60b561d1dcac.png)

### Actual result
1. Prices in the invoice PDF and invoice page are different. Getting wrong price in invoice PDF for bundle product. 
Invoice PDF Screen shot:
![invoice-pdf](https://user-images.githubusercontent.com/30342958/34294363-2d6657f2-e72e-11e7-8440-22fed75ec1e4.png)

**Comment by magento-engcom-team** [comment] 2017-12-26 15:05
@digvijay2017 thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by digvijay2017** [comment] 2017-12-27 07:14
Hi, 

This issue occurring only with the bundle product. And product is taxable good, So Create a Tax Rule and Zone like This:  
![tax zones](https://user-images.githubusercontent.com/30342958/34373738-2425490e-eb03-11e7-8cb9-7515f920fadf.png)

![tax-rule](https://user-images.githubusercontent.com/30342958/34373744-2e6633ec-eb03-11e7-9fbe-2aa2ffa9a13c.png)

Please use the following Tax configuration : 

![tax-include-config](https://user-images.githubusercontent.com/30342958/34373758-3a995126-eb03-11e7-857f-3b38d4fbf36c.png)


I have checked this issue with the fresh Magento  2.2.1 installation:

Invoice : 
![error-invoice](https://user-images.githubusercontent.com/30342958/34373798-70520b8c-eb03-11e7-836e-f94ed94364d8.png)

Invoice Pdf screenshot: 
![invoice-error-pdf](https://user-images.githubusercontent.com/30342958/34373823-81242652-eb03-11e7-9c37-1dfcdc0641fc.png)


In the screen shoot first product is the simple product but second product is the bundle product. Basically bundle product not including the TAX amount in the invoice PDF.

**Comment by magento-engcom-team** [comment] 2017-12-28 14:29
@digvijay2017, thank you for your report.
We've created internal ticket(s) MAGETWO-86128 to track progress on the issue.

**Comment by RomaKis** [comment] 2018-01-02 13:14
Working on this.

**Comment by sergiypop** [comment] 2018-04-24 07:25
Hello Magento-team, is there any progress for this bug ? I am facing the same problem.

**Comment by ishakhsuvarov** [comment] 2018-04-25 07:49
@sergiypop Solution is in the process of delivery at the moment.

**Comment by sergiypop** [comment] 2018-04-26 07:51
@ishakhsuvarov It would be great if you could post the commit for the solution.

**Comment by ishakhsuvarov** [comment] 2018-04-26 07:52
@sergiypop It is currently available only in private repositories. Comment with information will be posted once fix is delivered.

**Comment by digvijay2017** [comment] 2018-04-27 04:14
@sergiypop  @ishakhsuvarov  . I am still looking the permanent solution for this issue. Well
For temporary solution: I am added this  
`$price = $order->formatPriceTxt($childItem->getPriceInclTax());` 
instead  of 
 `$price = $order->formatPriceTxt($childItem->getPrice());`  in the file :  vendor/magento/module-bundle/Model/Sales/Order/Pdf/Items/Invoice.php   line : 135 by overwrite the Model : Magento\Bundle\Model\Sales\Order\Pdf\Items\Invoice

**Comment by thlassche** [comment] 2019-06-24 14:02
@ishakhsuvarov @sergiypop Will this be in 2.3.2?

**Comment by engcom-Bravo** [comment] 2019-12-27 13:25
Reproducible on Magento 2.4-develop
![bundle_subtotal](https://user-images.githubusercontent.com/51680745/71518767-0bcaee00-28bd-11ea-94f9-4d56dcd474b7.png)

**Comment by magento-engcom-team** [comment] 2019-12-27 13:31
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-12-30 10:29
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30127` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2021-01-05 13:20 UTC
Labels: Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Component: Email, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.2.x

**Comment by rickcj** [comment] 2022-04-25 09:20
I have upgraded from 2.3.4 to 2.3.5, 2.3.5-p1, -p2, 2.3.7 and every time I have to redo this fix as it hasn't been back ported.
