### ISSUE TITLE
Invalid header value in NewRelicReporting when flushing Magento cache

### ISSUE THREAD

**Issue by speller** [magento/magento2#34646] opened 2021-11-16 07:30 UTC
### Preconditions (*)
1. Magento 2.4.3
2. Running on AWS behind Application Load Balancer.

### Steps to reproduce (*)
1. Enable built-in NewRelic reporting
2. System -> Cache management -> Flush Magento cache.

### Expected result (*)
Cache flushed.

### Actual result (*)
Raw plain-text PHP error page with the following content:

```
1 exception(s):
Exception #0 (Zend_Http_Header_Exception_InvalidArgumentException): Invalid header value

Exception #0 (Zend_Http_Header_Exception_InvalidArgumentException): Invalid header value
<pre>#1 Zend_Http_Client->_validateHeaderValue() called at [vendor/magento/zendframework1/library/Zend/Http/Client.php:467]
#2 Zend_Http_Client->setHeaders() called at [vendor/magento/zendframework1/library/Zend/Http/Client.php:439]
#3 Zend_Http_Client->setHeaders() called at [vendor/magento/module-new-relic-reporting/Model/Apm/Deployments.php:75]
#4 Magento\NewRelicReporting\Model\Apm\Deployments->setDeployment() called at [vendor/magento/module-new-relic-reporting/Model/Observer/ReportSystemCacheFlushToNewRelic.php:62]
#5 Magento\NewRelicReporting\Model\Observer\ReportSystemCacheFlushToNewRelic->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#6 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#7 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:66]
#8 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#9 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/module-backend/Controller/Adminhtml/Cache/FlushSystem.php:31]
#10 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Cache/FlushSystem/Interceptor.php:23]
#14 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#15 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#16 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#19 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#20 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/mirasvit/module-rewards/src/RewardsCustomerAccount/Plugin/CustomerSessionContext.php:55]
#21 Mirasvit\RewardsCustomerAccount\Plugin\CustomerSessionContext->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#23 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Cache/FlushSystem/Interceptor.php:32]
#24 Magento\Backend\Controller\Adminhtml\Cache\FlushSystem\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#25 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#26 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#27 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#31 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#32 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#33 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>
```

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by speller** [comment] 2021-11-16 07:34
Seems to be related to #9494

**Comment by kanna32** [comment] 2021-11-26 10:22
It same issue I got in Magento 2.4.2 while flushing the cache from the backend.

**Comment by artttj** [comment] 2021-12-21 16:58
Hi @speller,

Did you solve the issue?

**Comment by speller** [comment] 2021-12-22 15:16
@artttj Unfortunately not...

**Comment by artttj** [comment] 2021-12-22 15:25
@speller 

The problem for us was, when we set env variable with API key from AWS into the global scope, they are not encrypted in scope config. A New Relic config helper tries to decrypt it and we get non-valid hieroglyphic  API key which throws an error when you send it as header with Zend Http. That is what's going on in the stack trace.

**Comment by razvan-optaros** [comment] 2022-02-23 11:49
Newrelic action should have a try catch. This is a bug.

**Comment by engcom-Dash** [comment] 2022-07-22 09:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-07-26 13:32
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-01 10:53
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-08-18 07:53
Hello @speller,
Thanks for the report and collaboration1

We have tried to reproduce this issue in the Magento 2.4-develop branch but the issue is not reproducible for us. 

We have enabled the NewRelic reporting, please refer to the below screenshot for reference:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/51681618/185340394-2880ff00-6fd2-4bec-bf94-ed230f285221.png">

After clearing the cache, we are not facing any error, also checked in the system.log file. Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-01 06:52
Dear @speller,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-09-01 06:52 UTC
Labels: Issue: needs update
