### ISSUE TITLE
Custom page layout change through XML has no effect (after 2.4.2-p2 to 2.4.3-p1 upgrade)

### ISSUE THREAD

**Issue by densen45** [magento/magento2#35195] opened 2022-03-15 11:49 UTC
### Preconditions (*)

1. Magento 2.4.3-p1

### Steps to reproduce (*)

Goal: Change the default page layout from 2columns-left to 3columns.

1. Create a custom theme
2. Create a `catalog_category_view.xml` file in the `app/design/frontend/<Vendor>/<Custom_Theme>/Magento_Catalog/layout` directory
3. Add the following content to the file
```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" layout="3columns" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"/>
```
Please note `layout="3columns"`, the default in e.g. `vendor/magento/module-catalog/view/frontend/layout/catalog_category_view.xml` is `layout="2columns-left"`.

4. Clean the cache 
5. Go to the frontend and open e.g. a category

### Expected result (*)

1. The page layout of the category is `3columns` (one main column with a sidebar on the left and another sidebar on the right)

### Actual result (*)

1. The page layout of the category is still `2columns-left` (one main column with sidebar on the left side)

### Investigation (so far)

The issue is discussed in this thread already: https://community.magento.com/t5/Magento-2-x-Version-Upgrades/Category-Layout-Not-Working-After-upgrade/td-p/483694

kanhaiya5590's comment pointed me into the right direction. He suspects that the `catalog_category_view.xml` of Magento's PageBuilder module (introduced in M 2.4.3) causes this issue. It sets the layout to `2columns-left`. Usually, all `catalog_category_view.xml` files are combined, but the one from the PageBuilder is in the wrong directory (kanhaiya5590 assumes). It is in `vendor/magento/module-page-builder/view/frontend/page_layout` instead of in `vendor/magento/module-page-builder/view/frontend/layout`. Therefore, the customization above has no effect.

Moving the `catalog_category_view.xml` to the correct directory (from `vendor/magento/module-page-builder/view/frontend/page_layout` to `vendor/magento/module-page-builder/view/frontend/layout`) makes the customization above work again. What supports the assumption of kanhaiya5590 that the file is in the wrong directory. 

In the thread mentioned above kanhaiya5590 proposes a better workaround. Moving the original file was for testing purposes only.
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by densen45** [comment] 2022-03-15 11:53
The reproduction on a Magento instance, which can be provided here, is not possible for me, because I can not edit files there.

**Comment by khoimm92** [comment] 2022-05-24 08:39
Same issue.
Remove the `layout` specific in `vendor/magento/module-page-builder/view/frontend/page_layout/catalog_category_view.xml` did the trick

**Comment by engcom-Echo** [comment] 2022-07-21 09:38
Hello @densen45 ,

Thank you for reporting the issue.

We tried to reproduce it on Magento 2.4.1-p1, magento 2.4.2-p2 and 2.4-develop but the issue is not reproducible.

Steps followed to reproduce issue:

1- Install the fresh magento instance.
2- Create custom theme
3- Create a catalog_category_view.xml file in the app/design/frontend/<Vendor>/<Custom_Theme>/Magento_Catalog/layout directory 
4- Add the following line
```
<page xmlns:xsi="[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22) layout="3columns" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd"/>


```
5- Clean the cache
6- Go to the frontend and open category page

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51681435/180178020-5c89d5fd-1fdb-4c9d-8e7a-a30e9025d3d0.png">


Please provide more information with exact step and screenshot so that we can reproduce it at our end and kindly test on latest 2.4-develop branch also. 

Thanks

**Comment by engcom-Echo** [comment] 2022-08-04 14:45
Hello @densen45,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-08-04 14:45 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by ereztaiar** [comment] 2023-04-03 12:20
This has happened to me
I have disabled all the modules of pagebuilder and the issue resolved

**Comment by webloft** [comment] 2023-04-28 08:41
Yes, this issue exists in 2.4.6 as well:

- default layout setting for categories is ignored
- page layout of app/design/frontend//<Custom_Theme>/Magento_Catalog/layout/catalog_category_view.xml is ignored
- page layout of vendor/magento/module-page-builder/view/frontend/page_layout/catalog_category_view.xml will be applied

We can verify this by updating the layout in page-builder module or creating an override in app/design/frontend/<Custom_Theme>/Magento_PageBuilder/page_layout/catalog_category_view.xml

**Comment by antoniocarboni** [comment] 2023-05-30 15:43
This issue still exist on 2.4..6

**Comment by Detzler** [comment] 2024-03-21 13:43
@engcom-Echo
Confirm issue on 2.4.6-p4
Still present.

Workaround solution by @webloft helped, thx.
