### ISSUE TITLE
Tax rules + Multi-currencies + Configurable products = Bug?

### ISSUE THREAD

**Issue by nntoan** [magento/magento2#7790] opened 2016-12-14 11:25 UTC
Hello there,
As the title said, I found a very interesting bug which you may concern...

### Preconditions

1. Magento 2.1.2
2. PHP 7.0
3. MySQL 5.7
4. Ubuntu 16.04
5. Setup tax rules as the following image
![screenshot-tax-rule-2016-12-14-18-18-11](https://cloud.githubusercontent.com/assets/3891429/21180057/c7afc53a-c229-11e6-970c-c110400aed79.png)
6. Setup multi-currencies for your web store

### Steps to reproduce

1. Go to any configurable product with A currency
2. Select any options
3. Choose B currency
4. Select any options while using B currency

### Expected result

1. Price of B currency must not change back to Price of A currency after select options

### Actual result

![screenshot 2016-12-14 18 12 57](https://cloud.githubusercontent.com/assets/3891429/21180192/6b1f62ac-c22a-11e6-8da3-ec1a35354fdc.png)
![screenshot 2016-12-14 18 13 44](https://cloud.githubusercontent.com/assets/3891429/21180198/73681670-c22a-11e6-884a-3f7d332bcdd4.png)
![screenshot 2016-12-14 18 14 08](https://cloud.githubusercontent.com/assets/3891429/21180210/7d8f4af6-c22a-11e6-91ad-5fbad2aa32a2.png)

**Comment by vacre** [comment] 2016-12-15 08:33
This is the same issue as #7371 and #7712.

**Comment by veloraven** [comment] 2016-12-19 13:22
@nntoan thank you for your report but I'm closing it as a duplicate of #7371

**Closed as completed by veloraven** 2016-12-19 13:22 UTC
