### ISSUE TITLE
rjsResolver.js not found on fresh installation, all grids are dead?

### ISSUE THREAD

**Issue by hectornguyen** [magento/magento2#6409] opened 2016-08-31 07:13 UTC
### Preconditions

1. Ubuntu 16.04.1 LTS
2. Magento 2.1.1
3. PHP 7.0.10 (or PHP 5.6.25)
4. Percona 5.7 (`5.7.14-7-log Percona Server (GPL), Release '7', Revision '083e298'`)
### Steps to reproduce

1. Install latest Magento version through `composer`, then install it via `bin/magento setup:install` with **https://** in `--base-url`
2. Execute `bin/magento setup:upgrade` 
3. Execute `bin/magento setup:di:compile`
4. Execute `bin/magento setup:static-content:deploy <code> en_US` (I'm using different locale code than en_US, `<code>` in this case is vi_VN)
5. Execute `bin/magento indexer:reindex` and `bin/magento cache:flush`

It also means, you are on fresh installation from composer and your `deploy:mode` is **default**
### Expected result

1. Magento **adminhtml** 2.1.x should works as usual as 2.0.x
### Actual result

1. Order grids and the other should look like this
   ![screenshot 2016-08-31 13-26-31](https://cloud.githubusercontent.com/assets/13457344/18119002/82cba14a-6f82-11e6-8be5-3dafed56c1eb.png)
2. Console log recognised by the browsers for those grid (I tried all browsers I had, Safari, Chrome, Firefox normal mode and private mode, and cleared all browsers cache too)
   ![screenshot 2016-08-31 13 33 45](https://cloud.githubusercontent.com/assets/13457344/18119001/82cb24d6-6f82-11e6-9ae4-f0d81d0110e9.png)
3. Require.js is dead for the whole backend, not only grids. Here is the Chrome's console log of Configurations
   ![screenshot 2016-08-31 13 56 55](https://cloud.githubusercontent.com/assets/13457344/18119190/a621058a-6f83-11e6-9888-36a8cb9edc95.png)
4. The frontend is good (at least no error recorded in the homepage)
   ![screenshot 2016-08-31 14-06-50](https://cloud.githubusercontent.com/assets/13457344/18119313/37873c74-6f84-11e6-9e0e-81bdae285b7b.png)

If you are worrying about my permission, then don't. Here is it, directly from the server. All files are 644, directories are 755. Please note that all other web applications on this server are working fine. No permission problem at all.
![screenshot 2016-08-31 14 02 07](https://cloud.githubusercontent.com/assets/13457344/18119338/509abb96-6f84-11e6-9bb1-f31715b40cf2.png)

I did **A LOT** of research before open this issue, they can't help me. I do install-reinstall Magento 2.1.x approx **billions** of time since the **beginning of August** before submit it by the **end of August**.

I didn't:
- Try install Magento 2.1.x from archive package (to reprocedure this issue)
- Try install Magento 2.1.x from git (to reprocedure this issue)

Magento 2.0.x works fine on this server (2.0.7 actually), so this issue not come from the server side absolutely.

Please help me find out what was happened and how to deal with it.

Thank you,
Hector.

**Comment by erikhansen** [comment] 2016-08-31 18:18
I'm also experiencing this issue on a clean 2.1.1 install running in production mode. When I run the site in developer mode, I don't see the issue.

**Comment by hectornguyen** [comment] 2016-09-01 02:37
@erikhansen I tried to change to production mode or developer mode in my case, neither works.

**Comment by yvoronoy** [comment] 2016-09-05 14:49
Internal MAGETWO-58052 has been created

**Comment by BenGlassAtlas** [comment] 2016-09-30 09:43
Any update on this please @yvoronoy - Running a production site in developer mode is not a great workaround 😞

**Comment by anton-huz** [comment] 2016-10-07 13:36
Hi guys,
I have a good news for: your instance already has all stuff needed to fix the issue.

### The root of an issue

Lets install Magento 2.1 and open Orders' list or Products' list in Admin area. When you look in network tab of your browser you can find that almost all files are loaded. There is just a few missings like `rjsResolver.js`. Indeed this file is missed from Magento-box.

Magento 2.1 (compare to Magento 2.0) introduces several code features. One of them (how JS app track changes on the page) touches `mage/requirejs/resolver` file. In M2.1 it loaded via alias `rjsResolver`.

The alias was placed in _main_ `requirejs-config.js` file in the Theme module. 

### How does it touch your website?

On each page Magento loads `requirejs-config.js` file from `.../static/_requirejs/.../` folder. This is _compiled_ version of all  `requirejs-config.js` files from all Modules for particular area. This means that when you _do update Magento_, _install new module_ or some how change list of the enabled Magento's modules, each time you need flush `pub/static/_requirejs/` folder. Or even whole `pub/static/`.

### But I do fresh install with generating static assets from scratch!

Ok, it's good. But you should pay attention to your browser cache. If you have older Magento installed on same domain your browser cached assets like `./requirejs-config.js` file.

### What can I do? How can I fix issue?

 You can:
- Clear browser cache in [Google Chrome](https://support.google.com/chromebook/answer/2392709), [Mozilla Firefox](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache), [Microsoft Edge](https://support.microsoft.com/en-us/help/10607/windows-10-view-delete-browser-history-microsoft-edge)
- Use _Private mode_ for your browser
- Dont cache assets for development instance in your developer's [Google Chrome](https://developers.google.com/web/tools/chrome-devtools/settings), [Mozilla Firefox](https://developer.mozilla.org/en-US/docs/Tools/Settings#Editor_Preferences), [Microsoft Edge ("Always refresh from server" option)](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/network/)

### What can we do with real production site and real customers? We can't clear cache for all of them.

Yes, you cann't force clear cache. You can:
- Use CDN for your static asset in such way that changes in modules' list affect static assets url
- Use ["Sign Static Files"](http://docs.magento.com/m2/ce/user_guide/system/static-file-signature.html) option in Admin panel. Just toggle it to _"Yes"_. From 2.2 it will be  _"Yes"_ by default.

In any way the issue will be resolved when `requirejs-config.js` will be updated to correct one.

**Comment by anton-huz** [comment] 2016-10-07 13:39
I'm closing an issue as "Not a bug" until you can correct my conclusion.

**Closed as completed by anton-huz** 2016-10-07 13:39 UTC
Labels: bug report, Area: Frontend

**Comment by hectornguyen** [comment] 2016-10-10 10:43
Hello @erikhansen @BenSpace48 and @guz-anton,

As @guz-anton said, this is definitely not a bug, I resolved it by myself after few more hours researching after open this ticket and forgot to update this ticket.

"Issue" I refer here is all things below:
- Fresh installation on Magento 2.1.x
- Clear cache in all browsers, tried private mode
- Switch to developer mode
- Execute `bin/magento setup:static-content:deploy` billion of times.

We are facing to this issue if and only if you are sastify all requirements below:
- Used to upgraded Magento from 2.0.x to 2.1.x
- Using any CDN service which support caches (or your CDN domain was run M2.0.x before)

In my case, that is CloudFlare. So the solution for this trouble is:
- Turn off CDN static cache (not recommended)
- Stop using Magento 2 (nice to try)
- Use [Sign Static Files](http://docs.magento.com/m2/ce/user_guide/system/static-file-signature.html) as @guz-anton mentioned above (recommended)

This issue is a silly reported by a drunk. Don't hate me.

**Comment by tookuul-owner** [comment] 2016-10-13 12:41
@guz-anton thanks for the detailed response. I admit that I am new to Magento so I am talking with no authority here. Just take my comments as those of a simple user experiencing Magento for the first time.
- This is caused by browser cache : not really. I installed Magento for the first time ever and experienced this problem. It was fixed after I removed pub/static/frontend and pub/static/adminhtml, ran bin/magento setup:static-content:deploy and then bin/magento cache:clean
- This is not a "bug" but an "issue" : that's fair enough. Technically nothing is broken. However, it can be improved. As a first time user to Magento I find that a fresh install is broken is far from a good first impression. If we want a stronger community this should be fixed because something like this can discourage people from using Magento and look into other options.

Maybe the installation needs to run a couple extra commands. I don't know. But from my perspective something wasn't right.

I hope this is useful.

**Comment by anton-huz** [comment] 2016-10-17 10:10
@tookuul-owner 
The only case when I reproduced the similar issue (an error with rjsRelover) is an outdated RequireJS config in the browser. There are several places that can lead to such behavior. Outdated browser cache  - is one of them.

Currently, in this discussion, there are no other insights about root causes.
