### ISSUE TITLE
REST API: 'searchCriteria' and 'fields' paramaters can't used with one another to fetch orders

### ISSUE THREAD

**Issue by jigardhaduk** [magento/magento2#23609] opened 2019-07-08 04:34 UTC
### Preconditions (*)

1. Magento 2.3.1

### Steps to reproduce (*)

1. Create a simple code of REST API with `curl` to fetch orders with `updated_at` **searchCriteria** parameter and **fields** parameter.
2. Code as below

```
$webSiteUrl = 'mydomain.com'
$last1DayUpdated = date('Y-m-d',(strtotime ('-1 day', strtotime(date('Y-m-d')))));
$ch = curl_init("{$webSiteUrl}/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]={$last1DayUpdated}&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&fields=billing_address,customer_firstname,customer_lastname");
```

### Expected result (*)

1. Output should json of orders with mentioned fields

### Actual result (*)

1. Output is blank array

**Comment by jigardhaduk** [comment] 2019-07-08 04:50
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-07-08 04:50
Hi @jigardhaduk. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-08 04:50
Hi @jigardhaduk, here is your [Magento instance](https://i-23609-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23609-2-3-develop.instances.magento-community.engineering/admin](https://i-23609-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by jigardhaduk** [comment] 2019-07-08 05:09
Hello @magento,
Used the given instance to fetch order.

And using below **curl** command to fetch last 1 day updated orders with required fields but give blank array.

`$ch = curl_init("https://i-23609-2-3-develop.instances.magento-community.engineering/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]=2019-07-07&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&fields=billing_address,customer_firstname,customer_lastname");`

**Comment by magento-engcom-team** [comment] 2019-07-08 08:58
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17970` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jigardhaduk** [comment] 2019-07-09 04:44
Hello,

Is there any update on this?

**Comment by edenduong** [comment] 2019-07-14 01:11
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-14 01:11
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-14 01:12
Hi @edenduong, here is your [Magento instance](https://i-23609-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23609-2-3-develop.instances.magento-community.engineering/admin](https://i-23609-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by edenduong** [comment] 2019-07-14 01:31
Hello @jigardhaduk :

fields=billing_address,customer_firstname,customer_lastname . I don't see it in the API docs : https://devdocs.magento.com/swagger/

I removed it and the API has the normal results.

**Comment by arushi013** [comment] 2019-07-17 12:35
Hi @jigardhaduk,

I suppose you want only the customer_firstname,customer_lastname and billing_address field as an result by using search criteria in Magento. But search criteria will response all the fields to you and there is no way to pass like fields=billing_address,customer_firstname,customer_lastname.

This can be achieved using graphql, you can see it here (https://devdocs.magento.com/guides/v2.3/graphql/send-request.html)

This does not seems to be an issue.

**Comment by arushibansal013** [comment] 2019-07-19 11:36
Hi @jigardhaduk,

The way to use fields with search criteria is different, here is the code:-

$webSiteUrl = 'mydomain.com'
$last1DayUpdated = date('Y-m-d',(strtotime ('-1 day', strtotime(date('Y-m-d')))));
$ch = curl_init("{$webSiteUrl}/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][value]={$last1DayUpdated}&searchCriteria[filter_groups][0][filters][0][condition_type]=gteq&fields=items[billing_address,customer_firstname,customer_lastname]");

**Closed as completed by arushibansal013** 2019-07-19 11:36 UTC
Labels: Issue: Ready for Work, Component: Framework/Webapi, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Api
