### ISSUE TITLE
Graphql updateCartItems (removal) not working when stock management and max stock amount reached

### ISSUE THREAD

**Issue by paulappelbe** [magento/magento2#30220] opened 2020-09-28 15:31 UTC
### Preconditions (*)
1. Magento 2.3
1. using graphql to add/remove products

### Steps to reproduce (*)
Say you have 3 products in stock, you add 3 to the cart and try to remove one via the "updateCartItems" graphql, so setting the qty to 2, it refuses to remove because of insufficient stock.
using Luma it works, but not using graphql.

### Expected result (*)

1. you should be able to remove the product even if at max amount of stock

### Actual result (*)
1. exception happens 
main.ERROR: Could not update cart item: La quantité demandée n’est pas disponible {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Could not update cart item: La quantité demandée n’est pas disponible at /vendor/magento/module-quote-graph-ql/Model/Resolver/UpdateCartItems.php:92, Magento\\Framework\\GraphQl\\Exception\\GraphQlInputException(code: 0): Could not update cart item: La quantité demandée n’est pas disponible at /magento/vendor/magento/module-quote-graph-ql/Model/Cart/UpdateCartItem.php:95)"} []

**Comment by fooman** [comment] 2020-09-29 20:39
While likely not the cause of this issue, there is a related issue with stock and grapqhl. Setup a product that uses custom option that importantly changes the SKU. 
![image](https://user-images.githubusercontent.com/455508/94613195-b6ff4c80-0300-11eb-9dd2-29e5cc981ce7.png)


Then add the product to the cart. This product will always be out of stock because https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L802 `getSku()` will provide the option adjusted sku rather than sku that inventory is based on.

Fix
```
diff --git a/Model/Resolver/StockStatusProvider.php b/Model/Resolver/StockStatusProvider.php
index 2002adf9..204f9752 100644
--- a/Model/Resolver/StockStatusProvider.php
+++ b/Model/Resolver/StockStatusProvider.php
@@ -55,7 +55,7 @@
         $product = $value['model'];

         $stockId = $this->getStockIdForCurrentWebsite->execute();
-        $result = $this->areProductsSalable->execute([$product->getSku()], $stockId);
+        $result = $this->areProductsSalable->execute([$product->getData('sku')], $stockId);
         $result = current($result);

         return $result->isSalable() ? 'IN_STOCK' : 'OUT_OF_STOCK';
```

**Comment by mmezhensky** [comment] 2020-10-28 08:57
@magento I am working on this

**Comment by mmezhensky** [comment] 2020-11-25 07:43
Hello @paulappelbe 
I can't reproduce this now. Changing QTY via GraphQL, for all cases, works well for me.
Could you give more detailed steps to reproduce this issue?
Thank you!

**Comment by engcom-Alfa** [comment] 2021-11-17 11:47
Hi @paulappelbe 
Thanks for your contribution and collaboration!
I have tried to reproduce this issue and seems to be not reproducible. Kindly cross-check below steps I followed please!

1. Created a cart using GraphQL request.
2. Added 3 products with 2 quantity each as shown in the below screenshot.
<img width="1440" alt="Products added to Cart" src="https://user-images.githubusercontent.com/51679138/142193999-8676795d-b271-43df-852c-9fcb355bb6a4.png">
3. Updated the cart with zero quantity for 2 of the products among 3, and the screenshot is below
<img width="1440" alt="update to cart" src="https://user-images.githubusercontent.com/51679138/142194306-4dc3aa5e-5134-4894-8459-06a282ec53cb.png">
4. GraphQL queried that retrieves the cart products and list.
<img width="1440" alt="cart after updating" src="https://user-images.githubusercontent.com/51679138/142194431-c0915160-bdd0-4ba1-bffc-2507d66d66cc.png">

As defined in the [issue description](https://github.com/magento/magento2/issues/30220#issue-710370985), didn't notice any issue as such. Zeroed quantity is successfully ignored in the cart queried response.
Tested it in the 2.4-develop Magento instance, and kI request you to kindly check if the issue is still existing. Since the issue was noticed many months back, it might have fixed with other PRs.

**Comment by engcom-Alfa** [comment] 2021-11-17 13:21
Hi @paulappelbe Thanks for your contribution!

I have retried to reproduce the issue in 2.4-develop instance and unable to reproduce it successfully. Below are steps I followed to reproduce the issue, kindly cross-check it and let me know if I have to change anything in my followed steps.

1. Created a simple product with quantity 3 as shown in below screenshot. 
<img width="1440" alt="Screenshot 2021-11-17 at 5 56 05 PM" src="https://user-images.githubusercontent.com/51679138/142206522-d3b87d34-4f4c-41ed-ac29-43badd3f2211.png">

2. Created a customer token and cart id using GraphQL requests.
3. Added the same above created product into the cart using GraphQL request and below screenshot shows the content of cart that is retrieved using GraphQL query.
<img width="1440" alt="Screenshot 2021-11-17 at 6 24 51 PM" src="https://user-images.githubusercontent.com/51679138/142207407-5fbb9d7c-8919-4639-9e64-c094653d30d2.png">

4. Using update GraphQL mutation, changing the product quantity to 2 from 3 as shown in the below screenshot.
<img width="1440" alt="Screenshot 2021-11-17 at 6 24 38 PM" src="https://user-images.githubusercontent.com/51679138/142208339-5f408845-982f-4bc1-ad94-963150643224.png">

As we can see the response data, there is no issue noticed that is defined in the above description.
Kindly re-test and let me know if the issue is not existing now please!
Thanks in advance!

**Comment by engcom-Alfa** [comment] 2021-11-18 18:14
> While likely not the cause of this issue unless custom product options are also used, there is a related issue with stock and grapqhl. Setup a product that uses custom option that importantly changes the SKU. ![image](https://user-images.githubusercontent.com/455508/94613195-b6ff4c80-0300-11eb-9dd2-29e5cc981ce7.png)
> 
> Then add the product to the cart. This product will always be out of stock because https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Type/AbstractType.php#L802 `getSku()` will provide the option adjusted sku rather than sku that inventory is based on.
> 
> Fix
> 
> ```
> diff --git a/Model/Resolver/StockStatusProvider.php b/Model/Resolver/StockStatusProvider.php
> index 2002adf9..204f9752 100644
> --- a/Model/Resolver/StockStatusProvider.php
> +++ b/Model/Resolver/StockStatusProvider.php
> @@ -55,7 +55,7 @@
>          $product = $value['model'];
> 
>          $stockId = $this->getStockIdForCurrentWebsite->execute();
> -        $result = $this->areProductsSalable->execute([$product->getSku()], $stockId);
> +        $result = $this->areProductsSalable->execute([$product->getData('sku')], $stockId);
>          $result = current($result);
> 
>          return $result->isSalable() ? 'IN_STOCK' : 'OUT_OF_STOCK';
> ```

Tried to reproduce utilising the product that has custom options. Details mentioned below:

1. Created a product with 3 available quantity with custom options as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-11-18 at 5 10 57 PM" src="https://user-images.githubusercontent.com/51679138/142472385-2ae488ea-45e2-4bb3-8cbd-5d5fb5bbb314.png">

2. With the logged in customer, added the same product into the cart, where used all 3 quantities of the product.
3. Checked the cart details using a GraphQL query ans screenshot of it is below.
<img width="1440" alt="Screenshot 2021-11-18 at 6 40 30 PM" src="https://user-images.githubusercontent.com/51679138/142472602-cf59881d-a7f4-4285-9afe-44aafde9769f.png">

4. Updated the cart by changing the quantity to 2 and didn’t get any issue as defined in the description. Below is the screenshot of it.
<img width="1440" alt="Screenshot 2021-11-18 at 6 40 35 PM" src="https://user-images.githubusercontent.com/51679138/142472755-4be75172-c108-475b-b125-b497cd0d7a7e.png">

Looks like the issue is not reproducible now. Can you please re-try in 2.4-develop and tell me if there is any execution needs to be corrected.

**Comment by fooman** [comment] 2021-11-18 22:57
@engcom-Alfa thanks for checking. Just to confirm in your tests did you only use this Github repo or did you also install magento/inventory?

If you could add 
stock_status
to your get cart items query https://github.com/magento/inventory/blob/d8be487cedff1dcad64d20f3375a3ce28e08dc57/InventoryGraphQl/etc/schema.graphqls#L6
you should be able to see it.

**Comment by engcom-Alfa** [comment] 2021-11-19 12:53
Hi @fooman
I had tried without inventory last time; I again tried using inventory module one more time and the steps are below.

1. Made sure to have the inventory configurations as shown in below screenshot.
<img width="1440" alt="Screenshot 2021-11-19 at 12 41 51 PM" src="https://user-images.githubusercontent.com/51679138/142625041-b2ff0e30-37e2-40ea-8666-69df102fe9dc.png">

2. Created a new product with custom options again with quantity 3, and the screenshot is below.
<img width="1440" alt="Screenshot 2021-11-19 at 12 43 20 PM" src="https://user-images.githubusercontent.com/51679138/142587052-e2f5a372-30be-4f6e-91e0-787ec6d78ea1.png">

3. Logged in as customer and added the above created product into the cart with all 3 quantities
4. Received the same customer token with GraphQL request and followed by retrieved the cart details using GraphQL request as shown in below screenshot. Where I have used stock_status as well as you said.
<img width="1440" alt="Screenshot 2021-11-19 at 1 24 41 PM" src="https://user-images.githubusercontent.com/51679138/142625451-10465309-8686-4139-8c84-aa8d6cdeff07.png">

 5. Updated the cart product quantity to 2 from 3 as shown in the below screenshot. No issue noticed!
<img width="1440" alt="Screenshot 2021-11-19 at 1 25 01 PM" src="https://user-images.githubusercontent.com/51679138/142625563-26d9ea9d-ad63-488a-8838-606e017c764c.png">

Can you check if any other procedure required to reproduce, If so please give me the proper steps/configurations to reproduce along with query u used.
Kindly test in 2.4-develop and reply me please!

**Comment by cpartica** [comment] 2022-02-10 03:54
Bumping priority because shopper behavior changed quite a lot since 2020, and out of stock is not an edge case anymore

**Closed as completed** 2022-03-29 19:55 UTC
Labels: Issue: Format is valid, Component: GraphQL, Priority: P1, Severity: S1, Project: GraphQL, Progress: done, Mageconf_Contribution_Day
