### ISSUE TITLE
Magento 2.1.0 Fresh Install: Toolbar broken and errors

### ISSUE THREAD

**Issue by Toweringmedia-clients** [magento/magento2#5196] opened 2016-06-23 18:06 UTC
On a fresh install of 2.1.0 after logging into admin navigating to the cms pages. The tool bar is broken at the top and I am getting the following in the debugger. 

/~magento2/pub/static/adminhtml/Magento/backend/en_US/knockoutjs/knockout.js:3012 Uncaught ReferenceError: Unable to process binding "scope: function (){return bulk }"
Message: Unable to process binding "template: function (){return getTemplate() }"
Message: Unable to process binding "if: function (){return $parent.isActionsColumn($col) }"
Message: $col is not defined
toolbar.js:357 Uncaught TypeError: Cannot read property 'offsetLeft' of undefined

**Comment by Toweringmedia-clients** [comment] 2016-06-24 18:02
updated title, I reinstalled and still have the same issue. Any help is appreciated.

**Comment by veloraven** [comment] 2016-07-05 07:21
@toweringmedia , thank you for your report.
Unfortunately I was not able to reproduce this issue.
Could you please provide us details about your environment: versions of PHP, MySQL and web server?
Please also describe all steps you have done in more detailed way.
And if you can attach screenshot or some logs it may help as well.

**Comment by Melvin-de-Jong** [comment] 2016-07-23 13:01
Hi,

We are having the same issue on a server. We did a clean install from Plesk 12.5 applications menu, we are running PHP 7.0.8 as FPM application served by Apache, MariaDB 10.1.14, on centos7 and Plesk 12.5.

We find the problem in the admin area of Magento 2.1.0 in pages and blocks overview.

![screen shot 2016-07-23 at 14 44 49](https://cloud.githubusercontent.com/assets/7561214/17077937/08d3fc8c-50e4-11e6-8a21-5ec1ebce1282.png)

I have tried:
-switching from developer to production mode, 
-clearing cache with command bin/magento cache:clean
-running command rm -rf var/cache/\* var/page_cache/\* var/generation/*
-clean installing from plesk

none of these have worked. 
I hope this helps in any way.

Kind regards,
Melvin de Jong
Vuyani Software

**Comment by ElliotGage** [comment] 2016-07-24 19:22
Same issue... getting grid header formatting problems in product and pages admin with a javascript error: 
toolbar.js:357 Uncaught TypeError: Cannot read property 'offsetLeft' of undefined

Version 2.1.0 command line installation. Older installs have gone fine.
CENTOS 7.2 x86_64
php 5.6
apache 2.4
 5.6.30 - MySQL Community Server (GPL)

**Comment by ElliotGage** [comment] 2016-08-06 23:33
I figured out why my site was having the above issue.
I had enabled mod_pagespeed long ago on my server. It was including javascript which interfered with the magento js includes.

Simple disable in .htaccess killed the problem.

**Comment by Melvin-de-Jong** [comment] 2016-08-06 23:38
@ElliotGage I can confirm that this fixed the issue. Add ModPagespeed off in your .htaccess file and the problem is solved.

**Comment by clementbeudot** [comment] 2016-08-26 16:09
Very nice guys, thank you for the solution. It helped me a lot.
Maybe we should write a warning note in the README.md about this ?

**Comment by PRAKASHSIVASANKAR** [comment] 2016-09-01 08:43
Amazing Guys this awesome...

this issue fixed...

**Comment by bery** [comment] 2016-09-01 09:01
Hi guys,

I would not call turning pagespeed of either in server config or .htaccess file a solution when it can be disabled for admin pages and kept on for frontend. Sample nginx pagespeed config that works for our use cases 

```
pagespeed On;
pagespeed RewriteLevel CoreFilters;
...
pagespeed Disallow "*/admin/*"; ##your admin URL
pagespeed Disallow "*/backend/*";
pagespeed Disallow "*/adminhtml/*";

```

Please note that we are updating the config as we go and keep finding affected URLs

**Comment by ubedarab** [comment] 2016-12-14 07:59
Thanks, your solution Fixed My issue, I had same issue, :) :+1:

**Comment by dmitriyprime** [comment] 2017-06-22 14:04
Thanks for reporting this issue. Is it actual for you or we can close it?

**Comment by jcsgithub** [comment] 2017-08-10 06:33
Hello guys,

Did a fresh install of Magento v2.1.7.
Saw that Catalog page is still broken so I added "ModPagespeed off" in the .htaccess file.
Then I also saw that Customer page is also broken, and the above fix didn't work the same.

Anyone having the same problem?

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@toweringmedia, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by okorshenko** [comment] 2017-10-04 16:20
we will retest this again

**Comment by magento-engcom-team** [comment] 2017-10-05 14:30
@toweringmedia, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by magento-engcom-team** [comment] 2018-03-05 22:51
Closing as non-issue. Please see previous comment

**Closed as completed by magento-engcom-team** 2018-03-05 22:51 UTC
Labels: Issue: Clear Description, Issue: Confirmed, non-issue, Issue: Format is not valid
