### ISSUE TITLE
[2.4] Order can be placed when requested qty more than qty exist

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/magento2#30299] opened 2020-10-01 20:16 UTC
Precondition:
* Create Configurable product **C1** with attribute "color" (red, qty - 10)

Steps to reproduce:
* Go to Sales -> Orders -> Create new Order -> Create new Customer
* Click "Add product" button
* Click "Configure" button near **C1**
* Select red and set quantity as 8(less that available)
* Select product **C1-red** and set quantity as 8
* Click "add selected product(s) to order" button <<sup>add selected product.png]
![image](https://user-images.githubusercontent.com/3409584/94858920-5b64ba00-03f9-11eb-9dd1-f5b17ee90e8f.png)

* Click "Update Items and Quantities" button [</sup>update.png] (x) There is no message. 
![image](https://user-images.githubusercontent.com/3409584/94858938-64558b80-03f9-11eb-825c-b0675f04d395.png)

* Refresh page [^f5.png> 
![image](https://user-images.githubusercontent.com/3409584/94858950-67e91280-03f9-11eb-9bd3-06753484c847.png)

* Fill all required data about customer and order
* Click "Place Order" button 

(x) The order Placed. Message ignored. C1-red qty has value -6. (Backorders disabled)
 (/) The order could not be placed as there is no such qty amount.

**Comment by magento-engcom-team** [comment] 2020-10-01 20:16
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/MC-29723

**Comment by magento-engcom-team** [comment] 2020-10-01 20:48
:white_check_mark: Confirmed by @magento-engcom-team 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29723` were created

**Issue Available**: @magento-engcom-team, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shikhamis11** [comment] 2020-10-09 09:17
@magento give me 2.4-develop instance

**Comment by irshadcedcoss** [comment] 2020-10-09 10:46
@magento I am working on this

**Comment by SeruyV** [comment] 2020-10-09 14:29
Hi, @irshadcedcoss the current issue is already fixed by another one. I believe that it fixed at https://github.com/magento/magento2/pull/26650/ but not 100%. Anyway, their main issue is fixed. The only thing which is not fixed is error messages which do not appear till the refresh page. I`ve just checked in with Magento 2 Open Source and Magento 2 Open Source + Inventory.

**Comment by miteshdhaduk** [comment] 2020-10-10 07:11
#dmcdindia2020

**Comment by magento-engcom-team** [comment] 2020-10-10 07:11
@miteshdhaduk thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Closed as completed** 2020-11-04 12:38 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue:  Cannot Reproduce, Component: Other, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Event: dmcdindia2020, Reported on 2.4.0

**Comment by sdzhepa** [comment] 2020-11-04 18:23
The related internal Jira ticket `MC-29723` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
