### ISSUE TITLE
I get '500 Internal Server Error' error when I added Configurable Product with 360 variants.

### ISSUE THREAD

**Issue by ismlyldz** [magento/magento2#13673] opened 2018-02-15 10:45 UTC
### Preconditions

1. Magento 2.2.2
2. PHP 7.0.26 

### Steps to reproduce

1. When I added Configurable Product with 360 variants,
2. I get '500 Internal Server Error' error,
3. It has been added 360 products,
4. But I can not enter product detail page.

### Expected result

1. I expect detail page to work.

### Actual result

1. Error that gave, like this;

<a href="http://ibb.co/mOCpRS"><img src="http://thumb.ibb.co/mOCpRS/pro1.png" alt="pro1" border="0"></a><a href="http://ibb.co/bWkXfn"><img src="http://thumb.ibb.co/bWkXfn/pro2.png" alt="pro2" border="0"></a>

memory_limit=5G, 
max_execution_time=12000000000, 
max_input_time=30000000000,
max_input_vars = 101000 etc.

**Comment by magento-engcom-team** [comment] 2018-02-16 09:36
@ismlyldz  thank you for your report
  Unfortunately, we can't reproduce this issue.
  Please try to reproduce this issue on the clean installation ver 2.2.2 and tell us the result.

**Comment by johnny-longneck** [comment] 2018-02-16 10:59
Error 500 is mostly a PHP error which you can see in the log files. Is there any hint?

**Comment by ismlyldz** [comment] 2018-02-16 11:08
@johnny-longneck I gave the error! 

<a href="http://ibb.co/bWkXfn"><img src="http://preview.ibb.co/hvqyLn/pro2.png" alt="pro2" border="0" /></a>

**Comment by johnny-longneck** [comment] 2018-02-16 11:18
Ah sorry,
Well it clearly says you are out of memory. 
Are you using PHP-FPM (maybe with nginx?)
So it can be that the setting of memory_limit=5G is not being applied.

First of all check the value of via phpinfo();
Command line: `php -r 'phpinfo();'`

Other possibility is that the memory is not available. Not physically and not virtually.
Check that via command line: "free -m"
So if 5G is not available you might need to increase the size of swap memory.

All in all this is a server configuration problem, rather than a magento 2.

**Comment by ismlyldz** [comment] 2018-02-16 11:53
I think so too and I made all settings according to this. But, result is always same!

<a href="http://ibb.co/dwCBQn"><img src="http://thumb.ibb.co/dwCBQn/Screen_Shot_2018_02_16_at_14_42_52.png" alt="Screen_Shot_2018_02_16_at_14_42_52" border="0"></a>

<a href="http://ibb.co/cCzQkn"><img src="http://thumb.ibb.co/cCzQkn/Screen_Shot_2018_02_16_at_14_43_27.png" alt="Screen_Shot_2018_02_16_at_14_43_27" border="0"></a>

**Comment by magento-engcom-team** [comment] 2018-02-19 11:52
thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.
 
GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.

**Comment by magento-engcom-team** [comment] 2018-02-19 12:04
@ismlyldz please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.
We are closing this ticket. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2018-02-19 12:04 UTC
Labels: non-issue, Issue: Format is valid
