### ISSUE TITLE
Bad Error Report: Your PHP Version is 5.6.20, but always_populate_raw_post_data = 0

### ISSUE THREAD

**Issue by jaimestuardo** [magento/magento2#4344] opened 2016-04-28 23:59 UTC
This is a bug when running a readiness check when updating Magento. I have decided to open a new ticket for it.

On readiness check, I get this error:

PHP Settings Check
Need Help?
PHP Documentation
Your PHP Version is 5.6.20, but always_populate_raw_post_data = 0. $HTTP_RAW_POST_DATA is deprecated from PHP 5.6 onwards and will be removed in PHP 7.0. This will stop the installer from running. Please open your php.ini file and set always_populate_raw_post_data to -1. If you need more help please call your hosting provider.

This is ridiculous because my PHP.INI file already has that setting with value -1, and I can check it by mean of phpinfo page.

With Magento most strange things happend. This is one of them, among millions.

Why does Magento report that error when that variable is correctly set? I have spent all day long trying to figure this out, but no avail.

**Comment by mazhalai** [comment] 2016-04-29 14:06
@jaimestuardo can you please post relevant portions of your phpinfo(); Also can you give more env details like OS and Webserver.

**Comment by mazhalai** [comment] 2016-05-05 13:18
@jaimestuardo has your issue been resolved?

**Comment by jaimestuardo** [comment] 2016-05-05 14:13
No... this is really a mystery.
![image](https://cloud.githubusercontent.com/assets/9195659/15045651/23556066-12b2-11e6-888f-6b72c56b9273.png)

And if I run phpinfo, I get this:
![image](https://cloud.githubusercontent.com/assets/9195659/15045672/44a8424c-12b2-11e6-86e5-71222cae6c57.png)

The same result was obtained at command line using "php -i" command.

**Comment by ghost** [comment] 2016-05-05 14:59
The only obvious thing is to restart the web server. Assuming you did that, because you evidently have >1 version of PHP installed, make sure you change the value in all the `php.ini` files, at least for troubleshooting. 

The command `php --ini` and `which php` probably report the first one in your `$PATH`. You'll need to find any other `php.ini` files and modify them. Ultimately, you should put only one php executable in your `$PATH` (or create a symlink) which should fix the issue.

**Comment by jaimestuardo** [comment] 2016-05-05 15:37
This is obvious, that is why I think this is a mystery. When I run php --ini I get this:

```
[root@vps-1128921-x /opt/php5-6/lib/php] # php --ini
Configuration File (php.ini) Path: /opt/php5-6/lib
Loaded Configuration File:         (none)
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
[root@vps-1128921-x /opt/php5-6/lib/php] #

```

The fact is in that path, there is no ini file. 

I will modify the variable in all PHP.ini files I have and will see what happen.

**Comment by mazhalai** [comment] 2016-05-09 18:58
@jamescowie closing this as duplicate of #4392

**Closed as completed by mazhalai** 2016-05-09 18:58 UTC
Labels: Progress: needs update
