### ISSUE TITLE
Admin captcha does not load due to CSP when admin and store base_url are different.

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento2#38854] opened 2024-06-20 17:20 UTC
### Steps to reproduce

1. Set your store's id 1' base_url to "magento2.test"
2. Set your admin store url to "admin.magento2.test"
3. Attempt to sign in enough to trigger captcha

### Expected result

See a captcha

### Actual result

See: 

![image](https://github.com/magento/magento2/assets/9029654/5b5e1de8-e96e-4575-b5bb-cb51d217534d)

Console contains

> Refused to load the image 'magento2.test' because it violates the following Content Security Policy directive: "img-src assets.adobedtm.com amcglobal.sc.omtrdc.net dpm.demdex.net cm.everesttech.net *.adobe.com amasty.com www.googleadservices.com www.google-analytics.com googleads.g.doubleclick.net www.google.com bid.g.doubleclick.net analytics.google.com www.googletagmanager.com *.ftcdn.net *.behance.net data: t.paypal.com www.paypal.com www.paypalobjects.com fpdbs.paypal.com fpdbs.sandbox.paypal.com *.vimeocdn.com i.ytimg.com *.youtube.com validator.swagger.io store.paradoxlabs.com www.sandbox.paypal.com b.stats.paypal.com dub.stats.paypal.com assets.braintreegateway.com c.paypal.com checkout.paypal.com *.paypal.com *.aptrinsic.com storage.googleapis.com data: 'self' 'unsafe-inline'".

### Additional information

You can circumvent the issue by opening the captcha url in a new tab, but that's not great.

![image](https://github.com/magento/magento2/assets/9029654/b977e79b-326c-4f27-8358-3dbb47f771ed)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-07-16 07:58
Hi @damienwebdev ,
Thanks for your reporting and collaboration.
We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible. Kindly refer the screenshots.
Steps to reproduce 
- Access Adobe Commerce Admin.
- Navigate to Stores>Settings>Configuration
In configuration page, click on Advanced>Admin
4.	To Change base url, Set the “Use custom admin url” to “Yes”
5.	Enter the new admin url in “Custom Admin URL” field
 
6.	Now, Click on save config
7.	Clear the Cache from System > Tools > Cashe Management
8.	User will be logged-out automatically.
9.	Access the admin url and enter invalid credentials multiple times.
10.	Observe Captcha Displays when user enters invalid credentials multiple times.

**Comment by engcom-Delta** [comment] 2024-07-16 11:10
Hi @damienwebdev ,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce** 

- Access Adobe Commerce Admin.
- Navigate to Stores>Settings>Configuration
- In configuration page, click on Advanced>Admin
- To Change base url, Set the “Use custom admin url” to “Yes”
- Enter the new admin url in “Custom Admin URL” field
![admin url custom](https://github.com/user-attachments/assets/a7f033fa-5a7f-4dc5-bc71-8c18bb082141)
- Now, Click on save config
- Clear the Cache from System > Tools > Cashe Management
- User will be logged-out automatically.
- Access the admin url and enter invalid credentials multiple times.
- Observe Captcha Displays when user enters invalid credentials multiple times.
![Able to view captcha](https://github.com/user-attachments/assets/363b2490-fa04-4356-b4fa-b4c5b84e9447)
Captcha is displaying as expected, User is also able to login with valid credentials and captcha.
Please let us know if we missed anything. 

Thanks.

**Comment by engcom-Delta** [comment] 2024-08-08 06:36
Hi @damienwebdev ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-08-08 06:36 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by damienwebdev** [comment] 2024-09-05 18:26
@engcom-Delta please reopen. There's an additional configuration necessary to trigger this result.

Add the following CSP Configuration:

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <csp>
            <mode>
                <storefront>
                    <report_only>0</report_only>
                </storefront>
                <admin>
                    <report_only>0</report_only>
                </admin>
            </mode>
        </csp>
  </default>
</config>
```

If you use strict CSP, media in the admin panel do not work as they are loaded from the storefront's domain.

The root cause is that the https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Store/Model/StoreResolver.php#L95 returns `1` for the admin store instead of `0`.
