### ISSUE TITLE
Unable to change product stock status when it has related configurable product with different attribute set

### ISSUE THREAD

**Issue by Fel1xx** [magento/magento2#8742] opened 2017-03-01 18:40 UTC
### Preconditions
1. Magento 2.1.4
2. (seems not important) PHP 7.0.13,  5.6.30 

### Steps to reproduce
1. On clean magento, create new Attibute Set.
2. Create a configurable product with attribute set from prev step with a couple configuration options.
3. Create simple product with Default attribute set. Save it.
4. Add configurable product to a list of related products for the simple one. Save it.
5. Try to change value of "Stock Status" of simple product. Save it.

### Expected result
1. After step 5 you should see "Stock Status" value changed.

### Actual result
1. The value of "Stock Status" remains the same after you try to save a product. Works fine if you remove configurable product from related products.

**Comment by Fel1xx** [comment] 2017-03-01 18:45
After couple hours together with XDebug I've found that attributes returned by \Magento\Eav\Model\Entity\AbstractEntity::getAttributesByCode depend on previous calls of \Magento\Catalog\Model\Product\Type\AbstractType::getSetAttributes . If the first product passed to it was having different attribute set than saved one then the result of \Magento\Eav\Model\Entity\AbstractEntity::_isApplicableAttribute was false negative inside of walkAttributes loop, form values are not applied to the stock model.

**Comment by neil-jennings** [comment] 2017-05-18 11:43
Having this issue as well

**Comment by neil-jennings** [comment] 2017-05-18 15:52
Done a hacky fix for now which seems to work.
Find the function addAttribute() in file module-eav/Model/Entity/AbstractEntity.php  

And change the line:
$this->_attributesByCode[$attributeCode] = $attribute;

To:
if (!array_key_exists($attributeCode, $this->_attributesByCode)) {
    $this->_attributesByCode[$attributeCode] = $attribute;
}

**Comment by Andrii-Deineha** [comment] 2017-06-30 14:17
@Fel1xx Hi,  thanks for reporting this issue. Internal ticket was created MAGETWO-70387.

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@Fel1xx, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:01 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is valid
