### ISSUE TITLE
Fotorama - Zoom function breaks at last 2 fullscreen images on mobile

### ISSUE THREAD

**Issue by tools-utrecht-hh** [magento/magento2#13317] opened 2018-01-22 15:17 UTC
After clicking on several gallery images and trying to zoom that image, the gallery breaks and you seem to scroll the page behind the gallery modal, instead of pinchzooming or moving the image.

### Preconditions

1. Magento 2.1.10
2. 

### Steps to reproduce

1. Create a simple product
2. Upload 4 large images (large enough to zoom on a smartphone device)
3. Go to the gallery on a smartphone
4. Tap on the main gallery image to go fullscreen
5. Pinchzoom the image, this works
6. Click on another gallery image
7. Pinchzoom this image, this also works
8. Now click another gallery image
9. Try to pinchzoom now, it zooms the entire browser window and when swiping up and down you are scrolling the page behind the modal
10. When you reproduce several times you'll find that it's always the last 2 images that haven't been clicked yet, will break the pinchzoom functionality

### Expected result

1. I should be able to pinchzoom these images

### Actual result

1. Pinchzoom functionality breaks and zooms entire browser instead of the image.

**Comment by magento-engcom-team** [comment] 2018-02-13 15:30
@experius-nl, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-02 10:58
Hi @mishanino. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-12-10 14:37
@experius-nl, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-12-10 14:37 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
