### ISSUE TITLE
Fatal error on creditmemo mail grouped product

### ISSUE THREAD

**Issue by arnoudhgz** [magento/magento2#25617] opened 2019-11-15 12:00 UTC
### Preconditions
1. Magento 2.3.3
2. Production mode and development mode

### Steps to reproduce (*)

1. Install Magento 2.3.3 with sample data
2. Add grouped product to cart _(Set of Sprite Yoga Straps)_
3. Place order
4. Login in admin section
5. Create invoice for order
6. Create credit memo for order
7. In the credit memo section click 'Send Email'

### Expected result (*)
1. Mail is send
2. No Fatal Error

### Actual result (*)
1. Mail is not send
2. Fatal Error is thrown
![image](https://user-images.githubusercontent.com/10864061/68942003-ab1da100-07a7-11ea-9e1b-3958f2f6d281.png)
```
Fatal error: Uncaught TypeError: 
Argument 1 passed to Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder::getItemPrice() must be an instance of Magento\Sales\Model\Order\Item, 
instance of Magento\Sales\Model\Order\Creditmemo\Item given, 
called in /www/magento233/vendor/magento/module-sales/view/frontend/templates/email/items/creditmemo/default.phtml 
on line 32 and defined in /www/magento233/vendor/magento/module-sales/Block/Order/Email/Items/Order/DefaultOrder.php:99 
Stack trace: 
#0 /www/magento233/vendor/magento/module-sales/view/frontend/templates/email/items/creditmemo/default.phtml(32): Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder->getItemPrice(Object(Magento\Sales\Model\Order\Creditmemo\Item)) 
#1 /www/magento233/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/ww...') 
#2 /www/magento233/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Gro in /www/magento233/vendor/magento/module-sales/Block/Order/Email/Items/Order/DefaultOrder.php on line 99
```

**When async email is enabled**
```
report.CRITICAL: Error when running a cron job 
{"exception":
"[object] (RuntimeException(code: 0): Error when running a cron job at /www/magento233/vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:330, 
TypeError(code: 0): 
Argument 1 passed to Magento\\Sales\\Block\\Order\\Email\\Items\\Order\\DefaultOrder::getItemPrice() must be an instance of Magento\\Sales\\Model\\Order\\Item, 
instance of Magento\\Sales\\Model\\Order\\Creditmemo\\Item given, 
called in /www/magento233/var/view_preprocessed/pub/static/vendor/magento/module-sales/view/frontend/templates/email/items/creditmemo/default.phtml 
on line 1 at /www/magento233/vendor/magento/module-sales/Block/Order/Email/Items/Order/DefaultOrder.php:99)"} []
```

**Bug introduced at** https://github.com/magento/magento2/pull/22265
But if you would revert this change, the mail works, but the subtotal is wrong indeed. So I think the accepted PR did some wrong fix.

**Comment by AnnaShepa** [comment] 2019-11-15 12:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-15 12:15
Hi @AnnaShepa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-15 12:15
Hi @AnnaShepa, here is your [Magento instance](https://i-25617-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25617-2-3-develop.instances.magento-community.engineering/admin](https://i-25617-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-11-15 13:57
@AnnaShepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-15 14:03
:white_check_mark: Confirmed by @AnnaShepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23209` were created

**Issue Available**: @AnnaShepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-03-11 14:34
Hi @arnoudhgz, @arnoudhgz. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-25248` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Comment by cyildirim** [comment] 2021-01-19 15:03
@magento give me 2.3-develop instance

**Comment by cyildirim** [comment] 2021-01-19 15:04
@magento give me 2.4-develop instance

**Comment by cyildirim** [comment] 2021-01-19 15:07
I am able to reproduce this issue. I'll test and update here.

**Comment by cyildirim** [comment] 2021-01-19 15:43
Couldn't reproduce on magento server. This could be related to test instances not sending any email. I'll eep here poster after i tried local and any SMTP.

**Comment by cyildirim** [comment] 2021-01-24 18:47
Bug is producable on a magento (2.4-develop) environment with a mail server. 
![image](https://user-images.githubusercontent.com/1422426/105640156-82099d80-5e8d-11eb-9e7b-5d8c4d7379ac.png)

please reopen the issue. FYI @magento @arnoudhgz

**Comment by cyildirim** [comment] 2021-01-24 20:55
Raised PR for this issue #31819

**Comment by engcom-Bravo** [comment] 2021-01-27 14:37
Hello @cyildirim, which _mail server_ are you using on your local environment?

Thank you

**Comment by cyildirim** [comment] 2021-01-27 15:55
@engcom-Bravo I used mailhog to reproduce this. But i had the same issue with Mageplaza SMTP/ AWS SES as well. Also feel free to share your thoughts in my PR here please. https://github.com/magento/magento2/issues/25617

**Comment by engcom-Bravo** [comment] 2021-01-28 10:48
@cyildirim Thank you for the quick response.

We have tried to use _Send Mail_, _Mailhog_ and _Magento 2 SMTP - AVADA_ extension.

In all cases, the email has been sent successfully 
See the screenshots from Mailhog for example

Creating Credit memo
![cre_me](https://user-images.githubusercontent.com/51680745/106126990-bff51300-6166-11eb-995d-69fe4475e775.png)

Send Email
![mail_sent](https://user-images.githubusercontent.com/51680745/106127013-c7b4b780-6166-11eb-9102-f0f912d3d958.png)

Mail received on Mailhog
![mailhog](https://user-images.githubusercontent.com/51680745/106127115-e2872c00-6166-11eb-9552-3bae6c91f093.png)

Do you have any ideas or additional information to help us to reproduce the exception error?

Thank you in advance

**Comment by cyildirim** [comment] 2021-01-28 11:02
@engcom-Bravo As far as i get it from screenshot you shared, you recieved email for order confirmation. You need to check creditmemo email. (you'll need to check "send copy of email" option while creating creditmemo). Also remember to disable async emails before to do that to see the exception right away.

**Comment by engcom-Bravo** [comment] 2021-01-28 11:51
@cyildirim Yes, we have Disabled _Asynchronous sending_ and checked the _Email copy of Credit Memo_ checkbox. Still no exception and the emails are received 
![cre_memo](https://user-images.githubusercontent.com/51680745/106134723-9d1b2c80-616f-11eb-8a2a-7b8f7660528e.gif)

**Comment by cyildirim** [comment] 2021-01-28 11:58
@engcom-Bravo your steps seem correct. I'll try it again with my local and will update here. Till then you may try to create new grouped product and try with that though. i don't expect that's the actual issue. Because i remember used a new grouped product.

**Comment by engcom-Bravo** [comment] 2021-01-28 12:09
> @engcom-Bravo your steps seem correct. I'll try it again with my local and will update here. Till then you may try to create new grouped product and try with that though. i don't expect that's the actual issue. Because i remember used a new grouped product.

Yes, already tried with a newly created Grouped product with default quantity per product(not sure if the default quantity is important). Still no error.

Thank you for the collaboration

**Comment by cyildirim** [comment] 2021-01-30 19:27
I am still able to reproduce the issue. Shared screen recording below. Steps seem pretty much the same. @engcom-Bravo 
![image](https://user-images.githubusercontent.com/1422426/106366018-3b62ea00-634a-11eb-8217-c1d1c5ba3c2d.png)

**Comment by gabrieldagama** [comment] 2021-02-01 10:48
Hi @cyildirim, I'm also not able to reproduce it locally but I've done some investigation on this. From what I could see locally with vanilla Magento installed we have the following scenario:

The Layout XML used when the email is sent is:
`app/code/Magento/GroupedProduct/view/frontend/layout/sales_email_order_creditmemo_renderers.xml`
```
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Creditmemo Items List" design_abstraction="custom">
    <body>
        <referenceBlock name="sales.email.order.creditmemo.renderers">
            <block class="Magento\GroupedProduct\Block\Order\Email\Items\CreditMemo\Grouped" name="sales.email.order.creditmemo.renderers.grouped" as="grouped" template="Magento_Sales::email/items/creditmemo/default.phtml"/>
        </referenceBlock>
    </body>
</page>
```

In this case, the block above extends `Magento\Sales\Block\Order\Email\Items\DefaultItems` that has the `getItemPrice`, but its parameter type is not specified.

```
    /**
     * Get the html for item price
     *
     * @param OrderItem|InvoiceItem|CreditmemoItem $item
     * @return string
     * @throws LocalizedException
     */
    public function getItemPrice($item)
    {
        $block = $this->getLayout()->getBlock('item_price');
        $item->setRowTotal((float) $item->getPrice() * (float) $this->getItem()->getQty());
        $item->setBaseRowTotal((float) $item->getBasePrice() * (float) $this->getItem()->getQty());
        $block->setItem($item);
        return $block->toHtml();
    }
```

Can you debug your case and provide more details? Maybe there is something else we are missing here. Thanks.

**Comment by cyildirim** [comment] 2021-02-01 11:24
Hi @gabrieldagama , 

I've already raised a PR to solve this there is a discussion around that as well. I appriciate if you can share your ideas in there as well. https://github.com/magento/magento2/pull/31819.  

As far as i can see in the code base it extends `\Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder` not `Magento\Sales\Block\Order\Email\Items\DefaultItems`. Am i missing something here ?

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/GroupedProduct/Block/Order/Email/Items/Order/Grouped.php

**Comment by engcom-Bravo** [comment] 2021-02-01 11:24
Hello @cyildirim thank you for the provided attachment.

From what I can see is that you are using Magento 2.3.5.
We have rechecked this issue on Magento 2.3.5-p1 on the Turkish locale and indeed, the issue is reproducible. Please see the attachments
![mail_server_error_500](https://user-images.githubusercontent.com/51680745/106451582-74f13d80-648f-11eb-8e56-61989bf68655.png)
![mail_server_error_source](https://user-images.githubusercontent.com/51680745/106451600-77539780-648f-11eb-87b9-79aa4ebb418f.png)

However, the issue is **not reproducible on the latest 2.4-develop** on the same machine, with the same steps and settings: locale, currency, products, user address...

Are you sure that you have been able to reproduce the issue on the latest 2.4-develop?

Thank you

**Comment by cyildirim** [comment] 2021-02-01 11:28
@engcom-Bravo ok my bad. i am using 2.3.5. I'll make sure it's not happening on 2.4 and will update here. 
```
"magento/product-community-edition": "2.3.5",
```

**Comment by cyildirim** [comment] 2021-02-01 11:36
Sharing for referenece. this issue is already fixed in here https://github.com/magento/magento2/pull/26246

**Comment by gabrieldagama** [comment] 2021-02-01 11:39
Thanks for following up on it @cyildirim! I will be closing this issue and the PR opened to fix it.

**Closed as completed by gabrieldagama** 2021-02-01 11:39 UTC
Labels: Partner: MediaCT, Component: Email, Priority: P2, Progress: done, Issue: ready for confirmation
