### ISSUE TITLE
Dropdown attribute required "no" gets automatically in new product and cannot be removed

### ISSUE THREAD

**Issue by arredod** [magento/magento2#4993] opened 2016-06-13 09:01 UTC
1. Dropdown attribute with Values Required "no" is created and not assigned to default products
2. a new product is created with the "default" attribute

Expected result
1. product should not have that actual attribute

Actual result
1. the product has the attribute and cannot be modified

**Comment by antboiko** [comment] 2016-06-14 12:06
Hi @arredod , could you please provide more detailed steps to reproduce this issue? What Magento version are you using?

Thanks,
Anton.

**Comment by arredod** [comment] 2016-06-14 12:38
Magento ver. 2.0.7
I created a few attributes with dropdown as input type, value "not required". Those attributes are not assigned to the _default_ group of attributes.
When I create new default products they get automatically those attributes. I can see the attributes assigned on frontend filter and also on backend if I display the attribute column.

![a1](https://cloud.githubusercontent.com/assets/19904060/16042914/682f64f2-323d-11e6-99f5-21e327ca3ba7.jpg)
![a2](https://cloud.githubusercontent.com/assets/19904060/16042913/68291d40-323d-11e6-91f0-c22ff2fae3e2.jpg)
![a3](https://cloud.githubusercontent.com/assets/19904060/16042912/6825d040-323d-11e6-8850-d7fc4f12f465.jpg)
![a4](https://cloud.githubusercontent.com/assets/19904060/16042911/682256e0-323d-11e6-91d9-3f16c4323944.jpg)

**Comment by antboiko** [comment] 2016-06-14 12:57
@arredod thanks for the details. Could you please tell me if the product Tavolo Assolo should have that attribute Larghezza Bagno? 

Thanks,
Anton.

**Comment by arredod** [comment] 2016-06-14 13:07
no, it shouldn't

**Comment by antboiko** [comment] 2016-06-14 14:05
@arredod I cannot reproduce the issue on develop branch. 
- I created new attribute with input type "Dropdown" - "Dropdown Test"
- Didn't assign it to any Attribute Set
- I have the column Dropdown Test appeared in Product grid, and there are empty cells for all products. If you don't want to have it in Product grid check these options for Product Attribute and set "No":
  ![dropdown_test](https://cloud.githubusercontent.com/assets/15442705/16045175/fe257dfe-324f-11e6-9855-522930da39f2.png)
- I created new product based on Default attribute set
- I checked, it doesn't have new attribute "Dropdown Test" as it wasn't added to the Default attribute set

As I see on your 3rd screenshot (Product Grid), the product Tavolo Assolo has another attribute set "Tavoli". Please check if your new dropdown attribute "Larghezza Bagno" is added to "Tavoli" attribute set. If yes, then this is correct behavior and it's correct that you have the value in the grid for Tavolo Assolo. 
Also, if you don't want this column "Larghezza Bagno" to be featured on product grid just refer to my 3rd step above.

Best,
Anton.

**Comment by pboisvert** [comment] 2016-06-18 06:20
@antboiko please close if not reproducible and no further action here in terms of investigation

**Comment by arredod** [comment] 2016-08-23 13:51
actually there's still an issue with attributes because even if they're unassigned to a certain attribute set they appear as a category filter on frontend

**Comment by antboiko** [comment] 2016-08-25 13:07
Hi @arredod , I cannot reproduce this issue. Please check the options you specified for the Storefront under the specific attribute.

**Comment by veloraven** [comment] 2016-09-12 07:28
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.

**Closed as completed by veloraven** 2016-09-12 07:28 UTC
Labels: Progress: needs update
