### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated on google-shopping-ads

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#25986] opened 2019-12-11 09:18 UTC
### Preconditions (*)
1. Magento 2.3.1, 2.3.2
2. Install magento google shopping ads channel

### Steps to reproduce (*)
1. Install magento/google-shopping-ads 
2. Navigate to the Marketing -> Google Shopping Ads section 
3. Use google chrome 
4. Open console.log
5. The following error appears
```

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
startGoogleReactAppLoading @ loader.js:23
(anonymous) @ (index):361
load (async)
(anonymous) @ (index):360

loader.js:47 Uncaught TypeError: Cannot read property 'test' of undefined
    at XMLHttpRequest.xhr.onload (loader.js:47)
    at startGoogleReactAppLoading (loader.js:75)
    at (index):361
```

I can't seem to replicate on firefox although it has happened there a few times with the following error 

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
TypeError: injectionOrder[i].pattern is undefinedloader.js:47:21
    onload https://channels.magento.com/loader.js:47
    startGoogleReactAppLoading https://channels.magento.com/loader.js:75
    <anonymous> https://www.airblock.gr/admin_ioweb/scconnector/index/index/key/d48aaf610819ae7eb1144da5aa2dc4f20ec2b0627460d4d5e7d2ce247b3626f9/#/:361
```

### Expected result (*)
1. The google shopping ads page renders correctly

### Actual result (*)
1. The page appears to be broken 

![image](https://user-images.githubusercontent.com/20220341/70607848-dc06bf80-1c07-11ea-9ff6-574b0c8fc410.png)

**Comment by engcom-Echo** [comment] 2019-12-11 09:57
Hello @ioweb-gr 


Issue is already open
You can review the conversation at
I am closing this issue as a duplicate of #[25506](https://github.com/magento/magento2/issues/25506), because i prefer to confirm 25506(this issue includes more clear description).

**Comment by engcom-Echo** [comment] 2019-12-11 10:01
Hello @ioweb-gr 

Thank you for your report and collaboration!
Issue is already open
You can review the conversation at #[25506](https://github.com/magento/magento2/issues/25506)

**Comment by ioweb-gr** [comment] 2019-12-11 10:02
Great. I'm happy that the issue is known. I just couldn't find it via search because all the messages were in screenshots.

**Closed as completed by engcom-Echo** 2019-12-11 10:01 UTC
Labels: duplicate, Issue: Format is valid, Component: Bundled Extension
