### ISSUE TITLE
Static content is deploying for disabled modules

### ISSUE THREAD

**Issue by shkodasv** [magento/magento2#24666] opened 2019-09-20 09:20 UTC
### Summary (*)
- Original summary from the reporter : 

> I disable module output for several modules (e.g Checkout, GiftRegestry) and would like to know how to exclude CSS related to these modules from styles-l/styles-m files? As I don't need to load extra CSS

### Preconditions (*)
- reproduced on `2.3-develop`

### Steps to reproduce (*)
1. Setup vanilla 2.3-develop installation
2. Take a look at the file `app/design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less`, notice the selector `.payment-method-braintree` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Braintree` module in the 
`Magento/Blank` theme.
3. Now disable that module (and its dependency): `bin/magento module:disable Magento_Braintree Magento_BraintreeGraphQl`
4. Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
5. Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/blank en_US`
6. Look at the generated file `pub/static/frontend/Magento/blank/en_US/css/styles-m.css`

### Expected result (*)
- Not finding a reference to the selector `.payment-method-braintree`

### Actual result (*)
- Finding references to the selector `.payment-method-braintree`

*Update*: In hindsight, @shkodasv is talking about the deprecated "disabling module output" feature of Magento which was removed in Magento 2.2 I believe. But the issue is still valid for disabled modules as well, or should we open a new issue then?

**Comment by engcom-Bravo** [comment] 2019-09-20 09:25
Hello @shkodasv. Thanks for applying, but the GitHub issue tracker is intended for Magento Core technical issues only. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Comment by hostep** [comment] 2019-09-20 19:13
@shkodasv: I think you have a very valid point here.

@engcom-Bravo: in my opinion this is a bug and I'll re-open this ticket for now, feel free to discuss if you don't agree.

### Steps to reproduce:
- Setup vanilla 2.3-develop installation
- Take a look at the file `app/design/frontend/Magento/blank/Magento_Braintree/web/css/source/_module.less`, notice the selector `.payment-method-braintree` is in there and also notice this selector is in no other file in the Magento source code except for this file in the `Magento_Braintree` module in the 
`Magento/Blank` theme.
- Now disable that module (and its dependency): `bin/magento module:disable Magento_Braintree Magento_BraintreeGraphQl`
- Remove potential left over files: `rm -R var/view_preprocessed/* pub/static/*`
- Run static content deploy: `bin/magento setup:static-content:deploy -f --theme Magento/blank en_US`
- Look at the generated file `pub/static/frontend/Magento/blank/en_US/css/styles-m.css`

### Expected result:
- Not finding a reference to the selector `.payment-method-braintree`

### Actual result:
- Finding references to the selector `.payment-method-braintree`

*Update*: In hindsight, @shkodasv is talking about the deprecated "disabling module output" feature of Magento which was removed in Magento 2.2 I believe. But the issue is still valid for disabled modules as well, or should we open a new issue then?

**Comment by engcom-Bravo** [comment] 2019-09-20 20:35
Ok @hostep, I'll check it.

**Comment by shkodasv** [comment] 2019-09-20 20:44
@hostep Thanks for your reply. You are right "Disable module output" is deprecated. I didn't know it. But in case of disabling the module the same logic should work IMHO - no css should be included.

**Comment by engcom-Charlie** [comment] 2019-09-23 08:04
Hello @shkodasv !
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/), for advice or general discussion about this issue.

**Comment by engcom-Bravo** [comment] 2019-09-23 08:18
@hostep I reproduced the behavior following the steps You have provided. But I still better question my Lead on it before confirming the issue. Hopefully tomorrow I'll be back with the result.

**Comment by sdzhepa** [comment] 2019-09-26 20:23
Hello @shkodasv  @hostep @engcom-Bravo

Finally, I have received a response from the internal team and confirmation that it is a bug. Previously were several concerns probably it was by design or so.

I will update Issue title and content based on test steps from https://github.com/magento/magento2/issues/24666#issuecomment-533676872

**Comment by magento-engcom-team** [comment] 2019-09-26 20:30
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-09-26 20:33
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-20509` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rganzhuyev** [comment] 2019-09-27 08:23
@magento I'm working on it.

**Comment by vasilii-b** [comment] 2021-02-15 15:42
Hey guys,
Until the PR in the core gets merged, feel free to use the approach described [here](https://github.com/vasilii-b/magento2-frontend-improvements).

cc @shkodasv

**Closed as completed** 2024-07-14 04:11 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Deploy, Component: Css, Reproduced on 2.4.x, Priority: P2, Severity: S2, Triage: Done, Progress: done, Area: UI Framework
