### ISSUE TITLE
Readiness Check - Could not parse version constraint 5.5.22-1~dotdeb.1

### ISSUE THREAD

**Issue by technolabtips** [magento/magento2#1081] opened 2015-03-06 17:14 UTC
Hi,
With Debian 7.8 , Nginx & PHP 5.5.22, the Readiness Check failed.

/mnt/hgfs/magento2/magento2/vendor/composer/composer/src/Composer/Package/Version/VersionParser.php(237): Composer\Package\Version\VersionParser->parseConstraint('5.5.22-1~dotdeb...')
#1 /mnt/hgfs/magento2/magento2/setup/src/Magento/Setup/Controller/Environment.php(69): Composer\Package\Version\VersionParser->parseConstraints('5.5.22-1~dotdeb...')
#2 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractActionController.php(83): Magento\Setup\Controller\Environment->phpVersionAction()
#3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#5 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Controller/AbstractController.php(117): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/DispatchListener.php(114): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-eventmanager/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /mnt/hgfs/magento2/magento2/vendor/zendframework/zend-mvc/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /mnt/hgfs/magento2/magento2/setup/index.php(25): Zend\Mvc\Application->run()
#13 {main}

**Comment by buskamuza** [comment] 2015-03-06 17:36
Hi @technolabtips , this issue has already been fixed internally and it should be available with the next release (should be today).

**Comment by mazhalai** [comment] 2015-03-06 17:37
Duplicate of #1066

**Comment by mazhalai** [comment] 2015-03-06 19:53
This issue has been fixed in 0.42.0-beta11
Thank you for reporting the issue.

**Closed by mazhalai** 2015-03-06 19:53 UTC

**Comment by technolabtips** [comment] 2015-03-09 14:25
@mazhalai OK.Thanks.
