### ISSUE TITLE
Disabling product variation with Actions dropdown doesn't work 

### ISSUE THREAD

**Issue by Cyrus180** [magento/magento2#9950] opened 2017-06-14 18:04 UTC
### Preconditions

1. Magento 2.1.3
2. Apache 2.4.25
3. PHP 7.0.19
4. MySQL 10.1.24

### Steps to reproduce

1.  Edit a configurable product.
2.  Scroll down to the Configurations.
3.  Click on Select -> Disable in the Actions column on one of the variations.
4. Click on Save.

### Expected result

1.  The variation should be disabled.

### Actual result

1. The variation is still enabled. It is enabled again in the backend and it is also enabled in the frontend.

#### Screenshots

1. Select and disable variation.
![magento_bug_variations_01](https://user-images.githubusercontent.com/4700269/27147242-571e2a76-513c-11e7-9f70-2801c0c59886.png)

2. Variation is shown as disabled.
![magento_bug_variations_02](https://user-images.githubusercontent.com/4700269/27147246-5bc1d71c-513c-11e7-9b7b-aa7f87f86f56.png)

3. After saving the variation is enabled again.
![magento_bug_variations_03](https://user-images.githubusercontent.com/4700269/27147249-5f9f4928-513c-11e7-8d6f-8ee806499d9b.png)

**Comment by smoskaluk** [comment] 2017-06-23 08:45
Internal ticket MAGETWO-70132 is created

**Comment by gediminaskv** [comment] 2017-08-24 10:16
I think this may be due to Store Views. When I disable product on "All Store Views" scope it doesn't necessarily disable the product on my particular store views. It just sets a default value for a product. 

If my product doesn't use default value on particular store view then the default value has no influence. You have to set the value by editing the variation on particular store view. Or set the product to use a default value. Just then the product/variation of a configurable product is disabled.

**Comment by poochie2** [comment] 2017-09-26 16:39
Just a note, my 2.1.5 installation has the same issue, but if I edit the Enabled flag right after using "Edit Configurations" and before saving, the issue does not persist and my dropdown values in frontend are correctly populated.

**Comment by magento-engcom-team** [comment] 2017-09-27 22:01
@Cyrus180, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-27 22:01 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Format is valid
