### ISSUE TITLE
Massaction in backend grid with select all does not work correctly

### ISSUE THREAD

**Issue by sydekumf** [magento/magento2#2778] opened 2015-12-21 21:06 UTC
Choose any backend grid and select all items available. Do a mass action. The affected number of results is not the same as number of entities available in the grid. I know there are actions which do not affect every entity, but I tested with neutral mass actions which certainly do affect all entities. I also tested it in my own module, it does not work either. Some javascript is not sending the correct entity ids to the server.
<img width="493" alt="bildschirmfoto 2015-12-21 um 22 03 19" src="https://cloud.githubusercontent.com/assets/3983052/11941356/0fbb0274-a82f-11e5-998a-00121f6ca3ae.png">

**Comment by NadiyaS** [comment] 2015-12-22 11:47
Hi @sydekumf ,
thanks for reporting this. Internal issue was created MAGETWO-47207

**Comment by sydekumf** [comment] 2016-01-22 18:29
Any news on that? How do know when this is fixed?

**Comment by ajpevers** [comment] 2016-03-24 09:37
Additionally, when you select all invoices of one order in the order detail page of the admin and apply a mass action to it, the mass action is applied on all invoices in the whole system. This is because the context of the order_id gets lost in the mass action.

vendor/magento/module-sales/view/adminhtml/ui_component/sales_order_view_invoice_grid.xml:
```xml
                    <item name="filter_url_params" xsi:type="array">
                        <item name="order_id" xsi:type="string">*</item>
                    </item>
```

This part of the code would filter only invoices of this order_id, but the order_id param is absent in the mass action POST/GET:

Request: http://magento2.dev/sitemanager/sales/invoice/pdfinvoices/key/57643a9c1297d88c9998a26eb46af31d1f36540631c3f81a4a231564f70ecfff/

Request payload:
```
------WebKitFormBoundary776fKNJgSVASkucJ
Content-Disposition: form-data; name="excluded"

false
------WebKitFormBoundary776fKNJgSVASkucJ
Content-Disposition: form-data; name="filters[placeholder]"

true
------WebKitFormBoundary776fKNJgSVASkucJ
Content-Disposition: form-data; name="search"


------WebKitFormBoundary776fKNJgSVASkucJ
Content-Disposition: form-data; name="namespace"

sales_order_view_invoice_grid
------WebKitFormBoundary776fKNJgSVASkucJ
Content-Disposition: form-data; name="form_key"

Ta4dxuMGnvF5q04Y
------WebKitFormBoundary776fKNJgSVASkucJ--
Name
```

To replicate this, open an order, go to invoices, select all and choose the Export PDF mass action:

![screen shot 2016-03-24 at 10 32 22](https://cloud.githubusercontent.com/assets/1489129/14013273/e3ac7c50-f1ab-11e5-949b-d11dd592fd81.png)

![screen shot 2016-03-24 at 10 32 52](https://cloud.githubusercontent.com/assets/1489129/14013276/e97dd62e-f1ab-11e5-91ad-f2abb246f112.png)

[invoice2016-03-24_09-32-57.pdf](https://github.com/magento/magento2/files/187529/invoice2016-03-24_09-32-57.pdf)

**Comment by LucScu** [comment] 2016-05-11 09:28
Is this issue fixed in last release?

**Comment by lucscu** [comment] 2016-05-12 06:53
In magento 2.0.5 it seems fixed.
Please update ufficially this issue.

**Comment by mbrinton01** [comment] 2016-06-11 05:51
@sydekumf I can no longer reproduce this issue.  Please reopen the issue if you are able to reproduce it and provide the version you are using.

**Closed as completed by mbrinton01** 2016-06-11 05:51 UTC
Labels: Issue: Ready for Work, bug report
