### ISSUE TITLE
Category Banner Image is distorted or broken if the image is not available in media directory.

### ISSUE THREAD

**Issue by Rakhi161** [magento/magento2#35088] opened 2022-02-11 11:19 UTC
**Preconditions (*)**
 Magento 2.4.3-p1
 
**Steps to reproduce (*)**
1. From backend upload category image from Catalog -> Category -> open any category -> go to content -> Category Image and Save it.
2. Delete the same image from pub/media/catalog/category folder.
3. Now if you check in frontend category page the broken image will shown which is not correct.

**Expected result (*)**
 The broken image will not shown.
 
 **Actual result (*)**
 The broken image showing which is not correct.

**Comment by Rakhi161** [comment] 2022-02-11 11:26
@magento I am working on this

**Comment by engcom-Hotel** [comment] 2022-02-14 09:03
Hello @Rakhi161,

We have gone through with the description and tried to reproduce the issue in Magento 2.4-develop branch but it seems that this is expected behavior. Because we are deleting something directly from the server.

Thanks

**Comment by engcom-Hotel** [comment] 2022-02-28 06:38
Dear @Rakhi161,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-28 06:38 UTC
Labels: Priority: P3, Progress: done, Issue: needs update
