### ISSUE TITLE
Product price always be removed in every 3 digits/thousand

### ISSUE THREAD

**Issue by lombokindustries** [magento/magento2#17010] opened 2018-07-23 07:19 UTC
Hi Masters.

I am using magento 2.1.10, and using IDR(Rp.) as currency, I have an issue in product price, for example:
I input Rp.2000000 then save -> Rp. 2,000,000 .. the problem come when I update or save it for the 2nd time, the price is going to be Rp. 2
I input Rp.2500000 -> Rp.2,500,000.. when update -> Rp.2,5
Only price I never changed, it changed by itself..

**Comment by magento-engcom-team** [comment] 2018-07-23 07:19
Hi @lombokindustries. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@lombokindustries do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-23 08:01
Hello @lombokindustries, thank you for your report. I cannot reproduce this issue.
![peek 2018-07-23 11-03](https://user-images.githubusercontent.com/40755810/43064502-c592c2e6-8e67-11e8-912a-07f05e93fb08.gif)

Could you please correct my steps or add more details to this issue?

**Comment by lombokindustries** [comment] 2018-07-23 10:01
Yes, like that. but in my case when I save it in the 2nd time, those 6 zero automatically removed, to be IDR 2.. I have no idea which module that should be fixed.

**Comment by lombokindustries** [comment] 2018-07-23 10:20
the first issue from Currency format is like 2,000,000,00. Decimal using ,00 not .00, so I removed it using Lilik PriceDecimal Modul.. maybe this is the bug. I also tested this case in magento 2.2.5, everything's fine like your demo.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-23 10:45
@lombokindustries, thank you for feedback. I'm closing this issue as GitHub issue tracker is intended for Magento Core technical issues only.
If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-backlog-nickolas** 2018-07-23 10:45 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is not valid
