### ISSUE TITLE
Default zip code error

### ISSUE THREAD

**Issue by atsareva** [magento/magento2#8962] opened 2017-03-21 13:25 UTC
Hi!

### Preconditions
1. Magento 2.1.5 CE (clear version)

### Steps to reproduce
1. Go to Stores Configuration -> Sales -> Tax -> Default Tax Destination Calculation
2. Set some value to 'Default Post Code' field (e.g 12345)
3. Go to checkout page (1 step) and select Ireland country. You shouldn't set zip code for this country, so leave it empty.
4. Go to the second step on the checkout and you will get 12345 zip (default zip code from tax) code there
5. If you return to the previous step, zip code will be still empty

### Actual result
1. Screenshots has been attached
![checkout_first_step](https://cloud.githubusercontent.com/assets/1243876/24149190/4be9d464-0e4a-11e7-9a94-6d077bb2ff57.png)
![checkout_second_step](https://cloud.githubusercontent.com/assets/1243876/24149191/4c326134-0e4a-11e7-852a-a0ac56245418.png)

Thank you,
Alona Tsarova

### Expected result
TBD

**Comment by dolmeta** [comment] 2017-03-21 14:19
I have a similar problem with a custom attribute.

To reproduce : 
- Create attribute "status" as select type, with a default value
- Create address in checkout
- Check the database => the default value is not set

**Comment by sdzhepa** [comment] 2017-03-23 14:05
@atsareva, @dolmeta  Thank you for reporting this issue. We have created an internal ticket `MAGETWO-66627` to fix the problem.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:56
@atsareva, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:56 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
