### ISSUE TITLE
Trim whitespace on SKU when saving product

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#16572] opened 2018-07-05 23:55 UTC
### Preconditions

Magento 2.2

### Steps to reproduce

Save or update product in admin with a space at beginning or end.

### Expected result

Trim excessive whitespace at beginning and end of SKU

### Actual result

Whitespace SKU saved in DB.

### The actual problem

When you accidentally save a product with whitespaced SKUs it can become a future problem when syncing data, importing images, or any other process because the SKU was correct but a space was accidentally added.

When doing syncing you could end up with duplicate products with good inventory systems that actually trim the SKU.

The GUI text field itself is padded which can lead to store managers not noticing an accidental extra space.

Is there an applicable real world reason for a space at the beginning of an SKU (and the end)? Why is it allowed?

**Comment by magento-engcom-team** [comment] 2018-07-05 23:55
Hi @Zyles. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Zyles do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-06 07:35
Hello @Zyles, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by wstnbrg** [comment] 2018-10-06 09:29
#squashtoberfest

**Comment by magento-engcom-team** [comment] 2018-10-06 09:29
@wstnbrg thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by wstnbrg** [comment] 2018-10-06 09:31
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-10-06 09:31
Hi @wstnbrg. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-10-06 09:32
Hi @wstnbrg, here is your [Magento instance](https://i-16572-2-3-develop.engcom.dev.magento.com).
Admin access: [https://i-16572-2-3-develop.engcom.dev.magento.com/admin](https://i-16572-2-3-develop.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by sidolov** [comment] 2018-10-27 10:17
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#18019 by @bartoszkubicki in 2.3-develop branch
Related commit(s):
 - [6c168dd9ced1f3eb141b01dc8091319b474811a6](https://github.com/magento/magento2/commit/6c168dd9ced1f3eb141b01dc8091319b474811a6)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment] 2018-10-29 17:20
Hi @Zyles. Thank you for your report. 
The issue has been fixed in magento/magento2#18862 by @gelanivishal in 2.2-develop branch
Related commit(s):
 - [109a27eb8bd2e5b8f37fcb84ef4c0d19490a5e16](https://github.com/magento/magento2/commit/109a27eb8bd2e5b8f37fcb84ef4c0d19490a5e16)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-10-29 17:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, good first issue, Event: squashtoberfest

**Comment by Zyles** [comment] 2018-10-29 17:52
Good, thank you.
