### ISSUE TITLE
The subcategories are not expandable via Android (Samsung Internet App)

### ISSUE THREAD

**Issue by in-session** [magento/magento2#34779] opened 2021-12-09 08:05 UTC
### Preconditions (*)

Can be tested in a test instance

### Steps to reproduce (*)

1. Create a test instance and open it via Andoid Internet App
2. Open the main menu and try, for example, to collapse the woman submenu.

### Expected result (*)

![Ashampoo_Snap_Donnerstag, 9  Dezember 2021_09h03m32s_010_](https://user-images.githubusercontent.com/16542619/145357489-4def51c8-7817-4c35-920a-b41b8159a170.png)

**Comment by engcom-Hotel** [comment] 2021-12-16 08:16
Hi @in-session,

Thank you for reporting the issue.

Verified the issue and is reproducible on the 2.4-develop instance.

Below are the steps which I followed to reproduce this:

1. Open frontend started Chrome Mobile Emulator.
2. The first time, the left menu is working as expected.
3. From the menu, click on the Women section or any section.
4. Once the clicked section page loaded, clicked on the left menu again to expand any dropdown tab but not a single tab was getting expanded.

Below is the screenshot of the same:
![image](https://user-images.githubusercontent.com/51681618/146333604-f94f811a-05bd-4516-8651-82bcc28eb62b.png)

Tried on multiple instances and the issue is there. So based on it, confirming the issue.

Thanks

**Comment by dphilipps** [comment] 2022-08-15 15:00
Also not working on Android Chrome with Magento 2.4.5

**Comment by Bashev** [comment] 2022-08-19 10:49
@magento give me instance

**Comment by MakoWish** [comment] 2023-01-07 15:27
This appears to have regressed in 2.4.4, but I am using Firefox for Android. I also tried Chrome for Android with the same issue. I can see the caret change directions and back immediately, so it does seem like the open and close events are triggering at the same time. I noticed it on my custom theme, but switching to Magento Blank or Magento Luma as a test did not fix the issue.

**Comment by MakoWish** [comment] 2023-01-07 15:46
The workaround posted in [#35329 (comment)](https://github.com/magento/magento2/issues/35329#issuecomment-1139618176) seems to have resolved it for me, but I understand this workaround will be overwritten with any updates and would have to be applied again. This issue was first reported more than a year ago, and there is still no official fix yet?? 😮

**Comment by cptX** [comment] 2023-02-24 09:04
> The workaround posted in [#35329 (comment)](https://github.com/magento/magento2/issues/35329#issuecomment-1139618176) seems to have resolved it for me, but I understand this workaround will be overwritten with any updates and would have to be applied again. This issue was first reported more than a year ago, and there is still no official fix yet?? 

Unfortunately doesn't work for me in 2.4.5 with Luma theme!

**Comment by engcom-Bravo** [comment] 2024-09-06 06:20
Hi @in-session,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/issues/35329#issuecomment-1628792240 issue is no more reproducible.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-06 06:20 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x, Area: UI Framework
