### ISSUE TITLE
Design issue in minicart item remove confirmation modal.

### ISSUE THREAD

**Issue by saumya1998** [magento/magento2#30452] opened 2020-10-12 10:11 UTC
Design issue in minicart item remove confirmation modal.

### Preconditions (*)
1.magento version - magento2-2.4-develop
2.php version - PHP 7.4.11
3.view - mobile view

### Steps to reproduce (*)
1) open magento base url.
2) open product and add to cart
3) now open minicart in top right corner.
4) click on delete button side to edit button
5) check the modal content design in mobile view. 

### Expected result (*)
![Screenshot_2020-10-12_15-29-53](https://user-images.githubusercontent.com/50991251/95734599-4e6d8380-0ca1-11eb-997a-a26f38b0e62d.png)

### Actual result (*)
![Screenshot(16)](https://user-images.githubusercontent.com/50991251/95734615-53cace00-0ca1-11eb-95f4-92cf0c6064da.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by saumya1998** [comment] 2020-10-12 10:11
#dmcdindia2020

**Comment by ajijshekh123** [comment] 2020-10-12 10:48
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-10-12 11:01
Hi @saumya1998,
I have verified the issue in iPhone X (375*812) and iPhone 6/7/8 (414*736) size but not able to reproduce the issue.
PFA:
![image](https://user-images.githubusercontent.com/24711761/95739243-27ff1680-0ca8-11eb-85af-c84cf1a92ab0.png)

![image](https://user-images.githubusercontent.com/24711761/95739272-2fbebb00-0ca8-11eb-9758-75ea8701ae69.png)

Can you please update me on which size you are facing the issue?

Thanks.

**Comment by saumya1998** [comment] 2020-10-12 11:03
@ajijshekh123 
![Screenshot_2020-10-12_16-32-33](https://user-images.githubusercontent.com/50991251/95739514-95ab4280-0ca8-11eb-8b40-4368f9c09ed8.png)
i am checking on Galaxy s5 (360x640)

**Comment by ajijshekh123** [comment] 2020-10-12 11:10
Hi @saumya1998,
I think this is not an issue. Popup UI content size depends on the device. Please update me your concern.
**PFA:**
![image](https://user-images.githubusercontent.com/24711761/95740057-7bbe2f80-0ca9-11eb-9165-e1f4681acd28.png)

Thanks.

**Comment by saumya1998** [comment] 2020-10-12 11:18
@ajijshekh123 , if you will check form code there is issue, like both left and right padding should be same but now, the right padding is 7rem and left padding is 3 rem. this is why the content is align with left side in mobile view. if both side padding will be same then the content will show aligned equally from both sides.

**Comment by ajijshekh123** [comment] 2020-10-12 11:20
Okay @saumya1998, Thanks for the update. Let me verify the issue. You can proceed with your work after confirming the issue.

**Comment by magento-engcom-team** [comment] 2020-10-12 11:22
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-38347` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saumya1998** [comment] 2020-10-12 11:23
I am working on this issue.

**Comment by niravkrish** [comment] 2020-10-12 16:41
@magento I am working on this

**Comment by saumya1998** [comment] 2020-10-13 05:09
@magento-admin i am working on this

**Comment by mrtuvn** [comment] 2020-10-13 09:21
https://media.giphy.com/media/uiC01xg33xOqb6QxrA/giphy.gif
slow down guys 👍

**Comment by mrtuvn** [comment] 2020-10-13 09:24
take it easy guys :)

**Comment by magento-engcom-team** [comment] 2020-10-16 13:35
Hi @saumya1998. Thank you for your report. 
The issue has been fixed in magento/magento2#30458 by @niravkrish in 2.4-develop branch
Related commit(s):
 - [daf0dc67926bde5de6e05f956ff0b09756ed0123](https://github.com/magento/magento2/commit/daf0dc67926bde5de6e05f956ff0b09756ed0123)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-10-16 13:35 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Component: Ui, Area: Design/Frontend, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S4, Priority: P4, Progress: done, Event: dmcdindia2020, Reported on 2.4.0
