### ISSUE TITLE
Last Compared Products widget not displayed

### ISSUE THREAD

**Issue by cduperron** [magento/magento2#7722] opened 2016-12-08 10:15 UTC
### Preconditions

1. Magento 2.0.7

### Steps to reproduce

1. Create a new CMS page
2. Insert the Last Compared Products widget inside
3. Compare two products in front-office by clicking on the compare button
4. Go to the CMS page which contains the widget

### Expected result

1. Last Compared Products widget is displayed in front-office into the CMS page

### Actual result

1. Nothing is displayed

**Comment by faducrocq** [comment] 2017-01-04 10:22
Hi @veloraven ,

Have you find anything to fix this bug ?

Thanks,

**Comment by faducrocq** [comment] 2017-01-30 15:54
Hi @veloraven ,

Do you have some news about this bug ?

Thanks,

Fanny

**Comment by faducrocq** [comment] 2017-03-07 09:56
Hi @veloraven ,

Do you have some news about this bug ?

Thanks,

Fanny

**Comment by faducrocq** [comment] 2017-03-21 09:50
Hi @veloraven ,

Do you have some news about this bug ?

Thanks,

Fanny

**Comment by jonathansayag** [comment] 2017-04-27 09:01
Hi,

I've the same problem on Magento 2.1.4. Did you find something for the issue ?

Regards

**Comment by veloraven** [comment] 2017-06-19 08:37
@cduperron thank you for your report but I'm closing this issue as it's not a bug.
Products will get to the widget as soon as you delete them from compare products list. If you need this functionality to work in other way please submit your improvement to  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

**Closed as completed by veloraven** 2017-06-19 08:37 UTC
Labels: bug report, Component: Cms
