### ISSUE TITLE
From wishlist to shopping cart not adding without product options. Specify the required product option (s) error.

### ISSUE THREAD

**Issue by Sonal824** [magento/magento2#13857] opened 2018-02-27 08:07 UTC
### Preconditions

1. Magento V : 2.1.9
2.  PHP V: 7.0.27

### Steps to reproduce

1.  Clicked on add to wishlist from product detail page.  
2.  Product is added in wishlist.
3.  Now when i click on add to cart button from wishlist. cart showing error message "Specify the required product options."

### Expected result

1. while adding product in wishlist it should ask for product options like size or color.

### Actual result

1.  Error Message : Specify the required product option (s). and not adding to cart.

So, I need to make the “Add to Wishlist” behave exactly like “Add to Cart”. The other benefit of doing so (asking user to choose configurable options while adding to wishlist) is that when you move the wishlist item (configurable product) to cart then it will directly go to cart without returning back to product page asking to select options.

**Comment by magento-engcom-team** [comment] 2018-02-27 08:24
Duplicate of #13856.

**Closed as completed by magento-engcom-team** 2018-02-27 08:24 UTC
Labels: Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2018-02-27 08:25
@Sonal824, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
