### ISSUE TITLE
DHL shipping not working

### ISSUE THREAD

**Issue by polcarrasco** [magento/magento2#25602] opened 2019-11-14 12:51 UTC
### Preconditions (*)

Magento 2.3.3 & 2.3-develop

### Steps to reproduce (*)

1. Configurate module DHL 
![Screenshot from 2019-11-15 14-25-31](https://user-images.githubusercontent.com/51681435/68943444-e2924a80-07b3-11ea-8c6e-da3e09975a3a.png)
![Screenshot from 2019-11-15 14-26-23](https://user-images.githubusercontent.com/51681435/68943471-f9d13800-07b3-11ea-83cc-a5b3b5fb83f9.png)
![Screenshot from 2019-11-15 14-26-56](https://user-images.githubusercontent.com/51681435/68943501-0c4b7180-07b4-11ea-9870-a9d394e85afb.png)
![Screenshot from 2019-11-15 14-27-50](https://user-images.githubusercontent.com/51681435/68943557-2d13c700-07b4-11ea-9b00-9547f3693b41.png)
2. Add some product to cart
3. Proceed to Checkout

### Expected result (*)
DHL rate is shown
![Screenshot from 2019-11-15 14-41-54](https://user-images.githubusercontent.com/51681435/68944297-30a84d80-07b6-11ea-8797-d7cfb56cc6ed.png)

### Actual result (*)
DHL not showing a price for the shipping and showing a message about the problem. See shipping log.
![Screenshot from 2019-11-15 14-28-49](https://user-images.githubusercontent.com/51681435/68943612-50d70d00-07b4-11ea-9391-618aa47f8fd0.png)
![Screenshot from 2019-11-15 14-29-51](https://user-images.githubusercontent.com/51681435/68943680-83810580-07b4-11ea-8feb-cc82c615177a.png)

**Comment by polcarrasco** [comment] 2019-11-14 17:03
The issue has been consulted to a programmer and DHL technical team. Both have not been able to fix it, but the information I have told in here is ok: Magento 2.3.3, DHL extension 100.3.3, configuration is ok, credentials are ok, result is DHL not showing a price for the shipping and showing a label about the problem.

**Comment by polcarrasco** [comment] 2019-11-14 17:05
We have also UPS shipping and Table rates and are both working fine.

**Comment by engcom-Echo** [comment] 2019-11-15 10:39
Hello @polcarrasco 

Could you provide more details for reproduce this issue?
Please add steps or screenshots of configuration DHL, Origin Shipping address and Customer`s addresses.

Thank you!

**Comment by polcarrasco** [comment] 2019-11-15 10:55
![Captura DHL CheckOut](https://user-images.githubusercontent.com/57757685/68938342-7527ef00-079e-11ea-8fa0-608628373af5.JPG)
![Captura DHL 3](https://user-images.githubusercontent.com/57757685/68938359-7e18c080-079e-11ea-9c18-e3ef6dfb1ec5.JPG)
![Captura DHL  1](https://user-images.githubusercontent.com/57757685/68938360-7e18c080-079e-11ea-83aa-f7b78db70066.JPG)
![Captura DHL 2](https://user-images.githubusercontent.com/57757685/68938361-7eb15700-079e-11ea-9907-cf5da833cf9d.JPG)

Hi,
Attached ypu may see screenshots of the extension configuration. Also a screenshot of the check out page where the shipping methods are shown.
It does not work for any address you may enter, to any country.
Thanks for your help!

**Comment by polcarrasco** [comment] 2019-11-15 10:59
![Captura Origin](https://user-images.githubusercontent.com/57757685/68938806-6261ea00-079f-11ea-818c-fdc58c36d69a.JPG)
...here is the origin config.

Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-15 12:43
@engcom-Echo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-15 12:46
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23207` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by devchris79** [comment] 2019-11-19 12:43
The source postcode looks wrong as the DHL log indicates. Spanish postcodes look to be 5 numbers and you have 6 (291008 in the origin).
https://en.wikipedia.org/wiki/List_of_postal_codes_in_Spain

**Comment by polcarrasco** [comment] 2019-11-19 13:23
Just fixed the postcode from Origin. It keeps faulty, DHL does not give any  rate.

**Comment by devchris79** [comment] 2019-11-19 14:05
What is your origin config now then?

**Comment by polcarrasco** [comment] 2019-11-19 14:15
![Captura origin](https://user-images.githubusercontent.com/57757685/69153952-65cadd80-0adf-11ea-97e4-e96e1be36043.JPG)

**Comment by devchris79** [comment] 2019-11-19 15:49
OK, can you please post the updated log for the request?

Both addresses as destinations work with our Magento 2.3.3 DHL module, but as its live I can't try your origin:

![grab](https://user-images.githubusercontent.com/43850303/69162128-13d88680-0ae4-11ea-815a-25031046fe3f.jpg)

**Comment by polcarrasco** [comment] 2019-11-27 09:54
Sorry, but I have not been able to get a log for the request. 
Is it any other way to find out the problem?

Thanks!

**Comment by devchris79** [comment] 2019-11-27 10:01
You need to use the setup option debug on, this will then write to the log for each request. 
I think the path is /var/log/shipping.log from memory. Although you posted it in your first post.

![debug](https://user-images.githubusercontent.com/43850303/69713578-b0121700-10fc-11ea-9bf1-5481080e9f43.jpg)

**Comment by devchris79** [comment] 2019-12-09 16:24
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-09 16:25
Hi @devchris79. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by devchris79** [comment] 2019-12-09 16:27
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-09 16:27
Hi @devchris79. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-09 16:28
Hi @devchris79, here is your [Magento instance](https://i-25602-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-25602-2-4-develop.instances.magento-community.engineering/admin](https://i-25602-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by devchris79** [comment] 2019-12-09 17:35
@polcarrasco I don't get any errors but I also don't get any rates, I think this is probably as our xml credentials are for UK.

You will need to post the log, if not I can't help further.

**Comment by polcarrasco** [comment] 2019-12-09 18:25
Thanks, I´ve asked my developer for the log, hopefully soon he can get it for me.

**Comment by sdzhepa** [comment] 2020-08-27 20:55
Hello @polcarrasco 

We are not able to reproduce this issue on the latest `2.4-develop` and latest release `2.4.0`
It seems the issue was already fixed in some other task or PR.

Could you please provide more details is it actual now and how to repro it on the `2.4-develop`? or we can close this issue

**Closed as completed** 2020-09-16 19:57 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Dhl, Progress: done

**Comment by Anantkprajapati** [comment] 2020-10-26 15:13
Hello Team,
Any updated about this. Same facing issue in magento 2.4 version.
