### ISSUE TITLE
 Translation doesn't work in the backend login page 

### ISSUE THREAD

**Issue by ghost** [magento/magento2#2465] opened 2015-11-22 03:56 UTC
This occurring because the locale manager is not getting  the default locale from database .

To solve this issue i simply edit this file : [Magento\Backend\Model\Locale\Manager](https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/Model/Locale/Manager.php) .

List of changes : 
1) Constructor : I add new dependency that implements  "\Magento\Backend\App\ConfigInterface"; 
2) Add new method called "getGeneralLocale()" to retrieve General locale;
3) Update  method "getUserInterfaceLocale()" to retrieve general locale when can't get "user locale" from session data.

Edition : 

``` php
namespace Magento\Backend\Model\Locale;

/**
 * Locale manager model
 *
 * @author     Magento Core Team <core@magentocommerce.com>
 */
class Manager
{
    /**
     * @var \Magento\Backend\Model\Session
     */
    protected $_session;

    /**
     * @var \Magento\Backend\Model\Auth\Session
     */
    protected $_authSession;

    /**
     * @var \Magento\Framework\TranslateInterface
     */
    protected $_translator;

    /**
     * @var \Magento\Backend\App\ConfigInterface
     */
    protected $_backendConfig;

    /**
     * Constructor
     *
     * @param \Magento\Backend\Model\Session $session
     * @param \Magento\Backend\Model\Auth\Session $authSession
     * @param \Magento\Framework\TranslateInterface $translator
     * @param \Magento\Backend\App\ConfigInterface $backendConfig
     */
    public function __construct(
        \Magento\Backend\Model\Session $session,
        \Magento\Backend\Model\Auth\Session $authSession,
        \Magento\Framework\TranslateInterface $translator,
        \Magento\Backend\App\ConfigInterface $backendConfig
    ) {
        $this->_session = $session;
        $this->_authSession = $authSession;
        $this->_translator = $translator;
        $this->_backendConfig = $backendConfig;
    }

    /**
     * Switch backend locale according to locale code
     *
     * @param string $localeCode
     * @return $this
     */
    public function switchBackendInterfaceLocale($localeCode)
    {
        $this->_session->setSessionLocale(null);

        $this->_authSession->getUser()->setInterfaceLocale($localeCode);

        $this->_translator->setLocale($localeCode)->loadData(null, true);

        return $this;
    }

    /**
     * Get general interface locale 
     *
     * @return string
     */
    public function getGeneralLocale()
    {
        return $this->_backendConfig->getValue('general/locale/code');
    }

    /**
     * Get user interface locale stored in session data
     *
     * @return string
     */
    public function getUserInterfaceLocale()
    {
        $userData = $this->_authSession->getUser();

        if ($userData && $userData->getInterfaceLocale()) {
            $interfaceLocale = $userData->getInterfaceLocale();
        }elseif ($this->getGeneralLocale()) {
            $interfaceLocale = $this->getGeneralLocale();
        }else {
            $interfaceLocale = \Magento\Framework\Locale\Resolver::DEFAULT_LOCALE;
        }

        return $interfaceLocale;
    }
}
```

Thanks

**Comment by labofidea** [comment] 2015-11-22 04:56
To resolve this issue i simply edit the file : Magento\Backend\Model\Locale\Manager.
Edition: 
```php
namespace Magento\Backend\Model\Locale;

/**
 * Locale manager model
 *
 * @author     Magento Core Team <core@magentocommerce.com>
 */
class Manager
{
    /**
     * @var \Magento\Backend\Model\Session
     */
    protected $_session;

    /**
     * @var \Magento\Backend\Model\Auth\Session
     */
    protected $_authSession;

    /**
     * @var \Magento\Framework\TranslateInterface
     */
    protected $_translator;
    /**
     * @var \Magento\Backend\App\ConfigInterface
     */
    protected $_backendConfig;
    /**
     * Constructor
     *
     * @param \Magento\Backend\Model\Session $session
     * @param \Magento\Backend\Model\Auth\Session $authSession
     * @param \Magento\Framework\TranslateInterface $translator
     * @param \Magento\Backend\App\ConfigInterface $backendConfig
     */
    public function __construct(
        \Magento\Backend\Model\Session $session,
        \Magento\Backend\Model\Auth\Session $authSession,
        \Magento\Framework\TranslateInterface $translator,
    	\Magento\Backend\App\ConfigInterface $backendConfig
    ) {
        $this->_session = $session;
        $this->_authSession = $authSession;
        $this->_translator = $translator;
        $this->_backendConfig = $backendConfig;
    }

    /**
     * Switch backend locale according to locale code
     *
     * @param string $localeCode
     * @return $this
     */
    public function switchBackendInterfaceLocale($localeCode)
    {
        $this->_session->setSessionLocale(null);

        $this->_authSession->getUser()->setInterfaceLocale($localeCode);

        $this->_translator->setLocale($localeCode)->loadData(null, true);

        return $this;
    }

    /**
     * Get general interface locale 
     *
     * @return string
     */
    public function getGeneralLocale(){
    	
    	return $this->_backendConfig->getValue('general/locale/code');
    }
    
    /**
     * Get user interface locale stored in session data
     *
     * @return string
     */
    public function getUserInterfaceLocale()
    {
        $interfaceLocale = \Magento\Framework\Locale\Resolver::DEFAULT_LOCALE;
               
        $userData = $this->_authSession->getUser();
        if ($userData && $userData->getInterfaceLocale()) {
            $interfaceLocale = $userData->getInterfaceLocale();
        }elseif ($this->getGeneralLocale()){
        	$interfaceLocale = $this->getGeneralLocale();
        }

        return $interfaceLocale;
    }
}
```

**Comment by shiftedreality** [comment] 2016-01-14 15:41
Hi @labofidea 

Please, create pull request with certain changes

**Comment by vzabaznov** [comment] 2016-06-22 12:29
Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-06-22 12:31
Hi @labofidea , referenced PR was closed and merged, if you still have such problems please  create new bug.

**Closed as completed by vzabaznov** 2016-06-22 12:31 UTC
