### ISSUE TITLE
Magento 2.4.4 Refused to apply style from 'http://gocustom.com/static/_cache/merged/source/stroke/helper.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by ziyaindia** [magento/magento2#35884] opened 2022-08-05 14:15 UTC
### Preconditions and environment

- M2.4.4
- Upgrade from M 2.4.2 to M 2.4.4

### Steps to reproduce

Take script and database backup and uload it on liver server

### Expected result

Site should be running as it is localhost

### Actual result

Getting following error

Refused to apply style from 'http://gocustom.com/static/_cache/merged/source/stroke/helper.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-08-08 10:58
Hello @ziyaindia , 

We have tried to reproduce the issue in Magento 2.4.4 branch the issue is not reproducible.
Please refer the below screenshot for the reference;
![Screenshot from 2022-08-08 16-26-18](https://user-images.githubusercontent.com/60198592/183402738-4023784b-6dc9-4c79-a20e-940cc1811080.png)

We have followed the below steps in order to reproduce the issue:
1.Install Magento 2.4.2 instance
2. Upgrade from 2.4.2 to 2.4.4
3. Site should be running as it is localhost

Let us know in case we have missed anything.

Thanks!!!

**Comment by gwharton** [comment] 2022-08-10 08:40
Whenever you get a bug like this, its because the less to css compilation failed. To work out what went wrong, in dev mode, if you browse to the file "http://gocustom.com/static/_cache/merged/source/stroke/helper.css", it should give you the less compilation error in the browser.

The underlying error is because the browser was expecting a compiled style sheet, but instead it got a html error page.

**Comment by engcom-Dash** [comment] 2022-08-10 10:18
Hi @gwharton ,

Thanks for your information....We are working as per your comments and the link is attached by you isn't not working for me...Kindly provide some alternate link or file...Because its very helpful us.


Thanks!!!

**Comment by gwharton** [comment] 2022-08-10 10:20
Yeah, that was a prompt to the original issue reporter on how to diagnose further.

**Comment by engcom-Dash** [comment] 2022-08-24 07:48
Hi @ziyaindia ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2022-08-24 07:48 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
