### ISSUE TITLE
Reindexing via Cron-Job not working - broken symlinks.

### ISSUE THREAD

**Issue by KGAlex** [magento/magento2#10122] opened 2017-07-02 10:28 UTC
Hi everyone,

We have a problem nobody was able to help us with so far. So I hope I get some helpful advices here.

1. We run Magento 2.0.7 with cpanel and Apache Version	2.4.25; PHP Version	7.0.19
2. After some Problems the system was installed fresh. After that a template and a language pack was installed. That´s about all what has been done so far.
3. Added a product via the backend, but it doesn´t appear in the frontend.
4. Cronjob does not work - no reindexing.

Checking update.log I get the following errors (only after customizing cronreadinesscheck.php):

`update-cron.ERROR: Cron readiness check failure! Found following non-writable paths: 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/templates/tooltip/tooltip.html 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/core/storage/local.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bootstrap.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/autoselect.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/bind-html.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/scope.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/mage-init.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/range.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/fadeVisible.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/bootstrap.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/outer_click.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/after-render.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/resizable.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/simple-checked.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/i18n.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/keyboard.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/datepicker.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/collapsible.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/tooltip.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/optgroup.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/bindings/staticChecked.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/template/renderer.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/template/observable_source.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/template/engine.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/template/loader.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/extender/bound-nodes.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/knockout/extender/observable_array.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/password-strength-indicator.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/zxcvbn.js 	/home/username/public_html/backups/pub/static/frontend/Magento/luma/en_US/FormData.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/templates/tooltip/tooltip.html 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bootstrap.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/autoselect.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/bind-html.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/scope.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/mage-init.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/range.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/fadeVisible.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/bootstrap.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/outer_click.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/after-render.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/resizable.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/simple-checked.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/i18n.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/keyboard.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/datepicker.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/collapsible.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/tooltip.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/optgroup.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/bindings/staticChecked.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/template/renderer.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/template/observable_source.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/template/engine.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/template/loader.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/bound-nodes.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/Magento_Ui/js/lib/knockout/extender/observable_array.js 	/home/username/public_html/backups/pub/static/adminhtml/Magento/backend/en_US/FormData.js [] []`

When I check those files permissions are fine, but they can´t be opened. I get an error 404 which says the symlink is broken. All the links refer to files which are not existant.

Thank´s in advance and regards
Alex

**Comment by mengbo123456** [comment] 2017-07-03 06:40
**# now i know why can't linking style ,but i don't know why this?**
because install path no version1499055289 folder ,and i add it  style work 
![qq 20170703141604](https://user-images.githubusercontent.com/29748690/27780458-9e8f6dfc-5ffb-11e7-9cf7-eaeb3d60d6c7.png)
![qq 20170703141841](https://user-images.githubusercontent.com/29748690/27780461-9f0b7dd4-5ffb-11e7-9a49-e3596576bcd9.png)
![qq 20170703142510](https://user-images.githubusercontent.com/29748690/27780459-9e9a501e-5ffb-11e7-96d0-4aa4b1650e53.png)
but i don't know why it can't add  version1499055289 folder itself in  During the installation process

**Comment by KGAlex** [comment] 2017-07-03 10:43
Hi,

I am not quite sure how this relates to our problem. Could you explain this to me?

**Comment by battulasurendra** [comment] 2017-07-04 12:38
I faced the same version folder problem. I cleared cache and switched to production mode from CLI. This works.

**Comment by KGAlex** [comment] 2017-07-05 09:23
When I try to switch to production mode I get following error:
```
...
Start compilation
Command returned non-zero exit code:
`php -f /home/petitechipie/public_html/bin/magento setup:di:compile-multi-tenant 2>&1
```


When I run the command seperatly I get this:
```

  [ReflectionException]
  Class \BasicTest does not exist



setup:di:compile-multi-tenant [--serializer="..."] [--extra-classes-file="..."] [--generation="..."] [--di="..."] [--exclude-pattern="..."] [--magento-init-params="..."]
```

Not quite sure what to do with this, any ideas?

**Comment by veloraven** [comment] 2017-07-05 11:19
@KGAlex thank you for your feedback.
If you want to report an issue please format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
If you are looking for some advice or discussion please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site as  GitHub issue tracker is intended for technical issues only.
Please also note that at the moment the latest versions are 2.1.7 and 2.0.15. So if you are looking for help on resolving the problem on ver. 2.0.7 please address it to forums.

**Comment by KGAlex** [comment] 2017-07-05 15:38
I tried doing that, what information are you missing?

Sadly the installations were outsourced to two different companies, which none seems to take responsibility. So if I knew exactly how this was produced I would be more specific. For now these are the informations I have.

**Closed as completed** 2017-09-18 19:24 UTC
Labels: Progress: needs update, Issue: Format is not valid
