### ISSUE TITLE
Adding product image: File doesn't exist

### ISSUE THREAD

**Issue by WalterSmulders** [magento/magento2#21978] opened 2019-03-27 18:54 UTC
### Preconditions (*)

1. Magento 2.2.8 & 2.3.1

### Steps to reproduce (*)

1. Add image trough \Magento\Catalog\Model\Product\Gallery\Processor->addImage
2. With $product, relative path, $options and true, false

### Expected result (*)

1. Image should be added to the product

### Actual result (*)

1. Exception will be raised:
[InvalidArgumentException]                                 
File '***pub/media/import/***' doesn't exist

I blocked out the prefix and suffix to the file location but these are correct. The error is because of the following:

In file:  Magento\Catalog\Model\Product\Gallery\Processor
Function: addImage
Lines: 194, 195, 196

With "$absoluteFilePath = $this->mediaDirectory->getAbsolutePath($file);" the absolute path to the file in pub/media/import will be resolved. In theory this is correct. However the lines 175 till 190 can possibly move the image to a other directory. When this happens $absoluteFilePath will be filled with a path that is the old path before the move was done since it uses the variable $file. Thus resulting on $this->mime->getMimeType($absoluteFilePath); giving an exception that the file doesn't exist anymore.

Possible fix is by moving lines 194, 195, 196 to above line 175 so the checks are done before the file will be moved.

**Comment by magento-engcom-team** [comment] 2019-03-27 18:54
Hi @WalterSmulders. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@WalterSmulders do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-28 03:11
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-28 03:12
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-28 03:12
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-28 03:12
Hi @shikhamis11, here is your [Magento instance](https://i-21978-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21978-2-3-develop.instances.magento-community.engineering/admin](https://i-21978-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dudzio12** [comment] 2019-03-29 08:20
@WalterSmulders - the only thing I changed was `$file` to `$destinationFile`, because if `$move` was false, it also changes it to magento nested directories, which updates `$destinationFile` variable, which in the end differs from `$file`.

**Comment by WalterSmulders** [comment] 2019-03-29 21:36
> @WalterSmulders - the only thing I changed was `$file` to `$destinationFile`, because if `$move` was false, it also changes it to magento nested directories, which updates `$destinationFile` variable, which in the end differs from `$file`.

Yeah, I know I tried that as well but I was in a hurry and if I remember correctly $destinationFile is a relative path that for some reason at that moment didn't get resolved correctly by getAbsolutePath but I can be mistaken. If it works, it works :)

**Comment by SergZen** [comment] 2019-04-03 10:47
> @WalterSmulders - the only thing I changed was `$file` to `$destinationFile`  because if `$move` was false, it also changes it to magento nested directories, which updates `$destinationFile` variable, which in the end differs from `$file`.

The problem exists when `$move` was `true`.
 
It moves file from $file to $destinationFile and $file after than not exist:
$this->mediaDirectory->renameFile($file, $destinationFile); 

After then we try to get wrong old file location because `$file` was removed and not exist this moment:
$absoluteFilePath = $this->mediaDirectory->getAbsolutePath($file);

We have wrong $absoluteFilePath for call this function:
$imageMimeType = $this->mime->getMimeType($absoluteFilePath); 

And getMimeType  throw new \InvalidArgumentException("File '$file' doesn't exist");

Solutions:

1. Add "$file = $destinationFile;" after $this->mediaDirectory->renameFile($file, $destinationFile);

2. Change 
$absoluteFilePath = $this->mediaDirectory->getAbsolutePath($file);
to
$absoluteFilePath = $this->mediaDirectory->getAbsolutePath($destinationFile);

**Comment by dudzio12** [comment] 2019-04-03 12:29
@SergZen - I've fixed it in #22020

**Comment by magento-engcom-team** [comment] 2019-04-15 07:45
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99206`, `MAGETWO-99207` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-05-01 11:05
Hi @WalterSmulders. Thank you for your report. 
The issue has been fixed in magento/magento2#22020 by @dudzio12 in 2.3-develop branch
Related commit(s):
 - [103c28be56300b235582504bbeb7a1325ef95eb7](https://github.com/magento/magento2/commit/103c28be56300b235582504bbeb7a1325ef95eb7)
 - [74ef0c0b5d168285d375b260ffbbddc87c4d3634](https://github.com/magento/magento2/commit/74ef0c0b5d168285d375b260ffbbddc87c4d3634)

The fix will be available with the upcoming 2.3.3 release.

**Closed as completed by magento-engcom-team** 2019-05-01 11:05 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by leoquijano** [comment] 2019-05-01 19:13
Hi @magento-engcom-team, is this fix going to be available in an upcoming 2.2.x release?

**Comment by magento-engcom-team** [comment] 2019-05-06 12:10
Hi @WalterSmulders. Thank you for your report. 
The issue has been fixed in magento/magento2#22579 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [008f8ef03b5eb4b8345bd1657d588bd7cb435e5a](https://github.com/magento/magento2/commit/008f8ef03b5eb4b8345bd1657d588bd7cb435e5a)
 - [e97f14c8e59f201a6fe8df7ed5326cfb130d0300](https://github.com/magento/magento2/commit/e97f14c8e59f201a6fe8df7ed5326cfb130d0300)

The fix will be available with the upcoming 2.2.9 release.
