### ISSUE TITLE
Shipping Setting issues

### ISSUE THREAD

**Issue by ArmandoV68** [magento/magento2#37679] opened 2023-06-28 00:00 UTC
### Preconditions and environment

- Magento version 2.3.2
- Shipping options have disappeared from our website. Trying to activate the ups shipping options and the backend is asking to Activate Magento Shipping, but we only use UPS. Anytime any changes are made to the backend there is an error - One or more of the Cache Types are invalidated: Page Cache. Please go to [Cache Management](https://www.summitmachine.com/admin_11a9b1/admin/cache/index/key/154c633c5ed362401795168ca332ae0f17d5d1be4a6b58470ac38f2337f5dc23/) and refresh cache types.

### Steps to reproduce

Navigate to store, add any item to cart, proceed to checkout.

Here you can not go forward as there is not any shipping options

### Expected result

Customer should be able to select shipping option and complete order

### Actual result

Customer can not complete order

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-28 07:04
Hi @ArmandoV68,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- Navigate to store, add any item to cart, proceed to checkout.


We are able to see the UPS shipping methods and other shipping method and we are place the order successfully using UPS and other shipping methods.




https://github.com/magento/magento2/assets/51680745/3b31141a-3885-419e-8130-c8f2523f0b92



After saving the Configuration please try to clear the cache.Please refer this document https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/manage-cache.html regarding cache management.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by devchris79** [comment] 2023-06-28 13:29
UPS have changed there API security, I think the issue is related to this  #37534
@engcom-Bravo is testing with the latest 2.4 develop instance that has OAuth 2.0 and works for now (until June 2024).

I have also read that UPS API support can give you a legacy link that will be supported for another year. [Here is a post ](https://magento.stackexchange.com/questions/367605/magento-2-4-3-ups-integration-now-that-ups-requires-oauth)talking about that.

**Comment by engcom-Bravo** [comment] 2023-06-30 06:21
@devchris79 Thanks for your contribution & collaboration over here.

@ArmandoV68 Kindly refer this comment https://github.com/magento/magento2/issues/37679#issuecomment-1611414806 and please let us know if you are still facing any issue.

it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.


Thanks.

**Comment by themew** [comment] 2023-07-04 15:50
> UPS have changed there API security, I think the issue is related to this #37534 @engcom-Bravo is testing with the latest 2.4 develop instance that has OAuth 2.0 and works for now (until June 2024).
> 
> I have also read that UPS API support can give you a legacy link that will be supported for another year. [Here is a post ](https://magento.stackexchange.com/questions/367605/magento-2-4-3-ups-integration-now-that-ups-requires-oauth)talking about that.

I spoke with the UPS API Team yesterday.  The legacy link will now result in a 182280 error as they're no longer giving out keys.  They explained it's OAuth or nothing.  Hard to comprehend that they'd cut off thousands of Magento UPS shippers like this, but they did and are aware they did.  Just looking to display rates...

**Comment by engcom-Bravo** [comment] 2023-07-13 06:16
@themew Thanks for your contribution & collaboration over here.

@ArmandoV68 Kindly update latest update on this comment https://github.com/magento/magento2/issues/37679#issuecomment-1614183927 please let us know if you are still facing any issue.


Thanks.

**Comment by themew** [comment] 2023-07-13 14:14
Unfortunately this issue will continue to exist until Magento has an OAuth option to retrieve UPS rates.  We've been forced to drop UPS shipping and I see other stores using a TBA or CALL for UPS shipping quotes.

**Comment by engcom-Bravo** [comment] 2023-08-10 12:07
Hi @themew @ArmandoV68,

Kindly refer this https://github.com/magento/magento2/issues/37846#issuecomment-1670710000 as per this 
For anyone else that runs into this, you'll need to contact UPS API support. They will send you the legacy link (which is no longer posted in their developerkit page) to request an access key - apparently access keys will still be supported for another year. Once you get that link, you'll submit your request, they'll email the access key to the primary contact's email address, then you enter that as your Access License Key, your UPS.com login ID for User ID, and your UPS.com login pw for Password.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-10 12:09
Hi @themew @ArmandoV68,

Regarding UPS shipping rates.

Kindly refer this https://magento.stackexchange.com/questions/367605/magento-2-4-3-ups-integration-now-that-ups-requires-oauth For anyone else that runs into this, you'll need to contact UPS API support. They will send you the legacy link (which is no longer posted in their developerkit page) to request an access key - apparently access keys will still be supported for another year. Once you get that link, you'll submit your request, they'll email the access key to the primary contact's email address, then you enter that as your Access License Key, your UPS.com login ID for User ID, and your UPS.com login pw for Password.

Thanks.

**Comment by themew** [comment] 2023-08-10 12:36
@engcom-Bravo Wish this was true, but sadly this is no longer the case with UPS.  My previous post https://github.com/magento/magento2/issues/37679#issuecomment-1620475057 is still UPS's position on this issue.

The ability to request a legacy link to obtain API access from UPS is unfortunately over.

**Comment by engcom-Bravo** [comment] 2024-01-10 07:01
Hi @ArmandoV68,

We have verified the issue in Magento 2.4-develop instance and the issue is not reproducible.


![Screenshot from 2024-01-10 12-17-02](https://github.com/magento/magento2/assets/51680745/56c3007e-3592-40a8-be46-647657e33465)


UPS Shipping method is working fine.

Regarding UPS issue Please refer this https://github.com/magento/magento2/issues/37679#issuecomment-1673098157 

Hence We are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-10 07:01 UTC
Labels: Issue: needs update, Reported on 2.3.2
