### ISSUE TITLE
The image is not assigning to the correct attribute option after sorting when use visual swatch- Magento 2.3.1

### ISSUE THREAD

**Issue by rohankatkar** [magento/magento2#23105] opened 2019-06-03 10:30 UTC
### Summary (*)
The image is not assigning to the correct attribute option after sorting when use visual swatch- Magento 2.3.1

### Examples (*)
**Please check the below images:**
**A) Below image is before adding the swatch option.**
![before_adding_swatch1](https://user-images.githubusercontent.com/5929761/58713861-226d9d00-83e1-11e9-81b0-a65bddda837e.png)

**B) Below image is after adding the option. Here option is sorted correctly alphabet-wise but the image is not assigning to that option. See below image**

![after_sort_1](https://user-images.githubusercontent.com/5929761/58714379-3d8cdc80-83e2-11e9-9865-51e4995e0108.png)

### Proposed solution
**File 1:** 

> vendor/magento/module-swatches/view/adminhtml/templates/catalog/product/attribute/Visual.phtml

in the above file, I have added code before last script tag. (after line 109)

```
<?php
    $values = [];
    $color = [];

    foreach($block->getOptionValues() as $value) {
        $value = $value->getData();
        $values[] = is_array($value) ? array_map(function($str) {
            return htmlspecialchars_decode($str, ENT_QUOTES);
        }, $value) : $value;
    }
    foreach($values as $key => $val) {
      $color[ucwords($key)]  = ucwords($val['store0']);
    }
    array_multisort($color, SORT_ASC, $values);
    ?>
```

also added the code in below file in getJsonConfig() after line 71

> vendor/magento/module-swatches/Block/Adminhtml/Attribute/Edit/Options/Visual.php

```
public function getJsonConfig()
    {
        $values = [];
        foreach ($this->getOptionValues() as $value) {
            $values[] = $value->getData();
        }
        //custom code
        foreach($values as $key => $val) {
          $mid[ucwords($key)]  = ucwords($val['store0']);
        }
        array_multisort($mid, SORT_ASC, $values);
        //custom code end
        $data = [
            'attributesData' => $values,
            'uploadActionUrl' => $this->getUrl('swatches/iframe/show'),
            'isSortable' => (int)(!$this->getReadOnly() && !$this->canManageOptionDefaultOnly()),
            'isReadOnly' => (int)$this->getReadOnly()
        ];
        
        return json_encode($data);
    }
```
    
after adding the above code, I am able to sort the attribute options.  But the visual swatches images don't sort with respective options.

How can we do that ? Above code is just temporary code

**Comment by rohankatkar** [comment] 2019-06-03 10:42
Hi @AlexWorking,   are you looking at this issue?

**Comment by rohankatkar** [comment] 2019-06-03 11:22
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-03 11:22
Hi @rohankatkar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-03 11:23
Hi @rohankatkar, here is your [Magento instance](https://i-23105-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23105-2-3-develop.instances.magento-community.engineering/admin](https://i-23105-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by AlexWorking** [comment] 2019-06-03 11:25
Hi, @rohankatkar. Yes.

Надіслано з мого телефону HTC

----- Відповідь -----
Від: "Rohan Katkar" <notifications@github.com>
Кому: "magento/magento2" <magento2@noreply.github.com>
Копія : "AlexWorking" <workmail2500@gmail.com>, "Mention" <mention@noreply.github.com>
Тема: [magento/magento2] The image is not assigning to the correct attribute option after sorting when use visual swatch- Magento 2.3.1 (#23105)
Дата: пн, черв. 3, 2019 13:43

Hi @AlexWorking,   are you looking at this issue?

**Comment by rohankatkar** [comment] 2019-06-03 11:30
Ok @AlexWorking ....

**Comment by AlexWorking** [comment] 2019-06-03 12:16
Ok, @rohankatkar. Thanks for applying. At now we've been not able to reproduce Your issue. Have You been successful in that?  We see You asked for a vanilla instance of magento from our bot.

**Comment by rohankatkar** [comment] 2019-06-03 12:19
Hello @AlexWorking ,

Please check below.

 **(Before replicating the above issue, please add the custom code given in issue summary)**

Steps to replicate: 
- Go to Store >> Attribute >> Product 
- Search for the color attribute 
- Add the swatch option with the image.
- Check that option get sorted
- But image assigned to last option.

Expected result:
The image should assign to the newly added option after sorting. (please see the screenshot)

Actual result:
The image does not assign against newly added option after sorting. (please see the screenshot)

**Comment by rohankatkar** [comment] 2019-06-03 12:21
Actually, I was not aware of the command which provides the vanilla instance of Magento .. I have mistakenly posted that in the comment box...

**Comment by AlexWorking** [comment] 2019-06-03 12:30
@rohankatkar, The GitHub issue tracker is intended for Magento Core technical issues only. For Your case, please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue.

**Closed as completed by AlexWorking** 2019-06-03 12:30 UTC
Labels: Issue: Format is valid
