### ISSUE TITLE
Menu does not expand in Brave browser

### ISSUE THREAD

**Issue by GrocExp** [magento/magento2#37413] opened 2023-04-22 23:48 UTC
The menu in the admin for Stores > Settings > Configuration does not do anything.  It does not expand.
https://prnt.sc/qf4eOt4ZBsQp

I have the same experience in 2 new Magento installs to 2.4.6 on Ubuntu 22.x
Everything else seems to work so I tried loading this in Firefox and the menu works (expands) as expected.

I'm running my client Brave browser on WIndows 11.

**Comment by engcom-November** [comment] 2023-04-25 04:24
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2023-04-25 04:36
Hi @GrocExp ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4-develop instance & 2.4.6 version with Brave browser but the issue is not reproducible.
All the menu items are expandable and no functional failures observed in Admin UI.
Brave browser version: [Version 1.50.125 Chromium: 112.0.5615.165 (Official Build) (64-bit)](https://brave.com/latest/)
Tested on Ubuntu OS 20.x
![image](https://user-images.githubusercontent.com/60198231/234174881-2a19881f-6965-4763-9936-81e025842412.png)
Kindly recheck if the issue occurring due to 3rd party modules / packages and elaborate missing steps if any if the issue is still reproducible.

**Comment by engcom-November** [comment] 2023-04-27 05:47
Thank you for the response @GrocExp . We will recheck the issue again on Windows 11.

**Comment by GrocExp** [comment] 2023-04-27 11:22
Thank you for your response too, but in my video I also demonstrated that
the issue I experienced on Windows 10 too using Brave Browser.

**Comment by engcom-Dash** [comment] 2023-10-13 08:03
Hi @GrocExp 
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance  with Brave browser ([Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)](https://brave.com/latest/) but the issue is not reproducible.
All the menu items are expandable and no functional failures observed in Admin UI.
Tested on Ubuntu OS 
Please refer the attached screenshots.
![image](https://github.com/magento/magento2/assets/60198592/49b14ce8-8873-4d8e-9faa-d05ab5ab9f32)

![image](https://github.com/magento/magento2/assets/60198592/51a97ee8-33bd-413b-b1a2-d5260f55d1b5)

![image](https://github.com/magento/magento2/assets/60198592/019032f8-ee08-4c58-b7c0-b58f265e0b86)

**Comment by engcom-Dash** [comment] 2023-11-03 08:08
Hi @GrocExp 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-11-03 08:08 UTC
Labels: Issue: needs update
