### ISSUE TITLE
Shipping methods doesn't work in 2.3.2

### ISSUE THREAD

**Issue by devchris79** [magento/magento2#23741] opened 2019-07-17 10:11 UTC
### Preconditions (*)

1. Magento 2.3.2

### Steps to reproduce (*)

1. Navigate to Stores>Configuration>Sales>Shipping Methods

### Expected result (*)

1. Able to make changes and save the result

### Actual result (*)

1. Save config and all the sales section menu buttons don't work, unlike all other menus that do. I get errors in the browser console on the page load:

![image](https://user-images.githubusercontent.com/43850303/61367337-49920800-a883-11e9-8a1c-02fe9db01097.png)

This appears to be confined to the Shipping methods, so it makes me think its a possible bug.

**Comment by engcom-Charlie** [comment] 2019-07-17 10:43
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-17 10:43
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-17 10:44
Hi @engcom-Charlie, here is your [Magento instance](https://i-23741-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23741-2-3-develop.instances.magento-community.engineering/admin](https://i-23741-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-17 11:00
@magento give me 2.3.2 instance

**Comment by magento-engcom-team** [comment] 2019-07-17 11:00
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3.2 instance for you

**Comment by magento-engcom-team** [comment] 2019-07-17 11:01
Hi @engcom-Charlie, here is your [Magento instance](https://i-23741-2-3-2.instances.magento-community.engineering).
Admin access: [https://i-23741-2-3-2.instances.magento-community.engineering/admin](https://i-23741-2-3-2.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-17 11:05
Hello @devchris79 ! Thank you for your report !
I was not able to reproduce this issue following steps you provide . I`m closing this for now but feel free to reopen it in case you can provide some extra steps/information about this issue !
Thanks in advance !

**Closed as completed by engcom-Charlie** 2019-07-17 11:05 UTC
Labels: Issue: Format is valid
