### ISSUE TITLE
Cannot call GET rest/V1/carts/search when a coupon is applied and item in cart is disabled

### ISSUE THREAD

**Issue by andrewkett** [magento/magento2#26087] opened 2019-12-18 08:55 UTC
### Preconditions
- Magento 2.3.3
- PHP 7.2

### Steps to reproduce
1. Create a clean Magento install
2. Add a single product
3. Create a single sales rule with a coupon targeting previously created product
3. Add the product to cart and apply sales rule with coupon
4. Disable the product in admin
5. Make GET request to rest/V1/carts/search 

### Expected result 
Magento returns a list of quotes containing the recently created one, it will contain no products as the product has been disabled

### Actual result 
Request hangs and eventually times out

**Comment by andrewkett** [comment] 2019-12-18 08:56
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-18 08:56
Hi @andrewkett. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-18 08:57
Hi @andrewkett, here is your [Magento instance](https://i-26087-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26087-2-4-develop.instances.magento-community.engineering/admin](https://i-26087-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by andrewkett** [comment] 2019-12-18 09:14
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-18 09:14
Hi @andrewkett. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by andrewkett** [comment] 2019-12-18 09:47
I just found https://github.com/magento/magento2/issues/25776 which looks to be the same issue. I've also tracked this down to Magento\SalesRule\Observer\CouponCodeValidation.

**Comment by andrewkett** [comment] 2019-12-18 09:49
I can't replicate this on 2.4-develop, I'm still waiting for my 2.3-develop environment to be built to replicate it there

**Comment by engcom-Echo** [comment] 2019-12-18 12:16
Hello @andrewkett 

Thank you for your report and collaboration!
I am not able to reproduce this issue on the 2.4-develop branch by provided steps.

**Testing scenario:**

**Steps to reproduce:**

1. Create a clean Magento install
2. Add a single product
3. Create a single sales rule with a coupon targeting previously created product
4. Add the product to cart and apply sales rule with coupon
5. Disable the product in admin
6. Make GET request to `rest/V1/carts/search`

**Result:** 
Magento returns a list of quotes containing the recently created one, it will contain no products as the product has been disabled. No errors.
![Screenshot from 2019-12-18 14-08-28](https://user-images.githubusercontent.com/51681435/71085707-cb72be00-21a0-11ea-82ef-e1bc81b14d37.png)
![Screenshot from 2019-12-18 14-08-39](https://user-images.githubusercontent.com/51681435/71085706-cada2780-21a0-11ea-86a6-74aa3eb94684.png)

So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-18 12:16 UTC
Labels: Issue: Format is valid

**Comment by andrewkett** [comment] 2019-12-18 19:51
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-18 19:51
Hi @andrewkett. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by andrewkett** [comment] 2019-12-18 22:51
Hi @engcom-Echo I tested on 2.4-develop and wasn't able to replicate this problem either. I have however tested locally on clean 2.3.3 and been able to replicate it. It is very similar to https://github.com/magento/magento2/issues/25776 so obviously I am not the only person seeing this in 2.3. I've been trying to spin up a 2.3 instance to verify if it still exists there, so far unsuccessfully.

**Comment by engcom-Echo** [comment] 2019-12-19 08:18
Hello @andrewkett 

The 2.3-develop branch is already closed for changes. The main one is the 2.4-develop. 
It looks like this issue has already been fixed in 2.4-develop.

**Comment by andrewkett** [comment] 2019-12-19 08:28
Does that mean this will not be resolved until 2.4 is released?

**Comment by engcom-Echo** [comment] 2019-12-19 08:39
@andrewkett 
Yes, but all changes are already available on 2.4 develop.
