### ISSUE TITLE
Can Someone Explain How This Bug Reporting Process On Github Is Supposed to Work?

### ISSUE THREAD

**Issue by ghost** [magento/magento2#4082] opened 2016-04-10 14:16 UTC
At the bottom of every Magento 2.0.x admin page there's a link 'Report Bugs' which brings you to https://github.com/magento/magento2/issues/ (this page).

Because of that I would expect that this github page is the authoritative place  to report bugs, correct?

Given that, I would also expect that there'd be some underlying process to progress the reports, correct?

What are the different steps along the way from 'opened' to 'closed'?  I'm asking this because I see many issues that been lying fallow for many, many days.  

Now I fully appreciate that there are a significant number of open issues (1153 at writing), and that a lot of  those may have been very poorly written up and have had no follow-up from the submitter when additional info is requested.  I also see that there are hundreds that appear to have zero comments ... which indicates that they are getting zero attention.  Why are they sitting around looking like litter?

All this makes clicking on "Report Bugs" almost worthless. :(

**Comment by mazhalai** [comment] 2016-05-09 17:52
@ircsome github issues are only for reporting bugs, if you want to have a discussion on process https://community.magento.com/ seems like the best avenue. 
Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-05-09 17:52 UTC
