### ISSUE TITLE
grand_total and base_grand_total have different values, although we have only ONE currency

### ISSUE THREAD

**Issue by thehl** [magento/magento2#34649] opened 2021-11-16 15:28 UTC
### Preconditions (*)
1. Magento 2.4.3-p1
2. Configure tax settings like in the screenshot
![taxsettings](https://user-images.githubusercontent.com/1321326/142010314-f6646577-3603-445d-9628-ef530d3b007f.png)
3. Tax Setup is 19% for Germany
4. Product Price is 5€ including taxes
5. Base currency is the same like the store currency

### Steps to reproduce (*)
1. Add the product with qty 1 to the cart 
2. Add shipping address in Germany
3. Get cart totals

### Expected result (*)
1. grand_total and base_grand_total should be the same value, because base and store currency are identical.

### Actual result (*)
1. grand_total and base_grand_total have different values
![grandtotal](https://user-images.githubusercontent.com/1321326/142011052-3a73f3d8-8d3b-4bd9-9413-9c4bfeb4fad6.png)
2. It seems grand_total is reduced by tax_amount, see: https://github.com/magento/magento2/blob/7255b67280f0755590232467662247789d82c449/app/code/Magento/Quote/Model/Cart/CartTotalRepository.php#L113

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-11-17 06:23
Hi @thehl,
Tried to reproduce the issue on Magento 2.4 Develop , observed that grand_total and base_grand_total values are different.
Hence  added 'Issue Confirmed'
Please find below response for reference.
![grandTotal](https://user-images.githubusercontent.com/51681379/142145791-e9b026d7-4991-4347-b150-015d20739442.JPG)


{
    
    "base_discount_amount": 0,
    "base_grand_total": 14,
    "base_discount_tax_compensation_amount": 0,
    "base_shipping_amount": 0,
    "base_shipping_discount_amount": 0,
    "base_shipping_discount_tax_compensation_amnt": 0,
    "base_shipping_incl_tax": 0,
    "base_shipping_tax_amount": 0,
    "base_subtotal": 14,
    "base_subtotal_incl_tax": 14,
    "base_tax_amount": 0,
    "base_total_due": 14,
    "base_to_global_rate": 1,
    "base_to_order_rate": 0.7067,
    "billing_address_id": 30,
    "created_at": "2021-11-17 06:13:27",
    "customer_firstname": "test",
    "customer_group_id": 1,
    "customer_id": 4,
    "customer_is_guest": 0,
    "customer_lastname": "techs",
    "customer_note_notify": 1,
    "discount_amount": 0,
    "entity_id": 16,
    "global_currency_code": "USD",
    "grand_total": 9.89,
    "discount_tax_compensation_amount": 0,
    "increment_id": "000000016",
    "is_virtual": 1,
    "order_currency_code": "EUR",
    "protect_code": "6695c817289e87adad6a5be38f53c1f8",
    "quote_id": 35,
    "remote_ip": "127.0.0.1",
    "shipping_amount": 0,
    "shipping_discount_amount": 0,
    "shipping_discount_tax_compensation_amount": 0,
    "shipping_incl_tax": 0,
    "shipping_tax_amount": 0,
    "state": "new",
    "status": "pending",
    "store_currency_code": "USD",
    "store_id": 1,
    "store_name": "Main Website\r\nMain Website Store\r\nDefault Store View",
    "store_to_base_rate": 0,
    "store_to_order_rate": 0,
    "subtotal": 9.89,
    "subtotal_incl_tax": 9.89,
    "tax_amount": 0,
    "total_due": 9.89,
    "total_item_count": 1,
    "total_qty_ordered": 1,
    "updated_at": "2021-11-17 06:13:30",
    "weight": 0,
    "items": [
        {

**Comment by arjunadobe** [comment] 2021-12-16 16:34
Hi @thehl  @sidolov  Is there any fix for this issue ?

**Comment by arjunadobe** [comment] 2021-12-16 16:35
I am also facing the same issue in Magento 2.4.3-p1

**Comment by itsmemagento** [comment] 2021-12-16 16:37
@thehl Is there any fix this issue

**Comment by pablomishchenko** [comment] 2022-01-10 13:14
@magento I am working on this

**Comment by veloraven** [comment] 2022-06-01 21:03
@magento I am working on this

**Comment by veloraven** [comment] 2022-06-01 21:04
Adobe Team is working on this issue now

**Comment by niekappartmedia** [comment] 2022-07-25 11:26
@veloraven Any news on this issue? Its now 25 of July.

**Comment by engcom-Delta** [comment] 2024-10-21 09:25
Hi @thehl ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Configure tax settings like in the screenshot
![image](https://github.com/user-attachments/assets/3819e3d3-332b-4979-b28e-a1fefa59ae56)
![image](https://github.com/user-attachments/assets/9a09480d-fbe1-469a-a4fb-a416b838798e)
2. Tax Setup is 19% for Germany
3. Product Price is 5€ including taxes
4. Base currency is the same like the store currency
5. Add the product with qty 1 to the cart
6. Add shipping address in Germany
7. Get cart totals
8. grand_total and base_grand_total should be the same value, because base and store currency are identical.
![image](https://github.com/user-attachments/assets/9c924fe7-d487-4440-b1a4-b5198a051827)

Can you please re-verify and confirm if you are still facing the issue.
Thanks.

**Comment by veloraven** [comment] 2024-10-21 18:09
I'm closing this issue as it was fixed before in internal ticket ACP2E-964 and the fix was delivered in version 2.4.6
If you need to find exact commits, you can search for commits containing ACP2E-964

**Closed as completed** 2024-10-21 18:10 UTC
Labels: Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Area: Tax
