### ISSUE TITLE
Cart custom shipping methods not updating when address changed

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4679] opened 2016-05-24 19:34 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Enable custom shipping methods added through extension.
3. Disable all built in shipping methods (i.e. UPS).
4. Add an item to your cart from the store front end.
5. Go to checkout.
6. Shipping methods show "Sorry, no quotes are available for this order at this time"
7. Enter an address.
## Expected result
1. The shipping methods should update and list rates for the custom shipping methods.
## Actual result
1. Shipping methods still shows "Sorry, no quotes are available for this order at this time"
2. This was fixed for built in methods such as UPS, but does not work for custom shipping methods. (See MAGETWO-50504)

**Comment by choukalos** [comment] 2016-05-25 14:32
Internal ticket - MAGETWO-53468 ; CC'ing @ilol so he's aware of issue; marked for patching back to 2.0.x

**Comment by ishakhsuvarov** [comment] 2016-05-31 09:18
@jim5359 We have tried to reproduce the case described with the latest code from the `develop` branch and did not find any errors.
Please check, that checkout shipping rate validators are implemented correctly in your extension (it is the mechanism responsible for reloading the list of available shipping methods on change of the specific address fields). There is a tutorial on this topic in the [Magento 2 Developer Documentation](http://devdocs.magento.com/guides/v2.0/howdoi/checkout/checkout_carrier.html).

**Comment by Kasoi-free** [comment] 2016-05-31 13:39
I am experiencing the same with built-in Table Rates method.

The trick is to setup your shipping methods in such way that when you try to get shipping for default Country (which is US in my case) there shouldn't be any available shipping methods. After that if you try to change shipping address to the one you have shipping rate for "Estimate Shipping and Tax" won't update. Same thing happens on Checkout page also.

This is how it can be set up:
1. Disable all Shipping Methods except Table Rates
2. Import rate only for non-default country in Table Rates (example for Afghanistan: http://prntscr.com/balo6t)
3. Check Estimate Shipping and Tax, there will be no shipping methods because default country does not match any rate in Table Rates, but if you change Country to the correct one shipping methods won't update: http://prntscr.com/balqlz

I am sure that rates I'm importing are correct, because when I reload Cart\Checkout page I see the rates: http://prntscr.com/balpph

Hope this will help to get to the bottom of this.

P.S. Tried this on 2.0.6 release, not sure if anything related to cart\checkout update was changed in development branch.

**Comment by jpreed2** [comment] 2016-05-31 18:42
I've confirmed that adding the shipping rate validators to my custom shipping rate extension solved the problem.  Thanks!

**Comment by asemenenko** [comment] 2016-06-01 08:09
Nice to hear that our documentation helped, @jim5359 !

**Comment by ishakhsuvarov** [comment] 2016-06-01 08:58
@Kasoi-free Thank you for reporting. We have created an internal ticket `MAGETWO-53785` to fix the issue.

**Comment by KrystynaKabannyk** [comment] 2016-06-08 16:07
Hello @jim5359, this issue has been fixed in Magento EE 2.1 RC2, that's why I'm closing it. Thank you for reporting the issue! If you have any questions or additional information you are welcome to reopen it or create another one.

**Closed as completed by KrystynaKabannyk** 2016-06-08 16:07 UTC
Labels: Issue: Ready for Work, bug report
