### ISSUE TITLE
[GraphQl] If all bundle item has Default Quantity greater than Quantity Per Source then it should OUT_OF_STOCK

### ISSUE THREAD

**Issue by haunguyen1989** [magento/magento2#30212] opened 2020-09-28 06:46 UTC
### Preconditions (*)

1. Magento 2.4-develop on Ubuntu 20.04 LTS
2. Elastic search 7.6

### Steps to reproduce (*)

1. 2 website and enable Store Code to Urls: Yes. Site Main Website and VN Website
2. Create new stock and assign new 2 source(Ha Noi, Ho Chi Minh) to site VN Website
3. Create 1 simple product. **Product A in-stock with qty = 1 for source Ho Chi Minh**
4. Create bundle product(sku: bundle03) and add new 1 option check required. Option 1: add product A and set **Default Quantity** **= 2**(**greater than qty product A = 1**) . Save
5. Reindex all
6. Check graphQL query for sku: bundle03:`query{
products(filter: {sku: {eq: "bundle03"} }){
    items {
      id
      sku
      stock_status
      name
      activity
      color
     related_products {
      name
      sku
    }
    }
    total_count
  }
}`

### Expected result (*)

1. "stock_status": "OUT_OF_STOCK"
2. Result: `{
  "data": {
    "products": {
      "items": [
        {
          "id": 2051,
          "sku": "bundle03",
          "stock_status": "OUT_OF_STOCK",
          "name": "bundle03",
          "activity": null,
          "color": null,
          "related_products": []
        }
      ],
      "total_count": 1
    }
  }
}`

### Actual result (*)

1. "stock_status": "IN_STOCK"
2. Result: `{
  "data": {
    "products": {
      "items": [
        {
          "id": 2051,
          "sku": "bundle03",
          "stock_status": "IN_STOCK",
          "name": "bundle03",
          "activity": null,
          "color": null,
          "related_products": []
        }
      ],
      "total_count": 1
    }
  }
}`
![Screenshot from 2020-09-28 13-42-52](https://user-images.githubusercontent.com/44774202/94398856-90220880-0190-11eb-9a12-e795d3cfbc37.png)

### Additional info from Engcom
Confirmed on the latest 2.4-develop.

The GraphQL query:
```graphql
query {
  products(filter: { sku: { eq: "bundle03" } }) {
    items {
      id
      sku
      stock_status
      name
      color
      related_products {
        name
        sku
      }
    }
    total_count
  }
}

```
returns **In Stock** despite that the product is Out of Stock on the Frontend
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "id": 6,
          "sku": "bundle03",
          "stock_status": "IN_STOCK", #<<<<<<<<<<<<<
          "name": "bundle03",
          "color": null,
          "related_products": []
        }
      ],
      "total_count": 1
    }
  }
}
```
![bundle](https://user-images.githubusercontent.com/51680745/106599074-3cba2f80-6561-11eb-9e96-984395a7920c.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by haunguyen1989** [comment] 2021-01-29 06:41
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 14 days if no further activity occurs. Is this issue still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? Thank you for your contributions!

We are still facing this issue at version 2.4.1.
If there is any feedback about it, thank you

**Comment by engcom-Bravo** [comment] 2021-02-02 12:18
Hello @haunguyen1989 

Thank you for your report.

We confirm that the issue is reproducible on the latest 2.4-develop. Additional info is added to the description.

**Comment by Usik2203** [comment] 2021-05-12 09:22
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-07-24 07:31
Hi @haunguyen1989,

Thanks for reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1145" alt="Screenshot 2024-07-24 at 12 58 18" src="https://github.com/user-attachments/assets/38daefe6-0574-4d6e-b46c-63dcf2b2844c">



<img width="1425" alt="Screenshot 2024-07-24 at 12 58 38" src="https://github.com/user-attachments/assets/a7b1ed63-2b9b-4deb-8d81-c02d4740fb3f">



The Stock Status is Out Of Stock.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-24 07:31 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Component: BundleGraphQl, Priority: P3, Severity: S3, Project: GraphQL, Progress: done, Reported on 2.4.0
