### ISSUE TITLE
Cannot edit product images from Magento cron

### ISSUE THREAD

**Issue by iwanvanzijderveld** [magento/magento2#38727] opened 2024-05-15 13:24 UTC
### Preconditions and environment

- Magento 2.4.7

Issue seems to the following function.
![image](https://github.com/magento/magento2/assets/97591780/98d15d2a-444c-42e3-9308-8f2781a1d117)

In the cron we emulate area adminhtml and this piece of code requires something from the frontend theme. which is not loaded (and shouldnt)

### Steps to reproduce

I haven't tested it out, but it would have to be something of the following.

1. Create a new cron that deletes images from a product.( execute it in $state->emulateAreaCode(Area::AREA_ADMINHTML, function here))
2. Run it with magerun sys:cron:run <cronjob>
3. See the error 'required parameter 'theme_dir' was not passed'

### Expected result

Cron to be executed.

### Actual result

Error required parameter 'theme_dir' was not passed

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-05-16 10:53
Hello @iwanvanzijderveld,

Thanks for the report and collaboration!

We have tried to reproduce this issue with the latest development branch i.e. 2.4-develop but the issue is not reproducible for us. We are able to delete the product images successfully.

Please refer to the below code for reference:

```
 public function execute()
    {
        $this->logger->alert('Cron job DeleteProduct Images is executing.');
        $this->registry->register('isSecureArea', true);
        $productSkusToDelete = ['SimpleProduct1-1-1'];
        foreach ($productSkusToDelete as $productSku) {
            $this->state->emulateAreaCode(Area::AREA_ADMINHTML, function () use ($productSku) {
                try {
                    $product = $this->productRepository->get($productSku);
                    $images = $product->getMediaGalleryEntries();
                    if (!empty($images)) {
                        foreach ($images as $image) {
                            $mediaGalleryEntryId = $image->getId();
                            $product->unsetData('media_gallery');
                            $this->productRepository->save($product->unsetData('media_gallery'));
                            $this->galleryResource->deleteGallery($mediaGalleryEntryId);
                        }
                    } else {
                        $this->logger->alert("Product Images with SKU $productSku does not have images.");
                    }
                    $this->logger->alert("Product Images with SKU $productSku is deleted.");
                } catch (\Exception $e) {
                    $this->logger->critical("Error: " . $e->getMessage());
                }
            });
        }
    }
```

Let us know if we missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2024-05-30 05:46
Dear @iwanvanzijderveld,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-05-30 05:46 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.7

**Comment by zakdma** [comment] 2024-10-23 09:24
Hey Guys, its really a BUG. I have the same weird behaviour and the same weird error message when delete media entries for products under adminhtml area. Why this buggy code provided in the issue description try to force access frontend area?

I do this
```
private \Magento\Catalog\Model\Product\Gallery\Processor $galleryProcessor;
...
$existingMedia = $product->getMediaGalleryEntries();
foreach ($existingMedia as $existingMediaItem) {
    $this->galleryProcessor->removeImage($product, $existingMediaItem['file']);
}
```

**Comment by engcom-Hotel** [comment] 2024-10-23 13:25
Hello @zakdma,

Actually, we have tried to reproduce the issue but it is not reproducible for us. Please refer to this https://github.com/magento/magento2/issues/38727#issuecomment-2114887724. 

Please let us know if we missed anything.

Thanks

**Comment by zakdma** [comment] 2024-10-23 15:36
> Hello @zakdma,
> 
> Actually, we have tried to reproduce the issue but it is not reproducible for us. Please refer to this [#38727 (comment)](https://github.com/magento/magento2/issues/38727#issuecomment-2114887724).
> 
> Please let us know if we missed anything.
> 
> Thanks

Please try my code instead.

```
private \Magento\Catalog\Model\Product\Gallery\Processor $galleryProcessor;
...
$existingMedia = $product->getMediaGalleryEntries();
foreach ($existingMedia as $existingMediaItem) {
    $this->galleryProcessor->removeImage($product, $existingMediaItem['file']);
}
```

**Comment by iwanzijderveld** [comment] 2024-11-08 11:58
Was the code above tried already?

**Comment by engcom-Hotel** [comment] 2024-11-11 10:21
Hello @zakdma,

According to the issue description, we have tried to reproduce the issue and the issue is not reproducible for us. We are able to delete the SKU images using the code mentioned [here](https://github.com/magento/magento2/issues/38727#issuecomment-2114887724). 

Can you please let us know the issue with using the above code to delete the images?

Thanks
