### ISSUE TITLE
filter customer order by scope

### ISSUE THREAD

**Issue by salah11172** [magento/magento2#37806] opened 2023-07-27 11:49 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug
2.4.4

### Steps to reproduce

try Retrieve orders based on scope argument:
1.Use the following payload and {{your URL}}/graphql to query the customer token.

mutation {
  generateCustomerToken(email: "{{your email address}}", password: "{{your password}}") {
    token
  }
}
2.Put above token in Postman Headers Authorization with Bearer {{your token}}.
3.Use following payload to query the above customer's sales orders.

```
{
    customer {
        orders(
            pageSize: 20,
            scope: GLOBAL
        ) {
            items {
                id
                order_number
                order_date
                total {
                    grand_total
                    { value currency }
                }
                status
            }
        }
    }
}
```

### Expected result

get all orders to this customer in all websites

### Actual result

get error 
            "message": "Unknown argument \"scope\" on field \"orders\" of type \"Customer\".",

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-28 07:06
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-28 12:19
Hi @salah11172,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

try Retrieve orders based on scope argument:

- Use the following payload and {{your URL}}/graphql to query the customer token.
- 

```
mutation {
generateCustomerToken(email: "{{your email address}}", password: "{{your password}}") {
token
}
}

```

- Put above token in Postman Headers Authorization with Bearer {{your token}}.


We have created multiple websites and multiple storeviews and we have placed the order from the different websites and different storeviews for the same customer.We are able to retrieve all the orders for the customer.


<img width="1464" alt="Screenshot 2023-07-28 at 1 03 50 PM" src="https://github.com/magento/magento2/assets/51680745/b4d5aa3f-ecbf-4eba-b470-a7ea8c801a55">



<img width="1468" alt="Screenshot 2023-07-28 at 1 06 37 PM" src="https://github.com/magento/magento2/assets/51680745/b80a44b9-b03e-4ee7-9bbf-3285dcad3885">



<img width="1495" alt="Screenshot 2023-07-28 at 1 06 45 PM" src="https://github.com/magento/magento2/assets/51680745/a0ddaf59-79db-4949-a3cc-033c2ff1935d">




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by salah11172** [comment] 2023-07-30 07:47
hello 
The problem is filtering orders
im add 2 filter to `CustomerOrdersFilterInput`

this is my code in _app/code/Teeela/CustomerOrder/etc/schema.graphqls_
```
input CustomerOrdersFilterInput @doc(description: "Identifies the filter to use for filtering orders.") {
    number: FilterStringTypeInput @doc(description: "Filters by order number."),
    status: FilterEqualTypeInput @doc(description: "Filters by status."),
    created_at: FilterRangeTypeInput @doc(description: "Filters by created at."),


}

input FilterRangeTypeInput @doc(description: "Defines a filter that matches a range of values, such as prices or dates.") {
    from: String @doc(description: "The beginning of the range")
    to: String @doc(description: "The end of the range")
}

input FilterEqualTypeInput @doc(description: "Defines a filter that matches the input exactly.") {
    in: [String] @doc(description: "An array of values to filter on")
    eq: String @doc(description: "A string to filter on")
}
```
when use 2 filter input like (created at , status )
use OR in condition 
expect use AND

![Screenshot from 2023-07-30 10-44-57](https://github.com/magento/magento2/assets/77698583/383f6a14-acfc-4507-9b6f-4302602d7e4f)

this screen should get just processing orders in this time that what expect 
the result 
get all orders in this time (because condition use OR not AND in query)

**Comment by engcom-Bravo** [comment] 2023-07-31 11:31
Hi @salah11172,

Thanks for your update.


Similar issue has been reported here https://github.com/magento/magento2/issues/37803 We are closing this as duplicate. Kindly move onto this issue for latest updates / solutions on the same.

Thank you.

**Closed as completed by engcom-Bravo** 2023-07-31 11:31 UTC
Labels: duplicate, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4
