### ISSUE TITLE
Exceptions when search product with sku like "42-"

### ISSUE THREAD

**Issue by Nazar65** [magento/magento2#20716] opened 2019-01-28 09:51 UTC
### Preconditions (*)
Magento 2.3 OpenSource
PHP 7.2
Apache
MySql 14.14
Ubuntu 18.04 LTS

### Steps to reproduce (*)
Create 2 or 3 products with sku like 42-315, 42-317 and 42-318.
Enable the MySql as search engine  in configuration.
Search in the frontend with sku "42-"

### Expected result (*)
Search result no exceptions

### Actual result (*)
![selection_295](https://user-images.githubusercontent.com/2481206/51827825-e8857080-22f2-11e9-8816-ff90e25cf98a.png)

**Comment by magento-engcom-team** [comment] 2019-01-28 09:51
Hi @Nazar65. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Nazar65 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by Nazar65** [comment] 2019-01-28 09:52
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-28 09:52
Hi @Nazar65. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-28 09:53
Hi @Nazar65, here is your [Magento instance](https://i-20716-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20716-2-3-develop.instances.magento-community.engineering/admin](https://i-20716-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-28 09:56
@Nazar65 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97945`, `MAGETWO-97946` were created

**Comment by magento-engcom-team** [comment] 2019-01-28 09:56
Hi @GovindaSharma. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Nazar65** [comment] 2019-01-28 09:57
I'm working on this

**Comment by magento-engcom-team** [comment] 2019-02-10 22:30
Hi @Nazar65. Thank you for your report. 
The issue has been fixed in magento/magento2#20727 by @Nazar65 in 2.3-develop branch
Related commit(s):
 - [cb681ab9f7f44457b420d7ae86cf7b324b7b8c94](https://github.com/magento/magento2/commit/cb681ab9f7f44457b420d7ae86cf7b324b7b8c94)
 - [7539e8e6829197467b59e417e317d38ea39a005b](https://github.com/magento/magento2/commit/7539e8e6829197467b59e417e317d38ea39a005b)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-10 22:30 UTC
Labels: Issue: Ready for Work, Component: Search, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by magento-engcom-team** [comment] 2019-02-11 16:35
Hi @Nazar65. Thank you for your report. 
The issue has been fixed in magento/magento2#20876 by @Nazar65 in 2.2-develop branch
Related commit(s):
 - [49d09cf331cd1ec6644b19ee7666ccfd87500c38](https://github.com/magento/magento2/commit/49d09cf331cd1ec6644b19ee7666ccfd87500c38)

The fix will be available with the upcoming 2.2.9 release.
