### ISSUE TITLE
Free shipping code is not working for UPS for magento 2

### ISSUE THREAD

**Issue by impunkj** [magento/magento2#10704] opened 2017-08-30 08:00 UTC
### Preconditions

1. Create a coupon code for free shipment.
2. Apply to coupon code on cart page or checkout both page.
3. Coupon applied successfully.  
4. 2.1.7 Magento

### Steps to reproduce

1. Generate a coupon code from Cart price rule for free shipping.
2. Shipping method is UPS 
3. Applied coupon to any cart or checkout flow.

### Expected result

1. Shipping amount should be zero.
2. Applied discount is equal to shipping amount. 

### Actual result

1. [Screenshot, logs]
The coupon code is applied but the amount remains same. 

After applying shipping price not changed. in same case price is changing for other shipping method.
Other shipping method is working fine Except UPS

**Comment by impunkj** [comment] 2017-09-04 05:54
Any update on this ?

**Comment by magento-engcom-team** [comment] 2017-09-12 07:54
@impunkj,  thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. 
Please, add the following information:
-Preconditions: Magento version, Is Sample Data installed

**Comment by impunkj** [comment] 2017-09-14 04:38
Hello , 
Thanks For reply. 
I already mention all the step but forget to mention version.
It is 2.1.7 Magento

**Comment by mbrzuzy** [comment] 2017-10-04 21:39
Also running into this issue. Free shipping method does not seem to be working for UPS through cart rules or through shipping configuration.

**Comment by JosephMaxwell** [comment] 2017-10-16 14:47
#squashtoberfest

**Comment by pmoreno1980** [comment] 2017-12-06 22:08
any update on this?

**Comment by tkacheva** [comment] 2019-01-28 22:42
Issue fixed in 2.2.6

**Comment by nadeefit6** [comment] 2019-04-05 06:13
Issue is still reproducing in 2.2.7.

**Comment by rafaelcalero** [comment] 2019-04-05 06:34
> Issue is still reproducing in 2.2.7.

+1

**Comment by nadeefit6** [comment] 2019-04-05 08:16
Any update on a fix?

**Comment by engcom-Delta** [comment] 2019-12-24 14:07
@nadeefit6 @rafaelcalero Unfortunately, I am not able to reproduce issue on  2.4-develop
**Steps to reproduce:**
- Generate a coupon code from Cart price rule for free shipping.
![image](https://user-images.githubusercontent.com/51681379/71415867-98c83a00-2666-11ea-884c-6563a5e9ebd4.png)

- Shipping method is UPS
![image](https://user-images.githubusercontent.com/51681379/71415780-25262d00-2666-11ea-88df-cea3c3ddf59e.png)

- Applied coupon to any cart or checkout flow.

**Actual result:**
:heavy_check_mark: Free shipping is applied for configured UPS method
![image](https://user-images.githubusercontent.com/51681379/71415936-e5ac1080-2666-11ea-9582-6c61f45163cc.png)

Could you take a look if it is correct steps to reproduce issue?

**Comment by Den4ik** [comment] 2019-12-25 11:20
@nadeefit6 @rafaelcalero Same results that provided by @engcom-Delta on 2.4-develop branch
**Before coupon apply in cart:**
![image](https://user-images.githubusercontent.com/1129623/71444257-f751ee80-2720-11ea-8726-9a3f172a9e90.png)
**After coupon apply in cart:**
![image](https://user-images.githubusercontent.com/1129623/71444269-033db080-2721-11ea-8fd7-adeb18fbe42d.png)
**Before coupon apply at checkout:**
![image](https://user-images.githubusercontent.com/1129623/71444272-12246300-2721-11ea-8cec-e5660a4d7f4c.png)
**After coupon apply at checkout:**
![image](https://user-images.githubusercontent.com/1129623/71444275-19e40780-2721-11ea-893e-871155bcb213.png)

Could you please provide information about shipping method and cart price rule configuration?
Please verify that you selected free method config for UPS, because zero price applying just to configured free method...
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Shipping/Model/Carrier/AbstractCarrier.php#L423-L426

**Comment by engcom-Delta** [comment] 2020-02-03 13:27
@nadeefit6 @rafaelcalero we are closing this issue due to inactivity. If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2020-02-03 13:27 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
