### ISSUE TITLE
Customer Login Not Working

### ISSUE THREAD

**Issue by nsbhanu** [magento/magento2#35067] opened 2022-02-08 11:57 UTC
### Preconditions (*)

1. Customer Login not working
2. Accepts Username & Password
3. Doesn't give any error, comes back to login page again
4. Checked logs from backend - No logs generated

### Steps to reproduce (*)

1. Initially when configured fresh, customer login was working
2. After couple of days, we were unable to login from Edge & Chrome, Firefox & Opera Browser worked
3. After some time unable to login with any of the browsers

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by devchris79** [comment] 2022-02-09 09:31
I had a similar issue to this and it was related to the Ultimo theme cache. 
You may want to check its not theme related. Also what version of Magento are you using?

**Comment by nsbhanu** [comment] 2022-02-09 11:15
Hi ,

 

We are using Supermarket2 theme and magento version is 2.4.3

**Comment by devchris79** [comment] 2022-02-09 11:27
I would test with the Luma theme and see if the issue is present. If its not then I would check the theme is the latest version and contact its support if required.

**Comment by engcom-Hotel** [comment] 2022-02-09 11:33
Hello @nsbhanu,

We have checked this issue with Magento 2.4-develop branch with luma theme and we are not facing such issues. It might be related to the theme you are using.

Please try it with Luma if the issue resolves.

Thanks

**Comment by nsbhanu** [comment] 2022-02-09 14:51
Thanks for the update… will check

**Comment by engcom-Hotel** [comment] 2022-02-10 07:33
Hello @nsbhanu,

Thanks for replying!

Please let us know in case you faced any issues with the Luma theme also.

Thanks

**Comment by engcom-Hotel** [comment] 2022-02-24 07:06
Dear @nsbhanu,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-24 07:06 UTC
Labels: Issue: needs update
