### ISSUE TITLE
Minicart popup is blank on currency change event.

### ISSUE THREAD

**Issue by Victor4G** [magento/magento2#4340] opened 2016-04-28 12:54 UTC
Hello,
There is issue in minicart, It becomes blank once you change the currency. 
It will be ok once you add more products after changing currency.

**NOTE:**  This issue only for development mode but we think initially there is a bug in our custom development so, it should work ok even on development mode.

**Comment by heyitsroberthe** [comment] 2016-04-28 19:47
Hi,

I couldn't reproduce your problem on a clean CE install. I see prices in the minicart correct for the currency I've selected.

**Comment by piotrekkaminski** [comment] 2016-05-12 23:59
@Victor4G can you provide steps to reproduce? does it reproduce on clean install?

**Comment by Victor4G** [comment] 2016-05-13 03:28
Hello,

I guess i have already mentioned about it..and yes.. i am using m2.0.2 and
2.0.4

Still you may follow as:
1. Your website have enables multi currency feature.
2. Add to cart any product and mini cart will be updated.
3. Now change currency from top dropdown.
4. You will see that minicart count and popup will be blank .. and will be
updated if you again add to cart on same page.

So this is the case but it not happens always...and for all pages.. it will
be random.

Let me know if you have any questions or query for the same.

**Comment by SerhiyShkolyarenko** [comment] 2016-10-13 10:03
Didn't reproduce on 2.0.9. 
@Victor4G as preconditions to the steps I enabled several currencies and created exchange rates for them. Is the issue still reproducible for you?

**Comment by SerhiyShkolyarenko** [comment] 2016-10-27 13:10
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by SerhiyShkolyarenko** 2016-10-27 13:10 UTC
Labels: bug report, Progress: needs update, Component: Tax, Component: Checkout, Component: Catalog
