### ISSUE TITLE
Not able to sync products cost using api /rest/V1/products/cost 

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#28374] opened 2020-05-26 14:26 UTC
### Preconditions (*)

1. Magento version 2.3.5 

### Steps to reproduce (*)

1. Configure the postman
2. Make an API call using the below details
API : rest/V1/products/cost
Request : {"prices":[{"cost":100.0,"store_id":0,"sku":"Test Prdouct-104"}]}

### Expected result (*)

1. Expected Result
 [
    {
        "message": "string",
        "parameters": [
                                "string"
                               ],
         "extension_attributes": {}
     }
]

### Actual result (*)

1. Actual result is empty braces 
[]

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sambath1293** [comment] 2020-06-04 09:34
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment] 2020-06-04 09:34
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by magento-engcom-team** [comment] 2020-06-04 09:35
Hi @sambath1293, here is your [Magento instance](https://i-28374-2-3-5.instances.magento-community.engineering).
Admin access: [https://i-28374-2-3-5.instances.magento-community.engineering/admin_b00f](https://i-28374-2-3-5.instances.magento-community.engineering/admin_b00f)
Login: `9a0bec0b` Password: `2207d2b0595e`
Instance will be terminated in up to 3 hours.

**Comment by sambath1293** [comment] 2020-06-04 09:48
@magento give me 2.4-develop instanc

**Comment by sambath1293** [comment] 2020-06-04 09:48
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-04 09:48
Hi @sambath1293. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-04 09:50
Hi @sambath1293, here is your [Magento instance](https://i-28374-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28374-2-4-develop.instances.magento-community.engineering/admin_36f5](https://i-28374-2-4-develop.instances.magento-community.engineering/admin_36f5)
Login: `db7f936a` Password: `ba4b6b59e1e8`
Instance will be terminated in up to 3 hours.

**Comment by sambath1293** [comment] 2020-06-04 10:08
Hi @webgility-amazonapi - I was tried to recreate this issue in both Magento 2.4-develop instance and  Magento 2.3.5 instance and I could see the empty array response in both instances.
See the below Reference:
 Magento 2.3.5 instance

![2 3 5APIissue](https://user-images.githubusercontent.com/60879885/83743988-1910b380-a679-11ea-8871-c489de0d3e18.png)
Magento 2.4-develop instance 
![2 4APIIssue](https://user-images.githubusercontent.com/60879885/83744028-25950c00-a679-11ea-8089-212442d895d0.png)


But in both instances, the price sync is happening accordingly.it just displayed empty response only in postman.
see the below reference :
![PriceUpdate](https://user-images.githubusercontent.com/60879885/83744211-68ef7a80-a679-11ea-8efc-24f1524b4767.png)

**Comment by magento-engcom-team** [comment] 2020-06-04 10:13
:white_check_mark: Confirmed by @sambath1293 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34947` were created

**Issue Available**: @sambath1293, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Echo** [comment] 2020-06-05 13:08
Hi, @sambath1293б @webgility-amazonapi .

If we look interface app/code/Magento/Catalog/Api/CostStorageInterface.php
![image](https://user-images.githubusercontent.com/51681435/83879597-8dfdef00-a746-11ea-9769-5fec49294ad3.png)
`If there were no failed items during update empty array will be returned.`
We get the right behavior.

**Comment by engcom-Echo** [comment] 2020-06-17 07:55
Hi @webgility-amazonapi, I'm closing this PR now due to inactivity.
Please reopen and update if you wish to continue.
Thank you for your collaboration.

**Closed as completed by engcom-Echo** 2020-06-17 07:55 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, non-issue, Issue: Format is valid, Component: Api, Reproduced on 2.4.x, Reported on 2.3.5
