### ISSUE TITLE
Getting incorrect base_row_total value in refund response.

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#38054] opened 2023-10-09 13:46 UTC
### Preconditions and environment

For some refunds getting the base_row_total is incorrect at item level.

As a user, I found that base_row_total = base_price* qty but for some records the base_row_total is not matching this formula. hence incorrect value getting displayed to the user.

### Steps to reproduce

(1) Create a new order.
(2) Now create refund for some of the items.
(3) Verify if the item level refund is correct.

### Expected result

base_row_total = base_price* qty 
4.1 = 0.82 * 5

### Actual result

4.08 getting displyed as row total.

### Additional information

![bug1](https://github.com/magento/magento2/assets/54638813/8cc06b86-7bdb-485b-ac87-95bbd51625b1)

### Release note

{
    "items": [
        {
            "adjustment": -5,
            "adjustment_negative": 15,
            "adjustment_positive": 10,
            "base_adjustment": -5,
            "base_adjustment_negative": 15,
            "base_adjustment_positive": 10,
            "base_currency_code": "USD",
            "base_discount_amount": -5.5,
            "base_grand_total": 50,
            "base_discount_tax_compensation_amount": 0,
            "base_shipping_amount": 5.5,
            "base_shipping_incl_tax": 5.5,
            "base_shipping_tax_amount": 0,
            "base_subtotal": 44.9,
            "base_subtotal_incl_tax": 55,
            "base_tax_amount": 10.1,
            "base_to_global_rate": 1,
            "base_to_order_rate": 1,
            "billing_address_id": 515,
            "created_at": "2023-09-28 10:47:28",
            "discount_amount": -5.5,
            "discount_description": "March40",
            "entity_id": 37,
            "global_currency_code": "USD",
            "grand_total": 50,
            "discount_tax_compensation_amount": 0,
            "increment_id": "000000032",
            "order_currency_code": "USD",
            "order_id": 262,
            "shipping_address_id": 514,
            "shipping_amount": 5.5,
            "shipping_incl_tax": 5.5,
            "shipping_tax_amount": 0,
            "state": 2,
            "store_currency_code": "USD",
            "store_id": 1,
            "store_to_base_rate": 0,
            "store_to_order_rate": 0,
            "subtotal": 44.9,
            "subtotal_incl_tax": 55,
            "tax_amount": 10.1,
            "updated_at": "2023-09-28 10:47:28",
            "items": [
                {
                    "base_cost": null,
                    "base_discount_amount": 5,
                    "base_discount_tax_compensation_amount": 0,
                    "base_price": 40.82,
                    "base_price_incl_tax": 50,
                    "base_row_total": 40.82,
                    "base_row_total_incl_tax": 50,
                    "base_tax_amount": 9.18,
                    "base_weee_tax_row_disposition": 0,
                    "discount_amount": 5,
                    "entity_id": 50,
                    "discount_tax_compensation_amount": 0,
                    "name": "Downloadble product",
                    "order_item_id": 318,
                    "parent_id": 37,
                    "price": 40.82,
                    "price_incl_tax": 50,
                    "product_id": 252,
                    "qty": 1,
                    "row_total": 40.82,
                    "row_total_incl_tax": 50,
                    "sku": "Downloadble product",
                    "tax_amount": 9.18,
                    "weee_tax_applied": "[]",
                    "weee_tax_applied_row_amount": 0,
                    "weee_tax_row_disposition": 0
                },
                {
                    "base_cost": null,
                    "base_discount_amount": 0.5,
                    "base_discount_tax_compensation_amount": 0,
                    "base_price": 0.82,
                    "base_price_incl_tax": 1,
                    "base_row_total": 4.08,
                    "base_row_total_incl_tax": 5,
                    "base_tax_amount": 0.92,
                    "base_weee_tax_row_disposition": 0,
                    "discount_amount": 0.5,
                    "entity_id": 51,
                    "discount_tax_compensation_amount": 0,
                    "name": "Apsara pencil",
                    "order_item_id": 321,
                    "parent_id": 37,
                    "price": 0.82,
                    "price_incl_tax": 1,
                    "product_id": 235,
                    "qty": 5,
                    "row_total": 4.08,
                    "row_total_incl_tax": 5,
                    "sku": "Apsara pencil",
                    "tax_amount": 0.92,
                    "weee_tax_applied": "[]",
                    "weee_tax_applied_row_amount": 0,
                    "weee_tax_row_disposition": 0
                },
                {
                    "base_cost": null,
                    "base_price": 0,
                    "base_price_incl_tax": 0,
                    "entity_id": 52,
                    "name": "Sprite Yoga Strap Dynamic Bundle",
                    "order_item_id": 322,
                    "parent_id": 37,
                    "price": 0,
                    "price_incl_tax": 0,
                    "product_id": 5,
                    "qty": 1,
                    "sku": "24-WG085-bundle-dynamic-24-WG085"
                },
                {
                    "base_cost": 40,
                    "base_price": 0,
                    "base_price_incl_tax": 0,
                    "base_row_total": 0,
                    "base_row_total_incl_tax": 0,
                    "base_weee_tax_row_disposition": 0,
                    "entity_id": 53,
                    "name": "Sprite Yoga Strap 6 foot",
                    "order_item_id": 323,
                    "parent_id": 37,
                    "price": 0,
                    "price_incl_tax": 0,
                    "product_id": 1,
                    "qty": 1,
                    "row_total": 0,
                    "row_total_incl_tax": 0,
                    "sku": "24-WG085",
                    "weee_tax_applied": "[]",
                    "weee_tax_applied_row_amount": 0,
                    "weee_tax_row_disposition": 0
                }
            ],
            "comments": []
        }
    ],
    "search_criteria": {
        "filter_groups": [
            {
                "filters": [
                    {
                        "field": "order_id",
                        "value": "262",
                        "condition_type": "eq"
                    }
                ]
            }
        ],
        "page_size": 1,
        "current_page": 1
    },
    "total_count": 1
}

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-11 10:27
Hi @webgility-amazonapi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance.Kindly refer the screenshots.


**Steps to reproduce**

- Create a new order.
- Now create refund for some of the items.
- Verify if the item level refund is correct.



<img width="551" alt="Screenshot 2023-10-11 at 3 52 52 PM" src="https://github.com/magento/magento2/assets/51680745/6cec599f-2445-46c1-b586-2e73e49af07f">




<img width="538" alt="Screenshot 2023-10-11 at 3 53 06 PM" src="https://github.com/magento/magento2/assets/51680745/6b2bcbcd-faf7-499d-8cf4-a09c8f5f4124">




It is working as expected because **base_row_total** means enitre amount while placing an order.**amount_refunded** is correctly displayed as per the refunded amount.

Could you please let us know if we are missing anything.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-23 05:31
Hi @webgility-amazonapi,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38054#issuecomment-1757349873 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-26 05:40
Hi @webgility-amazonapi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-26 05:40 UTC
Labels: Issue: needs update, Reported on 2.4.x
