### ISSUE TITLE
Indexing problem.

### ISSUE THREAD

**Issue by Chrisk1993** [magento/magento2#4485] opened 2016-05-12 20:36 UTC
Trying to reindex manually as my con jobs are throwing errors and came across this which I am struggling to get rid of. It doesn't seem to be permission related as setting everything to 777 doesn't help. Customer Grid indexer process unknown error:

```
SessionHandler::read(): open(timeout=5&amp;retry_interval=15/sess_eca02a7940c14aa4367e40e37dd819fc, O_RDWR) failed: No such file or directory (2)
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:01

Fatal error: Uncaught exception 'ErrorException' with message 'SessionHandler::write(): open(timeout=5&amp;retry_interval=15/sess_eca02a7940c14aa4367e40e37dd819fc, O_RDWR) failed: No such file or directory (2)' in /var/sites/e/emtuning.co.uk/public_html/vendor/magento/framework/Session/SaveHandler.php:86
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'SessionHandler:...', '/var/sites/e/em...', 86, Array)
#1 /var/sites/e/emtuning.co.uk/public_html/vendor/magento/framework/Session/SaveHandler.php(86): SessionHandler->write('eca02a7940c14aa...', 'adminhtml|a:0:{...')
#2 [internal function]: Magento\Framework\Session\SaveHandler->write('eca02a7940c14aa...', 'adminhtml|a:0:{...')
#3 {main}
  thrown in /var/sites/e/emtuning.co.uk/public_html/vendor/magento/framework/Session/SaveHandler.php on line 86
```

Also have this as a debug.

```
[2016-05-12 20:18:05] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"DB_PDO_MYSQL_DDL_catalogsearch_fulltext_scope1_4"},"is_exception":false} []
[2016-05-12 20:18:05] main.DEBUG: cache_invalidate:  {"method":"GET","url":"http:/","invalidateInfo":{"identifier":"request_declaration"},"is_exception":false} []
[2016-05-12 20:18:25] main.DEBUG: cache_invalidate:  {"method":"POST","url":"(myurl)/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []
[2016-05-12 20:20:32] main.DEBUG: cache_invalidate:  {"method":"GET","url":"(myurl)/","invalidateInfo":{"tags":["interception","CONFIG"],"mode":"matchingTag"},"is_exception":false} []

```

**Comment by maksek** [comment] 2016-05-12 23:13
@Chrisk1993 it looks like session storage permission issues. Check where session files are stored, and make sure your user has rights to read/write to the storage.
The issue is not reproducible, and it seems like your local env. Please provide detailed steps to reproduce how we can get the same error, otherwise we will close the issue. All questions HowTo please ask in forum.

**Comment by duhon** [comment] 2016-06-15 10:22
closed due to lack of response

**Closed as completed by duhon** 2016-06-15 10:22 UTC
Labels: Progress: needs update
