### ISSUE TITLE
Price cannot be saved per website (prices website scoped)

### ISSUE THREAD

**Issue by netzkollektiv** [magento/magento2#31978] opened 2021-02-05 10:53 UTC
### Preconditions (*)

1. Magento 2.3.5p1
2. the store has two websites, e.g. "DE" and "AT"
3. every website has a single storeView

### Steps to reproduce (*)

1. Price Scope is set to "per website"
2. Create a product with price = 10
2. Switch to another StoreView than default
3. Remove "Use default" for price, set price = 20
4. Save the product

### Expected result (*)

1. Price for website 1 should be 20
2. "Use default" should be unchecked (please only look at the database when solving this issue - there is another issue with displaying the value in the admin backend - it just does not show the correct value, even if the database is correct)
3. the catalog_product_entity_decimal should look like this:

value_id	attribute_id	store_id	entity_id	value
471122	75	0	38045	10.000000
471122	75	1	38045	10.000000

### Actual result (*)

1. Price for the seelcted storeView 1 is still 10
2. "Use default" is checked
3. the catalog_product_entity_decimal actually looks like this:

value_id	attribute_id	store_id	entity_id	value
471122	75	0	38045	10.000000

The problem was introduced with the following commit:

```
commit a8dc219fb67c7a803b9a83e890835e5fb260f0e6
Author: Yaroslav Onischenko <yonischenko@magento.com>
Date:   Fri Dec 16 10:27:05 2016 +0200

    MAGETWO-56978: [GITHUB] Product prices not scoped to Website - scoping seems to be at store view level #5133 #7251
```

module-eav handles it correctly, module-catalog then removes the value:

```
INSERT IGNORE INTO `catalog_product_entity_decimal` (`entity_id`,`attribute_id`,`store_id`,`value`) VALUES (?, ?, ?, ?)Array
(
    [0] => 38045
    [1] => 75
    [2] => 2
    [3] => 20
)
#0 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(616): mylog('INSERT IGNORE I...', true)
#1 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(2068): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT IGNORE I...', Array)
#2 /var/www/html/vendor/magento/module-eav/Model/ResourceModel/AttributePersistor.php(155): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('catalog_product...', Array, Array, 2)
#3 /var/www/html/vendor/magento/module-eav/Model/ResourceModel/AttributePersistor.php(330): Magento\Eav\Model\ResourceModel\AttributePersistor->processInserts('Magento\\Catalog...', Array)
#4 /var/www/html/vendor/magento/module-eav/Model/ResourceModel/UpdateHandler.php(187): Magento\Eav\Model\ResourceModel\AttributePersistor->flush('Magento\\Catalog...', Array)
#5 /var/www/html/vendor/magento/framework/EntityManager/Operation/Update/UpdateAttributes.php(59): Magento\Eav\Model\ResourceModel\UpdateHandler->execute('Magento\\Catalog...', Array, Array)
#6 /var/www/html/vendor/magento/framework/EntityManager/Operation/Update.php(108): Magento\Framework\EntityManager\Operation\Update\UpdateAttributes->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#7 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Framework\EntityManager\Operation\Update->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#8 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(758): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#11 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#12 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#14 /var/www/html/vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#17 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#18 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(655): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#19 /var/www/html/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(142): Magento\Framework\Model\AbstractModel->save()
#20 /var/www/html/vendor/magento/framework/App/Action/Action.php(108): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#21 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent('dispatch', Array)
#24 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /var/www/html/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#28 /var/www/html/vendor/magento/framework/App/FrontController.php(162): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#34 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#36 /var/www/html/index.php(53): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#37 {main}

DELETE FROM `catalog_product_entity_decimal` WHERE (attribute_id='75' AND entity_id='38045' AND store_id=2)Array
(
)
#0 /var/www/html/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(616): mylog('DELETE FROM `ca...', true)
#1 /var/www/html/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(664): Magento\Framework\DB\Adapter\Pdo\Mysql->query('DELETE FROM `ca...')
#2 /var/www/html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1696): Zend_Db_Adapter_Abstract->delete('catalog_product...', '(attribute_id='...')
#3 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(661): Magento\Eav\Model\Entity\AbstractEntity->saveAttribute(Object(Magento\Catalog\Model\Product\Interceptor), 'price')
#4 /var/www/html/vendor/magento/module-catalog/Model/Product.php(1846): Magento\Catalog\Model\ResourceModel\Product\Interceptor->saveAttribute(Object(Magento\Catalog\Model\Product\Interceptor), 'price')
#5 /var/www/html/vendor/magento/module-catalog/Model/Product/Attribute/Backend/Price.php(140): Magento\Catalog\Model\Product->addAttributeUpdate('price', NULL, '2')
#6 /var/www/html/generated/code/Magento/Catalog/Model/Product/Attribute/Backend/Price/Interceptor.php(50): Magento\Catalog\Model\Product\Attribute\Backend\Price->afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#7 [internal function]: Magento\Catalog\Model\Product\Attribute\Backend\Price\Interceptor->afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#8 /var/www/html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(677): call_user_func_array(Array, Array)
#9 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(505): Magento\Eav\Model\Entity\AbstractEntity->walkAttributes('backend/afterSa...', Array, NULL)
#10 /var/www/html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1840): Magento\Catalog\Model\ResourceModel\Product\Interceptor->walkAttributes('backend/afterSa...', Array)
#11 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(306): Magento\Eav\Model\Entity\AbstractEntity->_afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#12 /var/www/html/vendor/magento/module-eav/Model/Entity/AbstractEntity.php(1961): Magento\Catalog\Model\ResourceModel\Product->_afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#13 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(713): Magento\Eav\Model\Entity\AbstractEntity->afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#14 /var/www/html/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(33): Magento\Catalog\Model\ResourceModel\Product\Interceptor->afterSave(Object(Magento\Catalog\Model\Product\Interceptor))
#15 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute(Object(Magento\Framework\Event\Observer))
#16 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Framework\EntityManager\Observer\AfterEntitySave), Object(Magento\Framework\Event\Observer))
#17 /var/www/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#18 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('magento_catalog...', Array)
#19 /var/www/html/vendor/magento/framework/EntityManager/EventManager.php(52): Magento\Framework\Event\Manager\Proxy->dispatch('magento_catalog...', Array)
#20 /var/www/html/vendor/magento/framework/EntityManager/Operation/Update.php(110): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent('Magento\\Catalog...', 'save_after', Array)
#21 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Framework\EntityManager\Operation\Update->execute(Object(Magento\Catalog\Model\Product\Interceptor), Array)
#22 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php(758): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Product\Interceptor))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save(Object(Magento\Catalog\Model\Product\Interceptor))
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent('save', Array)
#25 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#26 /var/www/html/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#28 /var/www/html/vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#29 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Product\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor))
#30 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor))
#31 /var/www/html/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins('save', Array, Array)
#32 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(655): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save(Object(Magento\Catalog\Model\Product\Interceptor))
#33 /var/www/html/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(142): Magento\Framework\Model\AbstractModel->save()
#34 /var/www/html/vendor/magento/framework/App/Action/Action.php(108): Magento\Catalog\Controller\Adminhtml\Product\Save->execute()
#35 /var/www/html/vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent('dispatch', Array)
#38 /var/www/html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /var/www/html/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#42 /var/www/html/vendor/magento/framework/App/FrontController.php(162): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /var/www/html/vendor/magento/framework/App/FrontController.php(99): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor))
#44 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#46 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /var/www/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#48 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#49 /var/www/html/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#50 /var/www/html/index.php(53): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#51 {main}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-05 12:39
Hello @netzkollektiv 

Thank you for your report.

The issue is already fixed on the latest 2.4-develop. Please see the attachment.
![fixed](https://user-images.githubusercontent.com/51680745/107034735-cb2bec80-67bf-11eb-854e-9a0ef4189010.png)

Can you please Confirm if you are able to reproduce it on the latest 2.4-develop?

Thank you in advance

**Comment by engcom-Bravo** [comment] 2021-02-25 14:33
We are closing this issue due to inactivity. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2021-02-25 14:33 UTC
Labels: Issue: needs update, not-confirmed

**Comment by vseager** [comment] 2021-04-23 10:21
We are experiencing this issue on 2.4.1

**Comment by netzkollektiv** [comment] 2021-07-14 09:26
We also reproduced exactly the same issue on 2.4.2 ....

**Comment by netzkollektiv** [comment] 2021-07-16 10:00
Ok, this seems to be a migration issue (migrated with official Magento 1 migration tool). If someone experiences this issue, please check if the "Catalog Price Scope" matches the Product Attribute Scope of "price". They should match, either `global` or `website`.

**Comment by vseager** [comment] 2021-07-16 10:43
@netzkollektiv I have checked on our client's site and they weren't matching. I set them both be "website" but it didn't solve the issue for us on Magento 2.4.2-p1

**Comment by isxam** [comment] 2021-10-04 08:40
@magento give me 2.4-develop instance
