### ISSUE TITLE
PayPal NVP CURL connection error #7

### ISSUE THREAD

**Issue by fruit-ninja** [magento/magento2#28597] opened 2020-06-06 23:41 UTC
### Preconditions (*)

1. 2.3.5p1
2. CentOS 8
3. PHP 7.3.18
4. Apache/2.4.37
5. 10.3.17-MariaDB MariaDB
### Steps to reproduce (*)

1. Add item to cart
2. Click cart, click proceed to checkout
3. Fill in info, select shipping option, click next
4. Click the radio button for PayPal Express Checkout
5. Click Continue to Paypal

### Expected result (*)

1. Redirected to Paypal to proceed with the checkout 

### Actual result (*)

1. `Payment Gateway is unreachable at the moment. Please use another payment option.`
2. `[2020-06-06 23:27:29] main.CRITICAL: PayPal NVP CURL connection error #7:  {"exception":"[object] (Exception(code: 0): PayPal NVP CURL connection error #7:  at /var/www/html/vendor/magento/module-paypal/Model/Api/Nvp.php:1215)"} []`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by fruit-ninja** [comment] 2020-06-06 23:45
@magento give me 2.3.5-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-06 23:45
Hi @fruit-ninja. Thank you for your request. I'm working on Magento 2.3.5-develop instance for you

**Comment by sivaschenko** [comment] 2020-10-19 14:17
@magento give me 2.3.6 instance

**Comment by irenelagno** [comment] 2020-10-19 16:06
@magento 2.3-develop instance

**Comment by irenelagno** [comment] 2020-10-19 16:07
@magento give me 2.3-develop instance

**Comment by sivaschenko** [comment] 2020-10-19 17:13
Cannot reproduce on 2.4-develop

**Comment by irenelagno** [comment] 2020-10-19 18:56
@magento give me 2.3-develop instance

**Comment by engcom-Bravo** [comment] 2020-10-20 14:28
Hello @fruit-ninja 

Thank you for your report

We confirm that the issue is reproducible on 2.3.5-p1
We get similar errors on while trying to Place Order
![reproduced1](https://user-images.githubusercontent.com/51680745/96600052-3331f200-12f9-11eb-90e0-78263dd7117b.png)
`[2020-10-20 10:39:55] main.CRITICAL: PayPal NVP gateway errors: The Buyer cannot pay with PayPal for this Transaction (#13113: Buyer Cannot Pay). Correlation ID: 488b83e7cdf9e. Version: 72.0. [] [] `

**However**, this issue is not reproducible on later Magento versions. We have rechecked on:
2.4-develop
2.3.5-p2 -composer
2.3.6 - composer
2.4.0 - composer
2.4.1 - composer

So we have to close this issue. Please feel free to comment, or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-10-20 14:28 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.5

**Comment by irenelagno** [comment] 2020-11-05 20:15
@magento give me 2.3-develop instance

**Comment by irenelagno** [comment] 2020-11-05 20:32
@magento give me 2.3-develop instance
