### ISSUE TITLE
Magento less compile cannot handle `/* stylelint-disable */`

### ISSUE THREAD

**Issue by andrewhowdencom** [magento/magento2#10553] opened 2017-08-16 13:41 UTC
### Preconditions

1. Magento version:         "magento/product-community-edition": "2.1.7"

### Steps to reproduce

 Use the following less syntax: 

```
            li {
                &.wishlist {
                    /* stylelint-disable */ // Deprecated. Too far nested.
                    a {
                        display: block;
                        line-height: 1.7;
                        text-align: center;

                        .lib-icon-font(
                            @icon_wishlist,
                            @_icon-font: @icon-font__font-name,
                            @_icon-font-position: before,
                            @_icon-font-size: 20px,
                            @_icon-font-margin: 0,
                            @_icon-font-color-hover: false,
                            @_icon-font-color: @light-__color,
                            @_icon-font-text-hide: false
                        );
                    }
                    /* stylelint-enable */
                }
            }
````

### Expected result

1. Less compiles

### Actual result

1. Less fails, with the following error:

```
Compilation from source: 
frontend/${THEME}/base/de_DE/css/styles-m.less
ParseError: missing opening `{` in _extend.less on line 37, column 13
```

This works:

```
            li {
                &.wishlist {
                    /* stylelint-disable */ // Deprecated. Too far nested.
                    a {
                        display: block;
                        line-height: 1.7;
                        text-align: center;

                        .lib-icon-font(
                            @icon_wishlist,
                            @_icon-font: @icon-font__font-name,
                            @_icon-font-position: before,
                            @_icon-font-size: 20px,
                            @_icon-font-margin: 0,
                            @_icon-font-color-hover: false,
                            @_icon-font-color: @light-__color,
                            @_icon-font-text-hide: false
                        );
                    }
                    /* stylelint-enable */ // Fuck logic.
                }
            }
```

**Comment by orlangur** [comment] 2017-08-16 14:05
Which version of https://github.com/oyejorge/less.php can handle this syntax?

**Comment by andrewhowdencom** [comment] 2017-08-16 14:18
I'm confused. Are you asking me to look into this further? My understanding of the bug reporting process is that I would find the minimal possible test case with Magento, and you would do the underlying investigation of the libraries involved.

Edit: The installation is currently on the most recent version of that library, and quick testing shows it's able to handle that syntax fine. I'm not too sure where it's going wrong, but investigating it is beyond what I have time for now. This issue is a stub -- if someone else comes across this and can reproduce a smaller test case, awesome -- but for now, this is the limit of my report.

**Comment by orlangur** [comment] 2017-08-16 14:55
> quick testing shows it's able to handle that syntax fine

Thanks for checking. If the bug would be in a third-party library Magento can not do much about it.

**Comment by magento-engcom-team** [comment] 2017-09-19 07:54
We are closing this issue because we cannot reproduce this issue as described. If you have questions, please refer to a question and answer site, such as Stack Exchange and the Magento Forums, where Magento community members can quickly provide recommendations and advice.

**Closed as completed by magento-engcom-team** 2017-09-19 07:54 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
