### ISSUE TITLE
Magento 2.3.4 Setup:upgrade Incorrect theme identification key

### ISSUE THREAD

**Issue by Fdec** [magento/magento2#27180] opened 2020-03-05 14:19 UTC
### Preconditions (*)

1. Magento 2.3.4 from scratch with sample data

### Steps to reproduce (*)

1. launch bin/magento setup:upgrade

### Expected result (*)

1. Upgrade modules OK

### Actual result (*)

1. Upgrade stopped on module Magento_ConfigurableSampleData: "Running data recurring...Incorrect theme identification key"

**Comment by bst2002git** [comment] 2020-03-05 14:44
It's the function in this File
 vendor/magento/module-configurable-sample-data/Setup/RecurringData.php:
public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $this->state->emulateAreaCode(
           \Magento\Framework\App\Area::AREA_CRONTAB,
           [$this, 'reindex']
        );
				 
    }

**Comment by cmuench** [comment] 2021-02-20 11:47
The problem still exists.
If I add a return in the `vendor/magento/module-configurable-sample-data/Setup/RecurringData.php::install` method the problem is gone.

**Comment by thomas-kl1** [comment] 2021-02-25 11:01
@magento create-issue

**Comment by engcom-Bravo** [comment] 2021-03-01 18:45
Rechecked on the latest Magento 2.4-develop git version by cloning repositories https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-clone.html
And on Magento composer versions 2.4.0, 2.4.1, 2.4.2. https://devdocs.magento.com/guides/v2.4/install-gde/install/sample-data-after-composer.html
Setup upgrade completed successfully without any errors.

**Comment by cmuench** [comment] 2021-03-01 19:14
@EarlBromStyle I also installed Magento 2.4.2 last week and got the error. I can still re-produce it. I did some further debugging here and see that in my case an external module is involved.

See stacktrace:

```
#0 /var/www/html/vendor/magento/module-theme/Model/View/Design.php(148): Magento\Framework\View\Design\Theme\FlyweightFactory->create(NULL, 'crontab')
#1 /var/www/html/vendor/magento/module-theme/Model/View/Design.php(212): Magento\Theme\Model\View\Design->setDesignTheme(NULL)
#2 /var/www/html/vendor/magento/framework/App/Area.php(261): Magento\Theme\Model\View\Design->setDefaultDesignTheme()
#3 /var/www/html/vendor/magento/framework/App/Area.php(219): Magento\Framework\App\Area->_initDesign()
#4 /var/www/html/vendor/magento/framework/App/Area.php(143): Magento\Framework\App\Area->_loadPart('design')
#5 /var/www/html/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/CmsContentFilter.php(67): Magento\Framework\App\Area->load('design')
#6 /var/www/html/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-cms/Model/Indexer/DataProvider/Page/ContentData.php(39): Divante\VsbridgeIndexerCms\Model\Indexer\DataProvider\CmsContentFilter->filter(Array, 1, 'page')
#7 /var/www/html/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-core/Indexer/GenericIndexerHandler.php(134): Divante\VsbridgeIndexerCms\Model\Indexer\DataProvider\Page\ContentData->addData(Array, 1)
#8 /var/www/html/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-core/Indexer/Action/Full.php(54): Divante\VsbridgeIndexerCore\Indexer\GenericIndexerHandler->saveIndex(Object(Generator), Object(Magento\Store\Model\Store\Interceptor))
#9 /var/www/html/vendor/divante/magento2-vsbridge-indexer/src/module-vsbridge-indexer-core/Indexer/Base.php(49): Divante\VsbridgeIndexerCore\Indexer\Action\Full->execute(Array)
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Divante\VsbridgeIndexerCore\Indexer\Base->executeFull()
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Divante\VsbridgeIndexerCore\Indexer\Base\Interceptor->___callParent('executeFull', Array)
#12 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Divante\VsbridgeIndexerCore\Indexer\Base\Interceptor->Magento\Framework\Interception\{closure}()
#13 /var/www/html/generated/code/Divante/VsbridgeIndexerCore/Indexer/Base/Interceptor.php(32): Divante\VsbridgeIndexerCore\Indexer\Base\Interceptor->___callPlugins('executeFull', Array, Array)
#14 /var/www/html/vendor/magento/module-indexer/Model/Indexer.php(443): Divante\VsbridgeIndexerCore\Indexer\Base\Interceptor->executeFull()
#15 /var/www/html/vendor/magento/module-indexer/Model/Indexer/DependencyDecorator.php(259): Magento\Indexer\Model\Indexer->reindexAll()
#16 /var/www/html/vendor/magento/module-configurable-sample-data/Setup/RecurringData.php(60): Magento\Indexer\Model\Indexer\DependencyDecorator->reindexAll()
#17 [internal function]: Magento\ConfigurableSampleData\Setup\RecurringData->reindex()
#18 /var/www/html/vendor/magento/framework/App/State.php(187): call_user_func_array(Array, Array)
#19 /var/www/html/generated/code/Magento/Framework/App/State/Interceptor.php(68): Magento\Framework\App\State->emulateAreaCode('crontab', Array, Array)
#20 /var/www/html/vendor/magento/module-configurable-sample-data/Setup/RecurringData.php(50): Magento\Framework\App\State\Interceptor->emulateAreaCode('crontab', Array)
#21 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1117): Magento\ConfigurableSampleData\Setup\RecurringData->install(Object(Magento\Setup\Module\DataSetup), Object(Magento\Setup\Model\ModuleContext))
#22 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(960): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\DataSetup), 'data', Array)
#23 /var/www/html/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(147): Magento\Setup\Model\Installer->installDataFixtures(Array, true)
#24 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/bin/magento(23): Symfony\Component\Console\Application->run()
#30 {main}
```

I will try to figure out if the problem has to be fixed in the core or the 3rd party module.

**Comment by cmuench** [comment] 2021-03-01 19:17
The 3rd party module is doing this:

```
$this->appEmulation->startEnvironmentEmulation($storeId);
$this->areaList->getArea(Area::AREA_FRONTEND)->load(Area::PART_DESIGN);
$templateFilter = $this->geTemplateFilter($type)->setStoreId($storeId);
```

Maybe it's an issue to run a store emulation with store emulation embedded.

**Comment by engcom-Bravo** [comment] 2021-03-03 10:23
@Fdec 
As far as the issue is not reproducible on clean Magento installation, and, as described in the [comment](https://github.com/magento/magento2/issues/27180#issuecomment-788199655) above, a third-party module is involved, we have to close this issue. We can not deliver a fix into third-party modules or extensions. Magento Comunity Backlog is for Magento Core issues.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by engcom-Bravo** 2021-03-03 10:23 UTC
Labels: Issue: ready for confirmation, Reported on 2.3.4

**Comment by cmuench** [comment] 2021-03-03 10:30
@engcom-Bravo I expected that you will close the issue during my investigation. That's not the Magento spirit we need. I understand that you try to cleanup your issue backlog, but it's not motivating.

It would be good to find a way to improve the sample data compatibility. Maybe the approach to start an indexing inside the RecuringData upgrade of the sample data module is not the best.
We should check at least that.
I know that other developer had similar problems with the installed sample data. The third party module is implementing the indexer in a proper way by implementing the interfaces with `@api` annotation.
