### ISSUE TITLE
Magento 2.1.0 wrong product price after removal of catalog price rule

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#6048] opened 2016-08-08 11:41 UTC
### Preconditions

1. Using Magento 2.1.0
### Steps to reproduce

1. Create a catalog price rule
2. Save and Apply
3.  Remove price rule
### Expected result

1.  After removal of price rule, original price of the product should be shown
### Actual result

1. Even after removal of price rule, its still showing the catalog rule price instead of original price.

**Comment by andimov** [comment] 2016-08-10 08:45
@routbiplab 
Thank you for reporting!
Can't reproduce this issue.
Changes in product price after removing catalog price rule required reindexing.
Please, check "Catalog Rule Product" in Index Management or add additional info for reproducing.

**Comment by magentodevleper** [comment] 2016-08-17 13:30
After remove catalog price rule , reindex must be require..

> magento indexer:reindex catalogrule_product

**Comment by routbiplab** [comment] 2016-08-24 07:46
Yeah did Re-index and it worked. Thanks

**Comment by andimov** [comment] 2016-09-02 16:03
@routbiplab 
Ok, thank you. I'm closing this issue as "not a bug".

**Closed as completed by andimov** 2016-09-02 16:03 UTC
Labels: bug report, Progress: needs update
