### ISSUE TITLE
Frontend wrongly shows a default price in a product list and a product view for a customer with a custom tier group price specified

### ISSUE THREAD

**Issue by zolthan** [magento/magento2#4151] opened 2016-04-14 12:14 UTC
Copy from #3101 

Magento2 no longer supports Group Prices. It is not possible to define and display a price for qty 1 that is not the default price.
## Steps to reproduce

See the Screenshots here: https://mage2.pro/t/544

or read this description: (from https://community.magento.com/t5/Just-Ask-Alan/Group-pricing-on-Magento-2/m-p/26734)

> Hi Alan
> 
> I need to show a wholesale price for my products for users in the Wholesale customer group.  This was easy in the Group Price functionality in Mage 1.9, but for some reason has been removed from Mage 2.
> 
> I have tried the following:
> 
> Setting up a separate Wholesale website
> - The Price attribute in the product's Basic Settings screen treats the Price attribute as Global scope, even though in the Attributes it shows that Price is Website scope
> 
> Using the Tiered Pricing in Advanced options
> - Even with the Quantity set as 1, it will only show the tiered price in the basket, not the catalogue pages
> 
> Any help would be appreciated
> 
> Many thanks
## Expected result

Display the correct price for Customer Group A if the logged in Customer is in Group A.
## Actual result

Displays the normal price.

**Comment by sammarcus** [comment] 2016-04-23 21:54
This is really bizarre. I was just doing some of my own research to determine where the Group Price section went (it is [still](http://docs.magento.com/m2/ce/user_guide/catalog/settings-advanced-advanced-pricing.html) shown in the M2 docs!) but it seems that Tier Pricing does not fully substitute this feature.

In #2094 it was suggested Group Pricing was removed because of the functionality overlap with Tier Pricing but if they do not overlap, how are users to be shown custom pricing then?

Any update on this would be appreciated.

**Comment by kandy** [comment] 2016-04-27 12:41
@sammarcus, I cannot reproduce issue in latest mainline.

**Comment by sammarcus** [comment] 2016-05-03 20:19
@kandy Thanks for looking into this. To clarify, you are seeing a Group Pricing section as the screenshot in the docs displays? 
Or, there is no separate Group Pricing section but Tier Pricing is working to handle this functionality?

**Comment by kandy** [comment] 2016-05-05 13:05
@sammarcus, i use Tier Pricing

**Comment by piotrekkaminski** [comment] 2016-05-24 16:24
Any other feedback on this? Does the tier price replace the previous feature enough?

**Comment by sammarcus** [comment] 2016-11-02 08:12
Can this please be clarified?

**Comment by Delta-40** [comment] 2017-01-16 14:06
> This bug still persist in 2.1.3!

Its actually fixed, if the customer logs out and in again, after getting the customer group.

**Comment by magento-engcom-team** [comment] 2017-10-23 11:30
@zolthan, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-23 11:30 UTC
Labels: bug report, Component: Tax, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
