### ISSUE TITLE
Impossible to change sort order of custom option values over several pages in product edit view

### ISSUE THREAD

**Issue by norgeindian** [magento/magento2#28153] opened 2020-05-08 08:19 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Create a new simple product in the backend
2. Add a custom option of type drop-down
3. Add 21 values, the last value appears on a new page.
4. Try to move the last value to another position on the first page.

### Expected result (*)

1. I would assume that it is possible to sort the values using the drag and drop functionality, even over several pages.

### Actual result (*)

1. It is not possible to move any value to another page using the drag and drop functionality.

**Comment by maheshWebkul721** [comment] 2020-05-13 11:56
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-13 11:56
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by maheshWebkul721** [comment] 2020-05-13 13:41
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-13 13:41
Magento instance deployment temporary unavailable due to service maintenance.

**Comment by ajijshekh123** [comment] 2020-05-15 05:51
Hello @norgeindian,
I have reviewed the custom values in the  Simple product.
Now, 20 Fixed values are displaying in the first page and then after other values are showing.
See attached the screenshot:

![New1](https://user-images.githubusercontent.com/24711761/82016127-f30d7a00-969d-11ea-886c-c1fec873205e.png)

![New2](https://user-images.githubusercontent.com/24711761/82016129-f4d73d80-969d-11ea-9a63-4c42d2cf3699.png)

@norgeindian - This is not an issue. This is a feature of the Magento Framework.

Let me know if anything missing from my side.

Thanks.

**Comment by magento-engcom-team** [comment] 2020-05-15 05:52
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-34356` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by norgeindian** [comment] 2020-05-15 06:16
@ajijshekh123 , thanks for checking, but I assume, that we speak of different things here.
As far as I can see, you checked, that the first 20 entries are on one page and all additional values are added to another page.
That's alright, I have no issue with that.

Put please try now, like I wrote in step 4 of my issue description, to move for example value 22 of your list between values 10 and 11 on the first page, to change the order the values appear in the frontend.
To change the order I only see the Drag & Drop functionality and this does not work over several pages.
Please be so kind and check again, that is actually an issue.

**Comment by ajijshekh123** [comment] 2020-05-15 07:18
@norgeindian - Is it feasible to send a video?

**Comment by norgeindian** [comment] 2020-05-15 07:56
@ajijshekh123 sorry, in my eyes it's kind of difficult to show something in a video, which can not be done...
So let my try to explain it again.
When you take a look at your first page with the values 1-20, you can use the Drag & Drop functionality (grey boxes on the left side of each value) to drag a value and drop it at another spot of your list.
So for example it is possible to drag value 1 and move it down a few spots so that it is placed after value 5 for example.
This way the sort order of the values can be changed.
Can you confirm that this is possible on your instance as well?

My issue now is, that it is impossible to move a value to a spot on another page.
So it **is** possible to move value 1 somewhere on the first page, but there is **no** way to move value 1 to a spot on the second page, so for example between value 22 and 23.

This way the sort order possibilities are limited to movements on a specific page, which is a bug in my eyes, as the sort order can not be individualized completely.

I hope my explanation was clearer now, please let me know, if you still miss something.

**Comment by ajijshekh123** [comment] 2020-05-15 09:16
Hello @norgeindian,
Thanks for the good clarifications. I understand your issue.
I think this is not an issue.  This is a limitation set by the Magento Team.
Let me confirm this issue with a feature request.

Thanks.

**Comment by norgeindian** [comment] 2020-05-15 10:04
@ajijshekh123, thanks for confirming the issue.
To be honest, in my eyes this is actually a bug and no feature request.
There is obviously the possibility to change the order of the values, so it should be possible to change it for any value in my eyes and not only for groups of 20 values.
In Magento1 there was the possibility to adapt the order by adding an integer to each value. This worked with as many values as wanted.
So here Magento actually takes a step back in adding the Drag & Drop functionality and limiting the functionality to each page.
So please be so kind and think one more time about labeling this as a bug, because I don't think that this limitation was set on purpose or with a special aim in mind.
Thank you.

**Comment by ajijshekh123** [comment] 2020-05-15 10:34
Okay, @norgeindian,
I understand your concern and your feedback.
Let me discuss with this issue the Magento team then update the label. 

Thanks.

**Comment by ajijshekh123** [comment] 2020-05-15 10:35
@sdzhepa - Can you please review this issue on your end update here? Is that issue or feature request?
Please update me asap.

Thanks.

**Comment by hostep** [comment] 2020-05-15 11:15
Let me post a screenshot from a discussion in Slack about this issue in here.

I also believe it's a bug if it's impossible to change the sort order when you have more then 20 entries. Adding a way to increase the page size could fix the issue I guess, might not be the most user-friendly solution, but can probably be implemented quite quickly in the existing UI?

<img width="1330" alt="Screenshot 2020-05-15 at 13 13 57" src="https://user-images.githubusercontent.com/85479/82044714-26f09b80-96ae-11ea-8cb5-9aa2276a56ef.png">

**Comment by norgeindian** [comment] 2020-12-28 12:15
@sdzhepa , what is the status of this issue?
Like discussed in May this should be handled as a bug as it is actually not possible to sort the options at all currently.

**Comment by sdzhepa** [comment] 2021-02-05 16:39
Hello @nocturnalfrog 

I do not have any updates. 
As I can see this issue was reviewed and Triaged
It was handled a bug report and the label " feature request" was removed.
It was prioritized on the [Public Triage Meeting](https://github.com/magento/magento2/wiki/Public-Triage-Meeting)  as Priority: P3 based on [Community Backlog Priority](https://devdocs.magento.com/contributor-guide/contributing.html#backlog)

**Comment by sprankhub** [comment] 2021-04-23 05:10
Shame on you, stale bot!

This is still relevant.

**Comment by josephrisner** [comment] 2021-05-20 19:21
This issue is affecting our store greatly.  We are unable to sort product attributes and those attribute options because of this.

**Comment by bluedarter2** [comment] 2022-02-12 03:00
I'm waiting for a fix, or a work-around, for this too!  I have products with **90** choices in the drop-down, they are dye color names fwiw, and I have **NO WAY** to add a new color name in the middle of the list - which I need to do to keep it in alphabetic order!

**Comment by norgeindian** [comment] 2022-03-14 11:27
Any update here?

**Comment by norgeindian** [comment] 2022-05-09 13:30
This is still an issue on our side.

**Comment by norgeindian** [comment] 2022-06-13 09:10
@sdzhepa , any updates here?

**Comment by norgeindian** [comment] 2022-08-08 05:56
@Team-MediaDivision , well, that is a workaround, but surely not the fix for the original issue.
@sdzhepa , any news reagrding this?

**Comment by sdzhepa** [comment] 2022-08-08 15:17
Hello @norgeindian 

I do not have any updates. I do not work on this task directly just can check and summarise public and internal information.
Priority for the issue was raised to P2. It is still Ready for Development in both backlogs - Community and Internal.
It means that the issue still waiting for developer(s) from Community Contributors or Adobe teams who start progress and propose PR with a fix.

**Comment by norgeindian** [comment] 2022-09-12 12:48
@sdzhepa , thanks for the update. That's better than nothing. Please keep me updated.

**Comment by norgeindian** [comment] 2022-11-07 07:14
@sdzhepa , did the status change or is everything still the same?

**Comment by sdzhepa** [comment] 2022-11-16 16:15
Hello @norgeindian 

As I can see the issue is still in "Progress: ready for dev" and does not have any assigned person
![image](https://user-images.githubusercontent.com/3409584/202233444-9a6fca96-c227-4684-baea-fa708a3cd082.png)

When someone from the public Community or internal team takes it in progress, the status "Progress: ready for dev" will change to something like "Dev in progress"


so, status still the same

**Comment by saurabhnxtgen** [comment] 2023-04-11 21:24
> easy..
> 
> https://magento.stackexchange.com/questions/294869/how-to-remove-pagination-from-customizable-options-backend-in-magento-2
> 
> i've changed the file in vendor directly. because i dont care.
> 
> magento/vendor/magento/module-ui/view/base/web/js/dynamic-rows.js
> 
> search for 20 - replace with 100.. or 1000... upgrade, cache clean, ready.

Legend

**Comment by Kannakiraj123** [comment] 2023-08-29 10:36
@magento I am working on this

**Comment by rogerdz** [comment] 2023-10-25 05:02
Seem like it was fixed by allow the page size to be selected in the custom option
![image](https://github.com/magento/magento2/assets/78783748/d9dc5bbf-be5a-4ec4-9689-11b78f7a295e)

**Comment by engcom-Bravo** [comment] 2024-07-15 06:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-15 06:46
Hi @norgeindian,

Thanks for reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.It was fixed by page size so we can sort.

![New-Product-Products-Inventory-Catalog-Magento-Admin](https://github.com/user-attachments/assets/5fc0b1af-02aa-491b-8fd7-14e157385bf6)


Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-15 06:46 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Reproduced on 2.4.x, Priority: P2, Severity: S3, Triage: Done, Progress: done, Reported on 2.3.4, Area: UI Framework
