### ISSUE TITLE
Bad performance in Salesrules -> Missing index

### ISSUE THREAD

**Issue by Christoph-AK** [magento/magento2#30998] opened 2020-11-20 10:20 UTC
(Magento 2.2.9 CE)

The table salesrule_coupon is missing an index over (is_primary, code). 
That leads to bad performance in the backend, searching salesrule via unique codes. 

Adding the index drops query time from 30+ seconds down to 0.01s. (Increases required disk space of the table by 30%, but I don't care about space.)

Query: 
    SELECT COUNT(*) FROM `salesrule` AS `main_table` LEFT JOIN `salesrule_coupon` AS `rule_coupons` ON main_table.rule_id = rule_coupons.rule_id AND rule_coupons.is_primary = 1 WHERE (`code` LIKE '%TESTCODE%')

We have 12.5 million codes.

(Also the index `IDX_SALESRULE_COUPON_RULE_ID` contains redundant rows already indexed in 'salesrule_coupon_rule_id_is_primary_idx' and can be deleted. Not sure if that one comes from some of my extensions tho.)

Not sure if this is fixed already because i couldn't find index definitions in the code. Just thought I should let someone know.

**Comment by dverkade** [comment] 2021-04-18 20:14
Posting a comment. Issues should not be automatically closed.

**Comment by engcom-Bravo** [comment] 2021-06-18 08:53
Hi @Christoph-AK ,

Could you please add steps to reproduce to this ticket?

**Comment by engcom-Hotel** [comment] 2021-07-08 08:03
Hi @Christoph-AK,

We are unable to hear from you since more than 14 days, so we are closing this issue. If you still facing the issue, then you can reopen this ticket or create a new ticket.

Thanks

**Closed as completed by engcom-Hotel** 2021-07-08 08:03 UTC
Labels: Triage: Dev.Experience, Severity: S2, Issue: needs update
