### ISSUE TITLE
Magento 2 Export not working

### ISSUE THREAD

**Issue by 1amDudman** [magento/magento2#29876] opened 2020-09-02 17:48 UTC
Preconditions (*)
1. Magento version 2.3.5, 2.3.5-p1, 2.3.5-p2

Steps to reproduce (*)
1. Install cron: `php bin/magento cron:install`
2. Exporting products using Magento export in CSV
3. It shows "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file"
4. Start consumers `mage queue:consumers:start exportProcessor`

Expected result (*)
1. Products export CSV file appears in the grid.

Actual result (*)
1. It shows the following message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file" and nothing else. The grid is empty even after 10 times of reloading.
2. It generates clean files with names like importexport_5gt31a8345a69
I already ran php bin/magento cron:run & php bin/magento queue:consumers:start exportProcessor but no result is obtained...

**Comment by engcom-Oscar** [comment] 2020-09-09 13:45
Hi @dukir , thank you for your report. I couldn't reproduce the issue following steps you described in the ticket. Probably it was already fixed by some other PR, can you please recheck it (on clean Magento 2.4-develop branch).

**Comment by engcom-Oscar** [comment] 2020-09-10 07:36
Hi @dukir , thank you for your report. I couldn't reproduce this issue on latest 2.4-develop Magento branch. May you please recheck it?

**Closed as completed** 2020-09-22 10:51 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: done, Reported on 2.3.5-p2
