### ISSUE TITLE
Configurable product's associated product stock is not updated in Magento 2

### ISSUE THREAD

**Issue by DeepPopat** [magento/magento2#11180] opened 2017-10-02 13:53 UTC
Select any configurable product, Then Edit Configuration and change bulk quantity and save configuration and save product. but associative product quantity is not changed its same as old.

### Preconditions

1. Magento 2.1.7
2. Magento 2.1.8
3. Magento 2.1.9
     

### Steps to reproduce
1. Install Magento latest version (Ex: 2.1.9) with sample data.
2. Select configurable product from admin.
3. Then edit the configurable product.
4. Click on "Edit Configurations"
5. Then "Select Attributes" for configurable product Ex. : Color, Size, etc ...
6. Click on "Next" Then select "Attribute Values" for configurable product.
7. Click on "Next" and Goto "Quantity" tab.
8. Select option "Apply unique quantity by attribute to each SKU"
9. Select attribute from drop down
10. set Quantity Ex. : 101 (that is different than old set quantity)
11. Same For all attribute.
12. Click on "Next" and Click On Save

### Expected result
1. All product Quantity is 101

### Actual result
1. All product quantity is 100(Its old quantity)

For your better understanding, I have attached some screenshots of my local Magento
### Product Quantity Before Edit
![product_quentity_befor_edit](https://user-images.githubusercontent.com/32391312/31080576-b2425b78-a7a6-11e7-85b7-12b93623ba00.png)

### Product Quantity At the time of Editing
![product_quentity_time_edit](https://user-images.githubusercontent.com/32391312/31080701-187cfb14-a7a7-11e7-90e2-447ff3f52e6f.png)

### Product Quantity After Save
![product_quentity_after_save](https://user-images.githubusercontent.com/32391312/31080708-22abd074-a7a7-11e7-8542-03a8aa725843.png)

**Comment by magento-engcom-team** [comment] 2017-10-02 15:30
@DeepPopat, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-02 15:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by congaframe** [comment] 2017-11-09 19:52
Hi
Any idea how to fix this issue? I'd like to back-port it to 2.1.x

**Comment by tuyennn** [comment] 2018-04-23 03:49
Is there any reference to fixed commits?

**Comment by babyasishhira** [comment] 2018-06-11 12:11
Please suggest a commit

**Comment by DeepPopat** [comment] 2018-06-11 12:36
Sorry, I have no idea about the solution.
