### ISSUE TITLE
Class \Magento\Framework\Data\Form\Element\Fieldset breaks specification of the parent class \Magento\Framework\Data\Form\Element\AbstractElement by not calling the method getBeforeElementHtml (getAfterElementHtml is called)

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2618] opened 2015-12-05 23:07 UTC
https://mage2.pro/t/248

See also: https://github.com/magento/magento2/issues/2202, https://github.com/magento/magento2/issues/2615

**Comment by shiftedreality** [comment] 2016-01-14 15:21
Hi @dfediuk 

Internal ticket MAGETWO-47934 was created for this issue

**Comment by magento-engcom-team** [comment] 2017-10-25 06:03
@dmitry-fedyuk, thank you for your report.
We've created internal ticket(s) MAGETWO-47934 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-10-25 07:46
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by okorshenko** [comment] 2018-10-31 20:08
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#18798 by @vasilii-b in 2.3-develop branch
Related commit(s):
 - [069195ce52b458f6ec9dbcc2907c27722e0f7990](https://github.com/magento/magento2/commit/069195ce52b458f6ec9dbcc2907c27722e0f7990)

The fix will be available with the upcoming 2.3.1 release.

**Comment by magento-engcom-team** [comment] 2018-11-07 17:34
Hi @dmitry-fedyuk. Thank you for your report. 
The issue has been fixed in magento/magento2#18985 by @vasilii-b in 2.2-develop branch
Related commit(s):
 - [66294452bd0fc6bcadc7360c438da79ca1f6c314](https://github.com/magento/magento2/commit/66294452bd0fc6bcadc7360c438da79ca1f6c314)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-11-07 17:34 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid, Progress: PR Created
