### ISSUE TITLE
magento 2.3.3  suggesting numerous zendframeworks and other extensions

### ISSUE THREAD

**Issue by Sharlyll** [magento/magento2#25567] opened 2019-11-12 09:54 UTC
### Preconditions (*)

1. Magento 2.3.3. Fresh install
2.  cloud server. (No preinstalled packages)
3. Ubuntu 18.04
4. Apache 2
5. Standard PHP extensions installed
6. php 7.2

### Steps to reproduce (*)

1. Install all php required extensions ( sudo apt-get install sudo apt-get install php7.2 libapache2-mod-php7.2 php7.2-mysql php7.2-soap php7.2-bcmath php7.2-xml php7.2-mbstring php7.2-gd php7.2-common php7.2-cli php7.2-curl php7.2-intl php7.2-zip zip unzip -y)

2.  install magento2.3.3 via composer

### Expected result (*)

1.error and warning free installation on terminal
2. full functional magento 2.3.3

### Actual result (*)

1. warning after magento 2.3.3 installation via composer
2. see warning here:

zendframework/zend-validator suggests installing zendframework/zend-i18n-resources (Translations of validator messages)
zendframework/zend-http suggests installing paragonie/certainty (For automated management of cacert.pem)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 0.5.* to handle lazy initialization of services)
zendframework/zend-filter suggests installing psr/http-factory-implementation (psr/http-factory-implementation, for creating file upload instances when consuming PSR-7 in file upload filters)
zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (in order to use the ReCaptcha form element)
zendframework/zend-mvc suggests installing zendframework/zend-authentication (Zend\Authentication component for Identity plugin)
zendframework/zend-mvc suggests installing zendframework/zend-servicemanager-di (^1.0.1, if using zend-servicemanager v3 and requiring the zend-di integration)
zendframework/zend-math suggests installing ext-gmp (If using the gmp functionality)
zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if Mcrypt extensions is unavailable)
zendframework/zend-crypt suggests installing ext-mcrypt (Required for most features of Zend\Crypt)
symfony/console suggests installing symfony/lock
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
magento/framework suggests installing ext-imagick (Use Image Magick >=3.0.0 as an optional alternative image processing library)
magento/module-widget suggests installing magento/module-widget-sample-data (Sample Data version: 100.3.*)
magento/module-theme suggests installing magento/module-theme-sample-data (Sample Data version: 100.3.*)
zendframework/zend-session suggests installing mongodb/mongodb (If you want to use the MongoDB session save handler)
zendframework/zend-session suggests installing zendframework/zend-cache (Zend\Cache component)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
zendframework/zend-captcha suggests installing zendframework/zend-i18n-resources (Translations of captcha messages)
zendframework/zend-captcha suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
magento/module-wishlist suggests installing magento/module-wishlist-sample-data (Sample Data version: 100.3.*)
magento/module-customer suggests installing magento/module-customer-sample-data (Sample Data version: 100.3.*)
magento/module-sales suggests installing magento/module-sales-sample-data (Sample Data version: 100.3.*)
magento/module-tax suggests installing magento/module-tax-sample-data (Sample Data version: 100.3.*)
magento/module-sales-rule suggests installing magento/module-sales-rule-sample-data (Sample Data version: 100.3.*)
magento/module-cms suggests installing magento/module-cms-sample-data (Sample Data version: 100.3.*)
magento/module-catalog suggests installing magento/module-catalog-sample-data (Sample Data version: 100.3.*)
magento/module-msrp suggests installing magento/module-msrp-sample-data (Sample Data version: 100.3.*)
magento/module-downloadable suggests installing magento/module-downloadable-sample-data (Sample Data version: 100.3.*)
magento/module-grouped-product suggests installing magento/module-grouped-product-sample-data (Sample Data version: 100.3.*)
magento/module-catalog-rule suggests installing magento/module-catalog-rule-sample-data (Sample Data version: 100.3.*)
magento/module-review suggests installing magento/module-review-sample-data (Sample Data version: 100.3.*)
magento/module-asynchronous-operations suggests installing magento/module-logging (101.1.*)
magento/module-bundle suggests installing magento/module-bundle-sample-data (Sample Data version: 100.3.*)
magento/module-configurable-product suggests installing magento/module-configurable-sample-data (Sample Data version: 100.3.*)
magento/module-configurable-product suggests installing magento/module-product-links-sample-data (Sample Data version: 100.3.*)
symfony/property-access suggests installing psr/cache-implementation (To cache access methods.)
magento/module-inventory-requisition-list suggests installing magento/module-requisition-list (*)
magento/module-inventory-advanced-checkout suggests installing magento/module-advanced-checkout (*)
vertex/module-tax suggests installing magento/module-gift-wrapping (Vertex Tax Links for Magento 2 also supports Magento's Gift Wrapping module)
vertex/module-tax suggests installing magento/module-gift-card-account (Vertex Tax Links for Magento 2 also supports Magento's Gift Card Account module)
vertex/module-tax suggests installing magento/module-reward (Vertex Tax Links for Magento 2 also supports Magento's Reward module)
zendframework/zend-barcode suggests installing zendframework/zendpdf (ZendPdf component)
temando/module-shipping-m2 suggests installing magento/module-rma (^101.1.0)
temando/module-shipping-m2 suggests installing magento/module-scalable-checkout (^100.3.0)
temando/module-shipping-m2 suggests installing magento/module-scalable-oms (^100.3.0)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
amzn/amazon-pay-module suggests installing magento/module-scalable-checkout (*)
amzn/amazon-pay-module suggests installing magento/module-scalable-oms (*)
magento/module-swatches suggests installing magento/module-swatches-sample-data (Sample Data version: 100.3.*)
magento/module-sample-data suggests installing magento/sample-data-media (Sample Data version: 100.3.*)
magento/module-offline-shipping suggests installing magento/module-offline-shipping-sample-data (Sample Data version: 100.3.*)
zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
zendframework/zend-view suggests installing zendframework/zend-authentication (Zend\Authentication component)
zendframework/zend-view suggests installing zendframework/zend-mvc-plugin-flashmessenger (zend-mvc-plugin-flashmessenger component, if you want to use the FlashMessenger view helper with zend-mvc versions 3 and up)
zendframework/zend-view suggests installing zendframework/zend-navigation (Zend\Navigation component)
zendframework/zend-view suggests installing zendframework/zend-paginator (Zend\Paginator component)
zendframework/zend-view suggests installing zendframework/zend-permissions-acl (Zend\Permissions\Acl component)
zendframework/zend-log suggests installing ext-mongo (mongo extension to use Mongo writer)
zendframework/zend-log suggests installing ext-mongodb (mongodb extension to use MongoDB writer)
zendframework/zend-i18n suggests installing zendframework/zend-cache (Zend\Cache component)
zendframework/zend-i18n suggests installing zendframework/zend-i18n-resources (Translation resources)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/event-dispatcher suggests installing symfony/http-kernel
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
paragonie/sodium_compat suggests installing ext-libsodium (PHP < 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
consolidation/output-formatters suggests installing symfony/var-dumper (For using the var_dump formatter)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
facebook/webdriver suggests installing ext-SimpleXML (For Firefox profile creation)
codeception/codeception suggests installing aws/aws-sdk-php (For using AWS Auth in REST module and Queue module)
codeception/codeception suggests installing codeception/specify (BDD-style code blocks)
codeception/codeception suggests installing codeception/verify (BDD-style assertions)
codeception/codeception suggests installing codeception/phpbuiltinserver (Start and stop PHP built-in web server for your tests)
codeception/codeception suggests installing league/factory-muffin (For DataFactory module)
codeception/codeception suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/codeception suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
codeception/codeception suggests installing stecman/symfony-console-completion (For BASH autocompletion)
magento/magento2-functional-testing-framework suggests installing epfremme/swagger-php (^2.0)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-isidenticalstring (For IsIdenticalString constraint.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-xmlmatchesxsd (For XmlMatchesXsd constraint.)
lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

**Comment by engcom-Charlie** [comment] 2019-11-14 16:26
Hello @Sharlyll 
We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.
I did not have errors after installation.
So i have to close this issue.

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-14 16:26 UTC
Labels: Issue: Format is valid

**Comment by Sharlyll** [comment] 2019-11-15 11:31
Hi @engcom-Charlie  I am new to installing magento2 on a clean cloud bare server. perhaps I am missing some php or zendframework packages before magento2 installation. could you tell me what packages you have on your server? 

best regards

**Comment by engcom-Charlie** [comment] 2019-11-15 12:07
**PHP:**
ii  php7.2                                     7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.2-bcmath                              7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Bcmath module for PHP
ii  php7.2-cli                                 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                              7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        documentation, examples and common module for PHP
ii  php7.2-curl                                7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        CURL module for PHP
ii  php7.2-fpm                                 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.2-gd                                  7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        GD module for PHP
ii  php7.2-intl                                7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Internationalisation module for PHP
ii  php7.2-json                                7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        JSON module for PHP
ii  php7.2-mbstring                            7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        MBSTRING module for PHP
ii  php7.2-mysql                               7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        MySQL module for PHP
ii  php7.2-opcache                             7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Zend OpCache module for PHP
ii  php7.2-readline                            7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        readline module for PHP
ii  php7.2-soap                                7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        SOAP module for PHP
ii  php7.2-xml                                 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-xsl                                 7.2.24-1+ubuntu16.04.1+deb.sury.org+1                    all          XSL module for PHP (dummy)
ii  php7.2-zip 
**Autoload section of composer.json:**
 "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        }

**Comment by Sharlyll** [comment] 2019-11-16 03:04
@engcom-Charlie O thanks! This helps a whole lot! My server is on Ubuntu 18.0.4. I will cross check the other packages and leave feedback here incase some newbie like my humble self faces same issue. 
I appreciate.
