### ISSUE TITLE
One of our administrators in unable to save any changes

### ISSUE THREAD

**Issue by amyprt** [magento/magento2#39051] opened 2024-08-15 17:40 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

User Wanda@portablerestroomtrailers.com logs in. Goes to make a change to a product listing. Clicks "Save" nothing happens.

### Expected result

The expectation is for the changes to be saved.

### Actual result

Nothing happens even though she has admin access/priviledges

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-08-16 13:22
Hi @amyprt,

Thanks for your reporting and collaboration.
We have verified the issue in latest 2.4-develop instance, but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**
1. Create a admin user and provide full access to its user role.
![image](https://github.com/user-attachments/assets/13f7a689-702b-42b2-8f83-57cd55d7dd82)
2. Access Catalog>Products
3. Select products and change the status. 

https://github.com/user-attachments/assets/844c74bc-2069-4833-8080-b7bc94b7c41e


4. Observe user is able to save status, create or edit a product successfully. 

https://github.com/user-attachments/assets/f723c588-c90e-4c92-9163-97ce3c8c21c6

Please let us know if any other steps are needed to be performed.

Thanks.

**Comment by amyprt** [comment] 2024-08-16 14:07
Thank you for your help! I don't see the option for "Role Resources", only "User Role". See screenshot.
![Screenshot 2024-08-16 at 10 06 18 AM](https://github.com/user-attachments/assets/0eb86335-ce0d-4e15-9f33-72ed77b43b8c)

**Comment by engcom-Delta** [comment] 2024-08-20 07:19
Hi @amyprt ,

Please follow below navigation to access user roles : 
1. Access Admin
2. Navigate to System > Permissions > User Roles
3. Create a new role or select an existing role
4. Select Role Resources
![image](https://github.com/user-attachments/assets/0b563576-c1b9-47bb-8842-119d330349d3)
5. Select 'Resource Access' as All or Custom.
![image](https://github.com/user-attachments/assets/bfa2e5f0-a00b-4e3d-a54a-e003f29dd498)

Thanks.

**Comment by engcom-Delta** [comment] 2024-09-02 11:10
Hi @amyprt ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-09-02 11:10 UTC
Labels: Issue: needs update, Reported on 2.4.x
