### ISSUE TITLE
Magento 2.1.7 - weird js translations caching (?)

### ISSUE THREAD

**Issue by Bartlomiejsz** [magento/magento2#9888] opened 2017-06-09 05:19 UTC
### Preconditions
1. Magento 2.1.7
2. Multiple store views (i.e. one with English language, second with German)
3. Production mode (online version)

### Steps to reproduce
1. Go to contact form on english version.
2. Try to submit form.
3. See validation error.
4. Switch to german version.
5. Try to submit form.
6. See validation error.

### Expected result
1. On english and german version there should be different translations for validation text.

### Actual result
1. On each version you can see 'Dies ist ein Pflichtfeld.' (german translation).

Translation cache is turned off, so I don't know what caused this...

**Comment by hostep** [comment] 2017-06-09 06:03
This sounds like a duplicate of: https://github.com/magento/magento2/issues/7862

Make sure you run:
```
php bin/magento setup:static-content:deploy de_DE
php bin/magento setup:static-content:deploy en_US
```
separately and **not**:
```
php bin/magento setup:static-content:deploy de_DE en_US
```
because this last command will have the effect you are experiencing right now.

**Comment by veloraven** [comment] 2017-06-09 08:15
@Bartlomiejsz thank you for your report.
But I’m closing this issue because it is a duplicate of #7862.
We already have internal ticket MAGETWO-63309 and this issue should be fixed in one of next patch releases.

**Closed as completed by veloraven** 2017-06-09 08:15 UTC
