### ISSUE TITLE
Block not shown inside a page

### ISSUE THREAD

**Issue by nsid32** [magento/magento2#9528] opened 2017-05-05 12:52 UTC
### Preconditions
1. Magento 2.1.6 

### Steps to reproduce
1. Create a block through Admin UI in magento
2. Reference this block inside a Page through "Layout update XML" using the following:
```
<referenceContainer name="page.top">
    <block class="Magento\Cms\Block\Block" name="home_slider">
        <arguments>
            <argument name="block_id" xsi:type="string">homeslider_5_en</argument>
        </arguments>
    </block>
</referenceContainer>
```

### Expected result
1. The block should appear when navigating to this page

### Actual result
1. The page appears without the block

If I use a pre-existing block from the template bought, the block shows correctly.
If I use a newly created block, the new block doesn't show.

Thanks!

**Comment by korostii** [comment] 2017-05-05 17:08
There is a number of things that might've go wrong, for example your theme (template) just might not have a container called "page.top" in its layout.
I'd recommend that you check your Magento's logs for errors first. (Read [here](https://mage2.pro/t/topic/307) on how to find those)

On a side note, if you are looking for some help or an advice regarding setup or development I would advise you to use the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

**Comment by nsid32** [comment] 2017-05-05 17:26
Thanks for your reply @korostii 
What is weird to me is that if I have a page and I reference an existing block there it works but if I reference a newly created block, it doesn't.
So we are actually talking about the same code on the same page but different block_id

Works
```

<referenceContainer name="page.top">
    <block class="Magento\Cms\Block\Block" name="home_slider">
        <arguments>
            <argument name="block_id" xsi:type="string">**existing_template_block**</argument>
        </arguments>
    </block>
</referenceContainer>
```

Doesn't work
```
<referenceContainer name="page.top">
    <block class="Magento\Cms\Block\Block" name="home_slider">
        <arguments>
            <argument name="block_id" xsi:type="string">**newly_created_block**</argument>
        </arguments>
    </block>
</referenceContainer>
```
Also the two blocks are exactly the same in content, they just have different id.
For some reason it seems that the two blocks are different.

**Comment by devamitbera** [comment] 2017-05-05 19:53
**Are u  sure that you have flushed cache properly?**

Please change the name="home_slider" to any other name.And flush the cache using 

> bin/maegento cache:flush

**Comment by nsid32** [comment] 2017-05-05 19:56
@devamitbera through the admin panel -> Cache Management I have clicked all the options.
I don't know if there is any other way to flush.
Thanks

**Comment by devamitbera** [comment] 2017-05-05 20:00
http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cache.html follow the blog 

Or  please post at the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange.](https://magento.stackexchange.com)

**Comment by nsid32** [comment] 2017-05-05 20:02
@devamitbera i did that also but still not showing

**Comment by korostii** [comment] 2017-05-08 07:40
> Also the two blocks are exactly the same in content, they just have different id.

Since this is clearly not a bug, but probably a misconfiguration, I would yet again refer you to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) where your question will be seen by a lot more people how's eager to help. Please provide as much info as you can while doing so: screenshots are very useful in this purpose and are worth a thousand words. 

The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only. 
Your issue isn't likely to get resolved in here.

**Comment by magento-engcom-team** [comment] 2017-10-19 08:36
@nsid32, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Closed as completed** 2017-10-19 08:37 UTC
Labels: Issue: Clear Description, non-issue, Issue: Format is valid
