### ISSUE TITLE
Composer install on cleanly created project fails

### ISSUE THREAD

**Issue by dmanners** [magento/magento2#34972] opened 2022-01-14 10:13 UTC
### Preconditions (*)

1. Composer version 2.1.14 or 2.2.4
2. Have the composer json from running create-project --repository-url=https://repo.magento.com/ magento/project-community-edition <install-directory-name>

### Steps to reproduce (*)

1. Run composer install

### Expected result (*)

1. Clean installation of Magento2

### Actual result (*)

```
  [Exception]                                                                                                                                   
  Higher matching version 1.8.0 of magento/composer was found in public repository packagist.org                                                
                               than 1.7.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
            please investigate and update package requirement to match the version from the private repository     
```

It seems like the version in repo.magento is older than the version publicly available on packagist.org. https://packagist.org/packages/magento/composer has version 1.8.0 but repo.magento seems to only have version 1.7.x

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dmanners** [comment] 2022-01-14 11:36
Seems to be linked to https://github.com/magento/composer/issues/33

**Comment by ihor-sviziev** [comment] 2022-01-14 15:48
Hi @dmanners,
Yeah, it was a duplicate of https://github.com/magento/composer/issues/33 that is already fixed https://github.com/magento/composer/issues/33#issuecomment-1013237236.

**Comment by sdzhepa** [comment] 2022-01-14 16:03
The issue is already fixed and fix was confirmed https://github.com/magento/composer/issues/33#issuecomment-1013237236
I assume we can close this issue as already fixed

**Closed as completed by sdzhepa** 2022-01-14 16:03 UTC
Labels: duplicate, Fixed in 2.4.x, Priority: P0, Progress: done
