### ISSUE TITLE
Cannot get correct response from API use OR condition

### ISSUE THREAD

**Issue by iproger** [magento/magento2#12899] opened 2017-12-28 00:07 UTC
### Preconditions
1. Magento 2.2.2 CE, php 7.1.

### Steps to reproduce
1. `GET` to API `/customers/search` with parameters.
```json
"search_criteria": {
    "filter_groups": [
        {
            "filters": [
                {
                    "field": "company",
                    "value": "%%",
                    "condition_type": "like"
                },
                {
                    "field": "company_name",
                    "value": "%%",
                    "condition_type": "like"
                }
            ]
        }
    ]
}
```

`company` is default magento attribute in customer address,` company_name` I created for customer entity.

Using the m2 [documentation](http://devdocs.magento.com/guides/v2.2/rest/performing-searches.html)
### Expected result
Search where `company` like `%%` OR `company_name` like `%%`.

### Actual result
Empty result. I noticed magento require filled `company_name` in customers. If I add any string in my custom field, magento returns this row without a problems even if the condition is not correct for this part of rule (expected result).

**Comment by magento-engcom-team** [comment] 2017-12-28 11:26
Hello @iproger. Thanks for reporting. If we understand Your case  correctly it may have the following explanation. You see when You save an entity (in our case a customer) with empty text fields that aren't the required ones these fields are having been recorded into database with values equal to NULL. Now according to SQL documentation "%" in queries with "LIKE" stands for "zero, one or multiple characters". NULL is neither of those three. Thus You don't get the result You expect because Your  empty field, that in fact is not an empty string but a NULL does not match Your "LIKE" conditions. If in database You change the value of Your field from NULL to even just an empty string ("") You will get the result You expect. Please tell us do we understand You right.

**Comment by magento-engcom-team** [comment] 2017-12-29 14:51
@iproger, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by iproger** [comment] 2017-12-29 19:43
@magento-engcom-team Hello. Ok, currently I know about NULL and like, thank you. I just want to search in first **OR** second field. If I try to use `like` for empty (NULL) field, I have empty result.

### Example 1:
| Customer 1 | |
| --- | --- |
| company | |
| company_name | Test |

`GET` customers where company like test OR company_name like test
#### Result => customer1.

### Example 2:
| Customer 2 | |
| --- | --- |
| company | Test |
| company_name | |

`GET` customers where company like test OR company_name like test
#### Result => [empty].

I hope you understood the problem with custom fields. Magento fields works currect.

**Comment by magento-engcom-team** [comment] 2018-01-03 10:07
@iproger 
Please provide us the steps on how you created your attribute "company_name" in table "customer entity".

**Comment by iproger** [comment] 2018-01-06 00:26
@magento-engcom-team 
```php
/**
 * {@inheritdoc}
 */
public function install(
    ModuleDataSetupInterface $setup,
    ModuleContextInterface $context
) {
    $setup->startSetup();

    /** @var CustomerSetup $customerSetup */
    $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);

    $customerEntity = $customerSetup->getEavConfig()->getEntityType('customer');
    $attributeSetId = $customerEntity->getDefaultAttributeSetId();

    /** @var $attributeSet AttributeSet */
    $attributeSet = $this->attributeSetFactory->create();
    $attributeGroupId = $attributeSet->getDefaultGroupId($attributeSetId);

    $customerSetup->addAttribute(Customer::ENTITY, 'company_name', [
        'type' => 'varchar',
        'label' => 'Company',
        'input' => 'text',
        'required' => false,
        'visible' => true,
        'user_defined' => true,
        'sort_order' => 1000,
        'position' => 1000,
        'system' => 0,
    ]);
    $attribute = $customerSetup->getEavConfig()->getAttribute(Customer::ENTITY, 'company_name')
        ->addData([
            'attribute_set_id' => $attributeSetId,
            'attribute_group_id' => $attributeGroupId,
            'used_in_forms' => ['adminhtml_customer'],
        ]);
    $attribute->save();

    $setup->endSetup();
}
```

**Comment by magento-engcom-team** [comment] 2018-01-15 08:07
@iproger, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2019-12-27 13:52
@engcom-Bravo Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by engcom-Bravo** [comment] 2019-12-27 13:57
Rechecked on Magento 2.4-develop via Swagger. The response is
```
{
  "message": "The \"%1\" attribute name is invalid. Reset the name and try again.",
  "parameters": [
    "company"
  ]
}
```

**Comment by magento-engcom-team** [comment] 2019-12-30 10:26
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30126` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by chirag-d-wagento** [comment] 2020-10-10 06:04
@magento i'm working on it

**Comment by chirag-d-wagento** [comment] 2020-10-10 07:39
Issue is not reproduce in 2.4

URL is http://127.0.0.1/magento-ce-2.4-develop/rest/all/V1/customers/search?searchCriteria[filterGroups][0][filters][0][field]=company_name&searchCriteria[filterGroups][0][filters][0][value]=mycompany&searchCriteria[filterGroups][0][filters][0][field]=company&searchCriteria[filterGroups][0][filters][0][value]=mycompany

Giving error below

The company attribute name is invalid.

I think because company is address attribute customers/search not allowing it.

**Comment by engcom-November** [comment] 2022-04-28 09:25
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-28 09:48
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
On searching with any other string - getting invalid error message in the response: "The \"%1\" attribute name is invalid. Reset the name and try again."
![image](https://user-images.githubusercontent.com/60198231/165726025-5a720bb2-9955-42de-a15a-35262ed68387.png)

On searching using field: name - getting 200 status code with below response:
![image](https://user-images.githubusercontent.com/60198231/165726257-939bdc5a-5597-4496-ae0c-a14c7203f778.png)

**Closed as completed** 2022-05-06 12:54 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Api, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P1, Severity: S1, Progress: done, CD, Area: APIs
