### ISSUE TITLE
Magento 2.3.2 : Warning during di compile - Reference to undeclared plugin with name 'stockedProductsFilterPlugin'

### ISSUE THREAD

**Issue by ameshca** [magento/magento2#23724] opened 2019-07-16 11:02 UTC
### Preconditions (*)

1. Magento 2.3.2(composer install)

### Steps to reproduce (*)

1. Do the di compile - bin/magento s:d:c

### Expected result (*)

1. Complete the compilation without any warnings and errors

### Actual result (*)

1. While compiling its showing the warning as "Reference to undeclared plugin with name 'stockedProductsFilterPlugin'"(the warning is being outputted in the files var/log/system.log and var/log/debug.log)

When i debugged this case and i found that in Magento 2.3.0 there was a plugin available with this name in 'module-elasticsearch' module and in Magento 2.3.2 that plugin is removed from the module. But in the module 'module-inventory-elasticsearch' we found a code to disable that plugin like below
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
<type name="Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider">
    <plugin name="stockedProductsFilterPlugin" disabled="true"/>
    <plugin name="stockedProductFilterByInventoryStockPlugin" type="Magento\InventoryElasticsearch\Plugin\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider\StockedProductFilterByInventoryStock"/>
</type>`
but no such plugin definition is currently existing, so this shows the warning message.

**Comment by engcom-Charlie** [comment] 2019-07-16 11:36
Hello @ameshca ! Thank you for your report !
I was not able to reproduce this issue on Vanilla Magento instance . I`m closing it for now but feel free to reopen it in case you can confirm that this issue is reproducible on Vanilla instance . Also you can refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
Thanks !

**Comment by gaurangpadhiyar007** [comment] 2019-07-26 09:49
@engcom-Charlie @ameshca 
Re-open this issue still present in magento 2.3.2  asper provieded steps by 


> ### Preconditions (*)
> 1. Magento 2.3.2
> 
> ### Steps to reproduce (*)
> 1. Do the di compile - bin/magento s:d:c
> 
> ### Expected result (*)
> 1. Complete the compilation without any warnings and errors
> 
> ### Actual result (*)
> 1. While compiling its showing the warning as "Reference to undeclared plugin with name 'stockedProductsFilterPlugin'"
> 
> When i debugged this case and i found that in Magento 2.3.0 there was a plugin available with this name in 'module-elasticsearch' module and in Magento 2.3.2 that plugin is removed from the module. But in the module 'module-inventory-elasticsearch' we found a code to disable that plugin like below
> `<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd"> <type name="Magento\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider"> <plugin name="stockedProductsFilterPlugin" disabled="true"/> <plugin name="stockedProductFilterByInventoryStockPlugin" type="Magento\InventoryElasticsearch\Plugin\CatalogSearch\Model\Indexer\Fulltext\Action\DataProvider\StockedProductFilterByInventoryStock"/> </type>`
> but no such plugin definition is currently existing, so this shows the warning message.

**Comment by engcom-Charlie** [comment] 2019-07-26 10:39
Hi, @gaurangpadhiyar007 ! I check it. Result:
![image](https://user-images.githubusercontent.com/51680850/61946155-83ad8900-afaa-11e9-9686-d0d5d8ff7e23.png)

**Comment by hostep** [comment] 2019-07-26 11:37
@engcom-Charlie: I can reproduce, but the reporter failed to mention that the warning is being outputted in the files `var/log/system.log` and `var/log/debug.log`. Can you check those log files as well?

**Comment by engcom-Charlie** [comment] 2019-07-26 11:48
Hi, @hostep ! Thank you for contributing. But i can't find same errors in my logs...

**Comment by hostep** [comment] 2019-07-26 11:52
Have you installed Magento using composer?
The problematic code is in the [Magento_InventoryElasticsearch module (part of MSI)](https://github.com/magento/inventory/blob/d956bd063d2d35f75c58c0e48cdfa31db28b4efd/app/code/Magento/InventoryElasticsearch/etc/di.xml#L10)

Or should this issue be moved over to https://github.com/magento/inventory/issues ?

Plugin was removed in this commit btw: https://github.com/magento/magento2/commit/9ab466d8569#diff-b6e582265c05aea3ea399da8d02d4e1b (introduced in 2.3.2)

**Comment by engcom-Charlie** [comment] 2019-07-26 12:07
@hostep , i tested on not composer version. Now i wont to try on composer.

**Comment by engcom-Charlie** [comment] 2019-07-26 12:36
@hostep , i reproduce it now. I will change description.
Thank you about contributing!

**Comment by engcom-Charlie** [comment] 2019-07-26 12:45
Hi @ameshca  ! Thank you for your report.
I suppose it could be related to Multi-source Inventory Modules.
You could create this issue with details in the https://github.com/magento/inventory/issues .

**Closed by engcom-Charlie** 2019-07-26 12:45 UTC
Labels: Component: Elasticsearch, Issue: Clear Description, Issue: Format is valid

**Comment by hostep** [comment] 2019-07-31 20:06
@sdzhepa: I saw you transfering over another ticket automatically to the MSI project, could you maybe do the same with this one and reopen it at the same time?
And maybe the engcom military squad can also get the rights to do this? (if they don't already have the rights)

Thanks!

**Comment by melaniajitaru** [comment] 2019-09-25 15:03
Hi @engcom-Charlie ! 

Do you have any news about this report? I have the same problem.

Thanks!

**Comment by sdzhepa** [comment] 2019-09-25 21:17
Hello @ameshca @hostep @melaniajitaru 

I have clarified this issue with Magento Inventory(MSI) team.
They said it already fixed and will be available with next release.

At this moment I move the issue into Inventory repo as is and will try to provide more details(PRs, commits etc) when found this info
