### ISSUE TITLE
Checkout/cart/product pages price and shipping zero values after upgrade from 2.2.8 to 2.4.3

### ISSUE THREAD

**Issue by operations1** [magento/magento2#34799] opened 2021-12-12 18:14 UTC
Preconditions (*)

    Magento CE upgraded to 2.4.3
    Nginx
    PHP 7.4

Steps to reproduce (*)

    1. Upgrade Magento from 2.2.8 to 2.4.3
    2. Re-index everything and clear all caches
    3. Go to product, cart and one step checkout pages

Expected result (*)

    Correct prices, order totals and shipping fees

Actual result (*)

    Zero product price and shipping (0.00). Checkout order subtotal, grand total, shipping and everything in summary or cart page (not popup) are showing zero values. Switched to Luma theme, but its still showing the same.

**Comment by ihor-sviziev** [comment] 2021-12-14 17:19
Hi @operations1,
It looks like this is a duplicate of https://github.com/magento/magento2/issues/33856 that was already fixed in the 2.4-develop branch. For more info, please check https://github.com/magento/magento2/issues/33856#issuecomment-946761019

**Comment by samma3a-dev** [comment] 2021-12-17 22:33
> Hi @operations1, It looks like this is a duplicate of #33856 that was already fixed in the 2.4-develop branch. For more info, please check [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-946761019)

Thanks Ihor. So I need to upgrade to 2.4-develop branch in order to fix it?

**Comment by operations1** [comment] 2021-12-17 22:39
> Hi @operations1, It looks like this is a duplicate of #33856 that was already fixed in the 2.4-develop branch. For more info, please check [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-946761019)

Thanks @ihor-sviziev. So I need to upgrade from 2.4.3 to 2.4-develop branch in order to fix it?

**Comment by ihor-sviziev** [comment] 2021-12-18 07:18
@operations1, you can apply that fix as a patch

**Comment by ihor-sviziev** [comment] 2021-12-18 10:46
Hi @operations1,
I'm closing this issue as a duplicate of https://github.com/magento/magento2/issues/33856

**Closed as completed** 2021-12-18 10:47 UTC
Labels: duplicate, Issue: needs update
