### ISSUE TITLE
PaymentMethod If Discount cancel. When Discount Applies, No Payment 

### ISSUE THREAD

**Issue by vasusundar** [magento/magento2#29060] opened 2020-07-09 15:08 UTC
### Preconditions (*)

1. Install Magento 2.3.5
2. Configure Cart Rule to apply discount in checkout page.
3. Enable Free Shipping Method and any 2 Payment Method.(COD, Check & Money Order)

### Steps to reproduce (*)

1. Product Total amount is $100. Shipping Method is Free. $0.00
2. Apply Discount coupon, then No Payment method will display, because total amount is $0.00
3. Cancel Discount coupon.

### Expected result (*)

1. Discount need to be cancel
2. Payment Method need to display to proceed place order

### Actual result (*)

1. After Cancel Discount coupon , then loader will show infinity,but in console, there is an error like paymentMethod is null

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-07-09 18:18
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-09 18:18
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment] 2020-07-10 17:28
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-10 17:28
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by 7865fug** [comment] 2020-07-13 09:52
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-13 09:53
Hi @7865fug. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by ajijshekh123** [comment] 2020-07-14 17:36
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-14 17:36
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-14 17:38
Hi @ajijshekh123, here is your [Magento instance](https://i-29060-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29060-2-4-develop.instances.magento-community.engineering/admin_5753](https://i-29060-2-4-develop.instances.magento-community.engineering/admin_5753)
Login: `cf90c5ca` Password: `69eff9871329`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-07-14 18:06
Hello @vasusundar,
I have followed your steps to be reproduced, actual result and expected result but not able to reproduce this issue on Default Magento 2.4 Instance.
It is stuck for a few seconds but after a few seconds its working fine.
See attached the video and screenshot:

![Checkout](https://user-images.githubusercontent.com/24711761/87460553-abb65200-c62a-11ea-96c7-4265f1381dcf.png)

![Untitled_ Jul 14, 2020 11_21 PM](https://user-images.githubusercontent.com/24711761/87460578-b40e8d00-c62a-11ea-8cdf-0250d97c84ac.gif)

Thanks.

**Comment by ajijshekh123** [comment] 2020-07-17 18:44
@vasusundar - Any Update. If this issue is fixed Please let me know so I will close this issue.

**Comment by vasusundar** [comment] 2020-07-18 03:04
@ajijshekh123  Hope latest version has resolved the issue, but i am getting an issue in Magento2.3.5 Version , Let me recheck in old version

**Comment by ajijshekh123** [comment] 2020-07-21 06:21
Hi... @vasusundar,
Please upgrade your Magento Version Or Please verify this issue on Old Magento Version.
If this issue reproduced again you can reopen it.

Thanks.

**Closed as completed by ajijshekh123** 2020-07-21 06:21 UTC
Labels: Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Format is valid, Component: Rule, Reported on 2.3.5

**Comment by chequille** [comment] 2020-07-26 17:50
Facing same problem.
Will it be fixed in 2.4.x?
By the way, do not understand why you let us test things on a 2.4-develop instance. We have the problems on 2.3.5 version.
Therefore, is it possible to install a 2.4-develop version on my own server?
If yes, let me know.

**Comment by chequille** [comment] 2020-07-28 18:20
THis is not solve in 2.3.5-p2
Owner of the issue, please re-open it.

**Comment by chequille** [comment] 2020-07-28 19:06
@vasusundar 
Hi, it is a shame that such easy things are not solved within 2.3.5-p2. But I tried with the script from 2.4.x and it works as well within 2.3.5-p2.
So, the solution is to use select-payment-method-mixins.js from 2.4.x and replace the file in 2.3.5-p2 (I guess as well in 2.3.5-p1). Of course the better way to override it in our theme. Path is Magento_SalesRules/web/js/action
It works on my site.
Just a personal comment: we have to find the solutions for the bugs ourselves !!!!
Regards
Chequille

**Comment by chequille** [comment] 2020-07-29 05:12
I am sorry, the information above is not 100% correct.
It is working if total 0, but if total is not 0 I am getting an error payment method not valid when finishing the order and it is not processed.
I am working on this, maybe I find a way.

**Comment by chequille** [comment] 2020-07-29 20:01
@vasusundar 
Hi, sorry for the confusion. The select-payment-method-mixin.js from 2.4.x is working as well with 2.3.5-p2.
I had a problem in my own Discount class.
So give it a try as I described to solve your problem.
Regards
Chequille

**Comment by vasusundar** [comment] 2020-07-30 09:32
Thanks, It worked by copying that js from Magento 2.4 version.
