### ISSUE TITLE
Update 2.1.7 to 2.2.0 --> No Developer Tab any more in the backend

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#11227] opened 2017-10-04 15:56 UTC
### Preconditions

1. Version 2.1.7 to 2.2.0 Update

### Steps to reproduce

1. Update magento from 2.1.7 to 2.2.0 via composer command

### Expected result

1. There is the tab "developer" under Stores -> Configuration -> Advanced -> Developer -> to set the Javascript Settings

### Actual result

1. There is no tab Developer any more see screen attached.
This is no caching problem and reproduced on 2 different systems. 
Also javascript bundling is not working properly any more - but this is just one of many other bugs on the update.
![developer](https://user-images.githubusercontent.com/16196483/31185810-39fb50b0-a92d-11e7-9df6-59a5f7c3ed25.png)

**Comment by hostep** [comment] 2017-10-04 17:52
@andidhouse: it's expected behaviour, de Developer tab is gone in production mode. It is mentioned somewhere on http://devdocs.magento.com/, but I can't find it anymore... 
Magento now picks the "best" configuration for those settings automatically and doesn't allow you to tweak it anymore from what I understand.

@jfrontain: I think major changes in the backend configuration should be mentioned on the release notes. The same thing happened in the release of Magento 2.1 where the design configuration was moved to another section: a lot of users were confused this happened because they weren't aware of this.
If something like this is mentioned in the release notes, it will hopefully minimize the confusion around big changes in the backend of Magento. I'm afraid were are going to see a lot of reports like the above for all the things which have changed in the backend of Magento for version 2.2.0. Maybe best to try to mention these on the release notes as to raise the awareness about these things?

**Comment by andidhouse** [comment] 2017-10-04 19:36
Hi @hostep - thanks for the info.

Do you mean this is present in developer mode or magento completly removed it?

This is really a bad way to update a system. As you mentioned we saw this on earlier versions as well. It would be better to first make a solid concept and then not change the concept in the versions.

**Comment by hostep** [comment] 2017-10-04 20:45
Yes indeed, in developer mode the tab is there, in production mode it isn't there.

**Comment by hostep** [comment] 2017-10-04 20:54
@andidhouse: I've just found the aforementioned devdocs page again:
http://devdocs.magento.com/guides/v2.2/config-guide/deployment/pipeline/technical-details.html#config-deploy-admin

Best to read through that whole pipeline deployment section, because there are more surprises hiding in there.

I'd advise you to wait with upgrading to version 2.2.x until you completely understand all the things which have changed, you can still use version 2.1.x, it's still supported and bugfixes are still going to be delivered on there.

**Comment by andidhouse** [comment] 2017-10-05 08:35
Thanks @hostep - i am not shure what sense this makes. 
So magento is putting effort in such wired things instead of fixing the major bugs. Hmmmm....

**Comment by magento-engcom-team** [comment] 2017-10-05 10:30
@andidhouse, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by orlangur** [comment] 2017-10-05 11:34
And also a duplicate of https://github.com/magento/magento2/issues/11191#issuecomment-333818461. Please check release notes before reporting some changed behavior as a bug.

**Closed as completed by orlangur** 2017-10-05 11:34 UTC
Labels: duplicate, non-issue, Issue: Format is valid

**Comment by franciskim** [comment] 2018-04-05 04:02
Agreed that it's expected - I wrote a quick help guide for those that might be struggling still: [Magento Developer Tab Missing](https://franciskim.co/magento-developer-tab-missing-after-upgrade/)
