### ISSUE TITLE
Catalog pricing rule not working on some sku's

### ISSUE THREAD

**Issue by hbprincepatel** [magento/magento2#8215] opened 2017-01-20 13:55 UTC
### Preconditions

1. Magento 2.1.0 (happens also in 2.1.2)
2. PHP 7.0.8 & MySQL 5.6.31-0ubuntu0.14.04.2

### Steps to reproduce

1. Set catalog pricing rule for some product sku's like 
If ALL  of these conditions are FALSE :
SKU  is  502W  
SKU  is  12065  
SKU  is  c017  
SKU  is  12004SWIVKDR  
SKU  is  WA006SIL-2   

set 30 % discount

### Expected result

1. All this product should not contain discount 

### Actual result

1. But still first two products show discount price. 502W  and 12065
2. In other three product display right. but issue only this two products.
3 I also check this two product in backend to check special price assign or not.

**Comment by miakusha** [comment] 2017-02-06 12:21
Hi @hbprincepatel, I cannot reproduce this issue. Are you used fresh magento install or third party extensions  for creations Catalog Rules? As I know in magento you have no ability to create Catalog rule based on list of SKU. You can create rule only based Attribute Set or Category.

**Comment by hbprincepatel** [comment] 2017-02-06 12:57
Hi @miakusha, thanks for your reply. I have created this rule and it's working but issue with only some sku's. First two sku still display discount price even i set no for it. other products sku's working fine.

**Comment by miakusha** [comment] 2017-02-06 13:26
@hbprincepatel  please provide more detailed information about you Catalog Rule.  Could you attach screenshot with rule conditions.

**Comment by hbprincepatel** [comment] 2017-02-07 05:22
I have set catalog price rule as shown as screen shot. I have set 4 products as not apply this discount price. but as shown as second scrren shot product "502w" shows discount price I checked in admin that no any special, tire price applied to this product. As shown as third screen shot other products working fine.
![sample discount for retailers catalog price rule promotions marketing magento admin](https://cloud.githubusercontent.com/assets/25247702/22678876/6fe477fe-ed23-11e6-9db3-dbe0fc52ba5e.png)
![search results for 502w](https://cloud.githubusercontent.com/assets/25247702/22678879/74dcfe7a-ed23-11e6-924c-55f381c47707.png)
![search results for c017](https://cloud.githubusercontent.com/assets/25247702/22678881/77b6a286-ed23-11e6-8ffa-e7d9bf404a65.png)

**Comment by miakusha** [comment] 2017-02-07 10:21
@hbprincepatel  I still can not reproduce issue. 
Products listed in conditions has simple type? 
Do you have any other applied rules ?

**Comment by jmtakahashi** [comment] 2017-02-10 02:02
I have this issue as well on an installation of Magento 2.1.2 (through softaculous).  In the past (up til this attempt) catalog price rules have worked.  I'm now trying to add a catalog price rule that discounts items by 30%.  I am using "SKU is one of" and then selecting the items from the drop down.  On save, only a few items are actually added to the price rule.  I have double checked the catalogrule_product table and I can see that only 2 items are being added.

@miakusha you stated  "As I know in magento you have no ability to create Catalog rule based on list of SKU. You can create rule only based Attribute Set or Category."  But I have been creating these catalog price rules fine up until now, using the SKU attribute. --> "SKU is one of..."  Is this a bug in Magento that is letting us do this?  

For reference:

The following instructions fall under Catalog Price Rule (but in the instructions, it states to use a cart price rule, but we only want the discount applied to individual items, not the entire cart)
http://docs.magento.com/m2/ce/user_guide/marketing/price-rule-multiple-sku.html

**Comment by jmtakahashi** [comment] 2017-02-11 02:43
#https://github.com/magento/magento2/pull/8246

**Comment by jmtakahashi** [comment] 2017-02-11 02:44
#8246

**Comment by jmtakahashi** [comment] 2017-02-11 02:44
#8246

**Comment by jmtakahashi** [comment] 2017-02-11 02:45
#7723

**Comment by jmtakahashi** [comment] 2017-02-21 02:36
Any updates regarding this issue?

**Comment by jmtakahashi** [comment] 2017-03-06 21:57
@hbprincepatel have you figured out a solution?

@veloraven @miakusha have we any progress on this matter?

@claridgeandco your other issue #7093  was closed because you didn't respond.  Did you figure out a fix? or did you just give up?

**Comment by jmtakahashi** [comment] 2017-03-07 23:54
@hbprincepatel could you let me know of the fix for this issue since you closed it?  Sorry, but I'm having the same problem as you.

**Comment by hbprincepatel** [comment] 2017-03-08 05:13
@jmtakahashi I can't find any solution for this. If any one help I reopen issue.

**Comment by jmtakahashi** [comment] 2017-03-08 05:24
@hbprincepatel ok.  Same for me.  @miakusha anything?

**Comment by Danielc3** [comment] 2017-05-16 11:59
I am getting a similar issue to this on 2.1.6. It seems I cannot add additional SKUs to catalog rule conditions e.g. SKU is one of. If I delete a condition and then re-add I am however able to add SKUs, it's only when editing an already saved condition. Has anyone else experienced this?

**Comment by koenner01** [comment] 2017-06-23 13:31
@Danielc3 sounds like your problem is similiar to https://github.com/magento/magento2/issues/6396

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@hbprincepatel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: bug report, Component: Tax, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
