### ISSUE TITLE
The `unsigned` flag is not recognized on schema parsing and comparison on MySQL 8.0.30

### ISSUE THREAD

**Issue by speller** [magento/magento2#36558] opened 2022-12-02 07:14 UTC
### Preconditions and environment

- Magento version 2.4.5
- MySQL version 8.0.30

### Steps to reproduce

Sample table

```
CREATE TABLE `yotpo_orders_sync` (
  `entity_id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Entity ID',
  `order_id` int unsigned NOT NULL COMMENT 'Order ID',
  `yotpo_id` double unsigned DEFAULT '0' COMMENT 'Yotpo ID',
  `synced_to_yotpo` datetime DEFAULT NULL COMMENT 'Synced to Yotpo',
  `response_code` varchar(5) DEFAULT NULL COMMENT 'Response Code',
  `is_fulfillment_based_on_shipment` tinyint(1) DEFAULT NULL COMMENT 'Fulfillment Sync Method',
  PRIMARY KEY (`entity_id`),
  UNIQUE KEY `YOTPO_ORDERS_SYNC_ORDER_ID` (`order_id`),
  KEY `YOTPO_ORDERS_SYNC_ENTITY_ID` (`entity_id`),
  KEY `YOTPO_ORDERS_SYNC_IS_FULFILLMENT_BASED_ON_SHIPMENT` (`is_fulfillment_based_on_shipment`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Orders sync with Yotpo'
```

See the `yotpo_id` field definition.

Sample Magento definition:

```
        <column xsi:type="double" name="yotpo_id" unsigned="true" nullable="true" scale="0" default="0"
                comment="Yotpo ID"/>
```

### Expected result

Magento successfully syncs database and declarative schema

### Actual result

Magento doesn't recognize the `unsigned` flag.
Thus, the declarative schema is ALWAYS not up-to-date.

### Additional information

The `Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader::readColumns()` method gets the following data for the `yotpo_id` field:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1829515/205235795-0051634d-3add-4b5b-bf8a-c1229ec0ae45.png">

And then, since the `\Magento\Framework\Setup\Declaration\Schema\Dto\ElementFactory::castGenericAttributes()` expects the `unsigned` flag to be a separate array value, the `unsigned` flag is never detected and set properly:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/1829515/205236102-b504adff-1a45-4811-939c-9e297ed8545a.png">

The `\Magento\Framework\ObjectManager\Factory\AbstractFactory::getResolvedArgument()` method expects the `unsigned` flag to be in the array. If not, it picks the default `false` value:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1829515/205238640-c692f9ff-1bd7-47ba-a30f-c15db8a877e4.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by speller** [comment] 2022-12-02 07:49
As a workaround, I'm using the following patch with the `cweagans/composer-patches` to fix the issue:

```diff
--- a/Setup/Declaration/Schema/Dto/ElementFactory.php
+++ b/framework/Setup/Declaration/Schema/Dto/ElementFactory.php
@@ -60,6 +60,11 @@
     {
         $booleanAttributes = ['nullable', 'unsigned', 'identity'];

+        if (isset($elementStructuralData['definition']) && strpos($elementStructuralData['definition'], ' unsigned') > 0)
+        {
+            $elementStructuralData['unsigned'] = true;
+        }
+
         foreach ($booleanAttributes as $booleanAttribute) {
             if (isset($elementStructuralData[$booleanAttribute])) {
                 $elementStructuralData[$booleanAttribute] = $this->booleanUtils
```

**Comment by engcom-Hotel** [comment] 2022-12-27 08:21
Hello @speller,
Thanks for the reporting and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. We are able to run the below command after creating the custom module for table creation:

`bin/magento setup:upgrade`

The definition of the `db_schema.xml` is as follows:

```
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
    <table name="issue_36558" resource="default" engine="innodb" comment="Issue 36558">
        <column
            xsi:type="double"
            name="entity_id"
            unsigned="true"
            nullable="true"
            default="0" comment="Entity ID"/>
    </table>
</schema>
```
We can see the table is created with the given definition above:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/51681618/209635937-eb02021c-3ddc-4799-afa9-8545ec1d8e8a.png">

Please let us know if we have missed anything.

Thanks

**Comment by speller** [comment] 2022-12-28 03:00
@engcom-Hotel does the `setup:db:status` command detect changes right after the `setup:upgrade` command in your case?

**Comment by engcom-Hotel** [comment] 2022-12-28 08:49
Hello @speller,

Thanks for the reply!

We have checked the output of `setup:db:status` but it is saying `Declarative Schema is not up to date`:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/51681618/209784844-5362fd71-b9af-4000-bf77-254580ebf50b.png">

But I have we have checked the `setup:db:status` with fresh installation without the above custom module, but we are still getting the same result as `Declarative Schema is not up to date`.

I think there is an issue related to this here which is confirmed https://github.com/magento/magento2/issues/35671.

Thanks

**Comment by speller** [comment] 2022-12-29 04:04
@engcom-Hotel as I described in the ticket, this issue exists in my setup in addition to #35671.
To confirm the issue, could you check whether the `Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader::readColumns()` method returns the `unsigned` flag for the `issue_36558.entity_id` column when you perform the `setup:db:status` command?

**Comment by engcom-Hotel** [comment] 2022-12-30 08:06
Yes @speller,

By using the above `Magento\Framework\Setup\Declaration\Schema\Db\MySQL\DbSchemaReader::readColumns()`, we are getting the `unsigned` flag. We have the output as below:

```
Array
(
    [entity_id] => Array
        (
            [name] => entity_id
            [default] => 0
            [type] => double
            [nullable] => 1
            [definition] => double unsigned
            [extra] => 
            [comment] => Entity ID
        )

)
```

Thanks

**Comment by engcom-Hotel** [comment] 2023-01-16 09:31
Dear @speller,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-01-16 09:31 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5

**Comment by speller** [comment] 2023-01-17 02:37
@engcom-Hotel you don't have the `unsigned` flag in the array, isn't it? As I mentioned earlier, the `Magento\Framework\Setup\Declaration\Schema\Dto\ElementFactory::castGenericAttributes()` method expects the `unsigned` flag to be a separate array key. In your example, the array doesn't have the `unsigned` key.

**Comment by engcom-Hotel** [comment] 2023-01-17 07:23
Hello @speller,

It has an unsigned flag. You can see this in the definition here at the https://github.com/magento/magento2/issues/36558#issuecomment-1367782418.

Thanks

**Comment by speller** [comment] 2023-05-25 07:33
@engcom-Hotel no, the flag is in the `definition` value, but it should be a **separate array key.**
