### ISSUE TITLE
Shipping and Billing address to be on first step of checkout in Magento 2.0.7

### ISSUE THREAD

**Issue by Digisha97** [magento/magento2#5515] opened 2016-07-07 11:49 UTC
I am trying to display billing address besides shipping address on first step of checkout , but after creating custom JS view files for billing address , and adding it in checkout_index_index.xml it's loading only HTML of billing address not the actual content of it. 

```
<item name="billing-address-list" xsi:type="array">
<item name="component" xsi:type="string">CPO_Checkout/js/view/billing-address-list</item>
</item>
```

Generated files in below location 
Theme/web/js/view/billing-address-list.js
Theme/web/template/billing-address-list/details.html
Theme/web/template/billing-address-list/form.html
Theme/web/template/billing-address-list/list.html
Theme/web/template/billing-address-list.html

For billing address management functions are written in js/view files and no model JS for it. So what is missing to display billing address options beside shipping address and make it work same as its coming after clicking on any payment method.

Can anyone add proper thoughts on it , for missing things ?

**Comment by veloraven** [comment] 2016-11-01 16:54
@Digisha97 
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue than please create new GitHub report following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Closed as completed by veloraven** 2016-11-01 16:54 UTC
