### ISSUE TITLE
Email template: many problems and impossible to translate

### ISSUE THREAD

**Issue by cptX** [magento/magento2#37507] opened 2023-05-16 12:49 UTC
### Preconditions and environment

- Magento version 2.4.6
- Using community-engineering greek language pack
- 2 store views: greek and english

### Steps to reproduce

UPDATE: According to my research this bug is a regression compared to 2.4.5. In 2.4.6 the telephone number in the email is an href link so this broke the translations but also makes it impossible to translate as well...

When changing the password the customer receives an email where there are several issues:

1. variable %user_name is not populated (not populated neither in english nor in greek)
2. translation for greek is wrong. Uses the word "Νέες" which is feminine but the following word is not. I have suggested a better translation in crowdin.
3. The word "password" is not translated neither in subject nor in main body of the email
4. the phrase "or call us at" is impossible to get translated

As you understand the final email arriving to the customer is really bad and unprofessional. The problem is that all my attempts to correct it failed, thus I'm needing your help!

### Expected result

Parts marked with bold here are wrong or missing. Here I show what they should be

Subject: **Νέος** **κωδικός ασφαλείας** για **username** or Αλλαγή **κωδικού ασφαλείας** για **username**

Body: 

Γεια **username**,

Έχουμε λάβει μια αίτηση για να αλλάξετε τις παρακάτω πληροφορίες που σχετίζονται με το λογαριασμό σας στο electrons.gr: **κωδικός ασφαλείας**.
Αν δεν έχετε εξουσιοδοτήσει αυτήν την ενέργεια, επικοινωνήστε μαζί μας αμέσως στο [info@test.gr](mailto:info@electrons.gr) **ή καλέστε μας στο** +30 211 75 05 813 .

Ευχαριστούμε,
test.gr

### Actual result

Subject: **Νέες password** για

Body: 

Γεια,

Έχουμε λάβει μια αίτηση για να αλλάξετε τις παρακάτω πληροφορίες που σχετίζονται με το λογαριασμό σας στο electrons.gr: **password**.
Αν δεν έχετε εξουσιοδοτήσει αυτήν την ενέργεια, επικοινωνήστε μαζί μας αμέσως στο [info@test.gr](mailto:info@electrons.gr) **or call us at** +30 211 75 05 813 .

Ευχαριστούμε,
test.gr

### Additional information

Regarding problem 4. I have tried several ways to translate the phrase "or call us at"
I have searched for the template used in this email and I think it is the password_reset.html
In this tempate there is the following {{trans 'or call us at <a href="tel:%store_phone">%store_phone</a>' store_phone=$store_phone |raw}}

In my attempts to translate this part in my el_GR.csv I have used:
"or call us at {{store_phone}}","ή καλέστε μας στο {{store_phone}}"
" or call us at {{store_phone}}"," ή καλέστε μας στο {{store_phone}}" <-- space in the front
"or call us at %store_phone","ή καλέστε μας στο %store_phone"
"or call us at <a href=""tel:%store_phone"">%store_phone</a>"

All the above failed. I'm still getting the same wrong translation.
Also this phrase was not existing at all in the community-engineering translation 

Regarding subject, I cannot find any template starting with the word "New...", so the tempates I'm finding are contradictory to what I see in the final result. Are they any other email templates used?

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-05-22 02:43
Hi @cptX ,

verified the issue in 2.4-develop instance and the issue is not reproducible, kindly recheck the behaviour in 2.4-develop.

Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-05-22 at 8 10 11 AM" src="https://github.com/magento/magento2/assets/60198592/63a8f1bf-f416-458a-8a16-d6129b512068">

After the reset the password in store we are getting mail as we expected.
Let us know if we are missing anything.

Thanks!

**Comment by cptX** [comment] 2023-05-25 11:35
Hi @engcom-Dash, the email you received is based on another template. I'm also confused why magento is using 2 different templates for password change. I suppose 1 is when you forgot your password during login and you ask the system to reset the password (this is what you have received) and the other is when you go to
My Account > Account Information and then select "Change Password". Then you will receive the template that I'm referring to, and you will see that is partially translated. Also if you try  to translate the part that is not translated you will fail. I spent a lot of time trying to translate this part and was impossible...

**Comment by engcom-Dash** [comment] 2023-06-07 08:38
Hi @cptX ,

Thanks for Contribution and collaboration !

Verified the issue in 2.4-develop still the issue is not reproducible and we are getting expected behaviour.
Kindly refer the below screenshots:
<img width="1512" alt="Screenshot 2023-06-07 at 9 10 29 AM" src="https://github.com/magento/magento2/assets/60198592/995fae12-b972-418b-897e-6b7867a393c0">
<img width="1512" alt="Screenshot 2023-06-07 at 2 03 40 PM" src="https://github.com/magento/magento2/assets/60198592/2e19267c-9ed2-4542-a908-efe542b1b200">

We are tried for reproducible as per your last comments > 
My Account > Account Information and then select "Change Password" and we are getting expected behaviour based on main description.

Kindly recheck the behaviour in 2.4-develop instance and provide if you have any screenshots and its very useful to reproduce the issue.

Thanks!

**Comment by cptX** [comment] 2023-06-07 09:51
In my system 2.4.6 this is the email I'm receiving, which is different than yours. I think is a regression in 2.4.6. Have you tested it in 2.4.6?

![image](https://github.com/magento/magento2/assets/9040042/4587b62a-34de-4d13-ae5c-151167f368de)

**Comment by engcom-Dash** [comment] 2023-06-08 14:35
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-06-08 14:36
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment] 2023-06-20 06:38
Hi @cptX ,

Thanks for contribution and collaboration !

verified the issue in 2.4.6 and the issue is not reproducible,Kindly refer the below screenshots:
<img width="1505" alt="Screenshot 2023-06-20 at 11 52 26 AM" src="https://github.com/magento/magento2/assets/60198592/86825b8b-247d-4244-86cf-c81822e98973">

Steps to reproduce:
My Account>Change Password>given New password

We are getting Expected result as per the main description and the issue is not reproducible.Let us know if we are missing anything.

Thanks!

**Comment by cptX** [comment] 2023-06-20 11:20
I really don't understand why my system uses another tempate!

**Comment by engcom-Dash** [comment] 2023-06-21 10:19
Hi @cptX ,

Could please verify which template you are using your end? ,Because we verified the issue both 2.4-develop and 2.4.6 instance in both we are using default magento templates.Kindly refer the below screenshots:
<img width="1509" alt="Screenshot 2023-06-21 at 3 44 29 PM" src="https://github.com/magento/magento2/assets/60198592/c4e04160-028f-4b67-a9c4-ba48d04f6852">
<img width="1509" alt="Screenshot 2023-06-21 at 3 44 43 PM" src="https://github.com/magento/magento2/assets/60198592/e9630d7d-42df-407e-9bc1-5777b7bb9c71">
Kindly check your end ,are you using default template or any third party extension ???because of that also you may get different results.

Thanks

**Comment by engcom-Dash** [comment] 2023-07-06 12:55
Hi @cptX ,

Verified the issue both 2.4-develop and 2.4.6 instance and we are getting this [template](https://github.com/magento/magento2/issues/37507#issuecomment-1598196903).Do you need any further investigation regarding this issue,Kindly let us know.Because its very useful to proceed further in this case.

Thanks.

**Comment by cptX** [comment] 2023-07-06 14:20
Is it possible that admin changing password triggers another template? I haven't created any custom email template, so I don't understand why I have this behavior in my system. Also my system was initiallly 2.4.5 and upgraded to 2.4.6

**Comment by engcom-Dash** [comment] 2023-07-10 11:15
Hi @cptX ,

Verified the issue 2.4-develop instance and the issue is reproducible Hence we are confirming the issue.
Magento version 2.4-develop
PHP version 8.1
**Steps to reproduce:**
1.Install magento instance
2.Reset Password from admin panel
3.Verify the template
**Kindly refer the below screenshot:**
<img width="1162" alt="Screenshot 2023-07-10 at 4 43 20 PM" src="https://github.com/magento/magento2/assets/60198592/813f9ee8-05d6-486d-89fa-6fee0045a6f0">

As per the description we are getting actual result(mail template),Hence we are confirming the issue.

Thanks!

**Comment by engcom-Hotel** [comment] 2023-07-11 11:14
@engcom-Dash As per our discussion in the triage call we need to recheck this issue with upgrading from 2.4.5 to the latest version.

Thanks

**Comment by engcom-Dash** [comment] 2023-07-31 11:26
Hi @cptX ,

Verified the issue in after upgrading 2.4.5 to 2.4.6 magento instance and the issue is not reproducible,Kindly refer the below screenshot:
<img width="1512" alt="Screenshot 2023-07-31 at 4 34 29 PM" src="https://github.com/magento/magento2/assets/60198592/bace3f6a-a722-413a-a592-7aaa32a55185">

**Comment by engcom-Dash** [comment] 2023-08-16 11:59
Hi @cptX ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by cptX** [comment] 2023-08-23 06:16
Hi, sorry for replying late, the system forced me today to change my password and I received again the same strange template which is partial in english and cannot be translated.
`
Γεια,

Έχουμε λάβει μια αίτηση για να αλλάξετε τις παρακάτω πληροφορίες που σχετίζονται με το λογαριασμό σας στο test.gr: password.
Αν δεν έχετε εξουσιοδοτήσει αυτήν την ενέργεια, επικοινωνήστε μαζί μας αμέσως στο [info@test.gr](mailto:info@test.gr) or call us at +30 xxx xxx xxx xxx.

Ευχαριστούμε,
test.gr`

Please reopen the issue and help me detect which template is this email using! It's really strange that this template doesn't follow your results...

**Comment by engcom-Bravo** [comment] 2023-09-08 06:07
Hi @cptX,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-08 06:07 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by tobiasolge** [comment] 2023-11-29 11:44
Hi, 
we seem to have a similar problem. Sometimes email templates do not use translations.
in our case this is regarding Shipment emails at the moment. The problem also occured on others.

What I can see is, that when the translation is not working, the entire template is broken. First letter from Links is removed. (ttp:// instead of http://)
![image](https://github.com/magento/magento2/assets/13048553/25c7557f-daab-447b-bf9b-94ae6c940505)

This happens randomly. One was broken and 20 were broken.

**Comment by engcom-Dash** [comment] 2023-12-05 07:26
@magento give me 2.4.6 instance

**Comment by engcom-Dash** [comment] 2023-12-05 07:45
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2023-12-05 07:52
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-12-05 11:04
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-12-05 12:37
@magento give me 2.4-develop instance
