### ISSUE TITLE
import/export issue:There is no sample file for this entity.

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#2197] opened 2015-10-27 11:56 UTC
![nosample](https://cloud.githubusercontent.com/assets/7636894/10757267/c237a8a2-7ccf-11e5-829c-bf0e04b5132c.png)

**Comment by markoshust** [comment] 2015-10-27 13:49
possible dupe of https://github.com/magento/magento2/issues/1840

**Comment by vkholoshenko** [comment] 2016-01-06 13:54
Closing as a duplicate

**Closed by vkholoshenko** 2016-01-06 13:54 UTC
Labels: MX
