### ISSUE TITLE
[Issue] Product Price Showing ZAR 0.00 when South African Currency Used

### ISSUE THREAD

**Issue by RedBeardedVikingDK** [magento/magento2#33910] opened 2021-08-25 19:21 UTC
### Preconditions (*)
    Magento 2.4.3
    PHP Version 7.4.22
    Elasticsearch 7.9
    Vanilla, clean installation with sample-data

### Steps to reproduce (*)
   
1. Go to Admin -> Store -> Configuration -> Currency Setup -> Set Base Currency to South African Rand
2. Go to Admin -> Store -> Configuration -> Currency Setup -> Set Default Currency to South African Rand
3. Reindex and Flush Cache

### Expected result (*)

1. Price of the product should show as ZAR xxx (where xxx is the price).

### Actual result (*)
1. Price of the product shows as ZAR 0.00. An inspection of the value shows that ZAR 0.00 but data-price-amount is correct.
![ZAR](https://user-images.githubusercontent.com/69049846/130851809-c8e6106a-0e09-4f03-936b-bac75fe09d4f.PNG)

P.S Changing back to USD shows the product price correctly.

**Comment by engcom-Echo** [comment] 2021-08-30 13:35
@StruggleSnuggl3 I will try to reproduce this issue on a clean instance of **2.4-develop** with given steps to reproduce again.

**Comment by engcom-Echo** [comment] 2021-08-30 13:36
@magento give me 2.4-develop instance

**Comment by StruggleSnuggl3** [comment] 2021-08-30 13:47
Something must have changed between 2.4-develop and 2.4.3 GPL. 

1. composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition magento2
2. find var generated vendor pub/static pub/media app/etc -type f -exec chmod u+w {} + && find var generated vendor pub/static pub/media app/etc -type d -exec chmod u+w {} + && chmod u+x bin/magento
3. bin/magento setup:install 
--base-url=
--base-url-secure=
 --db-host=localhost 
 --db-name=magento2
 --db-user=magento2
 --db-password='whocaresabouthis' 
 --admin-firstname=admin
 --admin-lastname=admin
 --admin-email=admin@magento2.com 
 --admin-user=admin
 --admin-password='!!Adm1n12345' 
 --use-rewrites=1 
 --use-secure=1 
 --use-secure-admin=1 
 --session-save=redis 
 --session-save-redis-host=127.0.0.1
 --session-save-redis-password='8545c555fj1fbb662a09c7c6a59fe9961a7420942fd3a0f8bd8f399zz5df885z' 
 --session-save-redis-db=2 
 --session-save-redis-log-level=2 
 --elasticsearch-host=127.0.0.1
 --elasticsearch-index-prefix=elmagento
 --session-save-redis-max-concurrency=72
 --amqp-host=127.0.0.1
 --amqp-port=5672 
 --amqp-user=admin 
 --amqp-password='3Z5jo62w711M29xjgk5zgsus3Mfrt' 
 --amqp-virtualhost=/ --consumers-wait-for-messages=0 
4. bin/magento cron:install -f
5. bin/magento c:f && bin/magento maintenance:enable && composer update && rm -rf generated/* && rm -rf pub/static/* && rm -rf var/page_cache/* && rm -rf var/view_preprocessed/* && rm -rf pub/static/frontend/* && rm -rf var/cache/* && bin/magento maintenance:disable && bin/magento s:up && bin/magento setup:di:compile && php bin/magento c:f && php bin/magento setup:static-content:deploy en_US -t Magento/backend -f && bin/magento setup:static-content:deploy -f && bin/magento index:reindex && bin/magento c:f
6. Login into Admin
7. Go to Admin -> Store -> Configuration -> Currency Setup -> Set Base Currency to South African Rand
8. Go to Admin -> Store -> Configuration -> Currency Setup -> Set Default Currency to South African Rand
9. Create product (give price, quantity, etc)

ZAR 0.00 appears on frontend

Redis version is 6.0.15
Rabbit version is 3.9.5

Thanks

**Comment by Bashev** [comment] 2021-08-30 20:58
@StruggleSnuggl3 can you confirm your OS version? 
After my investigation i found relation with ICU  version related to OS.

Is your php compiled from source or part of package? Do you have lsphp?

**Comment by ihor-sviziev** [comment] 2021-08-31 05:50
Anyone who has this issue - could you run composer check-platform-reqs and php -i | grep ICU on your environment?

**Comment by StruggleSnuggl3** [comment] 2021-08-31 06:22
> @StruggleSnuggl3 can you confirm your OS version?
> After my investigation i found relation with ICU version related to OS.
> 
> Is your php compiled from source or part of package? Do you have lsphp?

OS: CentOS 7.9
Cpanel: v98.0.6
Litespeed WS: 6.0.8 (build 2)


> Anyone who has this issue - could you run `composer check-platform-reqs` and `php -i | grep ICU` on your environment?

1. composer check-platform-reqs -> all success
composer-plugin-api  2.1.0       success
ext-bcmath           7.4.22      success
ext-ctype            7.4.22      success
ext-curl             7.4.22      success
ext-dom              20031129    success
ext-fileinfo         7.4.22      success
ext-filter           7.4.22      success
ext-gd               7.4.22      success
ext-hash             7.4.22      success
ext-iconv            7.4.22      success
ext-intl             7.4.22      success
ext-json             7.4.22      success
ext-libxml           7.4.22      success
ext-mbstring         7.4.22      success
ext-openssl          7.4.22      success
ext-pcre             7.4.22      success
ext-pdo_mysql        7.4.22      success
ext-phar             7.4.22      success
ext-simplexml        7.4.22      success
ext-soap             7.4.22      success
ext-sockets          7.4.22      success
ext-sodium           2.0.23      success
ext-tokenizer        7.4.22      success
ext-xml              7.4.22      success
ext-xmlreader        7.4.22      success
ext-xmlwriter        7.4.22      success
ext-xsl              7.4.22      success
ext-zip              1.15.6      success
lib-libxml           2.9.7       success
lib-openssl          1.1.1.11    success
php                  7.4.22      success

2. php -i | grep ICU ->
ICU version => 69.1
ICU Data version => 69.1
ICU TZData version => 2021a
ICU Unicode version => 13.0

**Comment by ihor-sviziev** [comment] 2021-08-31 06:27
@StruggleSnuggl3, Could you try running the following code in the CLI?
```bash
 cat - <<'EOF' | php
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);

echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;
EOF
```

**Comment by ihor-sviziev** [comment] 2021-08-31 07:01
Oh... I was able to reproduce the issue on AWS EC2 instance with Amazon Linux 2 and PHP 7.3:
```
$ php -i | grep ICU
ICU version => 50.2
ICU Data version => 50.2
ICU TZData version => 2018e
ICU Unicode version => 6.2
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and 
```
$ cat - <<'EOF' | php
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);

echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

$formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;
EOF
50.2
10,30 €
10,30 €
```

❌ As you see - the latest line returned price WITH currency symbol, while it had to return price WITHOUT it.

**Comment by ihor-sviziev** [comment] 2021-08-31 08:15
Hi @engcom-Echo, please check https://github.com/magento/magento2/issues/33910#issuecomment-908956529, feels like there is some diff on different OS, or library versions that causing these issues.

**Comment by WebHostingAce** [comment] 2021-08-31 08:37
> 
> 
> Oh... I was able to reproduce the issue on AWS EC2 instance with Amazon Linux 2 and PHP 7.4:
> 
> ```
> php -i | grep ICU
> ```
> 
> outputs
> 
> ```
> ICU version => 50.2
> ICU Data version => 50.2
> ICU TZData version => 2018e
> ICU Unicode version => 6.2
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> and
> 
> ```
> cat - <<'EOF' | php
> <?php
> 
> try {
>     $reflector = new \ReflectionExtension('intl');
>     ob_start();
>     $reflector->info();
>     $output = strip_tags(ob_get_clean());
>     preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
>     $icuVersion = trim($matches[1]);
> } catch (\ReflectionException $e) {
>     $icuVersion = null;
> }
> echo $icuVersion . PHP_EOL;
> 
> 
> $formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);
> 
> echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;
> echo $formatter->getSymbol(\NumberFormatter::CURRENCY_SYMBOL) . PHP_EOL;
> 
> $formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
> 
> echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;
> echo $formatter->getSymbol(\NumberFormatter::CURRENCY_SYMBOL) . PHP_EOL;
> EOF
> ```
> 
> outputs
> 
> ```
> 50.2
> 10,30 €
> €
> 10,30 €
> ```
> 
> ❌ As you see - the latest line will price returned price WITH currency symbol, while it had to return price WITHOUT it.

@ihor-sviziev Thank you for confirming this.

**Comment by ihor-sviziev** [comment] 2021-09-01 14:43
Just tried one idea - feels like it should help:
```
<?php

try {
    $reflector = new \ReflectionExtension('intl');
    ob_start();
    $reflector->info();
    $output = strip_tags(ob_get_clean());
    preg_match('/^ICU version (?:=>)?(.*)$/m', $output, $matches);
    $icuVersion = trim($matches[1]);
} catch (\ReflectionException $e) {
    $icuVersion = null;
}
echo $icuVersion . PHP_EOL;


$formatter = new NumberFormatter('de_DE', NumberFormatter::CURRENCY);
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

$formatter->setSymbol(\NumberFormatter::CURRENCY_SYMBOL, '');
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

$formatter->setPattern( str_replace('¤','', $formatter->getPattern() ) );
echo $formatter->getPattern() . PHP_EOL;
echo $formatter->formatCurrency(10.3, "EUR") . PHP_EOL;

EOF
```
returns 
```
50.2
#,##0.00 ¤
10,30 €
#,##0.00 ¤
10,30 €
#,##0.00 
10,30
```
Could someone check if the changes from https://github.com/magento/magento2/pull/33966 are fixing the issue?

**Comment by StruggleSnuggl3** [comment] 2021-09-01 15:36
I won't be able to test until next week. If @ihor-sviziev would like to test on my Magento 2 instance then I can provide the details.

**Comment by ihor-sviziev** [comment] 2021-09-01 19:51
Maybe someone else could check it?

**Comment by engcom-November** [comment] 2021-09-14 08:50
Hi @StruggleSnuggl3 ,

Did you get a chance to reproduce this issue?
Thanks in advance.

**Comment by StruggleSnuggl3** [comment] 2021-09-14 09:53
@engcom-November The issue is still present; and I am unable to resolve it.

**Comment by ihor-sviziev** [comment] 2021-09-14 14:24
@engcom-November, the issue IS reproducing with different ICU library versions. You can see more details in the https://github.com/magento/magento2/pull/33966

**Comment by dudzio12** [comment] 2021-09-16 09:22
@StruggleSnuggl3 - what are your totals when adding broken products to cart?

**Comment by StruggleSnuggl3** [comment] 2021-09-16 09:46
Hi

0.00. 

I’ll post a screenshot a little later to confirm.

**Comment by dudzio12** [comment] 2021-09-16 09:49
@StruggleSnuggl3 That is what I was afraid of.
![image](https://user-images.githubusercontent.com/6281733/133590724-2b12c66d-c5e9-4434-aed5-92659e726113.png)

**Comment by StruggleSnuggl3** [comment] 2021-09-16 09:50
On a positive - yay free stuff?

**Comment by ihor-sviziev** [comment] 2021-09-16 10:11
@StruggleSnuggl3 @dudzio12,
As a temporary workaround, you can apply the following patch: https://github.com/magento/magento2/issues/33856#issuecomment-904606945

**Comment by StruggleSnuggl3** [comment] 2021-09-16 10:31
I just saw this on the ICU git

[ICU Upgrade](https://github.com/unicode-org/icu/releases/tag/cldr%2F2021-09-15)

Do you think this will fix the issue?

**Comment by ihor-sviziev** [comment] 2021-09-16 11:18
@StruggleSnuggl3, sorry, I don't have a fully working solution yet. But I think that should be fixed on the Magento side, not in the ICU library

**Comment by StruggleSnuggl3** [comment] 2021-09-16 11:22
I can hold out a little longer for a permanent solution - will build the store around the issue for now

**Comment by dudzio12** [comment] 2021-09-16 11:29
> @StruggleSnuggl3 @dudzio12,
> As a temporary workaround, you can apply the following patch: [#33856 (comment)](https://github.com/magento/magento2/issues/33856#issuecomment-904606945)

It's working :) Thanks! 

@StruggleSnuggl3 if you are using composer to maintain Magento you can easily apply patch in it using `cweagans/composer-patches` package.

**Closed as completed** 2021-10-07 06:16 UTC
Labels: duplicate, Severity: S1, Issue: needs update, Reported on 2.4.3
