### ISSUE TITLE
Multi-Store: "Store View" sort order values are not reflected in the admin or front-end store-switcher

### ISSUE THREAD

**Issue by duffner** [magento/magento2#13401] opened 2018-01-28 07:52 UTC
### Preconditions

1. Magento 2.2.2 
2. PHP 7.0

### Steps to reproduce

1. Create one website, with three Store Groups Each with 1 store
2. Within the Store view 1, set priority of 0, Store View 2, priority of 10, Store View 3, priority of 20
3. Save 
4. Reviewing admin grid of stores, the sort order does not change.
5. Reviewing store switcher on front-end, sort order does not change 

<img width="1812" alt="screen shot 2018-01-28 at 1 40 37 am" src="https://user-images.githubusercontent.com/7387019/35480073-a4648a94-03cc-11e8-9e5f-0aaf2db1461f.png">

### Expected result

1. When changing the sort order of stores in the admin, their new sort order should be reflected on the admin grid and main store switcher. 

### Actual result

1. Nothing changes 

This feature works as expected in Magento 1.14.x and 1.9.x.  The business case, I want to be able to arrange my stores in the store switcher drop down by popularity or other arbitrary value.  This is not possible as the sort order value does nothing.  Additionally, if I have 100 stores, I want to be able to sort them in a way that makes sense in the admin.

**Comment by duffner** [comment] 2018-01-28 07:56
An additional bug relating to Enterprise Support Ticket #03228684: 

When switching stores, if a url key for a category is not valid on the second store the native store switcher places user onto a 404 page.   This issue also exists in plain 2.2.2 with no customizations.

**Comment by magento-engcom-team** [comment] 2018-01-29 13:29
@duffner, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by duffner** [comment] 2018-02-25 00:01
@vasilii-b , I'm adding you to this ticket as you were already in the Store Switcher Logic for a separate ticket and this is the last piece to allowing the store switcher to work as expected for Magento 2 merchants.  I was curious if you had any interest in taking this on as well.

**Comment by vasilii-b** [comment] 2018-06-17 15:35
For the admin panel, I've found responsible method `joinGroupAndStore` from `Magento\Store\Model\ResourceModel\Website\Collection`.

https://github.com/magento/magento2/blob/cc85cbe1a1220225905440b4b71e144df2540d58/app/code/Magento/Store/Model/ResourceModel/Website/Collection.php#L125-L134

But I do not understand why there is the need to sort by Group Name, Store View Name and Store View Order.
Can anyone form Magento Team (as the Annotation says these order lines were added by `team`) suggest why it's so ? @magento-engcom-team Where we can read more about it, the reason of doing so ?

Thank you!

**Comment by magento-engcom-team** [comment] 2020-06-11 00:21
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-06-11 00:23
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35092` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AbdulRahmanAbouzaid** [comment] 2020-06-11 09:29
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-11 09:30
Hi @AbdulRahmanAbouzaid. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-26 12:50
Hi @duffner. Thank you for your report. 
The issue has been fixed in magento/magento2#28163 by @Bartlomiejsz in 2.4-develop branch
Related commit(s):
 - [85b6d054008a84a7b7a3439f66ee6d6aec925c17](https://github.com/magento/magento2/commit/85b6d054008a84a7b7a3439f66ee6d6aec925c17)
 - [47bc47bc97fb36f93e91f1595f63825bd406c8b3](https://github.com/magento/magento2/commit/47bc47bc97fb36f93e91f1595f63825bd406c8b3)
 - [e87199eac6a845ec198d3209ca7fc6ecde0e199e](https://github.com/magento/magento2/commit/e87199eac6a845ec198d3209ca7fc6ecde0e199e)
 - [06a5ac496fa33eec309f54b3b7d16a564ed805ff](https://github.com/magento/magento2/commit/06a5ac496fa33eec309f54b3b7d16a564ed805ff)
 - [a78ddde117df894ddab53c9f0d436a017b4da465](https://github.com/magento/magento2/commit/a78ddde117df894ddab53c9f0d436a017b4da465)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-08-26 12:50 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, Component: Store, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Triage: Done
