### ISSUE TITLE
Entity Attributes not showing while export the Products

### ISSUE THREAD

**Issue by ghost** [magento/magento2#23049] opened 2019-05-29 11:36 UTC
### Preconditions (*)

1. 2.2.6

### Steps to reproduce (*)

1. Admin -> System -> Data Transfer -> Export
2. Select product from Entity type  
3. It displays the entity attributes
4. Change the Entity type to -- Please Select --
5. It will hide the entity attributes
6. Now Again select the Products from Entity type

### Expected result (*)

1. Product should have exported buy it failed to export
All the Entity Attributes should display.

### Actual result (*)

1. .https://nimb.ws/sAe98t

**Comment by krishprakash** [comment] 2019-05-29 12:12
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-29 12:12
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-29 12:13
Hi @krishprakash, here is your [Magento instance](https://i-23049-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23049-2-2-develop.instances.magento-community.engineering/admin](https://i-23049-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-05-29 12:15
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-29 12:15
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-29 12:16
Hi @krishprakash, here is your [Magento instance](https://i-23049-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23049-2-3-develop.instances.magento-community.engineering/admin](https://i-23049-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-29 12:26
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99863` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Alfa** [comment] 2019-08-02 10:25
Hello @wajeehmmc !

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Alfa** 2019-08-02 10:25 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: CatalogImportExport
