### ISSUE TITLE
\Magento\Framework\Stdlib\DateTime\Timezone timezone shifted for non parsable time

### ISSUE THREAD

**Issue by sergiynezbritskiy** [magento/magento2#29200] opened 2020-07-19 15:14 UTC
### Preconditions (*)

1. Magento versions: 2.3.4, 2.3.5, 2.4-develop

### Steps to reproduce (*)
1.Configure Magento instance to some non UTC locale, e.g. Go Magento admin -> Stores -> Settings -> General -> General -> Locale Options and set Timezone to some non UTC timezone, e.g. *Central Standard Time (America/Chicago)*
2. Get an instance of \Magento\Framework\Stdlib\DateTime\Timezone
3. Call method with any time string, which can't be parsed by \IntlDateFormatter, e.g. *19th July 2020 9:30:00*, *Monday 08:00* etc.
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$timezone = $objectManager->create(\Magento\Framework\Stdlib\DateTime\Timezone::class);
$dateTime = $timezone->date('19th July 2019 09:30:00','en_US', 'en_US', true);
var_dump($dateTime);
```
### Expected result (*)
Returned datetime object should match to time in argument and affected by timezone. E.g. the result of the code snipped above should be like:
```
class DateTime#638 (3) {
  public $date => string(26) "2020-07-19 09:30:00.000000"
  public $timezone_type => int(3)
  public $timezone => string(15) "America/Chicago"
}
```
### Actual result (*)
1. Returned datetime object is actually for UTC timezone, but marked as for specific timezone, e.g.
```
class DateTime#638 (3) {
  public $date => string(26) "2020-07-19 04:30:00.000000" // UTC time
  public $timezone_type => int(3)
  public $timezone => string(15) "America/Chicago" //marked as Chicago time
}
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by sergeynezbritskiy** [comment] 2020-07-19 15:22
Here is the PR with the fix for this issue https://github.com/magento/magento2/pull/29201

**Comment by engcom-Charlie** [comment] 2020-09-23 08:54
As mentioned here https://github.com/magento/magento2/pull/29201#issuecomment-689668146 looks like this is expected behavior.

**Closed as completed by engcom-Charlie** 2020-09-23 08:54 UTC
Labels: Issue: Format is valid, Priority: P2, Severity: S1, Progress: done, Reported on 2.3.4
