### ISSUE TITLE
Product Bulk "Update Attributes" Price Bug

### ISSUE THREAD

**Issue by vseager** [magento/magento2#14364] opened 2018-03-26 09:13 UTC
### Preconditions
1. Magento 2.1.12

### Steps to reproduce (Admin)
1. Products > Inventory > Catalog
2. Select more than 1 simple product from the grid
3. Choose "Update attributes" from the actions drop down
4. Click 'Change' under 'Price'
5. Try to enter new price

### Expected result
Can type in text field and see what I am typing

### Actual result
Cannot type in text field as the `[Inc. Tax]` is covering the field.

See the attached screenshot, where I have typed '1234567890' into the 'Price' field, but can only see the last 2 digits (90)

![update-attribute-price](https://user-images.githubusercontent.com/2035088/37897538-4902fdc2-30de-11e8-9d9b-c986c13acd4a.png)

**Comment by magento-engcom-team** [comment] 2018-03-26 13:33
@vseager 
thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Comment by magento-engcom-team** [comment] 2018-03-29 14:01
Hello again @vseager. The issue is fixed in 2.2.3 version.

**Comment by davidwindell** [comment] 2018-03-29 23:21
@magento-engcom-team Can this fix be backported to 2.1.x?

**Comment by magento-engcom-team** [comment] 2018-04-24 13:30
@davidwindell Unfortunately we can not provide any reliable information regarding port of this fix to 2.1. You may submit a PR to speed up the process if you wish.

Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-04-24 13:30 UTC
Labels: Issue: Ready for Work, Progress: needs update, Issue: Confirmed, Reproduced on 2.1.x, Issue: Format is valid
