### ISSUE TITLE
Cannot get the product's price included tax by rest api

### ISSUE THREAD

**Issue by davidnguyen2205** [magento/magento2#7207] opened 2016-10-27 09:21 UTC
### Preconditions

Magento 2.1.1 
### Steps to reproduce
1. Add tax rate & rule (10%)
2. Change some settings in Stores > Configuration > Sales > Tax:
   ![price incl tax](https://cloud.githubusercontent.com/assets/18303554/19761430/1dedd2d8-9c60-11e6-8df8-d3cbc33ba6a3.PNG)
3. Add a new product (for testing):
   Price: $10
4. Save then indexer:reindex and clear cache or even disable cache.
### Expected result
1. The price in frontend included tax. The test product's price is $11.
2. The price when calling rest api ( /V1/products/SKU + /V1/carts/mine + /V1/carts/mine/items ) included tax. The test product's price is $11.
### Actual result
1. On website, it's great.
2. On the response, the price is always excluded tax.

Is that missing something in my steps to set up the product's price included tax? Or is that an issue?

**Comment by olysenko** [comment] 2016-10-31 14:30
Hi, thank you for your report. To get full prices with tax, discount, shipping  etc in the shopping cart use request /V1/carts/mine/totals. Calls like /V1/carts/mine and /V1/carts/mine/items are not supported price calculation.  Was this comment helpful for you?

**Comment by PaulBoss** [comment] 2016-11-01 13:01
It would be great if there is a way to get the same price the frontend is showing available in the API for products. Right now you can get price, special_price but special logic has to be made by the programmer implementing the API. 

As for tax: I'd like to see that the API returns both prices, with and without tax. Then you can easily select which price you want to synchronize via the API. It is a PITA if you need to re-create the same tax logic which is already available in Magento

**Comment by davidnguyen2205** [comment] 2016-11-01 16:01
Ya, as @PaulBoss said.
We should get prices with or without tax as same way the frontend showing.
For now, I must hack by getting tax rate with admin token then implementing in the price calculation before showing on my app... and something is going to be bad if using search via the api....
It's so painful :(

**Comment by PaulBoss** [comment] 2016-11-09 14:39
The same happens for pricing rules. The API only returns the price from the database without taking pricing rules into account. We are trying to sync products, not carts, to our platform so we can send out an email newsletter with some products in it. Currently there seems to be no way to get the price the frontend is showing via the API (e.g. finalPrice).

**Comment by PaulBoss** [comment] 2016-11-25 13:11
Is there any update?

**Comment by olysenko** [comment] 2016-11-25 15:17
Hi all, internal ticket was created MAGETWO-61408

**Comment by misha-kotov** [comment] 2017-03-16 18:57
This should not be considered a bug since the original catalog API was never designed to serve this purpose, it was meant to serve up product information as it is set up in the catalog. There should be an additional price service built to expose the "final" storefront price given a certain customer context. Since price can vary by customer, customer segment, tax class, etc, this context will need to be passed as input to the service. I have written this up as a Magento feature request for now: MAGETWO-66253. In the meantime, you may find [this article](https://gielberkers.com/get-product-price-including-excluding-tax-magento-2/) useful.

**Comment by piotrekkaminski** [comment] 2017-03-31 19:00
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).



We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Cannot-get-the-product-s-price-included-tax-by-rest-api/idi-p/64456).

**Closed as completed by piotrekkaminski** 2017-03-31 19:00 UTC
Labels: feature request, Component: Framework/Webapi

**Comment by brideo** [comment] 2022-01-27 03:18
> This should not be considered a bug since the original catalog API was never designed to serve this purpose, it was meant to serve up product information as it is set up in the catalog. There should be an additional price service built to expose the "final" storefront price given a certain customer context. Since price can vary by customer, customer segment, tax class, etc, this context will need to be passed as input to the service. I have written this up as a Magento feature request for now: MAGETWO-66253. In the meantime, you may find [this article](https://gielberkers.com/get-product-price-including-excluding-tax-magento-2/) useful.

Doesn't it make sense for the backend to handle this functionality as they should have all the customer information stored against the quote.

**Comment by brideo** [comment] 2022-01-27 03:21
How is this not a bug? Australia is legally obliged to show including tax settings and the customer doesn't have access to a tax API 

Can we re-open this please unless it's fixed in the latest version?

**Comment by FadyEffat** [comment] 2022-12-04 20:39
Any updates on this issue? We are having the same thing in our country, Tax is legally obligatory to be included in displayed products
