### ISSUE TITLE
Braintree Credit Card Not Working for Virtual Product When 3DSecure is set to Yes

### ISSUE THREAD

**Issue by salvadorcanillas** [magento/magento2#26937] opened 2020-02-20 02:34 UTC
### Preconditions (*)

1. Magento CE 2.3.3 with Sample Data
2. magento-braintree version 100.3.3

### Steps to reproduce (*)

1. Create a virtual product
2. Add a Braintree Sandbox account. Set the 3D Secure Verification Setting to Yes. Set Threshold Amount to any amount.
3. Order the virtual product and use Credit Card (Braintree) as payment method. 

### Expected result (*)

1. Order successfully created.

### Actual result (*)

1. Place Order button not working with error in console
![error](https://user-images.githubusercontent.com/40746365/74895197-00cba000-53cc-11ea-8893-bcb39afe56d0.PNG)

### Additional Notes
1. Set the 3D Secure Verification to No.
2. Order the virtual product using Credit Card (Braintree) as payment method.
3. Order successfully placed when 3D Secure is set to No.

**Comment by salvadorcanillas** [comment] 2020-02-20 02:38
@magento give me 2.3.3 instance

**Comment by ajijshekh123** [comment] 2020-02-20 04:39
@magento give me 2.4-develop instance

**Comment by Kannakiraj** [comment] 2020-02-21 07:10
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-02-21 07:10
Hi @Kannakiraj. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-02-21 07:11
Hi @Kannakiraj, here is your [Magento instance](https://i-26937-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-26937-2-3-3.instances.magento-community.engineering/admin_3612](https://i-26937-2-3-3.instances.magento-community.engineering/admin_3612)
Login: `7f0bcaca` Password: `6d36e87eb3db`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-02-25 05:04
Hello @salvadorcanillas ,
I have verified this issue as per your steps, actual result, expected result and additional steps. But I didn't reproduce this issue.
@salvadorcanillas - Can you please share the video?
**See attached the screenshot:**

![Braintree_Issue1](https://user-images.githubusercontent.com/24711761/75216549-5a601000-57ba-11ea-9f36-9d5f9d6003a8.png)

![Braintree_Issue2](https://user-images.githubusercontent.com/24711761/75216552-5b913d00-57ba-11ea-9041-b66571c7bb30.png)



Thanks.

**Comment by salvadorcanillas** [comment] 2020-02-25 05:10
Please try to order as guest.

**Comment by ajijshekh123** [comment] 2020-02-25 05:12
Okay @salvadorcanillas, Let me check it and update you.

**Comment by ajijshekh123** [comment] 2020-02-25 05:22
Hello @salvadorcanillas,
I have verified this issue as a Guest user with 2 different scenarios:
3D Secure "Yes" - Place an order is successful without getting error.
See screenshot:
![GuestUser_3D_Yes](https://user-images.githubusercontent.com/24711761/75217333-c2aff100-57bc-11ea-8b84-dd74e40446c2.png)

3D Secure "No" - Place order is successful with getting error. 
See screenshot:
![GuestUser_3D_No](https://user-images.githubusercontent.com/24711761/75217338-c9d6ff00-57bc-11ea-8a29-9caf7277265e.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-02-25 05:23
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31852` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ganedda-softfobia** [comment] 2020-03-12 16:43
we have the same problem, although it's possible for some users to place orders and not for some others and that's something we need to understand.
We identified in this file
vendor/magento/module-braintree/view/frontend/web/js/view/payment/3d-secure.js
the problem, at line 89, where the quote has an object shippingAddress without any attribute. So at line 120 enters the if instead of avoiding it, and generating the issue.

**Comment by sdzhepa** [comment] 2020-08-17 20:45
Hello @salvadorcanillas

Thank you for your report and collaboration!

Unfortunately, we are closing this Issue report because we are not able to process contribution to the `2.3.x` release line through this public repository. See details [Code Contributions: Accepted pull requests and ported code](https://devdocs.magento.com/contributor-guide/contributing.html#rules)
And starting from `2.4.0` release, code related to this payment was removed for Magento code-base:
[Magento Commerce 2.4.0 Release Notes](https://devdocs.magento.com/guides/v2.4/release-notes/release-notes-2-4-0-commerce.html)
> With this release, the Authorize.Net, Braintree, eWay, CyberSource, and Worldpay payment method integrations have been removed from core code. Merchants should migrate to the official extensions that are available on the Magento Marketplace.

[Deprecation of Magento core payment integrations](https://community.magento.com/t5/Magento-DevBlog/Deprecation-of-Magento-core-payment-integrations/ba-p/426445)

All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page

**Closed as completed by sdzhepa** 2020-08-17 20:45 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Braintree, Reproduced on 2.4.x, Reported on 2.3.3
