### ISSUE TITLE
Adding category image from gallery not possible when using custom media base URLs

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26301] opened 2020-01-08 05:56 UTC
### Preconditions (*)

1. Magento 2.3.3 or 2.4-develop

### Steps to reproduce (*)

1. Install Magento
2. Setup base URL for media like: media.domain.com (this example works even without a proper CDN)
3. Create category
4. Click "Upload", select image, and save category
5. Mouse over the image in admin and you can see the http://media... URL Right? As it should be.
6. Now click "Select from gallery"
8. Create directory in gallery
9. Upload image to gallery
10. Select the image and click "Add selected"
11. Image does not have http://media. in URL anymore and going to it gives 404
12. Save category
13. Open category again and now the image is gone

### Expected result (*)

A working category image.

### Actual result (*)

Image leads to 404 and gets deleted.

**Comment by Zyles** [comment] 2020-01-08 05:57
@magento give me 2.4-develop

**Comment by Zyles** [comment] 2020-01-08 06:02
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-08 06:02
Hi @Zyles. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-08 06:02
Hi @Zyles, here is your [Magento instance](https://i-26301-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26301-2-4-develop.instances.magento-community.engineering/admin](https://i-26301-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Zyles** [comment] 2020-01-08 06:08
Reproduced on 2.4-develop

**Comment by magento-engcom-team** [comment] 2020-01-08 06:24
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30270` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by wescey** [comment] 2020-01-10 15:39
@Bartlomiejsz i guess this is related to #19872

**Comment by vimal-ranosys** [comment] 2020-01-18 09:02
I could not find this issue in my setup.

**Comment by Zyles** [comment] 2020-01-18 14:51
Are you serious?

Re-open the issue at once and try again.

**Comment by Zyles** [comment] 2020-01-18 14:52
@magento give me 2.4-develop instance

**Comment by Zyles** [comment] 2020-01-18 14:53
@magento give me 2.4-develop instance

**Comment by Zyles** [comment] 2020-01-18 15:04
Just re-produced it on 2.4-develop

Re-open the issue.

**Comment by Bartlomiejsz** [comment] 2020-01-19 11:22
Reopening as I was also able to reproduce issue on 2.4-develop.
This however doesn't seem to be related to https://github.com/magento/magento2/issues/19872 as mentioned by @wescey, because here issue occurs right after selecting image from gallery.
In ticket mentioned fix was provided on page load, after image was already saved.

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @Zyles. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
Hi @Zyles. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-21 19:58
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30270` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-01-21 20:00
Hi @Zyles, here is your [Magento instance](https://i-26301-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26301-2-4-develop.instances.magento-community.engineering/admin_5fca](https://i-26301-2-4-develop.instances.magento-community.engineering/admin_5fca)
Login: `0273939b` Password: `8cd8246e5a6b`
Instance will be terminated in up to 3 hours.

**Comment by amenk** [comment] 2020-05-11 14:37
@Zyles We are trying to figure out if we have the same issue.
We have custom media URLs and 

     SELECT * FROM catalog_category_entity_varchar WHERE attribute_id=(SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'image' AND entity_type_id = 3);
     |     5437 |           48 |        0 |       348 | /media/catalog/category/foobar-tile_1.jpg |

So the /media/category/category/ path is added to the database after selecting an image from the Gallery in the backend

**Comment by amenk** [comment] 2020-08-05 07:13
Workaround for us is currently to execute

    update catalog_category_entity_varchar set value=  SUBSTRING_INDEX(value, '/', -1)  WHERE value is not null and attribute_id=(SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'image' AND entity_type_id = 3);

**Comment by amenk** [comment] 2020-09-24 09:32
@sidolov Is anybody planed for the development yet? We have similar problems, but not with a different media URL, but a different base url and wondering if that is the same root cause.

**Comment by amenk** [comment] 2020-09-24 09:47
We are wondering if there should be a path information in the category images or not. What is the normal behaviour?

**Comment by amenk** [comment] 2020-09-24 10:31
After digging into it we are not sure if it is a problem on getImageUrl or while saving.

Looking at the logic of https://github.com/magento/magento2/blob/5977749781ebdbb5e28a03db73207a7fb08ae744/app/code/Magento/Catalog/Model/Category.php#L679-692
there is a check whether the URL is relative. It means it starts with a /, then the media URL is not prepend. Why is that? shouldn't especially relative URLs be prefixed with the media URL?

**Comment by greg-drozd** [comment] 2021-01-12 14:59
Any update on this issue?

**Comment by amenk** [comment] 2021-03-29 16:06
Still relevant I think

**Comment by greg-drozd** [comment] 2021-06-14 05:53
This still an issue. Maybe there should be a setting for that feature ?

**Comment by MTheProgrammer** [comment] 2022-03-21 08:56
The problem lies within `Magento\Catalog\Model\Category\Attribute\Backend\Image::fileResidesOutsideCategoryDir`
Base media url is retrieved from the filesystem as 'media` string and then it is compared to custom url path:

```php
return strpos($fileUrl, $baseMediaDir) !== false;
```

The `strpos` function is then called with these parameters:

- https://magento2.domain/custom/path/catalog/category/category-image.jpg
- media

This code always evaluates to false, unless your custom link contains 'media' part.

**Comment by engcom-Bravo** [comment] 2024-11-20 03:56
Hi @Zyles,

Thanks for your reporting and collaboration.

We have verified the issue in latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1276" alt="Screenshot 2024-11-20 at 09 22 31" src="https://github.com/user-attachments/assets/eec7a356-3a7c-4f37-b748-7db23ec71612">



<img width="1276" alt="Screenshot 2024-11-20 at 09 23 46" src="https://github.com/user-attachments/assets/fd0be156-2a87-4ef0-92a0-443d80b892d7">



Category image was working fine.


Hence we are closing this issue.


Thanks.

**Closed as completed by engcom-Bravo** 2024-11-20 03:56 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Admin, Component: Image, Reproduced on 2.4.x, Priority: P3, Severity: S2, Progress: done, Reported on 2.3.3
