### ISSUE TITLE
Updating Magento from version. 2.4.2-p1 to 2.4.3

### ISSUE THREAD

**Issue by sgeleon** [magento/magento2#33768] opened 2021-08-12 10:22 UTC
I updated Magento from the version. 2.4.2-p1 to 2.4.3

### Preconditions 
1) Update Magento to version 2.4.3
2) Generate DI configuration by command "bin/magento setup:di:compile"

### Expected result 
Get a successful message.

### Actual result 
Fatal error: Interface 'Magento\QuoteGraphQl\Model\Cart\MergeCarts\CartQuantityValidatorInterface' not found in /var/www/html/vendor/magento/module-inventory-quote-graph-ql/Model/Cart/MergeCarts/CartQuantityValidator.php on line 19

Call Stack:
    0.0002     394600   1. {main}() /var/www/html/bin/magento:0
    3.2905   55875728   2. Magento\Framework\Console\Cli->run() /var/www/html/bin/magento:23
    3.2965   58730880   3. Magento\Framework\Console\Cli->doRun() /var/www/html/vendor/symfony/console/Application.php:149
    3.2965   58730880   4. Magento\Framework\Console\Cli->doRun() /var/www/html/vendor/magento/framework/Console/Cli.php:115
    6.8673  116848688   5. Magento\Framework\Console\Cli->doRunCommand() /var/www/html/vendor/symfony/console/Application.php:273
    6.8674  116848688   6. Magento\Setup\Console\Command\DiCompileCommand->run() /var/www/html/vendor/symfony/console/Application.php:1009
    6.8675  116850352   7. Magento\Setup\Console\Command\DiCompileCommand->execute() /var/www/html/vendor/symfony/console/Command/Command.php:255
    8.4572  117872832   8. Magento\Setup\Module\Di\App\Task\Manager->process() /var/www/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:216
    8.7006  125799416   9. Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation() /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
   11.7126  260125408  10. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList() /var/www/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php:61
   11.7126  260134416  11. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract() /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:87
   11.7132  260353472  12. Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass() /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:117
   11.7132  260353472  13. class_exists() /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   11.7132  260353584  14. spl_autoload_call() /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   11.7132  260353696  15. Composer\Autoload\ClassLoader->loadClass() /var/www/html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php:134
   11.7132  260353856  16. Composer\Autoload\includeFile() /var/www/html/vendor/composer/ClassLoader.php:322
   11.7133  260362944  17. include('/var/www/html/vendor/magento/module-inventory-quote-graph-ql/Model/Cart/MergeCarts/CartQuantityValidator.php') /var/www/html/vendor/composer/ClassLoader.php:444

**Comment by mrtuvn** [comment] 2021-08-12 11:46
Have you clear code generated folders

**Comment by mrtuvn** [comment] 2021-08-12 11:47
i would try rm -rf generated/code/*

**Comment by mrtuvn** [comment] 2021-08-12 14:27
https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html

**Comment by engcom-November** [comment] 2021-08-13 10:08
Unable to reproduce this issue while upgrading Magento version from 2.4.2-p1 to 2.4.3
**Steps performed:**
On Magento 2.4.2-p1 Magento Instance Root Folder:
Run: > composer require magento/product-community-edition 2.4.3 --no-update
composer update
php bin/magento setup:upgrade - **No issue**
php bin/magento setup:di:compile - **No Issue** 
sudo php bin/magento setup:static-content:deploy -f
sudo php bin/magento indexer:reindex
sudo php bin/magento cache:flush
Verify version: php bin/magento --version   : "Magento CLI 2.4.3" 
User is able to access both Admin and Front-end pages after upgrade - **No issue**
@sgeleon , kindly recheck the issue again after deleting var/cache, generated folders, clearing cache before upgrade and elaborate the steps to reproduce if the issue is still reproducible.
Thank you.

**Comment by BorisovskiP** [comment] 2021-08-16 12:59
@sgeleon if you are using [Yireo Replace GraphQL](https://github.com/yireo/magento2-replace-graphql) in your project, you can see that the [module]( https://github.com/yireo/magento2-replace-graphql/blob/54685bee71d7fc8ad851b5b1c926d60cf52516fb/composer.json#L44) is added to be replaced/removed. So naturally this will throw the error.

**Comment by engcom-November** [comment] 2021-08-19 07:42
Hi @sgeleon, are you using [Yireo Replace GraphQL](https://github.com/yireo/magento2-replace-graphql) in your project? If yes, try removing it and upgrade to 2.4.3. Kindly elaborate the steps if issue still exist.
Thank you.

**Comment by engcom-November** [comment] 2021-09-02 04:41
Hi @sgeleon ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-02 04:41 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3

**Comment by khoimm92** [comment] 2022-06-07 04:32
In my case, `module-quote-graph-ql` has been marked in `replace` node in composer.json. Remove it out, then do
```
composer update
php bin/magento setup:di:compile
```
