### ISSUE TITLE
Create JPEG Exif writer for MediaGalleryMetadata module

### ISSUE THREAD

**Issue by lenaorobei** [magento/magento2#30101] opened 2020-06-11 21:07 UTC
### Description (*)
Create the `\Magento\MediaGalleryMetadata\Model\Jpeg\Segment\WriteExif` class implmenting the `\Magento\MediaGalleryMetadataApi\Model\WriteMetadataInterface`. The class should add the metadata information to the image in exif format.

### Expected behavior (*)
1. Disable old media gallery in Store Configuration -> Advanced -> System
2. Go to Content -> Media Gallery
3. Upload an image
4. Edit image details
5. Change/populate title and description
6. Save

The image file in the media storage is updated and contains entered title and description in EXIF format

### Benefits
Ability to save image details in EXIF format

**Comment by magento-engcom-team** [comment] 2020-09-18 10:08
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-09-18 10:08
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-09-18 10:09
@sivaschenko Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-09-18 10:11
:white_check_mark: Confirmed by @sivaschenko 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37748` were created

**Issue Available**: @sivaschenko, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-12-23 05:26
Hi,

Since the Related PR closed we are closing this issue please feel free to reopen the issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-23 05:26 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P3, Severity: S3, Component: MediaGalleryMetadata, Risk: medium, Progress: done
