### ISSUE TITLE
Changing theme for product from custom to luma or base theme causes bug - invalid template file

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#32396] opened 2021-03-08 14:19 UTC
### Preconditions (*)

1. Fresh 2.4.2 Enterprise
2. Apache 2
3. PHP 7.4

### Steps to reproduce (*)

**TERMS:**
app/design/frontend/company/fresh = **THEME**

# 1. Create new theme based on luma

## 1.1. **THEME**/registration.php

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use \Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::THEME, 'frontend/company/fresh', __DIR__);
```

## 1.2. **THEME**/registration.php

```
<theme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="urn:magento:framework:Config/etc/theme.xsd">
    <title>Company Fresh</title>
    <parent>Magento/luma</parent>
</theme>
```

## 1.3. **THEME**/Magento_Theme/layout/default.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <container name="user-actions-col-b" htmlTag="div" htmlId="user-actions-col-b">
            <block class="Magento\Framework\View\Element\Template"
                   name="user-actions-col-b-block"
                   template="Magento_Customer::header/test.phtml" />
        </container>
    </body>
</page>
```
## 1.4. **THEME**/Magento_Customer/templates/header/test.phtml

`test`

# 2. Install Theme

`php bin/magento setup:upgrade`

# 3. Select the new Theme "Company Fresh"

Login to Magento Backend

`Content -> Design: Configuration`

![image](https://user-images.githubusercontent.com/16349349/110330261-dfad1000-801d-11eb-9b5f-e7a0531ffe80.png)

# 4. Open a product and set the Theme to "Magento Luma" or "Magento Base".

# 5. Load the product in the frontend.

# 6. You will get:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Magento_Customer::header/test.phtml' in module: '' block's name: 'user-actions-col-b-block'

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'Magento_Customer::header/test.phtml' in module: '' block's name: 'user-actions-col-b-block'
<pre>#1 Magento\Framework\View\Element\Template\Interceptor->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#2 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1111]
#3 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1115]
#4 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:675]
#5 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Magento\Framework\View\Element\Template\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Magento\Framework\View\Element\Template\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/devtools/Plugin/View/Element/AbstractBlockPlugin.php:58]
#8 MSP\DevTools\Plugin\View\Element\AbstractBlockPlugin->aroundToHtml() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#9 Magento\Framework\View\Element\Template\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Framework\View\Element\Template\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Element/Template/Interceptor.php:302]
#11 Magento\Framework\View\Element\Template\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#12 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#13 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#14 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#15 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#17 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/devtools/Plugin/View/LayoutPlugin.php:97]
#18 MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#19 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/honl/magento2-templatehints/Plugin/View/LayoutPlugin.php:70]
#20 Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#22 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#23 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#24 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#25 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#26 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#27 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#28 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#29 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/msp/devtools/Plugin/View/LayoutPlugin.php:97]
#30 MSP\DevTools\Plugin\View\LayoutPlugin->aroundRenderElement() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#31 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/honl/magento2-templatehints/Plugin/View/LayoutPlugin.php:70]
#32 Ho\Templatehints\Plugin\View\LayoutPlugin->aroundRenderElement() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#33 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#35 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#36 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#37 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#38 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#39 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347]
#40 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#41 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#42 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#43 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#44 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#45 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#46 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#47 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#48 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#49 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>
```

### Expected result (*)

1. It should load Luma Theme

### Actual result (*)

1. Code of custom theme is interfering and causing a bug.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Eddcapone** [comment] 2021-03-08 14:54
Sorry, I mean "4. Open a product and set the Theme to "Magento Luma" not "Company Fresh". I edited the issue.

**Comment by mrtuvn** [comment] 2021-03-09 02:29
Are you sure file template defined in layout exist ?

> <?xml version="1.0" encoding="UTF-8"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <container name="user-actions-col-b" htmlTag="div" htmlId="user-actions-col-b">
            <block class="Magento\Framework\View\Element\Template"
                   name="user-actions-col-b-block"
                   template="Magento_Customer::header/test.phtml" />
        </container>
    </body>
</page>

**Comment by Eddcapone** [comment] 2021-03-09 08:04
Yes, of course. I double tested it on a fresh magento 2.4.2

**Comment by mrtuvn** [comment] 2021-03-09 08:53
Ok theory it's should work but in real case we have to check for root cause if problem exists
CC: @engcom-Alfa @engcom-Bravo

**Comment by Eddcapone** [comment] 2021-03-09 12:14
I only get the problem on the product detail page of the product where I changed the style to Luma or Base

**Comment by Eddcapone** [comment] 2021-05-26 06:12
Still relevant

**Comment by engcom-Echo** [comment] 2021-05-31 03:56
Hi @Eddcapone,

This is not an issue, as you are setting the Content theme to 'Custom Theme' and setting the product theme update to 'Default' theme , your customer theme has a template 'template/header/test.phtml' which is not present in default theme , when you are changing the product theme as 'Default' theme m system is expecting this theme will also have that template which you want to override , the issue can be solved if you have the override template file in your default theme.

Thanks

**Comment by engcom-Echo** [comment] 2021-06-14 09:00
Hi @Eddcapone ,

We are closing the issue as there has been no update on the same.

Thanks

**Closed as completed by engcom-Echo** 2021-06-14 09:00 UTC
Labels: non-issue, Triage: Dev.Experience, Issue: needs update
