### ISSUE TITLE
StockState.php Are theses comment a feature or a forget ?

### ISSUE THREAD

**Issue by vahir2016** [magento/magento2#26702] opened 2020-02-04 17:14 UTC
Hello,

If instructions are commented, is it a feature or a forget from the last commit? I have got issues with MSI stocks. Please remove useless comments if needed.

### Preconditions (*)

1. 2.4

### Steps to reproduce (*)

1. Open app/code/Magento/CatalogInventory/Model/StockState.php

### Expected Result (*)
No comments in the code

### Actual Result (*)
There are several not needed comments in the file
![stock_code_comments](https://user-images.githubusercontent.com/51680745/73853847-31db9a80-483a-11ea-8bfa-36cdd841efe7.png)

**Comment by magento-engcom-team** [comment] 2020-02-05 15:12
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-31131` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by naydav** [comment] 2020-02-21 20:34
Hello @vahir2016,
It is legacy code.

Possibility to work with Multi Stocks was implemented in a separate project:
https://github.com/magento/inventory/wiki

>  I have got issues with MSI stocks
Do you mean **Multi-Source Inventory (MSI) project**? Can you provide more details, what exactly is the issue?

Thanks

**Comment by VladimirZaets** [comment] 2020-08-07 20:09
@vahir2016 , due to inactivity we decided just remove the commented condition.
Thank you for collaboration

**Comment by magento-engcom-team** [comment] 2020-08-14 07:20
Hi @vahir2016. Thank you for your report. 
The issue has been fixed in magento/magento2#27758 by @ProkopovVitaliy in 2.4-develop branch
Related commit(s):
 - [e5271144dd535e4473bed3b72a1fa4c3ecfe805e](https://github.com/magento/magento2/commit/e5271144dd535e4473bed3b72a1fa4c3ecfe805e)
 - [677ddce85ae53150a846d4768592ae59ce81b332](https://github.com/magento/magento2/commit/677ddce85ae53150a846d4768592ae59ce81b332)
 - [7199dfe99bc248c04c91bec7c920ca20b0819575](https://github.com/magento/magento2/commit/7199dfe99bc248c04c91bec7c920ca20b0819575)
 - [6d024bb2f344b59b014f34a04e2e86364f7c4b4b](https://github.com/magento/magento2/commit/6d024bb2f344b59b014f34a04e2e86364f7c4b4b)
 - [707297a309600de4c46bb5969913e3126a7fa4bb](https://github.com/magento/magento2/commit/707297a309600de4c46bb5969913e3126a7fa4bb)
 - [e035f6a3282df3a7586becf9210311da414a22f5](https://github.com/magento/magento2/commit/e035f6a3282df3a7586becf9210311da414a22f5)

The fix will be available with the upcoming 2.4.1 release.

**Closed as completed by magento-engcom-team** 2020-08-14 07:20 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Code, Triage: Dev.Experience, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S4, Priority: P4, Progress: done, Reported on 2.4.0
