### ISSUE TITLE
Mail template footer

### ISSUE THREAD

**Issue by albsa** [magento/magento2#2477] opened 2015-11-22 23:09 UTC
There are qoutes in de mail template footer. See screenshot.
![](http://i.imgur.com/fFHqrmS.jpg)

**Comment by MomotenkoNatalia** [comment] 2015-11-24 10:52
@albsa  Thanks for reporting this issue! This is a known bug, internal ticket MAGETWO-45067

**Comment by parthviroja** [comment] 2016-05-11 07:09
This is not an bug, Need to fill store information from Admin Side.

Admin -> Stores -> Configuration -> General -> General -> Store Information 

After fill this info, you can visible data in footer block of mail

**Comment by magento-engcom-team** [comment] 2017-10-13 08:52
@albsa, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-13 08:52 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
