### ISSUE TITLE
Email sending broken to valid email ending with hyphen (M2.4.3)

### ISSUE THREAD

**Issue by pemann** [magento/magento2#34318] opened 2021-10-12 10:29 UTC
### Preconditions (*)

1. Magento 2.4.3

### Steps to reproduce (*)

1. Create an order
2. Use email address that ends with hyphen (-). Like: aaa-@example.com
3. Finish the order
4. Check exception log

### Expected result (*)

1. No exceptions
2. Order confirmation email successfully sent

### Actual result (*)

1. Exception: "Could not add an invalid email address to the mailing queue"
2. Email is not sent.

The problem comes from new email address converting functionality introduced in M2.4.3. Php function "idn_to_ascii" returns empty result for input that ends in hyphen (-). That causes empty user-part to be used as email recipient which causes error.
See:
https://github.com/magento/magento2/blob/2.4.3/lib/internal/Magento/Framework/Mail/AddressConverter.php#L63

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ihor-sviziev** [comment] 2021-10-12 10:58
@pemann,
I never saw such emails as you provided, so I guess it might be the result of the IDN. If so - please give some examples.

**Comment by pemann** [comment] 2021-10-12 11:04
@ihor-sviziev I don't understand. Are you saying that because you haven't ever seen an email address where hyphen is used as last character of "user"-part, that those don't exists and there is no bug?
There are multiple of customer emails with that syntax in a M2 store I'm looking at right now.

**Comment by pemann** [comment] 2021-10-13 05:40
@hostep my db has roughly the same percentage of customers with "-@" vs total orders.

**Comment by ihor-sviziev** [comment] 2021-10-13 07:59
@pemann, from what I tried - it all the time wasn't resulting in the hyphen symbol at the end, examples
https://3v4l.org/BGaGl
https://3v4l.org/J6gFW
If you have some examples - please provide

**Comment by pemann** [comment] 2021-10-13 08:08
@ihor-sviziev If email is like "Hyvä-@example.com", idn_to_ascii will fail and that fix will return the original containing non-ascii chars. So the original fix "convert non-ascii chars" is not applied.

**Comment by ihor-sviziev** [comment] 2021-10-13 08:35
Okay, this feels reasonable, but BTH, I don't know how to handle it correctly.
https://3v4l.org/K3ZMe

**Comment by pemann** [comment] 2021-10-13 09:12
Maybe remove trailing hyphens before idn_to_ascii call and append them back after? But is hyphen the only character that breaks idn_to_ascii?

**Comment by enl** [comment] 2021-11-09 15:29
> @pemann, I'm not sure what will be the correct solution.
> @victor-v-rad, could you check this issue and discussions around it? We need your opinion as you introduced changes that caused the issue.

@ihor-sviziev, you can try to pass last `$info` reference to `idn_to_ascii`, it can will contain `results` key.

```
        if (preg_match('/^(.+)@([^@]+)$/', $email, $matches)) {
            [, $user, $hostname] = $matches;
            $info = [];
            $userEncoded = idn_to_ascii($user, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46, $info);
            if (!$userEncoded || $userEncoded === $user) {
                return $email;
            }
            $email = sprintf('%s@%s', $userEncoded, $hostname);
        }
        return $email;
```

And `info` looks like this after execution (I json-encoded it for readability): 

```json
{
    "result": "xn--hyv--noa",
    "isTransitionalDifferent":false,
    "errors":16
}
```

Although, as you can see, the result does not contain trailing hyphen, so the solution definitely needs some more black magic.

`errors` is a bitset of IDNA_ERROR_* constants, as described here: https://www.php.net/manual/en/intl.constants.php

**Comment by sydekumf** [comment] 2021-11-25 10:47
Despite the obvious core bug what is the actual reason that Magento wants to convert the user part of the email address but *NOT* the domain part? What is the purpose? In my opinion this is wrong.

**Comment by swnsma** [comment] 2022-01-12 10:20
Reason is well-described here: https://github.com/symfony/polyfill/issues/256

Overall, problem that while RFC forbid leading/trailing dash, email services providers allow to create such email addresses.
In such case I see 3 options:
1) Follow RFC 3492: do not do nothing in scope of fixing an issue, however check if this is a part of email validation in Magento. Community members could use discussion around this ticket to solve issue on their projects if they need to deviate from the standard.
2) Add exception to do not follow point in RFC according to leading/trailing dash.
According to previous discussions,
In https://github.com/magento/magento2/blob/4c36116dcf878e127059d9be9566a119783583f2/lib/internal/Magento/Framework/Mail/AddressConverter.php#L61 change
```
            $user = $matches[1];
            $hostname = $matches[2];
            $userEncoded = idn_to_ascii($user, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46);
            if ($userEncoded == $user) {
                return $email;
            }
            $email = sprintf('%s@%s', $userEncoded, $hostname);
```
to 
```
            $user = $matches[1];
            $hostname = $matches[2];
            preg_match("/([\-]+)$/", $user, $trailing);
            preg_match("/^([\-]+)/", $user, $leading);
            $user = trim($user, "-");
            $userEncoded = idn_to_ascii($user, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46);
            if ($userEncoded == $user) {
                return $email;
            }
            $userEncoded = (string)array_pop($leading) . $userEncoded . (string)array_pop($trailing);
            $email = sprintf('%s@%s', $userEncoded, $hostname);
```
P.S. I am not an expert and not sure that it will deliver email to Hyvä-@example.com, as discussed before.

@hostep, @ihor-sviziev, @sidolov I am curious about your opinion.

**Comment by hostep** [comment] 2022-01-23 16:19
I think if it was ever possible to register an account or create an order with this sort of email address in Magento (and it was), then we should still keep supporting it, because those customers would not really appreciate it if they can no longer use their previously working email address all out of the sudden. Especially if they are able to use that email address on a variety of other websites.

The suggested change looks like it will work (although we might need to make it a bit more readable and more robust), but we will definitely need to add a bunch of extra [test cases](https://github.com/magento/magento2/blob/c901f760818228faaf72177a0601bb4258aa9eec/lib/internal/Magento/Framework/Mail/Test/Unit/AddressConverterTest.php#L59-L75).

**Comment by jesse-deboer** [comment] 2022-02-21 16:10
This bug looks bigger then reported before. Also email addresses like these `example-.test@gmail.com` don't work, so it's not just trailing or leading parts of an email. Also, this occurs more often, we have a customer with over 200 email addresses that don't work because of this reason.

**Comment by mvisd** [comment] 2022-03-14 12:33
Just leaving this here. In our case, the invoices get sent out automatically, this happens in the cronjobs based on a flag in the invoices table. So if one invoice is blocking your entire email sending because of this issue, set the column `send_email` to NULL on the problematic invoice. Probably the same for orders. 

This doesn't solve the issue though.

**Comment by kassner** [comment] 2022-04-04 09:54
@mvisd if you can test it, please have a look at the patch mentioned in #35258.

**Comment by justpeeet** [comment] 2022-04-07 09:22
We got the same issue. #35258 is not a fix for this issue

**Comment by NathanDayFE** [comment] 2022-04-08 11:57
Surely the issue here is that [`idn_to_ascii`](https://www.php.net/manual/en/function.idn-to-ascii.php) is the wrong function to use here as it is designed to convert domain names, not parts of an email address. would switching to [`iconv('UTF-8', 'ASCII', $user)`](https://www.php.net/manual/en/function.iconv.php) not be a better solution

**Comment by hostep** [comment] 2022-05-04 14:38
Recent change that might change something regarding this ticket: [ACP2E-717: Emails are not sent for the email containing ".-"](https://github.com/magento/magento2/commit/583b4dd5d71a3c38910cdfb6b3456fd8a7dc643c) (not convinced that it will fix this issue, but maybe somebody wants to give it a try?)

**Comment by moElwan** [comment] 2022-05-05 10:49
@kassner Testing the changes on https://3v4l.org/5IZ27 I see there's a difference in the output. So I assume it actually resolves the issue. I'll be testing the patch soon. Wish it work :crossed_fingers:

**Comment by kassner** [comment] 2022-05-05 11:11
@moElwan The problem is calling `idn_to_ascii` with `$user`. Only `$hostname` should be used there.

See https://gist.github.com/kassner/808f13e1263108fdde7b12ebdfdb0fca line 16.

**Comment by Darkwolf81** [comment] 2022-06-29 11:30
Hello,
we have a silimar issue, dont know if it is the same error, seems the validation in laminas-validator. Emails with dot and hyphen although broken.
a.-test@example.com
only if 2 special-chars are together, alone it is no problem
These are working:
a.test@example.com
a-test.example.com
a.test-test@examlple.com

Regards,
Andreas

**Comment by Aquive** [comment] 2022-08-23 10:35
I can confirm this is an issue in terms of running a business. I took me a while to find this issue since we had errors in our logs but not much more information what was going wrong. 

Our exception log was full of these entries:

```
main.ERROR: Invalid email; contains no at least one of "To", "Cc", and "Bcc" header {"exception":"[object] (Laminas\\Mail\\Transport\\Exception\\RuntimeException(code: 0): Invalid email; contains no at least one of \"To\", \"Cc\", and \"Bcc\" header at /data/web/project/releases/58/vendor/laminas/laminas-mail/src/Transport/Sendmail.php:146)"}

\"Bcc\" header at /data/web/project/releases/58/vendor/laminas/laminas-mail/src/Transport/Sendmail.php:146)"} []
[2022-08-23 10:28:36] main.WARNING: Could not add an invalid email address to the mailing queue {"exception":"[object] (Laminas\\Mail\\Exception\\InvalidArgumentException(code: 0): The input is not a valid email address. Use the basic format local-part@hostname at /data/web/project/releases/58/vendor/laminas/laminas-mail/src/Address.php:74)"} []

```

So the emails are queued but cannot be sent. As a result of this, the exception log is being spammed every minute with the errors for every record.

I used the below query to select all orders. Just check the `customer_email` row for mail addresses with the hyphen as described in the OP

`SELECT * FROM `sales_order` WHERE `email_sent` IS NULL AND `send_email` = 1 ORDER BY `state` DESC`

**Comment by bramstroker** [comment] 2022-09-01 08:51
I also did a check for 2 customers of us, both having the same issue with order emails not being sent. Both have more than 100 cases in the DB with email address having a trailing dash on the user part. 
So I don't consider this a really rare case at all.
Don't understand why this major issue is reported almost a year ago without solving.
As many people already indicated `[idn_to_ascii](https://www.php.net/manual/en/function.idn-to-ascii.php)` should be used for domain/host part only and not for user part.

**Comment by kassner** [comment] 2022-09-02 13:23
Unfortunately 2.4.5 hasn't fixed it, as it's still using `idn_to_ascii` in the wrong part of the email address.

https://github.com/magento/magento2/blob/2.4.5/lib/internal/Magento/Framework/Mail/AddressConverter.php#L63

**Comment by ed007m** [comment] 2022-11-10 18:17
@jesse-deboer, @kassner 
This issue has been fixed here
https://github.com/magento/magento2/blob/2.4.5/lib/internal/Magento/Framework/Mail/AddressConverter.php#L68

**Comment by kassner** [comment] 2022-11-10 18:46
@ed007m it hasn't. As it was stated in previous comments, this piece of code is converting the `$user` variable, but it should be converting the `$host` variable _only_.

**Comment by ed007m** [comment] 2022-11-10 18:59
Cases like this as passed now
aaaa-bbb-@hotmail.co.uk
aaa.-bbbb@asd.com

so why it's not working?)

**Comment by danielpugh** [comment] 2022-12-06 07:55
Logs full of this error for months. Currently 2.4.4 Painful mechanism purely to fill log space?

**Comment by Poovarasan-06** [comment] 2023-08-28 07:26
@magento give me 2.4-develop instance

**Comment by Poovarasan-06** [comment] 2023-08-28 07:59
@pemann Hey, I tried reproducing this in latest 2.4-develop instance and i was able to send mail in both the scenarios without any exception.

Emails Used : 

 lsanjana_.m@srmuniv.edu.in
<img width="1792" alt="image" src="https://github.com/magento/magento2/assets/136694041/7f281289-9137-4263-9376-17792c0d25ac">

lsanj-@srmuniv.edu.in
<img width="1792" alt="image" src="https://github.com/magento/magento2/assets/136694041/96d0477a-7598-4c2b-b392-33ce401dcaaf">

Please reply if you're still facing the issue.

**Comment by thomas-kl1** [comment] 2023-10-17 09:47
@kassner have you try to suggest your changes from https://gist.github.com/kassner/808f13e1263108fdde7b12ebdfdb0fca as a PR?
You changes looks good.

For any interested, there a lot more usage of hyphens in emails in Japan, you may see a various usage of hyphens and underscore in emails.

**Comment by engcom-Bravo** [comment] 2024-09-03 08:16
Hi @pemann,

Thanks for your reporting and Collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="959" alt="Screenshot 2024-09-03 at 13 45 22" src="https://github.com/user-attachments/assets/695c555f-4f54-4b86-9ee3-8c4c5f60c38b">


Order confirmation email successfully sent


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-03 08:16 UTC
Labels: Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P2, Severity: S3, Progress: done, Area: Framework
