### ISSUE TITLE
Payflow only accepts English characters

### ISSUE THREAD

**Issue by H3dz** [magento/magento2#7835] opened 2016-12-15 20:07 UTC
The Payflow Gateway only supports customer input and API parameter values that are in regular ASCII (English language) characters.

https://developer.paypal.com/webapps/developer/docs/classic/payflow/integration-guide/#supported-languages

### Preconditions
Magento version 2.1.2
PHP 7.0.11
MySQL 5.6

### Steps to reproduce
1. Set Payflow as your payment option
2. Enter a valid credit card and cvv number
3. Enter a name that has an accent like "Noémie"

### Expected result
1. The payment should succeed

### Actual result
1. Payflow returns an error, "Invalid expiration date: 10563-This transaction cannot be processed. Please enter a valid credit card expiration month."

### Quick Fix
In app/code/Magento/Paypal/Model/Payflowpro.php

Add
`use Magento\Framework\Filter\RemoveAccents;`

Change
```
public function setBilling(DataObject $request, $billing)
    {
        $filter = new \Magento\Framework\Filter\RemoveAccents();
        $request->setFirstname(
            $filter->filter($billing->getFirstname())
        )->setLastname(
            $filter->filter($billing->getLastname())
        )->setStreet(
            $filter->filter(implode(' ',$billing->getStreet()))
        )->setCity(
            $filter->filter($billing->getCity())
        )->setState(
            $billing->getRegionCode()
        )->setZip(
            $billing->getPostcode()
        )->setCountry(
            $billing->getCountryId()
        );
        return $request;
    }


    public function setShipping($request, $shipping)
    {
        $filter = new \Magento\Framework\Filter\RemoveAccents();
        $request->setShiptofirstname(
            $filter->filter($shipping->getFirstname())
        )->setShiptolastname(
            $filter->filter($shipping->getLastname())
        )->setShiptostreet(
            $filter->filter(implode(' ', $shipping->getStreet()))
        )->setShiptocity(
            $filter->filter($shipping->getCity())
        )->setShiptostate(
            $shipping->getRegionCode()
        )->setShiptozip(
            $shipping->getPostcode()
        )->setShiptocountry(
            $shipping->getCountryId()
        );
        return $request;
    }

```

**Comment by ioliinyk** [comment] 2016-12-27 11:24
English language input is expected behavior of the system

**Comment by YevSent** [comment] 2016-12-27 11:28
Closed as not a bug.

**Closed as completed by YevSent** 2016-12-27 11:28 UTC
Labels: bug report, Component: Payment

**Comment by rparsi** [comment] 2019-01-23 23:21
@joni-jones The bug is that magento code doesn't properly account for special characters in the address fields that should be url encoded (ie `&`).

In this method
`\Magento\Paypal\Model\Payflow\Service\Gateway::postRequest`
line 96
`$client->setUrlEncodeBody(false);`

So if the `lastname` or `street` fields (for example) in the `customer_address_entity` contain characters like `&` or `=` then Paypal will decline the Order.

Either do `$client->setUrlEncodeBody(true);` or
in `\Magento\Paypal\Model\Payflowpro::setBilling`, `\Magento\Paypal\Model\Payflowpro::setShipping`
inspect the address fields and throw an exception when invalid characters are found.
