### ISSUE TITLE
Feature request:configurable product options price should calculate from based on simple product  

### ISSUE THREAD

**Issue by sivajik34** [magento/magento2#1289] opened 2015-05-19 13:11 UTC
So many clients not interest to adjust price based on configurable base price.Its very helpful to customers  if magento provide option to use simple product  prices.

**Comment by orlangur** [comment] 2015-05-19 15:35
Duplicate of  #335, tracked in MAGETWO-23739 internally.

**Comment by tanya-soroka** [comment] 2015-05-25 15:11
Closed as duplicate of #335

**Closed by tanya-soroka** 2015-05-25 15:11 UTC
Labels: CS, PROD
