### ISSUE TITLE
Braintree extension Broken in multiple ways

### ISSUE THREAD

**Issue by MichaelThessel** [magento/magento2#25077] opened 2019-10-15 22:57 UTC
### Preconditions (*)

1. 2.3.3, all modules updated
2. Braintree needs to be disabled

### Steps to reproduce (*)

1. Add product to cart, check cart page or minicart

### Expected result (*)
1. Don't have additional paypal buttons if PP is not enabled
2. If the module is not enabled no Braintree specific JS should be loaded on the cart page

### Actual result (*)
There are several things broken here
1.  I get an additional Paypal button on my checkout page  (bottom button)

![20191015_154023](https://user-images.githubusercontent.com/2926266/66875153-264e2600-ef62-11e9-879a-8ac9762863a1.png)

2. When disabling `Magento_BraintreeGraphQl`  `Magento_Braintree` I get an exeption on the cart page (see below)

3. The Crome console shows one Corb warning and another error relating to Braintree (see below)

#### Module has no custom settings

**For reference**

![20191015_155136](https://user-images.githubusercontent.com/2926266/66875631-dcfed600-ef63-11e9-8497-acfe82cde642.png)

```
    mysql> select * from core_config_data where value like '%braintree%';
    Empty set (0.00 sec)

    mysql> select * from core_config_data where path like '%braintree%';
    Empty set (0.00 sec)
```
#### Chrome console error

```
Uncaught (in promise) o {name: "BraintreeError", code: "INSTANTIATION_OPTION_REQUIRED", message: "options.authorization is required when instantiating a client.", type: "MERCHANT", details: undefined}code: "INSTANTIATION_OPTION_REQUIRED"details: undefinedmessage: "options.authorization is required when instantiating a client."name: "BraintreeError"type: "MERCHANT"__proto__: Errorconstructor: ƒ o(e)__proto__: constructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()__proto__: Object
    Promise.then (async)
    initialize @ button.js:55
    (anonymous) @ wrapper.js:109
    UiClass @ class.js:49
    (anonymous) @ main.js:31
    ...
    enable @ require.js:1511
    (anonymous) @ require.js:1128
    (anonymous) @ require.js:132
    each @ require.js:57
    enable @ require.js:1090
    init @ require.js:774
    (anonymous) @ require.js:1416
    setTimeout (async)
    req.nextTick @ require.js:1755
    localRequire @ require.js:1405
    window.require @ mixins.js:245
    (anonymous) @ (index):1097
    Show 391 more frames
```

#### Chrome console warning

```
    util.js:71 PaypalCross-Origin Read Blocking (CORB) blocked cross-origin
    response https://www.paypal.com/xoplatform/logger/api/logger with MIME type
    application/json. See https://www.chromestatus.com/feature/5629709824032768
    for more details.
```

#### Disable module

As we don't use Braintree I just tried to get rid of the entire module. This didn't work either.

```
    bin/magento module:disable Magento_BraintreeGraphQl  Magento_Braintree                             
    The following modules have been disabled:
    - Magento_BraintreeGraphQl
    - Magento_Braintree
```

This results in an error on the cart page

```
    1 exception(s):
    Exception #0 (UnexpectedValueException): Payment model name is not provided in config!

    Exception #0 (UnexpectedValueException): Payment model name is not provided in config!
    #1 Magento\Payment\Model\PaymentMethodList->Magento\Payment\Model\{closure}('braintree')
    #2 array_map(&Closure#000000007f37563600000000312df7ec#, array('free', 'substitution', 'checkmo', 'purchaseorder', 'banktransfer', 'cashondelivery', 'authorizenet_dir...', 'vault', 'paypal_express', 'paypal_express_b...', 'payflow_express', 'payflow_express_...', 'payflowpro', 'payflowpro_cc_va...', 'paypal_billing_a...', 'payflow_link', 'payflow_advanced', 'hosted_pro', 'authorizenet_acc...', 'cittransfer', 'houseterms', 'wiretransfer', 'braintree', 'braintree_paypal', 'aw_sarp_braintre...', 'aw_sarp_braintre...', 'aw_sarp_authoriz...', 'aw_sarp_cashonde...', 'amazon_payment', 'amazonlogin', 'boltpay', 'ipcarthandoff')) called at [vendor/magento/module-payment/Model/PaymentMethodList.php:45]
    #3 Magento\Payment\Model\PaymentMethodList->getList(1) called at [vendor/magento/module-payment/Model/PaymentMethodList.php:84]
    #4 Magento\Payment\Model\PaymentMethodList->getActiveList(1) called at [vendor/magento/module-vault/Model/PaymentMethodList.php:53]
    #5 Magento\Vault\Model\PaymentMethodList->getActiveList(1) called at [vendor/magento/module-vault/Model/Ui/VaultConfigProvider.php:67]
    #6 Magento\Vault\Model\Ui\VaultConfigProvider->getConfig() called at [vendor/magento/module-checkout/Model/CompositeConfigProvider.php:39]
    #7 Magento\Checkout\Model\CompositeConfigProvider->getConfig() called at [vendor/magento/module-checkout/Block/Cart/Shipping.php:65]
    #8 Magento\Checkout\Block\Cart\Shipping->getCheckoutConfig() called at [vendor/magento/module-checkout/Block/Cart/Shipping.php:99]
    #9 Magento\Checkout\Block\Cart\Shipping->getSerializedCheckoutConfig() called at [vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml:37]
    #10 include('/data/src/m2/ven...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
    #11 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Checkout\Block\Cart\Shipping\Interceptor#000000007f375e5400000000312df7ec#, '/data/src/m2/ven...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
    #12 Magento\Framework\View\Element\Template->fetchView('/data/src/m2/ven...') called at [vendor/magento/framework/Interception/Interceptor.php:58]
    #13 Magento\Checkout\Block\Cart\Shipping\Interceptor->___callParent('fetchView', array('/data/src/m2/ven...')) called at [vendor/magento/framework/Interception/Interceptor.php:138]
    #14 Magento\Checkout\Block\Cart\Shipping\Interceptor->Magento\Framework\Interception\{closure}('/data/src/m2/ven...') called at [vendor/magento/framework/Interception/Interceptor.php:153]
    #15 Magento\Checkout\Block\Cart\Shipping\Interceptor->___callPlugins('fetchView', array('/data/src/m2/ven...'), array(array('searchautocomple...'))) called at [generated/code/Magento/Checkout/Block/Cart/Shipping/Interceptor.php:26]
    #16 Magento\Checkout\Block\Cart\Shipping\Interceptor->fetchView('/data/src/m2/ven...') called at [vendor/magento/framework/View/Element/Template.php:301]
    #17 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
    #18 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
    #19 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
    #20 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
    #21 Magento\Framework\View\Layout->_renderBlock('checkout.cart.sh...') called at [vendor/magento/framework/View/Layout.php:533]
    #22 Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.sh...') called at [vendor/magento/framework/View/Layout.php:488]
    #23 Magento\Framework\View\Layout->renderElement('checkout.cart.sh...', false) called at [vendor/magento/framework/View/Layout.php:585]
    #24 Magento\Framework\View\Layout->_renderContainer('cart.summary', false) called at [vendor/magento/framework/View/Layout.php:535]
    #25 Magento\Framework\View\Layout->renderNonCachedElement('cart.summary') called at [vendor/magento/framework/View/Layout.php:488]
    #26 Magento\Framework\View\Layout->renderElement('cart.summary', false) called at [vendor/magento/framework/View/Layout.php:585]
    #27 Magento\Framework\View\Layout->_renderContainer('checkout.cart.co...', false) called at [vendor/magento/framework/View/Layout.php:535]
    #28 Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.co...') called at [vendor/magento/framework/View/Layout.php:488]
    #29 Magento\Framework\View\Layout->renderElement('checkout.cart.co...', false) called at [vendor/magento/framework/View/Layout.php:585]
    #30 Magento\Framework\View\Layout->_renderContainer('checkout.cart.it...', false) called at [vendor/magento/framework/View/Layout.php:535]
    #31 Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart.it...') called at [vendor/magento/framework/View/Layout.php:488]
    #32 Magento\Framework\View\Layout->renderElement('checkout.cart.it...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:518]
    #33 Magento\Framework\View\Element\AbstractBlock->getChildHtml('with-items') called at [vendor/magento/module-checkout/view/frontend/templates/cart.phtml:16]
    #34 include('/data/src/m2/ven...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
    #35 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Checkout\Block\Cart\Interceptor#000000007f3759eb00000000312df7ec#, '/data/src/m2/ven...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
    #36 Magento\Framework\View\Element\Template->fetchView('/data/src/m2/ven...') called at [vendor/magento/framework/Interception/Interceptor.php:58]
    #37 Magento\Checkout\Block\Cart\Interceptor->___callParent('fetchView', array('/data/src/m2/ven...')) called at [vendor/magento/framework/Interception/Interceptor.php:138]
    #38 Magento\Checkout\Block\Cart\Interceptor->Magento\Framework\Interception\{closure}('/data/src/m2/ven...') called at [vendor/magento/framework/Interception/Interceptor.php:153]
    #39 Magento\Checkout\Block\Cart\Interceptor->___callPlugins('fetchView', array('/data/src/m2/ven...'), array(array('searchautocomple...'))) called at [generated/code/Magento/Checkout/Block/Cart/Interceptor.php:26]
    #40 Magento\Checkout\Block\Cart\Interceptor->fetchView('/data/src/m2/ven...') called at [vendor/magento/framework/View/Element/Template.php:301]
    #41 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1097]
    #42 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
    #43 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
    #44 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
    #45 Magento\Framework\View\Layout->_renderBlock('checkout.cart') called at [vendor/magento/framework/View/Layout.php:533]
    #46 Magento\Framework\View\Layout->renderNonCachedElement('checkout.cart') called at [vendor/magento/framework/View/Layout.php:488]
    #47 Magento\Framework\View\Layout->renderElement('checkout.cart', false) called at [vendor/magento/framework/View/Layout.php:585]
    #48 Magento\Framework\View\Layout->_renderContainer('content', false) called at [vendor/magento/framework/View/Layout.php:535]
    #49 Magento\Framework\View\Layout->renderNonCachedElement('content') called at [vendor/magento/framework/View/Layout.php:488]
    #50 Magento\Framework\View\Layout->renderElement('content', false) called at [vendor/magento/framework/View/Layout.php:585]
    #51 Magento\Framework\View\Layout->_renderContainer('main', false) called at [vendor/magento/framework/View/Layout.php:535]
    #52 Magento\Framework\View\Layout->renderNonCachedElement('main') called at [vendor/magento/framework/View/Layout.php:488]
    #53 Magento\Framework\View\Layout->renderElement('main', false) called at [vendor/magento/framework/View/Layout.php:585]
    #54 Magento\Framework\View\Layout->_renderContainer('columns', false) called at [vendor/magento/framework/View/Layout.php:535]
    #55 Magento\Framework\View\Layout->renderNonCachedElement('columns') called at [vendor/magento/framework/View/Layout.php:488]
    #56 Magento\Framework\View\Layout->renderElement('columns', false) called at [vendor/magento/framework/View/Layout.php:585]
    #57 Magento\Framework\View\Layout->_renderContainer('main.content', false) called at [vendor/magento/framework/View/Layout.php:535]
    #58 Magento\Framework\View\Layout->renderNonCachedElement('main.content') called at [vendor/magento/framework/View/Layout.php:488]
    #59 Magento\Framework\View\Layout->renderElement('main.content', false) called at [vendor/magento/framework/View/Layout.php:585]
    #60 Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:535]
    #61 Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') called at [vendor/magento/framework/View/Layout.php:488]
    #62 Magento\Framework\View\Layout->renderElement('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:585]
    #63 Magento\Framework\View\Layout->_renderContainer('root', false) called at [vendor/magento/framework/View/Layout.php:535]
    #64 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [vendor/magento/framework/View/Layout.php:488]
    #65 Magento\Framework\View\Layout->renderElement('root') called at [vendor/magento/framework/View/Layout.php:954]
    #66 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
    #67 Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
    #68 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
    #69 Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', array(), array(array('layout-model-cac...', 'mstCacheWarmerDe...'))) called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:39]
    #70 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
    #71 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#) called at [vendor/magento/framework/View/Result/Layout.php:171]
    #72 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
    #73 Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
    #74 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
    #75 Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#), array(array('result-messages', 'mstCacheWarmerCo...', 'FishPig_WordPres...', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:39]
    #76 Magento\Framework\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000007f376d7900000000312df7ec#) called at [vendor/magento/framework/App/Http.php:141]
    #77 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
    #78 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http#000000007f376d7b00000000312df7ec#) called at [index.php:39]
```

**Comment by sudheers-kensium** [comment] 2019-10-16 06:18
@MichaelThessel this is duplicate issue so I am closing this issue.

**Comment by MichaelThessel** [comment] 2019-10-16 06:20
Duplicate of which ticket?

**Comment by MichaelThessel** [comment] 2019-10-16 06:21
@sudheers-kensium can you please reference the duplicate ticket?

**Comment by sudheers-kensium** [comment] 2019-10-16 06:27
> @sudheers-kensium can you please reference the duplicate ticket?

#25078

**Comment by MichaelThessel** [comment] 2019-10-16 06:32
Not a duplicate I created that ticket as well. It's a different issue. The only thing that this has in common is that there is a additional button even though the extension is not enabled. The fact that you cannot disable the extension and that you get errors in the Chrome dev console is just happening for the Braintree module.

**Comment by engcom-Charlie** [comment] 2019-10-21 09:38
Hello @MichaelThessel 
We are not able to reproduce this issue on a fresh Magento 2.3-develop & 2.3.3.
 
**Manual testing scenario:**
1. Disable `Magento_BraintreeGraphQl` `Magento_Braintree` modules 
![image](https://user-images.githubusercontent.com/51680850/67192961-30a66f00-f3fd-11e9-885a-8c4e14a6e518.png)
2. Add product to cart, check cart page or minicart

**Actual result:**
1. Don't have additional paypal buttons if PP is not enabled(if `Magento_BraintreeGraphQl` `Magento_Braintree` modules  enabled too)
2. If the module is not enabled no Braintree specific JS should be loaded on the cart page

I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-21 09:38 UTC
Labels: Issue: Format is valid
