### ISSUE TITLE
Checkout error after upgrade to Magento 2.4.7 Error: "email" is required. Enter and try again  When clicking on the button: Place Order (in Connected mode and not Connected to the BO), I have this error message:

### ISSUE THREAD

**Issue by LemjidEminece** [magento/magento2#39127] opened 2024-08-30 09:38 UTC
### Summary

When clicking on the button: Place Order (in Connected mode and not Connected to the BO), I have this error message:

### Examples

![Capture d'écran 2024-08-30 100324](https://github.com/user-attachments/assets/5d06a4a4-8891-4c72-81b6-ee466cdabb04)
![Capture d'écran 2024-08-30 100417](https://github.com/user-attachments/assets/ddfdc5d9-828f-435b-8fce-48aa0226421d)

POST .../rest/store_en/V1/guest-carts/eFlVy14vPXeH9hU5R6BpK2QZiRCYx508/payment-information 400 (Bad Request)

 

After migration to 2.4.7 : The email field has disappeared Any help please . Order sending is blocked

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-09-02 09:32
Hi @LemjidEminece,

Thanks for your reporting and collaboration.

We have verified the issue and we are not able to reproduce the issue.Please check if any third party modules causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-09-13 06:24
Hi @LemjidEminece,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-13 06:24 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.7
