### ISSUE TITLE
Magento for sync product API not working every time

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#33734] opened 2021-08-10 08:12 UTC
### Preconditions (*)

1. Outdated Magento version? CE 2.2.2 - 2.2.
2.

### Steps to reproduce (*)

1. Call the api URLfor sync product : https://doorcloser.com/rest/V1/products/base-prices
Post Data : {"prices": [{"price": 72.29,"store_id": 1,"sku": "170A36"}]}
2. Now download product individual with URL
https://doorcloser.com/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=170A36&searchCriteria[filter_groups][0][filters][0][condition_type]=in  

Request and response 
[Magento API Request Response.txt](https://github.com/magento/magento2/files/6960054/Magento.API.Request.Response.txt)

### Expected result (*)

1. expected result in price 72.29 but getting 35.29 every time .
2.

### Actual result (*)

1. Some time its working fine but not all time.
2. ![image-20210809-090354](https://user-images.githubusercontent.com/54638813/128832001-e1bd4089-e0db-4fef-8342-a7ee931bf585.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-08-10 12:20
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible:
Steps performed:
1. Generate Admin access token using POST request: /rest/default/V1/integration/admin/token
2. Send POST request to /rest/V1/products/base-prices using below payload:
{
  "prices": [
    {
      "price": 72.29,
      "store_id": 1,
      "sku": "frrrfrerrrrr"
    }
  ]
}
3. Send POST request to /rest/V1/inventory/source-items using below payload:
{
  "sourceItems": [
    {
      "sku": "frrrfrerrrrr",
      "source_code": "base",
      "quantity": 0.0,
      "status": 0
    }
  ]
}

4. Hit the below GET request:
/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=sku&searchCriteria[filter_groups][0][filters][0][value]=frrrfrerrrrr&searchCriteria[filter_groups][0][filters][0][condition_type]=in

**No issue:** Response Price: 72.29 is displayed as expected
![image](https://user-images.githubusercontent.com/60198231/128865529-0e1b72a1-3c61-4322-b7db-edbe5aa3bc49.png)

@webgility-amazonapi Kindly recheck the issue on Magento 2.4-develop branch and provide the missing steps if any if the issue is still reproducible.
Thank you

**Comment by webgility-amazonapi** [comment] 2021-08-10 12:24
Hello engcom-November,

Have you tried several times? As this issue is sometimes not updating price and sometimes it is updating. Please try several times and this issue will be reproduced.

Thanks
Webgility

**Comment by webgility-amazonapi** [comment] 2021-08-12 06:34
Hello engcom-November,

What I have found is that you have tested this with latest version and the issue does not exists in "Magento 2.4". Please test and reproduce the issue in version "CE 2.2.2 - 2.2.3".

Thanks
Webgility.

**Comment by engcom-November** [comment] 2021-08-12 07:37
Hi @webgility-amazonapi,

Its recommended to verify the issues on Magento 2.4-develop branch only. Kindly upgrade your Magento version and recheck the issue. Closing this issue as "Price" is getting updated as expected in the API even after trying several times on Magento 2.4-develop branch.
Thank you.

**Closed as completed by engcom-November** 2021-08-12 07:37 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
