### ISSUE TITLE
Update Bundle Product without changes in bundle items 

### ISSUE THREAD

**Issue by miller-nicholas** [magento/magento2#6916] opened 2016-10-07 00:36 UTC
### Preconditions
1. Latest Magento 2.1.1 from release archive
### Steps to reproduce
1. Admin -> Catalog -> Products
2. Edit Bundle product, nothing change, just save it 

If you just update (not new) bundle product and edit any Bundle Items Saves works
I added new category and image, saves not works. Actually saves doesn't work for me even without any changes.

Update: i have more then 20 items, and save works only if i go to page 2 and wait until it loaded, then saves works correct.
### Actual result

Notice: Undefined index: delete in .../vendor/magento/module-bundle/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Bundle.php on line 130

**Comment by riyuk** [comment] 2016-10-07 09:46
Replacing in File `/vendor/magento/module-bundle/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Bundle.php`:
`if ((bool)$optionData['delete']) {`
&
`if ((bool)$linkData['delete']) {`

With:
`if (isset($optionData['delete']) && (bool)$optionData['delete']) {`
&
`if (isset($linkData['delete']) && (bool)$linkData['delete']) {`

does fix the Problem for me.
Probably also the solution for #6046.

**Comment by miller-nicholas** [comment] 2016-10-07 12:09
yeah, tx, just i want to get this working in next release :)

**Comment by TommyKolkman** [comment] 2016-10-18 09:49
@riyuk Thanks for the quick fix, works for me too. But come on Magento, this seriously can't be happening. We've got quite some websites depending on this stuff...

**Comment by TommyKolkman** [comment] 2016-10-18 12:12
@riyuk When I apply your fix, by the way, connections from catalog_product_bundle_option_value seem to disappear. Had this problem?

**Comment by quynhvv** [comment] 2016-11-03 09:04
Yeah, let's do steps as @riyuk hav indicated to solve this issue.

**Comment by quynhvv** [comment] 2016-11-03 10:04
Hi guys,

> Notice: Undefined index: delete in .../vendor/magento/module-bundle/Controller/Adminhtml/Product/Initialization/Helper/Plugin/Bundle.php on line 130

The root issue because the attribute sets of your bundle products was missing the Attribute group named
`Bundle Items`
So to solve this issue, for each the Attribute Set of your bundle products let's open it and add more the Attribute Group named `Bundle Items` and move the Attribute code named `shipment_type` to the Attribute Group you have just added. See more here: http://i.prntscr.com/1e45d623dafc4a8d97297ccf3b4eba6e.png

Let's do it to solve the issue!
Regards,
quynhvv

**Comment by IlnitskiyArtem** [comment] 2017-06-23 08:33
@magecodenet,  thanks for reporting this issue
Unfortunately I could not reproduce this issue. May you please advise if this problem is still relevant for latest release Magento 2?

**Comment by magekey** [comment] 2017-06-23 09:07
@IlnitskiyArtem 
yes it still there.

Release 2.1.7

Steps to reproduce:
1. Edit sample product "Sprite Yoga Companion Kit"
2. by default this product has 4 options in bundle items. You need to add more so in total you have at least 21 options. And now we got Bundle Items pager.
3. Save product with all options and reload page.
4. Click save without any changes. you should see error.
5. If you move to the second page of bundle items and click save everything works correct.
Looks like system think we trying to remove invisible items.

**Comment by IlnitskiyArtem** [comment] 2017-06-23 12:16
@magekey, Thanks for the additional information!
We've created internal ticket MAGETWO-70162 to address this issue.

**Comment by nkajic** [comment] 2017-09-26 10:26
Hi all, it seems problem is caused when we have two pages of product options and secund page it not loaded and therefore not filled with required fields. If you try to open secound page od product options and hit save product will be saved without problems.

https://i.imgur.com/TnamhJK.png

**Comment by magento-engcom-team** [comment] 2017-10-06 11:30
@magecodenet, thank you for your report.
We've created internal ticket(s) MAGETWO-70162 to track progress on the issue.

**Comment by giacmir** [comment] 2017-11-28 11:39
Seems like some strange server setting / php bug. 

If you inspect the request you can see all the fields leaving the browser, so it must be something server side.

Since it appears only above a certain number of options I tought it could be caused by a php `max_input_vars` setting being too low. But raising it doesn't solve.

**Comment by magento-team** [comment] 2017-12-28 06:15
Hi @magecodenet. Thank you for your report. 
The issue has been fixed in magento/magento2#12734 by @dzianis-yurevich in 2.2-develop branch
Related commit(s):
 - e6a7a4e82099de6e90239e7b0598c3ff43d1fb48

The fix will be available with the upcoming patch release.

**Closed as completed by magento-team** 2017-12-28 06:15 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2018-02-08 22:59
Hi @magecodenet. Thank you for your report. 
The issue has been fixed in magento-engcom/magento2ce#1359 by @magento-engcom-team in 2.3-develop branch
Related commit(s):
 - 1db3f8f6a336026d4a4493c8ba8d3e165ade66d8
 - 412d2287ee5a1a9620fb2a256bab562bdd10fe49
 - 02620b09456d77408ccbbd6a6b61a7b7ebcf73fa
 - 57c5d8a819e403905bd4d5419564d184712bc142
 - 94a3f0346ea086626d8b11c08fd397b11a570caa
 - 0d557dc99c15c6638e1c894ce46cb681a74b8912
 - 48baf590f86590c44bba81a9d5303902aed9d8d7
 - dc3bb78962c4522eb5df8a1a8f40c3bbe2b623fc
 - 0ab45334ef4d44e55c9f84f9c6e4b6a9e08e9237
 - 00f64b077ce00e55216e6ea9fb39071dc74b51a1
 - 440a1b5f9e6309fa87790a5f5b7d1b8fd7ffa53d
 - 4ed8f5b65d5d1779522653102120917c5f9578be
 - 656eeb5587eb1baebaffdc8ba68f1028afda8910
 - fd2f731f7efc4a2cec9e03f8de88bf39c0988829
 - 2c1a23faa60805bd63ff62216309d57a052612d1
 - f7ff71a92bcf56679b82c22549244e1adb9f4ed2
 - ac9bcfa15b1b0b98f9cb3851f4d9b56e18ede89b
 - 55debe0c2b514e37271ed6edf20b95fec6cc41c9
 - 349508628dc1c4334e13b3541227505e26c93c64
 - d678f1568b6e2d30c6d651dd3da02e0f3512353e
 - bf8ee3089f005e267f0b14cf81b14e9a3ee26986
 - 335c91c07dde6f90309f11cf0efcbd9127630955
 - c5a823f95161f7c13fb0947abb445fdc9e9a620a
 - 696a5a575513bb87c47ffc15a571034b0b91d7ae

The fix will be available with the upcoming 2.3.0 release.
