### ISSUE TITLE
Full Page Cache: 'cachable=false' attribute does not work for Product Page

### ISSUE THREAD

**Issue by stasleo** [magento/magento2#3202] opened 2016-01-29 14:49 UTC
There is no way to insert some dynamic content to Product Page. Only via AJAX :(. Using AJAX is not an option, becuase block will be displayed on product page with a delay, and this behavior is not OK from UX point of view.

According to our research, 'cachable=false' attribute works properly for all pages except product page.
## 

Best regards
Product Manager at aheadWorks

**Comment by stasleo** [comment] 2016-05-18 09:11
any updates on this?

**Comment by pboisvert** [comment] 2016-05-18 12:54
@choukalos Can you have the team investigate?

**Comment by kandy** [comment] 2016-05-20 18:28
Can you describe in more details what yo mean in " 'cachable=false' attribute does not work for Product Page"? If you add any block with 'cacheable=false' to page then FPC will disabled for this page.

If you need render dynamic data on page please use JavaScript for this.

**Comment by ashishnai** [comment] 2016-07-08 05:12
I thought cacheable="false" is a way for whole punching. But currently it skips entire page from FPC i.e if a block has property cacheable="false", FPC is disabled for that page. 

Is this the expected behavior??

If so, how whole punching can be done in FPC?

**Comment by Vinai** [comment] 2016-07-08 08:29
It is the intended behavior. A block with `cachable="false"` will make the whole page uncached.
There are two options for adding dynamic "holepunched" blocks to a page:
- You can use the `ttl="300"` attribute, but that only works with the varnish cache backend (not the builtin PHP version) as it uses ESI
- You can set the `isPrivateScope` property of a block to true (can't be done using layout XML, only PHP). In this case the block will be requested via ajax after the cache page is rendered in the browser.

If you want further information consider asking a question in the community forums or on Magneot stackexchange.

**Comment by Vinai** [comment] 2016-07-08 08:30
Since this isn't a bug, I'll be closing the issue. If you don't consider it properly handled please feel free to reopen.

**Closed as completed by Vinai** 2016-07-08 08:30 UTC

**Comment by adragus-inviqa** [comment] 2016-07-08 09:01
And there's another options: ajaxifying the block entirely.

Btw, if you're using `isPrivateScope = true`, the block's content will be cached in the browser, so the next fetch is instant. Not _that_ bad of a UX.

**Comment by PascalBrouwers** [comment] 2016-10-13 12:17
Seeing that isPrivateScope is no longer supported (http://devdocs.magento.com/guides/v2.0/config-guide/cache/cache-priv-priv.html) can we remove this option? Because now it is too confusing. I expected a FPC block hole punch but it makes the whole page uncached.
