### ISSUE TITLE
Elasticsearch8 does not work when Server has Basic authentication

### ISSUE THREAD

**Issue by lory-to** [magento/magento2#37356] opened 2023-04-10 15:43 UTC
### Preconditions and environment

- 2.4.6 CE
- Elasticsearch server 8.X

### Steps to reproduce

1. Deploy elastic-cloud with Elasticsearch 8.X
2. Configure Magento to use elasticsearch8, see https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch
3. Configure `Catalog > Catalog > Catalog Search` as follows
```["hostname"]=>
  string(75) "https://*****.*****.azure.elastic-cloud.com"
  ["port"]=>
  NULL
  ["index"]=>
  string(8) "magento2"
  ["enableAuth"]=>
  string(1) "1"
  ["username"]=>
  string(7) "*****"
  ["password"]=>
  string(24) "*****"
  ["timeout"]=>
  string(2) "15"
  ```
4. Run `bin/magento setup:upgrade`
5. Run `bin/magento indexer:reindex`

### Expected result

`bin/magento setup:upgrade` ends without errors
`bin/magento indexer:reindex` ends without errors

### Actual result

- `bin/magento setup:upgrade` ends with `Could not validate a connection to Elasticsearch. Verify that the Elasticsearch host and port are configured correctly.`
- `bin/magento indexer:reindex` ends with `Indexer handler is not available: elasticsearch8`

### Additional information

The versions required for `elastic/transport` and `elasticsearch/elasticsearch` ignore the settings for `username` and `password`
The Transport then does not have such credentials and according to the code they are not recorvered from the available nodes. (the nodes have the credentials as the URL is created prepending `username:password@` but this URL is not used.
`\Elastic\Elasticsearch\Client::sendRequest` is then sent without credentials.

Suggested change `\Magento\Elasticsearch8\Model\Client\Elasticsearch::buildESConfig`

add the following
```
$options['basicAuthentication'] = [$options['username'], $options['password']];
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-28 13:01
Hi @lory-to,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.


We have Configured Magento with elasticsearch8 using https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch.


<img width="1149" alt="Screenshot 2023-04-28 at 12 56 46 PM" src="https://user-images.githubusercontent.com/51680745/235123385-a9c6593a-f4b4-4196-a50d-7a189eff3ed0.png">


<img width="772" alt="Screenshot 2023-04-28 at 12 59 09 PM" src="https://user-images.githubusercontent.com/51680745/235123425-8c285ed3-db5c-4c28-b505-4e6989234c0b.png">



Both the `bin/magento setup:upgrade` and `bin/magento indexer:reindex` ends without errors.


Kindly recheck the behavior on Magento 2.4.6 instance and elaborate steps to reproduce if the issue is still reproducible.



Thanks.

**Comment by lory-to** [comment] 2023-04-30 07:36
> Hi @lory-to,
> We have Configured Magento with elasticsearch8 using https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch.
> 
> Both the `bin/magento setup:upgrade` and `bin/magento indexer:reindex` ends without errors.
> 
> Kindly recheck the behavior on Magento 2.4.6 instance and elaborate steps to reproduce if the issue is still reproducible.
> 
> Thanks.

Good morning @engcom-Bravo
Does your Elasticsearch instance have Authentication enabled?

This is happening only when I'm required to imput username and password.

**Comment by engcom-Bravo** [comment] 2023-05-02 12:30
Hi @lory-to,

Thanks for your update.

Verified the issue on Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.

Please try to install elasticsearch with setup : install command.Kindly check this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/advanced.html

`bin/magento setup:install --base-url=[http://magento246.local](http://magento2.local/) --db-host=localhost --db-name=magento246 --db-user=global --db-password=Global@123 --admin-firstname="admin" --admin-lastname=admin --admin-email=admin@admin.com --admin-user=admin --admin-password=admin123 --language=en_US --currency="USD" --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin --search-engine=elasticsearch8 --elasticsearch-host=localhost --elasticsearch-port=9200 --elasticsearch-username=magento --elasticsearch-password=guest`

We have configured Magento instance with Elasticsearch8 using this document https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/prepare/prerequisites.html?lang=en#upgrade-elasticsearch


<img width="1250" alt="Screenshot 2023-05-02 at 1 36 53 PM" src="https://user-images.githubusercontent.com/51680745/235613925-245ec214-4523-47cd-901d-ace093077262.png">



<img width="784" alt="Screenshot 2023-05-02 at 1 46 48 PM" src="https://user-images.githubusercontent.com/51680745/235615096-665e1dc8-56df-42c8-a1ec-a84fa22484c8.png">






https://user-images.githubusercontent.com/51680745/235614003-9b47f854-09c4-4553-914e-3dbf5bcce37e.mov




Both the `bin/magento setup:upgrade` and `bin/magento indexer:reindex` ends without errors.

Kindly recheck the behavior on Magento 2.4.6 instance and elaborate steps to reproduce if the issue is still reproducible.


Please let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-15 06:03
Hi @lory-tom,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-15 06:03 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by jtolhurst-trellis** [comment] 2023-05-31 23:55
I have also ran into this issue on 2.4.6 and found @lory-to 's proposed solution to work.  This seem to happen with external hosts.  I also am using an externally hosted instance and not one hosted on `localhost`.  It is possible this could play a role in how you are testing.

In either case, it would be beneficial for Magento to use the Elasticsearch library correctly.  Here is a demonstration without Magento that shows how Magento's config array that it builds does not work, but adding the correct configurations allows a connection.

```
composer require elasticsearch/elasticsearch
```

Create a file `test.php`

```
<?php

include 'vendor/autoload.php';

use Elastic\Elasticsearch\ClientBuilder;

// How Magento would build an options array
$options1 = [
    'hostname' => 'https://my-instance.es.us-east-1.aws.found.io',
    'port' => '443',
    'index' => 'myindex',
    'enableAuth' => '1',
    'username' => 'username',
    'password' => 'password',
    'timeout' => '15',
    'hosts' => [
        'https://username:password@my-instance.es.us-east-1.aws.found.io:443'
    ]
];

$client1 = ClientBuilder::fromConfig($options1, true);

// Adding in `basicAuthentication` to the config
$options2 = [
    'hostname' => 'https://my-instance.es.us-east-1.aws.found.io',
    'port' => '443',
    'index' => 'myindex',
    'enableAuth' => '1',
    'username' => 'username',
    'password' => 'password',
    'timeout' => '15',
    'basicAuthentication' => [
        'username',
        'password',
    ],
    'hosts' => [
        'https://username:password@my-instance.es.us-east-1.aws.found.io:443'
    ]
];

$client2 = ClientBuilder::fromConfig($options2, true);


// Info API
$response1 = $client1->ping()->asBool();
$response2 = $client2->ping()->asBool();
```

Execute the file

```
php test.php
```

And you will get the following output

```
bool(false)
bool(true)
```

Where the first `ping()` fails because of a 401 Unauthorized response from the server, but the second will succeed because it properly authenticates.  So it seems that Magento could do better to correctly configure the Elasticsearch client to ensure a connection to all clients.

As an additional note, the current array that Magento passes is largely discarded.  If you do not silence the errors, `fromConfig($options, false)`, the Elasticsearch library will emit an error showing that it discards all but the `hosts` key from the options because they are not valid configurations.
