### ISSUE TITLE
How to I enable and disable module in WHM Cpanel 

### ISSUE THREAD

**Issue by osmansorkar** [magento/magento2#4338] opened 2016-04-28 12:01 UTC
Hello,
I has seen Magento 2 need terminal to enable , disable and update module. 
In WHM Cpanel I dont find any Terminal because it is shared hosting. So is it true any extra module can't not use in WHM Cpanel.

How to I get all feature of Magento 2 in WHM Cpanel ................ 

I already use magento 1 in WHM Cpanel .

**Comment by mazhalai** [comment] 2016-04-28 13:07
@osmansorkar Navigate in admin to System->Web Setup Wizard-> Component Manager. This will show a list of all modules, you can enable and disable them by following steps [here](http://devdocs.magento.com/guides/v2.0/comp-mgr/compman-main-pg.html#compman-access-enable)

Closing since this is not a bug.

**Closed as completed by mazhalai** 2016-04-28 13:07 UTC

**Comment by osmansorkar** [comment] 2016-04-28 13:44
Can I install and upgrade a module in System->Web Setup Wizard-> Component Manager.

**Comment by mazhalai** [comment] 2016-04-28 13:51
Yes your purchases in marketplace will show up in component manager. You need to save you keys in "system config" and then click sync on component manager page.

**Comment by osmansorkar** [comment] 2016-04-29 09:08
I have a blog module which download from another site. Now how to it install in Magento 2 without terminal......... I try many time but every time I fail.
