### ISSUE TITLE
Dependency version audit plugin doesn't respect locked versions (magento/composer-dependency-version-audit-plugin)

### ISSUE THREAD

**Issue by denis-zyk** [magento/magento2#34390] opened 2021-10-19 15:12 UTC
### Preconditions (*)

1. PHP 7.4
2. Magento 2.4.3-p1
3. composer v1
4. magento/composer-dependency-version-audit-plugin 0.1.1
4. Some dependency available in both private and public package repositories (e.g. `shipperhq/module-shipper`), where public repo version is higher than private repo version (e.g. `20.45.6` vs. `20.45.5`)

### Steps to reproduce (*)

1. Lock module in question to a specific version in `composer.json` (e.g. `"shipperhq/module-shipper": "20.45.5"`) as suggested on https://support.magento.com/hc/en-us/articles/4410675867917-Composer-plugin-against-Dependency-Confusion-attacks
> ## Recommendations to merchants
> * Take the error message shown when the plugin stops the composer install/update seriously, and contact the extension developer if you recognize the potentially compromised package.
> * You can still install Adobe Commerce with the safe version of the package from the Marketplace or another trusted private repository.
> * __Change the required package version in your composer.json to the exact version found in the Marketplace in order to proceed with the composer install/update.__
2.  Run `composer install` (if you don't have any lock file yet) or `composer update`

### Expected result (*)

1. Install succeeds

### Actual result (*)

1. The exception is thrown although the module is set to specific version `20.45.5` in `composer.json`
2. ![image](https://user-images.githubusercontent.com/44240055/137938360-48d955d7-b710-4f78-b96c-2d033761f775.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-11-11 12:04
Hello @denis-zyk,

We have tried to reproduce the issue in Magento 2.4.3-p1 version with mentioned steps. But for us, the issue is not reproducible. The whole process is running successfully. Please refer to the below screenshot for reference:
![image](https://user-images.githubusercontent.com/51681618/141294954-f0de1105-2bd5-4165-a37d-d579f37aa4b1.png)

Let us know if we missed anything.

Thanks

**Comment by denis-zyk** [comment] 2021-11-11 13:47
Hello @engcom-Hotel,
Have you tried to that with an empty vendor directory, e.g. ```rm -rf vendor/* && composer update```?

**Comment by engcom-Hotel** [comment] 2021-11-25 07:49
Hello @denis-zyk,

We have tried this as well but are still unable to reproduce the issue:

![image](https://user-images.githubusercontent.com/51681618/143400738-5252a015-c053-4748-9b4c-6ba30e422981.png)

Please let us know in case we missed anything
Thanks

**Comment by lakshmana** [comment] 2021-12-06 09:11
The issue is linked to this one [we also had similar ](https://github.com/magento/magento2/issues/34325) 
The main culprit seems to be magento/composer-dependency-version-audit-plugin and the issues is resolved when this library is removed. Any if it is safe to remove this library `magento/composer-dependency-version-audit-plugin` ?

**Comment by Green2Matter** [comment] 2021-12-08 11:00
magento/composer-dependency-version-audit-plugin and ShipperHQ caused a big fail when issuing `composer update` command:
<img width="1678" alt="composer update fail" src="https://user-images.githubusercontent.com/71682684/145196140-27f7fabb-6b2f-4e82-8850-f025830abfc3.png">
I had to restore my own magento backup because at that point many files were missing (magento, autoload and so on)
After removing magento/composer-dependency-version-audit-plugin I was able to completely remove  ShipperHQ and I reinstalled everything by deleting vendor directory and lock file followed by `composer install`

**Comment by engcom-Hotel** [comment] 2021-12-09 09:39
Hello @denis-zyk @Green2Matter,

I have tried once again with Magento 2.4.3-P1 but I am unable to reproduce the issue. Please have a look into below video for reference and let us know we have missed anything:

https://user-images.githubusercontent.com/51681618/145371756-f7e1b70b-460b-4508-aad6-1c651e1f43a0.mp4

Thanks

**Comment by Green2Matter** [comment] 2021-12-09 11:42
Hi @engcom-Hotel 
I have tried as well installing autocomplete
<img width="1042" alt="autocomplete failed installation" src="https://user-images.githubusercontent.com/71682684/145389979-06a0977e-bb58-4dff-b1b2-ab14e72ff4a8.png">
But then composer-dependency-version-audit-plugin kicks in and stops installation... Couldn't we set repos we want to update from?

**Comment by engcom-Hotel** [comment] 2021-12-10 12:37
Hello @Green2Matter,

Thanks for the reply!

I tried to install `shipperhq/module-address-autocomplete`, and I am able to install it without any issues:

![image](https://user-images.githubusercontent.com/51681618/145574908-5780578f-d04d-4a99-bae1-af832127ec04.png)

I think I am missing something to reproduce the issue. Please help me in reproduction of the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-12-24 05:59
Dear @Green2Matter,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-12-24 05:59 UTC
Labels: Issue: needs update

**Comment by hatimeria-artur-jewula** [comment] 2022-05-24 12:45
@engcom-Hotel do you have shipperhq module purchased for the account you are using to connect to repo.magento.com? Because if you don't then you will not see the problem. Today I got the same error with `mailchimp/mc-magento2` module. repo.magento.com has version 103.4.44 and packagist 103.4.45. Even though I have it locked on 103.4.44 and lock file fetches the module from repo.magento. com and not packagist I still have the error that prevents building an environment

**Comment by hatimeria-artur-jewula** [comment] 2022-05-24 12:55
What will happen if a vendor decides not to provide updates to magento marketplace and instead use packagist for future release. That package will be completely blocked and the name will be held as a hostage by this plugin. That vendor will have to change package name so it won't be found in repo.magento.com

**Comment by hostep** [comment] 2022-05-25 09:32
If you would be able to remove a module from your Magento Marketplace account, I think it should solve itself with the next `composer update` run. But I'm not sure if that's possible, I can't immediately find a way to remove a module from my account at the Marketplace ...

**Comment by speedupmate** [comment] 2022-05-25 10:12
nothing bad in changing the namespace and using a replace in composer.json for old namespace

**Comment by shochdoerfer** [comment] 2022-05-25 13:12
It's manual work but you can exclude packages via the repositories configuration in the composer.json file like this:
```
"0": {
    "type": "composer",
    "url": "https://repo.magento.com/",
    "exclude": ["vendor/magento-module"]
}
```

Not sure if this solves the use-case you need.

**Comment by engcom-Hotel** [comment] 2022-05-25 14:40
As seen in the activity on this ticket, we will do more analysis on this and update here soon.
