### ISSUE TITLE
Thumbnail product image in checkout page order summary too big

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2#28634] opened 2020-06-09 11:25 UTC
### Preconditions (*)

1. 2.4.0
2. sample data installed

### Steps to reproduce (*)

1. Add product to cart
2. Go to checkout page

### Expected result (*)

1. [Screenshots, logs or description]
2. Image size idealy will be 75x75

### Actual result (*)

1. [Screenshots, logs or description]
2. Image size 150x150

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-06-09 12:43
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-09 12:43
Hi @ajijshekh123. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-09 12:45
Hi @ajijshekh123, here is your [Magento instance](https://i-28634-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28634-2-4-develop.instances.magento-community.engineering/admin_7d74](https://i-28634-2-4-develop.instances.magento-community.engineering/admin_7d74)
Login: `7458527a` Password: `985982f5301b`
Instance will be terminated in up to 3 hours.

**Comment by ajijshekh123** [comment] 2020-06-09 12:56
Hello @mrtuvn,
This issue is reproduced on Magento 2.4 Instance.
See attached the screenshot:

![Checkout_ProductImage](https://user-images.githubusercontent.com/24711761/84149812-aa6b9580-aa7e-11ea-8633-43e9a8709b61.png)

Thanks.

**Comment by magento-engcom-team** [comment] 2020-06-09 12:57
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35036` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-06-11 00:38
Hello @mrtuvn 
fyi: @ajijshekh123 

Thank you for your report and confirmation!

Occasionally, I found this bug was found and reporter into internal Jira during regression before 2.4.0
The bug has been fixed in delivered into the internal 2.4.0 branch (not publicly available)
- Fix has been done and delivered in the scope of `MC-34950`
- Internal PR: https://github.com/magento/magento2ce/pull/5757


Changes from the internal branch are not synced yet with the public `2.4-develop` branch. But it will be soon.

I provide details/commits here as soon as it will be available in `2.4-develop`

**Comment by ajijshekh123** [comment] 2020-06-11 04:52
Thanks for the information @sdzhepa

**Comment by sdzhepa** [comment] 2020-07-29 13:50
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-29 13:50
Hi @sdzhepa. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-07-29 13:51
Hi @sdzhepa, here is your [Magento instance](https://i-28634-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28634-2-4-develop.instances.magento-community.engineering/admin_3d7d](https://i-28634-2-4-develop.instances.magento-community.engineering/admin_3d7d)
Login: `96540529` Password: `b117d394aa9a`
Instance will be terminated in up to 3 hours.

**Comment by sdzhepa** [comment] 2020-07-29 13:56
Hello @mrtuvn 
cc: @ajijshekh123 

The branches have been synced. And this fix for the issue is available now 
Issue can be closed.

![2020-07-29_8-55-22](https://user-images.githubusercontent.com/3409584/88809165-68ef9080-d179-11ea-95d3-ad43ab4683f5.jpg)

**Closed as completed by sdzhepa** 2020-07-29 13:56 UTC
Labels: Issue: Ready for Work, Component: Checkout, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Reproduced on 2.4.x, Priority: P1, Severity: S1, Triage: Done, Progress: done, Reported on 2.4.0
