### ISSUE TITLE
PHP Fatal Error: Uncaught Type Error Account Management Authenticate

### ISSUE THREAD

**Issue by Mkennethsmith** [magento/magento2#21285] opened 2019-02-16 20:49 UTC
### Preconditions (*)

1. Fresh install of Magento 2.3 Commerce 

### Steps to reproduce (*)

1.  With a fresh install of Magento 2.3 Commerce, create a single customer via the admin panel
2. On the frontend, attempt to login with the created customer with anything in the password field

### Expected result (*)

1. An invalid exception message of  "'Invalid login or password." is displayed to the user
2. A message prompting the user to access their email account and click on the set password link provided

### Actual result (*)

1. PHP Fatal Error for uncaught TypeError:  explode() expects parameter 2 to be string, null given  
2.  This happens with any customer where no password hash has yet been set. 

<img width="1552" alt="screenshot 2019-02-16 at 20 48 13" src="https://user-images.githubusercontent.com/16221145/52905054-463f1580-322c-11e9-9b79-de8ae51542b9.png">

**Comment by magento-engcom-team** [comment] 2019-02-16 20:50
Hi @Mkennethsmith. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Mkennethsmith do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Mkennethsmith** [comment] 2019-02-16 21:04
Issue seems to stem from the fact a user has no passwords set yet, and there for no password hash yet exists. 

See screen shot below for reference to issue in \Magento\Framework\Encryption\Encryptor.php line 238. 
 
![screenshot 2019-02-16 at 20 58 15](https://user-images.githubusercontent.com/16221145/52905153-0711c400-322e-11e9-86f5-272573178eca.png)


The most appropriate place to check if a hash exists would be in the Magento\Customer\Model\Authentication.php file line 169. 

![screenshot 2019-02-16 at 21 04 17](https://user-images.githubusercontent.com/16221145/52905183-7ab3d100-322e-11e9-8674-b5f6cc198a09.png)

**Comment by magento-engcom-team** [comment] 2019-02-17 11:44
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-17 11:45
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-17 11:46
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-17 11:46
Hi @shikhamis11, here is your [Magento instance](https://i-21285-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21285-2-3-develop.instances.magento-community.engineering/admin](https://i-21285-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-02-17 11:55
@Mkennethsmith this issue is not reproduceable at current Magento 2.3 develop instance

**Closed as completed by shikhamis11** 2019-02-17 11:55 UTC
Labels: Issue: Format is valid

**Comment by Mkennethsmith** [comment] 2019-02-18 09:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-18 09:37
Hi @Mkennethsmith. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-18 09:38
Hi @Mkennethsmith, here is your [Magento instance](https://i-21285-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21285-2-3-develop.instances.magento-community.engineering/admin](https://i-21285-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.
