### ISSUE TITLE
API returns quote totals data for a specified cart not properly working

### ISSUE THREAD

**Issue by cys2best** [magento/magento2#24548] opened 2019-09-11 04:21 UTC
Hello, 

I'm using rest API of Magento to develop a mobile app base on Reactjs

# Preconditions (*)

1. Magento ver. 2.2.8
2. PHP 7.1.32

# Steps to reproduce
1. Place order via API (carts/mine/payment-information)
2. Create a new quote (carts/mine)
3. Add product to cart (carts/mine/items)
4. Get totals data of new quotes (carts/mine/totals)

This issue just comes from first time add a product to cart after I created a new empty quote

# Expected result (*)
{
    "grand_total": 169000,
    "base_grand_total": 169000,
    "subtotal": 169000,
    "base_subtotal": 169000,
    "discount_amount": 0,
    "base_discount_amount": 0,
    "subtotal_with_discount": 169000,
    "base_subtotal_with_discount": 169000,
    "shipping_amount": 0,
    "base_shipping_amount": 0,
    "shipping_discount_amount": 0,
    "base_shipping_discount_amount": 0,
    "tax_amount": 0,
    "base_tax_amount": 0,
    "weee_tax_applied_amount": null,
    "shipping_tax_amount": 0,
    "base_shipping_tax_amount": 0,
    "subtotal_incl_tax": 169000,
    "shipping_incl_tax": 0,
    "base_shipping_incl_tax": 0,
    "base_currency_code": "VND",
    "quote_currency_code": "VND",
    "items_qty": 1,
    "items": [
        {
            "item_id": 21800,
            "price": 169000,
            "base_price": 169000,
            "qty": 1,
            "row_total": 169000,
            "base_row_total": 169000,
            "row_total_with_discount": 0,
            "tax_amount": 0,
            "base_tax_amount": 0,
            "tax_percent": 0,
            "discount_amount": 0,
            "base_discount_amount": 0,
            "discount_percent": 0,
            "price_incl_tax": 169000,
            "base_price_incl_tax": 169000,
            "row_total_incl_tax": 169000,
            "base_row_total_incl_tax": 169000,
            "options": "[]",
            "weee_tax_applied_amount": null,
            "weee_tax_applied": null,
            "name": "Nước Pepsi - Thùng 24 lon x 330ml"
        }
    ],
    "total_segments": [
        {
            "code": "subtotal",
            "title": "Tổng phụ",
            "value": 169000
        },
        {
            "code": "shipping",
            "title": "Vận chuyển & xử lý",
            "value": 0
        },
        {
            "code": "tax",
            "title": "Thuế",
            "value": 0,
            "extension_attributes": {
                "tax_grandtotal_details": []
            }
        },
        {
            "code": "grand_total",
            "title": "Tổng số",
            "value": 169000,
            "area": "footer"
        }
    ]
}

# Actual result (*)
{
    "grand_total": 0,
    "weee_tax_applied_amount": null,
    "base_currency_code": "VND",
    "quote_currency_code": "VND",
    "items_qty": 1,
    "items": [
        {
            "item_id": 21800,
            "price": 169000,
            "base_price": 0,
            "qty": 1,
            "row_total": 0,
            "base_row_total": 0,
            "row_total_with_discount": 0,
            "tax_amount": 0,
            "base_tax_amount": 0,
            "tax_percent": 0,
            "discount_amount": 0,
            "base_discount_amount": 0,
            "discount_percent": 0,
            "options": "[]",
            "weee_tax_applied_amount": null,
            "weee_tax_applied": null,
            "name": "Nước Pepsi - Thùng 24 lon x 330ml"
        }
    ],
    "total_segments": [
        {
            "code": "subtotal",
            "title": "Tổng phụ",
            "value": null
        },
        {
            "code": "shipping",
            "title": "Vận chuyển & xử lý",
            "value": null
        },
        {
            "code": "tax",
            "title": "Thuế",
            "value": 0,
            "extension_attributes": {
                "tax_grandtotal_details": []
            }
        },
        {
            "code": "grand_total",
            "title": "Tổng số",
            "value": null,
            "area": "footer"
        }
    ]
}

**Comment by engcom-Charlie** [comment] 2019-09-11 07:21
Hello @cys2best 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates 2.3-develop branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-09-11 07:21 UTC
Labels: Issue: Format is valid

**Comment by cys2best** [comment] 2019-09-11 09:03
Hi @engcom-Charlie. Thank you for spend time with my issue.
It's too sad when heard Magento no longer support on v2.2. BTW, do you have any suggestions with my issue, I will fix it by myself

**Comment by engcom-Charlie** [comment] 2019-09-11 11:47
@cys2best Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.
