### ISSUE TITLE
@magento-team - Now it is enough with your bugs - Paypal Express is not usable!

### ISSUE THREAD

**Issue by andidhouse** [magento/magento2#10464] opened 2017-08-08 11:46 UTC
We really learned to live with the buggy coding of the magento2 system BUT now it is really enough.

The out of the box integrated PayPal express module is completely rubbish.
If you look at the bugs here - several times reported - never fixed.

In our case: 

Running Magento 2.1.7 via download on Nginx/php7/varnish

People are complaining that when they get redirected from PayPal normally to the success page of magento they are redirected instead to the magento shopping cart page with several error messages (this is reported here several times - several month ago!).

The order is placed right in the backend but the user does not even get an order confirmation.

So @magento-team - what is the point here. Paypal is unusable with your eccommrece system and now what?

- creating internal tickets again and let 1 year pass before anything changes?
- provide a quick fix? -- You know about this bug since month and do nothing to fix it in the current 2.1.7 version?

This is really a behavior of programmers which is worst case. Allen Kent told me 1 year ago that you gonna improve your service here but the opposite happens.

You guys are creating internal tickets again and again but no bugs are fixed.

For us: We as a premium PayPal partner contacted PayPal and will discontinue our PayPal accounts - PayPal is informed and i am sure will come back to you guys. 

If this is not a primary 1+++ bug to fix ASAP in a view days for the current version 2.1.7 i am not shure we can believe magento2 is a system to rely on.

What do you say against this? You know this bug for months and now?

We really have enough of your internal tickets which are never fixed - really a shame for the person who is responsible for a stable system at your company.

**Comment by careys7** [comment] 2017-08-08 21:52
@andidhouse what are the referenced ticket numbers and error messages you are seeing? 

A lot of fixes for open Github issues are available in the develop branch.

**Comment by misha-kotov** [comment] 2017-08-08 21:56
Thanks, was just going to ask for the same thing.

**Comment by andidhouse** [comment] 2017-08-08 22:05
For example 

#10142

If search for "PayPal" here at GitHub you will get al lot of tickets and find the same errors again and again - reported 6-12 month. No solution - not implemented in the latest version.

Not shure how bugs in the PayPal extension can be just ignored for so long. Our shops run at amazon pay for the moment - close to PayPal performance. Bad news for PayPal - think they will be not very happy.

**Comment by misha-kotov** [comment] 2017-08-08 22:17
@andidhouse the issue you cite was created one month ago and is already in process of being fixed for the next release. We will update the ticket with more info as soon as we can. 

Any software will have bugs, and the Paypal module is no exception. Not all issues are created equal, and we do our best to prioritize and work on them appropriately. Upvoting and contributing to discussion of a specific issue normally helps it get noticed.

**Comment by orlangur** [comment] 2017-08-09 09:07
@andidhouse from https://github.com/magento/magento2/issues/6296 it looks like issue was fixed in `develop` and then backported to `2.1.x` https://github.com/magento/magento2/blame/2.1.8-preview/app/code/Magento/Paypal/Model/Express/Checkout.php#L550. Did you have a chance to check if the issue still persists in `2.1.8-preview`?

https://github.com/magento/magento2/issues/9116 looks like the issue is quite hard to reproduce thus obviously hard to fix. There were some observations regarding inventory on problematic sites, it could help as well. Maybe it occurs only in some rare circumstances, like only when the last product in stock is bought.

**Comment by andidhouse** [comment] 2017-08-09 09:28
Hi all,

thanks for the answers.
The main problem in this case i think is really:

Paypal cooperates with magento - the extension comes as default in the system.

So magento is the largest ecommerce system in the world right now - also PayPal is one of the largest payment providers.

Then if you search for "PayPal" here at GitHub you find over one hundred? bugs reported - some of them closed, some fixed some with internal tickets some open.

So now? Not even the biggest commerce system in the world cooperating with one of the biggest payment providers get it to manage to build a very stable checkout payment solution? In my point of view this can not be and has only one reason: bad quality programming, bad code AND bad testing.  You can see this here so many times. more then a view thousand bugs reported in less then a year is a absolute no go for an ecommrece system.

We are working also with other small and enterprise ecommerce systems here like shopify (enterprise), shopware, oxid, etc. - None of these systems are even close in bugs to magento2. None of them have a bug fixing range of in most cases 6-18 month. 

It is really hard to believe in magento2 - with every release new bugs are introduced and in best case maybe 10 existing bugs are solved.

In the PayPal case i think it should be quite simple as this is one of the most important implementations for both companies:

Magento and PayPal should really overthink the integration with the background that there are hundreds of bugs reported here with PayPal. You guys should test every scenario and test test test. I think the users here do not report any bugs without a reason.

In our case we spent so many times in bugfixing we could have build 10 systems on other platforms. 

Not happy with that situation at all.

**Comment by orlangur** [comment] 2017-08-09 17:01
@andidhouse `2.1.8` was released a hour ago by the way. Would you mind to give it a try? :wink:

**Comment by misha-kotov** [comment] 2017-08-09 18:13
@andidhouse we understand your frustrations and appreciate you voicing your concerns. 

We've made great strides in improving our overall quality lately but are always trying to do more. [2.1.8 release](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.8CE.html) that went out today fixed over 100 issues (closer to 150 if we count issues that were found and fixed internally), not "best case 10 existing bugs". It's also the first release containing a significant number of contributions from this community. This is something we strongly encourage and we're confident that together with the extra help from our contributors we'll build a better and better product. 

PS Comparing Magento to SMB platforms like Shopify in terms of numbers of issues is not really a fair comparison. Magento is much more feature rich and hence has a much more complex codebase that is more difficult to maintain. Thanks again for speaking out.

**Comment by gewaechshaus** [comment] 2017-08-11 15:54
@orlangur  - https://github.com/magento/magento2/issues/10499

@andidhouse - it's a buggy paypal world since magento 1 roundings issues etc :) I am seeing this a bit more reflected as it ain't easy from a developers side, but from the marketing side it's a real shame for magento in general.  Shopify etc. will be happy. However, let's keep on reporting and fixing :)

**Comment by andidhouse** [comment] 2017-08-22 08:55
It is not a buggy PayPal world as on other ecommerce system PayPal works like a charm ;-).

We traced the bug and it is really the integrated PayPal extension which comes as default! It is just implemented wrong and so causing these massive errors.

We ended up in using another external papal extension and it is working great.

Really do not know why extensive testing is not done by the magento team - payment is a real issue on ecommerce sites.

**Comment by gewaechshaus** [comment] 2017-08-22 11:19
@andidhouse - we are testing out paypal over braintree... Are you refering the one made by mage2pro?

**Comment by okorshenko** [comment] 2017-09-30 08:07
@andidhouse please checkout latest 2.1.9 or 2.2.0 and let us know if you have any issues with the payment methods.

**Closed as completed by okorshenko** 2017-09-30 08:07 UTC
Labels: Fixed in 2.1.x, Fixed in 2.2.x, Issue: Format is not valid

**Comment by pbh-stu** [comment] 2017-11-28 13:46
I can confirm It's not fixed in 2.1.9

**Comment by aeu** [comment] 2017-12-18 19:19
I created another ticket because I thought this one was closed, but I am currently seeing this in 2.1.10.

https://github.com/magento/magento2/issues/12792
