### ISSUE TITLE
Duplicate Form Key Cookie

### ISSUE THREAD

**Issue by mvenghaus** [magento/magento2#36248] opened 2022-10-06 05:36 UTC
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

1. Open any page with page cache enabled.
Ex:  https://demoshops.splendid-internet.de/magento/demoshop-magento2-daily/hero-hoodie.html
-> first form_key by js

2. Select size & color
-> second form_key by php

### Expected result

one "form_key" cookie

### Actual result

there are two cookies
"form_key" 
"form_key"

### Additional information

when the cookie is handled by php there is always a dot prefix in the domain

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/View/Element/Js/Cookie.php#L64

when the js form-key-provider.js sets the cookie, there is no configuration for the domain and the cookie is set without the dot

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/PageCache/view/frontend/web/js/form-key-provider.js#L30

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-10-06 11:49
Hi @mvenghaus ,
Thank you for reporting and collaboration. Verified the issue on both Magento 2.4-develop instance and 2.4.5 project-community-edition as well but the issue is not reproducible.
Only one "form_key" cookie is present as displayed below:
![image](https://user-images.githubusercontent.com/60198231/194304743-fc5d4624-988f-4d9a-9541-65f5a0bd76bb.png)
Kindly check the behavior on Magento 2.4-develop instance / elaborate missing steps / configuration details if the issue is still reproducible.
Thank you.

**Comment by mvenghaus** [comment] 2022-10-06 12:01
@engcom-November

Step 1
open
https://demoshops.splendid-internet.de/magento/demoshop-magento2-daily/hero-hoodie.html
-> first form_key by js

Step 2
select size & color
-> second form_key by php

**Comment by engcom-November** [comment] 2022-10-10 12:54
Thank you for the reponse @mvenghaus . Verified the issue again on Magento 2.4-develop instance with above mentioned steps and the issue is reproducible. Hence updating the description and confirming the issue.
![image](https://user-images.githubusercontent.com/60198231/194870927-b215ba31-0730-4322-8273-98fdbe89cc3c.png)

**Comment by engcom-Bravo** [comment] 2024-12-12 07:26
Hi @mvenghaus,

Thank for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


<img width="1440" alt="Screenshot 2024-12-12 at 10 48 14 am" src="https://github.com/user-attachments/assets/0a990037-7709-48d4-a994-fc8f5fba7f97" />


only one "form_key" cookie is there.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-12 07:26 UTC
Labels: Issue: Confirmed, Component: Developer, Component: Cookie, Reproduced on 2.4.x, Priority: P3, Progress: done, Area: Product, Reported on 2.4.5
