### ISSUE TITLE
Cannot add plugin to class with return by reference function

### ISSUE THREAD

**Issue by maderlock** [magento/magento2#11560] opened 2017-10-19 13:59 UTC
### Preconditions

1. Magento 2.1.9
2. PHP 7.0.21
3. Warnings displayed as errors
4. PayPal Express enabled

### Steps to reproduce

1. Add di.xml entry in a new module for a plugin on \Magento\Paypal\Model\Info - perhaps to output additional information against PayPal orders.
2. Create plugin class. Does not need to actually do anything.
3. Visit cart or checkout or order view page

### Expected result

1. Visit as normal

### Actual result

1. Warning causes exception to be thrown - see screenshot 
![errorscreenshot](https://user-images.githubusercontent.com/630320/31774481-cee01d1c-b4dd-11e7-93bd-a362223b3f8d.jpg)

From what I can tell, by adding a plugin to this class, it causes an interceptor class to be generated. Perhaps autogenerated classes cannot handle return by reference, so there is then a mismatch in the method signatures.

Our workaround has been to use a preference instead. Obviously plugins are preferable as the are less likely to cause interoperability problems with other extensions and Magento itself.

**Comment by magento-engcom-team** [comment] 2017-10-20 08:30
@maderlock, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-20 08:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
