### ISSUE TITLE
Knockoutjs returns WRONG item_id in checkout

### ISSUE THREAD

**Issue by grasdaggel** [magento/magento2#7092] opened 2016-10-19 13:35 UTC
### Preconditions

1.  Modify the details.html on line 15 to: `<a class="product-item-name" data-bind="text: $parent.name, attr: { 'data-id': $parent.item_id }, getUrl:{}"></a>`
2. go into the checkout and inspect DOM
### Steps to reproduce

1. See preconditions
2. In DOM there is now an data-id attribute in the A/strong element depending on your previous config
3. 
### Expected result

1. the products ID is in there
### Actual result

1. something completely different ID is stored in it 

I request product with the name "Metropolights Berlin". In the backend it has set ID "305". Knockout JS gives me ID: 1960.

If I lookup the ID 1960 in the database I found something in Table `mg1_catalog_product_entity_int`, which is linked to a completely different product, as well. 

What is ìtem_id`, if not the ID for the specific product or a quoted ID? 

Further IDs are just incrementing. What kind of sorcery is this?

**Comment by veloraven** [comment] 2016-10-19 14:04
@grasdaggel thank you for your feedback.
Please, identify which version of Magento you are running.

**Comment by grasdaggel** [comment] 2016-10-19 14:17
We are using Magento 2.0.6.

**Comment by tkacheva** [comment] 2016-10-21 13:35
@grasdaggel Plese help to understand the use case you are trying to do?

**Comment by tkacheva** [comment] 2016-10-21 13:35
Issue MAGETWO-59944

**Comment by grasdaggel** [comment] 2016-10-21 14:59
I've found out that the item_id is the ID from the quote. The table for the quotes itselfs hold each item_id together with the foreign key, the product ID. I wasn't able to find any Mage-hooks to get the product ID by item_id and therefore I've build a dirty ajax which does a manual SQL query... That solved my problem. 

So, in short:
- item_id => item cart id for respective current quote, not the wrong id

Suggestion: add another key for the SKU/product ID itself to $parent and therefore make it easier to modify the onepage-checkout.

**Comment by veloraven** [comment] 2017-06-20 08:36
I'm closing this issue as internal ticket was closed as not a bug.

**Closed as completed by veloraven** 2017-06-20 08:36 UTC
Labels: Issue: Ready for Work, bug report, Component: Checkout, Area: Frontend
