### ISSUE TITLE
Buy 1 Get 1 Free Magent 2.3.5-p1

### ISSUE THREAD

**Issue by SalesFC** [magento/magento2#30769] opened 2020-11-04 02:31 UTC
### Preconditions (*)

1. Have 2.3.5-p1 Magento
2. 

### Steps to reproduce (*)

1.  Create a rule for 'Buy 1 Get 1 free' (Buy X get Y free)
2.  No Coupon
3. Uses Per Customer : 5 
4. Condition: To have 1 specific product to apply this promotion. 
![Condition #1](https://user-images.githubusercontent.com/73920700/98062319-c25a1080-1e88-11eb-88e8-1fc6aeff6cf6.JPG)
![condition #2](https://user-images.githubusercontent.com/73920700/98062325-c71ec480-1e88-11eb-959c-735a966536e6.JPG)

### Expected result (*)

1. [Screenshots, logs or description]
2. Expect the item to automatically applied the promotion for whenever 2 quantity or even number quantity is in cart. 

### Actual result (*)

1. [Screenshots, logs or description]
2. Discount is not displayed.
![cart](https://user-images.githubusercontent.com/73920700/98062389-e61d5680-1e88-11eb-81ed-c8d8c428d7b5.JPG)

### Additional Information
- Confirmation steps https://github.com/magento/magento2/issues/30769#issuecomment-733737951

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.
  
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-11-06 05:33
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-11-25 13:07
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-11-25 14:24
Hi @SalesFC,
I have verified this issue as per your steps to be reproduced, actual result and expected result.
The "Buy 1 Get 1" rule is not applied to the selected category.
See attached the screenshot:

![image](https://user-images.githubusercontent.com/24711761/100239825-dd83e180-2f57-11eb-8bc1-73fcdfa33f3e.png)

![image](https://user-images.githubusercontent.com/24711761/100239875-ed032a80-2f57-11eb-8c44-edd4c9eba6ca.png)

If anything is missing from my end. Let me know.

Thanks.

**Comment by magento-engcom-team** [comment] 2020-11-25 14:25
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39357` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Hotel** [comment] 2021-01-20 09:06
Hello @SalesFC,
Checked the issue and was not able to reproduce it.
Preconditions:
Magento version: 2.4-develop
PHP version: 7.4
ElasticSearch version: 7
MySQL version: 8.0
1. Created a simple product and category for it.
2. Created the cart price rule
![30769_cart_rule_example](https://user-images.githubusercontent.com/51681618/105151804-1337e780-5b0f-11eb-9a31-52dbeffec3cd.png)
3. bin/magento cron:run (if not started)
4. Add 2 created products to the cart
![30769_rule_works](https://user-images.githubusercontent.com/51681618/105151937-3e223b80-5b0f-11eb-9893-08df819e0a77.png)
Works as expected.
Could you please check if I miss something?
Thank you.

**Comment by engcom-Hotel** [comment] 2021-02-02 16:47
Closing the issue due to inactivity.
Feel free to reopen it if you can reproduce it.

**Closed as completed by engcom-Hotel** 2021-02-02 16:47 UTC
Labels: Area: Frontend, Issue:  Cannot Reproduce, Component: Rule, Fixed in 2.4.x, Priority: P2, Progress: done, Reported on 2.3.5-p1

**Comment by magento-engcom-team** [comment] 2021-02-02 16:49
Hi @SalesFC, @engcom-Hotel. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39357` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.
