### ISSUE TITLE
Password policy exception when auto-provisioning an user during SSO

### ISSUE THREAD

**Issue by pitbulk** [magento/magento2#32965] opened 2021-05-07 00:50 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
I have an [SSO extension ](https://marketplace.magento.com/sixtomartin-onelogin-module-saml2-extend.html) which is based on SAML. That extension defines an AdminLoginObserver for controller_action_predispatch_adminhtml_auth_login so basically a SAML Message is sent to the Magento login endpoint, I validate it and SSO the user related to the SAML flow. If the user does not exist, I automatically generate it
The extension works for Magento 2.1, Magento 2.2, Magento 2.3 Magento 2.4, but at Magento 2.4.2  the PR: [[MC-34197: Admin user improvement](https://github.com/magento/magento2/commit/67fae82c6278827f2c9b0f63083486a9d7740366)] introduced at the User ResourceModel the code:

```
    protected function _beforeSave(AbstractModel $user)
    {
        if ($user->hasRoleId()) {
            $user->setReloadAclFlag(1);
        }
        return parent::_beforeSave($user);
    }
```
So basically, if I save the User, its acl flag will be set as 1.

Then the App/Action/Plugin/Authentication.php aroundDispatch method is executed, and such method at the end has a call to:
```
$this->_auth->getAuthStorage()->refreshAcl()
```

the [refreshAcl](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Backend/Model/Auth/Session.php#L123) method contains:
```
if ($user->getReloadAclFlag()) {
    $user->unsetData('password');
    $user->setReloadAclFlag('0')->save();
}
```

Since the acl flag is enabled, the password of the user is removed and the save action raises an exception because
the user can't be saved without a password

### Expected result (*)
1. Be able to create the user and SSO

### Actual result (*)
Exception:
```
Exception #0 (Magento\Framework\Validator\Exception): Password is required field.
Invalid type given. String expected
Invalid type given. String, integer or float expected

Exception #0 (Magento\Framework\Validator\Exception): Password is required field.
Invalid type given. String expected
Invalid type given. String, integer or float expected
<pre>#1 Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(&Magento\User\Model\User\Interceptor#000000004535c950000000000255011c#) called at [vendor/magento/framework/Model/AbstractModel.php:655]
#2 Magento\Framework\Model\AbstractModel->save() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#3 Magento\User\Model\User\Interceptor->___callParent('save', array()) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#4 Magento\User\Model\User\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\User\Model\User\Interceptor->___callPlugins('save', array(), array(array('revokeTokensFrom...'))) called at [generated/code/Magento/User/Model/User/Interceptor.php:23]
#6 Magento\User\Model\User\Interceptor->save() called at [vendor/magento/module-backend/Model/Auth/Session.php:136]
#7 Magento\Backend\Model\Auth\Session->refreshAcl() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:142]
#8 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor#000000004535ca48000000000255011c#, &Closure#000000004535ca4d000000000255011c#, &Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#9 Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#), array(array('adminLoadDesign'))) called at [generated/code/Magento/Backend/Controller/Adminhtml/Dashboard/Index/Interceptor.php:32]
#11 Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/App/FrontController.php:186]
#12 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#, &Magento\Backend\Controller\Adminhtml\Dashboard\Index\Interceptor#000000004535ca48000000000255011c#) called at [vendor/magento/framework/App/FrontController.php:118]
#13 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#14 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#), array(array('default_store_se...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#17 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000004535c853000000000255011c#) called at [vendor/magento/framework/App/Http.php:116]
#18 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#19 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000004535c8be000000000255011c#) called at [index.php:39]
```

- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

**Comment by pitbulk** [comment] 2021-05-08 02:22
It seems that the issue happened because I created the user object and later used the same object after the save call to be injected into the session. After saving, if the user object is loaded 
```
$user = $this->userFactory->create()->load($user->getId());
```
the issue is gone.

**Comment by engcom-Echo** [comment] 2021-05-31 12:24
Hi @pitbulk ,

As per your comment, it looks like the issue is gone . We will be closing this issue then . 

Thanks

**Closed as completed by engcom-Echo** 2021-05-31 12:24 UTC
Labels: non-issue, Issue: ready for confirmation
