### ISSUE TITLE
«TypeError: this.trigger is not a function» in lib/web/mage/backend/validation.js

### ISSUE THREAD

**Issue by zzvara** [magento/magento2#10758] opened 2017-09-03 13:33 UTC
### Preconditions

1. Magento 2.1.8 CE release
2. PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
3. Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

### Steps to reproduce

1. Have an attribute set with 131 attributes, 5 store views at least
2. When there is only 1 store view, specifying an attribute set does not require the "admin" column to be specified.
3. When there are 5 store views, the attribute set form can not be saved, due to "admin" column not being specified for all the 131 entries.
4. Specify the 131 entries, and click on save.
5. The page loads indefinitely, and JS shell reports: «TypeError: this.trigger is not a function»
6. Go to "lib/web/mage/backend/validation.js" and update the corresponding problematic line to "$('body').trigger('processStop');"
7. Repeat from 4. again. Magento will load, after 4 seconds, you will be redirected to Dashboard. The attribute set is not updated.

### Expected result

1. The attribute set should be updated.

### Actual result

1. JS error.

Running in a Docker container, with only the minimum required components and environment to run Magento.

**Comment by zzvara** [comment] 2017-09-11 19:43
Is there any way to find the underlying error? I have checked the exception.log and other log files, there is nothing at the time of the error.

**Comment by honeygarg** [comment] 2017-09-20 07:12
Please upgrade magento version 2.1.8 to 2.1.9. The issue is resolved in m2.1.9.

**Comment by magento-engcom-team** [comment] 2017-09-20 08:20
Hi, @zzvara, thank you for your report, but we can not reproduce this issue with your "steps to reproduce".
What do you mean under "admin" column on attribute set form? Maybe attribute form?
We tried to do next:
1. Create attribute with "dropdown" type.
2. Specified 131 values for it(fill admin field for each).
3. Click save.
4. Attribute saved successfully.

Please provide more detailed steps to reproduce.

**Comment by zzvara** [comment] 2017-09-20 16:33
Hi,

1. We have swatch type or something like this.
2. We also have 5 additional languages as store views.
3. 5 additional languages have been added after 131 values have been specified in advance and saved.

By admin column I mean the attribute form, has (for each value) 5x2 input boxes, 2 for each store view and 2 additional which states "admin".
On 2017-09-20 01:21:46, Magento Community Engineering <notifications@github.com> wrote:
Hi, @zzvara [https://github.com/zzvara], thank you for your report, but we can not reproduce this issue with your "steps to reproduce".
What do you mean under "admin" column on attribute set form? Maybe attribute form?
We tried to do next:
* Create attribute with "dropdown" type.
* Specified 131 values for it(fill admin field for each).
* Click save.
* Attribute saved successfully.
Please provide more detailed steps to reproduce.

**Comment by magento-engcom-team** [comment] 2017-09-21 15:17
Hi, @zzvara again) thank you for your report.

So I did next steps(2.1.9 M2 version):
1.Go to Store->Attributes->Product->Add New Attribute.
2. Pick attribute type "Visual Swatch" and add 131 values for it(admin value is required 
![f57755f500c3932917378d8b261a100541ab50b0de62911345 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/31669971/30703906-afeb0628-9ef9-11e7-97fe-d1c72b0d1642.png)
).
3. Save attribute. Success message appeared.
4. Add 4 more store views, so now i have 5 store views.
5. Go to created attribute and try to save it.
6. Success message appeared, attribute is saved.

Please correct my steps to reproduce if they are wrong. If they are right try to reproduce this
issue on a clean installation.

**Comment by zzvara** [comment] 2017-09-21 16:38
OK thanks, we will look into it again and try to experiment with it. Unfortunately there are no errors thrown. Where should I find for errors? Nothing in the exception logs.
On 2017-09-21 08:21:23, Magento Community Engineering <notifications@github.com> wrote:
Hi, @zzvara [https://github.com/zzvara] again) thank you for your report.
So I did next steps(2.1.9 M2 version):
1.Go to Store->Attributes->Product->Add New Attribute.
2. Pick attribute type "Visual Swatch" and add 131 values for it(admin value is required).
3. Save attribute. Success message appeared.
4. Add 4 more store views, so now i have 5 store views.
5. Go to created attribute and try to save it.
6. Success message appeared, attribute is saved.
Please correct my steps to reproduce if they are wrong. If they are right try to reproduce this
issue on a clean installation.

**Comment by magento-engcom-team** [comment] 2017-09-22 16:17
@zzvara, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-22 16:17 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
