### ISSUE TITLE
Double Redis connection within single request using persistent connection

### ISSUE THREAD

**Issue by madonzy** [magento/magento2#35066] opened 2022-02-08 11:22 UTC
### Preconditions (*)

1. Magento 2.3.6 (Open Source)

### Steps to reproduce (*)
1. Add "persistent" key with "example-123" value into env.php under cache->frontend->default->backend_options->remote_backend_options
2. Use ab to run all php-fpm children
3. run redis-cli and run CLIENT LIST command

### Expected result (*)

1. The amount of connections should be the same as php-fpm processes quantity

### Actual result (*)

1. Double connections (ex. for 10 php-fpm processes there'd be 20 connections to Redis)

I did debug a bit, and I can see that we have two separate connections:
- Magento\Framework\App\Bootstrap::create
- Magento\Framework\App\Bootstrap->run

Full trace:

First connection:

```
#0 /var/www/vendor/colinmollenhour/credis/Client.php(792): Credis_Client->connect()
#1 /var/www/vendor/colinmollenhour/credis/Client.php(645): Credis_Client->__call('select', Array)
#2 /var/www/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(393): Credis_Client->select(0)
#3 /var/www/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(250): Cm_Cache_Backend_Redis->_applyClientOptions(Object(Credis_Client))
#5 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct(Array)
#6 /var/www/vendor/magento/framework/Cache/Backend/RemoteSynchronizedCache.php(78): Zend_Cache::_makeBackend('\\Cm_Cache_Backend_Re...', Array, true, true)
#7 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(153): Magento\Framework\Cache\Backend\RemoteSynchronizedCache->__construct(Array)
#8 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('\\Cm_Cache_Backend_Re...', Array, true, true)
#9 /var/www/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\Framewo...', '\\Cm_Cache_Backend_Re...', Array, Array, true, true, true)
#10 /var/www/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(38): Magento\Framework\App\Cache\Frontend\Factory->Magento\Framework\App\Cache\Frontend\{closure}()
#11 /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Cache\Frontend\Adapter\Zend->__construct(Object(Closure))
#12 /var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#13 /var/www/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#14 /var/www/vendor/magento/framework/App/Cache/Frontend/Factory.php(158): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#15 /var/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#16 /var/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(151): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#17 /var/www/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#18 /var/www/vendor/magento/framework/App/Cache/Type/Config.php(49): Magento\Framework\App\Cache\Type\FrontendPool->get('config')
#19 /var/www/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend()
#20 /var/www/vendor/magento/framework/App/ObjectManager/ConfigLoader.php(73): Magento\Framework\Cache\Frontend\Decorator\Bare->load('gl
obal::DiConfi...')
#21 /var/www/vendor/magento/framework/App/ObjectManager/Environment/Developer.php(79): Magento\Framework\App\ObjectManager\ConfigLoader->load('global')
#22 /var/www/vendor/magento/framework/App/ObjectManagerFactory.php(191): Magento\Framework\App\ObjectManager\Environment\Developer->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Developer), Array)
#23 /var/www/vendor/magento/framework/App/Bootstrap.php(211): Magento\Framework\App\ObjectManagerFactory->create(Array)
#24 /var/www/vendor/magento/framework/App/Bootstrap.php(126): Magento\Framework\App\Bootstrap->__construct(Object(Magento\Framework\App\ObjectManagerFactory), '/var/www', Array)
#25 /var/www/pub/index.php(37): Magento\Framework\App\Bootstrap::create('/var/www', Array)
#26 {main}
```

Second connection:

```
#0 /var/www/vendor/colinmollenhour/credis/Client.php(792): Credis_Client->connect()
#1 /var/www/vendor/colinmollenhour/credis/Client.php(645): Credis_Client->__call('select', Array)
#2 /var/www/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(393): Credis_Client->select(0)
#3 /var/www/vendor/colinmollenhour/cache-backend-redis/Cm/Cache/Backend/Redis.php(250): Cm_Cache_Backend_Redis->_applyClientOptions(Object(Credis_Client))
#5 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct(Array)
#6 /var/www/vendor/magento/framework/Cache/Backend/RemoteSynchronizedCache.php(78): Zend_Cache::_makeBackend('\\Cm_Cache_Backend_Re...', Array, true, true)
#7 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(153): Magento\Framework\Cache\Backend\RemoteSynchronizedCache->__construct(Array)
#8 /var/www/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('\\Cm_Cache_Backend_Re...', Array, true, true)
#9 /var/www/vendor/magento/framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\Framewo...', '\\Cm_Cache_Backend_Re...', Array, Array, true, true, true)
#10 /var/www/vendor/magento/framework/Cache/Frontend/Adapter/Zend.php(38): Magento\Framework\App\Cache\Frontend\Factory->Magento\Framew
ork\App\Cache\Frontend\{closure}()
#11 /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\Cache\Frontend\Adapter\Zend->__construct(Object(Closure))
#12 /var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#13 /var/www/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...', Array)
#14 /var/www/vendor/magento/framework/App/Cache/Frontend/Factory.php(158): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#15 /var/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#16 /var/www/vendor/magento/framework/App/Cache/Frontend/Pool.php(151): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#17 /var/www/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#18 /var/www/vendor/magento/framework/App/Cache/Type/Config.php(49): Magento\Framework\App\Cache\Type\FrontendPool->get('config')
#19 /var/www/vendor/magento/framework/Cache/Frontend/Decorator/Bare.php(65): Magento\Framework\App\Cache\Type\Config->_getFrontend()
#20 /var/www/vendor/magento/framework/Interception/PluginList/PluginList.php(297): Magento\Framework\Cache\Frontend\Decorator\Bare->load('global|primary|...')
#21 /var/www/vendor/magento/framework/Interception/PluginList/PluginList.php(266): Magento\Framework\Interception\PluginList\PluginList->_loadScopedData()
#22 /var/www/generated/code/Magento/Framework/App/MaintenanceMode/Interceptor.php(22): Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\\Framewo...', 'isOn')
#23 /var/www/vendor/magento/framework/App/Bootstrap.php(298): Magento\Framework\App\MaintenanceMode\Interceptor->isOn('192.168.50.55')
#24 /var/www/vendor/magento/framework/App/Bootstrap.php(259): Magento\Framework\App\Bootstrap->assertMaintenance()
#25 /var/www/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#26 {main}
```

**Comment by engcom-Hotel** [comment] 2022-07-29 07:15
Hello @madonzy,

We have tried to reproduce the issue in the Magento 2.4-develop branch via the below steps but the issue is not reproducible for us:
Steps:
1. Enable Redis cache for the Magento instance via following this [page](https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html).
2. Run cache clear command `bin/magento c:c`
3. Make the changes in the env.php file as below:
```
cache' => [
        'frontend' => [
            'default' => [
                'id_prefix' => 'test1_',
                'backend' => 'Magento\\Framework\\Cache\\Backend\\Redis',
                'backend_options' => [
                    'server' => '127.0.0.1',
                    'database' => '0',
                    'port' => '6379',
                    'password' => '',
                    'compress_data' => '1',
                    'compression_lib' => '',
                    'remote_backend_options' => [
                        'persistent' => 'example-123'
                    ]
                ]
            ]
        ]
     ]
```
5. Try to navigate the homepage.
6. But we can see one connect only with the `CLIENT LIST` command. Please refer the below screenshot:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/51681618/181703809-7d40d613-b83b-46ad-8edd-d5c2fd4ab144.png">

Please let us know in case we have missed anything.

Thanks

**Comment by madonzy** [comment] 2022-07-29 09:19
HI, @engcom-Hotel it looks like you did not configure redis properly. You have actually 0 connections, not 1. The one you see is your redis-cli connection (you can see by IP 127.0.0.1). Try out this config:

**Comment by engcom-Hotel** [comment] 2022-08-01 07:55
Hello @madonzy,

Please let us know if we missed anything in order to reproduce the issue. Actually, for us, both Magento and Redis are installed on the localhost.

Thanks

**Comment by madonzy** [comment] 2022-08-01 08:04
@engcom-Hotel as I said before, your configuration in env.php is invalid. You are not connected at all or your persistence is not configured

**Comment by engcom-Hotel** [comment] 2022-08-02 08:04
Hello @madonzy,

Thanks for the clarification!

Now as per further investigation, I enable session storage with Redis via the below command:
`bin/magento setup:config:set --session-save=redis --session-save-redis-host=127.0.0.1 --session-save-redis-log-level=4 --session-save-redis-db=2 --session-save-redis-persistent-id=sess_id_abhi`

and then try to access the Magento instance. Now whenever I am clicking on any new category, it is creating new connection in Redis. Please refer to the below screenshot for reference:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/51681618/182324112-4a7c1729-4cdc-44ee-8d62-65c85fd0c6c4.png">

Are you talking about the same? Just to confirm if I am on the same page as you.

Thanks

**Comment by madonzy** [comment] 2022-08-02 08:43
@engcom-Hotel cool, now you are using Redis :) do the same for the default cache (not session) and make a simple curl to the home page, see how many connections you have

**Comment by engcom-Hotel** [comment] 2022-08-17 05:39
Dear @madonzy,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-08-17 05:39 UTC
Labels: Triage: Dev.Experience, Issue: needs update
