### ISSUE TITLE
Error: End Date must follow Start Date. on creating promotion rule will clear complete rule

### ISSUE THREAD

**Issue by onepack** [magento/magento2#21803] opened 2019-03-16 23:24 UTC
### Preconditions (*)

1. Magento 2.3
2. PHP 7.2

### Steps to reproduce (*)

1. Create a promotion rule
2. type the end date in a wrong format like 01-07-2020 instead of 1/7/2020

### Expected result (*)

1. Expected is that there would be a warning while saving
2. Expected is that after the warning all settings done are still present

### Actual result (*)

1. The error appears and the whole form is emptied. All settings are gone
2. Have to start all over again

**Comment by magento-engcom-team** [comment] 2019-03-16 23:24
Hi @onepack. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@onepack do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by onepack** [comment] 2019-03-17 14:53
I have this behavior on all my Magento2.3 environments.

**Comment by magento-engcom-team** [comment] 2019-03-18 06:13
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-18 06:16
@onepack this issue is not reproducable at magento 2.3-develop instance Please check this on current 2.3-develop instance message here if you get this issue there

**Closed as completed by shikhamis11** 2019-03-18 06:16 UTC
Labels: Issue: Format is valid

**Comment by niners52** [comment] 2020-04-06 18:49
Issue on 2.3.2-p2
