### ISSUE TITLE
Wrong Catalog Cache Images after Upgrade Magento 2.3.2 to 2.4.2

### ISSUE THREAD

**Issue by nabeeljavaid** [magento/magento2#32350] opened 2021-03-03 10:38 UTC
### Preconditions (*)

1. Magento 2.4.2 (Open Source)
2. Apache 2.4
2. PHP 7.4
3. MySQL 5.7
4. ElasticSearch 7.6

### Steps to reproduce (*)

1. Upgrade Magento using CLI (https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html)
2. Tried all following commands but useless
php bin/magento catalog:image:resize
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento indexer:reindex

### Expected result (*)

1. 
![Magento 2 4 Expected Result](https://user-images.githubusercontent.com/2786954/109793072-03471380-7c36-11eb-8941-ad24c7f5aa28.png)

2.

### Actual result (*)

1. 
![Magento 2 4 Actual Result](https://user-images.githubusercontent.com/2786954/109793101-0b9f4e80-7c36-11eb-8da8-87835a8ab394.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by AlldoGroup** [comment] 2021-03-03 16:40
@nabeeljavaid 

Please check that the following lines in your root .htaccess exists:

```
RewriteCond %{REQUEST_URI} !^/pub/
RewriteCond %{REQUEST_URI} !^/setup/
RewriteCond %{REQUEST_URI} !^/update/
RewriteCond %{REQUEST_URI} !^/dev/
RewriteRule .* /pub/$0 [L]
```

**Comment by nabeeljavaid** [comment] 2021-03-04 07:21
@AlldoGroup 

I updated root .htacess file as you proposed but still getting wrong cache image please see attached screenshots

![Magento2 Root  htaccess](https://user-images.githubusercontent.com/2786954/109925815-07316f00-7ce4-11eb-968a-fc78db4cbcd7.png)
![Magento2 Frontend](https://user-images.githubusercontent.com/2786954/109925828-0c8eb980-7ce4-11eb-8190-32e2c35e5f9a.png)

**Comment by engcom-Oscar** [comment] 2021-03-22 13:01
Hi @nabeeljavaid  ! Thank you for your report.
Unfortunately, I was not able to reproduce the issue by following steps from this ticket. May be you can provide some additional information how to reproduce it, please?

**Comment by nabeeljavaid** [comment] 2021-03-22 13:58
@engcom-Oscar I have explained everything that after upgrade I am having this issue.

**Comment by ymssrikanth** [comment] 2021-06-06 16:44
This issue exits

**Comment by engcom-November** [comment] 2021-09-30 09:53
Verified the issue after upgrading from 2.3.2 to 2.4.2-P1 but the issue is not reproducible:
Before Upgrade:
![image](https://user-images.githubusercontent.com/60198231/135430269-6a0c988f-053c-4995-9659-780e337dbcd2.png)

After upgrade:
![image](https://user-images.githubusercontent.com/60198231/135430173-368d33ab-d44c-425a-9a11-fc6d10cde482.png)
@nabeeljavaid kindly recheck the issue again and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-10-13 12:22
Hi @nabeeljavaid ,

We are closing this issue as there has been no latest update on the same.
Thank you

**Closed as completed by engcom-November** 2021-10-13 12:22 UTC
Labels: Issue: needs update, Reported on 2.4.2
