### ISSUE TITLE
Product Visibility Type : Search Don't update Products count in Toolbar

### ISSUE THREAD

**Issue by yagneshponkiya** [magento/magento2#6070] opened 2016-08-09 11:18 UTC
### Steps to reproduce
1. Go to any Product listing page and check the number of product count in product toolbar
2. Go to admin panel update any of the product being listed in above product listing page. set Product visibility to "Search"
3. Go back to frontend product listing page again and check.you will notice that product is being removed from the list but the toolbar product count is not updated.
### Expected result
1.  Toolbar should show product count in association with product being listed on that page. It should show count whose product visibility set to "Catalog, Search" or "Catalog"

Have tested this with Magento2.1 and magento 2.0.7

**Comment by allanpaiste** [comment] 2016-08-10 07:29
Duplicate of: https://github.com/magento/magento2/issues/5670, https://github.com/magento/magento2/issues/5151

Fixed in: with https://github.com/magento/magento2/pull/6035

**Comment by tkacheva** [comment] 2016-09-29 11:32
Closing as duplicate of https://github.com/magento/magento2/issues/5670 as there is more details

**Closed as completed by tkacheva** 2016-09-29 11:32 UTC
Labels: bug report
