### ISSUE TITLE
Js error in backend

### ISSUE THREAD

**Issue by cizgidekiadam** [magento/magento2#7960] opened 2016-12-26 12:53 UTC
### Preconditions

1. Magento 2.1.3 (updated from 2.1.2 via Setup Wizard)
2. PHP 7.0.11
3. Cache cleaned, indexes completed, var/di, var/generation etc.. cleaned

### Steps to reproduce

1. Login to admin
2. Enter a product edit page

### Expected result

1. Opens product edit page.

### Actual result

1. Page not loaded correctly
<pre>Uncaught ReferenceError: Unable to process binding "if: function (){return opened() || _wasOpened }"
Message: _wasOpened is not defined
    at if (eval at createBindingsStringEvaluator (knockout.js:2624), <anonymous>:3:74)
    at ko.computed.disposeWhenNodeIsRemoved (knockout.js:3989)
    at evaluateImmediate (knockout.js:1737)
    at Object.ko.computed.ko.dependentObservable (knockout.js:1946)
    at init (knockout.js:3988)
    at knockout.js:2989
    at Object.ignore (knockout.js:1249)
    at knockout.js:2988
    at Object.arrayForEach (knockout.js:151)
    at applyBindingsToNodeInternal (knockout.js:2974)</pre>

**Comment by TwassistantKeith** [comment] 2016-12-29 23:05
I also am having this same error:

```
knockout.js:297 Uncaught ReferenceError: Unable to process binding "if: function (){return opened() || _wasOpened }"
Message: _wasOpened is not defined
    at if (eval at createBindingsStringEvaluator (knockout.js:263), <anonymous>:3:74)
    at ko.computed.disposeWhenNodeIsRemoved (knockout.js:360)
    at evaluateImmediate (knockout.js:178)
    at Object.ko.computed.ko.dependentObservable (knockout.js:199)
    at init (knockout.js:360)
    at knockout.js:295
    at Object.ignore (knockout.js:124)
    at knockout.js:295
    at Object.arrayForEach (knockout.js:12)
    at applyBindingsToNodeInternal (knockout.js:294)
```

Magento 2.1.3, cleared cache, cleared all browser data, same issue.

**Comment by mgwalk** [comment] 2017-01-04 20:41
I am having this same problem on 2.1.3  when trying to edit products.
I upgraded from 2.1.2 to 2.1.3 via command line.

**Comment by andreaskoch** [comment] 2017-01-04 21:42
I had a similar issue and in my case it was caused by the JavaScript file versioning being activated by default in Magento 2.1.3 (see: [Relelase Notes of Magento 2.1.3](http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html)):

> Versioning of static files (including CSS, JS, font, and image files) is now enabled by default.

![Magento 2.1.3 JavaScript files cannot be loaded because the static/version route is not resolved by my webserver](https://cloud.githubusercontent.com/assets/247364/21660036/ec47f3e0-d2cd-11e6-8055-ff61efa03017.png)

Requests to `/static/version1482951220/_requirejs` all led to an 404 because the folder `version1482951220` does not actually exist.

I found the solution described in the Magento2 issue #7889 and adapted my Nginx config as described in the sample file provided with Magento: https://github.com/magento/magento2/blob/develop/nginx.conf.sample#L101

**Comment by mgwalk** [comment] 2017-01-05 13:18
I found that clearing browsing history fixed this.

**Comment by tanmayabiswal** [comment] 2017-01-05 14:40
I upgrader the site from 2.1.1 to 2.1.3 via via Setup Wizard, even cleared the browser, history, cleaned and flushed the cacche, remove the static and var folder details, deployed 5 times but the same , error.

Whenever there a a modal kind of things, any row from admin grid to edit.
product edit , theme configuration edit etc causing the issues

ReferenceError: _wasOpened is not defined
![error](https://cloud.githubusercontent.com/assets/20254654/21684256/f74f6736-d382-11e6-9a7a-3d5a964d5417.png)

**Comment by cizgidekiadam** [comment] 2017-01-05 20:17
Hi folks,
php bin/magento setup:static-content:deploy --frontend=adminhtml fixed for me.

**Comment by TwassistantKeith** [comment] 2017-01-10 15:21
I was using CSS & Javscript minification on Cloudflare, turning it off to clear the cache and then back on again fixed this for me.

**Comment by nishantbkw** [comment] 2017-08-24 12:56
Could any one solve this issue? 
I Just upgraded from 2.1.1 to 2.1.8 and seeing same error in console 
Tried clean,flush cache cleared javascript cache also re deployed static content several times

**Comment by magento-engcom-team** [comment] 2017-10-09 10:30
@rbostan, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.

**Comment by korostii** [comment] 2017-11-27 13:31
> This seems to be correct Magento behavior.

Could you please expand on that? 
In particular, are you referring to the JS error in the browser console, or something else? I mean, JS errors  by definition mean that something in the code is incorrect.

> Otherwise you may submit Pull Request with the suggested changes.

What kind of changes would you expect here if you claim that the current behavior is "correct" already?
With all due respect, please add some kind of detailed explanation to this boilerplate response, because it is very confusing, considering the issue in question.

>  magento-engcom-team added `Fixed in 2.1.x`, `Fixed in 2.2.x`, `Fixed in 2.3.x` labels

Is that correct, too? Could you pleasereference the exact changes \ commits fixing the issue? Seems a bit contradictory with the comment right above it which there's just nothing to fix.

**Comment by magento-engcom-team** [comment] 2017-12-13 11:40
@rbostan thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more detailed steps to reproduce or try to reproduce this issue on a clean installation or latest release.

**Closed as completed by magento-engcom-team** 2017-12-13 11:40 UTC
Labels: bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, non-issue, Issue: Format is valid

**Comment by riyajalijunakiya** [comment] 2019-03-30 19:14
Its due to caching issue.
Enable static sign from developer in store config that solve issue for me.
