### ISSUE TITLE
Product edit page crashes if product image is not present

### ISSUE THREAD

**Issue by giacmir** [magento/magento2#7086] opened 2016-10-19 09:21 UTC
2.1.2 backend crashes with the following error: `Cannot gather stats! Warning!stat(): stat failed for <filename>` when you try to edit a product and its image is not present into filesystem.

Since this is a very frequent case in development and/or debugging it should not happen.
### Preconditions

1. Magento 2.1.2
2. php 7
### Steps to reproduce

1. Create a product with image
2. Delete image file from file system
3. Try to edit product from admin
### Expected result

1. Product is editable
### Actual result

1. Edit form doesn't show up

**Comment by sevos1984** [comment] 2016-10-19 16:20
Internal ticket MAGETWO-59880, thanks for reporting

**Comment by olysenko** [comment] 2016-10-28 08:16
issue is fixed. closed as an duplicate of the [5871](https://github.com/magento/magento2/issues/5871)

**Closed as completed** 2016-10-28 08:16 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog

**Comment by Ctucker9233** [comment] 2016-10-30 00:16
@olysenko is there a commit reference?

**Comment by olysenko** [comment] 2016-10-31 09:15
Yes, in [5871](https://github.com/magento/magento2/issues/5871) you can find the commit [reference](https://github.com/magento/magento2/commit/2db5aa15722307fb6ad703627933224f5f74bbe3)

**Comment by Ctucker9233** [comment] 2016-11-03 23:27
@olysenko I actually had a questions about this commit. Can you take a look and maybe answer it?
