### ISSUE TITLE
Admin Panel UI Displays Website assignments Incorrectly on Product Edit Page

### ISSUE THREAD

**Issue by ghost** [magento/magento2#31630] opened 2021-01-12 20:31 UTC
### Preconditions (*)
1. Magento 2.4-develop or 2.4.1
2. Magento instance has exactly 1 website configured in store settings. 

### Steps to reproduce (*)
1. Go to Catalog > Products, then edit a product
2. In "Product in Websites", unassign the only website.
3. Save
4. The product should no longer have a value in catalog_product_website

### Expected result (*)
1. UI correctly displays that the item is unassigned in both the products overview and the product edit page. (This works as intended when you have multiple websites)

### Actual result (*)
1. UI incorrectly shows that the product is assigned in the product edit page, while showing correctly in the products overview page
![Actual - Product Edit Page shows incorrect info](https://user-images.githubusercontent.com/61755260/104369072-ebcb9400-54ea-11eb-8828-033287672267.png)
![Actual - Product Overview](https://user-images.githubusercontent.com/61755260/104369059-e9693a00-54ea-11eb-82c8-6a04f80ec180.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pmcnamaracpc** [comment] 2021-01-12 20:31
@magento give me 2.4-develop instance

**Comment by pmcnamaracpc** [comment] 2021-01-12 20:39
Recreated on 2.4-develop
![Recreated - Product Edit Pagepng](https://user-images.githubusercontent.com/61755260/104370021-43b6ca80-54ec-11eb-93c9-0dad17c83873.png)
![Recreated - Product Overview](https://user-images.githubusercontent.com/61755260/104370024-444f6100-54ec-11eb-814e-931fc086c010.png)

**Comment by krishprakash** [comment] 2021-01-13 04:41
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-01-13 05:28
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40394` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by saphaljha** [comment] 2021-01-13 18:15
@magento I am working on this

**Comment by Patelcc** [comment] 2021-01-30 06:08
@magento I am working on it

**Comment by Patelcc** [comment] 2021-01-30 06:08
@magento add to contributors team

**Comment by pmcnamaracpc** [comment] 2021-05-28 20:43
@Patelcc Did you still want to work on this issue?

**Comment by engcom-Bravo** [comment] 2024-06-06 04:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-06-06 04:52
Hi @ghost,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

UI correctly displays that the item is unassigned in both the products overview and the product edit page..

Hence We are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-06 04:52 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S2, Progress: done
