### ISSUE TITLE
Problem displaying the site in the mobile version - MAGENTO 2.3.0

### ISSUE THREAD

**Issue by eliadcohenn** [magento/magento2#36670] opened 2022-12-25 14:38 UTC
I have a problem with the website - MAGENTO 2.3.0
Every day when I enter the website via cell phone - the products are not displayed properly.
To fix it I go into the management panel and do a FLUSH MAGENTO CACHE and only after that it works.
Another problem is on the home page - the resolution is probably not correct as well.
How can this problem be solved permanently?
 Attached is a screenshot for the 2 problems.

**another problem**
After making a purchase on the website, I do not receive an email notification about placing the order. (It used to work and stopped working for some reason)
I would love to get a solution.
Thank you very much everyone!
![WhatsApp Image 2022-12-25 at 16 40 35](https://user-images.githubusercontent.com/50859031/209472556-f9d2eccc-dfe1-4e84-afa4-f4696fca39f7.jpeg)
![WhatsApp Image 2022-12-25 at 16 40 38](https://user-images.githubusercontent.com/50859031/209472558-6816dba3-fd70-4709-a9c4-46428d7226fd.jpeg)

**Comment by engcom-Dash** [comment] 2022-12-27 10:15
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-12-27 17:09
Hi @colinodell ,

We trying to reproduce the issue in 2.4.4 magento instance,But we are not able to reproduce the issue.
we can able to see the products with proper description and details.
we are getting successfully order mail also in mail-hog and we attached all the screenshot for your reference.
Screenshots:
<img width="1512" alt="Screenshot 2022-12-27 at 9 52 12 PM" src="https://user-images.githubusercontent.com/60198592/209698523-337f58da-2908-49dd-9137-912e53ef5853.png">
<img width="1512" alt="Screenshot 2022-12-27 at 10 14 06 PM" src="https://user-images.githubusercontent.com/60198592/209698706-a3f44869-4579-466a-89ea-7a8907a69bef.png">
<img width="1246" alt="Screenshot 2022-12-27 at 10 14 38 PM" src="https://user-images.githubusercontent.com/60198592/209698719-546de11c-5b15-467c-a16f-511fbe59d874.png">

Let us know if we are missing anything!!!

Thanks!!!

**Comment by eliadcohenn** [comment] 2022-12-28 08:37
still have the same problem.... help anyone ?

**Comment by engcom-Dash** [comment] 2023-01-05 12:06
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2023-01-05 13:10
Hi @eliadcohenn ,

We are trying to reproduce the issue in mobile device also....We are  getting same while testing in mobile device.

Let us know if we are missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2023-01-18 02:32
Hi @eliadcohenn ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-01-18 02:32 UTC
Labels: Issue: needs update
