### ISSUE TITLE
[2019-07-30 12:11:53] [ERROR] SyntaxError: Unexpected token < in JSON at position 83

### ISSUE THREAD

**Issue by stenovishal98** [magento/magento2#23945] opened 2019-07-30 07:01 UTC
I am Working on localhost. when I click in place order button   then I saw console error "[2019-07-30 12:11:53] [ERROR] SyntaxError: Unexpected token < in JSON at position 83". how I solve this issue.please guys help me.
![error](https://user-images.githubusercontent.com/53423249/62107700-cda5b000-b2c5-11e9-8865-d54f93ea794f.png)

**Comment by engcom-Charlie** [comment] 2019-07-30 07:06
Hi @stenovishal98 ! Can you give me more info about you Magento configuration?

**Comment by engcom-Charlie** [comment] 2019-08-09 08:53
I close this issue because we can't reproduce it.

**Closed as completed** 2019-08-09 08:53 UTC
Labels: Issue: Format is not valid
