### ISSUE TITLE
Error with php 8.2

### ISSUE THREAD

**Issue by rogerdz** [magento/magento2#36629] opened 2022-12-16 15:53 UTC
### Preconditions and environment

- Magento version 2.4-develop

### Steps to reproduce

- Setup magento run with php 8.2

### Expected result

No error

### Actual result

- Error when run bin/magento setup:upgrade: Could not validate a connection to the OpenSearch. Deprecated Functionality: Creation of dynamic property GuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated in /home/magento2/vendor/ezimuel/ringphp/src/Client/CurlMultiHandler.php on line 47

- Error when load page:
<b>Deprecated</b>:  Using ${var} in strings is deprecated, use {$var} instead in <b>/home/magento2/app/code/Magento/Paypal/Model/PayLaterConfig.php</b> on line <b>94</b><br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: Creation of dynamic property Magento\Framework\HTTP\PhpEnvironment\Response::$headersSent is deprecated in /home/magento2/lib/internal/Magento/Framework/Escaper.php:95

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-12-16 17:11
@magento give me 2.4-develop instance

**Comment by victoria-s1** [comment] 2022-12-17 12:04
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-12-19 06:50
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-12-20 01:32
Hi @rogerdz 

We trying to reproduce the issue in 2.4-develop brnach...we are not able to reproduce the issue.we are getting expecetd result.
Magento Version: 2.4-develop
PHP :8.2
Step to reproduce:
After upgrading the PHP run the setup upgrade command ...It was run successfully.

Let us know if we missing anything!!!

Thanks!!!

**Comment by rogerdz** [comment] 2022-12-20 03:35
Hi @engcom-Dash , I try pull all new commit in repo and it still error. Are you sure you are using php 8.2 ?

**Comment by engcom-Dash** [comment] 2022-12-20 09:08
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-12-20 09:59
hi @rogerdz ,

We worked as per your last comments... w got error while upgrading the issue with PHP 8.2
Scrrenshot:
<img width="1512" alt="Screenshot 2022-12-20 at 3 23 48 PM" src="https://user-images.githubusercontent.com/60198592/208638765-cc068d1e-7124-42ad-94be-ce51997eb49c.png">
<img width="1512" alt="Screenshot 2022-12-20 at 3 26 19 PM" src="https://user-images.githubusercontent.com/60198592/208638809-41e4a692-192f-404e-98c9-bb5f54263ac8.png">

Can you Confirm the same error got your side also...Because it useful to confirm this issue.

Let us know if we missing anything!!!

Thanks!!!!

**Comment by rogerdz** [comment] 2022-12-20 15:49
Hi @engcom-Dash, it not same error. Your error  is memory_limit not enough, try increment memory_limit to 2-3GB.
Error from my side: 
![2022-12-20_22-48](https://user-images.githubusercontent.com/78783748/208708178-080604cd-4ffa-4788-95ff-38e4e6486dba.png)
![2022-12-20_22-48_1](https://user-images.githubusercontent.com/78783748/208708188-e62fbecd-7f21-4fff-b3e5-9ff659e95ff0.png)

**Comment by engcom-Dash** [comment] 2022-12-21 12:06
Hi @rogerdz ,

Thanks for Contribution with us....We worked as per your Instructions and we can able to reproduce the issue.
Magento version:2.4-develop branch
PHP :8.2
Steps:
Install 2.4-develop
install PHP 8.2
Run the setup upgrade Command 
we getting error as per your Actual result. So we are confirming the issue and its a reproducible.

Screenshot:
<img width="1512" alt="Screenshot 2022-12-21 at 5 21 19 PM" src="https://user-images.githubusercontent.com/60198592/208901446-89ac3f23-c4ec-4d55-a6d0-3b43de07f1a0.png">

Let us know if we missing anything!!!

Thanks!!!!

**Comment by rogerdz** [comment] 2022-12-21 22:57
Hi @engcom-Dash,

You miss check frontend, it has a error : 
 Fatal error: Uncaught InvalidArgumentException: Creation of dynamic property Magento\Framework\HTTP\PhpEnvironment\Response::$headersSent is deprecated in /home/magento2/lib/internal/Magento/Framework/Escaper.php:95

**Comment by engcom-Dash** [comment] 2022-12-22 18:03
@magento give me 2.4-develop branch

**Comment by engcom-Dash** [comment] 2022-12-22 18:03
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-12-22 18:55
Hi @rogerdz ,

we got similar Error while Upgrading magento instance....We are checking in front-end and will update ASAP.

Thank you.

**Comment by engcom-Dash** [comment] 2022-12-23 12:10
Hi @rogerdz ,

We are trying to reproduce the issue in 2.4-develop instance...we are not able to reproduce the issue.
Magento version 2.4-develop
PHP 8.2
We didn't find any exception like "Invalid Argument Exception" and We checked both System Log as well as Exception Log.
We got Similar error while upgrading the Magento instance.But we could not find any Exception while loading the page.
We still working on this issue...we will check this issue will update you.

Let us know if we are missing anything!!!

Thanks!!!

**Comment by sims-smith-corona** [comment] 2022-12-27 15:45
I also started to encounter this same issue, but this was happening when attempting to reindex. I would receive the following:

> Catalog Search index process error during indexation process:
Could not ping search engine: Deprecated Functionality: Creation of dynamic property GuzzleHttp\Ring\Client\CurlMultiHandler::$_mh is deprecated

It appears to be related to my specific version of the ezimuel/ringphp package which is a dependency of the native elasticsearch/elasticsearch module.

I was using version ezimuel/ringphp 1.1.2 which satisfied the elasticsearch's module's requirements. However this specific deprecation warning appears to be resolved in ezimuel/ringphp as of version 1.2.1 and additional fixes were released in version 1.2.2. 

Updating the ezimuel/ringphp package to at least version 1.2.1 may correct this for you.

**Comment by sims-smith-corona** [comment] 2023-01-03 20:03
Just following this up. I realized that in my case, the server's default PHP version had inadvertently been changed from 8.1 to 8.2. This is why I suddenly began observing errors without being able to attribute to them to any recent changes I'd made.

Based on the published system requirements, it doesn't look like the latest version of Magento officially supports PHP 8.2 yet: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

Dynamic properties are deprecated in PHP 8.2 and that's why we've been seeing that deprecation notice. Our issues have been limited to the ezimuel/ringphp dependency used by the OpenSearch and Elasticsearch modules, but it's likely other modules' dependencies will be affected similarly.

**Comment by engcom-Dash** [comment] 2023-01-10 09:47
Hi @rogerdz ,

We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-Dash** 2023-01-10 09:47 UTC
Labels: Issue: needs update, Reported on 2.4.x

**Comment by skghorela** [comment] 2023-06-01 10:00
I am getting the same error when I run the php bin/magento setup:upgrade command.
Could you please check with Magento 2.4.6 and PHP 8.2?

Deprecated Functionality: Creation of dynamic property BoostMyShop\AdvancedStock\Console\Command\RefreshSellableQuantity\Interceptor::$pendingOrderCollectionFactory is deprecated in /var/www/php82/m246/app/code/BoostMyShop/AdvancedStock/Console/Command/RefreshSellableQuantity.php on line 29
