### ISSUE TITLE
PHP Fatal error:  Interface with InvoiceFlexFieldProcessorInterface not found in vertex module

### ISSUE THREAD

**Issue by zuongthao** [magento/magento2#25891] opened 2019-12-04 02:24 UTC
### Preconditions (*)

1. Magento version: 2.3.3

### Steps to reproduce (*)

1. Run 
php bin/magento se:di:compile
or
php bin/magento deploy:mode:set production

### Expected result (*)

Command runs successfully.

### Actual result (*)

1. [Screenshots, logs or description]
PHP Fatal error:  Interface 'Vertex\Tax\Model\Flexfield\Processor\InvoiceFlexFieldProcessorInterface' not found in /var/www/html/surfari/vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php on line 24

Fix by:
edit file vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php
change namespace from
namespace Vertex\Tax\Model\Flexfield\Processor;
to
namespace Vertex\Tax\Model\FlexField\Processor;

**Comment by engcom-Echo** [comment] 2019-12-04 10:52
Hello @zuongthao 

Thank you for your report and collaboration!
We are not able to reproduce this issue on the 2.3.3 branch by provided steps.

**Testing scenario:**

**Preconditions:**
Magento 2.3.3 clean installation 

**Steps to reproduce:**

1. Run  `php bin/magento se:di:compile`
2. Run  `php bin/magento deploy:mode:set production`

**Result:**
Command runs successfully.
![php se di compile](https://user-images.githubusercontent.com/51681435/70136454-b2dcb100-1694-11ea-85ba-7b5a33aa2287.png)
So I have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Echo** 2019-12-04 10:52 UTC
Labels: Issue: Format is valid, Component: Bundled Extension

**Comment by zuongthao** [comment] 2019-12-05 02:39
Hi
Have you checked  file 
vendor/vertex/module-tax/Model/FlexField/Processor/OrderCurrencyGetterProcessor.php
and see "namespace Vertex\Tax\Model\Flexfield\Processor;"
instead of "namespace Vertex\Tax\Model\FlexField\Processor;" ?

I downloaded Magento 2.3.3 from site, not from github.

**Comment by engcom-Echo** [comment] 2019-12-05 10:59
Hello @zuongthao 

I don't think this is an issue in Magento 2. Please refer to [Vertex Support](https://www.vertexinc.com/contact-us) for advice or general discussion about this.

Thank you!

**Comment by navarr** [comment] 2019-12-09 17:46
This issue is fixed as of Vertex 3.3.0, included in Magento 2.3.4.
