### ISSUE TITLE
[GraphQL] Result for route query for products and cms pages is never cached

### ISSUE THREAD

**Issue by t-heuser** [magento/magento2#36142] opened 2022-09-14 14:39 UTC
### Preconditions and environment

- Magento version: 2.4.5
- Cache must be enabled (for easy testing use default file cache)
- A product with the url key "test"
- A cms page with the url "test-cms"

### Steps to reproduce

Execute the following query as GET request:
```GRAPHQL
query route {
    route(url: "test") {
        type
    }
}
```

```GRAPHQL
query route {
    route(url: "test-cms") {
        type
    }
}
```

### Expected result

I expect the query result to be cached with the following cache identity tag: 
For products: mage---_XXX_\_CAT_P\__PRODUCTID_
For cms pages: mage---_XXX_\_CMS_P\__CMSID_

(Italic written XXX, PRODUCTID, CMSID are variables)

### Actual result

No cache is written for the result.
This leads to the problem that the route query is slow for products and cms pages as it's never cached.

### Products
The problem arises because of the following code:
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php#L29-L39

In line 32 the isset checks for the occurence of `id`. This works only for categories as the id for products is stored in the array with the key `entity_id` instead of `id`. So no cache tag is returned from the function which leads to no cache gets written.

![image](https://user-images.githubusercontent.com/53174153/190185910-6fd224be-9dc1-4287-a62d-f186dfcfaf01.png)

### Cms pages
The problem arises because of the following code:
https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CmsUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CmsUrlResolverIdentity.php#L26-L33

In line 29 the isset checks for the occurence of `id`. This doesn't work as the id for cms pagesis stored in the array with the key `page_id` instead of `id`. So no cache tag is returned from the function which leads to no cache gets written.

![image](https://user-images.githubusercontent.com/53174153/190185015-866e3c5b-c842-45cf-8d63-347e710b676d.png)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by oneserv-heuser** [comment] 2022-09-15 12:48
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-09-16 08:07
Hello @oneserv-heuser,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch by setting up the breakpoint on the below file in line number 32:

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/CatalogUrlRewriteGraphQl/Model/Resolver/UrlRewrite/CatalogUrlResolverIdentity.php#L29-L39

but the debug pointer is not hitting on that location. We have tried it with both with cache and a clean cache environment.

But further to debug this issue, we have observed the below behavior:

- After hitting the below request through GraphQL:
```
{
  route(url: "endurance-watch.html") {
    type
  }
}
```
- Request catch by the below method:

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/UrlRewriteGraphQl/Model/Resolver/Route.php#L44-L66

- After that `parent::resolve` method has been called, from where internally it is calling the `findFinalUrl` (Line number 82) method to get the information:

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/UrlRewriteGraphQl/Model/Resolver/AbstractEntityUrl.php#L79-L97

- Which internally calls `findOneByData` and then `doFindOneByData` which is fetching data from the database but not checking anywhere in the cache:

https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/UrlRewrite/Model/Storage/DbStorage.php#L100

We have also checked the same by enabling the database logs. Whenever we are hitting the above query, the following MySQL query is used to fetching the data:

```
SELECT `url_rewrite`.* FROM `url_rewrite` WHERE (`request_path` IN ('endurance-watch.html', 'endurance-watch.html/')) AND (`store_id` IN (1))
```

As per the findings it is not saving data from the cache and getting the data from the database always. Please let us know in case we have missed anything

Thanks

**Comment by oneserv-heuser** [comment] 2022-09-16 12:36
@engcom-Hotel It seems like your cache isn't working at all. Because if you fire a GET request only the first one ever executes the resolver ([magento2/app/code/Magento/UrlRewriteGraphQl/Model/Resolver/Route.php](https://github.com/magento/magento2/blob/91549b925da128ba79807400f551f2b2d0cfeed9/app/code/Magento/UrlRewriteGraphQl/Model/Resolver/Route.php#L44-L66)) of the query. The second request doesn't execute the code itself as magento retrieves the result from the cache.

So I don't know what exactly went wrong when you were testing the query. The only possibility I can think of is that you made a POST request instead of a GET request. If you execute the query as POST request it's never cached.
Maybe you can try the Altrair GraphQL Client Browser Extension ([Chrome ](https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja )or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/altair-graphql-client/)) and set the request method to GET. Then it should work and the second request should not even hit the route resolver.

**Comment by engcom-Hotel** [comment] 2022-09-19 07:58
Hello @oneserv-heuser,

Thanks for the response!

Yes, you were right, we were hitting the POST request mistakenly. And now as we tried to debug this issue with GET request we are able to reproduce the issue. 

After clearing the cache, normally the first request is taking time but other consecutive hits should not take times and server the response from the cache.

But here in this case, when we are hitting the below request, the response time is in between 450 ms to 520 ms:

```
{
  route(url: "endurance-watch.html") {
    type
  }
}
```

But after making the below changes the response time is reduced to below 300ms:

`$resolvedData['id'] = $resolvedData['entity_id'] ?? $resolvedData['id'];`

Hence confirming the issue.

Thanks

**Comment by JacobBrownAustin** [comment] 2023-01-04 17:38
Thank you.  It appears that this issue was fixed in a similar commit from last month (December 7th),  https://github.com/magento/magento2/commit/967439abee8e9e2e934aaa983748357dd8816b7d .
The changes in that commit are slightly different,  but from my quick testing,  it does work to solve the same issue as this pull request.

**Closed as completed** 2023-01-04 17:41 UTC
Labels: Issue: Confirmed, Component: Cache, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Component: GraphQlCache, Project: GraphQL, Progress: done, Area: Framework, Reported on 2.4.5
