### ISSUE TITLE
Theme templates overrides don't work in environment emulation cross-area

### ISSUE THREAD

**Issue by alessandroniciforo** [magento/magento2#10402] opened 2017-08-02 09:20 UTC
The theme templates overrides are not resolved correctly if we're in an environment emulation cross-area (e.g.: we're in adminhtml emulating frontend).

My particular case has been this: I have a custom template overriding the payment method info template, I login in the Magento admin, find an order, click "Send email". The email won't have the overridden template.

### Techincal details
To render the payment method info block Magento emulates the order's store in the frontend area (https://github.com/magento/magento2/blob/develop/app/code/Magento/Payment/Helper/Data.php#L208) and then calls `toHtml()` on the block. The template file resolution will pass through `Magento\Framework\View\Asset\Repository::updateDesignParams()`, will execute line [#145](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Asset/Repository.php#L145) setting `$theme` to the theme ID, and will execute line [#149](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/View/Asset/Repository.php#L149) that tries to load the theme by full path rather than by ID, thus returning no theme.

The code of this method normally works because if we're not in an environment emulation cross-area, the execution will not fall into that `elseif` and will not execute line #145 going likely into line #154.

I'm going to submit a pull request with what I believe is a possible solution.

### Preconditions
1. Magento CE 2.1.7

### Steps to reproduce
1. Create a new custom frontend template that inherits from Magento/Luma
2. Inside the template directory (`app/design/frontend/<vendor>/<themeName>`) create the folder `Magento_OfflinePayments/templates/info/` and create `checkmo.phtml` into it. The content of this file can be, for example, "Payment method override test"
3. Go on Magento admin, set the store design to use this template and flush cache
4. Go on frontend, login, complete an order with payment method "Check / Money order"
5. Go in your account area, open this order and verify that it shows "Payment method override test" as payment method
6. Go on Magento admin, find this order and click "Send email" on it

### Expected result
7. The email received has "Payment method override test" as well as payment method

### Actual result
7. The email doesn't have "Payment method override test" but it has the standard payment method label provided by the module template

**Comment by magento-engcom-team** [comment] 2017-09-25 22:00
@alessandroniciforo, thank you for your report.
We've created internal ticket(s) MAGETWO-78298 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-08-20 11:05
Hi @alessandroniciforo

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 12:07
@alessandroniciforo, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 12:07 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, triage wanted

**Comment by diamondavocado** [comment] 2019-06-04 15:56
This issue should be re-opened as it is quite a fundamental flaw. It makes it impossible to properly override templates for transactional emails which is pretty serious. 

It looks like @alessandroniciforo has already created a solution for this, including unit tests, so couldn't this fairly easily be solved? @okorshenko

**Comment by Asitis** [comment] 2019-11-13 15:12
> This issue should be re-opened as it is quite a fundamental flaw. It makes it impossible to properly override templates for transactional emails which is pretty serious.
> 
> It looks like @alessandroniciforo has already created a solution for this, including unit tests, so couldn't this fairly easily be solved? @okorshenko

I completely agree. I think it's a weird stance to say "oh yeah, this is a bug, it's reproducible in all versions, but we're not fixing it because too few people respond to this topic". I've been pulling my hair out the last two days trying to figure out why my email templates wouldn't work. This doesn't bode well for my attitude towards Magento as a system; in my experience in this case it's a broken thing and when I stumble upon a bug report from 2+ years ago saying "yeah we know, won't fix" is very bad advertisement :/

**Comment by bartoszkubicki** [comment] 2020-05-14 09:46
Still an issue in 2.3.4

**Comment by alessandroniciforo** [comment] 2020-06-09 15:32
For the records, the only blocker at that time for merging the PR was an apparently unrelated integration test that I couldn't understand why it was failing.
Afterwards, the bug seemed fixed by another commit but I see now that it's still there in 2.3.4.

I encourage anybody that is interested in this to copy [my changes](https://github.com/magento/magento2/pull/10403/files) into a new fork from 2.3-develop and open a new PR.

**Comment by ioweb-gr** [comment] 2021-03-05 11:07
Persists in 2.4. It should be reopened.
