### ISSUE TITLE
magento 2.3.2 wrong title translation on custom option when saving product via code

### ISSUE THREAD

**Issue by LouNik1984** [magento/magento2#26030] opened 2019-12-13 16:19 UTC
### Preconditions (*) 
Magento 2.3.2 with nginx and php 7.2 and multi store views 

### Steps to reproduce (*)
1. create one customizable option on simple product via code below. The option title must be different for each store view

```
$store_ids = array(1,8,9);
foreach ($store_ids as $storeid) {
   // \Magento\Catalog\Api\ProductRepositoryInterface
   $product = $productInterface->get($sku, true, $storeid, true); 
   $product->setHasOptions(1);
   $product->setCanSaveCustomOptions(true);
    if($storeid == 1) $title = "de";
    elseif($storeid == 8) $title = "en";
    elseif($storeid == 9) $title = "es";
    else $title = "default";
   // \Magento\Catalog\Api\Data\ProductCustomOptionInterface
   $option = $productCustomOptionInterface->setProductId($product->getId())->addData($newdata)->setStoreId($storeid)->setTitle($title)->save(); 
$product->addOption($option);
}
```
At this point, I can see the option is saved correctly on backend with the right titles but the option doesn't appear on frontend. In order to have the option appear on frontend I should save the product. 

2. If I save the product from the backend, then everything works fine: in frontend I can see my option and the title changes based on the store view. This is correct.

3. If I save the product from code with `$productInterface->save($product)`, then the default title is fine (the title is right), all the other storevies except the first are fine (the all show the right title) but the first store view shows the title of the last store view.

So, if we look at the example code above, the default store view has the right title "default", the store view with id 8 has the right title (en), the store 9 has the right title (es) but the store view with id 1 should have title "de" instead it has "es". If I remove the store 9 and have only store views 1 and 8, then store view 1 gets title "en", it always gets the last title. 

So, for some reason, when I save the product with `$productInterface->save($product);` , the first store always picks the last title of the option.

### Expected result (*)
1. the first store view should have the right title of the option

### Actual result (*)
1. the first store view always shows the last title assigned to the option

**Comment by LouNik1984** [comment] 2019-12-16 08:15
I cannot ask for a vanilla instance since the issue happens when I update the product via code

**Comment by engcom-Charlie** [comment] 2019-12-23 11:46
Hello @LouNik1984 
We are not able to reproduce your issue on the Magento 2.4-develop.
Because your code is wrong. You have to set `title` separately of another data. 
You can only change the title for different stores(another data have to be same and can't be replaced for different stores).

So i have to close this issue.
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-12-23 11:46 UTC
Labels: Issue: Format is valid

**Comment by LouNik1984** [comment] 2019-12-23 13:10
"You have to set tittle separately of another data"

I'm not sure if I understand correctly: what you mean is that I have to first create the option and then get the option and change the title? I cannot add the different titles during creation? Is that what you mean?

**Comment by engcom-Charlie** [comment] 2019-12-23 13:29
@LouNik1984 yes, right
