### ISSUE TITLE
New order does not generate customer email

### ISSUE THREAD

**Issue by broeder** [magento/magento2#37977] opened 2023-09-08 13:42 UTC
### Preconditions and environment

Magento ver. 2.4.5-p1

### Steps to reproduce

Log into storefront using an email you have reading access to.
Create order.

### Expected result

Open client email.
A new order confirmation email is visible.

### Actual result

Open client email.
No new order confirmation email in inbox.

### Additional information

If order is placed using Back-End, mail is sent as expected.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by broeder** [comment] 2023-09-09 14:33
@magento give me 2.4-develop instance

**Comment by broeder** [comment] 2023-09-09 14:50
Account created.
Order placed.
Result:
No mail received on both previous actions.

**Comment by engcom-Bravo** [comment] 2023-09-11 12:29
Hi @broeder,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Log into storefront using an email you have reading access to.
- Create order.

We have configured with mailhog and we are able to confirmation mails after placing the order from the Backend and Storefront.


https://github.com/magento/magento2/assets/51680745/1e43b311-1098-4562-8c1d-2f5b129686c3




Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by broeder** [comment] 2023-09-11 15:09
Please review steps to reproduce:

Order must be created on Front-End. Not on Back-End.

**Comment by broeder** [comment] 2023-09-12 12:16
Hello,
Looks good. 
That leaves 2 options:
1. We are not on same version. Ours= 2.4.5-p1
2. Back-end not configured properly on my side. Can you provide relevant config ?

**Comment by engcom-Bravo** [comment] 2023-09-12 13:17
Hi @broeder,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**

- Log into storefront using an email you have reading access to.
- Create order.


https://github.com/magento/magento2/assets/51680745/4742357f-282c-4300-8b02-5a85f3e99834



We have placed the order from the storefront and we are able to get the order confirmation email.

Could you please refer this document https://experienceleague.adobe.com/docs/commerce-admin/systems/communications/email-communications.html?lang=en regarding email communications.


it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-26 06:19
Hi @broeder,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-26 06:19 UTC
Labels: Issue: needs update, Reported on 2.4.5-p1

**Comment by broeder** [comment] 2023-09-26 08:18
closed. Bug found. Linked with 3rd party module.
