### ISSUE TITLE
Admin page "has a redirect loop"

### ISSUE THREAD

**Issue by vasilii-b** [magento/magento2#2569] opened 2015-12-01 07:25 UTC
After I installed (succesfully) Magento 2.0 on my local server I wanted to access my admin panel. BUT _for the first time I got this message_ : "**This webpage has a redirect loop**". After a couple of refreshes of page I was able to login. Then, after a while I went to admin webpage again and was told the same: "**This webpage has a redirect loop**".
I used Chrome 46.0.26 on Win 7 Professional.

**Comment by danielsun174** [comment] 2015-12-01 12:07
Are you running magento on localhost?
Have you tried the admin-Panel with firefox?

Cookie-Saving on localhost with chrome doesn't always work as expected. I would recommend to intall magento on '127.0.0.1' instead of 'localhost'

**Comment by vasilii-b** [comment] 2015-12-02 07:39
@danielsun174  I tried FF and it worked (but slowly, both front & admin). Thank you for advice.

**Comment by davidalger** [comment] 2015-12-02 15:36
@vasilii-b Magento does not support running on localhost. If you're running on that domain, please change it. Duplicate of #2439

**Closed as completed by davidalger** 2015-12-02 15:36 UTC

**Comment by ValeraPogrommist** [comment] 2016-04-28 16:18
@davidalger I had the same issue using vagrant. Could u explain why magento works in this way? I use local address **Magento.dev** and sometimes! have redirection loop and sometimes! don't while authorizing in admin panel. How to control that process?
