### ISSUE TITLE
Magento 2 don't support IPv6 for DB connection

### ISSUE THREAD

**Issue by chrom** [magento/magento2#17846] opened 2018-08-29 06:28 UTC
Information on your environment:
Magento 2.2.5

Steps to reproduce:
set configuration for DB connection in IPv6 format (unconditionally at this address you should have an appropriate service)
<img width="459" alt="screen shot 2018-08-29 at 09 48 22" src="https://user-images.githubusercontent.com/944310/44770555-16625f80-ab71-11e8-8e40-d20469be8cec.png">

- Expected results:
connection to DB
- Actual results:
Error: 
`
Exception #0 (Zend_Db_Adapter_Exception): SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[:3306"
Exception #1 (PDOException): SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[:3306"
`

**Comment by magento-engcom-team** [comment] 2018-08-29 06:28
Hi @chrom. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@chrom do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-08-29 06:48
Hello @chrom, thank you for your report. GitHub is intended for bug reports, please use https://github.com/magento/community-features for other suggestions like improvements or feature requests.

**Comment by chrom** [comment] 2018-08-29 06:54
@engcom-backlog-nickolas Is it impossible to connect the database is not it a bug?

**Comment by engcom-backlog-nickolas** [comment] 2018-08-29 07:27
@chrom, this is duplicate of https://github.com/magento/magento2/issues/774, and already has corresponding ticket [MAGETWO-31246](https://jira.corp.magento.com/browse/MAGETWO-31246). It will be processed faster if you move this to https://github.com/magento/community-features

Best regards!

**Closed as completed** 2018-08-29 07:42 UTC
Labels: feature request, Issue: Format is not valid
