### ISSUE TITLE
StoreManager::getStore(null) returns default store after calling StoreManager::setCurrentStore(0)

### ISSUE THREAD

**Issue by JacobDrummond** [magento/magento2#6068] opened 2016-08-09 09:42 UTC
### Preconditions
1. PHP 5.6.16
2. MySQL 5.6.21-log
3. Magento 2.1.0
4. Nginx 1.4.6
### Steps to reproduce
1. Write a console command that writes EAV attribute values to the admin store scope.
2. In my case I was looping over a product collection to set URL keys. I execute these lines above loading the product collection: `$this->appState->setAreaCode('adminhtml')` and `$this->storeManager->setCurrentStore(0);`.
3. Execute the command.
### Expected result
1.  EAV attribute values will be written to tables with store_id=0
### Actual result
1.  EAV attribute values are written to tables with store_id=1 (or whatever your default store is).
### Cause
1. If a current store has not been set, the store manager loads the default store.
2. To test whether a store has been set, StoreManager [runs the following test](/magento/magento2/blob/2.1.0/app/code/Magento/Store/Model/StoreManager.php#L149): `if (!$this->currentStoreId)`
3. If `$this->currentStoreId` is `0`, then the default store is loaded, even though the calling scope has specifically requested the admin store.
### Solution
1. Change `if (!$this->currentStoreId)` to `if (!isset($this->currentStoreId))`

**Comment by JacobDrummond** [comment] 2016-09-02 15:34
@andimov, has this issue been acknowledged and an internal ticket created?

**Comment by andimov** [comment] 2016-09-02 15:40
@JacobDrummond
Thank you for reporting this issue!
This issue is not reproduced yet by our team members. 
Could you please provide a solution with pull request in github?

**Comment by JacobDrummond** [comment] 2016-09-02 15:53
@andimov,

> This issue is not reproduced yet by our team members. 

As in they haven't attempted to reproduce it, or they can't reproduce it?

> Could you please provide a solution with pull request in GitHub?

My solution is the one provided in the "Solution" section of the bug report. I'll create a pull request over the weekend.

**Comment by JacobDrummond** [comment] 2016-09-18 20:39
@andimov, my long-overdue pull request is #6660.

**Comment by magento-engcom-team** [comment] 2017-10-19 13:30
@JacobDrummond, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-19 13:30 UTC
Labels: bug report, Component: Eav, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
