### ISSUE TITLE
DHL Sandbox Mode - Validation Failure:Site Id is wrong

### ISSUE THREAD

**Issue by WebHostingAce** [magento/magento2#31091] opened 2020-11-30 04:33 UTC
### Preconditions (*)

1. Magento 2.4.1
2. DHL Module - 100.4.0

### Steps to reproduce (*)

1. Use sandbox Access ID, Password, Account Number
2. Sandbox Mode - Yes

### Expected result (*)

1. Sandbox Mode to work

### Actual result (*)

1.  Sandbox Mode is not working

In Line No, 1043 https://github.com/magento/magento2/blob/91aaeec6b2ea79f364b5614ac931972d00c085b0/app/code/Magento/Dhl/Model/Carrier.php#L1043 - It seems gateway_url being used regardless of Admin setting.

**Comment by engcom-Alfa** [comment] 2020-12-15 09:12
Hi @WebHostingAce . Thank you for your report!
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.

**Manual testing scenario:**

1. Configure **_DHL_** shipping method

![2020-12-15_10-57](https://user-images.githubusercontent.com/51679138/102193117-5970aa00-3ec4-11eb-96f1-eb7d65bb8bb2.png)

2. Sandbox Mode - Yes

![2020-12-15_10-57_1](https://user-images.githubusercontent.com/51679138/102193148-62617b80-3ec4-11eb-85a1-dabb3273b13a.png)

**Actual Result:** :heavy_check_mark: Sandbox Mode is working

![Screenshot from 2020-12-15 11-08-38](https://user-images.githubusercontent.com/51679138/102194507-10b9f080-3ec6-11eb-9082-bdeb3e2bb480.png)
![2020-12-15_11-09](https://user-images.githubusercontent.com/51679138/102194516-131c4a80-3ec6-11eb-883e-13284d61ae38.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-15 09:12 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.4.1
