### ISSUE TITLE
Watermark turning images cyan

### ISSUE THREAD

**Issue by fvlasie** [magento/magento2#38855] opened 2024-06-20 21:26 UTC
### Preconditions and environment

- Magento version: 2.4.7-p1
PHP 8.2.2

### Steps to reproduce

Product images with watermark applied are showing in cyan.

### Expected result

Product images with watermark applied should be unchanged in terms of colour where the watermark does not fall

### Actual result

Product images are turning up in cyan after setting watermarks on.

### Additional information

Original image:
<img width="247" alt="Screenshot 2024-06-20 at 14 24 42" src="https://github.com/magento/magento2/assets/33334298/98c9ef01-b675-4b33-8a83-c939522adac6">

Image after watermark:
<img width="418" alt="Screenshot 2024-06-20 at 14 24 17" src="https://github.com/magento/magento2/assets/33334298/707f097f-10cb-4227-836b-0fe0cff93bdd">

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-06-21 12:38
Hi @fvlasie ,

Thanks for reporting and collaboration.

Verified the issue on 2.4-develop and we are not able to reproduce this issue.

Steps to reproduce:-

1.Navigate to Content > Design > Configuration
2.Expand “Product Image Watermarks” and configure the Base, Thumbnail, Small, and Swatch Image image settings
3.Create a new product
4.Add image to the product
5.Verify the product image in frontend


Configure product image watermark

<img width="1439" alt="Screenshot 2024-06-21 at 5 53 46 PM" src="https://github.com/magento/magento2/assets/51681379/eb108c1d-e7c7-4e90-8f09-9e505619a7d3">


Product image before watermark


<img width="1392" alt="Screenshot 2024-06-21 at 5 59 13 PM" src="https://github.com/magento/magento2/assets/51681379/2d94fe3b-f6d8-470f-a545-8739612b0e22">

<img width="1436" alt="Screenshot 2024-06-21 at 5 59 37 PM" src="https://github.com/magento/magento2/assets/51681379/0bd8729b-9ac2-446a-a748-197695fa2001">


Product image after watermark


<img width="1429" alt="Screenshot 2024-06-21 at 5 55 18 PM" src="https://github.com/magento/magento2/assets/51681379/2731834c-2471-402a-83d3-f1c465db1240">

<img width="1440" alt="Screenshot 2024-06-21 at 5 56 21 PM" src="https://github.com/magento/magento2/assets/51681379/25f20256-b16a-442b-9ab4-d1a8fb4b2e18">


Please refer the attached screenshots and let us know if we missed anything.

**Comment by fvlasie** [comment] 2024-06-24 16:24
Thanks for checking, the issue must be elsewhere!

**Comment by engcom-Delta** [comment] 2024-06-25 11:08
Hi @fvlasie ,

Closing this issue as this is not reproducible on 2.4-develop and 2.4.7.Feel free to raise a new issue or reopen this if you need more assistance.

Thanks,

**Closed as completed by engcom-Delta** 2024-06-25 11:08 UTC
Labels: Issue: needs update, Reported on 2.4.7-p1
