### ISSUE TITLE
HTTP/HTTPS assets serving

### ISSUE THREAD

**Issue by moraryou** [magento/magento2#3496] opened 2016-02-21 14:15 UTC
When i install Magento 2 and configure installer for backend to use HTTPS but keep HTTP for the frontend, if i load the frontend over the HTTPS i get:
`Mixed Content: The page at 'https://magento2.dev/' was loaded over HTTPS, but requested an insecure stylesheet 'http://magento2.dev/pub/static/frontend/Magento/luma/en_US/mage/calendar.css'. This request has been blocked; the content must be served over HTTPS.`
and most of the assets are not served.

**Comment by pantaoran** [comment] 2016-05-14 12:11
I also have this problem.

**Comment by oserediuk** [comment] 2016-06-22 15:37
Hello! Please, provide the used version. If the problem is actual for a specific branch, please, specify it and be sure that the latest update was used.

**Comment by pantaoran** [comment] 2016-06-23 06:29
I had the problem with 2.0.2 back then when I first tried this. Haven't tried it since.

**Comment by moraryou** [comment] 2016-06-23 17:43
I have tested with latest stable version(v2.0.7) and i can confirm the bug is still present.
_v2.1 is out just now after i tested with 2.0.7_

**Comment by soragan** [comment] 2016-10-08 07:23
problem still exist in 2.1.1, is there any work around while waiting for the fix?

**Comment by dmcmillin** [comment] 2017-02-12 06:22
I can confirm in 2.1.2+ it is still present.

**Comment by IlnitskiyArtem** [comment] 2017-07-11 06:42
Hi, @moraryou.
I've linked this GitHub issue to internal ticket MAGETWO-70598.

**Comment by magento-engcom-team** [comment] 2017-10-20 12:33
@moraryou, thank you for your report.
We've created internal ticket(s) MAGETWO-70598 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-08-20 11:05
Hi @moraryou

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-09-07 11:49
@moraryou, thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-09-07 11:49 UTC
Labels: Issue: Ready for Work, bug report, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is not valid, triage wanted
