### ISSUE TITLE
Magento 2.1.9 image upload not working in swatches when using safari web browser

### ISSUE THREAD

**Issue by Mahenderpinakisoft** [magento/magento2#16519] opened 2018-07-04 04:55 UTC
### Preconditions

1. Magento version 2.1.9
2.Safari Web Browser

### Steps to reproduce

1. Log in to Admin Panel
2. Navigate to "Store" -> "Product" -> "Choose Color Product Attribute"
3. go to "Manage Swatch (Values of Your Attribute)" 
![fireshot capture 28 - color _ product attributes _ attribute_ - http___localhost_magento-ce-2 1 13](https://user-images.githubusercontent.com/40623041/42257139-cdc5b27e-7f72-11e8-8254-63d72c10138c.png)
4. Click On "upload a File"

### Expected result

1. Image Browse Option
![2018-07-03](https://user-images.githubusercontent.com/40623041/42257498-6f20c892-7f74-11e8-853d-d0cec9bf1e69.png)

2. Image Should be saved

### Actual result

1. Nothing Happened , no browse option coming in safari.

**Comment by magento-engcom-team** [comment] 2018-07-04 04:55
Hi @Mahenderpinakisoft. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Mahenderpinakisoft do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-07-06 17:02
Hi @Mahenderpinakisoft Thank you for reporting.

Unfortunately Safari for windows is not supported according to the "Browser Support" [documentation](https://devdocs.magento.com/guides/v2.2/install-gde/system-requirements_browsers.html).

We are closing this ticket now.

**Closed as completed by magento-engcom-team** 2018-07-06 17:02 UTC
Labels: Issue: Format is valid
