### ISSUE TITLE
Product page frozen

### ISSUE THREAD

**Issue by KerriGymkit** [magento/magento2#37585] opened 2023-06-06 09:52 UTC
### Preconditions and environment

Magento ver. 2.4.4

product page frozen, cleared cache
![Screenshot 2023-06-06 104514](https://github.com/magento/magento2/assets/135701391/59da0556-03f1-4da4-8ee7-19a72229699c)

### Steps to reproduce

?

### Expected result

Need this cleared so I can update products on our website

### Actual result

attached screenshot of what I get when I try to see our products listed
![Screenshot 2023-06-06 104514](https://github.com/magento/magento2/assets/135701391/aea2f399-ede3-4bcd-b241-e0a1d936c17c)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-06 12:36
Hi @KerriGymkit,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


We are able to update the products.


<img width="1486" alt="Screenshot 2023-06-06 at 4 12 15 PM" src="https://github.com/magento/magento2/assets/51680745/e69a97ea-18ba-487b-a8aa-c26a23083f31">



Please provide us steps to reproduce the issue it will helps us to proceed further.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by KerriGymkit** [comment] 2023-06-06 12:39
Thank you for the update but as I have shown you I cannot even get to this stage as soon as I click products I get the below message 
![screen](https://github.com/magento/magento2/assets/135701391/49b3a111-942d-4b94-9ee5-e8d3df3ff9f6)

**Comment by engcom-Bravo** [comment] 2023-06-07 10:22
Hi @KerriGymkit,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.

<img width="1486" alt="Screenshot 2023-06-06 at 4 12 15 PM" src="https://github.com/magento/magento2/assets/51680745/0c12c7a4-6d84-4f50-939d-238fd906cca4">


Please try to clean cache and browser cache and try to enable cron by refering this document https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/configure-cron-jobs.html

bin/magento indexer:reindex && bin/magento c:f
bin/magento setup:upgrade


Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-21 06:02
Hi @KerriGymkit,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-21 06:02 UTC
Labels: Issue: needs update, Reported on 2.4.4
