### ISSUE TITLE
Excel writer generates invalid files for numbers that are followed by spaces

### ISSUE THREAD

**Issue by chenglinag** [magento/magento2#38543] opened 2024-03-22 08:19 UTC
### Preconditions and environment

- Magento 2.4.6
- php 8.2

### Steps to reproduce

Create an instance of with an over an array containing a field with a value like (i.e. space followed by digits, read as space).Magento\Framework\Convert\ExcelArrayIterator␣123␣
Call or on the object.convertwrite
Try opening the resulting file with a current version of Microsoft Excel or LibreOffice Calc. They will refuse to open the file or display for the value respectively.NaN``

### Expected result

The Excel XML should encode field as a :String

<Data ss:Type="String">123 </Data>

### Actual result

The value is encoded as :Number

<Data ss:Type="Number">123 </Data>

### Additional information

magento2/lib/internal/Magento/Framework/Convert/Excel.php#L153

 $dataType = is_numeric($value) && $value[0] !== '+' && $value[0] !== '0' ? 'Number' : 'String';

### Release note

https://www.php.net/manual/en/migration80.incompatible.php

Numeric string handling has been altered to be more intuitive and less error-prone. Trailing whitespace is now allowed in numeric strings for consistency with how leading whitespace is treated. This mostly affects:

The [is_numeric()](https://www.php.net/manual/en/function.is-numeric.php) function

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2024-03-25 05:44
Hello @chenglinag,

Thank you for the report and collaboration!

Do we have to create a custom product attribute with a value field, so that the product can be exported and then can we see the error?
Please elaborate the steps to reproduce.

Thank you.

**Comment by chenglinag** [comment] 2024-03-26 01:35
https://github.com/magento give me 2.4-develop instance

**Comment by chenglinag** [comment] 2024-03-26 01:37
@magento give me 2.4-develop instance

**Comment by chenglinag** [comment] 2024-03-26 01:56
@magento give me 2.4.6-develop instance

**Comment by chenglinag** [comment] 2024-03-26 01:59
@magento give me 2.4.6-p4 instance

**Comment by chenglinag** [comment] 2024-03-26 05:13
@magento give me 2.4-develop instance

**Comment by chenglinag** [comment] 2024-03-26 05:29
@engcom-November 
hello

It took some time and can now be reproduced.

1. Create a new customer
2. Enter 123 spaces
3. Download using XML.

**Comment by chenglinag** [comment] 2024-03-26 05:30
<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:x2="http://schemas.microsoft.com/office/excel/2003/xml" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:c="urn:schemas-microsoft-com:office:component:spreadsheet"><OfficeDocumentSettings xmlns="urn:schemas-microsoft-com:office:office"></OfficeDocumentSettings><ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel"></ExcelWorkbook><Worksheet ss:Name="customer_listing.xml"><Table><Row><Cell><Data ss:Type="String">ID</Data></Cell><Cell><Data ss:Type="String">Name</Data></Cell><Cell><Data ss:Type="String">Email</Data></Cell><Cell><Data ss:Type="String">Group</Data></Cell><Cell><Data ss:Type="String">Phone</Data></Cell><Cell><Data ss:Type="String">ZIP</Data></Cell><Cell><Data ss:Type="String">Country</Data></Cell><Cell><Data ss:Type="String">State/Province</Data></Cell><Cell><Data ss:Type="String">Customer Since</Data></Cell><Cell><Data ss:Type="String">Web Site</Data></Cell><Cell><Data ss:Type="String">Confirmed email</Data></Cell><Cell><Data ss:Type="String">Account Created in</Data></Cell><Cell><Data ss:Type="String">Billing Address</Data></Cell><Cell><Data ss:Type="String">Shipping Address</Data></Cell><Cell><Data ss:Type="String">Date of Birth</Data></Cell><Cell><Data ss:Type="String">Tax VAT Number</Data></Cell><Cell><Data ss:Type="String">Gender</Data></Cell><Cell><Data ss:Type="String">Street Address</Data></Cell><Cell><Data ss:Type="String">City</Data></Cell><Cell><Data ss:Type="String">Fax</Data></Cell><Cell><Data ss:Type="String">VAT Number</Data></Cell><Cell><Data ss:Type="String">Company</Data></Cell><Cell><Data ss:Type="String">Billing Firstname</Data></Cell><Cell><Data ss:Type="String">Billing Lastname</Data></Cell><Cell><Data ss:Type="String">Account Lock</Data></Cell></Row><Row><Cell><Data ss:Type="Number">2</Data></Cell><Cell><Data ss:Type="String">000000  000000 000000 000000 000000</Data></Cell><Cell><Data ss:Type="String">test@test.com</Data></Cell><Cell><Data ss:Type="String">General</Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"> </Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String">Mar 25, 2024 06:53:48 PM</Data></Cell><Cell><Data ss:Type="String">Main Website</Data></Cell><Cell><Data ss:Type="String">Confirmation Not Required</Data></Cell><Cell><Data ss:Type="String">Default Store View</Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String">2024-03-25</Data></Cell><Cell><Data ss:Type="String">000000 </Data></Cell><Cell><Data ss:Type="String">Male</Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String"></Data></Cell><Cell><Data ss:Type="String">Unlocked</Data></Cell></Row></Table></Worksheet></Workbook>

**Comment by engcom-November** [comment] 2024-03-27 07:34
Hello @chenglinag

Thank you for the quick response!

Tried to verify this on 2.4-develop, but in our case it is not reproducible.
Steps followed are:
1. Create a new customer.
2. Since you have not mentioned where the 123 spaces should go, we assume the name should be given as  123 .
3. Exported the customer as xml.

Opened the xml in excel and we were able to see the value entered. We did not see NaN in the name field.

Please let us know if we are missing anything.

Thank you.

**Comment by chenglinag** [comment] 2024-03-28 03:32
> Hello @chenglinag
> 
> Thank you for the quick response!
> 
> Tried to verify this on 2.4-develop, but in our case it is not reproducible. Steps followed are:
> 
> 1. Create a new customer.
> 2. Since you have not mentioned where the 123 spaces should go, we assume the name should be given as  123 .
> 3. Exported the customer as xml.
> 
> Opened the xml in excel and we were able to see the value entered. We did not see NaN in the name field.
> 
> Please let us know if we are missing anything.
> 
> Thank you.

2.4.6-p4 instance

**Comment by chenglinag** [comment] 2024-03-28 03:37
> Hello @chenglinag
> 
> Thank you for the quick response!
> 
> Tried to verify this on 2.4-develop, but in our case it is not reproducible. Steps followed are:
> 
> 1. Create a new customer.
> 2. Since you have not mentioned where the 123 spaces should go, we assume the name should be given as  123 .
> 3. Exported the customer as xml.
> 
> Opened the xml in excel and we were able to see the value entered. We did not see NaN in the name field.
> 
> Please let us know if we are missing anything.
> 
> Thank you.
@engcom-Bravo 

2.4.6-p4 instance

Tax VAT Number

**Comment by engcom-November** [comment] 2024-03-28 07:35
@chenglinag, added 123 for vat number with spaces, but the we are able to get expected result.
The entry 123 is saved as a string as seen in excel.

Take a look at the screenshot below:
<img width="877" alt="image" src="https://github.com/magento/magento2/assets/60198231/534753c9-8893-4eb2-9927-678bc6d21ecf">

Please reverify this on your end and let us know if issue persist.

Thank you.

**Comment by chenglinag** [comment] 2024-03-28 12:07
I am using the Excel version in 2016
If you have time, you can use Notepad to open the XML and compare it.

2.4-develop:                 <Data ss: Type="String">123 </Data>
2.4.6-p4 instance:        <Data ss:Type="Number">123 </Data>

**Comment by engcom-November** [comment] 2024-03-29 07:45
@chenglinag, It is recommended to check in 2.4-develop, as the issue in not reproducible in 2.4-develop, It might have been fixed in latest version.

**Comment by chenglinag** [comment] 2024-04-08 05:53
@engcom-November 

Sorry, could you tell me the PHP version information for your 2.4 development
This issue is caused by a PHP upgrade

**Comment by engcom-November** [comment] 2024-04-08 08:22
@chenglinag, This issue was tested on php 8.2.14.

**Comment by chenglinag** [comment] 2024-04-11 06:41
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2024-04-19 11:39
Hello @chenglinag,

This issue is not reproducible on 2.4-develop with php 8.3, we are closing this as the issue might have been fixed in latest version.
Feel free to reopen or raise a fresh ticket if you need more assistance on this.

Thank you.

**Comment by engcom-November** [comment] 2024-04-19 11:39
Hello @chenglinag,

This issue is not reproducible on 2.4-develop with php 8.3, we are closing this as the issue might have been fixed in latest version.
Feel free to reopen or raise a fresh ticket if you need more assistance on this.

Thank you.

**Closed as completed by engcom-November** 2024-04-19 11:39 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.6
