### ISSUE TITLE
Adding a decimal quantity product

### ISSUE THREAD

**Issue by Veorirac** [magento/magento2#29031] opened 2020-07-08 09:09 UTC
### Preconditions (*)

 Magento 2.3.5
1. Need to create configurable product with available qty

### Steps to reproduce (*)

1. Open site
2. Open configurable product page
3. Choose configuration product
4. Enter in qty field 1.1
5. Click on the button **Add to bag**
6. Open mini cart

### Expected result (*)

1. When adding product with decimal qty, must be validation for decimal qty with notification message

### Actual result (*)

1. Product added with decimal qty, and cart subtotal is recalculated

---

- [ ] Severity: **S2** 

![Juno Jacket - Google Chrome 2020-07-08 12 04 42 (1)](https://user-images.githubusercontent.com/68002645/86900354-ea707780-c113-11ea-9479-4573d6bc18e6.png)

**Comment by swathishs** [comment] 2020-07-08 09:45
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-08 09:45
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment] 2020-07-08 09:55
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-08 09:55
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-08 09:56
Hi @swathishs, here is your [Magento instance](https://i-29031-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29031-2-3-5-p1.instances.magento-community.engineering/admin_5d9c](https://i-29031-2-3-5-p1.instances.magento-community.engineering/admin_5d9c)
Login: `4acbec8d` Password: `879400b8f7f2`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-08 11:20
@Veorirac : Cant understand the issue could you please elaborate the issue.

Since cart subtotal will be calculated with the quantity 
![image](https://user-images.githubusercontent.com/58288685/86912479-b78daa00-c13a-11ea-999f-c774564bba9f.png)

**Comment by Veorirac** [comment] 2020-07-08 11:31
@swathishs This amount of product should not be added to the cart, customer can overpay for the product, but in the end will receive only 1 product, not 1.1, so I think there must be validation for the field quantity, like for negative quantity (For example -2 displayed error message **Please enter a quantity greater than 0**.

**Comment by swathishs** [comment] 2020-07-09 04:41
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-09 04:41
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment] 2020-07-17 08:01
@Veorirac : In 2.4 develop instance the fix is like automatically the decimal value is cut and added only the correct value like in the screenshot.
![image](https://user-images.githubusercontent.com/58288685/87762952-88a9bf00-c831-11ea-86d4-777ced73e791.png)

**Comment by swathishs** [comment] 2020-07-17 08:04
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-17 08:04
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-17 08:06
Hi @swathishs, here is your [Magento instance](https://i-29031-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-29031-2-3-5-p1.instances.magento-community.engineering/admin_fc2a](https://i-29031-2-3-5-p1.instances.magento-community.engineering/admin_fc2a)
Login: `47759153` Password: `7b1daf117936`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-17 08:13
Tested in 2.3.5P1 develop instance .Please find the attachment below:
![image](https://user-images.githubusercontent.com/58288685/87764053-5e590100-c833-11ea-98a3-18300c5b2b9f.png)

**Comment by swathishs** [comment] 2020-07-17 08:13
@Veorirac : Thank you for your contribution and collaboration. Since the issue is like a feature request. Hence closing the ticket.
Please create this on the Community feature repository.
https://github.com/magento/community-feature

**Closed as completed by swathishs** 2020-07-17 08:13 UTC
Labels: Issue: Format is valid, Reported on 2.3.5
