### ISSUE TITLE
Filter in url rewrites table in backend isn't being remembered

### ISSUE THREAD

**Issue by hostep** [magento/magento2#21805] opened 2019-03-17 08:55 UTC
### Preconditions (*)
1. PHP 7.2.15
2. Magento 2.3.0 (older versions are also affected)

### Steps to reproduce (*)
1. Have a vanilla 2.3.0 installed using composer
2. Make sure you have some products in your catalog
3. In the backend, go to Marketing > URL Rewrites
4. Put a filter in one of the columns (like in the `Request Path` column) and apply it
5. Click on one of the filtered results
6. Click on the `Back` button

### Expected result (*)
1. The filter you entered in the grid should still be there

### Actual result (*)
1. The filter you entered in the grid is gone

### Discussion
If you do the same on for example the product, customer, order, cms pages, ... grid, it remembers the applied filter. But not in the url rewrites grid unfortunately. Which is not user friendly if you have to manually change a couple of url rewrites based on a certain filter.

**Comment by magento-engcom-team** [comment] 2019-03-17 08:56
Hi @hostep. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@hostep do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-18 07:56
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-18 08:02
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98749`, `MAGETWO-98750` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-30 21:00
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#21834 by @vbmagento in 2.3-develop branch
Related commit(s):
 - [ae6c8bcff2d8203f7e9b36dad790a90047827b84](https://github.com/magento/magento2/commit/ae6c8bcff2d8203f7e9b36dad790a90047827b84)
 - [d85fd44346a024cd3f4f61f28dbd50a9ba8074a1](https://github.com/magento/magento2/commit/d85fd44346a024cd3f4f61f28dbd50a9ba8074a1)
 - [f75b3e9eba8192fef0116d63832aa375b22a1848](https://github.com/magento/magento2/commit/f75b3e9eba8192fef0116d63832aa375b22a1848)
 - [d5a61c01cec3429d9fb93c1a56b78a264b06ba45](https://github.com/magento/magento2/commit/d5a61c01cec3429d9fb93c1a56b78a264b06ba45)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-30 21:00 UTC
Labels: Issue: Ready for Work, Component: CatalogUrlRewrite, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Admin

**Comment by magento-engcom-team** [comment] 2019-04-04 12:30
Hi @hostep. Thank you for your report. 
The issue has been fixed in magento/magento2#22069 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [d6c12e5ea2ea391221231bbee8cf6d5094b793f6](https://github.com/magento/magento2/commit/d6c12e5ea2ea391221231bbee8cf6d5094b793f6)
 - [646200a14003f75e8be34772b9826df4b395b993](https://github.com/magento/magento2/commit/646200a14003f75e8be34772b9826df4b395b993)
 - [2a39dd308271ce1699cf64bd5f8c6c10605a0039](https://github.com/magento/magento2/commit/2a39dd308271ce1699cf64bd5f8c6c10605a0039)
 - [c126f399f0ffc1fe382a37cdf90791beb869bbd6](https://github.com/magento/magento2/commit/c126f399f0ffc1fe382a37cdf90791beb869bbd6)

The fix will be available with the upcoming 2.2.9 release.
