### ISSUE TITLE
TypeError: rawurlencode() expects parameter 1 to be string, bool given in /vendor/laminas/laminas-escaper/src/Escaper.php:246

### ISSUE THREAD

**Issue by mtjweb** [magento/magento2#33356] opened 2021-06-25 14:13 UTC
### Preconditions (*)

1. Magento version 2.4.2
2.

### Steps to reproduce (*)

1. Updatet yesterday with composer and it broke my site
2. Tried to resolve it by upgrading to Magento 2.4.2-p1, but error stayed

### Expected result (*)

1. No error

### Actual result (*)

1. Following error:

TypeError: rawurlencode() expects parameter 1 to be string, bool given in /vendor/laminas/laminas-escaper/src/Escaper.php:246 Stack trace: #0 /vendor/laminas/laminas-escaper/src/Escaper.php(246): rawurlencode(true) #1 /vendor/magento/framework/Escaper.php(286): Laminas\Escaper\Escaper->escapeUrl(true) #2 /vendor/magento/framework/Url/RouteParamsResolver.php(115): Magento\Framework\Escaper->encodeUrlParam(true) #3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Url\RouteParamsResolver->setRouteParams(Array, false) #4 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callParent('setRouteParams', Array) #5 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Url\RouteParamsResolver\Interceptor->Magento\Framework\Interception\{closure}(Array, false) #6 /generated/code/Magento/Framework/Url/RouteParamsResolver/Interceptor.php(23): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callPlugins('setRouteParams', Array, Array) #7 /vendor/magento/framework/Url.php(716): Magento\Framework\Url\RouteParamsResolver\Interceptor->setRouteParams(Array, false) #8 /vendor/magento/framework/Url.php(747): Magento\Framework\Url->_setRouteParams(Array, false) #9 /vendor/magento/framework/Url.php(929): Magento\Framework\Url->getRouteUrl('', Array) #10 /vendor/magento/framework/Url.php(873): Magento\Framework\Url->createUrl('', Array) #11 /vendor/magento/module-catalog/Model/Product/Url.php(199): Magento\Framework\Url->getUrl('', Array) #12 /vendor/magento/module-review/Block/Product/ReviewRenderer.php(149): Magento\Catalog\Model\Product\Url->getUrl(Object(Magento\Catalog\Model\Product\Interceptor), Array) #13 /generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(59): Magento\Review\Block\Product\ReviewRenderer->getReviewsUrl(false) #14 /vendor/magento/module-review/view/frontend/templates/helper/summary.phtml(12): Magento\Review\Block\Product\ReviewRenderer\Interceptor->getReviewsUrl() #15 /vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/blowers/p...') #16 /vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Review\Block\Product\ReviewRenderer\Interceptor), '/home/blowers/p...', Array) #17 /generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(122): Magento\Framework\View\Element\Template->fetchView('/home/blowers/p...') #18 /vendor/magento/framework/View/Element/Template.php(303): Magento\Review\Block\Product\ReviewRenderer\Interceptor->fetchView('/home/blowers/p...') #19 /vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #20 /vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #21 /vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #22 /generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(347): Magento\Framework\View\Element\AbstractBlock->toHtml() #23 /vendor/magento/module-review/Block/Product/ReviewRenderer.php(111): Magento\Review\Block\Product\ReviewRenderer\Interceptor->toHtml() #24 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Review\Block\Product\ReviewRenderer->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #25 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Review\Block\Product\ReviewRenderer\Interceptor->___callParent('getReviewsSumma...', Array) #26 /vendor/yotpo/magento2-module-yotpo-reviews/Plugin/Review/Block/Product/ReviewRenderer.php(32): Magento\Review\Block\Product\ReviewRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #27 /vendor/magento/framework/Interception/Interceptor.php(135): Yotpo\Yotpo\Plugin\Review\Block\Product\ReviewRenderer->aroundGetReviewsSummaryHtml(Object(Magento\Review\Block\Product\ReviewRenderer\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #28 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Review\Block\Product\ReviewRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #29 /generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(32): Magento\Review\Block\Product\ReviewRenderer\Interceptor->___callPlugins('getReviewsSumma...', Array, Array) #30 /vendor/magento/module-catalog/Block/Product/AbstractProduct.php(221): Magento\Review\Block\Product\ReviewRenderer\Interceptor->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #31 /generated/code/Magento/CatalogWidget/Block/Product/ProductsList/Interceptor.php(158): Magento\Catalog\Block\Product\AbstractProduct->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), 'default', false) #32 /app/design/frontend/Hiddentechies/bentriz-nl/Magento_CatalogWidget/templates/product/widget/content/grid.phtml(88): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), 'default') #33 /vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/blowers/p...') #34 /vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\CatalogWidget\Block\Product\ProductsList\Interceptor), '/home/blowers/p...', Array) #35 /generated/code/Magento/CatalogWidget/Block/Product/ProductsList/Interceptor.php(365): Magento\Framework\View\Element\Template->fetchView('/home/blowers/p...') #36 /vendor/magento/framework/View/Element/Template.php(303): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->fetchView('/home/blowers/p...') #37 /vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #38 /vendor/magento/framework/Cache/LockGuardedCacheLoader.php(136): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #39 /vendor/magento/framework/View/Element/AbstractBlock.php(1133): Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('BLOCK_c561c896a...', Object(Closure), Object(Closure), Object(Closure)) #40 /vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #41 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml() #42 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->___callParent('toHtml', Array) #43 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->Magento\Framework\Interception\{closure}() #44 /generated/code/Magento/CatalogWidget/Block/Product/ProductsList/Interceptor.php(581): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->___callPlugins('toHtml', Array, Array) #45 /vendor/magento/module-widget/Model/Template/Filter.php(121): Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->toHtml() #46 /vendor/magento/module-widget/Model/Template/Filter.php(132): Magento\Widget\Model\Template\Filter->generateWidget(Array) #47 [internal function]: Magento\Widget\Model\Template\Filter->widgetDirective(Array) #48 /vendor/magento/framework/Filter/DirectiveProcessor/LegacyDirective.php(42): ReflectionMethod->invokeArgs(Object(Magento\Widget\Model\Template\Filter), Array) #49 /vendor/magento/framework/Filter/Template.php(184): Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process(Array, Object(Magento\Widget\Model\Template\Filter), Array) #50 /vendor/magento/module-email/Model/Template/Filter.php(1080): Magento\Framework\Filter\Template->filter('
_toHtml() #53 /vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #54 /vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #55 /generated/code/Magento/Cms/Block/Block/Interceptor.php(230): Magento\Framework\View\Element\AbstractBlock->toHtml() #56 /app/design/frontend/Hiddentechies/bentriz-nl/Hiddentechies_Bentriz/templates/bentrizbelow.phtml(5): Magento\Cms\Block\Block\Interceptor->toHtml() #57 /vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/blowers/p...') #58 /vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template\Interceptor), '/home/blowers/p...', Array) #59 /generated/code/Magento/Framework/View/Element/Template/Interceptor.php(77): Magento\Framework\View\Element\Template->fetchView('/home/blowers/p...') #60 /vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template\Interceptor->fetchView('/home/blowers/p...') #61 /vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #62 /vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #63 /vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #64 /generated/code/Magento/Framework/View/Element/Template/Interceptor.php(302): Magento\Framework\View\Element\AbstractBlock->toHtml() #65 /vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\Template\Interceptor->toHtml() #66 /vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('bentriz.below') #67 /generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('bentriz.below') #68 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('bentriz.below') #69 /generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('bentriz.below', false) #70 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('bentriz.below', false) #71 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) #72 /generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') #73 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper') #74 /generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.wrapper', false) #75 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false) #76 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false) #77 /generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('root') #78 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') #79 /generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('root', true) #80 /vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement('root') #81 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput() #82 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array) #83 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #84 /generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #85 /vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #86 /vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor)) #87 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #88 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array) #89 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor)) #90 /generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array) #91 /vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #92 /generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #93 /vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #94 /pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #95 {main}

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrtuvn** [comment] 2021-06-25 14:30
Thanks you for report but this ticket already duplicated with this one https://github.com/magento/magento2/issues/33346

**Comment by ihor-sviziev** [comment] 2021-06-25 15:10
Hi @mtjweb,
Thank you so much for your report! As @mrtuvn said, it's a duplicate of https://github.com/magento/magento2/issues/33346 this has the highest possible priority P0.
**We're already working on a fix.**

As this issue duplicates another, I'm closing it.

**Closed as completed by ihor-sviziev** 2021-06-25 15:10 UTC
Labels: duplicate, Issue: ready for confirmation
