### ISSUE TITLE
Magento 2 gallery images swatching does not show the video in the gallery

### ISSUE THREAD

**Issue by rashidtahir** [magento/magento2#9226] opened 2017-04-13 07:31 UTC
### Preconditions

1. Magento 2.1.2 

### Steps to reproduce

1. Go to a product page that has swatches and gallery contain images and video's
2. Click on the swatches
3-By default in magento 2.1.2 on clicking swatches only base images was changed so our requirement was to change the whole gallery according to swatch selected so i used a solution to replace the whole gallery from github below is the link of the solution after that image swatching works but video's doesn't showing.

https://github.com/magento/magento2/commit/e67e1dfb30a1a7c30133e6a347b3fc929a1bf4b6

### Expected result

1. It should swach the images as well as video's containing that product

### Actual result

1. [Screenshot, logs]
But it only show images also it show image of the video not the video.

On page load it shows the video's from configurable product gallery fine
![pageload](https://cloud.githubusercontent.com/assets/5793268/24994817/e9aac354-2045-11e7-95d4-f209c440d636.png)
Now same image and video is in simple products clicking on size 38 you can see the video is converted to image not the actual video which were showing on page load 
![afterclickingonswatches](https://cloud.githubusercontent.com/assets/5793268/24994861/1681db56-2046-11e7-99f3-55b764aea175.png)

**Comment by korostii** [comment] 2017-05-03 16:03
@rashidtahir please don't flood discussions of unrelated tasks with your comments. 
With all due respect, it isn't likely to attract anything beyond annoyance to your issue.

This is not a help desk, it's a bug tracker. Don't expect a fast response: there's quite a lot of open issues and not so much people to sort them out. The harsh truth is that if your issue isn't a priority for neither the core team, nor the community - it might drag on for ages.

If you are looking for some quick help or advice please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

**Comment by korostii** [comment] 2017-05-04 14:27
Possible duplicate of #6360

**Comment by magento-engcom-team** [comment] 2017-10-11 14:30
@rashidtahir, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 14:30 UTC
Labels: Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
