### ISSUE TITLE
Bank transfer's Instruction isn't showing up in email template

### ISSUE THREAD

**Issue by lombokindustries** [magento/magento2#19352] opened 2018-11-23 02:33 UTC
### Summary (*)
For the spesific need in my site, I disabled new order email (order_new.html), and use order comment email (order_update.html) to inform the order to customer.

so, I replaced order_update.html script with order_new.html and set bank transfer method statically, because i have only 1 bank account..

for now, there are 2 banks accounts, and I created multiple banks module.. and the problem comes, only the payment instruction not showing up in email template (order_update.html)..

{{ var payment_html|raw }} not working anymore.. I already tried to use conditional statement (native & javascript) also, but not working..

so, How do I show the payment INSTRUCTION in order_update.html, OR How do I use conditional in email template. we can use
{{ order.getPayment().getMethodInstance().getCode() == "banktransfer" }} and set the instruction statically

_
Thank You

### Examples (*)

{{ var payment_html|raw }}  not working
{{ order.getPayment().getMethodInstance().getInstruction() }} not working

**Comment by magento-engcom-team** [comment] 2018-11-23 02:33
Hi @lombokindustries. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@lombokindustries do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by lombokindustries** [comment] 2018-11-23 02:54
**Summary of the issue**
Payment information not showing up in email template (order_update.html)
these code not working:
{{ var payment_html|raw }} 
{{ order.getPayment().getMethodInstance().getInstruction() }}

**Information on your environment**
Magento 2.1.10

**Steps to reproduce**
I had been trying to use getInstruction() to show the bank's instruction and I also use conditional with getCode() value to set the bank instruction statically. but I have no idea which conditional format is valid and can be implemented in email template.

**Expected and actual results**
I need to show up payment information using {{ var payment_html|raw }} on email template (order_update.html) that is sent from comment order that exist in order detail. if it isn't working, we can still use conditional like I said.

**Comment by orlangur** [comment] 2018-11-23 03:16
GitHub is intended for bug reports, please use [Magento Stack Exchange](https://magento.stackexchange.com) for questions on how particular customization can be implemented.

**Comment by magento-engcom-team** [comment] 2018-11-23 03:16
Hi @orlangur. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Closed as completed** 2018-11-23 03:16 UTC
Labels: Issue: Format is not valid

**Comment by lombokindustries** [comment] 2018-11-23 03:35
Ok, Thank You.. [here the link](https://magento.stackexchange.com/questions/251017/bank-transfers-instruction-isnt-showing-up-in-email-template)
