### ISSUE TITLE
Unable to upload logo or favicon magento 2.1.8.

### ISSUE THREAD

**Issue by anton-dvornik** [magento/magento2#10804] opened 2017-09-07 09:09 UTC
### Preconditions

1. Magento CE 2.1.8 with sample data is installed.
2.Browser: Safari Version 10.1.2

### Steps to reproduce
1. Go to the admin panel
2.Go to the tab Content -> Configuration
3. Click "edit" on any store
4.Open tab HTML Head or HEADER
5.Try to upload any image

### Expected result
1. Image will be uploaded

### Actual result
1. Image doesn't upload (see screenshot)
![screen shot 2017-09-07 at 12 02 49](https://user-images.githubusercontent.com/31726599/30155188-d1a2ef6e-93c4-11e7-9022-a3a207031d4f.png)

Issue reproduces only in safari browser

**Comment by orlangur** [comment] 2017-09-12 20:04
https://github.com/magento/magento2/pull/10033 seems to be a fix for this bug not backported to `2.1` yet: https://github.com/magento/magento2/blob/2.1-develop/app/code/Magento/Ui/view/base/web/js/form/element/file-uploader.js#L307

Looks like an easy frag to me. Anybody? 😎

**Comment by Olek89** [comment] 2017-09-13 15:01
i have the same issue in uploading downloadable products

**Comment by magento-engcom-team** [comment] 2017-09-19 20:50
@anton-dvornik thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation or latest release.

**Comment by anton-dvornik** [comment] 2017-09-20 12:30
@magento-engcom-team Thank for your response.
I’ve installed the latest clean version of magento CE-2.1.8, and tried to reproduce the issue. The issue still reproduces.
What details of my environment are you interested in?

**Comment by orlangur** [comment] 2017-09-20 12:37
OS maybe. Is it MacOS or Windows in your case?

**Comment by anton-dvornik** [comment] 2017-09-20 12:46
I use Mac Os version 10.12.1

**Comment by magento-engcom-team** [comment] 2017-09-20 14:19
@anton-dvornik, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 14:19 UTC
Labels: bug report, Progress: needs update, Issue: Clear Description, Issue: Format is valid
