### ISSUE TITLE
Performance Toolkit's benchmark.jmx cannot sign in as admin

### ISSUE THREAD

**Issue by heygambo** [magento/magento2#28485] opened 2020-06-03 09:55 UTC
### Preconditions
- Install Magento 2.3.2 (Magento-CE-2.3.2-2019-06-13-03-23-52.tar.gz)
- Follow the performance toolkit readme to:
  - install the small.xml fixtures on Magento.
  - enable admin account sharing.
  - Set the indexes to update on a schedule rather than on update.
- Open JMeter
- Open benchmark.jmx using jMeter (https://github.com/magento/magento2/blob/2.4-develop/setup/performance-toolkit/benchmark.jmx)
- Update the benchmark.jmx custom variables:
  - host
  - request_protocol (http or https) 
  - admin_path
  - admin_user
  - admin_password
- Enable "View Results Tree" using the context menu

### Steps to reproduce
- Click "Clear all" from the top action buttons (multiple brooms icon)
- Click "Start" from the top action buttons (play icon)
- Click on "View Results Tree"

### Expected result
- It logs the admin in and keeps a session for the following tests

### Actual result
It fails to sign in the admin user.
![image](https://user-images.githubusercontent.com/449438/83621581-22255600-a58f-11ea-92e8-be9fd707c5d7.png)

I've tried the exact same URL + credentials on the browser and I can sign in without any issues.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Note about Severity:** This does not affect Magento itself but the provided performance toolkit. I've tried many things including using different JMeter versions and adjusting the sign-in request to what the browser is doing.

It doesn't block us from using Magento, but because of this, we cannot determine if and how we would have to use it in a high scale manner.

**Comment by engcom-Lima** [comment] 2020-07-17 09:50
Hello @heygambo 
Could you provide more details for reproduce this issue?
Make sure the "Server Name or IP" is set correctly in the "Default HTTP Request" 
![Screenshot_26](https://user-images.githubusercontent.com/60198022/87771297-d66df980-c828-11ea-8ffd-8e0b1496e70e.png)
More information about using [Jmeter](https://upcloud.com/community/tutorials/benchmark-magento-with-jmeter/)

Thank you!

**Comment by heygambo** [comment] 2020-07-18 18:08
Hey @engcom-Lima, unfortunately, I don't have the setup anymore but I'm sure I had the correct endpoint.

I've updated those variables on benchmark.jmx

> * Update the benchmark.jmx custom variables:
>   
>   * host
>   * request_protocol (http or https)
>   * admin_path
>   * admin_user
>   * admin_password
> * Enable "View Results Tree" using the context menu

**Comment by engcom-Lima** [comment] 2020-07-20 07:52
Hello @heygambo 
Unfortunately, I'm not able to reproduce issue by steps you described on 2.4-develop and on 2.3.5-p1.
I`m not changed the "host" value in the benchmark.jmx. I change it only in the "Default HTTP Request"

**Comment by heygambo** [comment] 2020-07-21 04:48
hm then maybe we should close it

**Comment by engcom-Lima** [comment] 2020-07-21 07:04
@heygambo  Closed as per [this](https://github.com/magento/magento2/issues/28485#issuecomment-660865475) and [this](https://github.com/magento/magento2/issues/28485#issuecomment-661630948) comments

**Closed as completed by engcom-Lima** 2020-07-21 07:04 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.2
