### ISSUE TITLE
Login as customers misbehaves when multistore, even after ending session

### ISSUE THREAD

**Issue by MartinAarts** [magento/magento2#34764] opened 2021-12-06 10:39 UTC
Severity: S4

environment: Magento 2.4.3p1 multistore
**Steps to reproduce:**

1. Stores - Configuration - Customer Configuration - Share Customer Accounts - Set to Website and Save
2. Stores - Configuration - Customers - Enable Login as Customer and set Store To Login To - "Auto-detection" - Save
Front end - Create a Customer in 2nd Store website
3. Admin - Stores - Configuration - General - Web - Change scope to 2nd Store view - change Base URLs & Base URLs (Secure)
Enter URL's with same URL of 1st Store URL and Save
4. Reindex and clear cache
5. Admin - Customers - All Customers - Edit 2nd Store customer - Login as Customer - No issue. User is logged in to store front.
6. Close session
7. Now change back the URL's of 2nd Store to old values and Save (Admin - Stores - Configuration - General - Web - Change scope to 2nd Store view - change Base URLs & Base URLs (Secure) to old URL values)
8. Clear cache
9. Login as customer again from Admin
10. Close session
11. Open Front end - 1st website Store - **Issue: User is redirected to 2nd Store URL.**

Result: you will get redirected to store B on random pages.

It's a bit hard to test without a development multisite environment.

**Comment by MartinAarts** [comment] 2021-12-06 12:07
@magento give me 2.4-develop instance

**Comment by MartinAarts** [comment] 2021-12-06 12:25
Reproduced on development instance, by creating a second store with the same url.

First created the second store with same url
Then login as customer, assigned to this new store
end this sessions
Change url of second store to something else
You will be redirected to this new url, when just browsing the frontend of the same. Not logged in as customer.

**Comment by engcom-November** [comment] 2021-12-07 12:08
Verified the issue on Magento 2.4-develop branch and the issue is reproducible.
Steps performed:
Stores - Configuration - Customer Configuration - Share Customer Accounts - Set to Website and Save
Stores - Configuration - Customers - Enable Login as Customer and set Store To Login To - "Auto-detection" - Save
Create 2nd Store with same URL of 1st Store URL
Stores - Customers - All Customers - Edit Customer of 2nd Store - Login as Customer - No issue.
![image](https://user-images.githubusercontent.com/60198231/145026378-cbb87701-a14e-4749-b0e6-407027cdc492.png)

Close Session
Now change the 2nd Store URL to Something else. Ex: in my case: http://fr.magento24.local
Open 1st Store - **Issue: User is redirected to 2nd Store.**
![image](https://user-images.githubusercontent.com/60198231/145026305-1b8e1364-ea8d-4558-9ed4-7415afd2c999.png)

**Comment by engcom-November** [comment] 2021-12-23 14:06
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-28 06:47
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-12-28 13:13
@magento give me 2.4-develop instance

**Comment by girija-kudupudi** [comment] 2021-12-29 06:07
@magento give me 2.4-develop instance

**Comment by girija-kudupudi** [comment] 2021-12-29 13:13
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-04-29 06:06
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-02 11:02
Hi @MartinAarts We re-verified the issue again on Magento 2.4-develop branch and setting up multiple stores requires below mandatory configuration as well as per [dev docs](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_over.html) . On doing so this issue is not reproducible anymore.
> Each website and each store view must have a unique identifier. This identifier is required to use the MAGE_RUN_TYPE and MAGE_RUN_CODE variables as follows:
MAGE_RUN_TYPE can be either store or website
Use website to load a website in your storefront.
Use store to load any store view in your storefront.
MAGE_RUN_CODE is the unique website or store view code that corresponds to MAGE_RUN_TYPE

Can you please recheck the issue again as per [dev docs ](https://devdocs.magento.com/cloud/project/project-multi-sites.html) , 
[guidelines](https://devdocs.magento.com/guides/v2.4/config-guide/multi-site/ms_websites.html#multi-storecode-baseurl)
Thank you.

**Comment by engcom-November** [comment] 2022-05-16 05:21
Hi @MartinAarts ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-16 05:21 UTC
Labels: Component: Customer, Reproduced on 2.4.x, Component: LoginAsCustomer, Progress: done, Issue: needs update, Area: Account, Reported on 2.4.3-p1

**Comment by cafefin** [comment] 2022-09-14 09:22
@magento give me 2.4-develop instance

**Comment by cafefin** [comment] 2022-09-14 10:06
I can reproduce this issue . Tried login as 2nd Store customer but magento direct to 1st store view
Customer Account Information: 
![image](https://user-images.githubusercontent.com/33374759/190125470-47752e2a-e8de-4b68-9f46-aaada305e406.png)
When login as customer : 
![image](https://user-images.githubusercontent.com/33374759/190125705-5f15c075-fa8e-4dc6-a89c-c307c9b25dac.png)
