### ISSUE TITLE
configurable product added to backend not show in front (added with api)

### ISSUE THREAD

**Issue by Gabriel-Bruno** [magento/magento2#27233] opened 2020-03-11 01:09 UTC
### Preconditions (*)

1.  Magento 2.4 with sample data

### Steps to reproduce (*)

1. Adding Configurable product with api to website
2. Using [this](https://devdocs.magento.com/guides/v2.4/rest/tutorials/configurable-product/plan-product.html) documentation
3. First create the new Attribute Set "Test" based on Default
4. Add the "attributeset3attribute1" attribute to this Attribute Set 
Here is Api requests [Configurable.zip](https://github.com/magento/magento2/files/4937433/Configurable.zip)
5. On the Luma storefront page, search for TS.
![Peek 2020-07-17 13-26](https://user-images.githubusercontent.com/60198022/87781529-80ee1880-c839-11ea-9d65-490d72a517ec.gif)
6. Status of the product in backend "Out of Stock"
7. Change the status to "In Stock"  -> Save
8. Try to search it again.
Result is the same as on 6 step
### Expected result (*)

1. The product should be added successfully to website and shows/display on front.  

### Actual result (*)

1. The product is added successfully in backend, but in front its not displayed. 
3.if open the product page(edit product) on backend, and just save it without any change, its shows/display on front! (on 2.3.4 version)
4. video : https://www.loom.com/share/0afc407bebb44c6ba45ee2e701b3f35c
5.this problem is just for configurable product, for simple product no issue.

**Comment by lbajsarowicz** [comment] 2020-03-11 01:47
@Gabriel-Bruno Do you have `realtime` indexers mode?

**Comment by Gabriel-Bruno** [comment] 2020-03-11 10:46
Hello @lbajsarowicz 
please find below the show-mode 
Design Config Grid:                                Update on Save
Customer Grid:                                     Update on Save
Category Products:                                 Update on Save
Product Categories:                                Update on Save
Catalog Rule Product:                              Update on Save
Product EAV:                                       Update on Save
Stock:                                             Update on Save
Inventory:                                         Update on Save
Catalog Product Rule:                              Update on Save
Product Price:                                     Update on Save
Google Product Removal Feed:                       Update on Save
Google Product Feed:                               Update on Save
Catalog Search:                                    Update on Save
Design Config Grid:                                Update on Save
Customer Grid:                                     Update on Save
Category Products:                                 Update on Save
Product Categories:                                Update on Save
Catalog Rule Product:                              Update on Save
Product EAV:                                       Update on Save
thanks for your kind attention.

**Comment by lbajsarowicz** [comment] 2020-03-11 10:53
Does the product appear when you perform reindex?
Do you have full page cache enabled?
Is product "in stock" with it's siblings?

**Comment by Gabriel-Bruno** [comment] 2020-03-11 11:07
@lbajsarowicz 
Does the product appear when you perform reindex?
now i run the reindex command and all products come live in front!
but how to solve the issue that no need to repeat it every time manually ?
Do you have full page cache enabled?yes
Is product "in stock" with it's siblings?yes

**Comment by lbajsarowicz** [comment] 2020-03-11 11:11
You should not reindex manually.
Especially with `On save` reindex method.

I have no idea what causes the issue, yet.

**Comment by mediact-pipelines** [comment] 2020-04-06 13:26
I'm having the same issue with multiple of our shops. If there is anything I can assist with please mention me.

**Comment by igorwulff** [comment] 2020-04-06 13:27
I'm having the same issue with multiple of our shops. If there is anything I can assist with please mention me.

**Comment by lbajsarowicz** [comment] 2020-04-09 16:15
Could you record video showing the issue?
Enter Indexer settings on the video and cache settings to find out what is the context of the issue.

**Comment by magento-engcom-team** [comment] 2020-07-17 11:35
:white_check_mark: Confirmed by @engcom-Lima 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-35965` were created

**Issue Available**: @engcom-Lima, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by subbu1993** [comment] 2020-07-27 16:53
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-27 16:55
Hi @subbu1993, here is your [Magento instance](https://i-27233-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-27233-2-3-5-p1.instances.magento-community.engineering/admin_2b60](https://i-27233-2-3-5-p1.instances.magento-community.engineering/admin_2b60)
Login: `be225cdb` Password: `bde9742fef01`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Kilo** [comment] 2020-10-26 15:42
Hello @Gabriel-Bruno 
Unfortunately, I'm not able to reproduce this issue on 2.4-develop
![Configurable-API](https://user-images.githubusercontent.com/60192090/97193053-3faec280-17b1-11eb-9691-1812c2cf8452.gif)

Can you please add more details or correct me in case I did something wrong?

**Comment by engcom-Kilo** [comment] 2020-10-28 09:56
Hello @Gabriel-Bruno 
As we are not able to reproduce this issue on 2.4-develop, I'm closing this one for now. If you have any updates, feel free to add more details and I'll re-open it for further investigation. Thanks!

**Closed as completed by engcom-Kilo** 2020-10-28 09:56 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Api, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S2, Priority: P1, Progress: done, Issue: needs update, Reported on 2.3.4

**Comment by sdzhepa** [comment] 2020-11-04 18:23
The related internal Jira ticket `MC-35965` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem on the latest `2.4-develop` please create new Issue with updated information/steps/preconditions in the **_Description section_**.
