### ISSUE TITLE
Custom URL Rewrite Not working

### ISSUE THREAD

**Issue by minesh0111** [magento/magento2#10231] opened 2017-07-13 06:21 UTC
### Preconditions

1. Magento versio 2.1.5 

### Steps to reproduce

1. Add New URL Rewrite 
![url-rewrite](https://user-images.githubusercontent.com/18025431/28152932-91cc4e56-67c0-11e7-952b-eea1740d71ea.png)

### Expected result

1. It should redirect **customer/account/create**  page To **customer/account/login** page same like [Magento 1.x](https://magento.stackexchange.com/a/134438/31150) 

### Actual result

1. Nothing is happening when we go to **customer/account/create** page

**Comment by dmitriyprime** [comment] 2017-07-25 12:56
Hi, @minesh0111. Thanks for the feedback. We've created internal ticket MAGETWO-70997 to address this issue.

**Comment by minesh0111** [comment] 2017-08-29 04:59
@dmitriyprime  will i get notification when this get resolved ?

**Comment by dmitriyprime** [comment] 2017-08-29 08:00
Hi, @minesh0111. Yes, you will get the notification.

**Comment by magento-engcom-team** [comment] 2017-09-28 10:30
@minesh0111, thank you for your report.
We've created internal ticket(s) MAGETWO-70997 to track progress on the issue.

**Comment by mrodespin** [comment] 2017-10-15 12:57
I have been looking this issue, it seems that is happening in version 2, 2.1 and 2.2. The problem is that magento routing logic is not having in mind the custom redirections.

Can anyone assign this ticket to me? I have one solution in mind but i am not sure if it is the better one, talking about performance terms

**Comment by maksek** [comment] 2017-10-15 13:02
@mrodespin , can you accept invitation in collaborator group. so I can assign the ticket to you?

**Comment by mrodespin** [comment] 2017-10-15 13:32
@maksek done!

**Comment by magento-team** [comment] 2017-10-16 23:00
Internal ticket to track issue progress: MAGETWO-81977

**Comment by okorshenko** [comment] 2017-10-17 15:02
@minesh0111 the issue has been fixed and delivered to 2.2-develop branch. Will be available in 2.2.2 release soon

**Closed as completed by okorshenko** 2017-10-17 15:02 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid

**Comment by magento-team** [comment] 2017-10-19 18:00
Internal ticket to track issue progress: MAGETWO-82312

**Comment by magento-team** [comment] 2017-10-19 19:00
Internal ticket to track issue progress: MAGETWO-82310
