### ISSUE TITLE
Problems with update timestamps of CMS pages?

### ISSUE THREAD

**Issue by debuysserk** [magento/magento2#2918] opened 2016-01-07 16:06 UTC
Hi guys,

Since upgrading to latest version of Magento 2, one of our customers is experiencing an update timestamp issue on CMS pages. The modification date of CMS pages (and blocks) is never updated to today's date.

Known issue?

**Comment by shiftedreality** [comment] 2016-01-12 15:47
@debuysserk is it still reproducible on latest developer branch? CMS pages/blocks had changes and this problem looks fixed.

**Comment by davidalger** [comment] 2016-02-12 02:57
Closing due to lack of reply from OP. Please re-open issue if still encountered on latest mainline.

**Closed as completed by davidalger** 2016-02-12 02:57 UTC
Labels: Progress: needs update
