### ISSUE TITLE
Cart Price Rules Usage limit error

### ISSUE THREAD

**Issue by nithinreddyb** [magento/magento2#36333] opened 2022-10-19 18:36 UTC
### Preconditions and environment

1. We are using Magento 2.4.5-p1 Enterprise/Commerce Edition with PHP 8.1
2. MySQL 8.0
3. Ubuntu 20.04 LTS
4. nginx 1.18
5. Trying to limit the usage of cart price rule.

### Steps to reproduce

1. In Marketing->Promotions->Cart Price Rules->Add New Rule.
2. I have provided the Rule Name, Description, set the rule as 'Active', selected 'Main Website', selected all Customer Groups available, set the 'Coupon' to 'Specific Coupon', provided the 'Coupon code' as 'TEST10', set 'Uses per Coupon' -> 1, set 'Uses per Customer' -> 1.
3. Under Conditions,  No Conditions applied.
4. Under Actions Tab, set 'Apply' as 'Fixed amount discount for whole cart' and set the 'Discount Amount' as '10'.
5. Place an order using the coupon code as a guest(Coupon is applied and you are able to get the discount).
6. Place an order using the same coupon code again as a guest(Coupon is applied and you are able to get the discount again)
7. Place an order using the same coupon code again as a registered user(Coupon is applied and you are able to get the discount again)
8. Place an order using the same coupon code again as a different registered user(Coupon is applied and you are able to get the discount again)
![scrnli_10_20_2022_12-00-03 AM](https://user-images.githubusercontent.com/47890585/196775135-b64c8e32-91f7-43c4-88e1-2cb6dbef0317.png)

### Expected result

Coupon should not be utilized more than once for both the guest and logged-in user combined.

### Actual result

Able to use the coupon as many time as I want as a guest and as a logged in user.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by subbu1993** [comment] 2022-10-20 07:18
@magento-engcom-team Give me 2.4.5 instance

**Comment by subbu1993** [comment] 2022-10-20 07:22
@magento give me 2.4.5-p1 instance

**Comment by engcom-Bravo** [comment] 2022-10-20 09:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-20 10:28
@magento give me 2.4-develop instance with edition ee

**Comment by engcom-Bravo** [comment] 2022-10-20 12:47
Hi @subbu1993,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is reproducible on both the instances.Cart Price Rules are not working as per Usage Limit.We are able to use the Coupon as many as times as a guest and registered Customers.

Steps to reproduce:

1.In Marketing->Promotions->Cart Price Rules->Add New Rule.
2.Add Rule name, set the rule as 'Active', selected 'Main Website', selected all Customer Groups available, set the 'Coupon' to 'Specific Coupon', provided the 'Coupon code' as '12345', set 'Uses per Coupon' -> 1, set 'Uses per Customer' -> 1.
3.Under Conditions, No Conditions applied.
4.Under Actions Tab, set 'Apply' as 'Fixed amount discount for whole cart' and set the 'Discount Amount' as '10'.
5.Place an order using the coupon code as a guest
6.Place an order using the same coupon code again as a guest
7.Place an order using the same coupon code again as a registered user
8.Place an order using the same coupon code again as a different registered user.


<img width="1304" alt="Screenshot 2022-10-20 at 6 13 31 PM" src="https://user-images.githubusercontent.com/51680745/196952004-2be8ec49-d087-491f-8ed2-b74d1421a2ad.png">



<img width="1187" alt="Screenshot 2022-10-20 at 4 17 53 PM" src="https://user-images.githubusercontent.com/51680745/196952115-f6efca7b-b01a-49bf-91e5-439d3d01916b.png">




<img width="1361" alt="Screenshot 2022-10-20 at 4 18 15 PM" src="https://user-images.githubusercontent.com/51680745/196952212-209bc666-8aeb-43f7-8c6a-10d46ae930c9.png">




Hence confirming the issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-10-20 13:49
Hi @nithinreddyb,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Cart Price Rules working as expected.




<img width="1338" alt="Screenshot 2022-10-20 at 7 10 42 PM" src="https://user-images.githubusercontent.com/51680745/196964977-56245aa6-65bd-4b71-b9f0-21381c3fa7a9.png">



<img width="1244" alt="Screenshot 2022-10-20 at 7 10 50 PM" src="https://user-images.githubusercontent.com/51680745/196965092-1ef11b7c-3b32-4d85-95b1-aecc6fac617b.png">




<img width="1270" alt="Screenshot 2022-10-20 at 7 11 00 PM" src="https://user-images.githubusercontent.com/51680745/196965179-fcd888f9-4f4a-4148-af97-fc4fb8686638.png">



<img width="1361" alt="Screenshot 2022-10-20 at 7 17 33 PM" src="https://user-images.githubusercontent.com/51680745/196966363-df165cdf-0e71-44ee-8d2a-9090868d2081.png">




After creating an Cart Price Rules we need to start Consumers to update Coupon usage.Kindly go through with this [document
](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/start-message-queues.html) and let us know if you are still facing any issue.

Kindly recheck the issue on Magento 2.4-develop instance.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-03 06:12
Hi @nithinreddyb,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-03 06:12 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
