### ISSUE TITLE
Upgrade from 2.00 to 2.01 stalls

### ISSUE THREAD

**Issue by mswaidan** [magento/magento2#3067] opened 2016-01-21 23:12 UTC
Hello-

Upgrade stalls on last step.

Contents of update_status.log:

[2016-01-21 12:31:04 EST] Job "maintenance_mode {"enable":true}" has been started
[2016-01-21 12:31:04 EST] Magento maintenance mode is enabled.
[2016-01-21 12:31:04 EST] Job "maintenance_mode {"enable":true}" has successfully completed
[2016-01-21 12:31:05 EST] Job "update {"components":[{"name":"magento/product-community-edition","version":"2.0.1"}]}" has been started
[2016-01-21 12:31:05 EST] Starting composer update...
[2016-01-21 12:31:05 EST] ./composer.json has been updated

**Comment by mazhalai** [comment] 2016-01-21 23:21
Closing since this is a duplicate of #3065 and possibly #3056

**Closed as completed by mazhalai** 2016-01-21 23:21 UTC

**Comment by mswaidan** [comment] 2016-01-21 23:34
@mazhalai I created a new issue since the error in the log was different than that shown in both #3065 and #3056 

That being said, for those of you that are getting the same error, the workaround presented in #3056 did allow me to install the update via composer, I think. I'm still getting the warning "Important: Install Magento Community Edition 2.0.1 for Security & Functional Updates – 1/20/2016" when I log in to admin, so not sure if the security patch has actually been applied.
