### ISSUE TITLE
Magento 2.0.4 url rewrite not working 

### ISSUE THREAD

**Issue by Yogesh7989** [magento/magento2#4356] opened 2016-04-30 06:22 UTC
Hello,

Magento 2.0.4 Url rewrite not working ?

How to remove all already placed custom url and re-create them is there same way like magento 1. I have get table **url_rewrite** which is may be working same way to **core_url_write**  magento 1 table ?

but if we truncate this table its automatic created by system ? because after truncated this table its not recreated and magento2 product and category page url structure has been changed like below for product

http://{domain}/catalog/product/view/id/1/s/joust-duffle-bag/category/4/

Is there any way we can resolve this issue ? 

there are many thread available which is reflected that magneto 2 url rewrite is not working, is there any perfect solution ?

this problem face after migration of project if it has custom url-key and .html extension  is removed from product page & category page
@magento-team  

Thanks

**Comment by piotrekkaminski** [comment] 2016-05-12 22:23
@Yogesh7989 Can you explain step by step how to reproduce this issue?

**Comment by Yogesh7989** [comment] 2016-05-13 07:08
Hello ,

 @piotrekkaminski  We have done following step,

I have installed magento 2.0.5 with sample database. i want to regenerate or update url key for all products as well category. i used method same as magento 1. truncate table of **url_rewrite** which is used in magento 2, after truncate this table magento is not generated url key path for products as well category. its gives system url like

**http://{domain}/catalog/product/view/id/1/s/joust-duffle-bag/category/4/**

Magento 2 remove core url rewrite from index management and generate run time but how it works ? we are not able to find that solution.

**Why we need to do above things.**

we have face issue in url rewrite mapping after migration from M1 version 1.7.0.2 & 1.9.2.2 to M2 version 2.0.2 & 2.0.4 & 2.0.5 , we have use migration tool 2.0.5 & 2.0.2 & done migration by CMD.
custom url is not working for all products & categories pages and its giving 404 error. we are not able to resolve that so we have try to regenerated it , truncate table **url_rewrite** and face problem same as above magento fresh installation.

Please let me know if you need more clarification.

Thanks

**Comment by andidhouse** [comment] 2016-05-13 16:11
Hi there,
same here. Our Urls when migrating from 1.7.0.2 to M2 2.0.2-5 are completely messed up.
Truncating the url_rewrite table in M2 then leads to system urls mentioned above.

So how can we regenerate this table to regenerate the new urls which are placed right in the categories in the backend by the way?

**Comment by dexterityzx** [comment] 2016-05-13 17:51
Hi, 
I got the same issue, but my reason for truncating the url_rewrite table is that we met some issue on product import and truncated the table was a working way to solve it.

**Comment by Yogesh7989** [comment] 2016-05-17 06:31
Hi ,
@piotrekkaminski is there any solution for this issue?

Thanks

**Comment by katmoon** [comment] 2016-05-17 07:42
Hi all,

Thanks for raising the question.
There's no such feature in M2 as it was in M1. I've created internal ticket `MAGETWO-52878` to process the issue.

Thanks,
Kateryna.

**Comment by Yogesh7989** [comment] 2016-05-17 07:54
Thanks @katmoon .

**Comment by katmoon** [comment] 2016-05-17 11:04
Hi @Yogesh7989 

That ability to auto-generate URL rewrites as in M1 is not planned for M2. That is it's better not to truncate url_rewrites table.

Which tool did you use for migration? It is the problem of the tool that it did not migrate url rewrites correctly.

Thanks,
Kateryna.

**Comment by andidhouse** [comment] 2016-05-17 11:25
@katmoon 
Many thanks four your answer.
We also have the same problem and using official data migration tool.

But there are also other cases where the urls need to be regenerated. For example we wrote a module to flatten the category urls (no main category in the subcategory url). This is a normal step for a lot of shops to have a url structure which is flat. The problem here is that in the backend there is no such setting and so you have to write a own module. And here is the problem again. The module can only affect new categories created - the old categories stay the same like before. And this is the problem: 

There is no way to regenerate the URL without the option to truncate the url_rewrite table at all. Or is there any?

So we face two problems regarding this:
1. the official migration tools messes up the urls
2. there is no way to "flatten" the category urls at all

Both keep us away from migrating to M2 at the moment which is really worst case to us.

**Comment by Yogesh7989** [comment] 2016-05-17 15:43
Hello  @katmoon ,

I have mention in above post.

**we have face issue in url rewrite mapping after migration from M1 version 1.7.0.2 & 1.9.2.2 to M2 version 2.0.2 & 2.0.4 & 2.0.5 , we have use migration tool 2.0.5 & 2.0.2 & done migration by CMD.**

Thanks
Yogesh

**Comment by Yogesh7989** [comment] 2016-05-23 11:50
Hello ,
@katmoon , @ilol , @piotrekkaminski  , @maksek , @yaronish 

Is there any solution for this issue we stuck this level in migration.

Thanks

**Comment by Yogesh7989** [comment] 2016-05-24 12:52
Hello ,

I have Find solution  in this way.

First check your affected rows with select query in url_rewrite

**SELECT 
   request_path,
   SUBSTRING(request_path, 1, CHAR_LENGTH(request_path) - 1) AS col_trimmed
FROM url_rewrite
WHERE request_path LIKE '%/'**

**Update affected row 
UPDATE `url_rewrite` SET `request_path` = SUBSTRING(request_path, 1, CHAR_LENGTH(request_path) - 1) WHERE request_path LIKE '%/'**

it is working fine for me.

**Comment by Tristan-N** [comment] 2016-06-28 15:03
@Yogesh7989 Thanks! Your solution works great!

**Comment by nmallepally** [comment] 2016-08-11 12:24
@Yogesh7989 I have imported my URLS from woo-commerce store into url_rewrite table on Magento 2.1v, the thing is all woo commerce store links have ?= parameters. Magento 2.1 does not redirect custom url with parameters ?, Is there any temporary solution?. [Issue](https://github.com/magento/magento2/issues/6105)

**Comment by thlassche** [comment] 2017-02-22 10:58
I developed a CLI command for this purposes, as a work around

**Comment by AgentGod** [comment] 2017-03-11 17:52
@Yogesh7989 Can you explain me how to execute your solution.
I am not an expert. Are they mysql commands?

**Comment by veloraven** [comment] 2017-06-19 15:36
Internal issue was closed as not a bug with a comment from PO that we don't want to have a separate indexer for URL rewrites in M2.
If you think such improvement should be done please submit it to Feature Requests and Improvements should now be submitted to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96))

**Closed as completed by veloraven** 2017-06-19 15:36 UTC
Labels: Issue: Ready for Work, bug report, Component: CatalogUrlRewrite

**Comment by thisfiore** [comment] 2017-07-13 16:04
@agentgod did you have find a solution?

**Comment by babyasishhira** [comment] 2017-09-10 13:45
Thanks @Yogesh7989 . Works perfect
