### ISSUE TITLE
Array to String conversion

### ISSUE THREAD

**Issue by Matt-OBell** [magento/magento2#7517] opened 2016-11-22 09:31 UTC
Notice: Array to string conversion in /var/www/Acme/vendor/magento/framework/Phrase.php on line 69
This occured on version 2.1.2 on php 7.

**Comment by Matt-OBell** [comment] 2016-11-22 09:45
This occurred as a result of third party module. thanks

**Comment by YevSent** [comment] 2016-11-22 16:04
@Matt-OBell , please, format this issue according to the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and an expected result.

Looks like similar to https://github.com/magento/magento2/issues/6215.

**Comment by vzabaznov** [comment] 2016-12-09 10:58
Hi @Matt-OBell , close this issue as we don't receive update for more than 2 weeks, please feel free to write here or reopen current / create new issue

**Closed as completed by vzabaznov** 2016-12-09 10:58 UTC
Labels: bug report, Progress: needs update
