### ISSUE TITLE
Product price of 99,999,999.99 shown as 100,000,000.00

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#11489] opened 2017-10-16 14:57 UTC
### Preconditions
1.  PHP 7.1.9
PHP_INT_MAX = 9223372036854775807
2. MySQL 5.6.37
3. Magento 1.0.0 B2B (=2.2.0 B2B)
4. tested it on Magento CE 2.1.7 as well - same behaviour

### Steps to reproduce

1. Create a product via PHP script, set the price to PHP_INT_MAX
(PHP_INT_MAX is of course bigger than the value that can be stored in the db, so I do not consider step 2 as a bug, storing the max value of the db for `decimal(12,4)` is fine)
2. Price is stored as 99999999.9999 in the database

3. Open product in frontend, price is shown as  €100,000,000.00 in frontend and adminhtml

### Expected result

1. Price is shown as 99,999,999.99 in frontend and adminhtml

### Actual result

1. Open product in frontend, price is shown as  €100,000,000.00 in frontend and adminhtml

![bildschirmfoto 2017-10-16 um 17 03 54](https://user-images.githubusercontent.com/1798594/31618995-ba8b4554-b293-11e7-99d8-2511649e5b5e.png)
![bildschirmfoto 2017-10-16 um 16 46 54](https://user-images.githubusercontent.com/1798594/31618664-d5ebc0b8-b292-11e7-97c6-d27fe57e009e.png)
![bildschirmfoto 2017-10-16 um 16 52 45](https://user-images.githubusercontent.com/1798594/31618665-d6241d28-b292-11e7-9ae0-30c474f5763b.png)

**Comment by orlangur** [comment] 2017-10-16 15:30
`.9999` I don't think Magento supports four decimals out of the box. Looks like a duplicate of https://github.com/magento/magento2/issues/10532 to me.

**Comment by avoelkl** [comment] 2017-10-16 15:54
Oh dear... I changed the price rounding to round(X, 4) so often that i keep forgetting it's using round(X, 2) per default...

**Closed as completed** 2017-10-16 16:00 UTC
Labels: Issue: Format is valid
