### ISSUE TITLE
[GraphQl] If all option required and 1 bundle item is OUT_OF_STOCK then it should OUT_OF_STOCK

### ISSUE THREAD

**Issue by haunguyen1989** [magento/magento2#30192] opened 2020-09-25 10:33 UTC
### Preconditions (*)

1. Magento 2.4 
2. Elastic search 7.6
### Steps to reproduce (*)

1. 2 website and enable Store Code to Urls: **Yes**. Site Main Website and VN Website
2. Display out of stock product: Yes
3. Create new stock and assign new 2 source(Ha Noi, Ho Chi Minh) to site VN Website
4. Create 2 simple product. Product A out of sotck for source Ha Noi, Product B in-stock
5. Create bundle product(sku: bundle01) and add **new 2 option check all required**. Option 1: add product A, option 2: add product B. Save
6. Reindex all
7. Check graphQL query for sku: bundle01:
`query{
products(filter: {sku: {eq: "bundle01"} }){
    items {
      id
      sku
      stock_status
      name
      activity
      color
     related_products {
      name
      sku
    }
    }
    total_count
  }
}`
### Expected result (*)

1. "stock_status": "OUT_OF_STOCK",
2. Result: `{
  "data": {
    "products": {
      "items": [
        {
          "id": 2047,
          "sku": "bundle01",
          "stock_status": "OUT_OF_STOCK",
          "name": "bundle01",
          "activity": null,
          "color": null,
          "related_products": []
        }
      ],
      "total_count": 1
    }
  }
}`

### Actual result (*)

1.  "stock_status": "IN_STOCK"
2. `{
  "data": {
    "products": {
      "items": [
        {
          "id": 2047,
          "sku": "bundle01",
          "stock_status": "IN_STOCK",
          "name": "bundle01",
          "activity": null,
          "color": null,
          "related_products": []
        }
      ],
      "total_count": 1
    }
  }
}`
![Screenshot from 2020-09-25 17-31-47](https://user-images.githubusercontent.com/44774202/94257217-2964db00-ff55-11ea-8187-7f3ec91e4fef.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by haunguyen1989** [comment] 2021-01-29 06:41
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed after 14 days if no further activity occurs. Is this issue still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? Thank you for your contributions!

We are still facing this issue at version 2.4.1.
If there is any feedback about it, thank you

**Comment by engcom-Bravo** [comment] 2021-02-03 11:32
Hello @haunguyen1989 

Thank you for your report

We have rechecked the reported issue with the provided steps.
- Product A - Out of Stock
- Product B - In Stock
- Bundle product containing two options, Option 1 - Product A; Option 2 - Product B
![bundle_03](https://user-images.githubusercontent.com/51680745/106740795-8e2af300-6623-11eb-98fc-76adb9702806.png)

The GraphQL query returns zero records
![graph_query_bundle_03](https://user-images.githubusercontent.com/51680745/106740997-d0543480-6623-11eb-9358-f5a05de9d2d1.png)

Seems like the issue is not reproducible on the latest 2.4-develop. We are closing this issue. If our steps are incorrect and you are able to reproduce the issue on the latest 2.4-develop, please feel free to provide more info and reopen.

Thank you

**Closed as completed by engcom-Bravo** 2021-02-03 11:32 UTC
Labels: Component: GraphQL, Issue: ready for confirmation, not-confirmed, Reported on 2.4.0

**Comment by haunguyen1989** [comment] 2021-02-04 02:48
> Hello @haunguyen1989
> 
> Thank you for your report
> 
> We have rechecked the reported issue with the provided steps.
> 
> * Product A - Out of Stock
> * Product B - In Stock
> * Bundle product containing two options, Option 1 - Product A; Option 2 - Product B
>   ![bundle_03](https://user-images.githubusercontent.com/51680745/106740795-8e2af300-6623-11eb-98fc-76adb9702806.png)
> 
> The GraphQL query returns zero records
> ![graph_query_bundle_03](https://user-images.githubusercontent.com/51680745/106740997-d0543480-6623-11eb-9358-f5a05de9d2d1.png)
> 
> Seems like the issue is not reproducible on the latest 2.4-develop. We are closing this issue. If our steps are incorrect and you are able to reproduce the issue on the latest 2.4-develop, please feel free to provide more info and reopen.
> 
> Thank you

Do you **Enable Display out of stock product**: Yes ?
