### ISSUE TITLE
Embeded videos on Product Pages not appearing on mobile devices

### ISSUE THREAD

**Issue by bettymch** [magento/magento2#34561] opened 2021-11-08 02:43 UTC
### Preconditions (*)

1. 2.2.2
2.

### Steps to reproduce (*)

1. All embedded videos on product pages across our entire website are not visible to users when viewing the website from their mobile devices, iPhone or android.
2.

### Expected result (*)

1. We'd like the embedded videos to display within the mobile version's product pages.
2. 

### Actual result (*)

1. There is simply no embedded videos appearing in the website's mobile version on product pages
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Hotel** [comment] 2021-11-08 07:54
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2021-11-08 08:11
Hello @bettymch,

We have tried to reproduce this issue on Magento 2.4-develop, but we are unable to reproduce this issue. We have tried it for the Vimeo video (https://vimeo.com/253989945) and it is working as expected.

Please have a look at the below screenshot for reference:

![WhatsApp Image 2021-11-08 at 1 37 16 PM](https://user-images.githubusercontent.com/51681618/140706184-a73d8e30-9123-4a7b-94fb-f8a423f2c6d4.jpeg)

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-11-23 07:51
Dear @bettymch,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-11-23 07:51 UTC
Labels: Issue: needs update, Reported on 2.2.x
