### ISSUE TITLE
Region doesn't updates after changing country and leaving region select unselected

### ISSUE THREAD

**Issue by Stepa4man** [magento/magento2#23460] opened 2019-06-28 11:25 UTC
### Preconditions
1. Create user
2. Create user address with country "_United States_" and region "_Alabama_"

### Steps to reproduce
1. Go to created customer page
2. Go to address customer address tab 
3. Hit edit action for the created address at the addresses grid
4. Change the country to France
5. Don't choose any region
6. Save address
7. Run in browser console `jQuery('[data-index="region_id_input"]').show()` to display hidden State/Province field (second field with the same label)

### Expected result (*)
1. Second State/Province input is empty

### Actual result (*)
1. Second State/Province input has value Alabama (which is saved to db after hitting Save button)

### Additional
The same issue is applicable for source edit page because the main point here is Region UI component which doesn't empty hidden region input with Region label for the described case.

###Env
Mac OS
Valet+ (PHP7.1, NGINX, MYSQL)
Magento 2.3-develop branch

**Comment by Stepa4man** [comment] 2019-06-28 11:31
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-28 11:31
Hi @Stepa4man. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-06-28 11:32
Hi @Stepa4man, here is your [Magento instance](https://i-23460-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23460-2-2-develop.instances.magento-community.engineering/admin](https://i-23460-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Stepa4man** [comment] 2019-06-28 11:36
@magento give me 2.1-develop instance

**Comment by magento-engcom-team** [comment] 2019-06-28 11:37
Hi @Stepa4man. Thank you for your request.
Unfortunately, I can only deploy instances for `2.2` and `2.3` release lines

**Comment by magento-engcom-team** [comment] 2019-06-28 11:38
:white_check_mark: Confirmed by @Stepa4man 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-17873`, `MC-17874` were created

**Issue Available**: @Stepa4man, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sunilit42** [comment] 2019-07-02 06:34
@Stepa4man  are you still working?

**Comment by Stepa4man** [comment] 2019-07-02 07:14
@sunilit42 Yes.

**Comment by VladimirZaets** [comment] 2019-07-09 21:38
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-09 21:38
Hi @VladimirZaets. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-09 21:39
Hi @VladimirZaets, here is your [Magento instance](https://i-23460-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23460-2-3-develop.instances.magento-community.engineering/admin](https://i-23460-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hostep** [comment] 2019-08-19 20:46
Good to see this issue report.

We recently investigated a problem on a shop where certain customers couldn't get through the checkout. And I think it might have been caused by this bug.
The Magento checkout doesn't seem to like it when you have a region stored in the database for a different country than the country from your address. Then you get some weird error message in the checkout preventing you from proceeding.
On that particular shop, only 2 customers out of ~6000 were affected luckily.

Would be nice to see this bug fixed.

A feature to search for customers in the database having this particular problem is probably out of scope for a bugfix for this issue, but would still be a nice feature to have in the backend of Magento (just an idea).

**Comment by LucasCalazans** [comment] 2019-09-14 18:12
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-09-14 18:12
Hi @LucasCalazans. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by LucasCalazans** [comment] 2019-09-14 18:12
I'm working on this issue

#MM19BR

**Comment by magento-engcom-team** [comment] 2019-09-14 18:13
Hi @LucasCalazans, here is your [Magento instance](https://i-23460-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23460-2-3-develop.instances.magento-community.engineering/admin](https://i-23460-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-10-03 12:58
Hi @Stepa4man. Thank you for your report. 
The issue has been fixed in magento/magento2#24597 by @LucasCalazans in 2.3-develop branch
Related commit(s):
 - [849a26752d0838c98f66a2bd3a179f14fe68a17e](https://github.com/magento/magento2/commit/849a26752d0838c98f66a2bd3a179f14fe68a17e)
 - [4122c40e193813e568b44953d6e12392cfed27cc](https://github.com/magento/magento2/commit/4122c40e193813e568b44953d6e12392cfed27cc)
 - [140d59162047b25b9d413e3e597e383b41090616](https://github.com/magento/magento2/commit/140d59162047b25b9d413e3e597e383b41090616)
 - [5d440c5f5acb7092d6ca27212d249b313aa700ce](https://github.com/magento/magento2/commit/5d440c5f5acb7092d6ca27212d249b313aa700ce)
 - [f51fd0b5f105966aa8bed720581e89c9e140424d](https://github.com/magento/magento2/commit/f51fd0b5f105966aa8bed720581e89c9e140424d)
 - [c381ae817a62bad16f32c07ed5e098bb4a8c4ae7](https://github.com/magento/magento2/commit/c381ae817a62bad16f32c07ed5e098bb4a8c4ae7)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-10-03 12:58 UTC
Labels: bug report, Component: Customer, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, partners-contribution, Partner: TechDivision, Event: mm19br
