### ISSUE TITLE
Cart item not updating while maximum quantity allowed in cart is set to 1

### ISSUE THREAD

**Issue by jsutariya** [magento/magento2#31504] opened 2021-01-04 13:03 UTC
### Preconditions (*)

1. Magento version 2.4.1
2. PHP 7.4

### Steps to reproduce (*)

1. Create a simple product in admin panel with customizable options
2. Set Maximum Qty Allowed in Shopping Cart value to 1 for the product
3. Add product to cart with selecting any customizable option.
4. Product added to cart successfully
5. Click on edit item in cart page for the product
6. Change cutomizable option for the product (keep quantity 1)
7. Click on "Update Item" button

### Expected result (*)

1. It should update existing cart item with selected custom option value

### Actual result (*)

1. It throws error message "The requested qty exceeds the maximum qty allowed in shopping cart"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-01-04 14:42
Hello @jsutariya 

Thank you for your report. 

We have rechecked the reported issue on clean Magento 2.4-develop and the issue is not reproducible. The product in the Shopping cart is successfully updated
![Shopping cart](https://user-images.githubusercontent.com/51680745/103545802-bf8c9380-4eaa-11eb-913b-90637a288b25.png)

However, the issue is reproducible on Magento 2.4.1 and on Magento 2.4-develop installed together with the [Inventory](https://github.com/magento/inventory) modules

Steps to reproduce
1. Install Magento 2.4-develop + Inventory
2. Set Maximum Qty Allowed in Shopping Cart value to 1in _Stores -Configuration - Catalog - Inventory - Product Stock Options_
![qty_max_1](https://user-images.githubusercontent.com/51680745/103546078-201bd080-4eab-11eb-80e4-868b108b998b.png)
3. Create a Simple product with _Customizable option_ Text Area for example
4. Add product to cart with selecting the customizable option.
5. Click on edit item in cart page for the product
6 Change cutomizable option for the product (keep quantity 1)
7. Click on "Update Item" button
![msi_repro](https://user-images.githubusercontent.com/51680745/103546356-86085800-4eab-11eb-97ba-5a380affd90e.gif)

We are closing this issue in this repository. Please, open a similar issue in https://github.com/magento/inventory/issues repository.

Thank you

**Closed as completed by engcom-Bravo** 2021-01-04 14:42 UTC
Labels: Issue: ready for confirmation, not-confirmed

**Comment by jbclaudio** [comment] 2023-10-16 09:41
I can confirm that this issue still exists on Magento 2.4.6-p3
