### ISSUE TITLE
Magento 2.4.4 x MariaDB 10.4 - Row size too large 

### ISSUE THREAD

**Issue by Axel29** [magento/magento2#35399] opened 2022-04-28 16:52 UTC
### Preconditions
1. Magento 2.4.4 upgraded from 2.3.x
2. MariaDB 10.4
3. Database with lots of orders

### Steps to reproduce
1. Run the `php bin/magento setup:upgrade` command after upgrading to Magento 2.4.4

### Expected result
1. The command runs properly

### Actual result
1. The upgrade fails with the following error:

```bash
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs, query was: ALTER TABLE `sales_order` MODIFY COLUMN `x_forwarded_for` varchar(255) NULL  COMMENT "X Forwarded For"
```

It seems like changing the ROW_FORMAT of the tables to "DYNAMIC" fixes the issue.
I found this solution on https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/#solving-the-problem and tried it on my "sales_order" table, which worked, but now I'm getting the same error on an other table but without any detail:

```bash
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```

It seems to me that Magento should change every table's ROW_FORMAT to "DYNAMIC" in order to work with MariaDB 10.4 properly.

---

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2022-05-10 07:20
Hello @Axel29,

Thanks for the report!

We have tried to reproduce the issue by upgrading Magento from 2.3.7-P2 to 2.4.4, but for us, the issue is not reproducible for us. Please have a look at the below screenshots for reference:
### Magento 2.3.7-P2 with 100 orders:
![2 3 7-p2](https://user-images.githubusercontent.com/51681618/167571507-0d5d3d9c-6b3f-4546-9e98-7039026334a2.png)

### Magento 2.4.4 after upgrade
![AfterUpgrade](https://user-images.githubusercontent.com/51681618/167571551-e069ad40-8440-4378-884f-1ac3dfe8523c.png)

### Ran `bin/magento setup:upgrade` after upgradation
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/51681618/167571717-ec7c8735-e612-4792-ab76-93dce3c1a26b.png">

Please let us know in case we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2022-05-24 06:44
Dear @Axel29,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-05-24 06:44 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.4
