### ISSUE TITLE
(Custom) price attributes for website scope were only saved via API, if a value for this attribute and scope already exists or no other attribute is set for the scope

### ISSUE THREAD

**Issue by attheCube** [magento/magento2#34971] opened 2022-01-14 08:08 UTC
### Preconditions (*)

1. Magento 2.4.3-p1
2. Multiple websites
3. Price scope: website

### Steps to reproduce (*)

1. Create 2 websites and according store views
2. Add a product in global scope with all needed Attributes
3. Set a few Attributes in a specific store scope via API. (Request example below)
4. Add a new price-attribute called "test_price".
5. Set test_price via API for the same store scope as in point 3 above. (Request example below)

#### Request examples:
**Step 3: Set data for special store scope**
Call: {{base_url}}/rest/[store_code]/V1/products
```
{
    "product": {
        "status": 1,
        "name": "Test 1 2 333  111111",
        "price": 125.12,
        "custom_attributes": [
            {
                "attribute_code": "short_description",
                "value": "abcdefg ggg"
            }
        ],
        "sku": "Test1"
    }
}
```

** Step 4: Set test_price for the same store scope**
Call: {{base_url}}/rest/[store_code]/V1/products
```
{
    "product": {
        "status": 1,
        "name": "Test 1 2 333  111111",
        "price": 125.12,
        "custom_attributes": [
            {
                "attribute_code": "short_description",
                "value": "abcdefg ggg"
            },
            {
                "attribute_code": "test_price",
                "value": 101.11
            }
        ],
        "sku": "Test1"
    }
}
```

### Expected result (*)

1. test price will be set for website scope of chosen store => 101.11

### Actual result (*)

1. test price is not set for website scope of chosen store. 
2. The database shows no entry for test_price in website scope

It seems to be an issue for each attribute based on price logic.
Values may only be written in database, if there are no other attribute values set for current website / websites default store.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by attheCube** [comment] 2022-01-14 08:12
Seems to be related to https://github.com/magento/magento2/pull/34665 but the solution there is not working properly for this  case.
We confirmed this issue existing also in vanilla Magento open Source 2.4.3 and Commerce 2.4.4-beta3 .

**Comment by engcom-Echo** [comment] 2022-01-17 12:52
Hi @attheCube,

Thank you for reporting the issue.

I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it.

The special price setup and its API is working as expected. Could you please provide more details on steps 3, 4, 5 and the provided request sample is not working so please provide the exact request which is causing the issue ?

Thanks

**Comment by attheCube** [comment] 2022-01-17 15:56
Hi @engcom-Echo ,

I adjusted the description.
Please check again.

Thank you.

**Comment by engcom-Hotel** [comment] 2022-01-21 13:06
Hi @attheCube,
I have tried this issue on the fresh installation (Magento 2.4-dev/2.4.3-P1) but I am not able to reproduce it.

It seems you are using the wrong rest API to set the special price. Use [this](https://devdocs.magento.com/guides/v2.4/rest/modules/catalog-pricing.html#set-special-prices) API request to set the special price.

Hope it helps. Let me know if you are still facing this issue or provide more relevant details if you think it is a Magento core issue.

Thanks.

**Comment by attheCube** [comment] 2022-01-26 16:21
Hi @engcom-Hotel ,
I updated the issue description.
The problem does not rely on using the wrong API-endpoint.

If you create an own price attribute, you need to use the endpoint described above.

Please check again.

Thanks a lot.

**Comment by attheCube** [comment] 2022-02-04 06:59
Here, you'll find a Screencast how the issue will be reproduced:
https://www.gothicgirly.de/rgtrhzthrsgfsee4t5454zhrtz/2022-02-03-18-09-26.mkv

**Comment by engcom-Lima** [comment] 2022-02-10 08:56
Hi @attheCube,
I tried reproducing the issue on the latest **2.4-develop** branch following all the steps mentioned in the description as well as by referring the video, however the issue is **not reproducible** on **2.4-develop** branch.

Steps followed to reproduce the issue:

1. Install fresh Magento 2.4-develop instance
2. Login to admin panel and add a new **Website, Store and Store View**. So in total I have 2 websites **(Main Website, Second Website)** with their respective stores and store views.
![image](https://user-images.githubusercontent.com/60198022/153366274-ed710d06-6e2c-46a7-9a1f-559cff08a06a.png)
3. Change price scope from **Global** to **Website**. 
**Stores->Configuration->Catalog->Catalog->Price**
![image](https://user-images.githubusercontent.com/60198022/153367032-bb2d1c3b-89bd-418e-bb36-655b5c7bfe7e.png)
4. Create a custom price attribute **testattr2** and assign it to an attribute set, it will be visible on Product Edit Page
5. Assign a value to testattr2 **eg: 555** and save the product

![image](https://user-images.githubusercontent.com/60198022/153367597-c76453bb-5711-41a0-801e-c0a886704b1f.png)

6. Set a few Attributes in a specific store scope via API. In my case I updated **name**, **short_description**, **price** for second store view **second_store_view**
<img width="985" alt="Screenshot 2022-02-10 at 2 03 25 PM" src="https://user-images.githubusercontent.com/60198022/153368452-4606a558-ad95-44db-8687-38e2698a6f9e.png">

**Notice**: In response we get the **custom testattr2** value as expected i.e **555**
Also the records in database are expected

![image](https://user-images.githubusercontent.com/60198022/153369330-64e41b8f-2b75-42ea-bc77-c674c3d4fd4a.png)

6. Now through the same endpoint **{{base_url}}/rest/[store_code]/V1/products** update our custom attribute **testattr2** for same store view. I updated with value **300**
<img width="985" alt="Screenshot 2022-02-10 at 2 10 52 PM" src="https://user-images.githubusercontent.com/60198022/153369750-050de8eb-b6da-4f95-b3ba-673096159558.png">

**Notice:** As you can see in response we do get the updated value **i.e. 300**, Also the changes are reflected in the DB as well as in the admin panel

**Change in the DB**
![image](https://user-images.githubusercontent.com/60198022/153370299-cda25729-ef0e-4acd-acee-58b7cf7895f8.png)

**Change in the Admin Panel**
![image](https://user-images.githubusercontent.com/60198022/153370945-21f7cad5-b713-4160-841e-ad9a429d4460.png)

Thank you for your crystal clear description as well as the reference video however the issue is **not reproducible on 2.4-develop**.
Can you please try reproducing this on latest 2.4-develop instance or incase if I have missed any steps then please let me know, I will reverify it again.

Thanks!

**Comment by engcom-Hotel** [comment] 2022-02-25 08:19
Dear @attheCube,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-25 08:19 UTC
Labels: Issue: needs update

**Comment by Detzler** [comment] 2023-01-12 16:35
@engcom-Hotel @attheCube 

I can confirm this bug also for the default "price" attribute. It appears when catalog prices are set to website-scope instead to global in the catalog settings.

Now we are workarounding by using the /products/base-price rest endpoint.

Need to be fixes asap.

**Comment by engcom-Hotel** [comment] 2023-01-13 08:41
Hello @Detzler,

Thanks for the reply!

We have closed this issue as we do not get any response from the reporter for 14 days. But we still reopen and work on it. 

So I request you to please go through with the [comment](https://github.com/magento/magento2/issues/34971#issuecomment-1034655634), made by us and let us know if any is missed by us in order to reproduce this issue.

Thanks
