### ISSUE TITLE
Rating error

### ISSUE THREAD

**Issue by bycollar** [magento/magento2#4455] opened 2016-05-10 21:10 UTC
Hello all
I can not set the ratings , need help.
## Steps to reproduce
1. Go to Magento admin panel - Stores - Rating
2. Press Add new rating
3. Set Default Value
4. Set Visibility
5. Check box Is Active
6. Save rating
## Expected result
1. The new rating is stored and visible on the product page
## Actual result
1. Error message appears: "Rolled back transaction has not been completed correctly.".
   ![image](https://cloud.githubusercontent.com/assets/19294171/15162604/84aa65f6-170c-11e6-9d66-3a4a10ebaed9.png)

**Comment by bycollar** [comment] 2016-05-11 18:44
Any body help me?

**Comment by maksek** [comment] 2016-05-11 18:48
@bycollar which version you are using? Do you have extra modules installed?

**Comment by bycollar** [comment] 2016-05-11 19:04
O, sorry, latest version, Magento ver. 2.0.5

I instalil latest version - this is not an error . And on the current site error occurred since the previous update and after the latter update has not disappeared

**Comment by maksek** [comment] 2016-05-11 19:15
@bycollar, you are saying - you do not have the error on clean 2.0.5, but you had it on older version, but after upgrade the error still reproducible?

**Comment by bycollar** [comment] 2016-05-11 19:47
Yes

**Comment by maksek** [comment] 2016-05-12 02:05
I was not able to reproduce issue you mentioned, also i didn't see the issue in 2.0.3, and after upgrade to 2.0.5 i didn't see any issue as well. It may be issue with your original installation. Btw which version did you use originally and how you did upgrade to 2.0.5?

**Comment by bycollar** [comment] 2016-05-12 10:01
I deleted all ratings and added new. On visibility set I have this DB exception:
[2016-05-12 09:54:36] main.CRITICAL: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magen
to-prod`.`rating_store`, CONSTRAINT `RATING_STORE_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`) ON DELETE CASCADE)' in /var/hosting/collar/www/magento/collar/vendor/m
agento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/hosting/collar/www/magento/collar/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/hosting/collar/www/magento/collar/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/hosting/collar/www/magento/collar/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/hosting/collar/www/magento/collar/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/hosting/collar/www/magento/collar/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ra...', Array)
#5 /var/hosting/collar/www/magento/collar/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO`ra...', Array)
#6 /var/hosting/collar/www/magento/collar/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `ra...', Array)
#7 /var/hosting/collar/www/magento/collar/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1915): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO`ra...', Array)
#8 /var/hosting/collar/www/magento/collar/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(1879): Magento\Framework\DB\Adapter\Pdo\Mysql->insertArray('rating_store', Array, Array)
#9 /var/hosting/collar/www/magento/collar/vendor/magento/module-review/Model/ResourceModel/Rating.php(259): Magento\Framework\DB\Adapter\Pdo\Mysql->insertMultiple('rating_store', Array)
#10 /var/hosting/collar/www/magento/collar/vendor/magento/module-review/Model/ResourceModel/Rating.php(219): Magento\Review\Model\ResourceModel\Rating->insertRatingData('rating_store', Array)
#11 /var/hosting/collar/www/magento/collar/vendor/magento/module-review/Model/ResourceModel/Rating.php(171): Magento\Review\Model\ResourceModel\Rating->processRatingStores(Object(Magento\Review\Model\Ra
ting))

**Comment by Zaitsev** [comment] 2016-05-12 10:26
posted data for error above::
rating_code:asdfasdf
rating_codes[3]:asdf
rating_codes[6]:asdf
rating_codes[4]:asdf
option_title[36]:1
option_title[37]:2
option_title[38]:3
option_title[39]:4
option_title[40]:5
stores[]:3
stores[]:4
stores[]:6
is_active:1
position:1

Stores table:
![image](https://cloud.githubusercontent.com/assets/127843/15211699/6d155cae-1845-11e6-9550-6b514ba1496f.png)

**Comment by maksek** [comment] 2016-05-12 23:17
@bycollar, we can't reproduce the issue on any version. It is issue with your local instance. 
I am closing the ticket, since you confirmed it works on clean installation. 
If you able to reproduce the issues and confirm it on clean installations, feel free to comment with exact steps to reproduce.

**Closed as completed by maksek** 2016-05-12 23:17 UTC

**Comment by rgpjones** [comment] 2016-06-29 08:19
We were also getting this issue.

It's fixed by this commit: https://github.com/magento/magento2/commit/de90990008b75992eb59b9e8c2c6579f6a2528c2#diff-417e3ceef95a6853116a22318a928c2bL216
