### ISSUE TITLE
magento amdin is not working 

### ISSUE THREAD

**Issue by durgagupta** [magento/magento2#8656] opened 2017-02-22 21:11 UTC
### Preconditions

Requested path '_cache/merged/265795891b8eeb9469152455a81118ae.js' is wrong.
#0 /var/www/metrotarkari.com/vendor/magento/framework/App/StaticResource.php(91): Magento\Framework\App\StaticResource->parsePath('_cache/merged/2...')
#1 /var/www/metrotarkari.com/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch()
#2 /var/www/metrotarkari.com/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#3 {main}

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by orlangur** [comment] 2017-02-23 08:18
Try to clean everything and redeploy all static content. Looks like configuration refers to outdated JS asset.

**Comment by pmjcreations** [comment] 2017-02-24 13:08
I am new to Magento. Could you please tell me how do I clean everything and redeploy all static content?
I am using cPanel. I have SSH access as well.

**Comment by orlangur** [comment] 2017-02-24 13:28
Here you are: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli-subcommands-static-view.html

By "everything" I mean `var/*` and `pub/static/*` removal (in `develop` branch `var/generation` is now placed in `generated` folder, I'm not aware of other changes).

Sometimes it is also helpful to remove `vendor/*` and do `composer install` again.

**Comment by pmjcreations** [comment] 2017-02-24 14:50
Thank you @orlangur 

I found these many missing files while doing `composer install`


```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magento/framework 100.1.5 -> satisfiable by magento/framework[100.1.5].
    - magento/framework 100.1.5 requires ext-iconv * -> the requested PHP extension iconv is missing from your system.
  Problem 2
    - Installation request for magento/magento2-base 2.1.5 -> satisfiable by magento/magento2-base[2.1.5].
    - magento/magento2-base 2.1.5 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 3
    - Installation request for magento/product-community-edition 2.1.5 -> satisfiable by magento/product-community-edition[2.1.5].
    - magento/product-community-edition 2.1.5 requires ext-iconv * -> the requested PHP extension iconv is missing from your system.
  Problem 4
    - Installation request for pelago/emogrifier v0.1.1 -> satisfiable by pelago/emogrifier[v0.1.1].
    - pelago/emogrifier v0.1.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 5
    - magento/framework 100.1.5 requires ext-iconv * -> the requested PHP extension iconv is missing from your system.
    - magento/theme-frontend-luma 100.1.4 requires magento/framework 100.1.* -> satisfiable by magento/framework[100.1.5].
    - Installation request for magento/theme-frontend-luma 100.1.4 -> satisfiable by magento/theme-frontend-luma[100.1.4].


```

**Comment by orlangur** [comment] 2017-02-24 15:08
Please check out [Installation Guide](http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html).

From what I see from `composer` output you need to install missing PHP extensions: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/prereq-overview.html#php

**Comment by pmjcreations** [comment] 2017-02-24 17:24
Thank you @orlangur 

I have enabled all required extensions, and now the storefront and admin panel is woking.
Based on my observation, the cause was just missing of these extensions (in my case), I didn't clean cache and other things.

**Comment by orlangur** [comment] 2017-02-24 19:00
Glad to hear you managed to fix it)

**Comment by veloraven** [comment] 2017-06-30 07:15
@durgagupta is this issue still actual?
If it is, please provide the used Magento version and if it was clear install or some upgrade.
If it is not, please close the issue.

**Closed as completed** 2017-09-03 11:06 UTC
Labels: Progress: needs update
