### ISSUE TITLE
New Shipping Address is not saving on customer address book on checkout order

### ISSUE THREAD

**Issue by viral8421** [magento/magento2#35132] opened 2022-02-23 13:55 UTC
### Preconditions (*)

1. Magento 2.4.3
2. You must register as a customer and have at least one address saved on the address book.

### Steps to reproduce (*)

1. Login as a customer with at least one saved address. 
2. Add a product to cart
3. Go to checkout
4. Click on Add new address while adding address please check **Save in address book** and click on ship here button
5. Select any shipping method click next.
6. Select Any payment method check **My billing and shipping address are the same** and place order.

### Expected result (*)

1. order is placed successfully after that we should be able to see the new address should be saved on the address book.

### Actual result (*)

1. order is placed but the new address is not available on the address book. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by viral8421** [comment] 2022-02-23 13:56
@magento give me 2.4-develop instance

**Comment by viral8421** [comment] 2022-02-23 14:13
@magento give me 2.4-develop instance

**Comment by knsalim** [comment] 2022-02-23 14:15
@magento give me 2.4.3-p1 instance

**Comment by knsalim** [comment] 2022-02-23 14:22
@magento give me 2.4.3 instance

**Comment by engcom-November** [comment] 2022-02-24 08:14
Hi@ viral8421

Thank you for reporting the issue.

We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

Steps performed:
1:Login as a customer with at least one saved address.
2:Add a product to cart
3:Go to checkout
4:Click on Add new address while adding address please check Save in address book and click on ship here button
5:Select any shipping method click next.
6:Select Any payment method check My billing and shipping address are the same and place order.


Result:

order is placed successfully after that we should be able to see the new address should be saved on the address book.
as shown in screenshot

![image](https://user-images.githubusercontent.com/60198231/155484768-1ce8f506-18b5-4fff-b66d-469955e320d5.png)
![image](https://user-images.githubusercontent.com/60198231/155484812-601dc81d-9bc8-469f-89b0-00e38d4559b3.png)


Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.


Thanks

**Comment by knsalim** [comment] 2022-02-24 09:30
@magento give me 2.4.3-p1 instance

**Comment by knsalim** [comment] 2022-02-24 09:32
@magento give me 2.4-develop instance

**Comment by viral8421** [comment] 2022-02-24 10:11
hi @engcom-November,

Yes, I've also tried on the Magento 2.4-develop branch but the issue is not reproducible.

But it seems that it will not work on the Magento2.4.3-p1 Enterprise Edition.

**Comment by knsalim** [comment] 2022-02-24 10:16
Hi @engcom-November 
I have tried the same in magento 2.4.3-p1  enterprise edition I am able to reproduce the issues . I have attached the screen cast for your reference 

https://user-images.githubusercontent.com/54523613/155504948-ae5bddb7-2b5a-4097-9ec7-7c2fb6d25c56.mp4

**Comment by engcom-November** [comment] 2022-02-25 10:58
Hi @viral8421

We verified the issue on Magento 2.4-develop branch with enterprise edition modules installed but not able to reproduce the issue. Its recommended to verify the issues on Magento 2.4-develop branch as it is having latest code base. We are closing this issue as this is not reproducible on 2.4-develop branch.

Thanks

**Closed as completed by engcom-November** 2022-02-25 10:58 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3

**Comment by DarekTw** [comment] 2022-03-25 14:10
Hi @engcom-November 

I can confirm that this problem only occurs on Magento Entrprice, I am currently using version 2.4.3-p1.

The code responsible for this is the plugin `vendor/magento/module-checkout-staging/Plugin/PaymentInformationManagementPlugin.php` and the `beforeSavePaymentInformationAndPlaceOrder` method that call `checkIfShippingNullOrNotSameAsBillingAddress`.

This plugin is responsible for setting `true` to the shipping address attribute `same_as_billing` in this scenario.

This checkout-staging module only exists in the enterprise version.

I believe this is a logical error, in fact the billing address is the same as the shipping address when you check the box **My billing address and shipping address are the same**, -> but the **shipping** address is displayed in the last checkout step <- and the user believe it should be saved if he wants to save it.
This is not done because the addresses are the same.

Check the `_prepareCustomerQuote` function in the `vendor/magento/module-quote/Model/QuoteManagement.php` file and this code snippet, if `$shipping->getSameAsBilling()` is true the shipping address will not be saved.

```
        if ($shipping && !$shipping->getSameAsBilling()
            && (!$shipping->getCustomerId() || $shipping->getSaveInAddressBook())
        ) {
```

**Comment by sonnnsmartosc** [comment] 2022-07-14 03:05
486798798

**Comment by dasithaaligent** [comment] 2022-08-12 06:50
As I found you will need to apply this patch to resolve this issue **MDVA-42855 - Fixes the issue where new customer address is not saved** and it is related to the mentioned plugin - **vendor/magento/module-checkout-staging/Plugin/PaymentInformationManagementPlugin.php**

You can find it in **vendor/magento/quality-patches/patches/commerce/MDVA-42855_2.4.3-p1.patch** and use either **magento-patches** or **ece-patches** tools based on your codebase.

Patch file: [MDVA-42855_2.4.3-p1.zip](https://github.com/magento/magento2/files/9314277/MDVA-42855_2.4.3-p1.zip)

**Comment by dylanngo95** [comment] 2022-09-08 07:29
@dasithaaligent Thank you so much, This patch work on Magento 2.4.4 EE
:dancers:
