### ISSUE TITLE
Issue when edit a category

### ISSUE THREAD

**Issue by zivendesign** [magento/magento2#1751] opened 2015-08-27 08:06 UTC
When I'm Added new category done. But I'm back to edit something. It has been showing the message.

{"data":[{"text":"Default Category (1)","id":"2","store":0,"path":"1\/2","cls":"folder active-category","allowDrop":true,"allowDrag":false,"children":[{"text":"Men (3)","id":"3","store":0,"path":"1\/2\/3","cls":"folder active-category","allowDrop":true,"allowDrag":true},{"text":"Women (9)","id":"4","store":0,"path":"1\/2\/4","cls":"folder active-category","allowDrop":true,"allowDrag":true},{"text":"Kids (4)","id":"5","store":0,"path":"1\/2\/5","cls":"folder active-category","allowDrop":true,"allowDrag":true,"expanded":true},{"text":"Home &amp; Living (4)","id":"6","store":0,"path":"1\/2\/6","cls":"folder active-category","allowDrop":true,"allowDrag":true},{"text":"Sales (4)","id":"7","store":0,"path":"1\/2\/7","cls":"folder active-category","allowDrop":true,"allowDrag":true}],"expanded":true}],"parameters":{"text":"Root (0)","draggable":false,"allowDrop":false,"id":1,"expanded":0,"store_id":0,"category_id":5,"root_visible":0}}

How To resolve it.
Best Regards,
Ziven.

**Comment by kokoc** [comment] 2015-09-03 09:24
@zivendesign thank you for reporting the issue. Unfortunately, we are unable to reproduce it. Could you please verify the issue on latest Magento and provide more detailed steps to reproduce the issue?

**Comment by piotrekkaminski** [comment] 2015-10-14 21:50
We are closing this issue as there are no new comments. If you still experience this issue, please create a new issue.

**Closed by piotrekkaminski** 2015-10-14 21:50 UTC
Labels: MX, needs update
