### ISSUE TITLE
Active Product only visible for few customers

### ISSUE THREAD

**Issue by segway-github** [magento/magento2#38816] opened 2024-06-10 16:25 UTC
### Preconditions and environment

- Magento version:  ver. 2.4.3-p1
- Anything else that would help a developer reproduce the bug
We created a new product. Only few customers can search it. All others could not.

### Steps to reproduce

1. Go to Catalog--> Products
2. Click the 'Add Product'
3. Add a new product and choose the Visibility "Catalog, Search".
4. Set the product website as "Admin", "Spare"

### Expected result

All customers have the access to Spare should able to search the item

### Actual result

Only few customers can find it.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-06-12 20:24
Hi @segway-github ,

Verified the issue on 2.4-develop and we are not able to reproduce this issue.

Steps to reproduce:-

1.Go to Catalog--> Products
2.Click the 'Add Product'
3.Add a new product and choose the Visibility "Catalog, Search".
4.Set the product website as "Admin", "Spare"

Please refer the attached screenshots and let us know if we missed anything.

Catalog ->products


<img width="1359" alt="Screenshot 2024-06-13 at 1 17 16 AM" src="https://github.com/magento/magento2/assets/51681379/4e2f66d8-c5d8-4d0b-bc5a-eb154bf4d852">


Clicked on create New Product


<img width="1363" alt="Screenshot 2024-06-13 at 1 17 34 AM" src="https://github.com/magento/magento2/assets/51681379/e7412ac5-15a3-4bac-99fa-7cff593f7f20">

created product


<img width="1434" alt="Screenshot 2024-06-13 at 1 23 39 AM" src="https://github.com/magento/magento2/assets/51681379/e02876b7-9e11-417c-8268-a70042621b0d">


product assigned to main and spanish website


<img width="1439" alt="Screenshot 2024-06-13 at 1 23 56 AM" src="https://github.com/magento/magento2/assets/51681379/18190cc1-c443-4481-be9f-d532e776caa7">


Product available for all customers

<img width="1440" alt="Screenshot 2024-06-13 at 1 46 30 AM" src="https://github.com/magento/magento2/assets/51681379/3e2d0566-6281-49dd-8624-71f5445670a1">


<img width="1440" alt="Screenshot 2024-06-13 at 1 48 25 AM" src="https://github.com/magento/magento2/assets/51681379/cec4136f-f045-4350-bd23-ba1381ca2153">


<img width="1435" alt="Screenshot 2024-06-13 at 1 49 30 AM" src="https://github.com/magento/magento2/assets/51681379/c4945d12-f62b-4fe8-a754-fbd26d9489e5">

**Comment by engcom-Delta** [comment] 2024-06-13 14:34
Hi @segway-github ,

As of now we have checked this issue for simple product.Please let us know if you have different settings for the product, so that we can check at our end.

Thanks,

**Comment by segway-github** [comment] 2024-06-13 15:59
We’re using the standard setup.

Regards
Ares

**Comment by engcom-Delta** [comment] 2024-06-20 13:07
Hi @segway-github ,

As there is no activity on this issue for a long time, we believe the issue has been resolved, hence closing this issue.
Feel free to raise a new issue or reopen this if you need more assistance.

Thank you.

**Closed as completed by engcom-Delta** 2024-06-20 13:07 UTC
Labels: Issue: needs update, Reported on 2.4.3-p1
