### ISSUE TITLE
Simple product images lose sort order when uploaded through "Create Configurations" wizard

### ISSUE THREAD

**Issue by AlekosDordas** [magento/magento2#9884] opened 2017-06-08 14:07 UTC
### Preconditions

1. Magento CE 2.1.6
2. PHP 7.0.18
3. mysql  Ver 15.1 Distrib 10.1.16-MariaDB

### Steps to reproduce

1. Admin Panel > Catalog > New product
2. Fill required fields
3. Configurations > Create Configurations
4. Select attributes (ie. size + color) > Select Values
5. At Step3, select "Apply unique images by attribute to each SKU" and choose one attribute.
6. Upload 4 images to each attribute value
7. *Change their sort order by drag 'n dropping*
8. Click Next > Next and then save the product

### Expected result

1. The simple products (that have just been created) should have their images in the sort order that have been set during the Step3 of the configurable product "Create configuration" wizard.

### Actual result

1. The simple products (that have just been created) lost their image sort order that have been set during the Step3 of the configurable product "Create configuration" wizard.

![magento2issuess1](https://user-images.githubusercontent.com/29279856/26932572-8e5ab33a-4c6c-11e7-9068-db317590c4f1.png)
![magento2issuess2](https://user-images.githubusercontent.com/29279856/26932571-8e53a478-4c6c-11e7-8bcd-a2746dd3169a.png)
![magento2issuess3](https://user-images.githubusercontent.com/29279856/26932570-8e4f00bc-4c6c-11e7-85ea-4829aa1d83d0.png)

### Additional information
This also happens if you try to edit configurations of an existing configurable product.
It does not happen when you reorder simple product images from simple products page. It only happens when you reorder images from configurable product "Create Configurations" wizard, or "Edit configurations" wizard, at Step3.

**Comment by AlexWorking** [comment] 2017-06-23 12:45
Hi, @AlekosDordas. Based on Your issue an internal ticket was created, identified as MAGETWO-70167. You'll be informed immediately as the bug is fixed. Thank You for applying.

**Comment by magento-engcom-team** [comment] 2017-09-29 09:30
@AlekosDordas, thank you for your report.
We've created internal ticket(s) MAGETWO-70167 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-07-30 06:15
Hi @AlekosDordas

This ticket has been marked as `"Triage Wanted"` due to low user involvement over time. Over the next 2 weeks we are looking for additional community feedback to decide if it should be archived or not. More information on this is available on the GitHub [wiki](https://github.com/magento/magento2/wiki/Triage-Wanted).

Thank you for collaboration.

**Comment by magento-engcom-team** [comment] 2018-08-20 09:10
@AlekosDordas thank you for your report.

Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

You may learn more about this initiative following this [link](https://github.com/magento/magento2/wiki/Triage-Wanted).

Please feel free to comment or reopen the ticket if you think it should be reviewed once more. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2018-08-20 09:10 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, triage wanted

**Comment by Celoain** [comment] 2018-11-30 09:57
Just for anyone coming across this problem, you can create a Plugin:
di.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\ConfigurableProduct\Block\Product\View\Type\Configurable">
        <plugin name="image_reorder" type="Vendor\Module\Plugin\ConfigurablePlugin" sortOrder="1" disabled="false" />
    </type>
</config>
```
Plugin:
```php
<?php
namespace Vendor\Module\Plugin;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\ConfigurableProduct\Block\Product\View\Type\Configurable;
use Magento\ConfigurableProduct\Helper\Data;
use Magento\Framework\Serialize\Serializer\Json;
class ConfigurablePlugin 
{
    /**
     * Inject Dependencies
     * @param Json                       $jsonHelper        Json Data serializer
     * @param Data                       $helper            helper
     * @param ProductRepositoryInterface $productRepository Repository for products
     */
    public function __construct(
        Json $jsonHelper,
        Data $helper,
        ProductRepositoryInterface $productRepository
    )
    {
        $this->_jsonHelper = $jsonHelper;
        $this->_helper = $helper;
        $this->_productRepository = $productRepository;
    }
    /**
     * execute after getJsonConfig
     * @param  Configurable $subject Object that was observed
     * @param  string       $result  json result of observed method
     * @return string                json result
     */
    public function afterGetJsonConfig(
        Configurable $subject,
        $result
    )
    {
        $config = $this->_jsonHelper->unserialize($result);
        $products = [];
        foreach($config['images'] as $key => $value) {
            $products[] = $this->_productRepository->getById($key);
        }
        $config['images'] = $this->getOptionImages($products);
        return $this->_jsonHelper->serialize($config);
    }
    /**
     * [getOptionImages description]
     * @param  array<Products> $products Products to iterate over
     * @return mixed<mixed>           Array of images
     */
    protected function getOptionImages($products)
    {
        $images = [];
        foreach ($products as $product) {
            $productImages = $this->_helper->getGalleryImages($product) ?: [];
            foreach ($productImages as $image) {
                $images[$product->getId()][$image->getPositionDefault()] =
                    [
                        'thumb' => $image->getData('small_image_url'),
                        'img' => $image->getData('medium_image_url'),
                        'full' => $image->getData('large_image_url'),
                        'caption' => $image->getLabel(),
                        'position' => $image->getPositionDefault(),
                        'isMain' => $image->getFile() == $product->getImage(),
                        'type' => str_replace('external-', '', $image->getMediaType()),
                        'videoUrl' => $image->getVideoUrl()
                    ];
            }
            ksort($images[$product->getId()]);
        }
        return $images;
    }
}
```

Please note that this is not the best solution and just a quick fix.

**Comment by TheExplorerMO** [comment] 2018-12-14 01:03
@Celoain quick fix works but on Magento 2.2.6, you need to change:
`$images[$product->getId()][$image->getPositionDefault()] =`
to
`$images[$product->getId()][$image->getPositionDefault() -1] =`

**Comment by juansumma** [comment] 2019-09-19 18:56
@magento-engcom-team, we've come across this issue in a Magento 2.2.5 instance, and none of the community proposed walkarounds have worked. Can this be re-open?

How come it was not added to the backlog even though it has been reproduced by Magento team?

**Comment by amokato** [comment] 2021-12-02 17:02
It seems this is still an issue at least in 2.4.2. Can anyone confirm that?
