### ISSUE TITLE
2.1.x CE Multistore Multi domains, getting 404 error on Product Display Page for the non-Default Store View

### ISSUE THREAD

**Issue by ipekerti** [magento/magento2#11564] opened 2017-10-19 16:20 UTC
### Preconditions
I have a Magento CE 2.1.9, with 2 store views with 2 different domains.
 
The “Add Store Code to URLs” in Stores > Configuration > General > Web > URL options is set to DISABLED since I'm already using distinct domain names for the 2 stores.

### Steps to reproduce
A product configured for both  stores, but has unique info in set at secondary the store view scope. 
 
### Expected result

1. PDP for each store should display the store scope product info.

### Actual result

On Default Store, the Product Display Page (PDP) works properly from the category link, and from the direct product URL (without the category path). On the secondary store, the PDP works properly with URLs containing the category path(s), but I get a 404 error when accessing the page without the category paths.

Default Store: https://m2dev.specialized.net/12v-erv-unit-solarpulse-erv-12v-solar-charger-maintainer-6-watt.html  >>> SUCCESS
URL Rewrite’s target path:   m2dev.specialized.net/catalog/product/view/id/15120
 
Secondary Store Scope: https://m2dev.pulsetech.net/12v-erv-unit-solarpulse-erv-12v-solar-charger-maintainer-6-watt**-test**.html  >>> **404 ERROR**
URL Rewrite’s target path:   m2dev.pulsetech.net/catalog/product/view/id/15120

So, I guess the core question is… Why would
https://m2dev.pulsetech.net/catalog/product/view/id/15120 get a **404 ERROR**
while it works for https://m2dev.specialized.net/catalog/product/view/id/15120 ?

NOTE:
* Even setting the product to use a unique URL key at the secondary store view scope also didn't solve the problem.
* Actually, the problem has existed for our site since 2.1.0
 
What’s strange is that when at least one category path present in the URL, I don’t get the 404 error.
 
Default Store: https://m2dev.specialized.net/installation-equipment-supplies/12v-erv-unit-solarpulse-erv-12v-solar-charger-maintainer-6-watt.html >>> SUCCESS
URL Rewrite’s target path:   m2dev.specialized.net/catalog/product/view/id/15120/category/3360
 
Secondary Store Scope: https://m2dev.pulsetech.net/store/12v-erv-unit-solarpulse-erv-12v-solar-charger-maintainer-6-watt-test.html  >>> SUCCESS
URL Rewrite’s target path:   https://m2dev.pulsetech.net/catalog/product/view/id/15120/category/4699
 
Thanks in advance.

Immanuel

**Comment by IlnitskiyArtem** [comment] 2017-10-20 07:21
It seems as duplicate of [5416](https://github.com/magento/magento2/issues/5416).

**Comment by magento-engcom-team** [comment] 2017-10-20 10:30
@ipekerti, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-20 10:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
