### ISSUE TITLE
Currency symbol for Danish Krone doesn't match what is shown in the backend.

### ISSUE THREAD

**Issue by jupiterlewis** [magento/magento2#32256] opened 2021-02-23 14:12 UTC
### Preconditions (*)

1. Magento 2.4.0 (2.4-develop)

### Steps to reproduce (*)

1. Set Locale to Danish (Denmark)
![Set Locale](https://i.ibb.co/7nCd6yy/screenshot-127-0-0-1-2021-02-23-20-24-23.png)
2. Set Base Currency and Default Display Currency to Danish Krone

### Expected result (*)

1. Should display the currency symbol as DKK in the frontend as defined in the backends Currency Symbol section
![Backend currency symbol](https://i.ibb.co/J73Nqsr/currency-symbol-dkk.png)
 
### Actual result (*)

1. Displays kr in the frontend instead of DKK
![Frontend currency symbol](https://i.ibb.co/9WbQ4Gg/screenshot-127-0-0-1-2021-02-23-19-14-09.png)

### More Information
1. If we switch the Locale to English (United States) then it shows DKK in the frontend as expected.
![Showing DKK](https://i.ibb.co/3hvQVBr/screenshot-127-0-0-1-2021-02-23-19-18-15.png)

### Workaround
1. Put a space before the currency symbol in the backend.

### What I have found
1. The kr comes form the file public_html/vendor/magento/zendframework1/library/Zend/Locale/Data/da.xml line 3668

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jupiterhs** [comment] 2021-02-23 14:13
@magento give me 2.4-develop instance

**Comment by jupiterhs** [comment] 2021-02-23 14:33
Hi I am able to reproduce this on the 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2021-02-23 14:48
Hello @jupiterhs 

Thank you for your report

We have set the **Interface Locale** to _Dansk (Danmark) / dansk (Danmark)_ 
![locale](https://user-images.githubusercontent.com/51680745/108859509-f69f3b80-75f5-11eb-9387-b96bb8fcbe1d.png)

and set **Base Currency** and **Default Display Currency** to _dansk krone_
![def_base](https://user-images.githubusercontent.com/51680745/108859855-4ed63d80-75f6-11eb-9d81-ca16e9d9e085.png)

The products on the Storefront are displayed with **DKK** currency as described in the **Expected Result**
![front](https://user-images.githubusercontent.com/51680745/108860362-cad08580-75f6-11eb-9b5e-a2e9ab0a96f5.png)

Can you please correct our steps?

Thank you in advance

**Comment by jupiterhs** [comment] 2021-02-23 14:58
Hi @engcom-Bravo 
Thanks for checking.

I have updated the issue. 
You need to set the locale like below
![Set Locale](https://i.ibb.co/7nCd6yy/screenshot-127-0-0-1-2021-02-23-20-24-23.png)

**Comment by engcom-Bravo** [comment] 2021-02-23 15:13
@jupiterhs Thank you for the quick response.

The Storefront is using the Currency Symbol specified in _Stores - Currency Symbols_
![cur_sym](https://user-images.githubusercontent.com/51680745/108863848-4f70d300-75fa-11eb-8419-5f4a0dbf1953.png)
If you'll change the default ".kr" to "DKK", the symbol "DKK" will be displayed on the Storefront

**Comment by jupiterhs** [comment] 2021-02-23 15:28
@engcom-Bravo 
You are able to change it to DKK because you changed the Interface Local. Please try switching it back to English and you should see something like below.

![Currency setup](https://i.ibb.co/0yFtx0g/screenshot-d3f72cb5b008e9e7d6a304bc19c02018-2-4-develop-instances-magento-community-engineering-2021.png)

**Comment by jupiterhs** [comment] 2021-02-26 05:42
Hi @engcom-Bravo 
Hope you having a good day :)
did you get a chance to check this out?

**Comment by engcom-Bravo** [comment] 2021-02-26 11:52
Hello @jupiterhs 

Sorry for the delay. We Confirm that the issue is reproducible on the latest 2.4-develop.
Thank you for updating the description, and for communication.

**Comment by magento-engcom-team** [comment] 2021-02-26 11:54
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41078` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mortenbirkelund** [comment] 2021-05-13 18:50
Still relevant

**Comment by 4DallasC** [comment] 2022-02-15 03:48
Howdy All,

Having the same problem with PHP v7.4 and not with PHP v7.3. Looks like a change to how PHP's `\NumberFormatter::formatCurrency` operates when the second parameter `string $currency` is provided. In v7.4 it now overrides the applied setting of the currency symbol with the default in PHP.

The following edit is required in `\Magento\Directory\Model\Currency::formatCurrency(string $price, array $options): string`:-
```
$formattedCurrency = $this->numberFormatter->formatCurrency(
   $price, $this->getCode() ?? $this->numberFormatter->getTextAttribute(\NumberFormatter::CURRENCY_CODE)
);

```
to:-

```
$formattedCurrency = $this->numberFormatter->format($price);
```

**Comment by bobemoe** [comment] 2022-06-28 11:32
Having same issue, 2.4.4CE

The workaround specified in OP ("Put a space before the currency symbol in the backend.") works fine for me.

The code change in post directly above does not make any difference for me.

**Comment by engcom-Bravo** [comment] 2024-08-12 06:10
Hi @jupiterhs,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1420" alt="Screenshot 2024-08-12 at 11 35 06" src="https://github.com/user-attachments/assets/350f6404-668e-461d-83ab-2444a82b25a7">


<img width="1420" alt="Screenshot 2024-08-12 at 11 38 33" src="https://github.com/user-attachments/assets/bb7bd603-5afe-48a6-9577-92954d9d2a19">


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-12 06:10 UTC
Labels: Issue: Confirmed, Component: CurrencySymbol, Component: Locale, Reproduced on 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation, Reported on 2.4.0
