### ISSUE TITLE
products in category checkbox not align properly

### ISSUE THREAD

**Issue by priti2jcommerce** [magento/magento2#21021] opened 2019-02-06 12:25 UTC
### Preconditions (*)

1. 2.3.0
2. 

### Steps to reproduce (*)

1. Go to admin >> Catalog >> Categories
2. Select any category having product

### Expected result (*)

1. 
![image](https://user-images.githubusercontent.com/18118695/52341293-33f8f680-2a38-11e9-9074-087e0cb01dd6.png)

2.

### Actual result (*)

1.
![image](https://user-images.githubusercontent.com/18118695/52341207-00b66780-2a38-11e9-9940-3fdb05b1f231.png)

2.

**Comment by magento-engcom-team** [comment] 2019-02-06 12:25
Hi @priti2jcommerce. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@priti2jcommerce do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-06 12:28
Hi @faizan2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by faizan2jcommerce** [comment] 2019-02-06 12:30
@magento-engcom-team  please give me 2.3 develop instance.

**Comment by faizan2jcommerce** [comment] 2019-02-06 12:32
* @magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-06 12:32
Hi @faizan2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-06 12:33
Hi @faizan2jcommerce, here is your [Magento instance](https://i-21021-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21021-2-3-develop.instances.magento-community.engineering/admin](https://i-21021-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-06 12:39
:white_check_mark: Confirmed by @faizan2jcommerce
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-06 12:39
Hi @faizan2jcommerce. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by dmytro-ch** [comment] 2019-02-06 12:49
Hi @priti2jcommerce,
please, feel free to create PR without opening an issue for such minor styling issues.
Thank you!

**Comment by priti2jcommerce** [comment] 2019-02-06 12:53
Hi @dmytro-ch ,

Thanks for the update, I will make it for next time.

**Comment by magento-engcom-team** [comment] 2019-02-07 16:03
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98144` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-13 21:25
Hi @priti2jcommerce. Thank you for your report. 
The issue has been fixed in magento/magento2#21022 by @priti2jcommerce in 2.3-develop branch
Related commit(s):
 - [bf2a704f6e45e689678593fcc825c33f8863af38](https://github.com/magento/magento2/commit/bf2a704f6e45e689678593fcc825c33f8863af38)
 - [6e7734e4066347b61c65278f2ae54f0138ee7479](https://github.com/magento/magento2/commit/6e7734e4066347b61c65278f2ae54f0138ee7479)
 - [bc3fa6b86a2541acd0a8d70ac31f11c4ebbcb59a](https://github.com/magento/magento2/commit/bc3fa6b86a2541acd0a8d70ac31f11c4ebbcb59a)
 - [bf6d02348fc414ad011d944731232734eea18dba](https://github.com/magento/magento2/commit/bf6d02348fc414ad011d944731232734eea18dba)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-13 21:25 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend
