### ISSUE TITLE
Admin Grid - missing horizontal scrollbar when grid width is greater than page width

### ISSUE THREAD

**Issue by github-studioraz** [magento/magento2#37963] opened 2023-09-06 13:04 UTC
### Preconditions and environment

- Magento version m246-p1
- Reproducible with any type of a grid

### Steps to reproduce

- Go to /admin/sales/order/
- Add columns to the order grid so it will be wider than screen view
- Scroll order grid

### Expected result

The horizontal scrollbar should be available only for the order grid, not for full page

### Actual result

![image](https://github.com/magento/magento2/assets/22908864/12e86e5a-8523-4f91-b788-acaa7d94bbb4)

horizontal scrollbar missing:
**overflow-x: auto** 

It was removed on 2.4.6-p1 for some reason in this commit

[fixed style issue with grid · magento/magento2@ba93336](https://github.com/magento/magento2/commit/ba933368fb3610977527e38acc4e1db33c7e9b59)

### Release note

Fixed horizontal scrollbar for the admin grid

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by drinkingsouls** [comment] 2023-09-06 14:08
This bug has already been confirmed and I believe was assigned P3 priority. I am having no luck finding the issue here but I know it's been confirmed and assigned.

**Comment by engcom-Bravo** [comment] 2023-09-07 06:50
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-09-07 07:16
@drinkingsouls Thanks for your contribution & collaboration over here.

Hi @github-studioraz,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Go to /admin/sales/order/
- Add columns to the order grid so it will be wider than screen view
- Scroll order grid


<img width="1474" alt="Screenshot 2023-09-07 at 12 38 55 PM" src="https://github.com/magento/magento2/assets/51680745/5c756c64-fb36-4649-99ca-ca45ce0873c7">



But there is similar issue confirmed here https://github.com/magento/magento2/issues/37459 We are closing this as duplicate. Kindly move onto this issue for latest updates / solutions on the same.

Thank you.

**Closed as completed by engcom-Bravo** 2023-09-07 07:16 UTC
Labels: duplicate, Issue: ready for confirmation, Reported on 2.4.6-p1

**Comment by hewgim** [comment] 2025-04-11 22:06
Hi @engcom-Bravo But the issue does still exist in 2.4.6-p10. Can you confirm which versions the fix has been applied to

Regards

Mark
