### ISSUE TITLE
"State is required" is ignored in backend / admin

### ISSUE THREAD

**Issue by klein0r** [magento/magento2#5851] opened 2016-07-28 08:26 UTC
### Preconditions
1. Install 2.0.7 from composer
2. Add a customer
### Steps to reproduce
1. Go to Configuration / General / General
2. Uncheck ALL items (nothing selected) in "State is Required for"
3. Set "Allow to Choose State if It is Optional for Country" to NO
4. Go to a customer of your choice and add a new address / edit an existing address
5. Choose "Germany" or "United States" as country

![screen shot 2016-07-28 at 10 25 25](https://cloud.githubusercontent.com/assets/1959049/17205961/9fc44800-54ad-11e6-8a25-639e393c1f89.png)

![screen shot 2016-07-28 at 10 26 13](https://cloud.githubusercontent.com/assets/1959049/17205977/bb95aac4-54ad-11e6-9f08-35ba69e55199.png)
### Expected result
1. "State/Province" is not visible or not required
### Actual result
1. "State/Province" appears and is a required field

![screen shot 2016-07-28 at 10 24 10](https://cloud.githubusercontent.com/assets/1959049/17205918/716f044a-54ad-11e6-984e-094b454f636a.png)

**Comment by dthampy** [comment] 2016-07-28 19:43
Internal jira ticket MAGETWO-56056 created

**Comment by PascalBrouwers** [comment] 2016-11-08 10:41
@sevos1984 
Seems like a duplicate of https://github.com/magento/magento2/issues/6261
Can you close this one? 6261 has more information on how to solve this.

**Comment by vrann** [comment] 2017-03-28 21:53
@sevos1984 closing as a duplicate

**Closed as completed by vrann** 2017-03-28 21:53 UTC
Labels: Issue: Ready for Work, bug report
