### ISSUE TITLE
cannot create order from admin side using a customer.

### ISSUE THREAD

**Issue by brio101** [magento/magento2#9143] opened 2017-04-05 12:08 UTC
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by korostii** [comment] 2017-04-06 11:10
If you are looking for some help or an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.

The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.
Thus if you are, in fact, reporting a technical issue, please try add as much information as possible, including the environment you use, 3rd party themes and modules installed, preconditions, exact steps to follow, screenshots and stack trace from browser console and even the custom code you're using. These raise the chances of the bug getting reproduced and acknowledged. 
If you don't provide enough information, it is likely that the issue will receive a "needs update" label and will get closed in a couple weeks.

**Comment by veloraven** [comment] 2017-06-26 12:19
@brio101 please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by magento-engcom-team** [comment] 2017-09-11 19:35
@brio101 we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-11 19:35 UTC
Labels: Progress: needs update, Issue: Format is valid
