### ISSUE TITLE
Customer Login Failing in Firefox/IE 2.1.1

### ISSUE THREAD

**Issue by Oxidation1** [magento/magento2#6874] opened 2016-10-04 17:11 UTC
On chrome the customers are able to login, however on firefox and IE/Edge after a customer logs in the page shows the infamous "This page is not redirecting properly." I have quadruple checked the cookies domains are set correctly [.domain.com], tried playing with the setting to redirect customers to my account after login with no change, tried changing the base urls to both http, both https, and as expected http for unsecure and https for secure with no luck either. 

I am getting VERY frustrated, and need these websites to be live.. this project is taking WAY to long magento 2.1.1 seems very broken out of the box. There is other issues after this I still need to tackle. 

I have also started by redoing the setup in index.php and .htaccess as per the documentation for multi-store mode. Still doing the same thing. I have checked the domain inside the cookies on firefox, they are all showing the same domain as well. 

Preconditions
1. PHP version is 5.6
2. MySql version is 5.6.3.3
3. Apache 3 - Cent OS
4. At the moment there is 2 stores, websites and configurations. They both have the same issue. 

Steps to reproduce / Result
1. Go to customer login, in chrome it works
2. Go to customer login, type in credentials, correct or incorrect gives same result, redirect error. 
3. Try to reload page in firefox, still redirect error. 
4. Clear cookies, close and reopen browser, page will show up again until you try and login again.

**Comment by stamster** [comment] 2016-10-05 09:25
Are you using HTTPS for a store?

**Comment by stamster** [comment] 2016-10-05 10:59
We also had many issues with broken 2.1.1 release xD
So we reverted back to 2.1.0 and at least some stuff is working. You should try the same.
Good luck.

**Comment by Oxidation1** [comment] 2016-10-05 13:18
Its a fresh install, I have a TON of products already loaded... unfortunately this problem was not noticed till after I loaded them.. was hoping to not have to do another install but may not have a choice.. this is just way to broken... Have herd a few comments similar to mine on 2.1.1, will have to give 2.1.0 a go. Doubt it helps at all but some other problems just to have it for other people to see.. 
1. Checkout hangs up -> chrome is showing unexpected end of JSON input as well as redirect errors. 
2. Redirect error and have to clear cookies in ALL BROWSERS if I click "add to cart" when not logged in. 
3. This log in issue
4. Web connect (domain.com/setup) goes to an error 404 page. 
5. Product image imports works when it wants to. (Seriously, exact same steps sometimes it works sometimes it doesn't, its very moody...)

.. and this is the end of my issues list.. I have fixed a ton of them...

**Comment by stamster** [comment] 2016-10-05 16:39
You're using Apache 3.... can you try with nginx perhaps, that's my recommendation.
If not, try to disable http2 support - that might also cause issues.

**Comment by sevos1984** [comment] 2016-10-17 07:43
I can't reproduce this, please provide more detailed steps, logs, configuration settings etc. Thanks

**Comment by sevos1984** [comment] 2016-10-31 10:16
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-10-31 10:16 UTC
Labels: bug report, Progress: needs update, Component: Customer
