### ISSUE TITLE
Error in forms with date inputs in german format

### ISSUE THREAD

**Issue by NeilofSteel** [magento/magento2#27265] opened 2020-03-12 13:00 UTC
### Preconditions (*)
1. Magento 2.3.4
2. Using locale de_DE 

### Steps to reproduce (*)
1. Use Magento 2.3.4
2. Set your Interface user and shop locale to germany
3. Edit customer in backend or go to create account in frontend
4. Pick for example the birthdate 30.01.1999 

### Expected result (*)
1. Save customer or create account with no error in the date input

### Actual result (*)
1. Getting error under the birthday date input "The Date of Birth should not be greater than today." and can't save the customer information or create a account.

I think the reason for that are the "." characters which we are using in dates in germany. -> dd.mm.yyyy
If I set my user Interface-Locale to en_US it works with the format dd/mm/yyyy

**Comment by NeilofSteel** [comment] 2020-03-12 13:00
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-03-12 13:00
Hi @NeilofSteel. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-03-12 13:01
Hi @NeilofSteel, here is your [Magento instance](https://i-27265-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27265-2-4-develop.instances.magento-community.engineering/admin_71e1](https://i-27265-2-4-develop.instances.magento-community.engineering/admin_71e1)
Login: `5c7e0e6c` Password: `89f28faae902`
Instance will be terminated in up to 3 hours.

**Comment by NeilofSteel** [comment] 2020-03-12 13:08
@magento give me 2.3.4 instance

**Comment by magento-engcom-team** [comment] 2020-03-12 13:08
Hi @NeilofSteel. Thank you for your request. I'm working on Magento 2.3.4 instance for you

**Comment by magento-engcom-team** [comment] 2020-03-12 13:09
Hi @NeilofSteel, here is your [Magento instance](https://i-27265-2-3-4.instances.magento-community.engineering).
Admin access: [https://i-27265-2-3-4.instances.magento-community.engineering/admin_573e](https://i-27265-2-3-4.instances.magento-community.engineering/admin_573e)
Login: `979805af` Password: `ba91b79a4b6a`
Instance will be terminated in up to 3 hours.

**Comment by NeilofSteel** [comment] 2020-03-12 13:13
Well only reproduceable in 2.3.4 is there a fix?
already tried https://github.com/magento/magento2/issues/27027 but not working for me

**Comment by devchris79** [comment] 2020-03-12 14:55
May be worth checking #26675

**Comment by Axel29** [comment] 2020-03-24 14:18
Any update on this issue? Having the same issue with French locale, customers can't create an account.
Thanks.

**Comment by Axel29** [comment] 2020-03-24 15:08
After debugging a little, it seems that if we make the following changes:

* `\Magento\Customer\Block\Widget\Dob::getHtmlExtraParams` :

```php
public function getHtmlExtraParams()
{
    $validators = [];
    if ($this->isRequired()) {
        $validators['required'] = true;
    }
    $validators['validate-date'] = [
        'dateFormat' => $this->getDateFormat()
    ];
    /*
     * The patch is here.
     * Original code: $validators['validate-dob'] = true;
     */
    $validators['validate-dob'] = [
        'dateFormat' => $this->getDateFormat()
    ];

    return 'data-validate="' . $this->_escaper->escapeHtml(json_encode($validators)) . '"';
}
```

* `view/frontend/web/js/validation.js` : 

```javascript
define([
    'jquery',
    'moment',
    'jquery/validate',
    'mage/translate'
], function ($, moment) {
    'use strict';

    $.validator.addMethod(
        'validate-dob',
        function (value, param, params) {
            if (value === '') {
                return true;
            }

            return moment.utc(value, params.dateFormat).isBefore(moment.utc());
        },
        $.mage.__('The Date of Birth should not be greater than today.')
    );
});

```

It's almost good.
The only thing left is that the date format doesn't seem to be okay.
The correct one would be `D/MM/Y` but Magento returns `"dd/MM/y"`.

**Comment by stkrelax** [comment] 2020-06-19 08:21
Also reproduced on magento 2.3.5-p1. Same Problem here. No account create possible...

**Comment by stkrelax** [comment] 2020-06-19 08:27
@Axel29 there is also a validation in vendor/magento/module-ui/view/base/web/js/lib/validation/rules.js where it is used

**Comment by hostep** [comment] 2020-07-02 11:55
I think this got fixed in 2.4-develop with [MC-31117](https://github.com/magento/magento2/commit/4ecae3093cfc04c0a7d66045e0b54b30c73112b3) in scope of https://github.com/magento/magento2/issues/26700, but might be wrong about this.

**Comment by NeilofSteel** [comment] 2020-07-02 13:28
To fix my issue I changed the line

`return moment(value).isBefore(moment());`
to
`return moment(value, ["D.MM.Y"]).isBefore(moment());`

in /vendor/magento/module-customer/view/frontend/web/js/validation.js

but you should only do that if you use that format too :)

**Comment by engcom-Bravo** [comment] 2020-10-22 07:59
Hello @NeilofSteel 

Thank you for your report

We have rechecked the issue on the latest 2.4-develop and the issue is **not** reproducible

Steps to reproduce:
1. Set your Interface user and shop locale to Germany
![Interface locale](https://user-images.githubusercontent.com/51680745/96842199-66899380-1455-11eb-8f08-446c30b2fcc7.png)
2. Edit customer in backend or go to create account in frontend
3. Pick for example the birthdate 30.01.1999
![Edit data](https://user-images.githubusercontent.com/51680745/96842255-7b662700-1455-11eb-9ea2-a12728965859.png)
![Create acc](https://user-images.githubusercontent.com/51680745/96842285-8620bc00-1455-11eb-8654-0a8dcd7e5b61.png)

Actual result: Save customer or create account with no error in the date input

We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-10-22 07:59 UTC
Labels: Reported on 2.3.4
