### ISSUE TITLE
MAGENTO 2.3.5 /V1/products overwrite default values on multi-store site even when only one field is sent to update

### ISSUE THREAD

**Issue by lano-vargas** [magento/magento2#31083] opened 2020-11-27 19:47 UTC
### Preconditions (*)

1. V:2.3.5, 2.4-develop
2. Product API (catalogProductRepositoryV1)

### Steps to reproduce (*)

1. Configure all store view to run under one domain E.G: dev.test. 
2. Set one more Environment apart from default website/store/store view.
3. E.G: IE
![Screen Shot 2020-11-27 at 19 26 08](https://user-images.githubusercontent.com/3495481/100479539-6cbeff80-30e6-11eb-8d32-0d7770ecbdc5.png)
4. Create product on all store view using postman or any other tool:
**URL:** `rest/all/V1/products`
**BODY**
```
{
  "product": {
    "sku": "test-1",
    "name": "Test 1",
    "attribute_set_id": 4,
    "price": 10,
    "status": 1,
    "visibility": 4,
    "type_id": "simple",
    "weight": 100
  },
  "saveOptions": true
}
```
5. Update product name for IE store view:
**URL:** `rest/en-ie/V1/products`
**BODY:**
```
{
  "product": {
    "sku": "test-1",
    "name": "Test 1 changed",
  },
  "saveOptions": true
}
```

### Expected result (*)

1. When API for en-ie is sent I expect only product name changed/updated for that store view

### Actual result (*)

1. Instead all values previously sent for all store view have the checkbox unchecked and populated with the all store view data therefore this values cannot be updated using the all store views again 
2.
![Screen Shot 2020-11-27 at 19 49 03](https://user-images.githubusercontent.com/3495481/100480589-a34a4980-30e9-11eb-9f5a-7f4699211a63.png)

Thanks

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by lano-vargas** [comment] 2020-11-27 20:00
@magento give me 2.3.5 instance

**Comment by lano-vargas** [comment] 2020-11-27 20:04
@magento give me 2.4-develop instance

**Comment by lano-vargas** [comment] 2020-11-27 20:20
@magento-team The issue however is on 2.3.5 I cannot test REST api USING the instance 2.4 given url:
![Screen Shot 2020-11-27 at 20 16 44](https://user-images.githubusercontent.com/3495481/100481943-a7786600-30ed-11eb-87ff-10d6e0d91779.png)

Can you confirm if this is a bug please ?

Thanks

**Comment by lano-vargas** [comment] 2020-11-28 14:41
@magento give me 2.4-develop instance

**Comment by lano-vargas** [comment] 2020-11-28 14:53
@magento I've replicated the issue on 2.4 instance see updated :
![Screen Shot 2020-11-28 at 14 51 20](https://user-images.githubusercontent.com/3495481/100518419-4900c580-3189-11eb-8297-1919d9e12036.png)
![Screen Shot 2020-11-28 at 14 51 12](https://user-images.githubusercontent.com/3495481/100518421-4aca8900-3189-11eb-9ca3-4251c3245e29.png)

I would spect only the Product Name checkbox to be unchecked but all store view fields checkbox are unchecked!

**Comment by lano-vargas** [comment] 2020-11-30 09:13
Reproduced on 2.4.x

**Comment by magento-engcom-team** [comment] 2020-11-30 09:21
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-39481` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by lano-vargas** [comment] 2020-12-01 14:23
@engcom-Delta  possible duplicate https://github.com/magento/magento2/issues/26484

**Comment by zakdma** [comment] 2020-12-03 15:46
@magento i am working on it

**Comment by magento-engcom-team** [comment] 2021-01-20 20:16
Hi @lano-vargas, @zakdma. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39481` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Closed as completed** 2021-01-20 20:15 UTC
Labels: Issue: Confirmed, Triage: Dev.Experience, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P1, Severity: S1, Progress: done, Reported on 2.3.5

**Comment by hostep** [comment] 2021-01-21 07:11
Commits related to `MC-39481`: https://github.com/magento/magento2/search?q=MC-39481&type=commits

**Comment by LiamKarlMitchell** [comment] 2021-04-07 21:21
Nice thanks :)

**Comment by neddy236** [comment] 2021-05-20 10:52
@hostep After trying the patch (https://github.com/magento/magento2/search?q=MC-39481&type=commits) to 2 magento instances. One 2.4.2 and one 2.3.5-p2 it creates a different problem.

The problem that @lano-vargas said was fixed but a new issue arised.

Let's say you have 1 website and 2 store views again.

You create a product via API and then you try to update the product via API -> PUT @ domain/rest/{{store_code}}/V1/products/{{sku}} and change your locale values like the name. It works great so far.

but then if you try to make another call to the same store view but change only ONE custom attribute, it then ticks off the use default again for all the attributes that were unchecked by the explicit api call that came before this one.

So if you changed the name to be specific to the locale, it gets lost and uses the default value once again.

ex.

`{
  "product": {
    "custom_attributes": [
      {
        "attribute_code": "my_attribute",
        "value": "test_value"
      }
    ]
  }
}`

**Comment by hostep** [comment] 2021-05-20 15:00
@neddy236: that sounds pretty bad.

Could you please open a new issue for this case? It will get picked up much faster that way.

**Comment by neddy236** [comment] 2021-05-20 15:40
@hostep done. https://github.com/magento/magento2/issues/33052

Imagine updating 20k products in one day in spanish store view for example. Then the next day change a boolean attribute on this products. 

You just lost all your spanish product names :)

**Comment by leonhelmus** [comment] 2022-02-08 13:36
This feature now seems to delete my url rewrites :(. If default store has visibility 4 and you try to update a store without adding visibility in the request like this:
[{
  "product": {
    "sku": "428138",
    "status": 1,
    "attribute_set_id": 1169
  }
}]
it will delete your url_rewrites.... If you use the url: https://example.dev.mediacthq.nl/rest/example_nl/async/bulk/V1/products. Because it adds a null value to visibility :(

**Comment by leonhelmus** [comment] 2022-02-08 14:03
Issue is fixed by this commit -> https://github.com/magento/magento2/commit/306f515d7a6b66d0dbfd0240d39f2d8e416b09ad
