### ISSUE TITLE
Whitespace between label and required star on Checkout page

### ISSUE THREAD

**Issue by tejash-wagento** [magento/magento2#26275] opened 2020-01-06 06:44 UTC
### Summary
Whitespace between the label and required star on the Checkout page

### Preconditions
1. Magento 2x - This issue reproduce in all version.

### Steps to reproduce

1. Add simple product in the cart
2. Go to checkout page

### Expected result

![image](https://user-images.githubusercontent.com/15318347/71800301-bbeae480-307d-11ea-8c69-2f53cb9bb7c6.png)

### Actual result

![image](https://user-images.githubusercontent.com/15318347/71800245-9067fa00-307d-11ea-8132-21399c99a9f0.png)

**Comment by tejash-wagento** [comment] 2020-01-06 06:48
I am working on this

**Comment by ajijshekh123** [comment] 2020-01-06 06:50
Okay @tejash-wagento, Let me verify and confirm the issue.

**Comment by ajijshekh123** [comment] 2020-01-06 06:51
Why @tejash-wagento  , You have to unassigned to me?

**Comment by krishprakash** [comment] 2020-01-06 07:31
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-06 07:31
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-06 07:32
Hi @krishprakash, here is your [Magento instance](https://i-26275-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26275-2-4-develop.instances.magento-community.engineering/admin](https://i-26275-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-01-06 07:36
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30219` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dmytro-ch** [comment] 2020-01-06 10:11
Hi @tejash-wagento,
please create the pull requests with minor fixes and obvious improvements without opening the issues.
Thank you!

**Closed as completed** 2020-01-06 10:11 UTC
Labels: Component: Checkout, Issue: Clear Description, non-issue, Issue: Format is valid, Reproduced on 2.4.x, Fixed in 2.4.x

**Comment by tejash-wagento** [comment] 2020-01-07 04:43
Hi @dmytro-ch,
How can I improvements without opening the issues,
Please suggest?

**Comment by DanielRuf** [comment] 2020-01-07 06:10
You can always create a PR, an issue is not required and produces more work for involved people.

**Comment by tejash-wagento** [comment] 2020-01-07 06:46
Hi @DanielRuf,
I have not created PR a long time, I have created my last PR 2 years ago at Jul 30, 2018.
So I am not always creating a PR, an issue is not required and produces more work for involved people.

Please check my PR history and comment.

**Comment by DanielRuf** [comment] 2020-01-07 06:57
Not sure why people downvote.
As @dmytro-ch wrote:

> Hi @tejash-wagento,
please create the pull requests with minor fixes and obvious improvements without opening the issues.
Thank you!

So just go ahead and create a PR with the fixes.

**Comment by DanielRuf** [comment] 2020-01-07 07:08
To quote yourself:

https://github.com/magento/magento2/issues/26275#issuecomment-571025640
> I am working on this

It was assigned to @ajijshekh123 and others who were working on it.

**Comment by DanielRuf** [comment] 2020-01-07 07:19
Interesting, 4 people from wagento downvoting for no obvious reasons (read the previous comments).

If you need help with the PR just let us know.

**Comment by DanielRuf** [comment] 2020-01-07 07:43
There you go: https://github.com/magento/magento2/pull/26285

Please be more polite next time and downvoting is never helpful (without further feedback) =)

**Comment by DanielRuf** [comment] 2020-01-07 07:49
There you go: https://github.com/magento/magento2/pull/26285

Please be more polite next time and downvoting is never helpful (without further feedback) =)

Also related: https://github.com/magento/magento2/pull/16048

Please keep in mind that at least two people (excluding you) were working on this. Please give them the chance to do the chances then when the issue is assigned to them. Unassigning them is not very nice. If you intend to fix it yourself please do so without creating a separate issue to prevent such cases in the future.

**Comment by slavvka** [comment] 2020-02-07 23:13
Hi @tejash-wagento. Thank you for your report. 
The issue has been fixed in magento/magento2#26285 by @DanielRuf in 2.4-develop branch
Related commit(s):
 - [d9a4bca7a289ea6c024d02989a6a29db54b1e5de](https://github.com/magento/magento2/commit/d9a4bca7a289ea6c024d02989a6a29db54b1e5de)
 - [51f4964bf339e7b233e09797cd8762208b974bf2](https://github.com/magento/magento2/commit/51f4964bf339e7b233e09797cd8762208b974bf2)
 - [574f052a3ad4ca82735d0b487d6ceb854066cc8b](https://github.com/magento/magento2/commit/574f052a3ad4ca82735d0b487d6ceb854066cc8b)
 - [0edeb06a2ef7f0af108756d3cb62069b976e207a](https://github.com/magento/magento2/commit/0edeb06a2ef7f0af108756d3cb62069b976e207a)
 - [fb208a8d6b4d738bb2e59c2771dd1223f4448fcb](https://github.com/magento/magento2/commit/fb208a8d6b4d738bb2e59c2771dd1223f4448fcb)
 - [c1c363fceaf6a0782412b56f0f97dc46e677e036](https://github.com/magento/magento2/commit/c1c363fceaf6a0782412b56f0f97dc46e677e036)
 - [98e1159d2bf6ef57c646bdd9c6ca09e6729af9bc](https://github.com/magento/magento2/commit/98e1159d2bf6ef57c646bdd9c6ca09e6729af9bc)
 - [10cc12a26209b38b210c9e67a64ab9d378d7e1bc](https://github.com/magento/magento2/commit/10cc12a26209b38b210c9e67a64ab9d378d7e1bc)
 - [ff4ead556dc0540e321bc2f9de6e835b04bf73d0](https://github.com/magento/magento2/commit/ff4ead556dc0540e321bc2f9de6e835b04bf73d0)
 - [535b7c8ab30702d087ac3958cbe2e45c13859daf](https://github.com/magento/magento2/commit/535b7c8ab30702d087ac3958cbe2e45c13859daf)
 - [4b86376704ed5bd19b9e83d052a9625d609bc779](https://github.com/magento/magento2/commit/4b86376704ed5bd19b9e83d052a9625d609bc779)
 - [3165046a04ef94be789d1028eca0048c5991227b](https://github.com/magento/magento2/commit/3165046a04ef94be789d1028eca0048c5991227b)
 - [66a76f3c8c5618731dd3286dd5bbda05bda0f272](https://github.com/magento/magento2/commit/66a76f3c8c5618731dd3286dd5bbda05bda0f272)
 - [ca19b0690d3178bef00050c8edcdb975ff8199ad](https://github.com/magento/magento2/commit/ca19b0690d3178bef00050c8edcdb975ff8199ad)
 - [60b7f1caa1e1921abd2dd17f2dc40e0924585b53](https://github.com/magento/magento2/commit/60b7f1caa1e1921abd2dd17f2dc40e0924585b53)
 - [1eed0f183d9cbaa038ba2cbec8722eaed9505e5f](https://github.com/magento/magento2/commit/1eed0f183d9cbaa038ba2cbec8722eaed9505e5f)
 - [5958409d4016223ccdec69283ac79050f48781ea](https://github.com/magento/magento2/commit/5958409d4016223ccdec69283ac79050f48781ea)
 - [4b9b6fa85fcbb2f47efe0f67ab5889b355b2f300](https://github.com/magento/magento2/commit/4b9b6fa85fcbb2f47efe0f67ab5889b355b2f300)

The fix will be available with the upcoming 2.4.0 release.
