### ISSUE TITLE
ability to change admin password from CLI

### ISSUE THREAD

**Issue by markoshust** [magento/magento2#2175] opened 2015-10-24 05:25 UTC
The `./bin/magento` CLI tool contains the command `admin:user:create`. It would be very helpful to add another command `admin:user:update`, which would allow the user to update the admin password. This comes up a lot when taking over development for projects from other companies, and/or just needing a quick way to change the admin password to access the site.

The same directives should probably be used from `admin:user:create`.

**Comment by mazhalai** [comment] 2015-10-26 17:08
Thank you @markoshust for your suggestion. We have created task MAGETWO-44629 to work on this.

**Comment by degaray** [comment] 2015-11-17 16:53
Is there a way to change the admin password while the CLI command is not done?

**Comment by mazhalai** [comment] 2015-11-18 22:39
@degaray why would you want to change admin password before the CLI is done?

**Comment by degaray** [comment] 2015-11-18 22:47
I lost my password, and I used a non existent email account. So I cannot retrieve or change my password.

**Comment by mazhalai** [comment] 2015-11-18 22:54
@degaray Please refer to [this doc](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-subcommands-admin.html#instgde-cli-admin-unlock) it should help you to unlock the account, or just [uninstall](http://devdocs.magento.com/guides/v2.0/install-gde/install/cli/install-cli-uninstall.html#instgde-install-uninstall) and start over.

**Comment by degaray** [comment] 2015-11-18 23:36
hmm. Ok, but the problem is it is not locked. It is lost unfortunately. However what I did is create a different user. I guess I can wait until you guys create this.

**Comment by davidalger** [comment] 2015-11-19 01:06
@degaray You should be able to change the password from the admin interface via the new admin user you created to use temporarily.

**Comment by magenx** [comment] 2016-01-28 21:21
i guess reset password is much faster and easier to do.... no need to create new user, etc...
could  you please add this feature. something like OP proposed:
`bin/magento admin:user:update --admin-user="dave" --admin-password="admin123"`

**Comment by piotrekkaminski** [comment] 2016-08-30 20:10
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/ability-to-change-admin-password-from-CLI/idi-p/47204).

**Closed by piotrekkaminski** 2016-08-30 20:10 UTC
Labels: acknowledged, Admin Panel, feature request, moved_to_forums, PROD
