### ISSUE TITLE
[v2.4.6-p1] Categories - Adding or modifying causes 6+ min db lock

### ISSUE THREAD

**Issue by FadedOut** [magento/magento2#37821] opened 2023-08-01 07:19 UTC
### Preconditions and environment

- Magento 2.4.6-p1
- PHP 8.2
- MariaDB 10.6.x
- Index: Update on Schedule
- ElasticSearch 8.5.3 (ElasticSuite 2.11.3)
- Single-store

My server is a 8-core 12GB ram VPS. It has nothing to do with my server specs. I am at around 6gb used while this is happening. And no other CPU usage other than the "mariadb" spike right after I add a category.

### Steps to reproduce

1. Have roughly 100 categories
2. Have at least 8500 products
3. Add or re-organize a category

### Expected result

Be able to add a new category right after adding a previous category.

### Actual result

Unable to add a new category for at least 6 minutes. Using htop in terminal I see mariadb using 98% cpu for the entire time. During this time if I try to add another category the page just says "Please wait..." (for about 45 seconds) then it will eventually reload the page, not adding the new category. Sometimes I get a failure to add warning and a DB lock error. Same when I try to move a category after adding or moving a previous category - nothing happens or I get a DB lock error.

The mysql process list shows it does the following query for the 6+ minutes: 

`INSERT INTO catalog_category_product_index_store1_replica (category_id, product_id, position`

...at this rate it takes one hour+ to add/modify 10 categories. It's horrible.

### Additional information

Some pictures showing the stats:

![magento-adding-category-causes-7min-db-lock](https://github.com/magento/magento2/assets/12685113/8230ff8d-8372-4cfd-ab84-b929170a0499)

![magento-adding-category-causes-5min-cpu-spike](https://github.com/magento/magento2/assets/12685113/39cca87d-097f-485e-92f0-9efb29d3f920)

This does not happen on a clean install with no products - categories can be added one after another no problem. They can also be re-organized and modified no problem one after another. It seems to be when there are thousands of products and 100+ categories. 

I also tried with "Update on Save" for the indexing, but that just causes a 1 min 30 second timeout with Cloudflare after choosing to save the category.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2023-08-01 11:35
Hi @FadedOut ,

Verified the issue in 2.4-develop instance and the issue is not reproducible,Kindly recheck the behaviour in 2.4-develop instance.
Kindly refer the below screenshots and video reference:

<img width="1512" alt="Screenshot 2023-08-01 at 2 43 21 PM" src="https://github.com/magento/magento2/assets/60198592/4f247f7c-f33a-40df-96d1-6565f54e50b6">
<img width="1512" alt="Screenshot 2023-08-01 at 2 39 43 PM" src="https://github.com/magento/magento2/assets/60198592/fecddd3d-6979-4ccb-aa5d-bf801553236e">
New category:
<img width="1512" alt="Screenshot 2023-08-01 at 5 03 45 PM" src="https://github.com/magento/magento2/assets/60198592/7900a22d-beba-435a-b85b-02f4dc1c8dae">

https://github.com/magento/magento2/assets/60198592/1782f9cd-6fc3-494e-b3d8-c435232bd961

Note: We created 100  100 categories and 8500 products as per [DevDocs](https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/generate-data.html)

We can add subcategories or new categories without any interruptions.Kindly let us know if we are missing anything.

Regards.

**Comment by engcom-Dash** [comment] 2023-08-18 09:26
Hi @FadedOut ,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2023-08-18 09:26 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
