### ISSUE TITLE
Move customer from one website to another. 

### ISSUE THREAD

**Issue by Emilyrosewell** [magento/magento2#31457] opened 2020-12-24 16:29 UTC
I am able to move the customer from one website to another from the list view. 
However, I am not able to change the associated website after clicking edit
Also, after moving customer from one website to another, the customer is not receiving any email.

**Comment by krishprakash** [comment] 2020-12-25 04:34
Hi @Emilyrosewell. In the current stage, it is not clear what the actual problem is.
Steps to reproduce, actual and expected result, screens that illustrate problem will help a lot.
Also update all the details as per [issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Comment by Emilyrosewell** [comment] 2020-12-28 10:55
![image](https://user-images.githubusercontent.com/76565961/103209395-0b7a8e00-4929-11eb-9830-9804342afd3c.png)
So, while editing in-line in the customer section. I am able to change the customer email id. 

But when I edit the customer details -- I cant change the website- -
![image](https://user-images.githubusercontent.com/76565961/103209483-39f86900-4929-11eb-9632-1762313062d3.png)

**Comment by engcom-Bravo** [comment] 2020-12-28 12:14
Hello @Emilyrosewell 

Thank you for your report

We have rechecked the reported issue on the latest 2.4-develop. 
The Customers web site can be changed both from _List_ and from the _Account Information_ window. Please see the attachment
![Peek 2020-12-28 14-10](https://user-images.githubusercontent.com/51680745/103213543-acac1900-4916-11eb-957e-bae47faee92f.gif)

Rechecked with Customers created from the Admin Panel and from Storefront. Customrs ssigned to different websites.

Can you please confirm that you are able to reproduce the issue on the latest 2.4-develop? If yes, please provide more details in order we could confirm the issue and provide a fix for it

**Comment by Emilyrosewell** [comment] 2020-12-29 15:14
To this, I have one more question. Will the data of customer (like orders, cart, wish list) will also be copied to another website.

**Comment by engcom-Bravo** [comment] 2020-12-30 11:23
@Emilyrosewell 

Thank you for the quick response

As for your previous question 

> To this, I have one more question. Will the data of customer (like orders, cart, wish list) will also be copied to another website.

The answer is Yes, the customer data like Wish List and Order are displayed in the Customer information. As for the Shopping cart, Admin may select the website scope, and the Cart(s) will be displayed.

As far as the issue is not reproducible on the latest 2.4-develop, we have to close it. Please feel free to comment or create a new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you

**Closed as completed by engcom-Bravo** 2020-12-30 11:23 UTC
Labels: not-confirmed
