### ISSUE TITLE
Refund PayPal error #100009: PayPal gateway has rejected request. The partial refund amount must be less than or equal to the remaining amount

### ISSUE THREAD

**Issue by boikolabs** [magento/magento2#24033] opened 2019-08-06 12:11 UTC
### Preconditions (*)
1. Magento ver. 2.3.1 
2. Sample Data
3. PayPal

### Steps to reproduce (*)
1. An order with different items are created (Pay with PayPal):
- 3items - Olivia 1/4 Zip Light Jacket (Size: M, Color: Blue)
- 2items - Fusion Backpack
- Shipment - Fixed $25.00
- Address: Main St, San Jose, CA 95131 United States
2. Go to Magento as admin
3. Create three invoices:
- Invoice 1 - Olivia 1/4 Zip Light Jacket - 1 qty with the shipment; 
- Invoice 2 -  Fusion Backpack - 2 qty;
- Invoice 3 - Olivia 1/4 Zip Light Jacket - 2 qty;
4. Create two shipments:
- Shipment 1 - Olivia 1/4 Zip Light Jacket - 3 qty;
- Shipment 2 - Fusion Backpack - 2 qty;
5. Go to Invoice 1, click Credit Memo, select all items and click Refund.
6. Go to Invoice 2, click Credit Memo, select all items and click Refund - ERROR.

### Expected result (*)
1. Correct created CreditMemo.

### Actual result (*)
1. PayPal gateway has rejected request. The partial refund amount must be less than or equal to the remaining amount (#10009: Transaction refused).

####LOG:  
[2019-07-31 13:50:33] main.CRITICAL: PayPal gateway has rejected request. The partial refund amount must be less than or equal to the remaining amount (#10009: Transaction refused). {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): PayPal gateway has rejected request. The partial refund amount must be less than or equal to the remaining amount (#10009: Transaction refused). at /home/ubuntu/magento-try-2/src/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:116)"} []

**Comment by engcom-Charlie** [comment] 2019-08-14 09:25
Hello @S-Boiko 
I can't reproduce this issue on fresh Magento 2.3-develop.

**Manual testing scenario:**

1. An order with different items are created (Pay with PayPal):
3items - Olivia 1/4 Zip Light Jacket (Size: M, Color: Blue)
2items - Fusion Backpack
Shipment - Fixed $25.00
Address: Main St, San Jose, CA 95131 United States
2. Go to Magento as admin
3. Create three invoices:
Invoice 1 - Olivia 1/4 Zip Light Jacket - 1 qty with the shipment;
Invoice 2 - Fusion Backpack - 2 qty;
Invoice 3 - Olivia 1/4 Zip Light Jacket - 2 qty;
4. Create two shipments:
Shipment 1 - Olivia 1/4 Zip Light Jacket - 3 qty;
Shipment 2 - Fusion Backpack - 2 qty;
5. Go to Invoice 1, click Credit Memo, select all items and click Refund.
6. Go to Invoice 2, click Credit Memo, select all items and click Refund.

**Actual result:**
Correct created Credit Memos(without any errors in logs) .
![image](https://user-images.githubusercontent.com/51680850/63010134-7e977780-be8e-11e9-89bd-5b8066225fb8.png)

So i have to close this issue. 
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-14 09:25 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Paypal
