### ISSUE TITLE
Messages are not added correctly when pressing Add To Cart Button (without redirect to Cart) multiple times

### ISSUE THREAD

**Issue by bytes-max** [magento/magento2#35514] opened 2022-05-22 13:51 UTC
### Preconditions and environment

- Magento version: 2.4.4
- Anything else that would help a developer reproduce the bug:
1. disable redirect to Cart upon pressing add2cart button

### Steps to reproduce

1. create a product 
2. make it available in the FE 
3. Click the button "Add 2 Cart" once
4. click the button "Add 2 Cart" once, again

### Expected result

2 individual messages are being shown above the PDP content

### Actual result

Messages flash, and new messages aren't shown at all, unless you wait some time and press the button again (but only 1 message is shown)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-25 09:29
Hi @nopenopenope ,
Thank you for reporting and collaboration. Verified the behavior on magento 2.4-develop branch however, this seems to be an expected behavior but not a bug.
Since the message "You added product to your shopping cart." is displayed on clicking "Add to cart" for the 1st time, same message is displayed but not removed when button is clicked again for 2nd time. User experience will be effected if the same message should be displayed again for every click on "Add to cart" button 
Also its no where mentioned in the docs to display 2 individual messages on PDP.
![image](https://user-images.githubusercontent.com/60198231/170228636-1bf3883e-4b1f-4f4b-8d3b-4b113a540e73.png)
Please recheck the behavior on Magento 2.4-develop and provide any reference doc/proofs that supports this to be valid bug.
Thank you.

**Comment by engcom-November** [comment] 2022-06-08 07:07
Hi @nopenopenope ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-08 07:07 UTC
Labels: Issue: needs update
