### ISSUE TITLE
CMYK images are rendered with inverted colors

### ISSUE THREAD

**Issue by ioweb-gr** [magento/magento2#22375] opened 2019-04-16 17:20 UTC
### Preconditions (*)
1. Magento 2.3.1
2. ImageMagick as image processor
3. One CMYK image

### Steps to reproduce (*)
1. Install Magento 2.3.1 and use ImageMagick as image processor. 
2. Create a product and upload an image in CMYK color profile. 
3. The image displays properly in backend in product edit page because it shows the original image.
4. Check the product in frontend and notice that the image is resized via ImageMagick but the colors are inverted. 

### Expected result (*)
1. The image displays properly would be ideal but at least the user should be warned that the image is saved in a color space that Magento 2 cannot handle so it will not be be converted correctly.

### Actual result (*)
1. Image is resized but the colors are inverted. 
![image](https://user-images.githubusercontent.com/20220341/56230632-61d86800-6085-11e9-9191-f12d6193db47.png)

Unfortunately the users of an eshop are not usually proficient in the handling of apps like photoshop and they will probably upload lots of images they downloaded from the web or from their providers. Thus it's very possible that they will encounter situations like this. 

I think the system should at least warn them that it cannot process the image correctly if it can't handle the conversion.
Perhaps Imagick::transformImageColorspace could be used to handle it silently? 
 
Here's a sample image
![madrid-orange_1_1](https://user-images.githubusercontent.com/20220341/56230294-a1eb1b00-6084-11e9-9f00-2cd8fcadc2ed.jpg)

**Comment by ioweb-gr** [comment] 2019-04-16 17:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-16 17:21
Hi @ioweb-gr. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-16 17:21
Hi @ioweb-gr, here is your [Magento instance](https://i-22375-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22375-2-3-develop.instances.magento-community.engineering/admin](https://i-22375-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ioweb-gr** [comment] 2019-04-16 17:27
Reproduced on Magento 2.3-develop instance

**Comment by dmytro-ch** [comment] 2019-04-17 07:02
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-04-17 07:02
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-04-17 07:03
Hi @dmytro-ch, here is your [Magento instance](https://i-22375-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22375-2-3-develop.instances.magento-community.engineering/admin](https://i-22375-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-04-17 07:21
:white_check_mark: Confirmed by @dmytro-ch 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99233` were created

**Issue Available**: @dmytro-ch, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krisdante** [comment] 2019-10-24 14:04
@magento I am working on it

**Comment by tdgroot** [comment] 2020-06-16 09:48
@magento I am working on it

**Comment by krisdante** [comment] 2020-06-17 09:35
@tdgroot the fix is ready. The test is missing because it's tricky to make. 
Do you have an idea of how to make a valid test? The difference can be spotted mainly with eyes.

**Comment by tdgroot** [comment] 2020-06-19 10:06
@krisdante I covered it with unit tests, see #28809.

**Comment by magento-engcom-team** [comment] 2020-10-06 22:20
Hi @ioweb-gr. Thank you for your report. 
The issue has been fixed in magento/magento2#28809 by @tdgroot in 2.4-develop branch
Related commit(s):
 - [5fd973325272198f1644c2f4be15490acc0d5518](https://github.com/magento/magento2/commit/5fd973325272198f1644c2f4be15490acc0d5518)
 - [4d801c57e0c3774a28017b034066be5bf5965976](https://github.com/magento/magento2/commit/4d801c57e0c3774a28017b034066be5bf5965976)
 - [50159281f9bb3569d29ee21adab386f8f0ed92b3](https://github.com/magento/magento2/commit/50159281f9bb3569d29ee21adab386f8f0ed92b3)
 - [2cc29b7aafa21aefcb818a7387a6340b92e9c953](https://github.com/magento/magento2/commit/2cc29b7aafa21aefcb818a7387a6340b92e9c953)
 - [16962dd07efcdb682b1dbbc8eb9be0c6458f003a](https://github.com/magento/magento2/commit/16962dd07efcdb682b1dbbc8eb9be0c6458f003a)
 - [a4bfb729e7d1932b8492544b071ca3bd2e0920c6](https://github.com/magento/magento2/commit/a4bfb729e7d1932b8492544b071ca3bd2e0920c6)
 - [82565e8df05d9fcc0a735183a60b3c6a11218e41](https://github.com/magento/magento2/commit/82565e8df05d9fcc0a735183a60b3c6a11218e41)
 - [9efd600982a6ee715bb885397d4effea7378abf2](https://github.com/magento/magento2/commit/9efd600982a6ee715bb885397d4effea7378abf2)
 - [8b251e467c663d689f2a475007188cb6987cc17c](https://github.com/magento/magento2/commit/8b251e467c663d689f2a475007188cb6987cc17c)
 - [efb7354ff5f09b7007b924c866547e47480790d0](https://github.com/magento/magento2/commit/efb7354ff5f09b7007b924c866547e47480790d0)
 - [4cc567dfbbc031e3b7bd8d1f918b2aec2fb85268](https://github.com/magento/magento2/commit/4cc567dfbbc031e3b7bd8d1f918b2aec2fb85268)

The fix will be available with the upcoming 2.4.2 release.

**Closed as completed by magento-engcom-team** 2020-10-06 22:20 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Framework/Image, Fixed in 2.4.x, Progress: done
