### ISSUE TITLE
Cache Identifier different in load, save, remove functions

### ISSUE THREAD

**Issue by CptCharlesG** [magento/magento2#38930] opened 2024-07-13 13:20 UTC
### Preconditions and environment

- Magento version 2.4.7-p1
- FPC enabled

### Steps to reproduce

0. Set up a multistore environment (needed?)
1. Enable FPC
2. Open a page twice

To debug: 
1. print/log $identifier parameters in load(), save(), remove() functions in Magento\Framework\Cache\Frontend\Decorator\Bare.php

### Expected result

x-magento-cache-debug: HIT

$identifier parameter for load(), save(), remove() should be the same

### Actual result

x-magento-cache-debug: MISS

Identifier example:
- load: MAGE_RUN_TYPE=store|MAGE_RUN_CODE=default|01fe946b0961551dcd1aeb82dcf5a8854bf64480
- save: 01fe946b0961551dcd1aeb82dcf5a8854bf64480

### Additional information

There were some bigger changes in the Page Cache module recently.

In module-page-cache/etc/di.xml there is a plugin for Magento\Framework\App\PageCache\Identifier: Magento\PageCache\Model\App\CacheIdentifierPlugin which adds the addition parameters.
This Identifier class is used for load() - and possibly for remove() but I am unsure.

For save() Magento\PageCache\Model\App\Request\Http\IdentifierForSave is used (in Magento\Framework\App\PageCache\Kernel argument as defined in module-page-cache/frontend/etc/di.xml) but there is no plugin for this class that would prepend the same runtype and store parameters.

As a workaround I have removed the additional parameters for now, as TTFB increased so much that is affected SEO.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by CptCharlesG** [comment] 2024-07-13 13:21
@magento give me 2.4-develop instance

**Comment by CptCharlesG** [comment] 2024-07-13 13:36
No x-magento-cache-debug in demo response header, cannot proceed.

**Comment by engcom-November** [comment] 2024-07-16 07:54
Hello @CptCharlesG,

Not able to reproduce this on 2.4-develop.
We have the same cache code for save and load method:
```
method load : diConfig59be6f2344e3bc4f606fa39531c6ac47 [] []
method save : diConfig59be6f2344e3bc4f606fa39531c6ac47 [] []
```

And `X-Magento-Cache-Debug` status is HIT.

This might have been fixed in the latest 2.4-develop branch.

Let us know if we are missing anything.

Thank you.

**Comment by CptCharlesG** [comment] 2024-07-16 11:06
I believe the problem occurs only when the following parameters are set in nginx.config (for multistore, multidomain environment):
```
    fastcgi_param  MAGE_RUN_TYPE $MAGE_RUN_TYPE;  # eg. store
    fastcgi_param  MAGE_RUN_CODE $MAGE_RUN_CODE;  # eg. default
```

As Magento\PageCache\Model\App\CacheIdentifierPlugin add the prefix only if these (and design) exist.

@engcom-November may you please test it this way?

**Comment by hostep** [comment] 2024-07-16 19:45
I believe this was reported before in https://github.com/magento/magento2/issues/38626, the last comment points to some commits that may fix this issue. But there was also this PR that attempted to fix it: https://github.com/magento/magento2/pull/38646
I don't know which changes exactly contain the proper fix, it's kind of confusing.

**Comment by CptCharlesG** [comment] 2024-07-17 12:41
@hostep 
Indeed, it looks the same issue, and seemingly it was corrected.
I was searching for cache related issues before opening this one, but only in Open state and these were already Closed.

**Comment by engcom-November** [comment] 2024-07-19 12:41
Hello @CptCharlesG,

We are closing this issue as it's been already been fixed, here is the [commit](https://github.com/magento/magento2/commit/315dd6817f4cc42728ae3b2b10c4c233891b8d64).

**Closed as completed by engcom-November** 2024-07-19 12:41 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.7-p1
