### ISSUE TITLE
Admin Sales Grid Bug: Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by Madhankumar-ox** [magento/magento2#38361] opened 2024-01-18 10:18 UTC
### Preconditions and environment

- Magento version: 2.4.6 p3
- Issue Location: Admin side
- Problem Description: When opening the order grid, this issue occurs.

### Steps to reproduce

Create new user.
Assign sales tab - order access.
When clicking the Order tab, the following issue is displayed.

### Expected result

Display order grid

### Actual result

Error: Something went wrong with processing the default view and we have restored the filter to its original state.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by andrewbess** [comment] 2024-01-18 11:48
@magento give me 2.4.6-p3 instance

**Comment by andrewbess** [comment] 2024-01-18 12:07
@magento give me 2.4.6 instance

**Comment by andrewbess** [comment] 2024-01-18 12:50
Hello @Madhankumar-ox 
Thank you for collaboration
I tried to reproduce it on the vanilla Magento and I cannot to reproduce it.
Maybe you have 3rd-party extension that provokes this problem
Could you please check logs and provide more information
Thank you in advance.

**Comment by gabrieldagama** [comment] 2024-01-18 22:26
https://github.com/magento give me 2.4.6-p3 instance

**Comment by gabrieldagama** [comment] 2024-01-18 22:26
@magento give me 2.4.6-p3 instance

**Comment by engcom-Bravo** [comment] 2024-01-19 05:46
Hi @Madhankumar-ox,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.


**Can you please check this solution** :


Please check "catalog_product_entity" table in the database for any sku 's having NULL value and update them:
UPDATE catalog_product_entity SET sku='' WHERE sku IS NULL;
Check if the user is having very restricted Access to the magento backend and grant users access to the product catalog / orders that may fix this issue.
Run the query: TRUNCATE ui_bookmark; this will reset the grid back to it's default and stop the infinite load.

Thanks

**Comment by engcom-Bravo** [comment] 2024-01-30 04:37
Hi @Madhankumar-ox,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38361#issuecomment-1899807315 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-02-05 05:42
Hi @Madhankumar-ox,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2024-02-05 05:42 UTC
Labels: Issue: needs update, Reported on 2.4.6-p3
