### ISSUE TITLE
Cart Coupon returns "Invalid" if a product is added that has an expired special price

### ISSUE THREAD

**Issue by apb-github** [magento/magento2#6387] opened 2016-08-29 21:33 UTC
### Preconditions

env1: DO ubuntu 16.04 / php5.5 / mysql 5.6 / Magento2.0.8
env2: Nexcess centos6.8 final / php 5.5 / mysql 5.6 / Magento2.0.8
### Steps to reproduce
1.  Create product with Advanced Price Pricing > Special Price [set a price], From Date [set date before today], To Date [set date before today]
2.  Create Cart rule... $ off for cart total over $$$, % off for any cart, etc
3. Add product with expired Special price to cart such that it meets the coupon requirements
4. Attempt to apply coupon
5. wonder if there could be a more opaque error than: "The coupon code "HAPPYSUMMER" is not valid."
### Expected result
1. Coupon should apply, even if there is an existing or pre-existing special price unless specifically excluded
### Actual result
1. Coupon is "invalid"
### Work Around
1. Delete Special Price, From, To dates, save product

**Comment by claridgicus** [comment] 2016-11-02 00:43
Any progress on this issue?

**Comment by apb-github** [comment] 2016-11-02 03:46
we finally moved to 2.1.x and the issue seems to have been fixed... or something changed anyway. It appears to no longer be an issue in this branch.

Edit to add: we also moved to php 7.0, so that may have been part of the solution. Don't know.

**Comment by oleg-onufer** [comment] 2017-06-22 15:34
Hi @apb-github 
I could not reproduce the issue.
Is this issue actual for you or we can close it?
If  this issue actual for you can you check your problem on the latest version of Magento 2?

**Comment by magento-engcom-team** [comment] 2017-09-13 21:06
@apb-github thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please provide more details regarding your environment, or try to reproduce this issue on a clean installation or latest release.

**Closed as completed by magento-engcom-team** 2017-09-13 21:06 UTC
Labels: bug report, Progress: needs update, Component: Tax, Component: Checkout, Issue:  Cannot Reproduce, Issue: Format is valid
