### ISSUE TITLE
During indexer:reindex catalogsearch_fulltext no products are listed in categories

### ISSUE THREAD

**Issue by heldchen** [magento/magento2#6308] opened 2016-08-24 09:17 UTC
while the "Catalog Search" is being reindexed, all category listing pages show "We can't find products matching the selection.". as soon as the reindex process is completed, the categories are browsable again.
### Preconditions
1. CE 2.1.0
### Steps to reproduce
1. create a large sized sample database with enough products that the fulltext reindex takes a while. ours has around 20'000 products with lots of attributes and takes 4min17s on a beefy server to reindex
2. `php bin/magento indexer:reindex catalogsearch_fulltext`
3. meanwhile, browse the fronted categories
### Expected result
1. the categories list products during reindexing
### Actual result
1. all categories show a "We can't find products matching the selection." message

**Comment by senthilengg** [comment] 2016-08-24 09:47
@heldchen try **php bin/magento indexer:reset** and then run **php bin/magento indexer:reindex**

**Comment by heldchen** [comment] 2016-08-24 10:30
@senthilengg that does not make any difference, products are still not listed in categories during the catalogsearch_fulltext run

**Comment by sevos1984** [comment] 2016-09-12 14:11
I have this issue with FPC turned off. With page cache catalog is available during reindex. This looks like expected behavior.

**Comment by sevos1984** [comment] 2016-09-26 12:17
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-09-26 12:17 UTC
Labels: bug report, Progress: needs update, Component: Search

**Comment by heldchen** [comment] 2016-09-26 12:23
the issue still exists and is a regression compared to magento1

**Comment by heldchen** [comment] 2016-09-26 12:27
reopened as #6754
