### ISSUE TITLE
Unable to checkout 2.4-develop branch locally with encrypted directory

### ISSUE THREAD

**Issue by kolaente** [magento/magento2#35520] opened 2022-05-23 10:58 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Prerequesites: Have an encrypted home directory under ubuntu 20.04.04.

1. Clone this repo
2. Run `git checkout 2.4-develop`

### Expected result

The `2.4-develop` branch is checked out successfully.

### Actual result

```
error: cannot stat 'dev/tests/acceptance/tests/_data/adobe-base-image-long-name-image-long-name-image-long-name-image-long-name-image-long-name-image-long-name-image-long-name-image-long-name-image-long-name.jpg': File name too long
error: could not detach HEAD
```

### Additional information

Probably related to https://github.com/magento/magento2/issues/29377 and https://github.com/magento/magento2/issues/26728

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-05-30 06:28
@magento give me 2.4-develop instance

**Comment by kolaente** [comment] 2022-05-30 08:37
@engcom-Dash how do you want to test this with a develop instance? This is a problem with git checkout.

**Comment by engcom-November** [comment] 2022-05-30 15:45
Hi @kolaente,
Thank you for reporting and collaboration. However we are not able to reproduce this issue with provided steps. Can you please recheck and elaborate steps about in which way home directory is encrypted and other missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-06-13 14:43
Hi @kolaente ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-13 14:43 UTC
Labels: Issue: needs update

**Comment by pointia** [comment] 2022-08-09 14:13
@engcom-November please reopen the ticket since the problem is in M2.4.5 as well if you have Magento installed on an encrypted device. 

Here is the explanation https://bugs.launchpad.net/ecryptfs/+bug/344878

The same problem already existed in an older version as well. Encrypting devices makes a lot of sense to me so this should work.

**Comment by Linek** [comment] 2022-12-14 13:00
@engcom-November I confirm the issue is back on 2.4.5

**Comment by maerroc** [comment] 2024-01-26 11:23
@engcom-November please give this some priority. Encrypted devices are standard in serious companies nowadays and this one file is making development on such a device a real pain. Thank you!

**Comment by isxam** [comment] 2026-01-19 21:10
had the same issue, fixed by ignoring the file using composer plugin
https://github.com/tons-of-limes/composer-plugin-filename-too-long

```
composer global require tonsoflimes/plugin-filename-too-long
composer global config --no-plugins allow-plugins.tonsoflimes/plugin-filename-too-long true
composer global config --json --merge extra.tonsoflimes/plugin-filename-too-long.allow '{"magento/magento2-base": true}'
```

and then run `composer install` in the magento root directory
