### ISSUE TITLE
Logged in customer is marked as guest in newsletter subscribers

### ISSUE THREAD

**Issue by jokeputs** [magento/magento2#33606] opened 2021-07-27 14:16 UTC
### Preconditions (*)

1. I can reproduce this issue on a Magento 2.4.2 installation.

### Steps to reproduce (*)

1. Register as a new cutomer without subscribing to the newsletter for example with the email address new.customer@example.com
2. Sign out
3. Subscribe to the newsletter using the same emailadress as the newly registered customer (new.customer@example.com) 

### Expected result (*)

1. In the admin in Marketing > Newsletter Subscribers I expect the news subscriber (new.customer@example.com) to be marked as customer not as guest
2. When I sign in as new.customer@example.com I see that I'm subscribe to the newsletter in my customer dashboard

### Actual result (*)

1.  In the admin in Newsletter Subscribers the subscriber new.customer@example.com is marked as guest
2. When I sign in as new.customer@example.com I see that I'm not subscribed to the newsletter in my customer dashboard
3. As the customer new.customer@example.com I cannot subscribe to the newsletter anymore. My changes are not saved.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jokeputs** [comment] 2021-07-27 14:17
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2021-07-28 05:39
Verified the issue on Magento 2.4-develop branch and cannot able to reproduce the issue with provided steps:
**Steps performed:**
1. Created a new Customer Account from Front-end without Signing up for Newsletter
2. Signout
3. Subscribed to News Letter for the same email address from Admin - Customers Dashboard (Admin - Customers - All Customers - Actions)
4. Admin - Marketing - Newsletter Subscribers - > No issue: Type is Customer and Status is Subscribed
5. Login to Frontend using same email id - **No issue**: Displayed as Subscribed
**Note:** Cannot able to reproduce this issue for newly created account from frontend/admin without subscribing to Newsletter - Singout and signin again using same customer - Subscribed to Newsletter from frontend - No issue: Marketing - Newsletter Subscribers - Type is Customer and Status is Subscribed.
Also note, we cannot create a new customer account again using newly created account to subscribe for newsletter as newly created customer
![image](https://user-images.githubusercontent.com/60198231/127269171-8ee494cd-f956-4e3b-88cf-892bc6f809ee.png)

@jokeputs, kindly recheck and elaborate the steps to reproduce (specific missing configuration details) to reproduce the issue.
Thank you.

**Comment by engcom-November** [comment] 2021-08-11 06:30
@jokeputs, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-11 06:30 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.2
