### ISSUE TITLE
Magento ver. 2.4.0 Cart Price Rules not working on selection of multiple product in cart

### ISSUE THREAD

**Issue by vermarajesh60** [magento/magento2#33146] opened 2021-06-04 08:08 UTC
We are trying to create Cart Price Rules 5% discount on every product only for prepaid orders.

![image](https://user-images.githubusercontent.com/85337619/120767722-14efce00-c539-11eb-9999-65bdd9d710a2.png)
![image](https://user-images.githubusercontent.com/85337619/120767820-32bd3300-c539-11eb-9f81-7d3178ffe3ab.png)
![image](https://user-images.githubusercontent.com/85337619/120768490-d4dd1b00-c539-11eb-906c-b8d3d2bf3001.png)

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2021-06-05 06:21
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2021-06-05 07:06
Hello @vermarajesh60,
I have verified this issue as per steps and attached the screenshot. Coupon code is applied on all prepaid payment method except the Cash on delivery payment method.

See attached the screenshot:
![image](https://user-images.githubusercontent.com/24711761/120883354-48466180-c5fa-11eb-8ce4-c05d36cbae7c.png)

![image](https://user-images.githubusercontent.com/24711761/120883378-63b16c80-c5fa-11eb-8173-44a3cf24287a.png)

![image](https://user-images.githubusercontent.com/24711761/120883370-56947d80-c5fa-11eb-875b-e3f686b536b6.png)

![image](https://user-images.githubusercontent.com/24711761/120883394-85125880-c5fa-11eb-9bd3-d00b916185d8.png)

Admin Cart price rule configuration:

![image](https://user-images.githubusercontent.com/24711761/120883400-922f4780-c5fa-11eb-845f-e96533b1eb1c.png)

@vermarajesh60 - Let me know which issue you are facing. Please update the actual result and expected result.

Thanks.

**Comment by vermarajesh60** [comment] 2021-06-06 06:20
Hi Ajij,

Thanks for your support.

Just add one more product in the cart and you will see the problem, in the
below screen discount should be  139.73.
[image: image.png]
.

**Comment by ajijshekh123** [comment] 2021-06-08 12:36
Okay, Let me see again this issue and Update it @vermarajesh60

**Comment by vermarajesh60** [comment] 2021-06-09 05:35
Hi Ajij,

Have you found this ?.

**Comment by vermarajesh60** [comment] 2021-06-11 06:43
Hi Ajij,

Have you found anything to solve this problem.

**Comment by ajijshekh123** [comment] 2021-06-24 04:42
Hello @vermarajesh60 ,
Sorry for the later response. This weekend I'll review again this issue and update the status.
Thanks.

**Comment by ajijshekh123** [comment] 2021-08-02 05:59
Hi @vermarajesh60,
I tried with one more product but the Issue is not able to reproduce.
I am closing this issue If you have reproduced it again you can reopen it.
Thanks.

**Closed as completed by ajijshekh123** 2021-08-02 05:59 UTC
Labels: Progress: needs update, Area: Frontend, Issue:  Cannot Reproduce, Component: Rule, Issue: ready for confirmation
