### ISSUE TITLE
Unable to send the cookie. Size of 'mage-messages' is 13831 bytes in reports

### ISSUE THREAD

**Issue by MTheProgrammer** [magento/magento2#8276] opened 2017-01-25 11:42 UTC
### Preconditions

1. Magento CE 2.0.11

### Steps to reproduce

1. Login as customer
2. Change email to an existing one of another customer
3. Submit form

### Expected result

1. Should show an error message like 'Email already in use'

### Actual result

1. On production server: 503 error

> Unable to send the cookie. Size of 'mage-messages' is 13831 bytes.

This limit is set in Magento\Framework\Stdlib\Cookie\PhpCookieManager::MAX_COOKIE_SIZE
2. On developer mode: just page reload and no error message displayed for customer.

This error is caused by returned stack trace that is too large for the cookie limit (4096 bytes) in Magento\Customer\Controller\Account\EditPost::execute()

```
       try {
                $this->customerRepository->save($customerCandidateDataObject);
            } catch (AuthenticationException $e) {
                $this->messageManager->addError($e->getMessage());
            } catch (InputException $e) {
                $this->messageManager->addException($e, __('Invalid input'));
            } catch (\Exception $e) {
                $message = __('We can\'t save the customer.')
                    . $e->getMessage()
                    . '<pre>' . $e->getTraceAsString() . '</pre>';
                $this->messageManager->addException($e, $message);
            }
```

**Comment by developer-lindner** [comment] 2017-01-25 16:19
@MTheProgrammer Magento CE 2.0.11 seriously? Update to latest version first than update or close this ticket. Creating tickets for an outdated version is very counterproductive.

**Comment by Aldecoez** [comment] 2017-01-26 10:41
@developer-lindner As I can see 2.0.11 is the latest version from 2.0 branch. If u think that 2.1 is newer version of 2.0 u're in big mistake.

**Comment by miakusha** [comment] 2017-01-30 12:32
Hi @MTheProgrammer thank for report 
We've created internal ticket MAGETWO-63830 to address this issue.
Issue exist only in 2.0 versions You can try to update to 2.1 versions and the problem will be solved

**Comment by orlangur** [comment] 2017-09-19 22:02
Closing as the fix for this issue is already available on Magento 2.1.0 and 2.2.0 branches.

Backports to 2.0.x are not processed due to its End of Life in November.

**Closed as completed by orlangur** 2017-09-19 22:02 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Fixed in 2.1.x, Fixed in 2.2.x, Issue: Format is valid

**Comment by valugi** [comment] 2019-09-18 15:06
@orlangur  This happens in 2.2.8.

> Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException: Noticed exception 'Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException' with message 'Unable to send the cookie. Size of 'mage-messages' is 6775 bytes.' in /var/www/magento2/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:215
in Magento\Framework\Stdlib\Cookie\PhpCookieManager::checkAbilityToSendCookie called at /var/www/magento2/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php (139)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager::setCookie called at /var/www/magento2/vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php (121)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager::setPublicCookie called at /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php (58)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager\Interceptor::___callParent called at /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php (138)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager\Interceptor::Magento\Framework\Interception\{closure} called at /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php (153)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager\Interceptor::___callPlugins called at /var/www/magento2/generated/code/Magento/Framework/Stdlib/Cookie/PhpCookieManager/Interceptor.php (26)
in Magento\Framework\Stdlib\Cookie\PhpCookieManager\Interceptor::setPublicCookie called at /var/www/magento2/vendor/magento/module-theme/Controller/Result/MessagePlugin.php (140)
in Magento\Theme\Controller\Result\MessagePlugin::setCookie called at /var/www/magento2/vendor/magento/module-theme/Controller/Result/MessagePlugin.php (95)
in Magento\Theme\Controller\Result\MessagePlugin::afterRenderResult called at /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php (146)
in Magento\Framework\Controller\Result\Redirect\Interceptor::Magento\Framework\Interception\{closure} called at /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php (153)
in Magento\Framework\Controller\Result\Redirect\Interceptor::___callPlugins called at /var/www/magento2/generated/code/Magento/Framework/Controller/Result/Redirect/Interceptor.php (26)
in Magento\Framework\Controller\Result\Redirect\Interceptor::renderResult called at /var/www/magento2/vendor/magento/framework/App/Http.php (140)
in Magento\Framework\App\Http::launch called at /var/www/magento2/vendor/magento/framework/App/Bootstrap.php (257)
in Magento\Framework\App\Bootstrap::run called at /var/www/magento2/pub/index.php (37)

**Comment by orlangur** [comment] 2019-09-22 19:42
@valugi it shouldn't. Error message is logged but does not cause `503 error`.

**Comment by kervin** [comment] 2019-10-08 05:40
I am getting the same issue in 2.3.1, it is causing checkout to throw 503 error.

**Comment by kervin** [comment] 2019-10-08 05:41
Any updates on this?

**Comment by orlangur** [comment] 2019-10-08 10:24
@kervin please report a new issue or reopen this one providing necessary details to reproduce.

**Comment by kervin** [comment] 2019-10-08 10:26
Sorry, issue on our site.. Magento all good.

**Comment by orlangur** [comment] 2019-10-08 10:40
@kervin thanks for quick response. Sometimes it happens, no problem)

**Comment by MerikMag** [comment] 2019-10-22 21:46
> Sorry, issue on our site.. Magento all good.

@kervin , can you explain, what was your issue? We are facing the same on 2.3.2

**Comment by kervin** [comment] 2019-10-23 06:23
It was a module throwing a large error message on add to cart.

An error message larger than the MAX_COOKIE_SIZE.

**Comment by mvalenziano** [comment] 2019-11-12 10:42
@kervin how did you debug that ? the logs don't help at all

**Comment by kervin** [comment] 2019-11-12 10:44
Try to log the message / log back trace.. Then figure out which module is throwing this error.

It might be an observer on add to cart.

**Comment by balabany** [comment] 2022-03-03 11:35
I am using the latest Magento 2 and having the same issue. Anyone knows how to fix? When I am in a cart page and clicking to Proceed to Checkout button, it gives me the following error.

1 exception(s):
Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 23854 bytes.

Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 23854 bytes.
<pre>#1 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie() called at [vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:123]
#2 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:140]
#3 Magento\Theme\Controller\Result\MessagePlugin->setCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:97]
#4 Magento\Theme\Controller\Result\MessagePlugin->afterRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:146]
#5 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
#7 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#8 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#9 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#10 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>

**Comment by Garde85** [comment] 2022-03-18 09:34
> I am using the latest Magento 2 and having the same issue. Anyone knows how to fix? When I am in a cart page and clicking to Proceed to Checkout button, it gives me the following error.
> 
> 1 exception(s): Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 23854 bytes.
> 
> Exception #0 (Magento\Framework\Stdlib\Cookie\CookieSizeLimitReachedException): Unable to send the cookie. Size of 'mage-messages' is 23854 bytes.
> 
> #1 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setCookie() called at [vendor/magento/framework/Stdlib/Cookie/PhpCookieManager.php:123]
> #2 Magento\Framework\Stdlib\Cookie\PhpCookieManager->setPublicCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:140]
> #3 Magento\Theme\Controller\Result\MessagePlugin->setCookie() called at [vendor/magento/module-theme/Controller/Result/MessagePlugin.php:97]
> #4 Magento\Theme\Controller\Result\MessagePlugin->afterRenderResult() called at [vendor/magento/framework/Interception/Interceptor.php:146]
> #5 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
> #6 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95]
> #7 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
> #8 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
> #9 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
> #10 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]

me too!

**Comment by i6media** [comment] 2022-03-22 08:38
Same here, Magento 2.4.3-p1:

"Unable to send the cookie. Size of 'mage-messages' is 4136 bytes."

**Comment by MTheProgrammer** [comment] 2022-03-22 12:59
This won't be fixed. At least the size limit can't be increased due to RFC specification, section 6.1
http://www.ietf.org/rfc/rfc6265.txt

One solution which I have in mind is to trim mage-messages and log its content when it overflows the limit of 4096b.

**Comment by plastikschnitzer** [comment] 2022-04-06 10:03
Same here, error is back in Magento 2.4.3-p1 …

**Comment by hungryriz** [comment] 2022-05-27 03:09
same here in magento 2.4.3-p1

**Comment by PawanKumarN** [comment] 2022-07-05 17:13
same here in magento 2.4.3-p2

**Comment by duckchip** [comment] 2022-08-01 08:13
linking https://github.com/magento/magento2/issues/33611
