### ISSUE TITLE
configurable_options uses disabled products to populate the options

### ISSUE THREAD

**Issue by lsv** [magento/magento2#26111] opened 2019-11-29 10:16 UTC
### Preconditions (*)

1. magento/module-configurable-product-graph-ql: 100.3.1

### Steps to reproduce (*)

1. Create Configurable product which contains two Color configurations, for example, "Color1" and "Color2". 
2. Disable the "Color2" configuration.
3. Perform query:
``` graphql
{
  products(
    filter: {
      sku: {
        eq: "Configurable"
      }
    }
  ) {
    items {
      id
      attribute_set_id
      name
      sku
      type_id
      categories {
        id
      }
      ... on ConfigurableProduct {
        configurable_options {
          id
          attribute_id
          label
          position
          use_default
          attribute_code
          values {
            value_index
            label
          }
          product_id
        }
        variants {
          product {
            id
            name
            sku
            attribute_set_id
          }
        }
      }
    }
  }
}
```
### Expected result (*)
Disabled option should not be returned.
``` graphql
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
}
```

### Actual result (*)
Disabled "Color2" option is returned in the `configurable_options` section.
``` graphql
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                },
                {
                  "value_index": 5,
                  "label": "Color2"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by engcom-Bravo** [comment] 2019-12-20 09:03
Hello @lsv 
Thank you for reporting an issue.
Please, let me clarify if we understand the bug.
In our case, we have a Configurable product which contains two Color configurations, for example, _"Color1"_ and _"Color2"_. We disable the _"Color2"_ configuration and perform the following GraphQL query
```graphql
{
  products(
    filter: {
      sku: {
        eq: "Configurable"
      }
    }
  ) {
    items {
      id
      attribute_set_id
      name
      sku
      type_id
      categories {
        id
      }
      ... on ConfigurableProduct {
        configurable_options {
          id
          attribute_id
          label
          position
          use_default
          attribute_code
          values {
            value_index
            label
          }
          product_id
        }
        variants {
          product {
            id
            name
            sku
            attribute_set_id
          }
        }
      }
    }
  }
}
``` 
In the response, we get One enabled product _variant_, but we still get the **value index** of the disabed product
```graphql 
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                },
                {
                  "value_index": 5,
                  "label": "Color2"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
}
```
Is this the behavior you are reporting issue about?
Thank you

**Comment by lenaorobei** [comment] 2019-12-20 16:38
@engcom-Bravo thank you for the investigation. I updated ticket description with the expected result.

**Comment by magento-engcom-team** [comment] 2019-12-20 16:38
:white_check_mark: Confirmed by @lenaorobei 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29989` were created

**Issue Available**: @lenaorobei, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sedonik** [comment] 2020-01-23 00:17
Hi @lenaorobei ,

When I was investigating the issue faced with a problem that when we disable nested product and hide it in Collection of the Attribute it is disabled from Admin->Product->Configurations->Current Variations  Grid as well.

I propose to add additional parameter: 'product_status' wich will show is this value enabled or not.
So response will be similar to :

```
{
  "data": {
    "products": {
      "items": [
        {
          "id": 4,
          "attribute_set_id": 4,
          "name": "Configurable",
          "sku": "Configurable",
          "type_id": "configurable",
          "categories": [
            {
              "id": 3
            }
          ],
          "configurable_options": [
            {
              "id": 1,
              "attribute_id": "93",
              "label": "Color",
              "position": 0,
              "use_default": false,
              "attribute_code": "color",
              "values": [
                {
                  "value_index": 4,
                  "label": "Color1"
                  "product_status": "Enabled"
                },
                {
                  "value_index": 5,
                  "label": "Color2"
                  "product_status": "Disabled"
                }
              ],
              "product_id": 4
            }
          ],
          "variants": [
            {
              "product": {
                "id": 5,
                "name": "Configurable-Color1",
                "sku": "Configurable-Color1",
                "attribute_set_id": 4
              }
            }
          ]
        }
      ]
    }
  }
} 
```

I've created [PR](https://github.com/magento/magento2/pull/26503) with this implementation.

Could you check, please?

Thanks.

**Comment by sedonik** [comment] 2020-02-04 10:48
Hi @lenaorobei , @lsv

After some thinking, I've another solution: added a plugin that detects if an option is disabled, unset this variable from return array.
Could you check is it implemented correctly.
[New PR](https://github.com/magento/magento2/pull/26690)

Thanks.

**Comment by danielrenaud** [comment] 2020-05-07 21:21
Hi,
I'm not sure the expected behavior of this bug is correct. The variant is disabled, and as we would expect the `variant` entry is gone.
I understand how one would think that the `configurable_option` option should also be removed, but think about the case when we have 2 options for a product (e.g. size and color for a shirt). if the medium-blue shirt were disabled, should we disable Size: medium, or Color: blue (I don't think so). 
To me the current behavior seems correct, when a variant is disabled it is removed form the output, but the options should still be available.
cc @sedonik @sdzhepa

**Comment by danielrenaud** [comment] 2020-05-21 15:48
@sdzhepa Regarding my previous comment. Does it make sense? Should we close this issue?

**Comment by lenaorobei** [comment] 2020-05-21 15:53
@danielrenaud, yes, I've talked with product owner @nrkapoor and we agreed that this is not a bug.
Thank you.

**Closed as completed by lenaorobei** 2020-05-21 15:53 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: ConfigurableProductGraphQl, Triage: Dev.Experience, Reproduced on 2.4.x

**Comment by aligent-lturner** [comment] 2021-07-30 02:52
@magento give me 2.4-develop instance

**Comment by schmengler** [comment] 2021-11-26 09:07
Hello @nrkapoor 

> @danielrenaud, yes, I've talked with product owner @nrkapoor and we agreed that this is not a bug.
Thank you.

can you explain why? The effect is, that both a wrong amount of configuration options is shown if we use GraphQl for configurable products, as well as wrong pricing. IMHO this is not something that the frontend should care for to fix.

**Comment by pawel-siejba** [comment] 2022-04-01 11:59
> Hi, I'm not sure the expected behavior of this bug is correct. The variant is disabled, and as we would expect the `variant` entry is gone. I understand how one would think that the `configurable_option` option should also be removed, but think about the case when we have 2 options for a product (e.g. size and color for a shirt). if the medium-blue shirt were disabled, should we disable Size: medium, or Color: blue (I don't think so). To me the current behavior seems correct, when a variant is disabled it is removed from the output, but the options should still be available. Since this expectation doesn't carry through for more than 1 option, I don't think it should implemented for that special case. cc @sedonik @sdzhepa

Given that the medium-blue shirt is the only medium and the only blue shirt available, when it is disabled, then both of those options should disappear. If there are any other blue shirts available - you still should display the colour, same for the sizes.

It really does not seem like this is an expected behaviour. Disabling a product in Magento should mean that the customer has no way of seeing it on the frontend, and with the current behaviour - it just acts as if the product was enabled.

**Comment by schmengler** [comment] 2022-04-04 07:07
@lenaorobei @engcom-Bravo Seems like this went unnoticed. Is @nrkapoor still the product owner?

**Comment by adarshkhatri** [comment] 2023-08-28 06:35
Do we have any update on this? I thought it should be simple to not provide the option if it is disabled in GQL. Why do we not think this is not the issue? 

Because of this, we have to do a crazy loop to see if the returned `configurable_options` has any option that is not in the child product list. This should be handled in M2, not SF.
