### ISSUE TITLE
Problem rest ship order

### ISSUE THREAD

**Issue by migmax48** [magento/magento2#23694] opened 2019-07-14 13:29 UTC
Magento ver. 2.3.1 on AWS LightSail

I'm trying to execute REST WS to ship an order. When I execute the PHP code I receive the following error message: "**The entity that was requested doesn't exist. Verify the entity and try again**". Anyway order_id and item_id are correct.

this is my PHP code:

        $curl = curl_init();
        $data_string = json_encode($shipmentObject);
        $httpheader = array(
            'Authorization: Bearer '.$token,
            'Content-Type: application/json',
            'Accept: application/json',
            'Content-Length: '.strlen($data_string)
        );

        curl_setopt($curl, CURLOPT_URL, $hostname."/index.php/rest/V1/order/".$order_id."/ship");
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data_string);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_HTTPHEADER, $httpheader);
        curl_setopt($curl, CURLOPT_VERBOSE, true);
        $verbose = fopen('php://temp', 'w+');
        curl_setopt($curl, CURLOPT_STDERR, $verbose);

        $response = curl_exec($curl);
        rewind($verbose);
        $verboseLog = stream_get_contents($verbose);

        $err = curl_error($curl);
        curl_close($curl);

        echo "Verbose information:\n<pre>", htmlspecialchars($verboseLog), "</pre>\n";

        if ($err) {
            throw new Exception($err);
        } else {
            return json_decode($response, true);
        }

Verbose Output from curl:

Verbose information:

* Expire in 0 ms for 6 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 1 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
* Expire in 0 ms for 1 (transfer 0x7f9114048800)
*   Trying 3.121.71.177...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x7f9114048800)
* Connected to 3.121.71.177 (3.121.71.177) port 80 (#0)
> POST /index.php/rest/V1/order/8/ship HTTP/1.1
Host: 3.121.71.177
Authorization: Bearer rupxc379v44mq294c2m5r09ajwnzh80z
Content-Type: application/json
Accept: application/json
Content-Length: 136

* upload completely sent off: 136 out of 136 bytes
< HTTP/1.1 404 Not Found
< Date: Sun, 14 Jul 2019 13:26:35 GMT
< Set-Cookie: PHPSESSID=epdlqrcrbktkme9lmjhkskqh39; expires=Sun, 14-Jul-2019 14:26:36 GMT; Max-Age=3600; path=/; domain=3.121.71.177; HttpOnly
< X-Frame-Options: SAMEORIGIN
< Vary: Cookie
< X-UA-Compatible: IE=edge
< Content-Type: application/json; charset=utf-8
< Pragma: no-cache
< Expires: -1
< Cache-Control: no-store, no-cache, must-revalidate, max-age=0
< Content-Length: 91
< Connection: keep-alive
< 
* Connection #0 to host 3.121.71.177 left intact

**Comment by engcom-Charlie** [comment] 2019-10-10 09:05
Hello @migmax48 
We are not able to reproduce this issue on the lates 2.3-develop branch.
So i have to close this issue.
If you still faced this issue on `2.3-develop` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).
Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-10-10 09:05 UTC
Labels: Issue: Format is not valid
