### ISSUE TITLE
Magento 2 When we are try to update the custom attribute for the product then the default store price updated to other store

### ISSUE THREAD

**Issue by vanchi-nathan** [magento/magento2#12301] opened 2017-11-16 10:16 UTC
When we are try to update the custom attribute for the product then the default store price updated to other stores for the same products. 
We are working with pro-grammatically bulk product uploads. We are processing the data from CSV file. here we are working with single web site and multiple store view. eg: IND, USD.... etc. Our csv file keeps different price for different store view and this is done good. After that we are try to update a custom attribute value for all products with updated information. After couple of hours we noticed that default store price is automatically updated to others stores for all processed products. 
We also tested this with multiple times and it is repeating / reproducing each time. 

I'm not sure.
- This is happen only when we are try to update only custom attribute value.
- This is not happen when we are try to update custom attribute value as well as all store price.

### Preconditions

1. Magento 2.4-develop
2. Catalog Price Scope=Website (Store->Configuration->Catalog->Price)

### Steps to reproduce
**Notice:** Custom attribute is not necessary in this scenario
- Create Second Website
![image](https://user-images.githubusercontent.com/51681379/72153880-c8da4180-33b7-11ea-8095-8e389ce3066a.png)
- Create product with different price per webiste
- Run code snippet to modify Stock Status for Second Website view
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load(// Some Product Id //);
$_product->setStatus(\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED);
$_product->setStoreId(// Some Store ID //);
$_product->save();
```
### Expected result
This should update only mentioned attribute value not price

### Actual result
This will updating mentioned attribute value and also merging default store price to all store instead of different store price
![image](https://user-images.githubusercontent.com/51681379/72154096-6897cf80-33b8-11ea-94b3-4829f3754508.png)

Please try to give update on this asap..

Thanks

Please use below code to reproduce this.

public function updateProductStock($productId,$rawdata){
	try{
	$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
	$objectManager = $bootstrap->getObjectManager();
	$state = $objectManager->get('Magento\Framework\App\State');
	$state->setAreaCode('frontend');
	$_product = $this->_product->load($productId);
	$WebsiteIds	=	"";
	if($rawdata[18] !=""){ $WebsiteIds[]	=	12; }
	if($rawdata[19] !=""){ $WebsiteIds[]	=	13; }
	if($rawdata[20] !=""){ $WebsiteIds[]	=	1; }
	if($rawdata[21] !=""){ $WebsiteIds[]	=	14; }
	$WebsiteId[]	=	1;
	$_product->setWebsiteIds($WebsiteId);
	if($_product->save()){
			$productsizings	=	$rawdata[31];
			if($productsizings == 1){
				$productsizings		=	'one size';
			}
			if(in_array(strtolower($productsizings),$aproduct_sizing)){
				$aproduct_sizing_key	= array_search(strtolower($productsizings),$aproduct_sizing);
			}
			if(in_array(12,$WebsiteIds)){
				$objectManager->create('Magento\Catalog\Model\Product')
					->load($_product->getId())
					->setStoreId(12)
					->setProductSizing($aproduct_sizing_key)
					->save();
			}
			if(in_array(13,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(13)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			if(in_array(1,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(1)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			if(in_array(14,$WebsiteIds)){
			$objectManager->create('Magento\Catalog\Model\Product')
				->load($_product->getId())
				->setStoreId(14)
				->setProductSizing($aproduct_sizing_key)
				->save();
			}
			date_default_timezone_set("Asia/Kuala_Lumpur");
			$logger->info('product "'.$_product->getSku().'" updated successfully');
		}
		date_default_timezone_set("Asia/Kuala_Lumpur");
		$logger->info('product "'.$rawdata[39].'" updated successfully');
		// exit;
	}catch (\Exception $e) {
		$ologger->info($e->getMessage());
	}
}

**Comment by rvanchinathan** [comment] 2017-11-27 13:57
Hello Magento Team,

I found very simple code to re produce this issue.
Please try this with below code

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load(// Some Product Id //);
$_product->setStatus(\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED);
$_product->setStoreId(// Some Store ID //);
$_product->save();

Note:
Before run this make sure your magento have single web site and multiple store view.

**Comment by vanchi-nathan** [comment] 2017-11-27 14:08
Hello Magento Team,

I found very simple code to re produce this issue.
Please try this with below code

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load(// Some Product Id //);
$_product->setStatus(\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_DISABLED);
$_product->setStoreId(// Some Store ID //);
$_product->save();

Note:
Before run this make sure your magento have single web site and multiple store view.

**Comment by magento-engcom-team** [comment] 2017-12-01 14:30
@vanchi-nathan, thank you for your report.
We've created internal ticket(s) MAGETWO-84877 to track progress on the issue.

**Comment by pktat** [comment] 2018-02-01 10:14
What is the status of this issue ?

**Comment by anthonyherve** [comment] 2019-01-11 16:35
Hello,

Is there any update for this issue?

Thank you.

**Comment by magento-engcom-team** [comment] 2020-01-10 12:52
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30347` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-10-06 19:32
Closed as cannot reproduce

**Closed as completed by sdzhepa** 2020-10-06 19:32 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is valid, Reproduced on 2.4.x, Progress: done
