### ISSUE TITLE
Shipping Information Form Stuck at 'Loading Regions (When I have only one Country without drop down State) Magento Venia - PWA

### ISSUE THREAD

**Issue by dariovranjkovic** [magento/magento2#35519] opened 2022-05-23 10:54 UTC
### Preconditions and environment

- Magento version 2.4, venia 12.4 

### Steps to reproduce
0. Problem on PWA solution, Venia theme
1. Our store have only one available Country for checkout page (UK United Kingdom)
2. Go on checkout page
3. Enter customer information
4. Try to Continue to Shipping method
5. Error on State field (Is required.) but I haven't option for choose, there should be input field (As when we have more option for Country, but when we have only one option, system will no setup correct input and change dropdown option )

### Expected result

Input field for enter State

### Actual result

Dropdown field (Empty)

![screencapture-0-0-0-0-10000-uk-checkout-2022-05-23-12_51_17](https://user-images.githubusercontent.com/11262309/169803985-59b72c86-f462-4341-af6f-a6a4fba5f3c9.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-23 12:13
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-24 11:34
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-30 06:35
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-30 09:41
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-05-30 11:05
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-02 11:48
Hello @Nuranto ,
 We have tried to reproduce the issue in Magento 2.4.4 instancethe issue is not reproducible.

Please refer the below screenshot for the reference;
![Screenshot from 2022-06-02 17-13-27](https://user-images.githubusercontent.com/60198592/171622290-6c890120-d520-4e64-8f07-57e54b39b137.png)
![Screenshot from 2022-06-02 17-13-32](https://user-images.githubusercontent.com/60198592/171622302-536db349-cade-4e6d-b27a-4bb585b2b61b.png)

We have followed the below steps in order to reproduce the issue:
1.Add the Products to Card
2.Go on checkout page
3.Enter customer information
4.Try to Continue to Shipping method
5.There is No error Showing in State Field.

Let us know in case we have missed anything. Thanks

**Comment by engcom-Delta** [comment] 2022-07-15 12:21
@magento give me 2.4-develop instance with venia 12.4

**Comment by dariovranjkovic** [comment] 2022-07-15 15:29
Is this pwa-venia theme? This checkout looks like as luma / standard
magento theme.. I sent report for venia, pwa, react theme.

Best regards,
Dario

pet, 15. srp 2022. 16:05 Penchalaiah K ***@***.***> je
napisao:

**Comment by engcom-Delta** [comment] 2022-07-18 10:16
@magento give me 2.4-develop instance with venia 12.4

**Comment by engcom-Delta** [comment] 2022-07-18 12:32
@magento give me 2.4-develop instance with venia 12.4

**Comment by engcom-Delta** [comment] 2022-07-21 12:15
Hi @dariovranjkovic ,
We have tried to reproduce the issue on Magento Venia PWA , issue is not reproducible.
Please find the attached video for reference.

https://www.loom.com/share/1d0c68b6074a4d40b40d335bf4faed33

**Comment by engcom-Delta** [comment] 2022-08-05 06:55
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Delta** 2022-08-05 06:55 UTC
Labels: Issue: needs update
