### ISSUE TITLE
Unsubscribe not working in Default Magento 2.1 from admin panel

### ISSUE THREAD

**Issue by ShubhSikarwar** [magento/magento2#6313] opened 2016-08-24 11:02 UTC
1. Login Magento 2.1 CE admin
2. Go to Customer -> All Customers
3. Click on Add new customer 
4. Fill all mandatory fields
5. Click on Save and Continue
6. Click on Newsletter in Left navigation
7. Check the Subscribed to Newsletter and Save and Continue.
8. Again Go to Newsletter and Uncheck the Subscribed to Newsletter and Save and Continue.
   ISSUE:   Again Go to Newsletter , Subscribed to Newsletter is still checked and in DB also status not changed.

**Comment by sevos1984** [comment] 2016-08-26 13:00
This is a known issue. Internal ticket MAGETWO-48138. Thanks for posting

**Comment by magento-engcom-team** [comment] 2017-10-05 06:30
@ShubhSikarwar, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 06:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Clear Description, Issue: Format is not valid
