### ISSUE TITLE
Magento render part of img

### ISSUE THREAD

**Issue by Kleibert** [magento/magento2#27694] opened 2020-04-10 15:19 UTC
### Preconditions (*)

1. Magento ver. 2.3.4
2. 

### Steps to reproduce (*)

1.  I upload the product image![4](https://user-images.githubusercontent.com/42814600/79001624-c903ed80-7b1c-11ea-836f-9f716303040a.png)

### Expected result (*)

1. Render a perfect img on frontStore.

### Actual result (*)

1. Render part of the img;
2.
![3](https://user-images.githubusercontent.com/42814600/79001769-18e2b480-7b1d-11ea-8f18-cc6c5c81dbbf.jpg)

**Comment by mrtuvn** [comment] 2020-04-12 11:19
This is seem related with image 
Can you check it ? @Kleibert 
https://www.colowsomarketplace.com/auto/pub/media/catalog/product/cache/09630293f6f89cf82c9e2aac50e3781a/1/5/15_3_9.png

https://www.colowsomarketplace.com/auto/pub/media/catalog/product/cache/96130ded19617189a2002e962fe79e7c/2/_/2_4_16.png

**Comment by engcom-Alfa** [comment] 2020-12-02 10:13
Hi @Kleibert .
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop.
:heavy_check_mark:  The images were rendered correctly.

![Screenshot from 2020-12-02 12-11-54](https://user-images.githubusercontent.com/51679138/100859169-99cd3280-3497-11eb-810d-f081fd641ff8.png)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-02 10:13 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.4
