### ISSUE TITLE
Asynchronous email sending for the sales entities which were created with disabled email sending

### ISSUE THREAD

**Issue by serhiyzhovnir** [magento/magento2#21786] opened 2019-03-16 09:09 UTC
### Preconditions (*)
1. Magento 2.3, Magento 2.2
2. Enabled CRON 
3. enabled sales_email/general/async_sending config 

### Steps to reproduce (*)
1. Disable email sending config for Invoice, Creditmemo, Shipment entities (Stores->Configuration->Sales->Sales Emails)
2. Create Invoice, Creditmemo, Shipment via admin panel
3. Enable email sending config for Invoice, Creditmemo, Shipment entities
4. Wait for CRON or trigger it manually via **bin/magento cron:run** command

### Expected result (*)

1. The emails for the sales entities which were created with disabled email sending do not send via asynchronous email sending after enabling the email sending config for the sales entities.

### Actual result (*)
1. The emails for the sales entities which were created with disabled email sending send via asynchronous email sending after enabling email sending config for the sales entities.

**Comment by magento-engcom-team** [comment] 2019-03-16 09:10
Hi @Leandry. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-16 10:41
:white_check_mark: Confirmed by @Leandry 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98743`, `MAGETWO-98744` were created

**Issue Available**: @Leandry, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-04-16 14:10
Hi @serhiyzhovnir. Thank you for your report. 
The issue has been fixed in magento/magento2#21788 by @serhiyzhovnir in 2.3-develop branch
Related commit(s):
 - [8ed926626330c219c76d9752e513bc0861ea7d05](https://github.com/magento/magento2/commit/8ed926626330c219c76d9752e513bc0861ea7d05)
 - [3ebdbffedbe3505e1a3535a6042f2becdeea127b](https://github.com/magento/magento2/commit/3ebdbffedbe3505e1a3535a6042f2becdeea127b)
 - [17cd172dcb809d1329313d4a2b44f4877fbf46b8](https://github.com/magento/magento2/commit/17cd172dcb809d1329313d4a2b44f4877fbf46b8)
 - [f36dbc9aeae87bb1656bfc4e93ad24f69dd5738b](https://github.com/magento/magento2/commit/f36dbc9aeae87bb1656bfc4e93ad24f69dd5738b)
 - [1a297e875a29d0d610180426519a59f91db797d5](https://github.com/magento/magento2/commit/1a297e875a29d0d610180426519a59f91db797d5)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-04-16 14:10 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: AsynchronousOperations, Component: Email

**Comment by magento-engcom-team** [comment] 2019-04-25 15:50
Hi @serhiyzhovnir. Thank you for your report. 
The issue has been fixed in magento/magento2#22108 by @serhiyzhovnir in 2.2-develop branch
Related commit(s):
 - [3751e4b1d86aa0f462e1c84e73cfde5c6d8b6e99](https://github.com/magento/magento2/commit/3751e4b1d86aa0f462e1c84e73cfde5c6d8b6e99)

The fix will be available with the upcoming 2.2.9 release.
