### ISSUE TITLE
Product count not appear on Mini cart 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32629] opened 2021-03-31 05:25 UTC
Product count not appear on Mini cart 

### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)
- As guest user add 2-3 products to cart 
- Shopping Cart 
- Click on Checkout with multiple addresses 
- Login page -> Click on Create an account button 
- Observe at mini cart 

### Expected result (*)
Product count should be appear on mini cart 

### Actual result (*)
https://prnt.sc/y4ut7w

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-31 05:26
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41669` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2021-03-31 05:52
Hi @renard123,
I just looked that you created multiple issues on the same page https://github.com/magento/magento2/issues/32629 https://github.com/magento/magento2/issues/32630 https://github.com/magento/magento2/issues/32632.
It looks like on this page some JS error appears. Could you confirm that and provide more info about that?

**Comment by ihor-sviziev** [comment] 2021-03-31 10:05
@magento give me 2.4-develop instance

**Comment by ihor-sviziev** [comment] 2021-03-31 10:15
Oh, I see we have there following JS error:
![image](https://user-images.githubusercontent.com/1873745/113128929-00cede00-9223-11eb-828e-cd97a751a87e.png)
![image](https://user-images.githubusercontent.com/1873745/113129057-24922400-9223-11eb-8e8a-76694bdd14da.png)

It was caused by an incorrect JSON file - in the source code we see the following code:
![image](https://user-images.githubusercontent.com/1873745/113128992-147a4480-9223-11eb-993e-7f2318c0435d.png)

**Comment by ihor-sviziev** [comment] 2021-03-31 10:41
@renard123 FYI I prepared PR that fixes this issue https://github.com/magento/magento2/pull/32634

**Comment by ihor-sviziev** [comment] 2021-04-07 05:52
Hi,

This issue was fixed in https://github.com/magento/magento2/commit/461509df6db50edf65de181ecb7decc27519a748.

**Comment by magento-engcom-team** [comment] 2021-04-07 05:53
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment or reopen according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
the ticket if you are still facing this issue on the latest `2.x-develop` branch. Thank you for collaboration.

**Closed as completed by ihor-sviziev** 2021-04-07 05:52 UTC
Labels: Issue: Confirmed, Component: Multishipping, Fixed in 2.4.x, Priority: P2, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation
