### ISSUE TITLE
Wrong row subtotal on invoice emails

### ISSUE THREAD

**Issue by fmarangi** [magento/magento2#38213] opened 2023-11-22 15:39 UTC
### Preconditions and environment

- Magento version 2.4.6 (the bug has been present for at least 4 years)

### Steps to reproduce

1. Add product to cart with qty 2 e.g. Joust Duffle Bag @ $ 34.00
2. Checkout, any payment method
3. Place the order
4. On the backend, Issue an invoice for the order
5. Only invoice qty 1

### Expected result

The row subtotal in the invoice email is $ 34.00

### Actual result

The row subtotal in the invoice email is $ 68.00

### Additional information

For some reason, the invoice item renderer uses `$block->getItemPrice($_item->getOrderItem())` instead of `$block->getItemPrice($_item)` (compare https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Sales/view/frontend/templates/email/items/invoice/default.phtml with all other item renderer, ie order, credit memo, etc.)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-11-22 22:33
Going through git's history, it looks like your issue got introduced by https://github.com/magento/magento2/pull/11297, which was to fix https://github.com/magento/magento2/issues/5105
So it sounds like this fix maybe wasn't the best way to solve that issue, maybe there is a better way.

**Comment by fmarangi** [comment] 2023-11-23 08:27
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-11-23 08:49
Hi @fmarangi,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Add product to cart with qty 2 e.g. Joust Duffle Bag @ $ 34.00
- Checkout, any payment method
- Place the order
- On the backend, Issue an invoice for the order
- Only invoice qty 1

The subtotal in the invoice email is only $34.

<img width="1088" alt="Screenshot 2023-11-23 at 11 56 29 AM" src="https://github.com/magento/magento2/assets/51680745/3aa8e534-caea-4b4b-8881-bcf4399ed383">



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-04 04:57
Hi @fmarangi,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38213#issuecomment-1824008447 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by fmarangi** [comment] 2023-12-08 12:54
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-12-12 04:55
Hi @fmarangi,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Bravo** 2023-12-12 04:55 UTC
Labels: Issue: needs update, Reported on 2.4.6
