### ISSUE TITLE
Change Image Size of Visual Swatch

### ISSUE THREAD

**Issue by lookinglavish** [magento/magento2#2978] opened 2016-01-13 01:37 UTC
I'm trying adjust the visual swatch. I'm able to adjust the border around the image, but unsuccessful on adjusting the image itself. I've made the changes in
vendor/module-swatches/view/frontend/web/css/swatches.css. Not sure if I'm in the wrong area or if I need to take extra steps?

Thanks!

**Comment by zanilee** [comment] 2016-01-14 10:51
Hi, @lookinglavish!

To modify swatches styles you should overwrite `swatches.css` in your theme.
To do that, copy `/app/code/Magento/Swatches/view/frontend/web/css/swatches.css` to
`/app/design/frontend/<vendor>/<theme>/Magento_Swatches/web/css/swatches.css` and do your modifications there.

**Comment by lookinglavish** [comment] 2016-01-14 15:55
Zanilee

Hello,

I have the Luma theme right now...not sure if that matters.

I'm trying to copy 
|/app/code/Magento/Swatches/view/frontend/web/css/swatches.css| TO 
|/app/design/frontend/<vendor>/<theme>/Magento_Swatches/web/css/swatches.css 
HOWEVER all I have from that path is ||/app/design/frontend/. After that 
I don't have ||/<vendor>/<theme>/Magento_Swatches/web/css/swatches.css 
to copy to...

Thanks,

Rob
|

**Comment by zanilee** [comment] 2016-01-25 10:48
Hello, @lookinglavish!

[Magento doesn't recommend to modify Luma or Blank theme](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/themes/theme-general.html#theme-gen-overview). 
But if you are modifying the Luma theme, you should create the needed folders
`/app/design/frontend/luma/Magento_Swatches/web/css`
and place swatches.css there:
`/app/design/frontend/luma/Magento_Swatches/web/css/swatches.css`

And then to see the changes remove all cache folders (but not the .htaccess files) in `pub/static/` and `var/`

**Comment by MomotenkoNatalia** [comment] 2016-03-01 12:54
@lookinglavish 
Please let us know if this helps.

**Comment by MomotenkoNatalia** [comment] 2016-03-15 12:20
I close the issue for now. If you have further question to this issue please feel free to reopen

**Closed as completed by MomotenkoNatalia** 2016-03-15 12:20 UTC

**Comment by Will-I4M** [comment] 2016-10-28 22:57
Something changed in magento 2.1.2 but, its not possible to change the swatche image size. I tried with the etc/view.xml, it doesen't work anymore. Could we have details on the proper way to change the size of swatches images ?

**Comment by matt-bailey** [comment] 2016-10-31 12:28
+1

I can confirm we also have this issue. The `swatch_image` setting in view.xml no longer exists.

**Comment by erikhansen** [comment] 2016-11-14 19:38
@Will-I4M @matt-bailey It looks like there is an open task to address the issue with custom swatch sizes not working on 2.1.x: https://github.com/magento/magento2/issues/6382

**Comment by MohanaKVS** [comment] 2018-11-22 05:29
Hi i followed the step you given below https://github.com/magento/magento2/issues/2978#issuecomment-171610891

But, i did not get out put in frontend
i used Setup:upgrade
           cache:clean
 
But the was no use still i get a swatches.css style from vendor folder.
