### ISSUE TITLE
Magento2 Paypal

### ISSUE THREAD

**Issue by robysalv** [magento/magento2#12372] opened 2017-11-21 10:02 UTC
Hi
Magento 2.2 version
 I have issue when  active native terms & condition on magento 2  and Paypal activate.
I click on checkbox Terms and Condition  and after click on " pay with Paypal"  I have a conflict because popup Paypal remain blocked  and the process no work .If I have term and condition without checkbox the payment paypal work well-

Regards
Roberto

### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by lexwet** [comment] 2017-11-21 10:13
#11885

**Comment by magento-engcom-team** [comment] 2017-11-21 11:16
@robysalv , thank you for your report.
This is duplicate of [#11885](https://github.com/magento/magento2/issues/11885)

**Closed as completed by magento-engcom-team** 2017-11-21 11:16 UTC
Labels: duplicate, Issue: Format is valid
