### ISSUE TITLE
translate error sales_rule_form.xml

### ISSUE THREAD

**Issue by ideirj** [magento/magento2#5104] opened 2016-06-20 10:51 UTC
app/code/Magento/SalesRule/view/adminhtml/ui_component/sales_rule_form.xml

line 54:
<item name="label" xsi:type="string">Currently Active</item>

miss: translate="true"

**Comment by Mulderua** [comment] 2016-06-21 13:54
Hi @ideirj, thank you for the report.
Internal ticket MAGETWO-54609 was created.

**Comment by magento-engcom-team** [comment] 2017-09-20 22:20
@ideirj, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:20 UTC
Labels: Issue: Ready for Work, bug report, Fixed in 2.2.x, Issue: Format is not valid
