### ISSUE TITLE
Fatal error on integration tests execution

### ISSUE THREAD

**Issue by mbrioski** [magento/magento2#26829] opened 2020-02-12 08:18 UTC
### Preconditions (*)
* Magento 2.3.3 | 2.3.4
* PHP 7.3>=
* PHPUnit 8.5.2

### Steps to reproduce (*)
Execute `vendor/bin/phpunit /app/dev/tests/integration/phpunit.xml.dist`

### Expected result (*)
Integration tests runs like expected

### Actual result (*)
```
Fatal error: Declaration of Magento\TestFramework\Event\PhpUnit::addError(PHPUnit\Framework\Test $test, Exception $e, $time) must be compatible with PHPUnit\Framework\TestListener::addError(PHPUnit\Framework\Test $test, Throwable $t, float $time): void in /app/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php on line 12
```

**Comment by engcom-Alfa** [comment] 2020-02-25 12:49
Hi, @ridesoft. Thank you for your report!

As we see from your description, you are using PHPUnit version **8.5.2**.
In [Magento 2.3 technology stack requirements](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html)  states that Magento(v. 2.3) recommends using PHPUnit version **6.2.0**.
There should be no such error in this version.
So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Comment by ridesoft** [comment] 2020-02-25 12:57
Ok... so basically is not possible to run integration tests with php73+ because phpunit 6.2.0 supports only php72.

**Comment by engcom-Golf** [comment] 2020-02-25 13:29
HI @ridesoft how you run in `vendor/bin/phpunit PHPUnit 8.5.2` ? as far i remeber there always  6.2 version.

**Comment by engcom-Golf** [comment] 2020-02-25 13:32
I think it would be better to open issue on devdoc and update PHPUnit requirements https://devdocs.magento.com/guides/v2.3/test/unit/unit_test_execution_cli.html

**Comment by engcom-Golf** [comment] 2020-02-25 13:37
@ridesoft  here an example of running unti tests on php7.3 

![DeepinScreenshot_select-area_20200225153906](https://user-images.githubusercontent.com/51681547/75252132-b63f8e80-57e4-11ea-8099-4fbb947789c3.png)

**Comment by ridesoft** [comment] 2020-02-25 15:15
I'm speaking about integration tests...

**Comment by engcom-Alfa** [comment] 2020-02-27 11:22
Hello @ridesoft 
Thank you for contribution and collaboration!

Sorry for the inconvenience. 
You were right that PHPUnit 6.x does not support PHP v 7.3. To run tests on PHP 7.3, you must have at least PHPUnit 7.x version. For now, Magento is using PHPUnit. 6.5.14. But in the future, Magento needs an updated PHPUnit.

Thank you!

Marked as **Feature Request**

cc @sdzhepa

**Comment by ihor-sviziev** [comment] 2020-05-28 10:20
@engcom-Alfa we already migrated to phpunit 9, so issue should be fixed. Could you confirm that?

**Comment by engcom-Alfa** [comment] 2020-05-29 11:28
Hi, @ihor-sviziev @mbrioski .
We are not able to reproduce this issue on a fresh 2.4-develop after migrated to PHPUnit 9.

**Preconditions:**
Php 7.3
PHPUnit 9.1.5

Run in console: `vendor/bin/phpunit -c /var/www/html/magento24/dev/tests/integration/phpunit.xml.dist
`

**Actual Result:** :heavy_check_mark:  Integration tests runs like expected

![Screenshot from 2020-05-29 14-27-51](https://user-images.githubusercontent.com/51679138/83255182-a30fd680-a1b8-11ea-8fa6-8f1ad1e8bf74.png)

**Comment by ihor-sviziev** [comment] 2020-05-29 11:49
Cool. thx for confirming. I'm closing this issue.

**Closed as completed by ihor-sviziev** 2020-05-29 11:49 UTC
Labels: feature request, Issue: Format is valid, Fixed in 2.4.x, Progress: done, Reported on 2.3.3
