### ISSUE TITLE
paypal pay later lose a param

### ISSUE THREAD

**Issue by JKair** [magento/magento2#33791] opened 2021-08-13 11:09 UTC
### Preconditions (*)

1.magento 2.4.3 the module-paypal
2.

### Steps to reproduce (*)

1. set the pay later support and will display a undefinded message on the paypal button
![image](https://user-images.githubusercontent.com/5440088/129347909-cbfba4e5-a22a-4fe1-9da9-17f8c657d851.png)

### Expected result (*)

1. ![image](https://user-images.githubusercontent.com/5440088/129348634-20d1475b-96e1-40f3-9c46-61ea0dbb14db.png)
2.

### Actual result (*)

1. ![image](https://user-images.githubusercontent.com/5440088/129347935-d47af7ca-070c-4a3f-84d1-719a5ed700ed.png)
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by JKair** [comment] 2021-08-13 11:18
I fix this bug through add a param in `module-paypal\view\frontend\web\template\paylater.html`
`'data-pp-buyerCountry':'US'`
but the admin panel dont support this setting.

this bug will appear in the paypal later message.

**Comment by engcom-November** [comment] 2021-08-18 12:45
Verified the issue on Magento 2.4-develop branch and the issue is not reproducible for both Signedin user and public user.
**Steps performed:**
Setup Paypal Express Checkout from Admin - Stores - Configuration - Sales - Payment Methods and enable PayPal Pay Later and Save
Reindex and Clear cache
Navigate to Front-end
Add a Product to Cart and Checkout - **No issue**: PayPal Pay Later text is displayed as expected.
Front-end - Login as Customer - Add Product to Cart - Checkout - **No issue**
Note: This issue is also not reproducible to me on Magento-2.4.3 version as well.
![image](https://user-images.githubusercontent.com/60198231/129900254-2e3868c2-23d5-42aa-b0e5-1b758623677c.png)

![image](https://user-images.githubusercontent.com/60198231/129900199-50f70e66-99e0-42df-87df-b53935fb794a.png)

![image](https://user-images.githubusercontent.com/60198231/129900158-bdb6173b-483b-4c15-937f-09b06691654c.png)

@JKair , kindly recheck the issue on Magento 2.4-develop branch as the issues in 2.4.3 are fixed on 2.4-develop branch and provide missing steps/configuration details if the issue is still reproducible.
Thank you

**Comment by engcom-November** [comment] 2021-09-01 05:48
Hi @JKair ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-01 05:48 UTC
Labels: Issue:  Cannot Reproduce, Component: Paypal, Issue: needs update, Reported on 2.4.3
