### ISSUE TITLE
Wrong email shows in order success page with multi-store 

### ISSUE THREAD

**Issue by haiwera-silk-cd** [magento/magento2#25870] opened 2019-12-02 02:09 UTC
### Preconditions (*)

1. Magento version 2.2.5
2. PHP 7.1.0
3. Mysql 5.7
4. Multi-store with order increment id the same(sequence id starts with the same number) 
5. assume default store named store 1, the other store is store 2
### Steps to reproduce (*)

1. Place an order as a guest with email xxx@xx.com in store 1, assume increment id is 000000001
2. Actual/Expected: Order placed successfully, and the email(suggestion of creating an account) is xxx@xx.com
3. Place an order as a guest with email yyy@yy.com in store 2, assume increment id is 000000001(same as above)
4. Actual: Order placed successfully, the email showed xxx@xx.com which is wrong

### Expected result (*)

1. The email should be yyy@yy.com 

### Actual result (*)

1. The email is xxx@xx.com 

### Note
- I guess It might be lacking of the store filter when reading the email in the order success page. the bug will never appear if no order increment id is conflicted

**Comment by engcom-Echo** [comment] 2019-12-02 13:17
Hello @haiwera-silk-cd 

Thank you for your report and collaboration!
We are not able to reproduce this issue by provided steps.
Tested on 2.3-develop and 2.3.3.

**Testing scenario:**

**Preconditions:**
 

1. Two websites are created.
2. Product assigned to each site.

**Steps to reproduce** 

1. Place an order as a guest with email site1m2@xx.com in store 1 
![Screenshot from 2019-12-02 13-24-35](https://user-images.githubusercontent.com/51681435/69958408-6b77e880-150d-11ea-9f49-034aa4e11bd3.png)
2. Order id is 2000000001
![Screenshot from 2019-12-02 13-25-24](https://user-images.githubusercontent.com/51681435/69960835-2787e200-1513-11ea-8d3a-6a2f370aa2ae.png)
3. Order placed successfully, and the email is site1m2@xx.com
![Screenshot from 2019-12-02 14-10-41](https://user-images.githubusercontent.com/51681435/69958557-bd207300-150d-11ea-86f8-ae6c9e33f015.png)
4. Place an order as a guest with email site2m2@yy.com in store 2
5. Increment id is 3000000001
![Screenshot from 2019-12-02 13-28-07](https://user-images.githubusercontent.com/51681435/69960531-5ea9c380-1512-11ea-8ffa-ab82d205e7a4.png)
![Screenshot from 2019-12-02 13-28-27](https://user-images.githubusercontent.com/51681435/69960154-746ab900-1511-11ea-8992-acfad35007cf.png)
**Result** Order placed successfully, the email showed site2m2@xx.com 
Order id is 3000000001
![Screenshot from 2019-12-02 14-39-38](https://user-images.githubusercontent.com/51681435/69960311-cc092480-1511-11ea-87bf-3e5c9a735c9f.png)
Could you check my steps are correct?

**Comment by haiwera-silk-cd** [comment] 2019-12-03 01:35
@engcom-Echo The steps were correct, but What I mean is the same order increment id are placed in both sites. I believe you would never reproduce the issue in the normal way, This should be a strategic issue that "would we allow the same increment id appears in different stores". if the answer is true, you could reproduce the issue after executing the SQL in DB
```sql
ALTER TABLE sequence_order_1 AUTO_INCREMENT=300000001;
```
and then, place an order on store 2 again, you will probably see the same increment id as store 1, and the email will be wrong.

**Comment by haiwera-silk-cd** [comment] 2019-12-03 01:51
BTW, I took a little survey in the code, the function loadByIncrementId in `\Magento\Sales\Model\Order` is unaware of distinguishing stores, it returns the first row that matches the increment id

**Comment by engcom-Echo** [comment] 2019-12-03 11:36
Hello @haiwera-silk-cd 

Could you provide a use case why is it necessary to change the order increment id?

Thank you!

**Comment by haiwera-silk-cd** [comment] 2019-12-05 05:57
@engcom-Echo Did you mean we don't allow the same increment id in different stores? What if they get conflicted in the far future as they increase, despite I know the possibility is extremely less.

**Comment by engcom-Echo** [comment] 2019-12-05 11:44
Hello @haiwera-silk-cd 

The value of increment id has type "UNIQUE". A Unique Key assures that the value in the column will be unique throughout the table.
Each store has its own unique id.
![id](https://user-images.githubusercontent.com/51681435/70227723-c30b9380-175b-11ea-887f-0d426c1c1a1c.png)
According to the above, we can say that magento does not allow the use of the same increment ID in different stores. 

So I have to close this issue.
Thank you!

**Closed as completed by engcom-Echo** 2019-12-05 11:44 UTC
Labels: non-issue, Issue: Format is valid
