### ISSUE TITLE
Captcha refreshes when Payment Method is changed (when checkout Captcha is set to OFF)

### ISSUE THREAD

**Issue by pmonosolo** [magento/magento2#34855] opened 2021-12-20 22:23 UTC
### Preconditions (*)

1. ReCaptcha turned OFF on all of the forms:

![image](https://user-images.githubusercontent.com/66754347/146839349-44f6b0c3-b151-4ff7-b28c-ad72c89421a1.png)

2. ReCaptcha keys added to the configuration

![image](https://user-images.githubusercontent.com/66754347/146839280-9338f584-99a0-4d12-a3b9-05b8f0beb1a3.png)

3. At least 2 payment methods are enabled.

### Steps to reproduce (*)

1. Go to checkout page
2. Click on different payment methods and notice request to /captcha/refresh/ is being made when payment method is changed.

### Expected result (*)

1. No request to refresh ReCaptcha when ReCaptcha is turned off for Checkout.

### Actual result (*)

1. Request is made to refresh to ReCaptcha which creates a delay of about 0.5 - 1.5 seconds on checkout page while totals are reloading.

![image](https://user-images.githubusercontent.com/66754347/146840469-dec5e355-2211-434e-be92-c0a54a6db968.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._

**Comment by pmonosolo** [comment] 2021-12-20 22:24
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment] 2021-12-21 20:06
@magento give me 2.4-develop instance

**Comment by pmonosolo** [comment] 2022-01-04 22:25
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-31 14:46
Hi @pmonosolo ,
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue with provided steps. Kindly verify the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by pmonosolo** [comment] 2022-02-01 19:17
> Hi @pmonosolo , Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue with provided steps. Kindly verify the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible. Thank you.

Hello, I got access to demo instance today.

Here are the tests:

![image](https://user-images.githubusercontent.com/66754347/152034373-125df593-da90-49a5-b04b-2d082881da95.png)

^^ you can see here /refresh is being called.

The checkout ReCaptcha is turned off:

![image](https://user-images.githubusercontent.com/66754347/152034443-b5e2c955-8fb7-4509-b33a-2e0245a77da6.png)

The instance from another ticket can be used to test this:

Admin access: https://fec85852d553821a047c03511225dba0.instances.magento-community.engineering/admin_f8b5
Login: 65d69133
Password: 5a0f52cfb398

It looks like the actual recaptcha is not being triggered, its the original Magento captcha that is being refreshed:
{"imgSrc":"https:\/\/fec85852d553821a047c03511225dba0.instances.magento-community.engineering\/media\/captcha\/base\/d63305d3d16607e2d1efc96b50b81081.png"}
{"imgSrc":"https:\/\/fec85852d553821a047c03511225dba0.instances.magento-community.engineering\/media\/captcha\/base\/b1f30744e2565ac6ef6780041e9a53fc.png"}
{"imgSrc":"https:\/\/fec85852d553821a047c03511225dba0.instances.magento-community.engineering\/media\/captcha\/base\/1e3ca4fb3f120139f704d92b2ae13f21.png"}

Each of these requests  are 0.5 seconds:

![image](https://user-images.githubusercontent.com/66754347/152034723-0d95970c-f660-4c42-9b72-b8dc1a36fb00.png)

Here is the look of the page:

![image](https://user-images.githubusercontent.com/66754347/152034827-4241698c-5b2c-40aa-afad-e360c8c9a566.png)

I checked Customer Configuration and original Magento captcha is turned on:

![image](https://user-images.githubusercontent.com/66754347/152035450-480d7176-c225-4cd4-883c-824b9e64f66b.png)

Although the Checkout / Placing Order is not turned on:

![image](https://user-images.githubusercontent.com/66754347/152035554-17631b67-b3b2-49f2-b94b-bfcdd5c64c5c.png)

So maybe it should not be generating Captcha when you click on each payment method when it's turned off in Configuration?

**Comment by pmonosolo** [comment] 2022-02-01 19:23
I did an additional test and turned off Admin and Customer Captcha:

CUSTOMER
![image](https://user-images.githubusercontent.com/66754347/152036479-43b2b5d0-09b5-4627-9e45-0e491999cb37.png)

ADMIN
![image](https://user-images.githubusercontent.com/66754347/152036537-4cf4f8e8-9e39-4aa5-8164-09c62a39d43c.png)

I'm getting the same result, /refresh is being called:
![image](https://user-images.githubusercontent.com/66754347/152036445-b3980f74-1914-4f1c-ba48-74519ba4b678.png)

**Comment by engcom-Hotel** [comment] 2022-02-08 09:47
Hello @pmonosolo,

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is reproducible for us. For us too the ReCaptcha is disabled for the below pages:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/51681618/152961107-4daadf4a-92fa-435e-88f6-86d9671db2bb.png">

We have enabled the ReCaptcha V2:
<img width="928" alt="image" src="https://user-images.githubusercontent.com/51681618/152961222-1626a2ea-2698-412f-8615-ba2b0eaef46e.png">

And on the checkout page that `refresh` is hitting:
![1](https://user-images.githubusercontent.com/51681618/152961357-60bf37e8-d5e5-4f4c-ba6a-297858e2bfac.jpg)

Hence confirming this issue.

Thanks

**Comment by pmonosolo** [comment] 2022-02-08 17:27
> Hello @pmonosolo,
> 
> We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is reproducible for us. For us too the ReCaptcha is disabled for the below pages:
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/51681618/152961107-4daadf4a-92fa-435e-88f6-86d9671db2bb.png">
> 
> We have enabled the ReCaptcha V2: <img alt="image" width="928" src="https://user-images.githubusercontent.com/51681618/152961222-1626a2ea-2698-412f-8615-ba2b0eaef46e.png">
> 
> And on the checkout page that `refresh` is hitting: ![1](https://user-images.githubusercontent.com/51681618/152961357-60bf37e8-d5e5-4f4c-ba6a-297858e2bfac.jpg)
> 
> Hence confirming this issue.
> 
> Thanks

Sorry my original post was about ReCaptcha, but I later found out, its the original Magento captcha that is being refreshed.

If you look at response result for /refresh its an image of captcha letters:

![image](https://user-images.githubusercontent.com/66754347/153041976-b6c4713e-5968-4b5e-b82d-9829e0f5bdc1.png)

![image](https://user-images.githubusercontent.com/66754347/153042037-8a46f18e-2345-4dc5-b28e-a5fe25742bf0.png)

**Comment by pmonosolo** [comment] 2022-10-05 23:38
Any update on this issue guys? 

I mean seriously this is like 500ms of dead space while your customer is fighting against their thoughts of "Do I really need this?"

When used on One Step Checkouts it's even slower because the sections reload multiple times.

**Comment by engcom-Hotel** [comment] 2022-10-06 06:54
Hello @pmonosolo,

As I can see this issue is prioritized as P3, currently the status of the related JIRA is `TECH ANALYSIS QUEUE`. I will update you more on this further.

Thanks

**Comment by engcom-Hotel** [comment] 2022-11-15 07:43
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-2338 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-2338&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-11-15 07:43 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.x, Area: Framework

**Comment by pmonosolo** [comment] 2022-11-15 17:20
> Hello,
> 
> As I can see this issue got fixed in the scope of the internal Jira ticket AC-2338 by the internal team Related commits: https://github.com/magento/magento2/search?q=AC-2338&type=commits
> 
> Based on the Jira ticket, the target version is 2.4.6.
> 
> Thanks

Beautiful! Thank you! @engcom-Hotel
