### ISSUE TITLE
Grouped Products - VAT included not working

### ISSUE THREAD

**Issue by connectjames** [magento/magento2#5813] opened 2016-07-26 09:48 UTC
### Preconditions

Environnement developer

1. Magento 2.1
2. PHP 7.0.6
3. Ubuntu
### Steps to reproduce

1. Create a grouped product
2. Select in config/tax, display price excl and incl VAT
3. When looking in the frontend both excl and incl price are the same
4. When looking a simple product the VAT excl and incl works
5. Example on this page: http://www.longstonetest.xyz/pneumatici-auto-d-epoca/alfa-romeo.html
### Expected result

1. Both price should be different, one incl and one excl VAT
### Actual result

1. As seen on this page: http://www.longstonetest.xyz/pneumatici-auto-d-epoca/alfa-romeo.html both excl and incl VAT prices are the same, the issue is the same when in the grouped product (here: http://www.longstonetest.xyz/155hr15-avon-cr6zz.html)

**Comment by paalsoberg** [comment] 2016-11-04 09:44
Any progress on this at all?

**Comment by oleg-onufer** [comment] 2017-06-23 15:21
@connectjames  Thanks for reporting this issue.
Internal ticket MAGETWO-70183 was created.

**Comment by magento-engcom-team** [comment] 2017-10-06 06:30
@connectjames, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-06 06:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
