### ISSUE TITLE
Cannot access web setup wizard from admin panel

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#7138] opened 2016-10-21 23:14 UTC
### Preconditions

magento version 2.1.1.
1. Magento version 2.1.1. Trying to upgrade to 2.1.2
2.  Logged in from admin account
### Steps to reproduce

1. Log in to magento panel
2. Go to System-> Web Setup Wizrrd
3. 
### Expected result

1. Should be able to access web setup wizard and update magento
### Actual result

1. See the following message - 
   Welcome to Magento Admin, your online store headquarters.
   To use the Magento setup wizard sign into your Admin account and navigate to System => Tools => Web Setup Wizard

**Comment by veloraven** [comment] 2016-10-27 11:49
@adityag186 thank you for your report.
I'm closing this issue as duplicate of #4687 and #4391

**Closed as completed by veloraven** 2016-10-27 11:49 UTC
