### ISSUE TITLE
Product placeholder image resize issue

### ISSUE THREAD

**Issue by Karlasa** [magento/magento2#13636] opened 2018-02-13 12:27 UTC
Wishlist sidebar block does not resize product placeholder image correctly 

### Preconditions
1.  Magento version 2.2.2 with sample data
2.  blank theme

### Steps to reproduce

1.  add product placeholder images 
2.  remove product image from product
3.  add product into wishlist

### Expected result
1. In sidebar wishlist block placeholder product images has same size as regular images in that container

### Actual result
1. Product placeholder is in default size (is not resized) and overflows container

**Comment by magento-engcom-team** [comment] 2018-02-13 16:17
@Karlasa, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by amitsiliguri** [comment] 2018-05-19 07:49
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 07:49
@amitsiliguri thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by amitsiliguri** [comment] 2018-05-19 07:50
I am working on this at #dmcdindia

**Comment by magento-engcom-team** [comment] 2018-05-19 07:50
@amitsiliguri thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by amitsiliguri** [comment] 2018-05-19 10:02
![capture](https://user-images.githubusercontent.com/39370641/40267396-4a2dce6e-5b79-11e8-9d94-d1a8352ec75d.JPG)
Placeholder image doesn't overflow any container in the sidebar wishlist after removing the product image. 
Resize beautifully in Magento blank theme.

**Comment by magento-engcom-team** [comment] 2018-05-26 10:36
@amitsiliguri Thank you for your research.
@Karlasa we are closing the issue now based on the comment above. Please reopen if you still experience the problem.

**Comment by sanjay-wagento** [comment] 2018-06-04 09:11
@magento-engcom-team give me test instance

**Comment by bartoszkubicki** [comment] 2019-02-06 09:05
Still exists on 2.2.5

**Comment by engcom-Bravo** [comment] 2019-12-31 13:57
Hello @Karlasa 
We are not able to reproduce the issue on Magento 2.4-develop. So we close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) .
Thank you for collaboration.

**Closed as completed by engcom-Bravo** 2019-12-31 13:57 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.1.x, Issue: Format is valid
