### ISSUE TITLE
Save the job applictions without Address using emoji

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36018] opened 2022-08-25 08:47 UTC
### Preconditions and environment

#Magento ver. 2.3.2
#commit ID-bddae5658e18dfa3244187404c7ce79056cc5c5a

### Steps to reproduce

1.Openn job portal.
2.Apply any job.
3 .In the candidate name field we add emoji and thi application was save without name of applicant
4.save the application.

### Expected result

show error massage

### Actual result

*not allow to to save withouth name of applicant.
*it is mandetry field so give some error massage shows
![186380536-a0c0ed3b-5c05-4a7c-95b9-b04828b4eac4](https://user-images.githubusercontent.com/110841790/186619507-5d596ccd-e129-4996-bb96-552e291567a5.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-08-25 09:05
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-08-26 07:58
Hi @SunilC1512 ,

We are trying to reproduce the issue in 2.4-develop instance...But we are not able to reproduce.

Here i attached the screenshots
![Screenshot from 2022-08-25 14-57-02](https://user-images.githubusercontent.com/60198592/186847778-cc9e7cb1-4e11-4b3f-a348-0f5e777814bb.png)
:

Steps:
1.Install Magento instance
2.Enter emojis with respective fields
3.Getting error while entering emojis

We are not able to reproduce the issue....

Let us know if we are missing anything!!!

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-09-12 09:16
Hi @SunilC1512 ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks!!!

**Closed as completed by engcom-Dash** 2022-09-12 09:16 UTC
Labels: Issue: needs update
