### ISSUE TITLE
Magento 2.4.4 Mini cart item images not showing

### ISSUE THREAD

**Issue by khoimm92** [magento/magento2#35535] opened 2022-05-25 04:19 UTC
### Preconditions and environment

- Magento 2.4.4
- PHP8.1

### Steps to reproduce

1. Go to  Content >> Design >> Configuration >>Edit theme >>Product Image Watermarks >> Thumbnail
2. Upload image with Thumbnail and set image position as "Center"
3. Add Products to Cart that all products have images.
4. Open Minicart.
5. Run `bin/magento catalog:image:resize` and observe the error in the terminal.

### Expected result

All item images in Minicart get the images

### Actual result

All item images are replaced by the default Product placeholder image

### Additional information

I have debugged in this file `vendor/magento/module-catalog/Helper/Image.php`
```
public function getUrl()
    {
        try {
            switch ($this->mediaConfig->getMediaUrlFormat()) {
                case CatalogMediaConfig::IMAGE_OPTIMIZATION_PARAMETERS:
                    $this->initBaseFile();
                    break;
                case CatalogMediaConfig::HASH:
                    $this->applyScheduledActions();
                    break;
                default:
                    throw new LocalizedException(__("The specified Catalog media URL format is not supported."));
            }
            return $this->_getModel()->getUrl();
        } catch (\Exception $e) {
            \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->info($e->getMessage());
            return $this->getDefaultPlaceholderUrl();
        }
    }
```
then got those errors
> Deprecated Functionality: Implicit conversion from float 12.5 to int loses precision in /home/stagefish/public_html/stage.livefish.com.au/vendor/magento/framework/Image/Adapter/Gd2.php on line 963 [] []

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-05-31 11:09
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-06-02 11:39
Hello @khoimm92 ,
 We have tried to reproduce the issue in Magento 2.4.4he issue is not reproducible.

Please refer the below screenshot for the reference; 
![Screenshot from 2022-06-02 17-05-36](https://user-images.githubusercontent.com/60198592/171620951-c587a4a7-4e61-4847-aeee-d0ef37e8ee17.png)
We have followed the below steps in order to reproduce the issue:
1.Add Products to Cart that all products have images
2.Open Mini-cart
3.Images Displaying in Mini Cart Page
Let us know in case we have missed anything. Thanks

**Comment by hostep** [comment] 2022-06-05 14:20
@khoimm92, this is just a guess, but could it be that you have a custom theme with a `etc/view.xml` file where the width or height is set to an odd number for the `mini_cart_product_thumbnail` image?
You can probably solve this problem you have by making the number even so it's divisible by 2 without getting a decimal fragment.

Also: where did you see that error? Was it outputted to a certain log file? Because I don't see it when I quickly test it out ...

**Comment by miteshdhaduk1** [comment] 2022-06-06 10:57
**Magento 2.4.4**

**small_image** URL returns the wrong cache hash in products and cart GraphQL for the default store. In other stores, it returns the correct URL.

**Comment by miteshdhaduk1** [comment] 2022-06-07 05:59
Fix for me, maybe help you @khoimm92 
https://github.com/magento/magento2/issues/34540#issuecomment-1148227600

**Comment by engcom-Dash** [comment] 2022-06-07 09:57
Hello @khoimm92 ,
As per our last [comment](https://github.com/magento/magento2/issues/35535#issuecomment-1144764966) , we have tried reproduce luma theme but here it seems that you are using a custom theme. 
So we request you to go through with the solution given in this [comment](https://github.com/magento/magento2/issues/35535#issuecomment-1148229270) and let us know this issue has resolved or not.
Thanks.

**Comment by engcom-Dash** [comment] 2022-06-21 06:45
Dear @khoimm92 ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Comment by craig-bartlett** [comment] 2022-07-07 15:35
Hi,

I've recently come across this same issue. It is indeed caused by theme images with an odd dimension **and** the watermark position set to centre. If using the Gd2 adapter, it uses [the following](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L541) to calculate the position:

```
$positionX = $this->_imageSrcWidth / 2 - imagesx($watermark) / 2;
$positionY = $this->_imageSrcHeight / 2 - imagesy($watermark) / 2;
```

If the image size has an odd dimension, this results in a float. These are then passed to imagecopymergeWithAlphaFix on the next line, which passes them [to imagecopy](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L963). This function expects integers and therefore gives the warning that the OP reported. I think the same is true for the [ImageMagick adapter](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Image/Adapter/ImageMagick.php#L337) as it handles it in the same way.

For what it's worth - when debugging this I didn't see any warnings at all in the system or debug log, only managing to get the output the OP saw by wrapping the call to [createWatermarkBasedOnPosition](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Image/Adapter/Gd2.php#L511) in a try/catch. The only sign I had that something was wrong was several missing folders in media/catalog/product/cache which relate to the sizes that were being silently skipped. Generating the images from the command line also gave no errors/warnings. It's worth noting that I couldn't find anything in the documentation regarding the use of odd dimensions with image sizes.

I patched this for our instances (2.4.4) by explicitly casting the resulting positions to integers. It works for us but your results may vary.


```diff --git a/vendor/magento/framework/Image/Adapter/Gd2.php b/vendor/magento/framework/Image/Adapter/Gd2.php
index af08cb5..2191f34 100644
--- a/vendor/magento/framework/Image/Adapter/Gd2.php
+++ b/vendor/magento/framework/Image/Adapter/Gd2.php
@@ -538,8 +538,8 @@ class Gd2 extends AbstractAdapter
         } elseif ($this->getWatermarkPosition() == self::POSITION_STRETCH) {
             $watermark = $this->createWaterMark($watermark, $this->_imageSrcWidth, $this->_imageSrcHeight);
         } elseif ($this->getWatermarkPosition() == self::POSITION_CENTER) {
-            $positionX = $this->_imageSrcWidth / 2 - imagesx($watermark) / 2;
-            $positionY = $this->_imageSrcHeight / 2 - imagesy($watermark) / 2;
+            $positionX = (int) ($this->_imageSrcWidth / 2 - imagesx($watermark) / 2);
+            $positionY = (int) ($this->_imageSrcHeight / 2 - imagesy($watermark) / 2);
             $this->imagecopymergeWithAlphaFix(
                 $this->_imageHandler,
                 $watermark,

```

And for ImageMagick:

```diff --git a/vendor/magento/framework/Image/Adapter/ImageMagick.php b/vendor/magento/framework/Image/Adapter/ImageMagick.php
index 5cfa7fe..099a960 100644
--- a/vendor/magento/framework/Image/Adapter/ImageMagick.php
+++ b/vendor/magento/framework/Image/Adapter/ImageMagick.php
@@ -326,8 +326,8 @@ class ImageMagick extends AbstractAdapter
                 $watermark->sampleImage($this->_imageSrcWidth, $this->_imageSrcHeight);
                 break;
             case self::POSITION_CENTER:
-                $positionX = ($this->_imageSrcWidth - $watermark->getImageWidth()) / 2;
-                $positionY = ($this->_imageSrcHeight - $watermark->getImageHeight()) / 2;
+                $positionX = (int) (($this->_imageSrcWidth - $watermark->getImageWidth()) / 2);
+                $positionY = (int) (($this->_imageSrcHeight - $watermark->getImageHeight()) / 2);
                 break;
             case self::POSITION_TOP_RIGHT:
                 $positionX = $this->_imageSrcWidth - $watermark->getImageWidth();
```

**Comment by benyatesvortex** [comment] 2022-10-19 16:56
I've had this same issue with more or less the exact experience as @craig-bartlett . This is a bug in the code and the ticket needs reopening.

One thing I would add, you can generate the error by running bin/magento catalog:image:resize (I saved time by hardcoding the particular image I was having trouble with)

**Comment by hostep** [comment] 2022-10-22 09:18
@sdzhepa, @engcom-Dash: can we reopen this ticket and redo the testing based on the last 2 comments?
@craig-bartlett: maybe if you find some time, try opening a Pull Request here with your fixes, it might get fixed quicker that way.

Thanks! 🙂

**Comment by craig-bartlett** [comment] 2022-10-26 10:41
@hostep Sorry I've not had much free time lately - the PR attached is how I fixed the issue on our instances. Hopefully I created the PR correctly, please advise if not!

**Comment by engcom-Dash** [comment] 2022-10-28 15:18
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2022-10-31 02:36
Hello @khoimm92 ,
We have tried to reproduce the issue in Magento 2.4.4 issue is not reproducible.

Please refer the below screenshot for the reference;
<img width="1512" alt="Screenshot 2022-10-28 at 9 22 32 PM" src="https://user-images.githubusercontent.com/60198592/198919416-fce159f6-e097-4633-a40f-e41061dfe8af.png">

We have followed the below steps in order to reproduce the issue:
1.Add Products to Cart that all products have images
2.Open Mini-cart
3.Images Displaying in Mini Cart Page
Let us know in case we have missed anything. Thanks

**Comment by craig-bartlett** [comment] 2022-10-31 08:21
@engcom-Dash 

Hi, for reference the following steps are required to trigger the bug:

- The instance must be running PHP 8.1
- The theme's image size must have an odd height and/or width
- The water mark must be enabled
- The water mark must be set to centred 

As @benyatesvortex said above - you can trigger the error after by running bin/magento catalog:image:resize

**Comment by WouterSteen** [comment] 2022-11-22 11:00
Its not only cart and checkout, its on every page where an image from a product exists.

**Closed as completed** 2022-11-24 17:05 UTC
Labels: Issue: Confirmed, Component: Theme, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: ready for confirmation, Area: Cart & Checkout, Reported on 2.4.4
