### ISSUE TITLE
configure Redis for cache 

### ISSUE THREAD

**Issue by premgurung** [magento/magento2#10614] opened 2017-08-22 13:31 UTC
### Preconditions
Env
php 5.6
magento 2.1.7
aws/Linux/Linux
current mode: developer
ElaticCache: Redis(amazon)

### Steps to reproduce

1.  added the below properties in 

/var/www/digitivy-prodmagento/MagentoStore/app/etc/env.php

'session' =>
  array (
    'save' => 'redis',
    'redis' =>
      array (
        'host' => 'cus-re-7ziaobeg4oob.myrysn.0001.use1.cache.amazonaws.com',
        'port' => '6379',
        'password' => '',
        'timeout' => '2.5',
        'persistent_identifier' => '',
        'database' => '0',
        'compression_threshold' => '2048',
        'compression_library' => 'gzip',
        'log_level' => '1',
        'max_concurrency' => '6',
        'break_after_frontend' => '5',
        'break_after_adminhtml' => '30',
        'first_lifetime' => '600',
        'bot_first_lifetime' => '60',
        'bot_lifetime' => '7200',
        'disable_locking' => '0',
        'min_lifetime' => '60',
        'max_lifetime' => '2592000',
    ),
  ),
  'cache' =>
  array(
     'frontend' =>
     array(
        'default' =>
        array(
           'backend' => 'Cm_Cache_Backend_Redis',
           'backend_options' =>
           array(
              'server' => 'cus-re-7ziaobeg4oob.myrysn.0001.use1.cache.amazonaws.com',
              'port' => '6379',
              ),
      ),
      'page_cache' =>
      array(
        'backend' => 'Cm_Cache_Backend_Redis',
        'backend_options' =>
         array(
           'server' => 'cus-re-7ziaobeg4oob.myrysn.0001.use1.cache.amazonaws.com',
           'port' => '6379',
           'database' => '1',
           'compress_data' => '0',
         ),
      ),
    ),
  ),

2. removed contents from: var/generation, var/di, var/cache, var/view_preprocessed, pub/static var/page_cache/* var/session/*

3. magento deploy:mode:set production

### Expected result
should be able to access both  the admin  and  storefront page .
successfully changed the mode to prod but unable to access the admin  and  storefront page

### Actual result

file_put_contents(/var/www/digitivy-prodmagento/MagentoStore/var/cache//mage-tags/mage---2a5_CONFIG_SCOPES): failed to open stream: Permission denied in /var/www/digitivy-prodmagento/MagentoStore/vendor/colinmollenhour/cache-backend-file/File.php on line 663";i:1;s:4983:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'file_put_conten...', '/var/www/digiti...', 663, Array)

**Comment by orlangur** [comment] 2017-08-22 13:51
How is that different from https://github.com/magento/magento2/issues/10588?

**Comment by premgurung** [comment] 2017-08-22 15:10
result of redis-cli monitor :

[root@ip-10-0-3-253 redis-stable]# src/redis-cli -c -h mycachecluster.eaogs8.0001.usw2.cache.amazonaws.com -p 6379
redis mycachecluster.eaogs8.0001.usw2.cache.amazonaws.com 6379> monitor 
1503414125.001284 [0 127.0.0.1:37583] "info" "default"
1503414125.001336 [0 127.0.0.1:37741] "ping"
1503414125.001341 [0 127.0.0.1:37581] "info" "default"
1503414125.002108 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:05.001Z"
1503414126.001127 [0 127.0.0.1:37741] "ping"
1503414126.001196 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:06.001Z"
1503414127.001051 [0 127.0.0.1:37741] "ping"
1503414127.001118 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:07.000Z"
1503414128.001028 [0 127.0.0.1:37741] "ping"
1503414128.001103 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:08.000Z"
1503414129.001037 [0 127.0.0.1:37741] "ping"
1503414129.001103 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:09.000Z"
1503414130.005816 [0 127.0.0.1:37581] "info" "default"
1503414130.005864 [0 127.0.0.1:37741] "ping"
1503414130.006124 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:10.005Z"
1503414130.006732 [0 127.0.0.1:37581] "info" "default"
1503414131.001057 [0 127.0.0.1:37741] "ping"
1503414131.001123 [0 127.0.0.1:37741] "set" "ElastiCacheMasterReplicationTimestamp" "2017-08-22T15:02:11.000Z"
1503414131.935756 [0 10.0.3.253:49752] "select" "1"
1503414131.949969 [0 10.0.3.253:49754] "select" "0"
1503414131.951356 [0 10.0.3.253:49754] "hget" "zc:k:2a5_INTERCEPTION" "d"
1503414131.970516 [0 10.0.3.253:49754] "hget" "zc:k:2a5_GLOBAL_FRONTEND_PLUGIN_LIST" "d"
1503414131.982763 [0 10.0.3.253:49754] "hget" "zc:k:2a5_SYSTEM_CACHE_EXISTS" "d"
1503414131.983251 [0 10.0.3.253:49754] "hget" "zc:k:2a5_SYSTEM_DEFAULTSYSTEM" "d"
1503414131.984194 [0 10.0.3.253:49754] "hget" "zc:k:2a5_SYSTEM_CACHE_EXISTS" "d"
1503414131.984571 [0 10.0.3.253:49754] "hget" "zc:k:2a5_SYSTEM_DEFAULTWEB" "d"
1503414131.987965 [0 10.0.3.253:49754] "hget" "zc:k:2a5_RESOLVED_STORES_D1BEFA03C79CA0B84ECC488DEA96BC68" "d"
1503414132.000025 [0 10.0.3.253:49754] "hget" "zc:k:2a5_GLOBAL__EVENT_CONFIG_CACHE" "d"
1503414132.000990 [0 127.0.0.1:37741] "ping"

result of ping 

cus-re-bwsv835p3zjm.myrysn.0001.use1.cache.amazonaws.com:6379> ping
PONG


but still unable to access the admin page .

Regards 
Prem

**Comment by orlangur** [comment] 2017-08-22 16:11
Hi @premgurung, did you post the right stack trace

> file_put_contents(/var/www/digitivy-prodmagento/MagentoStore/var/cache//mage-tags/mage---2a5_CONFIG_SCOPES): failed to open stream: Permission denied in /var/www/digitivy-prodmagento/MagentoStore/vendor/colinmollenhour/cache-backend-file/File.php on line 663";i:1;s:4983:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'file_put_conten...', '/var/www/digiti...', 663, Array)

? As this one does not seem to be related to Redis.

**Comment by premgurung** [comment] 2017-08-22 16:15
@orlangur  

i have updated the issues .Thank you

**Comment by misha-kotov** [comment] 2017-08-22 21:21
Sounds like a file permissions issue. Can you ensure the file has correct permissions and try again?

**Comment by premgurung** [comment] 2017-08-23 04:40
@misha-kotov 
 i have given the below permissions 
find var pub/static pub/media app/etc -type f -exec chmod g+w {} \;
find var pub/static pub/media app/etc -type d -exec chmod g+ws {} \;

**Comment by xtremeperf** [comment] 2017-08-26 21:39
@premgurung ,
The issues area is for reporting bugs and issues with the project and it's code.  General help and user support should be discussed somewhere else like Stack Exchange.  Your issues appear to be mostly caused by misconfiguration of filesystem permissions.

I recommend that you avoid trying to use Redis/Memcached/etc. in your development or test instance.  I think it would be best to use the default file caching system until it becomes insufficient for your production site.

You will need to reset all of your file and directory permissions, for the entire installation, back to their original "as installed" state and then follow the steps I've outlined in #10588 .

**Comment by magento-engcom-team** [comment] 2017-09-26 08:41
@premgurung thank you for your report.
This issue not related with Redis.
I’m closing this issue because it is a duplicate #10588. Please reopen this issue as needed.

**Closed as completed by magento-engcom-team** 2017-09-26 08:41 UTC
Labels: bug report, Issue: Clear Description, Issue: Format is valid
