### ISSUE TITLE
Cron task catalog_index_refresh_price fails because of date formatting on 2.4.4

### ISSUE THREAD

**Issue by Quazz** [magento/magento2#35517] opened 2022-05-23 10:37 UTC
### Preconditions and environment

- Magento version 2.4.4
- MariaDB 10.4
- Need to have clock reach midnight for store time

### Steps to reproduce

Have products with special price and special price date range set

Wait for cron task (it runs once per hour, BUT the cron task itself only reaches the error at midnight)
- See https://github.com/magento/magento2/blob/b092dd6df013e8b1e77e8b5d639148ed76a7172a/app/code/Magento/Catalog/Cron/RefreshSpecialPrices.php#L107

- Cron task fails due to date formatting

### Expected result

- Cron task runs at midnight
- It does its task and no error is reported

### Actual result

- Cron task runs at midnight
- The job does not complete because of SQL error in date format
- ```Cron Job catalog_index_refresh_price has an error: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens, query was: SELECT `cat`.`entity_id` FROM `catalog_product_entity_datetime` AS `attr` LEFT JOIN `catalog_product_entity` AS `cat` ON cat.entity_id= attr.entity_id WHERE (attr.attribute_id = '77') AND (attr.store_id = '0') AND (attr.value = DATE_FORMAT('2022-05-23', '%Y-%m-%d %H:%i:%s'))```

### Additional information

Imo, the issue stems from https://github.com/magento/magento2/blob/b092dd6df013e8b1e77e8b5d639148ed76a7172a/app/code/Magento/Catalog/Cron/RefreshSpecialPrices.php#L103

If the second parameter were to be true, it would include the time and thus have the Mysql compliant datetime stamp. 

edit: On closer inspection that doesn't appear to be the case.

### Additional Information Updated
We have further investigated the issue and this time the issue is reproducible in Magento 2.4-develop. In order to reproduce the issue, we have made some changes in the codebase like:

In the below file below line number `104`:

https://github.com/magento/magento2/blob/26057964cdb9057610de42284f605c93a6882407/app/code/Magento/Catalog/Cron/RefreshSpecialPrices.php#L104

We have reinitialized the $timestamp variable as follows:

```
$timestamp = "1662595200";
```

And then run the below command to debug the issue:

```
XDEBUG_CONFIG=idekey=phpstorm n98-magerun2.phar sys:cron:run catalog_index_refresh_price
```

Now the issue is reproducible for us. Please refer the below screenshot:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/51681618/188876378-e0ad7074-48de-41f0-8ab6-fc3af91c77d8.png">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-27 12:07
Hi @Quazz ,
Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue with provided steps.
No error was observed in the cron job at any time.
![image](https://user-images.githubusercontent.com/60198231/170696050-151fa631-0a67-4f72-aaf4-6973fe9d10a2.png)
Kindly recheck the issue again on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by loic-paquin** [comment] 2022-06-10 01:29
I got exactly the same error, the cron task failed at midnight but went smoothly at 10 am.

@engcom-November Please test again, I reproduced it on **2.4.4** and the cron **MUST** be launched at **midnight** ( default cron schedule) with some products with special prices.

**Comment by Mavlyan** [comment] 2022-06-15 13:00
To reproduce just run this simple Console Command. I've copied query from `catalog_index_refresh_price` cron.

```
<?php

namespace Unilever\EywaAddressNormalizer\Console\Command;

use Magento\Framework\App\ResourceConnection;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ReproduceCommand extends Command
{
    private const NAME = 'reproduce:pdo:bug';

    private \Magento\Framework\DB\Adapter\AdapterInterface $connection;

    public function __construct(
        ResourceConnection $resourceConnection
    ) {
        $this->connection = $resourceConnection->getConnection();

        parent::__construct(self::NAME);
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $identifierField = 'entity_id';
        $linkField = 'row_id';


        //Copy of Query
        $select = $this->connection
            ->select()
            ->from(
                ['attr' => $this->connection->getTableName('catalog_product_entity_datetime')],
                [
                    $identifierField => 'cat.' . $identifierField,
                ]
            )->joinLeft(
                ['cat' => $this->connection->getTableName('catalog_product_entity')],
                'cat.' . $linkField . '= attr.' . $linkField,
                ''
            )->where(
                'attr.attribute_id = ?',
                79
            )->where(
                'attr.store_id = ?',
                0
            )->where(
                "attr.value = DATE_FORMAT('2022-06-15', '%Y-%m-%d %H:%i:%s')"
            );


        //2nd param is redundant. To fix the issue - just remove it!
        $selectData = $this->connection->fetchCol($select, $identifierField);
    }
}
```

**Comment by Quazz** [comment] 2022-06-28 13:54
@engcom-November As pointed out by @Mavlyan the problem only occurs on PHP >8 and only when the time hits midnight (since it checks for "day" changes)

@Mavlyan also provided a possible solution for this problem which seems to work!

**Comment by kassner** [comment] 2022-08-10 07:26
https://github.com/magento/magento2/blob/2.4.4-p1/app/code/Magento/Catalog/Cron/RefreshSpecialPrices.php#L167

The second parameter there, `$identifierField`, resolves to `(string) "entity_id"`. However, `$connection` is an object of `Magento\Framework\DB\Adapter\Pdo\Mysql`, and `fetchCol` is defined as:

https://github.com/magento/zf1/blob/master/library/Zend/Db/Adapter/Abstract.php#L785-L797

It's expecting parameters to bound to the preparedStatement (i.e.: WHERE values, etc), but it's assumed to be the column to be returned. So it's being used in the wrong way.

I wrote a [small patch](https://gist.github.com/kassner/30c1bc89dbadb864e82d5f048487f2bc) that makes the error go away, however I can't really say it is working because I don't use special prices at all, so couldn't test it.

**Comment by engcom-Hotel** [comment] 2022-08-22 10:56
Hello @Mavlyan,

Thanks for the code sample here https://github.com/magento/magento2/issues/35517#issuecomment-1156442415.

We are able to reproduce the issue using that codebase sample. Can you please let us know from where you picked (File path) this code sample?

This will help us in moving forward with this ticket.

Thanks

**Comment by engcom-Hotel** [comment] 2022-09-05 08:09
Dear @Quazz @Mavlyan,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Comment by engcom-Hotel** [comment] 2022-09-07 12:18
Hello @Quazz,

We have further investigated the issue and this time the issue is reproducible in Magento 2.4-develop. In order to reproduce the issue, we have made some changes in the codebase like:

In the below file below line number `104`:

https://github.com/magento/magento2/blob/26057964cdb9057610de42284f605c93a6882407/app/code/Magento/Catalog/Cron/RefreshSpecialPrices.php#L104

We have reinitialized the $timestamp variable as follows:

```
$timestamp = "1662595200";
```

And then run the below command to debug the issue:

```
XDEBUG_CONFIG=idekey=phpstorm n98-magerun2.phar sys:cron:run catalog_index_refresh_price
```

Now the issue is reproducible for us. Please refer the below screenshot:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/51681618/188876378-e0ad7074-48de-41f0-8ab6-fc3af91c77d8.png">

Hence confirming the issue.

Thanks

**Comment by sprankhub** [comment] 2022-10-20 14:00
@kassner, thanks for the fix. I did not test your [diff](https://gist.github.com/kassner/30c1bc89dbadb864e82d5f048487f2bc) yet, but in https://github.com/magento/magento2/pull/34344, a similar fix to a similar issue has been merged.

**Comment by CHallski** [comment] 2022-11-10 22:19
I just finished tracing through this myself and came up with the exact same patch as @kassner and @Mavlyan (we DO use special prices). Wish I'd found this thread earlier and saved myself several hours of digging, but the title was definitely misleading as to the actual issue. This has nothing to do with the date formatting, but with the core code incorrectly calling a framework function.

This is still an issue on 2.4.5-p1.

**Comment by hostep** [comment] 2022-11-18 09:35
It looks like this was fixed internally by ticket "ACP2E-1243: the catalog_index_refresh_price cron fails with an error that is only reported when run between 0000 and 0059 UTC", commits: e0625468fcbf282b90cfbdd85e139f91e1275cc2 & 0e261c8a202be04a39a4c5ff4563165f0116e90f & d9557e6fd6f6335d7cc10e8a06445979cb113369
Unfortunately there is no clean merge commit, but here is a patch I created out of those 3 commits that can be applied to the `magento/module-catalog` module:
[ACP2E-1243-Catalog.txt](https://github.com/magento/magento2/files/10040046/ACP2E-1243-Catalog.txt)

Applying this patch on Magento 2.4.5-p1 works and the error no longer occurs for me.

@engcom-Hotel: this ticket can probably be closed since the fix was merged in 2.4-develop about 2 weeks ago.

**Comment by pmonosolo** [comment] 2022-12-06 22:57
There was a hotfix released for this issue (ACSD-47332):

![image](https://user-images.githubusercontent.com/66754347/206042496-51ee6f76-4794-442f-a7a7-0f504b702455.png)

**Comment by engcom-Hotel** [comment] 2022-12-07 06:55
Hello,

As mentioned in this https://github.com/magento/magento2/issues/35517#issuecomment-1319757036, the issue has been fixed and merged with the 2.4-develop branch. Hence closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-12-07 06:55 UTC
Labels: Component: Cron, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Framework, Reported on 2.4.4

**Comment by pmonosolo** [comment] 2022-12-07 17:02
> It looks like this was fixed internally by ticket "ACP2E-1243: the catalog_index_refresh_price cron fails with an error that is only reported when run between 0000 and 0059 UTC", commits: [e062546](https://github.com/magento/magento2/commit/e0625468fcbf282b90cfbdd85e139f91e1275cc2) & [0e261c8](https://github.com/magento/magento2/commit/0e261c8a202be04a39a4c5ff4563165f0116e90f) & [d9557e6](https://github.com/magento/magento2/commit/d9557e6fd6f6335d7cc10e8a06445979cb113369) Unfortunately there is no clean merge commit, but here is a patch I created out of those 3 commits that can be applied to the `magento/module-catalog` module: [ACP2E-1243-Catalog.txt](https://github.com/magento/magento2/files/10040046/ACP2E-1243-Catalog.txt)
> 
> Applying this patch on Magento 2.4.5-p1 works and the error no longer occurs for me.
> 
> @engcom-Hotel: this ticket can probably be closed since the fix was merged in 2.4-develop about 2 weeks ago.

New error shows up:

Type Error occurred when creating object: Magento\Catalog\Cron\RefreshSpecialPrices, Too few arguments to function Magento\Catalog\Cron\RefreshSpecialPrices::__construct(), 6 passed in /home/user/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 and exactly 7 expected

:(

**Comment by CHallski** [comment] 2022-12-07 17:18
@pmonosolo It looks like that patch doesn't include some underlying changes to the AbstractFactory that were probably done separately from those commits. Kassner's [diff](https://gist.github.com/kassner/30c1bc89dbadb864e82d5f048487f2bc) will address the cron error in isolation without the other changes.

**Comment by pmonosolo** [comment] 2022-12-07 17:22
Thanks! 

I just can't anymore, I mean seriously........

**Comment by MatthijsvanNoort** [comment] 2023-02-25 23:41
ACSD-47332 works for me on 2.4.5p1

> UPDATE: Patch is broken, do not use.
> 
> ==============
> 
> There was a hotfix released for this issue (ACSD-47332):
> 
> https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html?lang=en
> 
> ![image](https://user-images.githubusercontent.com/66754347/206042496-51ee6f76-4794-442f-a7a7-0f504b702455.png)

**Comment by dankhrapiyush** [comment] 2024-04-23 06:53
ACSD-47332 worked for 2.4.5-p2

**Comment by mahmoud-abdelmalek** [comment] 2025-03-24 15:09
@TheMetalMonkey-00 - @pmonosolo 
The Quality Patch resolved the issue but you have to recompile the dependency injection to avoid this Interceptor error
Run the following command to compile the dependency injection
`php bin/magento setup:di:compile`
