### ISSUE TITLE
No any message displaying after remove product from Ship to Multiple Addresses 

### ISSUE THREAD

**Issue by mageprince** [magento/magento2#21708] opened 2019-03-12 09:35 UTC
No any message displaying after remove product from Ship to Multiple Addresses 

### Preconditions (*)

Magento 2.3.x

### Steps to reproduce (*)

1. Login user >> Add to cart 2 or more products
2. Go to checkout with multiple addresses
3. Click on remove item

### Expected result (*)

Success message should display after removed the product.

### Actual result (*)

No any message display after remove item from multiple addresses.
![Ship to Multiple Addresses   Magento Commerce](https://user-images.githubusercontent.com/24751863/54189548-0a6c3880-44d8-11e9-82b0-b514f6780896.png)

**Comment by magento-engcom-team** [comment] 2019-03-12 09:35
Hi @mageprince. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mageprince do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-12 09:36
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-03-12 09:38
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-12 09:38
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-12 09:38
Hi @krishprakash, here is your [Magento instance](https://i-21708-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21708-2-3-develop.instances.magento-community.engineering/admin](https://i-21708-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by rogyar** [comment] 2019-03-12 10:57
Hi @mageprince. Thank you for your report. I believe it's not an issue. It's just the system designed in that way. There's no success message when you remove a product from the shopping cart or remove product upon admin order creation. We can consider this change as an improvement, but I have doubts about its usefulness.

**Comment by mageprince** [comment] 2019-03-12 11:07
@rogyar Yes, we can consider this as an improvement for better user experience.

**Comment by rogyar** [comment] 2019-04-03 07:46
As I said before. It's a good idea to show a success/failure message in case if something non-obvious is happening. For example, adding a product to the shopping cart, etc. In this case, you can see that the item has been removed on the main screen (as on the shopping cart/mini cart page).
So, we should avoid excessive notifications to keep the UI/UX simple.

**Closed as completed by rogyar** 2019-04-03 07:46 UTC
Labels: Component: Checkout, Area: Frontend, Issue: Clear Description, Reproduced on 2.3.x, non-issue, Issue: Format is valid, Component: Multishipping
