### ISSUE TITLE
Depreciated USPS Shipping methods; new USPS Ground Advantage method

### ISSUE THREAD

**Issue by Abbey-Lubber** [magento/magento2#37742] opened 2023-07-10 12:55 UTC
### Preconditions and environment

Magento 2.4.6-p1
Sample Data

### Steps to reproduce

1. Setup USPS shipping methods such as 'USPS First-Class Package', 'USPS Retail Ground' or 'USPS Parcel Select' in Stores->Configuration->Sales->Delivery Methods->USPS->Allowed Methods.
2. Add product (under 1lb product weight ) to cart on frontend.
3. Estimate shipping costs.

### Expected result

Shipping prices for all available shipping methods are displayed.

### Actual result

Shipping methods are not visible due to the fact that these shipping methods have been depreciated by USPS on July 9, 2023

https://faq.usps.com/s/article/USPS-Ground-Advantage

The new shipping method, USPS Ground Advantage, does not appear in the list of 'allowed shipping methods' and cannot be used.

*relative newbie creating this bug report...

![image](https://github.com/magento/magento2/assets/128196848/54c6ebeb-7d70-43e5-8c51-0b7d498d3cff)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by FadedOut** [comment] 2023-07-12 00:05
Wow this is a pretty big issue. Did USPS not give a heads up or did Magento drop the ball again?

Either way hopefully someone has a way to work in the new shipping methods as USPS is used by many many merchants (and customers) and waiting 6+ months for two releases from now would not be good...

**Comment by Abbey-Lubber** [comment] 2023-07-12 00:09
I got notifications from USPS and Pirateship the last week of June about the coming changes... I just assumed someone here had gotten the same notifications and patched it until I lost functionality on the 9th.... Looks like they are working on it though...

**Comment by FadedOut** [comment] 2023-07-12 04:33
Oh yeah, I just checked and you're right, Pirateship did send out a notice - but I didn't even notice the notice lol. Well, let's hope they really are working on it because my customers will be complaining soon I'm sure as USPS is used here and there.

**Comment by engcom-Dash** [comment] 2023-07-12 07:26
Hi @Abbey-Lubber ,

Verified the issue in 2.4-develop instance and the issue is reproducible,Hence we are confirming the issue.
Magento version 2.4-develop
PHP version8.1

**Steps to reproduce:**
1.Install magento instance
2.Go to Stores->Configuration->Sales->Delivery Methods->USPS->Allowed Methods
3.Select new shipping method "USPS Ground Advantage"

**Kindly refer the below video reference:**

https://github.com/magento/magento2/assets/60198592/59fa67a5-b716-4142-bd1f-1c2de8a0ef73

The new shipping method "USPS Ground Advantage" does not appear in the list of 'allowed shipping methods'.

Thanks

**Comment by swonton23** [comment] 2023-07-13 02:25
We are trying to find a solution. Please share if anyone has the fix?

**Comment by FadedOut** [comment] 2023-07-13 07:41
@swonton23 thankfully it looks like @Franciscof-Serfe is working on a PR as mentioned earlier in this ticket. Also, from that same page, it is mentioned (with a USPS pdf as source) that we have a grace period of up to Sep 30, 2023. So, we can keep using the available shipping methods listed in Magento for now and USPS will accept the packages even if they are the old ship methods.
But again, thankfully someone other than Magento devs are working on it because if we had to wait on them we'd all be screwed - at this point this will probably be April 2024 to be fixed "officially" in the Magento base. They always fix things two or more versions later. It's awful. IDK how the "Adobe Commerce" patching is with something like this but if this wasn't fixed immediately, I'd be cancelling my $20k+/mo subscription so quick. IDK how any pays that with such terrible delays in fixes. WooCommerce is also free and fixes things like this in one week. /ugh I digress...

**Comment by Abbey-Lubber** [comment] 2023-07-13 09:56
Just a clarification on the grace period: USPS will not generate labels or provide rate quotes for the deprecated shipping methods. They will only "Accept, process and deliver" these shipping services. As of July 9th, 2023, 'First Class Package, Parcel Select Ground and Ground Returns' do not show on the website frontend and cannot be selected by customers. This is literally the least expensive shipping method available in the USA and the most common shipping method chosen on my website...
Again, I appreciate @Franciscof-Serfe working on this...

**Comment by Franciscof-Serfe** [comment] 2023-07-13 13:12
@magento I am working on this

**Comment by Franciscof-Serfe** [comment] 2023-07-13 13:13
@magento add to contributors team
@magento I am working on this

**Comment by DMC-15** [comment] 2023-07-13 13:19
@Franciscof-Serfe Thanks for helping out on this!

**Comment by FadedOut** [comment] 2023-07-14 02:57
@Abbey-Lubber 
> Just a clarification on the grace period: USPS will not generate labels or provide rate quotes for the deprecated shipping methods. They will only "Accept, process and deliver" these shipping services. As of July 9th, 2023, 'First Class Package, Parcel Select Ground and Ground Returns' do not show on the website frontend and cannot be selected by customers.

Wow it's even worse than I thought. Unbelievable. This makes me very nervous to be using Magento for my business with barely an official response to this situation...

**Comment by bbatten** [comment] 2023-07-20 20:26
@Franciscof-Serfe Thanks for helping out on this!

Do you have any updates on a solution?  Do you know when we can expect a fix?

**Comment by Abbey-Lubber** [comment] 2023-07-20 21:44
@esteban-serfe has provided working patches in the pull request (#37745) above. Most of @Franciscof-Serfe's patches have been reverted. Manually patched on my website and appears to be working beautifully!

**Comment by DMC-15** [comment] 2023-07-21 16:54
@Abbey-Lubber are the patches fully functional yet? It looks like some checks are still being ran.

**Comment by Franciscof-Serfe** [comment] 2023-07-21 18:40
Hello everyone,
  I wanted to share some good news. The issue with USPS shipping methods has been successfully resolved in pull request #37745 
  
You can find the validation in this comment:   https://github.com/magento/magento2/pull/37745#issuecomment-1646083016 of what the test instance showed.

Currently, we are finishing the final adjustments to the test results to complete the process.
Best regards, 
Francisco

**Comment by DMC-15** [comment] 2023-07-21 18:45
@Franciscof-Serfe Great news indeed! Thank you for all your help and hard work! I'll let my developers know.

**Comment by Franciscof-Serfe** [comment] 2023-07-21 20:02
@magento add:pr 37745

**Comment by Franciscof-Serfe** [comment] 2023-07-25 01:41
Hi @engcom-Dash , 
 Can you relate this issue to PR #37745?
  I have not found what command I should pass to the bot to do it or if there is one that can run as a collaborator.

Thank you so much!

**Comment by engcom-Bravo** [comment] 2023-07-26 07:07
Hi @Abbey-Lubber,

Thank you for reporting and collaboration.

"Team has started processing this PR [#37745](https://github.com/magento/magento2/issues/37745) internally after testing all possible scenarios."

Thanks.

**Comment by Franciscof-Serfe** [comment] 2023-08-09 01:49
@magento give me 2.4.4-p5 instance

**Comment by Franciscof-Serfe** [comment] 2023-08-09 01:51
@magento give me 2.4-develop instance

**Comment by chernenm** [comment] 2023-08-28 19:50
A hotfix for this issue for all 2.4.4, 2.4.5 and 2.4.6 versions has been released recently https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/known-issues-patches-attached/usps-ground-advantage-shipping-method-support-hotfix-for-ac-9182.html

**Closed as completed** 2023-09-01 20:55 UTC
Labels: Issue: Confirmed, Component: Usps, Reproduced on 2.4.x, Priority: P1, Progress: done, Issue: ready for confirmation, Area: Admin UI, Reported on 2.4.6-p1
