### ISSUE TITLE
Source item status not changed after product qty reaches 0 

### ISSUE THREAD

**Issue by Pawlo2703** [magento/magento2#36569] opened 2022-12-06 12:02 UTC
### Preconditions and environment

- clean 2.4.4 version
- PHP8.1
- Default store view
- inventory configuration:
![image](https://user-images.githubusercontent.com/26777333/205905867-dc0240ea-a6b3-4be1-b8fa-23a6d40015e4.png)

### Steps to reproduce

1. Create new source (example name: 'test')
2. Create new stock and assign previously created source
3. Create simple product (example name 'test-product') and assign it to prevously created source
4. Set test source **qty to 5**
5. Go to frontend, **add 5 qty** of 'test-product' to cart, proceed to checkout as guest, use **Flat Rate** as shipping method and **checkmoney or cash on delivery** as payment methods.
6. Go to backend sales -> order. Choose recently create order.
7. Create invoice with **Qty to invoice: 5**
8. Create shipment with **Qty to ship: 5**

### Expected result

test source item stats is out of stock when qty reaches 0

### Actual result

test source item status is in stock when qty reaches 0
![image](https://user-images.githubusercontent.com/26777333/205904693-15b08764-f071-428b-8447-b6e2faab8bb4.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-12-06 12:30
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-12-06 12:57
Hi @Pawlo2703,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

1.Create new source (example name: 'test')
2.Create new stock and assign previously created source
3.Create simple product (example name 'test-product') and assign it to prevously created source
4.Set test source qty to 5
5.Go to frontend, add 5 qty of 'test-product' to cart, proceed to checkout as guest, use Flat Rate as shipping method and 6.checkmoney or cash on delivery as payment methods.
7.Go to backend sales -> order. Choose recently create order.
8.Create invoice with Qty to invoice: 5
9.Create shipment with Qty to ship: 5


<img width="1357" alt="Screenshot 2022-12-06 at 5 58 24 PM" src="https://user-images.githubusercontent.com/51680745/205918663-a17b58fc-e154-44e2-80ab-868d7ee5ec4a.png">



<img width="1403" alt="Screenshot 2022-12-06 at 5 58 36 PM" src="https://user-images.githubusercontent.com/51680745/205918684-9b19a83e-ab9c-420e-b391-d43ced0f2641.png">


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by Pawlo2703** [comment] 2022-12-08 07:01
Thanks @engcom-Bravo for the reply
I ve rechecked the issue on Magento 2.4-develop and I was able to reproduce issue
![image](https://user-images.githubusercontent.com/26777333/206380012-bcc32a37-aac9-49be-b9e9-c4c8c520fff2.png)
![image](https://user-images.githubusercontent.com/26777333/206380140-5b446a39-713e-4e7a-9e26-8236ec4fffa4.png)

**Comment by engcom-Bravo** [comment] 2022-12-09 11:20
Hi @Pawlo2703,

Thanks for your Update.

As per Magento devdocs we need to update sources manually for a product.

Kindly go through with this document

https://experienceleague.adobe.com/docs/commerce-admin/inventory/quantities/quantities-assign-per-product.html?lang=en


<img width="1175" alt="Screenshot 2022-12-09 at 4 03 49 PM" src="https://user-images.githubusercontent.com/51680745/206691107-cb22262c-d88b-403f-a285-ed087e27b8bf.png">



Kindly let us know if you are still facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2022-12-21 06:12
Hi @Pawlo2703,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-12-21 06:12 UTC
Labels: Issue: needs update, Reported on 2.4.4
