### ISSUE TITLE
Add to cart redirection

### ISSUE THREAD

**Issue by Aartitops** [magento/magento2#6416] opened 2016-08-31 10:43 UTC
Hi,
I use  Magento ver. 2.0.0.
I want to chnage add to cart button with more info button and i change button text also redirect url but it can't redirect product detail page.
Actual result:- 
![tifin](https://cloud.githubusercontent.com/assets/20356638/18125863/1cf308ea-6f96-11e6-9681-61773fa41fb9.png)

Excepted result:- 
when i click on more info button it will redirect product detail page.

**Comment by veloraven** [comment] 2016-08-31 11:45
@Aartitops thank you for your feedback.
Please provide more detailed steps: what exactly you have changed and how.

**Comment by PingusPepan** [comment] 2016-08-31 11:50
You can't simply just edit the Add to cart button to redirect you to another page instead of adding the product to cart. You should edit the template more and completely replace the button with, for example, styled link so it looks like a button. That would be much easier than forcing the Add to cart button to do this.

**Comment by developer-lindner** [comment] 2016-08-31 12:22
@Aartitops Why are using version 2.0.0 and create a ticket here when there is version 2.1.1 already out ? This is just a waste of time for everyone here.

**Comment by andimov** [comment] 2016-09-27 09:41
@Aartitops 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:41 UTC
Labels: Progress: needs update
