### ISSUE TITLE
Bulk API PUT/DELETE do not work when Magento_ReCaptchaWebapiRest is enabled

### ISSUE THREAD

**Issue by nuzil** [magento/magento2#35348] opened 2022-04-21 11:18 UTC
### Preconditions (*)
1. Magento 2.4.3 - 2.4.4

### Steps to reproduce (*)
1. Execute any Rest Api Bulk request with PUT or DELETE, when in URL expected 1 or more parameters. Example: {{URL}}rest/async/bulk/V1/products/bySku
**Sample payload:**
_[
   {
      "product":{
         "sku":"24-MB01",
         "name":"Printed Dress",
         "status":1,
         "visibility":4,
         "price":17
      }
   },
   {
      "product":{
         "sku":"24-MB04",
         "name":"Black WATCH",
         "status":1,
         "visibility":4,
         "price":77
      }
   }
]_
3. Request will return 500 and exception.

### Expected result (*)
1. Execute any Rest Api Bulk request with PUT or DELETE, when in URL expected 1 or more parameters. Example: {{URL}}rest/async/bulk/V1/products/bySku
2. Request will return 200 and will be processed correctly

### Actual result (*)
1. See "Steps to reproduce" for actual result.
2. If disable module "Magento_ReCaptchaWebapiRest", then requests start to work.

**Additional Information:**
Exception stack trace:

`[2022-04-26T08:31:18.611204+00:00] main.CRITICAL: TypeError: Argument 1 passed to Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver::resolveBulkItemParams() must be of the type array, string given, called in /var/www/html/mg24/magento2/app/code/Magento/WebapiAsync/Controller/Rest/Asynchronous/InputParamsResolver.php on line 123 and defined in /var/www/html/mg24/magento2/app/code/Magento/WebapiAsync/Controller/Rest/Asynchronous/InputParamsResolver.php:178
Stack trace:
#0 /var/www/html/mg24/magento2/app/code/Magento/WebapiAsync/Controller/Rest/Asynchronous/InputParamsResolver.php(123): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolveBulkItemParams()
#1 /var/www/html/mg24/magento2/app/code/Magento/WebapiAsync/Controller/Rest/AsynchronousRequestProcessor.php(100): Magento\WebapiAsync\Controller\Rest\Asynchronous\InputParamsResolver->resolve()
#2 /var/www/html/mg24/magento2/app/code/Magento/Webapi/Controller/Rest.php(195): Magento\WebapiAsync\Controller\Rest\AsynchronousRequestProcessor->process()
#3 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#4 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#5 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#6 /var/www/html/mg24/magento2/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#7 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#8 /var/www/html/mg24/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#9 /var/www/html/mg24/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#10 /var/www/html/mg24/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#11 {main} [] []`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-21 12:45
Verified the issue on both Magento 2.4-develop and 2.4.4 versions and the issue is reproducible:
Requests used:
PUT request to /rest/all/async/bulk/V1/products/bySku
Sample payload:
`[ { "product": { "sku": "24-MB01", "name": "Printed Dress", "status": 1, "visibility": 4, "price":17 } }, { "product": { "sku": "24-MB04", "name": "Black WATCH", "status": 1, "visibility": 4, "price":77 } } ]`

Delete request to /rest/async/bulk/V1/cmsPage/byPageId
`[
    {
        "pageId": "7"
    }
]
`

![image](https://user-images.githubusercontent.com/60198231/164460563-7c610ccc-d887-48e6-8bd8-b515b7c664c3.png)
![image](https://user-images.githubusercontent.com/60198231/164460631-f154ff1f-8a0b-4ef7-a6ff-e0fc0708e399.png)

**Comment by engcom-Hotel** [comment] 2022-05-26 11:19
Hence this is a duplicate of https://github.com/magento/magento2/issues/35370, closing this ticket.

Thank you!

**Closed as completed by engcom-Hotel** 2022-05-26 11:19 UTC
Labels: Issue: Confirmed, Component: Api, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: APIs, Reported on 2.4.4
