### ISSUE TITLE
Untranslatable string "Short Description" in product compare module

### ISSUE THREAD

**Issue by jernejh** [magento/magento2#6663] opened 2016-09-19 08:12 UTC
### Preconditions

1. Magento 2.1.1
2. Php 7.0
### Steps to reproduce

1. Compare 2 products
### Expected result

1. String "Short Description" should be translatable, but it is not generated with magento i18n:collect-phrases tool
### Actual result

![2016-09-18 1](https://cloud.githubusercontent.com/assets/282687/18625848/87a6925a-7e51-11e6-9f78-95ff26afec79.png)

**Comment by sevos1984** [comment] 2016-09-21 12:43
This is a product attribute, to translate it you should add storeview label in admin. Closing as not a bug.

**Closed as completed by sevos1984** 2016-09-21 12:43 UTC

**Comment by jernejh** [comment] 2016-09-22 02:07
True. Thank you!
