### ISSUE TITLE
SQL error in Reports -> Reviews -> By Customers using table prefiix

### ISSUE THREAD

**Issue by nja78** [magento/magento2#3609] opened 2016-03-02 09:26 UTC
SQL for this report does not use table prefix and we cannot view report Reports -> Reviews -> By Customers

See trace report attached
[fatal_error_m2.txt](https://github.com/magento/magento2/files/154398/fatal_error_m2.txt)

**Comment by veloraven** [comment] 2016-08-17 07:39
@nja78 thank you for your report.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by nja78** [comment] 2016-08-17 07:57
Description
1. Magento ver. 2.1.0 with sample data
2. table prefix "m2_" used while installation

Steps to reproduce
1. login to admin panel
2. go to Reports -> Reviews -> By Customers

Expected result
Report page

Actual result
got SQL error, that table "customer_entity" does not exist. And its true, becouse we used table prefix and database contain table m2_customer_entity

**Comment by sevos1984** [comment] 2016-09-14 15:30
This is fixed in develop https://github.com/magento/magento2/commit/18e8998b87f4049d705e875d83d461915d208fca and will be fixed for 2.1. Internal ticket created MAGETWO-58405. Thanks for reporting.

**Comment by magento-engcom-team** [comment] 2017-10-17 07:30
@nja78, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-17 07:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
