### ISSUE TITLE
Password strength not updating issue on register page 

### ISSUE THREAD

**Issue by renard123** [magento/magento2#32630] opened 2021-03-31 05:30 UTC
### Preconditions (*)

1. Magento 2.4

### Steps to reproduce (*)

- As guest user add 2-3 products to cart 
- Shopping Cart 
- Click on Checkout with multiple addresses 
- Login page -> Click on Create an account button 
- Create an account page -> Enter value in password 
- Observe password strength not update

### Expected result (*)

Password strength should be updated as enter values 

### Actual result (*)

https://prnt.sc/y4x64i

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magento-engcom-team** [comment] 2021-03-31 05:32
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41670` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ihor-sviziev** [comment] 2021-03-31 10:19
Hi @renard123,
This issue duplicates https://github.com/magento/magento2/issues/32629, as it happened on the same page and was caused by the same JS error https://github.com/magento/magento2/issues/32629#issuecomment-810950643.

I'm closing this issue as a duplicate

**Comment by magento-engcom-team** [comment] 2021-03-31 10:20
Hi @renard123, @ihor-sviziev. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-41670` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Closed as completed by ihor-sviziev** 2021-03-31 10:19 UTC
Labels: duplicate, Issue: Confirmed, Component: Multishipping, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P3, Severity: S3, Progress: done, Issue: ready for confirmation

**Comment by ihor-sviziev** [comment] 2021-04-07 05:52
Hi,

This issue was fixed in https://github.com/magento/magento2/commit/461509df6db50edf65de181ecb7decc27519a748.
