### ISSUE TITLE
cron job Re-indexing takes 1 hour and gets stuck mostly

### ISSUE THREAD

**Issue by adityag186** [magento/magento2#7963] opened 2016-12-26 18:48 UTC
### Preconditions
1.  2CPU Cores, CentOS, 5GB RAM, 60GB SSD on siteground cloud server
2. Magento CE 2.1.3
3. 350000 products,5GB database size

### Steps to reproduce

1. Cron job runs re-indexer at night when there is no traffic 99% of the times

### Expected result

1. Indexing should happens in 10 minutes at the most I guess

### Actual result

1. Indexers get stuck at processing. Catalog search gets stuck.
2. Website does not show products for that time
3. Manual re-indexing needs to be done everytime it happens

**Comment by choukalos** [comment] 2017-01-05 18:40
Tracking the issue for FullText indexer as MAGETWO-56356 - we're planning on addressing near term.

**Comment by choukalos** [comment] 2017-02-21 16:51
In the short term please adjust your MySQL configuration - tmp_table_size variable so indexer continues.

**Comment by adityag186** [comment] 2017-02-21 18:12
Hi,

Can you please tell me steps on how to do that?

**Comment by maghamed** [comment] 2017-02-21 22:53
@adityag186 
You have to set MySQL global system variable  https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_tmp_table_size
which default value is 16MB, If an in-memory temporary table exceeds the limit, MySQL automatically converts it to an on-disk MyISAM table, so the re-indexation process stucks.

you can read how to do it in this article 
https://dev.mysql.com/doc/refman/5.7/en/using-system-variables.html

**Comment by magento-engcom-team** [comment] 2017-10-25 12:30
@adityag186, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-25 12:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
