### ISSUE TITLE
Reset customer password with /V1/customers/resetPassword

### ISSUE THREAD

**Issue by VZeroCool** [magento/magento2#28235] opened 2020-05-15 07:36 UTC
### Preconditions (*)

1. Magento 2.3.3 CE
2. Apache + AWS

### Steps to reproduce (*)

1. Create customer password reset token
2. `$resetPasswordToken = $this->userData->generateResetPasswordLinkToken();` 
    `New \Magento\User\Helper\Data;`
2. Invoke  /V1/customers/resetPassword to set new password

### Expected result (*)

1. It should update customer password with given in "newPassword" key
2.

### Actual result (*)

1. The password token is mismatched. Reset and try again.
2. `{"message":"The password token is mismatched. Reset and try again.","trace":"#0 \/var\/www\/html\/magento\/vendor\/magento\/module-customer\/Model\/AccountManagement.php(685): Magento\\Customer\\Model\\AccountManagement->validateResetPasswordToken('32', '5SEwugR9l6tgtvs...')\n#1 \/var\/www\/html\/magento\/generated\/code\/Magento\/Customer\/Model\/AccountManagement\/Interceptor.php(102): Magento\\Customer\\Model\\AccountManagement->resetPassword('zerocool@gm...', '5SEwugR9l6tgtvs...', 'admin1234')\n#2 [internal function]: Magento\\Customer\\Model\\AccountManagement\\Interceptor->resetPassword('zerocool@gm...', '5SEwugR9l6tgtvs...', 'admin1234')\n#3 \/var\/www\/html\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#5 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#7 \/var\/www\/html\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/html\/magento\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#9 \/var\/www\/html\/magento\/vendor\/magento\/framework\/App\/Http.php(137): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/magento\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#11 \/var\/www\/html\/magento\/vendor\/magento\/framework\/App\/Bootstrap.php(261): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#12 \/var\/www\/html\/magento\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#13 {main}"}` 

**UPDATE**

After generating token with `$resetPasswordToken = $this->userData->generateResetPasswordLinkToken();` 
    `New \Magento\User\Helper\Data;`

I'm verifying token with `/V1/customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}`

In response getting **true** but still /V1/customers/resetPassword showing same error as above.

**Comment by VZeroCool** [comment] 2020-05-15 07:37
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-15 07:37
Hi @VZeroCool. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-15 07:39
Hi @VZeroCool, here is your [Magento instance](https://i-28235-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28235-2-4-develop.instances.magento-community.engineering/admin_e997](https://i-28235-2-4-develop.instances.magento-community.engineering/admin_e997)
Login: `86e963e7` Password: `9d0a892b79ec`
Instance will be terminated in up to 3 hours.

**Comment by VZeroCool** [comment] 2020-05-15 07:48
I need code access to generate PasswordReset token, I'm not able to find any API for generate passwordreset token. If its there can anyone share  ?

**Comment by VZeroCool** [comment] 2020-05-15 08:08
After generating token with $resetPasswordToken = $this->userData->generateResetPasswordLinkToken();
New \Magento\User\Helper\Data;

I'm verifying token with /V1/customers/{customerId}/password/resetLinkToken/{resetPasswordLinkToken}

In response getting true but still /V1/customers/resetPassword showing same error as above.

**Comment by swathishs** [comment] 2020-06-04 13:17
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-04 13:17
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment] 2020-06-04 17:54
@VZeroCool : Tested the issue in both 2.3.5p1 and 2.4 develop instance. The issue is not reproducible. Hence closing the ticket.

**Closed as completed by swathishs** 2020-06-04 17:54 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid, Component: Api, Reported on 2.3.3
