### ISSUE TITLE
FPT is not added in cart for child products

### ISSUE THREAD

**Issue by eBusinessAtlantique** [magento/magento2#37711] opened 2023-07-04 11:09 UTC
### Preconditions and environment

- Magento version : M2.4.6-p1
- Theme Luma

### Steps to reproduce

Activate FPT in VAT menu
Set visiblilty of FPT to Included and whow description (2nd choice in dropdown)

Create an attribute called "ecotax". Set the attribute type to Fixed product tax.
Add this attribute to your preferred attribute set next to Cost in Price section so you can easily find it.

Create a configurable product.
Create a child product at 100€ with FPT like 2€
See product in storefront product page and list page

### Expected result

1. On list view, the product is visible at 102 €
2. On product page the product is visible at 102€ when attribue option is not selected or selected.
3. In cart the child product is sold at 102€

### Actual result

1. Bug on list view : 
The product is sold at 100€.
2. Bug on product view : if attribute option is not selected product price is 100€
3. Product is sold at 100€ in cart

### Additional information

To verify if behaviour is correct on single product  >
Create a single procuct with price 100€. Add FPT at 2€.
View the product in storefront in list view and product page, price is always correct at 102€.
Add the product to the cart : product is at 102€. FPT is shown under a dropdown at 2€

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by eBusinessAtlantique** [comment] 2023-07-04 11:12
![Panier(2)](https://github.com/magento/magento2/assets/910330/cb4721fb-fdf2-45a5-ba4f-6d531688539d)
Screenshot of cart
Both products have the same prices and the same FPT.
First product is a child product.
Second product is a simple product.
FPT is only added to simple product and not to the child product.

**Comment by eBusinessAtlantique** [comment] 2023-07-04 14:39
Reproduced the issue on dev instance.

**Comment by eBusinessAtlantique** [comment] 2023-07-04 15:02
Issue: Confirmed

**Comment by eBusinessAtlantique** [comment] 2023-07-04 15:22
How do I add a label on my ticket ????

**Comment by engcom-Bravo** [comment] 2023-07-05 09:50
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-07-05 12:43
Hi @eBusinessAtlantique,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.


**Steps to reproduce**

- Activate FPT in VAT menu
- Set visiblilty of FPT to Included and whow description (2nd choice in dropdown)
- Create an attribute called "ecotax". Set the attribute type to Fixed product tax.
- Add this attribute to your preferred attribute set next to Cost in Price section so you can easily find it.
- Create a configurable product.
- Create a child product at 100€ with FPT like 2€
- See product in storefront product page and list page



<img width="1346" alt="Screenshot 2023-07-05 at 4 00 42 PM" src="https://github.com/magento/magento2/assets/51680745/e9b5015f-71ee-45d3-b599-80d14f04beb3">




<img width="1356" alt="Screenshot 2023-07-05 at 3 54 00 PM" src="https://github.com/magento/magento2/assets/51680745/51d58494-59b6-40d1-8a94-bfcb35fcb23a">



On list view product is showing at 102 € and child product is sold at 102 €.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-17 06:22
Hi @eBusinessAtlantique,

Please provide us latest update on this https://github.com/magento/magento2/issues/37711#issuecomment-1621683858 still you are working on this issue,if you are able to reproduce the issue provide us steps to reproduce the issue.Please let us know if you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-25 06:05
Hi @eBusinessAtlantique,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-25 06:05 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
