### ISSUE TITLE
A product that gets disabled stays in shopping carts.

### ISSUE THREAD

**Issue by TimQSO** [magento/magento2#24924] opened 2019-10-08 13:17 UTC
**Preconditions (*)**

- Magento 2.2.7
- Redis Cache Enabled
- Built-In FPC Enabled

**Steps to reproduce (*)**

1. Enable persistent shopping carts
2. Create a customer account and login
3. Add a product to your cart
4. Add another, different, product to your cart
5. Go to the backend and disable one of those products that are in the cart, put the stock on 0 and disable backorders of that product
6. Go to the front end again and check the cart, the disabled product is gone
7. Try to checkout

**Expected result (*)**

The customer should be able to checkout with the product that is left in the cart

**Actual result (*)**

The customer gets a message that one of the products are out of stock and he is not able to checkout.

**Comment by webkul-ratnesh** [comment] 2019-10-11 10:56
@magento i am working on it

**Comment by webkul-ratnesh** [comment] 2019-10-12 07:03
unable to reproduce this issue in 2.3-develop branch. So I am closing this issue.

**Closed as completed by webkul-ratnesh** 2019-10-12 07:03 UTC
Labels: Issue: Format is valid
