### ISSUE TITLE
Shipping Address saved when customers use mobile gadget

### ISSUE THREAD

**Issue by Zu-Hause-Plattform** [magento/magento2#12620] opened 2017-12-11 09:03 UTC
Hi, 
we are having issues on our website which is when customers make a purchase with their mobile phones, the shipping address is not relayed to us. Desktop seems to be alright.
Can you guys help us fix this issue?
here is the link to screenshot of the issue:
https://www.awesomescreenshot.com/image/3029835/219d7d52837f15afe36cf436a6ebcf11

Preconditions:
Magento ver. 2.1.7

Steps to reproduce:
1- Go to frontend(https://shop.zähler-plattform.de) and purchase any product
2- Log in to backend and choose the order

Expected result: 
Invoice address and Shipping address should be listed in the order overview

Actual result:
only the Invoice address is shown(see attachment)

thanks for your prompt response

**Comment by magento-engcom-team** [comment] 2017-12-11 09:36
@Zu-Hause-Plattform , thank you for your report.
Please use the issue [reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) to report an issue. Please, edit issue description and include the preconditions, the steps required to reproduce, the actual result, and the expected result.
Please, add the following information:
 - [ ] Preconditions: Magento version
 - [ ] Steps to reproduce
 - [ ] Expected result
 - [ ] Actual result

**Comment by Zu-Hause-Plattform** [comment] 2017-12-11 11:12
Hello Magento Team,
i have updated the issue, please let me know if more info. is needed.

Thanks

**Comment by magento-engcom-team** [comment] 2017-12-11 14:30
@Zu-Hause-Plattform, thank you for your report.
The issue is already fixed in 2.2.1

**Closed as completed by magento-engcom-team** 2017-12-11 14:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
