### ISSUE TITLE
Unable to save product when price si website defined and custom options

### ISSUE THREAD

**Issue by frangolacci** [magento/magento2#22346] opened 2019-04-15 14:26 UTC
### Preconditions (*)

1. Under Magento Multisite 2.3.0 (it's the same under 2.3.1)
2. My backend Locale is fr_FR , so the decimal separator is , (instead of . for en_US)

### Steps to reproduce (*)

1. Put the price at website level (instead of global by default) (to do so, go to configuration -> catalog -> catalog -> Price )
2. Add custom options to a product with a fixed price of 0 and save it
3. Try to save the same product under a specific website view scope

### Expected result (*)

1. The product is successfully saved under this specific view
2.

### Actual result (*)

1. The product is not saved , the error is:
2. **Notice: A non well formed numeric value encountered in XXX/vendor/magento/module-catalog/Model/ResourceModel/Product/Option.php on line 175**

After searching the explanation , i found that in the Options.php file, if we are in a specific view scope and if the price scope if website instead of global (by default), Magento try to calculate the new price of the option (in case the is not the same currency i guess) with the line (175):
`$newPrice = $object->getPrice() * $rate;`
But , if the option price value is 0 , the value of $object->getPrice() is 0,00 (because of my locale) and it raise an error when trying to do:  0,00 * $rate.

I tried to put 0 in the option's price input box , so i can save the product. but Immediately after, Magento put again 0,00 in the option price box (still because of my locale) so i can't save the product anymore without changing 0,00 by 0 every time .

If i cast by a float the value of $object->getPrice(), it solve the issue.

PS: if the backend locale is en_US , we can't reproduce this issue because magento will put 0.00 instead of 0,00 , and 0.00 * 1 will not raise a php error

**Comment by shikhamis11** [comment] 2019-05-10 10:33
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-05-10 10:34
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-05-10 10:34
Hi @shikhamis11, here is your [Magento instance](https://i-22346-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22346-2-3-develop.instances.magento-community.engineering/admin](https://i-22346-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-05-29 16:31
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-99866` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by supportnubix** [comment] 2019-07-09 10:35
As the issue is reproduced on 2.3.x, is anyone still looking at this issue?

**Comment by edenduong** [comment] 2019-07-14 14:31
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-14 14:31
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-14 14:32
Hi @edenduong, here is your [Magento instance](https://i-22346-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-22346-2-3-develop.instances.magento-community.engineering/admin](https://i-22346-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by tdgroot** [comment] 2019-10-07 10:04
@magento-engcom-team I'm picking up this issue.

**Closed as completed** 2019-10-23 13:20 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid
