### ISSUE TITLE
M2.1 : Head link manifest HREF attr not work correct

### ISSUE THREAD

**Issue by denis-g** [magento/magento2#6765] opened 2016-09-27 10:36 UTC
### Preconditions

Magento 2.1 EE
### Steps to reproduce
1. open `Magento_Theme/layout/default_head_blocks.xml`
2. insert  
   `<link rel="manifest" href="manifest.json" />`
### Expected result

`<link  rel="manifest" href="http://site.com/static/frontend/Vendor/default/en_US/Magento_Theme/manifest.json" />`
### Actual result

`<link  rel="manifest" href="manifest.json" href="http://site.com/static/frontend/Vendor/default/en_US" />`

~~
_Magento2 makes me crazy._

**Comment by piatrouski** [comment] 2016-09-27 11:38
> Don't worry, be happy
> In every life we have some trouble
> When you worry you make it double
> Don't worry, be happy

**Comment by veloraven** [comment] 2016-09-27 13:03
@denis-g thank you for your report.
If this issue is actual for Enterprise Edition only, please address it to Magento Support.

**Comment by pavelnovitsky** [comment] 2016-09-27 15:29
Confirm the same bug in CE 2.1.1

**Comment by anton-huz** [comment] 2016-10-05 14:39
@denis-g , @pavelnovitsky 
You can use the `src=".."` attribute for proper behavior. It will be processed and converted to `href=".."`.
Some additional notes – [Page layout instructions on devdocs](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/layouts/layout-types.html#layout-types-conf).

Also, there was created an internal issue for the proper handling attributes and their merging: MAGETWO-59371.
Please, stay in touch.

**Comment by korostii** [comment] 2017-03-13 14:02
See also similar #5023

**Comment by magento-engcom-team** [comment] 2017-10-17 11:30
@denis-g, thank you for your report.
We've created internal ticket(s) MAGETWO-59371 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2019-01-29 13:59
Hi @vasilii-b. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by vasilii-b** [comment] 2019-01-29 14:15
As for Magento `2.3-develop` you cannot add `href` attribute to the `link`:
![xnip2019-01-29_16-08-24](https://user-images.githubusercontent.com/13456702/51913882-388e3100-23e0-11e9-93a7-6729cb319cc7.jpg)
If the `src` attribute is used instead, the url is generated absolutely fine:
![xnip2019-01-29_16-14-25](https://user-images.githubusercontent.com/13456702/51914242-0a5d2100-23e1-11e9-849b-5a3c3e218733.jpg)

**Comment by vasilii-b** [comment] 2019-01-29 14:17
Closing the issue as it was not reproduced on 2.3-develop instance.

**Closed as completed by vasilii-b** 2019-01-29 14:17 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend, Issue: Clear Description, Reproduced on 2.1.x, Reproduced on 2.2.x, Issue: Format is valid, Component: Theme
