### ISSUE TITLE
Frontend show message "Merge for content type" when Upgrade magento 2.1.9 to version 2.2.1 : 1 exception(s): Exception #0 (InvalidArgumentException): Merge for content type '' is not supported.

### ISSUE THREAD

**Issue by LeLieu** [magento/magento2#12189] opened 2017-11-11 09:27 UTC
```
1 exception(s):
Exception #0 (InvalidArgumentException): Merge for content type '' is not supported.
Exception #0 (InvalidArgumentException): Merge for content type '' is not supported.
#0 /var/www/html/magento2/var/generation/Magento/Framework/View/Asset/MergeService/Interceptor.php(24): Magento\Framework\View\Asset\MergeService->getMergedAssets(Array, '')
#1 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(266): Magento\Framework\View\Asset\MergeService\Interceptor->getMergedAssets(Array, '')
#2 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(239): Magento\Framework\View\Page\Config\Renderer->processMerge(Array, Object(Magento\Framework\View\Asset\PropertyGroup))
#3 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(226): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup))
#4 /var/www/html/magento2/lib/internal/Magento/Framework/View/Page/Config/Renderer.php(99): Magento\Framework\View\Page\Config\Renderer->renderAssets(Array)
#5 /var/www/html/magento2/lib/internal/Magento/Framework/View/Result/Page.php(235): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#6 /var/www/html/magento2/lib/internal/Magento/Framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#7 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#9 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#10 /var/www/html/magento2/app/code/Magento/PageCache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#12 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#13 /var/www/html/magento2/app/code/Magento/PageCache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#14 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#15 /var/www/html/magento2/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#16 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#17 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#18 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#19 {main}
```

**Comment by magento-engcom-team** [comment] 2017-11-16 11:18
@LeLieu Please format your issue description according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Comment by magento-engcom-team** [comment] 2017-11-20 12:52
@LeLieu, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.10, 2.2.1
Also, the answer to your problem might be here: https://magento.stackexchange.com/questions/106436/merged-js-and-css-do-not-work-when-production-mode we hope that helps you.

**Closed as completed by magento-engcom-team** 2017-11-20 12:52 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
