### ISSUE TITLE
datetime bug in (product) import/export

### ISSUE THREAD

**Issue by bh-ref** [magento/magento2#3814] opened 2016-03-16 15:10 UTC
## Steps to reproduce
1. In backend, go to Stores / Settings / Configuration / General / General / Locale Options.
2. Set `Locale` to `German (Switzerland)`.
3. Export a product which has value in a datetime field (Special price from/to date, New from/to date).
## Expected result
1. With the Locale `English (United States )`, a an exportet datetime looks like `2015-03-16 16:08:55`
## Actual result
1. With the Locale `German (Switzerland)`, a an exportet datetime looks like `16.03.15, 17:08`
2. Which is a problem, because when I delete the product and use the export to import/create it again, it fails with the following error message:
   `Value for '%s' attribute contains incorrect value`

**Comment by piotrekkaminski** [comment] 2016-06-11 01:12
internal issue MAGETWO-54246

**Comment by veloraven** [comment] 2017-06-20 13:06
I'm closing this issue as we were not able to reproduce it on develop branch, most likely it was fixed in scope of some other task.
If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by veloraven** 2017-06-20 13:06 UTC
Labels: Issue: Ready for Work, bug report, Component: ImportExport
