### ISSUE TITLE
CartItemInterface should include customizable_options

### ISSUE THREAD

**Issue by laurentiumagureanu** [magento/magento2#31180] opened 2020-12-04 18:58 UTC
Fix all nullable customizable_options

```java
customizable_options: <SelectedCustomizableOption]
```

to be non nullable 
customizable_options: [SelectedCustomizableOption]!

this will fix the BiC introduced in 2.4.1
will also fix the bundle problem which is the only one that's nullable now
[~cspruiell> plz update this description accordingly 

 !screenshot-1.png|thumbnail! 

1. I need to query a user's cart via `graphQL` and include `customizable_options` for each cart item.
1. In order to do that now I need to use a fragment for each type implementing `CartItemInterface`
1. Problem is that `BundleCartItem` has `customizable*options: [SelectedCustomizableOption]!` ( not nullable ) while all the other cart item types have `customizable*options: [SelectedCustomizableOption]` (nullable)

### Expected result (*)
1. The `customizable_options` field should be part of `CartItemInterface` since all implementing types include it.
1. The `customizable_options` field should at least use the same type declaration in all implementing types in order to be able to fetch it in the `cart` query.

### Actual result (*)
1. The `cart` query validation error
![image](https://user-images.githubusercontent.com/6639076/101203436-52030280-3673-11eb-986f-810b4216a658.png)

**Comment by laurentiumagureanu** [comment] 2020-12-04 18:59
@magento export issue to Jira project MCLOUD as Story

**Comment by dthampy** [comment] 2020-12-04 19:26
@magento export issue to Jira project MC as Bug

**Comment by mauragcyrus** [comment] 2020-12-04 19:38
@magento export issue to Jira project MCLOUD as Bug

**Comment by magento-engcom-team** [comment] 2020-12-04 19:38
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/MCLOUD-7370) is successfully created for this issue.

**Comment by korovitskyi** [comment] 2020-12-09 11:57
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2020-12-11 17:40
Hi @laurentiumagureanu, @shikhamis11, @korovitskyi. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-39690` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by lilbumblebear** [comment] 2021-08-18 15:06
I do not think this issue has been resolved.  Please see 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProductGraphQl/etc/schema.graphqls
Line 65

customizable_options: [SelectedCustomizbleOption] (without !)

This causes the same error initially described when running the query

**Comment by sprankhub** [comment] 2022-01-26 10:45
@sidolov looks like this needs to be re-opened.

**Comment by engcom-Alfa** [comment] 2022-04-06 08:17
Hi @laurentiumagureanu ,
Thanks for your reported bug, the internal team has fixed and delivered this issue successfully.
Please find related commits [HERE](https://github.com/magento/magento2/commit/5c97ea79ab68dbb1ff0a7182f82abaa79374722d).

Kindly upgrade to the latest Magento version `2.4-develop` to retest the case.

In case of any Magento related issues found in `2.4-develop`, you may report a new bug with all the information like Preconditions, detailed steps to reproduce, expected and actual Results along with screenshots/ screen recordings.

For any Magento related references, you may refer to the [Magento user guide](https://docs.magento.com/user-guide/).

Thanks!

**Closed as completed by engcom-Alfa** 2022-04-06 08:17 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P1, Project: GraphQL, Progress: done, Area: APIs
