### ISSUE TITLE
Error when trying to add a new product

### ISSUE THREAD

**Issue by psdevquestions** [magento/magento2#36342] opened 2022-10-20 23:04 UTC
### Preconditions and environment

- Magento version 2.4.3-p1

### Steps to reproduce

Navigate to Catalog > Products

Click on "Add Product" in upper right corner

### Expected result

Expect the new product details page to appear

### Actual result

The following text is displayed on screen within the Magento environment:

SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT `e`.`entity_id` FROM `catalog_product_super_link` AS `l` INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = l.parent_id WHERE (l.product_id IN(?))

### Additional information

I can duplicate existing products, but I am unable to create any type of new product using the Add Product button/dropdown

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-21 09:36
Hi @psdevquestions,

Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.There is no error when clicking on "Add product".Kindly refer screenshots.


<img width="1444" alt="Screenshot 2022-10-21 at 3 03 40 PM" src="https://user-images.githubusercontent.com/51680745/197164651-66931726-b3b6-4fab-a722-413849f804c7.png">




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-02 06:28
Thanks for your contribution @kestraly,

@psdevquestions Kindly go through with @kestraly comment.Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.


Please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-16 06:06
Hi @psdevquestions,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-16 06:06 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3-p1
