### ISSUE TITLE
Fotorama : Vertical slider does not work properly

### ISSUE THREAD

**Issue by Etje** [magento/magento2#37590] opened 2023-06-07 13:00 UTC
### Preconditions and environment

- Magento version: 2.4.6 Enterprise Edition

### Steps to reproduce

1. Install clean Magento 2.4.6
2. Add 6 pictures to a random product
3. Change <var name="navdir">horizontal</var> to <var name="navdir">vertical</var>
4. Flush Magento Cache
5. Navigate to Product Detail Page of the random product (where 6 pictures where added)
6. Try to slide thumbnail by click and drag up and down

### Expected result

Expected result is a perfectly smooth working vertical slider which shows all different images when dragging

### Actual result

Actual result is a very slow vertical slider which maybe moves 10 pixels when you drag it up and down, but certainly not working fully

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-06-08 08:32
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-06-20 10:03
Hi @Etje,

Please provide us latest update on this https://github.com/magento/magento2/issues/37590#issuecomment-1582530299 you are able to reproduce the issue or still working on this issue and let us know if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-04 05:47
Hi @Etje,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-04 05:47 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by al-hiren-kathiriya** [comment] 2024-11-29 05:25
Hello,

I am facing the same issue with the vertical thumbnail slider. Do you have any solution for this?

Thanks
