### ISSUE TITLE
Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "6827" already exists

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#31814] opened 2021-01-23 14:21 UTC
### Preconditions (*)
1. Magento 2.4.1

### Steps to reproduce (*)
1. Imported customer data with Magento tool from Magento 1 to Magento 2
2. Visit customer overview in new install Magento 2

### Expected result (*)
1. No webapi error

### Actual result (*)
1. Critical: Report ID: webapi-600ad6e880167; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "6827" already exists

`Request URI: /index.php/rest/V1/customers/search?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2021-01-01%2009:23:26&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5Bsort_orders%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bsort_orders%5D%5B0%5D%5Bdirection%5D=ASC&searchCriteria%5Bpage_size%5D=101&searchCriteria%5Bcurrent_page%5D=1`

`[2021-01-22 15:18:23] main.CRITICAL: Report ID: webapi-600aecbf05b0d; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "6827" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-600aecbf05b0d; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "6827" already exists. at /var/www/vhosts/domain.com/httpdocs/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "6827" already exists. at /var/www/vhosts/domain.com/httpdocs/vendor/magento/framework/Data/Collection.php:408)"} []`

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2021-01-28 08:10
Hi @jorgb90 thank you for your report. Seems like this issue related to Data Migration Tool 
Could you create issue in appropriate [repo](https://github.com/magento/data-migration-tool/issues) and close this one once it will be done?

**Comment by engcom-Delta** [comment] 2021-02-26 07:27
@jorgb90  we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-Delta** 2021-02-26 07:27 UTC
Labels: Issue: needs update, not-confirmed

**Comment by Timothy-V** [comment] 2021-04-20 08:17
@jorgb90, did you ever find the solution for this problem? I'm experiencing the same thing with an automatic synchronisation program via api. Magento 2.4.1. This seems to be after I upgraded to the latest Magento version and upgraded the sql database.

Stopping Magento to Exact customer synchronizer. An error occured while getting a list of customers. Response: Internal Error. Details are available in Magento log file. Report ID: webapi-607e89615872c Parameters: lastUpdatedAt '2021-04-02 12:53:19'.

[2021-04-20 07:57:21] main.CRITICAL: Report ID: webapi-607e89615872c; Message: Item (Magento\Customer\Model\Customer\Interceptor) with the same ID "5377" already exists. {"exception":"[object] (Exception(code: 0): Report ID: webapi-607e89615872c; Message: Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"5377\" already exists. at /data/web/magento2/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Item (Magento\\Customer\\Model\\Customer\\Interceptor) with the same ID \"5377\" already exists. at /data/web/magento2/vendor/magento/framework/Data/Collection.php:408)"} []

**Comment by lenlorijn** [comment] 2021-05-06 08:06
Has anyone found a solution yet? This error is occurring for us as well after a 2.4.2 upgrade when searching for a customer by email via the API. It is not reproducible locally without customer data.

**Comment by lenlorijn** [comment] 2021-05-06 09:38
For anyone finding this thread/issue. Our issue was duplicate newsletter subscribers, perhaps caused by the data-migration-tool.

**Comment by rangerz** [comment] 2021-05-12 21:06
I found a workaround on [here](https://magento.stackexchange.com/questions/329937/item-magento-customer-model-customer-interceptor-with-the-same-id-6827-alrea)

@lenlorijn 
In `getList` function of  `vendor/magento/module-customer/Model/ResourceModel/CustomerRepository.php`
```
public function getList(SearchCriteriaInterface $searchCriteria)
{
    ...
    $collection->getSelect()->group('e.entity_id'); # Add this line for workaround

    $this->collectionProcessor->process($searchCriteria, $collection);
    ...
}
```

**Comment by Timothy-V** [comment] 2021-05-19 12:35
> For anyone finding this thread/issue. Our issue was duplicate newsletter subscribers, perhaps caused by the data-migration-tool.

Did not use any migration tool, but I found some duplicate email addresses within our newsletters subscribers. It seems the error also shows up when a duplicate email address exists, even though they are splitted by Website. So I deleted every duplicate and the error does not show up anymore!
I wonder what will happen now and how long it takes before another duplicate exists. Otherwise I will try the provided solution by Rangerz.

Anyway, thank you very much for sharing Lenlorijn, helped me a lot for now!

**Comment by jorgb90** [comment] 2021-05-29 21:22
> For anyone finding this thread/issue. Our issue was duplicate newsletter subscribers, perhaps caused by the data-migration-tool.

Sorry I didnt reply earlier, but this was exactly our problem as well. Remove the duplicate subscriptions and its fixed.

**Comment by zhukant** [comment] 2021-08-11 02:39
> For anyone finding this thread/issue. Our issue was duplicate newsletter subscribers, perhaps caused by the data-migration-tool.

Same issue for us and this fix worked for us as well, although we did not use any migration tool, either.

**Comment by yuriichayka** [comment] 2021-09-02 08:19
Looks like here is the fix - https://github.com/magento/magento2/issues/31168
