### ISSUE TITLE
Incorrect item subtotal on partial invoice email

### ISSUE THREAD

**Issue by MarianMates** [magento/magento2#28295] opened 2020-05-20 10:55 UTC
The item subtotal on the email for a partial invoice is incorrect. It displays the value of the entire ordered quantity, not only the invoiced quantity.

### Preconditions (*)
1. Magento version 2.3.3

### Steps to reproduce (*)
1. Add a product to cart
2. Increase quantity (6 for example)
3. Place order
4. Go to admin, open the order and click invoice
5. Update the quantity to half
6. Check Email Copy of Invoice and click Submit

### Expected result (*)
1. The items subtotal should be the total of the invoiced quantity

### Actual result (*)
1. The items subtotal is the total of the ordered quantity, even tough the subtotal in the Totals are is correct
![image](https://user-images.githubusercontent.com/21063382/82438194-541fbe00-9aa1-11ea-9cc0-2181858af3b9.png)

**Comment by yogeshkarodiya** [comment] 2020-05-30 11:22
I am working into this issue.

**Comment by AaronONeill** [comment] 2020-09-24 14:40
We have also just seen this issue on Magento 2.3.5.

**Comment by Pavel-Fekete** [comment] 2020-11-09 14:18
Not reproducible on the latest 2.4-develop
Item subtotal is correct in partial invoice email
![Subtotal](https://user-images.githubusercontent.com/67371013/98552412-1a3cb100-22a7-11eb-986a-fc18300578cb.png)

**Comment by engcom-Bravo** [comment] 2020-11-09 15:01
Hello @MarianMates 

Thank you for your report

The issue is already fixed in the latest 2.4-develop
We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-11-09 15:01 UTC
Labels: Reported on 2.3.3
