### ISSUE TITLE
Downloadable product - download link in order confirmation email

### ISSUE THREAD

**Issue by tanghia** [magento/magento2#3929] opened 2016-03-30 17:00 UTC
## Steps to reproduce
1. Administrator creates a downloadable product 
2. the customer creates new order
3. the system sends order confirmation email
4. Customer opens email and click on download link

Expected result
1. Go to correct link

Actual result
1. Go to admin login page.

![err01](https://cloud.githubusercontent.com/assets/7329746/14150474/5e119116-f6d3-11e5-9ecc-20b58bd7588f.jpg)
![err02](https://cloud.githubusercontent.com/assets/7329746/14150475/5e13c63e-f6d3-11e5-8f3d-8a47c6dd739a.jpg)

I uploaded some products, but this error made me cant run my shop now.

NghiaTT

**Comment by Bravarg** [comment] 2016-04-26 09:44
Yes, I have the same issue with Invoice email. In method getPurchasedLinkUrl() of Downloadable module, Url builder create link for backend instead of frontend urls. The problem is in block **Magento\Downloadable\Block\Sales\Order\Email\Items\Order\Downloadable** for order confirmation email, and **Magento\Downloadable\Block\Sales\Order\Email\Items\Downloadable** for Invoice email. There are _urlBuilder is an object of **Magento\Backend\Model\Url** and it create admin link always. I fixed this using in overrided block __construct() after parent::__construct() **$this->_urlBuilder = \Magento\Framework\Url object.** The overrided _urlBuilder will create frontend links.

**Comment by Mulderua** [comment] 2016-05-17 12:35
Hi @tanghia ,
thank you for reporting this issue. Internal ticket was created MAGETWO-52897.

**Comment by NadiyaS** [comment] 2016-06-08 08:57
Hi @tanghia ,
fix has been delivered to develop branch.
Issue is closed as resolved.

**Closed as completed by NadiyaS** 2016-06-08 08:57 UTC
Labels: Issue: Ready for Work, bug report

**Comment by tanghia** [comment] 2016-06-08 16:50
Thank you :dancer:
