### ISSUE TITLE
Payment Module with redirect to external Payment Page do not redirect

### ISSUE THREAD

**Issue by sjauck** [magento/magento2#8075] opened 2017-01-09 14:04 UTC
I write a payment module to use a Payment provider with external Login and Pay Page. The code set the redirect URL in Redirect Controller. With Xdebug i see the Redirect URL is insert in response correctly but in FrontController suddenly the URL in response is overwritten with the success url.

### Preconditions

1. Magento 2.1.X
2. PHP 7

### Expected result
1. In checkout customer choose Payment Methode. Push "Place order"
2. Redirect to external page
3. Redirect to shop

### Actual result
1. In checkout customer choose Payment Methode. Push "Place order"
2. Redirect to success page (no redirect to external page

**Comment by korostii** [comment] 2017-01-10 13:19
While I agree that such a behavior might seem unexpected, it might largely depend on the source code of your payment module. It might speed up things a bit if you'd share some relevant bits of your code.
If, by a chance, you're adapting a payment module written for Magento 1.9 there would probably be a lot of stuff to get changed.  
If you're just getting around, I'd suggest starting with looking into the code used by existing payment modules such as PayPal. Here's also some relevant info about the redirect URLs in particular:
https://mage2.pro/t/topic/626/2

**Comment by sjauck** [comment] 2017-01-10 13:23
This module is no port from Magento1.
The code work with Magento 2.0.11. 
This is strange.

**Comment by korostii** [comment] 2017-01-10 17:06
Well, I've heard there were extensive changes to the Payments part of Magento introduced in 2.1, but unfortunately I don't have any more info on that, sorry. Hopefully, someone more profound in this aspect will eventually comment on this :)

**Comment by korostii** [comment] 2017-01-10 17:13
Update: I think @joni-jones might be the right person to direct such questions to.

**Comment by sjauck** [comment] 2017-01-11 05:42
Hi. 
Correct they are many changes in checkout but the old way to implemente payments is still deprecated. So it should work.

**Comment by YevSent** [comment] 2017-01-11 12:21
Hi, @sjauck. Some described things are confusing me. As I understand you need to redirect to external payment provider before placing an order, you described a case when you place the order and when tries to redirect to an external payment page, looks a little strange.

But anyway, you can specify the `redirectAfterPlaceOrder` property in your js payment component and it will process redirect. https://github.com/magento/magento2/blob/develop/app/code/Magento/Checkout/view/frontend/web/js/view/payment/default.js#L149

It is not clear what type of integration do you use.
More details about payment integrations in Magento you can find in [this presentation](http://www.slideshare.net/elogic_commerce/payment-integration-patterns-magento2).

Also, you can look [dev docs](http://devdocs.magento.com/guides/v2.1/payments-integrations/bk-payments-integrations.html).

Described case looks like expected, if you will have some issues related to redirect, please, update this ticket and be free to reopen it, now, I'm closing it as not a bug.

**Closed as completed by YevSent** 2017-01-11 12:21 UTC
Labels: Component: Payment, Component: Checkout

**Comment by danielruedaa** [comment] 2017-02-15 19:48
i created module payment with the tool http://cedcommerce.com/magento-2-module-creator/payment-module
When the purchase order is finished the payment module must redirect to the page to process the payment but generates this error 
Fatal error: Call to a member function getMethodInstance() on null in /var/www/html/magento/medishop/vendor/magento/module-payment/Observer/SalesOrderBeforeSaveObserver.php on line 24
