### ISSUE TITLE
Error when opening order as client

### ISSUE THREAD

**Issue by SilvanLaroo** [magento/magento2#2902] opened 2016-01-06 16:16 UTC
Hi,

When I try to open an order as client, I get this error: `Warning: Illegal offset type in isset or empty in /var/www/bhvtotaal/vendor/magento/module-sales/Model/OrderRepository.php on line 62`.

I believe this error occurs because the function expects to receive an int, but the Order itself is passed to the function. A fix would be to retrieve the order id from the order:

``` php
public function get($order)
    {
        $id = $order->getId();

        if (!$id) {
            throw new InputException(__('Id required'));
        }

        if (!isset($this->registry[$id])) {
            /** @var \Magento\Sales\Api\Data\OrderInterface $entity */
            $entity = $this->metadata->getNewInstance()->load($id);
            if (!$entity->getEntityId()) {
                throw new NoSuchEntityException(__('Requested entity doesn\'t exist'));
            }
            $this->registry[$id] = $entity;
        }
        return $this->registry[$id];
    }
```

I'm not sure what the effect would be on other code that uses this function, but this fixes my problem for viewing the order as a client.

**Comment by SilvanLaroo** [comment] 2016-01-06 16:21
I see this function is also used from the backend, in this case the id is passed to the function. Simply using getId() will not do the trick.

**Comment by Mulderua** [comment] 2016-06-15 13:40
Hi @SilvanLaroo, looks like it was fixed on current Magento version.
Could you provide more information about your issue, like Magento version and detail scenario for reproducing this bug?

Thank you!

**Comment by NadiyaS** [comment] 2016-07-12 08:40
The issue is closed since there is no response from reporter more than 2 weeks.
Feel free to reopen the issue if you still have this problem and do not forget to provide Magento version and all details to reproduce it

**Closed as completed by NadiyaS** 2016-07-12 08:40 UTC
Labels: Progress: needs update
