### ISSUE TITLE
Inline edit admin grid record while filter with conditions error.

### ISSUE THREAD

**Issue by taipt-0504** [magento/magento2#32717] opened 2021-04-12 11:46 UTC
### Preconditions (*)

1. Magento 2.3.5 EE, Magento 2.4.1 EE

### Steps to reproduce (*)

1. Go to Customer list screen and filter by some conditions. For example customer by group. Make sure results has only 1 total page.
![1customer](https://user-images.githubusercontent.com/49227466/114393096-d9352980-9bc3-11eb-8c3e-d983b8369795.PNG)
![2filter customer group](https://user-images.githubusercontent.com/49227466/114393111-de927400-9bc3-11eb-85c4-767fe37bd017.PNG)

2. Inline edit last record to results change after save record. For example change customer to other group.
![3 edit last record](https://user-images.githubusercontent.com/49227466/114393144-e5b98200-9bc3-11eb-8fb9-b5b9c8b389a5.PNG)
![4 change group](https://user-images.githubusercontent.com/49227466/114393151-e81bdc00-9bc3-11eb-927b-6fba20d91d3d.png)

3. After click save, data save but js error occurs. Grid screen stuck at infinite spinner.

![5 stuck spinner](https://user-images.githubusercontent.com/49227466/114393172-ec47f980-9bc3-11eb-9e48-fb76e93316ac.PNG)

### Expected result (*)

1. Screen update successfully
2. No js error.

### Actual result (*)

1. Admin grid screen stuck at infinite spinner
![5 stuck spinner](https://user-images.githubusercontent.com/49227466/114392942-a55a0400-9bc3-11eb-9999-eec15a0dfcc5.PNG)

2. Js error occurs
![js errors](https://user-images.githubusercontent.com/49227466/114392953-ab4fe500-9bc3-11eb-8c1b-f2f6a5d8a2ab.PNG)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by taipt-0504** [comment] 2021-04-12 12:26
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-04-12 13:13
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41859` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by taipt-0504** [comment] 2021-05-26 11:05
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2021-10-04 04:20
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2021-11-30 06:13
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2021-12-21 06:14
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2021-12-21 06:46
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2021-12-21 07:39
@magento give me 2.4-develop instance

**Comment by taipt-0504** [comment] 2022-01-13 09:37
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-19 04:35
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-07-19 04:59
Hi @taipt-0504,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.


https://github.com/user-attachments/assets/5fcb7d6f-2fa1-436c-8be2-9646338f3df0



Customer was saved successfully and there were JS errors.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-19 04:59 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Priority: P3, Progress: done
