### ISSUE TITLE
Google Shopping ads Error

### ISSUE THREAD

**Issue by elfeffe** [magento/magento2#25506] opened 2019-11-07 11:19 UTC
### Preconditions (*)

1. Magento 2.3.3, Chrome (Version 78.0.3904.97 (Official Build) (64-bit))
2. I already got the API for Google Shopping ads, I had the same white page with the API and without.

### Steps to reproduce (*)

1. Access Google Shopping ads from Marketing tab

### Expected result (*)

1. "Welcome to Google Shopping ads Channel in Magento" popup appears. Behavior is not depends from browser

### Actual result (*)

1. I have a white screen of death. This one https://gyazo.com/0bbf57e074580d3407b3355defdbe90b
2. I also have several errors in my console https://gyazo.com/12be8ca6dac50c7a85e704a5711aec4f
3. See screenshot.
![Screenshot from 2019-11-12 19-38-15](https://user-images.githubusercontent.com/51681435/68761839-9f05d800-061d-11ea-9cdb-a6ff427c6e25.png)
4 Everything works fine in Firefox. (version 70.0.1 (64-bit))
![Screenshot from 2019-11-13 13-59-50](https://user-images.githubusercontent.com/51681435/68762090-23585b00-061e-11ea-9729-04d05c71d258.png)
Can't be reproduced in Vanilla Magento because it doesn't include Google Shopping ads

**Comment by elfeffe** [comment] 2019-11-07 11:22
@magento give me 2.3-develop instance - upcoming 2.3.x release

**Comment by magento-engcom-team** [comment] 2019-11-07 11:22
Hi @elfeffe. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-07 11:22
Hi @elfeffe, here is your [Magento instance](https://i-25506-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25506-2-3-develop.instances.magento-community.engineering/admin](https://i-25506-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by elfeffe** [comment] 2019-11-07 11:27
Magento Vanilla doesn't include Google Shopping ads

**Comment by sea129** [comment] 2019-11-07 23:27
#25482 And it is not pop up blocker. The issue is loader.js uses for ... in iterator on array which is wrapped by prototypejs.

**Comment by magento-engcom-team** [comment] 2019-11-11 12:12
@elfeffe Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-11 12:13
@elfeffe Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-11-13 12:13
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23087` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Vogel335** [comment] 2019-11-13 14:25
Hello
here is screenshot of my broswer debugg console when opening Google Shopping Ads
![Bildschirmfoto 2019-11-13 um 15 23 47](https://user-images.githubusercontent.com/57420558/68772277-d24e6400-0629-11ea-8543-8312becd32c4.png)

**Comment by elfeffe** [comment] 2019-11-13 14:28
@engcom-Echo You added a point 4 saying it works in Firefox, but it doesn't.
It just ask for the API key, but after you add it, you get the same blank screen as in Chrome
So, it doesn't work on FF, it just let you reach one more step, add the API key

**Comment by ioweb-gr** [comment] 2019-12-15 20:55
I can confirm that I'm having the same behaviour on firefox as @elfeffe mentions. You get to do one more step but hten blank screen as in chrome.

**Comment by Rawpro1** [comment] 2019-12-29 09:48
I can confirm that I'm having the same behaviour on firefox as @elfeffe mentions. You get to do one more step but hten blank screen as in chrome.
Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Work+Sans:400,700.less' because it violates the following Content Security Policy directive: "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' channels.magento.com assets.adobedtm.com cdn.wootric.com d8myem934l1zi.cloudfront.net wootric-eligibility.herokuapp.com amcglobal.sc.omtrdc.net stg-channels.magedevteam.com dpm.demdex.net react-google-channel-qa.s3-website.us-east-2.amazonaws.com google-dev-bucket.s3.amazonaws.com http://react-google-channel.s3-website.us-east-2.amazonaws.com eligibility.wootric.com s3.amazonaws.com/extension-release-notes/ amc.demdex.net cm.everesttech.net production.wootric.com http://react-google-channel-qa.s3-website.us-east-2.amazonaws.com". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

jquery-migrate.js:23 JQMIGRATE: Migrate is installed with logging active, version 1.4.1
(index):1 Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Work+Sans:400,700.less' because it violates the following Content Security Policy directive: "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' channels.magento.com assets.adobedtm.com cdn.wootric.com d8myem934l1zi.cloudfront.net wootric-eligibility.herokuapp.com amcglobal.sc.omtrdc.net stg-channels.magedevteam.com dpm.demdex.net react-google-channel-qa.s3-website.us-east-2.amazonaws.com google-dev-bucket.s3.amazonaws.com http://react-google-channel.s3-website.us-east-2.amazonaws.com eligibility.wootric.com s3.amazonaws.com/extension-release-notes/ amc.demdex.net cm.everesttech.net production.wootric.com http://react-google-channel-qa.s3-website.us-east-2.amazonaws.com". Note that 'style-src-elem' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by rmanor1** [comment] 2020-10-06 15:35
Hello, this should probably be closed as we've deprecated the Google Shopping ads Channel, and the [service was shut down ](https://docs.magento.com/user-guide/sales-channels/google-eol.html)as of Apr 28th.

**Closed as completed** 2020-10-06 15:38 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundled Extension, Component: Google Shopping ads, Progress: done
