### ISSUE TITLE
Sort by Price (Ascending) on Products doesn't work in 2.4.1 and 2.4.2

### ISSUE THREAD

**Issue by intheshallow** [magento/magento2#32571] opened 2021-03-22 18:15 UTC
### Preconditions (*)

1. 2.4.1
2. 2.4.2

### Steps to reproduce (*)

1. Create a Category
2. Create 13+ products with varying prices. Create one or two with $0.
3. Click on the category and choose Price (ascending) within the Sort By dropdown.

### Expected result (*)

1. $0 should be shown first or even last is fine with me. Last would honestly be best.

### Actual result (*)

1. http://55c08fbd8a.nxcli.net/test.html
2. Go there and you will see that both items marked as $0 are on the first page, but at the end. If anything, they should be the very first on the first page, or on page 2 at the very end. The latter is ideal in my case.
3. Descending seems to work just fine though.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-03-23 04:41
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2021-03-23 05:04
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41496` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by intheshallow** [comment] 2021-03-24 15:06
Hello,

I am checking up on this for any information.

Thank you.

**Comment by Rakhi161** [comment] 2021-03-27 16:43
@magento I am working on this

**Comment by Rakhi161** [comment] 2021-03-27 16:43
@magento add to contributors team

**Comment by Rakhi161** [comment] 2021-03-27 16:44
@magento I am working on this

**Comment by intheshallow** [comment] 2021-05-05 21:57
Hello,

Is there any update on this? I am just checking in.

**Comment by ia-gaurav** [comment] 2021-05-17 18:06
any update please

**Comment by kamil-bogdziewicz-orba** [comment] 2021-07-23 15:03
any update please

**Comment by intheshallow** [comment] 2021-07-23 15:14
I doubt they ever will update this. I have another bug posted on here about In Stock not sorting at all which is also not getting any updates at all. This is pathetic.

**Comment by kamil-bogdziewicz-orba** [comment] 2021-07-28 15:33
I think I solve my problem. Maybe it help you. Check your configurable products price value. I had these prices set and the value was not same as cheapest simple product inside. When configurable product have some price set it will be taken to indexer process and this value will be processed to get minimal_price. To get minimal_price value original price is modified by cart rules, price options, price tier, price for groups etc and then you have not really proper price in index. If you set 0$ value for configurable products then the indexer process will take cheapest simple product. After all we have proper minimal_price and sort by price is using it. Now sorting by price is working for me. [M2.4.2-p1]

**Comment by intheshallow** [comment] 2021-07-28 15:35
Kamil,

All of the products I set on the live site and the staging that I sent them were all simple products. Not configurable.

**Comment by yogesh-valiya** [comment] 2022-12-16 06:16
@magento give me 2.4-develop instance

**Comment by yogesh-valiya** [comment] 2022-12-16 06:32
![image](https://user-images.githubusercontent.com/66505755/208036767-20bf86b4-8c52-49af-8782-221d3d5536b3.png)

Seems like issue ins't reproducible on 2.4-develop. Thanks.

**Comment by engcom-Bravo** [comment] 2024-06-11 07:19
Hi @intheshallow,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.

As per this https://github.com/magento/magento2/issues/32571#issuecomment-1354283905.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-06-11 07:19 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Area: Catalog
