### ISSUE TITLE
RestAPI add order comment without providing status sets status to NULL, preventing from showing in order grid

### ISSUE THREAD

**Issue by edward-simpson** [magento/magento2#34180] opened 2021-09-28 12:53 UTC
### Preconditions (*)

1. Magento 2.3.x, 2.4.x
2. Existing order to add comments to

### Steps to reproduce (*)

1. Using the orders/{id}/comments endpoint, POST a new comment, but exclude "status" field (as is not required)
2. Check the order in the sales_order, sales_order_grid database tables
3. Check the order in the admin > Sales > order grid and Front-end -Customer login > My Orders page

### Expected result (*)

1. Order should maintain existing status
2. Order should appear in adminhtml order grid and Front-end - My Orders page

### Actual result (*)

1. Order gets status set to NULL
2. Order no longer appears in adminhtml order grid
3. Order no longer appears in front-end - My Orders page
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by edward-simpson** [comment] 2021-09-28 12:57
Occurs because [`\Magento\Sales\Model\Order::addStatusHistory`](https://github.com/magento/magento2/blob/192b28038dac2e993c65b49fb8b5af10cb520945/app/code/Magento/Sales/Model/Order.php#L1740) used in API call does not check if provided $history param has status set before using it:

$this->setStatus($history->getStatus());

I would create a PR to fix this but a decision needs to be made whether to either: 

- Make the rest API endpoint's "status" parameter required
- Modify the addStatusHistory method to check for status before setting
- Potentially use `addStatusHistoryComment` instead?  Although I guess this would remove the option to add a status/other history

**Comment by engcom-November** [comment] 2021-09-29 11:47
Verified the issue on Magento 2.4-develop branch and the issue is reproducible:

**Steps performed:**
Created Order from front-end for a logged in customer using check/money Order. Order status is "Pending"
Sent POST request to generate admin access token using: /rest/default/V1/integration/admin/token
Sent POST request to /rest/V1/orders/15/comments to update comments for existing order using below sample payload:
`
{
  "statusHistory": {
    "comment": "my api comment",
    "created_at": "2021-09-29 12:45:40",
    "entity_id": 15,
    "is_visible_on_front": 1
  }
}
`
**Issue:** Order status is becoming NULL in "sales_order" table and "sales_order_grid" table
Order is not getting displayed on Front-end - My Orders page
Admin - View Order - Comment is also not added.
![image](https://user-images.githubusercontent.com/60198231/135262259-74a4f846-34bb-4f32-b909-ae85340717e1.png)

![image](https://user-images.githubusercontent.com/60198231/135262200-f86cdd2a-5ca7-48dd-8c72-12e161cadd85.png)

**Comment by bireney** [comment] 2022-01-18 07:14
Assign to me

**Comment by sivaganeshsg** [comment] 2022-09-22 18:33
> Assign to me

This is still pending @bireney

**Comment by koushikch7** [comment] 2023-01-17 15:43
Assign to me

**Comment by yogesh-valiya** [comment] 2023-03-16 14:26
@magento I'm working on this

**Comment by glo05363** [comment] 2023-03-20 09:43
@yogesh-valiya @koushikch7 This issue has been taken care by internal team. No need to work on this.

**Comment by yogesh-valiya** [comment] 2023-03-20 13:42
@glo05363 

I'm just repeating myself as this comment on :disappointed:  - https://github.com/magento/magento2/issues/36800#issuecomment-1475712021

When I started working on this issue, the issue wasn't assigned to anyone. If the internal team was addressing the issue, may I inquire as to why it had not been assigned to someone specifically?

It's frequent, where an individual is working on a particular issue and raises a pull request, only to find out that there is already a pull request from the internal team in progress.

In light of this, I question the value of the effort put forth to resolve the issue. Could you clarify why the pull request is not linked to the issue if it is already in progress?

**Comment by glo05363** [comment] 2023-03-24 07:13
> @glo05363
> 
> I'm just repeating myself as this comment on 😞 - [#36800 (comment)](https://github.com/magento/magento2/issues/36800#issuecomment-1475712021)
> 
> When I started working on this issue, the issue wasn't assigned to anyone. If the internal team was addressing the issue, may I inquire as to why it had not been assigned to someone specifically?
> 
> It's frequent, where an individual is working on a particular issue and raises a pull request, only to find out that there is already a pull request from the internal team in progress.
> 
> In light of this, I question the value of the effort put forth to resolve the issue. Could you clarify why the pull request is not linked to the issue if it is already in progress?

I see your concern yogesh, Internal Team make sure to change status as per need, In this issue You will find above  changes as **PR:created by JIra-Sync_bot** before you have tried to assign the same to yourself.
Irrespective of that we will make sure to be more clear in terms of adding comment.
As i can see the changes proposed in PR will not suffice , we will take care of the same in internal JIRA.
We highly appreciate all the efforts in community, Internal PRs will not be linked here, once it is merged it will be available.

**Closed as completed** 2023-04-18 14:03 UTC
Labels: Issue: Confirmed, Component: Api, Reproduced on 2.4.x, Priority: P2, Priority: P1, Progress: done, Component: order status, Component: Order grid, Reported on 2.4.x, Area: APIs, Area: Order

**Comment by engcom-Hotel** [comment] 2023-04-18 14:21
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-1342 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-1342&type=commits

Thanks
