### ISSUE TITLE
Magento2: Issue in pagination

### ISSUE THREAD

**Issue by vipin-eglobeits** [magento/magento2#3861] opened 2016-03-22 11:28 UTC
I found an issue when we adding different pagination for list and grid view.
On that time the grid view pagination will not work.
Anybody please help me to solve this issue?

**Comment by mazhalai** [comment] 2016-03-22 13:17
Please give us some steps to reproduce.

**Comment by vipin-eglobeits** [comment] 2016-03-22 13:29
Thank you for your quick response.
The issue appears when we:
Take back end Stores->Configuration->Catalog->Catalog->Storefront 
'Products per Page on Grid Default Value' is reflecting properly in grid view.
But 'Products per Page on List Default Value' is not setting the pagination to that value.

**Comment by piotrekkaminski** [comment] 2016-06-10 23:53
reproduced, internal issue MAGETWO-54242

**Comment by piotrekkaminski** [comment] 2016-06-13 21:45
Issue is fixed internally and should be included in 2.1

**Closed as completed by piotrekkaminski** 2016-06-13 21:45 UTC
Labels: Issue: Ready for Work, bug report

**Comment by bluethink164** [comment] 2017-06-28 06:38
I have the same issue pagination not showing in the product list. Due to uncomment in list2.phtml in theme but when I uncomment it shows this


![screenshot from 2017-06-28 12-08-09](https://user-images.githubusercontent.com/29700825/27623630-e95f02fc-5bfa-11e7-8612-4a23300e28f1.png)
![screenshot from 2017-06-28 12-07-26](https://user-images.githubusercontent.com/29700825/27623636-f4d34c24-5bfa-11e7-80f9-78a396dcc677.png)
