### ISSUE TITLE
$quote->setCartFixedRules(*) is not cleared before calculating the rule

### ISSUE THREAD

**Issue by speedupmate** [magento/magento2#31496] opened 2020-12-31 10:32 UTC
### Preconditions (*)

1. Magento 2.4.* 

https://github.com/magento/magento2/blob/960a51f7afa371e444842b953f0b5493d2255b13/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php#L185

where:

$quote->setCartFixedRules($cartRules); 

is not always cleared before new calculation (all other values are cleared in validator process method) and  leaves merchant in a situation when this calculation is called multiple times from diff parts of code it will not apply the discount on calls where this data is already set . Totals will look like code is applied but discount is not calculated , coupon is set to quote and discount is 0 

NB: temp workaround is to 

$quote->setCartFixedRules();

before calling totals calculation from your code and passing a quote object for totals calculation
        
### Steps to reproduce (*)

1. Create a fixed cart rule with a coupon code 
2. Apply the code in checkout 
3. Have any extension in system that calls totals collector multiple times (between quote saves). 
4. Discount is removed 

### Expected result (*)

1. Create a fixed cart rule with a coupon code 
2. Apply the code in checkout 
3. Have any extension in system that calls totals collector multiple times (between quote saves). 
4. Discount is applied every time totals are collected

### Actual result (*)

1. Create a fixed cart rule with a coupon code 
2. Apply the code in checkout 
3. Have any extension in system that calls totals collector multiple times (between quote saves). 
4. Discount is removed 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [* ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment] 2021-04-18 20:14
Posting a comment. Issues should not be automatically closed.

**Comment by stoutik** [comment] 2021-05-05 14:42
I have the same problem.

**Comment by olgaimproove** [comment] 2021-05-11 11:53
Magento 2.4.* having the same issue

**Comment by SvanteAvenla** [comment] 2021-05-11 12:12
I have the same problem. Magento 2.4.2.

**Comment by engcom-Lima** [comment] 2021-06-14 11:37
@speedupmate I am working on your issue. I have created a fixed cart rule with a coupon code and apply the coupon code in cart page. Discount is showing as expected. As far as issue can't reproduce. 

So, Can you please provide me the complete reproducible steps with screenshots? so it will be helpful in reproduce the issue.
And also tell me the example of extensions which you are using or clear the 3rd point.

**Comment by speedupmate** [comment] 2021-06-14 11:41
@engcom-Lima Write a test that calls collectTotals multiple times in a row on quote object and you can replicate this. Otherwise you can let it go stale or close. I know how to fix but unfortunately  have no time for painting it red or provide samples. Will avoid making such reports also as I can understand its hard to replicate for you just based on description.

**Comment by engcom-Lima** [comment] 2021-06-17 09:36
Hi @speedupmate,

Sorry, We need the reproducible steps to reproduce the issue. Whenever you get time then open or raise the new ticket with reproducible steps and screenshots.

Hence we are closing this ticket. Thanks for the understanding!

**Closed as completed by engcom-Lima** 2021-06-17 09:36 UTC
Labels: Triage: Dev.Experience, Issue: needs update
