### ISSUE TITLE
upgarded to Magento 2.4 unable to Upgrade issue:  1452 Cannot add or update a child row: a foreign key constraint fails (`kingdomdb_22dec20`.`#sql-4a2_9`, CONSTRAINT `QUOTE_STORE_ID_STORE_STORE_ID` FOREIGN KEY (`store_id`) REFERENCES `store` (`store_id`) ON DELETE CASCADE), query was

### ISSUE THREAD

**Issue by niksjethva** [magento/magento2#31414] opened 2020-12-23 07:12 UTC
### Preconditions (*)

1. Upgrading from Enterprise edition version 2.2.3 into Version 2.4.0 in local server
2. The bug is during  (php bin/magento setup:upgrade) throwing the error (see below)
3. Installed PHP version 7.3 
4. Installed Elastic search version 7.1

### Steps to reproduce (*)

1.  Upgrade from enterprise edition 2.2.3 to 2.4.0 (**upgrade has been successfully done from 2.2.3 to 2.4.0**)
2.  unable to php bin/magento setup:upgrade
3. The setup:upgrade would fail.
4. while I am trying to upgrade command and foreign key constraint goes off from the table and throwing error.

### Expected result (*)

1. Upgrade Should work Successful
2. Values in the database should be UPDATED not re-INSERTED with the insertOnDuplicate function, which is causing the error Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails

### Actual result (*)

1. setup:Upgrade Fail with the following error:
![image](https://user-images.githubusercontent.com/50106354/102969212-5193b400-451b-11eb-8692-ab6128df702b.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by dverkade** [comment] 2021-03-17 15:34
Ready for confirmation issues can't be closed automatically.

**Comment by engcom-Golf** [comment] 2021-06-07 11:48
@niksjethva I tried to reproduce this issue, but can't reproduce. It is working as expected. I can successfully run the **setup:upgrade** command. So considering this, I am closing this Issue.

**Closed as completed** 2021-06-07 11:48 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: ready for confirmation
