### ISSUE TITLE
 Cron script readiness check failed. Hide detail - Error from Updater Application Cron Script

### ISSUE THREAD

**Issue by GlobalOutsourcing** [magento/magento2#6405] opened 2016-08-30 21:55 UTC
Centos System 7
PHP 5.6.21
Magento 2.1
### Steps to reproduce
1. Navigate to System -> Tools -> Setup Wizard
2. Select System Upgrade
3. Start Readiness check
### Expected result
1. Readiness check completes successfully and can move to next step for upgrade
### Actual result
1. Error displays:

Error! You need to resolve these issues to continue.

Check Cron Scripts

Cron script readiness check failed. Hide detail

Error from Updater Application Cron Script:

Found non-writable path(s):
/var/www/mywebsite.com/public_html/pub/media/.htaccess
/var/www/mywebsite/public_html/pub/static/.htaccess

For additional assistance, see cron scripts help.

![2016-08-30_224644](https://cloud.githubusercontent.com/assets/17181901/18108557/ada4891e-6f04-11e6-859d-082f00004f20.png)

Have already triple checked that the paths are writeable, no console errors etc. This is in development mode on Magneto 2.1.

Thanks in advance for your suggestion and help!

**Comment by bondimedical3** [comment] 2016-08-31 08:28
I have the same problem in my update.log file

**Comment by shiftedreality** [comment] 2016-09-07 07:32
Hi @GlobalOutsourcing 

Please check whether user that running cron jobs have permissions to write.
Could you try using `sudo crontab -e` to check with root user?

**Comment by andimov** [comment] 2016-09-27 09:41
@GlobalOutsourcing 
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines).

**Closed as completed by andimov** 2016-09-27 09:41 UTC
Labels: bug report, Progress: needs update, Component: Setup, Issue: Format is not valid

**Comment by strom-man** [comment] 2017-09-22 08:34
i have  this problem sovle
