### ISSUE TITLE
Graphql request placeOrder does not send order confirmation email

### ISSUE THREAD

**Issue by leroynas** [magento/magento2#28224] opened 2020-05-14 13:30 UTC
As the order is placed using the magento 2 grahql interface, the expected result is that a email with the order confirmation is send to the guest email submitted to the cart.

### Preconditions (*)

1. Magento 2.3.4(release)

### Steps to reproduce (*)

1. Call graphql create cart mutation
2. Call graphql add item to cart mutation
3. Call graphql add cart guest email on cart mutation
4. Call graphql add shipping address on cart mutation
5. Call graphql add billing address on cart mutation
6. Call graphql add shipping method on cart mutation
7. Call graphql add payment method on cart mutation
8. Call graphql place order mutation

### Expected result (*)

1. Order confirmation is send to the guest email submitted on step 3

### Actual result (*)

1. No order confirmation is send

**Comment by leroynas** [comment] 2020-05-14 13:34
I confirm this issue is present on a clean magento 2.3.4 installation.

**Comment by leroynas** [comment] 2020-05-17 10:27
I also confirm this issue is present on Magento 2.4.0-p1

**Comment by shamrox** [comment] 2020-05-20 15:16
Where are we with this issue. We are experiencing the same issue with AEM cif (react) and Magento 2?

**Comment by leroynas** [comment] 2020-05-22 10:36
@shikhamis11 Thank you for taking on this issue! Can you give me any indication when this issue will be worked on and be ready for release? We are working on a PWA and really need this feature. We want to be compatible with a clean magneto 2 installation so this is really important for us.

**Comment by leroynas** [comment] 2020-05-27 07:00
The same goes for logged in customers via graphql. On submitting the placeOrder method there is no confirmation email send to the customer email.

**Comment by Hexmage** [comment] 2020-05-28 12:05
duplicate of https://github.com/magento/magento2/issues/28124

**Closed as completed** 2020-05-28 19:44 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
