### ISSUE TITLE
[GraphQL] Adding a bundle product with multiple selection options via addProductsToCart doesn't work as expected

### ISSUE THREAD

**Issue by laurentiumagureanu** [magento/magento2#33123] opened 2021-06-02 10:47 UTC
### Preconditions (*)

1.  Magento version 2.4.2
2. Configure a bundle product to have multiple selection options

### Steps to reproduce (*)

1. use the addProductsToCart mutation
2. Try to add the bundle product to cart with at least 2 selections for checkbox or multiple selection options
3. Check the cart and see if the multi-selection option has all the sent selections 
4. I use this mutation: 
```graphql
{
    "operationName": "addProductToCart",
    "variables": {
        "cartId": "B6S7atkjsvbtcG4xmOt4QqbMAq1LBZwR",
        "cartItems": [
            {
                "sku": "24-WG080",
                "quantity": 1,
                "selected_options": [
                    "YnVuZGxlLzEvMS8x",
                    "YnVuZGxlLzIvNC8x",
                    "YnVuZGxlLzMvNS8x",
                    "YnVuZGxlLzMvNy8x",
                    "YnVuZGxlLzQvOC8x"
                ]
            }
        ]
    },
    "query": "mutation addProductToCart($cartId:String!$cartItems:[CartItemInput!]!){addProductsToCart(cartId:$cartId cartItems:$cartItems){cart{id __typename}__typename}}"
}
```
5. the 3rd and 4th entry from `selected_options` refer to the same `bundle_option_id` but use different `bundle_option_selection_id` because it is multiple selection: `bundle/3/5/1` and `bundle/3/7/1`

### Expected result (*)

1. All the selections from a multi-selection field should be present in the cart

### Actual result (*)

1.  only the last selection is added to cart with the bundle

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by heerdt** [comment] 2021-06-02 20:30
Duplicated: https://github.com/magento/magento2/issues/32590

**Comment by heerdt** [comment] 2021-06-02 20:32
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by engcom-Bravo** [comment] 2021-08-23 08:48
Verified issue on Magento 2.4.2 and issue is reproducible.
Below are steps to reproduce:

All steps should use GraphQL

1. Create a new empty cart
2. Add product + required options + same option multiple checkbox items to the cart using 'addProductsToCart' mutation
```
mutation {
  addProductsToCart(
    cartId: "yRL4q5jYZorZbmUOYiMroXcVjXl8csg7",
    cartItems: [
        {
            quantity: 1,
            sku: "bgearpro",
            selected_options: [
               "YnVuZGxlLzUvOS8x",
              "YnVuZGxlLzUvMTEvMQ==",
              "YnVuZGxlLzUvMTAvMQ==",
              "YnVuZGxlLzYvMTMvMQ==",
            ]
        }
    ]

  ) {
    cart {
      items {
        id
        product {
          name
          sku
        }
        quantity
        
            ... on BundleCartItem {
                bundle_options {
                    id
                    label
                    type
                    values {
                        id
                        label
                        price
                        quantity
                    }
                }
            }
      }
    }
  }
}
```
Product is added to the cart, the options are added but only one of the checkbox items is added to the cart item.
Below is cart response
```
{
  "data": {
    "addProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "5",
            "product": {
              "name": "bgearpro",
              "sku": "bgearpro"
            },
            "quantity": 3,
            "bundle_options": [
              {
                "id": 5,
                "label": "bgear-bundle",
                "type": "checkbox",
                "values": [
                  {
                    "id": 10,
                    "label": "Go-Get'r Pushup Grips",
                    "price": 19,
                    "quantity": 1
                  }
                ]
              },
              {
                "id": 6,
                "label": "drop",
                "type": "select",
                "values": [
                  {
                    "id": 14,
                    "label": "Overnight Duffle",
                    "price": 45,
                    "quantity": 1
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}
```

**Comment by engcom-Lima** [comment] 2021-09-09 09:53
Closing as there has been no update from the reporter on the same.

**Comment by cpartica** [comment] 2021-09-22 15:17
re-opening this issue as this is a known use case for AEM

**Comment by engcom-Hotel** [comment] 2021-12-20 06:50
Hello @laurentiumagureanu @cpartica,

We have tried to reproduce the issue in Magento 2.4-develop branch but still, we are not able to reproduce it. Please find the below video for reference:

https://user-images.githubusercontent.com/51681618/146723990-c0332a4c-4da4-4bd9-86b3-41042c7582fb.mp4

Hence we are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2021-12-20 06:50 UTC
Labels: Component: GraphQL, Priority: P1, Progress: done, Area: APIs
