### ISSUE TITLE
While installing sample data on magento 2.4.6 on mac os with php version 8.1, Getting error

### ISSUE THREAD

**Issue by kushaljindal92** [magento/magento2#37549] opened 2023-05-26 21:40 UTC
### Preconditions and environment

- Magento version -- 2.4.6
- php version -- 8.1
- os mac
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Try install Magento 2.4.6 sample data using Magento 2 commands on PHP version 8.1
Error code : In PluginManager.php(277) : eval()'d code line 188:

### Expected result

Installation is successfull 

### Actual result

installation got break due to chmod and eval error.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-30 13:28
HI @kushaljindal92,

Thank you for reporting and collaboration.


Verified the issue while installing sample data on Magento 2.4.6 instance we are not able to reproduce the issue.Kindly refer the screenshots.

Sample data installed successfully.


<img width="1502" alt="Screenshot 2023-05-30 at 12 02 41 PM" src="https://github.com/magento/magento2/assets/51680745/b508fca5-86a1-4f04-8c53-ff850bce2394">



<img width="1488" alt="Screenshot 2023-05-30 at 12 03 20 PM" src="https://github.com/magento/magento2/assets/51680745/624c90b1-9701-421d-bb8e-71be8f6a1a35">



Please refer this document https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/next-steps/sample-data/composer-packages.html to install sample data.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-13 06:11
Hi @kushaljindal92,

Kindly provide update this https://github.com/magento/magento2/issues/37549#issuecomment-1568437788 are you still facing the issue.if you are able to reproduce the issue provide us steps to reproduce.Please let us know if you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-26 06:08
Hi @kushaljindal92,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-26 06:08 UTC
Labels: Issue: needs update, Reported on 2.4.6
