### ISSUE TITLE
Catalog Search index process error during indexation process

### ISSUE THREAD

**Issue by LukaszZabielskiMonogo** [magento/magento2#38869] opened 2024-06-25 07:21 UTC
### Preconditions and environment

- Magento 2.4.6-p5 Open Source
- PHP 8.2

### Steps to reproduce

1. Create Bundle product with simple product option. Simple product option with numeric SKU for example: 10007.
2. Try Reindex - Catalog Search Index via console.

### Expected result

Catalog Search index has been rebuilt successfully

### Actual result

Catalog Search index process error during indexation process:
Magento\InventorySales\Model\IsProductSalableCondition\IsProductSalableConditionChain::execute(): Argument #1 ($sku) must be of type string, int given, called in /code/vendor/magento/module-inventory-sales/Model/AreProductsSalable.php on line 48

### Additional information

Patch to resolve problem.

$isSalable = $this->isProductSalable->execute($sku, $stockId);
$isSalable = $this->isProductSalable->execute(**(string)**$sku, $stockId);

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by SerhiiMandrykin** [comment] 2024-06-25 10:38
@magento give me 2.4.7 instance

**Comment by engcom-Bravo** [comment] 2024-06-26 03:50
Hi @LukaszZabielskiMonogo,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**
Create Bundle product with simple product option. Simple product option with numeric SKU for example: 10007.
Try Reindex - Catalog Search Index via console.

**Comment by engcom-Bravo** [comment] 2024-06-26 04:00
Hi @LukaszZabielskiMonogo,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Create Bundle product with simple product option. Simple product option with numeric SKU for example: 10007.
- Try Reindex - Catalog Search Index via console.


<img width="1423" alt="Screenshot 2024-06-26 at 09 18 43" src="https://github.com/magento/magento2/assets/51680745/40114e45-6762-4d66-b8f3-c954246040db">



<img width="1423" alt="Screenshot 2024-06-26 at 09 19 01" src="https://github.com/magento/magento2/assets/51680745/f1f3733f-ed82-46ad-8a21-659167dc0e99">


Catalog Search index has been rebuilt successfully

It might be possible the issue has been fixed in Latest branch and please check any third party modules causing the issue.

Thanks.

**Closed as completed** 2024-06-26 09:06 UTC
Labels: Issue: needs update, Reported on 2.4.6-p5

**Comment by LukaszZabielskiMonogo** [comment] 2024-06-26 09:09
Thanks for checking, the issue is not reproducible on Magento 2.4.7. I closed the issue.
