### ISSUE TITLE
Invalid check after saving product, for updating price / specialPrice attributes

### ISSUE THREAD

**Issue by bampisSyk** [magento/magento2#32892] opened 2021-04-28 10:33 UTC
### Preconditions (*)

1. v2.3.6-p1
2. Update product specialPrice per website using product repository

### Steps to reproduce (*)

1. Set the price scope to "Website"
2. Load a product entity using ProductRepository
3. Update price and specialPrice with different values per storeView
4. Save each product entity using product repository

### Expected result (*)

1. Product has different price / specialPrice per storeView

### Actual result (*)

1. Product has the default views ( storeId 0 ) specialPrice to all storeViews

### Description

I've found a strange issue when trying to update specialPrices per website for products.

Bellow a sample code to update the product price / specialPrice for a specific storeView

```
$productInStore = $this->productRepository->getById($productId, true, $storeId);

$productInStore->setPrice($storePrice);
$productInStore->setSpecialPrice($storeDiscount);

$this->productRepository->save($childInStore);
```

I've searched through the Core and found that after the ProductModel is saved, though the event dispatched , the following class is beeing called

**Magento\Catalog\Model\Product\Attribute\Backend\Price**

there is a strange piece of code in the **afterSave** method, indicating that the attribute (price / specialPrice) value has to be **null**
if the value passed is null or > 0 ( which is weird ), if the attribute is set to Website scope

```
    public function afterSave($object)
    {
        /** @var $attribute \Magento\Catalog\Model\ResourceModel\Eav\Attribute */
        $attribute = $this->getAttribute();
        $attributeCode = $attribute->getAttributeCode();
        $value = $object->getData($attributeCode);
        // $value may be passed as null to unset the attribute
        if ($value === null || (float)$value > 0) {
            **if ($attribute->isScopeWebsite() && $object->getStoreId() != \Magento\Store\Model\Store::DEFAULT_STORE_ID) {**
                if ($this->isUseDefault($object)) {
                    $value = null;
                }
                foreach ((array)$object->getWebsiteStoreIds() as $storeId) {
                    $object->addAttributeUpdate($attributeCode, $value, $storeId);
                }
            }
        }

        return $this;
    } 
```
As a result, whenever trying to set a specialPrice greater than zero, it gets nulled, and removed from the database table **catalog_product_entity_decimal**, so the product resets the specialPrice to the one the master storeId has ( storeId 0 )

The walkaround is to update prices using the **\Magento\Catalog\Model\Product\Action->updateAttributes()**, but even when do so, the next time a product is beeing saved using the repository, the data are once again mutated

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ 1 ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bampisSyk** [comment] 2021-05-07 13:56
Some more info about the issue.

The logic gets in the following snippet ( **Magento\Catalog\Model\Product\Attribute\Backend\Price -> afterSave()** )

`if ($this->isUseDefault($object)) {
                    $value = null;
                }`

The system checks if the value is overriden / get the default value passing null.
While digging some more , i've found that the **containsValue** function in **Magento\Catalog\Model\Attribute\ScopeOverriddenValue** returns false due to the fact that **$this->attributesValues** does not contain the attribute_code **special_price** ( talking about configurable products, with different prices per website ).

Hope that the information above, help a bit in order to clarify the issue

**Comment by engcom-Lima** [comment] 2021-06-03 12:46
Hi @bampisSyk ,

Unfortunately, Can't reproduce the issue.

I configured price/special price different for each website, It is working as expected. Please find the screenshots, both the screenshots are from different website.
<img width="975" alt="Screenshot 2021-06-03 at 6 13 54 PM" src="https://user-images.githubusercontent.com/60198022/120646798-81b28c00-c497-11eb-9145-0ae021b6bb2b.png">

<img width="626" alt="Screenshot 2021-06-03 at 6 15 01 PM" src="https://user-images.githubusercontent.com/60198022/120646929-a6a6ff00-c497-11eb-9bb6-405c61e9e675.png">

Hence, closing the issue, Please feel free to raise new ticket if you any issue.

**Closed as completed by engcom-Lima** 2021-06-03 12:46 UTC
Labels: non-issue, Triage: Dev.Experience, Issue: ready for confirmation
