### ISSUE TITLE
Catalog > Categories - Category View fails, showing raw SQL query for large categories

### ISSUE THREAD

**Issue by lbajsarowicz** [magento/magento2#33995] opened 2021-09-04 22:48 UTC
### Preconditions (*)
1. Magento 2.4.3
2. MySQL 5.7
3. PHP 7.4.23
4. Product Catalog with a Category that contains 100k+ SKUs

### Steps to reproduce (*)

1. Open Catalog > Categories
2. Head to the category with 100k+ SKUs

### Expected result (*)

1. I should be able to view Category details, including Products listed in the Category
2. Magento should never display a raw SQL query anywhere on Admin or Storefront (!)    

### Actual result (*)

1. Magento displays raw SQL query with Product IDs for Products in a Category
    ![Screenshot from 2021-09-05 00-44-17](https://user-images.githubusercontent.com/1639941/132109703-4323ae8c-c9a6-41d7-8903-ee01729fd598.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Lima** [comment] 2021-09-06 08:59
Hi @lbajsarowicz,

I tried to reproduce this issue on Magento 2.4-develop instance with sample data of 100+ SKUs in Category but couldn't find raw SQL query. So, in order to reproduce this can you please check and update if this issue is reproducible on 2.4-develop branch or is it specific to 2.4.3 version ?

Thanks

**Comment by lbajsarowicz** [comment] 2021-09-06 21:00
@engcom-Lima The issue depends strongly on the infrastructure you use. 

I operate on categories of size 1M+ products and we had to bring the `max_allowed_packet` directive to 256M, as a workaround.

The unprofessional part is that Magento fetches the `entity_id`s for a Category, to use exactly the same IDs to count entities in a category.

**Comment by hostep** [comment] 2021-09-06 21:04
@lbajsarowicz: out of curiosity, does the sql query show up both in developer and production mode, or only in developer mode?

**Comment by lbajsarowicz** [comment] 2021-09-06 21:06
The screenshot was performed on Staging environment (`production` mode)

**Comment by hostep** [comment] 2021-09-06 21:08
@nathanjosiah: sounds like a security-related issue then. Magento shouldn't output database details in the webbrowser when running in production mode, right?

**Comment by lbajsarowicz** [comment] 2021-09-06 21:38
IMO Even the evil "Something went wrong", so typical for Magento, is much better than raw SQL :)

**Comment by nathanjosiah** [comment] 2021-09-06 21:41
Yep. I'll get this some attention tomorrow when we are all back.

**Comment by mzeis** [comment] 2021-09-07 03:48
> Hi @lbajsarowicz,
> 
> I tried to reproduce this issue on Magento 2.4-develop instance with sample data of 100+ SKUs in Category but couldn't find raw SQL query. So, in order to reproduce this can you please check and update if this issue is reproducible on 2.4-develop branch or is it specific to 2.4.3 version ?
> 
> Thanks

@engcom-Lima: just to be sure: you noticed that @lbajsarowicz wrote about 100k (100000) products in a category, not 100, correctly?

**Comment by nathanjosiah** [comment] 2021-09-07 14:36
@magento export issue to Jira project AC as Bug

**Comment by ihor-sviziev** [comment] 2021-12-22 08:17
@sidolov FYI, I put P1 priority as a result of this bug the raw SQL is showing in the admin

**Comment by engcom-Bravo** [comment] 2022-11-02 11:58
Hi @lbajsarowicz,

Thank you for reporting and collaboration.

Magento site is running on Production Mode.
Verified the issue on Magento 2.4-develop and the issue is not reproducible.we tired with 100k+ products and 500k+ Products in a category but couldn't find raw SQL query.Kindly refer the screenshots.


<img width="1453" alt="Screenshot 2022-11-02 at 4 51 44 PM" src="https://user-images.githubusercontent.com/51680745/199483495-f503f043-59f9-4294-ae04-dea022cd2ae3.png">



<img width="1460" alt="Screenshot 2022-11-02 at 4 50 19 PM" src="https://user-images.githubusercontent.com/51680745/199483547-8f6257d5-fa8c-47d1-87c1-51a76971ba93.png">



<img width="1440" alt="Screenshot 2022-11-02 at 4 50 29 PM" src="https://user-images.githubusercontent.com/51680745/199483579-967234b9-e75f-4e3f-ac0a-b1f236701fe2.png">




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by engcom-Bravo** [comment] 2022-11-16 06:06
Hi @lbajsarowicz,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-16 06:06 UTC
Labels: Issue:  Cannot Reproduce, Priority: P1, Severity: S1, Progress: done, Issue: needs update, Area: Admin UI, Area: Catalog, Area: Performance
