### ISSUE TITLE
Items container missing in admin when creating shipment

### ISSUE THREAD

**Issue by samuellinde** [magento/magento2#6595] opened 2016-09-13 13:12 UTC
### Preconditions
1. Magento 2.1.1
2. PHP 7.0.8
3. Apache 2.4.7
### Steps to reproduce
1. Create an order in either admin/frontend
2. Select the "ship" action when displaying order in the backend
### Expected result
1. The page should fully load, including the table showing the ordered items.
### Actual result
1. Page is not fully loaded, table of items is missing.
2. No error message, neither JS or PHP, is generated.

<img width="1455" alt="screen shot on 2016-09-13 at 15-02-00" src="https://cloud.githubusercontent.com/assets/57992/18474842/58f20a7a-79c4-11e6-9ee4-4afa78ea7382.png">

**Comment by samuellinde** [comment] 2016-09-23 08:20
Has no one else experienced this issue?

**Comment by viktym** [comment] 2016-09-30 09:49
Hi @samuellinde 
We cannot reproduce this issue as described.  Please provide the detailed steps we must follow to reproduce this issue. In addition, identify used shipping and payment methods, language package, any customizations

**Comment by alena-marchenko** [comment] 2016-10-17 10:06
Hi @samuellinde 

We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by alena-marchenko** 2016-10-17 10:06 UTC
Labels: bug report, Progress: needs update, Component: Shipping
