### ISSUE TITLE
Admin/Backend "Something went wrong" for non-superadmins (/mui/index/render)

### ISSUE THREAD

**Issue by vandijkstef** [magento/magento2#35311] opened 2022-04-14 13:07 UTC
### Preconditions (*)

1. Mage 2.4.3-p1
2. PHP 7.4.X
3. Elastic 7.X
4. Varnish 6.0

### Steps to reproduce (*)

1. Create a second user role with custom resources (all can be enabled, just not set it to 'All' aka a superadmin)
5. Assign a user to that role
6. Login as that user on the backend/admin
7. Open an order and wait untill everything is loaded

### Expected result (*)

1. No error modal popping up/Nothing

### Actual result (*)

1. Error modal pops up: "Something went wrong"

Diving into the browser development tools, it can be seen that the call '/mui/index/render' is returning as 403 FORBIDDEN. This is likely to generate the error modal popping up.

When using a user that has 'All Resources' (not 'Custom, with all enabled) this '/mui/index/render' call returns actual proper data and no error is generated, so I feel this is something to do with ACL in some way.

We are able to work around it. Actually everything still seems functional if you ignore the error popping up.

I opted for S3 severity as anything with rights of access should not be taken lightly, but practically we are only experiencing S4 levels of annoyance. We are considering however to just make everyone superadmin. All we had blocked was the 'Dashboard', but even enabling that for this secondary user role didn't fix anything.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-04-29 10:19
Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
Steps performed:
system - User Roles - Created new role with custom resources
System - All users - Add new User and assigned new user role
sign out and sign using new user
Go to Sales - Orders - View Order - No issue/ no error
Create New Order - no issue
@vandijkstef kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-05-05 12:40
Re-verified the issue again on Magento 2.4-develop branch with enterprise edition modules installed but cannot reproduce the issue.
**Steps performed:**
Pre-conditions: Magento multi store setup with existing orders for both the websites.
1. System - User Roles - Created new role with custom resources
2. System - All users - Add new User and assigned new user role
3. sign out and sign using new user
4. Go to Sales - Orders - View Order - No issue/ no error
5. Create New Order - no issue
@vandijkstef Please check if the issue occurred due to any third party extensions / modules enabled and recheck on Magento 2.4-develop branch as it is the upcoming 2.4.x release. Kindly elaborate the steps if the issue is still reproducible.

**Comment by engcom-November** [comment] 2022-05-18 05:56
Hi @vandijkstef ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-05-18 05:56 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by ankitrtpl** [comment] 2022-11-18 01:35
Does anyone find the resolution of this issue. I am also facing the same issue.

**Comment by vandijkstef** [comment] 2022-11-20 11:05
@ankitrtpl Still facing this issue, maybe we can compare packages to lock down the culprit?

```
"require": {
        "ext-ctype": "*",
        "alekseon/module-cleanrunningjobs": "^1.0",
        "avada/module-proofo": "^1.0",
        "deved/magento2-disable-customer-registration": "^2.1",
        "dominicwatts/contactattachment": "1.0.8",
        "elgentos/regenerate-catalog-urls": "^0.2.10",
        "magenizr/magento2-resetuibookmarks": "1.2.0",
        "magento/composer-dependency-version-audit-plugin": "~0.1",
        "magento/product-community-edition": "2.4.4",
        "mageplaza/magento-2-french-language-pack": "dev-master",
        "mageplaza/magento-2-swedish-language-pack": "dev-master",
        "magevision/module-update-order-email-address": "^2.3",
        "mirasvit/module-feed": "^1.1",
        "nadeem0035/allow-html-tags": "^1.0",
        "onpoint-commerce/module-shipping-rule": "^1.2",
        "orange35/magento2-catalog-import-export": "~1.0.1",
        "orange35/magento2-color-picker-element": "^1.0.1",
        "paynl/magento2-plugin": "^2.8",
        "spatie/html-element": "^1.1.1",
        "splashlab/magento-2-cors-requests": "dev-master",
        "swissup/cache-warmer": "^1.0",
        "swissup/firecheckout": "^1.28",
        "swissup/module-address-field-manager": "^1.5",
        "swissup/module-checkout-fields": "^1.5",
        "swissup/module-marketplace": "^1.8",
        "vpietri/adm-quickdevbar": "^0.1.17"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.4",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
        "friendsofphp/php-cs-fixer": "~2.18.1",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "^3.0",
        "pdepend/pdepend": "~2.7.1",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "^2.8.0",
        "phpstan/phpstan": "^0.12.77",
        "phpunit/phpunit": "^9",
        "sebastian/phpcpd": "^6.0.3",
        "squizlabs/php_codesniffer": "~3.6.0",
        "symfony/finder": "^5.2"
    },
```
