### ISSUE TITLE
running catalog:images:resize out of memory with 6GB assigned to php

### ISSUE THREAD

**Issue by spyrule** [magento/magento2#10085] opened 2017-06-28 15:37 UTC
With a large catalog (250K+) products and images, if an attempt to run catalog:images:resize, eventually the command fails with "PHP Fatal error:  Allowed memory size of 6442450944 bytes exhausted (tried to allocate 20480 bytes) in /vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 291"

There is no way to batch this command into smaller processes.

### Preconditions

1.  Magento 2.1.3+
2.  PHP 7.0.20
3. MySQL
4. NginX Hosted service

### Steps to reproduce
1. Import a LARGE amount of products into Magento catalog with images (250,000+ products)
2. Make sure your PHP is set to allow x GB in memory (my host max is 6GB for php).
3. run catalog:images:resize, eventually a PHP out of memory error will occur.

### Expected result
1. The command should be able to be run with a memory size limit set, once that memory limit is reached, it should be able to stop, and re-start from where it left off.
or have a sub-set of commands like:

- catalog:images:resize new (start from the beginning).
- catalog:images:resize continue (restart from where it last ended).
- catalog:images:resize refresh (on process those images which have not been previously processed).

### Actual result

1. With my PHP memory maxxed for my host (6GB) I run out of memory on attempting to run catalog:images:resize.

**Comment by leibra** [comment] 2017-07-14 05:57
I can confirm this issue. we assigned 5GB to php still our 100k sku catalog failed to resize images. ultimately we had to make a different store with less SKUs and copy image to our original media folder. Mage2 is an impossible platform to use in production.

**Comment by magento-engcom-team** [comment] 2017-10-03 10:30
@spyrule, thank you for your report.
We've created internal ticket(s) MAGETWO-80699 to track progress on the issue.

**Comment by engcom-Charlie** [comment] 2019-12-10 10:30
Hello @spyrule 
Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.4-develop branch by provided steps.

**Testing scenario:**

1. Import a LARGE amount of products into Magento catalog with images (100,000+ products)
2. PHP is set to allow x GB in memory (my host max is 2GB for php).
![image](https://user-images.githubusercontent.com/51680850/70521750-73a4d900-1b48-11ea-8f19-ba736cc31ebf.png)
3. run catalog:images:resize

**Result:** 
`catalog:images:resize ` works fine
![ended](https://user-images.githubusercontent.com/51680850/70521791-87e8d600-1b48-11ea-9400-b6a50d7fe5d9.png)

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-12-10 10:30 UTC
Labels: bug report, Issue: Clear Description, Issue: Format is valid, Triage: Dev.Experience

**Comment by spyrule** [comment] 2019-12-10 14:24
I should mention, I no longer work for the company that had this huge catalog. They got fed up with Magento's broken product management, and dropped Magento completely.  I now work for a company that has a tiny catalog by comparison, and have not experienced this issue since.
