### ISSUE TITLE
Submitting Credit Memo reduces Quantity of inventory products

### ISSUE THREAD

**Issue by blockedie** [magento/magento2#35914] opened 2022-08-11 17:40 UTC
### Preconditions and environment

- Magento ver. 2.4.2-p2
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Configure an inventories product that has a specific stock quantity and salable quantity. Make sure it is greater than or equal to two for the purpose of recreating this bug.
2. Create an order with one of these products and submit it. Note that the salable quantity and the quantity should be reduced by 1
3. From that order, create a credit memo and fully refund the inventoried product.
4. View the quantity of the product and note that is has been _reduced by one_ where I would expect it to actually increase it by one.

### Expected result

I would expect submitting credit memo to either have no change to the quantity of an inventoried product or to increase the quantity by the number of products refunded.

### Actual result

Quantity of inventoried product decreases after a refund for the product is submitted and processed.
For example it looks like the following example:
Pre-purchase: Salable quantity=6, Quantity=6
Post-Purchase: Salable quantity=5, Quantity=5
Post-Credit Memo: Salable quantity=4, Quantity=4. As you can see, the quantity was reduced by 1 even though nothing has been purchased.

### Additional information

Info on inventory reservations: https://devdocs.magento.com/guides/v2.3/inventory/reservations.html

### Release note

Prior to a fix, an end user would see that the quantity of an inventoried product is reduced by the number of items refunded in a credit memo.
Now (assumedly after fix) the quantity of an inventoried product will be unchanged after a credit memo refunding the item is placed.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-08-22 12:25
Hi @blockedie ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not reproduce the issue.
Both qty and salable qty of the inventoried product are same before and after creating the credit memo.
![image](https://user-images.githubusercontent.com/60198231/185920609-ee392269-b856-45df-82e1-bef61d4f803c.png)

![image](https://user-images.githubusercontent.com/60198231/185920516-7ada1532-e7a6-454f-98e2-978d1483558d.png)
Kindly check the issue on Magento 2.4-develop instance as it is the upcoming 2.4.x release and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-09-05 13:08
Hi @blockedie ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-09-05 13:08 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
