### ISSUE TITLE
Using 'getCustomAttribute' in a 'catalog_product_save_before' observer prevents 'Multiple Select'-fields from being saved

### ISSUE THREAD

**Issue by deeke-dmf** [magento/magento2#36210] opened 2022-09-28 16:26 UTC
### Preconditions and environment

Magento Version: **2.4.5**

### Steps to reproduce

1. Create a new "Multiple Select" field named `test_attribute_1`
2. Create an observer for the `catalog_product_save_before` event which uses the `getCustomAttribute` method of the product to be saved
3. Select new values for the `test_attribute_1` field

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="catalog_product_save_before">
        <observer name="package_module_set_test_attribute"
                  instance="\Package\Module\Observer\SetTestAttribute"/>
    </event>
</config>
```
```
<?php
declare(strict_types=1);

namespace Package\Module\Observer;

use Magento\Catalog\Model\Product;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;

class SetTestAttribute implements ObserverInterface
{
    public function execute(Observer $observer)
    {
        /** @var Product $product */
        $product = $observer->getData('product');

        $someCustomAttribute = $product->getCustomAttribute('some_custom_attribute');
    }
}
```

### Expected result

The new selected values of "Multiple Select" field are saved to the database.

### Actual result

Every "Multiple Select" field of the product retains its old values, ignoring the selection of the user. All the other field types are saved without a problem.

This only happens if the `getCustomAttribute` method is called in the observer.  The `setCustomAttribute` method does not cause the issue.

### Additional information

We've found another issue that seems to be related, since we traced the behaviour of our issue in the same way from the `\Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend` to `\Magento\Framework\EntityManager\Operation\Update\UpdateMain::execute`:

https://github.com/magento/magento2/issues/34982

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-20 12:19
Hi @deeke-dmf,

Thank you for reporting and collaboration.
Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**
1.Create a new "Multiple Select" field named test_attribute_1
2.Create an observer for the catalog_product_save_before event which uses the getCustomAttribute method of the product to be saved
3.Select new values for the test_attribute_1 field



```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="catalog_product_save_before">
        <observer name="package_module_set_test_attribute"
                  instance="\Package\Module\Observer\SetTestAttribute"/>
    </event>
</config>
```

```
<?php
declare(strict_types=1);

namespace Package\Module\Observer;

use Magento\Catalog\Model\Product;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;

class SetTestAttribute implements ObserverInterface
{
    public function execute(Observer $observer)
    {
        /** @var Product $product */
        $product = $observer->getData('product');

        $someCustomAttribute = $product->getCustomAttribute('some_custom_attribute');
    }
}
```

<img width="1371" alt="Screenshot 2023-01-20 at 5 37 26 PM" src="https://user-images.githubusercontent.com/51680745/213693203-2a5059c1-6843-4c4f-8266-50c829dda5c6.png">



<img width="1370" alt="Screenshot 2023-01-20 at 5 37 44 PM" src="https://user-images.githubusercontent.com/51680745/213693223-9395071c-1773-41fb-b52e-85afd69c59ed.png">



<img width="1361" alt="Screenshot 2023-01-20 at 5 38 03 PM" src="https://user-images.githubusercontent.com/51680745/213693234-e88f55f0-a5d5-4f30-89ba-686aa724d0c5.png">


<img width="1369" alt="Screenshot 2023-01-20 at 5 38 38 PM" src="https://user-images.githubusercontent.com/51680745/213693245-3557e133-be01-42b4-b79f-6b05e6e02c64.png">




<img width="1375" alt="Screenshot 2023-01-20 at 5 39 22 PM" src="https://user-images.githubusercontent.com/51680745/213693258-df5a9c5b-f9df-4224-adb7-403505f3382c.png">




<img width="1380" alt="Screenshot 2023-01-20 at 5 39 31 PM" src="https://user-images.githubusercontent.com/51680745/213693272-4b8bd3ba-46b5-4464-9b81-1115af5db21a.png">


Selected values of "Multiple Select" field are saved to the database.And isssue is not getting reproducible.

Kindly let us know if we missed anything.

Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

**Comment by engcom-Bravo** [comment] 2023-02-06 09:07
Hi @deeke-dmf,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-06 09:07 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5
