### ISSUE TITLE
Adding multiple configurable variants (with low stock) to cart fails

### ISSUE THREAD

**Issue by patrick-bigbridge** [magento/magento2#16968] opened 2018-07-20 13:47 UTC
### Preconditions
Tested on Magento 2.1.11, but by checking the code, this will still fail on Magento 2.2

### Steps to reproduce
Hang on, this is complicated ;)

I am adding configurable products to the cart, programmatically. Some of these products have low stock, let's say: one item in stock each. The problem occurs when I add multiple variants of the same configurable in the same request.

```
/** @var \Magento\Checkout\Model\Cart $cart */

$params = [
    'qty' => 1,
    'super_attribute' => [
        $product1['super_attribute_id'] => $product1['option_id']
    ]
];

$this->cart->addProduct($configurableId, $params);

$params = [
    'qty' => 1,
    'super_attribute' => [
        $product2['super_attribute_id'] => $product2['option_id']
    ]
];

$this->cart->addProduct($configurableId, $params);
```
When I run this code, which adds two variants of the same configurable, I get this error:

"We don't have as many "<configurable product name>" as you requested."

So while each variant has stock of 1, when I add 1 of each to the cart, I still get an out-of-stock error.

I traced the cause of this error to this line: 

```
$product = $this->productRepository->getById($productInfo, false, $storeId);
```
(in vendor/magento/module-checkout/Model/Cart.php : 304)

It loads the configurable that is used as a "candidate" for the cart. When the configurable is needed twice in the request, it is loaded from the product repository cache, and not created anew. The problem with this is that this product model is later modified with some "custom options" (especially "attributes"), that should make the first configurable different from the second configurable. They are used to compare present cart products to check if they are in the cart already (\Magento\Quote\Model\Quote\Item::compareOptions()).

Since the same configurable is used twice (while it shouldn't) it is added a qty of 1, which gives it a quantity of 2, and this exceeds the stock of the variants, and this gives the named error.

### Expected result
I should be able to add multiple variants of a configurable (with low stock).

### Actual result
"We don't have as many "<configurable product name>" as you requested."

### Suggested solution
The solution could be to force a reload of the cart product, as in:

```
$product = $this->productRepository->getById($productInfo, false, $storeId, true);
```
(in vendor/magento/module-checkout/Model/Cart.php : 304)

**Comment by magento-engcom-team** [comment] 2018-07-20 13:47
Hi @patrick-bigbridge. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@patrick-bigbridge do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-07-20 14:19
Hello @patrick-bigbridge, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-24 13:07
Hi @otsmyh. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by sdzhepa** [comment] 2019-05-22 15:06
Closed this issue based on discussion under PR #19394 with fix and comment https://github.com/magento/magento2/pull/19394#issuecomment-445176791

**Closed as completed by sdzhepa** 2019-05-22 15:06 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, help wanted
