### ISSUE TITLE
Order details in my account doesn't work

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#3140] opened 2016-01-26 10:01 UTC
When logging in as a customer and trying to view my order details, it redirects back to the overview page.

I'm getting this javascript error:
GET http://172.30.0.222/magento2_v2/customer/section/load/?sections=cart%2Ccomp…directory-data%2Creview%2Cwishlist&update_section_id=false&_=1453802141872 400 (Bad Request)

"{"message":"\"*\" section source is not supported"}"

**Comment by rklerck** [comment] 2016-01-27 10:11
On another server, we don't get this javascript error. But it still doesn't work, it redirects back to its own page.

**Comment by mstumpf818** [comment] 2016-04-28 18:51
We can reproduce this issue on OS X Chrome

On Windows 10 Firefox we get a "JQMIGRATE: jQuery.parseJson requires a valid JSON string" error

**Comment by NadiyaS** [comment] 2016-06-08 14:54
Hi @rklerck , @mstumpf818 ,
this issue is not reproducible on 2.0.7 version. 
Please upgrade your code to this version and if you still have encountered this problem, please, provide more detailed steps to reproduce.
Thanks.

**Comment by NadiyaS** [comment] 2016-06-23 11:37
The Issue is closed as not reproducible.
If you still have encountered this bug feel free to reopen it and provide all necessary details to reproduce it (Magento version, steps to reproduce, also all external extensions should be disabled, etc.)

**Closed as completed by NadiyaS** 2016-06-23 11:37 UTC
Labels: Progress: needs update
