### ISSUE TITLE
Page limiter overlapping on pager in customer order section in frontend

### ISSUE THREAD

**Issue by cedarvinda** [magento/magento2#19686] opened 2018-12-10 13:26 UTC
### Preconditions (*)

1. Magento 2.3.0
2. PHP 7.2

### Steps to reproduce (*)

Step 1: Go to Frontent base url 
Step 2: Login as customer 
Step 3: Go to my acccount section 
Step 4: Click on my order link on left sidebar 
    	Note : Order should be greater than default page limiter.
    	Example: if page limiter default value set to 10 then order should be 11 then pager will display

### Expected result (*)

http://i.imgur.com/BEAQXRQ.png

### Actual result (*)

http://i.imgur.com/ihO9Djd.png

**Comment by magento-engcom-team** [comment] 2018-12-10 15:12
Hi @eduard13. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by eduard13** [comment] 2018-12-10 16:45
@cedarvinda I wasn't able to reproduce it on the latest version, the `float:right` already persists.
![db4651cead](https://user-images.githubusercontent.com/15868188/49747102-51654a80-fcab-11e8-8e4a-5f689425ce31.jpg)
Please feel free to reopen the issue if you have some additional info which will help to reproduce the issue.

PS: Next time please attach the images to the issue, not just the link to them.
Thank you.

**Comment by magento-engcom-team** [comment] 2018-12-10 18:14
Hi @cedarvinda. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@cedarvinda do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by cedarvinda** [comment] 2018-12-11 05:16
@magento-engcom-team  give me 2.3-develop instance

**Comment by shikhamis11** [comment] 2018-12-11 05:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-12-11 05:20
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-12-11 05:21
Hi @shikhamis11, here is your [Magento instance](https://i-19686-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-19686-2-3-develop.instances.magento-community.engineering/admin](https://i-19686-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2018-12-11 05:44
The issue is resolved in 2.3 develop

**Closed as completed by shikhamis11** 2018-12-11 05:44 UTC
Labels: Issue: Clear Description, Issue: Format is valid, Component: Theme
