### ISSUE TITLE
PayPal Pay-later amount is not shown

### ISSUE THREAD

**Issue by in-session** [magento/magento2#35560] opened 2022-05-31 21:23 UTC
### Preconditions and environment

- Magento version 2.4.4.
- PHP 7.4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/16542619/171339009-88d185f6-e6b7-4dbb-b575-29b5aeccb2cf.png)

### Expected result

![Ashampoo_Snap_Dienstag, 31  Mai 2022_23h21m57s](https://user-images.githubusercontent.com/16542619/171286660-3ce725ee-d420-455d-af8f-49274582a279.png)

### Actual result

![Ashampoo_Snap_Dienstag, 31  Mai 2022_23h20m19s](https://user-images.githubusercontent.com/16542619/171286454-9e198768-f2b9-4d1f-915d-bc3ab03bc96b.png)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-06-02 11:43
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-06-02 12:08
Hi @in-session ,
Thank you for the update. Verified the issue again on Magento 2.4-develop branch but cannot able to reproduce the issue.
Pay later amount is displayed as expected in all the pages of front-end
FYI.. In order to display Paylater amount, paypal billing agreement settings should be disabled from admin payment configuration. Please check. (Configuration - Sales - Payment methods - Configure Paypal Express checkout - Advanced settings - Enable Paypal billing agreement settings - NO)
![image](https://user-images.githubusercontent.com/60198231/171625752-8bebba1a-0891-4eed-9008-493f524c78b3.png)
![image](https://user-images.githubusercontent.com/60198231/171625799-15ca5c69-36f9-4d4b-bd7a-164508fa0919.png)
Kindly recheck the issue again on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by in-session** [comment] 2022-06-02 12:24
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-06-17 11:11
Hi @in-session ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-17 11:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by in-session** [comment] 2022-06-23 15:35
https://github.com/magento give me 2.4-develop instance

**Comment by in-session** [comment] 2022-06-23 15:36
@magento give me 2.4-develop instance

**Comment by in-session** [comment] 2022-06-23 15:38
@engcom-November did you use the PayPal Express Checkout or Braintree module here? The problem is with PayPal Express Checkout.
