### ISSUE TITLE
View and Edit Cart link not aligned in middle because bellow the link a blank div (class="minicart-widgets") existing has 15px margin top, this div (class="minicart-widgets" ) should be display none or should not come if has no content, should only display if has content

### ISSUE THREAD

**Issue by irajneeshgupta** [magento/magento2#20382] opened 2019-01-17 19:07 UTC
**View and Edit Cart** link not aligned in middle because bellow the link a blank div (**class="minicart-widgets"**) existing has **15px margin top**, this div (**class="minicart-widgets"** ) should be display none or should not come if has no content, should only display if has content.

### Preconditions (*)

1. Magento 2.3
2. php 7.2

### Steps to reproduce (*)

1. Open frontend 
2. Add any product in cart and go to minicart and see **View and Edit Cart** Link  (you will get issue )
3. you will see extra space bellow the link and now inspect you see bank div has 15px margin top.

### Expected result (*)

![mini_sol](https://user-images.githubusercontent.com/18143480/51342164-fd871780-1a47-11e9-96f2-bfee781af7e8.png)

### Actual result (*)

![mini_issue](https://user-images.githubusercontent.com/18143480/51342113-da5c6800-1a47-11e9-9790-af8e1b7aa49d.png)

**Comment by magento-engcom-team** [comment] 2019-01-17 19:07
Hi @irajneeshgupta. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@irajneeshgupta do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-17 19:07
Hi @cedarvinda. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cedarvinda** [comment] 2019-01-17 19:08
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-17 19:08
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-17 19:08
Hi @cedarvinda, here is your [Magento instance](https://i-20382-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20382-2-3-develop.instances.magento-community.engineering/admin](https://i-20382-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-17 19:09
@cedarvinda Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97700` were created

**Comment by cedarvinda** [comment] 2019-01-17 19:10
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-17 19:10
Hi @cedarvinda. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-17 19:10
Hi @cedarvinda, here is your [Magento instance](https://i-20382-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20382-2-2-develop.instances.magento-community.engineering/admin](https://i-20382-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-10 18:20
Hi @irajneeshgupta. Thank you for your report. 
The issue has been fixed in magento/magento2#20383 by @irajneeshgupta in 2.3-develop branch
Related commit(s):
 - [5aa0cd069e82ae106d7d9eb6c37d38776a2ba762](https://github.com/magento/magento2/commit/5aa0cd069e82ae106d7d9eb6c37d38776a2ba762)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2019-02-10 18:20 UTC
Labels: Issue: Ready for Work, Component: Checkout, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by magento-engcom-team** [comment] 2019-02-12 17:25
Hi @irajneeshgupta. Thank you for your report. 
The issue has been fixed in magento/magento2#21124 by @irajneeshgupta in 2.2-develop branch
Related commit(s):
 - [05848e5e999e25aa75583fdfbee960f708a8e8dc](https://github.com/magento/magento2/commit/05848e5e999e25aa75583fdfbee960f708a8e8dc)

The fix will be available with the upcoming 2.2.9 release.

**Comment by kozie** [comment] 2019-06-28 13:42
@irajneeshgupta  Why did you add an `if` statement to the following line?https://github.com/magento/magento2/blob/f77ac3c8ce55a52be143f18073106c5de68adc35/app/code/Magento/Checkout/view/frontend/web/template/minicart/content.html#L100
It doens't make sense seeing the current issue and it's causing my widgets to not show up anymore.
