### ISSUE TITLE
Messages from customerData should be unique before displaying to frontside

### ISSUE THREAD

**Issue by tuyennn** [magento/magento2#34386] opened 2021-10-19 12:38 UTC
### Preconditions (*)

1. Magento 2.4.x
2.

### Steps to reproduce (*)

1. Try to do something could show message to frontside as an ajax function for multiple times, actually same action for multiple times
2. Observe the messages on frontend

### Expected result (*)

1. Same Messages should not be duplicated, should be unique and be displayed as 1 message if they are duplicated
2.

### Actual result (*)

1. Same messages were displayed for lines
2.

### Suggestion
See https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/frontend/web/js/view/messages.js#L32 seem the cookieMessages were truncated and be unique.
Should add something here to https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/frontend/templates/messages.phtml#L20-L21 make the messages unique

```
<div aria-atomic="true" role="alert" class="messages" data-bind="foreach: {
        data: _.unique(messages().messages, 'text'), as: 'message'
    }">
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-12-28 06:43
Hi @tuyennn,

I checked and still the info is not clear. What I could not understand is, if you are creating an ajax function to be called multiple times then obviously it'll display same messages again if you have provided logic like that. It would be more clear after I can look at the code.

Can you please share the code and other relevant details due to which you are facing this issue ? I will do further analysis accordingly.

Thanks

**Comment by tuyennn** [comment] 2021-12-30 07:16
@engcom-Echo I believe the Suggestion I put on the top could describe the bug in detail, while `cookieMessages` was made unique, but `messages().messages` was not. Possible you could get multiple duplicate messages on customerData message. You'll see the frontend messed with duplicated messages throwed.

**Comment by engcom-Echo** [comment] 2021-12-30 13:37
Hi @tuyennn,

Yes I understood the issue but in order to confirm this issue, I will have to reproduce this with the correct code implementation so that I can confirm the validity of it. 

And also, I’ll have to check the impact of it and it won’t be possible until I try with the code changes. So can you please help me with that ?

Thanks

**Comment by engcom-Echo** [comment] 2022-01-14 04:55
Hi @tuyennn,

We have noticed that this issue has not been updated for more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-01-14 04:55 UTC
Labels: Component: Message, Triage: Dev.Experience, Issue: needs update

**Comment by tuyennn** [comment] 2022-01-14 05:33
@engcom-Echo Well in this case I think magento could resolve all the open tickets in next 18000 days, thanks for the support, I have my own solution and fixes.
