### ISSUE TITLE
Disable vat required value

### ISSUE THREAD

**Issue by mariogobos** [magento/magento2#35755] opened 2022-07-12 08:47 UTC
### Preconditions and environment

- Magento version 2.4.4
- Multi store version

### Steps to reproduce

Only for FR Website in Stores=>Configuration=>Customer=>Customer Configuration=> Name and Adress Options=> Show Tax/VAT Number=> No
after try to save a customer without vat number and you can't to save it

### Expected result

Only for FR Website Vat number is not a required value

### Actual result

Vat number in FR website is a required value

### Additional information

I try to set Show Tax/VAT Number=>Optional, i try to disable eav cache but not work.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by glo11468** [comment] 2022-07-13 15:55
Hi @mariogobos ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.Can you please check on 2.4-develop branch whether you are still able to reproduce the issue.Vat Number is not a required value.we can save without it.please refer the screenshots.

![Screenshot (287)](https://user-images.githubusercontent.com/90306034/178777724-b27b4254-bd54-47e6-a082-7025a974a019.png)
![Screenshot (288)](https://user-images.githubusercontent.com/90306034/178777739-128b9db9-ae32-484b-8df9-dc091e25fb95.png)
![Screenshot (290)](https://user-images.githubusercontent.com/90306034/178777748-da4aed27-6195-4e1b-8db4-8b630186286d.png)
![Screenshot (291)](https://user-images.githubusercontent.com/90306034/178777750-7a3df5bc-6458-4267-894d-4abc1ccea93f.png)

**Comment by engcom-Delta** [comment] 2022-07-14 12:12
Hi @mariogobos ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.Can you please check on 2.4-develop branch whether you are still able to reproduce the issue.Vat Number is not a required value.we can save without it.please refer the screenshots attached.

![Screenshot (288)](https://user-images.githubusercontent.com/51681379/178979486-11c7ea38-8da3-4b0c-88be-75c3151517d1.png)
![Screenshot (290)](https://user-images.githubusercontent.com/51681379/178979491-e95c77e5-8c00-49ca-8c0f-24d4959c69ca.png)
![Screenshot (291)](https://user-images.githubusercontent.com/51681379/178979500-9b6304d6-3d10-4882-a5d8-d22da8212f63.png)

![Screenshot (287)](https://user-images.githubusercontent.com/51681379/178979466-4f4fdef5-2891-429e-8940-cb0ff9205ba6.png)

**Comment by engcom-Bravo** [comment] 2022-07-28 09:40
We have noticed that this issue has not been updated for a period of more than 14 Days. 
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Bravo** 2022-07-28 09:40 UTC
Labels: Issue: needs update, Reported on 2.4.4

**Comment by mariogobos** [comment] 2022-09-06 09:16
Hello, sorry for delay, it's very importat to resolve this issue. I have migrate a multilanguage store from magento 1.7 to magento 2.4. But now when i set vat number as not required for website for example FR and it write correctly on database under customer_eav_attribute_website don't work. After full cache refresh vat number is not required but when i create a new customer, try to save old customer without vat or create quote for customer without vat doesn't work magento required vat.
