### ISSUE TITLE
Customer Address update in Backend and "customer_address_save_commit_after" or "customer_address_save_after" event do not update Address Data in associated Magento\Customer\Model\Backend\Customer address collection

### ISSUE THREAD

**Issue by pisc-software** [magento/magento2#8855] opened 2017-03-11 10:43 UTC
### Preconditions
1.  Magento 2.1.4
2. PHP 7 (Zend Server) and MariaDB10

### Steps to reproduce
1. Add a debug breakpoint to a observer using "customer_address_save_commit_after" or "customer_address_save_after" and get the customer model by "$address->getCustomer".
2. Edit Customer Account Address in Backend (e.g. the default Billing Address) and change some data there (e.g. VAT ID, Country)
3. Save the Customer Account
4. Evaluate the "$address->getCustomer()" variable and further into the "_addressCollection->_items" structure
5. You will see that the recently saved address changes are not reflected in that structure, there the old data is still in there

### Expected result
1. The edited address data should be in the "$address->getCustomer()->_addressCollection->_items" variable.

### Actual result
1. The old address data (before save) is in the "$address->getCustomer()->_addressCollection->_items" variable.
2. When using the observers "customer_address_save_commit_after" or "customer_address_save_after" to get the related customer data and then save the customer the original address data is overwritten over the edited address data actually reverting the previous edited address data save back to its original state.

Now that actually prevents using the $address->getCustomer() function to use the associated customer model for processing as the address data in there is out of sync with the DB. The assumption is that the address data changes are reflected into the $address->getCustomer() received model.

This also related to this one here when there is a module using these Events and consequently is saving the Customer Object received from the Address in the Observer (by effectively resetting back the Address to the original state):

[https://github.com/magento/magento2/issues/7668](https://github.com/magento/magento2/issues/7668)

**Comment by orlangur** [comment] 2017-03-12 18:29
Plugins/interceptors shall be implemented instead of observers whenever possible.

Will you observe the wrong behavior in corresponding interceptor implemented properly? (note that `save` method of models is deprecated and thus you should not rely on it in interceptors)

**Comment by pisc-software** [comment] 2017-03-13 16:34
When using a Interceptor onto the AddressRepository->save Method that issue is not there, as we need to load the Customer Data in a separate call to the CustomerRepository, because there is no ->getCustomer() method on the address data model.

So that is related to the event where the data is not updated. So if one shall not use the observers, why is the observer still in there?

We are porting our extensions from M1.9 to M2.1 and the amount of coding time is already immense to adapt the code. So I think every developer will try to use the events that are still there. And those should render the to be expected data results in my opinion.

Now we see - from our experience working with the M2.1 code base - that by introducing new concepts of separating models and data into their own model parallel ways of handling models and data open up. And we see that as a downside as it creates additional coding work for developers, so a nice idea actually is adding costs to customer projects and developments.

In many places we find it still more easier and straightforward to work with M1.9 than with M2.1 because of the lower level of complexity and the fact that M1.9 had a fully working data persistency in their model structure. It was simple, and did work. So why this is now gradually thrown over board is unclear to us. And apparently creates issues with backward compatibility on events.

**Comment by magento-engcom-team** [comment] 2017-10-05 15:30
@pisc-software, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 15:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is valid
