### ISSUE TITLE
Default billing/shipping addresses overwritten in 'My Account'

### ISSUE THREAD

**Issue by dspiritocme** [magento/magento2#25588] opened 2019-11-13 20:16 UTC
### Preconditions (*)

1. 2.3.1 Cloud Commerce
2. can provide project URL if requested.

### Steps to reproduce (*)

1.  Create account from frontend of website
2.  Confirm Account
3.  Login to My Account
4.  Click Address book
5.  Click edit default billing or shipping address
6.  Save
7.  Note both addresses were updated

### Expected result (*)

1.  Create account from frontend of website
2.  Confirm Account
3.  Login to My Account
4.  Click Address book
5.  Click edit default billing or shipping address
6.  Save
7.  Only edited address should update, unless missing checkbox 'Use this address as my default X address' is added and selected.

### Actual result (*)

1. Both addresses were updated, for example: edited billing address only and billing/shipping were both updated

**Comment by dspiritocme** [comment] 2019-11-13 20:18
Confirmed on vanilla-ish install. http://magento2demo.firebearstudio.com/

**Comment by ajijshekh123** [comment] 2019-11-14 05:34
Hi @dspiritocme,

I have verified this issue as per your steps to be reproduced and also verify different scenarios. But I can't reproduce it.
Can you please provide me the video?

Thanks.

**Comment by ajijshekh123** [comment] 2019-11-15 11:52
@dspiritocme - Can you please update me about this issue. If you haven't reproduced this issue ask me, I will close this issue.

Thanks.

**Comment by ajijshekh123** [comment] 2019-11-18 04:39
@dspiritocme - If you have found this issue again. You can attached the video and reopen this issue.
Now I am closing this issue.

Thanks.

**Closed as completed by ajijshekh123** 2019-11-18 04:39 UTC
Labels: Progress: needs update, Area: Frontend, Issue:  Cannot Reproduce, Issue: Format is valid
