### ISSUE TITLE
Tier price of simple item not working in Bundle product

### ISSUE THREAD

**Issue by adarshkhatri** [magento/magento2#21467] opened 2019-02-27 05:59 UTC
### Preconditions (*)

1. Magento 2.3.0
2. Bundle products having at least 1 child product
3. Child product should have some tier prices

### Steps to reproduce (*)

1. Simple product priced $500
2. Add tier price exactly as follow:
3. First row: qty=1000, Fixed Price = $300
4. Second row: qty=500, Fixed Price = $400
5. Third row: qty=10000, Fixed Price = $100
6. Fourth row: qty=5000, Fixed Price = $200
7. Save product.

When adding tier price, you must add in this sequence. Unless you change the sequence later on like this:
1. Simple product priced $500
2. Add tier price exactly as follow:
3. qty=500, Fixed Price = $400
4. qty=5000, Fixed Price = $300
5. Save product.
6. Lets add more tier price: 
7. New row: qty=10000, Fixed Price = $100
8. New row: qty=1000, Fixed Price = $200
9. Save product.

### Expected result (*)

1. Display correct price (price as configured).

### Actual result (*)

1. Displayed price (price as configured) is wrong,
2. Wrong tier price rate applies
3. 
![budnle bug](https://user-images.githubusercontent.com/8390252/53468859-f3791f80-3aaf-11e9-80ff-e1d77b89f2bb.png)

When Adding to cart, it calculates correctly. Only displaying problem.

**Comment by magento-engcom-team** [comment] 2019-02-27 06:00
Hi @adarshkhatri. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@adarshkhatri do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by adarshkhatri** [comment] 2019-02-27 06:02
yes

**Comment by magento-engcom-team** [comment] 2019-02-27 06:16
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-27 06:20
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-27 06:20
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-27 06:21
Hi @krishprakash, here is your [Magento instance](https://i-21467-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21467-2-3-develop.instances.magento-community.engineering/admin](https://i-21467-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-27 08:15
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-06 08:34
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98581` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-20 02:50
Hi @adarshkhatri. Thank you for your report. 
The issue has been fixed in magento/magento2#21469 by @adarshkhatri in 2.3-develop branch
Related commit(s):
 - [caabef2fe931aa69b4955ff8265afa52cb61a361](https://github.com/magento/magento2/commit/caabef2fe931aa69b4955ff8265afa52cb61a361)
 - [4c1c65303c3b60de437cb84d882b16718f2f085a](https://github.com/magento/magento2/commit/4c1c65303c3b60de437cb84d882b16718f2f085a)
 - [d4dd2e6bb7c331a167317e2b67126f1c39df6a0f](https://github.com/magento/magento2/commit/d4dd2e6bb7c331a167317e2b67126f1c39df6a0f)
 - [e7589ad85786211022c3860c78ccb21a26f69e8f](https://github.com/magento/magento2/commit/e7589ad85786211022c3860c78ccb21a26f69e8f)
 - [6f49b07031e8e9248a19d8f3ee20402650e60d30](https://github.com/magento/magento2/commit/6f49b07031e8e9248a19d8f3ee20402650e60d30)
 - [0332391af0883d78daa90de5bafc93a5e67765a2](https://github.com/magento/magento2/commit/0332391af0883d78daa90de5bafc93a5e67765a2)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-20 02:50 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Bundle

**Comment by dmytro-ch** [comment] 2019-03-22 10:02
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-22 10:02
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-22 10:03
Hi @dmytro-ch, here is your [Magento instance](https://i-21467-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21467-2-2-develop.instances.magento-community.engineering/admin](https://i-21467-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-26 15:15
Hi @adarshkhatri. Thank you for your report. 
The issue has been fixed in magento/magento2#21844 by @amol2jcommerce in 2.2-develop branch
Related commit(s):
 - [9afef9930cceeceff76bb3aa9311ee56a656dbca](https://github.com/magento/magento2/commit/9afef9930cceeceff76bb3aa9311ee56a656dbca)
 - [6577c64b27fc6bb031cf9a760793d84e9b45c088](https://github.com/magento/magento2/commit/6577c64b27fc6bb031cf9a760793d84e9b45c088)
 - [6fd1080ffac2350f378f7a3fa2a3e49b511c9019](https://github.com/magento/magento2/commit/6fd1080ffac2350f378f7a3fa2a3e49b511c9019)
 - [8f085e6e1aee2b415a867d0475a65c7b4c1316e4](https://github.com/magento/magento2/commit/8f085e6e1aee2b415a867d0475a65c7b4c1316e4)
 - [134bfd5636a00e68fb978c361dc78d96898c1d6d](https://github.com/magento/magento2/commit/134bfd5636a00e68fb978c361dc78d96898c1d6d)
 - [a14c80439f97bb4a954e39f44c3372587f07ff5d](https://github.com/magento/magento2/commit/a14c80439f97bb4a954e39f44c3372587f07ff5d)

The fix will be available with the upcoming 2.2.9 release.
