### ISSUE TITLE
magento 2.x taxamo checkout integration having error

### ISSUE THREAD

**Issue by vikeni** [magento/magento2#7898] opened 2016-12-20 11:23 UTC
Failed to communicate with Braintree:

**Preconditions**
1. Magento 2.1.2
2. configure taxamo site - set merchant 
3. braintree configuration in taxamo site & set test mode 

**Steps to reproduce**
1. in cart.phtml page add script as below
Taxamo.initialize('SamplePublicTestKey1'); //you should use your own public key here
var transaction = { currency_code:'EUR',
                    transaction_lines: [{'custom_id': 1, amount: 1.99}] }
var metadata    = { allowed_payment_providers: 'braintree',
                    require_invoice_address: true };
var checkout = new Taxamo.Checkout(transaction, metadata);
checkout.overlay(function(data) { //you can also use .redirect() here
   alert('callbackhandler:' + JSON.stringify(data, null, '\t'));
});
2. add to cart any product then taxamo checkout form will open
3. fill the details and click on proceed button.

### Expected result
1. should proceed form without any error

### Actual result
Errors have occurred, please validate your input and re-try. Error details:
Failed to communicate with Braintree:
If errors persist, please contact customer support.

**Comment by YevSent** [comment] 2016-12-26 16:26
Hi, @vikeni, described issue looks like a problem with Taxamo, please, contact with Taxamo support.
If it Magento issue, please, provide details about errors on Magento side, like browser console errors.

**Comment by alena-marchenko** [comment] 2017-01-19 14:41
Hi @vikeni 

We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue.

**Closed as completed by alena-marchenko** 2017-01-19 14:41 UTC
Labels: bug report, Progress: needs update, Component: Payment
