### ISSUE TITLE
PayPal Button z-index too high

### ISSUE THREAD

**Issue by Eddcapone** [magento/magento2#30480] opened 2020-10-13 09:03 UTC
### Preconditions (*)

1. 2.4.0

### Steps to reproduce (*)

1. Enable PayPal
2. Open a product in the frontend (catalog product view)
3. Inspect the paypal button iframe
4. It has z-index 100

If you have magnifier for product images enabled and you hover over the image, then the paypal button is visible over the zoom image container.

![image](https://user-images.githubusercontent.com/16349349/95839858-c7251c00-0d43-11eb-8058-e88c973a9362.png)

We also have a elastic search searchbar and the paypal button is showing over the search result box.

![image](https://user-images.githubusercontent.com/16349349/95839644-8a592500-0d43-11eb-86a4-46bb31523535.png)

### Expected result (*)

see above

### Actual result (*)

see above

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ajijshekh123** [comment] 2020-10-14 05:03
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2020-10-14 05:24
Hi, @Eddcapone,
Default Magento doesn't provide magnifier functionality so not able to verify the issue. It will require the Triage dev Experience.

**Comment by mrtuvn** [comment] 2020-10-17 01:47
Is this reproduce in default magento theme ? In my view from your screenshot bug css reproduce in custom theme with custom menu module and also produce in details page when user zoom in media image

**Comment by mrtuvn** [comment] 2020-10-17 02:10
Found this inline css. Maybe iframe contain paypal have higher z-index than other so that you will get visual like description
#zoid-paypal-buttons-39a244ba06_mdi6mdq6nty > iframe.component-frame {
    z-index: 100;
}

**Comment by mrtuvn** [comment] 2021-03-30 08:38
I believe this report still valid

**Comment by engcom-Bravo** [comment] 2023-01-18 12:47
Hi @Eddcapone,

Thank you for reporting and collaboration.


It seems to be a magnifier issue which a third party module and core Magento 2 does not provide this and it is applying on Paypal button which is also a third party module so we  request you please connect with the Paypal developer team or magnifier team which you are using.


Thanks.

**Comment by Eddcapone** [comment] 2023-01-18 13:36
I use the magento default magnifier.

**Comment by engcom-Bravo** [comment] 2023-01-24 12:53
Hi @Eddcapone,

Thanks for your update.

Steps to reproduce :

1.Enabled PayPal
2.Opened a product in the frontend (catalog product view)
3.Inspected the paypal button iframe.


<img width="1377" alt="Screenshot 2023-01-24 at 3 51 17 PM" src="https://user-images.githubusercontent.com/51680745/214296260-98c7bd14-c03c-42da-9090-162c67ce876b.png">


while hover the product image we are not able to see paypal button above that.So can you please tell us have you also followed same magento magnifier or added some more steps in between .If we get some more inputs it willl be helpful to reproduce the isssue

Thanks.

**Comment by engcom-Bravo** [comment] 2024-05-14 05:46
Hi @Eddcapone,


We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-14 05:46 UTC
Labels: Severity: S4, Priority: P4, Progress: done, Issue: needs update, Reported on 2.4.0
