### ISSUE TITLE
Pagebuilder 404 error on save when using <script type="text/javascript">

### ISSUE THREAD

**Issue by Josch-KEDO** [magento/magento2#35502] opened 2022-05-19 15:26 UTC
### Preconditions and environment

- Magento version: 2.4.3-p1
- PHP 7.4.29
- Ubuntu 18.04.6 LTS

### Steps to reproduce

Add a new block, open "Edit with Page Builder". 

Drag an "Elements" > "HTML Code" element in the right window and paste the line <script type="text/javascript"></script> into this HTML code element. 

Save the block.

You'll get an error page with the error "404 error: Page not found.".

### Expected result

Expected, that the block will be saved.

### Actual result

Get an error page "404 error: Page not found."

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-20 12:36
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-20 12:57
Hi @Josch-KEDO ,
Thank you for reporting and collaboration. Verified this issue on Magento 2.4-develop branch but could not able to reproduce the issue.
**Steps performed:**
1. Admin - Content - Elements - Blocks - Add new Block - Edit with Page builder - Drag - Elements" > "HTML Code" element in the right window and paste the line <script type="text/javascript"></script> into this HTML code element.
User is able to apply and save the block
However a warning message "Temporarily allowed to save HTML value that contains restricted elements. Allowed HTML tags are: div, a, p, span, em, strong, ul, li, ol, h5, h4, h3, h2, h1, table, tbody, tr, td, th, tfoot, img, hr, figure, button, i, u, br, b, iframe, style, pre" is displayed to the user.
![image](https://user-images.githubusercontent.com/60198231/169532538-041b0ff3-1e16-460e-b9f5-e226e92317f4.png)
![image](https://user-images.githubusercontent.com/60198231/169532609-092571c3-b86a-4664-8564-89e63673e7b5.png)
Kindly recheck the issue again on Magento 2.4-develop branch as it is the upcoming 2.4.x release and have latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by Josch-KEDO** [comment] 2022-05-23 11:48
Update - the same for me - it works, when the PageBuilder module is disabled.
What can cause these 404 errors on saving with PageBuilder?

Could it be a Javascript problem - maybe an incompatibility with other Javascripts?

**Comment by engcom-November** [comment] 2022-05-25 10:41
Hi @Josch-KEDO ,
Thank you for the response. We cannot add any layouts to the content if page builder module is disabled on magento 2.4-develop.
Without page builder, we can only add text as shown below and cant perform any given steps.
![image](https://user-images.githubusercontent.com/60198231/170242419-fd9f32f7-d0b6-4235-9580-ee7c1915ddbf.png)
Rechecked the issue again with page builder enabled on 2.4-develop branch but could not able to reproduce the issue. Please find attached videos of the same.
Also please note that, Magento versions: 2.4.3-p1 / 2.4.3-p2 requires system default PHP version: 7,.4 but not 8.1. Please refer the magento [system requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) compatible for specific magento versions and also check if any 3rd party extensions / modules enabled causing this issue. 

https://user-images.githubusercontent.com/60198231/170244129-e6ab9b9d-3cb0-4cf0-9fa6-291180bec0e4.mp4
Thank you

**Comment by engcom-November** [comment] 2022-06-08 07:08
Hi @Josch-KEDO ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-06-08 07:08 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by hgati** [comment] 2023-09-26 11:32
> OK - I have an update on this for whom it may concern:
> 
> I wasn't a Magento error/bug, it was the ModSecurity module on our server (here: Plesk) that was triggered by the code posted from the PageBuilder module ("text/javascript found within ARGS_POST"). I added the Security rule ID to the ignore list and now I can save HTML code with embedded JS code.

In the /var/log/modsec_audit.log, you can see that it triggers the following blocking rule in the ModSecurity log.

![](https://gcdnb.pbrd.co/images/dQS6RbRz7hJV.png) 

I have resolved the issue by excluding seven rule IDs only when the specific URI is encountered.

```
SecRule REQUEST_URI "^/admin/blog/post/save/" "id:106,phase:1,ctl:ruleRemoveById=920170;ARGS:id,ctl:ruleRemoveById=941100;ARGS:id,ctl:ruleRemoveById=941110;ARGS:id,ctl:ruleRemoveById=941140;ARGS:id,ctl:ruleRemoveById=941160;ARGS:id,ctl:ruleRemoveById=941190;ARGS:id,ctl:ruleRemoveById=949110;ARGS:id,nolog"
```
