### ISSUE TITLE
Magento unable to fully read themes [Magento 2.0.5]

### ISSUE THREAD

**Issue by AngelsDustz** [magento/magento2#4445] opened 2016-05-10 09:26 UTC
## Steps to reproduce
1. Create a new theme in `app/design/frontend/[Vendor]/[Theme]`
2. Create a `layout.xml` and `theme.xml`
   3.
   a. When trying to select your theme in Page->Theme you will get the default Theme name
   b. When trying to select a layout from your theme in Content->page you are only able to select the    default layouts.
## Expected result
1. Create the files, configure them and select and use them.
## Actual result
1. The Theme will get default values. (theme.xml and layout.xml not being read)
   (The theme does get detected though!)
2. The Theme has no layouts.

I managed to fix this by reverting to version 2.0.0
During all of this I tried any thing I could to get it to work;
- reset cache
- edit vendor files (This actually gave some results, but really weird ones)

During all this the Mode was set to development.

If anything this needs some research.

**Comment by mazhalai** [comment] 2016-05-10 14:21
@AngelsDustz this looks like the duplicate of #2797

**Comment by AngelsDustz** [comment] 2016-05-11 07:39
@mazhalai By the looks of it (s)he wants to include/load a Theme using composer as where I tried to create one.
Also my themes were added, it simply didn't read beyond the fact it saw the folder, theme.xml etc. was being ignored.

**Comment by mazhalai** [comment] 2016-05-24 19:56
@AngelsDustz did you have a chance to try it on 2.1.0-rc1?

**Comment by AngelsDustz** [comment] 2016-05-25 08:03
@mazhalai Sorry I didn't after we saw it didn't work/gave problems on 2.0.5
we reverted back to 2.0.0 A.S.A.P.

**Comment by mazhalai** [comment] 2016-05-27 14:50
@AngelsDustz regardless, we have created MAGETWO-53544 to investigate.

**Comment by skovalenk** [comment] 2016-06-01 12:53
Hi @AngelsDustz 
I have checked MAGETWO-53544 on Magento 2.1.0-rc. 
Seems problem was fixed. This bug was also related to this one: https://github.com/magento/magento2/issues/519

**Closed as completed** 2016-06-01 12:54 UTC
Labels: Issue: Ready for Work, Progress: needs update
