### ISSUE TITLE
"Area is already set" on Design Config save

### ISSUE THREAD

**Issue by josephmcdermott** [magento/magento2#17169] opened 2018-07-26 14:44 UTC
### Preconditions
1. Install 2.2.5

### Steps to reproduce
1. Go to Admin > Content > Design > Configuration
2. Issue 1: The design grid filters render BELOW the grid
3. Issue 2: Edit the Default Store View (the store view scope, third one down)
4. Hit save, and see the error message: "Something went wrong while saving this configuration: Area is already set"

### Expected result
1. Design config should save

### Actual result
1. Cannot save design config at store view level.

![josephmcdermott 2018-07-26 at 15 43 04](https://user-images.githubusercontent.com/6955944/43269422-bd7e82ea-90ea-11e8-81f7-21c0ab0753c7.jpg)
![josephmcdermott 2018-07-26 at 15 43 48](https://user-images.githubusercontent.com/6955944/43269423-bd9c61f2-90ea-11e8-81e2-9750e13b5a4c.jpg)

**Comment by magento-engcom-team** [comment] 2018-07-26 14:44
Hi @josephmcdermott. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@josephmcdermott do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by niners52** [comment] 2018-07-26 14:47
Hi Joseph, I had the same issue and found this https://github.com/magento/magento2/issues/14968 It will be fixed in 2.2.6

**Comment by DanielRuf** [comment] 2018-07-26 18:56
Closing as this is already fixed in the develop branches (2.2-dev and 2.3-dev afaik).

**Closed as completed by DanielRuf** 2018-07-26 18:56 UTC
Labels: Issue: Format is valid
