### ISSUE TITLE
Second language Guest Checkout - Api Call Guest Cart Status 400 Payment method #28161

### ISSUE THREAD

**Issue by veltix** [magento/magento2#35054] opened 2022-02-02 23:41 UTC
### Preconditions (*)
Magento 2.4.3-p1

### Steps to reproduce (*)
Selecting language and then adding product to cart, then I go checkout and fill data and click place order then console log shows error 400 message

### Expected result (*)
It should place order like main language.

### Actual result (*)
If I click place order it loads and then console shows error.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-02-21 08:25
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Steps performed:
1. Installed Dutch Language Pack on Magento
2.  Admin - Stores - Configuration - Locale options - selected - Locale: Dutch (Netherlands) - Save config
3. Clear cache
4. Front end - Add product to cart - Checkout - Fill Details and Place Order using Check/Money Order
No issue: User is able to place order and no error in console logs
![image](https://user-images.githubusercontent.com/60198231/154916041-cd9ce590-1d86-456a-8776-248837846f9a.png)
@Veltix , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-03-07 06:45
Hi @Veltix ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-03-07 06:45 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3-p1
