### ISSUE TITLE
Unable to set 'country of manufacture' attribute to be comparable on frontend

### ISSUE THREAD

**Issue by tsmith1985** [magento/magento2#8870] opened 2017-03-13 20:17 UTC
Unable to set 'country of manufacture' attribute to be comparable on frontend.

### Preconditions

- Magento CE v2.1.5
- PHP v7.0.14
- MySQL v14.14 Distrib 5.7.16, for osx 10.12

### Steps to reproduce
1.  Log into Admin
2. Navigate to `Stores > Attributes > Product`
3. Click on `country_of_manufacture`.
4. Navigate to `Storefront Properties`.
5. Set `Comparable on Storefront` to `Yes`.
6. Open browser dev tools to view errors console.
7. Click `Save Attribute`.

### Expected result
1. Attribute is saved.

### Actual result
1. Attribute fails to save and error message is returned from server.

![attr-err-1](https://cloud.githubusercontent.com/assets/582928/23873457/53c5db26-07ef-11e7-96d6-f44d2a7cfc31.png)

<img width="1276" alt="attr-err-2" src="https://cloud.githubusercontent.com/assets/582928/23873463/5a488ae8-07ef-11e7-9e9f-49b9938eade6.png">

**Comment by martinhetschel** [comment] 2017-03-30 14:52
![image](https://cloud.githubusercontent.com/assets/17616012/24510357/4632e86e-1569-11e7-918d-0e8888430e31.png)
Same problem, but 503 error

**Comment by veloraven** [comment] 2017-06-29 13:07
I'm closing this issue as duplicate of #9153.
We already have  internal ticket MAGETWO-6971

**Closed as completed by veloraven** 2017-06-29 13:07 UTC
