### ISSUE TITLE
conflicting component dependencies on installing extensions in magento2

### ISSUE THREAD

**Issue by kitsupport** [magento/magento2#9386] opened 2017-04-25 06:17 UTC
### Preconditions

1.  Magento 2.1.6, php 7.0

### Steps to reproduce

1.  web setup wizard -> component manager -> Install an extension

### Expected result

1.  Need to get installed, and able to use

### Actual result

![image](https://cloud.githubusercontent.com/assets/27992174/25371050/42a1b66a-29ac-11e7-80e1-d89ccdd08bac.png)

## Problem
1. Can't install any extensions

**Comment by korostii** [comment] 2017-04-25 10:59
The error in question might be caused by a legitimate reason is is not necessarily symptomatic of a bug. It is likely to be caused by conflicting requirements of 3rd party modules you're using, however the information you provide is not enough to identify the exact cause. 
If you are looking for some help or an advice regarding setup or configuration please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/). 
The GitHub issue tracker is intended for tracking technical issues (read: "bugs") of Magento CE itself only.

**Comment by kitsupport** [comment] 2017-04-25 11:23
I can't add any extensions to my magento2.x projects, I tried a lot but no any extension works

**Comment by korostii** [comment] 2017-04-25 13:06
Well, either way you'll need to look closer into the details of the error yourself because the information you provided isn't enough to identify the cause remotely.

For example, you could check the network tab for the erroneous request as shown here http://dl3.joxi.net/drive/2016/03/31/0011/0609/774753/53/c624e5e3ef.jpg , the response tab then should contain the full error message and trace.

Have you tried following the [instructions from the docs](http://devdocs.magento.com/guides/v2.1/comp-mgr/trouble/cman/component-depend.html)? That would be a good starting point. There is also a number of other solutions suggested by community if you just try googling the error :)

On a side note, the GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE installed on a sufficient server environment aren't likely to get resolved in here.

**Comment by magento-engcom-team** [comment] 2017-10-11 19:17
@kitsupport, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-11 19:17 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid
