### ISSUE TITLE
Price indexers are not used on any product listing in entire framework

### ISSUE THREAD

**Issue by jakwinkler** [magento/magento2#30238] opened 2020-09-30 07:43 UTC
### Preconditions (*)

1. Any Magento 2 version, open source / commerce
2. This issue affects the most: bundle, grouped & configurable products. 
3. This is causing performance drop in entire framework. 

### Steps to reproduce (*)

1. You need to have blackFire in order to debug / verify this 
2. Disable full page & block html cache 
3. Visit any product page which has configurable / bundle / simple products
4. Profile product listing page using blackfire

### Expected result (*)

1. Product prices are fetched from price indexers
2. Fast load of any product listing

### Actual result (*)

1. Prices are calculated for every product in product listing
![image](https://user-images.githubusercontent.com/4256191/94656447-625bd180-0300-11eb-8113-6e925dac117c.png)
2. It is the same for any product listing: 
-- crosssell
-- upsell
-- related products
-- basically any product listing is affected

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

Severity: **S0**

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ilnytskyi** [comment] 2020-09-30 09:39
I think it's the same issue as I reported https://github.com/magento/magento2/issues/26850
and be careful with using price from index on composite products https://github.com/magento/magento2/issues/24953 but it mostly causes only issue with wrong products order when user sorts by price

**Comment by qsolutions-pl** [comment] 2020-09-30 09:45
@ilnytskyi it's not even related to sort by price, indexers are only used there.
The problem is that magento does not load prices from indexes at all on any product listing pages which results in very very slow catalog pages. In one of my projects this operation adds 8.0s in total for any category page which has visible products. 
Now imagine clearing the cache in such website.

**Comment by ilnytskyi** [comment] 2020-09-30 09:58
@qsolutions-pl 
Was your product collection customized somehow (by module or template)?
Normally it should use method
`\Magento\Catalog\Model\ResourceModel\Product\Collection::addPriceData`
that joins prices from index here
`\Magento\Catalog\Model\ResourceModel\Product\Collection::_productLimitationPrice`

And Magento 2 does load prices from index in this case but anyways recalculates them in
`\Magento\Catalog\Block\Product\ListProduct::getProductPrice`

**Comment by qsolutions-pl** [comment] 2020-09-30 10:03
Thats the problem, prices on product list should not be recalculated because it slows down entire performance.

**Comment by qsolutions-pl** [comment] 2020-09-30 10:35
When you sort by price, the issue is the same. 
![image](https://user-images.githubusercontent.com/4256191/94675095-7a8c1a80-0319-11eb-8bb2-5510c2e89339.png)

**Comment by sdzhepa** [comment] 2020-10-01 18:29
Hello @qsolutions-pl and @ihor-sviziev 

Thank you for the report and collaboration!

After verification, our developer confirm this issue
And also found that it is a Duplicate of https://github.com/magento/magento2/issues/26850
So I close this one in favor of already created, confirmed and triaged issue

**Closed as completed by sdzhepa** 2020-10-01 18:29 UTC
Labels: duplicate, Issue: Format is valid, Severity: S1, Triage: Performance, Progress: done
