### ISSUE TITLE
Unsetting product attribute (setData/unsetData) does not work

### ISSUE THREAD

**Issue by ivokund** [magento/magento2#8988] opened 2017-03-23 11:33 UTC
### Preconditions
1. Magento 2.1.5 CE
2. PHP 7.0.15

### Steps to reproduce
1. Log in to admin, go to product catalogue
2. Add a new product, sku: "TEST", "Special Price" (under Advanced Pricing): `12`
3. Save the product
4. Unset the special price in a console command by running:

```php
        $product = $this->productRepository->get('TEST', true);
        $product->unsetData('special_price');

        // also tried these, any of which work
        // $product->setData('special_price', '');
        // $product->setData('special_price', null);
        // $product->setCustomAttribute('special_price', null);

        // note that using an actual value like this works:
        // $product->setData('special_price', 22);

        $product->save();
```

### Expected result
1. I expect the "Special price" field under Advanced Pricing to be empty after reloading the product page in admin

### Actual result
1. Instead I see the old value `12` as the special price.

Please correct me if there is a "more correct" way to update product data.

**Comment by faisalmirza** [comment] 2017-06-02 11:54
When is this bug expected to be fixed? I am facing the same problem.

$product->setSpecialPrice(null) and $product->setSpecialPrice('') aren't an option either.

**Comment by Andrii-Deineha** [comment] 2017-08-07 08:04
@ivokund Hi, thanks for reporting this issue. Internal ticket was created MAGETWO-71377.

**Comment by magento-engcom-team** [comment] 2017-10-11 10:30
@ivokund, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-11 10:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Issue: Format is valid

**Comment by omniprolatam** [comment] 2018-03-22 20:00
I'm still facing the same issue in 2.2.1

**Comment by acampos1916** [comment] 2018-03-22 20:02
I'm still facing the same issue in 2.2.1

**Comment by leoquijano** [comment] 2018-05-02 10:29
There seems to be no commit reported here. For those looking, I found this in ```2.2``` branch: 14b9205f790b1cf86bb1dd2ccbcd1f6267ad6e22.

That creates an observer: ```Magento\Catalog\Observer\UnsetSpecialPrice```, that will set the field as '' when set to ```NULL```. This causes a strange behavior when trying to unset the value of an existing product (the row gets stored as ```NULL``` in the ```catalog_product_entity_decimal``` table).

```2.2-develop``` doesn't seem to have that observer, though, only ```2.2```.
