### ISSUE TITLE
"Create an Account" button of customer registration form is disabled when we submit the form with the different passwords in password and confirm password field

### ISSUE THREAD

**Issue by rahul-ks176** [magento/magento2#32091] opened 2021-02-10 13:14 UTC
### Preconditions (*)

1. Magento 2.4.1
2. PHP 7.3.20

### Steps to reproduce (*)

1. click on create an account link on the header at the home page.
2. fill the required details with different passwords in 'password' and 'confirm password' field of the form.
3. click on create an account button then the confirm password field highlight with the error msg and create an account button is disabled.
4. Fill the correct password in the 'confirm passowrd' field.
5. After fill the correct password but the 'create an account' button is not enabled again. This button disabled until we refresh/reload the page.

### Expected result (*)

1. 'create an account' button should be enabled again when we fill the correct password in confirm password field.

### Actual result (*)

1.'create an account' button disabled until we refresh the page.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
![customer-registration](https://user-images.githubusercontent.com/61263875/107514221-67def780-6bcf-11eb-8ac2-87f0deb276ea.png)

**Comment by engcom-Alfa** [comment] 2021-02-11 07:29
@magento give me 2.4-develop instance

**Comment by engcom-Alfa** [comment] 2021-02-11 07:47
Hi @rahul-ks176. Thank you for your report!
Unfortunately, we are not able to reproduce this issue on a fresh 2.4-develop.
Looks like the issue has already been fixed.

**Actual Result:** :heavy_check_mark:  The "create account" button is enabled and you can create a client

![Peek 2021-02-11 09-41](https://user-images.githubusercontent.com/51679138/107611938-c9de4200-6c4d-11eb-8dc9-5442a04eeb52.gif)

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2021-02-11 07:47 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.4.1

**Comment by rahul-ks176** [comment] 2021-02-11 07:52
Hi @engcom-Alfa <https://github.com/engcom-Alfa>,

Actually, this issue arises in the magento2.4.1 version only. In
magento2.4.0 it works correctly.
Can you please check it in a specific Magento 2.4.1 version?


------------------------------------
Thanks & Regards,
Rahul Rathour
Software Developer
Ksolves - https://www.ksolves.com
Email: rahul.rathour@ksolves.com
Contact: 8887846302

**Comment by hostep** [comment] 2021-03-15 20:19
@rahul-ks176, in case you still didn't find a solution by now, Magento released an official hotfix for this problem half a year ago:
1. Go to https://magento.com/tech-resources/download
2. Click on the 'Patches' link in the right hand menu
3. Find the patch labelled 'MC-38509'
4. Install it on your shop

Alternatively, you could also upgrade Magento to 2.4.2 which also contains this fix.

(and this is a duplicate of https://github.com/magento/magento2/issues/30513 btw)
