### ISSUE TITLE
Backend: Category products not keeping position when the page is changed

### ISSUE THREAD

**Issue by tzyganu** [magento/magento2#669] opened 2014-09-16 15:17 UTC
I'm adding a new category in the backend, select one product and fill in a position value. 
![before](http://i.imgur.com/ly31wZU.png)  
After doing any action on the grid (filter, sorting, change page) the product I previously selected is still selected but the position is empty.
In this example I change the sorting 

![after](http://i.imgur.com/MqSwo4b.png)

**Comment by vpelipenko** [comment] 2015-01-29 12:40
Internal ticket: MAGETWO-28813

**Comment by verklov** [comment] 2015-01-30 13:13
@tzyganu, after investigating within the team, we identified this rather a feature request rather than a bug. Thus we added additional requirement to the epic for enhanced grids that's in the backlog and closed the initial ticket.

We are also closing this issue now. Please watch the repository for updates. We will deploy the updated code once the epic is implemented.

**Comment by tzyganu** [comment] 2015-01-30 16:25
@verklov Oddly looking feature I might say :smile: https://geekwhisperin.files.wordpress.com/2009/09/bug-vs-feature.jpg

**Comment by verklov** [comment] 2015-01-30 16:51
Well, if the system was not designed to work in this way, we consider it a feature request, not a bug :-)

**Comment by orlangur** [comment] 2015-02-05 10:38
@tzyganu, not like current behavior seems to be logical, just a statement of inability to change this  behavior with a spot fix for old grid. The new grid is currently used for CMS pages and not used for category management page.

**Comment by vkorotun** [comment] 2016-08-04 06:38
@tzyganu Can we close this one? :)

**Comment by tzyganu** [comment] 2016-08-04 07:31
@vkorotun You can do what you want, it's your repo :smile: , but the problem still exists.  
Here is the products list in the add/edit category screen after I selected a product and filled in a position

![image](https://cloud.githubusercontent.com/assets/2447784/17393779/6dd9753c-5a2e-11e6-8e32-943deabcb72c.png)

And here it is after I sorted the list by name:  
![image](https://cloud.githubusercontent.com/assets/2447784/17393788/81b2fa24-5a2e-11e6-9b6e-bda3e3328b14.png)

As you can see, the position is gone.

**Comment by piotrekkaminski** [comment] 2016-08-30 19:03
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Backend-Category-products-not-keeping-position-when-the-page-is/idi-p/46191).

**Closed by piotrekkaminski** 2016-08-30 19:03 UTC
Labels: acknowledged, feature request, Frontend, moved_to_forums
