### ISSUE TITLE
Product Permission Settings changing

### ISSUE THREAD

**Issue by rod00003** [magento/magento2#38620] opened 2024-04-15 17:43 UTC
### Summary

We have experienced multiple product permissions changing on their own which has allowed customers to see and sometimes order items they are not authorized to purchase.

### Examples

The most recent example of this is is customer group Casey's should only be able to view the following items: XMO36, OTS2, PRO, HDSPR2, OTSSPR, and SPR. However, as of this morning, this group could also see CAFTOTE and XMOEH. 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2024-04-16 10:06
Hello @rod00003,

Thanks for the report and collaboration!

Please provide us with more information on this issue. 

It might be due to some third-party module. Please try to disable all the third-party modules and check if the issue is still occurring.

Also checking logs will help you in finding the actual issue.

Thanks

**Comment by engcom-Hotel** [comment] 2024-05-02 07:21
Dear @rod00003,

We've observed that there haven't been any updates on this issue for quite some time. Therefore, we're assuming it's been resolved and will be closing it. Feel free to open a new ticket or reopen this one if you require further assistance.

Regards

**Closed as completed by engcom-Hotel** 2024-05-02 07:21 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.x
