### ISSUE TITLE
paypal flow showing incorrect sub total amounts in adminhtml

### ISSUE THREAD

**Issue by dmcmillin** [magento/magento2#7238] opened 2016-10-29 00:28 UTC
### Preconditions

1. 2.2.0-dev
2. php 5.6
### Steps to reproduce

1. Order 80 products in cart. 
2. Then in checkout / mini cart remove said items. 
3. update
4. checkout with paypal payflow. 
### Expected result

1. Order should not show a weird subtotal 
### Actual result

1. order shows a weird sub total. Please See attached.

![your main website store order confirmation](https://cloud.githubusercontent.com/assets/13723980/19825846/a7737fb6-9d33-11e6-90a4-84cec39d2848.png)

My assumption is purely based on the end result and the steps might not be exact.The only thing I know is that the orders both had to do with large amounts of products. Initially the products were showing up on the backend as large amounts in the order. which ended up only being one or two products only. both have paypal payflow as the amount. 

Also, The grand total is correct.

**Comment by alena-marchenko** [comment] 2016-11-04 12:11
Hi @dmcmillin 

I was unable to reproduce the issue on the latest develop branch.
Please provide us with exact steps to reproduce the issue, product price, tax configuration, debug logs, that include request to PayPal for us to be able to investigate the issue further.

**Comment by YevSent** [comment] 2016-11-28 16:56
Hi, @dmcmillin. We are closing this issue because it hasn’t been updated in more than two weeks.

If you can still reproduce this issue, please, be free to reopen it.

**Closed as completed by YevSent** 2016-11-28 16:56 UTC
Labels: bug report, Progress: needs update, Component: Payment
