### ISSUE TITLE
Multishipping with CartFixed Salesrule and exluded SKU calculates the wrong discount amount

### ISSUE THREAD

**Issue by thehl** [magento/magento2#33331] opened 2021-06-24 09:06 UTC
### Preconditions (*)
1. Magento 2.4.2

### Steps to reproduce (*)
1. Create sales rule like screenshot:
![salesrule](https://user-images.githubusercontent.com/1321326/123233984-d6678680-d4da-11eb-951e-21249f5c9e2b.png)
2. Add two items to cart and one of them has to be the excluded one of the sales rule.
3. Enter coupon code BDAY. Now we receive 25€, which is correct.
![cart](https://user-images.githubusercontent.com/1321326/123234038-e3847580-d4da-11eb-9ba5-8399f6d0883d.png)
4. Click on 'Checkout with Multiple Addresses'
5. Use two different addresses
![addresses](https://user-images.githubusercontent.com/1321326/123234065-eb441a00-d4da-11eb-9d08-880968454640.png)
6. Proceed the checkout to the order review page

### Expected result (*)
1. Discount amount for the second delivery has to be 25€

### Actual result (*)
 ![reviewpage](https://user-images.githubusercontent.com/1321326/123234091-f0a16480-d4da-11eb-85b0-5bbb36b688c1.png)
1. Discount amount is 11,09€, which is not the full discount of the rule.

Severity: S1

For further details about the configuration, please find below:
https://github.com/magento/magento2/issues/33331#issuecomment-867532865

**Comment by engcom-November** [comment] 2021-06-24 10:42
Verified the issue on Magento 2.4-develop version and the issue is reproducible:

**Steps to reproduce:**
1. Magento Admin: Navigate to - Stores -> Attributes -> products -> Search for Sku -> Storefront Properties -> Use for Promo Rule Conditions – Set to Yes – Save Attribute
2. Navigate to Stores -> Configuration -> Sales – Multi shipping Settings - Yes and Save
3. Navigate to Marketing -> Cart Price rules - Add new Rule - Configure as per below screenshot and save
**Note: Make Sure to exclude sku under Actions**
![image](https://user-images.githubusercontent.com/60198231/123249612-c6659c00-d506-11eb-9296-037dc658c53b.png)
![image](https://user-images.githubusercontent.com/60198231/123249506-a59d4680-d506-11eb-9e4f-67859ce117ef.png)
4. Front end - Add two items to cart and one of them has to be the product which is excluded from sku.
5. Navigate to cart - Enter coupon code BDAY. Now we receive $25, which is correct.
6. Click on 'Checkout with Multiple Addresses'
7. Use 2 different addresses
8. Proceed the checkout to the order review page
**Issue:** Discount of $11.09 is getting applied to the product.
**Expected behavior:** $25 Discount should be applied on the other product
![image](https://user-images.githubusercontent.com/60198231/123249060-39bade00-d506-11eb-9300-fcf6a8124d02.png)
![image](https://user-images.githubusercontent.com/60198231/123249184-56efac80-d506-11eb-9a4d-cd6e19a63107.png)

**Comment by magento-engcom-team** [comment] 2021-07-01 07:23
:white_check_mark: Confirmed by @engcom-Hotel 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42761` were created

**Issue Available**: @engcom-Hotel, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mimou78** [comment] 2022-05-15 09:56
@magento give me 2.4-2 instance

**Comment by mimou78** [comment] 2022-05-15 09:58
@magento give me 2.4.2 instance

**Comment by mimou78** [comment] 2022-05-15 10:01
@magento I am working on this

**Comment by mimou78** [comment] 2022-05-15 10:01
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-14 09:38
Hi @thehl,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


![Review-Order-Magento-Commerce](https://github.com/user-attachments/assets/34fa8bce-0ec8-46fa-aa17-8a70b4db0643)


Discount amount for the second delivery is 25.

Hence we are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-14 09:38 UTC
Labels: Issue: Confirmed, Component: Multishipping, Component: SalesRule, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.2, Reproduced on 2.4.2, Area: Shipping
