### ISSUE TITLE
Order Status stuck in payment reviewin order grid

### ISSUE THREAD

**Issue by gcampedelli** [magento/magento2#25166] opened 2019-10-20 12:54 UTC
### Preconditions (*)

1. Custom Payment gateway is implemented.
2. Customer placed order
3. Customer didn't pay the payment gateway
4. Payment gateway cancelled the order

### Steps to reproduce (*)

1. Go to order grid
2. Order grid is cancelled. Open order. 
3. Get back to order grid. Order grid status is payment review, but inside order it shows cancelled
4 . Go inside order and click invoices
5. Cancel invoice, click on capture online
6. Order status shows processing
7. Go to credit memo. Unable to create credit memo
8. Order status goes back to cancelled
9 Order grid keep showing Payment Review despite de fact everywhere else, order is cancelled

### Expected result (*)

1. Cancelled invoices should not go back to payment review in order grid, showing different status that is displayed inside the order
2. Cancelled invoices should show cancelled in order grid

### Actual result (*)

1. I get order payment review status on a cancelled order

What might be wrong?

**Comment by annakoehler** [comment] 2019-10-21 08:52
@magento I am working on it

**Comment by NicoSiebler** [comment] 2019-10-21 08:54
@magento I am working on it.

**Comment by waldroot** [comment] 2019-10-21 09:05
@magento I am working on it

**Comment by engcom-Charlie** [comment] 2019-11-08 13:50
Hello @gcampedelli 

We are not able to reproduce this issue on a fresh Magento 2.3-develop by provided steps,
because in normal behavior if customer didn't pay the payment gateway Invoice will not be created and it is not possible to cancel invoice as you wrote in your steps:
![image](https://user-images.githubusercontent.com/51680850/68481152-1f53c400-023f-11ea-9078-ccdbaf449313.png)

Could you provide more clear steps if it possible?

**Comment by gcampedelli** [comment] 2019-11-08 15:36
Hello, I'm posting here more clear steps with images. So, here is a screenshot of Order Cancelled right after customer has placed the order. 

1- Custom Payment Gateway returns Order Cancelled. 
![canceled customer account](https://user-images.githubusercontent.com/7084395/68487657-3cc66500-0222-11ea-8be4-ba57ccdd3e90.jpg)

So, I went to Admin Orders grid and it shows - Payment Review. So here is a screenshot of order grid right after customer has placed order and didn't pay. 
![order-grid-after-place-order](https://user-images.githubusercontent.com/7084395/68487756-7008f400-0222-11ea-822d-c665148a8a05.png)

2- Then I open the order and it shows order cancelled in Information Section
![order-information-after-opening-order](https://user-images.githubusercontent.com/7084395/68487855-9d55a200-0222-11ea-913a-78deebd24f97.png)

3- The I go to see invoice grid inside the order and it shows invoice Pending
![Invoice-status](https://user-images.githubusercontent.com/7084395/68487915-c118e800-0222-11ea-9d6b-a7f7befa6f77.png). 

4- So I opened the invoice in order to cancel the invoice and order status is showing cancelled. 
![Invoice-Opened](https://user-images.githubusercontent.com/7084395/68488083-135a0900-0223-11ea-82cf-d6eee0e7d02c.png)

5- So I decide to cancel invoice because the order was not payed. And order status has changed to processing
![Invoice-cancelled](https://user-images.githubusercontent.com/7084395/68487999-e3ab0100-0222-11ea-9d16-04577a21f7cc.png)
![Order-status-after-cancel-invoice](https://user-images.githubusercontent.com/7084395/68488383-adba4c80-0223-11ea-9d1f-a73ebdf5c0a6.png)

6- I go to orders and try to see invoice tab to see if it show invoice cancelled, but in this tab invoice is back to pending. 
![Invoice-grid-inside-order-after-cancel](https://user-images.githubusercontent.com/7084395/68488209-50260000-0223-11ea-8304-73e0cb630837.png)

I open the invoice and I can't cancel it
![status-processing-inside-invoice-cant-cancel](https://user-images.githubusercontent.com/7084395/68488526-fd007d00-0223-11ea-84e4-ac06eb144c2d.png)

7- Then I go back to order grid it keeps Payment Review status
![Order-grid-after-cancel-invoice](https://user-images.githubusercontent.com/7084395/68488271-73e94600-0223-11ea-9165-7ddc47c2d8ca.png)

8- So I decide to cancel order using order grid dropdown by selecting this specific order.  So I cancel order and grid keeps in Payment Review forever. 
![then_i_cancel-orde](https://user-images.githubusercontent.com/7084395/68488407-bc086880-0223-11ea-8e36-d3d590a51638.png)

9- I open the order and status has changed to cancelled. 
![order-status-back-to-cancel](https://user-images.githubusercontent.com/7084395/68488466-d93d3700-0223-11ea-95be-1a530203b5e2.png)

10- But in order grid it keeps Payment Review
![grid-keeps-stuck-in-payment-review](https://user-images.githubusercontent.com/7084395/68488552-0a1d6c00-0224-11ea-9ffc-781ffa8c9f2c.png)

**Comment by engcom-Charlie** [comment] 2019-11-08 16:33
@gcampedelli thank you for contribution and collaboration!
What Magento version do you have?

**Comment by gcampedelli** [comment] 2019-11-08 17:47
Magento 2.3.2

**Comment by engcom-Charlie** [comment] 2019-11-11 11:36
Hello @gcampedelli 

I figured out this issue.

The bug is present only on versions prior to 2.3.2, because the bug calls the Cancel button in the Invoice grid. It should not be there because you cannot cancel Invoice as it is an accounting document and it should not be deleted. This order is already closed and it should not be restored.

And for example, in all Magento payment methods(included), an order will not be created if customer didn't pay the payment gateway.

In Magento 2.3.3, the button has already been removed and this behavior can no longer be called up.
![image](https://user-images.githubusercontent.com/51680850/68584044-3ab11000-0487-11ea-8d95-aaadfae727bd.png)

So i have to close this issue, because i can't reproduce it on a fresh Magento 2.3-develop & 2.3.3.

Thank you for contribution and collaboration!

**Closed as completed by engcom-Charlie** 2019-11-11 11:36 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Triage: Dev.Experience

**Comment by gcampedelli** [comment] 2019-12-11 16:28
I want to reopen issue because I don't accept your answer as valid. It is not a matter of Magento2 version. So I upgraded to version 2.3.3 and Cancel Button is right there for invoice in pending state. So again, I reproduced the matter of cancelling the invoice and order goes to processing status.

**Comment by gcampedelli** [comment] 2019-12-11 16:31
Cancel button does not exist when order is status processing 
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/7084395/70640262-75d76800-1c1a-11ea-9a5e-46cbad202499.png">
For order status cancelled there is a button to cancel invoice. If we use that, then order goes back to processing.
