### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lantran171** [magento/magento2#35466] opened 2022-05-12 15:25 UTC
### Preconditions (*)

1.  magento 2.3.2-p2
2.

### Steps to reproduce (*)

1. Sales > Invoices > Search > entered too many invoice numbers and got the error message : something went wrong with processing the default view and we have restored the filter to its original state. 
![image](https://user-images.githubusercontent.com/105444431/168111062-9d2c4d36-bc10-41bd-81b1-2a2082a4e102.png)

### Expected result (*)

I want to be able to search for invoices again because it is stuck on the same page not loading or letting me clear anything. 

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-05-16 05:16
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-05-16 06:00
Hi @lantran171,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but could not able to reproduce the issue.
![image](https://user-images.githubusercontent.com/60198231/168528696-6f83510f-04e7-496c-921a-e8d477d089af.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by hostep** [comment] 2022-05-16 15:30
This issue is being reported every few months and I've seen it happening myself. But unfortunately engcom squad doesn't get correct steps to reproduce because it's hard to figure those out.

But there is definitely a bug here with trying to reset the grid to its default filters.

@engcom-November: the way you should try to reproduce it, is by trying to get the grid to crash by setting invalid filters somehow (maybe by manually changing some things in the `ui_bookmarks` database table).
In theory the grid's filters should reset themselves when the current filters give an error (because that's what the error message says: `we have restored the filter to its original state`). But this resetting often fails and then people get stuck on that grid until they create a different admin user or until they manually fix things in the `ui_bookmarks` database table. Which is far from user friendly.

**Comment by engcom-November** [comment] 2022-05-18 12:43
Verified the issue again on Magento 2.4-develop branch and the issue is reproducible by following below steps:
1. Admin - Sales - Invoices - Applied Filter with large test data
Invoices page is crashed and unable to reload the page/ clear filter/ nor reuse the page anymore.
![image](https://user-images.githubusercontent.com/60198231/169041243-1a804ba1-8075-4b25-8bcc-5a2bf1daa2bf.png)

**Comment by oneserv-heuser** [comment] 2022-07-19 13:41
@engcom-November Will this be available as patch via the quality-patches Tool and in Magento 2.4.5?
For us this is definitly an issue with the highest priority as you can read in #35759

**Comment by engcom-Delta** [comment] 2024-10-08 04:24
Hi @lantran171  @hostep ,

Thanks for your reporting and collaboration.
We have re-verified the issue in 2.4-develop instance , but we are unable to reproduce the issue. Kindly refer the screenshots.

**Steps to reproduce**

1. Sales > Invoices > Search > entered too many invoice numbers and got the error message
2. Click on Clear, Observe user is able to clear the search keyword and refresh the page.

https://github.com/user-attachments/assets/9fd51b59-216c-4efd-8a06-576fb05531d8


Can you please re-verify and confirm if you are still facing the issue.

Thanks.

**Comment by engcom-Delta** [comment] 2024-10-21 13:24
Hi @lantran171 ,

We have noticed that this issue has not been updated since long time.
Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Delta** 2024-10-21 13:24 UTC
Labels: Component: Filter, Reproduced on 2.4.x, Priority: P2, Progress: done, Issue: needs update, Area: Admin UI, Reported on 2.4.3-p2
