### ISSUE TITLE
Adding products with rest doesn't work when indexes are set to update by schedule

### ISSUE THREAD

**Issue by rklerck** [magento/magento2#1833] opened 2015-09-10 09:42 UTC
We're adding our products with Rest. There was already one bug with it: https://github.com/magento/magento2/issues/1720

But now there is another one. We set our indexes to update by schedule (config is default). When we add a product with rest, and enable it in backend. It's not visible in the frontend. In the backend everything looks fine. Even when we manually rebuild index (magento indexer:reindex), the product isn't visible.

When we do the same routine with indexes set to on update, it works like expected, except for the bug mentioned earlier.

**Comment by choukalos** [comment] 2015-10-02 21:10
Hi @rklerck when you're doing index update by schedule what happens when the scheduled indexing happens?  Does the product then show up on the front end ( that would be expected behavior )?

**Comment by rklerck** [comment] 2015-10-19 14:08
It indeed shows up on the front end now after running: "indexer:reindex". Not sure how the whole cron mechanism works, but that's not a bug of course. 

It looks like #1720 isn't a problem anymore, after reindexing manually.

**Comment by choukalos** [comment] 2015-10-20 14:54
@rklerck the cron effectively needs to run 2 times to actually update.  first time it runs it grabs a # of tasks and converts those tasks to actions that it queues up for the next run.  When it runs the 2nd time it processes those actions.

Since you've confirmed we're working correctly I'm going to close this item.  I look forward to understanding how the change in indexing strategy impacts #1823 .

Thanks!

**Closed by choukalos** 2015-10-20 14:54 UTC
Labels: improvement, MX, question
