### ISSUE TITLE
Icon on a page

### ISSUE THREAD

**Issue by laurazacatrus** [magento/magento2#35087] opened 2022-02-11 10:25 UTC
Magento ver. 2.4.3-p1

Bug: If you place an icon on a page, for example: 🎉📆🎁💙, you can't edit the page and the site crashes.

Steps
--> 
1. Content > Page > New Page 
2. Edit with page Builder
3. To select Row > Elements > Text 
4. Put an icon 🎉📆🎁💙
5. The site crashes and the site deletes everything.

### Expected result (*)
1. I want to place icons on a page

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._

**Comment by engcom-Delta** [comment] 2022-02-18 13:24
Hi @laurazacatrus ,
Thank you for reporting the issue.We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.


**Steps performed:**

1. Content > Page > New Page
2. Edit with page Builder	
3. To select Row > Elements > Text
4. Put an icon 

As shown in the screenshot
![icon1](https://user-images.githubusercontent.com/51681379/154690488-618c21d2-63e9-4fda-a2f3-31827662a5ea.png)

Note:we have put both svg and ico icon image too so its giving error as shown in screenshot
![ico](https://user-images.githubusercontent.com/51681379/154690628-5dbdb10f-c256-4be1-87f6-5d11fd5223df.png)

Result:
Able to place icon on a page

![icon image](https://user-images.githubusercontent.com/51681379/154690687-fcc8b0bb-3cfd-4e8f-b08c-d0e39827b2c6.png)


Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

**Comment by engcom-Delta** [comment] 2022-02-21 14:35
hi@ laurazacatrus

Thank you for reporting the issue.

We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

we have used  https://es.piliapp.com/facebook-symbols/ as mentioned above 
getting error as shown in screenshot
![iconfinal](https://user-images.githubusercontent.com/51681379/154975392-02e2f1d5-6384-41e9-9621-f917f7f9266e.png)
Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.

**Comment by engcom-November** [comment] 2022-02-22 09:24
hi@ laurazacatrus

Thank you for reporting the issue.

We tried to reproduce the issue on Magento 2.4-develop branch but the issue is not reproducible.

we have used  https://es.piliapp.com/facebook-symbols/ as mentioned above 
But getting error as shown in screenshot

![image](https://user-images.githubusercontent.com/60198231/155102109-8bafe03c-c6a6-4e48-95f5-0a992a10db37.png)



Please let me know if this is exactly what your issue was or if there is some more configuration required from my end. Will update accordingly.


Thanks

**Comment by engcom-November** [comment] 2022-03-08 05:21
Hi @laurazacatrus ,
We are closing this issue as there has been no latest update on the same
Thank you.

**Closed as completed by engcom-November** 2022-03-08 05:21 UTC
Labels: Issue: needs update, Area: Content
