### ISSUE TITLE
Paypal payment option within Braintree is failing to connect to paypal 

### ISSUE THREAD

**Issue by cckassis** [magento/magento2#10873] opened 2017-09-13 16:11 UTC
I have connected PayPal to my merchant account/payment gateway Braintree in Magento 2. When proceeding with PayPal payment option, it is failing to connect to PayPal giving me this message: 
"Sorry we cannot connect to PayPal. Please try again in a few mintues" (screen shot attached) [screen shot 2017-09-13 at 11 59 26 am](https://user-images.githubusercontent.com/31739622/30387645-2791d3c6-987b-11e7-930b-019c765f2bae.png)

### Preconditions
Magento 2.1.5
When i reached out to Braintree, i was given the below explanation: 

 Magento is using a custom integration of PayPal - the following code is lifted directly from your checkout page:
            config.paypal = {
                container: 'paypal-container',
                singleUse: !isActiveVaultEnabler,
                headless: true,
                amount: this.grandTotalAmount,
                currency: totals['base_currency_code'],
                locale: this.getLocale(),
                enableShippingAddress: true

This is designed to be combined with paypal.initAuthFlow() method, via an on-click action/event listener, to prevent pop-up blockers from interfering with the launch of the window.

However, Magento is attempting to launch the paypal.initAuthFlow() method from within an independent function, additionalValidators.validate(), which appears to check that all obligatory fields within the page are filled:
        payWithPayPal: function () {
            if (additionalValidators.validate()) {
                Braintree.checkout.paypal.initAuthFlow();
            }
        }

In less code-based terms, a custom PayPal integration should be launched by the user taking some sort of action, so pop-up blockers recognize the PayPal window is legitimate. Because your integration is being launched by an independent action - the validation of the fields on the page - pop-up blockers may consider it problematic, and interfere with the checkout. 

### Steps to reproduce
1. On the last page of checkout, Select PayPal as payment option
2. Click on Proceed with PayPal
3. Error is occurring

### Expected result
1. User to be connected to PayPal for the payment to go through.

### Actual result
1. System is failing to connect to PayPal 
2. [screen shot 2017-09-13 at 11 59 26 am](https://user-images.githubusercontent.com/31739622/30387645-2791d3c6-987b-11e7-930b-019c765f2bae.png)

**Comment by magento-engcom-team** [comment] 2017-09-21 11:02
@cckassis thank you for your report. Please specify the exact version of Magento or the tagged build you installed.

**Comment by cckassis** [comment] 2017-09-21 13:23
@magento-engcom-team Thanks for your reply. I am on ver 2.1.5. The problem is still unresolved!

**Comment by okorshenko** [comment] 2017-09-21 15:13
@ccasciotti thank you for update. Unfortunately we can not update 2.1.5, but we will check 2.1.9 and 2.2.0

**Comment by magento-engcom-team** [comment] 2017-09-27 12:55
Unfortunately we can't reproduce the issue with version  2.1.9. Could you provide us screenshots as you configure you Braintree payment methods if the issue exists on 2.1.9 version0?
Example of our settings are provided and with the setting all works well with 2.1.9:
![braintree3](https://user-images.githubusercontent.com/31669971/30914356-1c2c4b5c-a39c-11e7-88c5-e7f2fec63d1f.png)
![braintree2](https://user-images.githubusercontent.com/31669971/30914357-1c2dea7a-a39c-11e7-8c6a-5d7b517d94f7.png)
![braintree1](https://user-images.githubusercontent.com/31669971/30914358-1c351b38-a39c-11e7-8a9d-d716a0746382.png)

**Comment by ccasciotti** [comment] 2017-09-27 13:06
@okorshenko @magento-engcom-team sorry but you've asked to the wrong person, I think you should ask to @cckassis

**Comment by cckassis** [comment] 2017-09-27 20:06
@okorshenko @magento-engcom-team Hi there, I haven't updated my Magento version yet so I don't know if the issue persists in 2.1.9/2.2.0. Since the issue wasn't solved, I have for now integrated PayPal outside of Braintree. Here are the screenshots for reference:

![screen shot 2017-09-27 at 4 02 24 pm](https://user-images.githubusercontent.com/31739622/30935082-8e377cc0-a39d-11e7-9fc6-dfb53ebcd7b6.png)

![screen shot 2017-09-27 at 4 02 39 pm](https://user-images.githubusercontent.com/31739622/30935102-a59c737a-a39d-11e7-9553-d26cf5c41069.png)

![screen shot 2017-09-27 at 4 03 10 pm](https://user-images.githubusercontent.com/31739622/30935123-b147506e-a39d-11e7-90c5-02fa19f6702b.png)

![screen shot 2017-09-27 at 4 02 55 pm](https://user-images.githubusercontent.com/31739622/30935136-be15c654-a39d-11e7-87a0-c8235078b5f4.png)

![screen shot 2017-09-27 at 4 03 25 pm](https://user-images.githubusercontent.com/31739622/30935141-c382abfc-a39d-11e7-9f7c-a8134989f108.png)

**Comment by magento-engcom-team** [comment] 2017-10-11 16:49
Hi @cckassis we are closing this issue for now. Looks like the issue already fixed in 2.1.9. We can not patch 2.1.5 separately.

**Closed as completed by magento-engcom-team** 2017-10-11 16:49 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by gulatipriyanka** [comment] 2018-12-15 12:19
@magento-engcom-team We are using magento version 2.2.7. When we checkout with paypal, popup is blocked on chrome browser. We click on continue button, it asks to unblock popup and when we unblock popup and again click on continue button. Continue button does not works. We need to close that paypal popup window and go to checkout page and again click on continue to paypal button then popup window will show up which is very confusing for customers. Many customers are complaining that they are not able to checkout with paypal and lots of orders affected due to this. 

![chrome-paypal-block-issue](https://user-images.githubusercontent.com/22371007/50043089-1b9dd880-0094-11e9-8241-40c42264b407.png)

The above issue is still coming on version 2.2.7.

**Comment by gulatipriyanka** [comment] 2018-12-15 13:33
Any help would be appreciated??
