### ISSUE TITLE
Unable to apply data patch Magento\Catalog\Setup\Patch\Data\UpdateMultiselectAttributesBackendTypes

### ISSUE THREAD

**Issue by seo-master** [magento/magento2#36412] opened 2022-11-03 08:21 UTC
### Preconditions and environment

- Magento version 2.4.3
- I have migrated version of Magento. Migration was made on april M1.9.4.5 to M2.3.5, after that Magento has upgraded successfully two times 2.3.5 -> 2.4.2 and 2.4.2 -> 2.4.3

### Steps to reproduce

1. Composer upgrade from 2.4.3 to 2.4.5
2. php bin/magento setup:upgrade

### Expected result

1. Successful upgrade

### Actual result

Module 'Magento_EavGraphQl':
Module 'Magento_Search':
Module 'Magento_CatalogImportExport':
Module 'Magento_Catalog':
Enabling caches:
Current status:
layout: 1
block_html: 1
full_page: 1
Unable to apply data patch Magento\Catalog\Setup\Patch\Data\UpdateMultiselectAttributesBackendTypes for module Magento_Catalog. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '510-142-0' for key 'catalog_product_entity_text.CATALOG_PRODUCT_ENTITY_TEXT_ENTITY_ID_ATTRIBUTE_ID_STORE_ID', query was: INSERT  INTO `catalog_product_entity_text` (`value_id`,`attribute_id`,`store_id`,`entity_id`,`value`) VALUES (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?, ?), (?, ?, ?, ?,

### Additional information

I have removed all multiselect attributes from all attribute sets, after that magento has upgraded successfully.

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jsdupuis** [comment] 2022-11-14 13:13
Getting the same error when upgrading from Magento 2.4.2 -> 2.4.4 (Open Source)

**Comment by jsdupuis** [comment] 2022-11-14 16:13
I managed to fix the problem by manually deleting rows in catalog_product_entity_text.

All the rows that are fully identical between catalog_product_entity_varchar and catalog_product_entity_text need to be deleted in the later one. Then run setup:upgrade and all the multiselect attributes will be copied from varchar to text.

The pain is to compare the data of both tables. Not an SQL expert so had to use concatenate and vlookups in Excel.

**Comment by engcom-November** [comment] 2022-11-23 10:54
Hi @seo-master ,
Thank you for reporting and collaboration. Verified the issue by upgrading from 2.4.3 to 2.4.5 with below steps but could not reproduce the issue.
Steps performed:
1. Installed Magento 2.4.3 Project-community-edition using  `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.3`
2. Created categories and few products with attributes.
3. Upgraded to Magento 2.4.5 Project-community-edition as per Upgrade [guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
4.php bin/magento setup:upgrade
No issue: Upgrade successful.
Both Admin login and frontend are working fine
Kindly check Magento system [requirements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and if any 3rd party modules / extensions enabled. Elaborate steps if the issue is still reproducible.
Thank you.

**Comment by jsdupuis** [comment] 2022-11-23 11:27
If I may add a theory: our Magento installation was migrated from Magento 1 to Magento 2 all the way to 2.4.4. I believe that multiselect attributes used to be stored as text, then they were migrated to be varchar on a subsequent version, then finally back to be stored as text in 2.4.4. Which explains duplicate entries in CATALOG_PRODUCT_ENTITY_TEXT and CATALOG_PRODUCT_ENTITY_VARCHAR. This issue might not affect brand new installations, only ones that have gone through multiple upgrades.

**Comment by engcom-November** [comment] 2022-12-02 17:06
Hi @jsdupuis ,
Verified the issue again with below steps performed but unable to reproduce the issue with below steps performed.
Unable to install Magento 1.x version. Installed Magento 2.3.7 Project-community-edition and upgraded to Magento 2.4.2. Upgraded Magento instance again to 2.4.3 and then to Magento 2.4.5. Upgraded completed successfully.

**Comment by engcom-November** [comment] 2022-12-16 10:09
Hi @jsdupuis ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-16 10:09 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
