### ISSUE TITLE
Product in cart's removed after reorder multiple times

### ISSUE THREAD

**Issue by khangtran2404** [magento/magento2#38059] opened 2023-10-10 02:59 UTC
### Preconditions and environment

- Magento version: 2.4.5-p1
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Navigate to Admin -> Catalog -> Product -> Choose a product -> Advanced Inventory -> set Maximum Qty Allowed in Shopping Cart to a small number -> Save product.
2. Navigate to Shop page -> Login -> Order history page -> Reorder the order which contains the above product
3. Reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number 

### Expected result

- Navigates to Shopping cart page
- Keep all the cart items as before the last click
- Show error message ( Ex: Reaches the Maximum Qty Allowed in Shopping Cart )

### Actual result

- Navigates to Shopping cart page
- The product that reaches the Maximum Qty Allowed in Shopping Cart will be removed
- Show error message ( Ex: Reaches the Maximum Qty Allowed in Shopping Cart )

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-10-10 11:48
Hi @khangtran2404,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Navigate to Admin -> Catalog -> Product -> Choose a product -> Advanced Inventory -> set Maximum Qty Allowed in Shopping Cart to a small number -> Save product.
- Navigate to Shop page -> Login -> Order history page -> Reorder the order which contains the above product
- Reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number


<img width="1103" alt="Screenshot 2023-10-10 at 2 45 39 PM" src="https://github.com/magento/magento2/assets/51680745/aa741b55-c128-451b-9138-53d522fc7c5e">



<img width="1434" alt="Screenshot 2023-10-10 at 2 45 13 PM" src="https://github.com/magento/magento2/assets/51680745/83f6e0d5-29a8-4929-8b2d-c4f1874c3e2f">



It is navigating to Shopping cart and also it is showing error message as **The requested qty exceeds the maximum qty allowed in shopping cart**


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by khangtran2404** [comment] 2023-10-11 03:20
https://github.com/magento/magento2/assets/72378291/e9861646-1d1c-4f9c-b656-41791f1dbd59

Hello, 
I have checked again and still got the same error as in the video. Could you find attached the video and follow its steps?
Thank you!

**Comment by engcom-Bravo** [comment] 2023-10-11 09:33
Hi @khangtran2404,

Thanks for your update.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the attached video.

**Steps to reproduce**

- Navigate to Admin -> Catalog -> Product -> Choose a product -> Advanced Inventory -> set Maximum Qty Allowed in Shopping Cart to a small number -> Save product.
- Navigate to Shop page -> Login -> Order history page -> Reorder the order which contains the above product
- Reorder this order until the quantity of the above product reaches the Maximum Qty Allowed in Shopping Cart number





https://github.com/magento/magento2/assets/51680745/699c18ca-bab0-4531-825d-35f529da2806





After doing multiple reorder the product got deleted from the cart.Error is as expected since we are adding more than maximum quantity but products should be there in the cart.

Hence Confirming the issue.

Thanks.

**Comment by BeggiNN** [comment] 2023-10-13 05:50
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2023-12-06 06:01
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-05-14 07:32
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-09-24 05:53
Hi @khangtran2404,

Thanks for your reporting and collaboration.

As per this comment https://github.com/magento/magento2/pull/38069#pullrequestreview-2055009141  issue is no more reproducible.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-09-24 05:53 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done, Area: Order, Reported on 2.4.5-p1
