### ISSUE TITLE
M2.4.2 Customer Name Prefixes Showing as numbers not Mr., Mrs., Ms. etc

### ISSUE THREAD

**Issue by likearocket** [magento/magento2#32177] opened 2021-02-15 16:48 UTC
After upgrading Magento from 2.4.1 to 2.4.2, customer orders are coming through with numbers instead of Name Prefixes such as Mr., Mrs. etc. No settings have been changed since the upgrade.

### Preconditions (*)

1. Magento CE 2.4.2
2. Magento 2.4-develop

### Steps to reproduce (*)

1. Enable customer prefix
![image](https://user-images.githubusercontent.com/51681379/108034395-1fe02a80-703e-11eb-84c6-1af90f43020e.png)
2. Go to Sales->Orders
3. Click Create New Order
4. Click Create New Customer
5. Fill required fields and choose **Name Prefix** from dropdown
6. Click Submit Order

### Expected result (*)

1. The name will show in the order summary page as [Name Prefix] [First Name] [Surname]

### Actual result (*)

1. The name shows as [Number] [First Name] [Surname]. This also replicated in the transactional emails.
![1](https://user-images.githubusercontent.com/79103583/107973723-7b160c80-6fad-11eb-8536-297456446107.jpg)
![image](https://user-images.githubusercontent.com/51681379/108034218-df80ac80-703d-11eb-99cb-55066a80263e.png)
![image](https://user-images.githubusercontent.com/51681379/108034774-b1e83300-703e-11eb-9081-106c04c933aa.png)

**Comment by magento-engcom-team** [comment] 2021-02-16 08:08
:white_check_mark: Confirmed by @engcom-Delta 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-40899` were created

**Issue Available**: @engcom-Delta, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ashtonsax** [comment] 2021-02-18 20:21
@magento I am working on it

**Comment by ashtonsax** [comment] 2021-02-18 20:21
@magento add to contributors team

**Comment by ashtonsax** [comment] 2021-02-18 20:21
@magento I am working on it

**Comment by codedge** [comment] 2021-02-21 15:00
It seems this does only happen for guest orders. The customer prefix is saved as integer inside the `prefix` column in `sales_orders_address` table instead as string.

![image](https://user-images.githubusercontent.com/4409904/108628937-e2c0d180-745d-11eb-8e48-89e3999f1d6d.png)

**Comment by Sental** [comment] 2021-03-09 16:26
This issue is caused by some questionable logic in `Magento\Checkout\Block\Checkout\LayoutProcessor` that was exposed by the change to `Magento\Customer\Model\Options` in #28238.

In the `convertElementsToSelect()` function of the `LayoutProcessor` it assumes the array key has relevance to the option and the content that it's getting ready to render. Previously to 2.4.2 the `Options` file created an array key that matched the array value so this wasn't a problem. Since the change in 2.4.2 to solve another issue the array key is now an integer element id that has no relevance to the display or function of the checkout process. The solution looks to be assigning the value from the `$options` array in the function to both the value & the label. So that the nested foreach inside that function would become as follows.

`foreach ($options as $key => $value) {
       $elements[$code]['options'][] = [
               'value' => $value,
                'label' => $value,
       ];
 }`

**Comment by stephansteiner** [comment] 2021-03-26 10:26
Any news on this? This is a very annoying bug and there seems to be no working  patch around

**Comment by Sental** [comment] 2021-03-26 11:02
This is the patch we've used for the issue on the frontend of our magento stores as a quick fix, until a full range solution can be written and incorporated into Magento itself.
[0001-prefix-array-element-index-issue-bugfix.patch.txt](https://github.com/magento/magento2/files/6211266/0001-prefix-array-element-index-issue-bugfix.patch.txt)

**Comment by nobodyMO** [comment] 2021-04-30 08:29
I'm surprised that anyone is using version 2.4.2 productively, when it can't even send mails to customers with the correct form of address. 
Thanks for the fix for the frontend. Since we very often have to correct the addresses of the customers so that we can automatically create the labels for the packages, we unfortunately also need a solution for the backend. That's why I tried to solve the problem in the backend by myself.
I have adapted the following file for this purpose:
`/module-sales/Block/Adminhtml/Order/Create/Form/Address.php`.

In the _prepareForm function, I replaced the retrieved simple array $prefixOptions with one that also has the Value as an index. With this, the address change in the backend works again for now. 

```
 if ($prefixElement) {
            $prefixOptions = $this->options->getNamePrefixOptions($this->getStore());
            if (!empty($prefixOptions)) {
				// fix for prefix value
				$prefixOptions2=array ();
				foreach ($prefixOptions as $prefix) {
					$prefixOptions2[$prefix]=$prefix;
				}
                $fieldset->removeField($prefixElement->getId());
                $prefixField = $fieldset->addField($prefixElement->getId(), 'select', $prefixElement->getData(), '^');
                $prefixField->setValues($prefixOptions2);
                if ($this->getAddressId()) {
                    $prefixField->addElementValues($this->getAddress()->getPrefix());
                }
            }
       }
```

**Comment by DanBeckett** [comment] 2021-05-19 08:50
We've written a small plugin to intercept the Order Address Model and check the prefix against  `Magento\Customer\Model\Options::getNamePrefixOptions()` as it's loaded. If the prefix appears as a key in the getNamePrefixOptions array (the case when it's an integer), the prefix in the Model is updated to use the matching value from the options array. [https://github.com/DanBeckett/door4-customer-prefix-patch](url)

**Comment by Alainvdz99** [comment] 2021-05-28 08:17
What is the status of this issue?

**Comment by antonio-valdez-arce** [comment] 2021-06-01 09:33
Hello, is there any update on this issue? Thanks.

**Comment by Alainvdz99** [comment] 2021-06-01 14:31
@antonio-valdez-arce Still not working in 2.4.2-p1. I used the solution of @DanBeckett for the admin and the emails and I used the patch from @Sental for in the frontend.

**Comment by antonio-valdez-arce** [comment] 2021-06-01 15:43
> @antonio-valdez-arce Still not working in 2.4.2-p1. I used the solution of @DanBeckett for the admin and the emails and I used the patch from @Sental for in the frontend.

ok, thank you. I will try it.

**Comment by hannes011** [comment] 2021-06-21 16:26
here @Sental s link again: https://github.com/DanBeckett/door4-customer-prefix-patch  (link was broken)

**Comment by marvinhinz** [comment] 2021-07-20 10:04
this error happens to us on 2.4.2-p1, but the fix from @Sental doesnt work somehow

![image](https://user-images.githubusercontent.com/35603466/126305436-f90d49e6-2964-4328-8fc4-3d7e50da3db3.png)

**Comment by Sental** [comment] 2021-07-20 10:37
> this error happens to us on 2.4.2-p1, but the fix from @Sental doesnt work somehow
> edit: door4/customerprefixpatch module works 👍🏼
> 
> ![image](https://user-images.githubusercontent.com/35603466/126305436-f90d49e6-2964-4328-8fc4-3d7e50da3db3.png)

In that case you were dealing with a prefix that had already been saved with the incorrect data which the door4 patch fixes. The patch I've made available corrects fields when new addresses are created/saved and tge error could have occurred. If you have corrupted data in ypur database you need both patches.

**Comment by bunnyofficiial** [comment] 2021-12-08 10:44
I have created a fix for this and this fix works for me.

https://github.com/bunnyofficiial/Customerprefixchange

**Comment by homecoded** [comment] 2021-12-08 13:13
I tried the solution by bunnyofficiial, DanBecket and Sental. For me only Sental's solution worked via core patch. It's also the most elegant as it gets obsolete as soon as there is a fix in the core (because then the patch cannot be applied anymore).

**Comment by mad-develop** [comment] 2022-03-04 14:00
I recently stumbled on this issue. As @Sental mentioned the issue was introduced with #28238. 

The issue #32066 seems also to be related. After the change to nummeric array index in the prefix options, the current value is no longer found and get added.

My current fix is a composer patch, reverting the change from #28238. 
I'm not done testing, but so far frontend issues seems to be fixed.
I am also not sure, what the intentions the prefix options changes had. But clearly there where some parts of that didn't get changed to support numeric index for the customer prefix array.

Composer patch for "magento/module-customer":
[github-issue-32177.diff.txt](https://github.com/magento/magento2/files/8186338/github-issue-32177.diff.txt)

**Comment by BorisovskiP** [comment] 2022-05-02 09:20
This issue is still reproducible on Magento 2.4.4.

**Comment by Beraa995** [comment] 2022-08-30 09:26
I made a fix which works with no problems for me.

I created after plugin on \Magento\Customer\Model\Options::getNamePrefixOptions method. It looks like this:

`
<?php
declare(strict_types=1);
namespace Vendor\Module\Plugin;

use Magento\Customer\Model\Options;

class ChangePrefixOptionKeys
{
    /**
     * @param Options $subject
     * @param array|bool $result
     * @return array|bool
     */
    public function afterGetNamePrefixOptions(Options $subject, array|bool $result): array|bool
    {
        if (!is_array($result)) {
            return $result;
        }

        $newPrefixArray = [];
        foreach ($result as $prefixValue) {
            $newPrefixArray[$prefixValue] = $prefixValue;
        }

        return $newPrefixArray;
    }
}

`

**Comment by homecoded** [comment] 2022-08-30 10:21
@Beraa995 Pretty cool! Thanks for sharing. It looks like you implemented your own "array_unique". I think you could reduce some lines of code by using the native array_unique-function.

**Comment by hostep** [comment] 2022-08-30 11:06
https://github.com/magento/magento2/pull/36003 could maybe also fix it?

**Comment by Sental** [comment] 2022-08-30 11:09
The pull request https://github.com/magento/magento2/pull/35060 has also been raised to fix this issue.

**Comment by kazimck** [comment] 2022-09-20 05:45
The issue is reproducing in M2.4.3. Any solution for this?

**Comment by lbajsarowicz** [comment] 2022-09-20 13:01
PR with the fix: https://github.com/magento/magento2/pull/36003
Composer Patch: https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/36003.diff
Instructions: https://devdocs.magento.com/guides/v2.4/comp-mgr/patching/composer.html

**Closed as completed** 2022-09-24 13:37 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P2, Progress: done

**Comment by vutrankien** [comment] 2022-10-30 17:18
Quick solution : edit this file : /vendor/magento/module-customer/Model/Options.php
Inline 104 update code : 
`$result[] = $this->escaper->escapeHtml(trim($value)) ?: ' ';`
to :
`$result[$value] = $this->escaper->escapeHtml(trim($value)) ?: ' ';`

**Comment by stefanfr** [comment] 2023-05-30 14:55
Well this is back again, if you change an order adres via admin the value is 0,1,2. @vutrankien's fix still applies

**Comment by oskars-elksnitis** [comment] 2023-06-02 06:15
@Sental Just ran into this issue on M2.4.4 when a new address is created in the checkout

**Comment by stefanfr** [comment] 2023-07-20 14:14
@Sental Didn't see your message, as @oskars-elksnitis said it is back since 2.4.4 and onwards, latest 2.4.6-p1 still has this issue:
```
foreach ($options as $value) {
    $result[] = $this->escaper->escapeHtml(trim(__($value))) ?: ' ';
}
```
