### ISSUE TITLE
Cannot export files

### ISSUE THREAD

**Issue by AmandaTamlm** [magento/magento2#37443] opened 2023-04-28 08:43 UTC
### Preconditions and environment

- Magento version  2.4.2
- After place the command to export inventory data, the file falied in the download progress.  The system only show a message as below:

The path "/var/www/html/var/export/stock_sources_20230428_070018.csv" is not writable.

### Steps to reproduce

1. go into our Magento dashboard
2. find System for exporting some needed file.
3. Choosing to export "Stock Sources" or any others.  There is a message  "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file"
4. Afterwards, system notice us with this message:  "Your export file is ready.  You can pick up your file at export main page"
5. Then go back to Export Main Page to click the download button, the system shows a message " The path "/var/www/html/var/export/stock_sources_20230428_070018.csv" is not writable. "

### Expected result

download  the export files

### Actual result

cannot download the export files

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-04-28 13:00
HI @AmandaTamlm,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


**Steps to reproduce**


- go into our Magento dashboard
- find System for exporting some needed file.
- Choosing to export "Stock Sources" or any others. There is a message "Message is added to queue, wait to get your file soon. Make sure your cron job is running to export the file"
- Afterwards, system notice us with this message: "Your export file is ready. You can pick up your file at export main page"
- Then go back to Export Main Page to click the download button,




https://user-images.githubusercontent.com/51680745/235122327-578e820f-18f1-438d-86c1-1a1c25b20479.mov



We are able to download the export files.


Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-09 06:12
Hi @AmandaTamlm,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-09 06:12 UTC
Labels: Issue: needs update, Reported on 2.4.2
