### ISSUE TITLE
GraphQL product attribute added by admin showed DEPRECATED in ProductInterface

### ISSUE THREAD

**Issue by richiardc** [magento/magento2#36037] opened 2022-08-26 09:47 UTC
### Preconditions and environment

- Magento version 2.4.5

### Steps to reproduce

1. Add new product attribute from admin
2. Set Storefront properties Visible on Catalog Pages on Storefront to Yes to expose it on api
3. Verify the new field in ProductInterface with a GraphQL client (I use Altair GraphQL Client)
Ex: Run the graphql [query](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/simple-product.html) with "custom_attributes" Ref [devdocs](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html)
### Expected result

The field hasn't to be DEPRECATED

### Actual result

The field result DEPRECATED and show the message below.

DEPRECATED:
Use the custom_attributes field instead.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-08-26 12:36
Verified the issue on Magento 2.4-develop branch and the issue is reproducible. Unable to use "custom_attributes" ProductInterface in graphQL query. Its not mentioned anywhere in Magento [docs](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html) that its a deprecated field hence confirming this issue.
Thank you.

**Comment by machado-thiago** [comment] 2022-09-20 17:19
@magento I am working on this

**Comment by machado-thiago** [comment] 2022-09-20 17:31
@magento add to contributors team

**Comment by machado-thiago** [comment] 2022-09-20 17:32
@magento I am working on this

**Comment by shomiadarshlt** [comment] 2022-12-22 13:26
@magento There is a query for the issue that if we remove the deprecated warning for a custom field  it will be removed from all fields. Is it correct ?

**Comment by danmooney2** [comment] 2023-02-08 19:46
Deprecation was deemed a fix for https://github.com/magento/magento2/issues/34929.  The proposed alternative is only available in [CatalogGraphQlAux module from PWA studio](https://github.com/magento/magento2-pwa/blob/main/CatalogGraphQlAux/etc/schema.graphqls#L23).  We should move this over to magento2 repo.

**Comment by danmooney2** [comment] 2023-03-13 14:01
Ticket is now https://jira.corp.adobe.com/browse/LYNX-109 CC @sivaschenko

**Comment by pepijnblom** [comment] 2023-05-26 12:37
So will the deprecation warning be removed or will we need to switch to use `custom_attributes` in the future?

**Comment by danmooney2** [comment] 2023-05-26 12:44
@pepijnblom need to switch to using custom_attributes in the future

**Comment by engcom-Bravo** [comment] 2023-06-09 07:48
Hello,

We got the reply from PM as follows,

this ticket should be closed and we can't merge this PR because it would contradict our direction with custom attributes

the recommendation provided by [Daniel Mooney](https://jira.corp.adobe.com/secure/ViewProfile.jspa?name=dmooney) is valid, except that we are consolidating that same code into core,

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2023-06-09 07:48 UTC
Labels: Issue: Confirmed, Component: GraphQL, Reproduced on 2.4.x, Priority: P2, Project: GraphQL, Progress: done, Area: Product, Reported on 2.4.5
