### ISSUE TITLE
[Frontend] Additional addresses DataTable Pagination count displaying wrong.

### ISSUE THREAD

**Issue by niravkrish** [magento/magento2#21396] opened 2019-02-22 05:51 UTC
### Description (*)
My Account > My addresses > additional address DataTable Pagination count displaying wrong.

### Preconditions (*)

1. Magento 2.3.x

### Steps to reproduce (*)

1. Go to My account >> Address book
2. Add more than 2 additional address.
3. Select different Shipping and Billing Address. 
4. Review Additional Address Data Table pagination count.

### Expected result (*)

1. https://s.nimbusweb.me/share/2588577/3xim0ff0y1n1661ohubq

### Actual result (*)

1. https://www.screencast.com/t/3jkUWqt1Au38
2. Item Count And Pagination Not Matched.
3. item count should be excluding shipping and billing address.
4. When additional address is 10 then displayed 11 item and 2 page pagination.
5. When we click on 2nd page it will disappear from there.

**Comment by magento-engcom-team** [comment] 2019-02-22 05:52
Hi @niravkrish. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@niravkrish do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-22 05:52
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-22 05:54
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-22 05:55
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-22 05:55
Hi @krishprakash, here is your [Magento instance](https://i-21396-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21396-2-3-develop.instances.magento-community.engineering/admin](https://i-21396-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-22 06:07
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-22 06:17
Hi @Dharmeshvaja91. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-22 16:16
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-22 16:18
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-22 16:18
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-22 16:18
Hi @shikhamis11, here is your [Magento instance](https://i-21396-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21396-2-3-develop.instances.magento-community.engineering/admin](https://i-21396-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-22 16:32
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98385` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-25 13:53
Hi @niravkrish. Thank you for your report. 
The issue has been fixed in magento/magento2#21399 by @Dharmeshvaja91 in 2.3-develop branch
Related commit(s):
 - [f1e2ffffafe5f70517ee6d65bcce9550d2b92c34](https://github.com/magento/magento2/commit/f1e2ffffafe5f70517ee6d65bcce9550d2b92c34)
 - [8a872be9be8c9932bf78a49fa7b33f05e92cada6](https://github.com/magento/magento2/commit/8a872be9be8c9932bf78a49fa7b33f05e92cada6)
 - [69aac2c6c45cdac540456b430eabd840bc781f1e](https://github.com/magento/magento2/commit/69aac2c6c45cdac540456b430eabd840bc781f1e)
 - [7320e1bdede210da0fd0ff3b813a6736509a0db2](https://github.com/magento/magento2/commit/7320e1bdede210da0fd0ff3b813a6736509a0db2)
 - [0fcf041130c82660af0d3f87dd89665d2529a7a3](https://github.com/magento/magento2/commit/0fcf041130c82660af0d3f87dd89665d2529a7a3)
 - [3ccc867ae22dd3d31adc5786904d92a733ef6de7](https://github.com/magento/magento2/commit/3ccc867ae22dd3d31adc5786904d92a733ef6de7)
 - [5552b3e1b5bbef5e596523078f21a17354681abe](https://github.com/magento/magento2/commit/5552b3e1b5bbef5e596523078f21a17354681abe)
 - [dcff5d1dc3383be9e2ebc0b2c773ee5d9422b2bd](https://github.com/magento/magento2/commit/dcff5d1dc3383be9e2ebc0b2c773ee5d9422b2bd)
 - [0ab0e035d7a5914e66ea7a3c24c13936905ed5a2](https://github.com/magento/magento2/commit/0ab0e035d7a5914e66ea7a3c24c13936905ed5a2)
 - [6584286dd68a29940dca3300dd3368fc2e9ec81e](https://github.com/magento/magento2/commit/6584286dd68a29940dca3300dd3368fc2e9ec81e)
 - [c39751f8cc06a1654e6f57418672b4e63c6be247](https://github.com/magento/magento2/commit/c39751f8cc06a1654e6f57418672b4e63c6be247)
 - [7127e16d5386956f5fa7b91f58c0995d15d52a36](https://github.com/magento/magento2/commit/7127e16d5386956f5fa7b91f58c0995d15d52a36)
 - [be076d5789d478f01c0e854e96e3b1e39aa71177](https://github.com/magento/magento2/commit/be076d5789d478f01c0e854e96e3b1e39aa71177)
 - [2f42295614f85355f029e6346278e2e24708ecd2](https://github.com/magento/magento2/commit/2f42295614f85355f029e6346278e2e24708ecd2)
 - [fa9b420971ebb3dc2129eae30934a11953e7d452](https://github.com/magento/magento2/commit/fa9b420971ebb3dc2129eae30934a11953e7d452)
 - [7436f30f9dae120a0e8f6249c889af2d49ce14f9](https://github.com/magento/magento2/commit/7436f30f9dae120a0e8f6249c889af2d49ce14f9)
 - [50ce1f5db56976fdd5f2818fdcd5d37c7382f38c](https://github.com/magento/magento2/commit/50ce1f5db56976fdd5f2818fdcd5d37c7382f38c)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-25 13:53 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
