### ISSUE TITLE
Website Specific Shipping Methods are not working after upgrade 2.1.2=>2.1.3

### ISSUE THREAD

**Issue by netzweltvimal** [magento/magento2#7840] opened 2016-12-16 07:10 UTC
### Preconditions

1. 2.1.3

### Steps to reproduce

1. Set Different Shipping Methods for Multi Website

### Expected result

1. Shipping Method should be appear according to website

### Actual result

1. Not showing according to Website Shipping Method which is set in Admin=> Shipping Methods 
2. Some time fetal error "Shipping Address Not Set" on Cart and Checkout page
3. Default Config Shipping Methods are showing , not Website Specific.

**Comment by nitinwaves** [comment] 2016-12-16 07:59
Looks like Website Level Configurations are not working at all..

We noticed this problem during base url setup as well.. we had setup base url at store level of each website.

But in case of shipping method, there is no option to enable /disable shipping method at store level. we can only set it at website level. So when we set the shipping methods at website level, it doesn't work.. it is always picking the shipping methods from default config.

**Conclusion:** Website Level Configurations are not working and it falls back to default config UNLESS there is any override at store level.

**Comment by alexpoletaev** [comment] 2016-12-16 14:39
> Website Level Configurations are not working and it falls back to default config UNLESS there is any override at store level.

Confirm.

**Comment by alexnos88** [comment] 2016-12-16 14:43
Same for me

**Comment by abi2** [comment] 2016-12-16 16:08
Guess this is the underlying problem of my issue
#7830

**Comment by mtuinstra** [comment] 2016-12-20 16:19
Try removing your configuration in the core_config_data table and then set is again via magento, this did the trick for us with themes: #7841

**Comment by alexpoletaev** [comment] 2016-12-20 18:06
The problem is here ```Magento\Store\Model\Config\Processor\Fallback::getWebsiteConfig()```.
This line ```$code = $website['website_id'];``` should be replaced with ```$code = $website['code'];```
As a workaround you can create your own module and extend the ```Fallback``` class using ```di.xml```, but since almost all methods and properties has a 'private' scope, you will need to override them all.

**Comment by abi2** [comment] 2016-12-20 18:30
@alexpoletaev can you be more specific,
This is what I have changed so far:
`private function getWebsiteConfig(array $websites, $id)
    {
        foreach ($this->websiteData as $website) {
            if ($website['website_id'] == $id) {
                $code = $website['code'];
                return isset($websites[$code]) ? $websites[$code] : [];
            }
        }
        return [];
    }`

Thanks

**Comment by alexpoletaev** [comment] 2016-12-20 20:36
@abi2, you did the right thing.

**Comment by abi2** [comment] 2016-12-20 20:40
@alexpoletaev still not working for me, any need to recompile?

Thanks

**Comment by salelsol** [comment] 2016-12-21 07:25
@alexpoletaev where is this file ?

**Comment by alexpoletaev** [comment] 2016-12-21 10:31
@salelsol ```vendor/magento/module-store/Model/Config/Processor/Fallback.php```

**Comment by salelsol** [comment] 2016-12-21 11:17
@alexpoletaev afther change file this modification works fine in all 3 multiwebsite frontend, but I can´t access to backend: Requested store is not found.

**Comment by salelsol** [comment] 2016-12-21 11:40
@alexpoletaev maybe I would be modify index.php:
index.php{main}";s:3:"url";s:7:"/admin/";s:11:"script_name";s:10:"/index.php";}
<?php
/**
 * Application entry point
 *
 * Example - run a particular store or website:
 * --------------------------------------------
 * require __DIR__ . '/app/bootstrap.php';
 * $params = $_SERVER;
 * $params[\Magento\Store\Model\StoreManager::PARAM_RUN_CODE] = 'website2';
 * $params[\Magento\Store\Model\StoreManager::PARAM_RUN_TYPE] = 'website';
 * $bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);
 * \/** @var \Magento\Framework\App\Http $app *\/
 * $app = $bootstrap->createApplication('Magento\Framework\App\Http');
 * $bootstrap->run($app);
 * --------------------------------------------
 *
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

try {
    require __DIR__ . '/app/bootstrap.php';
} catch (\Exception $e) {
    echo <<<HTML
<div style="font:12px/1.35em arial, helvetica, sans-serif;">
    <div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
        <h3 style="margin:0;font-size:1.7em;font-weight:normal;text-transform:none;text-align:left;color:#2f2f2f;">
        Autoload error</h3>
    </div>
    <p>{$e->getMessage()}</p>
</div>
HTML;
    exit(1);
}

$bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $_SERVER);
/** @var \Magento\Framework\App\Http $app */
$app = $bootstrap->createApplication('Magento\Framework\App\Http');
$bootstrap->run($app);

**Comment by salelsol** [comment] 2016-12-21 11:51
@alexpoletaev backend works also. Many thaks for your help.

**Comment by veloraven** [comment] 2016-12-28 16:18
Internal ticket MAGETWO-62758 was created

**Comment by MagePsycho** [comment] 2016-12-29 07:45
Fix provided by @alexpoletaev is not working for General > Allowed Country settings. So Magento Team should provide the solution ASAP as this is very sensitive issue for any store.
Thanks

**Comment by hostep** [comment] 2016-12-30 16:03
I agree with @MagePsycho that this bug needs to be fixed ASAP. It's the only new bug in 2.1.3 that actually prevents us from upgrading our shops to 2.1.3 since it has the potential of causing all kinds of unexpected issues.

@MagePsycho: For me the Allowed Country setting works when I apply the fix from @alexpoletaev btw (maybe you forgot to flush your caches?).

@veloraven: this exact same bug is also being tracked over here and got a different MAGETWO number assigned, just so you know if you didn't know already: https://github.com/magento/magento2/issues/7943
And the issue was introduced in this commit: https://github.com/magento/magento2/commit/c1e806fa653714870fb0bd44a30e84e64bc75602#diff-5dec7e10285c9a96cf5b40b06ece36c0L107

@veloraven: I really would like to see this bug getting a very high priority, and being fixed in a new release in the first week of January if possible (for my part you can create a version '2.1.3.1' which only contains a fix for this bug).

And thanks to @alexpoletaev for discovering the fix!

**Comment by wsagen** [comment] 2017-01-03 12:22
Also affecting our clients - needs fixing ASAP

**Comment by JonasBlicherJensen** [comment] 2017-01-04 08:46
Extremely critical bug.
How did this get released? It must be one of the most fundamental functionalities in Magento 2.

**Comment by ebaschiera** [comment] 2017-01-16 13:18
Apparently the fix suggested in this issue is breaking the payment selection step in checkout. It appears as blank, and the corrisponding `<div>` stays hidden.
I am on Magento EE 2.1.3.

**Comment by ebaschiera** [comment] 2017-01-16 17:04
Sorry, my problem was on a 3rd party module, not magento core.

**Comment by erikhansen** [comment] 2017-01-23 19:23
Do be aware that if this is a critical issue for you on 2.1.3, you can fix this issue by patching your installation by making the change I outlined here: https://github.com/magento/magento2/issues/7943#issuecomment-269508822

If you're installing Magento via Composer, you should check out this elegant [composer-patches](https://github.com/cweagans/composer-patches) plugin that @hostep alerted me of that allows you to apply patches when `composer install` is run.

**Comment by ghost** [comment] 2017-01-23 22:01
Rather concerning that something so elementary made it past their testers, if they use any.

**Comment by salelsol** [comment] 2017-02-08 17:52
@alexpoletaev , afther upgrading to M2.1.4 vendor/magento/module-store/Model/Config/Processor/Fallback.php has changed and $code = $website['code']; it´s O.K. , but I can´t access to subdomains like before in M2.1.3.

**Comment by salelsol** [comment] 2017-02-08 17:58
@alexpoletaev , Sorry issue is due because .htaccess was changed, now works fine.

**Comment by KrystynaKabannyk** [comment] 2017-03-02 12:37
Hi @netzweltvimal, this issue was fixed under MAGETWO-62648 in 2.1.4, that's why I closed it. If you have additional questions or info please feel free to reopen this one or create a new one.

**Closed as completed by KrystynaKabannyk** 2017-03-02 12:37 UTC
Labels: Issue: Ready for Work, bug report, Component: Shipping
