### ISSUE TITLE
Payment methods not visible on checkout

### ISSUE THREAD

**Issue by asshumski** [magento/magento2#23665] opened 2019-07-11 09:35 UTC
### Preconditions (*)

1. Magento 2.2.8
2. Magento Cloud

### Steps to reproduce (*)

1. Add item to cart and Go to checkout
2. On the first step fill in required data and click next to proceed to the second step (notice that 'next' button is disabled after the first click)
3. Go back to the first step and click 'next' button multiple times, after that 'payment methods' on the second step will blink (they will disappear if you click next button 2 times)

### Expected result (*)

1. Payment methods will not disappear

### Actual result (*)

1. ![Screen Shot 2019-06-26 at 17 12 12](https://user-images.githubusercontent.com/19212187/60187079-9d39a480-9835-11e9-8211-3297260ed788.png)
2. [magento_2_checkout.zip](https://github.com/magento/magento2/files/3381314/magento_2_checkout.zip)

**Comment by engcom-Charlie** [comment] 2019-07-11 09:41
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-11 09:41
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-11 09:42
Hi @engcom-Charlie, here is your [Magento instance](https://i-23665-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23665-2-3-develop.instances.magento-community.engineering/admin](https://i-23665-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-11 09:53
Hello @asshumski ! Thank you for your report !
I`ve just rechecked this issue on Vanilla Magento 2.3-develop instance and i was not able to reproduce it . I will try to reproduce it on 2.2-develop instance

**Comment by engcom-Charlie** [comment] 2019-07-11 09:54
@magento give me 2.2.9-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-11 09:54
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.2.9-develop instance for you

**Comment by engcom-Charlie** [comment] 2019-07-11 10:04
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-07-11 10:04
Hi @engcom-Charlie. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-07-11 10:05
Hi @engcom-Charlie, here is your [Magento instance](https://i-23665-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23665-2-2-develop.instances.magento-community.engineering/admin](https://i-23665-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-07-11 10:14
@asshumski still can not reproduce this issue even on 2.2-develop instance . I`m closing this issue for now but feel free to reopen it in case you can confirm this issue exist in 2.3.x release line
Thanks in advance

**Closed as completed by engcom-Charlie** 2019-07-11 10:14 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid
