### ISSUE TITLE
Magento 2.3 CE backend urser interface problem for product attribute options

### ISSUE THREAD

**Issue by dharake** [magento/magento2#21668] opened 2019-03-10 05:50 UTC
### Preconditions (*)

1.M2.3 CE running on any environment, not important here.

### Steps to reproduce (*)

1. Create 14 store views 
2. Create a product attribute with options (i.e. dropdown)

### Expected result (*)

1. I should have adequate space in the table to input my values.

### Actual result (*)

1. ![Capture](https://user-images.githubusercontent.com/22891885/54081172-ef979980-4308-11e9-9bcb-abffff516007.PNG)

Basic stuff guys that has a real impact on usability.

**Comment by magento-engcom-team** [comment] 2019-03-10 05:50
Hi @dharake. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@dharake do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by dharake** [comment] 2019-03-10 05:57
@magento-engcom-team I confirm it's a Vanilla Magento instance.

**Comment by magento-engcom-team** [comment] 2019-03-10 18:16
Hi @Leandry. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by Leandry** [comment] 2019-03-10 18:16
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-10 18:16
Hi @Leandry. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-10 18:17
Hi @Leandry, here is your [Magento instance](https://i-21668-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21668-2-3-develop.instances.magento-community.engineering/admin](https://i-21668-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Leandry** [comment] 2019-03-10 18:36
Hi, @dharake. 

Unfortunately, I was not able to reproduce the issue on three different browsers on 2.3 Vanilla Magento instance.
![2019-03-10_20-25-39](https://user-images.githubusercontent.com/9416636/54089602-49cd4480-4373-11e9-911e-cecac33a0d3a.gif)

Could you update preconditions and give more information(for example browser and OS)?

Thank you!

**Comment by dharake** [comment] 2019-03-10 19:12
Hi @Leandry ,

Thanks for taking the time to test this.

Please find attached, Chrome, IE, Edge

![ie](https://user-images.githubusercontent.com/22891885/54089935-2d330b80-4377-11e9-9bb3-c7bae8e3ed1d.PNG)
![edge](https://user-images.githubusercontent.com/22891885/54089936-2dcba200-4377-11e9-8df3-f74a66b020be.PNG)
![chrome](https://user-images.githubusercontent.com/22891885/54089937-2dcba200-4377-11e9-8fd1-592db7837f01.PNG)

Upon further inspection, notice that each box takes the max-width from the store view name? Try making one of your store view names "areyoutiredofbugs.com" and come back to me with your results. Or don't, too tired, don't care, fixed it myself.

Thanks

#newslogan #magento #notabletoreproduce

**Comment by dharake** [comment] 2019-03-10 19:15
Hi @Leandry ,

Thanks for taking the time to test this.

Please find attached, Chrome, IE, Edge

![ie](https://user-images.githubusercontent.com/22891885/54089935-2d330b80-4377-11e9-9bb3-c7bae8e3ed1d.PNG)
![edge](https://user-images.githubusercontent.com/22891885/54089936-2dcba200-4377-11e9-8df3-f74a66b020be.PNG)
![chrome](https://user-images.githubusercontent.com/22891885/54089937-2dcba200-4377-11e9-8fd1-592db7837f01.PNG)

Upon further inspection, notice that each box takes the max-width from the store view name? Try making one of your store view names "areyoutiredofbugs.com" and come back to me with your results. Or don't, too tired, don't care, will fix it myself.

Thanks

#newslogan #magento #notabletoreproduce

**Comment by Leandry** [comment] 2019-03-10 19:47
@dharake,

Thank you for additional information, but the issue was not replicated on GC, EDGE.

![2019-03-10_21-43-26](https://user-images.githubusercontent.com/9416636/54090536-daa91d80-437d-11e9-9ebf-a13f8ea26da7.png)

Closing the issue. 

Thank you!

**Comment by dharake** [comment] 2019-03-10 19:48
Quelle surprise!

For you other frustrated Magento users out there facing this issue, add the below to your admin CSS 

**For the record, this is an actual bug, and this is how Magento deals with 90% of this stuff, by closing the topic. So sick of it.**  

When the length of text in the combined store view names exceeds the defined width of the container (which he has not reproduced by adding one long store view, but keeping the others short), things go awry.

2 solutions.

1: keep store view codes short (although if you have a lot of languages you may still face the issue, depending on your screen rez)

**2. FIX!** Add this to admin CSS. Only a quick fix, so not responsive but will work on laptop or desktop at least. You will now be able to see what you are typing. You could also add this to inspector on the fly just to get your attribute values saved.

table.admin__control-table {
    width: 5000px;   /* Whatever length exceeds the table requirements */
}

![fix](https://user-images.githubusercontent.com/22891885/54090720-d7169600-437f-11e9-8977-0f9916d35fbb.PNG)

**Closed as completed** 2019-03-10 19:47 UTC
Labels: Progress: needs update, Issue:  Cannot Reproduce, Issue: Format is valid
