### ISSUE TITLE
Exception #0 (Magento\Framework\Exception\LocalizedException): Could not read config file

### ISSUE THREAD

**Issue by manos-nookala** [magento/magento2#8939] opened 2017-03-18 17:13 UTC
Hi
I created a new theme with parent theme as Luma in magento2, after creating i reloaded my local site, i am getting this issue. Please help me.

Issue Is
======

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Could not read config file

Exception #0 (Magento\Framework\Exception\LocalizedException): Could not read config file
#0 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Config\Reader\Filesystem.php(123): Magento\Framework\Config\FileResolver->get('view.xml', 'global')
#1 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Config\View.php(233): Magento\Framework\Config\Reader\Filesystem->read('global')
#2 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Config\View.php(213): Magento\Framework\Config\View->read()
#3 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Config\View.php(90): Magento\Framework\Config\View->initData()
#4 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-catalog\Helper\Image.php(833): Magento\Framework\Config\View->getVarValue('Magento_Catalog', 'product_image_w...')
#5 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-checkout\Block\Cart\Sidebar.php(82): Magento\Catalog\Helper\Image->getFrame()
#6 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Checkout\Block\Cart\Sidebar\Interceptor.php(37): Magento\Checkout\Block\Cart\Sidebar->getImageHtmlTemplate()
#7 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-checkout\Block\Cart\Sidebar.php(70): Magento\Checkout\Block\Cart\Sidebar\Interceptor->getImageHtmlTemplate()
#8 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Checkout\Block\Cart\Sidebar->getConfig()
#9 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Checkout\Block\Cart\Sidebar\Interceptor.php(26): Magento\Checkout\Block\Cart\Sidebar\Interceptor->___callPlugins('getConfig', Array, Array)
#10 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-checkout\view\frontend\templates\cart\minicart.phtml(46): Magento\Checkout\Block\Cart\Sidebar\Interceptor->getConfig()
#11 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\TemplateEngine\Php.php(59): include('E:\\xampp\\htdocs...')
#12 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Element\Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Cart\Sidebar\Interceptor), 'E:/xampp/htdocs...', Array)
#13 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Checkout\Block\Cart\Sidebar\Interceptor.php(297): Magento\Framework\View\Element\Template->fetchView('E:/xampp/htdocs...')
#14 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Element\Template.php(279): Magento\Checkout\Block\Cart\Sidebar\Interceptor->fetchView('E:/xampp/htdocs...')
#15 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Element\AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#16 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Checkout\Block\Cart\Sidebar\Interceptor.php(609): Magento\Framework\View\Element\AbstractBlock->toHtml()
#17 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(542): Magento\Checkout\Block\Cart\Sidebar\Interceptor->toHtml()
#18 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(518): Magento\Framework\View\Layout->_renderBlock('minicart')
#19 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('minicart')
#20 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('minicart')
#21 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('minicart', true)
#22 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('minicart')
#23 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header-wrapper')
#24 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('header-wrapper')
#25 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('header-wrapper')
#26 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('header-wrapper', true)
#27 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('header-wrapper')
#28 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('header.containe...')
#29 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('header.containe...')
#30 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('header.containe...')
#31 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('header.containe...', true)
#32 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('header.containe...')
#33 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#34 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#35 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#36 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#37 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#38 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#39 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#40 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#41 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#42 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#43 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#44 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Layout\Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#45 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Result\Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#46 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\View\Result\Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#47 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Chain\Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#49 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Chain\Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#50 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-page-cache\Model\Controller\Result\VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#51 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Chain\Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#52 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#53 E:\xampp\htdocs\MagentoEmpty\vendor\magento\module-page-cache\Model\Controller\Result\BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\Interception\Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#55 E:\xampp\htdocs\MagentoEmpty\var\generation\Magento\Framework\View\Result\Page\Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#56 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\App\Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 E:\xampp\htdocs\MagentoEmpty\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#58 E:\xampp\htdocs\MagentoEmpty\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#59 {main}

**Comment by korostii** [comment] 2017-03-20 10:22
Well, it clearly says that Magento "Could not read config file ... 'view.xml' ... ".
Please make sure that you have an accessible view.xml find inside your theme.
Additionally, the path in the traces ("E:\xampp\htdocs\...") hints that you use Windows as server OS. FYI It's not listed among [operating systems supported by Magento](http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements-tech.html). Have you tried switching to Linux yet? ;)

**Comment by korostii** [comment] 2017-03-20 10:33
In general, if you are looking for an advice please refer to the[ Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions. As GitHub issue tracker is intended for technical issues only.
The issues which cannot be consistently reproduced on a clean installation of Magento CE aren't likely to get resolved in here.

**Comment by veloraven** [comment] 2017-06-27 11:18
@manos-nookala please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify which version of Magento you are running.

**Comment by magento-engcom-team** [comment] 2017-09-13 20:19
@manos-nookala please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this issue. The GitHub issue tracker is intended for Magento Core technical issues only.

**Closed as completed by magento-engcom-team** 2017-09-13 20:19 UTC
Labels: Progress: needs update, Issue: Format is not valid
