### ISSUE TITLE
Issue while creating product on store

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#34900] opened 2021-12-29 13:20 UTC
### Preconditions (*)

1. Magento ver. 2.3.6
2.

### Steps to reproduce (*)

1. Call the API /rest/V1/products  [Request magento.txt](https://github.com/magento/magento2/files/7789027/Request.magento.txt)
2. Getting Error in api call  

### Expected result (*)

1. Product should be successfully created on store without any error.
2.

### Actual result (*)

1. Getting Error in api call  
2. [response error-magento.txt](https://github.com/magento/magento2/files/7789025/response.error-magento.txt)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Echo** [comment] 2021-12-29 15:12
Hi @webgility-amazonapi,

Thank you for reporting the issue.

However, we tried to reproduce it on Magento 2.4-dev but the issue is not reproducible. Steps followed to reproduce issue:

1. Installed the fresh Magento 2.4-dev instance.
2. Added sample product by using JSON provided in the ticket description.
3. API works fine, see the attached response body. 

By looking at the response provided in the ticket, it seems the issue is with the installed Magento instance.

If the issue still persists at your end then please provide some more details like debug logs, screenshots or video, accordingly, I’ll try to reproduce it again.

Thank You

**Comment by engcom-Echo** [comment] 2022-01-12 06:39
Dear @webgility-amazonapi,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket with the requested details in last comment if you need more assistance on this.

Thanks

**Closed as completed by engcom-Echo** 2022-01-12 06:39 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
