### ISSUE TITLE
Improve oAuth Integration Identity Link Popup

### ISSUE THREAD

**Issue by jpreed2** [magento/magento2#4457] opened 2016-05-11 01:06 UTC
## Steps to reproduce
1. Install Magento from `develop` branch.
2. In Magento Admin: System > Extensions > Integrations click Add New Integration.
3. Enter an integration name, email address, callback url and identity link url.
4. Click API tab on the left and choose Resource Access All.
   Click Save.
5. The new integration displays in the list of integrations. Click the "Authorize" link for the new integration.
6. Verify API authorizations and click the Authorize button.
## Expected result
1. Popup should appear containing the contents of the Identity Link URL.
## Actual result
1. Nothing happens unless you disable the popup blocker.
2. There is not even a notification that the popup was blocked.

Need to improve the flow so the popup avoids the popup blocker.  As long as the popup is a direct response to a user action it will not trigger the popup blocker.

Another option is to use an iFrame.

**Comment by choukalos** [comment] 2016-05-11 21:27
Internal ticket to improve this flow - MAGETWO-52007 ; reassigning to Mark

**Comment by sevos1984** [comment] 2016-07-27 07:32
@jim5359 We can't reproduce this issue. Is it still actual?

**Comment by jpreed2** [comment] 2016-07-27 16:34
Yes, this is fixed in the current version.  It now warns you if you have a popup blocker enabled.

**Comment by slavvka** [comment] 2016-07-28 08:36
Thank you, closing

**Closed as completed by slavvka** 2016-07-28 08:36 UTC
Labels: improvement, Component: Framework/Webapi
