### ISSUE TITLE
Customer is logged in but showing 404 error in frontend.

### ISSUE THREAD

**Issue by ananth-iyer** [magento/magento2#35838] opened 2022-07-28 12:54 UTC
### Preconditions and environment
 - 2.3.x, 2.4.x CE and Adobe Commerce

![](https://user-images.githubusercontent.com/24892273/181508159-7dbdb063-347c-4391-a7b9-8931c4bd1b94.png)

Base64 - aHR0cDovL21hZ2VudG8yNDAubG9jYWwvY3VzdG9tZXIvYWNjb3VudC9sb2dpblBvc3Qv
Decoded Base64 - <http://magento240.local/customer/account/loginPost/>
### Steps to reproduce
1. Go to frontend.
1. Add `/customer/account/loginPost/` in your magento url. ex-<http://magento240.local/customer/account/loginPost/>
1. Now click on {**}S{*}*ign In** 
1. Give login id and password.

### Expected result

It should generate referer url to Customer dashboard page when referer URL header contains /loginPost.
### Actual result

It is not generating referrer url to customer dashboard page,It is showing 404 error page but customer is logged in.

**Attached video:** [Untitled_ Jul 29, 2022 3_00 PM.webm](https://user-images.githubusercontent.com/24892273/181730483-2e2f226d-7e83-4cf5-b101-49c7a7526ee1.webm)
### Additional information

*No response*
### Release note

*No response*
### Triage and priority
 - < > Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - < > Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

**Comment by ananth-iyer** [comment] 2022-07-28 12:54
@magento give me 2.4-develop instance

**Comment by ananth-iyer** [comment] 2022-07-28 13:09
If you visit this link: https://70b0711c568e9cdf00416449ee01f393.instances.magento-community.engineering/customer/account/loginPost/
Click on Sign In on above link so will get better idea

**Comment by engcom-Lima** [comment] 2022-07-28 13:49
Hi @ananth-iyer 

Thanks for your contribution and collaboration.
I have tried to reproduce the issue but unable to reproduce it.
Kindly refer this [video](https://shared-assets.adobe.com/link/0175876c-b35c-4619-7534-3842343abe56) for your reference.
If possible can you send video of this issue.

Thanks

**Comment by ananth-iyer** [comment] 2022-07-28 15:31
You did not click this link to replicate the issue - https://70b0711c568e9cdf00416449ee01f393.instances.magento-community.engineering/customer/account/loginPost/

It is clear, you don't want to fix the issue.

**Comment by ananth-iyer** [comment] 2022-07-29 04:40
@engcom-Lima ☝🏻

**Comment by engcom-Lima** [comment] 2022-07-29 06:15
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-07-29 07:07
Hi @ananth-iyer ,

I had clicked on [above url](https://github.com/magento/magento2/issues/35838#issuecomment-1198314418) you have given and I got the 404 error as you described. Further I tried to investigate when we get this url appended with `/loginPost`.
Inorder to identify the specific scenario I had followed your steps to reproduce and recorded [above video](https://github.com/magento/magento2/issues/35838#issuecomment-1198169171).
**Can you please help answering whether you are updating url your own or any specific scenario we have to follow to get the url appended with `/loginPost`?**

Thanks

**Comment by ananth-iyer** [comment] 2022-07-29 09:05
@engcom-Lima  It takes referer url `/loginPost`, encodes with base64 and adds in referer parameter of `/login`. So after success login, page is redirected to `/loginPost`

**Comment by ananth-iyer** [comment] 2022-07-29 09:09
@magento give me 2.4-develop instance

**Comment by ananth-iyer** [comment] 2022-07-29 09:33
@engcom-Lima check this screen recording
[Untitled_ Jul 29, 2022 3_00 PM.webm](https://user-images.githubusercontent.com/24892273/181730483-2e2f226d-7e83-4cf5-b101-49c7a7526ee1.webm)

**Comment by engcom-Lima** [comment] 2022-07-29 12:01
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:** Customer is logged in but showing 404 error in the frontend.
**Pre-requisite:**
Fresh magento `2.4-develop` should be installed.

**Steps to reproduce:**

1. Go to frontend.
2. Add `/customer/account/loginPost/` in your magento url.
3. Now click on **sign In**
4. Give login id and password.

**Expected result:**
It should generate referrer url to Customer dashboard page when referer URL header contains /loginPost.

**Actual result:**
It is not generating referrer url to customer dashboard page,It is showing 404 error page but customer is logged in.

**Screenshots:**
![image](https://user-images.githubusercontent.com/60198022/181753392-ee083d67-291c-49c9-9d52-f1ee90313e28.png)

**Comment by ananth-iyer** [comment] 2022-08-05 11:21
Hi @engcom-Lima are there any updates?

**Comment by pmonosolo** [comment] 2022-09-20 22:23
I have the same issue, its also compounded by Amasty plugin redirecting all 404 pages to search making it confusing as hell.

This is still present on 2.4.5 upgrade from 2.4.3.

I think what happens is that after an unsuccesful login, it loses referrer URL or something similar happens and it just dumps the user to 404 page.

**Comment by engcom-Lima** [comment] 2022-09-21 14:04
Hi @pmonosolo & @ananth-iyer ,

Thanks for your contribution and collaboration.

Internal team is working on it ,we will come back soon with some result.

Thanks

**Comment by pmonosolo** [comment] 2022-09-21 16:34
> Hi @pmonosolo & @ananth-iyer ,
> 
> Thanks for your contribution and collaboration.
> 
> Internal team is working on it ,we will come back soon with some result.
> 
> Thanks

Thanks @engcom-Lima ! 

It'd be great if the fix was released as a hotfix instead of waiting for a full release or a patch. 

We cant have enterprise software have a serious issue where we lose customers because the basic function such as login does not work.

**Comment by Vishrootways** [comment] 2023-01-05 11:40
We faced a similar issue in our one of the commerce cloud websites and the Adobe support team is not ready to check this so I am also actively looking for a solution.

In our case, the referer URL is incorrectly generated, and due to that customer is not redirecting to the previous page after login.

The issue is the login referer URL miss %2C at the end of the URL.
**Correct URL:** https://www.our_domain.com/en/customer/account/login/referer/aHR0cHM6Ly93d3cucGFjaWZpY3Ntb2tlLmNvbS9lbi8%2C%2C/

**Wrong URL:**  https://www.our_domain.com/en/customer/account/login/referer/aHR0cHM6Ly93d3cucGFjaWZpY3Ntb2tlLmNvbS9lbi8%2C/

As you can see, the correct URL has %2C at the end, which is missing in the wrong URL. (Basically, correct URL has two %2C%2C but the wrong URL only has one)

If we manually add %2C at the end of the URL, then it works as expected.

Now we are not sure why %2C is missing from the URL.

And the best thing is if we cloned the commerce cloud website to local (with same code and DB) then we have not face any issue :(

Thanks,
Vish

**Comment by ananth-iyer** [comment] 2023-02-14 05:32
@engcom-Lima are there any updates?

**Comment by andriydeveloper** [comment] 2023-07-21 13:18
It happens everywhere where you have an exception during login. 
For example, you created a new customer account but did not verify the customer's email. Try to log in and you will get the link with the referer param. Then verify the customer email and finish login using the link with the referer param.
Main bug in the file vendor/magento/module-customer/Model/Url.php, function getLoginUrlParams
It makes referer using urlBuilder from */*/* 
`$referer = $this->urlBuilder->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);`
but due to an exception, it generates to own controller: customer/account/loginPost

Quick solution until Magento developers make the right fix:

use Magento\Framework\Url\DecoderInterface;
use Magento\Framework\Url\EncoderInterface;
use Magento\Framework\UrlInterface;

```
/**
     * Fix Magento bug with customer logged in 404 referer url
     * https://github.com/magento/magento2/issues/35838
     *
     * @param  \Magento\Customer\Model\Url  $subject
     * @param $result
     * @return mixed
     */
    public function afterGetLoginUrlParams(
      \Magento\Customer\Model\Url $subject,
      $result
  ) {
        if(isset($result[\Magento\Customer\Model\Url::REFERER_QUERY_PARAM_NAME])){
          $referer = $result[\Magento\Customer\Model\Url::REFERER_QUERY_PARAM_NAME];
          $refererUrl = $this->urlDecoder->decode($referer);
          if(strpos($refererUrl, 'customer/account/loginPost')){
              $newReferer = $this->urlBuilder->getUrl('customer/account/index', ['_current' => true, '_use_rewrite' => true]);
              $result[\Magento\Customer\Model\Url::REFERER_QUERY_PARAM_NAME] = $this->urlEncoder->encode($newReferer);
          }
      }

      return $result;
  }
```

**Closed as completed** 2024-05-28 15:06 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Component: LoginAsCustomerFrontendUi, Progress: done, Reported on 2.4.x, Reported on 2.3.x, Area: Account
