### ISSUE TITLE
Downloadable Product should be OUT OF STOCK if there are no links just samples saved

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#26106] opened 2019-08-12 12:08 UTC
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1. Create Downloadable Product 1 without any links. Just add a file in the samples section
2. Open this product on Storefront and verify that status of the product is OUT OF STOCK
3. Get Stock Status of the product using `query products`
```graphql
{
  products(
    search: "downloadable"
  ) {
    items {
      ... on DownloadableProduct {
        stock_status
        sku
      }
    }
  }
}

```

### Expected result (*)

1. Stock Status is OUT OF STOCK
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "stock_status": "OUT_OF_STOCK",
          "sku": "Downloadable Product 1"
        }
      ]
    }
  }
}
```

### Actual result (*)

1. 
```graphql
```graphql
{
  "data": {
    "products": {
      "items": [
        {
          "stock_status": "IN_STOCK",
          "sku": "Downloadable Product 1"
        }
      ]
    }
  }
}
```

![image](https://user-images.githubusercontent.com/11827230/62863956-107a7580-bd13-11e9-8c7c-1507bc2bb03f.png)

**Comment by magento-engcom-team** [comment] 2019-12-18 21:23
:white_check_mark: Confirmed by @lenaorobei 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29904` were created

**Issue Available**: @lenaorobei, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by AleksLi** [comment] 2020-02-19 21:53
I tried to verify that the issue is still relevant but I couldn't. 
What I did:
Branch 2.4-develop. 
<img width="1389" alt="downloadable product-2 2020-02-19 22-41-25" src="https://user-images.githubusercontent.com/10618641/74879516-9aae3100-5369-11ea-9a6d-e6191d10af25.png">
I tried to get it using GRAPHQL 
<img width="1167" alt="chrome-extension:::fkkiamalmpiidkljmicmjfbieiclmei" src="https://user-images.githubusercontent.com/10618641/74879801-33dd4780-536a-11ea-884a-90ef2ea49f61.png">

**Closed as completed by AleksLi** 2020-02-19 21:53 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, good first issue, Component: Downloadable, Reproduced on 2.4.x
