### ISSUE TITLE
Problem when i try to install magento2

### ISSUE THREAD

**Issue by ruCyberPoison** [magento/magento2#12424] opened 2017-11-23 22:42 UTC
I am using the newest PHP verison but he says something is wrong to install magento2.
how can i fix this....

PHP Version Check
Your PHP version is 7.1.8-1ubuntu1. The required PHP version is ~5.6.5|7.0.2|7.0.4|~7.0.6. Hide detail

Download and install PHP from www.php.net using this PHP Documentation.

For additional assistance, contact your hosting provider.

**Comment by ishakhsuvarov** [comment] 2017-11-24 09:16
@Screamfox From the context it looks like you are attempting to install Magento 2.1, which does not support PHP version `7.1`, only `5.6` and `7.0` are supported for 2.1.
To solve the issue you may downgrade PHP version to `7.0` or use Magento 2.2 which is compatible with PHP `7.1`

You may find more information in the devdocs in the System Requirements section for [2.1](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html) and [2.2](http://devdocs.magento.com/guides/v2.2/install-gde/system-requirements-tech.html).
Closing this issue, as it is not a bug.

**Closed as completed by ishakhsuvarov** 2017-11-24 09:16 UTC
Labels: Issue: Clear Description, non-issue, Issue: Format is not valid

**Comment by magento-engcom-team** [comment] 2017-11-24 09:29
@Screamfox, thank you for your report.
This seems to be correct Magento behavior. Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/) site for advice or general discussion about this.
Otherwise you may submit Pull Request with the suggested changes.
