### ISSUE TITLE
Wrong column type when creating temporary tables for flat catalog

### ISSUE THREAD

**Issue by xi-ao** [magento/magento2#14571] opened 2018-04-06 07:45 UTC
## Preconditions
* Tested on Magento OS from 2.0.0 to 2.2.3.

## Steps to reproduce
* Columns named `entity_id` in `\Magento\Catalog\Model\Indexer\Product\Flat\TableBuilder::_createTemporaryTable` should be created with option
```
['unsigned' => true] 
```
to match columns from original tables.

## Actual result
* Without this option, entity IDs above 2147483647 are not copied correctly and flat catalog fails to rebuild.

## Expected result
* Larger catalogs rebuild correctly.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-03 08:53
Hello @xi-ao, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-10-15 03:08
Hi @jasonevans1. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by jasonevans1** [comment] 2018-10-15 21:09
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2018-10-15 21:09
Hi @jasonevans1. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2018-10-15 21:09
Hi @jasonevans1, here is your [Magento instance](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14571-2-3-develop/).
Admin access: [http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14571-2-3-develop//admin](http://ec2-34-228-235-121.compute-1.amazonaws.com/i-14571-2-3-develop//admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-12-06 16:45
Hi @xi-ao. Thank you for your report. 
The issue has been fixed in magento/magento2#18818 by @jasonevans1 in 2.3-develop branch
Related commit(s):
 - [c58ac50f9f090e2094639b006dca414b13a225d5](https://github.com/magento/magento2/commit/c58ac50f9f090e2094639b006dca414b13a225d5)

The fix will be available with the upcoming 2.3.1 release.

**Closed as completed by magento-engcom-team** 2018-12-06 16:45 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, help wanted
