### ISSUE TITLE
Orders Page Date Search not working for none US date format

### ISSUE THREAD

**Issue by thorrrr** [magento/magento2#29020] opened 2020-07-07 09:18 UTC
### Preconditions (*)

1.2.3.5 p1
2.

### Steps to reproduce (*)

1. The date selection in the orders page only does USA format. Whatever you have set in the backend all mine is the UK but M2 orders page does not change to sys date. So any search you try gives you wrong results for the dates you pick, as my orders have a UK format but search return date month swapped round
2.

### Expected result (*)

1. See [here](https://nextcloud.daddycloud.co.uk/s/MgiqWNAq244pGTA) 
2.I expect it to allow us to have UK date format and the search to work

### Actual result (*)

1. See above screen shot
![Screenshot- 533](https://user-images.githubusercontent.com/8170673/86757688-3a2f4000-c03b-11ea-94b3-700235652032.png)

2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [* ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by thorrrr** [comment] 2020-07-10 07:18
Hi Guys
Mine is a vanilla install brand new M2 just moved over from M1 and saw the issue. I am amazed it has never been picked up before

**Comment by Pavel-Fekete** [comment] 2020-11-11 14:06
Not relevant for latest 2.4-develop

'_Purchase Date_' column instead of '_Date_' column and date format is changed
In this case 'Filter' works properly, for UK backend as well
![Interface](https://user-images.githubusercontent.com/67371013/98820950-8d752d00-2437-11eb-9c49-78f5daf4b5cc.png)
![Purchase date](https://user-images.githubusercontent.com/67371013/98820956-8fd78700-2437-11eb-9c09-3f5f71f2f34c.png)

**Comment by engcom-Alfa** [comment] 2020-11-26 14:33
Hi @thorrrr .

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop

**Actual Result:** :heavy_check_mark: Search works correctly for UK date format

![Peek 2020-11-26 16-29](https://user-images.githubusercontent.com/51679138/100363048-debf1800-3004-11eb-8cec-a5b1120a6f8c.gif)

So, we have to close it. 
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-26 14:33 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5
