### ISSUE TITLE
Translation inheritance

### ISSUE THREAD

**Issue by KevinGimbel** [magento/magento2#11759] opened 2017-10-26 08:51 UTC
A language package in `vendor/` appears to have a higher priority than a local package, e.g. `app/design/frontend/MyCompany/i18n` or `app/i18n/MyCompany/de_de`. When I install a generic language package, for example https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE, and try to overwrite one of the translations in my theme it does not work.

### Preconditions

Magento 2.2.0
PHP 7.0.24

### Steps to reproduce
1.  Create a custom theme and set it active (e.g. `app/design/frontend/Test/base`
2.  Add `app/design/frontend/Test/base/i18n/de_DE.csv` to the theme
3.  Add `"Place Order", "WILL NOT BE TRANSLATED"` to `i18n/de_DE.csv`
4. Require and setup https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE
5. Clear caches, deploy static content, etc. 

### Expected result

I expect to see `WILL NOT BE TRANSLATED` as button title and text inside the checkout (where `Place Order` is used). My active Theme should have a higher priority in my opinion. 

### Actual result
Visit store front, add an item to the cart and proceed to `/de/checkout/#payment`. The order button will say "Zahlunspflichtig bestellen" instead of "WILL NOT BE TRANSLATED" from the theme translation 

Open `/pub/static/frontend/Test/base/de_DE/js-translation.json` and search for `Place Order`. The string from the vendor package is used instead of the theme translation.

----

I also tried to overwrite this string form multiple places but non of them work - it appears a vendor language package has the highest priority. Places I have tried: 

- `app/i18n/MyCompany/de_de/`
- `app/code/MyCompany/MyModule/i18n`
- `app/design/frontend/MyCompany/base/i18n`

Which language file has the highest priority? Where should I put my files if I want to overwrite all other translations? In Magento 1.x this location was `app/design/mycompany/mytheme/locale` - files placed here could overwrite all other translations.

**Comment by magento-engcom-team** [comment] 2017-10-31 15:30
@kevingimbel, thank you for your report.
We've created internal ticket(s) MAGETWO-83072 to track progress on the issue.

**Comment by KevinGimbel** [comment] 2018-11-28 10:09
EDIT: removed

Seems the cache got me. Either Magento cache or browser cache. After removing the file `pub/static/frontend/Test/base/de_DE/js-translation.json` it works now.

**Comment by KevinGimbel** [comment] 2018-11-28 10:41
Alright. It seems the original error is actually fixed!

Working with translations (and developer mode) is still a bit weird tho because I manually have to delete the `js-translation.json` file and clear caches after making changes to the translations.

**Comment by engcom-Alfa** [comment] 2019-12-26 14:45
Hi @kevingimbel ! Thank you for your reporting.

We are not able to reproduce this issue on the fresh 2.4-develop instance. Everything works correctly. So we have to close it.

**Manual testing scenario:**
1. Create a custom theme and set it active (e.g. app/design/frontend/Test/base;
2. Add app/design/frontend/Test/base/i18n/de_DE.csv to the theme;
3. Add "Place Order", "WILL NOT BE TRANSLATED" to i18n/de_DE.csv;
4. Require and setup https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE;
5. Clear caches, deploy static content, etc.
6. Go to Storefront->Proceed to Checkout;

**Actual Result:**
![before](https://user-images.githubusercontent.com/51679138/71479859-f3949980-27fe-11ea-87e4-7e313b2f3bd9.png)

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2019-12-26 14:45 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid
