### ISSUE TITLE
Page scrolling behaves strangely in safari browser

### ISSUE THREAD

**Issue by Iamwade** [magento/magento2#34626] opened 2021-11-12 13:16 UTC
### Preconditions (*)
1. Magento 2.4.3
2. Safari version 15  (16612.1.29.41.4, 16612)  (It is likely that this error can be reproduced in all safari browsers)

### Steps to reproduce (*)
1. Open project in the safari browser.
2. Add many items to cart (more than 9).
3. Open a mini cart.
4. Hover your cursor over the items in the mini cart and **quickly** scroll through them

### Expected result (*)
1. When quickly scrolling items in the mini-cart, when the end of the scrolling object, the main page must be unblocked to continue scrolling

https://user-images.githubusercontent.com/33068778/141473020-6a7f891c-e5a0-4075-926b-30281aa99d9a.mov

This problem is reproduced only when quickly scrolling products in the mini-cart. Maybe it's not a bug but default scrolling behavior in safari browser. Can anyone give advice on this issue?
For example, in the browser Chrome, when you scroll quickly, everything works fine

### Actual result (*)
1. Scrolling is blocked on the mini-cart and is not allowed to scroll through the main page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2021-11-14 10:49
@magento give me 2.4-develop instance

**Comment by Melnychuk-Alexandr** [comment] 2022-01-05 13:27
@magento I am working on this

**Comment by Melnychuk-Alexandr** [comment] 2022-01-05 13:29
@magento add to contributors team

**Comment by Melnychuk-Alexandr** [comment] 2022-01-05 13:30
@magento I am working on this

**Comment by Melnychuk-Alexandr** [comment] 2022-01-06 11:36
@magento give me 2.4-develop instance

**Comment by Melnychuk-Alexandr** [comment] 2022-01-06 14:17
@magento give me 2.4-develop instance

**Comment by Melnychuk-Alexandr** [comment] 2022-01-10 12:56
@magento give me 2.4-develop instance

**Comment by Melnychuk-Alexandr** [comment] 2022-01-18 15:11
https://user-images.githubusercontent.com/92367120/149963559-cb3465d5-fb97-4332-853b-c6b5583b68ba.mp4

I could not reproduce this problem.

**Comment by engcom-Bravo** [comment] 2024-08-16 06:34
Hi @Iamwade,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the attached video.



https://github.com/user-attachments/assets/6adfedf5-e613-4adb-a67c-4d24c206bc93



Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-16 06:34 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P4, Progress: done, Component: Frontend, Area: Cart & Checkout
