### ISSUE TITLE
SalesOrder and SalesOrderGrid Relation not consistent with saveAttribute method

### ISSUE THREAD

**Issue by ludwig-gramberg** [magento/magento2#6115] opened 2016-08-11 10:24 UTC
There's a significant difference between saving an entire order and just saving one of its attributes:

```
$order->setData('some_attribute', 10);
$order->save();
```

and

```
$order->setData('some_attribute', 10);
$order->getResource()->saveAttribute($order, 'some_attribute');
```

the first one will save every data in the order object, the second one will only save one value. however the first statement will run a bunch of other methods which the second one doesnt.

so my question is, does using the second method break the framework? is there another efficient way to just save one value on an entity instead of having to save the entire entity? 

the motivation here is to be efficient and to not load and save values you didn't need (if 2 processes overlap doing so old data might by saved)

My specific problem with this is, that I wanted the changed attribute to be saved in the sales_order_grid as well (as defined in the virtual types columns) but it didn't. It only did that when saving the entire order.

So I ended up injecting this: `Magento\Framework\Model\ResourceModel\Db\VersionControl\RelationComposite` into my object and calling: `$this->entityRelationComposite->processRelations($order);` which triggered the values from sales_grid to be copied over to sales_order_grid

But this got me thinking what else the framework might expect to have done at this point if the `->save()` method were beign used. 

So is it ever save to not use the highlevel `->save()`? Could we introduce a safe saveAttribute(s) method on a high level?

**Comment by veloraven** [comment] 2016-08-15 12:22
@ludwig-gramberg thank you for your report.
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ludwig-gramberg** [comment] 2016-08-15 12:32
version 2.0.7

**Comment by antonkril** [comment] 2016-12-13 16:24
It is recommended to use Service contracts to persist entities. And although persisting just one value is more efficient it is never 100% safe to do it, because some customisations might not expect this data integrity will be violated. 

We recommend to use forum for discussions, so I close this ticket. Please start a forum topic if you have additional questions

**Closed as completed by antonkril** 2016-12-13 16:24 UTC
