### ISSUE TITLE
State input is the wrong type on checkout

### ISSUE THREAD

**Issue by andrei-furnica** [magento/magento2#33472] opened 2021-07-13 10:33 UTC
### Preconditions (*)

1.  Magento 2.4.2-p1
2. int Stores -> Configuraton -> General -> General -> Default country chose a default country a country with mandatory state and predefined list of states (such as Romania)
3. in Stores -> Configuraton -> General -> General set -> Allow countries select only the same country as above
4. enable in store pickup shipping method
5. add inventory source and set is a pickup location

### Steps to reproduce (*)

1. add product to cart
2. go to checkout
3. do *not* complete shipping address
4. select in store pickup
5. select store
6. select other shipping method so the shipping address form is shown

### Expected result (*)

1. state field is a dropdown with allowed states for the default country

### Actual result (*)

1. state field is text input

The only fix i was able to found is to select more than one country in the Allowed countries field

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2021-07-16 12:54
Unable to verify this issue on Magneto 2.4-develop branch as add inventory source and In-store pickup shipping method options are not available in 2.4-develop branch. Hence verified this issue on Magento 2.4.2-p1 version and the issue is reproducible:
Steps:  
1. Admin -> Stores -> Configuraton -> General -> General -> Default country chose a default country a country with mandatory state and predefined list of states (such as Romania)
2. Stores -> Configuraton -> General -> General set -> Allow countries select only the same country as above.
3. State Options - State is Required for "Romania"
4. Enable in store pickup shipping method (Stores - Configuration - Sales - Delivery Methods - In Store Delivery)
5. Add inventory source and enable use as a pickup location (Stores - Inventory - Sources)
6. Add new Stock and assign source (Stores - Inventory - Stocks)
7. Clear Cache, Reindex
8. Create a new simple product and assign the newly created source (Catalog - Products)
9.  Front-end - Login to the website using customer having shipping address saved already 
10. Add this product to cart
11. Go to checkout
12. Do not complete shipping address
13. select In Store pickup Delivery
14. Select store. (Try entering zip-code or city and clear the values )**Issue 1: Store is not displayed on typing city or postcode. User is able to select the store after clearing the values.**
15. Click on "Shipping" button again
15. select other shipping method so the shipping address form is shown Ex: Free or Flat Rate
16. If Shipping Address is pre-selected, click on "+New Address" button
**Issue: State field is text input but not a drop down**
![image](https://user-images.githubusercontent.com/60198231/125950580-e6c511e5-f583-42ac-a9b2-89e0a681e93c.png)

![image](https://user-images.githubusercontent.com/60198231/125950447-91a105ae-9331-41da-b7e3-b8415086e725.png)
![image](https://user-images.githubusercontent.com/60198231/125950475-d6a871d8-34e6-47b2-84de-394d238d7a1b.png)
![image](https://user-images.githubusercontent.com/60198231/125950632-7760373f-cfb7-457c-adda-9b77f53f6081.png)

**Expected behavior:** State field should be a dropdown
![image](https://user-images.githubusercontent.com/60198231/125950521-78def966-7fca-48c9-a3f3-8a1a3ac6196b.png)

**Comment by magento-engcom-team** [comment] 2021-07-16 12:56
:white_check_mark: Confirmed by @engcom-November 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-42863` were created

**Issue Available**: @engcom-November, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-November** [comment] 2021-07-27 10:32
Verified the issue again on Magento 2.4-develop branch by installing inventory-metapackage (ref [link)](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide) and the issue is not reproducible:
**Steps:**
1. Admin -> Stores -> Configuraton -> General -> General -> Default country chose a default country a country with mandatory state and predefined list of states (such as Romania)
2. Stores -> Configuraton -> General -> General set -> Allow countries select only the same country as above.
3. State Options - State is Required for "Romania"
4. Enable in store pickup shipping method (Stores - Configuration - Sales - Delivery Methods - In Store Delivery)
5. Add inventory source and enable use as a pickup location (Stores - Inventory - Sources)
6. Add new Stock and assign source (Stores - Inventory - Stocks)
7. Clear Cache, Reindex
8. Create a new simple product and assign the newly created source (Catalog - Products)
9. Front-end - Login to the website using customer
10. Add this product to cart
11. Go to checkout
12. Do not complete shipping address
13. select In Store pickup Delivery
14. Select store. (Try entering zip-code or city and clear the values )Issue 1: Store is not displayed on typing city or postcode. User is able to select the store after clearing the values.
15. Click on "Shipping" button again
16. select other shipping method so the shipping address form is shown Ex: Free or Flat Rate
17. If Shipping Address is pre-selected, click on "+New Address" button
**No issue:**State field is a drop-down but not a text field.
@andreif23, kindly re-check the issue on 2.4-develop branch and provide missing steps if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-08-10 06:09
@andreif23, we are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-08-10 06:09 UTC
Labels: Component: Shipping, Issue:  Cannot Reproduce, Progress: done, Issue: needs update, Reported on 2.4.2-p1
