### ISSUE TITLE
Paypal and cart issue for 2.1.9

### ISSUE THREAD

**Issue by alen9788** [magento/magento2#10959] opened 2017-09-19 11:48 UTC
### Preconditions

1. magneto 2.1.9  PHP7
2. 

### Steps to reproduce

1. After we upgrade to the latest 2.1.9
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]
The paypal method do not appear at the "check out" page. We did not make any changed for the paypal setting at our backend which worked well before the 2.1.9 version.
and also it said:" there is no item at the cart "although the item has been added.

**Comment by orlangur** [comment] 2017-09-19 11:55
From which version did you upgrade? Seems to be a duplicate of https://github.com/magento/magento2/issues/10499.

**Comment by alen9788** [comment] 2017-09-19 12:00
We upgraded it from the 2.1.8 to 2.1.9, maybe the issue happened for the version 2.1.8, we did not notice that. because we just used the 2.1.8 for one week. but we confirm that there is no such issue for the for the 2.1.5 we are using for another Magneto site.

**Comment by orlangur** [comment] 2017-09-19 12:03
Thanks for the quick reply! Let's close this issue then to keep the things consolidated.

**Closed as completed by orlangur** 2017-09-19 12:03 UTC
Labels: bug report, duplicate, Issue: Format is valid
