### ISSUE TITLE
Can't update store view specific labels of order statuses

### ISSUE THREAD

**Issue by MidnightDesign** [magento/magento2#4773] opened 2016-05-30 11:46 UTC
## Steps to reproduce
1. Open an order status in the admin area
2. Enter a new store view specific label without changing the status label
3. Hit "Save Status"
4. Open the same status again
## Expected result

The label you just entered is still there
## Actual result

The label is still the same

The problem is that [`isModified()`](https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php#L389) evaluates to `false`. If you change the status label too, `isModified()` returns `true` and the status is saved.

**Comment by NadiyaS** [comment] 2016-06-07 11:48
Hi @MidnightDesign ,
thank you for reporting this issue. 
Internal ticket MAGETWO-54003 was created

**Comment by pantaoran** [comment] 2016-08-04 09:08
I also found this bug just now on Magento 2.1.0. Looks like I will need to put this directly into the db instead.

**Comment by franckgarnier21** [comment] 2017-06-12 12:17
The bug is still present on Magento 2.1.7

**Comment by palvinder03** [comment] 2017-09-02 10:13
I have followed steps "Can't save order status label #7006" the but it's not working for me. I have stores and when try to save order status it's showing blank. [Store-> Order Status ] and update status lable for for each store

I have created file
Fixes #7006, sales_order_status_label does not support version control #7020
https://github.com/magento/magento2/blob/7cceda81d231d071b715068fa58afb3d6ead2af6/app/code/Magento/Sales/Model/ResourceModel/Order/Status.php

I am using magento 2.17

can any one tell what would be the issue?

**Comment by magento-engcom-team** [comment] 2017-10-18 10:42
@MidnightDesign, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-18 10:42 UTC
Labels: Issue: Ready for Work, bug report, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
