### ISSUE TITLE
Creditmemo Gift Cards (Partial Refund)

### ISSUE THREAD

**Issue by zepgram** [magento/magento2#36559] opened 2022-12-02 10:11 UTC
### Preconditions and environment

- Magento EE 2.4.5

### Steps to reproduce

1. Add 1 gift card product to the cart
2. Add 1 simple product or any other types
3. Place an order
4. Navigate to order detail in admin panel
5. Invoice the order
6. Navigate to invoce detail
7. Click Creditmemo
8. Create a Creditmemo for the the simple product

### Expected result

1. The gift card account should be kept

### Actual result

1. The gift card account is deleted

### Additional information

Take a look here, the reason is very simple
magento/vendor/magento/module-gift-card-account/Model/Plugin/CreditmemoRepository.php

   ```php
 /**
 * Remove gift card account for refund
 *
 * @param CreditmemoRepositoryInterface $subject
 * @param CreditmemoInterface $entity
 *
 * @return CreditmemoInterface
 *
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 */
public function afterSave(CreditmemoRepositoryInterface $subject, CreditmemoInterface $entity): CreditmemoInterface
{
    $order = ($entity->getOrder()) ?: $this->getOrderById((int)$entity->getOrderId());
    $orderItems = $this->getOrderItems($order);
    if ($orderItems) {
        foreach ($entity->getItems() as $creditMemoItem) {
            $orderItem = $orderItems[$creditMemoItem->getOrderItemId()];
            if ($orderItem->getProductOptionByCode('giftcard_created_codes')) {
                $this->removeGiftCardAccount(
                    $orderItem->getProductOptionByCode('giftcard_created_codes'),
                    abs((int)$creditMemoItem->getQty())
                );
            }
        }
    }

    return $entity;
}
```

The error is here:
```php
 foreach ($entity->getItems() as $creditMemoItem) {
```

Should be:
```php
 foreach ($entity->getAllItems() as $creditMemoItem) {
```

This way, we exclude the gift card item who has been previously deleted from the object (because she's not targeted by our creditmemo)

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-02 16:24
Hi @zepgram ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance with enterprise edition modules enabled but the issue is not reproducible with below steps performed.
**Steps performed:**
Placed an order from front end with gift card product and simple product. Created invoice from admin and credit memo for only simple product. No issue. Credit memo / refund created for only simple product as expected. No gift card account is deleted.
Kindly recheck the issue on Magento 2.4-develop instance with enterprise edition and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by zepgram** [comment] 2022-12-02 16:52
I don't know how you do, anytime I'm reporing something you cannot reproduce. Just look at the code, it's wrong anyway.

**Comment by engcom-November** [comment] 2022-12-05 15:07
Hi @zepgram ,
I verified the code in Magento 2.4-develop instance and the code is the same which mentioned by you but still unable to reproduce the issue. I rechecked again with Gift card type Virtual and Combination but could not able to reproduce the issue. Please find the below screenshots of the steps performed:
Steps performed:
1. Admin - Stores - Configuration - Sales - Gift cards - Created gift card 
2. Created Gift card product of Virtual type with open amount selected.
3. Login to Front end and added simple product and gift card product to cart
4. Proceed to checkout and paid with Gift card balance
5. Admin - Sales - Orders - Created invoice for both products
6. Credit memo created only for simple product.
No issue: If refund to store credit is selected - amount credited to store credit balance
Gift card account is not deleted. Balance deducted as expected.
![image](https://user-images.githubusercontent.com/60198231/205669559-d6d9401f-c097-4b2d-8088-28f8220c5f3e.png)
![image](https://user-images.githubusercontent.com/60198231/205670746-7df3ad41-abf7-4ca1-8d34-15da6ec1e0db.png)
Kindly let us know if you are using any third party extensions / modules and recheck on clean 2.4-develop enterprise edition instance, provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by zepgram** [comment] 2022-12-05 15:26
Then you must probably disable the store credit to reproduce

**Comment by engcom-November** [comment] 2022-12-07 11:06
Hi @zepgram ,
Thank you for the response. Verified the issue again on latest Magento 2.4-develop instance with enterprise edition modules enabled with below steps but the issue is still not reproducible.
**Steps performed:**
1. Disabled Store credit option from Admin (Stores - Settings - Configuration - Customers - Customer Configuration - Enable Store credit - No) and save
2. Reindex and clear cache
3. Created Gift card account from  - Marketing - Promotions - Gift Card Accounts
4. Created Gift card product and simple product
5. Front end - Added both the products to cart
6. Placed order using Gift card balance
7. Admin - Order details page - Created invoice for both the products
8. Credit Memo - Update Quantity 0 for gift card product and create credit memo only for simple product.
No issue: Credit memo created successfully and balance updated as expected in Gift card account. Gift card account is not deleted. Can you please check if the issue occurred due to any 3rd party extensions / modules enabled? Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and provide missing steps if any if the issue is still reproducible.
Thank you.
![image](https://user-images.githubusercontent.com/60198231/206163050-61730fa8-c8ac-4c25-8ec6-e6c484471e63.png)
![image](https://user-images.githubusercontent.com/60198231/206163106-f41a67fd-3170-4a16-afa4-76c60091cb07.png)
![image](https://user-images.githubusercontent.com/60198231/206163296-e0cdc976-7415-4108-afb5-b797c9e4e8ca.png)

**Comment by engcom-November** [comment] 2022-12-20 13:24
Hi @zepgram ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-12-20 13:24 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update

**Comment by zepgram** [comment] 2023-06-14 13:53
Quality patch available here: https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-32/acsd-51230-gift-card-account-is-deleted.html?lang=en
