### ISSUE TITLE
Can't load product's attribute set, when category_ids is outside the "General" group

### ISSUE THREAD

**Issue by Krossfire** [magento/magento2#21626] opened 2019-03-07 15:07 UTC
### Preconditions (*)

1. Magento 2.2.7, 2.3.0 - clean installs
2. PHP 7.1 (2.2.7), PHP7.2 (2.3.0)

### Steps to reproduce (*)

1. Create a new Attribute Set, based on the Default attribute set
2. When editing the new Attribute Set, move the "category_ids" attribute outside the General group (you can move it to any other existing group)
3. Save your new attribute set
4. Try to create a new product, and select your new attribute set in the "Attribute Set" dropdown

### Expected result (*)

Like usual - expected M2 to load selected attribute set

### Actual result (*)

1. M2 loads the attribute set
2. Then suddenly (and automatically) M2 tries to load attribute set 'unknown'
3. New product screen locks on "loading"

![attribute-set-bug](https://user-images.githubusercontent.com/6045529/53966154-e1703000-40f2-11e9-9bee-6878a1b6500e.png)
![attribute-set-bug-calls](https://user-images.githubusercontent.com/6045529/53966162-e46b2080-40f2-11e9-96f7-9c8b1be04836.png)
[m2.local-1551971074461.log](https://github.com/magento/magento2/files/2941866/m2.local-1551971074461.log)

**Comment by magento-engcom-team** [comment] 2019-03-07 15:07
Hi @Krossfire. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@Krossfire do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-08 10:17
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-08 10:18
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-08 10:18
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-08 10:20
Hi @shikhamis11, here is your [Magento instance](https://i-21626-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21626-2-3-develop.instances.magento-community.engineering/admin](https://i-21626-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-03-08 10:28
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-08 10:28
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-08 10:29
Hi @shikhamis11, here is your [Magento instance](https://i-21626-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21626-2-2-develop.instances.magento-community.engineering/admin](https://i-21626-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-03-08 10:38
@Krossfire Thank you for your report . this issue is not coming either on 2.3-develop and 2.2-develop instance. so I am closing this one message here if you still getting this issue on 2.2 of 2.3 develop instance

**Closed as completed by shikhamis11** 2019-03-08 10:38 UTC
Labels: Issue: Format is valid
