### ISSUE TITLE
Admin: Word should not broken to next line

### ISSUE THREAD

**Issue by cena4438** [magento/magento2#34466] opened 2021-10-28 10:46 UTC
Admin: Word should not broken to next line

### Preconditions (*)

1. Magento 2.4
2. Screen resolution: 1920 x 1080

### Steps to reproduce (*)

1. Admin -> Widgets -> Add new 
2. Next form -> see the word **Theme** break to next line
3. this happens in most of the forms

### Expected result (*)
Wording should not be break
![image](https://user-images.githubusercontent.com/92792212/139238135-45d173d5-b3c7-432e-b2c6-321d8a5362aa.png)

### Actual result (*)
![image](https://user-images.githubusercontent.com/92792212/139238168-b6771546-281e-4156-9693-7a86d953ee01.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by pablomishchenko** [comment] 2021-12-13 10:45
@magento I am working on this

**Comment by pablomishchenko** [comment] 2021-12-13 10:45
@magento add to contributors team

**Comment by pablomishchenko** [comment] 2021-12-13 10:46
@magento I am working on this

**Comment by pablomishchenko** [comment] 2022-01-04 21:06
Fix without changing translation is not possible, but changing translation is not allowed https://devdocs.magento.com/contributor-guide/backward-compatible-development/#translatable-phrases

**Comment by vass30** [comment] 2022-03-14 11:07
@magento I am working on this

**Comment by engcom-Bravo** [comment] 2024-08-06 06:31
Hi @cena4438,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="881" alt="Screenshot 2024-08-06 at 11 57 34" src="https://github.com/user-attachments/assets/0005ded6-ca02-4660-8d82-81ceb1ae4752">

Wording is not breaking.

Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-06 06:31 UTC
Labels: Issue: Confirmed, Component: Admin, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done, Issue: ready for confirmation, Area: Admin UI
