### ISSUE TITLE
Backlog reindexing of catalog_product_price

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#37681] opened 2023-06-28 06:59 UTC
### Preconditions and environment

- Magento version 2.4.6
- Having multiple websites

### Steps to reproduce

1. `bin/magento indexer:set-dimensions-mode catalog_product_price website`
3. Make changes in catalog product prices
4. Wait for `indexer_update_all_views` cron to execute

### Expected result

cron status = success

### Actual result

cron status = error

error :
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.catalog_product_index_price_ws0' doesn't exist
```

### Additional information

Note that with "none" dimension mode, it also fails due to this similar issue : https://github.com/magento/magento2/issues/15187

Since the backlog reindex is always crashing, it prevents other indexer from being reindexed via that cron. So it forces us to manually reindex regularly.

Another strange thing, if I set realtime mode to `catalog_product_price` index, I still get that error, even after manually reindex full index.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Jhone55** [comment] 2023-06-28 11:56
To perform a backlog reindexing of the catalog_product_price index in Magento, you can follow these steps:

Log in to your Magento admin panel.
Go to System > Index Management.
Locate the catalog_product_price index in the list of indexes.
Check if the index is marked as "Reindex Required" or "Update Required." If it is, proceed to the next steps. If it's not, you may not need to perform a backlog reindexing for this index page of [junk-removal-parker-co](https://haultogo.com/junk-removal-parker-co/).
If the index needs to be reindexed, click on the checkbox next to catalog_product_price to select it.
From the Actions dropdown, select "Update on Save" or "Reindex."
Note: The option "Update on Save" will update the index in real-time as you save changes to product prices. The option "Reindex" will initiate a full reindexing of the catalog_product_price index. Choose the option that best suits your requirements.

**Comment by engcom-Bravo** [comment] 2023-09-14 08:43
Hi @Nuranto,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.


**Steps to reproduce**

- bin/magento indexer:set-dimensions-mode catalog_product_price website
- Make changes in catalog product prices
- Wait for indexer_update_all_views cron to execute

<img width="1437" alt="Screenshot 2023-09-14 at 2 03 28 PM" src="https://github.com/magento/magento2/assets/51680745/d198a757-133f-4bad-8082-18e5c43294ee">




We got cron status = success


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-26 06:19
Hi @Nuranto,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-26 06:19 UTC
Labels: Issue: needs update, Reported on 2.4.6
