### ISSUE TITLE
Multi store get wrong value.

### ISSUE THREAD

**Issue by taimaiduc** [magento/magento2#14221] opened 2018-03-21 07:28 UTC
### Preconditions

1. PHP 7.0.27
2. MySQL Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
3. Vanish 4
4. Magento 2.1.10
### Steps to reproduce

1. Create a product (All store view) with a filed is textarea -> Save it
2. Edit product with another store view (Store view Vietnam) with field textarea _(uncheck Use Default Value )_ -> Save it

### Expected result

1. View product at store view Vietnam in the backend and front end the value from field textarea is from store view Vietnam.

### Actual result

1. View product at store view Vietnam in the backend and front end the value field textarea is from **all store view**.

After debuging we found the reason from
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Eav/Model/ResourceModel/ReadHandler.php#L132
```
$unionSelect = new \Magento\Framework\DB\Sql\UnionExpression(
                       $selects,
                       \Magento\Framework\DB\Select::SQL_UNION_ALL
                     );
```
**After unionSelect the result is not order By Store View Id.**
Use of ORDER BY for individual SELECT statements implies nothing about the order in which the rows appear in the final result because UNION by default produces an unordered set of rows
https://dev.mysql.com/doc/refman/5.7/en/union.html

To use an ORDER BY or LIMIT clause to sort or limit the entire UNION result, parenthesize the individual SELECT statements and place the ORDER BY or LIMIT after the last one

**After remove MySQL Ver 15.1 Distrib 10.0.33 and install MySql 5.7 the result is correct.**

**Comment by magento-engcom-team** [comment] 2018-03-21 12:51
Hello @taimaiduc. Thanks for reporting. Probably we have missed something essential for this issue reproduction, but currently we are not able to reproduce it. So please watch the attached video and tell us were we went wrong if so.
[SVtextarea.zip](https://github.com/magento/magento2/files/1833256/SVtextarea.zip)

**Comment by taimaiduc** [comment] 2018-03-22 03:12
@magento-engcom-team Thanks for your support.
Make sure you are using **10.0.33-MariaDB**
Can you create a new product attribute type is textarea.
 ![selection_2018-03-22-10 00 41](https://user-images.githubusercontent.com/10907980/37748905-14ce6d76-2db8-11e8-8a9d-b82c7c0cf43e.png)

In the description, you have to use. 
```
<p><strong>How does Rafferty's Garden develop their recipes?</strong><br />The primary basis to all our recipes is flavour but with consideration to baby&rsquo;s highly sensitive taste buds. Basically we select recipes that deliver on nutritional and healthy eating then set about refining these with baby in mind &ndash; simply put &lsquo;adult food for baby&rsquo;.<br />Don't forget, we always source the freshest ingredients including fruit and vegetables as well as prime cuts of meats.</p>
<p>&nbsp;</p>
<p><strong>How does Rafferty's Garden achieve a 12 month shelf life with no additives and no need to refrigerate?</strong><br />We are able to achieve this shelf life with our products due to the quality of ingredients combined with the mixture of heat treatment and our special packing process.<br />Our smooth products are cooked in much the same way as people have been preserving fruit and vegetables for centuries. This employs the use of the natural acidity found in fruits combined with a gentle heat treatment process. We take the greatest care in selecting only the finest raw ingredients while ensuring we do not remove any of the goodness, including taste through the cooking process.</p>
<p>&nbsp;</p>
<p><strong>How is it that we can achieve a 12 month shelf life for our 'Just Veggie' range?</strong><br />Our Just Veggie range are a retorted product so instead of high acid to preserve it, they are cooked in the same way as the puree range of products. This means they are prepared and cooked in large kettles before transferring into packaging for a final cooked process using pressurised heat equipment. Again, we are reinforcing the reduced cooking time due to flexible pouches and this helps retain the natural goodness of the ingredients. <br />And did you know that the minimal cooking time is the primary advantage of products make in flexible pouches vs cans and jars!</p>
<p>&nbsp;</p>
<p><strong>How is the cooking process different for Rafferty's Garden product? (from other manufacturers)</strong><br />Rafferty&rsquo;s Garden has a couple of methods on how we prepare our baby food.<br />Our smooth range is produced using hot fill. The products are cooked for the minimum time required, using the natural acidity of the ingredients as preservatives, while locking in the natural goodness and flavours. This is a process that has been used for centuries by people when preserving fruit and vegetables at home.<br />Our puree and lumpy range is prepared and cooked in large kettles before transferring into our pouches for a final cooked process using pressurised heat equipment. The reduced cooking time and our flexible pouches help retain the natural goodness of the ingredients.<br />Rafferty&rsquo;s Garden uses the greatest care and attention when selecting the finest raw ingredients while ensuring that we do not remove any of the goodness, including taste. Simply put our recipes are better &ndash; packed full of good quality ingredients, flavour combined with a gentle cooking process.</p>
<p>&nbsp;</p>
<p><strong>Can you freeze Rafferty's Garden products?</strong><br />As the food is 100% natural and there are no additives so it is fine to freeze and then later defrost the products after they have been packed in an airtight container. Please ensure that you exclude as much air as possible to prevent freezer burn. Defrost ONLY in your refrigerator and consume this product immediately after it is defrosted</p>
<p>&nbsp;</p>
<p><strong>How does Rafferty's Garden address allergies?</strong><br />Our range is designed and produced with significant input and controls from allergen experts and are produced and packed in a dedicated plant that do not pack allergens such as wheat, egg or nuts. The products are regularly tested for the presence of such allergens and we have not had any such allergens detected. Likewise we wish to stress that the ingredients listed on the packets are a complete reflection of what is in our products, there are no &ldquo;extra ingredients&rdquo;.<br /><a href="https://www.raffertysgarden.com.au/media/wysiwyg/RaffertysGarden/Allergy/Raffertys_Garden_Allergen_Matrix_Oct_2016.pdf">Click here</a> to view the complete allergens table for Rafferty&rsquo;s Garden products.</p>
<p>&nbsp;</p>
<p><strong>Why is there apple in so many smooth products?</strong><br />Apple is used in our smooth range to help balance the natural acidity levels so we can achieve a shelf life of 12 months without having to add any extra nasties to our food.<br />Did you know that apples contain pectin, a gentle dietary fibre that helps your baby's digestive system.</p>
<p>&nbsp;</p>
<p><strong>Are your products halal certified? If so, which ones are halal certified?</strong><br />Rafferty&rsquo;s Garden has a number of halal certified products. We make baby food for all babies irrespective of race or religion of their parents. We do not discriminate in any way. We have a number of products that have received halal certification. We have not altered our products from their original recipe. <a href="http://magento-elec.pzcussons.com/media/wysiwyg/RaffertysGarden/FAQs/Raffertys-Garden-Halal-Certified-Products-02.2017.pdf">Click here</a> for a link to a list of halal certified products.</p>
<p>&nbsp;</p>
<p><strong>Why does the Rafferty&rsquo;s Garden pouch now have a little magnifying glass icon on its packaging?</strong><br />The magnifying glass directs you to extra information on the front of our pouches: &ldquo;Given ingredient, seasonality, very small amounts of fruit acidity may be added to some of our fruit and veggies range to ensure product quality&rdquo;.<br />But what does this mean?<br />Well, our Smooth products are cooked in much the same way as people have been preserving fruit and vegetables for centuries. This employs the use of fruit acids, to balance the seasonal changes in natural fruit acids and ensure the safety of the product. For the majority of our Smooth products, we use natural acidity found in fruits combined with a gentle heat treatment process, but sometimes due to seasonality, some of our fruit and veggies are not as acidic as they should be. Because of this, we occasionally need to add a very small amount of Fruit Acid (Citric Acid or Ascorbic Acid) to our pouches.<br />By using this process, we do not have to heat our Smooth foods to higher than is absolutely necessary, keeping in all the nutrients and yummy flavours for your little foodie to enjoy.</p>
```

In Ingredient paragraph field you have to use. 
```
Apple Paste 40% [Apple Puree Concentrate (48%), Sugar, Glucose, Humectant (Glycerol), Wheat Fibre, Citrus Fibre, Acid (Malic), Natural Flavour, Ground Cinnamon], Wheat Flour, Dextrose, Water, Wholegrain Oat Flour (4%), Butter (Contains Milk), Sugar, Whey Powder (From Milk), Humectant (Glycerol), Canola Oil, Raising Agent (500, 450, 341, 541), Whey Protein Concentrate (From Milk), Natural Flavour, Emulsifier (Soy Lecithin), Caramelised Sugar, Ground Cinnamon. 
Contains: Gluten Containing Cereals, Soy and Milk Products
```
After that please change Ingredient paragraph in Vietnam store view.

This is SQL we debug. The results are wrong when using **10.0.33-MariaDB**

```
(SELECT `t`.`value`, `t`.`attribute_id` FROM `catalog_product_entity_varchar` AS `t` WHERE (entity_id = '123') AND (`store_id` IN ('1', 0)) ORDER BY `t`.`store_id` DESC
)UNION ALL(SELECT `t`.`value`, `t`.`attribute_id` FROM `catalog_product_entity_text` AS `t` WHERE (entity_id = '123') AND (`store_id` IN ('1', 0)) ORDER BY `t`.`store_id` DESC
)UNION ALL(SELECT `t`.`value`, `t`.`attribute_id` FROM `catalog_product_entity_decimal` AS `t` WHERE (entity_id = '123') AND (`store_id` IN ('1', 0)) ORDER BY `t`.`store_id` DESC
)UNION ALL(SELECT `t`.`value`, `t`.`attribute_id` FROM `catalog_product_entity_datetime` AS `t` WHERE (entity_id = '123') AND (`store_id` IN ('1', 0)) ORDER BY `t`.`store_id` DESC
)UNION ALL(SELECT `t`.`value`, `t`.`attribute_id` FROM `catalog_product_entity_int` AS `t` WHERE (entity_id = '123') AND (`store_id` IN ('1', 0)) ORDER BY `t`.`store_id` DESC
)
```

**_I can make a video for you later because on my production are runing Mysql 5.7 and i can not reinstall it._**

**Comment by magento-engcom-team** [comment] 2018-03-23 08:55
Ok, @taimaiduc, for now we've had a ready to use instance with 10.0.30-MariaDB, but the issue is still not reproduced on it. Later we'll try to repeat it using 10.0.33-MariaDB. Do You think that last digit is critical for reproduction?

**Comment by taimaiduc** [comment] 2018-03-26 03:29
Maybe not I think. I will try record video for you.

**Comment by taimaiduc** [comment] 2018-03-30 05:12
Wrong value when using MariaDB
@magento-engcom-team  
https://www.useloom.com/share/b69b6bcdb12643b5a20e824de1c8cc5b

**Comment by magento-engcom-team** [comment] 2018-03-30 08:26
Thank You @taimaiduc. By the way we also have tried with 10.0.34-MariaDB just as in Your video, but obtained no positive result again. May we ask You to try to reproduce Your issue on a clear fresh instance of Magento. Just download a fresh instance to Your server from the official website, create a new empty database for it. Don't add there any custom modules, extensions, themes, whatsoever else. Create two store views, an attribute and a product and try to reproduce it. Probably the main cause of the issue is not Maria-DB itself but something else concerning customization or the very server.

**Comment by taimaiduc** [comment] 2018-04-09 02:47
Sound like the same on this #6958 @magento-engcom-team

**Comment by magento-engcom-team** [comment] 2018-04-20 08:36
@taimaiduc Thank you for finding another issue.
I would suggest to continue tracking under that reference.

Closing

**Closed as completed by magento-engcom-team** 2018-04-20 08:36 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Format is valid
