### ISSUE TITLE
Cannot load and execute third party .js in .phtml

### ISSUE THREAD

**Issue by huuquyasb** [magento/magento2#24525] opened 2019-09-09 09:13 UTC
### Preconditions (*)
1. Magento 2.3.2  & 2.3-develop
### Steps to reproduce (*)
 1 .Added  into `header.phtml`
`<div class="zalo-share-button" data-href="https://magento.com/" data-oaid="579745863508352884" data-layout="2" data-color="blue" data-customize=false></div>`
And 
`<script src="https://sp.zalo.me/plugins/sdk.js"></script>`

### Expected result (*)
1. Iframe created
for example:
https://codepen.io/huuquyasb/pen/yLBvGbr
http://prntscr.com/p3oi2a

### Actual result (*)
2. Not load js from sdk.js, and cannot create iframe.

Hopefully somebody can help.
Thanks for reading this.

**Comment by magento-engcom-team** [comment] 2019-09-09 12:57
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-19942` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by jmcharadva** [comment] 2019-09-17 10:44
@huuquyasb 
I have used third party js in magento. I have mentioned steps for integration. Please check it and let me know if you have any query.

Follow below steps for integrating third-party js in magento2

Here, I have taken theme name is <ecommerce/theme>

1) Download third party js into your theme js directory.
	
	app/design/frontend/ecommerce/theme/web/js/<Your Js file> "here we are using myApp.js"

2) Register your theme in the requirejs-config.js file.
	
	var config = {
	    map: {
	        
	    },
	    paths: {
	        
	        myApp: 'js/myApp',
	    },
	    shim: {
	        'myApp': {
	            deps: ['jquery']
	        },
	    }
	};

	the requirejs-config.js file is located on your theme directory so, it will be on below path.
		
	app/design/frontend/ecommerce/theme

3) In phtml file call js using below code.

	<script>
        require(['jquery','myApp'], function($){ 
            mainApp.initSomeFunction();
        });
    </script>

4) js file content will look like this.

	var mainApp = {
    	initSomeFunction: function () {
    	
    	},
    }

**Comment by krzksz** [comment] 2019-12-02 19:13
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-12-02 19:13
Hi @krzksz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-12-02 19:13
Hi @krzksz, here is your [Magento instance](https://i-24525-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24525-2-3-develop.instances.magento-community.engineering/admin](https://i-24525-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krzksz** [comment] 2019-12-02 19:24
I cannot reproduce the issue with JS not loading so it seems to be an issue with the script itself.
<img width="893" alt="obraz" src="https://user-images.githubusercontent.com/829189/69988197-7482ad00-1541-11ea-8857-de03b7238c7b.png">
There is also a nice guide in DevDocs on loading JavaScript so please check that: https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/js_overview.html

**Closed as completed by krzksz** 2019-12-02 19:24 UTC
Labels: Issue: Ready for Work, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: View
