### ISSUE TITLE
Missed form validation in Admin Order Address Edit route sales/order/address

### ISSUE THREAD

**Issue by ilnytskyi** [magento/magento2#19360] opened 2018-11-23 10:02 UTC
### Preconditions (*)

Magento 2.2.* 
EAV validation rules are not checked during editing an address in order.
route: sales/order/address
See column **validate_rules** in table **customer_eav_attribute**
e.g. name may have '{"max_text_length":255}'
Controller: **\Magento\Sales\Controller\Adminhtml\Order\AddressSave::execute**

This rules work in other forms on fronted and in address form and during creating new order from Admin
route: sales/order_create/index/

### Steps to reproduce (*)

1. Create an order
2. Find the order in admin
3. Click edit on address section
4. Fill the field firstname or lastname with any characters till length be more than 255
5. Save address and see saved value

### Expected result (*)

1. The errors should be shown e.g.
Shipping Address: "First Name" length must be equal or less than 255 characters.
Billing Address: "First Name" length must be equal or less than 255 characters.
2. Address should not be saved as in **sales/order_create/index**
![selection_005](https://user-images.githubusercontent.com/3192770/48937581-dbbd5880-ef0e-11e8-8c08-57affc69dde3.png)

### Actual result (*)

1. Form saves and invalid data shown on the page
![selection_004](https://user-images.githubusercontent.com/3192770/48937532-b0d30480-ef0e-11e8-9ca5-ca3e94de3165.png)
**UPD**: so on the screenshot there is concatination with lastname. 
Max length in DB is 255 so it relates to max value. 
But if we set the rule to e.g. 100 symbols in **customer_eav_attribute** it's still possible to save 255 characters from  this form

**Comment by magento-engcom-team** [comment] 2018-11-23 10:02
Hi @ilnytskyi. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ilnytskyi do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-23 10:03
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by ilnytskyi** [comment] 2018-11-23 10:33
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment] 2018-11-23 10:33
Hi @ilnytskyi. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment] 2018-11-23 10:34
Hi @ilnytskyi, here is your [Magento instance](https://i-19360-2-2-5.instances.magento-community.engineering).
Admin access: [https://i-19360-2-2-5.instances.magento-community.engineering/admin](https://i-19360-2-2-5.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2018-11-23 10:42
@engcom-backlog-andrii Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96613`, `MAGETWO-96614` were created

**Comment by magento-engcom-team** [comment] 2018-11-23 12:19
Hi @viral-wagento. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2018-11-24 04:58
Hi @ravi-chandra3197. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-30 12:50
Hi @XxXgeoXxX. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-16 15:00
Hi @ilnytskyi. Thank you for your report. 
The issue has been fixed in magento/magento2#20840 by @XxXgeoXxX in 2.3-develop branch
Related commit(s):
 - [54469ce4307776cf5e5beedb002ef8b5775da51e](https://github.com/magento/magento2/commit/54469ce4307776cf5e5beedb002ef8b5775da51e)
 - [464e9817dee6dd9c0f15d3b7823e70a84ff6e2b4](https://github.com/magento/magento2/commit/464e9817dee6dd9c0f15d3b7823e70a84ff6e2b4)
 - [7b8e969747b4ecefbfcf407cfabe11a4ff08e3c7](https://github.com/magento/magento2/commit/7b8e969747b4ecefbfcf407cfabe11a4ff08e3c7)
 - [fd4ed41edfd534a1037f13c21aa9d16a8d07c37a](https://github.com/magento/magento2/commit/fd4ed41edfd534a1037f13c21aa9d16a8d07c37a)
 - [7d6cca6c944eb694d40ae169fe8443bbd75486c8](https://github.com/magento/magento2/commit/7d6cca6c944eb694d40ae169fe8443bbd75486c8)
 - [8b99ea2db4a117ec50b5decf84c6012d91c856ce](https://github.com/magento/magento2/commit/8b99ea2db4a117ec50b5decf84c6012d91c856ce)
 - [5867a48a5e7ab3ac7e5bad35e98db1b2b4d8b35c](https://github.com/magento/magento2/commit/5867a48a5e7ab3ac7e5bad35e98db1b2b4d8b35c)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-16 15:00 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
