### ISSUE TITLE
Unrelated attribute error - The value of attribute "name_of_attribute" must be set [Magento 2.1.4]

### ISSUE THREAD

**Issue by tipofloe** [magento/magento2#9245] opened 2017-04-14 04:38 UTC
### Preconditions
1. Magento 2.1.4
2. CenOS 6.9, MySQL 5.6.35, PHP 7.0.17, Apache 2.4.25

### Steps to reproduce
1. Create new required product attribute "test_required" and add it to default attribute set.
2. Create attribute set "set_required", based on default. Remove from created attribute set attribute "test_required".
3. Create simple product "Simple1" (Products - Add Product).
3. Go to Products - Add Product - Grouped Product - and create a product based on an attribute set "set_required".
4. Fill out the pertinent information for the product and then add product "Simple1" to group.  
5. Save product.

### Expected result
1. The Grouped Product should be created

### Actual result
1. An error message appears "The value of attribute "bra_band_size" must be set, an attribute that is not being used to create the Grouped Product.  
https://www.dropbox.com/s/7nqysiff600qonj/Unrelated%20value%20of%20attribute%20error.mp4?dl=0

**Comment by magento-engcom-team** [comment] 2017-10-10 13:05
Description updated.

**Comment by magento-engcom-team** [comment] 2017-10-10 15:30
@tipofloe, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 15:30 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid
