### ISSUE TITLE
Unable to add new address on checkout

### ISSUE THREAD

**Issue by astvdurnev** [magento/magento2#28221] opened 2020-05-14 12:07 UTC
### Preconditions (*)
1. Magento 2.3.4(release)

### Steps to reproduce (*)
1. Login as a customer with saved addresses
2. Add product to cart
3. Open website in incognito mode or clean all cookies and local storage
4. Login as a customer from step 1
5. Go to checkout
6. Add new address
7. Select shipping method and click "Continue to payment"

### Expected result (*)

1. Payment step is opened

### Actual result (*)
1. Error message "Please specify a regionId in shipping address." is shown

### Additional info
1. customer data section `directory-data` is empty @see app/vendor/magento/module-checkout/view/frontend/web/js/model/address-converter.js:46
2. Caused by https://github.com/magento/magento2/commit/73ba36616fbd3244b75ef07129aeb967c299765f

**Comment by krishprakash** [comment] 2020-05-30 09:40
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-30 09:40
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-30 09:41
Hi @krishprakash, here is your [Magento instance](https://i-28221-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28221-2-4-develop.instances.magento-community.engineering/admin_fc36](https://i-28221-2-4-develop.instances.magento-community.engineering/admin_fc36)
Login: `8cf1d4b6` Password: `8f7710200e4c`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-05-30 09:58
Hi @AstoundJenkins.
Not able to reproduce the issue as provided steps by you
Kindly provide more detailed steps with video link if possible so It will help to reproduce issue here
Thanks

**Comment by ben91376** [comment] 2020-06-05 17:32
Today, I was on a demo with our client in a staging environment V2.3.5-p1 and encountered the same error in the original description.  At some point, the "State" value was removed from my saved address.    So during checkout, I was able to see my state (South Carolina) in my address; however, in the admin, I accessed my address again and the state value was missing.    Once I added my state again and saved my address, I was able to checkout successfully.    At no point, did I provide an action that removed the state value.

**Comment by happymachines** [comment] 2020-06-10 01:55
@astvdurnev I was running into the same issue, it turns out the issue stemmed from a theme override of the file `vendor/magento/module-customer/view/frontend/web/js/section-config.js`. The theme override in my case was missing the changes that appeared in this commit https://github.com/magento/magento2/commit/d57d43a0bf0e620f006fbca9562f70dc3bdc1036#diff-82971003fd8862a51cf2b4e47b34733a

**Comment by astvdurnev** [comment] 2020-06-11 19:55
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-06-11 19:55
Hi @astvdurnev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-06-11 19:56
Hi @astvdurnev, here is your [Magento instance](https://i-28221-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28221-2-4-develop.instances.magento-community.engineering/admin_f4c8](https://i-28221-2-4-develop.instances.magento-community.engineering/admin_f4c8)
Login: `a268848d` Password: `7efe6e44b5cc`
Instance will be terminated in up to 3 hours.

**Comment by Dnd-Mafer** [comment] 2020-06-19 15:50
I had the same issue 100% of the time : `customer/online_customers/section_data_lifetime` configuration was set to "" in database ...

**Comment by grichards** [comment] 2020-06-21 18:49
I am experiencing the same issue in 2.3.4. 

As a logged in user who already has a saved address, if I attempt to add a new address, the State / Region does not save.

**Comment by erikhansen** [comment] 2020-08-04 02:10
One of my merchants running 2.3.4-p2 had a customer report this issue to them. However I logged in as that customer (using [this extension](https://github.com/magefan/module-login-as-customer)) and was able to add a new address just fine. Has anyone come up with steps to consistently reproduce this issue on Magento 2.3.x?

**Comment by paras89** [comment] 2020-09-18 10:21
I was able to reproduce the issue using the steps given in steps to reproduce on Magento 2.3.5-p2. 

Used the JS debugger to figure the error was coming from here: https://github.com/magento/magento2/blob/2.3.5-p2/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L340

On that line, the code looks for region in the shippingAddress observable but when saving a new address for a not logged in user, in this case Magento is not setting the "region" property on the shippingAddress object, instead only regionId is set since the name of the region dropdown field for US is regionId. 

As a workaround on line 212 of shipping.js I would add:
var regionSelector = '#co-shipping-form select[name=region_id] option:selected';
                if (addressData['region_id'] == $(regionSelector).val()) {
                    addressData['region'] = $(regionSelector).text();
                }

This is not the perfect framework fix, but should be safe enough for anyone looking to resolve this important checkout issue.

**Comment by engcom-Bravo** [comment] 2020-10-22 08:51
Hello @astvdurnev 

Thank you for your report. 

This issue seems to be fixed on the latest Magento 2.4-develop version.

Manual testing scenario:
1. Login as a customer with saved addresses
2. Add product to cart
![Login](https://user-images.githubusercontent.com/51680745/96847746-3a254580-145c-11eb-94f8-4c601089b370.png)
3. Open website in incognito mode or clean all cookies and local storage
4. Login as a customer from step 1
5. Go to checkout
6. Add new address
![Add new address](https://user-images.githubusercontent.com/51680745/96847836-52956000-145c-11eb-85ac-eee2f26616f0.png)
7. Select shipping method and click "Continue to payment"

Actual result: Payment Method page appears without errors
![Place order page](https://user-images.githubusercontent.com/51680745/96848186-c899c700-145c-11eb-9317-03db6f3c7d95.png)

We are closing this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines]

**Closed as completed by engcom-Bravo** 2020-10-22 08:51 UTC
Labels: Reported on 2.3.4

**Comment by nickpiro** [comment] 2021-02-15 19:19
So this is closed because it's fixed in 2.4.x? But where was it fixed? We're running 2.3.6, how do we correct it there!?

**Comment by pyyick** [comment] 2021-07-23 03:42
I can confirm @paras89 method works. If you have the same issue please apply his fix.

**Comment by sunilit42** [comment] 2022-07-06 10:30
https://github.com/magento give me 2.4-develop instance

**Comment by sunilit42** [comment] 2022-07-06 10:33
@magento give me 2.4-develop instance

**Comment by Stoyvo** [comment] 2022-09-05 02:34
I was able to recreate this. Magento 2.4.4

A customer is signed into their account, with no address saved.
An admin will create an address for the customer (billing, shipping are the same).
Customer will add items to cart and proceed to checkout.
Customer will not be able to proceed to Payment step.
Address shown to customer is missing region (Eg: Alberta in Canada is missing)
Admin can see province/region assigned to the customer in their saved addresses.

If customer signs out, flushes all cookies/local storage, and signs back in, then the checkout process will work.

**Comment by erikhansen** [comment] 2024-03-05 21:51
@paras89 We've been continuing to experience this issue on Magento Commerce `2.4.4-p6`. [Your solution](https://github.com/magento/magento2/issues/28221#issuecomment-694786633) helped workaround the issue, thanks. 

For everyone else's benefit, I added this code:

```
                // BEGIN EDIT - Fix issue with "Please specify a regionId in shipping address" for small subset of logged in customers
                // See https://github.com/magento/magento2/issues/28221#issuecomment-694786633 for context
                var regionSelector = '#co-shipping-form select[name=region_id] option:selected';
                if (addressData['region_id'] == $(regionSelector).val()) {
                    addressData['region'] = $(regionSelector).text();
                }
                // END EDIT
```


Below this line: https://github.com/magento/magento2/blob/2.4.4-p6/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L244
