### ISSUE TITLE
Magento 2.1.2 rating stars icons not available

### ISSUE THREAD

**Issue by FloWord** [magento/magento2#9128] opened 2017-04-04 14:10 UTC
### Preconditions

1. Magento 2.1.2
2. Create new parent theme of default magento theme "luma"

### Steps to reproduce

1. Enable Ratings, Stores->Attributes->Ratings
2. Go to the product detail page on frontpage of your new parent theme

### Expected result

1. You see the ratings stars are not correct available

### Actual result

1. You see the rating stars with an grey arrow and if you hover over the arrows you see the red stars.
![ntut4](https://cloud.githubusercontent.com/assets/21309911/24660780/bbfd9d6a-1950-11e7-803b-68c6e57e314b.jpg)

How can i fix that Problem and the rating stars are showing like an star, not like an arrows?
Thanks for any help.

**Comment by korostii** [comment] 2017-04-06 10:17
If you are looking for an advice regarding setup or development please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](http://magento.stackexchange.com/).

The GitHub issue tracker is intended for tracking technical issues (read: "bugs") only.
The issues which cannot be consistently reproduced on a clean installation of Magento 2 CE aren't likely to get resolved in here.

**Closed as completed** 2017-09-29 12:51 UTC
Labels: Issue: Format is valid
