### ISSUE TITLE
issue with meta description

### ISSUE THREAD

**Issue by fvillata** [magento/magento2#5107] opened 2016-06-20 11:21 UTC
## Steps to reproduce
1. Create a new product and insert a description more than 255 characters long and with html tags.
2. Don't edit Meta Description attribute ( in search engine optimization tab)
3. Save product.
## Expected result
1. Save product and leave meta description empty or with the content of the description attribute without html tags.
## Actual result
1. Can't save the product and get error message "Maximum length of this field must be equal or less than 255 symbols" for meta description attribute.
2. Reducing characters to < 255, I can save the product but the meta description in frontend appears with html tags. 

Not a severe issue but actually this force editing meta description attribute when creating products.

**Comment by antboiko** [comment] 2016-06-21 12:46
Hi @fvillata , I cannot reproduce this issue on 2.1 - rc3. The issue with HTML tags in Meta Description was fixed and will be available in 2.1 release.

I'm closing this ticket. Please feel free to reopen if it's needed.

Thanks,
Anton.

**Closed as completed by antboiko** 2016-06-21 12:46 UTC
