### ISSUE TITLE
Two Factor Authenticator Login Issue

### ISSUE THREAD

**Issue by drinkingsouls** [magento/magento2#38597] opened 2024-04-09 15:47 UTC
### Preconditions and environment

We've just updated from Magento 2.4.6-p4 to 2.4.7
After upgrading, we are unable to login with Two Factor Authentication enabled.
If we disable the Magento Two Factor Authentication modules then we can login.

### Steps to reproduce

- Navigate to Magento admin login page
- Enter username & password
- Enter 2FA - Google Authenticator Code

### Expected result

- Admin is logged in successfully

### Actual result

- Admin is not logged in.
- Message _There was an internal error trying to verify your code_ is shown.
- system.log populated with: `main.ERROR: The leeway must be lower than the TOTP period`

![internal-error](https://github.com/magento/magento2/assets/45666862/5b92d812-a4e3-4fa7-8324-ce0d08ca7081)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by nathanjosiah** [comment] 2024-04-09 18:58
The issue appears to be due to an update with how otphp validates the window setting. This is controlled with the commerce configuration setting `twofactorauth/google/otp_window` which must be customized to see this error.

Basically, this setting was not previously validated by the third party library and now it is.

Try setting it to something else e.g. `bin/magento twofactorauth/google/otp_window 1`

**Comment by drinkingsouls** [comment] 2024-04-10 11:01
@nathanjosiah Thank you, setting the value to lower than 30 (Google default value) seemed to work.
`bin/magento twofactorauth/google/otp_window 29`

**Comment by nathanjosiah** [comment] 2024-04-16 13:57
We are going to make some changes to core as a result of this so I'm going to reopen the ticket. The work is tracked in AC-11762

**Comment by engcom-Dash** [comment] 2024-04-17 11:08
Hi @drinkingsouls 

Thanks for reporting and collaboration.

Verified the issue on 2.4.7 after upgrading from 2.4.6-p2 but the issue is not reproducable.

We are able to get the 2FA - Google Authenticator Code and able to login into admin.

Steps to reproduce

1. Navigate to Magento admin login page
2. Enter username & password
3. Enter 2FA - Google Authenticator Code

Please refer the attached screenshots.Let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-04-17 at 4 37 41 PM" src="https://github.com/magento/magento2/assets/60198592/0d421322-be5c-4511-a4e9-dcd87a87185b">

<img width="1440" alt="Screenshot 2024-04-17 at 4 38 00 PM" src="https://github.com/magento/magento2/assets/60198592/d88313ac-2a84-4d62-97fc-681e1f97d7bd">

**Comment by engcom-Dash** [comment] 2024-04-29 05:43
Hi @drinkingsouls 

We have noticed that this issue has not been updated for long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel free to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-04-29 05:43 UTC
Labels: Issue: needs update, Reported on 2.4.7

**Comment by webshotNL** [comment] 2024-08-28 12:46
Same issue after 2.4.5-p8 patch. We have created this module to overwrite the content in the layout file of the login page.
[TFA-fix-module.zip](https://github.com/user-attachments/files/16783526/TFA-fix-module.zip)
