### ISSUE TITLE
subtotal_with_discount includes shipping discount

### ISSUE THREAD

**Issue by thehl** [magento/magento2#34650] opened 2021-11-16 16:06 UTC
### Preconditions (*)
1. Magento 2.4.3-p1
2. Setup shipping method flatrate like this:
![freeshippingmethod](https://user-images.githubusercontent.com/1321326/142019032-76749190-7b04-4bd4-afce-1b12abb52f6c.png)
3. Setup freeshipping salesrule like this:
![freeshippingrule](https://user-images.githubusercontent.com/1321326/142019087-036de3c6-1b2e-4518-89e0-8a18ea182bd2.png)
4. Setup tax settings like this:
![taxsettings](https://user-images.githubusercontent.com/1321326/142019939-62ff8dd3-7a1e-4728-ae30-3a105cb6ae67.png)
Note: Actions - to add sku: (Stores - Configuration - Product - Attributes - Search for SKU - Store-front Properties - Use for Promo Rule Conditions - set to Yes)
Cart Price Rule - Actions - Add as below:
![image](https://user-images.githubusercontent.com/60198231/156773855-ab5bf070-d800-4b77-88d9-cb4dd27f1cac.png)
5. Tax Setup is 19% for Germany
6. Shipping Settings - Country: Germany
7. Store Information: Germany
8. Currency setup: Euro
9. Product Price is 5€ including taxes

### Steps to reproduce (*)
1. Add product with qty 1 to cart
2. Use shipping address with country Germany
3. Get cart totals

### Expected result (*)
1. subtotal_with_discount should be 4.20€, because the product has no discount and the subtotal doesn't include shipping amounts.

### Actual result (*)
1. subtotal_with_discount is -0.75€ and the calculation seems to be like this: 
`subtotal - discount_amount`
2. The subtotal doesn't include the shipping amount, but the discount_amount includes the shipping discount amount (incl tax.)
![subtotalwithdiscountfield](https://user-images.githubusercontent.com/1321326/142021379-a8189d21-4994-4303-8332-1c7c867adf67.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by itsmemagento** [comment] 2021-12-16 16:34
Hi @thehl  @engcom-Hotel  Is there any fix for this issue ?

**Comment by arjunadobe** [comment] 2021-12-16 16:35
I am also facing the same issue in Magento 2.4.3-p1

**Comment by itsmemagento** [comment] 2021-12-16 16:36
I am also facing the same issue in Magento 2.4.3-p1

**Comment by engcom-November** [comment] 2021-12-28 12:19
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue:
Since Cart Price Rule is applied to Shipping amount as well, Discount amount is applied to subtotal and shipping amount.
![image](https://user-images.githubusercontent.com/60198231/147565267-0f302b9f-f3a6-4e25-b747-41c8c18d4778.png)
Verified  DB tables sales_order, quote and quote_item tables but none of the tables have "subtotal_with_discount" column.
Kindly recheck the issue on Magento 2.4-develop branch, enable Cross Border Trade for international shipping and elaborate the steps: DB table to reproduce the issue.
Thank you.

**Comment by thehl** [comment] 2022-01-13 10:59
@engcom-November Hi, when using the following API Endpoint:

/rest/{{storeCode}}/V1/guest-carts/{{cartId}}/totals

You can't see the field "subtotal_with_discount" in the response? It's also in the quote and quote_address table on my vanilla test environment, can also recheck if it's gone now, but I would be surprised if it has been deleted. At least it's included in version "2.4.3-p1".

**Comment by engcom-Hotel** [comment] 2022-02-07 13:03
Hello @thehl,

We are reopening this issue for further analysis.

Thanks

**Comment by engcom-Hotel** [comment] 2022-02-08 07:57
Hello @thehl,

We have tried to reproduce the issue in Magento 2.4-develop branch. In the above steps, we have confusion in 3rd step:


> * Setup freeshipping salesrule like this:
>   ![freeshippingrule](https://user-images.githubusercontent.com/1321326/142019087-036de3c6-1b2e-4518-89e0-8a18ea182bd2.png)

We are not able to find the condition mentioned in your screenshot. Please have a look into below screenshot of our instance for reference:

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/51681618/152942735-3dbfa699-e883-4cd2-a446-561519be4f69.png">

Thanks

**Comment by thehl** [comment] 2022-02-16 07:17
@engcom-Hotel Ok, then the SKU attribute isn't unlocked to use it in sales rule, but this is no problem, you can also just use "Category" for example with a "fake" value that does not match.

**Comment by engcom-Hotel** [comment] 2022-02-21 06:47
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-23 08:56
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-04 13:35
Verified the issue on Magento 2.4-develop branch and the issue is reproducible
![image](https://user-images.githubusercontent.com/60198231/156772741-c7ac3b0f-4e5d-45e6-8177-506cb45d7f86.png)
![image](https://user-images.githubusercontent.com/60198231/156772840-1b3a960b-5402-49c9-a68b-fd76f116f901.png)

**Comment by engcom-November** [comment] 2022-05-20 13:37
Hi @thehl ,
We got the confirmation from PO that this is an expected behavior but not a bug.
This rule is configured to apply discount on subtotal and shipping and this is what happens based on the calculation.
Not to apply discount on subtotal, the rule should have action condition limiting the rule. Hence we are closing this issue. Kindly reopen/create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-05-20 13:37 UTC
Labels: Issue: Confirmed, Component: DB, Reproduced on 2.4.x, Priority: P1, Progress: done, Area: Payments, Reported on 2.4.3-p1
