### ISSUE TITLE
All products are redirecting to 404 eror page in magento 2.0

### ISSUE THREAD

**Issue by bacd** [magento/magento2#8558] opened 2017-02-15 06:28 UTC
When I click on products in home page of my website, it is redirecting to some error page i.e u have typed wrong url. I am using magento 2.0. I am getting same error for all products. How to resolve it?????

but all products are displayed in categories as well as home page.

**Comment by bacd** [comment] 2017-02-15 10:08
I am currently adding products to and configuring a Magento 2 . As such I made each product a configurable product with size , and each variation has a different assigned price. The price is changed in the product page when a combination of these attributes is selected, but not in the category page i.e store front. What can I do to remedy this

**Comment by mbrinton01** [comment] 2017-02-15 17:48
Hello @bacd. Please use GitHub for bug reports only. For your first question about products on the home page, please post on the Magento 2 [Forums](https://community.magento.com/t5/Core-Technology-Magento-2/ct-p/Magento-2).  The second question is a duplicate of #3150, so I am closing this issue.

**Closed as completed by mbrinton01** 2017-02-15 17:48 UTC
