### ISSUE TITLE
Impossible to a user to perform a first connection when using multiple website/store/view

### ISSUE THREAD

**Issue by lemmel** [magento/magento2#10180] opened 2017-07-07 14:09 UTC
Hi.

On a fresh installation of Magento, and after creation of multiple store/website, a newly created customer can't perform a first connection: he will get _Something went wrong while saving the new password_

I already found a ticket that is close or nearly the same of mine (see #5726), but in my case I'm not event trying to reset a password: the customer could not set one password, so it seems that Magento is not fonctionnal with multiple store/website (I could import/export user on need to change a password, but there, it isn't even possible to the customer to do a first connection).

### Preconditions
- magento: 2.1.7-2017-05-30-02-18-42
- nginx: 1.10
- PHP/FPM: 7.0, with modules: bcmath, cache-lite, curl, fxsl, http-request2, igbinary, intl, json, mbstring, mcrypt, memcached, msgpack, net-url2, pear, soap, xml, xml-htmlsax3, xml-rpc2, xml-svg, yac, yaml, zip, gd, mysql, readline, zip
- MariaDB: 10.1.23
- OS: debian stable

### Steps to reproduce
- Make a fresh install (without any example data)
- Creation of multiple Web Site/Store/Store View like this:
  ![image](https://user-images.githubusercontent.com/810483/27960042-180f9ed2-632a-11e7-83bc-dcbcf65a797f.png)
- Creation of one customer

- Use of the mail "Welcome to Main Website Store" sent to the user and try to set a password.
- You get : Something went wrong while saving the new password.

### Expected result
One should be able to set a password.
### Actual result
One can't set a password: 
![image](https://user-images.githubusercontent.com/810483/27960797-ded0418c-632c-11e7-8706-ac89d004bb4c.png)

### More informations
here are the log of /magento/var/log : [log.tar.gz](https://github.com/magento/magento2/files/1131178/log.tar.gz)
I can provide a ready to use virtualbox VM

**Comment by magento-engcom-team** [comment] 2017-10-04 17:30
@lemmel, thank you for your report.
We've created internal ticket(s) MAGETWO-80891 to track progress on the issue.

**Comment by watermark** [comment] 2018-03-01 18:32
This issue is coming up on its year anniversary and it's still not fixed.  This bug effectively means that customers cannot be created from the admin panel on a multi-website install (there's no way for them to set the password, so there's no way for them to login).

Can you please assign a higher priority to this issue?

**Comment by magento-engcom-team** [comment] 2018-10-06 14:31
Hi @ZhukValentina. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by raulsinapsis** [comment] 2019-02-08 09:46
This is still happening, more than 1 year ago... Really?

**Comment by shikhamis11** [comment] 2019-05-04 11:50
Hi @lemmel, Thank you for reporting this issue. 
I follow the same step but not able to reproduce this issue 
Can you Please confirm .. are you able to reproduce this issue on magento2.3-develop instance

**Comment by lemmel** [comment] 2019-08-19 08:38
Sorry, it has been 2 years (time does fly), and I switched to another tool a long time ago.
IMHO 2 years for having just the « kickstarting/Hello World » application running is too long for me.

So if you can't reproduce the problem, then maybe it is fixed, so if no one is complaining feel free to close the ticket.

**Comment by shikhamis11** [comment] 2019-09-24 02:18
I am closing this issue as it is not reproducible

**Closed as completed by shikhamis11** 2019-09-24 02:18 UTC
Labels: Issue: Ready for Work, bug report, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid, help wanted, Event: dmcdindia1
