### ISSUE TITLE
Redis + Sentinel + PHP8

### ISSUE THREAD

**Issue by Nuranto** [magento/magento2#35634] opened 2022-06-17 11:57 UTC
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1

Redis + Sentinel for session & cache

### Steps to reproduce

Launch a command or page that use session or cache

### Expected result

Everything's working fine

### Actual result

```
Exception #0 (Exception): Deprecated Functionality: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /var/www/html/vendor/colinmollenhour/php-redis-session-abstract/src/Cm/RedisSession/Handler.php on line 300
```

### Additional information

I reported the issue here : https://github.com/colinmollenhour/php-redis-session-abstract/issues/47

When it will be solved, the magento's composer version requirement for this package should be updated.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Nuranto** [comment] 2022-06-17 15:00
Your sentinel_master and sentinel_servers are empty. To reproduce, you need to fill them

**Comment by engcom-November** [comment] 2022-06-20 12:31
Verified the issue again on Magento 2.4-develop branch by filling sentinel_master and sentinel_servers values but could not able to reproduce the issue:
![image](https://user-images.githubusercontent.com/60198231/174601180-92871ed6-76e9-4a4a-b8cb-b732f10c08ef.png)
Kindly recheck the issue on Magento 2.4-develop branch and provide missing configuration details if any if the issue is still reproducible.
Thank you

**Comment by engcom-Hotel** [comment] 2022-10-10 11:47
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket AC-5972 by the internal team
Related commits: https://github.com/magento/magento2/search?q=AC-5972&type=commits

Based on the Jira ticket, the target version is 2.4.6.

Thanks

**Closed as completed by engcom-Hotel** 2022-10-10 11:47 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Component: Session, Priority: P1, Progress: done, Component: RedisMq, Area: Install & Administer, Reported on 2.4.4
