### ISSUE TITLE
Magento 2.4.x error "Environment emulation nesting is not allowed" occurs while sending invoice email

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#36134] opened 2022-09-13 04:20 UTC
### Preconditions and environment

- Magento 2.4.x CE

### Steps to reproduce

1. Create order
2. Go Backend > Sales > Orders
3. Create Invoice 
4. Send Email invoice
5. Check system.log 

### Expected result

Invoice send to customer without error

### Actual result

system.log logged the error: **Environment emulation nesting is not allowed**.

The reason is **\Magento\Sales\Model\Order\Email\Sender\InvoiceSender::send** calls **\Magento\Payment\Helper\Data::getInfoBlockHtml** into (startEnvironmentEmulation and stopEnvironmentEmulation) scope. and **\Magento\Payment\Helper\Data::getInfoBlockHtml** is also declared (startEnvironmentEmulation and stopEnvironmentEmulation).

https://imgur.com/0YvQX4E
https://imgur.com/Wd3AUhQ

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-09-14 05:22
:heavy_check_mark: Issue confirmed

Issue got reproduced in **2.4-develop** branch.

**Description:**

While sending the invoice mail , mail was sent and  an error is showing in the system.log file. 

**Pre-requisite:**

1. Magento 2.4.x CE


**Steps to reproduce:**

1. Create a order from frontend
2. Create a invoice for the order
3. Send the mail from invoice
4. Checked in system.log file

**Expected result:** 

Invoice send to customer without error  

**Actual result:** 

In system.log file error is generated.

**Screenshots:**

1. Create a order from frontend
<img width="592" alt="Screenshot 2022-09-14 at 10 45 37 AM" src="https://user-images.githubusercontent.com/51681379/190065383-8b582bf4-81aa-43c1-afff-5e8fa0cd3ada.png">

2. Create a invoice for the order
<img width="1391" alt="Screenshot 2022-09-14 at 10 47 16 AM" src="https://user-images.githubusercontent.com/51681379/190065553-6cfabe26-7d37-446e-8964-4b6cd1e9debe.png">

3. Send the mail from invoice
<img width="1153" alt="Screenshot 2022-09-14 at 10 48 54 AM" src="https://user-images.githubusercontent.com/51681379/190065756-89878f1d-eefb-4df2-80d4-4c5d5d7af62b.png">

4. Checked in system.log file
<img width="963" alt="Screenshot 2022-09-14 at 10 49 53 AM" src="https://user-images.githubusercontent.com/51681379/190065877-079aa6b2-c545-45c2-b69d-f38b4de875ac.png">

Hence, confirming the issue.
Thanks.

**Comment by thomas-kl1** [comment] 2024-04-11 13:05
I'm still experiencing this issue, I need to dig a bit deeper to confirm.

**Comment by jamesswilliamsv** [comment] 2024-06-13 09:20
Same here and this is from 2.4.6-p6

**Comment by ajung2** [comment] 2024-06-14 08:08
Also, starting from version 2.4.6-p6, this error is difficult to debug. However, we discovered that it originates from the EmailSenderHandler.php function sendEmails() at line 134. In this line, it uses the AbstractModel $item and selects the send method by the abstract class name. So, if it is a Shipment, it goes to the deprecated ShipmentSender.php class where the nested emulation starts—first emulation at line 125 and the second emulation triggered by $this->getPaymentHtml($order) -> getInfoBlockHtml(InfoInterface $info, $storeId) at line 223. The process works, and emails are sent successfully. However, the message "nested emulation..." generates garbage in the system.log when you send 1000 emails daily to customers.

This is a core issue, and we hope for an update. Meanwhile, we are patching this message by commenting out Emulation.php line 126 temporarily to keep the log clear.

**Comment by atIOCrON** [comment] 2024-10-03 09:01
I'd also like an update? @engcom-Delta

**Comment by erfanimani** [comment] 2024-11-01 07:02
Potentially a more conscientious fix would be the following:

- When environment emulation is called a second time, if the requested scope matches the existing emulation, ignore the call.
- But if environment emulation is called a second time with a new scope (not matching the initial emulation), that should put an error in the log (as this indicates some error within the system).

Although I don't really know when this would ever happen unless it's some wacky coding, so maybe just removing the logger line is fine.

**Comment by erfanimani** [comment] 2024-11-01 07:03
@atIOCrON

Looks like this was fixed in 2.4.7 onwards: https://github.com/magento/magento2/commit/4c6d47846fb00c398d36c0b8c0b1e69a417c3a79#diff-9c76aaedd0d6bac8ab3575c02f0107dca7af5ae95bb8fe11e2faf1753221f32bR147

**Comment by engcom-Bravo** [comment] 2024-12-11 04:30
@erfanimani Thanks for your Contribution!!.

Hi @nhatlich994,

As per this comment https://github.com/magento/magento2/issues/36134#issuecomment-2451406717 issue got fixed.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-12-11 04:30 UTC
Labels: Issue: Confirmed, Component: Email, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.4.x, Area: Admin UI
