### ISSUE TITLE
Elastic search throws error "illegal_argument_exception","reason":"size must be positive" when Search Suggestion Count set to zero.

### ISSUE THREAD

**Issue by CyberSecutor** [magento/magento2#37880] opened 2023-08-16 14:43 UTC
### Preconditions and environment

Magento 2.4.5-p3
Elastic search 7.6.0

'catalog/search/engine' is set to 'elasticsearch7'

![image](https://github.com/magento/magento2/assets/843685/94478d06-a8c9-4ace-befb-94eeea2fb980)

### Steps to reproduce

Go to the Admin

- Stores -> Configuration -> Catalog -> Catalog
- Open 'Catalog Search'
- Set `Enable Search Suggestions` to Yes
- Set `Search Suggestions Count` to 0
- Open a category page on the Frontend

### Expected result

No error is thrown by ElasticSearch

### Actual result

This error is thrown in the logs:
```
[2023-08-14T12:22:19.616626+00:00] report.CRITICAL: Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"size must be positive"}],"type":"illegal_argument_exception","reason":"size must be positive"},"status":400} in **************/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:693
Stack trace:
#0 **************vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(333): Elasticsearch\Connections\Connection->process4xxError()
#1 **************/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#2 **************/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(65): React\Promise\FulfilledPromise->then()
```

### Additional information

The patch to fix this is:

```
Added a condition based on $searchSuggestionsCount where ES gave an error when
this was set to 0 or lower.
diff --git a/vendor/magento/module-elasticsearch/Model/DataProvider/Base/Suggestions.php b/vendor/magento/module-elasticsearch/Model/DataProvider/Base/Suggestions.php
--- a/Model/DataProvider/Base/Suggestions.php
+++ b/Model/DataProvider/Base/Suggestions.php
@@ -216,21 +216,23 @@
     {
         $fields = $this->getSuggestFields();
         foreach ($fields as $field) {
-            $searchQuery['body']['suggest']['phrase_' . $field] = [
-                'phrase' => [
-                    'field' => $field,
-                    'analyzer' => 'standard',
-                    'size' => $searchSuggestionsCount,
-                    'max_errors' => 1,
-                    'direct_generator' => [
-                        [
-                            'field' => $field,
-                            'min_word_length' => 3,
-                            'min_doc_freq' => 1,
-                        ]
-                    ],
-                ],
-            ];
+            if ($searchSuggestionsCount > 0) {
+                $searchQuery['body']['suggest']['phrase_' . $field] = [
+                    'phrase' => [
+                        'field' => $field,
+                        'analyzer' => 'standard',
+                        'size' => $searchSuggestionsCount,
+                        'max_errors' => 1,
+                        'direct_generator' => [
+                            [
+                                'field' => $field,
+                                'min_word_length' => 3,
+                                'min_doc_freq' => 1,
+                            ]
+                        ],
+                    ],
+                ];
+            }
         }

         return $searchQuery;
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-08-17 10:08
Hi @CyberSecutor,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

Go to the Admin

- Stores -> Configuration -> Catalog -> Catalog
- Open 'Catalog Search'
- Set Enable Search Suggestions to Yes
- Set Search Suggestions Count to 0
- Open a category page on the Frontend


<img width="705" alt="Screenshot 2023-08-17 at 11 47 35 AM" src="https://github.com/magento/magento2/assets/51680745/91ca675f-32bb-4770-a6f3-1b7737cc542a">


![Configuration-Settings-Stores-Magento-Admin (10)](https://github.com/magento/magento2/assets/51680745/e0d0fcdb-3a71-48ce-b626-d3e78cbe7dd6)



<img width="1457" alt="Screenshot 2023-08-17 at 11 51 40 AM" src="https://github.com/magento/magento2/assets/51680745/ec0ef5fb-dc79-4548-b3ee-d556be257070">



We are able to open the category page without any errors.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-29 06:06
Hi @CyberSecutor,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37880#issuecomment-1682008987 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-09-06 06:12
Hi @CyberSecutor,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-09-06 06:12 UTC
Labels: Issue: needs update, Reported on 2.4.5-p3
