### ISSUE TITLE
Magento sitemap.xml listing is different from the canonical url

### ISSUE THREAD

**Issue by sammyhq** [magento/magento2#3716] opened 2016-03-10 13:33 UTC
## **Steps to reproduce**
1. Install Magento 2.0.2 from zip archive.
2. Set Use Canonical Link Meta Tag to Yes for products and categories
3. Generate Sitemap.xml file.
## **Expected result**
1. I want to make sure that Sitemap contains canonical URLs
## **Actual result**

1.the problem is in Magento's default sitemap.xml, it is taking a lot of *_non-canonical *_ product urls:
For example,:
<url><loc>http://SITENAME/men/tops-men/tees-men/ryker-lumatech-trade-tee-v-neck.html</loc>
<url><loc>http://SITENAME/men/tops-men/tees-men/logan-heattec-reg-tee.html </loc>
....
<loc>http://SITENAME/women/tops-women/hoodies-and-sweatshirts-women/autumn-pullie.html</loc>

AND many more....

It's a bad practice from SEO perspective and worth fixing.

Could you please take a look at it

**Comment by redinn** [comment] 2016-03-13 08:20
Looks like it's a duplicate of #3099

**Comment by shiftedreality** [comment] 2016-03-15 10:15
Hi @sammyhq,  thank you for reporting.

I created  internal ticket MAGETWO-50495 to resolve this issue.

**Comment by shiftedreality** [comment] 2016-04-11 10:11
Fix merged with 9bf93a3fc6da720da989607916b92301e4af6a57
Closed

**Closed as completed by shiftedreality** 2016-04-11 10:11 UTC
Labels: Issue: Ready for Work
