### ISSUE TITLE
Checkout Page Password Input Box Do Not Display

### ISSUE THREAD

**Issue by Yuwei9291** [magento/magento2#37716] opened 2023-07-04 16:06 UTC
### Preconditions and environment

- Magento 2.4.6-p1
- New installation with sample data

### Steps to reproduce

1. New installation with sample data deployed
2. add item to cart without login
3. go to checkout page
4. input a customer email , sample account is roni_cost@example.com

### Expected result

Once input a registed account, a password input box would be displayed :
![image](https://github.com/magento/magento2/assets/45879513/b4dd2218-c710-4f93-87eb-5a6c7f3d9f25)

### Actual result

In this version of magento, once we input the email address, it would have a verify loading process
![image](https://github.com/magento/magento2/assets/45879513/c98707fa-9216-4599-b93a-f2d87e75bbde)
but the password input box is still display:none

![image](https://github.com/magento/magento2/assets/45879513/c5903a06-f5f2-47b9-9b8b-62bae4e967b7)
![image](https://github.com/magento/magento2/assets/45879513/ecdf99d0-c7ca-45c3-af97-08d966e235dd)

### Additional information

this issue can be reproduced in 2.4.6-p1. 
I've tested 2.4.4, it do not be reproduced in this version

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-07-05 10:04
Hi @Yuwei9291,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4.6-p1 instance and the issue is not reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- New installation with sample data deployed
- add item to cart without login
- go to checkout page
- input a customer email , sample account is [roni_cost@example.com](mailto:roni_cost@example.com)


A new feature has been added in configuration **Enable Guest Checkout Login**. please try to enable to this feature after we are able to see the password field.

<img width="1506" alt="Screenshot 2023-07-05 at 3 30 09 PM" src="https://github.com/magento/magento2/assets/51680745/6f48aa2f-a648-43d1-a327-ec05ce00fddd">





https://github.com/magento/magento2/assets/51680745/b57f925d-447d-4bf0-a7a7-5bfe1ef591f4




Kindly recheck the behaviour on Magento 2.4.6-p1 instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-18 06:03
Hi @Yuwei9291,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37716#issuecomment-1621444796 and please let us know if you are still facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-24 05:36
Hi @Yuwei9291,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-24 05:36 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
