### ISSUE TITLE
Shipment methods are not selectable (infinite spinner) on checkout page when there are other payment methods enabled

### ISSUE THREAD

**Issue by zolikonta** [magento/magento2#36095] opened 2022-09-06 15:26 UTC
### Preconditions and environment

- Magento version 2.3.7-p4 (upgraded from 2.3.4)
- PHP 7.4
- MySQL 5.7
- Any other built-in payment method enabled with PayPal Express Checkout

### Steps to reproduce

1. go to /admin/system_config/edit/section/payment/
2. have PayPal Express Checkout enabled
3. enable either Cash on delivery or Bank transfer
4. go to the frontend
5. put something in your cart
6. go to checkout

### Expected result

On the checkout page shipment method radio buttons should be active.

### Actual result

On the checkout page the shipment method radio buttons are inactive (spinner overlay stays on) due to failed address validation.

### Additional information

Workaround: Disable other payment methods temporarily. Shipment methods are accessible with only PayPal Express Checkout enabled.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by zolikonta** [comment] 2022-09-06 17:44
@magento give me 2.3.7-p4 instance

**Comment by devchris79** [comment] 2022-09-07 08:38
Hi @zolikonta 

this may be related to #25399

**Comment by engcom-November** [comment] 2022-09-26 12:13
Hi @zolikonta ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop branch but the issue is not reproducible.
User is able to place orders with both Paypal Express checkout and Cash on delivery payment methods with available shipping methods.
![image](https://user-images.githubusercontent.com/60198231/192273087-f0ee5cc4-6364-461f-a9ca-0589e617d7bd.png)
Kindly recheck the issue on Magento 2.4-develop instance as it is having latest code base and is upcoming 2.4.x release and provide missing steps or any configuration details (3rd party modules enabled if any) if any if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2022-10-10 06:06
Hi @zolikonta ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-10-10 06:06 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.3.7-p4
