### ISSUE TITLE
Braintree credit card - copy of invoice fails to generate

### ISSUE THREAD

**Issue by kishanpatadia** [magento/magento2#6565] opened 2016-09-10 11:19 UTC
Using Magento 2 and Braintree Payments. When payment is by credit card email copy of invoice fails to generate as per attached picture.
### Preconditions
1. CE 2.1.1
### Steps to reproduce

1. Navigate to store front-end
2. Add any product to cart
3. Go to checkout page
4. Select braintreee credit card payment method
5. Place order by completing other steps
### Expected result

Order invoice mail is generated successfully and customer receives it in email.
### Actual result

Invoice order email is failed to generate and customer gets that error message in email
![email_invoice](https://cloud.githubusercontent.com/assets/4959946/18410106/26b344b6-7776-11e6-99ed-2d8ab9556ec1.jpg)

**Comment by iivashchenko** [comment] 2016-09-16 14:07
Hi @kishanpatadia, thank you for the feedback. We can't reproduce your issue as described. Please, identify the web server you are running, the versions of PHP and MySQL, logs would be helpful too.

**Comment by alena-marchenko** [comment] 2016-09-30 10:00
Hi @kishanpatadia,

We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by alena-marchenko** 2016-09-30 10:00 UTC
Labels: bug report, Progress: needs update, Component: Payment
