### ISSUE TITLE
Unable to add custom item renderer for mini-cart

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#5965] opened 2016-08-03 13:45 UTC
Unable to add custom renderer for mini-cart.
File: app/code/MagePsycho/Test/view/frontend/layout/checkout_cart_sidebar_item_renderers.xml

```
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <referenceBlock name="minicart">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="minicart_content" xsi:type="array">
                            <item name="config" xsi:type="array">
                                <item name="itemRenderer" xsi:type="array">
                                    <item name="free_gift" xsi:type="string">testRenderer</item>
                                </item>
                            </item>
                            <item name="children" xsi:type="array">
                                <item name="item.renderer" xsi:type="array">
                                    <item name="config" xsi:type="array">
                                        <item name="displayArea" xsi:type="string">testRenderer</item>
                                        <item name="template" xsi:type="string">MagePsycho_Test/minicart/item/free</item>
                                    </item>
                                </item>
                            </item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
    </body>
</page>
```

On inspection, I saw that custom renderer got added to the `itemRenderer` list. But not the `item.renderer` > `displayArea`

is there any limitation with custom renderer for mini-cart? 
Note: Custom item renderer works fine for Cart page though.

**Comment by veloraven** [comment] 2016-11-01 17:12
@MagePsycho 
I'm closing this issue as the GitHub issue tracker is intended for technical issues only. 
Please refer to the [Community Forums](https://community.magento.com) or the [Magento Stack Exchange](http://magento.stackexchange.com/) site for technical questions.
If you think it to be an issue than please create new GitHub report following the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result. Please, also identify which version of Magento you are running.

**Closed as completed by veloraven** 2016-11-01 17:12 UTC
