### ISSUE TITLE
Active state of shipping method not respecting store scope config in adminhtml

### ISSUE THREAD

**Issue by Jeroenll** [magento/magento2#14664] opened 2018-04-12 13:32 UTC
### Preconditions
1. Magento 2.2.2
2. PHP 7.1.15-1
3. MySQL 5.7.16-10

### Steps to reproduce

1. Make sure all shipping methods are disabled.
2. Add group to a `etc/adminhtml/system.xml` file
```
<group id="subscription_carriers" translate="label" type="text" sortOrder="5" showInDefault="1" showInWebsite="1" showInStore="1">
    <label>Shipping Methods</label>
    <field id="shipping_methods" translate="label" type="multiselect" sortOrder="1" showInDefault="1" showInWebsite="1" showInStore="1" canRestore="1">
        <label>Enabled Shipping Methods</label>
        <source_model>Magento\Shipping\Model\Config\Source\Allmethods</source_model>
    </field>
</group>
```
2. Change to website view scope.
2. Enable shipping method `flatrate` on a website scope.
3. Go to your module where above added group will be shown.

### Expected result
1. `flatrate` shipping method is shown in the multiselect.

### Actual result
1. `flatrate` shipping method isn't shown in the multiselect.
2. All shipping methods are considered not active in source model.

### Point of origin
https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Shipping/Model/Carrier/AbstractCarrier.php#L126-L138
`$this->getStore` is `null` for adminhtml requests and causes Magento to fallback to default config value.

or

https://github.com/magento/magento2/blob/2.2-develop/lib/internal/Magento/Framework/App/Config.php#L69
Where `scopeResolver` is resolving to default scope instead of store view.

**Comment by engcom-backlog-nickolas** [comment] 2018-08-03 08:34
Hello @JeroenVanLeusden, thank you for your report.
We've acknowledged the issue and added to our backlog.

I've changed step 2 and 3 to website view scope, as enabling shipping methods have no store view scope in vanilla magento.

**Comment by magento-engcom-team** [comment] 2019-02-21 19:43
Hi @AleksLi. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-09-18 17:19
@JeroenVanLeusden, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.3-develop` branch. Thank you for collaboration.

**Closed as completed by magento-engcom-team** 2019-09-18 17:19 UTC
Labels: Issue: Ready for Work, Component: Shipping, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue: Format is valid
