### ISSUE TITLE
Schedule index - entities processed multiple times

### ISSUE THREAD

**Issue by mabaud** [magento/magento2#37367] opened 2023-04-13 13:30 UTC
### Preconditions and environment

Magento version : 2.4.5-p2

### Steps to reproduce

1. Magento with sample data
2. Run bin/magento index:set-mode schedule
3. Disable cron
4. Change 1 product name for instance and save
5. Change method \Magento\Framework\Mview\View::executeAction => reduce batch size for testing purpose and add logs

For instance : 
`private function executeAction(ActionInterface $action, int $lastVersionId, int $currentVersionId)
{
    $batchSize = isset($this->changelogBatchSize[$this->getChangelog()->getViewId()])
        ? (int) $this->changelogBatchSize[$this->getChangelog()->getViewId()]
        : self::DEFAULT_BATCH_SIZE;

	$batchSize = 3;
	file_put_contents('/tmp/debug.log', json_encode($this->getData('view_id')) . PHP_EOL, FILE_APPEND);
	
    $vsFrom = $lastVersionId;
    while ($vsFrom < $currentVersionId) {
        $walker = $this->getWalker();
        $ids = $walker->walk($this->getChangelog(), $vsFrom, $currentVersionId, $batchSize);

        if (empty($ids)) {
            break;
        }
        $vsFrom += $batchSize;
		file_put_contents('/tmp/debug.log', json_encode($ids) . PHP_EOL, FILE_APPEND);            
		$action->execute($ids);
    }
}`

6. Enable cron

### Expected result

Product is indexed once (per index).
In my example, we should have something like that: 
`"catalog_product_attribute"
["1"]
"inventory"
"catalogrule_product"
["1"]
"cataloginventory_stock"
["1"]
"catalog_product_price"
["1"]
"catalogsearch_fulltext"
["1"]
`

### Actual result

Here the result on the generated file : 
`"catalog_product_attribute"
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
"inventory"
"catalogrule_product"
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
"cataloginventory_stock"
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
"catalog_product_price"
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
"catalogsearch_fulltext"
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
["1"]
`
The product 1 is indexed 9 times per index.

### Additional information

We were migrating from 2.3.7 to 2.4.5, we updated products through API and it took like 50 hours to process the catalog_product_category index.
I made a patch to fix this issue => 
[indexation_issue.patch.txt](https://github.com/magento/magento2/files/11221155/indexation_issue.patch.txt)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by hostep** [comment] 2023-04-13 14:00
This sounds like this problem: https://github.com/magento/magento2/issues/30012, with a possible solution in https://github.com/magento/magento2/pull/36155

Haven't tried your patch yet, it seems quite simple in contrast to the PR, but maybe it's enough to solve the problem ... 🙂

**Comment by mabaud** [comment] 2023-04-13 14:13
Ah yes it's the same problem, I missed that !
And yes the PR seems big, the only issue to fix here is to get the right version_id to not read X times the same rows in the changelog tables (but maybe i'm missing something!)

**Comment by engcom-November** [comment] 2023-07-25 12:55
Hello @mabaud,
Thank you for reporting and collaboration.
Thank you @hostep for the input.

As this issue is duplicate of [#30012 ](https://github.com/magento/magento2/issues/30012), we are closing this issue as duplicate.

Please track the progress on the issue from above mentioned link.

Thanks.

**Closed as completed by engcom-November** 2023-07-25 12:55 UTC
Labels: duplicate, Triage: Dev.Experience, Reported on 2.4.x
