### ISSUE TITLE
Not able to override sortRatesByPrice() method of core class \Magento\Shipping\Model\Rate\Result by using preference

### ISSUE THREAD

**Issue by Laiba-Gillani** [magento/magento2#35786] opened 2022-07-20 06:17 UTC
I am trying to override sortRatesByPrice() method of core class \Magento\Shipping\Model\Rate\Result by using preference but its returning prefered method in script but core method on frontend. Frontend is in vue.

**Comment by engcom-Lima** [comment] 2022-07-21 08:10
Hi @Laiba-Gillani ,

Thank you for raising the issue.

However, the info provided is not enough for us to check and reproduce. Kindly provide below info so that we can check if the issue is related to Magento Dev:

1. Summary of the issue
2. Information on your environment
3. Steps to reproduce
4. Expected and actual results

Also we would like to inform you that if you have any general query relating to Magento architecture and related functionality, you can raise on various Magento forums like [Magento Stack Exchange](https://magento.stackexchange.com/) or [Magento Community](https://community.magento.com/).

Hope that helps.

Thanks

**Comment by engcom-Lima** [comment] 2022-08-04 10:34
Hi @Laiba-Gillani ,

We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it.Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Lima** 2022-08-04 10:34 UTC
Labels: Triage: Dev.Experience, Issue: needs update
