### ISSUE TITLE
iPad: Add to cart button should not display as Adding.. once back form detail page

### ISSUE THREAD

**Issue by hasim32** [magento/magento2#25795] opened 2019-11-28 13:20 UTC
iPad: Add to cart button should not display as Adding.. once back form detail page

### Preconditions (*)
Magento : 2.3
Sample data installed

### Steps to reproduce (*)

1. iPad: Go to product listing page
2. Click on Add to cart for configurable product (without select product options)
3. It redirect to detail page
4. Now click on back button
5. Review the Adding.. button not changed to Add to cart

### Expected result (*)
It should work fine

### Actual result (*)
Adding.. button not changed to Add to cart

**Comment by magento-engcom-team** [comment] 2019-11-28 15:16
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29259` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by krishprakash** [comment] 2019-11-28 15:16
![Image-1 (49)](https://user-images.githubusercontent.com/46617848/69817139-eeecbd80-121f-11ea-8996-60204ccbc5c3.jpg)

Iss reproduced on iPad

**Comment by krzksz** [comment] 2019-12-13 17:33
I am unable to reproduce the issue:

![ezgif-4-90b2fa4ff3c9](https://user-images.githubusercontent.com/829189/70819642-05c21100-1dd7-11ea-9385-8b5223f51201.gif)

**Closed as completed by krzksz** 2019-12-13 17:33 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Area: Design/Frontend
