### ISSUE TITLE
Default Store Configuration Conflict

### ISSUE THREAD

**Issue by vetalkab** [magento/magento2#1592] opened 2015-07-30 18:09 UTC
**Description:** 
It is impossible to switch to default (set in Magento admin) Store View on frontend when MAGE_RUN_CODE is set to another Store View in .htaccess or index.php. 

**Steps to reproduce:**
There are 3 Store Views which belong to one Store and one Website:
store1 - is set as default in Magento admin
store2
store3 - is set as default in index.php

> $params = $_SERVER;
> $params['MAGE_RUN_CODE'] = 'store3';
> $params['MAGE_RUN_TYPE'] = 'store';
> $bootstrap = \Magento\Framework\App\Bootstrap::create(BP, $params);

Go to frontend. As default opens store3. We can successfully switch to store2, we can not switch to store1, it redirect to store3.

**Comment by piotrekkaminski** [comment] 2015-10-02 21:24
internal issue MAGETWO-43620

**Comment by mengbo123456** [comment] 2017-07-03 02:20
****
![image](https://user-images.githubusercontent.com/29748690/27775937-3ecb6b04-5fd9-11e7-8a21-452e861139a6.png)

**Comment by magento-engcom-team** [comment] 2017-09-26 22:00
@vetalkab, thank you for your report.
The issue is already fixed in 2.2.0

**Closed by magento-engcom-team** 2017-09-26 22:00 UTC
Labels: 2.1.x, acknowledged, Application Framework, bug report, Fixed in 2.2.x, G1 Failed, G2 Passed, G3 Passed, Reproduced on 2.1.x
