### ISSUE TITLE
Hidden elements on Pagebuilder still shows up on the Front-End

### ISSUE THREAD

**Issue by Abdo-93** [magento/magento2#38156] opened 2023-11-07 22:43 UTC
### Preconditions and environment

- Magento version -> Version 2.4.4-p6
- Chrome Version ->  Version 119.0.6045.105
              

### Steps to reproduce

Reproduce the bug => 
                    - On any Google Chrome -> latest version.
                    - Navigate to a page build entirely on Pagebuilder.
                    - Choose to hide some elements and flush the cache.     
                    - Refresh page.

### Expected result

Hidden elements should not be visible on the front-end.

### Actual result

Hidden elements are visible on the front-end.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by Abdo-93** [comment] 2023-11-07 22:45
@magento give me 2.4-develop instance

**Comment by Abdo-93** [comment] 2023-11-07 23:01
Unable to reproduce issue on Magento Instance provided.

**Comment by Abdo-93** [comment] 2023-11-08 22:42
Issue: Confirmed

**Comment by engcom-Bravo** [comment] 2023-12-12 09:07
Hi @Abdo-93,

Thank you for reporting and collaboration.

Could you please elaborate regarding this step :

**Choose to hide some elements and flush the cache.**


Please provide us screenshots or screencast if possible it will helps us to reproduce the issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-12-28 05:32
Hi @Abdo-93,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38156#issuecomment-1851581146still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-01-04 05:09
Hi @Abdo-93,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-01-04 05:09 UTC
Labels: Issue: needs update, Reported on 2.4.4-p6
