### ISSUE TITLE
Newsletter issue on Magento 2.2.3

### ISSUE THREAD

**Issue by Giteebs** [magento/magento2#25460] opened 2019-11-04 12:00 UTC
Tested on Magento 2.2.3
The issue is, can't disable or enable newsletter popup on magento home page.
In admin panel,
 Go to Codazon->fastest Options->General options->Theme options->Newsletter Pop-up

I have enabled newsletter option and gave corresponding static block ID too. but the worst thing is newsletter pop-up close icon alone displaying instead of the form information. 
What should i do to load newsletter information fully.. 

Kindly, let me know the possible option to enable newsletter form on Home page. 
Thanks in advance.

**Comment by engcom-Charlie** [comment] 2019-11-05 10:59
Hello @Giteebs 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the latest 2.3-develop branch by provided steps.

We are closing this issue due to branch `2.2-develop` was closed and
> Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3.

 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thanks for your report!

**Closed as completed by engcom-Charlie** 2019-11-05 10:59 UTC
Labels: Issue: Format is not valid
