### ISSUE TITLE
Invoice generation error with bundle product

### ISSUE THREAD

**Issue by anujeetphj** [magento/magento2#28976] opened 2020-07-02 17:56 UTC
### Preconditions (*)
Magento 2.3.3

### Steps to reproduce (*)
1. Create a bundle product which has one simple product and one virtual product as child products.
2. Keep Dynamic Price = off
3. Keep Dynamic SKU = on
4. Keep Dynamic weight = on
5. Add this product to cart
6. Complete checkout with Cash on delievery
7. In the admin panel, go to 
Orders -> Edit Order
8. Click on ‘Invoice’ in header
9. Click on ‘Submit invoice’ to generate the invoice for the order.

### Expected result (*)
 Invoice processed successfully

### Actual result (*)
500 server error with the below stack trace in server logs:
[12-Sep-2019 09:22:56 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
Stack trace:
#0 /chroot/home/www/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems()
#1 /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array)
#2 /chroot/home/www/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61) in /chroot/home/www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102

###Severity
**S0**

I first saw the error on the frontend while placing order with a payment method. After that when I tried to generate the invoice from admin, got the same error.

There is no way I can generate invoice for my bundle products now.

**Comment by anujeetphj** [comment] 2020-07-02 18:01
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-07-02 18:01
Hi @anujeetphj. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-02 18:03
Hi @anujeetphj, here is your [Magento instance](https://i-28976-2-3-3.instances.magento-community.engineering).
Admin access: [https://i-28976-2-3-3.instances.magento-community.engineering/admin_a258](https://i-28976-2-3-3.instances.magento-community.engineering/admin_a258)
Login: `fa101186` Password: `4a60e3c528d5`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-03 07:10
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-03 07:10
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by anujeetphj** [comment] 2020-07-04 14:42
@magento give me 2.3.3 instance

**Comment by magento-engcom-team** [comment] 2020-07-04 14:42
Hi @anujeetphj. Thank you for your request. I'm working on Magento 2.3.3 instance for you

**Comment by anujeetphj** [comment] 2020-07-04 14:47
@magento-admin, did you get anything for this issue? The issue is having the same status from quite some days. I am facing issues with my payment.
Please take a look at my report.

Thanks

**Comment by swathishs** [comment] 2020-07-07 06:09
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-07-07 06:09
Hi @swathishs. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by swathishs** [comment] 2020-07-07 07:07
@magento give me 2.3.5-p1 instance

**Comment by magento-engcom-team** [comment] 2020-07-07 07:07
Hi @swathishs. Thank you for your request. I'm working on Magento 2.3.5-p1 instance for you

**Comment by magento-engcom-team** [comment] 2020-07-07 07:09
Hi @swathishs, here is your [Magento instance](https://i-28976-2-3-5-p1.instances.magento-community.engineering).
Admin access: [https://i-28976-2-3-5-p1.instances.magento-community.engineering/admin_f46c](https://i-28976-2-3-5-p1.instances.magento-community.engineering/admin_f46c)
Login: `21250323` Password: `b33521560c69`
Instance will be terminated in up to 3 hours.

**Comment by swathishs** [comment] 2020-07-07 08:00
@anujeetphj : Issue is not reproducible on Magento 2.3.5 p1 instance

Please find the attachment below:
1. **Bundle product:**
![image](https://user-images.githubusercontent.com/58288685/86741331-eaf60900-c054-11ea-95a4-ef78a002b625.png)

2. **Virtual product and simple product:**
![image](https://user-images.githubusercontent.com/58288685/86741520-124cd600-c055-11ea-8957-521c8abd1b04.png)

3. **Cart page:**
![image](https://user-images.githubusercontent.com/58288685/86741759-43c5a180-c055-11ea-9f0c-f0ab9f1eadd3.png)

4. **Cash on delivery:**
![image](https://user-images.githubusercontent.com/58288685/86741996-6ce63200-c055-11ea-8343-fe5b63ac053c.png)

5. **Order:**
![image](https://user-images.githubusercontent.com/58288685/86742381-b5055480-c055-11ea-9a42-ef6e78221e9b.png)

6. **Invoice order:**
![image](https://user-images.githubusercontent.com/58288685/86742544-d36b5000-c055-11ea-993f-2106386b7f77.png)
![image](https://user-images.githubusercontent.com/58288685/86742698-eda52e00-c055-11ea-9850-804a3ab9d516.png)

**Comment by cuiyang000** [comment] 2020-09-14 08:57
@swathishs I have this same issue, I think you will have to add both simple & virtual product to cart to reproduce the issue, instead of set both of them into one dropdown - in this case you can only add one of them to cart.

So I think you will have to create 2 bundle options, one with simple products, one with virtual products, and try again to have both options selected in the frontend.

**Comment by engcom-Oscar** [comment] 2020-09-18 13:37
Hello @anujeetphj  

Thank you for your report.
Unfortunately, I was not able to reproduce this issue on the latest `2.4-develop` code. Probably it was already fixed and will appear in the next release. Or we missed some steps or preconditions.

Could you please recheck it on clean Magento installation and confirm?

**Comment by engcom-Bravo** [comment] 2020-10-15 13:33
Hello @anujeetphj 

Thank you for your report

We confirm that the issue is reproducible on Magento 2.3.3. We get a 500 error after an attempt to **Submit Invoice**
![error500](https://user-images.githubusercontent.com/51680745/96132400-0a79b900-0f03-11eb-8e82-1ab915fa1423.png)
_Fatal error: Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in_



**However**, the issue is not reproducible with the same steps on 2.4-develop
After clicking **Submit Invoice**
![sumbit_invoice](https://user-images.githubusercontent.com/51680745/96132489-22513d00-0f03-11eb-8c2d-e09a679d9484.png)

The invoice is successfully created
![invoice_created](https://user-images.githubusercontent.com/51680745/96132572-3c8b1b00-0f03-11eb-894a-79288cc0b8ef.png)

Unfortunately, we can not deliver a fix to already released version 2.3.3. So we have to close this issue.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2020-10-15 13:33 UTC
Labels: Issue: Format is valid, Progress: done, Reported on 2.3.3

**Comment by Dim3nsioneer** [comment] 2021-03-22 09:22
I seem to have the same issue with 2.3.5-p2. An internal error (500) occurs when an invoice should be created for an order that includes a bundle product which itself includes a virtual product.
Setting the corresponding item in the table sales_order_item from virtual to simple provided a very ugly work-around.
