### ISSUE TITLE
Export data issue

### ISSUE THREAD

**Issue by MizoAhmed33** [magento/magento2#37853] opened 2023-08-07 07:02 UTC
### Preconditions and environment

- Magento version : Magento ver. 2.3.7-p4

### Steps to reproduce

Login to Magento 
then Orders 
then i filter orders by date  
then i select export from export icon i select CSV then export 
-- 
then i go to Export file listing .
and select from file i export download after it success .

### Expected result

Normally i export file then i can download it from 1 minute up to 10 minutes .

### Actual result

i need to wait more than 3 Hours as the exported file is Pending 
then it success and ready to download after 3 up to 5  hours  tell the export is successful then i can download it  
so it waste time and we need this data daily at the morning

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by magenizr** [comment] 2023-08-07 09:39
@MizoAhmed33

Did you try to generate an order export in smaller chunks? For example, just for one month instead of multiple months? Maybe you simply hit a limitation on your server, most likely PHP.

Also, did you check for any errors in your `./var/log/exception.log`?

**Comment by engcom-Bravo** [comment] 2023-08-08 07:10
@magento give me 2.4-develop instance

**Comment by nuzil** [comment] 2023-08-08 08:48
@MizoAhmed33 
check question from @magenizr 

Also another point, that you have too many other messages being processed at the same time.
So in any case, export have to be available in short term after you trigger it. If its not so, issue is coming from amount of data you exporting, amount of data system processing via the queue, infrastructure problems.

**Comment by engcom-Bravo** [comment] 2023-08-08 08:49
@nuzil @magenizr Thanks for your contribution & collaboration over here.

Hi @MizoAhmed33,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.


**Login to Magento**

- then Orders
- then i filter orders by date
- then i select export from export icon i select CSV then export


We are able to download the CSV file for order reports.


<img width="1495" alt="Screenshot 2023-08-08 at 12 55 08 PM" src="https://github.com/magento/magento2/assets/51680745/7f7efe81-b318-4889-9e62-48c9fb690e98">



We have downloaded below file :

[sales (2).csv](https://github.com/magento/magento2/files/12288421/sales.2.csv)

Please make sure you have enabled CRON.

Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-21 06:07
Hi @MizoAhmed33,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/37853#issuecomment-1669193555 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-08-28 06:06
Hi @MizoAhmed33,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-08-28 06:06 UTC
Labels: Issue: needs update, Reported on 2.3.7-p4
