### ISSUE TITLE
Shipping address missing after canceled payment redirect to checkout/#payment

### ISSUE THREAD

**Issue by wintermute-84** [magento/magento2#11247] opened 2017-10-05 11:57 UTC
This issue was reported multiple times and every ticket is closed.
Like #5959

### Preconditions
1. Latest Magento 2.2.0
2. Payment method that uses redirected payment page
3. Ability to cancel payment to get back to checkout

### Steps to reproduce

1. Add product
2. Go to checkout, fill shipping address, go to the next step
3. Click pay with 3rd party payment provider
4. Cancel payment to get back to /checkout/#payment

### Actual result
The shipping address is not loaded. 
Address is still present in db.
Other quote info like products/prices are loaded.
![screen shot 2017-09-20 at 13 28 51](https://user-images.githubusercontent.com/3521295/31225910-2bedc31e-a9e5-11e7-902a-8a57841b4f82.png)

Cancel action is standard:

```
public function execute()
    {
        $this->checkoutHelper->cancelCurrentOrder('');
        $this->checkoutHelper->restoreQuote();

        $this->_redirect('checkout', ['_fragment' => 'payment']);
    }
```

If anyone has any fixes to this, please help.
Referenced commit in other tickets:
https://github.com/magento/magento2/commit/63ff3aee27a7d5830221aa6a2bf92f4bd88c56ef
not only is missing from 2.2 but also does not fix it.

**Comment by magento-engcom-team** [comment] 2017-10-10 08:08
@wintermute-84 We cannot reproduce this issue as described. Please provide the detailed steps we must follow to reproduce this issue. In addition, what payment method do you use, and any other information needed to reproduce your issue.

**Comment by reihaan** [comment] 2017-10-12 11:59
I am also facing same issue, when we cancel the payment it take us to cart instead of checkout page and all the fields get emptied.
The issue exists in Magento Community Edition 2.2.0

Also when we refresh the checkout page we see the same behavior.

**Comment by wintermute-84** [comment] 2017-10-23 12:15
If you use CreditCard (QuickPay) as payment method and just cancel your payment on the HPP it will redirect back to checkout purging shipping address. You can debug JS that is loading the address.

Or you can use Adyen HPP with the same result as @reihaan has. It will redirect to cart and after proceeding to checkout you will see that shipping is empty.

Also I'm pretty sure that using Paypal\Hostedpro will have the same result but I don't have an account to verify it.

In all cases quote address is present in the DB.

And I'm also curious how have you tested/ with what payment method that you didn't get it to fail.

**Comment by magento-engcom-team** [comment] 2017-10-24 08:36
@wintermute-84, thank you for your report.
We've created internal ticket(s) MAGETWO-82589 to track progress on the issue.

**Comment by magento-engcom-team** [comment] 2018-01-05 16:31
@wintermute-84, thank you for your report.
The issue is already fixed in 2.2.4

**Closed as completed by magento-engcom-team** 2018-01-05 16:31 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Issue: Format is not valid

**Comment by richardechidna** [comment] 2018-01-31 08:29
Where can I find the code for this ?

**Comment by kapil019** [comment] 2018-01-31 10:16
@richardechidna I have fixed this in https://github.com/magento/magento2/issues/11197#issuecomment-359785930
Please check my commit
https://github.com/kapil019/magento2/commit/108c3fac3d5bde3353433199359582e7bf7cea0f

**Comment by richardechidna** [comment] 2018-01-31 10:29
@kapil019 thanks bro, but the code seem not to be working. 
My issue is after i fill in the shipment address and proceed to the payment section and then after refresh while being at payment section the shipping data gets removed

**Comment by brekz** [comment] 2018-02-09 17:54
Yes, I'm getting the same issue, as @richardechidna described. Any solution?

**Comment by richardechidna** [comment] 2018-02-10 01:25
@brekz unfortunately not yet. we are waiting on Magento's help. Will post it once we get it

**Comment by cleardarren** [comment] 2018-02-26 13:57
I'm seeing the same issue too, it only happens when using Free Shipping though.

**Comment by mvaisberg** [comment] 2018-04-10 19:54
Any update here? i am having the same issue.

**Comment by tig-robertgrundeken** [comment] 2018-04-18 11:51
Still having the problem with branch 2.2.4-preview. Is it already merged in there?

**Comment by peterjaap** [comment] 2018-04-23 14:19
Also having this issue. The fix @kapil019 described is for when you use the step navigator at the top to go back and forth a page (as described [here](https://github.com/magento/magento2/issues/11197#issue-262429376)), not for the bug that occurs when refreshing the payment page ~~or hitting the back button in your browser~~.

**Comment by fk-whothat** [comment] 2018-06-14 08:21
Any update having the same issue at magento v2.2.2

**Comment by elvinristi** [comment] 2018-06-14 08:30
@fk-whothat, if you know how to add patches then maybe you can try this one for `Magento_Checkout` to apply and see if it fixes issue for you?

- https://github.com/magento/magento2/issues/6817#issuecomment-397211593

**Comment by worldnettps** [comment] 2022-01-07 11:44
This still happening in v2.4.2 The only difference in our payment flow is that the cartManagement->placeOrder method is called only when the gateway returns a successful payment. Otherwise the quote is kept active and user gets redirected to the payment page. The quote information is correct, it just seems that the checkout-data in the localstorage gets emptied and the quote shipping address is not correctly populated, resulting in the same issue originaly posted. This only happens for guest checkout. Is there an open issue for this?
