### ISSUE TITLE
content:deploy only create minified css and js files

### ISSUE THREAD

**Issue by klarlichter** [magento/magento2#6242] opened 2016-08-19 08:38 UTC
Hello,
we had run content:deploy. We can see that content:deploy only create minified css and js files.
How we can solve that? We want get example.min.css and example.css files. 

We dont know where that bug cause...:(

**Comment by veloraven** [comment] 2016-08-22 06:40
@klarlichter thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also provide the used Magento version.

**Comment by mbrinton01** [comment] 2016-08-25 23:58
Closing, duplicate of #6245

**Closed as completed by mbrinton01** 2016-08-25 23:58 UTC
Labels: Progress: needs update
