### ISSUE TITLE
Multi Store view for Customizable Options of products do not work

### ISSUE THREAD

**Issue by alen9788** [magento/magento2#7954] opened 2016-12-25 15:52 UTC
### Preconditions

1. M2.1.3
2. 

### Steps to reproduce

We have the store view of EN,DE,FR but the Customizable Options of products do not work.
e.g
For EN store view.
Option Title: color
Title: Gray.

And we switched the store view to DE
translated them to German
Option Title: Farbe
Title: grau

Then we switched back to the EN store view

### Expected result

The EN store view should keep the original data.

### Actual result

But the EN store view's data was also changed to the German. Same issue happened for the store front.
That means there is only one language for the Customizable Options. The translation does not work at all.

**Comment by AlexWorking** [comment] 2017-06-21 07:46
Hi. We created an internal ticket for Your issue - MAGETWO-70038. You'll be informed right after the bug is fixed. Thank You for applying.

**Comment by mileswilhelm** [comment] 2017-06-30 13:37
I posted a solution to this in the reference issue #6640

**Comment by magento-engcom-team** [comment] 2017-10-05 09:30
@alen9788, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-05 09:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog, Issue: Format is valid
