### ISSUE TITLE
Quote Item - Duplicate sku in same quote

### ISSUE THREAD

**Issue by vlauria** [magento/magento2#7679] opened 2016-12-05 12:09 UTC
### Preconditions (*)
1. Magento 2.4-develop branch

### Steps to reproduce (*)
1. Create an account on frontend and log in to this account on frontent
2. Go to category page, click "♥" icon for product1 (just simple product) to add it to wishlist
3. On the wishlist page click **"Add to cart"** button on the product (NOTE: use button add to cart for single item. NOT ADD ALL TO CART).
4. Open developer console and remove "PHPSESSID" cookie (to emulate that session cookie already expired)
5. Go to the same category as in step 2, add to cart product 1
6. Click "Log In" and login to the same account as in step 1

### Expected result (*)
You should see in cart one product with qty 2:
![image](https://user-images.githubusercontent.com/1873745/78531492-2e3ea280-77ee-11ea-9510-f01cfcbce8de.png)

### Actual result (*)
You see in cart two exactly the same products in cart, each with qty 1:
![image](https://user-images.githubusercontent.com/1873745/78531451-1535f180-77ee-11ea-8cbc-5c0d27f98430.png)

### Additional info:
@princeantil90 provided video for reproducing this issue https://nimb.ws/wcJX67

**Comment by wert2all** [comment] 2016-12-13 14:46
Please provide more concrete steps for reproducing because I got a merged quantity in my cart.

**Comment by vlauria** [comment] 2016-12-13 17:07
Precondition:
Magento CE 2.1 without sample data is installed.
Wishlist is set up

Steps to reproduce:
Logged user on frontend. Add one product to wishlist and from wishlist page add to cart. (NOTE: use button add to cart for single item. NOT ADD ALL TO CART).
Clear cookie or session id (SO LOGOUT USER ON FRONTENT) after logout go to category page and add same product to cart.
Login on frontend.

Expected result:
One row in quote_item table with merge quantity
Actual result:
In quote_item I have two row with same sku.

**Comment by wert2all** [comment] 2016-12-16 10:38
Can you upgrade to 2.1.3 and try to reproduce?

**Comment by vlauria** [comment] 2017-02-09 08:33
I tested it with 1.2.3 and 1.2.4, it does not work

**Comment by ulftietze** [comment] 2017-05-17 12:13
Hey guys,

we have this bug in our System (Magento 2.1.2, PHP 7) too.
So i tried to figure out why this happens and stepped into the Magento Core.

During \Magento\Quote\Model\Quote->merge() Magento compares the quote items (to merge guest and customer quote) against each other.
The comparison between the two items happens on different steps:
1. Compare ProductIds against each other
2. Grep the options of each item and make an array_diff_key() against.
3. Compare every option value against each other.

In this case, the problem comes in step 3, because in here we have the option key "info_buyRequest" with different values.
In the item, which was added by wishlist:

```
$targetOptions['info_buyRequest'] = [
        "item": "someItemId",
        "product": "theproductid",
        "originQty": "someOriginQty" // This is filled in \Magento\Wishlist\Model\Item->getBuyRequest()
];
```
In the item, which was added by default from category or detail page:
```
$comparedOptions['info_buyRequest'] = [
        "product": "theproductid"
];
```

![auswahl_021](https://cloud.githubusercontent.com/assets/12051528/26152278/925d0888-3b06-11e7-8614-f88778e0e8bd.png)

As you can see, the values differ and added the same quote items twice.
As far as i know, these options are for special cases like:
- Adding a configurable product from wishlist to cart
- May have a superspecialproduct with super unique options which would 

A really crappy solution to this problem is to comment out or remove the 3rd step of the compare function, but I don't know what is going to happen.
This is probably a Bug in Magento Wishlist.

**Comment by magento-engcom-team** [comment] 2017-09-25 22:00
@vlauria, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.1.9

**Comment by magento-engcom-team** [comment] 2017-09-26 22:01
@vlauria, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Comment by Jimgitsit** [comment] 2017-11-30 16:51
I'm seeing this in 2.1.7.

**Comment by franckgarnier21** [comment] 2018-03-08 07:59
@magento-engcom-team : Can we have a commit reference for the fix applied ?

Because on my side, if I add the same product to the cart multiple times in a very short delay, I get 2 same quote item row even if the stock quantity is 1.

Many thanks.

**Comment by drew7721** [comment] 2018-07-16 21:57
I have the same issue. 

- Magento 2.2.5
- PHP 7.1

In a custom carrier class I am using the `getAllItems` method from the `\Magento\Quote\Model\Quote\Address\RateRequest` class and it returns duplicate items in the quote. Both items have the same sku and share almost the same proprieties but only one of them has the correct price info and the other the correct stock information.

This is :100: a bug and the ticked should be reopened and fixed. 

Here are some screenshots: 

<img width="751" alt="screen shot 2018-07-16 at 5 48 34 p m" src="https://user-images.githubusercontent.com/9411699/42785541-e73c6830-8920-11e8-9b50-c404a7f7da57.png">
<img width="857" alt="screen shot 2018-07-16 at 5 46 47 p m" src="https://user-images.githubusercontent.com/9411699/42785671-6517c9ca-8921-11e8-8c0a-11d9228c7bd4.png">
<img width="861" alt="screen shot 2018-07-16 at 5 47 00 p m" src="https://user-images.githubusercontent.com/9411699/42785659-58358f26-8921-11e8-8a43-3c0cdffdf717.png">

**Update**
If you look in the `Flatrate` shipping class (line 108) this code skips the items that don't belong 

    if ($item->getProduct()->isVirtual() || $item->getParentItem()) {
        continue;
    }

I guess this can be used as a fix, but in my opinion items should not be added twice to the quote, the proprieties should be merged and only one should exist.

**Comment by ihor-sviziev** [comment] 2020-04-03 20:04
Seems like we have fix for this issue that was closed as can’t reproduce, also I see that there was added additional info that could help reproduce the issue.
Reopening this issue for confirmation that it still valid

**Comment by ihor-sviziev** [comment] 2020-04-03 20:18
> I have the same issue.
> 
> * Magento 2.2.5
> * PHP 7.1
> 
> In a custom carrier class I am using the `getAllItems` method from the `\Magento\Quote\Model\Quote\Address\RateRequest` class and it returns duplicate items in the quote. Both items have the same sku and share almost the same proprieties but only one of them has the correct price info and the other the correct stock information.
> 
> This is 💯 a bug and the ticked should be reopened and fixed.
> 
> Here are some screenshots:
> 
> <img alt="screen shot 2018-07-16 at 5 48 34 p m" width="751" src="https://user-images.githubusercontent.com/9411699/42785541-e73c6830-8920-11e8-9b50-c404a7f7da57.png">
> 
> <img alt="screen shot 2018-07-16 at 5 46 47 p m" width="857" src="https://user-images.githubusercontent.com/9411699/42785671-6517c9ca-8921-11e8-8c0a-11d9228c7bd4.png">
> 
> <img alt="screen shot 2018-07-16 at 5 47 00 p m" width="861" src="https://user-images.githubusercontent.com/9411699/42785659-58358f26-8921-11e8-8a43-3c0cdffdf717.png">
> 
> **Update**
> If you look in the `Flatrate` shipping class (line 108) this code skips the items that don't belong
> 
> ```
> if ($item->getProduct()->isVirtual() || $item->getParentItem()) {
>     continue;
> }
> ```
> 
> I guess this can be used as a fix, but in my opinion items should not be added twice to the quote, the proprieties should be merged and only one should exist.

Hi @drew7721,
I just reviewed your screenshots and it looks like expected behavior.

When you have configurable product - you’re having in cart actually two products, one relates to “configurable” product, while other relates to “simple”. That’s needed for association that you bought this product from configurable. Also you could add the same product as a simple, in this case you’ll have only one. You could see that on your screenshots you have different product_id values for those 2 products.

**Comment by ihor-sviziev** [comment] 2020-04-06 06:51
Hi,
@princeantil90 provided following video to reproduce this issue:
https://nimb.ws/wcJX67

**Comment by ihor-sviziev** [comment] 2020-04-06 06:51
@magento give me test instance

**Comment by ihor-sviziev** [comment] 2020-04-06 06:52
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-06 06:52
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-06 06:52
Hi @ihor-sviziev, here is your [Magento instance](https://i-7679-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-7679-2-4-develop.instances.magento-community.engineering/admin_1743](https://i-7679-2-4-develop.instances.magento-community.engineering/admin_1743)
Login: `e63c5858` Password: `a24f6d9af8c6`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-04-06 07:09
:white_check_mark: Confirmed by @ihor-sviziev 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33098` were created

**Issue Available**: @ihor-sviziev, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Kilo** [comment] 2020-04-30 12:46
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-30 12:46
Hi @engcom-Kilo. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-30 12:47
Hi @engcom-Kilo, here is your [Magento instance](https://i-7679-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-7679-2-4-develop.instances.magento-community.engineering/admin_d6c1](https://i-7679-2-4-develop.instances.magento-community.engineering/admin_d6c1)
Login: `50d1c56d` Password: `bc2a3313687e`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment] 2020-04-30 19:18
Hi @vlauria,
We weren’t able to reproduce this issue on 2.4-develop branch anymore. More info https://github.com/magento/magento2/pull/27548#issuecomment-621819654
Unfortunately I don’t have exact commit(s) that fixed this issue, but as it’s not reproducing - I’m closing this issue

**Closed as completed by ihor-sviziev** 2020-04-30 19:18 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Quote, Component: Wishlist, Reproduced on 2.4.x, Fixed in 2.4.x, Severity: S3
