### ISSUE TITLE
Date attribute import timezone bug

### ISSUE THREAD

**Issue by vseager** [magento/magento2#33705] opened 2021-08-06 16:38 UTC
### Preconditions (*)

1. Magentop 2.4.2-p1

### Steps to reproduce (*)

1. Set locale to English (United Kingdom) and timezone to GMT (London)
2. Create a custom DATE attribute
3. Import date attribute for product via CSV

### Expected result (*)

1. Date attribute updates with value in CSV

### Actual result (*)

1. Product has completely random date.

Example CSV:

```
"sku","sort_date"
53610,"07/15/2021"
```

![screenshot-2021 08 06-17_27_53](https://user-images.githubusercontent.com/2035088/128542947-aac5da55-77c9-4b09-b5c2-1410dabb2460.png)

**Note:** I tried using other date formats in the CSV, for example the UK format which would be "15/07/2021" but it would not pass the "Check Data" step during the import process. I also tried many other variations... "2021/07/15", "2021/15/07" etc.

![screenshot-2021 08 06-17_37_08](https://user-images.githubusercontent.com/2035088/128543376-bd08acb8-cad3-4a79-9e21-b39cd3c9d956.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2021-08-12 07:46
Hello @vseager,

We have tried to reproduce the issue in the 2.4-develop branch but are unable to do so. We have tried the steps mentioned in the attached document. Please have a look and let us know if we missed anything.

[ISSUE - 33705 -Date attribute import timezone bug.docx](https://github.com/magento/magento2/files/6973640/ISSUE.-.33705.-Date.attribute.import.timezone.bug.docx)


Thanks

**Comment by vseager** [comment] 2021-08-12 08:49
@engcom-Hotel In your screenshot the timezone is set to Central Standard Time. Can you test again with this set to GMT (London).

**Comment by davidwindell** [comment] 2021-08-13 11:25
Possible duplicate of #25700 ?

**Comment by vseager** [comment] 2021-08-13 11:31
I have retested and can confirm that the issue is related to locale settings on the admin user. When I set my admin user locale to "English (United States)" I can import the date, when it's set to "English (United Kingdom)" the issue occurs.

**Comment by engcom-Hotel** [comment] 2021-09-13 08:30
Hello @vseager,

We have tried to reproduce the issue after making changes as per the above comment. It has been observed that, if we are passing date with format "YYYY/MM/DD" then no error has been occurs but in case of "DD/MM/YYYY" format, the issue is occurs.

Please have a look into below screenshot:

With Date Format YYYY/MM/DD:

![image](https://user-images.githubusercontent.com/51681618/133049984-da755987-0faa-43a5-b8d8-5c3c1c9745df.png)

After uploading the date has format "DD/MM/YYY":

![image](https://user-images.githubusercontent.com/51681618/133050414-34c8326b-db3a-40e5-885d-c51e7a48d930.png)


With Date Format DD/MM/YYYY:

![image](https://user-images.githubusercontent.com/51681618/133050138-7a92575e-cc2c-40e1-9a90-1f8f31c12fe3.png)

Please try to pass date format in "YYYY/MM/DD" format and let us know if you still able to reproduce the issue.

**Comment by vseager** [comment] 2021-09-20 09:30
@magento give me 2.4.3 instance

**Comment by vseager** [comment] 2021-09-20 11:23
@engcom-Hotel 

I have tested this again both on the provided Magento 2.4.3 instance and our local environment.

The test on the provided Magento instance didn't work at all, although I don't know if this could be an indexing issue (is there a way to run indexes on the develop instances?).

Here is a screencast from the test:  
![screencast-nimbus-capture-2021 09 20-11_28_10](https://user-images.githubusercontent.com/2035088/133993455-afb78916-b2b0-4948-98e7-09e68847d379.gif)

Your screenshots show the successful import but don't show the result on the product itself. I tested it again in our local environment using the date format `DD/MM/YYYY` as you suggested. The import appears to work okay but the date that actually appears on the product is completely random:

**CSV:**
```
"sku","sort_date"
"53610","2021/12/15"
```

**Successful Import:**
![screenshot-hardcloud2 staging edge-servers com-2021 09 20-11_33_15](https://user-images.githubusercontent.com/2035088/133994390-f06e552a-acf6-4447-b5b2-79c7b95cae8f.png)

**Wrong date on product:**
![screenshot-hardcloud2 staging edge-servers com-2021 09 20-11_59_42](https://user-images.githubusercontent.com/2035088/133994388-fdb14cbe-0ddb-43bd-8b66-abc165e32e6e.png)

**Comment by engcom-Hotel** [comment] 2021-09-20 17:26
Hello @vseager,

Thanks for the reply!

> The test on the provided Magento instance didn't work at all, although I don't know if this could be an indexing issue (is there a way to run indexes on the develop instances?).

Indexing is not required here after updating.





> Your screenshots show the successful import but don't show the result on the product itself.

Please refer the below screenshot with correct date:

![image](https://user-images.githubusercontent.com/51681618/134046442-454a9392-677a-4a26-b8e0-c4176492dae5.png)

We have tried to reproduce the issue in Magento 2.4-develop branch and the issue is not reproducible. Please try to reproduce the issue in Magento 2.4-develop.

Thanks

**Comment by vseager** [comment] 2021-09-21 15:26
@magento give me 2.4.3 instance

**Comment by vseager** [comment] 2021-09-21 15:45
Can no longer reproduce on 2.4.3 or 2.4-develop

**Comment by vseager** [comment] 2022-10-28 15:03
This issue seems to have resurfaced. Tested on 2.4.3-p3

**Comment by engcom-Hotel** [comment] 2022-10-31 11:47
Hello @vseager,

Thanks for reopening the issue!

Just a question, is the issue reproduction are same as mentioned in the main description, or changed?

Thanks

**Comment by vseager** [comment] 2022-11-02 16:10
@engcom-Hotel Yes I can confirm that the steps to reproduce are the same as the original description.

**Comment by engcom-Bravo** [comment] 2022-11-03 08:50
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-11-03 10:41
Hi @vseager,


Thank you for reporting and collaboration.

Verified the issue on Magento `2.4-develop` and the issue is not reproducible.Kindly refer the screenshots.


Steps Followed:

1.Set locale to English (United Kingdom) and timezone to GMT (London)
2.Create a custom DATE attribute
3.Import date attribute for product via CSV



<img width="1219" alt="Screenshot 2022-11-03 at 3 57 38 PM" src="https://user-images.githubusercontent.com/51680745/199700200-d48d1581-8354-4add-9ac3-a766316f14d8.png">



CSV File:

[99.csv](https://github.com/magento/magento2/files/9927523/99.csv)


Kindly recheck the issue on latest Magento 2.4-develop instance and Please let us know if you are still facing any issue.

Thanks.

**Comment by vseager** [comment] 2022-11-14 10:12
@magento give me 2.4.3-p3 instance

**Comment by engcom-Bravo** [comment] 2022-11-17 06:14
Hi @vseager,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-11-17 06:14 UTC
Labels: Issue: needs update, Reported on 2.4.2-p1

**Comment by vseager** [comment] 2022-11-18 09:34
https://github.com/magento give me 2.4.3-p3 instance

**Comment by vseager** [comment] 2022-11-18 09:39
@magento give me 2.4.3-p3 instance
