### ISSUE TITLE
Catalog Price Rule with Condition Category Is Not One Of not applied to products without a category

### ISSUE THREAD

**Issue by timpea** [magento/magento2#32734] opened 2021-04-13 11:12 UTC
### Preconditions (*)

1. Magento 2.4.2

### Steps to reproduce (*)

1. Create 3 products, 
2. 1 product in a category "no discount"
3. 1 product in a category "10% off"
4. 1 product with no category
5. Create a Catalog Price Rule - 10% Original Price, in conditions add Category is not one of and select "no discount" category
6. Create an order with all 3 products

### Expected result (*)

1. The product that is not applied to a category should have **10% off**
2. The product in "10% off" should have 10% off.
3. The product in "no discount" should be at full price

### Actual result (*)

1. The product that is not applied to a category is at **full price**
2. The product in "10% off" has 10% off.
3. The product in "no discount" is at full price

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by timpea** [comment] 2021-04-13 11:12
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment] 2021-04-14 09:39
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41893` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by iphigenie** [comment] 2021-04-15 16:19
Hi

I was about to report a similar bug: the same thing happens with multiselect attributes - products which do not have the attribute set at all are not returned as matches for a "not one of" for a value of that attribute.

**Comment by gabrieldagama** [comment] 2021-04-20 16:33
Hi @timpea, can you provide some PrintScreen with the details of the Catalog Rule configuration?

Thanks!

**Comment by iphigenie** [comment] 2021-04-21 14:03
hi @gabrieldagama i have illustrated it for multiselect on #32805 but it'd be the exact same for categories as I suspect it is the same query building logic in the back end.

The "is not one of" or "does not contain" options will not included undefined entries.

For a dropdown attribute, there is an "is undefined" condition so one can do "is not or is undefined" to get the "intuitive" result.

It is not available for categories or for multiselect

For categories there is a workaround which is create a non visible categories containing all products - there is no such workaround for multiselect as it would show.

**Comment by timpea** [comment] 2021-04-22 14:53
@gabrieldagama @iphigenie 

Correct, I have also just noticed we have a rule Manufacture is not Apple,  this rule doesn't apply to any products that don't have a manufacture applied.

**Comment by iphigenie** [comment] 2021-04-24 11:43
@timpea 

For manufacturer you can add "manufacturer is not Apple OR manufacturer is undefined" to get what a human would expect

We don't have an "is undefined" for categories or for multiselect, and I suspect the solution will be to add such criteria options and make it more obvious to humans in documentation what the computer logic is 

Similar to how the difference between "contains" (has that option) and "is one of" (has only that option) is clear, but the names certainly are not

**Comment by timpea** [comment] 2021-04-27 15:40
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by timpea** [comment] 2021-04-27 16:05
@iphigenie I hadn't spotted the "is undefined" option for the attribute.  That works as expected.

Agree, it could do with having this same option for the categories and documentation updating.

**Comment by iphigenie** [comment] 2021-05-25 14:52
Just keeping this one alive too - the existence of a "no category assigned" condition would solve this one just like the "no option selected" condition for a multiselect would solve my other bug  #32805

**Comment by jsamhall** [comment] 2022-10-24 18:29
Over a year later... any update on this? It seems to be resolved in 2.4.5 based on what I have exposure to, but I don't see an official remark anywhere

**Comment by engcom-Bravo** [comment] 2024-07-19 05:56
Hi @timpea,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.

<img width="1404" alt="Screenshot 2024-07-19 at 11 18 35" src="https://github.com/user-attachments/assets/b592eaed-4e30-438a-980a-f77ea661f603">


Product COnfigureeee is not in any category having 10 % discount.
Product Simple in "10% off" having 10% off.
Product Joust Duffle Bag  in "no discount" having full price


Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-07-19 05:56 UTC
Labels: Issue: Confirmed, Component: SalesRule, Reproduced on 2.4.x, Priority: P3, Progress: done
