### ISSUE TITLE
Duplication of store instance

### ISSUE THREAD

**Issue by alexmtch** [magento/magento2#37202] opened 2023-03-13 15:36 UTC
### Preconditions and environment

- Magento version : 2.4.5
- Anything else that would help a developer reproduce the bug : In graphql queries

### Steps to reproduce

- Run any graphql query
- Debug `in vendor/magento/module-store/Model/StoreManager.php` in `getStore` function return by using xdebug or `var_dump(spl_object_id($store) . ' : ' . $storeId);`

### Expected result

Always the same combinaison of object id / store id

### Actual result

At certain times the object id is different

### Additional information

It's due to the `vendor/magento/module-store/Model/StoreRepository.php` `getList` function.
It recreate a brand new instance of the store without checking if it's already exists.

It's also due to `vendor/magento/module-store-graph-ql/Controller/HttpRequestValidator/StoreValidator.php` which load all the stores instead of only the current store.

From my opinion both should be fixed to avoid theses cases which can produce board effects (like multiple reloading of currencies, or store datas, ...)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Hotel** [comment] 2023-03-14 10:14
Hello @alexmtch,

Thanks for the report and collaboration!

We have tried to reproduce the issue in Magento 2.4-develop branch but the issue is not reproducible for us. In order to reproduce the issue we have logged the string `$text = spl_object_id($store) . ' : ' . $storeId . "\r\n";` in a file and then inspect the content of the file and we got something like below:

```
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : 1
352 : default
352 : default
352 : default
352 : default
352 : default
352 : default
352 : default
352 : 1
352 : default
352 : 1
352 : default
352 : default
352 : default
352 : default
```

We have used the below mutation:

```
mutation createAccount {
    createCustomer(
        input: {
            email: "test@magento.com"
            firstname: "Test"
            lastname: "Magento"
            password: "T3stP4assw0rd"
            is_subscribed: false
        }
    ) {
        customer {
            id
        }
    }
}
```

Please let us know if we have missed anything.

Thanks

**Comment by alexmtch** [comment] 2023-03-14 10:23
Hello @engcom-Hotel could you try with a query (i tried with a product query filtered on a sku for example) maybe for mutations it doesn't works due to the fact that mutations are post and not get.

Also i'm using the Magento 2.4.5 enterprise edition

**Comment by engcom-Hotel** [comment] 2023-03-15 10:21
Hello @alexmtch,

Thanks for the reply!

As per your reply, we have checked the issue with the below query:

```
{
  products(
    search: "Messenger"
    filter: { price: { to: "50" } }
    pageSize: 25
    sort: { price: DESC }
  ) {
    items {
      name
      sku
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    total_count
    page_info {
      page_size
    }
  }
}

```

it seems this time also the issue is not reproducible for us. Please review the log file below:

```
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : 1
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : 1
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : 1
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : 1
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
2560 : admin
350 : 1
350 : 1
350 : 1
350 : 1
350 : default
350 : default
350 : 1
350 : default
350 : default
350 : 1
350 : 1
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
350 : default
```

Let us know if we have missed anything.

Thanks

**Comment by engcom-Hotel** [comment] 2023-03-29 05:55
Dear @alexmtch,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2023-03-29 05:55 UTC
Labels: Triage: Dev.Experience, Issue: needs update, Reported on 2.4.5

**Comment by alexmtch** [comment] 2023-04-05 08:52
If you do not reproduce, maybe you could close. It's strange we don't have the same 🤔
