### ISSUE TITLE
Create a Media Library for reusing images

### ISSUE THREAD

**Issue by CRYX2** [magento/magento2#1457] opened 2015-07-08 09:31 UTC
Hello to all, it think it could be very usefull creating a media library for storing and retreving all uploaded files (for example like the Drupal media module: https://www.drupal.org/project/media).

It's very usefull for the users reusing an uploaded file for a product or for a custom entity (like news or blogs).

**Comment by roshimon** [comment] 2015-07-08 16:54
Yeah good idea.

**Comment by CRYX2** [comment] 2015-07-08 18:54
I do not think we should necessarily make a complex system such as Drupal.
Without realizing systems too complex, creating a file as a single entity will simplify reuse and also any translation.

For example in optical SEO, an entity file may be composed of some additional fields such as Alt tag, or better still might have a chance to rewrite his url.

I think for a system so advanced as Magento this feature is now mandatory.

**Comment by choukalos** [comment] 2015-07-09 19:52
Assigning to Tanya; we have a backlogged epic that covers a lot of this ( MAGETWO-4527 ).

**Comment by roshimon** [comment] 2015-07-12 08:42
Hi,

I'd like to add you to my professional network on LinkedIn.

- roshi

Confirm that you know roshi: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0Z8x_U1g&amp;invitationId=6025916685117071360&amp;trk=eml-guest-invite-cta&amp;trkEmail=eml-invite_guest-null-2-null-null-%7E5quj5k%7Eic08ffcb%7El


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-5quj5k-ic08ffcb-l&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQFHMzUjKh-yBwAAAU6BbYbY6Z3kF9xwyLoqiHLWmckZSyGxwyJ9gsYzwv2Dzp4BLPROfSRKIbjCgxmas3izyXWIv57_bVwNOqaIpeLbv1eln4HQK6IU8qqW2r2_IfDS_4axtZP2L5wNiWYynYKG855puOCEUd4o1IggmARimfVM7DPcAF7-GVSR9iuurhl2shQ6&amp;eid=-5quj5k-ic08ffcb-l Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=-5quj5k-ic08ffcb-l&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by Vinai** [comment] 2015-07-12 19:06
Can someone block this guy please?

**Comment by roshimon** [comment] 2015-07-14 14:11
Who bro ?

**Comment by roshimon** [comment] 2015-07-16 09:00
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0MdzcNdP0Tcj4Re3oScjARcz0Sfkh9rCZFt65QqnpKqipDcllvu3xqc3RVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4Cuj4JsClPsCYRoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3gMdzkRd30ScjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCuj4JsClPsCYRoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mlCczsSejkMpmcVdz5xczAOc31yd68Ncj4Mc30Mc30MpCcOejgMpjAMd3cMdmoNejsNpzwPc69Bcj8OomkVdj5BoCoRom8OdjcVd30Tp3gSd3kMc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0ScP4Tc3sNcjkUdzoNejkOc3oZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCuj4JsClPsCYRoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1VciROpndOrPlzqiRHdmFRsjkJfmhFpipIuzdErCZQjP9Nh5pfdSlypTddoP0McnhbqStLhABfglAQcmgRcltfimRApkp1bld8lmkJenFdtQgPpCMRk4hypSpzimJ3dzB1sjsNsQ9hgAhRjAIVh4pMqkxbhB5zh59zlRBziQpbjAx1hT9Ui6ZHuz1ooQxSnORUi7BHjPtNgPdGiDFShmAVc3BWqTFVjkZfln5dcDoOoSATrzxChlxxh4MMoQsTpBx9k6N9pPsRhBsSlk51gmt5jPdcgjB4dzBhhR51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCuj4JsClPsCYRoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916703702020096_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cuj4JsClPsCYRoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by roshimon** [comment] 2015-07-24 01:01
roshi mon would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=30ScP4Tc3sNcjkUdzoNejkOc3oZh4BKrSBQonhFtCVF9CsNllZUe5EMfnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCcPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4Cq38JpTtzdmVDoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

View roshi mon&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=d30SdjkQc3oNfkh9sClyrmlJ9DhUpnhvpmNFpCZOs3RPt2pLsClEfmQCd3RFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCtD1KfngCq38JpTtzdmVDoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2lBpz8TdzARc6lzejoNoj8Vcz0Mozhycj4Nc30Mc30Mc6pzczAQc6kVc3gPc3lCcjATcmoUcP1ypj4OcC5BejkNpm9Cdm5yczkPejgMdSgQdzgRc312cylVr71BszRIqm5JpioMdz0MczRAqioMdzcNdP0Tcj4Re3oScjARcz0SfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCq38JpTtzdmVDoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6wObmtToPlKpSdFbmIRqDlNdiQZp6BB9ApmtBxScl9mikNTpjtIuAROjRtOcnxkdzBhlyRPentenSAVt3BCtQB9rSMNdDcVdjsQh69ntC5Vj51KsDwSkRxKsmxjiD93r49InSJlrDhUomRCrmFTukt3mz9TkBgSm695tkVWhD9lgS53sCcQsCVfkTp7eklTiPsNiztTjlt1em5Fs79egjlluj5GnTlIdD1QdkFyq5Zdcn9TrPtigmxznSxquDtdbjh8lDkOnQdIejplgk51pQpetn9fc5oOulx8kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCq38JpTtzdmVDoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I6025916703702020096_500&amp;markAsRead=This email was intended for magento/magento2. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cq38JpTtzdmVDoSAJqPlGtn4RbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I6025916703702020096_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by piotrekkaminski** [comment] 2016-08-30 20:11
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Create-a-Media-Library-for-reusing-images/idi-p/47263).

**Closed by piotrekkaminski** 2016-08-30 20:11 UTC
Labels: acknowledged, feature request, moved_to_forums, PROD
