### ISSUE TITLE
Bug in GET /V1/products Pagination

### ISSUE THREAD

**Issue by huynguyen0257** [magento/magento2#39031] opened 2024-08-09 11:31 UTC
### Preconditions and environment

- url: 'https://as98.net/rest/V1/products'
- headers: { Authorization: 'Bearer <administrator token>' }
- Query: {
      fields: undefined,
      'searchCriteria[filter_groups][0][filters][0][field]': 'website_id',
      'searchCriteria[filter_groups][0][filters][0][condition_type]': 'eq',
      'searchCriteria[filter_groups][0][filters][0][value]': 2,
      'searchCriteria[sortOrders][0][direction]': 'DESC',
      'searchCriteria[sortOrders][0][field]': 'id',
      'searchCriteria[currentPage]': 1,
      'searchCriteria[pageSize]': 500
    }

### Steps to reproduce

I want to export report for my client with their credentials for product metadata

1. Call to GET /V1/products with pagination 
- currentPage = 1
- pageSize=500
- sort desc by id (for sure paging working, i already test call without searchCriteria[sortOrders])
- filter website_id = '2'

2. When data return, i handle pagination 
- check if total_count > currentPage * pageSize -> currentPage = currentPage + 1;
- loop again

3. After a year, i detect the error with your pagination
- Your paging return duplicate record when i move to next page
- It appears in the records near the end.
- With my client AS.98
Magento return total_count = 16349
I skip duplicate records and count by my process = 16106 <--- That not constant
I cal duplicate occur 243 times <--- That not constant
I check and see magento_total_count - my_total_count = duplicate_times (16349 - 16106 = 243)

### Expected result

- magento_total_count = 16349
- my_total_count (without duplicate) = 16349
- duplicate_times = 0

### Actual result

- magento_total_count = 16349
- my_total_count (without duplicate) = 16106
- duplicate_times = 243
[logs-as98.txt](https://github.com/user-attachments/files/16560512/logs-as98.txt)

### Release note

Fix Get Product Pagination

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by huynguyen0257** [comment] 2024-08-09 12:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-12 09:44
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2024-08-12 10:10
Hi @huynguyen0257,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

<img width="869" alt="Screenshot 2024-08-12 at 15 38 52" src="https://github.com/user-attachments/assets/97dcf3c3-e10e-4b78-af87-60a4d3c51539">


Kindly recheck the issue in Latest 2.4-develop instance and the elaborate the steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2024-08-23 05:30
Hi @huynguyen0257,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2024-08-23 05:30 UTC
Labels: Issue: needs update, Reported on 2.4.x
