### ISSUE TITLE
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() 

### ISSUE THREAD

**Issue by ubedrajput** [magento/magento2#35657] opened 2022-06-22 06:18 UTC
magento ver 2.4.4
magento2 upgrade 2.4.4 i m doing setup upgrade give this type of error
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /var/www/test.test/public_html/vendor/magento/framework/Reflection/TypeProcessor.php on line 550

**Comment by engcom-November** [comment] 2022-06-22 11:59
Hi @ubedrajput ,
Thank you for reporting and collaboration. Verified the issue by installing 2.4.4 Project-community-edition with PHP 8.1 version and performed setup:upgrade but could not able to reproduce the issue. Kindly recheck the issue as per [System requirements](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html) and elaborate configuration details / any 3rd party extensions / modules enabled is causing this issue.
Thank you.

**Comment by hostep** [comment] 2022-06-22 20:22
Does the [following comment](https://github.com/magento/magento2/issues/22773#issuecomment-1111790015) help in finding a solution @ubedrajput?

**Comment by engcom-November** [comment] 2022-07-06 09:40
Hi @ubedrajput ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue f you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-07-06 09:40 UTC
Labels: Triage: Dev.Experience, Issue: needs update

**Comment by elizad** [comment] 2022-08-30 15:24
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName(): Argument #2 ($typeName) must be of type string, null given, called in /var/www/html/m/vendor/magento/framework/Reflection/TypeProcessor.php on line 550  when updrading to M.4.5 FRM M4.3

**Comment by Kerolusnasser** [comment] 2022-09-01 01:30
One of your custom modules is not Magento 2.4.* compatible.
you should update your custom modules to the updated version , it solved my issue

**Comment by davidduong90** [comment] 2022-09-27 04:08
@Kerolusnasser Thank you! In my case, I need to update plugin Magefan_Blog

**Comment by sanaeefar-saeed** [comment] 2022-12-09 04:41
it's all about doc block you can read more about it here:
**best practice**
https://magento.stackexchange.com/questions/354838/error-when-upgrading-to-magento-to-2-4-4
 **cowboy way!:**
  https://stackoverflow.com/questions/57720302/upgrade-magento-2-2-2-3-2-type-error-occurred-when-creating-object-magento
