### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by sdzhepa** [magento/magento2#29701] opened 2020-08-20 15:37 UTC
test
 er
1. 1
1. 2
1. 3

**Comment by magento-engcom-team** [comment] 2020-08-20 15:37
@sdzhepa Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Add `"Component: "` label(s) to this ticket based on verification result. If uncertain, you may follow the best guess
- [ ] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2020-08-20 15:38
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-36887` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2020-08-20 15:47
Hi @sdzhepa, @sdzhepa. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-36887` was closed as `non-reproducible` in `2.4-develop`.
It means that Magento team either unable to reproduce this issue using provided _Steps to Reproduce_ from the **_Description section_** on clean Magento instance or the issue has been already fixed in the scope of other tasks.

But if you still run into this problem please update or provide additional information/steps/preconditions in the **_Description section_** and reopen this issue.

**Closed as completed by magento-engcom-team** 2020-08-20 15:47 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Issue:  Cannot Reproduce, Issue: Format is not valid, Component: Admin
