### ISSUE TITLE
GET /V1/products/attributes/{attributeCode}/options only returns label value for Default View

### ISSUE THREAD

**Issue by oefterdal** [magento/magento2#26374] opened 2020-01-13 14:55 UTC
**Preconditions (*)**

    Magento 2.3.3

**Steps to reproduce (*)**

When i request
/V1/products/attributes/{attributeCode}/options
It only returns label and value for Default View

**Actual result (*)**
```
[
 {
  "label":"abc",
  "value":"123"
 }
 {
  "label":"abcd",
  "value":"1233"
 }
]
```

**Expected result (*)**

In the documentation at http://devdocs.magento.com/swagger/
it should return something like this:

```
[
  {
    "label": "string",
    "value": "string",
    "sortOrder": 0,
    "isDefault": true,
    "storeLabels": [
      {
        "storeId": 0,
        "label": "string"
      }
    ]
  }
]
```

This issue is the same as https://github.com/magento/magento2/issues/2733 
I can confirm that this issue is still in M2.3.3

**Comment by oefterdal** [comment] 2020-01-13 14:56
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-13 14:56
Hi @oefterdal. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-13 14:56
Hi @oefterdal, here is your [Magento instance](https://i-26374-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26374-2-4-develop.instances.magento-community.engineering/admin](https://i-26374-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by oefterdal** [comment] 2020-01-13 15:06
@magento Can confirm that this issue is on M2.4 vanilla installation also. 

`[
    {
        "label": " ",
        "value": ""
    },
    {
        "label": "Black",
        "value": "4"
    }
]`

It also includes an empty object.

**Comment by shikhamis11** [comment] 2020-01-14 18:57
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-14 18:57
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-14 18:58
Hi @shikhamis11, here is your [Magento instance](https://i-26374-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26374-2-4-develop.instances.magento-community.engineering/admin](https://i-26374-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2020-01-14 19:13
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30436` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by mallikaverma** [comment] 2020-01-29 08:58
@magento-engcom-team  give me 2.4-develop instance

**Comment by shikhamis11** [comment] 2020-01-29 09:37
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-01-29 09:37
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-01-29 09:37
Hi @shikhamis11, here is your [Magento instance](https://i-26374-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26374-2-4-develop.instances.magento-community.engineering/admin_93bc](https://i-26374-2-4-develop.instances.magento-community.engineering/admin_93bc)
Login: `470337f6` Password: `807f32adcd15`
Instance will be terminated in up to 3 hours.

**Comment by oefterdal** [comment] 2020-02-24 12:38
@shikhamis11 Did you find out anything?

**Comment by sidolov** [comment] 2020-09-15 16:50
Should be validated with store code usage in the URL

**Comment by zakdma** [comment] 2021-03-04 17:31
@oefterdal this behaviour is by default. If you dont specify store code it takes data from default one.
If you want get data (options labels) from other than default store you should specify store code in URL
Example for second store view with code **ssv**
```
curl -X GET "http://m2ee24.loc/index.php/rest/ssv/V1/products/attributes/color/options" -H "Authorization: Bearer vgo7m9wbv12gqsjlcshuqooz8y9rruvj"
```

**Comment by zakdma** [comment] 2021-03-18 13:36
Closed as not a bug

**Closed as completed by zakdma** 2021-03-18 13:36 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Issue: Format is valid, Component: Webapi, Triage: Dev.Experience, Reproduced on 2.4.x, Priority: P2, Severity: S2, Progress: done, Reported on 2.3.3
