### ISSUE TITLE
M2.1.7 : Custom options that are $1000 or more are set to $1 when saved again

### ISSUE THREAD

**Issue by kanduvisla** [magento/magento2#9995] opened 2017-06-20 14:27 UTC
Now here's an interesting one: Got this from a client, but I was able to reproduce it on a vanilla installation of Magento 2.1.7. Appearantly, when you create a custom option that is $1000 or higher and you save the product twice, the price of this option is set to $1.

Can anyone confirm this?

### Preconditions

1. Magento 2.1.7

### Steps to reproduce

1. Create a simple product
2. Add a custom option of type 'checkbox' (I had mine set to 'not required')
3. Add some options with various prices. Make sure that some of them are equal to or above $1000.
4. Save the product.
5. At this point, everything works as expected. The prices in the admin are correct and the frontend is correct as well.
6. Save the product again.

### Expected result

1. The custom options that are $1000 or higher should stay the same

### Actual result

1. The custom options that are $1000 or higher are now $1

### Update:

I found the cause of this problem: Magento is formatting the numbers. This means that a number like `1250` is formatted to `1,250.00` when the admin loads again:

![screen shot 2017-06-20 at 16 32 06](https://user-images.githubusercontent.com/346681/27338712-3bdb435e-55d6-11e7-8115-33284e921ce9.png)

Needless to say, this value is then posted to the server and converted to a (floating?) number. If I enter a higher value (3000 for example), it gets formatted to `3,000.00` and after the second save the value is `3`.

So I guess the fix to do here is either:

- Don't format them numbers, or:
- Handle this kind of locale-formatting server-side.

### Update #2:

The problem is the `\Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\CustomOptions::formatPrice()`-method that formats the value to the locale currency:

    /**
     * Format price according to the locale of the currency
     *
     * @param mixed $value
     * @return string
     */
    protected function formatPrice($value)
    {
        if (!is_numeric($value)) {
            return null;
        }

        $store = $this->storeManager->getStore();
        $currency = $this->getLocaleCurrency()->getCurrency($store->getBaseCurrencyCode());
        $value = $currency->toCurrency($value, ['display' => \Magento\Framework\Currency::NO_SYMBOL]);

        return $value;
    }

This results in the data being entered wrong in the datasource:

![screen shot 2017-06-20 at 16 32 17](https://user-images.githubusercontent.com/346681/27340667-5859992c-55db-11e7-9009-75fd37fcc2c6.png)

However, this JSON data has also the unformatted price:

    {
        "option_type_id": "52",
        "option_id": "14",
        "sku": null,
        "sort_order": "5",
        "default_title": "E",
        "store_title": "E",
        "title": "E",
        "default_price": "2000.0000",
        "default_price_type": "fixed",
        "store_price": "2000.0000",
        "store_price_type": "fixed",
        "price": "2,000.00",
        "price_type": "fixed"
    }

So perhaps a better approach would be to change the JavaScript so it uses `store_price` instead of `price` perhaps? I'll leave this one to the community to digest. In the meanwhile I'm going to write a hotfix for my client.

**Comment by veloraven** [comment] 2017-06-23 07:10
@kanduvisla thank you for your report.
I'm closing this issue as a duplicate of #6342.
This issue was fixed and the fix will be available in one of the nearest releases.

**Closed as completed by veloraven** 2017-06-23 07:10 UTC
Labels: bug report, Component: Catalog
