### ISSUE TITLE
Integrity Constraint Violation SALES_INVOICE_ORDER_ID_SALES_ORDER_ENTITY_ID

### ISSUE THREAD

**Issue by ghost** [magento/magento2#38431] opened 2024-02-07 17:11 UTC
### Preconditions and environment

- Magento version: 2.4.6-p1
- I can't find anything else written about this exact issue in other forums so it must have something to do with my environment. I'm not sure the exact workflow that magento goes through, but it seems like the order should be created and then the invoice, but this seems to be creating an invoice which is a "child" of the order due to the foreign key constraint, but without the order pre-existing, the invoice can't be created and it just fails. 
- It's worth noting that I migrated from Shopify to Magento using LitExtension and they pushed content directly into the database. I wonder if the database is "out of sync" because of something they did, and if so, I need to know how to troubleshoot and fix this.

### Steps to reproduce

Set payment method to Authorize and Capture
Complete checkout as a customer

### Expected result

Order completes and payment is captured

### Actual result

Error with report file name presented to customer. Report indicates:
PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`bitnami_magento`.`sales_invoice`, CONSTRAINT `SALES_INVOICE_ORDER_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`order_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE CASCADE

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by bbosWebServices** [comment] 2024-02-09 21:07
Im sure this is not a bug, but I just can't find anyone that can point me in the right direction of solving my problem. Any help, advice or direction to a better forum would be much appreciated.

**Comment by engcom-Dash** [comment] 2024-02-16 09:18
Closing this ticket as its not a bug.

**Closed as completed by engcom-Dash** 2024-02-16 09:18 UTC
Labels: Issue: needs update, Reported on 2.4.6-p1
