### ISSUE TITLE
Unable to set custom price to 0 within a buy request.

### ISSUE THREAD

**Issue by Beraa995** [magento/magento2#27175] opened 2020-03-05 09:52 UTC
The zero price can't be set within the prepare method in vendor/magento/module-quote/Model/Quote/Item/Processor.php. PHP empty method is registering 0 as true so it is skipped.

### Preconditions (*)
1. Use a vanilla Magento 2.3.4.
2. In vendor/magento/module-checkout/etc/frontend/di.xml remove a custom_price item from the filter list.

### Steps to reproduce (*)
1. Use the addProduct method of Magento\Checkout\Model\Cart.
2. Pass product id and buy request arguments.
3. Buy request argument should be an array containing 'custom_price' => 0.

### Expected result (*)
1. Add item to cart with 0 price.

### Actual result (*)
1. Item added to the cart with a normal product price.

**Comment by magento-engcom-team** [comment] 2020-04-08 10:06
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-33195` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by sdzhepa** [comment] 2020-05-12 23:55
Hello @Beraa995 
fyi: @krishprakash @Bal2018 

We reviewed this issue during the internal Triage Meeting with Product Managers.
_With the current description, it is not clear what is the business value of this issue_

Could you please provide more details, examples, explanations?
- what exactly user flows is broken by this issue?
- what benefits/value will be after fix?
- any dev experience for integrators will be improved?
- any other examples

This information will help to raise this issue one more time during the Triage(Prioritization) Meeting one more time.

Thank you in advance!

**Comment by sdzhepa** [comment] 2020-06-11 17:52
Due to no response https://github.com/magento/magento2/issues/27175#issuecomment-627661528 I am closing this issue.
 Business value is not clear. Magento Product Managers reject such changes

**Closed as completed by sdzhepa** 2020-06-11 17:52 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Pricing, Reproduced on 2.4.x, Reported on 2.3.4
