### ISSUE TITLE
Magento 2.1 fails to load email_logo.png

### ISSUE THREAD

**Issue by PierAlex** [magento/magento2#5633] opened 2016-07-14 07:52 UTC
Steps to reproduce
Magento 2.1 fresh installation and upgrade from 2.07 both
Also with cache enabled, disabled, flushed...
Try to upload a logo for email templates from Admin ->Content Design ->Configuration ->website ->transactional emails
Upload your logo file
Save

Expected result
New Logo for email is applied

Actual result
Previous Logo still remain

Back in the admin, in the image logo box there is the image broken icon.

![image](https://cloud.githubusercontent.com/assets/17165819/16831257/433e568e-49a4-11e6-90c7-d5a8a4d3dedc.png)

 I also create the Magento_Email/web folder under my custom theme (my fallback is Luma theme) and it does not take effects. Always Luma logo appears in the header of my e-mails (orders, invoices, shipments...).

Strange is that, just for testing, i overwrited the email_logo.png under Luma theme to see if it takes effect but nothing happens (?).

Then... back to the admin, i discover that the file is searched in pub/media/email/logo/website/<website_id>/filename.png

My Logo file was uploaded in pub/media/logo/website/<website_id>/filename.png.
No email folder in pub/media.

As a workaround, created the email folder under pub/media and saved my file (/logo/website/<website_id>/filename.png)

In the backend it takes effect and in the emails too!!

**Comment by Krapulat** [comment] 2016-07-17 23:41
I have the same problem.

**Comment by zolthan** [comment] 2016-07-28 15:22
Same problem here...

**Comment by ghost** [comment] 2016-07-30 07:43
Same issue here... 
logo saved in directory /pub/media/logo/websites/1/email_logo.png
but this should be save in /pub/media/email/logo/stores/1/email_logo.png

seems its bug in Magento 2.1

**Comment by hostep** [comment] 2016-07-30 10:03
Isn't this a duplicate of https://github.com/magento/magento2/issues/5352 which already got fixed on the develop branch?

**Comment by liquidia** [comment] 2016-08-01 13:30
here is easy fix .create a folder and put image with same name :) until it fixed officially

**Comment by GlobalOutsourcing** [comment] 2016-08-04 22:41
Same issue experienced in 2.1.

Logo is changed in backend but when template previewing the logo is the magento one.

**Comment by zolthan** [comment] 2016-08-05 04:50
Hotfix: Create a symlink from /pub/media/logo to /pub/media/email/logo ;-)

**Comment by peec** [comment] 2016-08-31 13:07
Same as #6275 .

**Comment by miakusha** [comment] 2016-10-04 13:23
Closed as duplicate #5352

**Closed as completed by miakusha** 2016-10-04 13:23 UTC
Labels: Issue: Ready for Work, bug report, Area: Frontend

**Comment by magento-team** [comment] 2017-07-31 23:01
Internal ticket to track issue progress: MAGETWO-69062
