### ISSUE TITLE
The request is allowed for logged in customer

### ISSUE THREAD

**Issue by aswinghosh-2hats** [magento/magento2#36570] opened 2022-12-06 12:19 UTC
### Preconditions and environment

- Magento version - 2.4
- Using Vuestorefront with Magento 2 and graphql
 

### Steps to reproduce

1. Run getToken API (Works fine)
mutation {
  generateCustomerToken(email: "email", password: "password") {
    token
  }
}
2. Run customerCart API with the token from step 1 - Gives error 
{
  customerCart {
    id
    items {
      id
      product {
        name
        sku
      }
      quantity
    }
  }
}
with Authorization Bearer <token>

### Expected result

{
    "data": {
        "customerCart": {
            "id": "SFEwatQQJGMP3IyqXpUuyymt35injcLc",
            "items": [] // cart details
        }
    }
}

### Actual result

{
    "errors": [
        {
            "message": "The request is allowed for logged in customer",
            "extensions": {
                "category": "graphql-authorization"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "customerCart"
            ]
        }
    ]
}

### Additional information

Connected my Vuestorefront to another Magento instance and everything works fine there. The issue is only in the new Magento backend created in an EC2 environment.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-06 12:50
Hi @aswinghosh-2hats ,
Thank you for reporting and collaboration. "Vuestorefront" is a 3rd party package and code of this extension is not part of https://github.com/magento/magento2 git repository. Verified the issue on clean 2.4-develop instance without any 3rd party modules and the issue is not reproducible. We are closing this issue as community is not able to provide fix for it in this repository. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page
Thank you.

**Closed as completed by engcom-November** 2022-12-06 12:50 UTC
Labels: Component: Bundled Extension, Issue: ready for confirmation
