### ISSUE TITLE
Something went wrong with processing the default view and we have restored the filter to its original state.

### ISSUE THREAD

**Issue by EcomMan123** [magento/magento2#38702] opened 2024-05-07 11:33 UTC
### Preconditions and environment

- Magento version
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Open Magento Orders

### Expected result

View Orders & Filter

### Actual result

"Something went wrong with processing the default view and we have restored the filter to its original state."

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-05-07 11:57
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-05-08 09:13
Hi @EcomMan123 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance and the issue is not reproducible.

We are able to Open Magento Orders and View Orders & Filter.

Please refer the attached screenshots and let us know if we missed anything.

<img width="1440" alt="Screenshot 2024-05-07 at 7 05 17 PM" src="https://github.com/magento/magento2/assets/60198592/79d6cf16-1642-40fa-95a3-6357e202e27e">

**Comment by EcomMan123** [comment] 2024-05-08 11:11
![Screenshot 2024-05-08 121116](https://github.com/magento/magento2/assets/169155242/181a27b2-2eaf-4d25-937f-4e38230cde9c)

**Comment by EcomMan123** [comment] 2024-05-08 11:12
Ive seen this is a common bug and the only temporary fix is to clear the ui_bookmark?

**Comment by engcom-Dash** [comment] 2024-05-09 06:51
@magento give me 2.4-develop instance

**Comment by engcom-Dash** [comment] 2024-05-09 13:05
Hi @EcomMan123 

Verified the issue on magento 2.4 dev instance and 2.4.7 instance the issue is not reproducible.

Please refer the attached screenshots. 

<img width="1440" alt="Screenshot 2024-05-09 at 1 58 16 PM" src="https://github.com/magento/magento2/assets/60198592/c5d2814a-9730-4504-b984-1331a9fef2ae">

<img width="1440" alt="Screenshot 2024-05-09 at 12 21 12 PM" src="https://github.com/magento/magento2/assets/60198592/3cb87829-9ded-4df1-94ae-f9953e994c30">

Please check the issue in the latest Magento instance.

**Comment by engcom-Dash** [comment] 2024-05-21 09:54
Hi @EcomMan123 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Dash** 2024-05-21 09:54 UTC
Labels: Issue: needs update, Reported on 2.4.x
