### ISSUE TITLE
spam mails sent to company website as customers 

### ISSUE THREAD

**Issue by K1mMar1tz** [magento/magento2#34046] opened 2021-09-10 09:22 UTC
### Preconditions (*)

1. 
2. 

### Steps to reproduce (*)

1. 
2. 
3. 

### Expected result (*)

1. [Screenshots, logs or description]

### Actual result (*)

1. [Screenshots, logs or description]

**Comment by engcom-November** [comment] 2021-09-10 11:59
Hi @K1mMar1tz ,
We are unable to reproduce this issue on Magento 2.4-develop branch.
**Steps performed:**
New Customer account emails are triggered to Customer only - **No issue**
New Company account email - sent to customer - **No issue**
Approval email sent to Website Owner - **No issue**
Order confirmation emails are sent to Customer only - **No issue**

Kindly recheck the issue on Magento 2.4-develop branch and elaborate steps to reproduce / missing configuration details if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2021-09-24 07:32
Hi @K1mMar1tz ,

We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2021-09-24 07:32 UTC
Labels: Issue: needs update
