### ISSUE TITLE
Login as customer opt-in checkbox not translatable

### ISSUE THREAD

**Issue by cdescamps-cleverage** [magento/magento2#32329] opened 2021-03-02 14:05 UTC
### Preconditions (*)

1. Have Magento 2.4.2 with multiple website and store view in different languages

### Steps to reproduce (*)

1. In back office >  Stores > Configuration >Customers > Login as Customer
2. Look at the scope for fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" 

### Expected result (*)

1. Fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" must be for scope "Store view" So you can translate for storeview

### Actual result (*)

1. Fields "Title for Login as Customer opt-in checkbox" and "Login as Customer checkbox tooltip" are for scope "Website" So you can't translate for storeview
![image](https://user-images.githubusercontent.com/20226525/109659299-d4626c00-7b67-11eb-8e67-261a0e7d0564.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by TheRealHunzik** [comment] 2021-03-02 14:23
@magently  give me 2.4-develop instance

**Comment by magently** [comment] 2021-03-03 12:20
@TheRealHunzik I guess you made a typo and wanted to call Magento. We can't help you with this one :)

**Comment by ejaz-alam** [comment] 2021-03-04 11:08
@magento I am working on this

**Comment by magento-engcom-team** [comment] 2021-03-04 11:59
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-41164` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by engcom-Bravo** [comment] 2024-07-12 07:22
Hi @cdescamps-cleverage,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and seems to be expected behaviour as per the magento devdocs https://experienceleague.adobe.com/en/docs/commerce-admin/config/customers/login-as-customer

Hence we are considering this as feature request.

Thanks.

**Closed as completed** 2024-12-24 15:16 UTC
Labels: Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Severity: S3, Component: LoginAsCustomer, Progress: done, Reported on 2.4.2, Area: Account
