### ISSUE TITLE
Import - Grouped Products - child products not assigned

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#12821] opened 2017-12-20 10:15 UTC
### Preconditions

1.  Magento 2.2.0, Magento 2.2.1 and Magento 2.2.2
2.  Downloaded the sample products CSV in the Admin import.

### Steps to reproduce

1.  Download the Sample Products CSV from the admin side.
2.  Change the names/values in the downloaded csv.
3.  Import that Downloaded csv from the admin side

### Expected result

1.  Simple and Grouped products should be inserted and simple products should be assigned to grouped products correctly. 

### Actual result

1.  Simple and Grouped products imported in the products section. But simple products are not assigned to grouped products.

**Comment by magento-engcom-team** [comment] 2017-12-21 06:35
@sasilinux,  thank you for your report.
Do you mean you have used optional ["Sample Data"](http://devdocs.magento.com/guides/v2.2/cloud/howtos/sample-data.html) of Magento?

**Comment by sasilinux** [comment] 2017-12-21 06:40
Yes. I have used "Sample Products CSV" that is available in the import option of the admin side.

**Comment by magento-engcom-team** [comment] 2017-12-21 14:53
Thank You @sasilinux. We are closing this issue as being a duplicate of #12793.

**Closed as completed by magento-engcom-team** 2017-12-21 14:53 UTC
Labels: Progress: needs update, Issue: Format is valid

**Comment by sasilinux** [comment] 2017-12-22 04:20
This is an important task for me, because we are going live. My client only uses product import regularly. So please let us know, if you find any solution ASAP.
