### ISSUE TITLE
Updating configurable product via REST API removes associated child products

### ISSUE THREAD

**Issue by careys7** [magento/magento2#9789] opened 2017-05-30 06:36 UTC
### Preconditions

1. Magento 2.1.6

### Steps to reproduce

1. Create configurable product via API
2. Create configurable product options for the product via API
3. Create configurable product links for the product via API 
4. PUT update the configurable product, eg:

```
PUT https://example.org/rest/default/V1/products/1565L

{
	"product":  {
		"sku": "1565L",
		"name": "Product Name"
	}
}
```
### Expected result

1. Configurable product links still associated to the product

### Actual result

1. Configurable product links disappear

**Comment by tmotyl** [comment] 2017-05-30 10:49
duplicate of #6884 and #7909 and #8371

**Comment by veloraven** [comment] 2017-06-22 07:50
I'm closing this issue as a duplicate.

**Closed as completed by veloraven** 2017-06-22 07:50 UTC
