### ISSUE TITLE
{"message":"\"Associate to Website\" is a required value."}

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magento2#25937] opened 2019-12-06 14:09 UTC
### Preconditions (*)

M 2.4-develop
1. Registered Customer

### Steps to reproduce (*)

1. Set your hostname, Customer's email and Customer's password as bash variables. In my case
```shell
endpoint="http://magento2.loc/rest";
email="John.Doe@example.com";
password="123123qA";
```
2. Get Customer token
```shell
customer_token=$(curl -X POST "$endpoint/V1/integration/customer/token" \
-H "Content-Type: application/json" \
-d "{\"username\":\"$email\",\"password\":\"$password\"}") && echo $customer_token  && customer_token=$(echo $customer_token | tr -d '"')
```
3. Try to change the **lastname** of the Customer with payload that has no `website_id` field
```shell
curl -X PUT "http://magento2.loc/rest/all/V1/customers/me" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $customer_token" \
-d "{ \"customer\": { \"firstname\": \"John\", \"lastname\": \"DoubleDoe\", \"email\": \"John.Doe@example.com\"} }"
```

### Expected result (*)

1. Message:
```json
{"message":"\"website_id\" is a required value."}
```

### Actual result (*)

1. Message:
```json
{"message":"\"Associate to Website\" is a required value."}
```

**Note**
These are all required fields. 
There is no such field as  "Associate to Website"
```
{
  "customer": {
    "id": 0,
    "group_id": 0,
    "default_billing": "string",
    "default_shipping": "string",
    "confirmation": "string",
    "created_at": "string",
    "updated_at": "string",
    "created_in": "string",
    "dob": "string",
    "email": "string",
    "firstname": "string",
    "lastname": "string",
    "middlename": "string",
    "prefix": "string",
    "suffix": "string",
    "gender": 0,
    "store_id": 0,
    "taxvat": "string",
    "website_id": 0,
    "addresses": [
      {
        "id": 0,
        "customer_id": 0,
        "region": {
          "region_code": "string",
          "region": "string",
          "region_id": 0,
          "extension_attributes": {}
        },
        "region_id": 0,
        "country_id": "string",
        "street": [
          "string"
        ],
        "company": "string",
        "telephone": "string",
        "fax": "string",
        "postcode": "string",
        "city": "string",
        "firstname": "string",
        "lastname": "string",
        "middlename": "string",
        "prefix": "string",
        "suffix": "string",
        "vat_id": "string",
        "default_shipping": true,
        "default_billing": true,
        "extension_attributes": {},
        "custom_attributes": [
          {
            "attribute_code": "string",
            "value": "string"
          }
        ]
      }
    ],
    "disable_auto_group_change": 0,
    "extension_attributes": {
      "is_subscribed": true
    },
    "custom_attributes": [
      {
        "attribute_code": "string",
        "value": "string"
      }
    ]
  },
  "passwordHash": "string"
}
```

**Comment by magento-engcom-team** [comment] 2019-12-06 14:40
:white_check_mark: Confirmed by @engcom-Echo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29504` were created

**Issue Available**: @engcom-Echo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by rajabilal555** [comment] 2022-08-17 14:41
i guess Magento is not the "best" Ecom solution as people say... is it?

**Comment by engcom-Bravo** [comment] 2024-10-04 07:33
Hi @TomashKhamlai,

Thanks for your reporting and collaboration.

We have verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Hence we are closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-10-04 07:33 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Issue: Format is valid, Component: Webapi, Triage: Dev.Experience, Reproduced on 2.4.x, Severity: S4, Priority: P4, Progress: done
