### ISSUE TITLE
Unable to edit existing product

### ISSUE THREAD

**Issue by sangatpedas** [magento/magento2#3905] opened 2016-03-27 03:56 UTC
## Steps to reproduce
1. After a git pull today "1b5272c..9546277  develop    -> origin/develop
   Updating 1b5272c..9546277". Could be caused by earlier update as well but I just notice now.
2. Edit a product
3. Save the product
## Expected result
1. Successfully saved
## Actual result
1. Error message "Item (Magento\Framework\DataObject) with the same ID "5" already exists."
2. 
   <img width="711" alt="screen shot 2016-03-27 at 10 50 55 am" src="https://cloud.githubusercontent.com/assets/5317971/14063773/7235c516-f40a-11e5-90ae-7a3b0e0b0a69.png">

**Comment by sangatpedas** [comment] 2016-03-27 04:57
When adding new products some strange things happen as well, such as images from other products being added automatically to the new product.

Also, I tried deleting all products and adding a new product to see if I can edit that product but the result is the same, unable to save the product with the same error message as mentioned above.

**Comment by sangatpedas** [comment] 2016-03-29 02:58
Why is this labeled "MX"? Sure it's a backend problem but shouldn't this be a high priority bug to fix? Not being able to edit products seems quite essential to me.

**Comment by josepaitamala** [comment] 2016-03-31 09:20
Hi, I am having the same problem, I have updated Magento to the latest version 2.0.3 , running sudo composer update, Magento 2 has been updated but the problem is still there

**Comment by kayintveen** [comment] 2016-04-01 12:49
I have the exact same issue, when editing existing items. Adding a new product was without any problem.

For me it seems that its related to product images. I saw that ID 24 i got was the first image. after removing images and adding new one's i got:

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento2dev`.`catalog_product_entity_media_gallery_value`, CONSTRAINT `CAT_PRD_ENTT_MDA_GLR_VAL_VAL_ID_CAT_PRD_ENTT_MDA_GLR_VAL_ID` FOREIGN KEY (`value_id`) REFERENCES `catalog_product_entity), query was: INSERT INTO`catalog_product_entity_media_gallery_value`(`value_id`,`store_id`,`entity_id`,`label`,`position`,`disabled`) VALUES (?, ?, ?, ?, ?, ?)

**Comment by sangatpedas** [comment] 2016-04-04 04:13
Hi,

For me the issue is solved, after today's git pull all seems to work as supposed to.

Thank!

**Comment by kayintveen** [comment] 2016-04-05 11:47
For me not. @sangatpeda any clue which file change helped you out here?
Where you already on 2.0.4?

I opend my own issue to get it solved now. https://github.com/magento/magento2/issues/4012

**Comment by sangatpedas** [comment] 2016-04-05 11:53
Looks like in the git pull as seen in the screenshot below the change of the file ".../Catalog/Controller/Adminhtml/Product/Save.php" did the trick.

<img width="543" alt="screen shot 2016-04-05 at 6 49 24 pm" src="https://cloud.githubusercontent.com/assets/5317971/14280800/4142dee2-fb5f-11e5-9cb4-a2daf28f94c8.png">

**Comment by sangatpedas** [comment] 2016-04-05 11:54
But, just to be clear, I use the develop version.

**Comment by kayintveen** [comment] 2016-04-05 12:37
Seems like it indeed. 
great... let me check.

**Comment by witold-prucnel** [comment] 2016-04-06 11:37
Confirm, I have the same issue, fresh installation.

**Comment by kayintveen** [comment] 2016-04-06 11:42
@sangatpedas I just did the same as you, pulled the recent from develop. And no solution for me. Categories, products all have a issue
Categories its the url key that already exists. 
and products has issues with the media gallery

**Comment by kayintveen** [comment] 2016-04-07 08:50
@sangatpedas Could you open this issue up again? Issue still not solved. and its a big one

**Comment by sangatpedas** [comment] 2016-04-07 08:53
Re-opened on request of @kayintveen

**Comment by kayintveen** [comment] 2016-04-07 09:00
Many many thanks

**Comment by mikeoloughlin** [comment] 2016-04-27 15:27
Same issue here. `2.0.4` and after an product update import with images. Any more info on this?

**Comment by kayintveen** [comment] 2016-04-27 17:34
Is there a way to bring this more under attention. Im stuck on this thing really badly now and i need to move forward but no clue where to start

**Comment by kandy** [comment] 2016-05-12 07:23
We finally can reproduce issue so, We have created ticket MAGETWO-52716 to fix this.

**Comment by kayintveen** [comment] 2016-05-12 07:48
Perfect, thanks for the update. Any idea how long that would take?

**Comment by piotrekkaminski** [comment] 2016-06-10 00:28
It is fixed in develop branch.

**Closed as completed by piotrekkaminski** 2016-06-10 00:28 UTC

**Comment by kayintveen** [comment] 2016-06-15 12:00
@piotrekkaminski Which commit?

**Comment by kandy** [comment] 2016-06-15 12:06
Looks like in was c5cc0b5

**Comment by kayintveen** [comment] 2016-06-15 12:23
@kandy thats MAGETWO-50893 right not MAGETWO-52716

**Comment by kandy** [comment] 2016-06-15 12:25
MAGETWO-52716 was closed with has a fix in MAGETWO-50893

**Comment by kayintveen** [comment] 2016-06-15 12:26
ahh perfect. going to pull that in and review if thats the solution indeed.  thanks for your quick response!

**Comment by adnan-jamil** [comment] 2016-09-02 06:32
please comment the link of this MAGETWO-50893, i could not find this.
