### ISSUE TITLE
Free shipping method issue

### ISSUE THREAD

**Issue by badsayer** [magento/magento2#8948] opened 2017-03-20 19:35 UTC
I found a bug with the free shipping method. The free shipping method not disappear when you remove products from your shopping cart, and the order amount is below the free shipping amount.

### Preconditions
Magento version: 2.1.2

### Steps to reproduce
1. When you put one product in the cart, in my case below € 20, no free shipping.
2. When adding a second product, and the cart amount above € 20, you get free shipping.
3. When you delete 1 product from the cart, and the total order amount below € 20, the free shipping method not disappear.

**Comment by zaximus84** [comment] 2017-04-03 21:27
This seems like a duplicate of [8614](https://github.com/magento/magento2/issues/8614).

**Comment by magento-engcom-team** [comment] 2017-10-18 14:00
@badsayer, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-10-18 14:00 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is not valid
