### ISSUE TITLE
Payment configurations not saved in the magento database

### ISSUE THREAD

**Issue by seebakannan** [magento/magento2#36075] opened 2022-09-02 11:32 UTC

**Comment by seebakannan** [comment] 2022-09-02 12:07
Hi,

I have provided the necessary information for reproducing the issue.

**Comment by rogerdz** [comment] 2022-09-02 15:21
@seebakannan You can try to fix max_input_vars = 60000 in php.ini and try again

**Comment by engcom-November** [comment] 2023-01-09 12:00
Hi @seebakannan ,

Thank you for reporting and collaboration. Most of the payment integrations / extensions and bundled extensions are moved to Magento [Market place](https://marketplace.magento.com/extensions/payments-security.html) page and code of those extensions is not part of https://github.com/magento/magento2 git repository. As the issue is not reproducible with default available payment methods, community is not able to provide fix for it in this repository. We are closing this issue. All questions, issue reports and fix for them should be addressed to the corresponding extension owners(support) on the [Magento Market place](https://marketplace.magento.com/extensions.html) page.
Thank you.

**Closed as completed by engcom-November** 2023-01-09 12:00 UTC
Labels: Component: Bundled Extension, Triage: Dev.Experience, Issue: ready for confirmation, Reported on 2.4.5

**Comment by seebakannan** [comment] 2023-03-07 06:58
Hi @rogerdz 

Thank You for the 

> @seebakannan You can try to fix max_input_vars = 60000 in php.ini and try again

Hi, @rogerdz Thanks for the solution. The issue has been resolved.
