### ISSUE TITLE
Magento2 doesn’t remember the currency or store view state when changing page in safari (but does in firefox)

### ISSUE THREAD

**Issue by JackNorm** [magento/magento2#13017] opened 2018-01-06 16:55 UTC
In a store with 2 or more currencies I can’t get Magento to remember the currency switch state using Safari browser. Everything works like a charm in for example Firefox. 

But when using Safari and I switch currency from one to another and then navigate back, the currency is changing to the previous instead of changing to the previous page.
Please help me out.
Thanks.

### Preconditions
1. Magento 2.2.2 
2. PHP 7.0
3. Varnish
4. 1 Website, 1 Store, 1 Store view, 2 currencies USD and EUR for example 

### Steps to reproduce
1. Install Magento2, Luma theme
3. Setup 2 currencies 
4. Switch from one Currency to another
5. Change page  (navigate back using safari browser)

### Expected result
1. Magento should remember the chosen currency and change to the previous page 

### Actual result
1. Magento switches to the previous currency, and not the previous page

Everything works perfect in Firefox but not i Safari on Mac or Iphone.

**Comment by JackNorm** [comment] 2018-01-07 14:45
Ok, after some more research the issue seams to be related to Safari back/forward cache.  So it also concerns for example:
1  add product
2 check mini cart 
3 click go to cart from mini cart
4 at cart page, click back in safari browser

**Expected result**
magento goes back to previous page

**Actual result**
magento goes back to previous page AND the mini cart is still expanded.

By adding following to head, will forcea reload when page is loaded from back forward cache

window.onpageshow = function(event) {
    if (event.persisted) {
        window.location.reload() 
    }
};

from:
 https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked

"It is supposed to save complete state of page when user navigates away. When user navigates back with back button page can be loaded from cache very quickly. This is different from normal cache which only caches HTML code.

When page is loaded for bfcache onload event wont be triggered. Instead you can check the persisted property of the onpageshow event. It is set to false on initial page load. When page is loaded from bfcache it is set to true."

However...

**Comment by magento-engcom-team** [comment] 2018-01-09 12:34
@JackNorm, thank you for your report.
We've created internal ticket(s) MAGETWO-86491 to track progress on the issue.

**Comment by engcom-Alfa** [comment] 2019-08-02 13:04
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-02 13:05
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-02 13:05
Hi @engcom-Alfa, here is your [Magento instance](https://i-13017-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13017-2-3-develop.instances.magento-community.engineering/admin](https://i-13017-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment] 2019-08-06 06:23
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-08-06 06:23
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-08-06 06:24
Hi @engcom-Alfa, here is your [Magento instance](https://i-13017-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-13017-2-3-develop.instances.magento-community.engineering/admin](https://i-13017-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment] 2019-08-06 06:45
Hello @JackNorm 

Thank you for contribution and collaboration!

We are not able to reproduce this issue on the lates `2.3-develop` branch by provided steps.

We are closing this issue due to _branch `2.2-develop` was closed and Magento no longer accepts pull requests and issues to the v2.2 release lines to focus all development efforts on v2.3._
 See [Accepted pull requests and ported code](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#rules) for more details

If you still faced this issue on `2.3` please create a new Issue with all required details according to [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Alfa** 2019-08-06 06:45 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by Green2Matter** [comment] 2023-09-04 08:45
Same happens in 2.4.6-p2…
