### ISSUE TITLE
[Fixed] missing "," in "New Order" Email template Magento_Sales 

### ISSUE THREAD

**Issue by trongkhoa1103** [magento/magento2#6782] opened 2016-09-28 04:14 UTC
### Preconditions

1. Magento version 2.1
2. 
### Steps to reproduce

1. Load New Order Email Template from Admin
2. Get Error Message
3. 
### Expected result

1. 
### Actual result

1. [Screenshot, logs]

[2016-09-28 03:56:20] main.CRITICAL: Zend_Json_Exception: Decoding failed: Syntax error in /vendor/magento/zendframework1/library/Zend/Json.php:97
Stack trace:
#0 /vendor/magento/module-email/Model/Template.php(306): Zend_Json::decode('{"var formatted...')

Fixed:
"var formattedShippingAddress|raw":"Shipping Address",
"var order.getShippingDescription()":"Shipping Description",   
"var shipping_msg":"Shipping message"

**Comment by mrkhoa99** [comment] 2016-09-28 04:45
@lytrongkhoa  your issue was fixed on current branch: https://github.com/magento/magento2/blob/develop/app/code/Magento/Sales/view/frontend/email/order_new.html

**Comment by veloraven** [comment] 2016-10-10 09:30
I'm closing this issue as duplicate of #5116.
Internal ticker for ver. 2.1 - MAGETWO-57026.

**Closed as completed by veloraven** 2016-10-10 09:30 UTC
