### ISSUE TITLE
Unable to get/see Product Length, Width and Height Attributes V 2.3.3

### ISSUE THREAD

**Issue by dev-Z-Apx** [magento/magento2#25092] opened 2019-10-16 11:41 UTC
### Preconditions (*)

1. Create some products with Length, Width and Height Attributes on Version 2.3.2
2. Upgrade the store to Latest Version 2.3.3

### Steps to reproduce (*)

1. AdminDasboard->Catalog->Products->Edit Product 
2. Get the Length attribute of product as `$_product->getData('ts_dimensions_length')`

### Expected result (*)

1. [Screenshots, logs or description]
![image](https://user-images.githubusercontent.com/56595197/66915790-4e598a00-f033-11e9-9f35-cb6c197cec5a.png)

2. It should return the Length Attribute of the Product

### Actual result (*)

1. It shows no attributes on Front End.
2. Does not return any value using this code.
3. Which merely means all of Product data has been lost as when I tried to get all attributes of a product Programatically even then I am unable to see any 'ts_dimensions_length' there but I can see this if I am on Version 2.3.2

**Comment by dev-Z-Apx** [comment] 2019-10-16 11:41
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-16 11:42
Hi @dev-Z-Apx. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-16 11:42
Hi @dev-Z-Apx, here is your [Magento instance](https://i-25092-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25092-2-3-develop.instances.magento-community.engineering/admin](https://i-25092-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by dev-Z-Apx** [comment] 2019-10-16 11:48
> Hi @dev-Z-Apx, here is your [Magento instance](https://i-25092-2-3-develop.instances.magento-community.engineering).
> Admin access: https://i-25092-2-3-develop.instances.magento-community.engineering/admin
> Login: `admin` Password: `123123q`
> Instance will be terminated in up to 3 hours.

I have checked the UI issue is still there for the new product also as it is a Fresh Instance therefore there are no old products that might have been added in the last version 2.3.2 But I can't execute the Programming task here so it needs to be checked by the Devs.

**Comment by dev-Z-Apx** [comment] 2019-10-21 07:24
did anyone check this issue ?
I see no comments or progress on this issue

@magento-engcom-team

**Comment by magento-engcom-team** [comment] 2019-11-14 14:30
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-23151` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by dev-Z-Apx** [comment] 2020-03-02 12:20
issue is ready for work for more than 3 months.....
Magento has released a new release 2.3.4 and still the issue is not fixed.....
@magento-engcom-team

**Comment by lazyguru** [comment] 2020-06-29 19:32
Since I did a bunch of research on this trying to track down the cause for other reasons, here's what I've found (along with sources where applicable):

- The `ts_dimension_*` attributes were provided by the Temando_Shipping module (which makes sense now `ts_`) [Reference](https://magento.stackexchange.com/questions/231697/product-dimensions-in-magento-2-2-5-update)
- Magento Shipping from Temando is no more [Reference](https://magento.com/shipping)
- Magento removed the Temando_Shipping module from 2.3.? (I think it was 2.3.3, but see Workaround 2 below)
- Magento further provided temando/module-shipping-remover (which **explicitly** deleted those attributes) in 2.3.? (I think it was 2.3.3, but see Workaround 2 below)

**Workaround 1**
You could add these attributes back in using [this](https://github.com/arendarenko/temando-module-shipping-m2/blob/master/Setup/SetupData.php#L153-L196) as a guide (either create your own module that does this programmatically, or just manually create these attributes using the info here to guide what settings to choose in the admin) 

**Workaround 2**
I've tested fresh installs of 2.3.3 and 2.3.4 and both no longer include the module-shipping-remover module but DO include Temando_Shipping. I suspect that Magento has repackaged those versions to put things back. So you _should_ be able to do `composer clear-cache && composer update` to have it put things back for you (YMMV, I haven't tested this. Do it on a dev environment first). 

**Final note**
As this is all linked to a module that is no longer included in core and Magento is not likely to add it back in (for obvious reasons), I doubt this issue gets a full resolution. It seems that anyone that was using those attributes was depending on something they shouldn't have been (unless they were using Magento Shipping). It's a little sad that some kind of migration wasn't created to "move" this data if it existed instead of just blindly purging it, but I suspect that the expectation was merchants were not using those fields _unless_ they were using Magento Shipping and any that were would have migrated their own data. While the workarounds above might solve your problem temporarily, 2.3.5 still removes things (and likely 2.3.6 will too), so you shouldn't depend on this and would be better off moving to other attributes for storing this data.

**Comment by sdzhepa** [comment] 2020-10-06 18:40
Magento stops supporting of Temando module. Please see more details https://magento.com/shipping
Long story short: 
- The extension owner does not work and support this module anymore.
- Magento will support "_existing customers until November 15, 2020_" only through the support channel associated with your Magento account. 
- In the internal Magento backlog there is a ticket to completely remove Temando from Magento.

**Closed as completed by sdzhepa** 2020-10-06 18:40 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Bundled Extension, Progress: done
