### ISSUE TITLE
[NOT READY] Coupon with Apply to Shipping Amount not working correctly in GraphQl

### ISSUE THREAD

**Issue by OleksiyOleksiyovych** [magento/magento2#31270] opened 2020-12-12 22:42 UTC
### Preconditions
Magento version: 2.4
php version : 7.3

### Steps to reproduce 
1. Go to Magento admin panel
2. Create a cart price rule (type coupon)
3. Set "Apply to Shipping Amount" to "Yes" in tab "Actions"
4. in GraphQl: 
 - create cart  (createEmptyCart)
 - add product (addSimpleProductsToCart)
 - set shipping address (setShippingAddressesOnCart) 
 - select shipping method (setShippingMethodsOnCart)
 - apply created coupon (applyCouponToCart)

### Expected result
I can get cart totals with the correct discount (discount for product and for shipping)
![Shopping-Cart](https://user-images.githubusercontent.com/3465267/101996277-9f1d4f00-3cd9-11eb-89fd-d07ebc0df449.png)

### Actual result 
I can not get a discount for shipping in GraphQl
CartPrices has `discount: CartDiscount` and it gets the correct discount value.
But it deprecated and we should use `discounts: [Discount]` where we do not have a discount for the shipping amount.
![graphql](https://user-images.githubusercontent.com/3465267/101996452-2919e780-3cdb-11eb-9d0d-8b22595fa2a0.png)

**Comment by OleksiyOleksiyovych** [comment] 2020-12-29 21:37
@magento give me 2.4-develop instance

**Comment by alitopaloglu** [comment] 2021-03-22 10:06
I can reproduce this issue on v2.4.2

Discount part of the graphQL response contains only discount about items, not handling shipping discount and there is no data about shipping discount in response.

**Comment by enikov** [comment] 2021-07-02 08:44
Reproduced on v2.4.2

Any update?

**Comment by alitopaloglu** [comment] 2021-08-09 11:08
I can reproduce this issue on v2.4.2

Discount part of the graphQL response contains only discount about items, not handling shipping discount and there is no data about shipping discount in response.

**Comment by engcom-Hotel** [comment] 2021-11-15 09:45
Hello @OleksiyOleksiyovych,

Thanks for posting this issue!

We request you to please try to reproduce this issue in Magento 2.4-develop branch and let us know in case you are able to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-11-29 01:35
Dear @OleksiyOleksiyovych,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-11-29 01:35 UTC
Labels: Project: GraphQL, Issue: needs update

**Comment by Ahmet-Djedovic** [comment] 2022-03-25 07:57
@magento give me 2.4-develop instance

**Comment by Abhay-Agrawal** [comment] 2022-05-27 13:04
It is same as https://github.com/magento/magento2/issues/31270

**Comment by alitopaloglu** [comment] 2022-06-01 09:04
I can reproduce this issue on v2.4.3-p2 but not sure if it's fixed on v2.4.4 or not.

**Comment by cpartica** [comment] 2022-06-02 20:43
> I can reproduce this issue on v2.4.3-p2 but not sure if it's fixed on v2.4.4 or not.

I see. It's important to reproduce all in the latest version, because we can't fix an older version because it's already released.
I see you opened https://github.com/magento/magento2/issues/35545 which give a nice explanation for what's going on
