### ISSUE TITLE
images for sample data not available on m 2.4.6

### ISSUE THREAD

**Issue by elizad** [magento/magento2#37446] opened 2023-04-29 20:56 UTC
### Preconditions and environment

- Magento version: 2.4.6
- Anything else that would help a developer reproduce the bug

- 
![image](https://user-images.githubusercontent.com/2777425/235323868-f3ffb969-9102-4f33-9744-0697d0c0684a.png)

### Steps to reproduce

- 1 install magento 
- 2 run bin/magento deploy:mode:set developer  and bin/magento sampledata:deploy 
- ==> no images for products showing 

### Expected result

see images 

### Actual result

no images 

### Additional information

Can you pls provide a working import cvs  with images ? thx 

Product import export is a pain !!!!

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by elizad** [comment] 2023-05-02 19:23
hi , i think is a bug on magento2-sample-data-2.4-develop\app\code\Magento\ConfigurableSampleData  . there on a fresh magento install , the code is stopping

**Comment by engcom-Bravo** [comment] 2023-05-08 09:48
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-08 13:25
Hi @elizad,

Thanks for your update.

Verified the issue on Magento 2.4.-develop instance and Magento 2.4.6 instance and the issue is not reproducible.Kindly refer the screenshots.


Sample data installed successfully with images.


<img width="1438" alt="Screenshot 2023-05-08 at 4 16 35 PM" src="https://user-images.githubusercontent.com/51680745/236815302-a76814f3-8e37-46ea-ae48-e88c501c5394.png">



Please try to install on fresh install of Magento instance.Kindly refer this doc https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/next-steps/sample-data/composer-packages.html for installing sample data.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-05-23 06:15
Hi @elizad,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-05-23 06:15 UTC
Labels: Issue: needs update, Reported on 2.4.6

**Comment by vvuksan-fastly** [comment] 2023-07-21 20:24
Hey folks this is definitely an issue. If I leave off the version e.g.

`composer create-project --no-interaction --repository-url=https://repo.magento.com/ magento/project-community-edition /var/www/magento`

None of the images get put in pub/media. If I use the exact same install script but specify the version e.g.

`composer create-project --no-interaction --repository-url=https://repo.magento.com/ magento/project-community-edition="2.4.5" /var/www/magento`

I get images

**Comment by Rayn93** [comment] 2024-06-11 10:48
I had the same issue with magento 2.4.7.
You could fix it by regenerate images:
`bin/magento catalog:image:resize`

**Comment by JonathanHelvey** [comment] 2024-08-25 21:01
This is happening on a fresh install of Magento2.4.4p-8 for me today as well. @zakdma is correct on `php bin/magento sampledata:deploy` it will add media path as media/catalog/catalog/product you have to move images to media/catalog/product. however, it does not map all images to the correct configurable products. After image resize simple products will display images, however, configurables will not display on either admin or frontend. Have to either import CSV file to add missing images or have to go through each products config and add the images from pub media manually. 

I opend a new issue here [https://github.com/magento/magento2/issues/39108](https://github.com/magento/magento2/issues/39108). It is a bug on  `php bin/magento sampledata:deploy`
