### ISSUE TITLE
Magento layered navigation filter showing not showing proper result for out of stock variant

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#35197] opened 2022-03-15 16:25 UTC
**Preconditions (*)**
Magento 2.4.1

**Steps to reproduce (*)**
1: Create Attribute say size - M , L ,X and use it in layered navigation
2: Create configurable product with stock of M and X
3: From Admin set : do not disable out of stock products
4: Apply filter of L on listing pages it will show configurable product with no stock of L

**Expected result (*)**
1: If product do not have stock of applied filter it should not show

**Actual result (*)**
it is showing configurable product which has selected filter out of stock

**Comment by ia-gaurav** [comment] 2022-03-15 16:26
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2022-03-17 05:53
@magento give me 2.4-develop instance

**Comment by ajijshekh123** [comment] 2022-03-24 08:21
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-03-24 13:51
Verified the issue on Magento 2.4-develop branch but cannot able to reproduce the issue.
Steps performed:
Admin - Stores - Configuration - Catalog - Catalog - Enabled Layered Navigation
Admin - Stores - Configuration - Catalog - Inventory - Display Out of Stock Products - Set to Yes and save
enable product attribute - Size - With options : S, M, L and use in layered navigation
Created Configurable product with stock: S and M
Front-end - select category - Filter - Size and select option 'L'
All products are displayed but only products containing L size option are highlighted 
![image](https://user-images.githubusercontent.com/60198231/159930056-eaee41b5-6e8c-43a4-9890-263df1a00268.png)
Set the Configurable product to out of stock from admin and save
Front-end apply filter - L
No issue: Out of stock product having size options - M and S is not displayed in front-end with filter L

**Comment by engcom-November** [comment] 2022-04-06 07:54
Hi @ia-gaurav ,
We are closing this issue as there has been no latest update on the same.
Thank you.

**Closed as completed by engcom-November** 2022-04-06 07:54 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
