### ISSUE TITLE
Wrong tax calculation after applying discount coupon in Magento Open Source v2.3.4 

### ISSUE THREAD

**Issue by aboutzahurul** [magento/magento2#29506] opened 2020-08-12 18:40 UTC
### Preconditions (*)
1. Fresh Magento 2.3.4, 2.4-develop (Open Source) with sample data

### Steps to reproduce (*)
1. Stores->Configuration-> Sales->Tax : Set all values including tax and Apply Customer Tax After Discount (http://prnt.sc/tyizqn)
2. Stores->Tax Zones and Rates: Set VAT of 15% (http://prnt.sc/tyizuc)
3. Stores->Tax Rules: Set VAT of 15% (http://prnt.sc/tyizwl)
4. Marketing-> Cart Price Rule: Set 10% off on "Percent of product price discount" (http://prnt.sc/tyizzo)

### Expected result (*)
If any taxable item's (https://prnt.sc/tyjm6f) selling price 100 and tax 15% (13.04) included, then:
1. Base price without tax should be (100 - 13.04) = 86.96
2. As 10% Discount from that Base price should be (86.96 * 10%) = 8.70
3. After Discount Base price should be (86.96 - 8.70) = 78.26
4. 15% Tax on New discounted base price (78.26 * 15%) = 11.74
5. So Total price after discount with tax (78.26 + 11.74) = 90

### Actual result (*)
But on Magento after discount, it calculates wrong Tax and total
1. it shows Base price without tax 86.96 which is ok
2. it shows As 10% Discount from that Base price 8.70 which is also ok
3. but the **Tax it shows 11.91 which is wrong**
4. and it shows **total price after discount with tax 91.30 which is also wrong**
http://prnt.sc/tyj01h
**Can anybody explain why it's working this way and what is the logic behind it?**

### Temporary solution
If we follow this fix  https://github.com/magento/magento2/issues/21456#issuecomment-467475342 

Fix on file `vendor/magento/module-tax/Model/Calculation/AbstractAggregateCalculator.php:49`

Replace:
```
//TODO: handle originalDiscountAmount
$taxableAmount = max($rowTotalInclTax - $discountAmount, 0);
$rowTaxAfterDiscount = $this->calculationTool->calcTaxAmount(
    $taxableAmount,
    $rate,
    true,
    false
);
$rowTaxAfterDiscount = $this->roundAmount(
    $rowTaxAfterDiscount,
    $rate,
    true,
    self::KEY_REGULAR_DELTA_ROUNDING,
    $round,
    $item
);
// Set discount tax compensation
$discountTaxCompensationAmount = $rowTax - $rowTaxAfterDiscount;
$rowTax = $rowTaxAfterDiscount;
```

With the following:
```
$taxableAmount = max($rowTotal - $discountAmount, 0);
$discountTaxCompensationAmount = 0;
$rowTax = $taxableAmount * ($rate / 100);
```

In our case, it works as expected (http://prnt.sc/tyj04g). Thanks to @pierzakp
**Is it reliable or safe enough to apply on the production site? Is there any alternative way or settings to fix that tax issue?**

>_Note: After applying this fix it wasn't working as expected, then find out its need clear cache properly both for Magento + Browser + 3rd party (if any)._

**Comment by magento-engcom-team** [comment] 2020-09-15 12:26
:white_check_mark: Confirmed by @engcom-Oscar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-37664` were created

**Issue Available**: @engcom-Oscar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by Kishorchhugani** [comment] 2020-10-09 13:35
@magento I am working on it

**Comment by Kishorchhugani** [comment] 2020-10-09 13:35
@magento add to contributors team

**Comment by Sartoric** [comment] 2020-10-09 15:49
I'm facing the same issue (2.3.5-p1)

It seems that it happens just after the coupon is applied, in fact reloading the checkout page seems to "fix" the issue

**Comment by Kishorchhugani** [comment] 2020-10-10 05:08
@magento I am working on it

**Comment by VivekM296** [comment] 2020-11-02 06:17
@Kishorchhugani Any update on this ?

**Comment by jjburbridge** [comment] 2020-11-03 13:26
@magento give me 2.3.5 instance

**Comment by engcom-Golf** [comment] 2021-01-12 14:52
This is not a bug. To get the result as expected you should enable configuration Sales->Tax->Calculation Settings->Apply Discount On Prices = Including  Tax. I'll try to explain why:
Tax value is calculated by the following formula
`{Taxable amount} * (1 - 1 / (1 + {Tax rate})`
Tax rate in your case is 0.15
Taxable amount - is a variable value that depends on configuration

Case Apply Discount On Prices **Including tax**
```
Total including tax = 100
Total excluding tax = 86.96
Discount = 10
Taxable amount(Total including tax - Discount) = 90
Result = 11.74
```

Case Apply Discount On Prices **Excluding tax**
```
Total including tax = 100 
Total excluding tax = 86.96
Discount = 8.70
Taxable amount(Total including tax - Discount) = 91.3
Result 11.91
```
Total including tax = {product price including tax} * {quantity}

I'll close this ticket for now. Feel free to reopen if you have any concerns.

**Closed as completed by engcom-Golf** 2021-01-12 14:52 UTC
Labels: Issue: Ready for Work, Component: Tax, Issue: Confirmed, Issue: Format is valid, Component: SalesRule, Reproduced on 2.4.x, Fixed in 2.4.x, Priority: P2, Severity: S2, Progress: done, CD, Reported on 2.3.4

**Comment by magento-engcom-team** [comment] 2021-01-12 14:54
Hi @aboutzahurul, @engcom-Golf. 

Thank you for your report and collaboration!

The related internal Jira ticket `MC-37664` was closed as `Fixed`. 

The fix will be available with the upcoming `2.4.3` release.

**Comment by Sartoric** [comment] 2021-01-12 16:07
@engcom-Golf 
I suppose you're referring to the main topic.
So my "sub-case" could be related to something, different, isn't it ? Maybe something wrong in the Carriers collectRates method

Ty

**Comment by engcom-Golf** [comment] 2021-01-13 11:35
Hi @Sartoric, I couldn't investigate your case as there are no accurate steps on how to reproduce the issue and what is the expected result. Please add more information about the tax configuration you are using and all the needed information to help us process the problem.
Thanks

**Comment by AjayKrP** [comment] 2021-04-26 10:40
Do we have any patch for this?

**Comment by patelnimesh1988** [comment] 2022-03-02 10:43
Please check this:
https://magento.stackexchange.com/questions/127471/discount-tax-compensation-amount-attribute-in-sales-order-item-magento-2
