### ISSUE TITLE
Database Media Storage - New Product Images fail when image is hidden from gallery

### ISSUE THREAD

**Issue by gwharton** [magento/magento2#21547] opened 2019-03-01 16:22 UTC
### Preconditions (*)
1. 2.2-develop

### Steps to reproduce (*)
1. Vanilla Install 2.2-develop
2. Change database media storage configuration to database and Synchronise
3. Save settings
4. Create new product, add new image to product, set the image to be hidden from gallery (in my test case tractor.200x100.jpg)
5. Save Image

Expected Result is what happens when you don't hide the image. Actual Result is what happens when you do hide the image.

### Expected result (*)

```
www-data@dev:~/dev1$ mysql dev1_magento -e "select filename,directory FROM media_storage_file_storage"
+----------------------------------+------------------------------------------------------------+
| filename                         | directory                                                  |
+----------------------------------+------------------------------------------------------------+
| preview_image_5c795024ca7af.jpeg | theme/preview                                              |
| preview_image_5c795024dc145.jpeg | theme/preview                                              |
| tractor.200x100.jpg              | catalog/product/t/r                                        |
| tractor.200x100.jpg              | catalog/product/cache/0b518a73ed92eecbe9790ec3a622cd2d/t/r |
| tractor.200x100.jpg              | catalog/product/cache/79cd194851544f88bafc552bf5216e5d/t/r |
| tractor.200x100.jpg              | catalog/product/cache/12479842094003d6e8198e99b15d1aad/t/r |
| tractor.200x100.jpg              | catalog/product/cache/aefcd4d8d5c59ba860378cf3cd2e94da/t/r |
| tractor.200x100.jpg              | catalog/product/cache/93545884bf1d6d40eefc44b2e3958bec/t/r |
| tractor.200x100.jpg              | catalog/product/cache/3e75d17be04cbebee9a78c36b24b6eea/t/r |
| tractor.200x100.jpg              | catalog/product/cache/07aa3e3829adcf2640e41cdeee09b5bb/t/r |
| tractor.200x100.jpg              | catalog/product/cache/19796d7732cc0b8676f199bbe04c742a/t/r |
| tractor.200x100.jpg              | catalog/product/cache/08a0b36ebc62d1aabd4a717a82ad731c/t/r |
| tractor.200x100.jpg              | catalog/product/cache/da51c19fe8c21b068c481cfb28c65074/t/r |
| tractor.200x100.jpg              | catalog/product/cache/c430e3e26517992a27628ce5995d6769/t/r |
| tractor.200x100.jpg              | catalog/product/cache/6b1c09900b407c50fce2db5e66ebc123/t/r |
| tractor.200x100.jpg              | catalog/product/cache/10f519365b01716ddb90abc57de5a837/t/r |
| tractor.200x100.jpg              | catalog/product/cache/ecd051e9670bd57df35c8f0b122d8aea/t/r |
| tractor.200x100.jpg              | catalog/product/cache/f9bb4946b08eb56afc1e83d5b55bf276/t/r |
| tractor.200x100.jpg              | catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/t/r |
| tractor.200x100.jpg              | catalog/product/cache/f0eed8c49b05a5a279de03029e69388c/t/r |
| tractor.200x100.jpg              | catalog/product/cache/66336d755d72c30139c8c62793bff496/t/r |
| tractor.200x100.jpg              | catalog/product/cache/a8be410535bd10951f8c121e888302ad/t/r |
| tractor.200x100.jpg              | catalog/product/cache/35d197d4a86bb7af9ea497ddcb0426c9/t/r |
| tractor.200x100.jpg              | catalog/product/cache/d664e1acc15f6090304d588386caff1d/t/r |
| tractor.200x100.jpg              | catalog/product/cache/411ddd1079653e9744172963f7b57a7a/t/r |
| tractor.200x100.jpg              | catalog/product/cache/647c742965ace57b5484ad847e8cd3cc/t/r |
| tractor.200x100.jpg              | catalog/product/cache/add01ceb5699006aaeaaa55353b05d62/t/r |
| tractor.200x100.jpg              | catalog/product/cache/e97e30f46ad3af2c4402aa864120074b/t/r |
| tractor.200x100.jpg              | catalog/product/cache/36fa622c226395c7a03aea76cb6f177a/t/r |
+----------------------------------+------------------------------------------------------------+
www-data@dev:~/dev1$ find pub/media -name *.jpg
pub/media/catalog/product/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/36fa622c226395c7a03aea76cb6f177a/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/12479842094003d6e8198e99b15d1aad/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/e4d64343b1bc593f1c5348fe05efa4a6/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/c430e3e26517992a27628ce5995d6769/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/411ddd1079653e9744172963f7b57a7a/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/a8be410535bd10951f8c121e888302ad/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/647c742965ace57b5484ad847e8cd3cc/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/e97e30f46ad3af2c4402aa864120074b/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/0b518a73ed92eecbe9790ec3a622cd2d/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/aefcd4d8d5c59ba860378cf3cd2e94da/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/d664e1acc15f6090304d588386caff1d/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/add01ceb5699006aaeaaa55353b05d62/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/f0eed8c49b05a5a279de03029e69388c/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/ecd051e9670bd57df35c8f0b122d8aea/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/10f519365b01716ddb90abc57de5a837/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/35d197d4a86bb7af9ea497ddcb0426c9/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/79cd194851544f88bafc552bf5216e5d/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/f9bb4946b08eb56afc1e83d5b55bf276/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/93545884bf1d6d40eefc44b2e3958bec/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/66336d755d72c30139c8c62793bff496/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/3e75d17be04cbebee9a78c36b24b6eea/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/08a0b36ebc62d1aabd4a717a82ad731c/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/19796d7732cc0b8676f199bbe04c742a/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/07aa3e3829adcf2640e41cdeee09b5bb/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/da51c19fe8c21b068c481cfb28c65074/t/r/tractor.200x100.jpg
pub/media/catalog/product/cache/6b1c09900b407c50fce2db5e66ebc123/t/r/tractor.200x100.jpg

```
### Actual result (*)

```
www-data@dev:~/dev1$ mysql dev1_magento -e "select filename,directory FROM media_storage_file_storage"
+----------------------------------+---------------------+
| filename                         | directory           |
+----------------------------------+---------------------+
| preview_image_5c795024ca7af.jpeg | theme/preview       |
| preview_image_5c795024dc145.jpeg | theme/preview       |
| tractor.200x100.jpg              | catalog/product/t/r |
+----------------------------------+---------------------+
www-data@dev:~/dev1$ find pub/media -name *.jpg
```

**Comment by magento-engcom-team** [comment] 2019-03-01 16:22
Hi @gwharton. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@gwharton do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [x] yes
- [ ] no

**Comment by gwharton** [comment] 2019-03-01 16:23
Unable to test using magento-engcom instances due to database and command line access required. Confirm able to reproduce on 2.2-develop. I suspect also present on 2.3-develop, but unable to test due to bug #21546

**Comment by gwharton** [comment] 2019-03-01 16:28
The 

`product->save() `

call that is called when the product is saved calls 

`Magento\Catalog\Model\Product\Image\Cache->generate()`

to pre-generate all cached images for the product. This function generates cached images for all images returned by 

`$product->getMediaGalleryImages()`

which happens to excludes hidden images (by design).

A secondary function also carried out while generating cached images (when in database media storage mode) is to make a copy of the image from the database and store on the filesystem. Thus when adding images to a product which are set to hidden causes the images to skip cache generation, and skip copying to filesystem, which causes the admin gui to display placeholder image as it thinks the image is missing (which it is!)

Seems that the cache generation function should retrieve a collection of ALL images to process, not just "visible" ones.

**Comment by magento-engcom-team** [comment] 2019-03-04 07:17
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-03-05 07:49
:white_check_mark: Confirmed by @engcom-backlog-nazar 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98560` were created

**Issue Available**: @engcom-backlog-nazar, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Closed as completed** 2019-07-06 13:21 UTC
Labels: Issue: Ready for Work, Component: Catalog, Component: Config, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Issue: Format is valid
