### ISSUE TITLE
Discount is incorrect (Magento 245 CE)

### ISSUE THREAD

**Issue by nhatlich994** [magento/magento2#36315] opened 2022-10-17 11:50 UTC
### Preconditions and environment

Magento 245 CE

### Steps to reproduce

1. Create two products A and B
2. Set Discount product A is percent 5% for each.
3. Go front end and add both A and B to cart
4. View Summary in Shopping Cart

### Expected result

Order Total cost is correct

### Actual result

Order Total is incorrect due to Discount is calculated by subtotal instead of product A price only.

> Ex:
> A (with discount 5% per qty) price 500$, B price 300$
> I bought x2 A and x1 B. So, subtotal = 1300$. So, Order Total is 1300$ - (1300$ * 0.1) ( + Tax, Ship ...)  => this is wrong calculation.
> It should be Order Total is (1000$ - 1000$ * 0.1) + 300$ ( + Tax, Ship ...) 

This is my test: [Test discount](https://www.loom.com/share/17639dc9148540e6ac826a94aee214ce)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-10-18 08:10
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2022-10-18 12:31
Hi @psydog-1101,


Thank you for reporting and collaboration.


Verified the issue on Magento 2.4-develop and 2.4.5 instances and the issue is not reproducible on both the instances.Discount is correctly populated.Kindly refer the screenshots.


<img width="1059" alt="Screenshot 2022-10-18 at 2 05 55 PM" src="https://user-images.githubusercontent.com/51680745/196422573-4b353be9-8088-47c3-8dd4-78a4289b77ed.png">


<img width="1100" alt="Screenshot 2022-10-18 at 2 06 02 PM" src="https://user-images.githubusercontent.com/51680745/196422633-9c8c232d-4eff-4367-9f85-f38d1a33529f.png">




<img width="1186" alt="Screenshot 2022-10-18 at 2 06 14 PM" src="https://user-images.githubusercontent.com/51680745/196422722-0d01cb19-a3e0-41de-9aae-10645775132c.png">




<img width="1408" alt="Screenshot 2022-10-18 at 2 05 00 PM" src="https://user-images.githubusercontent.com/51680745/196422764-dadf734a-2017-4db8-9a4c-b38c950d6177.png">






Kindly recheck the issue on Magento 2.4-develop instance.


Note: In your video you are adding wrong product to cart kindly check. And also after adding a discount it will directly deducted from product price.in your case discount is applying from cart price rules.please check if any cart price rules are active.

Thanks.

**Comment by psydog-1101** [comment] 2022-10-19 02:00
@magento give me 2.4-develop instance

**Comment by psydog-1101** [comment] 2022-10-19 02:38
Hi @engcom-Bravo , I confirm that discount is correct. It is something missing with my testing formula. Thank you for your confirmation. Please close this issue.

**Comment by engcom-Bravo** [comment] 2022-10-19 07:11
Hi @psydog-1101,

Thanks for quick update.

We are closing this issue as per your comment.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-19 07:11 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5
