### ISSUE TITLE
Error 500 when no parameter is given to shipping/tracking/popup [PHP 8]

### ISSUE THREAD

**Issue by TheoGranier** [magento/magento2#37558] opened 2023-05-30 09:26 UTC
### Preconditions and environment

- Magento version 2.4.4-p2
- PHP 8.1.13
- Current application mode : production (even developper)

### Steps to reproduce

In frontend, open https://***/shipping/tracking/popup url without giving parameter,

You'll get this error : 
`Exception #0 (Exception): Deprecated Functionality: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/magento/framework/Url/Decoder.php on line 34`
because php native function strtr is trying to read a null parameter 

As a counter-example, if you access to this url from BO shipment with a "hash" parameter for example : https://****/shipping/tracking/popup?hash=c2hpcF9pZDoxNDg4ODg6MTcxZTNmZDkxODZkNzczMzRhMjk3ZTY5MmVlMjJmYzI%2C 

You won't have the error because strtr is reading the hash parameter that is provided.

### Expected result

When no "hash" parameter is given, the result expected is a 404 error like if there is a bad "hash" parameter provided. And no more 500 error

### Actual result

Exception, and 500 error with this stacktrace : 
`1 exception(s):
Exception #0 (Exception): Deprecated Functionality: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/magento/framework/Url/Decoder.php on line 34

Exception #0 (Exception): Deprecated Functionality: strtr(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/magento/framework/Url/Decoder.php on line 34
<pre>#1 strtr() called at [vendor/magento/framework/Url/Decoder.php:34]
#2 Magento\Framework\Url\Decoder->decode() called at [vendor/magento/module-shipping/Helper/Data.php:59]
#3 Magento\Shipping\Helper\Data->decodeTrackingHash() called at [vendor/magento/module-shipping/Model/Info.php:81]
#4 Magento\Shipping\Model\Info->loadByHash() called at [vendor/magento/module-shipping/Controller/Tracking/Popup.php:57]
#5 Magento\Shipping\Controller\Tracking\Popup->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Magento\Shipping\Controller\Tracking\Popup\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Magento\Shipping\Controller\Tracking\Popup\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Shipping\Controller\Tracking\Popup\Interceptor->___callPlugins() called at [generated/code/Magento/Shipping/Controller/Tracking/Popup/Interceptor.php:23]
#9 Magento\Shipping\Controller\Tracking\Popup\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#10 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Shipping\Controller\Tracking\Popup\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Shipping\Controller\Tracking\Popup\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Shipping\Controller\Tracking\Popup\Interceptor->___callPlugins() called at [generated/code/Magento/Shipping/Controller/Tracking/Popup/Interceptor.php:32]
#14 Magento\Shipping\Controller\Tracking\Popup\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#15 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#16 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#17 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#20 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#22 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/amasty/geoipredirect/Plugin/Action.php:196]
#24 Amasty\GeoipRedirect\Plugin\Action->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#27 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#28 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#29 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>
` 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-05-31 06:19
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-05-31 13:06
Hi @TheoGranier,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the attached video.


In both the cases we are getting 404 error.


https://github.com/magento/magento2/assets/51680745/8e357a67-6151-4a09-acd4-7bed74684fed



Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-06-13 06:11
Hi @TheoGranier,

Kindly provide update on this comment https://github.com/magento/magento2/issues/37558#issuecomment-1570200741
are you still working on this issue.Please let us know if you are facing any issue.


Thanks.

**Comment by TheoGranier** [comment] 2023-06-19 15:10
Hello, 
Thank you for your test,
What php version is in your environment ? Because the issue is with php 8 that the function strtr throws the error
If you are in php 7, it's normal you don't reproduce the issue
Can you confirm me you are testing with php 8 please ?
Thank you

**Comment by engcom-Bravo** [comment] 2023-06-20 10:03
Hi @TheoGranier,

Thanks for your update.

We are using php `8.1` still we are not able to reproduce the issue.

<img width="610" alt="Screenshot 2023-06-20 at 11 43 29 AM" src="https://github.com/magento/magento2/assets/51680745/94e49d9b-50ff-4aa3-a26d-b30ff2f34f6c">


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-07-03 05:25
Hi @TheoGranier,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-07-03 05:25 UTC
Labels: Issue: needs update, Reported on 2.4.4-p2
