### ISSUE TITLE
Edit default store view will stop saying that Default store cannot be disabled

### ISSUE THREAD

**Issue by barbanet** [magento/magento2#7349] opened 2016-11-08 14:22 UTC
### Preconditions

1. Default installation of Magento CE 2.1.2 without sample data (without any data yet), installed using composer.
2. PHP 5.6.27.
3. Mysql 5.6.33.

### Steps to reproduce

1. In order to add a new store view for another language, edit the default sotre view and change the name from "Default Store View" to "English"
2. Save your change.

### Expected result

1. Store view name should be saved.

### Actual result

1. When you try to save your change you'll see the message "Default store cannot be disabled".
![area de trabajo 1_003](https://cloud.githubusercontent.com/assets/392385/20102595/652a4b60-a5a5-11e6-820b-277a467271b3.png)

2. So now you need to set the Status value (first time was disabled by default).
![area de trabajo 1_004](https://cloud.githubusercontent.com/assets/392385/20102609/77607a16-a5a5-11e6-8e9f-c36c1aae8fd5.png)

3. Now you can save correctly.
![area de trabajo 1_005](https://cloud.githubusercontent.com/assets/392385/20102617/7f960b74-a5a5-11e6-9d5c-0db428736e41.png)

If you try to edit another store view (not the default one) this won't happen.

**Comment by odubovyk** [comment] 2016-11-09 14:20
Thank you for the report. Internal ticket MAGETWO-60746

**Comment by magento-engcom-team** [comment] 2017-09-20 23:07
@barbanet, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 23:07 UTC
Labels: Issue: Ready for Work, bug report, Issue: Format is valid
