### ISSUE TITLE
.shop domain not accepted

### ISSUE THREAD

**Issue by johnvanderstelt** [magento/magento2#6814] opened 2016-09-29 21:01 UTC
.shop domains are not accepted as store e-mail addresses (admin)

**Comment by hostep** [comment] 2016-09-30 07:04
Duplicate: https://github.com/magento/magento2/issues/4547

**Comment by mbrinton01** [comment] 2016-09-30 09:59
@johnvanderstelt, @hostep is correct that this is a duplicate of another issue. I am closing this issue, please follow the other ticket for updates on a fix.

**Closed as completed by mbrinton01** 2016-09-30 09:59 UTC
