### ISSUE TITLE
admin panel: Can't mass delete more customers than the limit of pagination

### ISSUE THREAD

**Issue by dionpapanik** [magento/magento2#28078] opened 2020-05-02 11:23 UTC
### Preconditions (*)

1. Clean installation of Magento 2.3.1 in developer mode

### Steps to reproduce (*)

1. Login to admin of an installation with many customer accounts and go to the Customers Section (Customers > All Customers)
2. Select all Customers for mass delete (Dropdown arrow > Select All) https://prnt.sc/s9mhut
3. Select Actions > Delete
4. Confirmation message appears with the correct number https://prnt.sc/s9mn2y
5. Press OK

### Expected result (*)

1. Successfully delete the selected number customers or throw an error message

### Actual result (*)

1. Deleted customers based on the limit of my pagination (200 entities) https://prnt.sc/s9mi9s . If I set a pagination limit to 50, it deletes only 50 and so on...

**Comment by krishprakash** [comment] 2020-05-03 09:47
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-05-03 09:47
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-05-03 09:48
Hi @krishprakash, here is your [Magento instance](https://i-28078-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28078-2-4-develop.instances.magento-community.engineering/admin_cdc8](https://i-28078-2-4-develop.instances.magento-community.engineering/admin_cdc8)
Login: `c91b8fbb` Password: `49f3b019cd2e`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-05-03 09:55
Hi @dionpapanik. Thank you for your report.
Can not able to reproduce the issue on latest instance
Issue is already fixed in 2.3.4 instance, Refer PR #15935

**Closed as completed by krishprakash** 2020-05-03 09:55 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Progress: ready for QA, Reported on 2.3.1
