### ISSUE TITLE
RabbitMQ causes 2.3.1 upgrade failure

### ISSUE THREAD

**Issue by adamlavery** [magento/magento2#22589] opened 2019-05-02 08:37 UTC
Preconditions (*)
1. Running M2.2.6

Steps to reproduce (*)
1. Upgrade to 2.3.1 as detailed in https://devdocs.magento.com/guides/v2.3/comp-mgr/cli/cli-upgrade.html.

Expected result (*)
1. Magento successfully upgrades to 2.3.1

### Actual result (*)
1. Magento fails to successfully upgrade to 2.3.1

Attempting to run setup:upgrade results in it failing with:

```
Running schema recurring...
...
Module 'Magento_Amqp':
Notice: Undefined index: save in /home/[site]/public_html/vendor/magento/framework/Reflection/MethodsMap.php on line 81
```

Disable module Magento_Amqp and it then fails with:

```
Module 'Magento_MysqlMq':
Running schema recurring...Notice: Undefined index: save in /home/[site]/public_html/vendor/magento/framework/Reflection/MethodsMap.php on line 81
```

This results in a failed website with:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Klarna_Core data: current version - 4.4.4, required version - 5.1.0
MSP_ReCaptcha data: current version - none, required version - 1.5.0
MSP_TwoFactorAuth data: current version - none, required version - 2.2.0
Amasty_Base data: current version - 1.5.0, required version - 1.6.3
Magento_AuthorizenetAcceptjs data: current version - none, required version - 1.0.0
Klarna_Ordermanagement data: current version - 4.3.4, required version - 5.0.2
Amasty_CronScheduleList data: current version - none, required version - 1.0.0
Klarna_Kp data: current version - 5.4.4, required version - 6.1.0
Temando_Shipping data: current version - 1.2.1, required version - 1.5.0
Vertex_Tax data: current version - 100.2.0, required version - 100.3.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Klarna_Core data: current version - 4.4.4, required version - 5.1.0
MSP_ReCaptcha data: current version - none, required version - 1.5.0
MSP_TwoFactorAuth data: current version - none, required version - 2.2.0
Amasty_Base data: current version - 1.5.0, required version - 1.6.3
Magento_AuthorizenetAcceptjs data: current version - none, required version - 1.0.0
Klarna_Ordermanagement data: current version - 4.3.4, required version - 5.0.2
Amasty_CronScheduleList data: current version - none, required version - 1.0.0
Klarna_Kp data: current version - 5.4.4, required version - 6.1.0
Temando_Shipping data: current version - 1.2.1, required version - 1.5.0
Vertex_Tax data: current version - 100.2.0, required version - 100.3.0
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000056c067c60000000023738766#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#2 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000056c067c60000000023738766#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#3 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000056c067c60000000023738766#) called at [vendor/magento/framework/App/Http.php:136]
#4 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#5 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#6 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000056c067840000000023738766#) called at [index.php:39]
</pre>

```

How do we fix whatever this is that has been added to 2.3 and is causing this failure?

**Comment by adamlavery** [comment] 2019-05-02 08:42
As for the automated response; I fail to see how requesting us to reproduce this on a vanilla install of Magento is of any value to us. I'm trying to upgrade our site, not a vanilla install.

**Comment by orlangur** [comment] 2019-05-02 16:31
@adamlavery you need to take a vanilla `2.2.6` install and try upgrading to `2.3.1` on your side.

**Comment by adamlavery** [comment] 2019-05-02 16:38
How does upgrading a vanilla 2.2.6, perhaps successfully, help in any way to solve the problem of upgrading OUR 2.2.6 site to 2.3.1?

**Comment by orlangur** [comment] 2019-05-02 18:59
@adamlavery, please pay attention to

> Please make sure that the issue is reproducible on the vanilla Magento instance following Steps to reproduce.

Only you can investigate a problem with your shop. Any bug report here must be reproducible on a vanilla instance.

**Comment by adamlavery** [comment] 2019-05-03 07:42
So to be clear, you're saying the Magento Core team is abdicating any responsibility for investigating issues that new core features are causing with customer sites?

We're not talking here about custom or 3rd party modules having issues with 2.3, which are our or the relevant 3rd party's responsibility to deal with whatever changes have been made to the core. We're talking about core modules that Magento have added in this release causing the general upgrade script to crash on (vanilla) core modules.

I've noticed this increasing trend on issues raised here for the Magento team to demand that an issue is reproducible on a vanilla version before they'll investigate. That is plain wrong. Probably 99.9% of Magento stores in production are not vanilla installs. I can reproduce this issue at will on OUR store, with it's theme and all the extra modules we need to give us the functionality our store needs.

It's not acceptable for the Magento Core team to say: well it works on a vanilla install so it's not our problem. That's not and has never been the nature of Magento. The Magento core alone is rarely enough to provide the fully functional store customers need. Which means stores use the absolutely essential Magento eco-system to build functional stores. Which means Magento core developers and contributors must take responsibility for changes/additions that break working sites, often because they have not considered the impact small and sometimes unnecessary code changes have on backward compatibility.

So to come back to the main point. You're confirming that the Magento team will not investigate this issue unless it's reproducible on a vanilla install? An exercise I would expect and hope would be a waste of time. Let's face it, if upgrading from a vanilla 2.2.6 to 2.3.1 fails, what does that say about the quality of Magento releases?

**Comment by orlangur** [comment] 2019-05-03 09:27
@adamlavery,

> We're talking about core modules that Magento have added in this release causing the general upgrade script to crash on (vanilla) core modules.

If this is the case, it should not be too hard to reproduce a problem on a vanilla installation. You can even disable new core modules which you don't need.

> I've noticed this increasing trend on issues raised here for the Magento team to demand that an issue is reproducible on a vanilla version before they'll investigate. That is plain wrong.

Nope, this is the only viable approach for Open Source. See https://github.com/magento/magento2/wiki/Issue-reporting-guidelines#steps-to-reproduce: 

> This part of the bug report is the most important, as developer will use this information to reproduce the issue. **Problem is more likely to be fixed if it can be reproduced.**

> So to come back to the main point. You're confirming that the Magento team will not investigate this issue unless it's reproducible on a vanilla install? 

I'm just saying that without clear steps to reproduce it is pretty hard if not impossible to fix any bug. This GitHub repo is not customer support, so, even if you give access to your store issue is unlikely to be investigated. "Reproduce on a vanilla install" does not mean you must use out-of-the-fox modules only in your scenario, what you should actually do is to isolate a problem on your side and provide a minimalistic case so that it can be reproduced by anyone else.

> Let's face it, if upgrading from a vanilla 2.2.6 to 2.3.1 fails, what does that say about the quality of Magento releases?

The nature of software development is that you can never predict amount of _unknown_ issues. I would be pretty surprised if such upgrade would fail with out-of-the-fox setup as there are automated builds which check each upgrade (2.2.5 -> 2.2.6, 2.3.0 -> 2.3.1) before release. With additional modules involved or some other configuration differences, like a particular RabbitMQ version, things can go wrong and there is no way to check all possible combinations of such prior to release.

I may be overlooking something, please provide another possible approach to investigate this issue if you see one.

**Comment by adamlavery** [comment] 2019-05-03 09:56
Ok, here's the approach I would expect to happen in this situation:

Whoever is responsible for adding the RabbitMQ support, which is not something I know anything about or have any reason at this stage to have an interest in, check the module code that runs when we issue a setup:upgrade command. They can then come up with a hypothesis on what is causing the upgrade script to fail with the noted errors and set about proving then fixing it.

The whole point of being able to reproduce an error is to be able to say that, when I do this, this happens. This allows me to know what code path is being followed, figure out how to fix it and then know how to verify that it has been fixed.

This issue is already reproduced. When I run setup:upgrade the Module_Amqp fails with the noted error - every time. If I disable Module_Amqp, then the next apparently RabbitMQ affected module fails, every time, with the noted error. This should be more than enough for whoever is responsible for this new code to figure out what is going wrong.

**Comment by orlangur** [comment] 2019-05-03 09:59
@adamlavery, ok, got it, the only confirmation I asked you for was to check if

> This issue is already reproduced. When I run setup:upgrade the Module_Amqp fails with the noted error - every time. If I disable Module_Amqp, then the next apparently RabbitMQ affected module fails, every time, with the noted error.

steps occur on a vanilla install.

Please add RabbitMQ version and any other environment details which could be useful to description.

**Comment by adamlavery** [comment] 2019-05-03 10:26
And herein maybe the crux of the issue. What is RabbitMQ? Never heard of it and have no idea why I'd want it! Just something that has appeared in the latest Magento release. Are we supposed to have checked our server has it installed and a particular version? No idea! Nothing in the reference article on upgrading to 2.3 mentions RabbitMQ. 

Is this another new facility added that we don't know about, is enabled by default and then breaks sites because it's not configured or supported on our server?

**Comment by orlangur** [comment] 2019-05-03 12:29
@adamlavery ah, got it: basically RabbitMQ is something you don't want to in your Magento installation even if it's running on your servers.

**Comment by swatts7777777** [comment] 2019-05-29 04:56
Back on the topic at hand....

I am experiencing this same problem.  A vanilla install of 2.3.1 works on my server, but upgrading from 2.2.7 to 2.31 results in this error:

```
Module 'Magento_Amqp':
Notice: Undefined index: save in /[Magento Root]/vendor/magento/framework/Reflection/MethodsMap.php on line 81
```

Can anybody help shed some light on how I can get around this issue?

**Comment by orlangur** [comment] 2019-05-29 09:30
@swatts7777777 disabling module is not an option?

**Comment by swatts7777777** [comment] 2019-05-29 09:58
Thanks @orlangur 

Disabling both Magento_Amqp and Magento_MysqlMq allows me to upgrade.  

Thankyou for your help.

**Comment by praveen-chelumalla** [comment] 2019-05-31 04:55
@swatts7777777 any solution you got for this?

```Notice: Undefined index: save in /[Magento Root]/vendor/magento/framework/Reflection/MethodsMap.php on line 81```

I am also facing the same issue.

After I am disabling both Magento_Amqp and Magento_MysqlMq module I am getting an error like 'Warning: PDOStatement::execute(): MySQL server has gone away '.

Can anybody help this on how I can get around this issue?

**Comment by swatts7777777** [comment] 2019-05-31 04:59
Hi @praveen-chelumalla 

I didnt have any issues with the MySQL service after doing this.  It sounds like you might be facing another potentially unrelated issue. 

Have you checked your MySQL logs to see what is causing the it to shutdown/restart?

**Comment by praveen-chelumalla** [comment] 2019-05-31 07:15
Hi, @swatts7777777 thank you for your reply, solved SQL error.

I got some solution to find where the exact problem is occurring.

I was added error log like this 
```
[Magento Root]/vendor/magento/framework/Reflection/MethodsMap.php on line 81
public function getMethodReturnType($typeName, $methodName)
    {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $logger = $objectManager->get('\Psr\Log\LoggerInterface');
        $logger->info(print_r("typeName ==> ".$typeName, true));
        $logger->info(print_r("methodName ==> ".$methodName, true));
        try{
            return $this->getMethodsMap($typeName)[$methodName]['type'];
        }catch (\Exception $e){
            $logger->info(print_r($e->getMessage(), true));
        }
    }
```

from the above method, we can find where the exact problem is occurring.

**Comment by engcom-Charlie** [comment] 2019-08-16 08:15
Hello @adamlavery 
I can't reproduce this issue(I didn't have any errors with the MySQL). 
So i close this issue.
Thank for your report!

**Closed as completed by engcom-Charlie** 2019-08-16 08:15 UTC
Labels: Component: Setup, Issue: Clear Description, Issue: Format is valid

**Comment by aholovan** [comment] 2019-11-04 11:57
Hello, 
I did upgrade from 2.2.3 to 2.3.3 and got the same error:
> Undefined index: save in //vendor/magento/framework/Reflection/MethodsMap.php on line 81

And it was done successfully only after disabling Magento_Amqp, Magento_MysqlMq.
So, the issue still exists despite Magento team unables reproduce it.

**Comment by pettersone** [comment] 2019-12-18 21:57
I was getting the same error and the issue was a commented out 'save' function in one of my custom modules api's interface files that was still visible in my webapi.xml declaration.

meaning. I had commented out some api's in the interface and I had missed the corresponding declaration for the save method in the webapi.xml file. I could either put the save function back in the interface to solve the problem, OR commenting out the route in webapi.xml also solved it.
