### ISSUE TITLE
Can't save product attribute: Attribute code is invalid.

### ISSUE THREAD

**Issue by hoangnm89** [magento/magento2#10172] opened 2017-07-07 03:48 UTC
### Preconditions

1. Magento 2.1.6
2. php 5.6
3. mysql 5.6

### Steps to reproduce

1. Create new product attribute: 
Title: `physical specification - Weight (g)`
Attribute Code: `specs_weight`
2. Press `Save and Continue Edit` => successfully
3. Change Title of attribute to: `Physical Specification - Weight (g)` (uppercase: P and S)

### Expected result

1. It should change title to new one: `Physical Specification - Weight (g)`

### Actual result

It can't save and thrown: `Attribute code "attr_physical_specification_weight_" is invalid. Please use only letters (a-z), numbers (0-9) or underscore(_) in this field, first character should be a letter.
`
![alt text](http://i.imgur.com/EERhEBZ.png "sss")

here is some more attributes get same problem:
Speaker - Subwoofer Type ( Active / Passive / Wireless, Bulit-in )
Connectivity - ARC (Audio Return Channel)
Audio Feature - Bluetooth HI-FI Codec

**Comment by korostii** [comment] 2017-07-07 14:58
This is probably a duplicate of #6770. 

The underlying issue is that there's a hard-coded limit on the maximum  allowed length of the attribute code. While I agree that the limit should be increased, the error message itself should also be changed.

**Comment by veloraven** [comment] 2017-07-25 06:40
I'm closing this issue as a duplicate.
@korostii thank you for link to corresponding issue.

**Closed as completed by veloraven** 2017-07-25 06:40 UTC
Labels: Issue: Format is valid

**Comment by korostii** [comment] 2017-07-25 14:45
Sure, NP. 
As far as I know, the limit [went up to 60](https://github.com/magento/magento2/commit/235ccff1e9afecb6a46e7cddc9acddfb7539efd7#diff-15304abf4bfa8fea00d5d541fbc5f002) on `develop` branch recently.

Still, it's a bit strange though that the automatic attribute code generation prevents you from having a longer label.

**Comment by abrittis** [comment] 2018-01-16 19:40
I agree with korostii.  Why is the attribute code uneditable, and there is a automatic generator that uses the label to generate an invalid one - thus limiting the ability to name the label.  

Either:
   1.  Allow the user to generate their own code.  System can give a uniqueness error length error as needed.
   2.  If the editor / system feels the need to generate a code (i.e. the user left it blank) - at least put proper logic to generate a valid code based on a valid label.
