### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by SunilC1512** [magento/magento2#36007] opened 2022-08-24 09:27 UTC
### Preconditions and environment

*2.4.5
*Fresh Install

### Steps to reproduce

#Steps to reproduce
1.Go to home page.
2.Type somthing in seerch bar
3.Enter to search.

### Expected result

#Expected result
We trying to search in the search feild....Show the all search to related kyeword in search bar.

### Actual result

#Actual result
Not show any result after click enter button.
![seach bar](https://user-images.githubusercontent.com/110841790/186382996-55fd501b-1d3a-4ceb-92ee-2e37bfd5118e.jpg)

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2022-08-24 11:00
Hi @SunilC1512,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop branch and 2.4.5 project-community-edition as well but the issue is not reproducible. Kindly refer the screenshots.

<img width="927" alt="search" src="https://user-images.githubusercontent.com/51680745/186402144-37d0c8ee-2bce-403d-86ee-8f216bbfc1c1.png">


<img width="934" alt="search 2" src="https://user-images.githubusercontent.com/51680745/186402174-e441727a-b8af-4ec6-b576-05ccefbed8ff.png">


Thanks.

**Comment by pmonosolo** [comment] 2022-08-24 18:13
I've seen this before, its not that its not working, its that it has a weird long delay.

![image](https://user-images.githubusercontent.com/66754347/186492370-408eaae4-4f74-4fcb-80e3-f1c1f8e04d63.png)

On a production store it took 19 seconds to do an ajax call for one customer. 

This is on a local developer server on Magento 2.4.3:
![image](https://user-images.githubusercontent.com/66754347/186492421-1439fa57-6a71-4b86-b229-ce7e73cc4330.png)

This feature is not like a super critical for a small store, but for bigger store, this is a must to have.

**Comment by engcom-Bravo** [comment] 2022-10-03 06:41
Hi @SunilC1512,


We have noticed that this issue has not been updated for a period of 14 Days.
Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2022-10-03 06:41 UTC
Labels: Issue: needs update, Reported on 2.4.5
