### ISSUE TITLE
Can not checkout in m2.4.3 when address has extension attribute

### ISSUE THREAD

**Issue by MaiDucQuan97** [magento/magento2#34202] opened 2021-09-30 04:36 UTC
### Preconditions (*)

1.  2.4.3-p1

### Steps to reproduce (*)

1. Address have extension attribute
2. Already reproduce this issue in default m2.4.3

### Expected result (*)

1. Checkout success

### Actual result (*)

1. Can not checkout 
2. Error message: Object of class Magento\Quote\Api\Data\AddressExtension could not be converted to string
![Selection_510](https://user-images.githubusercontent.com/30230100/135387968-4a0e2414-b0f9-47e0-abbb-de1fcc287386.png)
![Selection_513](https://user-images.githubusercontent.com/30230100/135410642-5849b164-70b0-4388-a90e-3b889805afb6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by ducquywp92** [comment] 2021-09-30 07:56
Hi every body,
I also got this error when I try to checkout with guest customer ( order customer that don't have any address before access checkout page )
Magento 2.4.3 have added the function to compare shipping and billing address when order is place.
Checkout Process working fine if I don't make any customize.

But when I add extension_attribute to AddressInterface, the function array_diff() will cause an error because $billingData contain an object.
class: 
Magento\CheckoutStaging\Plugin\GuestPaymentInformationManagementPlugin
Magento\CheckoutStaging\Plugin\PaymentInformationManagementPlugin

![image](https://user-images.githubusercontent.com/16161115/135411231-d46dbd8b-2a73-45d1-83c5-34429a49b33f.png)

Can you fix it asap? thank you

**Comment by braders** [comment] 2021-11-09 09:27
I have also faced this issue on Magento EE 2.4.3. It seems to affect sites that have the CheckoutStaging module enabled (which is the default) and who are using custom extension attributes for addresses. Custom extension attributes for addresses are documented at https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_new_field.html, and so should be something Magento fully supports.

For anyone else facing this issue, the following patch has been working well for us (placed in the `m2-hotfixes` directory on cloud installations):

```
--- a/vendor/magento/module-checkout-staging/Plugin/GuestPaymentInformationManagementPlugin.php
+++ b/vendor/magento/module-checkout-staging/Plugin/GuestPaymentInformationManagementPlugin.php
@@ -101,7 +101,7 @@
         $billingData = $this->convertAddressValueToFlatArray($billingAddress->getData());
         $billingKeys = array_flip(array_keys($billingData));
         $shippingData = array_intersect_key($quoteShippingAddressData, $billingKeys);
-        $removeKeys = ['region_code', 'save_in_address_book'];
+        $removeKeys = ['region_code', 'save_in_address_book', 'extension_attributes'];
         $billingData = array_diff_key($billingData, array_flip($removeKeys));
         $difference = array_diff($billingData,$shippingData);
         return empty($difference);

--- a/vendor/magento/module-checkout-staging/Plugin/PaymentInformationManagementPlugin.php
+++ b/vendor/magento/module-checkout-staging/Plugin/PaymentInformationManagementPlugin.php
@@ -117,7 +117,7 @@
                 $billingData = $this->convertAddressValueToFlatArray($billingAddressData);
                 $billingKeys = array_flip(array_keys($billingData));
                 $shippingData = array_intersect_key($quoteShippingAddressData, $billingKeys);
-                $removeKeys = ['region_code', 'save_in_address_book'];
+                $removeKeys = ['region_code', 'save_in_address_book', 'extension_attributes'];
                 $billingData = array_diff_key($billingData, array_flip($removeKeys));
                 $difference = array_diff($billingData, $shippingData);
                 $sameAsBillingFlag = empty($difference);
```

**Comment by dborishansky** [comment] 2022-01-06 16:25
@magento give me 2.4-develop instance

**Comment by dborishansky** [comment] 2022-01-06 17:27
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-01-12 09:47
Hi @MaiDucQuan97,

Thank you for reporting the issue.
However, we tried to reproduce it on Magento 2.4-develop but the address extension functionality works as expected.
Steps followed to reproduce issue:

1. Added a new plugin and added the address extension attribute by following the steps given in the [doc](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_new_field.html).
2. Verified the checkout functionality after adding the address extension attribute as a Guest user as well as the registered user.
3. Checkout functionality works as expected and I was able to place the order. (See the attached screenshots.)
<img width="1438" alt="Screenshot 2021-11-10 at 8 18 39 PM" src="https://user-images.githubusercontent.com/51681618/149114776-d0fd6539-9f8f-47f7-89bc-f10a8f9cd1c5.png">
<img width="1438" alt="Screenshot 2021-11-10 at 8 21 52 PM" src="https://user-images.githubusercontent.com/51681618/149114854-c19a5f2c-f789-4a3b-96f4-966809a850d5.png">
<img width="1438" alt="Screenshot 2021-11-10 at 8 22 49 PM" src="https://user-images.githubusercontent.com/51681618/149114869-63f6d2c9-fd54-4bf5-a3aa-5d188e9998ba.png">

4. We tested the address attribute extension for string and array type and it works as expected. 

If the issue still persists at your end then provide the issue details in depth also provide screenshots or video, accordingly I’ll try to reproduce it again.

Thanks

**Comment by wsbrs** [comment] 2022-01-21 12:02
@engcom-Hotel 

The issue happens when you send `extension_attributes` as part of Billiing Address (screen 1), **OR** when shipping address contains extension attributes when order is placed (screen 2). 

Screen 1
![image](https://user-images.githubusercontent.com/2466082/150523435-65d7f7fa-f326-44c6-a4af-c748f83fe953.png)

Screen 2
![image](https://user-images.githubusercontent.com/2466082/150523839-23bea415-1e11-47cc-b645-fee107038fcb.png)

**Comment by igi8819** [comment] 2022-02-04 12:57
We have same issue in Magento EE 2.4.3
For us only works if we remove "extension_attributes" key from both (billingData, shippingData)
```
$removeKeys = ['region_code', 'save_in_address_book', 'extension_attributes'];
$billingData = array_diff_key($billingData, array_flip($removeKeys));
$shippingData = array_diff_key($shippingData, array_flip($removeKeys));
```

**Comment by engcom-Lima** [comment] 2022-02-10 22:49
Hi @MaiDucQuan97,
Thank you for reporting the issue.

I tried reproducing the issue on Magento 2.4-develop branch EE edition and I was able to reproduce the issue.

Steps followed to reproduce the issue:-

1. Install fresh Magento 2.4-develop instance EE edition
2. Add Extension attributes for `Magento\Quote\Api\Data\AddressInterface`
<img width="985" alt="Screenshot 2022-02-11 at 4 03 46 AM" src="https://user-images.githubusercontent.com/60198022/153508000-4e76fd33-bbfc-4ac4-90f1-261b593fd3cd.png">

3. Override LayoutProcessor and all other required mixins by following the official [documentation](https://devdocs.magento.com/guides/v2.4/howdoi/checkout/checkout_new_field.html)

4. Try to place order from Frontend through Guest Checkout
![image](https://user-images.githubusercontent.com/60198022/153508434-05417ac9-3b7c-458f-a50c-bb6eab90431f.png)

**Note:** I have added **unit_number** in shipping data

**Expected Result:** 
User should be able to checkout successfully

**Actual Result:**
1. Can not checkout
2. Error message: Object of class Magento\Quote\Api\Data\AddressExtension could not be converted to string
<img width="1417" alt="Screenshot 2022-02-11 at 4 11 48 AM" src="https://user-images.githubusercontent.com/60198022/153509251-41028b23-2f38-4c73-bb6b-87dcfe1818e8.png">

Hence confirming the issue.

Thanks!

**Comment by MrBlueEyez** [comment] 2022-04-21 09:40
Also facing this issue in 2.4.4. It would be possible to add a check for AbstractSimpleObject and then cast it to array and json_encode it:
```
private function convertAddressValueToFlatArray(array $address): array
    {
        array_walk(
            $address,
            function (&$value) {
                if (is_array($value) && isset($value['value'])) {
                    if (!is_array($value['value'])) {
                        $value = (string)$value['value'];
                    } elseif (isset($value['value'][0]['file'])) {
                        $value = $value['value'][0]['file'];
                    }
                } else {
                    if ($value instanceof AbstractSimpleObject) {
                        $value = json_encode((array) $value);
                    }
                }
            }
        );
        return $address;
    }
```

This way the extension attribute is converted to a string, and the values are still being compared.

**Comment by Pranav-242** [comment] 2022-05-31 06:13
@magento i'm working on it

**Comment by tuyennn** [comment] 2022-07-21 10:26
Hi folks, any update on this ticket?

**Comment by vpodorozh** [comment] 2022-08-23 06:29
Hi All, any updates about the solution? It still happens :)

**Comment by frostitution** [comment] 2022-09-19 21:58
Just discovered this issue on 2.4.4 EE, does @braders patch still work as a temporary fix? Is this still a thing on 2.4.5?

**Comment by chittima** [comment] 2022-10-13 14:15
Internal Team started working on this issue and solution is almost ready

**Comment by trunglv** [comment] 2022-11-07 16:28
A patch for you guys while waiting updating from Magento.
https://gist.github.com/trunglv/9956b6e4adb206ad304c0b00eec05a5a

**Comment by chittima** [comment] 2022-11-07 16:56
Issue is already fixed in the develop branch and not reproducible anymore. Here is the commit https://github.com/magento-commerce/magento2ce/commit/b4f87e9632055d369a0a4c943dee00888c336ea4

**Comment by engcom-Hotel** [comment] 2022-11-09 08:25
Thanks for the update @chittima. We are closing this issue.

Thanks

**Closed as completed by engcom-Hotel** 2022-11-09 08:25 UTC
Labels: Component: Checkout, Issue: Confirmed, Reproduced on 2.4.x, Priority: P1, Progress: done, Reported on 2.4.3, Area: Cart & Checkout

**Comment by mhamzaraja** [comment] 2022-11-17 08:19
Hi, @chittima I am facing the same issue on Magento 2.4.3P and I check your commit link its shows 404 can you please share the patch with me?

Thanks

**Comment by chittima** [comment] 2022-11-17 15:17
Hi @mhamzaraja Please find the commit: b4f87e9632055d369a0a4c943dee00888c336ea4

**Comment by rendyep** [comment] 2024-07-26 10:18
Is patch for 2.4.5-p8 available for this issue?
