### ISSUE TITLE
\Magento\Framework\Image\Adapter\Gd2::open() does not free the previous GD image resource _imageHandler with imagedestroy before creating a new one

### ISSUE THREAD

**Issue by dmitrii-fediuk** [magento/magento2#2712] opened 2015-12-15 02:23 UTC
https://mage2.pro/t/293

Similar to https://github.com/magento/magento2/issues/2694, https://github.com/magento/magento2/issues/2696

**Comment by palamar** [comment] 2016-06-22 16:36
@mage2pro 
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by vzabaznov** [comment] 2016-07-14 08:07
Hi, @mage2pro thanks for contributing, we will close this issue as not updated more than 2 week, if this issue still reproducible please feel free to create new one.

**Closed as completed by vzabaznov** 2016-07-14 08:07 UTC
Labels: Progress: needs update
