### ISSUE TITLE
Attributes with lots of options crash browser when viewed in admin

### ISSUE THREAD

**Issue by careys7** [magento/magento2#11985] opened 2017-11-03 04:31 UTC
### Preconditions

1. Magento 2.1.8, Magento 2.2.0

### Steps to reproduce

1. Add Color attribute with Swatch input type
2. Add ~800+ options
3. Click on "Add Swatch" button

### Expected result

1. Browser doesn't crash

### Actual result

1. Chrome freezes, Firefox freezes etc. 
2. Difficult to find colours in select dropdown element when editing a product

---

A lot of our clients (particularly those in apparel) have hundreds or thousands of colour options. 

The frontend seems to work well, but managing these via admin doesn't work very well. There is a lot of Javascript generated in admin, and the generated DOM is very large. 

**Possible Solution(s)**

- Move attribute option & swatch management to an ajax grid (reduce load on DOM and size of initial backend load)

- Move product edit attribute option selection from a select / multiselect element to an ajax lookup (makes options easier to find, reduces initial backend performance)

- Possibly an attribute setting "Admin selection type" (Ajax, Dropdown, etc)?

**Comment by magento-engcom-team** [comment] 2017-11-20 13:30
@careys7, thank you for your report.
We've created internal ticket(s) MAGETWO-84149 to track progress on the issue.

**Comment by engcom-Alfa** [comment] 2020-01-10 12:00
Hi @careys7. Thank you for your report.
Unfortunately, we are not able to reproduce this issue on the fresh 2.4-develop instance.

**Manual testing scenario:**
1. Add Color attribute with Swatch input type
2. Add ~1000+ options
3. Click on "Add Swatch" button

**Actual Result:**
Browser doesn't crash ( tested on Chrome v.79)

@careys7 So I have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed** 2020-01-14 14:47 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Reproduced on 2.2.x, Reproduced on 2.3.x, Issue:  Cannot Reproduce, Issue: Format is valid
