### ISSUE TITLE
Unable to install Magento with Composer version 2.4.4

### ISSUE THREAD

**Issue by fredden** [magento/magento2#36516] opened 2022-11-23 12:01 UTC
### Preconditions and environment

- Magento `2.4-develop` branch, after https://github.com/magento/magento2/commit/4b43b2b29e9dc42501875b6356978868a1b1268e
- Composer version 2.3.0 or better

### Steps to reproduce

1. Clone repository
1. Run `composer install`

### Expected result

Required packages are installed.

### Actual result

An error is shown.

![Screenshot_2022-11-23_11-51-13](https://user-images.githubusercontent.com/334786/203541366-361a7292-527e-4412-8be1-428365144ec9.png)

### Additional information

The `laminas/laminas-dependency-plugin` package does not support recent / current versions of Composer. See https://github.com/laminas/laminas-dependency-plugin/pull/41/commits/54d508ab145072c4c7e7ec07cdad1e10196ad373 for some details about this. It's likely that this plug-in can be safely removed from this project.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-23 13:58
Verified the issue on Magento 2.4-develop instance and the issue is reproducible.
Unable to run composer install command after cloning 2.4-develop Magento repository.
Users are asked to run composer update command. Hence confirming the issue.
Composer version used: 2.4.4
![image](https://user-images.githubusercontent.com/60198231/203564874-2c95d421-facc-4849-ac9d-c4e1d4d197fc.png)

**Comment by hostep** [comment] 2022-11-23 17:04
Is duplicate of https://github.com/magento/magento2/issues/36515 😉

**Closed as completed** 2022-12-03 20:20 UTC
Labels: Issue: Confirmed, Component: Composer, Reproduced on 2.4.x, Priority: P2, Progress: done, Reported on 2.4.x, Area: Install & Administer
