### ISSUE TITLE
Product Image Attributes not present in store view at be even if they should

### ISSUE THREAD

**Issue by romeof1980** [magento/magento2#38018] opened 2023-09-28 12:57 UTC
### Preconditions and environment

- Magento version: 2.4.3
- Create 2 store view, i.e. EN and DE

### Steps to reproduce

note: what reported here has also been reproduce when programmatically uploading image via addImagetoMediaGallery

1. Upload (manually) a product image in the "Default Store View" for a chosen product (tested with a grouped prod)
2. check that after uploading "small_image, image and thumnail" icons (the "image attributes") are present on the bottom of the uploaded product image
3. go to store view EN or DE

### Expected result

In the EN or DE store_views we expect to see the icons on the bottom of the image because they are correctly set: indeed at fe the image appears correctly for the store_views

### Actual result

the icons do not appear as if they were set per website and not per the store_view and as if the store view has got no image attribute set (hence expecting no image being shown at fe for the given store view.
they are not flagged as well if we open the image dialog.

this looks like an inconsistent behaviour: in the store_view we should see what is set for the store_view.
Take the name for example: it does NOT look blank because it was set for the website: it shows what would appear at fe for the store view.

this is inconsistency and poor user experience (be user). furthermore put confusion about what really happened when uploading the image

### Additional information
flagged S1 because dev try to employ a workaround when it is really not needed

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by romeof1980** [comment] 2023-09-28 12:59
@magento give me 2.4-develop instance

**Comment by romeof1980** [comment] 2023-09-28 13:23
not reproducible on 2.4.5 dev-develop

**Comment by romeof1980** [comment] 2023-09-28 13:23
https://github.com/magento give me 2.4.3-develop instance

**Comment by engcom-Bravo** [comment] 2023-10-04 10:57
Hi @romeof1980,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.Kindly refer the screenshots.

**Steps to reproduce**


- Upload (manually) a product image in the "Default Store View" for a chosen product (tested with a grouped prod)
- check that after uploading "small_image, image and thumnail" icons (the "image attributes") are present on the bottom of the uploaded product image
- go to store view EN or DE



<img width="1201" alt="Screenshot 2023-10-04 at 12 23 16 PM" src="https://github.com/magento/magento2/assets/51680745/7f5bb32e-ef75-4fc6-91b1-9a423c365016">



<img width="1177" alt="Screenshot 2023-10-04 at 12 23 55 PM" src="https://github.com/magento/magento2/assets/51680745/91eb9788-5c93-4147-940c-cd7b0ca1e582">


In the EN or DE store_views we are able to see the icons on the bottom of the image.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-16 06:18
Hi @romeof1980,

Kindly provide latest update on this comment https://github.com/magento/magento2/issues/38018#issuecomment-1746636136 still you are working on this issue if you are able to reproduce the issue please elaborate the steps to reproduce.Please let us know still if you are facing any issue.

Thanks.

**Comment by engcom-Bravo** [comment] 2023-10-23 05:30
Hi @romeof1980,

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-10-23 05:30 UTC
Labels: Issue: needs update, Reported on 2.4.5
