### ISSUE TITLE
Search doesn't work for new product review

### ISSUE THREAD

**Issue by TClilMouse** [magento/magento2#6720] opened 2016-09-22 23:28 UTC
### Preconditions

1. Magento 2.1
2. PHP 7.0.9, MySql 5.6.27
### Steps to reproduce

1. Admin->marketing->reviews-> new review
2. Enter anything in the filter
### Expected result

1. Show result with filter
### Actual result

1. Show all products.

**Comment by miakusha** [comment] 2016-09-23 12:20
Hi @seavenger, thank for your report

We've created internal ticket MAGETWO-58909 to address this issue.

**Comment by florinserbu2** [comment] 2016-10-13 09:48
I am also having this issue and I have temporary fixed by extending the 
`\Magento\Review\Block\Adminhtml\Product\Grid` and set the pageSize on the collection:

` protected function _prepareCollection()
    {
        parent::_prepareCollection();
        $this->getCollection()->setPageSize((int)$this->getParam($this->getVarNameLimit(), $this->_defaultLimit));
    }`

**Comment by florinserbu2** [comment] 2016-10-13 10:05
in order to temporary fix this you need to extend `\Magento\Review\Block\Adminhtml\Product\Grid` and rewrite `_prepareCollection()` :

```
protected function _prepareCollection()
{
    $store = $this->_getStore();
    $collection = $this->_productFactory->create()->getCollection()->addAttributeToSelect(
        'sku'
    )->addAttributeToSelect(
            'name'
        )->addAttributeToSelect(
            'attribute_set_id'
        )->addAttributeToSelect(
            'type_id'
        )->setStore(
            $store
        );

    if ($this->moduleManager->isEnabled('Magento_CatalogInventory')) {
        $collection->joinField(
            'qty',
            'cataloginventory_stock_item',
            'qty',
            'product_id=entity_id',
            '{{table}}.stock_id=1',
            'left'
        );
    }
    if ($store->getId()) {
        //$collection->setStoreId($store->getId());
        $collection->addStoreFilter($store);
        $collection->joinAttribute(
            'name',
            'catalog_product/name',
            'entity_id',
            null,
            'inner',
            Store::DEFAULT_STORE_ID
        );
        $collection->joinAttribute(
            'custom_name',
            'catalog_product/name',
            'entity_id',
            null,
            'inner',
            $store->getId()
        );
        $collection->joinAttribute(
            'status',
            'catalog_product/status',
            'entity_id',
            null,
            'inner',
            $store->getId()
        );
        $collection->joinAttribute(
            'visibility',
            'catalog_product/visibility',
            'entity_id',
            null,
            'inner',
            $store->getId()
        );
        $collection->joinAttribute('price', 'catalog_product/price', 'entity_id', null, 'left', $store->getId());
    } else {
        $collection->addAttributeToSelect('price');
        $collection->joinAttribute('status', 'catalog_product/status', 'entity_id', null, 'inner');
        $collection->joinAttribute('visibility', 'catalog_product/visibility', 'entity_id', null, 'inner');
    }

    $this->setCollection($collection);

    $this->getCollection()->addWebsiteNamesToResult();

    if ($this->getCollection()->isLoaded()) {
        $this->getCollection()->clear();
    }

    $this->_preparePage();

    $columnId = $this->getParam($this->getVarNameSort(), $this->_defaultSort);
    $dir = $this->getParam($this->getVarNameDir(), $this->_defaultDir);
    $filter = $this->getParam($this->getVarNameFilter(), null);

    if (is_null($filter)) {
        $filter = $this->_defaultFilter;
    }

    if (is_string($filter)) {
        $data = $this->_backendHelper->prepareFilterString($filter);
        $data = array_merge($data, (array)$this->getRequest()->getPost($this->getVarNameFilter()));
        $this->_setFilterValues($data);
    } elseif ($filter && is_array($filter)) {
        $this->_setFilterValues($filter);
    } elseif (0 !== sizeof($this->_defaultFilter)) {
        $this->_setFilterValues($this->_defaultFilter);
    }

    if ($this->getColumn($columnId) && $this->getColumn($columnId)->getIndex()) {
        $dir = strtolower($dir) == 'desc' ? 'desc' : 'asc';
        $this->getColumn($columnId)->setDir($dir);
        $this->_setCollectionOrder($this->getColumn($columnId));
    }

    if (!$this->_isExport) {
        $this->getCollection()->load();
        $this->_afterLoadCollection();
    }


    return $this;
}
```

**Comment by magento-engcom-team** [comment] 2017-10-05 14:30
@TClilMouse, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-10-05 14:30 UTC
Labels: Issue: Ready for Work, bug report, Issue:  Cannot Reproduce, Issue: Format is valid
