### ISSUE TITLE
Upgrading to 2.3.5 breaks Swagger (Dotmailer API defintion)

### ISSUE THREAD

**Issue by moloughlin** [magento/magento2#28244] opened 2020-05-16 01:11 UTC
### Preconditions (*)
   In composer.json:

```
"require": {
        "magento/magento-cloud-metapackage": ">=2.3.5 <2.3.6
},
```
   
Run `composer update --with-dependencies magento/magento-cloud-metapackage`

### Steps to reproduce (*)
Visit /swagger 

### Expected result (*)
Able to see Swagger docs

### Actual result (*)
Error shown: `Failed to load API definition.`
Error logged: `The "\DateTime" parameter type is invalid. Verify the parameter and try again.`

---

Set a breakpoint at vendor/magento/framework/Reflection/TypeProcessor.php:435
The problematic definition is \Dotdigitalgroup\Email\Api\Data\CouponAttributeInterface::getExpiresAt which declares a \DateTime return type, which the type processor seemingly can't handle.

**Comment by moloughlin** [comment] 2020-05-16 01:12
@magento give me 2.3.5 instance

**Comment by magento-engcom-team** [comment] 2020-05-16 01:12
Hi @moloughlin. Thank you for your request. I'm working on Magento 2.3.5 instance for you

**Comment by steved1982** [comment] 2020-05-18 09:32
I am having the same issue here all SOAP requests now do not work on Magento 2.3.5

https://magento.stackexchange.com/questions/312864/magento-2-3-5-soap-datetime-is-invalid

**Comment by sta1r** [comment] 2020-05-18 09:57
@moloughlin This was fixed in v4.5.1 of our connector: https://github.com/dotmailer/dotmailer-magento2-extension/pull/558

To resolve you can upgrade via:
```
composer require dotmailer/dotmailer-magento2-extension:"4.5.1 as 4.4.0"
php bin/magento setup:upgrade
```

or add a replace directive to remove our module if you prefer:
```
"replace": {  
        "dotmailer/dotmailer-magento2-extension": "*",  
}
```

**Comment by lano-vargas** [comment] 2020-05-28 20:20
Same issue here, fresh installation 2.3.5 😒

**Comment by Emanuel-23** [comment] 2020-07-01 06:13
I also confirm the issue and i am able to fix it by setting the composer alias as described by @sta1r for now. 

although this seems not right to me, instead we should update the version in all packages that currently depend on dotmailer prior to `dotmailer/dotmailer-magento2-extension` in version `4.5.1` (i.e. `magento/product-community-edition`)...

**Comment by Emanuel-23** [comment] 2020-10-29 11:21
@magento-engcom-team
Can please someone check this, it seems not be solved in magento 2.3.6, although it looks like it could have been solved easily (see https://github.com/magento/magento2/issues/28244#issuecomment-630077997)

**Comment by engcom-Delta** [comment] 2021-01-15 18:28
Hi @moloughlin @Emanuel-23 I'm not able to reproduce issue on clean 2.4-develop and on the latest composer version 2.4.1. Also was checked case with upgrade from 2.3.6 to 2.4.1 and swagger page is correctly displayed after upgrade
**Result:**
:heavy_check_mark: Swagger page is opened without errors
![image](https://user-images.githubusercontent.com/51681379/104764271-d2874980-576f-11eb-9aed-5d025c34df7e.png)


If you'd like to update the issue, please reopen it.

**Closed as completed by engcom-Delta** 2021-01-15 18:28 UTC
Labels: Reproduced on 2.3.5p1, Issue: ready for confirmation, not-confirmed, Reported on 2.3.5
