### ISSUE TITLE
admin | Some cookies are misusing the recommended “SameSite“ attribute

### ISSUE THREAD

**Issue by salehawal** [magento/magento2#34461] opened 2021-10-28 08:37 UTC
### Preconditions (*)
1. php 7.4.3
2. magento 2.4-develop

### Steps to reproduce (*)
1. install latest magento 2.4-develop
2. add ssl to yoru site
3. login to backend

### Expected result (*)
1.
![Screenshot from 2021-10-28 10-34-51](https://user-images.githubusercontent.com/3238761/139219035-bff2a738-20dc-4623-ba0f-c34b71b430e9.png)

### Actual result (*)

1.
![Screenshot from 2021-10-28 10-32-43](https://user-images.githubusercontent.com/3238761/139218705-c3418130-45ef-46b8-8746-b122a091635a.png)
2.
![Screenshot from 2021-10-28 10-33-00](https://user-images.githubusercontent.com/3238761/139218778-86696ddc-85b6-4c14-8cad-737ebd8be0f6.png)

---
- [x] Severity: **S2**

**Comment by salehawal** [comment] 2021-11-02 16:46
it is also related to this issue : #34476 
tried to remove "Magento_AdminAnalytics" but it is still not working, to confirm and checkedout 2.4.3 branch and install it and it is working great .. one thing i notice is that when i login in admin area, it asked me for a security question to allow user and i allwed and continue working

**Comment by salehawal** [comment] 2021-11-02 20:18
i have resolved the issue by downloading the file "https://assets.adobedtm.com/a7d65461e54e/37baabec1b6e/launch-177bc126c8e6.js" and move it under /pub directory ad updating caller url with the new url of edited file as follow:
1- save and edit the file adding "secure" in code to force all cookies to be secure
```
u = s ? "Secure" : "Secure",
o = r ? "Secure" : "Secure",
```
2- update the file call url in "/app/code/Magento/AdminAnalytics/view/adminhtml/layout/default.xml"
```
<!-- <argument name="tracking_url" xsi:type="string">//assets.adobedtm.com/a7d65461e54e/37baabec1b6e/launch-177bc126c8e6.min.js</argument> -->
 <argument name="tracking_url" xsi:type="string">https://magento.darelm.io/pub/launch.min.js</argument>
```

it is a quick and dirty solution, but i hope for a better solution in the next update
![Screenshot from 2021-11-02 22-06-58](https://user-images.githubusercontent.com/3238761/139945639-737ff080-4dc9-4a8d-b374-f3012c744bb4.png)

but it seems that admin is still not resolved and the problem for it spinning forever was not the same site issue from the start 
![Screenshot from 2021-11-02 22-07-11](https://user-images.githubusercontent.com/3238761/139945782-7d8284b5-eed7-4fe2-9210-63e302c9fc19.png)
#34476

**Comment by engcom-Hotel** [comment] 2021-12-31 13:16
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-01-06 07:49
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-11 06:28
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-11 06:29
@magento give me 2.4-develop instance

**Comment by engcom-November** [comment] 2022-01-12 13:07
@magento give me 2.4-develop instance

**Comment by slavvka** [comment] 2022-01-20 18:31
@magento give me 2.4-develop instance

**Comment by engcom-Hotel** [comment] 2022-02-02 08:20
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment] 2022-02-02 12:51
Hi @salehawal,

Thank you for reporting the issue.

I have tried this issue on the fresh installation Magento 2.4-dev but I am not able to reproduce it.
![Screenshot from 2022-02-02 18-20-22](https://user-images.githubusercontent.com/60198022/152157216-ade8db8c-fb1e-4d48-b2fc-5389547302f8.png)


Kindly recheck the issue on Magento 2.4-develop branch and elaborate the steps if the issue is still reproducible.
Thank you.

**Comment by engcom-Hotel** [comment] 2022-02-16 14:16
Dear @salehawal,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2022-02-16 14:16 UTC
Labels: Component: AdminAnalytics, Severity: S3, Issue: needs update
