### ISSUE TITLE
addExpressionFieldToSelect has to be called after all addFieldToSelect

### ISSUE THREAD

**Issue by dbsdsun** [magento/magento2#17635] opened 2018-08-16 05:13 UTC
### Preconditions

1. Magento 2.1.12
2. 

### Steps to reproduce

1. create a collection
2. the following code will only addExpressionFieldToSelect before addFieldToSelect, and the 'stime_part' won't appear in the result.
           $bookingCollection = $this->_bookingCollectionFactory->create();
            $bookingCollection->addExpressionFieldToSelect('stime_part', 'time(start_time)', []);
            $bookingCollection->addFieldToSelect('finish_time', 'finish_date');

### Expected result
Field 'stime_part' populated with calculated data.

### Actual result
Field 'stime_par' doesn't populated with calculated data.

The bug is in the following code

Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection

    protected function _initSelectFields()
    {
        $columns = $this->_select->getPart(\Magento\Framework\DB\Select::COLUMNS);
        $columnsToSelect = [];
        foreach ($columns as $columnEntry) {
            list($correlationName, $column, $alias) = $columnEntry;
            if ($correlationName !== 'main_table') {
                // Add joined fields to select
                if ($column instanceof \Zend_Db_Expr) {
                    $column = $column->__toString();
                }
                $key = $alias !== null ? $alias : $column;
                $columnsToSelect[$key] = $columnEntry;
            }
        }

        $columns = $columnsToSelect;

        $columnsToSelect = array_keys($columnsToSelect);

        if ($this->_fieldsToSelect !== null) {
            $insertIndex = 0;
            foreach ($this->_fieldsToSelect as $alias => $field) {
                if (!is_string($alias)) {
                    $alias = null;
                }

                if ($field instanceof \Zend_Db_Expr) {
                    $column = $field->__toString();
                } else {
                    $column = $field;
                }

                if ($alias !== null && in_array(
                    $alias,
                    $columnsToSelect
                ) ||
                    // If field already joined from another table
                    $alias === null && isset($alias, $columnsToSelect)
                ) {
                    continue;
                }

                $columnEntry = ['main_table', $field, $alias];
                array_splice($columns, $insertIndex, 0, [$columnEntry]);
                // Insert column
                $insertIndex++;
            }
        } else {
            array_unshift($columns, ['main_table', '*', null]);
        }

        $this->_select->setPart(\Magento\Framework\DB\Select::COLUMNS, $columns);

        return $this;
    }

This line skips the ExpressionField
            if ($correlationName !== 'main_table') {

Working around is 
       Call all addFieldToSelect before addExpressionFieldToSelect

**Comment by magento-engcom-team** [comment] 2018-08-16 05:13
Hi @dbsdsun. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@dbsdsun do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by engcom-backlog-nickolas** [comment] 2018-08-16 08:54
Hello @dbsdsun, thank you for your report.
We've acknowledged the issue and added to our backlog.

**Comment by magento-engcom-team** [comment] 2018-11-12 11:09
Hi @dbsdsun. Thank you for your report. 
The issue has been fixed in magento/magento2#17915 by @magently in 2.2-develop branch
Related commit(s):
 - [e9451e0f337cc48e285905c99e83221defc78a36](https://github.com/magento/magento2/commit/e9451e0f337cc48e285905c99e83221defc78a36)
 - [29680f7653167268f474af8929b87aa2d863b9b5](https://github.com/magento/magento2/commit/29680f7653167268f474af8929b87aa2d863b9b5)
 - [5a702eff42e1907d8887281ed32857534d4066bd](https://github.com/magento/magento2/commit/5a702eff42e1907d8887281ed32857534d4066bd)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2018-11-12 11:09 UTC
Labels: Issue: Ready for Work, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Component: Framework/Model

**Comment by sidolov** [comment] 2018-11-22 19:39
Hi @dbsdsun. Thank you for your report. 
The issue has been fixed in magento/magento2#19180 by @torhoehn in 2.3-develop branch
Related commit(s):
 - [e697698a5be421e215f6bab5454d706eed97fb6e](https://github.com/magento/magento2/commit/e697698a5be421e215f6bab5454d706eed97fb6e)
 - [3050d2367c284bded10815e7cd559b7bc3937546](https://github.com/magento/magento2/commit/3050d2367c284bded10815e7cd559b7bc3937546)
 - [99ea1956fd75f7aeef809c90a3ec45f2cdbbd619](https://github.com/magento/magento2/commit/99ea1956fd75f7aeef809c90a3ec45f2cdbbd619)

The fix will be available with the upcoming 2.3.1 release.
