### ISSUE TITLE
[Magento =< 2.1.7] Translation for "Please specify a shipping method." not working.

### ISSUE THREAD

**Issue by royvanos** [magento/magento2#9862] opened 2017-06-07 08:36 UTC
### Preconditions

1. Magento CE 2.1.7 (probably any Magento 2 version)

### Steps to reproduce

1. Set up a store with demo content
2. Enable multiple shipping methods
3. Go directly to the checkout page by clicking the checkout button in the minicart popup
4. Try going to the billing step without selecting a shipping method

### Expected result

1. Translation for "Please specify a shipping method." is translated

### Actual result

1. Translation for "Please specify a shipping method." is not translated

Changing magento/module-checkout/view/frontend/web/js/view/shipping.js
from 
`if (!quote.shippingMethod()) { this.errorValidationMessage('Please specify a shipping method.'); return false; }`
 to 
`if (!quote.shippingMethod()) { this.errorValidationMessage($.mage.__('Please specify a shipping method.')); return false; }` 
does the job!

**Comment by veloraven** [comment] 2017-06-12 13:19
@royvanos thank you for your report.
Internal ticket was created for this issue - MAGETWO-69712

**Comment by koenner01** [comment] 2017-06-13 10:23
This was already fixed on the develop branch in MAGETWO-50289 (https://github.com/magento/magento2/commit/2477c5ca5fdac3c972e81835dc3550f6bdbaacc6)

**Comment by magento-engcom-team** [comment] 2017-10-10 08:30
@royvanos, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 08:30 UTC
Labels: Issue: Ready for Work, bug report, Component: Translation, Issue: Clear Description, Issue: Format is valid
