### ISSUE TITLE
ProcessingErrorAggregator doesn't clear _skippedRows.

### ISSUE THREAD

**Issue by ericrisler** [magento/magento2#8136] opened 2017-01-13 17:38 UTC
The ImportExport\Model\Import\ErrorProcessing\ProcessingErrorAggregator::clear() method does not clear the _skippedRows ivar.  This causes unexpected skipping of rows when executing multiple imports in a loop. (code below)

### Preconditions

1. Magento v2.1
2. php7
3. mySql 5.6

### Steps to reproduce

1. We create a new import model on each loop:
LOOP
        /* @var Magento\ImportExport\Model\Import $importModel */
        $importModel = $this->importModelFactory->create();
2. Then we validate our source data:
         $importModel->validateSource($source);
3. Then we import.
         $importModel->importSource();
END LOOP

What we observe is that the error aggregator is only instantiated once during the **first iteration** of the loop. The import model is instantiated **each iteration**. We see that the import model validateSource() method calls the entity adapter's validateData() method which in turn calls the error aggregator clear() method. Since the error aggregater persists between loop iterations, the clear method needs to clear the _skippedRows ivar in order to reset the state.

### Expected result

1. _skippedRows should be cleared for each bunch

### Actual result

1. Its not.

**Comment by magento-engcom-team** [comment] 2017-10-10 08:30
@ericrisler, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-10-10 08:30 UTC
Labels: bug report, Component: ImportExport, Issue: Clear Description, Issue: Format is valid
