### ISSUE TITLE
Magento 2.1.0 wrong product price in mini cart after removal of any advanced pricing (category discount, tier price etc )

### ISSUE THREAD

**Issue by routbiplab** [magento/magento2#6061] opened 2016-08-09 08:21 UTC
### Preconditions

1. using Magento 2.1.0
### Steps to reproduce

1.  Apply any advance pricing on products.
2.  Add product to cart.
3.  Remove all advance pricing for that product.
4. Check mini cart or cart details view. It shows advance price or discounted price instead of original price.
### Expected result

1.  Mini cart or Cart view should show the original price.
### Actual result

1. Mini cart or cart view page shows discounted price.

**Comment by AVoskoboinikov** [comment] 2016-08-18 10:20
Hello

Thanks for request. It is OK that you see previous price on Mini Cart and Cart. But if you proceed to checkout - you will see original price there.

**Comment by andimov** [comment] 2016-08-18 11:19
@routbiplab 
Thank you for reporting!
This is an expected behavior. So, this is not a bug and I'll close this issue. Please feel free to reopen if it's needed.

**Closed as completed by andimov** 2016-08-18 11:19 UTC

**Comment by routbiplab** [comment] 2016-08-18 12:50
Ok Thanks.
