### ISSUE TITLE
Url Rewrite Cardinality issue

### ISSUE THREAD

**Issue by alucardatem** [magento/magento2#37689] opened 2023-06-29 16:41 UTC
### Preconditions and environment

- Magento version 2.4.X

merchandise a product in multiple store views that
reindex

### Steps to reproduce

Merchandise a product in a multi store view website
run a reindex 

### Expected result

`Catalog Search index has been rebuilt successfully in XX:YY:ZZ`

### Actual result

```

Catalog Search index process error during indexation process:
Fail in child process

```

and in exception.log

```
main.ERROR: Child process failed with message: SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s), query was: SELECT `url_rewrite`.*, `relation`.`category_id`, `relation`.`product_id` FROM `url_rewrite`
 LEFT JOIN `catalog_url_rewrite_product_category` AS `relation` ON url_rewrite.url_rewrite_id = relation.url_rewrite_id WHERE (url_rewrite.entity_id IN ('538940')) AND (url_rewrite.entity_type IN ('product')) AND (url_rewrite.store_id IN (9)) AND (url_rewrite.redirect_type IN (0)) AND (relation.category_id = '368', '377', '380', '383', '764', '766', '772', '773', '774', '872', '874', '882', '883', '892', '950')

```

list of category ids at this point is irellevant

### Additional information

This has caused a store to stop functioning properly. 

### Release note

Fix on url rewrite cardinality issue when running reindex for 

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by alucardatem** [comment] 2023-06-29 16:42
@magento I am working on this

**Comment by alucardatem** [comment] 2023-06-29 16:42
@magento add to contributors team

**Comment by engcom-Bravo** [comment] 2023-06-30 08:44
Hi @alucardatem,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenshots.

**Steps to reproduce**

- Merchandise a product in a multi store view website
- run a reindex


<img width="1416" alt="Screenshot 2023-06-30 at 2 12 39 PM" src="https://github.com/magento/magento2/assets/51680745/4ac3639c-c6a9-446f-bcec-7f200141d2f9">


<img width="681" alt="Screenshot 2023-06-30 at 2 13 47 PM" src="https://github.com/magento/magento2/assets/51680745/98327b24-28bc-484a-a594-6a5567a40ef0">



Reindex completed successfully.


Kindly recheck the behaviour on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by alucardatem** [comment] 2023-06-30 09:40
Hello,
The structure is the following
![image](https://github.com/magento/magento2/assets/900208/286aacdf-4b1e-470e-b75d-fcf504563fdb)

and added a product to X categories.. and the settings for that are: 
![image](https://github.com/magento/magento2/assets/900208/b04e2d4c-2388-4ae4-9067-cee1835c3b86)

merchandising wise:
![image](https://github.com/magento/magento2/assets/900208/77127795-f426-4496-9078-bdb153ec45f6)

then changing the position of the item in the category from 0 to 1000

there should not be a cardinality issue at all... 

`where relation.category_id = [0-999],[0-999],.....`

as that is wrong completely.

**Comment by engcom-Bravo** [comment] 2023-07-07 06:16
Hi @alucardatem,

Thanks for your update.

Similar issue has been created here https://github.com/magento/magento2/issues/37710 We will update our findings in this ticket https://github.com/magento/magento2/issues/37710 we need to close this issue as Duplicate.Kindly move onto this issue https://github.com/magento/magento2/issues/37710 for latest updates / solutions on the same.

Thank you.

**Closed as completed by engcom-Bravo** 2023-07-07 06:16 UTC
Labels: duplicate, Issue: needs update, Reported on 2.4.x
