### ISSUE TITLE
customer_save_after_data_object event dispatching on customer login and login error

### ISSUE THREAD

**Issue by sky4git** [magento/magento2#5825] opened 2016-07-27 02:46 UTC
### Preconditions

1. Magento CE 2.1.0
### Steps to reproduce

1. Setup an observer for **customer_save_after_data_object** event in custom module.
2. Try to do your stuff in the observer. For example, in my case, I am sending email to customer on account update.
3. Now try to login as any customer from fontend. Also try to login with wrong password.
### Expected result

1. The observer for **customer_save_after_data_object** should only come into effect when either admin or customer itself update their account information.
### Actual result

1. As in my case, my observer is sending email for account update on login and login error events.
### events.xml

`<event name='customer_save_after_data_object'>
                        <observer
                            name='tto_custom_observer_customersaveafter'
                            instance='Tto\Custom\Observer\CustomerSaveAfter'
                        />
</event>`

**Comment by sevos1984** [comment] 2016-10-31 11:22
Is this still actual in latest release version?

**Comment by sevos1984** [comment] 2016-11-14 12:20
We are closing this issue because it hasn’t been updated in more than two weeks. If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by sevos1984** 2016-11-14 12:20 UTC
Labels: bug report, Progress: needs update, Component: Customer
