### ISSUE TITLE
Product attribute creation fails with REST API

### ISSUE THREAD

**Issue by j4hangir** [magento/magento2#6213] opened 2016-08-18 00:55 UTC
Magento version is 2.1.0.

When using REST for creating a new attribute, this works: 

URL: `post /rest/V1/products/attributes`
Body:
`{'attribute': {'attribute_id': 0, 'frontend_labels': [{'store_id': 1, 'label': 'azmun'}], 'is_html_allowed_on_front': True, 'attribute_code': 'azmun', 'position': 0, 'is_user_defined': True, 'is_required': True, 'used_for_sort_by': True, 'is_filterable': True, 'frontend_input': 'multiselect', 'default_frontend_label': 'azmun', 'is_filterable_in_search': True, 'is_visible': True, 'is_wysiwyg_enabled': True}}`

But adding any of the following fields will make Magento throw an exception and return the index html page instead: **is_used_in_grid, is_filterable_in_grid, is_visible_in_grid**

Looking into the logs this will be shown:
`Next exception 'Exception' with message 'Report ID: webapi-57b506762d4ff; Message: Property "IsVisibleInGrid" does not have corresponding setter in class "Magento\Catalog\Api\Data\ProductAttributeInterface".' in /home/pcpal/public_html/vendor/magento/framework/Webapi/ErrorProcessor.php:195
`

**Comment by sevos1984** [comment] 2016-08-29 13:17
Thanks for reporting, internal ticket MAGETWO-57753

**Comment by magento-engcom-team** [comment] 2017-09-20 22:31
@j4hangir, thank you for your report.
The issue is already fixed in 2.2.0

**Closed as completed by magento-engcom-team** 2017-09-20 22:31 UTC
Labels: Issue: Ready for Work, bug report, Component: Framework/Webapi, Reproduced on 2.1.x, Fixed in 2.2.x, Issue: Format is not valid
