### ISSUE TITLE
"0" in customizable options price keeps the old value

### ISSUE THREAD

**Issue by SpartakusMd** [magento/magento2#11870] opened 2017-10-30 08:51 UTC
Hello,

There is a issue with the price field. Let's say you have a customizable option for which the price of a value is 10$. If you edit the product and change the price to "0" (not "0.0"), after saving, the price will be 10$. If you set "0" when you add another value, after saving the price will be empty.

### Preconditions
1. Tested on Magento 2.1.6 and 2.1.9

### Steps to reproduce
1. Create a product with a Customizable option
3. Let's say you have the value "checkbox-1" with the price "10"$. Set its the price to "0" (not "0.0")

### Expected result
1. The price for the value "checkbox-1" should be filled with "0" or "0.0"

### Actual result
1. The price for the value "checkbox-1" is "10"$

### Steps to reproduce (alternative)
1. Create a product
2. Create a Customizable option
3. Create the value "checkbox-1" and set the price to "0" (not "0.0")

### Expected result
1. The price for the value "checkbox-1" should be filled with "0" or "0.0"

### Actual result
1. The price for the value "checkbox-1" is empty

**Comment by magento-engcom-team** [comment] 2017-10-30 09:38
Hi @SpartakusMd, thanks for a well-formed bug report!

It is a duplicate of [#4092](https://github.com/magento/magento2/issues/4092), [#4808](https://github.com/magento/magento2/issues/4808)

**Closed as completed** 2017-10-30 09:39 UTC
Labels: duplicate, Issue: Clear Description, Issue: Format is valid
