### ISSUE TITLE
Multiple Address Checkout - Stored Cards (Using Magento_Vault)

### ISSUE THREAD

**Issue by shaw-tech** [magento/magento2#7246] opened 2016-10-31 12:05 UTC
### Preconditions

1. Magento 2.1.2
2. PHP 5.6.11
3. mysql  Ver 14.14 Distrib 5.6.31,

### Details
I've developed a credit card payment method, integrating with a 3rd party, which has the option to store cards for reuse.

I've achieved the latter part by using the constructs provided Magento_Vault in a very similar way to the way that the Magento_Braintree extension leverages it. 

When I attempted to integrate it into the multiple address checkout, however, I observed that it didn't behave the same way as it did on the regular checkout.

Here's what I see:

![selection_131](https://cloud.githubusercontent.com/assets/23167920/19853559/de4c4718-9f61-11e6-8816-2235b15e24f1.png)

I would expect to see a list of the stored cards, or nothing at all (if the logged in customer hadn't stored any yet).

If I continue with with as the selected payment method, I get an error:

![selection_132](https://cloud.githubusercontent.com/assets/23167920/19853599/269c9e1e-9f62-11e6-9c91-a247f905103f.png)

That's fairly understandable - it doesn't know which Magento-side token to use for the payment.

To me, it looks like Magento's multiple address checkout doesn't support the Magento_Vault functionality - is that correct? If so, are there any plans to do so?

**Comment by veloraven** [comment] 2016-11-02 11:36
@shaw-tech thank you for your feedback.
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.

**Comment by shaw-tech** [comment] 2016-11-02 13:30
Hi Veloraven,

The format doesn't really apply because this isn't necessarily a bug, it just looks like there's a feature missing or hasn't been considered.

Could you please address the last query:

To me, it looks like Magento's multiple address checkout doesn't support the Magento_Vault functionality - is that correct? If so, are there any plans to do so?

**Comment by shaw-tech** [comment] 2016-11-07 10:47
Hi again,

Could someone please respond to my query:

It looks like Magento's multiple address checkout doesn't support the Magento_Vault functionality - is that correct? If so, are there any plans to do so?

**Comment by veloraven** [comment] 2016-11-17 14:08
@shaw-tech 
You are right: this functionality was not implemented.
You can submit an improvement to the new  [Magento 2 Feature Requests and Improvements forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).
I'm closing this report as it is not an issue and GitHub issue tracker is intended for technical issues only.

**Closed as completed by veloraven** 2016-11-17 14:08 UTC
Labels: Progress: needs update
