### ISSUE TITLE
Cannot re-order Grouped product's children between pages.

### ISSUE THREAD

**Issue by SanderJP** [magento/magento2#10263] opened 2017-07-17 14:02 UTC
### Preconditions
Magento 2.2 RC 1.4 and below
Php 7.0.20
MySQL 5.7.18

### Steps to reproduce
1. Install Magento.
2. Install Sample Data or create 21 simple products.
3. Create Grouped product and add all 21 simple products so you get 2 pages of associated products.
4. Try to re-order the simple product on page 2 to page 1.

### Expected result
A way to move the products between pages.

### Actual result
You can only re-order products on one page, not from one page to another.

Drupal had this problem and they added the option to manually change the order numbers; which would allow to move them to other pages.

**Comment by misha-kotov** [comment] 2017-07-17 20:42
Hi @SanderJP thanks for reporting this issue - I created an internal ticket for it: MAGETWO-70784. Have you come up with a work-around?

**Comment by SanderJP** [comment] 2017-07-17 22:51
@misha-kotov an ugly one, I've changed the amount of children per page from 20 to 60, so that's not a solution.

From a UX perspective: once I start dragging, I would expect to be able to: (max. 20 products per page)
- drag an item to the bottom of page one and drop it into the 21st position, which switches out numbers 20 (first page) and 21 (second page).
- drag an item to the top of any page but the first, which switches it with the last item on the previous page.

The second scenario could look something like:
![drag_n_drop_through_pages](https://user-images.githubusercontent.com/2470914/28291884-c95c205a-6b4c-11e7-981e-37c774cc4d57.jpg)

Another solution can be to add a Position column, like the 'Products in Category' tab from a category details page. This would allow admins to manually re-arrange products by changing individual order numbers. This would, however, require some additional functionality to move items up or down the order. If you try to move a second page item to the front by assigning  position 0, but all items on the first page have position 0 by default, the item's order is based on alphabetical order and the item could end up on position 20. This functionality is also missing from the order of the products in a category.

**Comment by misha-kotov** [comment] 2017-07-17 22:59
Thanks for providing more context - this is definitely very helpful.

**Comment by Gerbilfarmer** [comment] 2017-08-15 13:45
Hi @SanderJP We have the same issue, but changing the number of children from 20 to 60 would solve our problem. Could you tell us how you made that change please? With thanks.

**Comment by mzenner1** [comment] 2018-02-06 19:19
@SanderJP I have the same request as @Gerbilfarmer.  How did you up the limit from 20 to 60?  As a temporary solution, I'd like to do that

**Comment by SanderJP** [comment] 2018-02-06 19:37
@Gerbilfarmer @mzenner1 Sorry, missed the earlier reply for some reason..
I had an extra task in my ansible deploy flow that installed 2 core hacks that just were not being fixed. So I regex replaced `pageSize:\ 20,` into `pageSize:\ 60,` in the file
`/vendor/magento/module-ui/view/base/web/js/dynamic-rows/dynamic-rows.js` each time I would build/test/deploy new changes to acc/prod. We are not managing said webshop anymore, so not sure if that's still correct, but since you ask for a workaround I assume it hasn't changed. Unfortunately no clean solution.

**Comment by magento-engcom-team** [comment] 2018-12-20 14:48
Hi @engcom-backlog-andrii. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [x] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [x] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by Bashev** [comment] 2021-09-03 17:49
This issue is out of date, now you can control number of items which can be showed per page.

![image](https://user-images.githubusercontent.com/1854269/132047003-b3c33332-120d-40b2-b203-fc15fd4fa720.png)

**Closed as completed** 2021-09-13 06:02 UTC
Labels: Component: Catalog, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Priority: P2, Severity: S2, Progress: done, Area: Catalog
