### ISSUE TITLE
We can't generate the sitemap right now Error in magento 2.1.8

### ISSUE THREAD

**Issue by BabliDey** [magento/magento2#15327] opened 2018-05-18 15:39 UTC
### Preconditions

1. Magento 2.1.8
2. PHP Version 7.0.29

### Steps to reproduce

1. Enabled XML sitemap from store> configuration > catalog > Xml site map
2.  Set Add Images into Sitemapto none in Product image option
3. In magketing > Seo & Search > Site Map > Add new set file name sitemap.xml and path to / then clicked on save and genrate. 

### Expected result

1. Sitemap.xml file should be geneerated and can be accessed by link

### Actual result

1. [Screenshot, logs]
We can't generate the sitemap right now.
![map](https://user-images.githubusercontent.com/24405051/40244095-db0982cc-5ab9-11e8-8adb-4fd66263fd3f.png)

**Comment by BabliDey** [comment] 2018-05-21 13:13
Need Solution for sitemap.xml generation

**Comment by AirmanAJK** [comment] 2018-05-23 18:19
I encountered a simliar problem with sitemap generation that I fixed myself. I had the product "name" attribute set as global scope, but the sitemap generation code for products had hardcoded it as store scoped. I believe that bug was fixed in a later version, but perhaps it was 2.2.x

If you do have the name attribute set as global, try testing it scoped to store instead. If that works, I can share my personal fix, or you can upgrade to a later version where I believe it's already solved.

**Comment by engcom-backlog-nickolas** [comment] 2018-07-20 13:51
Hello @BabliDey, thank you for your report. I cannot reproduce this issue.
![peek 2018-07-20 16-55](https://user-images.githubusercontent.com/40755810/43005968-121096b6-8c3d-11e8-8123-d85e976736bc.gif)
Could you please add more details?

**Comment by engcom-backlog-nickolas** [comment] 2018-08-03 12:43
@BabliDey, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.

**Closed as completed by engcom-backlog-nickolas** 2018-08-03 12:43 UTC
Labels: Issue: Clear Description, Issue: Format is valid

**Comment by tr33m4n** [comment] 2018-10-19 12:38
@BabliDey I'm not sure whether this is the issue you're experiencing, however this line here https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Sitemap/Block/Adminhtml/Edit/Form.php#L115 sets the store ID to that of the admin if the site has a single store (at least in our setup), which obviously would break generation. We fixed by adding a plugin after the `beforeSave` method of `\Magento\Sitemap\Model\Sitemap` to check whether the ID was the admin store and correct to the default store
