### ISSUE TITLE
Front Side add to cart button not working properly

### ISSUE THREAD

**Issue by ghost** [magento/magento2#7481] opened 2016-11-18 06:37 UTC
### Preconditions

1. when click on Add to cart button in product page 
2.  when product added in cart

### Steps to reproduce

1. click on product 
2.  go to product page 
3.  click on add to cart button

### Expected result

1.  product added in cart basket

**Comment by veloraven** [comment] 2016-11-23 13:58
@savan13 thank you for your feedback.
Please specify Magento version you are running.
Please also specify actual result.

**Comment by ghost** [comment] 2016-11-28 11:05
Magneto Version:-   Magento ver. 2.2.0-dev
 actual result: Cart popup not open, I have already added product in cart

**Comment by slopukhov** [comment] 2016-11-30 10:14
@savan13 Please describe that is not displayed.
When you add a product in the shopping cart should be displayed message like 'You added Item to your shopping cart.' and the quantity on the shopping cart icon.
![results](https://cloud.githubusercontent.com/assets/8982177/20748354/81b3a6ca-b6f6-11e6-94c9-6d1802a69fc7.png)

**Comment by ghost** [comment] 2016-11-30 11:01
product page when click add to cart product added in shopping cart message are show but when you click on shopping cart there is nothing to show.
**see the image**  
![bug](https://cloud.githubusercontent.com/assets/23548160/20749855/114e16da-b71a-11e6-923c-ec9a73b9dc89.png)

**Comment by veloraven** [comment] 2017-06-21 10:22
I'm closing this issue as we were not able to reproduce it and reporter's account was deleted.
If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by veloraven** 2017-06-21 10:22 UTC
Labels: bug report
