### ISSUE TITLE
min_sale_qty < 1 is not possible, why?

### ISSUE THREAD

**Issue by DJ0815** [magento/magento2#12224] opened 2017-11-13 21:26 UTC
Hello,

i am using Magento ver. 2.1.8 and i am trying to add products, which can be bought in qty < 1, due to the fact that customers can buy products by meter, so they should be able to buy 0,2m

### Steps to reproduce
i set "is_qty_decimal" to yes, change Minimum Qty Allowed in Shopping Cart to 0.1 . After that i am not able to save due to an error.

so i tried to change Minimum Qty Allowed in Shopping Cart to 0. After that i can save, but when i reopen the product in admin, again Minimum Qty Allowed in Shopping Cart is 1.
 
### Expected result
1. Minimum Qty Allowed in Shopping Cart should be allowed to be < 1 so customer can by products in qty 0,1m for example.

**Comment by magento-engcom-team** [comment] 2017-11-14 12:42
@DJ0815, thank you for your report.
The issue is already fixed in develop branch, 2.2.0

**Closed as completed by magento-engcom-team** 2017-11-14 12:42 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
