### ISSUE TITLE
Wysiwyg Editor Image Upload Doesn't Work Second Time

### ISSUE THREAD

**Issue by bydrei** [magento/magento2#9597] opened 2017-05-11 08:37 UTC
### Preconditions

1. Magento Version EE 2.1.5
2. Theme based of blank.

### Steps to reproduce

1. Login to admin panel
2. Go to Content - Pages
3. Edit any page then click on "Show / Hide Editor" to go to the plain editor.
4. Click on Insert Image, let the GUI load, then click the X to close.
5. Click  on Insert Image again (here you won't be able to open the popup again)

### Expected result

1. You should be able to close and open as many times you want and need.

### Actual result

1. ```Uncaught TypeError: Cannot read property 'closed' of undefined at Object.openDialog (browser.js:39) at HTMLButtonElement.onclick ((index):1)```

**Comment by KevinGimbel** [comment] 2017-05-15 11:50
Can confirm this is the case for Magento CE 2.1.6. It also does not work after inserting an image (e.g not closing the overlay with X). 

I am also not able to switch to the WYSIWYG Editor from the plain editor.

**Comment by hostep** [comment] 2017-05-15 17:28
This was already fixed on the develop branch almost a year ago, but wasn't being backported. So I did just that and created a backport for this fix to apply on Magento 2.1.x: https://github.com/magento/magento2/pull/9332 and it was approved!
I hope it will make its way into the next 2.1.x release :)

**Comment by vincentwinkel** [comment] 2017-07-03 09:00
Hi,
I don't know if it's the same problem, but tested on several personal 2.0.14 install and testable on this 2.0.7 demo online : http://magento2.demo.ubertheme.com/admin (uber / uber123).
1) Create a new CMS page
2) Insert an image (open popup + choose an  image + validate) : the popup is closed, the image is inserted
3) Insert a new image (open popup + choose an image + validate) : the popup is closed but the overlay is still here and no image is inserted
<img width="1089" alt="screen shot 2017-07-03 at 11 01 32" src="https://user-images.githubusercontent.com/1402505/27785827-12522eae-5fdf-11e7-8803-94ec41c70272.png">

Do I need to create a new ticket ? I don't find solution neither similar ticket except this one.

**Comment by magento-engcom-team** [comment] 2017-09-28 11:30
@ferrazzuk, thank you for your report.
The issue is already fixed in develop branch, 2.2.0, 2.1.9

**Closed as completed by magento-engcom-team** 2017-09-28 11:30 UTC
Labels: bug report, Issue: Clear Description, Issue: Confirmed, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by vincentwinkel** [comment] 2017-10-06 12:10
What about magento 2.0 ?
