### ISSUE TITLE
DivisionByZeroError: Division by zero in module-sales/Model/Order/Creditmemo/Total/Tax.php:139

### ISSUE THREAD

**Issue by jorgb90** [magento/magento2#37340] opened 2023-04-05 12:24 UTC
### Preconditions and environment

- Magento 2.4.6

### Steps to reproduce

1. Create an order with zero / free shipping
2. Create an invoice for this order
3. Try to create a credit for this order

### Expected result

Credit loads and can be created

### Actual result

When clicking on credit a main.CRITICAL error appears.

### Additional information

`[2023-04-05T11:37:17.403018+00:00] main.CRITICAL: DivisionByZeroError: Division by zero in /home/xxx/public_html/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Tax.php:139
Stack trace:
#0 /home/xxx/public_html/vendor/magento/module-sales/Model/Order/Creditmemo.php(374): Magento\Sales\Model\Order\Creditmemo\Total\Tax->collect()
#1 /home/xxx/public_html/vendor/magento/module-sales/Model/Order/CreditmemoFactory.php(99): Magento\Sales\Model\Order\Creditmemo->collectTotals()
#2 /home/xxx/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/CreditmemoLoader.php(220): Magento\Sales\Model\Order\CreditmemoFactory->createByOrder()
#3 /home/xxx/public_html/vendor/magento/module-sales/Controller/Adminhtml/Order/Creditmemo/NewAction.php(64): Magento\Sales\Controller\Adminhtml\Order\CreditmemoLoader->load()
#4 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction->execute()
#5 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callParent()
#6 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->Magento\Framework\Interception\{closure}()
#7 /home/xxx/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/NewAction/Interceptor.php(23): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callPlugins()
#8 /home/xxx/public_html/vendor/magento/framework/App/Action/Action.php(111): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->execute()
#9 /home/xxx/public_html/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch()
#10 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch()
#11 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callParent()
#12 /home/xxx/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->Magento\Framework\Interception\{closure}()
#13 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch()
#14 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->Magento\Framework\Interception\{closure}()
#15 /home/xxx/public_html/generated/code/Magento/Sales/Controller/Adminhtml/Order/Creditmemo/NewAction/Interceptor.php(32): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->___callPlugins()
#16 /home/xxx/public_html/vendor/magento/framework/App/FrontController.php(245): Magento\Sales\Controller\Adminhtml\Order\Creditmemo\NewAction\Interceptor->dispatch()
#17 /home/xxx/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#18 /home/xxx/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#19 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#20 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#21 /home/xxx/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /home/xxx/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#23 /home/xxx/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#24 /home/xxx/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#25 /home/xxx/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#26 /home/xxx/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#27 {main} {"exception":"[object] (DivisionByZeroError(code: 0): Division by zero at /home/xxx/public_html/vendor/magento/module-sales/Model/Order/Creditmemo/Total/Tax.php:139)"} []`

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by jorgb90** [comment] 2023-04-05 12:27
Ah its already reported https://github.com/magento/magento2/issues/36800

Couldn't find it at first.

**Comment by engcom-Hotel** [comment] 2023-04-05 14:46
Hello @jorgb90,

Closing this issue as Duplicate of #36800

**Closed as completed by engcom-Hotel** 2023-04-05 14:46 UTC
Labels: Issue: ready for confirmation, Reported on 2.4.6
