### ISSUE TITLE
Bug with REPLACE method in Advanced Prices in CSV Import 

### ISSUE THREAD

**Issue by kamilmaliszewski** [magento/magento2#18761] opened 2018-10-23 07:13 UTC
### Preconditions (*)
1. Magento 2.2.5
2. PHP 7.1
3. MySQL Ver 14.14 Distrib 5.7.20

### Steps to reproduce (*)
1. Define bunch size as e.g 100 (probably 100 is default)
2. Prepare CSV with over 100 records (I had 2012) and different SKU! E.g 4-5 prices for one SKU
3. Select the "Replace" method
4. Make an import

### Expected result (*)
1. All prices should be imported into Magento

### Actual result (*)
1. For my example only 1909 records are imported into Magento
2. SKU of records from first bunch are cached as products to remove and in each next bunch itreration products with only those SKUs are removed. So in my exmaple always 103 prices records was removed. All from first bunch size and first 3 from 2-nd - becuase they have SKU used in first bunch.

### TIP
It's nice to check on the empty database. If you have empty tier_prices and import big files with advanced pricing with option "replace" then there will be missing records from 1-st bunch. 

### HOW TO FIX IT
1. In file `vendor/magento/module-advanced-pricing-import-export/Model/Import/AdvancedPricing.php` in method `deleteProductTierPrices` on line _467_ are cached and saved to property SKU to remove. They are saved only when propety is null, so only 1-st time (1-st bunch). Then in each iteration prices with those SKUs are removed
2. I thnik first should be removed all used advacned pricing, then should be added

**Comment by magento-engcom-team** [comment] 2018-10-23 07:13
Hi @kamilmaliszewski. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kamilmaliszewski do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-10-23 07:13
Hi @kamilmaliszewski. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@kamilmaliszewski do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2018-11-26 07:48
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [x] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2018-11-26 10:11
@engcom-backlog-nazar Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-96629`, `MAGETWO-96630` were created

**Comment by magento-engcom-team** [comment] 2019-02-13 07:15
Hi @DenisSaltanahmedov. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if you want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-03-16 13:28
Hi @kamilmaliszewski. Thank you for your report. 
The issue has been fixed in magento/magento2#21189 by @DenisSaltanahmedov in 2.3-develop branch
Related commit(s):
 - [a572ae2a1c5c86519ac3e0fd1eaf4d3157e80ef7](https://github.com/magento/magento2/commit/a572ae2a1c5c86519ac3e0fd1eaf4d3157e80ef7)
 - [6692e087dd2d5f2dcc4d16f35407ae6630ea5b2b](https://github.com/magento/magento2/commit/6692e087dd2d5f2dcc4d16f35407ae6630ea5b2b)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-16 13:28 UTC
Labels: Issue: Ready for Work, Component: ImportExport, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid
