### ISSUE TITLE
Adding to wishlist doesn't work when not logged in

### ISSUE THREAD

**Issue by mikelevy300** [magento/magento2#11908] opened 2017-10-31 14:47 UTC
### Preconditions

1. Apache 2.4
2. PHP 7.0.16
3. MySQL 5.7
4. Magento 2.1.9 w/ sample data installed

### Steps to reproduce

1. Make sure you're not logged in
2. Navigate to any category or product details page
3. Click the Add to Wishlist button

### Expected result

1. The user get's redirected to the login page
2. After logging in the user is redirected to the wishlist page where the item has been added to his or her wishlist

### Actual result

1. The user is redirected to the wishlist page, but the item has not been added to his or her wishlist

I traced it out and the form_key is failing validation in Magento\Wishlist\Controller\Index\Add.php after the user has been logged in.  It appears that the form_key is used during both the login controller call as well as the wishlist controller call.  The form_key passes validation just fine during the login controller call, but then fails when it reaches the wishlist controller.

**Comment by magento-engcom-team** [comment] 2017-10-31 15:01
@mikelevy300, thank you for your report.
This is duplicate of #11825

**Closed as completed** 2017-10-31 15:01 UTC
Labels: duplicate, Fixed in 2.1.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid

**Comment by okorshenko** [comment] 2017-12-01 18:54
The issue has been fixed and delivered to 2.2-develop branch. Will be available with upcoming patch release
