### ISSUE TITLE
getTotalNum() in /Magento/Catalog/Block/Product/ProductList/Toolbar.php causes slow catalog page and search load

### ISSUE THREAD

**Issue by mikew-westlund** [magento/magento2#36375] opened 2022-10-26 19:56 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- most discernable on categories with large collections and in catalog search
- my temporary solution is removing  
`<?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>` from 
`Magento/Catalog/view/frontend/templates/product/list/toolbar.phtml`

### Steps to reproduce

Do a search or open a category with a large collection.

### Expected result

uncached results in ~2 seconds

### Actual result

for a category with ~19000 products ~15-20 second load
for catalog search ~60 seconds

### Additional information

Magento_Catalog/templates/product/list/toolbar.phtml went from ~20 seconds on category page and ~60 seconds in catalog search to ~0.013 seconds after removing `<?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>` from `Magento/Catalog/view/frontend/templates/product/list/toolbar.phtml`

I've identified the culprit as the getTotalNum() method in /Magento/Catalog/Block/Product/ProductList/Toolbar.php

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-11-09 09:14
Hi @mikew-westlund ,
Thank you for reporting and collaboration. Verified the issue on Magento 2.4-develop instance and the issue is not reproducible.
Catalog search results page in both Admin and Front end loads immediately with no issues in an instance with 30k - 40k products.
![image](https://user-images.githubusercontent.com/60198231/200789003-c331b30c-272e-48f3-84c8-4082bba70628.png)
![image](https://user-images.githubusercontent.com/60198231/200789091-29bb7a52-765b-44b9-a4af-08cfa642cc78.png)
![image](https://user-images.githubusercontent.com/60198231/200789129-ad6e9c50-1e4c-4282-afc9-b9641647d4d6.png)
Kindly recheck the issue on Magento 2.4-develop instance and provide missing steps if any if the issue is still reproducible.
Thank you.

**Comment by timpea** [comment] 2022-11-09 10:43
@magento give me 2.4-develop instance

**Comment by timpea** [comment] 2022-11-09 11:10
@magento give me 2.4.5-p1 instance

**Comment by timpea** [comment] 2022-11-09 12:02
@engcom-November @mikew-westlund I have had the same issue with 2.4.5-p1 on our system, but I am unable to replicate.

The issue goes away on our website if I set "Display Out of Stock Products" to "No".

I am not sure what I am missing when trying to replicate.  I have tried importing 10,000 products to the 2.4.5-p1 instance, setting  "Display Out of Stock Products" to "Yes", then search on the front end.   For some reason this count only shows 175 and the search is reasonably fast.
![Screenshot 2022-11-09 at 11 52 50](https://user-images.githubusercontent.com/4026115/200823645-9b0db1df-2061-4686-a478-2678706014bc.png)

On our website with the live products, this count in 2.4.5-p1 always shows 5406 products. 
Search result with 39 results:
![Screenshot 2022-11-09 at 11 58 42](https://user-images.githubusercontent.com/4026115/200824830-6e3abe32-93bc-42f3-9464-0adc79b81dd3.png)
Search result with only 3 results:
![Screenshot 2022-11-09 at 11 59 01](https://user-images.githubusercontent.com/4026115/200824842-efdada43-c421-4811-8dd5-be5fd0bcf5e8.png)

**Comment by engcom-November** [comment] 2022-11-10 11:39
Hi @timpea ,
There is an ongoing confirmed issue: https://github.com/magento/magento2/issues/36404 - incorrect item count on search results page if display out of stock products is set to "Yes" which is a different issue. Kindly move on this [issue](https://github.com/magento/magento2/issues/36404) for latest updates / solutions on the same.
Thank you.

**Comment by engcom-November** [comment] 2022-11-23 11:46
Hi @mikew-westlund ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2022-11-23 11:46 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
