### ISSUE TITLE
After upgrading from magento 2.1.1 to magento 2.1.6 image resize error occurs

### ISSUE THREAD

**Issue by sasilinux** [magento/magento2#9698] opened 2017-05-19 10:02 UTC
### Preconditions

1.  Run the following command through putty. php bin/magento catalog:images:resize
2. 

### Steps to reproduce

1. After run the php bin/magento catalog:images:resize
2. Got the following error ...Notice: getimagesize(): Read error! in /var/www/html/vendor/magento/module-catalog/Model/Product/Image.php on line 452
3. 

### Expected result

1.  Images have to resize accordingly

### Actual result

1. Command catalog:images:resize throws an error.

**Comment by YPyltiai** [comment] 2017-05-19 11:57
Hello, @sasilinux,

Please see if this may help you: [Image Resize Issue with Magento version 2.1.6](http://devdocs.magento.com/guides/v2.1/release-notes/tech_bull_216-imageresize.html)

**Comment by bhargavmehta** [comment] 2017-05-20 09:06
To Apply the patch use command

git patch MAGETWO-67805.patch

**Comment by sasilinux** [comment] 2017-05-23 07:00
I am not using git. So please let me know how to update the mentioned patch in my magento 2.1.6

**Comment by heyepic** [comment] 2017-05-26 21:30
I also need help fixing this as I'm not using git.

That being said, I read this is still an issue even after the patch?

**Comment by mzeis** [comment] 2017-05-31 21:26
Magento just released 2.1.7 with a "reversion of the changes to image resizing that we introduced in 2.1.6": http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.7CE.html

Can you please check if the problem is gone in 2.1.7? Thanks!

**Comment by heyepic** [comment] 2017-05-31 22:09
Thanks for the heads up - we will give this a shot!

**Comment by veloraven** [comment] 2017-06-07 13:13
@sasilinux thank you for report.
Is this issue still actual after Magento 2.1.7 release?

**Comment by heyepic** [comment] 2017-06-07 13:16
The problem is resolved on latest!

**Comment by pboisvert** [comment] 2017-06-19 15:21
closing given issue is resolved by 2.1.7 release

**Closed as completed** 2017-06-19 15:21 UTC
Labels: Progress: needs update
