### ISSUE TITLE
Backend cart in customer detail view

### ISSUE THREAD

**Issue by bernd-reindl** [magento/magento2#26921] opened 2020-02-19 07:58 UTC
### Preconditions (*)

1. Magento 2.3.4
2. PHP 7.2.x
3. Multi website environment

### Steps to reproduce (*)

1. Setup a multi website environment
2. Set customer/account_share/scope to 0 (SHARE_GLOBAL)
3. create an customer on website > 1 (default frontend website)
4. Add something to the cart on website > 1
5. Now in the database should be an active cart for the store in website with id > 1 and no cart for the website with id 1 
6. Go to backend and open the customer account detail view
7. Go to tab "Shopping cart"

### Expected result (*)
1. See the carts for the different websites

### Actual result (*)

1. A cart with all quote items of all carts because $this->getWebsiteId() in Magento\Customer\Block\Adminhtml\Edit\Tab\Cart returns NULL and $storeIds contains only store_id 1 in getQuote. But there is no quote for store id 1 and so $this->_items->setQuote($this); in function getItemsCollection of Magento\Quote\Model\Quote has no effect because there is no ID in the quote model.

###Additional infos
I think this happens because on clicking the "Shopping Cart" button the controller Adminhtml/Index/Cart is called. But Adminhtml/Index/Carts handles the shared account config and create multiple grids with the correct website id.

![cart](https://user-images.githubusercontent.com/2369089/74813666-f8a13100-52f5-11ea-9e74-eac1ba53d046.jpg)

**Comment by bernd-reindl** [comment] 2020-02-19 07:58
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-02-19 07:59
Hi @bernd-reindl. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-02-19 07:59
Hi @bernd-reindl, here is your [Magento instance](https://i-26921-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26921-2-4-develop.instances.magento-community.engineering/admin_f5f1](https://i-26921-2-4-develop.instances.magento-community.engineering/admin_f5f1)
Login: `71b4736a` Password: `89854edda769`
Instance will be terminated in up to 3 hours.

**Comment by bernd-reindl** [comment] 2020-02-19 08:24
Additionaly if a customer has products in his quote with store_id > 1 this cart is not shown in backend.

See Customer 2 in instance  https://i-26921-2-4-develop.instances.magento-community.engineering/admin_f5f1. This customer has products in quote with store_id 2. But the shopping cart Tab shows only an empty cart.


![cart](https://user-images.githubusercontent.com/2369089/74815485-9d713d80-52f9-11ea-81ec-ab347fc440f1.jpg)

![order](https://user-images.githubusercontent.com/2369089/74815495-a2ce8800-52f9-11ea-8fb8-831fa4b09297.jpg)

**Comment by jhruehl** [comment] 2020-02-19 09:28
Already argued with the Enterprise support about it. Debugging clearly shows it cannot work for a multiwebsite/store setup with shared customers.

Only one active cart could be handled by the code, but it actually tries to load the quote for store id 0, for which no active quote exists, so in the aftermath getAllItems() is called on an unfiltered quote object and returns all quote items given in the database.

**Comment by bernd-reindl** [comment] 2020-02-20 10:17
I have solved it by three modifications.

1. Edit Magento\Sales\Block\Adminhtml\ShoppingCartsTab -> getTabUrl()

`return $this->getUrl('customer/*/carts', ['_current' => true]);`
not 
`return $this->getUrl('customer/*/cart', ['_current' => true]);`

customer/*/cart(s) handle all store_ids

I also think that ShoppingCartsTab should be part of module-quote not module-sales.

2. Magento\Customer\Block\Adminhtml\Edit\Tab\Cart -> getQuote()

`$this->quote = $this->quoteFactory->create()->setId(-1)->setSharedStoreIds($storeIds);`
not 
`$this->quote = $this->quoteFactory->create()->setSharedStoreIds($storeIds);`

If getId() return null, $quote->getItemsCollection(false) returns a collection with no quote filter and all QuoteItems are shown. See _prepareCollection()

The if block in _prepareCollection() is not required, because $this->getQuote() allways return a qoute.

3. Magento\Quote\Model\QuoteRepository -> getForCustomer()

If the cache key is only the customerId, and the function was called with diferent sharedStoreIds, always the quote with the first requested  storeIds is returned.
So the cache key has to contain the sharedStoreIds.

E.G.
```
$cacheKey = $customerId.'-'.implode('-', $sharedStoreIds);
if (!isset($this->quotesByCustomerId[$cacheKey])) {
    $quote = $this->loadQuote('loadByCustomer', 'customerId', $customerId, $sharedStoreIds);
    $this->getLoadHandler()->load($quote);
    $this->quotesById[$quote->getId()] = $quote;
    $this->quotesByCustomerId[$cacheKey] = $quote;
}
return $this->quotesByCustomerId[$cacheKey];
```

**Comment by GuiltyNL** [comment] 2020-02-20 16:07
I can confirm we are having this issue too. On Magento 2.3.3 Multi Website / Multi Storeview

**Comment by engcom-Bravo** [comment] 2020-03-04 16:10
Hello @bernd-reindl 

Thank you for your report 

I have rechecked this issue on 2.4-develop, and I'm getting the same result you've mentioned in this [screenshot](https://user-images.githubusercontent.com/2369089/74815485-9d713d80-52f9-11ea-81ec-ab347fc440f1.jpg), no cart at all.
This looks like another issue. But what about the initial one? If I understood your comment correctly, you were not able to reproduce the initial issue on 2.4-develop, is that correct?

Thank you in advance

**Comment by magento-engcom-team** [comment] 2020-03-05 07:06
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-32168` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by hardikason** [comment] 2020-10-27 15:25
I have also faced same issue. But most easy and quick solution is as below :

**Comment by engcom-Bravo** [comment] 2024-05-16 06:55
Hi @bernd-reindl,

Thanks for your reporting and collaboration.

verified the issue in Latest 2.4-develop instance and the issue is no more reproducible.Kindly refer the screenshots.


**Steps to reproduce**

- Setup a multi website environment
- Set customer/account_share/scope to 0 (SHARE_GLOBAL)
- create an customer on website > 1 (default frontend website)
- Add something to the cart on website > 1
- Now in the database should be an active cart for the store in website with id > 1 and no cart for the website with id 1
- Go to backend and open the customer account detail view
- Go to tab "Shopping cart"


<img width="1435" alt="Screenshot 2024-05-16 at 12 19 22" src="https://github.com/magento/magento2/assets/51680745/0b083611-cc3c-4f1c-9a66-788444359f88">



<img width="1347" alt="Screenshot 2024-05-16 at 12 19 35" src="https://github.com/magento/magento2/assets/51680745/dfc81735-8cb8-4ad8-bb26-818e373bbd19">



<img width="1347" alt="Screenshot 2024-05-16 at 12 20 11" src="https://github.com/magento/magento2/assets/51680745/6a2dcd24-e242-4ab0-b503-ff3257102e70">



Hence We are Closing this issue.

Thanks.

**Closed as completed by engcom-Bravo** 2024-05-16 06:55 UTC
Labels: Component: Customer, Issue: Confirmed, Reproduced on 2.4.x, Priority: P3, Progress: done, Reported on 2.3.4
