### ISSUE TITLE
Adding out of stock items to wishlist shows success message but fails

### ISSUE THREAD

**Issue by netjordanlee** [magento/magento2#21519] opened 2019-02-28 23:03 UTC
### Preconditions (*)
1. Magento 2.3.0

### Steps to reproduce (*)
1. Navigate to an out of stock product page
2. Add product to wishlist

### Expected result (*)
1. Product should be added to wishlist (ideal)
or
2. Message should reflect that out of stock items can not be added to wishlist

### Actual result (*)
1. Success message is shown that item was added to wishlist
2. Item is not added to wishlist

Related to #21518

**Comment by magento-engcom-team** [comment] 2019-02-28 23:04
Hi @netjordanlee. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@netjordanlee do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-03-01 04:40
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-03-01 04:41
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 04:41
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 04:42
Hi @krishprakash, here is your [Magento instance](https://i-21519-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21519-2-3-develop.instances.magento-community.engineering/admin](https://i-21519-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-03-01 05:03
![wishlist](https://user-images.githubusercontent.com/46617848/53617493-621fbf80-3c0d-11e9-8c48-8a29e1796137.png)

**Comment by magento-engcom-team** [comment] 2019-03-01 06:26
Hi @ravi-chandra3197. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-03-01 15:54
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 15:54
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 15:55
Hi @shikhamis11, here is your [Magento instance](https://i-21519-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21519-2-3-develop.instances.magento-community.engineering/admin](https://i-21519-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by shikhamis11** [comment] 2019-03-01 16:08
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-01 16:08
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-01 16:09
Hi @shikhamis11, here is your [Magento instance](https://i-21519-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21519-2-2-develop.instances.magento-community.engineering/admin](https://i-21519-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-03-01 16:15
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98515`, `MAGETWO-98516` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by amol2jcommerce** [comment] 2019-03-04 08:37
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-03-04 08:37
Hi @amol2jcommerce. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-03-04 08:37
Hi @amol2jcommerce, here is your [Magento instance](https://i-21519-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21519-2-3-develop.instances.magento-community.engineering/admin](https://i-21519-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Januszpl** [comment] 2019-03-21 15:29
As far as I've checked it's is added to wishlist_item table but it isn't returned in template by $block->getItems(). Leaving it to some backend developer.

**Comment by vijaydckap** [comment] 2019-05-04 05:17
I am working on this at #dmcdindia1

**Comment by magento-engcom-team** [comment] 2019-05-04 05:18
@vijaydckap thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by magento-engcom-team** [comment] 2019-09-20 00:33
Hi @netjordanlee. Thank you for your report. 
The issue has been fixed in magento/magento2#24300 by @Rus0 in 2.3-develop branch
Related commit(s):
 - [8048c09d7f37460c8dda1938fde85a2e36bce49b](https://github.com/magento/magento2/commit/8048c09d7f37460c8dda1938fde85a2e36bce49b)
 - [8f491d3dcc905b12b08b5327999ce51e658a34ac](https://github.com/magento/magento2/commit/8f491d3dcc905b12b08b5327999ce51e658a34ac)
 - [91f8f886b47578956a6059c8b4273e5800fc213c](https://github.com/magento/magento2/commit/91f8f886b47578956a6059c8b4273e5800fc213c)
 - [6753604a30cb29fcc1772bc90e639e0a2f459c3c](https://github.com/magento/magento2/commit/6753604a30cb29fcc1772bc90e639e0a2f459c3c)
 - [71d1ebc5d9287f885f07ca75060d86a4a03f678a](https://github.com/magento/magento2/commit/71d1ebc5d9287f885f07ca75060d86a4a03f678a)
 - [9a1b78154950da21073ee762ccd43e3e789766c5](https://github.com/magento/magento2/commit/9a1b78154950da21073ee762ccd43e3e789766c5)
 - [964105c807e31449f41cdaba8fd79068d2daa694](https://github.com/magento/magento2/commit/964105c807e31449f41cdaba8fd79068d2daa694)

The fix will be available with the upcoming 2.3.4 release.

**Closed as completed by magento-engcom-team** 2019-09-20 00:33 UTC
Labels: Issue: Ready for Work, Component: Customer, Area: Frontend, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Wishlist, Event: dmcdindia1

**Comment by rameshrajankk** [comment] 2021-06-26 19:50
I have upgraded to 2.3.3 to 2.3.4 but still, I'm having this issue.

**Comment by vkadkol** [comment] 2021-12-10 10:10
I have fixed this issue on my magento application. Please refer the link for detailed description 
https://stackoverflow.com/a/70302695/1468900
