### ISSUE TITLE
Non English characters in product URL Key are ignored.

### ISSUE THREAD

**Issue by adzminz** [magento/magento2#1139] opened 2015-03-27 15:18 UTC
[Input]
![issue1](https://cloud.githubusercontent.com/assets/11070293/6870260/6f81054a-d4cd-11e4-9a33-de28d38d2fc6.PNG)

Click save button then switch to another tab and switch back to "Search Engine Optimization".

![issue2](https://cloud.githubusercontent.com/assets/11070293/6870443/a713511a-d4ce-11e4-8f29-5578f2ed7e64.PNG)

![issue3](https://cloud.githubusercontent.com/assets/11070293/6870494/08535c7c-d4cf-11e4-95a0-535c705ccc73.png)

**Comment by kokoc** [comment] 2015-03-31 08:57
@adzminz Thank you for reporting the issue! We will get back to you once we complete the analysis.

**Comment by kandy** [comment] 2015-03-31 09:52
What the 'url key' do you expect to get? Can you provide some example 'Product Name' -> 'url key'?

**Comment by adzminz** [comment] 2015-03-31 10:21
Product Name: สินค้าตัวอย่าง
Input URL Key: สินค้าตัวอย่าง-1

Expected URL Key to be saved: สินค้าตัวอย่าง-1
Expected product URL: สินค้าตัวอย่าง-1.html

**Comment by sIiiS** [comment] 2015-03-31 10:51
I think these are same!
https://github.com/magento/magento2/issues/653

**Comment by adzminz** [comment] 2015-03-31 10:57
@sIiiS Exactly!!

**Comment by joanhe** [comment] 2015-03-31 17:17
@adzminz Would you mind close this issue, since this is duplicate of #653?

**Comment by adzminz** [comment] 2015-04-01 02:25
@joanhe Sure, no problem.

**Comment by joanhe** [comment] 2015-04-01 13:48
This is duplicate of #653. Closing it.

**Closed** 2015-04-01 13:48 UTC
Labels: bug, MX
