### ISSUE TITLE
 Image gets uploaded if field is disable in Category

### ISSUE THREAD

**Issue by mohammadzakir** [magento/magento2#20376] opened 2019-01-17 14:16 UTC
### Preconditions (*)

1. Magento 2.3.0 
2. Php Version 7.2

### Steps to reproduce (*)

1. Login to admin panel
2. Goto Catalog present on left
3. Then goto Categories
4. Select Dafault category
5. Change Store View to Default Store view
6. Now click to content tab
7. then click Browse to find or drag image here, it will not work untill we don't remove the tick from the Use Default Value
8. But when we simply drags a image on it, then image gets added successfully.

### Expected result (*)

1. Images should not be added unless there is a tick on Use Default Value 

### Actual result (*)

1. Images can be uploaded using drag option although there is tick on Default Value

![category](https://user-images.githubusercontent.com/43291220/51324334-727e3f80-1a90-11e9-8cc8-15ff44826d97.png)

**Comment by magento-engcom-team** [comment] 2019-01-17 14:16
Hi @mohammadzakir. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@mohammadzakir do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-01-17 14:16
Hi @GovindaSharma. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [x] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [x] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [x] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by GovindaSharma** [comment] 2019-01-17 14:17
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-17 14:17
Hi @GovindaSharma. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-17 14:17
Hi @GovindaSharma, here is your [Magento instance](https://i-20376-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20376-2-3-develop.instances.magento-community.engineering/admin](https://i-20376-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-17 14:19
@GovindaSharma Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-97694` were created

**Comment by magento-engcom-team** [comment] 2019-01-17 15:53
Hi @saphaljha. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by magento-engcom-team** [comment] 2019-01-21 19:10
Hi @maheshWebkul721. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by rogyar** [comment] 2019-01-23 10:44
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-23 10:44
Hi @rogyar. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-23 10:45
Hi @rogyar, here is your [Magento instance](https://i-20376-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-20376-2-3-develop.instances.magento-community.engineering/admin](https://i-20376-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-26 15:41
Hi @serhiyzhovnir. Thank you for working on this issue. 
Looks like this issue is already verified and confirmed. But if your want to validate it one more time, please, go though the following instruction:
- [ ] 1. Add/Edit `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.

- [ ] 2. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [x] 3. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 4. If the issue is not relevant or is not reproducible any more, feel free to close it.

**Comment by serhiyzhovnir** [comment] 2019-01-26 15:42
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-01-26 15:42
Hi @serhiyzhovnir. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-01-26 15:43
Hi @serhiyzhovnir, here is your [Magento instance](https://i-20376-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-20376-2-2-develop.instances.magento-community.engineering/admin](https://i-20376-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-01-29 16:50
Hi @mohammadzakir. Thank you for your report. 
The issue has been fixed in magento/magento2#20636 by @serhiyzhovnir in 2.2-develop branch
Related commit(s):
 - [b9390c9f3a5d9be797a460a0e4d09d9932d70910](https://github.com/magento/magento2/commit/b9390c9f3a5d9be797a460a0e4d09d9932d70910)
 - [0b24b39b12e34dfc7ac60746caf420abbd3c2b76](https://github.com/magento/magento2/commit/0b24b39b12e34dfc7ac60746caf420abbd3c2b76)

The fix will be available with the upcoming 2.2.8 release.

**Closed as completed by magento-engcom-team** 2019-01-29 16:50 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created

**Comment by magento-engcom-team** [comment] 2019-02-13 15:45
Hi @mohammadzakir. Thank you for your report. 
The issue has been fixed in magento/magento2#20461 by @serhiyzhovnir in 2.3-develop branch
Related commit(s):
 - [dd9e8cf217b78baf12da5120fdfc76d869043bfa](https://github.com/magento/magento2/commit/dd9e8cf217b78baf12da5120fdfc76d869043bfa)
 - [85c4e92c8e2f60a71ab3745ef3056deb6a4d795e](https://github.com/magento/magento2/commit/85c4e92c8e2f60a71ab3745ef3056deb6a4d795e)
 - [d91d0ed3c9d59a412b7131cec8e3601cd87b2fb1](https://github.com/magento/magento2/commit/d91d0ed3c9d59a412b7131cec8e3601cd87b2fb1)
 - [3671bbe7ac374e9bdb7c1957479a06369d0f0952](https://github.com/magento/magento2/commit/3671bbe7ac374e9bdb7c1957479a06369d0f0952)
 - [b0363af805c5624dfc6be6cdb8ecdf1e478a1f6b](https://github.com/magento/magento2/commit/b0363af805c5624dfc6be6cdb8ecdf1e478a1f6b)

The fix will be available with the upcoming  release.
