### ISSUE TITLE
Infinite loop detected, review the trace for the looping path - Magento 2.3.4 Payment Method

### ISSUE THREAD

**Issue by andrew-boehm** [magento/magento2#26799] opened 2020-02-10 19:16 UTC
### Preconditions (*)

1. 2.3.4
2. checkout

### Steps to reproduce (*)

1. Click Place Order button or Continue to Paypal button

### Expected result (*)

1. Checkout successfully

### Actual result (*)

1. http://prntscr.com/r0cxc5

**Comment by SamJUK** [comment] 2020-02-11 09:01
This is a duplicate of the following issues #26774 and #26786 Both those issues had issues with a 3rd party stripe module.

I had an issue with Miravist's GiftRegistry module which was caused by a custom `Magento\Authorization\Model\CompositeUserContext` context they added

**Comment by wolfautoparts** [comment] 2020-02-11 15:52
Mirasvit Rewards module causing this issue for me.

**Comment by engcom-Alfa** [comment] 2020-02-12 08:03
Hi @andrew-boehm. Thank you for your report.
Unfortunately, we are not able to reproduce this issue on fresh 2.4-develop and 2.3.4 version.
So, we have to close it.
This question seems to be connected with a 3rd party stripe module.
Please review issue #26774

**Closed as completed by engcom-Alfa** 2020-02-12 08:03 UTC
Labels: Issue: Format is valid, Reported on 2.3.4

**Comment by andrew-boehm** [comment] 2020-02-12 08:06
So you are saying it’s the stripe integrations

And

Not your exstention?


But is the stripe code inside your exstention?

**Comment by andrew-boehm** [comment] 2020-02-12 08:34
There was an issue on one of extension.
Thanks,

**Comment by nazimwibsoft** [comment] 2020-02-12 10:18
The issue was with the Stripe Payment Integration extension, after updating that to latest 1.5.2 resolved the issue for me. Thanks.

We can install the latest version from here: https://stripe.com/docs/plugins/magento/install

**Comment by rahulthakral38** [comment] 2020-06-10 07:06
**Infinite loop detected, review the trace for the looping path in Payment gateways on checkout.**

![magento-payment-checkout](https://user-images.githubusercontent.com/17290393/84237387-e6ead000-ab16-11ea-80d2-bcf4e0985cce.png)

**Any solution for this, any patch released..??**

**Comment by roshanyadav89** [comment] 2020-09-23 11:32
Any solution for the same I am facing the same issue after m2.3.3 upgrade 2.3.5 EE
