### ISSUE TITLE
Product attribute type "Media Image" is not working

### ISSUE THREAD

**Issue by wenpingguo** [magento/magento2#7601] opened 2016-11-29 04:04 UTC
### Preconditions

1. Fresh installed Magento 2.1.2 CE

### Steps to reproduce

1. Create a new product attribute with type "Media Image"
![p1](https://cloud.githubusercontent.com/assets/19483820/20696058/f730cbce-b644-11e6-8e2d-296832736642.png)

2. Assign the newly created attribute to an attribute set e.g. "Top" and save
![p2](https://cloud.githubusercontent.com/assets/19483820/20696062/fbbfdedc-b644-11e6-9d58-1dd7f24d4b41.png)

3. Check a product belongs to "Top" attribute set

### Expected result

1. You can see the newly created attribute which allow you to upload images

### Actual result

You cannot see the newly created attribute
![p3](https://cloud.githubusercontent.com/assets/19483820/20696057/efcfd6c2-b644-11e6-99cd-dc34e062c5bc.png)

**Comment by slopukhov** [comment] 2016-11-29 08:40
@wenpingguo thank you for your feedback.
Internal issue created: MAGETWO-61545

**Comment by jellyfyi** [comment] 2017-01-30 02:11
Any fix for this yet?

**Comment by veloraven** [comment] 2017-06-20 07:53
I'm closing this issue as internal ticket was closed as not a bug:
> Media Image is not a file uploader, it provides an additional Role for product image.

**Closed as completed by veloraven** 2017-06-20 07:53 UTC
Labels: Issue: Ready for Work, bug report, Component: Catalog
