### ISSUE TITLE
On Invoice: Address and City on Same Line

### ISSUE THREAD

**Issue by thebreakfastcowboy** [magento/magento2#12911] opened 2017-12-28 16:04 UTC
### Preconditions
Magento 2.1.10

### Steps to reproduce
Create a PDF invoice

### Expected result
City and Address on different line, to easily distinguish between them

### Actual result
City and Address on same line. 

An example of the issue with this default invoice behavior: if a city begins with a cardinal direction, it's unclear if it's part of the street name (e.g. Test Ave. North, Testville vs. Test Ave., North Testville -- assuming these are both valid addresses)

**Comment by magento-engcom-team** [comment] 2017-12-29 14:07
@thebreakfastcowboy , thank you for your report.
We are not able to reproduce this problem by the steps which you provided.
Please, provide more additional information and screenshots.
Here is what we got while trying to reproduce this problem.
You can see that city and address placed on different lines.

![front](https://user-images.githubusercontent.com/31669971/34438750-a37c2074-ecb1-11e7-8d58-be2ab780ada8.png)
![pdf](https://user-images.githubusercontent.com/31669971/34438751-a394ff22-ecb1-11e7-8720-1a212ce7f989.png)

Please try to reproduce the issue with a clean instance of Magento or clarify some steps in order for us to reproduce the issue. Screenshots would be helpful too. Thank you

**Comment by thebreakfastcowboy** [comment] 2017-12-29 19:30
Hmm, thanks for looking into this.

Here's the order information (incomplete for privacy concerns):

![screen shot 2017-12-29 at 2 28 04 pm](https://user-images.githubusercontent.com/16323972/34445865-9cccb1a6-eca4-11e7-8dfc-bf34c6849e21.png)

And here's it on the invoice:

![screen shot 2017-12-29 at 2 27 02 pm](https://user-images.githubusercontent.com/16323972/34445874-a9f612c8-eca4-11e7-877d-18f96ad2d619.png)

This is on a store that conservatively extends the blank theme, though there are some extensions running.

**Comment by magento-engcom-team** [comment] 2018-01-02 09:48
@thebreakfastcowboy Thanks for clarifying. We tried with a clean instance of Magento using the blank theme, and we were not able to reproduce the issue. Please try to reproduce it on the clean instance of Magento without 3'rd party extensions. Thank you.

**Comment by magento-engcom-team** [comment] 2018-01-02 11:22
@thebreakfastcowboy, thank you for your report.
The issue is already fixed in 2.2.2

**Closed as completed by magento-engcom-team** 2018-01-02 11:22 UTC
Labels: Progress: needs update, Issue: Clear Description, Issue: Confirmed, Fixed in 2.2.x, Issue: Format is valid
