### ISSUE TITLE
Email fail - Invalid header value detected

### ISSUE THREAD

**Issue by rafaelstz** [magento/magento2#25542] opened 2019-11-09 15:00 UTC
### Preconditions (*)

1. Magento 2.3.3
2. Change the Sender Name using punctuation.

<img width="1309" alt="Screen Shot 2019-11-09 at 11 56 09 AM" src="https://user-images.githubusercontent.com/610598/68530564-fe937900-02e7-11ea-95f4-83a816cd22a8.png">

### Steps to reproduce (*)

1. You can access the contact form and fill the name using punctuation like **Rafael Corrêa**
2. Or changing the Sender Name using punctuation.

### Expected result (*)

1. Send the email

### Actual result (*)

1. Receive the error message below.

> Invalid header value detected

<img width="619" alt="Screen Shot 2019-11-09 at 12 00 14 PM" src="https://user-images.githubusercontent.com/610598/68530612-824d6580-02e8-11ea-8737-45d0ef1ecfd3.png">

**Comment by rafaelstz** [comment] 2019-11-10 15:33
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-10 15:33
Hi @rafaelstz. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-10 15:34
Hi @rafaelstz, here is your [Magento instance](https://i-25542-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25542-2-3-develop.instances.magento-community.engineering/admin](https://i-25542-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by andrewbess** [comment] 2019-11-11 07:05
Hello @rafaelstz 
Magento uses "zendframework/zend-mail" to send emails.
This module validates headers according to RFC 2822.
Please take a look at [this document](https://www.rfc-editor.org/rfc/rfc2822.txt) (section 2.2).
As you can see, your sender name has the symbol "á" with code 195.
So, I think this task can be closed.
@magento-engcom-team how do you think about it?

**Comment by rafaelstz** [comment] 2019-11-12 15:13
Hi @andrewbess,
But Magento's core requires the version, the Magento 2.3.2 doesn't have this issue.

**Comment by davidverholen** [comment] 2019-11-19 12:33
the same happens for order mails if the customer name contains non ascii characters. So this issue is valid and even pretty critical

**Comment by magento-engcom-team** [comment] 2019-11-19 12:34
:white_check_mark: Confirmed by @davidverholen 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-28945` were created

**Issue Available**: @davidverholen, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by david-fuehr** [comment] 2019-11-21 12:46
This issue is a duplicate of https://github.com/magento/magento2/issues/24902 and already fixed in MR https://github.com/magento/magento2/pull/24906

**Closed as completed by david-fuehr** 2019-11-21 12:46 UTC
Labels: Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Component: Mail

**Comment by vipin12117** [comment] 2020-03-17 12:47
It did not fixed in 2.3.4

**Comment by hanhpv** [comment] 2020-03-18 10:08
still happens on EE 2.3.3
If customer name contains special characters like this Rafael Corrêa. The email failed to send.

**Comment by rafaelstz** [comment] 2020-06-08 21:32
This solution worked for me 🎉 !
In the EmailMessage class `vendor/magento/framework/Mail/EmailMessage.php` the encoding can be set if passed in an argument in the constructor, but it is **null by default**.

```php
if ($encoding) {
   $this->message->setEncoding($encoding);
}
```

So, I think the best practice use type in di.xml in your module without rewrite and plugins.

```xml
<type name="Magento\Framework\Mail\EmailMessage">
   <arguments>
       <argument name="encoding" xsi:type="string">utf-8</argument>
   </arguments>
</type>
```
Reference: https://magento.stackexchange.com/a/306638/16416

**Comment by abdulrafay-systemsltd** [comment] 2021-07-08 15:05
I am facing this issue in Magento EE ver. 2.3.2 
Invalid header value detected {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Invalid header value detected at /vendor/magento/module-email/Model/Transport.php:101,
