### ISSUE TITLE
When category URL page param is larger than the pagination, the page will break with elastic search 2

### ISSUE THREAD

**Issue by ron-jomashop** [magento/magento2#23843] opened 2019-07-23 18:00 UTC
### Preconditions (*)
1. Magento 2.3.2
1. Elasticsearch 2

### Steps to reproduce (*)
1. Create a category with products
1. Enable elasticsearch 2
1. Reindex all
1. Go to the category and add this params: "?p=999999999999999&product*list_order=price". Ex: https://www.example.com/category?p=9999999999999999999999999999&product_list*order=price

### Expected result (*)
1. Go to the last page of the category

### Actual result (*)
1. {{1 exception(s):
Exception #0 (Elasticsearch\Common\Exceptions\ServerErrorResponseException): {"error":{"root*cause":<{"type":"json_parse_exception","reason":"Numeric value (2.3058430092137e<ins>20) out of range of int (-2147483648 - 2147483647)\n at [Source: [B@33145eaa; line: 1, column: 28]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_product_1_v173","node":"viwpe1vCTrGQomOe0uHakA","reason":{"type":"json_parse*exception","reason":"Numeric value (2.3058430092137e</ins>20) out of range of int (-2147483648 - 2147483647)\n at [Source: [B@33145eaa; line: 1, column: 28]"}}>},"status":500}}}

**Comment by ron-jomashop** [comment] 2019-07-23 18:04
I cannot test with the Magento instance because this ticket related to the elasticsearch.

**Comment by engcom-Charlie** [comment] 2019-07-24 08:54
Hi, @ron-jomashop ! I'm sorry, but i have to close this issue, because i can't reproduce it on 2.3-develop and 2.3.2 branches(have not any exception after adding this params: "?p=999999999999999&product_list_order=price").
Thank for contributing!

**Comment by ron-jomashop** [comment] 2019-07-24 14:13
@engcom-Charlie
Please have a look again. I have tested with Magento repo with Magento sample data and it also has the error.
The page you need to go to is http://127.0.0.1/training/training-video.html?p=999999999999999
and it should produce the error with the Elasticsearch 2 enabled.

**Comment by engcom-Charlie** [comment] 2019-07-24 14:42
@ron-jomashop , that is right! I'm sorry about closing this issue. 
Thank you for contributing!

**Comment by magento-engcom-team** [comment] 2019-07-24 14:43
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18549` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by victorpetryk** [comment] 2020-12-04 14:54
@magento I am working an this

**Comment by victorpetryk** [comment] 2020-12-04 14:55
@magento I am working on this

**Closed as completed** 2021-01-13 20:25 UTC
Labels: Issue: Confirmed, Reproduced on 2.3.x, Component: Elasticsearch, Priority: P2, Severity: S1, Progress: done
