### ISSUE TITLE
Refactoring: Adding items to the Sitemap

### ISSUE THREAD

**Issue by avoelkl** [magento/magento2#10045] opened 2017-06-25 14:23 UTC
PR #9970 was already an improvement to the sitemap for easier adding of additional items.

@antonkril suggested to refactor the improved behaviour even more:

### Expected result
> Better approach in this case would be to introduce the reversed extension point: some kind of $ItemResolver dependency that would be called by sitemap (with sitemap id argument) to load custom sitemap items.
> 
> This dependency could be implemented as a composite, or just pluginized by third-party developers to add new items to the custom list.

**Comment by piotrkwiecinski** [comment] 2017-07-14 08:11
Here is my proposal:

```
interface SitemapItemResolverInterface {
    /**
      * @return SitemapItemInterface[]
      */
    public function getItems();
}
```
To create ```CmsPageSitemapItemResolver```,```CategorySitemapItemResolver```,```ProductSitemapItemResolver``` as implementation of above. In addition create ```CompositeSitemapItemResolver``` with constructor parameter ```SitemapItemResolverInterface $itemResolvers = [] ```

DI preference for ```SitemapItemResolverInterface``` would be ```CompositeSitemapItemResolver```

```
interface SitemapItemInterface {
    public function getUrl();

    public function getPriority();

    public function getChangeFrequency();

    public function getImages();

    public function getUpdatedAt();
}
```

As method ```addSitemapItem()``` was added only to develop and item resolvers are more flexible solution I would prefer to remove it.

I'm happy to work on it.

**Comment by vrann** [comment] 2017-07-14 14:00
@piotrekkaminski proposal looks good, go for it!

**Comment by avoelkl** [comment] 2017-07-18 08:50
@piotrkwiecinski see last message :) guess the wrong piotr was notified :)

**Comment by antonkril** [comment] 2017-07-21 17:58
"Resolver" is not the best name here. "List" or "Provider" would be a better fit.

**Comment by magento-team** [comment] 2017-08-01 15:24
Internal ticket to track issue progress: MAGETWO-70872

**Comment by piotrkwiecinski** [comment] 2017-08-04 18:47
@antonkril I haven't noticed your comment. I could provide additional PR as a follow up to change resolver to provider. WDYT @vrann?

**Comment by magento-team** [comment] 2017-08-05 01:02
Internal ticket to track issue progress: MAGETWO-71372

**Comment by magento-engcom-team** [comment] 2017-09-20 22:56
@avoelkl, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2017-09-20 22:58
@avoelkl, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2017-09-20 23:02
@avoelkl, thank you for your report.
The issue is already fixed in develop branch
But we will consider to backport the fix to patch releases

**Comment by magento-engcom-team** [comment] 2017-10-06 20:51
Hi @avoelkl 
Can we close this issue or there are some tasks TODO?

**Comment by avoelkl** [comment] 2017-10-09 06:20
Hi @magento-engcom-team, sorry I missed the notification. This issue can be closed.

**Closed as completed** 2017-10-11 11:41 UTC
Labels: Issue: Ready for Work, up for grabs, Reproduced on 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
