### ISSUE TITLE
Order status not selected while search in order report

### ISSUE THREAD

**Issue by niranjan-gondaliya** [magento/magento2#36746] opened 2023-01-16 12:11 UTC
### Preconditions and environment

- Magento version 2.4.5-p1
- PHP 8.1

### Steps to reproduce

1. Go to admin panel 
2. Report >> Sales >> Orders 
3. Select required filed and **Order Status** => Specified
4. Select multiple order status 
5. Click on **Show Report**

### Expected result

All selected order status selected in multi select options.

https://nimb.ws/Qqj9uV

### Actual result

Only one option is selected.

https://nimb.ws/reX9ML

### Additional information

**Magento 2.4.5-p1**

- I have debug issue in local with magento 2.4.5-p1 in URL string is pass like 

`report_type=created_at_order&period_type=day&from=01%2F1%2F2023&to=01%2F31%2F2023&show_order_statuses=1&order_statuses%5B%5D=canceled&order_statuses%5B%5D=closed&order_statuses%5B%5D=complete&order_statuses%5B%5D=fraud&order_statuses%5B%5D=holded&show_empty_rows=0&show_actual_columns=0`

- `order_statuses` parameter is pass multiple time based on selected order status.

**Magento 2.4.2-p1**

- In magento 2.4.2-p1 URL string pass like
 
`report_type=created_at_order&period_type=day&from=01%2F1%2F2023&to=01%2F31%2F2023&show_order_statuses=1&order_statuses%5B%5D=canceled%2closed%2complete%2fraud&order_statuses%5B%5D=holded&show_empty_rows=0&show_actual_columns=0`

- All order status pass in only one paramater `order_statuses`  
 

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2023-01-17 08:30
@magento give me 2.4-develop instance

**Comment by maghamed** [comment] 2023-01-17 14:34
@magento  give me 2.4-develop instance

**Comment by maghamed** [comment] 2023-01-17 18:26
@magento give me 2.4-develop instance

**Comment by niranjan-gondaliya** [comment] 2023-01-18 08:24
Hello @engcom-Bravo , @maghamed,

In my local, I have install Magento 2.4.5-p1 and PHP 8.1, OS Linux Ubuntu, Issue is generated.

If you want than i can provide you video.

**Comment by engcom-Bravo** [comment] 2023-01-18 12:08
Hi @niranjan-gondaliya,

Thanks for your update.

We have verified the issue in both 2.4 develop and 2.4.5-p1 instances we are not able to reproduce the issue in both the instances. Kindly refer the screenshots.

 In Magento 2.4.5-p1 Instance We are able to select multi options.


<img width="1482" alt="Screenshot 2023-01-18 at 2 09 12 PM" src="https://user-images.githubusercontent.com/51680745/213167490-5f46164c-a793-48e4-8e9b-51b78c98e3f4.png">



it is recommended to verify the issue on Magento 2.4-develop instance as it is an upcoming 2.4.x release and have latest code base.




Kindly recheck the issue on Magento 2.4-develop instance and check if any 3rd party extensions / modules enabled is causing this issue.



Thanks.

**Comment by manuel-EGO** [comment] 2023-01-25 13:20
We have this issue as well, its not about no being able to select multiple statuses but about the report only using one of them:
Selection: (before clicking Show Report)
<img width="641" alt="result" src="https://user-images.githubusercontent.com/74413969/214573688-eb2bfd01-1b6d-4250-82ea-b857fc8690b8.png">

Result: (after clicking Show Report and receiving daa)
<img width="646" alt="selection" src="https://user-images.githubusercontent.com/74413969/214573693-c9f1f97a-1e94-4213-acfb-00048a88834c.png">

Also note that the data provided correlates with (in our case) complete orders only (missing processing ones)

**Comment by manuel-EGO** [comment] 2023-01-25 13:47
Diving into this, looks like the encoded filter value is sent incorrectly to the backend:
<img width="274" alt="Screenshot 2023-01-25 at 13 47 10" src="https://user-images.githubusercontent.com/74413969/214579975-e33f31a1-2648-4b77-a7e7-fbc7d03889f3.png">

**Comment by engcom-Bravo** [comment] 2023-01-27 07:22
@magento give me 2.4-develop instance

**Comment by engcom-Bravo** [comment] 2023-01-27 10:34
Hi @manuel-EGO,

Verified the issue on Magento 2.4-develop instance and the issue is not reproducible. Kindly refer the screenhsots.


Selection: (before clicking Show Report)


<img width="931" alt="Screenshot 2023-01-27 at 1 25 05 PM" src="https://user-images.githubusercontent.com/51680745/215065545-aad2f68d-83aa-4802-bd80-d986370a4e71.png">



Result: We are getting data for both completed and processing orders.


![Orders-Report-Sales-Reports-Magento-Admin](https://user-images.githubusercontent.com/51680745/215065698-2587418c-fedf-487d-b676-92ece7aa2e34.png)



Kindly recheck the behavior on Magento 2.4-develop instance and elaborate steps to reproduce if the issue is still reproducible.


Thanks.

**Comment by engcom-Bravo** [comment] 2023-02-08 06:07
Hi @niranjan-gondaliya,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks.

**Closed as completed by engcom-Bravo** 2023-02-08 06:07 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.5-p1
