### ISSUE TITLE
Luma theme my account Order Information status tabs break in tablet view

### ISSUE THREAD

**Issue by abrarpathan19** [magento/magento2#21070] opened 2019-02-08 12:23 UTC
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Place new order -> My account -> My orders -> select any order -> View Order -> see the order status tabs are breaking. see the attached screenshots
2. It will happen when we will create a cash memo from admin for the order.

### Expected result (*)

1. http://prntscr.com/mibkdm

### Actual result (*)

1. http://prntscr.com/mibji7

**Comment by magento-engcom-team** [comment] 2019-02-08 12:23
Hi @abrarpathan19. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@abrarpathan19 do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment] 2019-02-08 12:24
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by krishprakash** [comment] 2019-02-08 12:24
@magento-engcom-team Please provide instance.

**Comment by krishprakash** [comment] 2019-02-08 12:25
![screenshot_2](https://user-images.githubusercontent.com/46617848/52478223-b6192480-2bca-11e9-9cb1-6bcdea0418f9.jpg)

I have checked in my local instance. verify issue.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:26
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-02-08 12:27
@krishprakash Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [x] Add `"Reproduced on "` label(s) to this ticket based on verification result

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-02-08 12:28
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:29
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by krishprakash** [comment] 2019-02-08 12:30
Please give me test instance.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:31
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by krishprakash** [comment] 2019-02-08 12:36
@magento-engcom-team can you please give me developer instance.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:41
Hi @krishprakash. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:42
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by magento-engcom-team** [comment] 2019-02-08 12:43
Hi @shikhamis11. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [x] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [x] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

-  _Next steps are available in case you are a member of **Community Maintainers**._

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by shikhamis11** [comment] 2019-02-08 12:46
@magento-engcom-team give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 12:46
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-08 12:47
Hi @shikhamis11, here is your [Magento instance](https://i-21070-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-21070-2-3-develop.instances.magento-community.engineering/admin](https://i-21070-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2019-02-08 12:57
![2019-02-08_18-24-34](https://user-images.githubusercontent.com/46617848/52479582-22962280-2bcf-11e9-8d3c-7a2a07cb3127.png)

I have verify this issue

**Comment by magento-engcom-team** [comment] 2019-02-08 12:57
:white_check_mark: Confirmed by @krishprakash
Thank you for verifying the issue! :+1: Your confirmation will help us to acknowledge and process this report.

**Comment by shikhamis11** [comment] 2019-02-08 13:00
@magento-engcom-team give me 2.2-develop instance

**Comment by magento-engcom-team** [comment] 2019-02-08 13:01
Hi @shikhamis11. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-02-08 13:03
Hi @shikhamis11, here is your [Magento instance](https://i-21070-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-21070-2-2-develop.instances.magento-community.engineering/admin](https://i-21070-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment] 2019-02-08 13:13
:white_check_mark: Confirmed by @shikhamis11 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98176`, `MAGETWO-98177` were created

**Issue Available**: @shikhamis11, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-02-14 20:54
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#21071 by @abrarpathan19 in 2.3-develop branch
Related commit(s):
 - [e575e978df3ad1ab690bf8af5c192872d15c549c](https://github.com/magento/magento2/commit/e575e978df3ad1ab690bf8af5c192872d15c549c)
 - [d3a1fd12406a37e943d9b4577e91c8c53e120e35](https://github.com/magento/magento2/commit/d3a1fd12406a37e943d9b4577e91c8c53e120e35)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-02-14 20:54 UTC
Labels: Issue: Ready for Work, Component: Customer, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.2.x, Reproduced on 2.3.x, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is valid, Area: Design/Frontend

**Comment by magento-engcom-team** [comment] 2019-02-16 15:45
Hi @abrarpathan19. Thank you for your report. 
The issue has been fixed in magento/magento2#21250 by @suryakant-krish in 2.2-develop branch
Related commit(s):
 - [da3a606adcdce1e1f55e2e74e106cf3f67a650db](https://github.com/magento/magento2/commit/da3a606adcdce1e1f55e2e74e106cf3f67a650db)
 - [6acd8a4c1265c3f6da08b9d7722a77d83def245f](https://github.com/magento/magento2/commit/6acd8a4c1265c3f6da08b9d7722a77d83def245f)

The fix will be available with the upcoming 2.2.9 release.
