### ISSUE TITLE
Multiple custom options update issue

### ISSUE THREAD

**Issue by yakivV** [magento/magento2#4174] opened 2016-04-15 16:20 UTC
In `public function saveOptions()` (app/code/Magento/Catalog/Model/Product/Option.php), when saving the first option, its **storedData** property is empty, so it’s initialized from the database.  
Then, when saving the next option, its **storedData** property doesn’t get updated. That happens because it’s initialized with the previous option’s data.  

That leads to the issue that in the file `lib/internal/Magento/Framework/Model/ResourceModel/Db/AbstractDb.php` in the `function prepareDataForUpdate($object)` call `$object->getStoredData()` returns data for the previous option.

That is the reason why some properties of the option get deleted from the $data array and never get into the database.
## Steps to reproduce
1. Install Magento from `2.0.4` branch.
2. Create a product with 2 options, as shown in the image. ![magento2-save-options-bug](https://cloud.githubusercontent.com/assets/10036589/14567888/f0e72434-033e-11e6-9e12-cf88150b9915.png)
3. Save the product and reopen the Custom Options tab. 
4. Change “Option 2” Input Type from “Checkbox” to Drop-down” and uncheck the flag “Required”
5. Save the product 
6. The issues DIDN’T get saved.

**Comment by piotrekkaminski** [comment] 2016-05-24 15:39
Internal issue MAGETWO-53430

**Comment by veloraven** [comment] 2016-10-26 09:40
Original internal ticket was closed without fixing.
We now have another one - MAGETWO-52971
I'm closing this issue as duplicate of #4462

**Closed as completed by veloraven** 2016-10-26 09:40 UTC
Labels: bug report
