### ISSUE TITLE
Tracking templates in shipping module using incorrect blocks

### ISSUE THREAD

**Issue by AirmanAJK** [magento/magento2#8025] opened 2017-01-03 21:21 UTC
Using Magento CE 2.1.3.
Add tracking info to a completed sales order. Visit the user account, and on the "My Orders" section, navigate to the "Order Shipments" tab. Click either the "Track this shipment" link, or the links for any individual tracking numbers.

Expected result: the tracking info visible in a popup window.

Actual result: an exception message: 
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Magento\Framework\View\Element\Template::formatDeliveryDateTime

The Magento_Shipping::tracking/popup.phtml template calls the $block->addChild function, using the tracking/details.phtml and tracking/progress.phtml templates depending on whether or not any info is available for the tracking numbers chosen.

The class types passed to the addChild functions are Template::class, yet inside the two templates, functions available only in the Magento\Shipping\Block\Tracking\Popup block are used. Specifically, formatDeliveryDateTime, formatDeliveryDate, and formatDeliveryTime.

It seems like poor design to hardcode a block instance in a template like this to begin with, but at the very least, the type instance passed in should be the Popup.php block class instead of the general Template class.

Has nobody else encountered this? I don't see how it could have ever worked when there is any tracking info to show, but I found no other reports of this issue, open or closed.

**Comment by abarua17** [comment] 2017-01-11 20:12
@AirmanAJK I created an order from front-end and on the back-end I submitted shipment. Then I added tracking info. I was not able to reproduce this on 2.1.3. Can you please try to give me step by step process, so I may try to reproduce this issue on our end?

**Comment by AirmanAJK** [comment] 2017-01-21 19:27
Are you sure the date format functions I mentioned above were being called? If no tracking info is available,  those child blocks aren't generated (per the if statements in the template). If you're sure they are being called, I'd be very curious to know what class instance was created for the child blocks instantiated in popup.phtml. Can you debug that file and examine the type? If it's as the code suggests, a plain instance of Template, those date functions definitely don't exist, and the framework should error as it did with me.

**Comment by AirmanAJK** [comment] 2017-01-25 02:26
#7229 
Looks like this got fixed elsewhere.

**Comment by YevSent** [comment] 2017-02-14 15:18
@AirmanAJK, this is known issue (internal ticket MAGETWO-63215). Closed as duplicated to https://github.com/magento/magento2/issues/8219.

**Closed as completed by YevSent** 2017-02-14 15:18 UTC
Labels: bug report, Progress: needs update, Component: Sales, Component: Shipping
