### ISSUE TITLE
CSS Issue mobile; broken content blocks, orange box next to cart

### ISSUE THREAD

**Issue by GreenWorldTrad** [magento/magento2#3713] opened 2016-03-10 11:12 UTC
Hello all, after some significant wrestling with our server we have managed to install magento 2, backend is working perfectly, frontend is giving a couple of issues which I shall detail here.

Our server is running Apache/2.4.18 and php7; we finally got it installed using the composer. Recompiled all libraries, double-checked permissions, etc, after installing sample data. 

Nonetheless, we are running into two strange problems (posted at community forum with no response yet):
1. A little orange box remains next to the shopping cart icon
2. on the mobile version, the content blocks appear to break the css, which at first load properly but then appear to be displaced by another css that loads after the fact.

I have seen the same issue on a number of demo stores. Please see:
http://neogrow.unr.com
http://magento2demo.firebearstudio.com/
and finally on our page: http://growcomponentes.com/tienda

I am attaching screen shots of the problem in the hopes that someone knows something about what could be going wrong. Again, I have seen this same issue on several magento 2 demo sites. I am also attaching a correct snapshot from another demo site.

No errors are appearing in Chrome's css/js inspector.

ANY insight appreciated in advance! Cheers!

![screen shot 2016-03-09 at 2 07 53 pm](https://cloud.githubusercontent.com/assets/9975439/13667891/3643202a-e6b9-11e5-8fea-53a1f61f0ba8.png)
![magento2mobile-correct](https://cloud.githubusercontent.com/assets/9975439/13667893/3d5cc0c8-e6b9-11e5-812c-0a85b39d03f5.png)

**Comment by ishakhsuvarov** [comment] 2016-03-10 13:04
@GreenWorldTrad Thank you for reporting these issues.

> 1. A little orange box remains next to the shopping cart icon

Fix for this issue is already available in the `develop` branch and will be available in the future releases. You may use [commit](https://github.com/magento/magento2/commit/eec3cf17bc5deae71c83c797d1339de46cf6905f) `eec3cf1` as a hotfix.

**Comment by GreenWorldTrad** [comment] 2016-03-10 17:01
@ishakhsuvarov 
Thanks for the tip. We are going to try this and report back. Hope to close the ticket if it works. Strangely, the orange box disappeared on its own. 

I also must add that the mobile menu is not working correctly either, when you expand it on mobile it does not close properly. If I see that it is still not working after the commit you mention I shall either open a new thread or add on to this (whatever the mods see fit!).

Regards!

**Comment by ishakhsuvarov** [comment] 2016-03-11 08:01
@GreenWorldTrad 

> Strangely, the orange box disappeared on its own.

That could happen. The fix above eliminates this random behaviour.

**Comment by eworksmedia** [comment] 2016-03-29 17:44
Applying this patch to the five files results in 

`knockout.js:3012 Uncaught ReferenceError: Unable to process binding "css: function (){return { empty:!!getCartParam('summary_count') == false} }
Message: getCartParam is not defined`

and the minicart fails to function properly now. After applying the patch both

`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`

were run as well as refreshing all cache types and flushing static cache, js/css cache, magento cache, and storage cache.

**Comment by ishakhsuvarov** [comment] 2016-03-31 10:50
@eworksmedia Which version are you applying patch to?

**Comment by eworksmedia** [comment] 2016-03-31 15:13
Sorry, v2.0.2. However, I reverted the patch and the orange box went away and the minicart works again. Sometimes it happens and sometimes it doesn't. It seems to be random on any given refresh.

**Comment by piotrekkaminski** [comment] 2016-06-14 10:31
Cannot reproduce on 2.1rc

**Closed as completed by piotrekkaminski** 2016-06-14 10:31 UTC
Labels: Progress: needs update
