### ISSUE TITLE
Rich snippets magento 2 - bug - price notation not right

### ISSUE THREAD

**Issue by JamboMedia** [magento/magento2#7173] opened 2016-10-25 09:56 UTC
Preconditions

Magento 2.1.2

Steps to reproduce
1. Test a productpage from the demo shop

The rich snippets for magento 2 are giving a warning for the element price

https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Fmagento2demo.firebearstudio.com%2Fargus-all-weather-tank.html

The notation is now:

<span class="price">$22.00</span>

The notation should be: (whithout the Currency)

<span class="price">22.00</span>

**Comment by veloraven** [comment] 2016-10-25 12:12
Please, format this issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result.
Please, also identify exact version of Magento you are running.

**Comment by JamboMedia** [comment] 2016-10-25 14:05
Better?

**Comment by caseyjonesaustralia** [comment] 2016-11-09 05:09
Same issue here v2.1.2
Can anyone provide a quick fix for this prior to the next release?

**Comment by fxdegroot** [comment] 2016-11-21 17:27
Same issue for me in 2.1.2. Can we get any news or diff in order to fix this issue ?

**Comment by Pakkapao** [comment] 2016-11-26 11:54
This works for me. Try updating `<magento root>/vendor/magento/module-catalog/view/base/templates/product/price/amount/default.phtml`

From:
`<?php echo $block->getSchema() ? ' itemprop="price"' : '' ?>>`

To:
`<?php echo $block->getSchema() ? ' itemprop="price" content="' . $block->getDisplayValue() . '"': '' ?>>`

Before:
![before](https://cloud.githubusercontent.com/assets/11070293/20640152/5492800c-b409-11e6-98d5-778d6e0f1393.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/11070293/20640153/5730821e-b409-11e6-956f-7761c7531f69.PNG)

Reference: http://schema.org/price
> Note that both RDFa and Microdata syntax allow the use of a "content=" attribute for publishing simple machine-readable values alongside more human-friendly formatting.

**Comment by hostep** [comment] 2017-02-28 19:13
It looks like this was recently fixed by an accepted PR: https://github.com/magento/magento2/pull/8132, albeit in a slightly different way then what @Pakkapao was suggesting.

Can somebody confirm? @okorshenko @avoelkl?

**Comment by avoelkl** [comment] 2017-03-01 20:47
Thanks for the heads up @hostep, this was indeed resolved with #8132.

**Comment by Sergeacc** [comment] 2017-06-29 09:03
Internal ticket created MAGETWO-70329

**Comment by hostep** [comment] 2017-06-29 10:16
@Sergeacc: this was already fixed in https://github.com/magento/magento2/pull/8132, or is this new MAGETWO ticket for backporting the fix to 2.1? Or am I missing something here? :)

**Comment by Sergeacc** [comment] 2017-06-29 10:22
@hostep yes, this is new MAGETWO ticket for backporting the fix to 2.1

**Comment by magento-engcom-team** [comment] 2017-09-21 14:11
@JamboMedia, thank you for your report.
The fix for this issue is already available in the develop branch. See PR https://github.com/magento/magento2/pull/8132.

**Closed as completed by magento-engcom-team** 2017-09-21 14:11 UTC
Labels: Issue: Ready for Work, bug report, Component: Tax, Fixed in 2.2.x, Fixed in 2.3.x, Issue: Format is not valid
