### ISSUE TITLE
Magento2.3.3: Bug in Admin Catalog Product StoreView wise.

### ISSUE THREAD

**Issue by sangeetajain** [magento/magento2#25146] opened 2019-10-18 10:21 UTC
### Preconditions (*)
1. Magento 2.3.3 & 2.3-develop

### Examples (*)
It will automatically disable product to other 2nd store view. We have not disabled for 2nd store view, we disabled this product for one store view.

### Steps to reproduce (*)

1. Create 2 store views 
2. Create a product
3. On a product edit page disable product for 'All store views'
4. Switch editing to some store view 
5. Enable product
6. Check other store views

### Expected result (*)
1. Only one store view enabled

### Actual result (*)
1. Other store views enabled too

**Comment by Khushbu-Webkul-QA** [comment] 2019-10-18 14:09
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-10-18 14:09
Hi @Khushbu-Webkul-QA. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-10-18 14:10
Hi @Khushbu-Webkul-QA, here is your [Magento instance](https://i-25146-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25146-2-3-develop.instances.magento-community.engineering/admin](https://i-25146-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Charlie** [comment] 2019-10-21 15:31
Hello @sangeetajain 
We are not able to reproduce this issue on the lates 2.3-develop branch by provided step.
I have to close this issue.
Thanks for your report!

**Comment by sangeetajain** [comment] 2019-10-22 04:36
In Magento 2.3.3 community version Go to admin create 2 stores view then create a product in admin for "All store View" and save this.
Now open this product again for edit and select the one storeview then remove checkmark from "Enabled" AND "Disable" this product for one store view. It will automatically disabled to other 2nd store view. We have not disabled for 2nd store view, we disabled this product for one store view.

**Comment by magento-engcom-team** [comment] 2019-10-22 08:32
@engcom-Charlie Thank you for verifying the issue.

Unfortunately, not enough information was provided to acknowledge ticket. Please consider adding the following:
- [ ] Update issue content to follow format required by [Issue Reporting Guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Once all required information is added, please add label `"Issue: Confirmed"` again.
Thanks!

**Comment by magento-engcom-team** [comment] 2019-10-22 08:34
:white_check_mark: Confirmed by @engcom-Charlie 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-21969` were created

**Issue Available**: @engcom-Charlie, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by crissanclick** [comment] 2019-10-27 11:04
Can't reproduced

**Comment by anabsotomayor** [comment] 2019-10-27 12:11
This isues doesn't posible, scope the attribute enable/disable is for website not for store view.

**Closed as completed** 2019-10-27 12:17 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Store
