### ISSUE TITLE
Magento 2.3.5-p2 issue on sending email with Chinese Sender Name "Invalid header value detected"

### ISSUE THREAD

**Issue by arslan-eg** [magento/magento2#31076] opened 2020-11-27 11:10 UTC
Summary (*)
When a customer or user wants to change its password in his dashboard password change option. If the Store Email Addresses configuration (Admin->stores->settings->configurations->general->Store Email Addresses->Customer Support->Sender Name) is set in Chinese e-g "蘭芝台灣" and save configuration. In this scenario email is not sending and shows the error "Invalid header value detected".

### Preconditions (*)
1. Magento 2.3.5-p2
2. Sender name in configuration is set in Chinese.

### Steps to reproduce (*)
1. In Admin Panel navigate to (Admin->stores->settings->configurations->general->Store Email Addresses->Customer Support->Sender Name).
2. Add Sender Name in Chinese e-g "蘭芝台灣" and save configuration
3. Login at website then navigate to My Account->Change Password and click on change password and add new password

### Expected result (*)
1. Email should be send to the user when he changed the password.

### Actual result (*)
1. Email is not received by the user and shows the error flash message "Invalid header value detected"

Further Details(*)
[Video recording of this issue](https://www.loom.com/share/9c9af35c0df64771bb4ea9818a0de3c7)

**Comment by engcom-Alfa** [comment] 2020-11-27 14:42
Hi @arslan-eg . Thank you for your report!

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop.

**Manual testing scenario:**

1. In Admin Panel navigate to (Admin->stores->settings->configurations->general->Store Email Addresses->Customer Support->Sender Name).
2. Add Sender Name in Chinese e-g "蘭芝台灣" and save the configuration

![Screenshot from 2020-11-27 16-30-05](https://user-images.githubusercontent.com/51679138/100459895-e8ad4d80-30ce-11eb-86af-363ad2146755.png)

3. log in to Storefront, then navigate to My Account->Change Password and click on change password and add a new password

**Actual Result:** :heavy_check_mark: An email is sent to the user when he has changed his password.

![Screenshot from 2020-11-27 16-33-10](https://user-images.githubusercontent.com/51679138/100460051-32963380-30cf-11eb-9577-ac5267970271.png)
![Screenshot from 2020-11-27 16-33-19](https://user-images.githubusercontent.com/51679138/100460055-34f88d80-30cf-11eb-83ac-0df5793e309c.png)

@arslan-eg Maybe we missed some details? Could you take a look?
Thanks!

**Comment by arslan-eg** [comment] 2020-11-27 20:56
Hello @engcom-Alfa Thank you for your response.

I'm using magento version  2.3.5-p2. which producing this email sending error with Chinese Sender Name. 
While you are testing this scenario at magento 2.4

Could you please check this scenario in version 2.3.5-p2. And what will be the solution for this.

Thank you!

**Comment by betooliveirame** [comment] 2020-11-30 18:00
@magento give me 2.3.5-p2 instance

**Comment by arslan-eg** [comment] 2020-12-02 06:38
@magento give me 2.3.5-p2 instance

**Comment by tuyennn** [comment] 2020-12-03 09:24
@magento give me 2.3.5-p2 instance

**Comment by tuyennn** [comment] 2020-12-03 09:39
Seem this is duplicate of #24902

**Comment by engcom-Alfa** [comment] 2020-12-22 13:57
@magento give me 2.3.5-p2 instance

**Comment by engcom-Alfa** [comment] 2020-12-22 14:38
Hi @arslan-eg 

Unfortunately, we are not able to reproduce this issue on `2.3.5-p2`, `2.4.1` and `2.4-develop`.
Everything works as expected.

**Actual Result:** :heavy_check_mark:  An email is sent to the user when he has changed his password.

![Screenshot from 2020-12-22 16-30-55](https://user-images.githubusercontent.com/51679138/102899241-4dac5700-4473-11eb-8da0-26b84e8303d6.png)

![2020-12-22_16-31](https://user-images.githubusercontent.com/51679138/102899255-513fde00-4473-11eb-919f-f127124cdd78.png)

It seems that the issue was solved by changes from PR #24906.
So, we have to close it.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch.
 Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-12-22 14:38 UTC
Labels: Severity: S1, Issue: needs update

**Comment by Nuranto** [comment] 2021-10-14 16:03
I just reproduced this issue on 2.4.3-p1, but not with UTF-8 in sender name, but in receiver name
