### ISSUE TITLE
Tax with Country store dropdown option not auto select actual tax rate calculation.

### ISSUE THREAD

**Issue by irshad-iflair** [magento/magento2#26853] opened 2020-02-13 05:50 UTC
### Summary of the issue (*)
-> Magento CE 2.3.2 with sample data is installed.
-> **I need, Multiple stores have a common country (i.e. united states and country states should be all) then different tax rules for all stores(*)**.

### Examples (*)
->  I create Two different stores **US and US1 for the common country (i.e. united states)** https://i.stack.imgur.com/S3X1I.png. Then create two different **tax rules (i.e. US-tax rule and US1-tax rule) for both stores**. https://i.stack.imgur.com/801Jw.png next In **Tax Zones and Rates set US Tax rate 5% and US1 tax 10%**. https://i.stack.imgur.com/VrSe6.png Now on the product details page while choosing store from the dropdown, **product price display sum of 5%+10%, that is the wrong calculation.**
**, For example, the product price is $22**https://i.stack.imgur.com/F7hrn.png.
**on selecting US1 or US stores on both steps**.

**result display 22(10% + 5%) = 25.30$ (wrong)** https://i.stack.imgur.com/qiMFs.png.

### Proposed solution
1> **it should be on choosing US store, 22*10%= $24.2(right)**
2> **US1 store 22*5%= $23.1 (right).**
       **Is it bug or functionality?**
        **how can we display separate tax on selecting particular stores from the dropdown?**

**Comment by irshad-iflair** [comment] 2020-02-13 05:52
yes

**Comment by engcom-Bravo** [comment] 2020-02-17 10:59
Hello @irshad-iflair 

Thank you for your report

I believe that it is not possible to set different tax rules for the same country, same state, same Website, but different Stores.
This is not a bug, and I believe that in Magento, user doesn't select Store scope for applying tax. User selects region.

(For example, the Tax title doesn't influence the Tax scope.)
![tax_title](https://user-images.githubusercontent.com/51680745/74647673-c58b6000-5184-11ea-8e0c-3b2602adf524.png)

We have to close this issue. Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

Thank you for collaboration

**Closed as completed by engcom-Bravo** 2020-02-17 10:59 UTC
Labels: Issue: Format is valid, Triage: Dev.Experience, Reported on 2.3.2

**Comment by irshad-iflair** [comment] 2020-02-17 14:12
Here  I make a dropdown for the users to choose the option of the tax rate, https://i.stack.imgur.com/76U7m.png.
is it not possible on particular  tax rule product price calculate accordingly.?
