### ISSUE TITLE
Admin product grid Massaction design issue with sub menu

### ISSUE THREAD

**Issue by ananth-iyer** [magento/magento2#20928] opened 2019-02-03 09:33 UTC
Mass action design issue on Product grid, Sales grid, where ever mass action is used.

### Preconditions (*)

1. Magento 2.2.x & Magento 2.3.x
2. Chrome
3. Ubuntu

### Steps to reproduce (*)

1. Go to Catalog > Products page
2. In Mass Actions drop down > click on **Change Status**: then you can not see the selected **Change Status** item & can not close the child drop down to check other items.

### Expected result design (*)

1. ![expected-massaction-design](https://user-images.githubusercontent.com/5195107/52174988-86c97880-27c2-11e9-80c8-50d6b3669d84.jpg)

### Actual result  design (*)

1. ![actual-massaction-design](https://user-images.githubusercontent.com/5195107/52174987-86c97880-27c2-11e9-8204-6397e2490351.jpg)

**Comment by magento-engcom-team** [comment] 2019-02-03 09:33
Hi @ananth-iyer. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [x] Summary of the issue
- [x] Information on your environment
- [x] Steps to reproduce
- [x] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me 2.3-develop instance` - upcoming 2.3.x release

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@ananth-iyer do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by ananth-iyer** [comment] 2019-02-03 09:33
I am working on it. #mm19in

**Comment by magento-engcom-team** [comment] 2019-02-04 12:13
Hi @sdzhepa. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by magento-engcom-team** [comment] 2019-02-04 12:20
:white_check_mark: Confirmed by @sdzhepa 
 Thank you for verifying the issue. Based on the provided information internal tickets `MAGETWO-98052` were created

**Issue Available**: @sdzhepa, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by magento-engcom-team** [comment] 2019-03-14 19:45
Hi @ananth-iyer. Thank you for your report. 
The issue has been fixed in magento/magento2#20938 by @ananth-iyer in 2.3-develop branch
Related commit(s):
 - [facfa44aa6f5163a1d78f501c94a8a4303b6b631](https://github.com/magento/magento2/commit/facfa44aa6f5163a1d78f501c94a8a4303b6b631)
 - [314d3a8ef24d49f5a55cf6ca3efe5bdfef025b4d](https://github.com/magento/magento2/commit/314d3a8ef24d49f5a55cf6ca3efe5bdfef025b4d)
 - [631c6b1a2c13c34bf2689148b1ec7ee6d88d2391](https://github.com/magento/magento2/commit/631c6b1a2c13c34bf2689148b1ec7ee6d88d2391)
 - [524eef39230cd60d2a4f32f6827c6f238d574957](https://github.com/magento/magento2/commit/524eef39230cd60d2a4f32f6827c6f238d574957)

The fix will be available with the upcoming 2.3.2 release.

**Closed as completed by magento-engcom-team** 2019-03-14 19:45 UTC
Labels: Issue: Ready for Work, Component: Catalog, Issue: Confirmed, Reproduced on 2.3.x, Fixed in 2.3.x, Issue: Format is valid, Progress: PR Created, Event: mm19in
