### ISSUE TITLE
G. Chrome - Add to cart not working

### ISSUE THREAD

**Issue by albsa** [magento/magento2#2527] opened 2015-11-25 22:11 UTC
Did a fresh magento 2.0 composer installation on local desktop.

Add to cart isn't working in Google Chrome Version 46.0.2490.86 (64-bit)

It stays stuck on faded button with text "Adding..."

It's working properly in Safari and Firefox.

**Comment by dmitrii-fediuk** [comment] 2015-11-26 07:34
Magento does not work properly on a top-level domain like `localhost`.

**Comment by davidalger** [comment] 2015-12-02 15:35
Please use a domain other than localhost, as it will not work properly in such case. Closing as duplicate of #2439

**Closed as completed by davidalger** 2015-12-02 15:35 UTC

**Comment by agjalpm** [comment] 2016-05-05 06:06
@mage2pro Why Magento does not work properly on top-level domain like `localhost`?

**Comment by mrkhoa99** [comment] 2016-05-05 08:47
@agjalpm this issue occurs on Chrome. You can read more here: http://superuser.com/questions/274562/teach-google-chrome-to-understand-custom-tld
https://bugs.chromium.org/p/chromium/issues/detail?id=30636
