### ISSUE TITLE
Can´t reindex after migration from M1 to M2, receiving No Such Entity.

### ISSUE THREAD

**Issue by allanzmn** [magento/magento2#10091] opened 2017-06-28 19:31 UTC
Got a client request to update an M1 store. Before I can give him an answer I´m trying to make a test in my environment. Everything seems to be worked fine despite of a few warnings but I get 'No Such Entity" when reindexing catalog_category_product, catalog_product_category and catalog_product_price. Did I ignored something I shouldn´t?

### Preconditions
My environment runs: Linux / Php 7.0.20
Updating from Magente 1.9.2.4 to Magento 2.1.7

Changes to map.xml.dist
```
    <source>
        <document_rules>
            <ignore>
                <document>bestsellerproducts</document>
            </ignore>
            <ignore>
                <document>blog_category_entity</document>
            </ignore>
            <ignore>
                <document>blog_category_entity_datetime</document>
            </ignore>
            <ignore>
                <document>blog_category_entity_int</document>
            </ignore>
            <ignore>
                <document>blog_category_entity_text</document>
            </ignore>
            <ignore>
                <document>blog_category_entity_varchar</document>
            </ignore>
            <ignore>
                <document>blog_category_post</document>
            </ignore>
            <ignore>
                <document>blog_category_post_index</document>
            </ignore>
            <ignore>
                <document>blog_comment</document>
            </ignore>
            <ignore>
                <document>blog_eav_attribute</document>
            </ignore>
            <ignore>
                <document>blog_post_entity</document>
            </ignore>
            <ignore>
                <document>blog_post_entity_datetime</document>
            </ignore>
            <ignore>
                <document>blog_post_entity_int</document>
            </ignore>
            <ignore>
                <document>blog_post_entity_text</document>
            </ignore>
            <ignore>
                <document>blog_post_entity_varchar</document>
            </ignore>
            <ignore>
                <document>blog_post_link</document>
            </ignore>
            <ignore>
                <document>blog_post_link_attribute</document>
            </ignore>
            <ignore>
                <document>blog_post_link_attribute_int</document>
            </ignore>
            <ignore>
                <document>blog_post_link_type</document>
            </ignore>
            <ignore>
                <document>blog_tag</document>
            </ignore>
            <ignore>
                <document>blog_tag_post</document>
            </ignore>
            <ignore>
                <document>blog_url_rewrite</document>
            </ignore>
            <ignore>
                <document>dynamicproducts</document>
            </ignore>
            <ignore>
                <document>em_multideal</document>
            </ignore>
            <ignore>
                <document>em_multideal_store</document>
            </ignore>
            <ignore>
                <document>em_slideshow2_slider</document>
            </ignore>
            <ignore>
                <document>label_css_entity</document>
            </ignore>
            <ignore>
                <document>label_css_entity_text</document>
            </ignore>
            <ignore>
                <document>blog_tag_post</document>
            </ignore>
            <ignore>
                <document>label_eav_attribute</document>
            </ignore>
            <ignore>
                <document>label_entity</document>
            </ignore>
            <ignore>
                <document>label_entity_int</document>
            </ignore>
            <ignore>
                <document>label_eav_attribute</document>
            </ignore>
            <ignore>
                <document>label_entity_text</document>
            </ignore>
            <ignore>
                <document>label_entity_varchar</document>
            </ignore>
            <ignore>
                <document>ln_filter</document>
            </ignore>
            <ignore>
                <document>ln_option</document>
            </ignore>
            <ignore>
                <document>megamenupro</document>
            </ignore>
            <ignore>
                <document>newproducts</document>
            </ignore>
            <ignore>
                <document>pagseguro_orders</document>
            </ignore>
            <ignore>
                <document>quoteadv_audit_trail</document>
            </ignore>
            <ignore>
                <document>quoteadv_crmaddon_messages</document>
            </ignore>
            <ignore>
                <document>quoteadv_crmaddon_templates</document>
            </ignore>
            <ignore>
                <document>quoteadv_customer</document>
            </ignore>
            <ignore>
                <document>quoteadv_extraoptions</document>
            </ignore>
            <ignore>
                <document>quoteadv_group_allow</document>
            </ignore>
            <ignore>
                <document>quoteadv_log_admin</document>
            </ignore>
            <ignore>
                <document>quoteadv_product</document>
            </ignore>
            <ignore>
                <document>quoteadv_product_downloadable</document>
            </ignore>
            <ignore>
                <document>quoteadv_quote_address</document>
            </ignore>
            <ignore>
                <document>quoteadv_request_item</document>
            </ignore>
            <ignore>
                <document>quoteadv_rotation</document>
            </ignore>
            <ignore>
                <document>quoteadv_shipping_rate</document>
            </ignore>
            <ignore>
                <document>quoteadv_tier_cost</document>
            </ignore>
            <ignore>
                <document>recentreviewproducts</document>
            </ignore>
            <ignore>
                <document>saleproducts</document>
            </ignore>
            <ignore>
                <document>smtppro_email_log</document>
            </ignore>
            <ignore>
                <document>supplierbiddingtool_bidding</document>
            </ignore>
            <ignore>
                <document>supplierbiddingtool_supplier</document>
            </ignore>
            <ignore>
                <document>themeframework_area</document>
            </ignore>
            <ignore>
                <document>themeframework_area_store</document>
            </ignore>
            <ignore>
                <document>themeframework_page</document>
            </ignore>
            <ignore>
                <document>themeframework_page_store</document>
            </ignore>
        </document_rules>
        <field_rules>
            <ignore>
                <field>sales_flat_order.c2q_internal_quote_id</field>
            </ignore>
            <ignore>
                <field>sales_flat_order_payment.cc_raw_response</field>
            </ignore>
            <ignore>
                <field>sales_flat_order_payment.customer_payment_id</field>
            </ignore>
            <ignore>
                <field>sales_flat_quote.proposal_quote_id</field>
            </ignore>
        </field_rules>
    </source>

```
Changes in class-map.xml.dist

```
    <rename>
        <from>blog/post</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/attribute</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/attribute_collection</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/category</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/attribute</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/attribute_collection</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/post_attribute_backend_image</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/post_attribute_source_author</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/post_attribute_source_allowcomment</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/category_attribute_backend_image</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/post_attribute_source_layout</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/category_attribute_source_displaymode</from>
        <to></to>
    </rename>
    <rename>
        <from>blog/category_attribute_source_cmsblock</from>
        <to></to>
    </rename>
    <rename>
        <from>productlabels/productlabels_attribute_backend_image</from>
        <to></to>
    </rename>
    <rename>
        <from>productlabels/productlabels</from>
        <to></to>
    </rename>
    <rename>
        <from>productlabels/attribute</from>
        <to></to>
    </rename>
    <rename>
        <from>productlabels/attribute_collection</from>
        <to></to>
    </rename>
    <rename>
        <from>productlabels/css</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/catalog_product_attribute_backend_qquoteadv_group_allow</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/source_conditions</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/catalog_product_attribute_backend_qquoteadv_tiercost</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/entity_assignsalesrep</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/entity_assignsalesrep</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/entity_assignsalesrep</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/entity_assignsalesrep</from>
        <to></to>
    </rename>
    <rename>
        <from>qquoteadv/entity_assignsalesrep</from>
        <to></to>
    </rename>
    <rename>
        <from>not2order/source_allowprice</from>
        <to></to>
    </rename>
    <rename>
        <from>not2order/source_alloworder</from>
        <to></to>
    </rename>
```

### Steps to reproduce
1. I installed M2, made no changes or even any access to home ou admin.
2. Installed Data Migration Tool
3. Edited config.xml, class-map.xml.dist and map.xml.dist to match db configuration and ignore extensions since I have nothing yet on M2.
4. Ran settings migration
5. Ran data migration
6. Ran delta migration
7. Copied Media folder
8. Flushed cash
9. Tried to reindex all indexes.

### Result
These are the only Warnings/Errors i got during whole process:

1. magento migrate:data
[WARNING]: Mismatch of entities in the document: report_event
[WARNING]: Mismatch of entities in the document: report_viewed_product_index
[WARNING]: Volume Check failed

2. magento migrate:delta
[WARNING]: Mismatch of entities in the document: catalog_product_entity_varchar
[WARNING]: Mismatch of entities in the document: search_query
[WARNING]: Mismatch of entities in the document: session
[WARNING]: Volume Check failed

3. magento indexer:index

```
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Product Flat Data index has been rebuilt successfully in 00:00:01
No such entity.
No such entity.
No such entity.
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:01

```

**Comment by allanzmn** [comment] 2017-06-28 20:37
SOLVED:
There was 1 store on 'stores' table that was relating with an 'store_group' that wasn´t there. Changed the ID and reindex worked fine.

**Comment by korostii** [comment] 2017-06-29 08:15
Hi @allanzmn,

For future reference: there's a [separate repository](https://github.com/magento/data-migration-tool) for the data migration tool. You'll probably get a faster response if you'll post your issues there.

Also, feel free to close the issue report if the issue is resolved for you.

**Comment by veloraven** [comment] 2017-06-30 11:19
I'm closing this issue as it was solved.
If you can still reproduce this issue, please create a new GitHub issue report.

**Closed as completed by veloraven** 2017-06-30 11:19 UTC
