### ISSUE TITLE
Conditions with multi-values (is one of/is not one of) dosen`t work

### ISSUE THREAD

**Issue by deiserh** [magento/magento2#8740] opened 2017-03-01 15:21 UTC
### Preconditions

1. Magento Version 2.1.4

### Steps to reproduce

1. Create a Catalog Price Rule 
2. Under Conditions add a condition with "is one of" or "is not one of" and a few values
3. Save the Price Rule

### Expected result

1. On reopen the price rule I expect that all selected values of the condition are saved

### Actual result

1. On reopen **only the first** value of the condition is saved

**Comment by jmtakahashi** [comment] 2017-03-06 22:10
I can confirm this is an issue and is lacking attention.  I used SKU attribute and "is one of".  

@deiserh please check this fix -> #8246 which helps saving the multiple selections.

HOWEVER, not all of my selections are saving yet.  In issue #8215 which seems like this is the same issue, @miakusha states that you cannot use SKU as a Catalog Rule condition, however, it appears that you can.  But when using SKU as a Catalog Rule Condition it does not apply to ALL the items for some reason (some are applied, and some are not).  Seems buggy.

To clarify my issue after adding the above mentioned #8246 "fix":

**Steps to Reproduce**
ALL same:
1. "If ANY of these conditions are TRUE:"
2. SKU is one of (multiple sku's selected using the selector box).

**Expected result**
On close, save, and apply the price rule, I expect that all selected values of the condition are saved and applied to the storefront.

**Actual result**
On reopen all values are listed (but not physically shown as checked in the selector box), but one or two SKU's do not have the discount applied and also do not show up in the database under the rule.

**Comment by koenner01** [comment] 2017-06-23 14:40
I can confirm that the fix https://github.com/magento/magento2/pull/8246 works for the multiselect problem (tested in 2.1.7)

I have NOT tried the SKU scenario yet though

**Comment by koenner01** [comment] 2017-06-29 14:02
duplicate of https://github.com/magento/magento2/issues/7723

**Comment by magento-engcom-team** [comment] 2017-09-28 15:30
@deiserh, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.

**Closed as completed by magento-engcom-team** 2017-09-28 15:30 UTC
Labels: Issue: Clear Description, Issue:  Cannot Reproduce, Issue: Format is valid

**Comment by LeonidTomashevskyAmasty** [comment] 2018-04-02 16:28
Hello @magento-engcom-team 
I think issue is still persist. See this code from the core.  https://github.com/magento/magento2/blob/f3f8975c3f48ad8d2a3221153bcce9f82a5b84b8/app/code/Magento/Rule/Model/Condition/AbstractCondition.php#L366-L372
If attribute is multiselect then value is array, and this piece of code will return to process only first element

**Comment by hoangnm89** [comment] 2019-02-25 19:25
hi @LeonidTomashevskyAmasty, you're right. 
Issue is fixed on 2.2.7. ref: https://github.com/magento/magento2/commit/09cf555
