### ISSUE TITLE
If we modify the existing address updated_at column is not updating in customer_entity table

### ISSUE THREAD

**Issue by ghost** [magento/magento2#9419] opened 2017-04-27 07:06 UTC
### Preconditions

1. Magento EE 2.1.4 & PHP 5.6

### Steps to reproduce

1.  Create a customer 
2. Go to My account > Address book > add new address
3. Edit/Modify newly created address

### Expected result

1.  SELECT  email, updated_at  FROM `customer_entity` ORDER BY `entity_id` DESC

The column `updated_at` should update on address save

### Actual result

1. `updated_at` column is not updating in `customer_entity` table

**Comment by korostii** [comment] 2017-04-27 09:10
Please note that Enterprise issues can also be reported via the Support portal of your account (or via the Partner portal if you are a partner reporting on behalf of a merchant). 
That way, your issue should probably get acknowledged and solved faster. GitHub is intended for the Community Edition issue reports.

**Comment by magento-engcom-team** [comment] 2017-10-03 07:30
@jellamahendra, thank you for your report.
We've created internal ticket(s) MAGETWO-80656 to track progress on the issue.

**Comment by gnuzealot** [comment] 2017-10-16 16:45
Working on it... #SQUASHTOBERFEST

**Comment by okorshenko** [comment] 2017-10-16 18:05
Hi @gnuzealot could you please accept the invite to join magento team on GitHub

**Comment by lfolco** [comment] 2017-10-16 18:56
Should that `updated_at` be changed in this case though? The `created_at` and `updated_at` fields are usually considered audit-style fields, and if the `customer_entity` record itself is not changed, why would the `updated_at` field change? There is no change to the `customer_entity` record at all.

**Comment by gnuzealot** [comment] 2017-10-16 19:17
In the interpretation of the created_at and updated_at columns as indicators of an individual row being updated or created then this ticket should be flagged as working as designed. Based on other implementations of similar models this appears to be the case. If this is not the case then it would have major implications throughout data structures that have hierarchies like products all of which would be much easier implemented with database triggers.

**Comment by orlangur** [comment] 2017-10-16 20:04
Please don't "fix" it :) Obviously such scenario should cause `updated_at` change in `customer_address_entity` table only.

I remember there was another issue reported that updating shipment does not change `updated_at` of order entity.

**Comment by lfolco** [comment] 2017-10-16 20:11
Yes, I agree that we should not make any changes; this ticket should be closed.

**Comment by okorshenko** [comment] 2017-10-19 17:02
Hi @orlangur and @lfolco for research.  Closing as non-issue

**Closed as completed by okorshenko** 2017-10-19 17:02 UTC
Labels: Issue: Ready for Work, Issue: Confirmed, Reproduced on 2.1.x, Reproduced on 2.2.x, Reproduced on 2.3.x, non-issue, Issue: Format is valid, Event: MMNY17

**Comment by Tjab** [comment] 2021-03-03 15:04
@okorshenko @orlangur @lfolco

Can you explain to me why there should be a difference between updating an address, and creating an address? Because the creation of an address **does** update the customer. I have not checked if the 'default billing/shipping' needs to be checked for this, but if not, I do think there should be one solution: either update the customer at address creation/modification, or not.
