### ISSUE TITLE
Remove Coupon From Cart but not resetting applied_rule_ids on quote item table

### ISSUE THREAD

**Issue by tonywkc07** [magento/magento2#38709] opened 2024-05-09 02:49 UTC
### Preconditions and environment

- Magento version 2.4.5-p7
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

1. Create 2 cart price rules : No coupon and specific coupon 
2. No coupon settings:
![Screenshot 2024-05-09 at 10 38 14 AM](https://github.com/magento/magento2/assets/115712122/9ca492b2-bc24-44f9-8667-b76c7c112987)
![Screenshot 2024-05-09 at 10 38 38 AM](https://github.com/magento/magento2/assets/115712122/860ab9b0-96d2-49d9-82e5-a33d48c843b3)

3.Specific coupon settings:
![Screenshot 2024-05-09 at 10 40 36 AM](https://github.com/magento/magento2/assets/115712122/692a1bc1-5318-4544-85b3-1ef2d8e795e8)
![Screenshot 2024-05-09 at 10 40 53 AM](https://github.com/magento/magento2/assets/115712122/250a94ae-88c1-4918-b68d-39339da600fb)

4.Add items into shopping cart
5.Apply specific coupon code into shopping cart
6.Remove specific coupon code into shopping cart  

### Expected result

Should be reset quote_item applied_rule_ids

### Actual result

Did not reset and still keep the specific coupon code rule id into quote_item applied_rule_ids column
<img width="774" alt="Screenshot 2024-05-09 at 10 48 55 AM" src="https://github.com/magento/magento2/assets/115712122/dbad608f-761a-4284-bfef-c5563add1939">
<img width="704" alt="Screenshot 2024-05-09 at 10 45 08 AM" src="https://github.com/magento/magento2/assets/115712122/ee9ef8ec-7059-4f67-9d9a-308d5f36a25f">

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-05-09 10:31
Hi @tonywkc07 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance but the issue is not reproducible.

The specific coupon code rule id in quote_item applied_rule_ids column is reset if the coupon code is removed from the shopping card.

Please refer the attached screen record. Let us know if we missed anything.

https://github.com/magento/magento2/assets/60198592/d9457c3f-e38d-436c-b2f5-c47f0748ef16

**Comment by tonywkc07** [comment] 2024-05-10 02:23
Thank you for your investigation!
For this case, i already builded new Magento 2 vanilla in my local env but still cannot reset quote_item applied_rule_ids.
My magento version 2.4.5-p7 and here is video link for your reference:
https://drive.google.com/file/d/12mDiXuEYmHObXdkjmfTqzvBIDFKssteO/view?usp=drive_link

**Comment by engcom-Dash** [comment] 2024-05-13 11:59
Hi @tonywkc07 

We have verified the issue on 2.4.7 instance too but the issue is not reproducible for us.

The specific coupon code rule id in quote_item applied_rule_ids column is reset if the coupon code is removed from the shopping card.

Please refer the screenrecording and let us know if we missed anything.


https://github.com/magento/magento2/assets/60198592/f0528ae5-c8b2-466e-b0cc-62d606207e12

**Comment by tonywkc07** [comment] 2024-05-14 02:33
Thank you for your help! Would you please kindly try to reproduce it on 2.4.5-p7 community version? Thanks!

**Comment by engcom-Dash** [comment] 2024-05-14 08:27
Hi @tonywkc07 

Verified the issue on 2.4.5-p7 and the issue is reproducable.

But we recommend you to install the latest magento stable version.

https://github.com/magento/magento2/assets/60198592/a96a5640-b269-4899-b377-84bc0bd7da5e

Thanks.

**Comment by tonywkc07** [comment] 2024-05-14 08:33
Thank you so much! May I know that any quality patches for this case?

**Comment by smeatball** [comment] 2024-05-17 19:52
Hello, just a +1 here, on version 2.4.6-p5 in staging. this is blocking an upgrade as our ERP is looking for the applied id discount but there isn't one as it was cancelled.
Thank-you @tonywkc07 for the reporting/proof efforts.

**Comment by tonywkc07** [comment] 2024-05-21 11:15
Hi @engcom-Dash , @engcom-Bravo 

May I know that any quality patches for this case?

**Comment by tonywkc07** [comment] 2024-06-04 02:10
Hi @engcom-Dash , @engcom-Bravo 

Hi All, any updates for the quality patches? Thanks!

**Comment by aschrammel** [comment] 2024-06-20 12:47
Hi @engcom-Dash @engcom-Bravo 

+1 for a quality patch from our end. It's an annoying one if you have to determine the applied voucher codes on item base.

**Comment by engcom-Dash** [comment] 2024-07-25 13:42
Hi @ssstankiewicz 

Thanks for providing the patch.

We are closing the ticket as the issue is not reproducible on 2.4.7.

Please feel free to reopen or raise a new ticket if the issue persists.

Thanks.

**Closed as completed by engcom-Dash** 2024-07-25 13:42 UTC
Labels: Issue: needs update, Reported on 2.4.x
