### ISSUE TITLE
Getting issue on Forget Password Page

### ISSUE THREAD

**Issue by harshadkothiya** [magento/magento2#36848] opened 2023-02-10 22:11 UTC
### Preconditions and environment

- Magento version = 2.4.2
- Anything else that would help a developer reproduce the bug =
- https://stage.bikerzbits.com/customer/account/forgotpassword/ getting so many errors in core files

### Steps to reproduce

forgotpassword

### Expected result

working perfect forgetpassword page

### Actual result

working perfect forgetpassword page

### Additional information

working perfect forgetpassword page

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by mrkhoa99** [comment] 2023-02-11 08:42
@harshadkothiya if you try to view the source page, we will see the issue is not from Magento default. It's clearly a custom template issue. Please, check template line 32 `app/design/frontend/Smartwave/porto/Magento_Customer/templates/form/forgotpassword.phtml:32`

![image](https://user-images.githubusercontent.com/6185767/218248980-ca9c3723-e90f-4159-9ef4-b86be9752ca8.png)

**Comment by engcom-Alfa** [comment] 2023-02-13 09:01
hey @harshadkothiya 

Thanks for reporting the ticket here.
As per looking at the ticket "description, the actual and expected result, all sections seem to be with same information whereas according to the given snapshot link, I only see email fields with captcha fields which is the expected behavior of the system and not a bug in case forgot password.

hence request you to please help us with more information on the use case that you are performing along with steps, actual result, and expected result.

Thanks

**Comment by engcom-Alfa** [comment] 2023-03-03 05:46
Hi @harshadkothiya 

closing issue since no updates from the last 2 weeks, in case still the issue persists then feel free to reopen the issue with updated information like proper steps, expected result, and actual result along with some video/snapshot for reference.

Thanks

**Closed as completed by engcom-Alfa** 2023-03-03 05:46 UTC
Labels: Component: Ui, Issue: needs update, Reported on 2.4.2, Area: UI Framework
