### ISSUE TITLE
Allow to Choose State if It is Optional for Country not working!!!!

### ISSUE THREAD

**Issue by chequille** [magento/magento2#31912] opened 2021-01-30 23:09 UTC
### Preconditions (*)

1. Version 2.4.1
2.

### Steps to reproduce (*)

1. Set "Allow to Choose State if It is Optional for Country" to NO in configuration
2. Try checkout as guest and the field to select the state is still there 

### Expected result (*)

1. Selection field for state should not be there
2.

### Actual result (*)

1. Field to select is there but it should not
2. By the way, it worked on Magento 2.3.5

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2021-02-02 09:43
Hello @chequille 

Thank you for your report.

According to the [documentation](https://docs.magento.com/user-guide/stores/state-options.html#set-up-the-state-options) when  _Allow to Choose State if It is Optional for Country_ is set to _No_ it means that "In countries where the state field is not required, omits the State field."
For example, for the Countries like Albania, Australia, United States... the State field will still be available because _the state, province, or region is a required part of a postal address_. And for the Countries like Angola, Belgium, France, where the state, province, or region is not required, the field will be omitted. 
![Peek 2021-02-02 11-40](https://user-images.githubusercontent.com/51680745/106581627-bba46d80-654b-11eb-815f-32b7286c244c.gif)

We are closing this issue. Please feel free to comment, or create new tickets according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)

**Closed as completed by engcom-Bravo** 2021-02-02 09:43 UTC
Labels: non-issue, Issue: ready for confirmation

**Comment by chequille** [comment] 2021-02-02 21:48
@engcom-Bravo

Sorry, what you are telling me is not the truth.
As I said, in Magento 2.3.5 it is working as expected.
Let me explain a little bit more in detail.
My shop is located in Germany and here nobody cares about the so called "Bundesland". 
**It is not necessary and I do not want to have it in the checkout nor in any address form.**

WIthin Magento 2.3.5 when I set the ""Allow to Choose State if It is Optional for Country" to NO, the selection for this "Bundesland" is not there and this is what I want.
The screen shows Magento2.3.5
![grafik](https://user-images.githubusercontent.com/15807794/106666458-e91f0480-65a7-11eb-8634-8242a0224014.png)

In Magento 2.4.1. all settings are the same as they are in my 2.3.5 shop, but here the "Bundesland" is shown and this is not correct.

The screenshot from 2.4.1
![grafik](https://user-images.githubusercontent.com/15807794/106666745-4dda5f00-65a8-11eb-9ff3-cb2ae95647d0.png)

Therefore, please be so kind and rethink this issue, because it is not correct what you are telling me.

**I DO NO WANT TO SEE "BUNDESLAND" IN MY FORMS**

**Comment by engcom-Bravo** [comment] 2021-02-04 09:58
Hello @chequille 

The _State/Province_ is not required for Germany. So when the _Allow to Choose State if It is Optional for Country_ is set to _Yes_, the _State/Province_ is displayed
![yes](https://user-images.githubusercontent.com/51680745/106876008-f2ab8800-66df-11eb-8db9-bfbb36472076.png)

When the _Allow to Choose State if It is Optional for Country_ is set to _No_, the _State/Province_ is NOT displayed 
![no](https://user-images.githubusercontent.com/51680745/106876124-1078ed00-66e0-11eb-8c0c-b176510c4e78.png)

These are screenshots from Magento 2.4.1 and 2.4-develop.

**Comment by chequille** [comment] 2021-02-04 19:36
Hi, that's what I expect to have.
Unfortunately, on my site this is not the case and I am using 2.4.1
As I said, exactly same settings as in 2.3.5.
I made a cross check in 2.3.5 and dit set the value to YES and I saw, state/province is shown.

So what else could cause this behaviour? 
Maybe the settings for allowed countries does have an influence. My shop is set to Germany only.
What is your setting for this?

**Comment by chequille** [comment] 2021-02-04 21:01
Additional info:
I added one more contry in "Allowed Countries".
If I select in the checout the other country and selected immediately afterwards again German, than the State/Province disappers.

Therefore, try with following settings:
Default Country: Germany
Allowed Countries: Germany
And of course the "Allow to choose ...." to NO
This is exactly my setup and the State/Province selection is shown!!!!

**Comment by engcom-Bravo** [comment] 2021-02-05 08:54
@chequille Can you please check if Germany is not selected in _State is Required for_ on your setup?
![germany](https://user-images.githubusercontent.com/51680745/107011013-c0f9f600-679f-11eb-81fd-245da3128cb6.png)


> Therefore, try with following settings:
> Default Country: Germany
> Allowed Countries: Germany
> And of course the "Allow to choose ...." to NO
> This is exactly my setup and the State/Province selection is shown!!!!

We have rechecked with the _Default Country: Germany_, the result is the same. 
And Germany is in the list of _Allowed Countries_ by default. Actually all the Countries are selected in _Allowed Countries_ by default. Does your setup use a specific list for _Allow Countries_?

Thank you

**Comment by chequille** [comment] 2021-02-05 09:41
Hi,
In "State is Required for" Germany is not selected !!!!!!!!!!
And in Allowed Countries, as I said already **ONLY GERMANY** is selected

**Comment by engcom-Bravo** [comment] 2021-02-05 11:03
@chequille Thank you for the response. We are asking about the Allowed Countries list because of
> If I select in the checout the other country and selected immediately afterwards again German, than the State/Province disappers.

Yes, we have already rechecked this setup.
> Please give it a try. I believe, that in this case, State/Province will be shown as well in your setup.

Please, try to use the _@magento give me 2.4-develop instance_ comment. This will deploy a temporary 2.4-develop instance for you. Please check if the behaviour is reproducible.

**Comment by chequille** [comment] 2021-02-05 17:26
@magento give me 2.4-develop instance

**Comment by chequille** [comment] 2021-02-06 07:35
Hi Guys,
meanwhile, I tried on the given instance and I could not reproduce it.
But, to get exactly the same config as in my setup, I must go through the whole config section and I do not have the time for it.
For my site, I found another way to hide the region_id field in the checkout and because it is a not required field this is OK.

I still wonder, why it is working in my 2.3.5-p1 setup.
The only thing I can imagine is, that for some reason the javascript which is setting the region_id to "display:none" is not working correct in my 2.4.1 setup.
Can you tell me which script is doing this, so I could have a look into it?

**Comment by JMLucas96** [comment] 2022-05-11 11:33
Take care if it is problem of redis or any cache config.

**Comment by damibosrengo** [comment] 2022-12-16 11:25
Have you seen the file Magento_Directory/etc/di.xml?

```
<type name="Magento\Directory\Model\ResourceModel\Country\Collection" shared="false">
        <arguments>
            <argument name="helperData" xsi:type="object">DirectoryHelperDataProxy</argument>
            <argument name="countriesWithNotRequiredStates" xsi:type="array">
                <item name="FR" xsi:type="string">FR</item>
                <item name="DE" xsi:type="string">DE</item>
                <item name="AT" xsi:type="string">AT</item>
                <item name="FI" xsi:type="string">FI</item>
                <item name="BE" xsi:type="string">BE</item>
            </argument>
        </arguments>
    </type>
```

Here is your problem, I think....
