### ISSUE TITLE
Tax Class is not reflecting on Product details pages under the Tax Class Dropdown.

### ISSUE THREAD

**Issue by webgility-amazonapi** [magento/magento2#30873] opened 2020-11-11 05:12 UTC
### Preconditions (*)

1.Magento version 2.3.5

### Steps to reproduce (*)

1.Configure the postman
2.Make an API call using the below details
API : rest/V1/products/Tax Class Test123
Method : PUT
Request : {"product":{"sku": "Tax Class Test123","name": "Tax Class Test123","attribute_set_id": 9,"price": 24.44,
    "status": 1,"visibility": 4,"weight": 0.0,"media_gallery_entries": null,"extension_attributes": {"stock_item": {
        "qty": 4.0,"is_in_stock": true},"website_ids": [1],"category_links": null},"custom_attributes": [{"attribute_code": "description",
        "value": "sadh"},{"attribute_code": "tax_class_id","value": "7"}]}}

### Expected result (*)

1. Tax Class should be applied and reflected on product on Products Grid and Product details pages under the Tax Class Dropdown.

### Actual result (*)

1. Tax Class is not reflecting on Product details pages under the Tax Class Dropdown.
2. ![image-20201106-080122](https://user-images.githubusercontent.com/54638813/98771477-8d126d00-240a-11eb-8c71-8ad713c4b8c6.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Alfa** [comment] 2020-11-11 12:22
Hi @webgility-amazonapi .

Unfortunately, we are not able to reproduce the issue on fresh 2.4-develop. 
It seems that the problem has already been solved.

**Manual testing scenario:**

1. Create _**Tax Class Test123**_ product;
![2020-11-11_14-08](https://user-images.githubusercontent.com/51679138/98810110-5ac33880-2427-11eb-939d-eb397f4889fc.png)

2. Create a new tax class as in [devdocs
](https://docs.magento.com/user-guide/tax/tax-class-new.html) (**_test_** for example)

3. Make an API call using the below details

**PUT**  `rest/V1/products`

sku: **Tax Class Test123**

```graphql
{
"product":{
"sku": "Tax Class Test123",
"name": "Tax Class Test123",
"attribute_set_id": 4,
"price": 24.44,
"status": 1,
"visibility": 4,
"weight": 0.0,
"media_gallery_entries": null,
"extension_attributes":{
"stock_item":
 {"qty": 4.0,
"is_in_stock": true
},
"website_ids": [1],
"category_links": null
},
"custom_attributes": [{
"attribute_code": "description",
"value": "sadh"
},
{"attribute_code": "tax_class_id",
"value": "4"
}]
}
}
```

**Actual Result:** :heavy_check_mark: Tax Class is applied and reflected on product on Products Grid and Product details pages under the Tax Class Dropdown.

So, we have to close it.
Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.

**Closed as completed by engcom-Alfa** 2020-11-11 12:22 UTC
Labels: Issue: ready for confirmation, not-confirmed, Reported on 2.3.5

**Comment by webgility-amazonapi** [comment] 2020-11-12 05:33
So can you let us know what we are doing wrong?

**Comment by webgility-amazonapi** [comment] 2020-12-02 10:26
Hello Magento Support, 

When we are selecting tax_class_id scope as 'Global' its working fine but if we are taking it as 'Website' its not working as expected. 

Please have a look on screenshot. 
![Screenshot 2020-12-02 155636](https://user-images.githubusercontent.com/54638813/100860804-fe4bba00-34b6-11eb-9642-8cf80d6ac639.jpg)
