### ISSUE TITLE
coupon_code field is empty in sales_order table (Magento 2.4.3-p2)

### ISSUE THREAD

**Issue by MagePsycho** [magento/magento2#36603] opened 2022-12-14 07:50 UTC
### Preconditions and environment

- Magento 2.4.3-p2
(We migrated Magento from `2.1.x` to `2.4.3-p2`)

### Steps to reproduce

1. Place an order with any coupon code
2. Order is placed but the `coupon_code` field is coming empty (though quote > coupon_code has value) 

### Expected result

The quote's `coupon_code` should be transferred to sales_order's `coupon_code`

### Actual result

coupon_code field is empty in sales_order table. 

### Additional information

But sales_order's `coupon_description` has the value.

Though I FIXED using a simple hack with `sales_model_service_quote_submit_before` event
```
$order = $observer->getEvent()->getOrder();
$quote = $observer->getEvent()->getQuote();
if (!$order->getCouponCode() && $quote->getCouponCode()) {
    $order->setCouponCode($quote->getCouponCode());
}
```

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-November** [comment] 2022-12-19 13:07
Hi @MagePsycho ,

Thank you for reporting and collaboration. Verified the issue with below steps performed but the issue is not reproducible on both Magento 2.4.3-p2 instance and 2.4-develop instance.
**Steps performed:**
1. Installed Magento 2.1.7 version with PHP Active version 7.0.2
2. Placed Orders with coupon code / discount applied
3. Upgraded to Magento 2.4.3-P2 version with active PHP version 7.4 as per [upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/implementation/perform-upgrade.html)
4. Verified 'coupon_code' in sales_order table.
**No issue:** Values displayed as expected. 
![image](https://user-images.githubusercontent.com/60198231/208432614-ffa58dcc-f00c-4782-b41f-1639398f3eb3.png)
Kindly recheck the issue on Magento 2.4-develop instance  / latest Magento instance as per Magento system [requiremements](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html) and provide missing steps / 3rd party extensions enabled if the issue is still reproducible.
Thank you.

**Comment by engcom-November** [comment] 2023-01-02 05:54
Hi @MagePsycho ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.

**Closed as completed by engcom-November** 2023-01-02 05:54 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update, Reported on 2.4.3-p2
