### ISSUE TITLE
Trigger::addStatement should not auto-add semicolon to the end of statement

### ISSUE THREAD

**Issue by ghost** [magento/magento2#5220] opened 2016-06-24 10:56 UTC
## Steps to reproduce

```
$trigger = $triggerFactory->create();
$trigger->setTable('some_table');
$trigger->setTime(Trigger::TIME_BEFORE);
$trigger->setEvent(Trigger::EVENT_INSERT);
$trigger->setName('some_trigger');
$trigger->addStatement('/* dummy */');
$setup->getConnection()->createTrigger($trigger);
```
## Expected result

Trigger is successfully created.
## Actual result

`[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ';END' at line 13`
## More info

Magento generates following query:

```
CREATE TRIGGER some_trigger BEFORE INSERT ON some_table FOR EACH ROW
  BEGIN
  /* dummy */;
  END
```

So, ::addStatement should use some heuristics for auto-adding semicolon after each statement, or doesn't add it at all.

**Comment by andimov** [comment] 2016-06-24 13:35
@adlogic 
Thank you for reporting this issue!
Please, provide the used version. If the problem is actual for a specific tag, please, specify it and be sure that the latest update was used.

**Comment by ghost** [comment] 2016-06-24 13:46
The problem exists in all M2 versions, including latest dev snapshot.

**Comment by andimov** [comment] 2016-06-24 16:31
@adlogic 
Which MySQL engine and version do you use?

**Comment by ghost** [comment] 2016-06-25 09:23
`mysqld  Ver 5.6.31 for Linux on x86_64 (MySQL Community Server (GPL))`

**Comment by piotrekkaminski** [comment] 2016-08-25 17:42
Thank you for your submission.

We recently made some changes to the way we process GitHub submissions to more quickly identify and respond to core code issues.

Feature Requests and Improvements should now be submitted to the new [Magento 2 Feature Requests and Improvements](https://community.magento.com/t5/Magento-2-Feature-Requests-and/idb-p/feature-requests) forum (see details [here](https://community.magento.com/t5/News-Announcements/Improvements-to-GitHub-Management/m-p/44572#M96)).

We are closing this GitHub ticket and have moved your request to the new [forum](https://community.magento.com/t5/Magento-2-Feature-Requests-and/Trigger-addStatement-should-not-auto-add-semicolon-to-the-end-of/idi-p/45069).

**Closed as completed by piotrekkaminski** 2016-08-25 17:42 UTC
Labels: improvement
