### ISSUE TITLE
Can't Create shipment for ordered qty less than 1

### ISSUE THREAD

**Issue by jancyceymox** [magento/magento2#36052] opened 2022-08-30 05:13 UTC
### Preconditions and environment

- Magento version: Magento Open Source Ver. 2.4.4-p1, Magento Open Source Ver. 2.4.5
- Create an Order with Qty less than 1. Then create the invoice and then create the shipment. The items will not be displayed in the "Items to Ship"  section.

![image](https://user-images.githubusercontent.com/67380078/187354091-04fce8a6-59db-4b34-94ff-33c53420d17e.png)

I have fixed this by changing the below code in the file **Magento\Sales\Model\Order\ShipmentFactory.php**

```
 private function validateItem(\Magento\Sales\Model\Order\Item $orderItem, array $items)
    {
        if (!$this->canShipItem($orderItem, $items)) {
            return false;
        }

        // Remove from shipment items without qty or with qty=0
        if (!$orderItem->isDummy(true)
            && (!isset($items[$orderItem->getId()]) || (int) $items[$orderItem->getId()] <= 0)
        ) {
            return false;
        }
        return true;
    }
```

Changed the **(int) $items[$orderItem->getId()]** to  **$items[$orderItem->getId()]**

### Steps to reproduce

Step 1: Create an order with an item with decimal qty and the qty must be less than 1. (Eg:0.5)
Step 2: Create invoice
Step 3: Create Shipment 

### Expected result

The items are to be displayed in the "Items to Ship" section.

### Actual result

The items are not displayed in the "Items to Ship" section.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2022-08-30 16:42
Hi @jancyceymox ,
Thank you for raising an issue , we tried to replicate the issue on magento 2.4.5 but we are unable to add less than 1 , i.e 0.5 product to cart whereas tried with 1.5 we are able to add an item to cart and place an order successfully.
We are able to invoice for 0.5 ( partial ) of product quantity.

Hence , request to review the pre-condition and steps provided.

<img width="1366" alt="Screenshot 2022-08-30 at 10 02 04 PM" src="https://user-images.githubusercontent.com/51681379/187492599-045c0186-768d-412c-8c63-832a7883eeee.png">

<img width="1411" alt="Screenshot 2022-08-30 at 10 11 14 PM" src="https://user-images.githubusercontent.com/51681379/187492927-029cb5b0-e8f7-4a9a-a126-ddae508af84b.png">


<img width="1346" alt="Screenshot 2022-08-30 at 10 07 44 PM" src="https://user-images.githubusercontent.com/51681379/187492696-662dc7c5-8e5f-4f9c-ab07-67d20893e8e9.png">

**Comment by jancyceymox** [comment] 2022-08-30 16:52
@engcom-Delta 
Here is the product configuration
![image](https://user-images.githubusercontent.com/67380078/187493798-e0efabd0-795e-4ffa-821a-86fd6d5fb0e8.png)

Added item to the cart
![image](https://user-images.githubusercontent.com/67380078/187494003-1498e2d7-9e1f-4ad1-92ee-cb477707a197.png)

Created the order
![image](https://user-images.githubusercontent.com/67380078/187494190-83fdf93c-2afb-4ea9-89dc-1ce8788ce09e.png)

Invoiced the order
![image](https://user-images.githubusercontent.com/67380078/187494311-a5901ef4-41da-4e9f-b498-4a74028032a0.png)

Shipment Creation (error screen)
![image](https://user-images.githubusercontent.com/67380078/187494458-b62e1155-56f4-4003-af87-1a5bf0f588ae.png)

After the fix, it is working fine. 
![image](https://user-images.githubusercontent.com/67380078/187494733-e537b4dc-3ab5-4c65-91e0-2ba0c3d4f034.png)

![image](https://user-images.githubusercontent.com/67380078/187494831-6761d772-2816-42bc-a0a2-bcc483d48438.png)

**Comment by gwharton** [comment] 2022-09-11 16:44
Duplicate of #35971

**Comment by engcom-Lima** [comment] 2022-09-14 08:14
Hi @jancyceymox ,

This issue is duplicate of this issue -https://github.com/magento/magento2/issues/35971.
Hence,closing this issue.

Thanks

**Closed as completed by engcom-Lima** 2022-09-14 08:14 UTC
Labels: duplicate, Priority: P1, Progress: done, Issue: needs update, Reported on 2.4.5

**Comment by Jilco** [comment] 2022-12-31 21:12
Yes works, but state of the order not changes to "complete" it stays "processing". Is there a complete sollution that also changes the state after shipping the complete 0.5 qty?
