### ISSUE TITLE
Specific Country on Block Estimate Shipping and Tax not working

### ISSUE THREAD

**Issue by ivansuharyadi** [magento/magento2#3502] opened 2016-02-22 03:13 UTC
i'm has been set specific country to Ireland and UK, on page checkout its working the dropdown only display Ireland and UK.

But on page checkout cart, all country displayed on dropdown country ?

**Comment by ishakhsuvarov** [comment] 2016-02-22 15:19
@ivansuharyadi We could not reproduce the described issue with the latest `develop` branch, please provide more information regarding your setup (detailed steps to reproduce, Magento version, etc).

**Comment by ivansuharyadi** [comment] 2016-02-23 01:37
Im using Magento 2.0.1, everything is ok, just this one problem only happens,

On page checkout cart : 

![untitled-1](https://cloud.githubusercontent.com/assets/4571528/13238724/a37f6c16-da07-11e5-940a-1a4ac85c0536.png)

On page checkout index: 

![untitled-2](https://cloud.githubusercontent.com/assets/4571528/13238725/aa8c3aca-da07-11e5-8ab5-b9134d54b4fa.png)

How to set dropdown country on page checkout cart like image above ?

Thanks

**Comment by ishakhsuvarov** [comment] 2016-02-23 11:08
@ivansuharyadi Thank you, the information you provided was really helpful.
Indeed, this issue exists in `2.0` branch but already fixed in `develop`. The fix is going to be available as a part of the next release. Meanwhile you may use [commit](https://github.com/magento/magento2/commit/7b1ac83b92228803884f04cb74505b776bef59cd) `7b1ac83b92228803884f04cb74505b776bef59cd` as a hotfix, if you wish.

**Comment by ivansuharyadi** [comment] 2016-02-23 12:57
@ishakhsuvarov Awesome!! Thank you....

**Comment by ishakhsuvarov** [comment] 2016-02-23 13:05
@ivansuharyadi Closing this ticket for now. Please feel free to reopen if you have additional questions.

**Closed as completed by ishakhsuvarov** 2016-02-23 13:05 UTC
Labels: Issue: Ready for Work, bug report
