### ISSUE TITLE
Double ui component with product_form.xml

### ISSUE THREAD

**Issue by Naberdz** [magento/magento2#32674] opened 2021-04-06 13:11 UTC
### Preconditions (*)

1.  Magento 2.4.2
2. PHP 7.4

### Steps to reproduce (*)

1. Create custom attribute
```
        /** @var EavSetup $eavSetup */
        $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'label_color',
            [
                'type' => 'varchar',
                'label' => 'Label color',
                'input' => 'colorPicker',
                'source' => '',
                'frontend' => '',
                'required' => false,
                'backend' => '',
                'default' => null,
                'user_defined' => true,
                'unique' => false,
                'group' => 'General',
            ]
        );
```
2. Create ui element for this attribute
```
        <field name="label_color" sortOrder="20" formElement="colorPicker">
            <settings>
                <dataType>text</dataType>
                <componentType>colorPicker</componentType>
                <label translate="true">Label color</label>
                <dataScope>label_color</dataScope>
                <validation>
                    <rule name="required-entry" xsi:type="boolean">false</rule>
                </validation>
            </settings>
            <formElements>
                <colorPicker>
                    <settings>
                        <colorPickerMode>full</colorPickerMode>
                        <colorFormat>hex</colorFormat>
                    </settings>
                </colorPicker>
            </formElements>
        </field>
```

### Expected result (*)

1. ui element should overwrite existing element with new functionality
2.

### Actual result (*)

1. Have double component
2. If i change one, another also changes value
<img width="361" alt="Schermafbeelding 2021-04-06 om 15 10 47" src="https://user-images.githubusercontent.com/37579149/113715876-46d7e600-96ea-11eb-89b1-9a52c3fbfac8.png">

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Charlie** [comment] 2021-06-23 14:09
Thanks @Naberdz for giving the steps to reproduce the issue. I am trying to reproduce it but by looking at the steps I need some more details on below points

1.  Are you adding 2 'Label color' formElements into your form? In which one with <colorFormat>hex</colorFormat> and without hex?
2. Are you adding one custom attribute too?

It will be really helpful if I will get the information on above points to proceed further.

**Comment by Naberdz** [comment] 2021-06-24 06:42
@engcom-Charlie 
i'm adding it as hex.
default one is RGB.

made a module 
Setup/Patch/Data/AttributelabelColor.php
```
public function apply()
    {
        $this->moduleDataSetup->getConnection()->startSetup();
        /** @var EavSetup $eavSetup */
        $eavSetup = $this->eavSetupFactory->create(['setup' => $this->moduleDataSetup]);
        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'label_color',
            [
                'type' => 'varchar',
                'label' => 'Label Background',
                'input' => 'colorPicker',
                'source' => '',
                'frontend' => '',
                'required' => false,
                'backend' => '',
                'default' => null,
                'user_defined' => true,
                'unique' => false,
                'group' => 'General',
            ]
        );

        $this->moduleDataSetup->getConnection()->endSetup();
    }
```
view/adminhtml/ui-component/product-form.xml
```
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
	<fieldset name="label">
		<field name="label_color" sortOrder="20" formElement="colorPicker">
			<settings>
				<dataType>text</dataType>
				<componentType>colorPicker</componentType>
				<label translate="true">Label color</label>
				<dataScope>label_color</dataScope>
				<validation>
					<rule name="required-entry" xsi:type="boolean">false</rule>
				</validation>
			</settings>
			<formElements>
                <colorPicker>
                    <settings>
                        <colorPickerMode>full</colorPickerMode>
                        <colorFormat>hex</colorFormat>
                    </settings>
                </colorPicker>
            </formElements>
		</field>
	</fieldset>
</form>
```
xml form should override my element appearance.

**Comment by engcom-Hotel** [comment] 2021-07-16 10:55
Hello @Naberdz,

We have tried to reproduce the issue in Magento 2.4-develop. But unable to reproduce the same. We have tried to overwrite "Stock Status" from the "Advanced Inventory" section and added one more option in the dropdown and it is added successfully. 

And only one form element of "Stock Status" is showing for us. Please find below screenshot for reference:

<img width="610" alt="Screenshot 2021-07-16 at 4 20 15 PM" src="https://user-images.githubusercontent.com/51681618/125937089-f37af91c-249e-4569-99fe-22730ffaf624.png">

Please let us know if we missed anything in order to reproduce the issue.

Thanks

**Comment by engcom-Hotel** [comment] 2021-08-04 07:24
Dear @Naberdz,

We have noticed that this issue has not been updated for a period of more than 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

Regards

**Closed as completed by engcom-Hotel** 2021-08-04 07:24 UTC
Labels: Issue:  Cannot Reproduce, Triage: Dev.Experience, Issue: needs update, Reported on 2.4.2
