### ISSUE TITLE
Magento 2.3.2 version

### ISSUE THREAD

**Issue by mayank-zestard** [magento/magento2#38417] opened 2024-02-05 08:28 UTC
### Summary

Both front-end and admin wont load JS files are not created in pub/static directory & as one directory _requireJs (this is live server issue not local)

### Examples

Both the front-end and admin wont load JS files are not created in pub/static directory and as one directory (this is live server issue not local)

Uncaught ReferenceError: config is not defined

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Bravo** [comment] 2024-02-05 11:49
Hi @mayank-zestard,

Thank you for reporting and collaboration.

Could you please provide steps to reproduce,expected results and actual results if possible please provide screenshots to proceed further.

Please provide the use case in which you are facing

**Comment by mayank-zestard** [comment] 2024-02-05 12:46
d

**Comment by engcom-Bravo** [comment] 2024-02-06 08:32
Hi @mayank-zestard,

Thanks for your update.

Please refer this https://magento.stackexchange.com/questions/130635/uncaught-referenceerror-config-is-not-defined-magento-2  it may resolves your issue.

Kindly provide steps to reproduce in which case you are facing the issue in order to proceed further.

Thanks.

**Comment by engcom-Dash** [comment] 2024-02-20 06:53
Hi @mayank-zestard 

We have noticed that this issue has not been updated since long time. Hence we assume that this issue is fixed now, so we are closing it. Please feel to raise a fresh ticket or reopen this ticket if you need more assistance on this.

Thanks

**Closed as completed by engcom-Dash** 2024-02-20 06:53 UTC
Labels: Issue: needs update, Reported on 2.3.2
