### ISSUE TITLE
Roundung issue with catalog price rule

### ISSUE THREAD

**Issue by Seb33300** [magento/magento2#26725] opened 2020-02-06 10:14 UTC
### Preconditions (*)

I am currently using Magento ver. 2.3.2-p2

### Steps to reproduce (*)

1. Create a new product with price `41.67 €`
2. Apply 20% VAT on this product => final price is now `50.00 €`
3. Create a catalog price rule to apply a 20% discount on this product => discounted price displayed on the shop is `40.01 €`

### Expected result (*)

The discounted price should be `40.00 €`.

```
41.67 * 1.2 = 50.004
50.004 * 0.8 = 40.0032
Rounded value = 40.00
```

### Actual result (*)

The discounted price is `40.01 €`.
How can this be possible?

**Comment by Seb33300** [comment] 2020-02-06 11:24
I just found a workaround: if I edit the product and set the price to `41.667 €`.
After saving, magneto will display `41.67 €` but `41.667 €` was really saved and the rounding issue doesn't appear anymore on the frontoffice.

Any way to configure Magento to display prices with 3 decimals in backoffice only?

**Comment by devchris79** [comment] 2020-02-06 12:17
I think this is related to #26599. There is a fix and pull request in there.

**Comment by engcom-Alfa** [comment] 2020-02-07 11:38
Duplicate of #26599

**Closed as completed by engcom-Alfa** 2020-02-07 11:38 UTC
Labels: Issue: Format is valid, Reported on 2.3.2-p2

**Comment by Seb33300** [comment] 2020-02-07 11:44
The other issue is related to shipping.

This issue is not related to shipping.

**Comment by devchris79** [comment] 2020-02-07 12:56
They are the same issue, the taxation functions are the source of the issue. You have seen this in the item taxation and the other post showed the issue in shipping.
