### ISSUE TITLE
Braintree payment credit card 3d secure billing surname special characters

### ISSUE THREAD

**Issue by hugoruivo** [magento/magento2#25483] opened 2019-11-06 07:59 UTC
### Preconditions (*)

1. Magento Version 2.3.3
2. Braintree Credit card setup as payment method with 3D Secure Verification enabled

### Steps to reproduce (*)

1. Add a product to the cart
2. Go to checkout
3. In the shipping address set the First Name with special characters ( Tést )
4. In the shipping address set the Last Name with special characters ( Tést )
5. In the payment method select Credit Card
6. Ensure that the "My billing and shipping address are the same" is checked
7. Insert card details
8. Click Place Order
9. Nothing happens

### Expected result (*)

1. Open braintree payment process

### Actual result (*)

1. An error is printed to the browser console
2. Checking the network tab of the braintree api we get the following: 
`{"error":{"message":"Billing given name format is invalid.\nBilling surname format is invalid."},"threeDSecureInfo":{"liabilityShifted":false,"liabilityShiftPossible":false}}`

**Comment by hugoruivo** [comment] 2019-11-06 08:00
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment] 2019-11-06 08:00
Hi @hugoruivo. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment] 2019-11-06 08:00
Hi @hugoruivo, here is your [Magento instance](https://i-25483-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25483-2-3-develop.instances.magento-community.engineering/admin](https://i-25483-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by hugoruivo** [comment] 2019-11-06 08:20
I'm able to replicate this issue @ https://i-25483-2-3-develop.instances.magento-community.engineering/admin

**Comment by ajijshekh123** [comment] 2019-11-06 09:32
I have verified this issue in your First and last name value. But I can't reproduce this issue.
I am using the Braintree Sandbox Payment configuration in the admin section on Magento 2.3 instance.
**Please see the attached video:**

![BraintreePayment_Issue](https://user-images.githubusercontent.com/24711761/68286013-58a4fc00-00a6-11ea-87f3-729b6999caa7.gif)

@hugoruivo - Can you please send me the video or any other helpful details to reproduce this issue?
I think some issues with your Braintree configuration.
If you have not found again this issue let me know so I will close this issue.

Thanks.

**Comment by hugoruivo** [comment] 2019-11-06 09:50
@ajijshekh123 You need to have 3D Secure Verification enabled on the braintree configuration.
![Configuration___Settings___Stores___Magento_Admin](https://user-images.githubusercontent.com/6104554/68287533-c5a29c80-007a-11ea-94d3-60a3043e3b99.png)

**Comment by ajijshekh123** [comment] 2019-11-06 10:00
Okay @hugoruivo

**Comment by ajijshekh123** [comment] 2019-11-06 10:20
@hugoruivo - I have reproduced this issue when I have enabled the 3D Secure verification on Braintree payment configuration.
Thanks for the update.
**See attached the video:**

![BraintreePayment_Issue_Reproduced](https://user-images.githubusercontent.com/24711761/68289903-07e4d180-00ad-11ea-9c49-8c658aa19a29.gif)

**Comment by magento-engcom-team** [comment] 2019-11-06 10:20
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-22857` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by bst2002git** [comment] 2019-11-14 15:54
Hello i can reproduce this Error using 3DS enabled and this name in german (field with non-ascii ) "Hr. Ronny Schönberger".
If you replace (for debugging) the umlaut "ö" with "oe" it works.
Using Magento 2.3.3 (braintreeLibraryVersion | braintree/web/3.48.0)

JSON-Request sent from Magento:
URL: https://api.sandbox.braintreegateway.com/merchants/xxxx/client_api/v1/payment_methods/tokenXXXX/three_d_secure/lookup
POST-Param:
{"amount":18.75,"additionalInfo":{"shippingGivenName":"Ronny","shippingSurname":"Schönberger","shippingPhone":"+430316 123456789","billingLine1":"Giga-Gasse 61","billingCity":"Maltschach","billingState":null,"billingPostalCode":"9820","billingCountryCode":"AT","billingPhoneNumber":"+430316 123456789","billingGivenName":"Ronny","billingSurname":"Schönberger","shippingLine1":"Giga-Gasse 61","shippingCity":"Maltschach","shippingState":null,"shippingPostalCode":"9820","shippingCountryCode":"AT"},"dfReferenceId":"0_15fe3003-53bb-4767-bd75-781231c2bdc3","clientMetadata":{"sdkVersion":"web/3.48.0","requestedThreeDSecureVersion":"2","cardinalDeviceDataCollectionTimeElapsed":344},"authorizationFingerprint":"...","braintreeLibraryVersion":"braintree/web/3.48.0","_meta":{"merchantAppId":"develshop.fangocur.at","platform":"web","sdkVersion":"3.48.0","source":"client","integration":"custom","integrationType":"custom","sessionId":"a7816h40-92f1-4263-bbfa-4217fgf8fjfec"}}

Response:
{"error":{"message":"Billing surname format is invalid."},"threeDSecureInfo":{"liabilityShifted":false,"liabilityShiftPossible":false}}

**Comment by franckgarnier21** [comment] 2020-05-01 09:28
Hello,

Any update or information where we can apply an hotfix ?

Thanks,

**Comment by hugoruivo** [comment] 2020-05-01 11:01
Hi,

I ended up doing a "dirty" quick fix for this.

By doing an override of: "Magento_Braintree/js/view/payment/3d-secure"

Then removing Special characters on the billingAddress givenName and surname from the validate function ( when I say removing it means changing the special char to the ASCII equivalent ex: ó -> o ).

**Comment by bst2002git** [comment] 2020-06-23 08:24
Hello this is the answer i get from Braintree-Support:

The error you are receiving, **94350 - Billing surname format is invalid​**, is generally thrown when diacritics are included. ​The accepted characters to pass in these parameters are ASCII printable characters. This limitation is set by our MPI provider Cardinal Commerce as it is an EMVco standard.

Thus far, there are two solutions:

1. You'd need to convert any non-ASCII characters - the issue here is that there aren't always direct matches from **ñ** to **n**​ so you could accidentally make mismatches between supplied names similar to your example with **æ**​ and changing it to **ae​.**

2. You could add a check on your client for any non-ASCII characters and inform the customer thusly. This way, it's in the customer's control to change the letters.

**Comment by bst2002git** [comment] 2020-07-01 10:05
Hello, my be it is better to provide an Input-Field for Credit Card-Holder Name (see Example Image) 

![CC_name_input_field](https://user-images.githubusercontent.com/10232785/86231582-12e7f700-bb93-11ea-9dee-35fa50ecf6ef.jpg)

**Comment by JoaoFerreiraEla** [comment] 2020-11-25 12:37
> 3d-secure

I'm facing the same issue, can you show me how you achieved this please?

Thanks in advance !

**Closed as completed** 2024-05-28 14:28 UTC
Labels: Issue: Ready for Work, Component: Sales, Issue: Clear Description, Issue: Confirmed, Reproduced on 2.3.x, Issue: Format is valid, Component: Braintree, Priority: P2, Severity: S2, Progress: done, CD, Area: Payments
