### ISSUE TITLE
 Undefined array key "column" in Declaration/Schema/WhitelistGenerator.php

### ISSUE THREAD

**Issue by ghost** [magento/magento2#38638] opened 2024-04-19 08:42 UTC
### Preconditions and environment

- Magento 2.4.6 EE

### Steps to reproduce

just run  bin/magento setup:db-declaration:generate-whitelist

### Expected result

Generated without errors

### Actual result

Warning: Undefined array key "column" in /var/www/html/vendor/magento/module-developer/Model/Setup/Declaration/Schema/WhitelistGenerator.php on line 197

### Additional information

Look at vendor/magento/module-catalog-staging/etc/db_schema.xml:33 
There we have <index referenceId="CATALOG_CATEGORY_ENTITY_DATETIME_ENTITY_ID" disabled="1"/> 
without <column name="<any_name>"/>

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2024-04-19 10:26
Hi @AlekseiMageworx 

Thanks for reporting and collaboration.

Verified the issue on magento 2.4 dev instance but the issue is not reproducible.

Generated without errors.

Please refer the attached screenshots. Let us know if we missed anything.

<img width="1440" alt="38638-1" src="https://github.com/magento/magento2/assets/60198592/57aa31a3-134e-49cb-900e-8ccdb6eb4d9c">

**Comment by AlekseiMageworx** [comment] 2024-04-19 11:05
Thanks for such a quick reply, maybe the problem is in the php settings or php version
I have PHP_VERSION=8.1

Also see the screenshots please, maybe it can help you out
![image](https://github.com/magento/magento2/assets/154973120/74f32e45-5b0a-449a-bada-f3c3541a7261)

[image](https://github.com/magento/magento2/assets/154973120/6bb2d189-fffc-48ed-8f61-b19ba48887e4)

**Comment by AlekseiMageworx** [comment] 2024-04-19 11:06
I checked version 2.4.7 
This problem has been solved there, sorry, I guess we can close this issue.
https://github.com/magento/magento2/blob/fcebd3a4ad2a6863af2e2092f5e548cbd81cb0f8/app/code/Magento/Developer/Model/Setup/Declaration/Schema/WhitelistGenerator.php#L197

**Closed as completed by AlekseiMageworx** 2024-04-19 11:06 UTC
Labels: Issue: needs update, Adobe Commerce, Reported on 2.4.6
