### ISSUE TITLE
Seem reindexing is Flusing magento page cache 

### ISSUE THREAD

**Issue by ia-gaurav** [magento/magento2#38705] opened 2024-05-07 23:06 UTC
### Preconditions and environment

We are using Redis for cache and page cache , after reindexing redis seems flushing page cache in redis

### Steps to reproduce

1: wait for redis page cache size to grow 
2: Key in page_cahe of redis is around 20 k
3: we did reindexing on magento php bin/magento index:reindex 
4: Keys in page_cache went down from 20 k to around 1.5k

### Expected result

Reindexing should not flush page_cache in redis

### Actual result

Page_cache in redis is flushed with number of keys in page_cache database of redis goes down

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Delta** [comment] 2024-05-14 13:23
Hi @ia-gaurav ,

Verified the issue on 2.4-develop and we see there is a decrement in the cache keys but we think it is as intended, as it is starting afresh.

Steps to reproduce:-

1: wait for redis page cache size to grow
2: Verify Key in page_cache of redis 
3: Perform reindex on magento php bin/magento index:reindex
4: Keys in page_cache went down 

We want know which keys shouldn't be deleted or cleared as particular, so that it will be easy to debug.

Please refer the attached screenshots

redis cache before reindexing

<img width="805" alt="Screenshot 2024-05-14 at 6 18 07 PM" src="https://github.com/magento/magento2/assets/51681379/480f5b58-df1a-4599-8883-bbcc5f6c0d60">

<img width="1093" alt="Screenshot 2024-05-14 at 6 25 04 PM" src="https://github.com/magento/magento2/assets/51681379/5ac7fbac-9553-4bb1-8836-a149381f7eaf">

<img width="1323" alt="Screenshot 2024-05-14 at 6 25 16 PM" src="https://github.com/magento/magento2/assets/51681379/23b6d5d4-5a07-4e05-a40f-4b21eb7c06fa">

perform reindexing
<img width="683" alt="Screenshot 2024-05-14 at 6 41 47 PM" src="https://github.com/magento/magento2/assets/51681379/f43e9466-068e-4bde-af28-2b652c3a76b2">

redis cache after reindexing

<img width="803" alt="Screenshot 2024-05-14 at 6 29 22 PM" src="https://github.com/magento/magento2/assets/51681379/1d2178ff-87e1-4467-bd75-60835b18b54f">

<img width="1257" alt="Screenshot 2024-05-14 at 6 30 14 PM" src="https://github.com/magento/magento2/assets/51681379/cec82532-13a5-406a-bd3a-1eaee179513f">

**Comment by engcom-Delta** [comment] 2024-05-21 06:59
Hi @ia-gaurav ,

Waiting for your reply on this issue to move further.

Thanks,

**Comment by ia-gaurav** [comment] 2024-05-22 13:52
yes - we should look for way to clear specific categroy or detail page cache instead of full cache flush,

Also for product details page is there way to ignore utm and show cached data

**Comment by hostep** [comment] 2024-05-22 17:58
> yes - we should look for way to clear specific categroy or detail page cache instead of full cache flush,

If you do a full reindex, it will go over every single product & category, so it makes sense that almost the entire cache will be emptied out. But a full reindex is something that almost never should happen on a production environment.

During normal operation, where you don't run a full reindex all the time, only products that are changed, will then cause a partial reindex and only a small amount of cache should get flushed.

> Also for product details page is there way to ignore utm and show cached data

No idea if this is possible with Redis FPC, probably not, but switching to Varnish for FPC and using the default VCL Magento ships with, should already ignore the `utm` param from the query string and don't cause double unnecessary cache entries: https://github.com/magento/magento2/blob/c89312182ef2e747b47348e9cd1f1148ba7af078/app/code/Magento/PageCache/etc/varnish6.vcl#L84-L88

**Comment by ia-gaurav** [comment] 2024-05-22 19:30
@hostep thank for you valuable information , 

1: is there way i can ignore marking query string using redis FPC
2: is there way to do reindeing for specific category ids only

**Comment by hostep** [comment] 2024-05-22 20:40
1. probably not, unless you write some custom code yourself (or find a module that has already done that)
2. yes, don't run a full reindex manually and let the system handle it for you (when indexers are set to "update by schedule" mode, and you've setup the crontab correctly to run once per minute, than the indexers will only index entities (products/categories) that were recently changed)

**Comment by ia-gaurav** [comment] 2024-05-23 03:39
@engcom-Delta @engcom-Hotel - can you please guide how to ignore marketing query string for Redis FPC also can this be added in future releases as it cause issues with high server response time

**Comment by engcom-Hotel** [comment] 2024-07-12 08:36
Hello @ia-gaurav,

Thanks for the reporting!

It seems the indexing works as expected. Hence we are closing this issue for now. 

> can you please guide how to ignore marketing query string for Redis FPC also can this be added in future releases as it cause issues with high server response time

For your above query, we will let you know whenever we get updates on the same.

**Closed as completed by engcom-Hotel** 2024-07-12 08:36 UTC
Labels: Issue: needs update, Reported on 2.4.x
