### ISSUE TITLE
Products populated with GraphQL Guest-Cart are gone when user goes to Magento Cart page

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento2#27059] opened 2020-02-27 19:31 UTC
### Steps to reproduce (*)
1. Make graphql call to add to guest-cart
2. Navigate to /checkout/cart

### Expected result (*)
1. Products in cart

### Actual result (*)
1. Cart is empty

**Comment by engcom-Bravo** [comment] 2020-03-02 08:06
Hello @Stoyvo 

Thank you for your report.

This is actually not a bug. 
If you will create an empty cart, **without** _Authorization headers_ (meaning that a Guest cart will be created)
![guest_cart](https://user-images.githubusercontent.com/51680745/75656116-f59a2f00-5c6b-11ea-82b2-15665e325585.png)

Add a product to created cart with, for example, the following mutation
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "FuLwDV477aMoq91HjoNBCcB64pEXVoDx"
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "Product2"
          }
 ...
``` 
And query the cart via the following query
```graphql
query {
  cart (cart_id: "FuLwDV477aMoq91HjoNBCcB64pEXVoDx" ) {
    items{
      id
      product{
        name
        id
      }
    }
  }
}
```

You'll see that the product is in the cart
```graphql
{
  "data": {
    "addSimpleProductsToCart": {
      "cart": {
        "items": [
          {
            "id": "3",
            "product": {
              "sku": "Product2",
              "stock_status": "IN_STOCK"
            },
            "quantity": 1
          }
        ]
      }
    }
  }
}
```
If you'll navigate to the Storefront from the web browser, you'll not be able to see the product in the cart. Because the, because this are two different Guest sessions.

We have to close this issue
If you wish to update, comment, reopen or create new ticket, please feel free to do so.

Thank you for your collaboration

**Closed as completed by engcom-Bravo** 2020-03-02 08:06 UTC
Labels: Issue: Format is not valid

**Comment by Stoyvo** [comment] 2020-03-03 01:52
@engcom-Bravo Thank you for the explanation. Can you please advise on the following:

If you browse Magento catalog in Luma theme, as a guest, and add items to the cart, this would be a guest cart and when user navigates to the cart page there are items.

How would you accomplish this in graphql? We can do this fine when the user is registered customer, however cannot do this for guest carts.

One would argue that the first example of a guest would align with graphql guest cart, where a session can be leverage the PHP session for the quote. 

Why would graphql not leverage the users session, and how do we add items to the cart via graphql for guest so they can complete purchase flow?

**Comment by Stoyvo** [comment] 2020-03-09 18:10
@engcom-Bravo If you're going to close this issue as a "non-issue", then please at least answer the questions above. I believe this issue is valid and is being closed inappropriately.
