### ISSUE TITLE
Restricted countries are not loading on Customer Addresses on Admin

### ISSUE THREAD

**Issue by popovdenis** [magento/magento2#29812] opened 2020-08-31 02:28 UTC
### Preconditions (*)

1. Magento version 2.3.3
2. PHP version is 7.2.24

### Steps to reproduce (*)

1. Navigate to Admin > Stores > Configuration > General > General
2. Open Country Options tab
3. Find Allow Countries, un-check the checkbox from Use System value and select any country, for example, Australia
4. Save changes
5. Navigate to Admin > Customers > All Customers
6. Select any existing customer (or create a new one)
7. Click on Edit link and navigate to Address tab
8. Click Add New Address
9. Make sure Countries dropdown is required field.
10. Make sure Countries dropdown has restricted countries (Australia).

### Expected result (*)

1. Restricted countries are available on Countries dropdown.

### Actual result (*)

1. Empty dropdown is available.
2. 
![Screen Shot 2020-08-31 at 12 29 29](https://user-images.githubusercontent.com/2659392/91677333-b8b0e580-eb85-11ea-9121-e5cece822f36.png)
![Screen Shot 2020-08-31 at 12 29 40](https://user-images.githubusercontent.com/2659392/91677328-b5b5f500-eb85-11ea-82f0-90a295ece494.png)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by krishprakash** [comment] 2020-08-31 05:34
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-08-31 05:34
Hi @krishprakash. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-08-31 05:36
Hi @krishprakash, here is your [Magento instance](https://i-29812-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-29812-2-4-develop.instances.magento-community.engineering/admin_84a1](https://i-29812-2-4-develop.instances.magento-community.engineering/admin_84a1)
Login: `068bced0` Password: `ea21240954a4`
Instance will be terminated in up to 3 hours.

**Comment by krishprakash** [comment] 2020-08-31 06:33
Hi @popovdenis. 
Not able to reproduce the issue on latest magento as mentioned steps below:

1. Go to system configuration-> Use system value -> Select country as only Australia
![image](https://user-images.githubusercontent.com/46617848/91688231-2e658300-eb7f-11ea-9a3a-0330239ee09c.png)
2. Clear caches from cache management
3. Admin -> Customer -> All Customer 
4. Add New Customer
![image](https://user-images.githubusercontent.com/46617848/91688281-463d0700-eb7f-11ea-9647-2c9909c3b9ce.png)

It may be fixed in latest instance
Feel free to reopen if you find in latest instance with updated steps
Thanks !!

**Closed as completed by krishprakash** 2020-08-31 06:33 UTC
Labels: Issue:  Cannot Reproduce, Issue: Format is valid, Reported on 2.3.3

**Comment by popovdenis** [comment] 2020-09-02 03:11
Hi @krishprakash ,

Thank you for your testing and reply!
It is possible to get a patch to resolve this issue on Magento 2.3.3 version? Or focus us to files where this issue is fixed?
Our project is going Live and we don't have ability to upgrade Magento to the newest version.
