### ISSUE TITLE
API not capturing invoice correctly

### ISSUE THREAD

**Issue by zsebacher-integritystl** [magento/magento2#23872] opened 2019-07-24 21:56 UTC
version: community 2.2.3

Issue: We have an integration service created for a client that will create invoices, shipment, etc. for an order through the api. 

![image](https://user-images.githubusercontent.com/48224308/61831167-a452d300-ae32-11e9-948f-289cef5a9220.png)

It creates the order just fine and also creates the invoice.

![image](https://user-images.githubusercontent.com/48224308/61831239-dd8b4300-ae32-11e9-9a9a-2b4c247cfafd.png)

If I go into the invoice however it says that it has not been captured yet. 

![image](https://user-images.githubusercontent.com/48224308/61831348-32c75480-ae33-11e9-906b-c72edfcd12d5.png)

If I then capture this invoice, and then go to create a credit memo for it. The qty will be listed at 0 and when i go to change it, it will give me an error regarding an invalid quantity to refund the item. The same thing happens if there is a shipment related to it. Notice that in the qty column for the items it will say Ordered 1 or Ordered 1 and Shipping 1, but it is not saying that it has been Invoiced, even though you can't create a credit memo without an existing invoice.. This is a core functionality of magento and should be working out of the box. 

![image](https://user-images.githubusercontent.com/48224308/61831454-7de16780-ae33-11e9-98d0-5965457d50ad.png)

![image](https://user-images.githubusercontent.com/48224308/61831567-cac53e00-ae33-11e9-805b-572af511f933.png)

**Comment by engcom-Charlie** [comment] 2019-07-25 12:42
Hi, @zsebacher-integritystl ! I can't reproduce this issue on fresh magento 2.3-develop. That problem is fixed. So i close this issue.
Thank you for contributing!

**Closed as completed by engcom-Charlie** 2019-07-25 12:42 UTC
Labels: Fixed in 2.3.x, Issue:  Cannot Reproduce, Issue: Format is not valid

**Comment by zsebacher-integritystl** [comment] 2019-07-29 13:17
Since you clearly did not read any part of this ticket, the client is not on version 2.3 they are on version 2.2.3

This needs to be reopened as it is an issue with magento 2

**Comment by engcom-Charlie** [comment] 2019-07-29 13:59
@zsebacher-integritystl i have to check it on developer branches. 
I'm sorry but i can't find a commit where that problem was fixed.
If you wont to fix that problem just update your magento to latest versions.

**Comment by zsebacher-integritystl** [comment] 2019-07-29 14:18
You can't just "update" magento to the latest version because all of the versioning was handled so poorly that it breaks other areas.
