### ISSUE TITLE
save&duplicate does not duplicate translations 

### ISSUE THREAD

**Issue by YiffyToys** [magento/magento2#35945] opened 2022-08-14 07:59 UTC
### Preconditions and environment

- Magento version 2.4.3-p3

### Steps to reproduce

1. create product with a description using the Page Builder
2. add a custom translation (store view) with the Page Builder, translating the added text, heading and button -elements
3. from the "All Store Views" view, select "Save&Duplicate product"
4. Edit the SKU and URL
5. Save
6. Change to the language (store view) that has a translation in the copied product

### Expected result

The copy has a translation that was copied from the original

### Actual result

The copy has no translation at all and uses the default texts for all Page Builder elements.

### Additional information

If you are in a store view whily using Save&Duplicate,
that store view's translation will be used for "All Store Views" in the copy.

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by engcom-Dash** [comment] 2022-08-16 09:32
@magento give me 2.4-develop instance

**Comment by YiffyToys** [comment] 2022-08-16 10:06
only Tiny Editor but not Page Editor seem to work in that Magento instance.
Drag&Drop elements doesn't work.

**Comment by engcom-Dash** [comment] 2022-08-16 11:28
Hi @YiffyToys ,

Drag and drop Elements in Magento doesn't Work.So i am not able to reproduce the issue...

Let us know if we are missing anything...

Thanks!!!

**Comment by engcom-Dash** [comment] 2022-09-02 10:19
Hi @YiffyToys ,

We have noticed that this issue has not been updated for a period of 14 Days. Hence we assume that this issue is fixed now, so we are closing it. Please raise a fresh ticket or reopen this ticket if you need more assistance on this.

**Closed as completed by engcom-Dash** 2022-09-02 10:19 UTC
Labels: Issue: needs update
