### ISSUE TITLE
[GraphQL]As a logged-in user setShippingMethodsOnCart mutation returns error on a magento backend with Guest Checkout disabled

### ISSUE THREAD

**Issue by kishormainali** [magento/magento2#34687] opened 2021-11-22 05:24 UTC
While using the Graphql api, as a logged-in user the setShippingMethodsOnCart mutation returns error on a magento 2.4.3 backend with Guest Checkout disabled

### Preconditions (*)

1. Magento version 2.4.3
2. Set Allow Guest Checkout to No on the admin page: Stores -> Configuration -> Sales -> Checkout -> Checkout options

### Steps to reproduce (*)

1. Create User
2. Log in
3. Create cart
4. Create a shipping address while logged in (ie: having the Authorization Bearer token on the headers for the graphql requests)
5. Try to call the setShippingMethodsOnCart graphql mutation with the created cart id and the available shipping methods.
like:
![Screen Shot 2021-11-22 at 11 04 33 AM](https://user-images.githubusercontent.com/33093136/142805125-77cd3e72-cba6-4546-a619-91e2bedd3f25.png)

### Expected result (*)
1. Expect the operation to be successful and return the graphql query results that we asked, for example:
![Screen Shot 2021-11-22 at 11 03 25 AM](https://user-images.githubusercontent.com/33093136/142805167-74f01b4f-fd36-4be1-8c1a-32798c9c79b4.png)

### Actual result (*)

1. It returns ""The current user cannot
perform operations on cart | "fyLXpuAErnB4XWUmIwZMd3dt2Yjwm3v2\""" "graphql-authorization" authorization error:

<img width="440" alt="Screen Shot 2021-11-22 at 11 06 07 AM" src="https://user-images.githubusercontent.com/33093136/142805229-d9584226-ab36-4b77-9dba-f400a73fc00a.png">

2. This error would be valid if i wasn't logged-in, but in this case i am, therefore its not a valid error/its a bug

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by kishor98100** [comment] 2021-11-22 06:41
@magento give me 2.4-develop instance

**Comment by kishor98100** [comment] 2021-11-22 07:06
@magento give me 2.4.3 instance

**Comment by engcom-November** [comment] 2021-11-22 15:14
Verified the issue on Magento 2.4-develop  branch but is not reproducible:
Steps performed:
Magento Admin - Stores - Configuration - Sales - Checkout - Checkout Options - Allow Guest Checkout - Set to No
Created a user
Created a cart using GraphQL
Added Product to Cart using GraphQL
Set Shipping Address using GraphQL
Set Shipping Method using GraphQL - No issue. User is able to set Shipping Method.
 
![image](https://user-images.githubusercontent.com/60198231/142886187-738ad014-ae64-41b0-895e-1c8b4d33eef1.png)
@kishor98100 , kindly recheck the issue on Magento 2.4-develop branch and provide missing steps if any if the issue is still reproducible.
Thank you

**Comment by kishor98100** [comment] 2021-11-23 03:22
@engcom-November thanks for confirmation. i found this issue was caused by push notification plugin so i'am closing this issue now.

**Closed as completed by kishor98100** 2021-11-23 03:22 UTC
Labels: Issue:  Cannot Reproduce, Issue: needs update
