### ISSUE TITLE
Thousands of records for new Customer in Shopping cart tab

### ISSUE THREAD

**Issue by trucatchtraps** [magento/magento2#28045] opened 2020-04-29 16:07 UTC
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Customers -> All Customers
2. Add New Customer
3. Fill in Required Fields
4. Save and Continue Edit
5. Shopping cart tab

### Expected result (*)

1. Zero Records since new customer

### Actual result (*)

1. Customer has thousands of records listed

Additional Information:
This appears to be linked to Confirmation Required status or logging in for the first time. Because as soon as I followed instructions in Welcome email (click link, set new password, then login) associated with email address provided in setting customer up, the records are removed and show 0 records in Customer Shopping Cart tab.

**Comment by sudheers-kensium** [comment] 2020-04-30 08:01
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment] 2020-04-30 08:01
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment] 2020-04-30 08:02
Hi @sudheers-kensium, here is your [Magento instance](https://i-28045-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28045-2-4-develop.instances.magento-community.engineering/admin_ac7a](https://i-28045-2-4-develop.instances.magento-community.engineering/admin_ac7a)
Login: `a1593ca8` Password: `a79f32f8cd79`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment] 2020-05-05 05:05
@trucatchtraps  I am not able to reproduced the issue on Magento 2.4-develop instance.

**Comment by sudheers-kensium** [comment] 2020-05-07 06:53
@trucatchtraps I am closing this issue. 
Feel free to reopen if you are reproduced this issue in Magento 2.4-develop instance.

**Closed as completed by sudheers-kensium** 2020-05-07 06:53 UTC
Labels: Issue: Format is valid, Reported on 2.3.4
